### ISSUE TITLE
Incorrect parser options used when using the `@typescript-eslint/parser` parser

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#10046]
In the `app` blueprint's `.eslintrc.js` file, the `sourceType` and `ecmaFeatures.legacyDecorators` options are not valid options for the `@typescript-eslint/parser` parser.

We also specify `sourceType` for the Node override.

Valid options can be found here:
https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#configuration

**Comment by Windvis** [comment]
What options should we add for the typescript parser? Would something like what's documented in the typescript-eslint docs be good? (https://typescript-eslint.io/docs/linting/typed-linting)

**Comment by simonihmig** [comment]
Good catch here!

> What options should we add for the typescript parser?

I guess we should add as few options as possible, so only those that are really needed. Given that the setup now is working, it just has extraneous options, we can just remove those. Means everything but `ecmaVersion`, right?
