### ISSUE TITLE
ember-cli not generating blueprints on z/OS

### ISSUE THREAD

**Issue by laijonathan** [ember-cli/ember-cli#10093]
On z/OS, there seems to be an issue where `ember generate` does not generate the necessary files.

When running the test suite on z/OS:
```
  2) Acceptance: ember generate in-addon-dummy
       dummy blueprint foo:
     Error: ENOENT: no such file or directory, open '/home/jolai/zos_fork/ember-cli/tmp/20221011-6129-psrjd9.p2bb/my-addon/blueprints/foo/index.js'
      at Object.openSync (node:fs:609:3)
      at Object.readFileSync (node:fs:474:35)
      at FileHelper.get (node_modules/chai-files/src/file-helper.js:42:26)
      at Context.<anonymous> (tests/acceptance/addon-dummy-generate-test.js:58:43)
```

I have tried testing this feature with both the CLI and by calling it programmatically. Both fail on z/OS but pass on Linux

Linux
```
$ ember new my_test
$ cd my_test
$ ember generate blueprint foo --dummy
installing blueprint
	  create blueprints/foo/index.js
$ ls blueprints/foo
index.js
$ 
```

z/OS
```
$ ember new my_test
$ cd my_test
$ ember generate blueprint foo --dummy
installing blueprint
$ ls blueprints/foo
$
```

Script.js
```
   const ember = require('../helpers/ember');
   let r2 = ember(['generate', 'blueprint', 'foo', '--dummy'])
```
Linux
```
$ node script.js
$ ls blueprints
foo
```

z/OS
```
$ node script.js
$ ls blueprints
ls: FSUM6785 File or directory "blueprints" is not found
```

Could someone point me to the code/components that generates the blueprint files?

Thanks

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 4.8.0
node: 18.9.1
v8: 10.2.154.15-node.12
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 3.0.5+quic
cldr: 41.0
icu: 71.1
tz: 2022b
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: os390 s390x
8.19.1
bash: yarn: command not found
```

**Comment by bertdeblock** [comment]
Code for the `generate` command:
https://github.com/ember-cli/ember-cli/blob/master/lib/commands/generate.js
Which is kind of the entry point for `ember generate`.

Code for the `generate-from-blueprint` task:
https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/generate-from-blueprint.js
This code looks up the correct blueprint(s) and calls `install` on it.

Code for the `blueprint` model:
https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js
Specifically, the action for writing files to disk can be found [here](https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L340-L343).

**Comment by bertdeblock** [comment]
Going to close this one for now, as we don't officially support z/OS. However, if you do find something we can help you with / fix, feel free to open a PR!

**Comment by laijonathan** [comment]
@bertdeblock The problem is with the library walkSync which ember-cli and a few of its dependencies uses.  

I have made a pull request that resolves this:
https://github.com/joliss/node-walk-sync/pull/72

**Comment by bertdeblock** [comment]
Great that you found a fix for your issue!
