### ISSUE TITLE
[DOUBT] Allow removing JS/CSS comments from third party packages included via app.import

### ISSUE THREAD

**Issue by AravinthAro** [ember-cli/ember-cli#10179]
Hi team, 
              Our app runs on `ember-cli: 3.28.4`. We're using a third-party npm package which is included in the build via `app.import`. We want to remove JS/CSS comments of this package which is added into our production build. We can't find any option to remove them in ember-cli. Is there any way to remove them?
Thanks.

**Comment by bertdeblock** [comment]
I did a quick test using a fresh v3.28 app, and using `app.import` to import `jQuery`. AFAICT, the comments are stripped away for production builds. Note that comments containing `@preserve` and `@license` are not stripped away by default.

**Comment by AravinthAro** [comment]
The third-party package is jquery-ui.
It seems the license header comment should not be removed and ember-cli is following it.
However I couldn't find any reference of code comments mentioned in any ember documents.
I'm closing this.
