### ISSUE TITLE
Cannot generate routes in a typescript project

### ISSUE THREAD

**Issue by kara-ryli** [ember-cli/ember-cli#10181]
This appears to be the same issue as #9641, however the [typed-ember/ember-cli-typescript-blueprints ](https://github.com/typed-ember/ember-cli-typescript-blueprints) project is now archived and directs to [typed-ember/ember-cli-typescript](https://github.com/typed-ember/ember-cli-typescript). I'm not sure how the latter project is related to this one.

I'm happy to open an issue on the other repo, but since I only ever interacted with ember-cli, I figured this would be the right place.

**Steps to reproduce**

```sh
npm i -g ember-cli
ember new --typescript my-app
cd my-app
ember g route my-route
```

**Expected**

Route gets generated.

**Actual**

Console output:

```sh
installing route
  create app/routes/my-route.js
  create app/templates/my-route.hbs
ENOENT: no such file or directory, open '/path/to/my-app/app/router.js'


Stack Trace and Error Report: /var/folders/3v/zckz1bk16nd8f203gj9ldtf40000gp/T/error.dump.7d8698dc3a9998b0579440019089a5ba.log
```

The root cause appears to be the `ember new --typescript` generates `app/router.ts`, but `ember g route` expects there to be an `app/router.js`.

This also doesn't work with `EMBER_TYPESCRIPT_BLUEPRINTS`:

```sh
% EMBER_TYPESCRIPT_BLUEPRINTS=true ember generate route my-route 
installing route
  create app/routes/my-route.ts
  identical app/templates/my-route.hbs
ENOENT: no such file or directory, open '/path/to/my-app/app/router.js'


Stack Trace and Error Report: /var/folders/3v/zckz1bk16nd8f203gj9ldtf40000gp/T/error.dump.9bb6669f130b29517845005d2ab07f35.log
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
% ember version --verbose && npm --version && yarn --version
ember-cli: 4.10.0
node: 16.11.1
v8: 9.4.146.19-node.13
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: darwin arm64
8.5.1
zsh: command not found: yarn
```

**Comment by bertdeblock** [comment]
The `route` blueprint comes from [ember-source](https://github.com/emberjs/ember.js). We already have [an issue](https://github.com/emberjs/ember.js/issues/20357) there to track this, and [this PR](https://github.com/emberjs/ember.js/pull/20361) should fix it.
I'll ping the maintainers to try and get it merged asap. Thanks for reporting!

**Comment by bertdeblock** [comment]
https://github.com/emberjs/ember.js/pull/20361 was merged.
