### ISSUE TITLE
 Ubuntu server 22.04 errors

### ISSUE THREAD

**Issue by says112** [ember-cli/ember-cli#10288]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
[Replace this line with the output.]
```
g ember-cli@2.9.1   nvm 
Hello, recently such errors began to appear on ubuntu 22.04

![Снимок экрана (86)](https://github.com/ember-cli/ember-cli/assets/22127398/8736bceb-2816-4c38-b9d9-3cb18df73ea7)
v0.39.2

**Comment by kategengler** [comment]
Hi! ember-cli v2.9.1 was released 7 years ago and hasn't been supported for many years. `ember-cli v5.0.0` is the latest version.

However, It looks like the command that is failing is `bower install`, not an ember-cli command.
