### ISSUE TITLE
Generating a new project on Node 14 with ember-cli 4.12 with yarn and typescript fails

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#10301]
CI failed on the lts-4-12 branch https://github.com/ember-cli/ember-cli/actions/runs/5406981956/jobs/9824464495

This exposed that generating a new project with yarn and typescript on Node 14 currently fails, due to dependencies of packages installed by ember-cli-typescript having `engines`.

Workarounds:
- Use a newer node version
- When generating the project errors, cd into the generated project and run the `yarn add` command that errored (should be printed to console), but with `--ignore-engines`. Any `yarn` command you run going forward will need `--ignore-engines`)
- Find the correct older versions of the `@types/ember*` packages to install that do not depend on the newer version of `@ember/test-helpers` that has the engines updated.

**Comment by locks** [comment]
Node 14 is EOL since May, can we assume people will be or will move to 16? 😅

**Comment by ef4** [comment]
I think it's worth skipping these tests on that version.

**Comment by bertdeblock** [comment]
Issue still relevant?

**Comment by kategengler** [comment]
This will only be relevant if we try to backport to 4.12 and are puzzled by failing test
