### ISSUE TITLE
Drop Node 16 in ember-cli 5.4

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#10384]
Node 16 was only supported through early September 2023. A newly generated ember app on the 5.4 beta already does not work on Node 16 due to a transitive dependency that has updated their engines.

**Comment by NullVoxPopuli** [comment]
dang that was fast

**Comment by Shishouille** [comment]
Forgot to put that issue in the Development section of my PR, but I think we can close it now 😄

**Comment by kategengler** [comment]
For future reference, we dropped support in line with our Node Support Policy https://github.com/ember-cli/ember-cli/blob/beta/docs/node-support.md We support LTSes of Node on the primary branch until the date that Node itself ends support for the version, meaning we do not release a version incompatible with a Node LTS until a minimum of 6 weeks after Node itself stopped supporting that version.
