### ISSUE TITLE
ember-cli@5.5.0 has security vulnerability

### ISSUE THREAD

**Issue by andreyfel** [ember-cli/ember-cli#10415]
I thought I would open the issue here as well.
https://github.com/patricklx/ember-template-tag/issues/80

**Comment by bertdeblock** [comment]
https://github.com/ember-cli/ember-cli/pull/10418 is merged and also resolved this issue.

**Comment by andreyfel** [comment]
Thanks guys! Is the plan to release it in 5.7.0? Should the issue remain open until the fix is released?
