### ISSUE TITLE
Run Prettier standalone 

### ISSUE THREAD

**Issue by jelhan** [ember-cli/ember-cli#10411]
Ember CLI blueprints run Prettier as part of the linters (ESLint, Stylelint). Prettier project explicitly recommends against doing so:

> When searching for both Prettier and your linter on the Internet you’ll probably find more related projects. These are **generally not recommended**, but can be useful in certain circumstances.
> 
> First, we have plugins that let you run Prettier as if it was a linter rule:
> 
> -    [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)
> -    [stylelint-prettier](https://github.com/prettier/stylelint-prettier)
> 
> These plugins were especially useful when Prettier was new. By running Prettier inside your linters, you didn’t have to set up any new infrastructure and you could re-use your editor integrations for the linters. But these days you can run `prettier --check`. and most editors have Prettier support.
> 
> The downsides of those plugins are:
> 
> -    You end up with a lot of red squiggly lines in your editor, which gets annoying. Prettier is supposed to make you forget about formatting – and not be in your face about it!
> -    They are slower than running Prettier directly.
> -    They’re yet one layer of indirection where things may break.
>
> https://prettier.io/docs/en/integrating-with-linters.html#notes

All those arguments seem to be valid for our use case as well. Additionally the integration of Prettier into linters has complicated the upgrade of Prettier, ESLint, Stylelint, Ember Template Lint iand related libraries n the past. For Prettier v3 many of those needed to be upgraded in a single PR due to limited sets of compatible versions.

Do we need a RFC to change how we integrate Prettier? Or do we consider it an implementation detail not requiring an RFC?

**Comment by bertdeblock** [comment]
I made this RFC issue a while ago, but closed it due to lack of time => https://github.com/emberjs/rfcs/issues/901. Sharing just in case.
I think this is a good idea as well!

**Comment by bertdeblock** [comment]
I wrote [an RFC](https://github.com/emberjs/rfcs/pull/1055) for this, so I think we can close this, and use the RFC to track discussions and progress.
