### ISSUE TITLE
You passed the '--typescript' flag but there is no TypeScript blueprint available. A JavaScript blueprint will be generated instead.

### ISSUE THREAD

**Issue by alakameljebali** [ember-cli/ember-cli#10420]
## Summary
The `--typescript` flag does not work with the `ember new` command and generates a JavaScript blueprint instead.

## Steps to reproduce
1. Run `ember new project --package-manager=pnpm --typescript --interactive`
2. Answer the prompts as follows:
  - Is this an app or an addon? App
  - Please provide the spoken/content language of your app: fr-FR
  - Which CI provider do you want to use? Ignore/Skip
3. Observe the output of the command

## Expected behavior
The command should create a new Ember app with TypeScript support and generate a TypeScript blueprint.

## Actual behavior
The command creates a new Ember app but prints the following message multiple times:

`You passed the '--typescript' flag but there is no TypeScript blueprint available. A JavaScript blueprint will be generated instead.`

The command then generates a JavaScript blueprint instead of a TypeScript blueprint.

## Environment
- Ember CLI version: 5.5.0
- Operating system: Linux Fedora 39
- Node.js Version: 20.10.0
- Package manager: pnpm

**Comment by evoactivity** [comment]
Can we make the message more friendly, maybe include the filename that outputs the warning?

```
You passed the '--typescript', we're just letting you know that ${fileInfo.outputPath} will be generated as a JavaScript file as it is run directly through node.
```

Had a new user confused with the output
https://discord.com/channels/480462759797063690/486548111221719040/1206049226480558100

**Comment by kategengler** [comment]
I think ideally we should remove the warning for the ones we expect to be javascript.

**Comment by bertdeblock** [comment]
I could be wrong, but it's probably "hard" to know which files are expected to be JavaScript without maintaining a hardcoded list? Which doesn't feel ideal. I was thinking we could just remove the warning altogether?

**Comment by kategengler** [comment]
I think that is fine, but we should ask @core-typescript -- @wagenet @gitKrystan?

**Comment by gitKrystan** [comment]
I'm in favor of removing the warning altogether.

**Comment by bertdeblock** [comment]
PR => https://github.com/ember-cli/ember-cli/pull/10450.
