### ISSUE TITLE
Environment file is not loading accurately in CircleCI

### ISSUE THREAD

**Issue by JackHowa** [ember-cli/ember-cli#10457]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.28.6 
npm: 8.15.0
```

In a circle ci test, I'm importing environment to get a flag. However, the environment variable doesn't seem to be accurate. This is working as expected locally. Any ideas what could be happening?

At the end of the `{company-name}/config/environment`, there's a log that says that `{ testFlag: true }` in CircleCI run. Upon importing that ENV in another file, that `{ testFlag: false }`.

I feel like I may be missing something where environment could be overwritten? is this possible?

All files look the same when I ssh into the box. Could it have anything to do that these flags are specifically in the env.APP folder? 

> APP can be used to pass flags or options to the app's Application instance.

https://guides.emberjs.com/v3.28.0/configuring-ember/

**Comment by NullVoxPopuli** [comment]
What's your environment.js look like, as well as which environment variables are set?

**Comment by JackHowa** [comment]
Thanks for the quick response. 

config/environment.js looks like essentially: 

```js
'use strict';

module.exports = function () {
  let ENV = {
    APP: {
      IS_TEST_ENV: false
    }
  };

  if (process.env.TEST_FLAG) {
    ENV.APP.IS_TEST_ENV = true;
  }

  console.log('output env', ENV.APP);

  //   output env {
  //   IS_TEST_ENV: true,
  // }

  return ENV;
};
```
Then, when imported into a test helper that runs prior to each qunit test the incoming value is different when logged:

```js 
import ENV from 'company/config/environment';

export default function (hooks) {
  hooks.beforeEach(function () {
    console.log(JSON.stringify(ENV.APP), 'env app');
    // {"type":"log","text":"{\"IS_TEST_ENV\":false, }}

    if (ENV.APP.IS_TEST_ENV) {
      // never gets to this
      console.log('DO SOMETHING HERE');
    }
  });
}

```

**Comment by JackHowa** [comment]
Note I can't use the environment incoming value because test, production, and development are already in use and mixed with other variables

**Comment by JackHowa** [comment]
Problem was a ember buld step that seemed to be the source of truth for the ember test's environment.

**Comment by NullVoxPopuli** [comment]
for testing the test environment, you'd probably want `import { isTesting, macroCondition } from `@embroider/macros`

```js
if (macroCondition(isTesting()) {

}
```

this way, when isTesting() is false, you don't ship test code to production :tada:
