### ISSUE TITLE
Lint dependencies are out of date.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#10466]
Updates needed:
- eslint-plugin-ember @ 12.1.1 +
- ember-template-lint @ 6.0.0 +
- eslint > 8, < 9 (not moving to v9 / flat config (yet?))

Part of this initially reported here: https://github.com/embroider-build/app-blueprint/issues/25

If folks are tired with dealing with eslint updates: https://github.com/embroider-build/app-blueprint/issues/25#issuecomment-2148244583

**Comment by NullVoxPopuli** [comment]
Solved here, just needs to be pulled in to this repo: https://github.com/ember-cli/ember-cli/issues/10467#issuecomment-2386569046

**Comment by bertdeblock** [comment]
Can be closed I think?
