### ISSUE TITLE
ember serve - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Steinweber** [ember-cli/ember-cli#10472]
`ember serve` 
results in 
`ENOENT: no such file or directory, open 'C:\C:\[...]\node_modules\@warp-drive\build-config\package.json`

```
npm install ember-cli
ember new projectname --lang en
ember serve
```

Problem persists even after reinstalling all components

---
```
ember-cli: 5.9.0
node: 20.14.0
acorn: 8.11.3
ada: 2.7.8
ares: 1.28.1
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.1.0
openssl: 3.0.13+quic
simdutf: 5.2.8
tz: 2024a
undici: 6.13.0
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.21
v8: 11.3.244.8-node.23
zlib: 1.3.0.1-motley-7d77fb7
os: win32 x64
npm: 10.8.1
yarn: 1.22.22
```

`

**Comment by Steinweber** [comment]
/node_modules/@warp-drive/build-config/dist/cjs-set-config.cjs
Line 622:
dirname starts with /C:/

```
let directory = new URL((typeof document === 'undefined' ? require('u' + 'rl').pathToFileURL(__filename).href : (_documentCurrentScript && _documentCurrentScript.src || new URL('cjs-set-config.cjs', document.baseURI).href))).pathname;
const dirname = directory.startsWith('/') ? directory.slice(1) : directory;
```

This works for me.

**Comment by kategengler** [comment]
Look like it is a bug in `@warp-drive`? cc @runspired

**Comment by runspired** [comment]
its a bug in node (imo) in that it will blindly append a second `/C:/` to a path when one already exists when using some APIs; however, we already released a patch to work around this last week and this can be closed.

**Comment by kategengler** [comment]
Thanks!
