### ISSUE TITLE
Cybersecurity  - update testem dependency to the latest version 3.15.1

### ISSUE THREAD

**Issue by VladMoglan-eaton** [ember-cli/ember-cli#10498]
Please update the testem package to latest version 3.15.1 for the reasons detailed in [this issue](https://github.com/testem/testem/issues/1813) on their GitHub. The version previous to 3.15.1 relied on some dependencies featuring some security vulnerabilities.

Could this be somehow retroactively applied to the latest current LTS?

**Comment by bertdeblock** [comment]
https://github.com/ember-cli/ember-cli/pull/10499 addresses this issue.
