### ISSUE TITLE
pushObject is undefined on @tracked annotated property

### ISSUE THREAD

**Issue by gagan-bhullar-tech** [ember-cli/ember-cli#10503]
1. Added property annotated with @tracked property
2. Calling `pushObject` method on that

It is throwing error pushObject is not defined.

**Comment by NullVoxPopuli** [comment]
pushObject only existed on arrays uf prototype extensions are turned on. Array prototype extensions are deprecated tho,
See here for the migration guide:

https://deprecations.emberjs.com/v5.x#toc_deprecate-array-prototype-extensions
