### ISSUE TITLE
[SOLVED] Disable auto port select by a config option

### ISSUE THREAD

**Issue by DirkLachowski** [ember-cli/ember-cli#10504]
https://github.com/ember-cli/ember-cli/pull/10394 added auto port selection if the default port is already in use. That's great, until you start the dev server, forget about it, start another server in a second terminal and then keep using your app already active in  a browser window. I now got bitten by this multiple times after upgrading ember.

While it is possible to disable this feature by adding a `--port` flag to `ember s`, it's something you have to think about beforehand.

Is it possible to disable this feature at all for a project by a config flag in `.ember-cli`?

**Comment by Windvis** [comment]
@DirkLachowski you can simply add the port you want to the .ember-cli file, it accepts the same options as the cli (but they need to be camelCased).

```json
{
  "port": "4200"
}
```

More info: https://cli.emberjs.com/release/appendix/configuration/
