### ISSUE TITLE
Plan v6 release

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#10537]
Clean up deprecations:
- [`outputPaths` build option](https://deprecations.emberjs.com/id/ember-cli-output-paths-build-option) - https://github.com/ember-cli/ember-cli/pull/10534
- [Travis CI support](https://deprecations.emberjs.com/id/travis-ci-support) - https://github.com/ember-cli/ember-cli/pull/10538

Additional cleanup work:
- https://github.com/ember-cli/ember-cli/pull/10496

**Comment by NullVoxPopuli** [comment]
Fixes:
- https://github.com/ember-cli/ember-cli/pull/10533 (linting is incomplete/broken on main)

**Comment by kategengler** [comment]
I want to merge these PRs but it will be easier to land https://github.com/ember-cli/ember-cli/pull/10536 before removing these deprecated features.

**Comment by NullVoxPopuli** [comment]
does it make sense to also put template-tag and embroider in the blueprint by default for the v6 timeline?

**Comment by zyhou** [comment]
Does V6 will handle[ Node 22 LTS](https://nodejs.org/en/blog/release/v22.11.0) and [Node 23](https://nodejs.org/en/blog/release/v23.0.0)? [Supported Version Matrix](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md#supported-version-matrix)

**Comment by bertdeblock** [comment]
Correct, we still need to update the Node support matrix.

**Comment by bertdeblock** [comment]
Made https://github.com/ember-cli/ember-cli/pull/10578 to test against Node v22.
