### ISSUE TITLE
thoughts on: ember-cli-addon -> ember-addon keyword?

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#1064]
https://github.com/stefanpenner/ember-cli/blob/88af30af65e07fbf8150d3ad4a58ceb5f2b0dd87/lib/models/project.js#L62

Im curious what your thoughts are @rjackson, I would prefer the later. Im just seeking confirmation I'm not missing something.

**Comment by shama** [comment]
> assume no-one build ember apps without the CLI

Just chiming in to let you all know we build ember apps without ember-cli.

**Comment by rwjblue** [comment]
Seems totally fine. We absolutely want to ensure that making your own build system is possible, but when you do you are definitely missing out on a decent portion of what the Ember ecosystem can provide you.

**Comment by shama** [comment]
Thanks @rwjblue, I know I'm missing out. :)

Is there any reason Ember addons don't use an existing module format? Seems like a big win for the entire JavaScript community to be able to consume Ember community created code.

**Comment by stefanpenner** [comment]
They are just authored in es6. Transpile to what you need and use them. But there is a lot more to addons then just the code that runs in browsers.

The conventions allow for a much higher fidelity experience.

**Comment by shama** [comment]
Oh sorry, I didn't mean the syntax but rather the format of the module/package/library.

Such as when I do `npm i ember-new-computed` and then `require('ember-new-computed')` or `import computed from 'ember-new-computed'` I expect to get the library for the new Ember computed syntax as indicated in the readme. Instead I get the ember-cli addon.

Couldn't we keep the same high fidelity experience if ember-cli used it's own path or module format to load addons? Then have the `main` path point to the actual library so it remains idiomatic to npm users?

**Comment by stefanpenner** [comment]
> Couldn't we keep the same high fidelity experience if ember-cli used it's own path or module format to load addons? Then have the main path point to the actual library so it remains idiomatic to npm users?

this isn't very high priority for us. We author in ES6, if people want to consume in different ways it is up to the consumer.

Ember addons already support this, as we prefer ember-addon-main key over main. If someone is interested in a polyglot addon, nothing prevents this.

**Comment by stefanpenner** [comment]
It is theoretically possible that the default blueprints could be adapted to better facilitate this by default. 

That being said I am fairly concerned the bifurcation will be more costly then the benefit. I am willing to be convinced.

**Comment by stefanpenner** [comment]
If someone is interested, a thoroughly fleshed out RFC would likely be appropriate, although and RFC issue to fact-find first is likely encouraged.

**Comment by shama** [comment]
Thanks for your response! I didn't know `ember-addon-main` was a thing. That is very helpful as, at the very least, I can start sending PRs to the libraries we use to support that approach, thanks!
