### ISSUE TITLE
.ember-cli settings file live-reload option not working

### ISSUE THREAD

**Issue by zigomir** [ember-cli/ember-cli#1080]
This is my `.ember-cli` file

``` json
{
  "port": 4200,
  "host": "0.0.0.0",
  "live-reload": false,
  "proxy": "http://localhost:3000",
  "environment": "development"
}
```

I'm running `ember-cli` with `ember server` command.

But it will automatically live reload my tab in browser even though I set it to false.

**Comment by ccarterc** [comment]
Is there a solution to have live-reload not point to localhost so that I can access my site from host machine.  My ember app is being served from vm and I would like to be able to access it in host or make it available on my local network so other people in office can access it.
