### ISSUE TITLE
ember test hangs after last ok

### ISSUE THREAD

**Issue by davidolrik** [ember-cli/ember-cli#1083]
On 0.0.35 `ember test` would hang for ever after the tests had printed the last ok.
On 0.0.36 `ember test` hangs for ~15 seconds.

**Comment by MichaelVdheeren** [comment]
I am expecting this issue with 0.2.3 as well

**Comment by stefanpenner** [comment]
I did restore the old code path that was causing everyone issues in the past as it was causing other issues not having it.  Unfortunately I was unable to reproduce. Can you assemble a reduced scenario for me to debug?

**Comment by MichaelVdheeren** [comment]
Even without integration tests, only jshint checks, it just hangs.

![screenshot 2015-04-10 10 20 51](https://cloud.githubusercontent.com/assets/375809/7084241/4af7037a-df6b-11e4-9618-c10105611ef1.png)

**Comment by MichaelVdheeren** [comment]
If I pass a port with --port it exits properly

**Comment by rwjblue** [comment]
Does it exit after pausing for a period of time (around 10-20 seconds)? Previously, before we force exited, it would eventually exit.

**Comment by MichaelVdheeren** [comment]
It doesn't. I believe it worked with ember-cli 0.2.0

**Comment by kylecoberly** [comment]
I'm experiencing this too with an unmodified model test. If I comment out the "it exists" test, it works.

**Comment by mixonic** [comment]
I do not believe this is the same issue as the original ticket here.

@rwjblue it just hangs forever after phantom has completed. The occurrence is intermittent. Passing a port does indeed seem to relieve the hanging builds.

**Comment by chrislopresto** [comment]
I'm seeing the same thing intermittently on 0.2.3 on Travis and locally. After seeing @kylecoberly's comment, I deleted two unmodified, generated tests, which got Travis green.

Locally, I was able to get `ember test` to return after blowing away the tmp test directory. I then added the same generated tests back in, and `ember test` continued to return properly. I'll try to do some more methodical troubleshooting if/when this happens again.

(Specifying a port in the `.ember-cli` file did not help locally.. didn't try it on Travis.)

**Comment by alexdiliberto** [comment]
I'm also seeing this issue fairly regularly. Will post findings if I have any more information

**Comment by adamesque** [comment]
I'm also seeing this issue in my ember-cli project, but now I'm wondering if it's an issue with testem:
https://github.com/airportyh/testem/issues/528

I chimed in there with my observations running `testem` & `testem ci` in an empty directory. Same issue, and like many here have reporting, passing testem a port number other than the default seems to work around the issue.

**Comment by skaterdav85** [comment]
I just ran into this issue where my tests were getting stalled on the last test on Travis CI. Adding `"port": 4200` to `.ember-cli` resolved it. Anyone have an idea why this came up now?

For some context, the app started on Ember 1.13, and has been upgraded periodically to what is is now, which is Ember 2.8 and Ember CLI 2.11.1.
