### ISSUE TITLE
Renders blank page when deployed, but not from ember serve

### ISSUE THREAD

**Issue by bguiz** [ember-cli/ember-cli#1098]
When I run this command, and visit http://localhost:4200, the app renders itself correctly.

```
ember serve --environment=production --live-reload=false
```

However, when I run this command, and deploy the contents of the `dist` folder to a location being served by an Apache instance, the app does _not_ render anything (blank page):

```
ember build --environment=production 
```
- There is no console output.
- There are no network 404 errors - all of vendor.js, appjs, vendor.css, app.css have been downloaded correctly.
- If I set a debugger, I can see that the Javascript is indeed being executed, the execution enters module `app/app`, and subsequently `ember/load-initializers` and `app/router`. Nonetheless nothing is being rendered on screen.
- If I visit a URL that  should exist, like `/foo`, I get a HTTP 400 error. It seems like the router did not load correctly, or the application's initial state is not getting started.

Note that using an Ember app built using vanilla EmberJs (without using ember-cli), and deployed to this same location, does not suffer from this issue at all, and gets rendered correctly. That app pre-pended its route URLs with `#`, so it might be history API related.

What other avenues can I investigate?

**Comment by cravindra** [comment]
I had the same issue and fixed as suggested by moving everything to the root directory.
However, while the root route loads properly, none of the other routes work.. Is there something I might've missed?
