### ISSUE TITLE
Ember version and add-on compatability

### ISSUE THREAD

**Issue by blesh** [ember-cli/ember-cli#1139]
I'm working on add-ons that require Ember canary. It would be a better experience for people down the road to have Ember-Cli tell them there was a version compatibility issue, and perhaps upgrade ember for them, rather than have them figure it out organically and manually call `bower install -S ember#canary`, or whatever they need to do to fix the issue.

Probably not important, just a nice to have.

**Comment by stefanpenner** [comment]
yes, this is important still, we will doit during the next addon push

**Comment by stefanpenner** [comment]
addons have been using the semver lib themselves to enforce this.

As we move to an npm pure build, we plan to use-peer dependencies to provide ember. In addition to this, we plan to provide a constraint based installer to ensure the various requirements have been met, or  error as helpful as possible.

This work is planned (just lots of work left todo), but I don't see value is keeping this issue around.
