### ISSUE TITLE
clean command to clean dist and tmp dirs

### ISSUE THREAD

**Issue by quaertym** [ember-cli/ember-cli#1186]
Would it be more convenient to have an `ember clean` command to clean `dist` and `tmp` directories rather than doing `rm -rf {tmp,dist}`?

**Comment by NeilAllen** [comment]
1.76GB tmp folder with a new install; what do you need to 'stomp'?

**Comment by craigotis** [comment]
I just removed an 11GB /tmp/ directory filled with directories like:
```
broccoli_merge_trees-cache_path-4BPMbXBt.tmp
broccoli_merge_trees-input_base_path-kVPkCxSc.tmp
broccoli_merge_trees-output_path-LwP2Kpme.tmp
config_replace-output_path-WfEinSBN.tmp
funnel-cache_path-2rfXuLD2.tmp
funnel-output_path-IcvtwRW3.tmp
template_compiler-output_path-siblALL6.tmp
```
I'm not sure what I can do to help you guys reproduce this, but I'd be surprised if you're not already seeing it in nearly any project you're using.

Using ember-cli 1.13.13

**Comment by XaserAcheron** [comment]
Holy yikes. I stumbled upon this issue via Google after checking my `/tmp` folder. 614,897 files, 9.11 GB.

I don't really know what details to give other than "I'm on Windows", though. That's proven to be a source of goofiness more than once.

**Comment by kgish** [comment]
Indeed, I am experiencing the same problem. The `tmp` directory is growing out of control with all kinds of stuff and is NOT being cleaned. Sometimes I clean it manually using `rm` and it takes forever (many minutes) to finish.

There must be someway to fix this.

**Comment by trianglegrrl** [comment]
Just stumbled on this myself. It happens using at least ember-cli 2.5.1,  2.6.2, and 2.7.0.

**Comment by stefanpenner** [comment]
It is most likely one of the plugins you have installed, or maybe hit some threshold that prevents the cleanup from happening before the process exists.

Please share a reproduction (as basic apps do work correctly), once you have the isolated reproduction open a new issue and we can debug

**Comment by ErisDS** [comment]
I'm seeing this problem too, in Ghost-Admin. I don't know what a reproducible case is other than: clone Ghost, develop on it. Sometime later notice you've got a ridiculous amount of files in the tmp folder. 

broccoli merge trees & babel are the two major culprits.

Eventually, I also noticed we get an ENOENT error for a `stat` call on a file in the tmp folder. At that point clearing the tmp folder out gets rid of the error.

**Comment by kgish** [comment]
Yes indeed, several releases later I continue to have this problem for some reason. Hard to reproduce, but now I've gotten into the habit of just running `rm -rf tmp/*` on a regular basis.

**Comment by nathanhammond** [comment]
We now provide a message that communicates that we're cleaning up. `ctrl + c` twice in rapid succession kills our cleanup process. Also partially addressed by https://github.com/ember-cli/ember-cli/pull/6423

**Comment by stefanpenner** [comment]
* https://github.com/sindresorhus/ora/issues/27 addressed on our end via https://github.com/ember-cli/ember-cli/pull/6423
* https://github.com/broccolijs/broccoli/issues/311 mid build cleanups don't work. I think i can have this addressed this week

**Comment by stefanpenner** [comment]
*  #6423 landed
* working on broccolijs/broccoli#311  now

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-builder/pull/2 landed. Some fixes are already in the wild, the rest should be in a release or two. (As the release train arrives)

**Comment by SebastianPetric** [comment]
I want to delete the tmp folder. but I only find the dist/ directory. Could someone pls tell me where the location of this tmp folder is on osx?

**Comment by lougreenwood** [comment]
@SebastianPetric Did you have any success with that? I need to do the same thing...

**Comment by pgib** [comment]
@SebastianPetric @lougreenwood You can find where your user's tmp folder is by running:

```sh
cd $(dirname $(mktemp -u))
```

or alternatively:

```sh
node -e "const os=require('os');console.log(os.tmpdir())"
```

For me to force a cold build, I had to remove the following folder:

```sh
rm -rI "$(dirname $(mktemp -u))/${USER}/if-you-need-to-delete-this-open-an-issue-async-disk-cache"
```

(The `-I` switch there will prompt for confirmation)
