### ISSUE TITLE
Testing Woe: "Cannot call get with 'currentPath' on undefined object"

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-cli#1203]
I'm starting a brand new project with Ember CLI and I see the below error in an integration test:

```
not ok 1 PhantomJS 1.9 - Acceptance: Viewing An Exercise: visiting /cars/1
    ---
        message: >
            Error: Assertion Failed: Cannot call get with 'currentPath' on an undefined object.
```

My integration test looks like this:

``` javascript
test('visiting /cars/1', function () {
  visit('/cars/1');

  andThen(function () {
    equal(currentPath(), 'car', 'is a specific car');
  });
});
```

Given that I'm using AutoLocation, the problem is obvious: I'm not serving up my Ember app at all possible routes. I think there's a missing piece of the puzzle for testing that shows you how to set up the api-stubs (or whatever) to serve up the Ember app accordingly.

**Comment by atomkirk** [comment]
I saw this as well, although I think there is something else at play. As stefanpenner can't reproduce it, I don't think this happens on a new fresh project, so there must be some other common element to my project and the two previous commenters. Investigating.

**Comment by famousgarkin** [comment]
Getting the same on a fresh project. Creating an empty application controller indeed fixes the issue.
