### ISSUE TITLE
ERROR: f2d_register_rpc()

### ISSUE THREAD

**Issue by chrishough** [ember-cli/ember-cli#1260]
I am running osx 10.9.3 and this error just started popping up when starting ember cli:

> 2014-07-03 20:01 ember[48381](CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

I was running node version v0.10.28 and after discovering this thread https://github.com/joyent/node/issues/5463 I upgraded to v0.10.29 but it did not fix the issue.

Is there a fix for this? Is this cli specific?

**Comment by albertpak** [comment]
:+1:

**Comment by aronysidoro** [comment]
:+1:
