### ISSUE TITLE
JSHint Errors : This character may get silently deleted by one or more browsers

### ISSUE THREAD

**Issue by Nininea-zz** [ember-cli/ember-cli#1297]
line 1, col 0, This character may get silently deleted by one or more browsers.
I get this error 4 times, for every .js file I've added.

For instance 

error text:

'scripts/models/company.js: line 1, col 0, This character may get silently deleted by one or more browsers '

scripts/models/company.js content:

import DS from "ember-data";

export default DS.Model.extend({
    name: DS.attr('string'),
    id: DS.attr('int'),
    number: DS.attr('int'),
    address: DS.attr('string')
});

**Comment by ctataryn** [comment]
@stefanpenner when using a french translation file that has accented characters we get this error.  https://gist.github.com/ctataryn/23274d5cf1b7ca26b91e

Sample Errors:
`````
utils/translations-fr.js: line 6, col 15, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 9, col 30, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 10, col 52, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 11, col 49, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 12, col 61, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 13, col 61, This character may get silently deleted by one or more browsers.
utils/translations-fr.js: line 14, col 69, This character may get silently deleted by one or more browsers.
``````

**Comment by ctataryn** [comment]
Actually... fixed this via vim by doing a:
`:write ++enc=utf-8`

**Comment by stefanpenner** [comment]
@ctataryn I suspect, having the editor set the correct encoding is the right answer. I think jshint just saved us from browser crazies.
