### ISSUE TITLE
Provide a means to import ES6 modules

### ISSUE THREAD

**Issue by bguiz** [ember-cli/ember-cli#1352]
In a `Brocfile.js`, we can import standard AMD assets, and standard non-AMD assets:

```
var app = new EmberApp(/* ... */);
/* ... */
app.import('vendor/momentjs/moment.js'); //standard non-AMD asset
app.import('vendor/ic-ajax/dist/named-amd/main.js', { exports: /* ... */ }); //standard AMD asset
//how to import ES6 module
```

This is great for including dependencies which have already been published on npm and bower.

However, let's say that we are writing our own dependency. Since we are starting from scratch, it would make the most sense to write the dependency as an ES6 module from the get go. 

I am not sure if this is currently possible to do in ember-cli, as the [documentation for managing dependencies](http://iamstef.net/ember-cli/#managing-dependencies) does not mention this. The imported module must, of course, go through the es6 transpiler. If this is possible, how?

**Comment by hparra** [comment]
Note to anyone landing here: You _do not_ need to `app.import` the ES6 module itself. This will be done automatically for you.
