### ISSUE TITLE
es6 with named exports

### ISSUE THREAD

**Issue by fordguo** [ember-cli/ember-cli#1379]
https://github.com/square/es6-module-transpiler#supported-es6-module-syntax

How can i use named exports

**Comment by alansouzati** [comment]
How to include an external library with this format? I'm new to the ember community and I'm trying to import an external library (not an addon), that has the following structure:

`import { MyComponent } from "my-library"`

`my-library` does not have any default export.

I'm having a hard time integrating this library in the ember ecosystem.

Initially I was just expecting that to work. But I would keep getting module not found errors. I'm trying to use `ember-auto-import`, but it complains that there is no default export.

Any advice here?
