### ISSUE TITLE
"Unexpected whitespace character" undefined "?"

### ISSUE THREAD

**Issue by Nininea-zz** [ember-cli/ember-cli#1397]
ember-cli build issue. I have added "-W100":true inside global .jshint file. I can't fix this issue. :(

**Comment by kmillerdevx3** [comment]
It appears to be a UTF (encoding) issue - I opened the files in Notepad++ and saved as ANSI instead of UTF-8, and they don't throw this error anymore.

**Comment by pnosko** [comment]
To me the error happened when I used windows-style line ending (CR-LF, i.e. \r\n) instead of unix-style (LF, i.e. \n). Strange that the parser is so fragile though...

**Comment by zanemayo** [comment]
For me this was caused by the javascript file being encoded in UTF-8 with a BOM (byte order mark).

To fix it, I did the following:

1. Open the file in Notepad++ 
2. Click on the 'Encoding' menu 
3. Click on 'Encode in UTF-8 without BOM' 
4. Save the file

**Comment by wereldbolt** [comment]
@zanemayo did the trick for me too. Thanks!
