### ISSUE TITLE
How to include stylesheets with names other than app.scss in the styles directory

### ISSUE THREAD

**Issue by agentVargas2012R** [ember-cli/ember-cli#1403]
Hey Guys,

Reading through the documentation, I see the following information presented:

Stylesheets

Ember CLI supports plain CSS out of the box. You can add your css styles to app/styles/app.css and it will be served at assets/application-name.css.

If I want to have another css file in the styles directory, what modifications would I need to make to the brocfile.js ?

Thanks!

**Comment by cedric07** [comment]
@HeroicEric 

Hi Eric !

I want try to have multiple compiled stylesheets to link to separately but i can't to do it.
Have you an idea ?

Thanks !

**Comment by raido** [comment]
You can have multiple output paths for you less or sass files:

http://ember-cli.com/user-guide/#asset-compilation

```
var app = new EmberApp(defaults, {
    outputPaths: {
      app: {
        css: {
          'my-source': '/css/my-compiled.css'
        }
      }
    }
});

// Where my-source is 'app/my-source.* and '/css/my-compiled.css is destination in 'dist/'.
```

**Comment by cedric07** [comment]
Thanks. I try this, but it not works. 
I use ember-cli-compass-compiler :

<pre>
var app = new EmberApp(defaults, {
  compassOptions: { 
      outputStyle: production ? 'compressed' : 'expanded'
  }
});
</pre>

I have <code>app.scss</code> and <code>override.scss</code> in <code>app/styles/</code> directory but only the <code>app.scss</code> is compiled to <code>app.css</code> in the <code>dist/assets/</code> directory by ember-cli-compass-compiler
