### ISSUE TITLE
Allow Ember Init and Generate for Coffeescript

### ISSUE THREAD

**Issue by srsgores** [ember-cli/ember-cli#1408]
It's very frustrating that I have to go and replace all the default `.js` files with coffeescript ones, on `ember init`.  Why can't I just specify a flag, like there was in ember app kit:

> ember init coffee:true

I would also like to see the same feature in generators:

> generate route about coffee:true

**Comment by sdhull** [comment]
Does anyone know if there is a coffeescript blueprint available for use somewhere yet?
