### ISSUE TITLE
Ember Test: No Tests Are Ran

### ISSUE THREAD

**Issue by agentVargas2012R** [ember-cli/ember-cli#1451]
I searched the issues and did not find anything matched this scenario exactly so I am creating an issues. 

**Background**
C:\opt\workspaces\CallCenter>ember test 
version: 0.0.39       

**From the docs**
ember test
Run tests with Testem on CI mode. You can pass any options to Testem through testem.json, by default we’ll search for it under your project’s root or you can specify config-file.

**Built project successfully. Stored in "C:\opt\workspaces\yomoma\tmp\class-tests_dist-qZh4xARd.tmp".**

1..0
 tests 0
 pass  0
 fail  0

ok

**directory structure:**
tests/*_/_-test.js

Is there a manual step that needs to be done in order to register the tests to execute inside the test folder?

**Comment by ccarterc** [comment]
Fixed it by adding:

`C:\Users\blessenm\AppData\Roaming\npm\node_modules\phantomjs\lib\phantom` to path variable.  

Do NOT add:

`C:\Users\blessenm\AppData\Roaming\npm\node_modules\phantomjs\lib\phantom\phantomjs.exe`

Also make sure to replace `blessenm` with your appropriate user name.

**Comment by KurtRMueller** [comment]
Hmmm.... I'm running into this same problem. I installed phantomjs via the ` npm install -g phantomjs` command. I get an error where 0 tests are ran.

I'm on a Mac however. Should I open up a new issue?

**Comment by vilhelmjosander** [comment]
Same problem here on mac. Terminal is just blank after building application, then when pressing ctrl+C I just get the following:

1..1
# tests 1
# pass  0
# fail  1

**Comment by stefanpenner** [comment]
@KurtRMueller @vilhelmjosander if you open a new issue be sure to give actionable info

* what version of node / npm / ember-cli / os / phantom
* does it work with a vanilla app etc.

**Comment by KurtRMueller** [comment]
Some of that info I gave here: https://github.com/ember-cli/ember-cli/issues/3977#issuecomment-97285168

My current version of phantom js is listed below. Of course, after `brew upgrade`ing and the like, it might be different than the version I attempted to run the tests with. Next time I will try to include more information.

```
phantomjs -v                                                                                                                                                                                     127 ↵
1.9.8
```

I am running OS/X Yosemite.

**Comment by steffenbrem** [comment]
I have the same as @vilhelmjosander described. I can't test my ember apps on my CI server because of this problem.

**Comment by stefanpenner** [comment]
Likely a testem and centos bug. If someone provides a centos vm as one of our vagrant vm. We can try and debug it

**Comment by steffenbrem** [comment]
@stefanpenner I tested a vanilla app, and there it all works fine. I am using Mocha on my main project, maybe that causes it?

**Comment by steffenbrem** [comment]
@stefanpenner The same problem exists on an Ubuntu box. I will now try an older version of my app with qunit and see if that runs. It might be a problem with Mocha? I do have `"framework": "qunit"` in my `testem.json`, or does that not matter?

**Comment by stefanpenner** [comment]
You likely lost something important. Please thoroughly compare the basic app and yours . Or doing something in your tests that may be screwing up testem

**Comment by vilhelmjosander** [comment]
For anyone else with this problem it was solved for me by changing the ENV.locationType to 'none' instead of 'hash' for the testing environment.

**Comment by kushdilip** [comment]
I faced exactly similar issue. Running `ember test

**Comment by kushdilip** [comment]
I faced exactly similar issue while back. Running `ember test` in console gave above error. This got fixed after changing from 
```
"launch_in_ci": [ ]
```
to
```
"launch_in_ci": [
    "PhantomJS"
  ]
```

**Comment by sunil-sharma** [comment]
Same problem here on mac with following error logs:
>1..0
#tests 0
#pass  0
#fail  0
#ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.*

**config/environment.js**
>module.exports = function (environment) {
    var ENV = {
        modulePrefix: 'app_name'
        podModulePrefix: 'some_prefix',
        APIServer: 'http://localhost:8080/****/',
        environment: environment,
        baseURL: '/',
        locationType: 'auto',
        EmberENV: {
            FEATURES: {
                // Here you can enable experimental features on an ember canary build
                // e.g. 'with-controller': true
            }
        },
        APP: {
            // Here you can pass flags/options to your application instance
            // when it is created
        }
    };
    if (environment === 'development') {
        // ENV.APP.LOG_RESOLVER = true;
        // ENV.APP.LOG_ACTIVE_GENERATION = true;
        // ENV.APP.LOG_TRANSITIONS = true;
        // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
        // ENV.APP.LOG_VIEW_LOOKUPS = true;
    }
    if (environment === 'test') {
        // Testem prefers this...
        ENV.baseURL = '/';
        ENV.locationType = 'none';
        // keep test console output quieter
        ENV.APP.LOG_ACTIVE_GENERATION = false;
        ENV.APP.LOG_VIEW_LOOKUPS = false;
        ENV.APP.rootElement = '#ember-testing';
    }
    if (environment === 'production') {
        ENV.baseURL = '***';
        ENV.locationType = 'hash';
    }
    return ENV;
};


**package.json**
>{
  "name": "idauto-idp-ui",
  "version": "0.0.0",
  "description": "Small description for ember-federation goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.13.2",
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-body-parser": "0.0.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.15",
    "ember-cli-release": "0.2.3",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "express": "^4.13.3",
    "glob": "^4.5.3",
    "morgan": "^1.6.1"
  }
}

**testem.json**
>{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}

**bower.json**
>{
  "name": "idauto-idp-ui",
  "dependencies": {
    "ember": "1.13.3",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.5",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.1",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1"
  }
}
versions:
phantom 1.9.8
testem 0.9.4
Any ideas?

I have created a vanilla app, tests are working fine. Not working for existing project with above files.

Thanks
