### ISSUE TITLE
Make it easy to add stylesheets for media="print", etc.

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli#1478]
I'd like to have an easier escape valve for building my print stylesheets.

I think the easiest approach would be to follow convention and generate a print stylesheet if a file exists at print.css. Other than that, I'd take anything that would allow building CSS together in a manner that doesn't require me to build my own Broccoli script.

**Comment by stefanpenner** [comment]
good idea, but stale. Will gladly accept and RFC or some proposal
