### ISSUE TITLE
Improve Windows Experience

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#1558]
Please note, this is a live document. Comments below will be used to incorporate ideas into this issue and then subsequently removed.

---

Very few of the main ember-cli contributors are also windows users. This results in some poor windows experiences as no-one is dog-fooding there issues.

It is also true some performance issues exist in unix systems but solutions are currently WIP (with order of magnitude improvements so far). These solutions may or may not translate to improvements in windows.
## Problems
- [x] performance (broccoli performance)
  - [x] performance solution (via github.com/broccolijs/node-symlink-or-copy/pull/1)
  - [x] performance docs (via http://www.ember-cli.com/#symlinks-on-windows)

this is often the result of editor/search indexing/virus scanner/defending indexing tmp directories. Broccoli relies on fast disk access, and often quickly changing files. Anything that interferes with this can result in slowdown, Progress but blocked on: https://github.com/broccolijs/node-symlink-or-copy/pull/1
- [x] stability
  - [x] get CI setup
  - [x] get CI passing (we need to upgrade to a premium account so we don't timeout)

our active development does not occur on windows, and neither does our CI run on windows so detecting regressions quickly is basically non-existent before releases.
- [x] time

As ember-cli is a labour of love (no corporate sponsorship) time invested is nearly entirely evenings/weekends. Because of this, most contributions are really dog-fooding the developers own pet peeves. Coupling this with far fewer windows contributors results is far less time spent improving the lives of our windows folk.
## Some Solutions
- [x] active windows contributor for ember-cli
- [x] active windows contributor for broccoli
- [ ] maybe sponsorship of @rwjblue, @joliss or some other eager and passionate individual to work on this problem?
- [ ] broccoli may want to consider using collide-able files names  (stability)
## Some tasks
- [x] documentation for windows specific issues/work-arounds
- [x] test suite should once again work on windows
- [x] some easy way for non-windows contributors to quickly test windows (maybe via some pre-configured VM all ready to go + some legally acquired windows licenses)
- [x] ember-cli test suite should once again work on windows (it may or may not.. this is part of the problem)
- [x] continuous integration on windows ?
- [x] test suite actually runs on windows (git-bash)
- [x] test suite actually runs on windows (without git-bash)
- [x] test suite largely working
- [x] test suite green on local vm
- [x] test suite green on CI
- [x] someone to work extend the current WIP symlinking approach to windows.
- [ ] fix usage on cygwin https://github.com/stefanpenner/ember-cli/issues/1812
- [x] fix: https://github.com/stefanpenner/ember-cli/issues/1292
- [ ] fix: https://github.com/stefanpenner/ember-cli/issues/1864#issuecomment-54489810

Once the symlink refactoring (broccolijs/broccoli#179) is finished & released, it will provide a great speed-up on Unix. But at the moment we're just falling back to copying on Windows, so performance isn't improving there. We should probably try to make symlinks or junctions work on Windows as much as possible, even if the exact code might need to cover some edge-cases. The relevant code is [node-symlink-or-copy/index.js#L14-L17](https://github.com/broccolijs/node-symlink-or-copy/blob/5e4ed362fb4206208583105d037adc4651cb5238/index.js#L14-L17).
                               -- @joliss 
## Sponsorship

I really want to discourage us from thinking this is the only way to solve this problem, but without more windows contributors it is hard to find the time ourselves to accomplish this without having our day-time employers giving us time.

If sponsorship is made available please remember that this gets quite tricky, as we all know quoting timelines is no developers speciality. And as such putting a single price-tag on improved windows quality is essentially impossible. But it may enable some improvements.

Another form of sponsorship could be for an entity to give one of there own developers some time to help work on the above tasks^
## Call for contributions

If any windows users (or users with time to help contribute improvements to our windows users) have time, but feel they need some guidance or help don't hesitate to reach out.

**Comment by bpcrao** [comment]
did not imrpove much for me with symlinks it takes around 60 seconds for a build

**Comment by stefanpenner** [comment]
> did not imrpove much for me with symlinks it takes around 60 seconds for a build

build or rebuild?

**Comment by bpcrao** [comment]
build is 60 seconds rebuild is 30 seconds.

**Comment by duizendnegen** [comment]
Improved for me initially (to build/rebuild around 4s) but back at 40s/25s now on Win7

**Comment by bpcrao** [comment]
@duizendnegen  is your tmp folder empty when you do a build?

**Comment by BryanCrotaz** [comment]
I get a big difference in speed when I run the command prompt as
administrator. I think this allows broccoli to use symlinks.


Bryan

**Comment by bpcrao** [comment]
@BryanCrotaz 
Yes, with symlinks there is improvement 
despite that build takes 60 sec, of that babel takes around 20 seconds

**Comment by joeyespo** [comment]
My experience is the same as @bpcrao. ~60 seconds today (although better than before!), with Babel taking 20s of that. Running in Administrator mode doesn't help.

**Comment by neilyoung** [comment]
The most annoying issue with ember-cli/broccoli on windows is, that due to strange dependency handling of brocooli (?) there are extremely long paths. You cannot even delete such a directory w/o being warned to have exceeded the max-path. I will stop messing with ember on windows

**Comment by stefanpenner** [comment]
> that due to strange dependency handling of brocooli

this would be npm, upgrading to `npm` version 3, produces much more flattened dependency structure.

> you cannot even delete such a directory w/o being warned to have exceeded the max-path.

Yes, this is unfortunate. Surprisingly windows actually does support this, but various tools (python) and the windows file browser do not. I have no idea why they do not, but they don't...

One technique is using the node_module `rimraf` which uses the correct windows api, and works correctly.

```
npm install -g rimraf
rimraf large/tree/to/delete
```

It is a pretty big bummer, but we have been working with Microsoft (who are users of ember-cli) to continue to improve the experience.

cc @felixrieseberg

**Comment by ccoenen** [comment]
I can also recommend [cmder](http://cmder.net/) as terminal emulator (download "full"). This will still be the regular cmd.exe shell, but you'll also have a nice round of unixy tools coming along with it. This includes `rm`, the unix command for deleting files. `rm -rf temp` works for me pretty well on windows.

**Comment by stefanpenner** [comment]
@ccoenen awesome, thanks for the tip.

**Comment by neilyoung** [comment]
@stefanpenner @ccoenen Thanks to both of you for your valuable hints. Will give both a try. I'm making a good progress with ember cli and Visual Studio Code on a Mac. Just wanted to return to the native environment for .net :)

**Comment by kellyselden** [comment]
Little tip for my fellow Windows users. If you install Git for Windows manually or via Chocolatey (`cinst git.install`), you can add the folder `C:\Program Files\Git\usr\bin` to your `PATH`, then get a plethora of unix tools, including `rm`, at your disposal.

**Comment by felixrieseberg** [comment]
And, since npm@3 is putting a whole bunch of Windows goodness in, I'd stick pretty close to the latest npm versions. We wrote a small tool, [helping you do upgrade](https://github.com/felixrieseberg/npm-windows-upgrade) :rocket:
