### ISSUE TITLE
I can not install ember-cli

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#1562]
I ran `npm install -g ember-cli"` from my home directory and got the following errors.

```
unbuild ember-cli@0.0.40
npm ERR! Refusing to delete: /usr/local/lib/node_modules/npm/bin/bin/ember not in /usr/local/lib/node_modules/npm/bin/lib/node_modules/ember-cli
File exists: /usr/local/lib/node_modules/npm/bin/bin/ember
Move it away, and try again. 

npm ERR! System Darwin 13.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "-g" "ember-cli"
npm ERR! cwd /Users/guysungkim
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/npm/bin/bin/ember
npm ERR! code EEXIST
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/guysungkim/npm-debug.log
npm ERR! not ok code 0
```

What could be an issue?
Thanks.

**Comment by raghuzcloudinc** [comment]
Unable to install ember cli on Windows 7. 
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0
npm WARN peerDependencies The peer dependency jscs@^2.1.1 included from mocha-js
cs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in fav
or of lodash@^4.0.0
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0
