### ISSUE TITLE
View events are not triggered during integration tests

### ISSUE THREAD

**Issue by jaydev** [ember-cli/ember-cli#1587]
Hi,

I noticed that code that is supposed to fire in Ember.View events like `click`, `mouseDown`, etc. is not getting called in my app's integration tests.

After a bit of digging, I realized that it might be because the global views hash (`Ember.View.views`) is emptied or not set while the tests are running. Thus no events are being triggered on the views.

I made a simple JSBin without using ember-cli which does not exhibit my issue:
http://emberjs.jsbin.com/vehoseni/1/edit

And I pushed up the same example with ember-cli where the problem occurs:
https://github.com/jaydev/ember-cli-integration-test-view-bug

I'm using ember-cli 0.0.39.

Thanks for your help!

**Comment by shivamtailor** [comment]
@jaydev I am facing same issue. Please let me know if you have found any work around to get rid of this issue. 

Ember Version:
version: 0.0.44
node: 0.10.32
npm: 1.4.26

Thanks,
Shivam

**Comment by stefanpenner** [comment]
> version: 0.0.44
> node: 0.10.32
> npm: 1.4.26

unrelated to this issue, but all of these versions are pretty old.
* npm 1.4 isn't supported you should attempt 2.6
* and ember-cli is at 0.2.0beta1

**Comment by jaydev** [comment]
@shivamtailor you should update your ember-cli and see if you still have the issue.

if it persists, you can fork ember-qunit and comment out the code in the `resetViews` function in `lib/ember-qunit/test.js`. i think that's what i did before.
