### ISSUE TITLE
Ember.js with moment.js - 'moment' is not defined.

### ISSUE THREAD

**Issue by zion03** [ember-cli/ember-cli#1607]
Include Non-AMD Asset as in docs:

bower:

```
    "moment": "2.8.1",
```

brocfile: 

```
     app.import("vendor/moment/moment.js");
```

app.js

```
 Ember.Handlebars.registerHelper('formatDate',function(date) {
      return moment(date).fromNow();
  });
```

It's works but ember-cli throw error in console:

```
         myapp/app.js: line 16, col 12, 'moment' is not defined.
```

**Comment by ajrobertson** [comment]
Thanks for this. Just what I needed to do!

**Comment by stefanpenner** [comment]
or use `ember-moment` which does this an provides handy helpers!

**Comment by stefanpenner** [comment]
> {
>   "predef": [
>     "moment"
>   ]
> }

actually don't use predef, if it's truely a global, refer to it via the global `window.moment`

**Comment by 20v100** [comment]
I'm using ember-moment but still get this warning: components/cond.js: line 26, col 28, 'moment' is not defined.

**Comment by 20v100** [comment]
Nevermind. I found that adding `import moment from 'moment';` solved the issue.

**Comment by markie2902** [comment]
@20v100 where did you say you added import moment from 'moment' ?

**Comment by kshitijfd** [comment]
I figured there are two ways to solve this:

- the one discussed above, that is, adding _"moment"_ in _"predef:"_ block of the _.jshintrc_ file of your application.

- the other is by doing an `npm install moment` followed by `bower install moment`. I'm not really sure why this method works as _npm_ is for installing backend dependencies and bower for front-end, and moment seems to be a front-end support package.
