### ISSUE TITLE
Templates in pods from addons

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#1634]
#1439 works well, but now it's not possible for addons to provide templates in a POD format because `this.trees.app` in doesn't include the 'app' trees from any addons when `_processedTemplatesTree()` runs. Obvious workaround is to use `templates/` in addons, but I thought I'd raise it here because it seems an unfortunate distinction to me.

**Comment by stavarotti** [comment]
@EndangeredMassa Any luck on this?  I can pitch in were needed.

**Comment by sglanzer** [comment]
I'm still very interested in this as well and would rather have a solution to this individually than have it buried in the pods todo list.  I can do some poking around, but let me know if there is anything specific I can help with.

**Comment by sglanzer** [comment]
So I did a little digging - it appears that the pod templates from addons aren't part of the build tree in the ember-cli/lib/brocolli/ember-app.js function:

````
EmberApp.prototype._processedTemplatesTree = function() {
````

The function includes process for pod templates from the app tree
````
 var podTemplates = new Funnel(this.trees.app, {
    include: this._podTemplatePatterns(),
    exclude: [ /^templates/ ],
    destDir: this.name + '/',
    description: 'Funnel: Pod Templates'
  });
````

So I made a few additions
````
var addonTree = this.addonTreesFor('app');
  console.log(addonTree);
  var addonPodTemplates = new Funnel('/home/sglanzer/Documents/Projects/pod-template-addon/app', {
    include: this._podTemplatePatterns(),
    exclude: [ /^templates/ ],
    destDir: this.name + '/',
    description: 'Funnel: Addon Pod Templates'
  });

  return preprocessTemplates(mergeTrees([standardTemplates, podTemplates, addonPodTemplates]), {
    registry: this.registry
  });
````
and I was able to use a template in my addon's app directory with a pod structure (app/pods/components/addon-component/)

This only worked if both the addon and the dummy app were set up to use podModulePrefix (makes sense, I think).

As you can see in the code above I hard coded the input path, but there should be a way to use the addonTreesFor('app') result.

If anyone wants to provide more direction or take it the rest of the way, I'm done with this for the day - I may pick it up again tomorrow, but it'd be cool if someone who knows more about the ember-cli architecture chimed in here.

**Comment by EndangeredMassa** [comment]
Sorry for the delay on my part. I just had a kid and have been very busy. If someone else can fix this, that would be great.

**Comment by deepflame** [comment]
Have the same problem and tried to dig into the code as well. So far I could not solve it.

@sglanzer Thanks for your initial work. That was really helpful for me! However I think the work should be done on the addon code itself and not in the app code.

So it would be great to let the `addonTrees` return the pod templates as well. [Code Reference](
https://github.com/ember-cli/ember-cli/blob/b12e0023dc653316f68aa58b9bb14ade3037e9e6/lib/broccoli/ember-app.js#L424)

To work around this I thought of implementing `treeForTemplates` in my addon's index.js as described here: https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#treefor-cont

But so far without luck.

Any help to make templates in an addon's pod structure would be highly appreciated.

**Comment by juggy** [comment]
I added a treeFroTemplates like this:

```
treeForTemplates: function(){
    var templates = pickFiles(this.project.root + "/node_modules/vroom-kit/app", {
          srcDir: '/',
          files: ['**/*.hbs'],
          destDir: '/'
        });
    return templates;
  }
```
And the templates get compiled (there is some hardcoded path in there, can someone show me how to get the path for the addon?). The resolver is not picking them for me, but that is one step further.

**Comment by sglanzer** [comment]
I did some work on this today that I've posted in #3964.  Hopefully with a bit of input this should be good to go soon.

**Comment by stevehanson** [comment]
@juggy thanks for sharing your code! Did you ever get this working? I tried using your `treeForTemplates` code, but I'm not sure how to hook up the resolver. I'm also not sure how to troubleshoot which files are being added and under which path.

I'm converting a POD-based application into an addon, so I can use it as the core for several other apps, but am hung up on getting the templates loaded. Thanks again :)

**Comment by sglanzer** [comment]
@stevehanson templates in addon pods already work with an explicit import.  I believe this is in the generators for components in addons.  Basically the template beside the component in the pod directory is imported as the layout of the component.  I think this has been in place for a few ember-cli releases - back to the 0.2.x range

**Comment by sglanzer** [comment]
ember generate component --pod in an addon project to see this example

We do this in a ton of addons currently

**Comment by stevehanson** [comment]
@sglanzer thanks for the reply. In my specific case, I have an application that I'm converting to an addon, which multiple apps will use and extend. The consuming apps include the core routes in `router.js`, and then I'd like the pages/functionality from the core addon to just work.

**Comment by sglanzer** [comment]
@stevehanson sounds a lot like the engines RFC, I'm looking forward to a solution like that myself

**Comment by stevehanson** [comment]
OK, I figured out how to include the pods templates from my addon, thanks to @juggy's comment pointing me in the right direction. Here is my code that I put in the addon's `index.js`:

```
treeForTemplates: function(tree){
  if(fs.existsSync(this.project.root + '/node_modules/boutique-admin')) {
    return mergeTrees([tree, this.podsTemplates()]);
  } else { // running as regular app, eg during testing
    return tree;
  }
},

podsTemplates: function podsTemplates() {
  // Add templates from pods directory, since Ember CLI doesn't include them by default
  return new Funnel(this.project.root + '/node_modules/boutique-admin/app/pods', {
    include: ['**/*.hbs'],

    getDestinationPath: function(relativePath) {
      if(relativePath.indexOf('/template.hbs') !== -1) {
        // Remove ".template" from the path, eg: pods/posts/template.hbs => templates/posts.hbs
        return relativePath.substr(0, relativePath.lastIndexOf('/')) + '.hbs';
      } else {
        return relativePath;
      }
    }
  });
}
```

Now, all of the functionality in pods in my addon works in consuming apps :)

**Comment by ohnnyj** [comment]
@stevehanson Thank you good sir. You are a gentleman and a scholar...and saved me a bunch of time.

**Comment by stevehanson** [comment]
Glad it helped, @ohnnyj :)

**Comment by erkie** [comment]
Since this is still an issue I'm posting an updated version of the code above that worked for me:

Note that my `podModulePrefix` is empty, therefor it's: `/node_modules/THENAMEOFYOURADDON/app`

```js
module.exports = {
  name: 'just my addon name...',
  
  treeForTemplates: function(tree) {
    if (tree) {
      return mergeTrees([tree, this.podsTemplates()]);
    } else {
      return this.podsTemplates();
    }
  },

  podsTemplates: function() {
    // Add templates from pods directory, since Ember CLI doesn't include them by default
    return new Funnel(this.project.root + '/node_modules/THENAMEOFYOURADDON/app', {
      include: ['**/*.hbs'],

      getDestinationPath: function(relativePath) {
        if (relativePath.indexOf('/template.hbs') !== -1) {
          // Remove ".template" from the path, eg: pods/posts/template.hbs => templates/posts.hbs
          return relativePath.substr(0, relativePath.lastIndexOf('/')) + '.hbs';
        } else {
          return relativePath;
        }
      }
    });
  }
}
```

**Comment by erkie** [comment]
And my provided fix seems to be broken for 2.5.0 somehow... Looking into it now.

**Comment by stefanpenner** [comment]
we are re-working pods/folder structure stuff, stay tuned.

**Comment by chris-pauley** [comment]
Any update on this? Currently working on a project that would greatly benefit from having the pod structure available in an in-repo-addon.

**Comment by nathanhammond** [comment]
@chris-pauley Update is we're moving toward this: https://github.com/emberjs/rfcs/pull/143

**Comment by vlascik** [comment]
@erkie: did you manage to make it work somehow? it would help a lot in the meantime

**Comment by erkie** [comment]
@vlascik sorry, nope. I gave up.

**Comment by chris-pauley** [comment]
@vlascik we're using that method for an app using 2.5 and it works pretty well. The only caveat is we had to add an option to the EmberApp constructor in ember-cli-build to include helpers. Also we had to make sure to include Broccoli Funnel for the solution posted by @erkie

The helper option looks like this:
```
var app = new EmberApp(defaults, {
    trees: {
        helpers: 'path/to/addon'
    }
});
```

**Comment by janmisek** [comment]
Workaround based on @erkie did not work for me on ember 2.9. I use following workaround

https://gist.github.com/janmisek/4920e0483aa7bb647ff61588be9816b1
