### ISSUE TITLE
[Documentation] Locking Canary

### ISSUE THREAD

**Issue by rtablada** [ember-cli/ember-cli#1640]
Right now there are features (especially in ember-data) that may lead to projects needing to use canary branch in production or in a team.

This means that it is best practice to lock to a single commit of `components/ember-data`.

The guide would really just need to mention how to grab the short hash for a commit from the right github repo (components/*) and then using that instead of `#canary` and including it in the resolutions.

I think the section header could be something like `Using canary builds with a team`.
I want to work a bit on the wording and that's why right now I'm just setting an issue for myself so I can tackle this later this week.

**Comment by thejchap** [comment]
Was this documented anywhere?
