### ISSUE TITLE
bower_components not being added to vendor.css/js

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/ember-cli#1644]
Working on master and trying to update a project to reflect the changes from #1436 that split bower_components into its own directory, I'm not seeing 3rd party css/js being concated into my vendor.css/js files.  

I tried this in a fresh project as well (working off master) and saw the same issue.

`ember new testapp`
`cd testapp`
`bower install --save-dev bootstrap`

Add to Brocfile.js
`app.import('bower_components/bootstrap/dist/css/bootstrap.css');` 

`ember server`

and my vendor.css file is empty

Is there something I'm missing?

**Comment by msounthar** [comment]
I have the all the scripts loaded twice once from bower_components or vendor where ever they are placed and they are all concatenated again in the vendor.js, is this the expected behaviour or they are supposed to be only present in vendor.js?

**Comment by marclundgren** [comment]
I had the same problem as originally posted, but it was resolved by simply restarting `ember serve`.
