### ISSUE TITLE
Recommended way to include remote files like google maps

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#1654]
Normally you would include the file in the index.html page.

```
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language=en"></script>
```

What is the recommended way to include a file like this in ember-cli using Brocfile?

**Comment by marcoow** [comment]
How do you guys solve the fact that including the Google Maps API from a remote host makes it impossible to run the app without an internet connection? I would really like to have a workflow that allows me to run the app on e.g. my notebook when I'm on a plane or so.

**Comment by jcowley** [comment]
> How do you guys solve the fact that including the Google Maps API from a remote host makes it impossible to run the app without an internet connection?
> @marcoow 

Dropping the script into the vendor directory then importing it in ember-cli-build.js seems to work well. 

I like that approach better than adding script tags to app/index.html.

**Comment by jcowley** [comment]
Scratch that. After about a week of having the Google Maps javascript checked in, I started getting 403 authentication errors from Google. [Here's a S.O. post about this issue](http://stackoverflow.com/questions/10719319/after-months-of-100-stability-today-i-get-403-error-on-google-maps-services).

So I guess adding a script tag to the index.html is unfortunately the way to go.

**Comment by mellatone** [comment]
@jcowley +1. I tried that and ran into the 403 errors as well.

**Comment by emiliogambone** [comment]
Should i included under {{content-for "head-footer"}} or {{head}} or is just the same?

**Comment by jackmatt2** [comment]
It is the same except where a library needs to happen before or after the
ember ones.
