### ISSUE TITLE
Suggestion: /dist/ should be isolated per environment

### ISSUE THREAD

**Issue by johnnyshields** [ember-cli/ember-cli#1683]
I had an issue where I ran `ember build -e production` at the same time as running `ember serve` (possibly a livereload event hit just at the right time). As a result, the production build referenced development files--oops!

This could be easily avoided if each environment's broccoli tree was isolated in it's own folder.

**Comment by stefanpenner** [comment]
i think if u want something one-off use `--output-dir`
