### ISSUE TITLE
Reboot `ember server` on `Brocfile.js` change

### ISSUE THREAD

**Issue by ssured** [ember-cli/ember-cli#1756]
`Ember server` listens for changes in the project and rebuilds on changes. When changing `Brocfile.js` nothing happens though. It would be nice that after a change to `Brocfile.js` the server would restart. The regular use case here is adding a new lib through bower and adding it using `app.import`, no restart would then be needed.

**Comment by stefanpenner** [comment]
@taras this is related to your RFC.

**Comment by stefanpenner** [comment]
Interestingly, this should now be close to possible for our watchman users.

**Comment by stefanpenner** [comment]
We will revisit this post broccoli 1.0
