### ISSUE TITLE
Automatically Shim 3rd Party Globals

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#1771]
Looked through the tickets and didn't find anything about automatically generating shim files for 3rd party non-amd code.  I was thinking the api could look something like the following.

```
app.import('path/to/global', {
   global: 'moment'
});
```
When you build you just run this through a template to generate a GLOBAL_NAME-shim.js that looks something like.

```
define('moment', (function ( ctx ) {
  return { 'moment' : ctx['moment'] }
})(window));
```

This way you can include 3rd party global code like this, without having to deal with the shimming your self.

```
import moment from 'moment';
```

**Comment by abuiles** [comment]
I think we can close this in favor of https://github.com/ember-cli/ember-cli/issues/2177
