### ISSUE TITLE
Blueprints - including the plural name

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#1778]
In our project we need the plural name for the filesystem as well as the module name.

```
ember g crud person
```

We need access the the plural for person (people) which is what Ember.String.pluralize('person') would return.

```
__NAME__   => __NAME_PLURAL__
camelizedModuleName  => camelizedModuleNamePlural
```

is it possible to get these added?

**Comment by stefanpenner** [comment]
@jgwhite ping

**Comment by stefanpenner** [comment]
@jgwhite friendly ping
