### ISSUE TITLE
Don't serve serve folders via the browser

### ISSUE THREAD

**Issue by abuiles** [ember-cli/ember-cli#1788]
If I have a route `/assets` I shouldn't get the '/assets' folder.

**Comment by rwjblue** [comment]
Was introduced in https://github.com/broccolijs/broccoli/pull/160.

**Comment by rwjblue** [comment]
Created issue upstream for this: https://github.com/broccolijs/broccoli/issues/231

**Comment by joliss** [comment]
Hm... If your Ember app has an `/assets` route, but the assets live at `/assets/*`, then it seems you'll still generally have the same problem when you deploy to production, won't you? I realize that in principle you could make it work in production, but we (ember-cli) don't control the production environment, so it seems quite error-prone...

I wonder if it might not be acceptable to just say "don't do that".

**Comment by stefanpenner** [comment]
I think in practice though, the directory browsing isn't a natural state for a webserver. Production or development, typically it is an `opt in` sorta of thing. If we could configure this in broccoli, we can pick and choose accordingly. But as far as I know today, we cannot.

**Comment by abuiles** [comment]
Closed via  #3916
