### ISSUE TITLE
parent addon assets being copied into child addon namespaces

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#1795]
I haven't confirmed if the final output has this but if I have an addon that has several dep addons and each one has its own addon namespace'd files the parent's assets appear to be copied into the child addon's namespace. This is really bad as the size of vendor.js will be unnecessarily large. I will start digging into this soon.

**Comment by abuiles** [comment]
@bcardarella can you confirm if this is still happening?

**Comment by stefanpenner** [comment]
i think the current behavior is expected, but we will revisit as the new packager stuff lands.
