### ISSUE TITLE
ember-cli doesn't run on cygwin

### ISSUE THREAD

**Issue by iagox86** [ember-cli/ember-cli#1812]
I'm not sure if cygwin support is desired, but when I complained to Stef he said to open a bug. :)

This command more or less works through cmd.exe, but fails in cygwin:

Ron@Ron-PC /cygdrive/c/Users/Ron/appdata/Roaming/npm $ ./ember new test

net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\bin\ember:27:25
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\node_modules\resolve\lib\async.js:48:21
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\node_modules\resolve\lib\async.js:127:35
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\node_modules\resolve\lib\async.js:99:39
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\node_modules\resolve\lib\async.js:65:30
    at C:\Users\Ron\appdata\Roaming\npm\node_modules\ember-cli\node_modules\resolve\lib\async.js:23:18
    at Object.oncomplete (fs.js:107:15)

**Comment by alocus** [comment]
I had a similar issue. To make ember cli works in cygwin is to launch cygwin as recommended by @ccoenen: C:\cygwin\bin\bash.exe --login -i -c "cd /cygdrive/c/Users/username/; exec bash"
