### ISSUE TITLE
[0.0.42] Font-awesome not working in Firefox

### ISSUE THREAD

**Issue by felipehw** [ember-cli/ember-cli#1843]
In my `Brocfile.js`:

    var fontTree = pickFiles('bower_components/font-awesome/fonts', {
      srcDir: '/',
      files: ['*'],
      destDir: '/assets/fonts'
    });

This is not working in Firefox. I get an error like this:

    15:27:03.215 downloadable font: incorrect file size in WOFF header (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1)
    source: http://localhost:4200/assets/fonts/fontawesome-webfont.woff?v=4.2.0 bbmli-ui.css
    15:27:03.215 downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1)
    source: http://localhost:4200/assets/fonts/fontawesome-webfont.woff?v=4.2.0 bbmli-ui.css
    15:27:03.464 downloadable font: incorrect entrySelector for table directory (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2)
    source: http://localhost:4200/assets/fonts/fontawesome-webfont.ttf?v=4.2.0 bbmli-ui.css
    15:27:03.464 downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2)
    source: http://localhost:4200/assets/fonts/fontawesome-webfont.ttf?v=4.2.0

and didn't display the icons.

This works though in Chrome in the same version (0.0.42) and was working in Firefox for v0.0.37.

**Comment by abuiles** [comment]
This issue seem to have gone stale, will reopen and investigate further if we have it appearing again.
