### ISSUE TITLE
ember serve and ember test cannot run in parallel due to 'port already in use' issue

### ISSUE THREAD

**Issue by pogopaule** [ember-cli/ember-cli#1848]
I updated a rather big ember app to ember-cli 0.0.42. Since then I get the following error if I try to run `ember test` while `ember serve` is running.

```
Built project successfully. Stored in "/vagrant/frontend/tmp/class-tests_dist-iCGqraxa.tmp".
not ok 1 Error
    ---
        message: >
            Testem Server Error: listen EADDRINUSE
    ...

1..1
# tests 1    
# pass  0
# fail  1
Connection to 127.0.0.1 closed.
```

If I start ember with `ember serve --port 4100` the test run fine. No port collission.

It's worth mentioning that I didn't manage to reproduct this problem with a newly created app...

**Comment by axsuul** [comment]
FYI: There is no longer a `--port` option on `ember test`. It has been changed to `--test-port`.
