### ISSUE TITLE
Multiple Addons sharing the same module namespace

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-cli#1911]
I just released [ember-velocity-mixin](https://github.com/quandl/ember-velocity-mixin) it provides ember-velocity-mixin module and the actual mixin can be imported with 

```import VelocityMixin from 'ember-velocity-mixin/mixin```

My addon currently imports Velocity.js in **included** method. I'm thinking about creating a package that will provide Velocity.js and my mixin library will use it as a dependency.

My question is: **Is it possible to create a ember-velocity addon that will provide the Velocity library and for my mixin to share it's namespace?** I would like to be able to import my mixin with ```import VelocityMixin 'ember-velocity/mixin'```.

Look forward to your thoughts on this.

PS: I just finally had a chance to really play around with Ember-CLI. You guys have done an amazing job. There is nothing more impressive than showing people how easy it is to start using Ember with Ember-CLI. Thank you for all of your hard work!

**Comment by stefanpenner** [comment]
I don't believe they should ever share the same namespace, this just seems like much pain.
