### ISSUE TITLE
Loading assets in node_modules in brocfile.js

### ISSUE THREAD

**Issue by conrad-vanl** [ember-cli/ember-cli#1984]
After upgrading to 0.0.42 (and another bump to 0.0.44, but this issue started with 42) I can no longer load in assets in node_modules: 

```
app.import("node_modules/verge/verge.js");
```

Results in:

```
Path or pattern "node_modules/verge/verge.js" did not match any files [string exception]
Error: Path or pattern "node_modules/verge/verge.js" did not match any files [string exception]
    at /media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:34:15
    at $$$internal$$tryCatch (/media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$$internal$$publishRejection (/media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:395:7)
    at $$rsvp$asap$$flush (/media/storage/Sites/rocksauce-studios-v6/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:415:13)
```

**Comment by rtm** [comment]
> You can only app.import from the vendor/ or bower_components/ directories. To include a node_modules you would need to create an addon that includes it or do some manual broccoli stuff in the Brocfile

Is there any particular reason for this restriction?

**Comment by QuantumInformation** [comment]
I also prefer to import from node modules

**Comment by stefanpenner** [comment]
> I also prefer to import from node modules

use ember-browserify

**Comment by stefanpenner** [comment]
> Is there any particular reason for this restriction?

current file watcher limitations.

**Comment by QuantumInformation** [comment]
Any updates the the current file watcher limitations?

**Comment by QuantumInformation** [comment]
I've loaded `ember-browserify` and added this to my `ember-cli-build.js`

`import MyCoolModule from "npm:test-recorder";`

How then can I get access to my scripts like I was trying previously with:
  `app.import('node_modules/test-recorder/dist/emberTestRecorder.js');`

**Comment by QuantumInformation** [comment]
I tried this approach using mergeTrees in my `addon` but I don't see these files end up in the dist folder.

demo: https://github.com/QuantumInformation/ember-cli-test-recorder/tree/use-test-recorder-npm

```js

  var mergeTrees = require('broccoli-merge-trees');
  var pickFiles = require('broccoli-static-compiler');
  var extraAssets = pickFiles('node_modules/test-recorder/dist/',{
    srcDir: '/',
    files: ['**/*'],
    destDir: '/test-recorder/'
  });

  module.exports = mergeTrees([app.toTree(), extraAssets]);
```

![image](https://cloud.githubusercontent.com/assets/216566/8695600/e4713e40-2add-11e5-89f7-314aec83c617.png)

the merge trees works fine in a regular ember cli project.

**Comment by QuantumInformation** [comment]
I created a separate issue for this:

https://github.com/ember-cli/ember-cli/issues/4470
