### ISSUE TITLE
Passing options to CSS preprocessors

### ISSUE THREAD

**Issue by jas** [ember-cli/ember-cli#2010]
What is the recommended way of passing options to a CSS preprocessor? Specifically, I need to pass the `use` option to Stylus.

**Comment by abuiles** [comment]
We still need to improve our config story and I think we are aware of that, for now I think you can use https://www.npmjs.com/package/ember-cli-stylus which gives you the tools to do this.

**Comment by stefanpenner** [comment]
https://github.com/gdub22/ember-cli-less documents this:

```js
var app = new EmberApp({
  lessOptions: {...}
});
```
