### ISSUE TITLE
Problem running `ember build --environment=production` when generating multiple apps.

### ISSUE THREAD

**Issue by AdamFerguson** [ember-cli/ember-cli#2037]
I'm working on a project right now with ember-cli where an `ember serve` or `ember build` generates two distinct ember apps in the form of different .js/.css files that both share a common `index.html` file. This is roughly accomplished by creating two separate `EmberApp` instances in the project's `Brocfile.js` and then exporting the following:

```javascript
module.exports = mergeTrees([mobileApp.toTree(), desktopApp.toTree()], { overwrite: true });
```

This has all worked beautifully (testament to the great work done by the ember-cli folks that this is even possible) but I noticed there was a snag when running `ember build --environment=production` in that the fingerprints were being applied to all of the assets but the references weren't updated in `index.html`.

After a bit of debugging, it looks like broccoli-asset-rev was being run for both of the ember apps. So, the `index.html` file was being updated for both trees, but only being applied for the last tree, `desktopApp` in this case. It seems to be b/c the addon hooks into [`postprocessTree`](https://github.com/stefanpenner/ember-cli/blob/master/lib/broccoli/ember-app.js#L201) which runs per tree.

The only other hook I could see to take advantage of would be [`postBuild`](https://github.com/stefanpenner/ember-cli/blob/master/lib/models/builder.js#L101) but at that point the build is done and the tree has been written to the filesystem. So, you would probably have to invoke a separate build to even be able to run broccoli-asset-rev postBuild.

Would it be possible to add in an additional hook for addons that runs after the total tree from the brocfile has been generated but before writing it to `dist` (or whatever the outputPath is configured to be) and then have broccoli-asset-rev hook into that instead of `postprocessTree`?

I know this is outside the norm so if not doable I understand. If it is doable, I'd be glad to work on the PR.

**Comment by stefanpenner** [comment]
i've seen several apps do this, if there are remaining issues will gladly accept new issues
