### ISSUE TITLE
watch EMFILE

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#2127]
`broccoli-sane-watcher` tends to walk trees and place a new watcher on every single directory. Where `ember-cli` is only requesting that top-level directories be watched anything with deep directory nesting, or projects with many directories in general can easily hit OSX's default file descriptor limit of `256`.

I realize the simple (hack) solution to this is "increase your ulimit". However doing that persisted seems to be different for every version of OSX, and I don't think this is the right solution.

`sane` needs to not walk directories, IMO.

Related? https://github.com/stefanpenner/ember-cli/issues/901

**Comment by marclundgren** [comment]
@sandstrom @deioo, here's how I fixed the problem:
```
limit descriptors 1024
```

[apple.com - Limit on file descriptors](https://lists.apple.com/archives/java-dev/2003/Apr/msg00857.html)

**Comment by deioo** [comment]
I've installed node-watcher and it fixed all issues for me, thanks for the update @marclundgren

**Comment by marclundgren** [comment]
http://git.io/vURMV

**Comment by rdingwell** [comment]
I've been running into this issue with my ulimit set to unlimited so I'm not sure that the reason is do to the limit on file descriptors.  What I have noticed is that fseventsd seems to get in a bit of a mess and killing that service , which automatically respawns, fixes the issue.
