### ISSUE TITLE
Mechanism for passing options to StylePlugins 

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli#2129]
The only way I could figure out to pass options to a StylePlugin like broccoli-sass is:

````js
app.registry.load('css')[0].options['imagePath'] = '/my/path';
````
Surely a better way is possible?

**Comment by abuiles** [comment]
Please see comment here https://github.com/ember-cli/ember-cli/issues/2010#issuecomment-92098282   both are related.
