### ISSUE TITLE
ember test not finishing

### ISSUE THREAD

**Issue by spruce** [ember-cli/ember-cli#2139]
Hey,
dunno if I'm stupid or not. :)
when I run `ember test` it runs all the tests and also completes them all. 
I wanted to use this command for automatic checking if a deploy to the server can be done.
But I expected it to exit with code 0 or if anything goes wrong with code 1.
Maybe clarify this in the docs.
cc: #2120

**Comment by AKST** [comment]
I'm getting the same thing, it stopped blocking after I commented out the contents of the serialisers test. It was just the default test as well, which is weird. I even changed the test to throw an error immediately and it was still hanging. Currently in the process of trying to fix it for myself.
