### ISSUE TITLE
Content Security Policy Errors

### ISSUE THREAD

**Issue by Globegitter** [ember-cli/ember-cli#2174]
I just upgraded to the latest master branch version (WARP SPEED) and getting the following errors from CSP:

``` js
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
 kwift.CHROME.min.js:409
(anonymous function) kwift.CHROME.min.js:409
(anonymous function) kwift.CHROME.min.js:414
(anonymous function) kwift.CHROME.min.js:515



Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
 jquery.min.js:2
(anonymous function) jquery.min.js:2
(anonymous function) jquery.min.js:2
(anonymous function) jquery.min.js:4
```

Some more like the second error and

``` js
Refused to connect to 'ws://127.0.0.1:35729/livereload' because it violates the following Content Security Policy directive: "connect-src 'self' localhost:35729".
 livereload.js?ext=Chrome&extver=2.0.9:193
__connector.Connector.Connector.connect livereload.js?ext=Chrome&extver=2.0.9:193
Connector livereload.js?ext=Chrome&extver=2.0.9:176
LiveReload livereload.js?ext=Chrome&extver=2.0.9:862
(anonymous function) livereload.js?ext=Chrome&extver=2.0.9:1074
(anonymous function) livereload.js?ext=Chrome&extver=2.0.9:1116


Uncaught SecurityError: Failed to construct 'WebSocket': Refused to connect to 'ws://127.0.0.1:35729/livereload' because it violates the document's Content Security Policy. livereload.js?ext=Chrome&extver=2.0.9:193
__connector.Connector.Connector.connect livereload.js?ext=Chrome&extver=2.0.9:193
Connector livereload.js?ext=Chrome&extver=2.0.9:176
LiveReload livereload.js?ext=Chrome&extver=2.0.9:862
(anonymous function) livereload.js?ext=Chrome&extver=2.0.9:1074
(anonymous function) livereload.js?ext=Chrome&extver=2.0.9:1116
```

It is a pretty bare-bone ember app with a few addons and I have added no inline js myself and no idea where this jquery bug is coming from. Don't know if it's anything I am doing wrong or a bug from the cli side.

Otherwise all is looking good, getting sub 1s rebuilds (no auto-refresh though) - great work

**Comment by mgenev** [comment]
@rwjblue Hmm interesting, I get the CSP 'delivered in report-only mode' error still with 0.1.7 on a project which has been upgraded from an older one. In incognito, I indeed don't get them, but when I disabled all my extensions I still get the error, so it has to be something else.

**Comment by joostdevries** [comment]
@mgenev could you paste the complete error?

**Comment by mgenev** [comment]
@joostdevries Here you go:
The Content Security Policy 'default-src 'self' https://maps.googleapis.com; font-src *; connect-src 'self' https://maps.googleapis.com ws://localhost:35729 ws://0.0.0.0:35729; img-src *; style-src *; frame-src *; script-src 'self' 'unsafe-eval' https://maps.googleapis.com https://maps.gstatic.com localhost:35729 0.0.0.0:35729; media-src 'self';' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.

**Comment by joostdevries** [comment]
@mgenev what version of ember-cli-content-security-policy is in your package.json?

**Comment by mgenev** [comment]
"ember-cli-content-security-policy": "0.3.0"

**Comment by joostdevries** [comment]
@mgenev Looks like `ember-cli-content-security-policy` needs a version bump @rwjblue

**Comment by mgenev** [comment]
I see. I did verify - I took the index.js and the package.json from the ember-cli-content-security-policy github repo and i put them in my project and the error did go away, but NPM is behind with 0.3.0 so it's hitting people's new installations of ember-cli

**Comment by joostdevries** [comment]
@mgenev The fix with the `report-uri` has not been released yet. In the meantime you could use:
```
"ember-cli-content-security-policy": "git://github.com/rwjblue/ember-cli-content-security-policy.git#master",
```

in you package.json
