### ISSUE TITLE
Allow to remap JS libs using Petal

### ISSUE THREAD

**Issue by abuiles** [ember-cli/ember-cli#2177]
The idea is to make JS libraries easier to consume, so people can use libs written in anom-amd version and also whitelist easily the imports and exports so it doesn't conflict with the ES6 compilation process, I started to work on integration of Petal but I've been busy to complete. (https://github.com/abuiles/ember-cli/commit/d82df0420921eb517411aaca71eee784a5e2ff04)

The following are the things that need to be done to get this working:

- [X]  Write a library which allows us manipulate JS libs (see https://github.com/stefanpenner/petal and https://github.com/abuiles/broccoli-petal)
- [ ] Integrate broccoli-petal with ember-cli (see API)

## API

An initial approach would be to allow people to do something like 

```
app.import('bower_components/ember-qunit/dist/amd', { remap: 'ember-qunit' });

app.import('bower_components/famous/core', { remap: 'famous/core'' }`;
// output of this should be  https://github.com/abuiles/famous-remap/tree/master/famous-remapped for output
```

`import` should recognize remap and also get the **exports** of the library so we can whitelist them.

https://github.com/abuiles/broccoli-petal only remaps,  it doesn't extract out the `exports`, I'm still not quite sure if that's something in the filter or inside `import`.

**Comment by blessenm** [comment]
So is this now working in the current ember-cli (0.2.3)? If so after remap how do we access the module on our code?

**Comment by lightblade** [comment]
This looks great. What's blocking it from finishing?

**Comment by stefanpenner** [comment]
> So is this now working in the current ember-cli (0.2.3)? If so after remap how do we access the module on our code?

this will be closed once it is working.



> This looks great. What's blocking it from finishing?

unfortunately no-one has had time to drive this to completion, we will likely explore this after the packager work lands ourselves unless someone else wants to pursue earlier.

**Comment by stefanpenner** [comment]
will be revisited as part of the packager work

**Comment by ef4** [comment]
See https://github.com/ember-cli/ember-cli/pull/5512 as a solution for anonymous AMD.
