### ISSUE TITLE
`ember update` fails to work

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2187]
it appears the usage of yam lost the default values here: https://github.com/stefanpenner/ember-cli/blob/master/lib/cli/index.js#L53 which means https://github.com/stefanpenner/ember-cli/blob/master/lib/models/update-checker.js#L23 is by default false.

@twokul mind taking a look?

**Comment by stefanpenner** [comment]
@twokul got some time to take a look, you are likely more familiar with the yam stuff

**Comment by stefanpenner** [comment]
@twokul ^^

**Comment by twokul** [comment]
@stefanpenner `checkForUpdates` is `false` by default b/c it's not defined in `.ember-cli` settings file in blueprints. should it be on by default?

**Comment by stefanpenner** [comment]
I believe so yes

**Comment by stefanpenner** [comment]
I believe so yes
