### ISSUE TITLE
Cryptic Error (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#2226]
Seeing a weird error in the Ember CLI console

```
(CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

And each time I relaunch it keeps adding that line.

Any insight into what this means?

OS X Mavericks 10.9.5

```
ember server --proxy http://0.0.0.0:3000/
version: 0.1.1
Proxying to http://0.0.0.0:3000/
Livereload server on port 35729
Serving on http://0.0.0.0:4200
2014-10-06 11:52 ember[23137] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2014-10-06 11:52 ember[23137] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2014-10-06 11:52 ember[23137] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2014-10-06 11:52 ember[23137] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by Aathi** [comment]
@stefanpenner 
![tamilhub-frontend_ _bash_ _202x55](https://cloud.githubusercontent.com/assets/5355180/6397357/697783fe-bde4-11e4-8a62-cfc725a64cab.png)
 I've been running into the same issue on OS X 10.10

**Comment by sir-dunxalot** [comment]
@Aathi I haven't experienced this issue since installing [Watchman](https://facebook.github.io/watchman/), which is now recommended for Ember CLI. Try that.

**Comment by granteagon** [comment]
@Aathi if you are using sublime, make sure you are not watching files unnecessarily.  https://github.com/gruntjs/grunt-contrib-watch/pull/398

**Comment by Aathi** [comment]
@sir-dunxalot  @granteagon  thank you. :+1:

**Comment by meltingice** [comment]
Just throwing it out there, adding `tmp/*` to my Sublime Text `folder_exclude_patterns` fixed it. Just make sure you restart Sublime Text first.

Either way, installing Watchman is the better solution.

**Comment by stefanpenner** [comment]
> Just throwing it out there, adding tmp/* to my Sublime Text folder_exclude_patterns fixed it. Just make sure you restart Sublime Text first.
> 
> Either way, installing Watchman is the better solution.

hopefully in the next month or two, we will finally move tmp -> system tmp.

**Comment by carloscheddar** [comment]
Thanks @meltingice adding that and restarting sublime fixed the issue which was still occurring after installing watchman.

**Comment by mattsmith** [comment]
@stefanpenner Fixed by just restarting Google Chrome.  

Added folder_exclude_patterns from here http://www.ember-cli.com/#sublime-text to see it fixes it longer term.

**Comment by MiracleBlue** [comment]
I've just figured out a fix that worked for me when running into this issue when I restart ember server rapidly - rm -rf tmp in the app directory, and then run ember server again, and that fixes it.

**Comment by rafael-paiva** [comment]
I had this same issue using Sublime Text and Ember CLI. Excluding "tmp" directory by adding it to the "folder_exclude_patterns" in Sublime seems to be the fix for me.

Thanks @sir-dunxalot: https://github.com/ember-cli/ember-cli/issues/2226#issuecomment-62499068
Ember CLI documentation: http://www.ember-cli.com/#sublime-text

**Comment by gneale** [comment]
Visual Studio Code may give the same problem as sublime

**Comment by solex16** [comment]
For Sublime Text 2 I tried the "folder_exclude_patterns" list in 
Ember CLI documentation: http://www.ember-cli.com/#sublime-text
but still same errors.

Only when I added "tmp/*" too did it fix the issue..

**Comment by mangatinanda** [comment]
Had same issue, adding "folder_exclude_patterns" in Sublime settings and restarting sublime fixed the issue for me.

Thanks @rafael-paiva

**Comment by alexloi** [comment]
Experienced this error after uninstalling watchman due to some other unrelated issues. Re-installing watchman solved it, in case someone else stumbles on this.

Error message was :
```
(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
``` 
x1000 in the terminal

**Comment by Evana13G** [comment]
I am having the same issue as well: 

version: 0.2.7
2015-09-01 11:38 ember[59134] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Livereload server on port 35729
Serving on http://localhost:4200/
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EMFILE
  at exports._errnoException (util.js:746:11)
  at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)

**Comment by stefanpenner** [comment]
> version: 0.2.7

@Evana13G  this version is quite outdated, i would strongly recommend upgrading to 1.13.8 and the latest watchman (3.7 as of right now)

**Comment by dianafa** [comment]
for me reboot helped

**Comment by kyrsten** [comment]
I had this same problem, the solution from @strukturedkaos fixed it for me.

osx: 10.10
ember-cli: 2.4.3
node: 0.12.7
npm: 2.15.6
sublime: build 2221

> Then I added the following to the Preferences.sublime-settings:
>`"folder_exclude_patterns": [".svn", ".git", ".hg", "CVS", "tmp/class-*", "tmp/es_*", "tmp/jshinter*", "tmp/replace_*", "tmp/static_compiler*", "tmp/template_compiler*", "tmp/tree_merger*", "tmp/coffee_script*", "tmp/concat-tmp*", "tmp/export_tree*", "tmp/sass_compiler*"]`
> and re-opened the project in Sublime

**Comment by herzzanu** [comment]
If anyone else sees this, this fix solved it for me https://github.com/react-community/create-react-native-app/issues/281#issuecomment-313813657
