### ISSUE TITLE
Making build errors hookable from addons

### ISSUE THREAD

**Issue by fivetanley** [ember-cli/ember-cli#2249]
I'd like to be able to access build errors from external plugins. For example, suppose I had a handlebars template compilation error. You can usually see the output in the build, which is fine, but if you have the build in another terminal window / tmux pane / desktop you won't notice it and wonder why your app isn't updating. It'd be cool if this was exposed via plugins so we can hook into various os level apis,such as growl, tmux notifications, windows, etc.

I'm willing to figure this out and do the work for it but figured I'd open an issue before investing time in it.

(side note; i'm not saying we add these kind of notifications in core right now, rather make it hookable through addons so the addons can do the notifying)

**Comment by stefanpenner** [comment]
not apposed to this, will accept and RFC or a good PR
