### ISSUE TITLE
Renaming an Ember CLI Project

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#2251]
Hi guys!

Quick Q:  Is there a protocol in place for renaming an entire Ember-CLI project?

I renamed it in `package.json`.

I got some errors, so I updated the modulePrefix in `config/environment.js` to be the same as the name.

Everything is working now - just wanna be sure that's all I need to do?  Don't want this to come back as an issue down the track.

Thanks!

hx

**Comment by Benjy1979** [comment]
Always seems a PITA to copy an ember folder and put it under a different name. 
ember init didn't work. 

I've changed the module name in config/environment.js, I've respecified the files in index.html deleted tmp folder, reinstalled node_modules (straw clutching), and still it's building the previous name so the files in index.html are not present.

What actually is it that determines the compiled css and .js name?

**Comment by tdiddi** [comment]
> `ember init` after renaming package.json should be sufficient.

Didn't work out for me as well. This worked for me:
Here are the locations of where the app name is excluding things that you have created, i.e. these are the locations where ember-cli puts your app name by default:

_package.json:_

`"name": "...",`

_environment.js:_

`modulePrefix: '...',`

_bower.json_

`"name": "...",`

_app/index.html_

```
<link rel="stylesheet" href="assets/....css">
<script src="assets/....js"></script>
```

_tests/index.html_
```

<link rel="stylesheet" href="assets/....css">
<script src="assets/....js"></script>
```

Replace `...` with your new app name.

[Tribute to: Source](https://stackoverflow.com/a/32814800)

After that I deleted `/tmp` and `/dist`
