### ISSUE TITLE
Calling `beforeInstall` on the controller blueprint causes errors

### ISSUE THREAD

**Issue by kimroen** [ember-cli/ember-cli#2255]
In several of the generators in `ember-cli-coffeescript`, we run `this.lookupBlueprint` as a sort of `super`. For the controller, [this](https://github.com/kimroen/ember-cli-coffeescript/blob/b6a0a78aa23e39c5bd196f5941100e3c3295d9c8/blueprints/controller/index.js#L8-10) doesn't work:

```js
beforeInstall: function(options) {
  this.lookupBlueprint('controller').beforeInstall(options);
},
```

This particular one errors out with a warning, as documented in #2134 and kimroen/ember-cli-coffeescript#19

```
TypeError: Cannot read property 'writeLine' of undefined
```

This error stems from [this line](https://github.com/stefanpenner/ember-cli/blob/659c8d69da8b1e2569e1f9d58dfc0591e2d7c1ca/blueprints/controller/index.js#L25) in the called blueprint:
```js
beforeInstall: function(options) {
  ...
  if (!type && !options.installingTest) {
    this.ui.writeLine(chalk.yellow('Warning: no controller type was specified, defaulting to basic. Specify using --type=basic|object|array'));
  }
},
```

`this.ui` is defined in the `install`-hook of the `Blueprint`-model: https://github.com/stefanpenner/ember-cli/blob/659c8d69da8b1e2569e1f9d58dfc0591e2d7c1ca/lib/models/blueprint.js#L320-L327

I can work around it by adding this to the ember-cli-coffeescript controller blueprint:

```js
install: function(options) {
  return this.lookupBlueprint('controller').install(options);
},
```

But that feels very unnecessary and unintuitive.

I'm not sure where to start to fix this, but maybe doing something about the logic in [the generator task](https://github.com/stefanpenner/ember-cli/blob/b6b8dd6cd12a450e20d412ce9a02ab53631bfee7/lib/tasks/generate-from-blueprint.js) or separating out the assigning of properties (it's used several places, so it should probably be abstracted anyway).

I'll deploy the workaround to ember-cli-coffeescript so generating controllers without the type defined will start working again, but it's obviously a very unstable solution.

Thanks to @rwjblue for suggesting the workaround :heart:

cc @jgwhite

**Comment by buschtoens** [comment]
@stefanpenner Why was this issue closed? It wasn't fixed.

Also, @rwjblue's workaround can't always be applied, as it is the case with https://github.com/Vestorly/ember-cli-emblem/issues/25. Doing so would generate/delete `.hbs` templates instead of the `.emblem` templates.

**Comment by stefanpenner** [comment]
@buschtoens because it was stale, thank you for an actionable example.

**Comment by buschtoens** [comment]
@stefanpenner You're welcome. :)

I'm prepping a temporary fix for `ember-cli-emblem` right now.
