### ISSUE TITLE
Addon: import own stylesheet (not vendored), possible ?

### ISSUE THREAD

**Issue by jeromeschneider** [ember-cli/ember-cli#2258]
Hi,

I'm building an ember-cli addon, and cannot find the way to import a stylesheet that is not vendored (that the addon owns); I have not found this information in http://www.ember-cli.com/#developing-addons-and-blueprints.

My addon's index.js looks like this:

``` js
// index.js
module.exports = {
  name: 'ember-cal',
  included: function(app) {
      this._super.included(app);
      app.import(app.bowerDirectory + '/momentjs/moment.js');
      app.import('app/styles/mycss.css'); // doesn't work
      app.import('styles/mycss.css'); // doesn't work neither
  }
};
```

What am I missing ? :)

**Comment by MiguelMadero** [comment]
For reference to others reading this. Creating `addon/styles/app.css` adds this to vendor.css on the app.

**Comment by knownasilya** [comment]
Does that work with CSS preprocessors?

**Comment by MiguelMadero** [comment]
I tried only ember-cli-less and I couldnt get this to work. I will give it another go. 
Im thinking this would require modifying the tree.

**Comment by MiguelMadero** [comment]
@knownasilya for less it was a bit different. I had to put all my styles under the app folder (it didn't work if I leave them in the addon folder) and then I reference them from the app's app.less. See an example [here](https://github.com/softlayer/sl-ember-components#how-to-use-this-addon-in-your-application). 

I would imagine that it will be similar with Sass. 

If I really wanted to leave them on the addon folder, I guess I could just `pickfiles` and move them. I was expecting Ember CLI to do this OOB, but there might a reason not to. Also, I was thinking of doing it in a way that we can remove the .less dependency, so if someone wants pure CSS or are using a different preprocessor, they could opt-in to an addon-name.css file.

**Comment by knownasilya** [comment]
@MiguelMadero if ember-cli-less was added to the addon's deps shouldn't it run (like the htmlbars on for templates)?

**Comment by MiguelMadero** [comment]
@knownasilya I tried this and it didn't make a difference. I checked their [README](https://www.npmjs.com/package/ember-cli-less#usage-in-addons), but I still couldn't get it to work.
