### ISSUE TITLE
Addon initialization confusion in codebase

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#2288]
I want to open this issue up for discussion as I keep seeing things that are related and to me, it's hinting at a larger problem that should be resolved before implementing lots of work arounds and "hacks" in the codebase / addons. 

From a [quick search](https://github.com/stefanpenner/ember-cli/search?p=1&q=initializeAddons&utf8=%E2%9C%93), there are 6 places I count where `Project.prototype.initializeAddons` is called. This has caused a few issues and it bound to cause more going forward because of all the various places it's possible for addons to be initialized and uncertainty about what's available to them. In a perfect world, this should be called in 1 place so that it's always known exactly when they are being initialized and within what context. A few issues/prs that I believe relate to this are here: #2287 #2271 and #2279 

In my mind, and addon should be initialized with `this.project` and `this.app` set. This way it has access to all information related all of the time and there's no confusion about what it can do with that. This seems like it could be possible as(at least currently) addon's are only used within an ember-cli project. Therefor it *should* always a project *and* app available. When any ember based command is run, it will locate the app and project, initialize those, and pass them in to the addons when it initializes them. This seems easy on the surface and I'd be happy to take a look at trying to implement this if there aren't any major problems I'm not thinking about. 

Thoughts?

**Comment by stefanpenner** [comment]
we are making incremental improvements here, and are aware of the issues. Slowly making progress, I think this issue can be closed as it is an ongoing effort.
