### ISSUE TITLE
Initializer Container Lookup Fails unless setTimeout is used

### ISSUE THREAD

**Issue by jme783** [ember-cli/ember-cli#2292]
I have created an initializer in `initializers/application.js` that is as follows:

```
export default {
  name: 'application',
  initialize: function(container) {

      var store = container.lookup('store:main');
      store.find('bag').then(function(bags) {
        ...
        }
      });
  }
};
```

This function returns an error as `container.lookup('store:main')` returns nil. The only way I've found to get this working was adding a short setTimeout that surrounded the lookup as follows:

```
export default {
  name: 'application',
  initialize: function(container) {

    setTimeout(function() {
      var store = container.lookup('store:main');
      store.find('bag').then(function(bags) {
        ...
      });
    },10);
  }
};
```

My senses tell me this is not an ideal way to go about this. Either I'm doing something wrong or there is an issue with the initializers being loaded before the container is ready. Thoughts anyone?

**Comment by atomkirk** [comment]
@stefanpenner You guys should update the docs. http://emberjs.com/api/classes/Ember.Application.html#method_initializer

![](http://d.pr/i/1diu8/5KcwXRQX+)

**Comment by atomkirk** [comment]
It looks like the docs are updated in the actual code base on master. How come that isn't reflected on the website?

**Comment by stefanpenner** [comment]
> It looks like the docs are updated in the actual code base on master. How come that isn't reflected on the website?

this doesn't seem like an ember-cli question.

**Comment by atomkirk** [comment]
Oh, my mistake. I will ask over there why the docs aren't updated.
