### ISSUE TITLE
Split addon development docs

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-cli#2300]
The section on "developing addons and blueprints" has gotten quite large and will probably need to grow further to completely cover all information required for addon development.

It's probably best to move this entire section to a sub-page of either **ember-cli.com** or **emberaddons.com** where we give extensive information to addon developers. That way, ember-cli.com can focus on consumers of ember-cli and we have another page geared towards authors.

Sections
- Getting started
- Project structure
- Package.json
- Addon entry point + Hooks (with arguments + return value)
- Blueprints
- Testing addons
- Publishing

I am **very** open to discussion about all of the above.

**Comment by stefanpenner** [comment]
@joostdevries closing this in-favor of your latest proposal
