### ISSUE TITLE
Livereolad, ignore .git/index.lock

### ISSUE THREAD

**Issue by marcemira** [ember-cli/ember-cli#2311]
I'm using sublime-text, and every time I open a file o change a tab ember serve does re-compile showing:

file added .git/index.lock
file deleted .git/index.lock

Build successful - 292ms.

Any toughs? It seems to be triggered by something like last open/seen meta on file.. 
Cheers :)

**Comment by aceofspades** [comment]
@marcemira Did you ever figure this one out? I'm getting it continuously after 0.1.12 upgrade

**Comment by stefanpenner** [comment]
@aceofspades something appears to be watching the root of your dir, incorrectly.

We likely should add watched roots to the future ember-cli doctor command cc @chadhietala
