### ISSUE TITLE
__name__ directory does not include sub-directories

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2319]
When you are authoring a blueprint and your structure is like the following:

```
   files/
        app/
            __name__/
                 someDir/
                    .gitkeep
                 someJs.js
```

`someDir` does not get copied. This is easily replicable by doing `ember g blueprint someBluePrint`, the `files` directory does not get copied. I verified this against master.

**Comment by stefanpenner** [comment]
@chadhietala is this still and issue?

**Comment by chadhietala** [comment]
@stefanpenner haven't tried, I don't have this use case anymore.  Will close for now.
