### ISSUE TITLE
Docs on ic-ajax use-cases 

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-cli#2321]
Refs #1548 

Since we're including this by default (which I think is a good idea), we need to have some docs on how to benefit from this. Adding docs on a `defineFixture` use-case for testing is one example. Another would be to teach people to modify their adapters + manual ajax calls to use ic-ajax.

**Comment by et** [comment]
Not sure why this was closed, but I agree with @joostdevries. Trying to write an acceptance test that depends on a backend responding with data would probably use `defineFixture` but I've yet to be able to find docs that demonstrate how this is used.

I'd gladly help, but I can't even get `defineFixture` to work.

**Comment by bf4** [comment]
fwiw, I came across this while writing a test.  My specific case (simplified below) is

```es6
import { defineFixture, lookupFixture } from 'ic-ajax';
var doc = Doc.create();
var entries = [{name: 'basket weaving'}]
defineFixture(doc.jsonURL, {
  response: {"entries" : entries},
  textStatus: 'success',
  jqXHR: {}
});
doc.fetchData(function(entries) {
    assert.equal(entries, lookupFixture(doc.jsonURL).response.entries);
});
```

**Comment by bf4** [comment]
Ref: https://github.com/emberjs/rfcs/pull/17

**Comment by ballPointPenguin** [comment]
How do I use ic-ajax in my code?
I was using Ember.$.ajax and thought it was the right thing to do, but I guess it is not..?
I am confused.

**Comment by jcope2013** [comment]
@ballPointPenguin ember-cli-ic-ajax is now deprecated in favour of ember-ajax. https://github.com/ember-cli/ember-cli/pull/4656 https://github.com/rwjblue/ember-cli-ic-ajax/pull/15 https://github.com/embersherpa/ember-ajax

**Comment by ballPointPenguin** [comment]
Thanks @jcope2013 . It would appear that ember-ajax is designed for ember 1.13+. I am working on a project that is on 1.10 (for now). I will see if switching to ember-ajax breaks anything.
