### ISSUE TITLE
Add separate directory under /server for hooking http server (similar to /routes)

### ISSUE THREAD

**Issue by blesh** [ember-cli/ember-cli#2328]
On the heels of #2302... 

I think it would be a very good idea to offset the hooking up middleware to another directory similar to how Ember-CLI is currently handling express routes.

Currently, while I'm waiting to be able to update to the latest Ember-CLI and have access to #2302, I'm actually leveraging a "route" to set up a WebSocket on another port.

My hackery looks something like:

```js
module.exports = function(app) {
  var server = http.createServer(app);
  server.listen(SOME_OTHER_PORT);

  var wss = new WebSocketServer({
  	server: server,
  	path: '/mysocketstuffs',
  });
}
```

The advantage here is when I upgrade, I have greater confidence the upgrade will not trample my work. Where if it's in `server/index.js` it will almost definitely require some manual intervention.

I don't really have any preference for how this is done. I would just like it as a feature I guess. If there is a preferred method, let me know.

### EDIT

clarification on why I'm waiting.

**Comment by stefanpenner** [comment]
> During the init, the server/index.js will be blown away or need to be merged, where the "routes" (now "mocks" and "proxies") will not.

ah, i see. We basically want a `thinner` generated piece of code here, to prevent the tech-debt that the larger blobs currently produce.

**Comment by blesh** [comment]
:+1:

**Comment by stefanpenner** [comment]
seems to have gone stale, if someone is interested a detailed RFC is a good starting point, from their and PR or implementation.
