### ISSUE TITLE
Fingerprinting adjustment not applied to image links in css included via addon

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#2344]
My addon, ember-cli-jquery-ui, imports images from jquery-ui installed in the bower directory. It also includes css files from the same location. The images are fingerprinted in production builds, but the included css files in those production builds continue to point to filenames without the fingerprint.

I am currently working around the issue by disabling the fingerprinting of the image files. Once I do this, the images appear in the example app.

Github repo for addon: https://github.com/Gaurav0/ember-cli-jquery-ui
Github repo for example app using addon: https://github.com/Gaurav0/ember-cli-jquery-ui-example

To reproduce the issue:
    
1. Clone the example repo from https://github.com/Gaurav0/ember-cli-jquery-ui-example
2. Remove the following code from the example app repo's Brocfile.js:

    ```
    fingerprint: {
        exclude: ['assets/images']
    }
    ```

3. Build the example repo for production:

    ```
    ember build --environment=production
    ```

4. Copy the dist/ folder to a web server.
5. Notice that the images do not appear.
6. Open web browser console 'Network' tab.
7. Notice that images are requested without fingerprint and 404 errors result.

**Comment by wheany** [comment]
Our project has jquery-ui under vendor/ and the same issue also affects css files imported from there.

**Comment by stefanpenner** [comment]
If this is sitll an issue, I believe it to be in broccoli-asset-rev.
