### ISSUE TITLE
Addon dummy app doesn't seem to support SCSS like a normal app.

### ISSUE THREAD

**Issue by go1dfish** [ember-cli/ember-cli#2348]
It seems like the dummy app used for ember addon development does not support SCSS in the same way as normal ember app development.

This makes it more difficult to to develop SCSS to include with reusable components than it should be.

**Comment by stefanpenner** [comment]
may be fixed with nested-addon support. That being said, `dummy` is kinda quirky so it may not be fixed yet...

**Comment by yaymukund** [comment]
Yo I documented it here: https://github.com/yaymukund/ember-cli-sass/tree/document-addon-usage#addon-usage

It's pretty arcane, yeahhhhh. I still don't know why the `_included` step works.. I vaguely understand it has to do with the config load order changing with the introduction of nested addons (in 0.2.0).

**Comment by eccegordo** [comment]
> That being said, dummy is kinda quirky so it may not be fixed yet...

Is there any convenient high level overview of the specific ways dummy app differs normal app tree?

I am trying to develop an addon and it seems my mental model of how a dummy app should work is definitely incongruent with reality, especially with styles and preprocessors.

**Comment by stefanpenner** [comment]
> Is there any convenient high level overview of the specific ways dummy app differs normal app tree?

not really, but the only differences are outlined here https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-addon.js#L26-L42

**Comment by sdhull** [comment]
FWIW it worked for me after I did `ember i ember-cli-sass -S` & had `dummy/app/styles/app.scss` in place
Defining `included` as suggested causes other strange problems, possibly from other addons
