### ISSUE TITLE
Preprocessing addons doesn't work

### ISSUE THREAD

**Issue by davewasmer** [ember-cli/ember-cli#2354]
I've created a [demonstration repo](https://github.com/davewasmer/ember-addon-coffeescript-test) to illustrate the issue. It contains an empty Ember app, freshly generated from the CLI (v0.1.2), with an addon (also generated with v0.1.2) that contains three files:

* `/app/controllers/bar.coffee`, which imports the other two files;
* `addon/bat.js` which exports a simple POJO as a basic test
* `addon/foo.coffee` which exports a simple POJO as a basic test

After a whole bunch of logging and tracing, it looks like the Registry for the Addon doesn't pick up the Coffeescript compiler - the glob that is built to look for files in the `/addon/` directory only checks for `.js` and `.em`.

I'm continuing to dig, but there's a lot of code to familiarize myself with, so I figured I'd post here in case it was an obvious fix.

**Steps to reproduce**

Run the demonstration repo (copy/pastable):

```sh
git clone git@github.com:davewasmer/ember-addon-coffeescript-test.git && cd ember-addon-coffeescript-test
npm install
bower install
ember s
```

**Expected Result**

The built app (`/dist`) should contain a controller called `bar` which imports from `addon-using-cs/bat` and `addon-using-cs/foo`.

**Actual Result**

Build fails:

```sh
ENOENT, no such file or directory '.../ember-addon-coffeescript-test/tmp/tree_merger-tmp_dest_dir-uy3fD5ba.tmp/addon-using-cs/foo.js'
```

And looking at the output in that tmp directory, it appears that the JavaScript file (`/addon/bat.js`) was picked up correctly, but not the Coffeescript one (`/addon/foo.coffee`):

```
$ cat vendor/addons.js
eval("define(\"addon-using-cs/bat\", \n  [\"exports\"],\n  function(__exports__) {\n    \"use strict\";\n    bat = {\n      fizz: \'bat\'\n    };\n\n    __exports__[\"default\"] = bat;\n  });//# sourceURL=addon-using-cs/bat.js");

;eval("define(\"addon-using-cs\", [\"addon-using-cs/index\",\"exports\"], function(__index__, __exports__) {\n  \"use strict\";\n  Object.keys(__index__).forEach(function(key){\n    __exports__[key] = __index__[key];\n  });\n});\n//# sourceURL=__reexport.js");
```

**Comment by aceofspades** [comment]
+1

**Comment by chadhietala** [comment]
I believe #2381 fixed this.  Feel free to reopen if I'm wrong.

**Comment by curtislinden** [comment]
Hi - this does not appear to be functioning in ember 0.2.3 with the 'addon' directory

I made an addon with a coffee file and it does not get included but a js file does get included.

It is functional with the 'app' directory

**Comment by davewasmer** [comment]
@curtislinden do you have `ember-cli-coffeescript` installed as a dependency (not a devDependency) of the addon project?

**Comment by curtislinden** [comment]
no.. that must be the issue. It's a devDependency
