### ISSUE TITLE
Proposal: add opt-in jscs support

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#2359]
I just created [broccoli-jscs](https://github.com/kellyselden/broccoli-jscs) for my project, and it works great as an addition to my Brocfile.js. Would this be a desirable opt-in addition to ember-cli? I envision there being an empty json object in a .jscsrc file at the root level. I added a short-circuit for this starting case, meaning since there are no rules, it doesn't do any processing or initializing. I could do the pull request if this is something you guys are interested in.

Here's how it looks in my Brocfile.js:

```
module.exports = mergeTrees([
  app.toTree(),
  jscs(
    pickFiles('app', {
      srcDir: '/',
      files: ['**/*.js'],
      destDir: '/'
    }), {
      esnext: true,
      configPath: '.jscsrc'
    }
  )
]);
```

**Comment by zeppelin** [comment]
@stefanpenner how about enabling jscs for addons by default? Unlike app code, most addons meant to be public, so it would make sense to nudge them towards common syntax rules

**Comment by zeppelin** [comment]
also, it'd be great if ember's jscs settings were extracted into a package to avoid duplication & ensure sync

**Comment by rwjblue** [comment]
@zeppelin - I am working on an addon that enforces a style guide. Should have something to look at in the next few days.

**Comment by zeppelin** [comment]
@rwjblue :heart:
