### ISSUE TITLE
Add ability to reload CSS without reloading the whole page

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#2371]
I've submitted [a PR to broccoli-sane-watcher](krisselden/broccoli-sane-watcher#13) that will provide the set of changed files in the `change` event. We can inspect this and tell LiveReload to only reload the CSS if only CSS files have changed.

I'm happy to do this, but the question is how to handle CSS preprocessors. For example if I use SASS then I need to check for changes to `\.(scss|sass)$`, but if I'm using LESS then I need to check for `\.less$`. Obviously we can just provide a list of file extensions that covers the current CSS preprocessors, but it would be better to be able to get this information from the Registry.

I can get this information from the Registry (I'd need to capture it in the `StylePlugin` but that's fine), but what I can't see is how I can get ahold of the registry from the livereload-server.js.

Any suggestions?

**Comment by pixelhandler** [comment]
This would be great :+1:

**Comment by rwwagner90** [comment]
What's the status on this? I can try to help out, but not sure how much help I would be.

**Comment by stefanpenner** [comment]
> What's the status on this? I can try to help out, but not sure how much help I would be.

we are re-working the internal build system to better provide selective builds. Once that lands we will likely dig in. If someone wants to make this work before, they are welcome to submit. If the PR is reasonable we will accept it.

**Comment by aexmachina** [comment]
I have been using ember-cli-styles-reloader as an interim solution and it appears to work well.

**Comment by oligriffiths** [comment]
@stefanpenner What's the progress on this?

**Comment by rwjblue** [comment]
@oligriffiths - This is being replaced by #5165.
