### ISSUE TITLE
Please provide docs for `content-for` helper and how to use/disable it.

### ISSUE THREAD

**Issue by gryzzly** [ember-cli/ember-cli#2407]
Right now, if you use `ember init` or `ember new app` the app `index.html` will have the following content:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TestApp</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/test-app.css">
  </head>
  <body>
    {{content-for 'body'}}

    <script src="assets/vendor.js"></script>
    <script src="assets/test-app.js"></script>
  </body>
</html>
```

Grepping for `'body'` or `"body"` doesn't bring any results, googling for `content-for` only brings up one closed issue https://github.com/stefanpenner/ember-cli/issues/2118

There's a link to [npm ember-cli-inline-content](https://www.npmjs.org/package/ember-cli-inline-content) but the `package.json` file doesn't seem to include that module as a dependency.

I'm writing my first app with ember, but it started without the use of ember-cli, so I'm trying to port the older code to modules etc. I only want to use parts that I need and understand from the stuff that ember-cli generates.

I'd be happy for a bit more directions on where to dig and will be happy to open a PR with attempted fix for the docs once I figure it out.

**Comment by Hipjea** [comment]
@bakura10 thanks for the tip, you saved my evening... oops, my night ! :)

**Comment by bakura10** [comment]
You're welcome :D

**Comment by olivierlacan** [comment]
I was surprised by finding content-for statements all over the application.html with no obvious calls to populate these hooks anywhere, and no files that they seemed to pull from. 

It makes it quick difficult to understand how they should be used, and the current documentation is [far from helpful on the subject](https://ember-cli.com/user-guide/#appindexhtml):

> The app/index.html file lays the foundation for your application. This is where the basic DOM structure is laid out, the title attribute is set, and stylesheet/javascript includes are done. In addition to this, app/index.html includes multiple hooks - {{content-for 'head'}} and {{content-for 'body'}} - that can be used by addons to inject content into your application’s head or body. These hooks need to be left in place for your application to function properly however, they can be safely ignored unless you are directly working with a particular addon.

Worse, a quick search for `ember content-for` brings up a mildly useful StackOverflow thread and... this issue: 

![image](https://cloud.githubusercontent.com/assets/65950/17645238/d7d14cd0-616d-11e6-8ccc-d10297a39681.png)

This is quite a rough initial experience with what appears to be the recommended way to inject content into the application template. I'd love to help document it better in guides but I wonder if this wouldn't be better explained by being used in the initial application in obvious ways.

**Comment by nathanhammond** [comment]
@olivierlacan Our current documentation can be found inline and extracted here: https://ember-cli.com/api/classes/EmberApp.html#method_contentFor

We would be glad to help you land a PR to improve the documentation in ways you think are useful!

Note that this is a hook which is only implemented by addons. It's not intended to be used by the application itself. The application itself can simply modify its own `index.html` file.

**Comment by tastycode** [comment]
The issue is that someone looking at their `index.html` might guess that these content-for blocks are dynamic. (Which is true). Someone looking to conditionally insert a 3rd party Javascript Library for a single page for example, might think that there is some way to override this, for example:

```handlebars
<!--app/components/share-widget/template.hbs-->
{{#content-for 'head'}}
    <script src="http://twitter/widget/js"></script>
{{/content-for}}

<div data-twitter-widget></div>
```

It would be reasonable for someone to then search around how to define the `content-for` blocks that are being generated by `content-for 'head'`, which will lead them here. 

This is especially confusing because many people who use ember come from rails backgrounds, and the above is precisely how the Rails version of content-for works: http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for

**Comment by nathanhammond** [comment]
@tastycode Would you be willing to extract the documentation to ember-cli.com (via https://github.com/ember-cli/ember-cli.github.io)?

**Comment by tastycode** [comment]
@nathanhammond I'm not clear that there is any documentation to extract?

My understanding is `content-for` is only usable for addons. Someone who just installed ember for the first time, and wants to make conditional changes to the `head` would have to go through the guide at https://ember-cli.com/extending/#detailed-list-of-blueprints-and-their-use,  and see instructions on how to use `ember generate in-repo-addon head-tag-customization`. 

I don't think that's what you mean by extracting the documentation to ember-cli.com

Just to clarify my original point. It's totally reasonable for someone looking at their index.html to believe that `content-for` is a way to dynamically figure `head` tags. It's then reasonable for them to look for documentation for it (which there really isn't much other than unit-level docs https://ember-cli.com/api/classes/EmberApp.html#method_contentFor) The documentation they find there doesn't support the reasonable inference that "this is some way to customize the head tags". So it's a dead end. 

Do you mean, create a guide for using the `content-for` tag by creating your own in-rep-addons?

**Comment by nathanhammond** [comment]
@tastycode I've spent so long in this ecosystem that I'm completely unfamiliar with the perspective of somebody coming fresh to Ember. In most cases people should simply directly customize their `index.html` file themselves. You're correct that conditional customization will require an in-repo-addon.

My goal is to make a cookbook type item like that more accessible to a broader audience and I don't trust myself to write it. The documentation inline for `contentFor` could be improved and some prose could also be written to explain the step-by-step solution.

**Comment by kevinansfield** [comment]
I've also just ended up here after looking for some documentation on how to conditionally customise index.html - in our case we have a requirement to have different favicons and external stylesheets dependent on the build environment.

Am I correct in my parsing of this discussion that the only way to do this at present is to create an in-repo-addon?

**Comment by rwjblue** [comment]
> Am I correct in my parsing of this discussion that the only way to do this at present is to create an in-repo-addon?

Yes, that is the easiest/best way to do this right now.

**Comment by BryanCrotaz** [comment]
> @olivierlacan Our current documentation can be found inline and extracted here: https://ember-cli.com/api/classes/EmberApp.html#method_contentFor

That page no longer has any reference to `contentFor`

**Comment by yagni** [comment]
@BryanCrotaz Looks like it moved into the Addon class [here](https://ember-cli.com/api/classes/addon#method_contentFor)
