### ISSUE TITLE
@import CSS being removed on build files

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#2408]
This issue is related to, but different to #982.

We have some bower components that have CSS containing relative paths to images and fonts contained in the bower component (select2 and foundation-icon-fonts). To get these to work in our build we have been copying these directories into `/assets` and then use `@import` statements to bring in the CSS in such a way that the relative paths still work.

This all works great until we get to the production build, where broccoli-clean-css sees these as invalid `@imports` because it's given a `relativeTo` parameter of `app/styles`, and these files don't exist in `app/styles`.

- If I move these directories into `app/styles` they are still removed and aren't inlined into the minified CSS
- If I set `minifyCSS.options.processImports` to `false`, the `@import`s are still removed
- I've tried using `app.import()` and just listing all of the files that I need, but these files get revved in the production build, and the CSS still refers to the original un-revved file names

The workaround that I have for now is to `npm install --save-dev broccoli-csso` to bypass the broccoli-clean-css plugin, but I'm wondering what's the right solution to this problem?

**Comment by stefanpenner** [comment]
seems to have gone stale. If someone can provide a reproduction on latest, we can reopen an investigate
