### ISSUE TITLE
Build for production creates cachebusting image names but CSS is unchanged.

### ISSUE THREAD

**Issue by jdhines** [ember-cli/ember-cli#2415]
When using `ember build --environment=production` all the images file get the cache-busting string appended to their name. But the reference in my SCSS files doesn't change (like for a background image), so the image is not found.

Am I putting my images in the wrong folder? Is there a way to tell build to not touch certain images? 

I'm following the recommendation here for where to put my images and how to reference them in my CSS: http://www.ember-cli.com/#asset-compilation

**Comment by devinrhode2** [comment]
So, for me it was as easy as making sure all my image names had the full path hardcoded before it. This made broccoli-asset-rev recognize and rewrite the url.
