### ISSUE TITLE
Tests fail: "Error: Assertion Failed: Cannot call get with 'currentPath' on an undefined object."

### ISSUE THREAD

**Issue by adamesque** [ember-cli/ember-cli#2440]
There's already an issue open with the same error message (#1203), but it's old enough that I'm not confident the root cause is the same.

I'm running 0.1.2, following the current docs, and have generated a brand-new project. As the docs recommend, I'm using an http-mock instead of fixture data. I've generated an ApplicationAdapter and set the `namespace` to "api" to match the default mock path. I've also generated a route, a model for that route, and an acceptance test to exercise them all. 

When I run the dev server and hit my route, everything works fine. But when I run the acceptance test that exercises the route, I get the following error: 

```
Error: Assertion Failed: Cannot call get with 'currentPath' on an undefined object.
```

After some research, I get that this happens because the test environment isn't running the mocks server, so the request to /api/whatever fails (and the test helper barfs). I see there's a lot of discussion about this in #1423, but it's not clear what the recommended workaround is. As it stands, I feel like the Ember-CLI docs kinda ran me off a cliff.

For now it seems like #1539 is the easiest answer: have testem proxy api requests, even though that means you have to start the dev server before running your tests. Since #1423 isn't closed yet, maybe we should add something to the docs in the meantime?

**Comment by stefanpenner** [comment]
may be fixed, this area has changed a lot and none of my apps are affected. Will gladly reopen if steps to reproduce can be provided.
