### ISSUE TITLE
Cannot Prepend CDN Path Without Fingerprinting

### ISSUE THREAD

**Issue by EmergentBehavior** [ember-cli/ember-cli#2445]
I store all my assets on Amazon S3. I also have fingerprinting enabled in my Brocfile.js for my desired environment. When fingerprinting is enabled, I also have my CDN path prepended. The issue I'm running into is that none of the hard-coded img paths in my application are updated with the fingerprinting, so all the images become broken. Two solutions to this would be:

(a) Allow certain assets to have CDN paths prepended _without_ fingerprinting them (i.e. partial exclude).

(b) Update hardcoded references to images so fingerprinting is applied.

I feel like (a) would be easier.

**Comment by KrisOlszewski** [comment]
@rwjblue and @EmergentBehavior is this feature still not an option in Ember CLI? I've been trying to prepend all assets with a CDN link, but exclude some assets from being fingerprinted.

**Comment by nathanhammond** [comment]
@KrisOlszewski Stop by the Ember community Slack in the #dev-ember-cli channel and we can discuss; I want to understand your goals and needs.

(Short response because I'm on a phone. Don't let that imply disinterest in engaging.)
