### ISSUE TITLE
in-app addons (and node_module addons) not watched

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2449]

**Comment by tonywok** [comment]
@rwjblue I was trying to make this work for regular addons.

Is the intended workflow that you start with an in-app-addon and convert it to an addon once a developer deems it mature enough?

**Comment by stefanpenner** [comment]
@tonycoco i think that workflow still needs to be paved nicely

**Comment by tonywok** [comment]
@stefanpenner Do you see the two concepts converging. Or phrased differently, would you use one over another? (it depends is a reasonable answer :smile:)

We have an app that is extended via addons (at the moment) that inherit from our host app's core functionality.

**Comment by stefanpenner** [comment]
> Do you see the two concepts converging?

yes, internally they are nearly the same thing.
