### ISSUE TITLE
Setting storeConfigInMeta: false causes tests to run outside of #ember-testing container

### ISSUE THREAD

**Issue by cristinawithout** [ember-cli/ember-cli#2480]
Steps to reproduce:

Add to Brocfile.js:
```js
var app = new EmberApp({
    storeConfigInMeta: false
});
```

Create at least one acceptance test:

```
ember g acceptance-test foo
```

Run tests on http://localhost:4200/tests

Result:
Application DOM elements aren't placed within the #ember-testing container. (Set a breakpoint in your foo acceptance test to see.) Can cause some tests to fail because find() doesn't #ember-testing as the root element. For example: find('h1').text() will find the qunit header "Client Tests" when it should only find the h1 elements in the application. 

After some debugging, found that config in tests/helpers/start-app.js isn't loading the environment config from config/environment.js so App.rootElement is not set to '#ember-testing' as it's defined in the test environment config.

**Comment by gdub22** [comment]
This is also a pain by not being able to refresh the /tests page because it uses the development `locationType` instead of 'none'.
Any suggestions how to work around this when still running in a development environment?

**Comment by rwjblue** [comment]
@gdub22 - the recommended way to run tests is via 'ember test' or 'ember test --server' (both of which run in the right environment). This is precisely why we have the defaults that we do (assets do not have the config embedded). Using storeConfigInMeta: false prevents easily switching the config values with the same assets.

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/ember-cli/ember-cli/issues/4535
