### ISSUE TITLE
Ability to set liveReloadFilterPatterns from the config file

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#2481]
Currently `liveReloadFilterPatterns` is a property on the Project model, but this doesn't appear to be settable from the Brocfile. This would be useful to prevent files that always change (eg. app.manifest) from triggering live reload. For example this prevents the CSS-only live reload from working (see #2371)

**Comment by knownasilya** [comment]
@aexmachina can you show an example of how you did this? Is it setting it on the express app instance?

**Comment by knownasilya** [comment]
For anyone wondering, I did this:

```js
// server/index.js
var env = process.env.NODE_ENV || 'development';
var isProduction = env === 'production';

module.exports = function (app, ember) {
  if (!isProduction) {
    ember.project.liveReloadFilterPatterns = ['.swp'];
  }
};
```

**Comment by aexmachina** [comment]
Yep that's the solution I used.

**Comment by knownasilya** [comment]
I think *.swp (vim temp file when opening files) should be a default, thoughts? @rwjblue @stefanpenner

**Comment by stefanpenner** [comment]
we support this
