### ISSUE TITLE
Ember test with environment flag does not use it for building tests

### ISSUE THREAD

**Issue by Myztiq** [ember-cli/ember-cli#2489]
If I run `ember test --environment foo` I want it to build the test directory with that environment too. If I log out the `environment` variable passed into `config/environment.js` I get:

```
Environment:  foo
Environment:  foo
Environment:  test
```

I was able to *fix* this issue by changing the line found here https://github.com/stefanpenner/ember-cli/blob/13cbd4ad10c3cddc140b45c0f363bbe415be2ace/lib/broccoli/broccoli-config-loader.js#L42 to 

```
var config = self.options.project.config(this.options.env);
```

**Comment by EmergentBehavior** [comment]
Any movement on this? This has been a sore point for me lately.

**Comment by EmergentBehavior** [comment]
So I actually got around this (for myself) by adding a conditional in my `if (environment === ' test') {}` block. Basically, it checks if an environmental variable is present and, if so, loads different configuration. This solved an issue I was having trying to build tests with a different config in a Travis box.

**Comment by heathharrelson** [comment]
Just noting that this issue bit me as well when trying to configure a CI box slightly differently from my local development system. It would be nice to at least get some kind of warning to prevent users from spending lots of time trying to debug a known issue.

**Comment by stefanpenner** [comment]
we only support test/production/developement environments, plans are to add a variable target https://github.com/ember-cli/rfcs/issues/26
