### ISSUE TITLE
HTML5 shivs / Modernizr ignored by template compiler?

### ISSUE THREAD

**Issue by antonydb** [ember-cli/ember-cli#2500]
I cannot get any HTML5 shivs to be recognised in ie8. I'm fairly new to ember-cli so apologies if I'm missing something. I'm not sure what the problem is, but it appears to be something to do with template compilation.

From the image below, the `<header>` tag in my app/index.html is recognised by the browser, however the `<header>` tag in my handlebars template is closed off (not recognised).

I have created a repository here https://github.com/antonydb/ember-cli-modernizr.git to help recreate the issue.

I thought this might have been an issue with handlebars, but I can't replicate the issue when I render the same content on a page with the handlebars library on its own.

![test-modernizr](https://cloud.githubusercontent.com/assets/2289142/5039615/2897bc00-6bf5-11e4-88e0-1c08aeb2ec44.jpg)

Version info below:

 DEBUG: -------------------------------
vendor.js:28547 DEBUG: Ember      : 1.8.1
vendor.js:28547 DEBUG: Ember Data : 1.0.0-beta.10
vendor.js:28547 DEBUG: Handlebars : 1.3.0
vendor.js:28547 DEBUG: jQuery     : 1.11.1
vendor.js:28547 DEBUG: -------------------------------

Here's my Brocfile which picks Modernizr from my `vendor/custom` directory.

```
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

var pickFiles = require('broccoli-static-compiler');
var customTree = pickFiles('vendor/custom', {
  srcDir: '/',
  destDir: '/assets'
});

var mergeTrees = require('broccoli-merge-trees');
module.exports = mergeTrees([app.toTree(), customTree], { overwrite: true });
```

Any help on this would be greatly appreciated.

**Comment by luiskhernandez** [comment]
@antonydb Did you solve this ? i am having the same problem
