### ISSUE TITLE
Does ember-cli support proxy websocket request to server like ajax?

### ISSUE THREAD

**Issue by xiujunma** [ember-cli/ember-cli#2508]

**Comment by dwickern** [comment]
@WooDzu you need to pass in the `httpServer` from `index.js`

Here's my code for future reference. I needed to proxy all requests, including some non-ajax and a websocket connection, to `/api`. I started with `ember generate http-proxy api http://localhost:80`

server/index.js
```
module.exports = function(app, options) {
  var globSync   = require('glob').sync;
  var mocks      = globSync('./mocks/**/*.js', { cwd: __dirname }).map(require);
  var proxies    = globSync('./proxies/**/*.js', { cwd: __dirname }).map(require);

  // Log proxy requests
  var morgan  = require('morgan');
  app.use(morgan('dev'));

  mocks.forEach(function(route) { route(app, options); });
  proxies.forEach(function(route) { route(app, options); });
};
```

server/proxies/api.js
```
var proxyPath = '/api';

module.exports = function (app, options) {
  var server = options.httpServer;
  var proxy = require('http-proxy').createProxyServer({
    target: 'http://localhost:80',
    ws: true,
    changeOrigin: true
  });

  proxy.on('error', function (err, req) {
    console.error(err, req.url);
  });

  server.on('upgrade', function (req, socket, head) {
    console.log('Proxying websocket to ' + req.url);
    proxy.ws(req, socket, head);
  });

  app.use(proxyPath, function (req, res) {
    req.url = proxyPath + '/' + req.url;
    return proxy.web(req, res);
  });
};
```

**Comment by ggayowsky** [comment]
With the release of Ember 3.5, livereload now uses no longer uses a separate port, so the code  above will intercept the `livereload` upgrade request and break livereload.

My suggested modification to @dwickern's code is to only proxy the websocket enpoints as desired.

E.g.

```
  server.on('upgrade', function (req, socket, head) {
    if (req.url === proxyPath)(
      console.log('Proxying websocket to ' + req.url);
      proxy.ws(req, socket, head);
    }
  });
```

**Comment by rwjblue** [comment]
@ggayowsky - maybe open a new issue? this one is long dead...

**Comment by ggayowsky** [comment]
@rwjblue I don't think a new issue is needed, because things are working as intended?
I was just adding a heads up to the code provided (as I have use @dwickern snippet in several projects) to reflect an potential snag that now happens in 3.5
