### ISSUE TITLE
Code coverage support

### ISSUE THREAD

**Issue by sglanzer** [ember-cli/ember-cli#2526]
My team has spent the last few days attempting to integrate code coverage tools into the ember-cli environment with no success.  Specifically we've tried http://blanketjs.org/ and http://gotwarlost.github.io/istanbul/.  We've explored both testem and karma as test runners and both qunit and the new mocha addon for test writing.

A lot of the integration issues appear to be based around the module structure of ember-cli projects.  All of the coverage tools support AMD modules (the transpiled result of the Broccoli build), but the examples I've seen for integration of these tools are based on the requirejs library.  The ember libraries appear to provide custom require methods that don't appear to support functions such as relative path inclusion of modules.  We've hacked around this to allow blanket and instanbul to be loaded as modules, but even when these are included there are additional integration issues.

We have a working environment with testem, amd modules for source and test files, requirejs, blanket and qunit that produces coverage.  The test runner html includes testem, qunit, require and blanket and also includes a method to delay the qunit start until the modules have been instrumented by blanket.  Here is the relevant code from the test runner:

```
<script type="text/javascript" src="vendor/testem.js"></script>
<script type="text/javascript" src="vendor/qunit.js"></script>
<script type="text/javascript" src="vendor/require.js"></script>
<script type="text/javascript" src="vendor/blanket.js" data-cover-only="sample" data-cover-never="-test.js"></script>
<script>
    QUnit.config.autostart = false;
    require({
        baseUrl: "./"
    }, [
        "tests/sample-test.js"
    ], function () {
        QUnit.start();
    });
</script>
```

Attempting to do something similar (some code moves into test-loader.js) in the ember-cli environment results in a hung test runner.  Stepping through the test run shows the test suite being loaded and tests being executed, but no results are produced and no error logs are present.  Testem produces a "Running..." screen and a spinner with "0/0" tests executing, but never completes the test run.

We can't determine what the difference is between the two environments (maybe the require methods?) and we're fairly stuck at this point.

Are there any plans for ember-cli to support test coverage or any addons working on this issue?  Any help would be appreciated.

**Comment by esbanarango** [comment]
+1

**Comment by vire** [comment]
Hi guys, is there any progress in developing a working simple code-coverage ember-cli add-on?

Currently I've checked following projects

* [ember-cli-blanket](https://github.com/sglanzer/ember-cli-blanket/)
* [ember-cli-istanbul](https://github.com/mharris717/ember-cli-istanbul)

But I had a feeling they were started and nothing big is going on there...

**Comment by sglanzer** [comment]
@vire ember-cli-blanket is working code coverage - my company uses it for our coverage reports, which is why I created the project in the first place.  Unfortunately I've been under a very heavy workload recently, so the project isn't as up to date as it could be, but there are workarounds to the common issues and the addon is functional.  I haven't had a chance to test against the latest ember-cli releases (the frequency is extremely high), but I'm hoping to find some time this weekend.  Give the project a try though, it likely will work for you and it's always a good thing to have more people involved.

**Comment by stefanpenner** [comment]
> ember-cli-blanket
> ember-cli-istanbul

both exists, closing this now.

**Comment by vire** [comment]
@sglanzer :+1: 
thanks for the update, I'll try it and if some unreported issue occurs I will open an issue on the right place :)

**Comment by NullVoxPopuli** [comment]
@sglanzer, @stefanpenner do we have a solution for ember 2.3+?

I've tried ember-cli-blanket, and haven't been able to get an lcov file. :-(

I opened an issue here: https://github.com/sglanzer/ember-cli-blanket/issues/124#issuecomment-193846289

**Comment by sglanzer** [comment]
@NullVoxPopuli we tend to only bug ember-cli when it's actually an issue with the framework, in your case the 0.9.1 release works with ember-cli 2.3+, we have this executing in a number of projects currently - we can continue the discussion in the linked github issue on ember-cli-blanket
