### ISSUE TITLE
Running A Single Test

### ISSUE THREAD

**Issue by JarrodCTaylor** [ember-cli/ember-cli#2530]
I have written a npm module that allows you to run a single QUint test (also a single QUnit module) and a vim plugin that allows you to execute them from within vim. 
- [QUnit Special Blend](https://github.com/JarrodCTaylor/qunit-special-blend)
- [Vim QUnit Special Blend](https://github.com/JarrodCTaylor/vim-qunit-special-blend)

In order to accomplish running the single tests you currently need to set up your src_files in `testem.json` or file in `karma.conf` like so

``` javascript
{
    "framework": "qunit",
    "src_files": [
      "node_modules/qunit-special-blend/qunit-special-blend.js",
      "src/js/lib/scripts.min.js",
      "node_modules/qunit-special-blend/run-qunit-special-blend.js"
    ]
}
```

A few questions is this possible to duplicate using ember-cli? Would there be any interest in including this functionality in ember-cli? I would be happy to work up a pull request if there is interest and someone could point me in the right direction of where this is wired up in the project.

**Comment by fotinakis** [comment]
Wanted to throw out another use case for `ember test` accepting a list of file paths: Circle CI's automatic test balancing requires the ability to pass a list of file paths as command-line args to test runners.

Other test runners that support this (RSpec, minitest, nose, Cucumber) are automatically supported because they support paths as command-line args. It'd be great to be able to do this, but I understand it may be non-trivial because of compilation steps in ember-cli.

**Comment by saverio-kantox** [comment]
Also pre-commit git hooks could run linting tests only on modified code, saving time and allowing to migrate old code-bases without having to change thousands of files at the same time.

**Comment by rwjblue** [comment]
@fotinakis:

> Wanted to throw out another use case for ember test accepting a list of file paths: Circle CI's automatic test balancing requires the ability to pass a list of file paths as command-line args to test runners.

Checkout [ember-exam](https://github.com/trentmwillis/ember-exam).  It allows arbitrary splitting with a nice API...

---

@saverio-kantox:

> Also pre-commit git hooks could run linting tests only on modified code, saving time and allowing to migrate old code-bases without having to change thousands of files at the same time.

Sure, but that is already possible via the command line tools provided by linting engines and will be much faster than building your app in a pre-commit hook:

```
eslint app test
```

**Comment by anhari** [comment]
Only issue I found with `ember test --filter "some string to match in test title"` is that if you have tests with similar titles you'll end up running more than one test.  I wonder if there's a way to drill down to running a test based on the line number like in RSpec?

**Comment by tbowler** [comment]
@anhari What about using `:focus` like RSpec. Just add `:focus` to the title and then run the command `ember test --filter=":focus"` This doesn't get you tests based on line number but it will easily help you run a specific test.  Hope this helps!

**Comment by elyobo** [comment]
`--filter` taking a regular expression like mocha's [`grep` ](https://mochajs.org/#usage) would be much more helpful

**Comment by rwjblue** [comment]
should work fine as long as you are using a recent enough QUnit version: `ember test --filter=/some thing/`

**Comment by elyobo** [comment]
Ah, thanks @rwjblue, I didn't pick that up from the help text and wouldn't have thought to try it.

```
  --filter (String) A string to filter tests to run
    aliases: -f <value>
```

**Comment by devinrhode2** [comment]
`ember test -f "Unit | Route | application"` and `ember test -m "Unit | Route | application"` both worked well for isolating the test.
