### ISSUE TITLE
Option to not concat files in development

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#2537]
In reference to #2526 and code coverage. It looks like this:
![screen_shot_2014-11-20_at_8_49_22_am](https://cloud.githubusercontent.com/assets/3799709/5126503/197a7d28-7093-11e4-9280-8605bac39c15.jpg)

You can click on the file name to view the individual file and see what's not covered. While this is still useful.. It's not easy to pinpoint which file's aren't covered well. It would be convenient if we could output multiple js files so that it could pick them up and give coverage on each file.

Thoughts?

**Comment by WooDzu** [comment]
Sorry for bringing this up but I think it might be an interesting option not to concat the vendor only file in development. There are mainly two points around the idea:
- the time needed to concat many vendor libs
- from time to time the map generated by ember-cli is broken which makes debugging impossible
