### ISSUE TITLE
Addons leak devDependencies into consumer apps

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2538]
Example: liquid-fire is an addon. In its devDependencies is another addon, ember-code-snippet, which is used for its dummy app.

But if a client app `npm link`s liquid-fire, the devDependencies are of course present, and they end up getting imported into the client app.

ember-cli should probably only look at the `dependencies` list, not the `devDependencies` list, when building an addon.  The `devDependencies` should be consulted only when building the dummy app.

**Comment by stefanpenner** [comment]
> ember-cli should probably only look at the dependencies list, not the devDependencies list, when building an addon. The devDependencies should be consulted only when building the dummy app.

this sounds correct

**Comment by rwjblue** [comment]
This is already true.  Addon's `devDependencies` are not used as of 0.2.0-beta.1.

References:

* `AddonDiscovery.prototype.discoverChildAddons` calls `AddonDiscovery.prototype.discoverFromDependencies` [here](https://github.com/ember-cli/ember-cli/blob/f7247d2127082ce20c3bcd60a87ebc19a2a0be77/lib/models/addon-discovery.js#L61) specifying `excludeDevDeps` as `true`.
* `AddonDiscovery.prototype.discoverFromDependencies` calls `AddonDiscovery.prototype.dependencies` [here](https://github.com/ember-cli/ember-cli/blob/f7247d2127082ce20c3bcd60a87ebc19a2a0be77/lib/models/addon-discovery.js#L94) passing through the provided `excludeDevDeps` flag (which was `true` in the addon case).
* `AddonDiscovery.prototype.dependencies` does not include `devDependencies` if `excludeDevDeps` is `true` [here](https://github.com/ember-cli/ember-cli/blob/f7247d2127082ce20c3bcd60a87ebc19a2a0be77/lib/models/addon-discovery.js#L212-L221)

**Comment by stefanpenner** [comment]
danke
