### ISSUE TITLE
Generator's do not create work properly in an addon

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#2544]
If you are in an addon and run a generator, like `ember g route foo`. It will create a folder at the root called /app with the route, then error out about a file existing, and not create any tests. 

It should be smart enough to generate files in the proper directories. `tests/dummy` for app files and tests `/tests`

From a quick look around it seems like we need to update the [Blueprint.prototype.install](https://github.com/stefanpenner/ember-cli/blob/master/lib/models/blueprint.js#L326) method to be more specific about `intoDir` and perhaps check if the project's package.json defines a different one (this option would need to be added). 

I'm guessing tests would still be in the incorrect place, so it would either have to have an explicit override for tests or something else internally would have to be changed to accommodate this. Maybe something similar to the `this.treePaths` in the `Project` model. Then it would be configurable on which files end up where.

Thoughts @jgwhite ?

**Comment by trabus** [comment]
#3356 seems to be working properly. The tests are generated exactly the same as when in a project, but this should be configurable on a per-blueprint basis.
