### ISSUE TITLE
[RFC] Prep For HTTP2/SPDY File Serving And Service Workers

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2551]
There are currently a couple areas in the code base where pre-HTTP2/SPDY best practices are the default.  This includes such things as concatenating and asset revving. Asset revving can already be removed, but broccoli-es6-concatenator cannot.  I propose that Ember CLI not only creates the artifacts it creates today but also produces non-concatenated and non-asset revved files by default.

**Stop reading if you know what HTTP2/SPDY and Service Workers Affords You**

### More about HTTP2/SPDY

The primary goals for HTTP 2.0 are to reduce latency by enabling full request and response multiplexing, minimize protocol overhead via efficient compression of HTTP header fields, and add support for request prioritization and server push.  In other words you can push static content dependencies onto the initial response, avoiding round trips to CDNs. This means that the best practice of having CDNs serve static content is essentially a moot point.  It also means that the browser can do fine grain caching of files.

### More about Service Workers

There currently is a draft specification of [Service Workers](http://www.w3.org/TR/2014/WD-service-workers-20141118/) which is being championed by [Google, Mozilla, and Opera](https://jakearchibald.github.io/isserviceworkerready/).  Service workers is a programmable network and caching layer for the browser. It's sort of like app cache but better as you have all the control of when and how caches are setup.  If this becomes a standard it means that web applications will continue to blur the lines of native and web applications.  It also means offline first.  This feature is shipping in Chrome 39 I believe.

I believe that some of the service worker implementation can be automated through an addon which is super exiciting, just need to stop concating all of the things by default.

**Comment by stefanpenner** [comment]
good idea, but we can address in the future. Not a bug.

**Comment by Ghostavio** [comment]
any update on this? (as we're almost at the end of the first half of the year :p)

**Comment by stefanpenner** [comment]
@Ghostavio yes, the pre-packager work @chadhietala is working on does enable this. I'm actually going to be pairing with him on it again today. We are getting close to landing it, lots of compatibility work ahead of though.

**Comment by GCheung55** [comment]
Any updates on this?

**Comment by GCheung55** [comment]
@stefanpenner @chadhietala andy progress/update on this?

**Comment by jeremiahlee** [comment]
> So, my question is given the browser topology we have today, is a world without concatenation 1 week out, 1 month out 1 year or or more out?

Since Nov 2014, HTTP/2 availability has increased to [70% of Internet users](http://caniuse.com/#feat=http2). I think the world benefiting from lack of concatenation has arrived.

> well when we upgrade to the latest transpiler this part of our build chain will need some attention. I'll be sure to make this an option

Has this been made an option since Nov 2014?

**Comment by stefanpenner** [comment]
> Since Nov 2014, HTTP/2 availability has increased to 70% of Internet users. I think the world benefiting from lack of concatenation has arrived.

Well, it isn't that straight-forward yet, the overhead of many small files is still very real.

We have a prototype, but it required some other work be completed first (before we could deliver it to all our consumers), and that work is near completion. When that completes we hope to give it another whirl.

cc @chadhietala

**Comment by chadhietala** [comment]
Khan Academy has done some research in this area.  http://engineering.khanacademy.org/posts/js-packaging-http2.htm I feel we need to strike a balance.

**Comment by stefanpenner** [comment]
@chadhietala good link, ya my thoughts as well. Split the current mega bundle into logic chunks "engines" and use HTTP2 when available etc.

**Comment by nathanhammond** [comment]
My initial research into this implies that sheer header overhead limits the value of splitting to probably 10-20 assets _maximum_. We'll instead need to leverage service workers and build tricks to achieve more granular caching: https://twitter.com/nathanhammond/status/761749168566120449

**Comment by gabrielcsapo** [comment]
I worked on an example of implementing this https://github.com/ember-cli/ember-cli/pull/9383 and put metrics on how much this could improve for local dev.
