### ISSUE TITLE
acceptance tests generated to sub-dir fail by default

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2556]
they are reference start_app via relative path.

solutions:

* reference absolute
* magic to calculate the correct path (brittle)
* move start_app to an addon and `import 'ember-test/start-app'`

**Comment by abuiles** [comment]
This was fixed already https://github.com/ember-cli/ember-cli/blob/master/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js#L6
