### ISSUE TITLE
Watching styles in pod structure

### ISSUE THREAD

**Issue by gdub22** [ember-cli/ember-cli#2561]
With a pod structure, it'd be nice to keep the css file associated with a feature within the pod's folder.  Then just import the path in `app/styles/app.css|less|scss` like you do now.

This builds correctly today, but any changes to style files outside `app/styles` are not triggering an auto rebuild of the style tree when the server is running.

**Comment by Globegitter** [comment]
Yep, being able to detect/build/watch POD `style.scss` would be highly useful.

My current structure is, or wants to be `app/component-name/style.scss` (with route.js, controller.js, etc) as well as `app/components/component-name/style.scss` (for actual components) and I can't import any of these files through my `styles/app.scss`.

So for example `@import "../components/component-name/style"` throws an `file to import not found or unreadable:` error.

**Comment by mszoernyi** [comment]
@Globegitter This might help https://www.npmjs.com/package/ember-cli-sass-pods

**Comment by patricklx** [comment]
Is there a official solution to this?
I solved it by changing the Brocfile like this:

```
var matchLess = [new RegExp(/.*\.(less|css)/)];
var moreStyles = mergeTrees([
  new Funnel(unwatchedTree('app/components'), {
    srcDir: '/',
    destDir: 'components',
    include: matchLess
  }),
  new Funnel(unwatchedTree('app/pods'), {
    srcDir: '/',
    destDir: 'pods',
    include: matchLess
  }),
  new Funnel(unwatchedTree('app/styles'), {
    srcDir: '/',
    destDir: '.',
    include: matchLess
  })
]);
var app = new EmberApp({
    trees: {
      styles: moreStyles
    },
});
```

**Comment by stefanpenner** [comment]
we are re-working pods/folder structure stuff, stay tuned.
