### ISSUE TITLE
Move default server implementation out of blueprints

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2571]
Both the http-mock and http-proxy generators insert their own copies of the default server implementation. Which is bad enough, since the two separate files are in danger of diverging, and cause potential conflicts when people add a second one.

Furthermore, users who just want to add a mock or proxy without changing the server/index.js shouldn't need to have it in their repo. 

I'm propose that creating `server/mocks/foo.js` or `server/proxies/foo.js` without an accompanying `server/index.js` should just use a server implementation built into ember-cli. We should also figure out what kinds of customization are likely to be needed in server/index.js and expose hooks instead so that people aren't copying the whole thing into their repos just to edit a line or two.

**Comment by stefanpenner** [comment]
If someone wants to champion this, i'll support it. But this doesn't seem to be on anyones critical path
