### ISSUE TITLE
Ember CLI Addons Documentation

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli#2598]
I am opening this issue as requested by @stefanpenner in the [Ember Forums](http://discuss.emberjs.com/t/best-practices-for-building-ember-cli-addons/6791).

Documentation and tips on best practices when building Ember CLI addons are not readily available. This makes it very hard for your standard Ember developer to realize the benefits of one of Ember CLI's greatest assests (addons).

I think the community and technology will benefit greatly from a very extensive, practical, ever-growing guide to building Ember addons that uses common addon use cases as guides to hit on major architectural decisions that will impact addon performance. A more in-depth [discussion of the guide content can be found here](http://discuss.emberjs.com/t/best-practices-for-building-ember-cli-addons/6791).

**Comment by jakecraige** [comment]
closing because this is in the docs now http://www.ember-cli.com/#developing-addons-and-blueprints

I'm sure we'll constantly need to update it but we have a good start currently. There's also #2835 which will elaborate on inline docs as a whole soon. Any specific things we may be missing we can open individual issues that we can resolve

**Comment by sir-dunxalot** [comment]
This issue was opened after that section was in the docs. If you look at the forum thread you'll see it's very different from the current scope of the docs - the issue is more about best practices, maximizing build tree performance, case studies, etc.

**Comment by jakecraige** [comment]
My bad, that makes sense. Will reopen

**Comment by sir-dunxalot** [comment]
No worries - thanks for checking in! Appreciate all the work you're doing.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md
