### ISSUE TITLE
Use http git repo for esprima

### ISSUE THREAD

**Issue by miguelcobain** [ember-cli/ember-cli#2605]
While running `ember addon addon-name` i got an error trying to execute `git clone git://github.com/ariya/esprima.git`.

I'm behind a proxy in my company. I can only proxy http(s) requests.

Is there any chance to make this command clone the repo through http?

I think it would be more proxy-friendly.

**Comment by stefanpenner** [comment]
we should try to  align our various deps and their esprima usage...

![screen shot 2015-02-24 at 9 35 55 am](https://cloud.githubusercontent.com/assets/1377/6355127/a2efeb86-bc08-11e4-990c-899cedc62707.png)

**Comment by stefanpenner** [comment]
i think the last of them are now fixed
