### ISSUE TITLE
Does delegate functionality still exist in moduleFor?

### ISSUE THREAD

**Issue by theworkerant** [ember-cli/ember-cli#2620]
Situation: I'm trying to setup my controller of interest using `moduleFor` with a model. So I'm looking at `moduleForModel` I see `this.store()` grabs it. In `moduleFor` `this.store()` is `undefined`. Although I'm not sure how to use it, I thought `delegate` might be the solution here as opposed hacking around in the container. Contrary to the docs, `delegate` is undefined.

As listed in the docs

> delegate: To manually modify the container & the testing context, supply a function as the delegate matching this signature delegate(container, testing_context)

Perhaps these docs were copied directly from Ember App Kit and something got changed in between? I can't seem to find any other info on this. Anyone got ideas on best practices here?

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli-qunit
