### ISSUE TITLE
ES6 module syntax, ASI is not respected.

### ISSUE THREAD

**Issue by kriswill** [ember-cli/ember-cli#2630]
If you use ASI style javascript with the ES6 `import` syntax, concatenation breaks.

``` javascript
import Ember from 'ember'; // <-- without the semicolon, it breaks

export default Ember.Route.extend({
  model: function(params) {
    if (!(params && params.contact_id)) return
    return this.store.find('contact', params.contact_id)
  }
})
```

I haven't looked at the parser for the ES6 concatenation closely, but I'm assuming it's RegEx bifurcating on the semicolon, instead of using an AST to find the statements.

**Comment by jrowlingson** [comment]
@rwjblue @stefanpenner is this worth a revisit?
