### ISSUE TITLE
Function#bind does not work with phatomjs without es5-shim

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#2634]
Function#bind not working with phantomjs ?

If app or addon code uses Function#bind phantomjs will error out as .bind is not defined.

Workaround:

Try using https://www.npmjs.org/package/es5-shim

1. `npm install --save-dev es5-shim`
2.  add to tests/index.html `<script src="assets/es5-shim.js"></script>`
3. Update Brocfile.js ...
```
es5Shim = pickFiles('node_modules/es5-shim', {
  srcDir: '/',
  files: ['es5-shim.js'],
  destDir: '/assets'
});
module.exports = app.toTree([es5Shim]);
```

**Comment by adam-knights** [comment]
For those coming to this because they are using ember-cli-materialize and having issues with .bind @pixelhandler 's addon resolves the issue and gets phantomjs working again.
