### ISSUE TITLE
Brocfile.js vendorFiles no longer works for es5-shim (IE8 support)

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#2635]
As of [this change](https://github.com/stefanpenner/ember-cli/commit/28dfe4d9dee97aa1ef3016c1493f4a5f9bbbcfe0), the `vendorFiles` hook will no longer work for shims (like es5-shim and matchMedia). This is because they need to be present before Ember loads for them to work. Because of this we're currently locked in at v0.1.1 because we need the shims to support IE8.

As much as shims suck, they're a necessary evil until older browsers die off. I propose we add an additional hook for shims in the vendor pipeline.
```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var app = new EmberApp({
    preVendorFiles: {
        'es5-shim.js':   'bower_components/es5-shim/es5-shim.js',
        'matchMedia.js': 'bower_components/matchMedia/matchMedia.js'
    },
    vendorFiles: {
       // ... vendor files go here and are appended to vendor.js 
    }
});
```

Thanks!

**Comment by asaf** [comment]
ping?

I'm finding myself adding all shim code into index.html because none of these solutions work,


Thanks! :)

**Comment by jakecraige** [comment]
@asaf The prepend flag was added in #2668 which is referenced right above your comment. It was implemented as described in https://github.com/ember-cli/ember-cli/issues/2635#issuecomment-65477313
