### ISSUE TITLE
App using Ember 1.9.0-beta.4 and handlebars 2.0.0 won't launch - cannot find module ember/handlebars

### ISSUE THREAD

**Issue by nosachamos** [ember-cli/ember-cli#2636]
I created a new app, then upgraded Ember to the latest 1.9.0-beta.4 and handlebars to 2.0.0, then attempted to serve that app. It fails with:

```
Uncaught Error: Could not find module handlebars
Uncaught Error: Could not find module ember
```

I hope I have set this up right and that this is a supported scenario. The repro steps are straightforward:

`ember new whatever-app-name`

Then replace bower.json with the following (upgrading ember and handlebars to latest):

```javascript
{
  "name": "frontend",
  "dependencies": {
    "handlebars": "~2.0.0",
    "ember": "1.9.0-beta.4",
    "ember-data": "1.0.0-beta.12",
    "ember-resolver": "~0.1.7",
    "ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "jquery": "~2.1.1",
    "loader.js": "~2.1.1"
  }
}
```

Then set Broccoli.js to:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

app.import('bower_components/jquery/dist/jquery.js');
app.import('bower_components/handlebars/handlebars.js');

app.import({
    development: 'bower_components/ember/ember.js',
    production:  'bower_components/ember/ember.prod.js'
 });

module.exports = app.toTree();
```

then cd into your app and:

`bower install`
`ember s`

Then open the app in the browser. Watch the error in devtools.

I'm using:
```
$ ember version --verbose
version: 0.1.2
http_parser: 1.0
node: 0.10.33
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.29
zlib: 1.2.3
modules: 11
openssl: 1.0.1j
npm: 2.1.3
```

Please let me know if I missed something, or if this is not a supported setup.

Thanks!

**Comment by lolmaus** [comment]
So, what's going on here? Ember CLI does not support Ember 1.9 for now?

**Comment by lolmaus** [comment]
I'm sorry, in my case it's EmblemJS being incompatible with Handlebars2 and/or HtmlBars.

**Comment by stefanpenner** [comment]
> So, what's going on here? Ember CLI does not support Ember 1.9 for now?

it seems to support it fine for my use-cases. I run canary all the time.

Im on a train with slow WIFI ATM, maybe i can dig into this when i get home. See why people are having pain

**Comment by stefanpenner** [comment]
this is all sorted out
