### ISSUE TITLE
Best way to include bower dependency in an addon

### ISSUE THREAD

**Issue by miguelcobain** [ember-cli/ember-cli#2639]
I've been trying to package some components as ember-cli addons.

Naturally, some require bower dependencies.
What is the correct way to include a bower dependency in an ember-cli addon?

Are blueprints currently the best answer for that?

Like this https://github.com/miguelcobain/ember-paper/blob/master/blueprints/ember-paper/index.js
or this https://github.com/gevious/ember-datepicker/blob/master/blueprints/ember-cli-datepicker/index.js

I'd rather avoid this because it requires an additional command to be run. Is this possible to accomplish using a postinstall script, at least for now?

Probably the outcome of this should be reflected on #2598.

**Comment by stefanpenner** [comment]
@miguelcobain currently like this: https://github.com/ember-cli/ember-cli-qunit/blob/master/blueprints/ember-cli-qunit/index.js#L8-L15

long time plans is to drop bower entirely, but NPM needs to move along more first.
