### ISSUE TITLE
Watchman watches should use the root of a repo

### ISSUE THREAD

**Issue by wez** [ember-cli/ember-cli#2643]
Looping back here via https://github.com/facebook/watchman/issues/70

I'd recommend that, when using watchman, you find a root dir and use that as the basis for your watch.  Simple heuristics for that are walking up the tree until you find a `.git` or `.hg` dir, or a `.watchmanconfig` file, then using that location as the root. 

This will establish a single fsevents stream on osx and a single inotify handle on Linux, and if you are using other tools (such as the `hgwatchman` extension for accelerating mercurial), you'll share the same watch resources across multiple tools.

Watchman will efficiently process the updates for you.  If you have extremely large trees (many thousands of dirs and files) you can configure a `.watchmanconfig` option to ignore dirs that contain only generated files (for example).

When subscribing to watchman notifications, I recommend using match expressions that most closely or uniquely identify the file or dir in question so that watchman only needs to send you data on the things that you have expressed an interest in.

It may make sense to push some or all of this functionality into sane itself; it's certainly worth talking to @amasad to see if this fits his vision for sane.

If you want to chat about this in real time, you can find a small population of folks in `#watchman` on FreeNode

**Comment by wez** [comment]
@amasad we did.  I'm not in favor of that approach because it will incur some overhead in watchman; for every changed path we'd need to lock and resolve the appropriate root(s) and queue to each of them.  In our current model, the root is directly associated with our FSEventStream so this changes from being (almost) free to being a function of the number of watched roots.  In addition, it introduces lock contention between watched roots and clients that may be issuing queries against unrelated root(s).   I'd *really* like to avoid this if possible, because this particular code path needs to quickly consume the kernel queue to avoid an overflow; overflows require a full tree recrawl to re-synchronize.

However, what might be a decent middle ground is adding some helpers for the scheme I proposed at the top of this issue; when requesting to watch `ROOT/bower_components` we could have watchman walk up to find the root using the same simple heuristic.  The watch command would then return the root it is actually watching back to the client (in this case `ROOT`).   We can also look at adding a relative path to query expressions (and thus subscriptions) that would filter accordingly (so you'd subscribe with a `relative_path: "bower_components"` or similar component in your `subscribe` invocation) .  We'd likely still return results in the same way, which is to return the actually watched root and the list of files relative to that root.

This would move the watch aggregation logic out of the hot code path that consumes notification events and places it in the watch establishment and watch querying paths where we can make it cheaper.  It would also help reduce the volume of watch resources used on other platforms and not be an OS/X specific solution; that makes me like this idea more.

As consumers of the watchman API/protocol, does this sound like a workable solution to you?

**Comment by wez** [comment]
I've put up a proposed change for watchman to support this use case.  Most of the diff is docs;
@stefanpenner I'd appreciate your feedback on this.
You can reach our open source phabricator code review for this proposed change here:
https://reviews.facebook.net/D36117

**Comment by stefanpenner** [comment]
done (for some time already) forgot to close this.
