### ISSUE TITLE
how should we handle config.usePodsByDefault when pods are enabled by default?

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-cli/ember-cli#2652]
When making pods the default project structure in ember-cli, how should we handle the config option `usePodsByDefault`? We have a couple of options.

1. switch to a different config option like `disablePodsByDefault`; (I don't know what to call the opposite of pods.)
2. just change the app blueprint to set `usePodsByDefault: true` 
3. deprecate the flag and assume pods going forward

I think that Option 2 is fine, but would love to hear what other people think about it.

---

/cc @trabus @stefanpenner

**Comment by stefanpenner** [comment]
better question, why is the podConfig in the app/config ? seems like a build tool concern.

cc @rwjblue

**Comment by trabus** [comment]
@stefanpenner This was my fault. I misunderstood something when I was adding it and actually wasn't aware of .ember-cli

**Comment by stefanpenner** [comment]
> @stefanpenner This was my fault. I misunderstood something when I was adding it and actually wasn't aware of .ember-cli

got time to deprecate and move? ;)

**Comment by stefanpenner** [comment]
I'm trying to re-start the pod fleshout effort this weekend.

example project -> https://github.com/stefanpenner/ember-jobs

**Comment by trabus** [comment]
Awesome. Yeah, I'll take a crack at it, I'm at a resort with my family on a Girl Scouts outing, but they're all asleep so I'll see how far I can get tonight. ;)

**Comment by trabus** [comment]
Looking for an example of how to show a deprecation warning in ember-cli. [This](https://github.com/ember-cli/ember-cli/blob/2935d10f6e12e99906ed5d27e0bdf883555219ab/lib/models/addon.js#L550) isn't working for some reason (inside the blueprint model).

**Comment by trabus** [comment]
Going with `usePods` to replace `usePodsByDefault`.  I had to do some tweaks to get the environment settings to be available to the blueprint, but I have it working. It should probably be easier to get `.ember-cli` properties inside ember-cli, but passing in the settings through the command and task is working for now.

**Comment by trabus** [comment]
Just a note, this issue isn't resolved with moving the config property to `.ember-cli`. We still need to derive some sort of antonym for `--pod` that people can use if they want to generate (or destroy) modules in the type based format.

This actually goes back to the initial addition of pod support, where it was proposed as a `--structure=pod` flag. We could refactor to use that instead, using shorthands for the generate and destroy commands to set the flag. Generate available options would look like:
```
availableOptions: [
{ name: 'structure', type: String, default: 'type', aliases: ['s',  {'pod' : 'pod' }, {'type' : 'type'}}
]
```

**Comment by trabus** [comment]
Because of existing options for the route blueprint, `-type` won't work as a shorthand. I was having some difficulty trying to find a suitable name other than `-type`, but ultimately I think the only one that would make any sense would be `-default`.

I feel that using the shorthands and keeping the current `--pod` flag intact for a period of time would allow the easiest transition. Using the `--structure` option would also open the door for generating in other structures that may come about (maybe engines would have a specific structure for instance).

**Comment by EndangeredMassa** [comment]
I like the `--structure=pod/type` idea. I can foresee some different structures that people may want to use. Do we need shorthand options? Whichever you prefer to do most of the time should be stored in your `.ember-cli`. So, you will only be typing it out long-form when you want to do the opposite of your configuration.

Supporting `--pod` with a deprecation warning would be nice.

**Comment by trabus** [comment]
I absolutely want to have shorthand options for structure that map to the defined structure. Using  `-pod` and `-default` is much easier than `--structure=pod/default`, or even `-s pod/default`. I don't think we immediately need to get rid of `--pod`, but definitely should deprecate it eventually. Internally, blueprints should have some way to define (and expand) structures that map to how `fileMapTokens` are processed. Maybe something like this:

```
Blueprint.prototype.getStructure = function(options) {
  var availableStructures = this._structures(options);
  // if the structure passed in options isn't supported fall back to default
  if (availableStructures[options.structure].isSupported(this)) {
    return availableStructures[options.structure];
  }
  return availableStructures['default'];
}

Blueprint.prototype._structures = function(options){
  var standardStructures = {
    pod : {
      // test to determine if this blueprint can support this structure
      isSupported: function(blueprint) {
        return blueprint.hasPath;
      },
      name: function(options) {
        return options.blueprintName;
      },
      path: function(options) {
        return path.join(options.podPath, options.dasherizedModuleName);
      },
      test: function(options) {
        return options.blueprintName;
      }
    },
    default : {

      isSupported: function() {
        return true;
      },
      name: function(options) {
        return options.dasherizedModuleName;
      },
      path: function(options) {
        var blueprintName = options.blueprintName;
        if(blueprintName.match(/-test/)) {
          blueprintName = options.blueprintName.slice(0, options.blueprintName.indexOf('-test'));
        }
        return inflector.pluralize(blueprintName);
      },
      test: function(options) {
        return options.dasherizedModuleName + '-test';
      }
    }
  }
  var customStructures = this.structures(options) || options.structures || {};
  return merge(standardStructures, customStructures);
}

Blueprint.prototype._fileMapTokens = function(options) {
  var currentStructure = this.getStructure(options);
  var standardTokens = {
    __name__: function(options) {
      return currentStructure.test(options);
    },
    __path__: function(options) {
      return currentStructure.path(options);
    },
    __test__: function(options) {
      return currentStructure.test(options);
    }
  };

  var customTokens = this.fileMapTokens(options) || options.fileMapTokens || {};
  return merge(standardTokens, customTokens);
};
```

**Comment by trabus** [comment]
@jgwhite @stefanpenner @rwjblue Thoughts ^^?

**Comment by EndangeredMassa** [comment]
I don't think that we should call the non-pod structure `default` when the goal is to make `pod` the default.

**Comment by trabus** [comment]
But even when pods are default, there will still be several blueprints that generate in the standard structure. Maybe `-standard` instead of `-default`, but regardless, the type based structure will still be around.

**Comment by lukesargeant** [comment]
We've been making the move to pods. I like bits of both. Neither quite capture the two most important concepts which i believe are components and resources.

Here's my spanner for the works on how i'd structure it.

app
- components
  - component-name
    - template.hbs
    - component.js
    - styles.css
- resources
  - resource-name
    - route.js
    - model.js
    - adapter.js
    - serializer.js
- styles

Moving to a new default structure would at least mean the usePodsByDefault config wouldn't need to be touched.

**Comment by trabus** [comment]
@lukesargeant I'm working on an RFC for a `Structure` model now. The way I'm designing it, you would be able to define your own structure that would be picked up be the resolver without any additional setup. You'd define the structure rules, and drop it into your project. I'm also thinking you'd be able to define your structure as the `defaultStructure` in your `.ember-cli` file, achieving the same result as `usePodsByDefault` but work for any structure, not just pods.

**Comment by chadhietala** [comment]
@trabus I think to make the resolver configurable devs would have to provide a custom pattern function and then push that cat that pattern on to the front of the default patterns.

Devs could write something like this
```
export default function(parsedName) {
    // return your custom lookup here
};
```
Internally we would blueprint a subclass of the resolver that did something like.
```
import customPattern from <%structure_resolver>
var Resolver = require('ember/resolver')['default'] // might be able to do `import Resolver from 'ember/resolver'`;
export default Resolver.extend({
  customPattern: customPattern,
  moduleNameLookupPatterns: Ember.computed(function(){
    var defaults = this._super();
    return [this.customPattern].concat(defaults);
  })
})
```

**Comment by abuiles** [comment]
@trabus is working on this and as part of it I'm sure he would include an answer for this, I'm closing this issue in favor of his work.
