### ISSUE TITLE
which blueprints are best suited to the pod structure?

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-cli/ember-cli#2653]
When making pods the default project structure in ember-cli, not all blueprints necessarily deserve the pod treatment. For example, it might not make sense to put a blueprint in a pod. Let's take a look at each blueprint and decide what "pod" even means for them.

Generator | Pod?
:----- | :----------
acceptance-test <name> | 
adapter <name> <options...> | X
adapter-test <name> | X
addon <name> | 
app <name> | 
blueprint <name> | 
component <name> | X
component-test <name> | X
controller <name> | X
controller-test <name> | X
helper <name> | 
helper-test <name> | 
http-mock <endpoint-path> | 
http-proxy <local-path> <remote-url> | 
in-repo-addon <name> | 
initializer <name> | 
initializer-test <name> | 
mixin <name> | 
mixin-test <name> | 
model <name> <attr:type> | X
model-test <name> | X
resource <name> | X
route <name> <options...> | X
route-test <name> | X
serializer <name> | X
serializer-test <name> | X
service <name> | 
service-test <name> | 
template <name> | X
transform <name> | X
transform-test <name> | X
util <name> | 
util-test <name> | 
view <name> | X
view-test <name> | X

I filled out the above table based on the current setup. Should we change anything?

---

/cc @trabus @stefanpenner

**Comment by nathanpalmer** [comment]
I believe we should remove these from the default pod structure

  * adapter
  * adapter-test
  * component
  * component-test
  * model attr:type
  * model-test
  * serializer
  * serializer-test
  * transform
  * transform-test

To us pods map to resources and routes and it makes it real easy to know where to find things with this in mind. I added more detail in #3234. It would also negate the main need for the pod blacklist in #3012.
