### ISSUE TITLE
Error: unable to resolve root

### ISSUE THREAD

**Issue by calvinmetcalf** [ember-cli/ember-cli#2674]
```
Error: unable to resolve root /Users/me/path/project/app: directory /Users/me/path/project/app is not watched
    at null.<anonymous> (/Users/me/path/project/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
```

the particular path changes and has included

- /Users/me/path/project/bower_components/qunit/qunit
- /Users/me/path/project/bower_components/selectize/dist/css

**Comment by makwanza** [comment]
Same issue as everyone else when trying to add imports in my brocfile.

Restart of device fixed it as well.

**Comment by makwanza** [comment]
I had the same exact issue as everyone else. Rebooting the device (OSX10.10.1) fixed the issue.

**Comment by ahx** [comment]
Running `watchman shutdown-server` and restarting ember server solved this for me.

Had this problem after installing [ember-cli-pretender](https://github.com/rwjblue/ember-cli-pretender) and  `bower_components/FakeXMLHttpRequest` was not watched.

**Comment by stefanpenner** [comment]
as watchman doesn't age-out watched roots, https://github.com/ember-cli/ember-cli/issues/2894 is a short term workaround.

Currently ember-cli is to conservative with assigning roots, we need to be more aggressive when watchman is present. This should cut down on watched roots.

**Comment by leobalter** [comment]
I've got this for the second time after running a custom component generator.

**Comment by leobalter** [comment]
Even the #2894 workaround doesn't work for me: https://gist.github.com/leobalter/a6c07307301a021a9c25

**Comment by chrisrickard** [comment]
Restarting Chrome fixed it for me.

**Comment by petermumford** [comment]
Closing Sublime fixed the error for me. There is another issue mentioning this as well (sorry I can't find the issue) 

Before closing Sublime and doing `watchman watch-list` showed the below
```
{
    "version": "3.0.0",
    "roots": [
        "/Users/petermumford/code/web/geojobs/client/public",
        "/Users/petermumford/code/web/geojobs/client/app",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-data",
        "/Users/petermumford/code/web/geojobs/client/vendor",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-cli-shims",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-load-initializers",
        "/Users/petermumford/code/web/geojobs/client/bower_components/qunit/qunit",
        "/Users/petermumford/code/web/geojobs/client/bower_components/qunit-notifications",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-qunit/dist/named-amd",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-qunit-notifications",
        "/Users/petermumford/code/web/geojobs/client/tests",
        "/Users/petermumford/code/web/geojobs/client/config"
    ]
}
```
and after restarting showed:
```
{
    "version": "3.0.0",
    "roots": [
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-resolver/dist/modules",
        "/Users/petermumford/code/web/geojobs/client/public",
        "/Users/petermumford/code/web/geojobs/client/app",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-data",
        "/Users/petermumford/code/web/geojobs/client/bower_components/loader.js",
        "/Users/petermumford/code/web/geojobs/client/vendor",
        "/Users/petermumford/code/web/geojobs/client/bower_components/jquery/dist",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-cli-shims",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-load-initializers",
        "/Users/petermumford/code/web/geojobs/client/bower_components/qunit/qunit",
        "/Users/petermumford/code/web/geojobs/client/bower_components/qunit-notifications",
        "/Users/petermumford/code/web/geojobs/client/bower_components/typeahead.js/dist",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-qunit/dist/named-amd",
        "/Users/petermumford/code/web/geojobs/client/bower_components/ember-qunit-notifications",
        "/Users/petermumford/code/web/geojobs/client/tests",
        "/Users/petermumford/code/web/geojobs/client/bower_components/handlebars",
        "/Users/petermumford/code/web/geojobs/client/config"
    ]
}
```

**Comment by stefanpenner** [comment]
@wez any thoughts?

**Comment by wez** [comment]
Closing Sublime and Chrome to resolve things makes this not sound like a watchman issue.
I still don't see any watchman logs referenced here, so it's hard to say for sure.

**Comment by stefanpenner** [comment]
@wez I don't use sublime but I will try it out and try and give you and the authors of sublime feedback

The fact that chrome matters leads me to believe the system is starved on free fd. Like will be improved once we use watchman correctly. I intend to do this still just haven't had a chance yet

**Comment by petermumford** [comment]
@wez I've tried to get my watchman logs for you but when I run this command `$TMPDIR/.watchman.$USER.log` I get the following error: `The file /var/folders/t6/fgpx3xp567xbvpzmjhj5bxrr0000gn/T//.watchman.petermumford.log does not exist.`

Is there something I've missed when installing/starting watchman? I have watchman version 3.0.0.

**Comment by blesh** [comment]
FWIW, just ran into the same issue on a new project. Ember CLI 0.1.9

**Comment by pwfisher** [comment]
Closing Sublime resolved this for me.

**Comment by karelvuong** [comment]
Would also like to report that closing `Sublime Text 3 b3069` resolved this issue for me on `ember-cli 0.1.14`.

**Comment by Panoplos** [comment]
I also got error until I closed Sublime Text 3.

**Comment by stefanpenner** [comment]
are integration with watchman is currently suboptimal. We watch way more roots then we need to when watchman is enabled.

**Comment by Panoplos** [comment]
Stefan, something I noticed is that the code automatically adds directories (and subdirectories!) of files specified in `app.import(...)`, which to me is a problem for several reasons:

1. I may have files within these directories that I do not need to be watched. In fact, I have a case where I do not *want* them to be watched. For instance, with Semantic UI, both the compiled sources and concatted outputs are placed under `path/to/dist`. I am running into an issue where I want to watch another directory for changes to set off the build system for SUI, but because I have to use `app.import('path/to//dist/outputfile.ext')`, it results in `dist` and all of the subdirs under `dist` getting watched. However, the actual files that I *need* watched are not. (I have not figured out how to add them to the watcher yet, so if you have any suggestions, please advise.
2. Due to above, many, many files are being watched needlessly, and contributing to the parent issue.

Also, I have noticed `ember-app.js` uses `unwatchedTree`. As a workaround to 1. I would like to use this, but have no clue where it should be used or how. Any help is extremely welcome.

**Comment by stefanpenner** [comment]
@Panoplos ya you nailed it, basically our watcher interactions + user facing API are mis-aligned.

**Comment by blesh** [comment]
Sublime:

```sh
<kbd>⌘</kbd>+<kbd>Q</kbd>
```

Terminal:

```sh
subl .
ember s
```

**Comment by morgondag** [comment]
not using sublime fixes ember serve..
So we cant use ember or sublime? I rather stick with sublime ;-p

**Comment by SSS2557** [comment]
Yeap!  :(
@morgondag 

Same here, with:

watchman: 3.2
npm: 1.4.3
node: 0.10.26
ember-cli: 0.2.5
ember:  1.11.3

**Comment by stefanpenner** [comment]
watching integration is now much better, haven't seen this when using watchman 3.7 or later.

**Comment by alidcastano** [comment]
@stefanpenner Just started using ember, getting startd with the quickstart tutorial. Two steps in, in the define a route step, I ran into this same problem (and I am using watchman version 4.40).

When I tried to visit the template page, nothing would show, and terminal logged the following error: 

```
unable to resolve root /Users/acastano/Sites/Projects/studbits: failed to opendir(/Users/acastano/Sites/Projects/studbits): No such file or directory
Error: unable to resolve root /Users/acastano/Sites/Projects/studbits: failed to opendir(/Users/acastano/Sites/Projects/studbits): No such file or directory
    at BunserBuf.<anonymous> (/Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:96:13)
    at BunserBuf.emit (events.js:188:7)
    at BunserBuf.process (/Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
    at /Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

I was able to resolve the path and get page to render by running `ember build` and then `ember serve`.

But (unless it was I who did something wrong) if the error isn't fixed, the documentation should be updated so as to not discourage beginners 2 steps into the tutorial.

**Comment by nathanhammond** [comment]
@alidcastano We've not seen this issue in a long time so can you open a new issue and include your environmental information?

Alternatively, since it's likely something unique about your machine please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and see if anybody in our community can help you solve this problem.
