### ISSUE TITLE
Access UI and options from server proxy?

### ISSUE THREAD

**Issue by indirect** [ember-cli/ember-cli#2678]
I'm trying to write a proxy that uses the URL passed in `--proxy url`. Unfortunately, inside the proxy definition, `app.options` doesn't exist, and so I got it working by combining `app.argv = this.process.argv` in `server/index.js`, and then parsing the argv array inside my proxy. It seems pretty awful; is there a better way? Thanks.

```js
# server/index.js
[...]
  var proxies    = globSync('./proxies/**/*.js', { cwd: __dirname }).map(require);

  // We use this to read the proxy URL in proxies/uploads.js
  app.argv = this.process.argv;

  app.use(bodyParser.json());
[...]
```

```js
# server/proxies/uploads.js
[...]
  var proxyEnabled, proxyUrl;
  for (i in app.argv) {
    var arg = app.argv[i];

    if (proxyEnabled) {
      proxyUrl = arg;
      break;
    }

    if (arg === "--proxy") {
      proxyEnabled = true;
    }
  }
[...]
```

Thanks!

**Comment by stefanpenner** [comment]
seems to have gone stale
