### ISSUE TITLE
--silent option ignored by jshint error messages

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli#2679]
When running `ember test --silent` jshint errors still show up during the build process. This does not make any sense, as one would use that option to get clean XML output from testem, but this will break it. And the jshint errors will be part of the testem report anyways... 

Already suggested to take care of it, see https://github.com/stefanpenner/ember-cli/issues/2423#issuecomment-61423703, unfortunately that did not make it into PR https://github.com/stefanpenner/ember-cli/pull/2574.

**Comment by kimroen** [comment]
A little poke on this one - what do we think is the best approach for this?

I think it makes sense for addons to also be silent in silent mode, so exposing some blessed way of doing this would be good.

**Comment by kimroen** [comment]
I'm asking because I'd love to do something about it for ember-cli-coffeescript - it outputs linting info regardless of the `--silent`-flag being active or not. Issue: https://github.com/kimroen/ember-cli-coffeescript/issues/52

**Comment by stefanpenner** [comment]
--silent doesn't appear related to jshint. Rather our jshint is consider a test failure, and it is actually a test failure that your CI is seeing.

My question:

* does your CI parse them correctly as test failures?

**Comment by rwjblue** [comment]
@stefanpenner - The ember-cli-qunit addon did not previously have access to `ui` that could be passed through to `broccoli-jshint` (this is now possible on master).

The following locations need to be updated to pass through the new addon `ui` object:

https://github.com/ember-cli/ember-cli-qunit/blob/master/index.js#L102-L105
https://github.com/rwjblue/broccoli-jshint/blob/master/index.js#L44-L45
https://github.com/rwjblue/broccoli-jshint/blob/master/index.js#L113-L114

**Comment by rwjblue** [comment]
I've self-assigned this to get it updated for the 0.2.0 final release.

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-cli/pull/3391
