### ISSUE TITLE
Windows Build Tree still slow in 0.1.3 w/ symlinking

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#2680]
Opening issue at the request of @stefanpenner.

I recently following the instructions to allow symlinking in Windows (7 Pro) found here: http://www.ember-cli.com/#symlinks-on-windows.  After updating my build, the build time went from around 230,000 ms to about 140,000 ms.  Still a lot higher than expected, so posting this issue to see what we can do to track down a problem.

Snapshot of some of the relevant dependencies:
```
    "broccoli-asset-rev": "0.3.0",
    "broccoli-ember-hbs-template-compiler": "1.6.2",
    "broccoli-less-single": "git://github.com/jasonmit/broccoli-less-single.git",
    "broccoli-macro": "git+ssh://git@git.corp.yahoo.com:thoov/broccoli-macro.git",
    "broccoli-merge-trees": "0.1.4",
    "broccoli-static-compiler": "0.1.4",
    "connect-livereload": "0.3.0",
    "connect-restreamer": "1.0.0",
    "ember-cli": "0.1.3",
    "ember-cli-content-security-policy": "0.1.1",
    "ember-cli-document-title": "0.0.1",
    "ember-cli-ember-data": "0.2.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "1.2.2",
    "ember-cli-qunit": "0.1.0",
    "ember-cpm": "1.3.0",
    "ember-deprecated": "0.0.1",
    "ember-devtools": "2.0.0",
```

I've included the build output of a

Initial Build:
```
Build successful - 145489ms.

Slowest Trees                  | Total          
-------------------------------+----------------
TreeMerger (appAndDependencies) | 31643ms        
JSHint - App                   | 25746ms        
TreeMerger (stylesAndVendor)   | 19331ms        
ES6Concatenator                | 15333ms        
LessCompiler                   | 12582ms   
```

Change Build 1:

```
Build successful - 181094ms.

Slowest Trees                  | Total          
-------------------------------+----------------
TreeMerger (appAndDependencies) | 46993ms        
TreeMerger (stylesAndVendor)   | 29225ms        
TreeMerger (ExternalTree)      | 18960ms        
CustomStaticCompiler           | 14766ms    
```

Change Build 2:

```
Build successful - 133385ms.

Slowest Trees                  | Total          
-------------------------------+----------------
TreeMerger (appAndDependencies) | 43403ms        
TreeMerger (stylesAndVendor)   | 26387ms        
CustomStaticCompiler           | 8509ms         
JSHint - App                   | 8197ms         
TreeMerger (ExternalTree)      | 7431ms 
```

**Comment by stefanpenner** [comment]
@elwayman02 hows the example project coming?

**Comment by elwayman02** [comment]
I haven't had time to work on it...will try something this week hopefully.  I'm running out of time before they take my windows machine away, so I need to do it soon. =P

**Comment by elwayman02** [comment]
@stefanpenner in the meantime I ran ember server on our sample project that we've put together to help teams get started with an ember app quickly.  It has about 28 files and maybe 2 dozen dependencies; a lot lighter than our actual project.

```
ember.cmd s
version: 0.1.5
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

Build successful - 48724ms.

Slowest Trees                  | Total          
-------------------------------+----------------
CustomStaticCompiler           | 6369ms         
TreeMerger (appAndDependencies) | 6208ms         
LessCompiler                   | 5457ms         
TreeMerger (ExternalTree)      | 4939ms         
TreeMerger (stylesAndVendor)   | 4671ms  
```

The build time was still incredibly long for how lightweight the application is.  Maybe we can work from this sample application rather than my main one, which is a lot harder to pick apart?

**Comment by elwayman02** [comment]
Package.json (edited to remove 3 internal dependencies):

```
"dependencies": {
    "express": "^4.8.5",
    "glob": "^4.0.5"
  },
  "devDependencies": {
    "morgan": "^1.5.0",
    "bower": "^1.3.12",
    "broccoli-asset-rev": "^1.0.0",
    "broccoli-ember-hbs-template-compiler": "git://github.com/toranb/broccoli-ember-hbs-template-compiler.git#ab7ecc75f3180bc6a99adf5275a7626b37c1e28e",
    "ember-cli-dependency-checker": "0.0.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-less": "^1.0.5",
    "ember-cli-qunit": "0.1.2",
    "ember-cli": "0.1.5",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0"
  }
```

Bower.json (removed 1 internal dependency)
```
  "dependencies": {
    "ember": "~1.9.1",
    "ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-data": "1.0.0-beta.12",
    "ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "ember-resolver": "~0.1.10",
    "ember-testing-httpRespond": "git@github.com:rjackson/ember-testing-httpRespond.git#e36a0b23c1c63648fbad7f863a96d6f7398ceea9",
    "handlebars": "~2.0.0",
    "jquery": "^1.11.1",
    "loader.js": "stefanpenner/loader.js#1.0.1",
    "qunit": "~1.16.0",
    "moment": "~2.8.4",
    "lodash": "~2.4.1",
    "velocity": "~1.1.0",
    "jquery-mousewheel": "~3.1.12"
  }
```

The main thing missing is that we have an internal version of bootstrap included as well, which adds some heft to the dependency chain.

**Comment by stefanpenner** [comment]
ya still seems long, my windows clients app is hundreds of modules and many dependencies and they have 2s incremental builds.

Wish i could just have your machine infront of me.

**Comment by elwayman02** [comment]
@stefanpenner you're gonna love this...we recently upgrade our main app to 0.1.5 with ember-cli-6to5 brought in...now my build times are around 700,000 ms...nearly tripled xD

**Comment by stefanpenner** [comment]
> @stefanpenner you're gonna love this...we recently upgraded our main app to 0.1.5 with ember-cli-6to5 brought in...now my build times are around 700,000 ms...nearly tripled xD

so after investigating @elwayman02 machine, there where some issues.

* `ls` in `git bash` also took about 10s for 20 files
* he was using a version of windows without symlink support

@felixrieseberg this is likely a topic we should chat about.

**Comment by QuantumInformation** [comment]
Does any have a ballpark figure of how the speed compares with a similar spec mac and pc with 8.1 with ssd. Lets say the mac is the new pro 13 2015.

**Comment by pjcarly** [comment]
I just updated my ember-cli in my project from 1.13.1 to 1.13.8, and the buildtimes went up considerably, I used to get build times on the same project with literally nothing changed (except for the updates of ember-cli) of about 2 seconds, but after the update, I'm looking at 2 minutes (!) build time.

Tested on Windows 10 - 6GB Ram - SSD.

To get an indication what changed, 
change in my **bower.json**

```
{
    "ember-data": "2.0.0", [FROM: 2.0.0-beta.1]
    "ember-qunit": "0.4.9", [FROM 0.4.1]
    "jquery": "^1.11.3", [FROM 1.11.1]
    "loader.js": "ember-cli/loader.js#3.2.1", [FROM 3.2.0]
    "qunit": "~1.18.0" [FROM 1.17.1]
  }
}
```

Changes in dependencies in **package.json**
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2", [FROM 2.0.2]
    "ember-cli": "1.13.8", [FROM 1.13.1]
    "ember-cli-app-version": "0.5.0", [FROM 0.4.0]
    "ember-cli-babel": "^5.1.3", [FROM 5.0.0]
    "ember-cli-dependency-checker": "^1.0.1", [FROM 1.0.0]
    "ember-cli-htmlbars-inline-precompile": "^0.2.0", [FROM 0.1.1]
    "ember-cli-inject-live-reload": "^1.3.1", [FROM 1.3.0]
    "ember-cli-qunit": "^1.0.0", [FROM 0.3.15]
    "ember-cli-uglify": "^1.2.0", [FROM 1.0.1]
    "ember-cli-sri": "^1.0.3", [NEW]
    "ember-disable-proxy-controllers": "^1.0.0",
  },
  "dependencies": {
    "ember-export-application-global": "^1.0.3" [NEW, used to be in DEV Dependencies]
  }
```

**Comment by elwayman02** [comment]
@pjcarly it's probably best to create a new issue for this

**Comment by stefanpenner** [comment]
> I'm looking at 2 minutes (!) build time.

2 minutes === symlinks aren't setup, please be sure to review the windows guide on the website.

**Comment by pjcarly** [comment]
Awesome, it was symlinks indeed. For anyone finding this comment in the future, the fix for windows is setting up Symlinks:

http://www.ember-cli.com/user-guide/#symlinks-on-windows

**Comment by stefanpenner** [comment]
@pjcarly master of cli actually tests and logs this. I suspect this will help future people.
