### ISSUE TITLE
Acceptance tests suite failing

### ISSUE THREAD

**Issue by amedrz** [ember-cli/ember-cli#2682]
Hi guys,

I plan to start adding acceptance tests to my (barely-new) application so I read and followed the instructions [here](http://www.ember-cli.com/#testing) to bump up the suite.

This is the first test I added in order to get my feet wet

```
# tests/acceptance/login-test.coffee 
`import Ember from "ember"`
`import { test } from 'ember-qunit'`
`import startApp from '../helpers/start-app'`

module('Logs in', {
  setup: (->
    App = startApp()
  ),

  teardown: (->
    Ember.run(App, App.destroy)
  )
})

test "Page contents", (->
  expect(1)

  visit('/login').then(->
    equal(find('.row .accounts').length, 1)
  )
)
```

And ir throws the following error

```
TypeError: Cannot read property 'port' of null
    at extractLocationOrigin (http://localhost:4200/assets/vendor.js:64719:26)
    at http://localhost:4200/assets/vendor.js:64759:16
    at Array.map (native)
    at __exports__.default (http://localhost:4200/assets/vendor.js:64758:74)
    at __exports__.default.initialize (this-app/initializers/simple-auth.js:13:9)
    at http://localhost:4200/assets/vendor.js:16036:11
    at visit (http://localhost:4200/assets/vendor.js:16448:7)
    at DAG.topsort (http://localhost:4200/assets/vendor.js:16560:11)
    at Namespace.extend.runInitializers (http://localhost:4200/assets/vendor.js:16033:15)
    at Namespace.extend._initialize (http://localhost:4200/assets/vendor.js:15917:14)
```

I took a look and the config files `resolver.js` `start-app.js` `test-helper.js` and they are intact.

I'm on

```
Ember: 1.8.1
Ember Data: 1.0.0-beta.12
Ember-CLI: 0.1.4
```

Any idea what's going on here?

Thanks

**Comment by jdhines** [comment]
@amedrz Can you tell me what ENV variable you were missing? I too am getting this with my acceptance tests, and not sure what to do.

**Comment by amedrz** [comment]
@jdhines if I recall correctly, this had something to do with declaring `ENV['simple-auth']`. Something like:

````
if (environment === 'test') {
    ENV['simple-auth'] = {
      authorizer: 'simple-auth-authorizer:devise',
      authenticator: 'simple-auth-authenticator:devise',
      store: 'simple-auth-session-store:ephemeral',
    }
}
````

Hope this works for you

**Comment by jdhines** [comment]
Thank you for the confirmation! I've been stuck on this for over a month, and upon running the test environment (which I never do since I found I could access /tests in dev), I saw that it highlighted part of simple-auth's code, which then led me to search for "ember-simple-auth testing" and around to essentially the same thing, and now my acceptance test will run!
