### ISSUE TITLE
Error: FSEventStreamStart failed

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#2683]
seeing this lately after updating npm packages and then running ember serve, co-workers also have seen it, requires a reboot of machine to fix and allow my ember server to work again otherwise it crashes right away

```
ember-cli: 0.1.4
Ember: Canary
Watchman: 3.0.0
Mac OS X: 10.10.1 (14B25)
Node: 0.11.14

ember serve
version: 0.1.4
valid watchman found, version: [3.0.0]
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: FSEventStreamStart failed
    at null.<anonymous> (/Users/jcope/Desktop/InboxHealth/inbox-dashboard/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at Readable.push (_stream_readable.js:125:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/jcope/Desktop/InboxHealth/inbox-dashboard/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:183:22)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:265:12)
    at writeOrBuffer (_stream_writable.js:252:5)
    at Writable.write (_stream_writable.js:197:11)
    at Socket.ondata (_stream_readable.js:539:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
```

**Comment by ksnyde** [comment]
For what it's worth I have now run into the same issue with Textmate. :8ball:

**Comment by noodles** [comment]
@benjaminbalazs - same here. You could have just told me at work today :)

**Comment by wez** [comment]
Since this was resolved by restarting Sublime, can someone reach out to the Sublime folks and point them at this thread?  Same for Textmate users.  I wonder if there is something smarter that each of the respective softwares can/should be doing.

**Comment by alekspetrov** [comment]
+1 to others. OS X Yosemite, Sublime 3, ember-cli 0.1.5.

**Comment by e-karma** [comment]
I get this error a disappointing amount of times in various situations with various installs... It only occurs when I seem to be pushing a limit on the size of the App i'm working with.  I did the close/re-open of sublime and it worked after the 2nd try.

**Comment by PDXIII** [comment]
Had the same problem after doing some git pushing and branch renaming. Restarting Sublime worked.
I sent an email to the Sublime Team with a link to this issue.

OSX Mavericks, Sublime 3, ember-cli 0.1.6

**Comment by stefanpenner** [comment]
@PDXIII awesome thank you. FYI future sublime team members, lets sort this tout.

**Comment by devinrhode2** [comment]
Had this occurring on ember-cli 0.1.9, mavericks, sublime text 3

# Restarting Sublime solved it

:) happy coding peopols

**Comment by jayphelps** [comment]
Same setup as above peeps, same workaround.

**Comment by olivierlesnicki** [comment]
+1

**Comment by e-karma** [comment]
FSEventStreamStart failed
Error: FSEventStreamStart failed

-For me it's getting worse.  Repeated fail requiring fallback
-Fallback isn't watching changes & keeps crashing; 
-Sublime restart is no longer fixing

Any new suggested course of action?

e-cli 0.1.12
ember-canary
ember-cli-compass-compiler for compiling to enable susy/compass (could be making bug worse but until now symptoms matched others while using the same combo w/ 0.1.9-0.1.12)...

Great Job overall though, love where Embers headed and appreciate the hard work!

**Comment by PDXIII** [comment]
What happens with a stable version of ember?

**Comment by harianus** [comment]
Having the same issues but with a different name. It started with the `FSEventStreamStart` error, but now I have to restart the server every time I change a file. I get this error message:

```
file changed index.html
EEXIST, file already exists '/my/path/to/development/socialshop/app/tmp/class-tmp_cache_dir-ZTp7xJL7.tmp'
Error: EEXIST, file already exists '/my/path/to/development/socialshop/app/tmp/class-tmp_cache_dir-ZTp7xJL7.tmp'
    at Object.fs.symlinkSync (fs.js:742:18)
```

```
ember: 1.10.0
ember-data: 1.0.0-beta.15
ember-cli: 0.1.15
node: 0.10.36
npm: 2.1.8
```

I'll try the new beta of ember-cli

**Comment by olivierlesnicki** [comment]
@harianus please see this thread - https://github.com/ember-cli/ember-cli/issues/3413

**Comment by simo163** [comment]
Same here, restarting sublime text solved it. This made my day :)

**Comment by bartocc** [comment]
@PDXIII, any news form the sublime team ?

**Comment by stefanpenner** [comment]
@bartocc I have not made contact. If someone wants to make intro I'll gladly speak with them and figure something out. I am not a sublime user nore a paying no subscriber so I feel somewhat bad so reaching out. Maybe I shouldn't

**Comment by bartocc** [comment]
@stefanpenner I'll try to talk to someone and see if I can have them speak with you. I'll keep you posted

**Comment by PDXIII** [comment]
@bartocc didn't receive any answers on my mail.

**Comment by bartocc** [comment]
a new release of sublimetext (Build 3080) got just released today.

Let's see if by any chance the bug goes away with it

**Comment by truenorth** [comment]
Confirming that I still see this problem with sublime text builds 3080 and 3083

**Comment by truenorth** [comment]
Pro tip for ST3 users: Build a sublime text project and ignore folders with huge numbers of files. You will run into this problem less frequently

```js
// yamp.sublime-project
{
	"folders":
	[
		{
			"name": "Yahoo! Ad Manager Plus",
			"follow_symlinks": true,
			"path": ".",
			"folder_exclude_patterns": [".bower*", ".idea", "node_modules", "tmp", "bower_components", ".live-archive"]
		}
	],
	"settings":
    {
        "tab_size": 4,
        "trim_automatic_white_space": true
    },
}

```

**Comment by pjmorse** [comment]
Another data point: I'm seeing it with

    ember-cli 0.2.0
    st3 build 3083
    npm 1.4.28

Thanks to @truenorth for the ST3 project suggestion, hopefully that will slow the rapid graying of my hair.

**Comment by markduan** [comment]
I restart sublime, and no errors any more, I don't know why.

**Comment by stefanpenner** [comment]
> npm 1.4.28

although doubtful that this will make a difference in this case, but we do not support this version of npm as it is riddled with bugs. Please upgrade to 2.8.x

**Comment by cwiese** [comment]
Ugh... this is happening so often for me now.

**Comment by e-karma** [comment]
Ditch sublime for atom.  worked for me

**Comment by lukemelia** [comment]
This script has been a savior for me: https://gist.github.com/lukemelia/8daa762da7e2bda3df12

**Comment by gdub22** [comment]
Just adding "tmp/*" to folder_exclude_patterns in sublime instead of the granular tmp subfolder recommendations here http://www.ember-cli.com/#sublime-text solved it for me.

**Comment by dmuneras** [comment]
Thanks @gdub22

**Comment by cwiese** [comment]
Yes, this worked for me too!

**Comment by victorleungtw** [comment]
+1

**Comment by sunocean-sand** [comment]
Wow same for me +1

**Comment by bartocc** [comment]
I move to @AtomEditor guys.
I hope those staying with sublime will manage solving this issue

**Comment by olivierlesnicki** [comment]
moved to atom as well lol

**Comment by MichalGallovic** [comment]
+1, ditched sublime thx

**Comment by stefanpenner** [comment]
@bartocc sounds good

**Comment by andrewobrien** [comment]
@gdub22 solution works for me, cheers.

**Comment by lucasocon** [comment]
I solved it restarting sublime text :D 
+1

**Comment by felix-digitalkarma** [comment]
@gdub22 's solution worked for me. no more errors

**Comment by bobintornado** [comment]
Why the hell starting Sublime text fix this issue? 
( Verify on Sublime Build 3095, NPM 3.3.6, Node 4.2.0, Yosemite 10.10.5 (14F27) )

**Comment by tsavani-drg** [comment]
Re-starting Sublime text did fix this issue...!!!! :+1:

**Comment by henryzp** [comment]
+1, ditched sublime thx

**Comment by cstengel88** [comment]
If you´re using sublime text don´t include the hole ember project the issue should be gone if you leave out the "tmp" and "dist" folder, seems to be a problem with the amount of changes in those folders while starting the server.

**Comment by marinatedpork** [comment]
@cstengel88 How do you tell sublime to leave out certain directories for a project?

**Comment by cstengel88** [comment]
@marinatedpork you can simply select which subfolders you want with file->open

**Comment by crhayes** [comment]
@marinatedpork You can also open "Preferences -> Settings" and add the folders you want to ignore under `folder_exclude_patterns`. Here is an example of mine:

```
{
  "folder_exclude_patterns":
  [
    "node_modules",
    ".vagrant",
    ".svn",
    ".git",
    ".hg",
    "CVS",
    "tmp",
    ".tmp"
  ],
}
```
