### ISSUE TITLE
Not detecting file changes

### ISSUE THREAD

**Issue by dallasread** [ember-cli/ember-cli#2688]
When I run `ember s` on OS X 10.10.1 (NVM at v0.10.33), this is what I get:

```
version: 0.1.4
valid watchman found, version: [3.0.0]
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

Build successful - 1499ms.

Slowest Trees                  | Total          
-------------------------------+----------------
EsnextFilter                   | 461ms          
ES3SafeFilter                  | 221ms          
ES6Concatenator                | 182ms          
JSHint - App                   | 118ms          
TemplateCompiler               | 75ms  
```

The app works fine in the browser, but _file changes are not detected_. It was working originally, then stopped after I restarted my computer. I also tried uninstalling watchman, but the same issue exists with NodeWatcher. I'm running into the same issue on all my Ember CLI apps - even have the same issue when creating a brand new app.

Any help is greatly appreciated!

**Comment by dallasread** [comment]
Update: I kept on using polling and then... Yesterday, I accidentally booted up `ember s` (without polling), and it works fine! Seems to have fixed itself. Thanks again!

**Comment by stefanpenner** [comment]
> Update: I kept on using polling and then... Yesterday, I accidentally booted up ember s (without polling), and it works fine! Seems to have fixed itself. Thanks again!

magicks!!!
