### ISSUE TITLE
ember build is not working

### ISSUE THREAD

**Issue by sakoh** [ember-cli/ember-cli#2690]
I run `ember build --watch` and I opened the index.html page in dist directory, all I have is a blank page and these are the errors in the chrome console:
![screen shot 2014-12-06 at 4 12 22 pm](https://cloud.githubusercontent.com/assets/3895968/5329457/cb982ab0-7d62-11e4-99e1-6c83b454055d.png)

Can you resolve this issue as quickly as possible?

**Comment by hosein2398** [comment]
I had exact same problem, I changed `locationType` to `hash` but it didn't work again.
Then I went to `dist/index.html` and changed all scripts and CSS links from something like :  
`
<script src="/assets/vendor.js"></script>
`
To : 
`
<script src="assets/vendor.js"></script>
`
and it worked! but problem is that all of my other assets have this problem (imgs , fonts) and they are not loaded.
I'm on Window , Node 6.10.3 , ember-cli 2.12.1

**Comment by hosein2398** [comment]
When I moved my `fonts` and `imgs` folder into assets folder problem with them is resolved.

**Comment by nigilan** [comment]
@hosein2398  Same here. I removed / and it worked for me!

**Comment by mariothedev** [comment]
Why is this ticket closed if the problem persists?

@nigilan - That too did the trick for me.

**Comment by abhilashlr** [comment]
Doesn't setting `rootUrl` to '' in `development` work? If yes, should this be part of the default cli behaviour of `ember new <app>` command?
