### ISSUE TITLE
Could not find watchman, falling back to NodeWatcher for file system events

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#2703]
I just updated to Ember-CLI v0.1.4 on ubuntu 14.04 (NOT Windows) and followed all of the instructions for setup and upgrading my project. However, now I get the following warning:

```
kiffin@T431s:book-ember-cli-101 $ ember s
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

Build successful - 509ms.
```

So why can't it find watchman any more?

**Comment by raulsouzalima** [comment]
I was getting the same issue. I tried to reinstall watchman, reboot my imac, etc... and nothing.
I tried to run `watchman shutdown-server` but then I got something like `unable to talk to your watchman`.

So, I ran `launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist`, deleted this same plist file, uninstalled the watchman again, deleted all files about watchman on homebrew cache `rm -rf /Library/Caches/Homebrew/watchman-*` and tried to install again, forcing a new download.

After that I was able to run `watchman shutdown-server` successfully and also up my ember server using watchman.

**Comment by simo163** [comment]
@raulsouzalima This solved my issue, Thank you!! could someone tell me how and why to use the command watchman watch ~/path-to-dir ?

**Comment by trev** [comment]
:+1: Cheers @raulsouzalima, that did it for me.

**Comment by kurtisnelson** [comment]
Upgrading to El Capitan may break watchman this way, I also had to manually clean things up as a plain brew uninstall/install did not fix it.
