### ISSUE TITLE
ember new <dir>  sometimes think I'm in $HOME when I'm not

### ISSUE THREAD

**Issue by shime** [ember-cli/ember-cli#2718]
$ pwd
    ~/code/hack
    $ ember new ember-test
    $ cd ember-test
    bash: cd: ember-test: No such file or directory
    $ ls ~
    ember-test

So it assumes I'm in `~` instead of `~/code/hack` for some reason.

This works, though
    
    $ pwd
    /tmp
    $ ember new ember-test
    $ cd ember-test
    $ head -n1 README.md 
    # Ember-test

**Comment by flecno** [comment]
This is really strange. I see the same problem, but can't see any pattern. I added this two lines in the create task (https://github.com/ember-cli/ember-cli/blob/master/lib%2Ftasks%2Fcreate-and-step-into-directory.js#L15):
```
console.log(process.cwd());
process.exit();
```

The result is:
```
$ cd /mnt/workspace/workspace
$ cd foo 
$ ember new dirtest
version: 0.1.12
/mnt/workspace/workspace
$ pwd
/mnt/workspace/workspace/foo
$ mkdir bar
$ cd bar 
$ pwd
/mnt/workspace/workspace/foo/bar
$ ember new dirtest
version: 0.1.12
/mnt/workspace/workspace
$ node -e "console.log(process.cwd());"
/mnt/workspace/workspace/foo/bar
$ cd /mnt/workspace
$ mkdir -p foo/bar
$ cd foo/bar
$ pwd
/mnt/workspace/foo/bar
$ ember new dirtest
version: 0.1.12
/mnt/workspace/foo/bar
```

I have no idea how to test this or what's wrong here.

**Comment by flecno** [comment]
Ahh... there is a unused `package.json` file in `/mnt/workspace`. Removing this solves the problem. @shime Do you have a `package.json` in `~/code/hack` or `~`?

**Comment by stefanpenner** [comment]
> Removing this solves the problem. @shime Do you have a package.json in ~/code/hack or ~?

this indicates a potential issue on our side

**Comment by stefanpenner** [comment]
This hasn't happened to be in some time. (Every since using node 5x). I believe this was a race in process.chdir.

I'll keep on eye on this, but due to how infrequently it strikes and how how to track down it is, I'm going to close this one down.
