### ISSUE TITLE
Issue with locationType: 'auto' while running ember serve

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#2720]
Versions
```
ember-cli: 0.1.3
Ember: 1.7.0
Watchman: 3.0.0
Mac OS X: 10.10 
Node: 0.11.14

ember serve
version: 0.1.3
valid watchman found, version: [3.0.0]
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
```

I have 
```
 locationType: 'auto'
```
in my environment.js

If I directly navigate to a page in my app using a link-to, the page works but if I try to refresh that page, I get this

![screen shot 2014-12-10 at 12 14 43 pm](https://cloud.githubusercontent.com/assets/3374461/5380459/46e27dfa-8066-11e4-8195-df8fb7829649.png)

if I switch to locationType: 'hash' while running ember serve , the pages works on both navigating and refreshing.

I have a deployed version of the app using locationType: 'auto' and that seems to be working fine on both navigating and refreshing.

this seems to be a issue that started happening on one of the recent ember-cli versions while running ember serve, auto was working fine a few versions ago and I haven't switched ember versions in awhile, happens to be the same screen that was rearing its head in https://github.com/stefanpenner/ember-cli/pull/2458, so I think this has something to do with live reload or watchman as the deployed ember build version is working fine with locationType: 'auto'

**Comment by stefanpenner** [comment]
if i recall there was a regression but it is now fixed. If this problem remains feel free to comment with steps to reproduce on (master) and I will reopen.
