### ISSUE TITLE
add concept of apply AST transform to blueprints

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2729]
escodegen now supports the es6 syntax we care about, so this would improve stuff like how we insert into router.js

https://github.com/stefanpenner/ember-cli/blob/master/lib/models/blueprint.js

**Comment by trabus** [comment]
This will still be considered for the extraction of the blueprint model. I think having a convenience method to get the AST after install would be useful.

**Comment by stefanpenner** [comment]
:+1:
