### ISSUE TITLE
With HTMLBars template processing differs for addons vs. apps

### ISSUE THREAD

**Issue by aceofspades** [ember-cli/ember-cli#2742]
Re: https://github.com/emberjs/ember.js/issues/9900

When using HTMLBars it appears that all templates in the application `app/` tree are processed (including `app/components`. However for addons, only those in `app/templates/` appear to be.

*Q: Can addon processing use the same manner to process templates that the main app does?*. That meaning, pick up all `*.hbs` files within the `app/` and `addon/` trees of the addon.

https://github.com/aceofspades/htmlbars_addon_templates

Note: After cloning repo, either `npm link` the addon or symlink `app/node_modules/addon -> ../../addon` before performing `npm_install`.

Current output is

```
app/app/compontents/x-alpha/template
addon/app/templates/components/x-bravo
```

Expected output is

```
app/app/compontents/x-alpha/template
addon/app/templates/components/x-bravo
addon/app/components/x-charlie/x-charlie
```

**Comment by stefanpenner** [comment]
fixed on master
