### ISSUE TITLE
Proposal: Add Project Anatomy section to documentation website.

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#2751]
I was looking at Sails.js and noticed their [Anatomy section of their docs](http://sailsjs.org/#/documentation/anatomy/myApp). We should do something like this for Ember CLI. I really like the breakdown of each specific file, and examples and comments about each part. We could even [embed a discourse thread](http://eviltrout.com/2014/01/22/embedding-discourse.html) for each file at the bottom for discussion and comments. It really makes clear the purpose and role every file or possible file has in a project.

While it would require frequent maintenance, I think it would be a great addition to the documentation, and overall be worth any maintenance work. I imagine this would probably need to come after #2589 is complete.

**Comment by stefanpenner** [comment]
@chnn ^^

**Comment by stefanpenner** [comment]
cc @chnn / @joostdevries some ideas

**Comment by stefanpenner** [comment]
I love this idea, Will keep this in mind when we make large changes to the site.
No need to keep this open for now.
