### ISSUE TITLE
Dasherized pod names do not work

### ISSUE THREAD

**Issue by phillipsj** [ember-cli/ember-cli#2752]
Using ember-cli 0.1.4. 

Pods generated using:

    $ ember -g resource customerNotes --pod

Generates a pod with the name customer-notes.  However, ember is not able to resolve the templates in the directory.  When I rename the pod to "customernotes" everything works as expected.  Does the dasherize not apply to pods?  If I have time I will try to dig through and see if I can determine the issue.   Just wanted to throw this out there in case it is working as designed.

**Comment by stefanpenner** [comment]
> @tomdale : I finally figure out what changed. I was not camel casing my route names. Previously that worked perfectly fine. However, since the recent update, the route names need to be camel cased and everything works as expected. Feel free to close it, if this expected behavior, however this is different from what I experienced before.

this doesn't sound correct, everything should be dasherized..  Can you share an example?

**Comment by phillipsj** [comment]
Yep I will dig through my commits and find an example.

**Comment by stefanpenner** [comment]
@phillipsj thanks

**Comment by stefanpenner** [comment]
> Yep I will dig through my commits and find an example.
> …

@phillipsj ping

**Comment by phillipsj** [comment]
I cannot find a good example of the behavior in my commits and I am not been able to recreate it.  I will keep trying when I get time again, just might have been strange configuration on my side.  I have went to exclusively using pods when I think may have helped.
