### ISSUE TITLE
Consuming application with the podModulePrefix setting can not use the addon that doesn't use the podModulePrefix but follows the component PODs structure.

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#2768]
My ```ember-cli(v0.1.4)``` application is using ```the podModulePrefix``` and trying to use the ```ember-cli-jquery-ui``` addon that doesn't use ```the podModulePrefix```but follows the component PODs structure like below.
```
app/components/jqui-accordian/component.js
app/components/jqui-accordian/template.hbs
```

It seems that my project  doesn't get components from the addon.I got the error saying ``` "Handlebars error: Could not find property jqui-progress-bar on object" ```

I test my ember-cli app without using ```the podModulePrefix```, it worked fine.

Thanks.

**Comment by stefanpenner** [comment]
we are re-working pods/folder structure stuff, stay tuned.
