### ISSUE TITLE
documentation clarification

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#2778]
As I'm working through the "create a new addon" documentation I *think* I'm missing something/and or the docs aren't something you can read top to bottom.

The first step goes like this (using the name my-x-button)

```
ember addon my-x-button
```

Next you show the index.js w/ the name "my-addon" (diff from step 1)

```
module.exports = {
  name: 'my-addon'
};
```

Then later when you say to create a component ...you show this import for the file

```
// app/components/x-button.js
import XButton from 'ember-x-button/components/x-button';
```

Does all this match up correctly or was this several parts/different starts ?

I've gone through this tutorial a few times over the past week but no matter what I do I can't seem to get beyond the error

Handlebars error: Could not find property 'x-button'

...when used like so in my ember-cli app after a simple npm install

```js
{{x-button focus=false}}
```

I'd like to ensure others (new to ember) don't hit the site and have the same issues I did so I'd PR in a change if/when I get this working (not the state I'm in today sadly).

Any clarification around this (the addon component example in particular) would be helpful! thank you!

here is the full addon (single commit to show what I've changed since the init commit)

https://github.com/toranb/ember-wat

**Comment by stefanpenner** [comment]
we should only consider what is both in package.json and in node_modules, or else we will self-troll .
