### ISSUE TITLE
ember-cli google hangout

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2789]
Contributors + community at large.

Im excited to see so much momentum and help on this project. I think it might be time to think about having a community google hangout soon. (Maybe before or after the holidays?)

Anyways, two things I'm interested in knowing is:

* topics of discussion
* best times/venues for this. (I suspect hangouts, but unsure what times)

I suspect we will be limited to 10 or so actual conversation holders, but we can do it as a hangout on-air for others to view.

topics:

- [ ] docs
- [ ] ...

**Comment by joostdevries** [comment]
@stefanpenner any further details yet?

**Comment by jgwhite** [comment]
Unfortunately due to personal commitments I can’t make the hangout. Looking forward to reading what gets decided though!

**Comment by stefanpenner** [comment]
1pm -> 2pm EST -5 GMT.

For those who are interested in attending, please email me @ stefan.penner@gmail.com with the email you use for google hangouts. I don't have a google apps account, so we wont be able to have more then 10 attendees (i suspect this is fine). If of course this proves insufficient soon enough, we attempt to convince someone with google apps to host, so we can have 15 participants. Hangouts on air is an option, but I have not configured this myself before. If someone wants to configure and host it for us, ping me. :)

Primary Goal of this hangout:

Although ember-cli is progressing nicely, we can always do better. Mostly by
improving things that hurt productivity, and optimizing for contributors.

Lots of the problems and pains we want to tackle are broader in scope, then we
can accommodate in this single hangout. So our goal should be today, to enable
our future productivity (and fun), and bring clarity to the problems we want to solve.

Plan:

 1. identify problems/solution that can enable ourselves
 2. identify the current largest pain-points
 3. attempt to triage order them (for discussion)
 4. as time permits we can dig into the largest of these issues

_note: many of the pain points we experience are likely large topics, so we_

Proposed Problem/Solution format
------

pain:
depends on:
who does this interest:
questions:
steps forward:

**Comment by hhff** [comment]
Can't make it either, I'm in transit - @stefanpenner / all - if someone could do a screen capture I would love to check it out

**Comment by stefanpenner** [comment]
@hhff at the very least we will take notes.

**Comment by hhff** [comment]
ty @stefanpenner !!

**Comment by stefanpenner** [comment]
result of the call:

RFC process
bi-weekly meetings and release plan

------

Ember CLI 01/03/2015

1pm -> 2pm EST -5 GMT

Primary Goal of this hangout:

Although ember-cli is progressing nicely, we can always do better. Mostly by
improving things that hurt productivity, and optimizing for contributors.

Lots of the problems and pains we want to tackle are broader in scope, then we
can accommodate in this single hangout. So our goal should be today, to enable
our future productivity (and fun), and bring clarity to the problems we want to solve.

Plan:
identify problems/solution that can enable ourselves
identify the current largest pain-points
attempt to triage order them (for discussion)
as time permits we can dig into the largest of these issues
note: many of the pain points we experience are likely large topics, so we

identify problems/solution that can enable ourselves

What are we missing to help continue enable contributions and overall
productivity of the project.

ember-cli org (good/bad)
something like: https://waffle.io/ ?
more regular hangouts? weekly/bi-weekly/monthly/quartly ?
I like our current ad-hoc issue ownership pattern, how can we enable this further?
issue as RFC -> PR


Proposed Problem/Solution format
pain:
who does this interest:
questions:
steps forward:

Improve Ember CLI for contributors

short info (3-5 min reading or video)
specific internals (like add-on hooks)
improve inline docs  (see: ember cli/ember cli#2835) 
style guide
re-sync architecture.md (siva)
reduce over all content
link to inline documentation for more detail
focus on how the pieces work together and their goals
test runs are far to slow
(raytiley) share node_modules between all acceptance tests, not just on a per file basis.
update contributing.md
flesh out new changelog rules

Website 
what are the next steps for the website
focus on the CLI itself
break out (stefan will coordinate this)
Ember CLI anatomy (ember cli/ember cli#2751)

Pain Points
identify the current pain-points
group them / put them in triage order
note: As time permits we can dig into the largest of these issues

pain: package management
balancing between two package managers is crazy sauce
bower's choose your own adventure dependency resolution is a common source of pain
NPM's dedupe strategy in it's current state has issues
browserify works, until it doesn't and then its tricky to deal with (mocha for example)
git dependencies can break badly
Maybe CI can error on git dependencies

goal:
bundler'esq sanity to our deps

relevant tech:
JSPM
petal
ember-browserify
browserify
...

who is interested:
 stefan
 chad
 adolfo

questions:
is their an npm solution without browserify?
our ember-addon's don't require it, because they are authored in a compatible convention
is ember-browserify to be included by default?
is ember-brwoserify also the path forward for non-legacy?
packages not available in npm, what do?

steps forward:
Add this to https://github.com/ember-cli/rfcs/

pain: pods aren't fully fleshed out
lots of promise, but many un-paved edge-cases

goal:
pave that path.

who is interested:
trabus

questions:
how do we document and express how this works
what blueprints should support pod format

steps forward:
identify pain-points -> fix them cycle
 experiment by upgrading ghost to pods, what works what doesnt'

pain: esnext performance
new syntax is great, but prohibitively slow for large apps.
we want the improved transpiler, but it will be slower.

goal:
5x -> 10x speed improvement to esnext/recast/ast-types
broccoli fast-boot

questions:
better alternatives?
...

who is interested:
stefan
chad

relevant stuff:
https://esnext.github.io/esnext/
https://6to5.org/
http://www.rich-harris.co.uk/esperanto/
https://github.com/stefanpenner/basic-transpiler-benchmarks
benjamn/ast types#82 

steps forward:
Stefan has a call immediately after this call, with the authors of esnext/6to5/esperanto to try and unite/share the burden

Pain: Website could be organized better

 Prospective users, first time users, experienced users, and blueprint developers all have to sift through a long README to find the documentation they need. By organizing the information into sections, we can treat each audience more effectively.

 We also need a website that easily allows for more sections in the future, such as an API reference that @joostdevries is working on.

Depends on

Some consensus for what steps should be taken. I (@chnn) am happy to do the work, just need to have some clear goals.

Who does this interest

@joostdevries @stefanpenner at the least.

Questions

How should this align with the main Ember site? (Also with the 2.0 roadmap in mind)
What are the main sections/threads for this site?
App developers (CLI consumers)
Addon developers
 Right now it's a Jekyll static site. Is there any reason we would want to use something else, say Ember?
If we go with Ember - Having some sort of search engine support is an absolute must.
Can someone elaborate on the site build process for emberjs.com?

Steps forward

1. Narrow down a list of steps we need to take for the first pass, merge, deploy.
a. Go over the list of 'docs' issues.
b. Create a clear "docs" roadmap  
2. Integrate with @joostdevries work on the API docs.

Pain: 
Ember CLI support for engines

Questions:
What's the path towards getting there?

Who's interested?
Siva

 pain: odd release cycles + improvements in changelog
 who does this interest: 
  - abuiles
 questions:
  - What time frame  should we aim for to release a new version?
  - Jake suggested a format for the changelog, Robert was trying to follow this, we should probably follow this and borrow ideas from (chai?) ember cli/ember cli#2837

 steps forward:
Have a release team
jake craige
Sivakumar Kailasam
Adolfo Builes
Aim  to "bi-weekly" releases (if possible)
Start tracking PR by section? so then we can fix the wording
ember-cli/ember-cli#changelog
co-ord on date/time

Pain: Lazy Loading
bundling "routes/engines"
CSS bundling
Needs conventions

Pain: Web workers
dependencies need to be delivered as fine grain and not concated.

Pain: Tmp Directory In Project
tmp directory being in project leads to editor / performance issues and file watching issues. Requires work in broccoli to resolve.

resolution:
Ray + Rob, should have that hangout with Jo

Pain: File Watching
File watching seems to be fragile, even after watchman. Its also problematic in windows and prevents us from using hard links / junctions which might offer performance benefits.

resolution: (ray)
tmp directory move out
with watchman, pick more more top level roots
experiment without tmp in the directory, can we watch large bower_components and node_module trees

Pain: Environment Configuration (Jake)
From rwjblue gist: "Currently we are building a pile of un-maintainable scenario specific configuration flags partially drivin by the ENV and partially by user configuration.
These are confusing and unmaintainable. current stuff:
stefanpenner/ember cli#930/files
https://github.com/stefanpenner/ember-cli/blob/master/blueprint/Brocfile.js#L5-L11
I would like to propose, we break configuration + ENV up. In addition we should have general configuration flags, which tools can tap into and provide "sensible defaults".

By doing so, we should easily be able to support an arbitrary # of ENV configuration bundles."

problems:
we don't support additional environments
lots of if testing do Y, but its entirely internal

resolution:
ember cli/ember cli#1520

Pain: Contributors showing samples of issues in ember-cli
Before cli we had to just give jsbin samples to reproduce issues but now with ember-cli its a little bit harder to put up samples in case of issues. 

resolution:
`ember debug`
npm version
node verison
os
libuv
npm
OS
bower deps
package.json deps
brocfile.js
config/environment.js
files counts in node_modues vendor bower_components
Who's interested:
Sivakumar Kailasam
Pull request:
ember cli/rfcs#2

Pain: Addon namespacing
Addons can have app code in pod format, which causes resolver issues if the using project has a podModulePrefix defined. Do addons need some sort of namespacing that the resolver is aware of, or should addons be built in a way that they inherit environment vars like podModulePrefix. (ember cli/ember cli#2768)

Resolution:
Suggest use of addon folder instead of app folder?
Have the resolver look for the pod format sans podModulePrefix after regular lookup?
Merge the addon's app tree into the consuming app's tree and convert it to their podModulePrefix if needed

Pain: Upgrading Apps
 Upgrades are too hard. The main issue we discussed was that there are files that are overridden that either shouldn't be(router.js and other "user" files) and ones that need to be, but could be done better(bower.json, package.json). With the coming bi-weekly release cycles, this would be good to tackle quickly
 
 Resolution:
`ember upgrade` command that handles these issues
