### ISSUE TITLE
Add Let's Code Tutorial to tutorials section

### ISSUE THREAD

**Issue by ulisesrmzroche** [ember-cli/ember-cli#2790]
I'm working on a 'Lets Code! project about building authentication backed by  Ember, Ember CLI, JSON Web Tokens & Express. I'm currently on the first part, but I want to finish this by February. Is it ok to add it to the tutorials section?

https://medium.com/@ulisesrmzroche/lets-build-jwt-backed-authentication-with-ember-and-express-5425a1977d23

**Comment by stefanpenner** [comment]
sorry for how long this took to review. It looks great! Good writing!

**Comment by stefanpenner** [comment]
Marking this as resolved, it is your call if you still wish to add it to the tutorials section.

**Comment by ulisesrmzroche** [comment]
Sweet! Yeah, PR incoming if y;all dont mind.. I'm trying to keep it
ever-green and need something to keep me motivated.
ᐧ
