### ISSUE TITLE
path.join in proxy blueprint fails on windows

### ISSUE THREAD

**Issue by bobmyers** [ember-cli/ember-cli#2796]
In the proxy blueprint we have

    req.url = path.join(proxyPath, req.url);

But this would seem to be incorrect. `path.join` does a normalization which under Windows changes slashes to backslashes (ouch!). `path.join` should not be used for URLs, only for file system paths.

This was introduced as part of commit https://github.com/stefanpenner/ember-cli/commit/431e6986d583f2a18522c67529058495d246259f made by @tstirrat.

**Comment by chadhietala** [comment]
This was fixed in #2826
