### ISSUE TITLE
Need better convention for appending to addon default configs

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2823]
We should offer a standardized convention for addon configs that lets people extend the default config without completely ovewriting it.

Just to pick two representative examples: 

 - in `broccoli-asset-rev` you can't add an additional file extension to `replaceExtensions` without copying and pasting the default list (which may change in the future and you will miss out). 
 - in `ember-cli-content-security-policy` you can't tweak one piece of the policy without copying the whole default policy into your own app.

**Comment by stefanpenner** [comment]
should be done, as we pass a shared config object around. Not ideal, but does the trick
