### ISSUE TITLE
[bug] Ember 1.9 Live Reload on IE8

### ISSUE THREAD

**Issue by zyllorion** [ember-cli/ember-cli#2825]
In IE8 using Ember 1.9 I get the following error at the start of page load:
'this.reloader' is null or not an object
On the last line of LiveReload.prototype.addPlugin.

Before that tries to execute and fails, there is an additional message without line number:
LiveReload disabled because the browser does not seem to support web sockets

So maybe the error can be handled gracefully and not execute the code if web sockets are not detected?

xref: https://github.com/emberjs/ember.js/issues/10024

**Comment by stefanpenner** [comment]
likely not going to support IE8 for this.
