### ISSUE TITLE
Load environment variables after build process.

### ISSUE THREAD

**Issue by kodayashi** [ember-cli/ember-cli#2827]
A core tenant of Continuous Delivery (CD) is the ability to modify configuration without rebuilding. Currently, it looks like the only way to specify an environment variable (e.g. "environment": production) is via the .ember-cli file and at build time. However, CD minded teams prefer building once and deploying anywhere. Typical solutions involve reading from a file at startup and initializing environment key/value pairs.

**Comment by stefanpenner** [comment]
> For environments that don't require a different build outcome, you could build an add-on that let's you swap the environment and reinitialize the app as needed, but personally I don't think this needs to be a part of ember-cli itself.

yes this is what we do by default, merely the `meta` tag in the index file changes with config changes the js and css files should remain identical.

**Comment by kodayashi** [comment]
@stefanpenner - Yea I'd agree there (in that ember-cli could manage environment/config in a way that makes doing this a bit easier). You nailed it with the CDN and file swapping -- that's exactly what we ended up doing.

@runspired - I hear you on opting out of minifying code for development/integration and possibly even UAT environments, but we like to minify in staging environments to more accurately reflect application performance as seen in production. Another scenario (which we don't practice, but I've seen done) is two production environments for A/B testing, where you'd like each site to perform as identical as possible to focus on isolating and measuring UX.

Thanks for the feedback guys. Feel free to close this out @stefanpenner.

**Comment by stefanpenner** [comment]
I'll close this, but i will keep this in mind as we continue to improve this area.

**Comment by Alexander-Krause** [comment]
@stefanpenner is there now a designated way to modify the environment without rebuilding the whole application?

**Comment by H1D** [comment]
@Alexander-Krause kinda of a workaround:

0) use [ember-cli-dotenv](https://github.com/fivetanley/ember-cli-dotenv) for config variables needs to be changed
1) update contents of `<meta name="app/config/environment` after deploy (its just an [escaped](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) JSON) using current `.env` contents
2) for Fasboot add `process` to your list of `fastbootDependencies` in your package.json. Then, you can do:
```  
if (typeof FastBoot !== 'undefined') {
    const env = FastBoot.require('process').env.APP_VARIABLE;
}```

**Comment by lougreenwood** [comment]
@H1D 

Could you elaborate on your process a little please? It seems that for statically/prember served sites, there's no .env file bundled into dist, so it's of no use for automatically updating `<meta name="app/config/environment` after a CD deployment.

It seems to me that the way we might tackle this (deploy to Nginx  docker container on AWS) is to:

- Set unique 'template' values for the config values in environment.js
- on development, overwrite these using `process.env.ENVVAR`
- add script to docker init which overwrites the 'template' values in `<meta name="app/config/environment` with actual ENV VAR values from docker container

**Comment by H1D** [comment]
@lougreenwood 

what we do:
Each machine has it's own `.env`. It as a local file delivered by ansible or just "by hands"

Then you going to need some external code to update `<meta name="app/config/environment`. For example simple python script that reads current `.env` and changes `<meta>` according to it

So you build pipeline would be: 1) deploy `dist/` folder, 2) run the script

**Comment by lougreenwood** [comment]
Yeah, seems we've gotten it working with something similar. However, because we use docker we inject actual environment variables into the container, so there's no need for `.env` file in our case.

We're using `gotmpl` to replace the values in the meta tag.

Hopefully, I'm  just about to deploy and put this to rest :)
