### ISSUE TITLE
Using --proxy with self signed SSL certificate

### ISSUE THREAD

**Issue by matthewlehner** [ember-cli/ember-cli#2838]
Using ember-cli 0.1.5 I've just gotten self signed certificates working, but have had to edit some of these files myself. It'd be great to expose this through some kind of config option or command line switch. I can send a PR and update the docs, just want a bit of direction for how you'd like to implement it.

Anyway, this fixes a DEPTH_ZERO_SELF_SIGNED_CERT error and may also remedy the UNABLE_TO_VERIFY_LEAF_SIGNATURE error.

I had to change add the `secure: false` option in [lib/tasks/server/middleware/proxy-server/index.js](https://github.com/ember-cli/ember-cli/blob/v0.1.5/lib/tasks/server/middleware/proxy-server/index.js) like so:

```
    var proxy = require('http-proxy').createProxyServer({
      target: options.proxy,
      ws: true,
      changeOrigin: true,
      secure: false
    });
```

**Comment by KalenAnson** [comment]
+ 1 for this feature. Testing an ssl API server and would love to have the whole stack in my development environment (with a self signed cert).
