### ISSUE TITLE
Fingerprinted sourcemap files not supported in production?

### ISSUE THREAD

**Issue by sohara** [ember-cli/ember-cli#2850]
I've been trying to get sourcemap files working in production builds, and while the map files appear to be correctly built, the url appended as a comment to built js file doesn't include the fingerprint part of the url. E.g I added the following to the Brocfile: 

``` js
  sourcemaps: {
    enabled: true,
    extensions: ['js']
  }
```

And the bottom of our built app file appears as:

``` js
//# sourcemappingurl=app.map
```

as opposed to have the fingerprint included in the file path, e.g. 

``` js
//# sourcemappingurl=app-a1407434fedc870be384371ef5920950.js
```

I believe this was supposed to be enabled via https://github.com/rickharrison/broccoli-asset-rewrite/pull/8 but it appears to not be working.

cc @ef4

**Comment by houfeng0923** [comment]
```
sourcemaps: {
    enabled: true,
    extensions: ['js', 'map']  // dont forget map extensions 
  }
```
