### ISSUE TITLE
Test fails in Chrome after a Livereload-triggered refresh only

### ISSUE THREAD

**Issue by joshuaconner** [ember-cli/ember-cli#2852]
Basically my issue is that I have a test that, when I'm running `ember test --server`, fails on Chrome only on a refresh triggered by LiveReload when I save the test file. 

I've created a minimal repro of my issue here: https://github.com/joshuaconner/ember-cli-test-only-fails-on-livereload. You should be able to run `ember test --server` and then save `tests/unit/components/test-failer-test.js` to see that test fail in Chrome only. You should also be able to reload the page manually to see all tests pass everywhere.

I'm not totally sure this is an ember-cli issue – if it belongs somewhere else, please let me know. Thanks!

```bash
$ ember v --verbose
version: 0.1.5
http_parser: 1.0
node: 0.10.32
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.28
zlib: 1.2.3
modules: 11
openssl: 1.0.1i
npm: 2.1.8
```

**Comment by stefanpenner** [comment]
this seems to have gone stale, if this problem still exists on the latest we can re-open.
