### ISSUE TITLE
When will ember-cli upgrade beyond ember 1.8.1 ?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#2853]
I just updated to ember-cli 0.1.5 and noticed it was still using ember 1.8.1 (totally cool with me btw). Just curious why it wasn't bump'd yet (and when it will be) ? thanks again for the amazing project !

**Comment by knownasilya** [comment]
Has anyone gotten the manual upgrade working?

I get `Uncaught Error: Unknown template object: function` after following the instructions in the [blog post](http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html).

**Comment by gdub22** [comment]
@knownasilya I got the latest stable release running by following the blog post directions.  Make sure you don't have any inlined precompiled templates since they won't be compatible with Handlebars 2.0.0

**Comment by knownasilya** [comment]
@gdub22 how would I find those?

**Comment by gdub22** [comment]
@knownasilya look for any views/components in your app defining its template or layout with`Ember.Handlebars.template`

**Comment by knownasilya** [comment]
So for anyone having this issue, I checked my stack trace, and in `main.js` it had a precompiled template and I worked backwards from there. For me it ended up being an old version of ember-notify which was incompatible with 1.9.
