### ISSUE TITLE
Adding extra environments to environment.js

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#2860]
Currently there is a `production`, `development` and `test` environment.  In out setup we have a `sit` and `pre-production` environment also which need their own specific configurations.  Is it possible to add my own environments?

**Comment by Eptis** [comment]
Is this still the case? I need to output multiple production build with different environments.

**Comment by joostdevries** [comment]
@Eptis unfortunately yes, but with `ember-cli-build.js` we have come quite a bit closer to better config management.

**Comment by stefanpenner** [comment]
will likely be superseed by: https://github.com/ember-cli/rfcs/issues/26

**Comment by wayne-o** [comment]
When should we expect ember-cli/rfcs#26
<https://github.com/ember-cli/rfcs/issues/26> to be usable?

**Comment by stefanpenner** [comment]
> When should we expect ember-cli/rfcs#26
> <https://github.com/ember-cli/rfcs/issues/26> to be usable?

when someone implements it ;)

**Comment by david-duncan** [comment]
rfc @26 looks awesome, but in the meantime you'd be surprised what you can hack up with ember-cli-dotenv if you need the output to be like production but need stuff changed

**Comment by wayne-o** [comment]
Is there anyway to get ember-cli-dotenv to work with ember serve?
