### ISSUE TITLE
Nested components?

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli#2861]
I saw this comment from the 1.5 release:

- #2741 allowed the creation of components with slashes in their names since this is
supported in Handlebars 2.0.

and thought it meant I could make an `inputs/day-selector` component. Seems like everything works until I try to pass in attrs i.e. I can do

    {{inputs/day-selector}}

but not

    {{inputs/day-selector value=value}}

Is this a bug or am I misunderstanding the feature?

**Comment by stefanpenner** [comment]
@abuiles no its, fine. We need to fix `1.9.x`
