### ISSUE TITLE
Add Sass/Less support to app.import

### ISSUE THREAD

**Issue by Bargs** [ember-cli/ember-cli#2872]
I like how Ember CLI builds vendor and first party css into two separate distributable files (app-name.css and vendor.css). Unfortunately when you use a third party sass/less library you lose this separation, as the current best practice seems to be to import the third party library into app.css using the preprocessor's import method.

If I were using Sass and Foundation, for instance, I have to add `@import "../../bower_components/foundation/scss/foundation";` to my app.scss, and the entire Foundation project gets compiled into `assets/app-name.css'.

It'd be awesome if I could import an scss file directly in my Brocfile like so:

`app.import('bower_components/foundation/scss/foundation.scss');`

which would place the compiled Foundation css into `assets/vendor.css`.

As far as I can tell, there currently isn't any way to accomplish this, but maybe I'm missing something?

Thanks!

**Comment by alexlafroscia** [comment]
One potential issue would be the ordering of the imported Sass files -- would you just assume that they should be added to `vendor.css` in the order they are listed in the Brocfile?  One nice thing about importing everything into `app.scss` is that you're explicit about the ordering.

You could also have a `vendor.scss` in `/app/styles/` that imports all of your vendor files -- is importing them in the Brocfile much different/better?

**Comment by ahacking** [comment]
Often you have to override settings prior to importing vendor scss so IMO there is no option but to import from app.scss to precisely control import order.

**Comment by Bargs** [comment]
I would expect the ordering to work the same as it does for regular css files (I assume they're just concatenated in the order they're listed in?). 

If the user needs precise control over the ordering, or needs to override settings as @ahacking mentioned, they could create another .scss under the vendor directory with the imports and settings overrides. 

For example, I could create `/vendor/foundationImports.scss`:

```
@import "../../bower_components/foundation/scss/normalize";
@import "../../bower_components/foundation/scss/foundation";

// Override some settings
$total-columns: 16;
```

And then import that file in my Brocfile: `app.import('/vendor/foundationImports.scss');`

I suppose you could also forget about the Brocfile and just establish a convention that `/vendor/someName.scss` gets compiled into vendor.css. This would be more in line with the way app.scss works, but seems less flexible.

**Comment by ahacking** [comment]
There is another problem with splitting scss into a vendor and app bundle in that the sass processor (and this is probably similar for less) needs all of the scss to produce its output.  Scss variables, mixins and rules defined in a "vendor" set need to be available for the app.scss. I'm not sure the processor can keep generated vendor rules separate from the app ones as the strategy it uses to generate the CSS takes into account all rules.
