### ISSUE TITLE
improve tree descriptions

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2873]
```
Slowest Trees                  | Total
-------------------------------+----------------
...
ES6: App Tree                  | 300ms
Funnel: App JS Files           | 211ms
...
```

* this app doesn't use esnext, so ES6 is misleading (i suspect this is actually es6:modules)
* Funnel is an  implementation detail

**Comment by rwjblue** [comment]
I added these particular descriptions in https://github.com/ember-cli/ember-cli/pull/2857.  Prior to that PR all of these trees showed up as "Class" in the slow tree graph. Clearly we are iterating towards a much better solution. :smile:

**Comment by jakecraige** [comment]
Potentially another topic, but should the trees be hidden by default? Only displaying when using a `--debug` flag. Personally I don't ever look at them unless we're debugging a perf thing so it's just unnecessary output the majority of the time

**Comment by stefanpenner** [comment]
I want people to be very aware of what is slow and what is not slow

**Comment by jakecraige** [comment]
@stefanpenner Is this something you'd consider at 1.0 ? For now, it makes sense for quick debugging which is nice due to constant changes to the transpiler and build phases, but once all that's resolved, it feels unnecessary.

**Comment by stefanpenner** [comment]
@jakecraige I fear people will install, slow transforms, or make silly broccoli choices and then blame ember-cli as a whole. I am fine with letter users opt-out of the logging, or only log if the total time is larger then 1s or something...
