### ISSUE TITLE
Consistently getting "Error: connect ECONNREFUSED" when running `ember serve` after upgrading to 0.1.5.

### ISSUE THREAD

**Issue by dpdawson** [ember-cli/ember-cli#2874]
I have been consistently getting the error message below when running `ember serve` after upgrading ember-cli to 0.1.5.

Sometimes it happens immediately after building and sometimes it happens after loading an app page or test page once or twice, but it always happens quickly.

`ember test --server` doesn't seem to have the same issue.

I'm running OS X Yosemite.

```
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by dpdawson** [comment]
I'm stupid.

**Comment by cmsimike** [comment]
I'm curious - what did you do to fix this? This happens to me in ember cli 2.8 but not 2.7 on otherwise identical setups

**Comment by xcambar** [comment]
Same here. It's happening again in 2.8.0

**Comment by xcambar** [comment]
FWIW: Disabling analytics solves this. See https://github.com/ember-cli/ember-cli/issues/6248
