### ISSUE TITLE
outputPaths.app.css 'app' doesn't work with ember-cli-less

### ISSUE THREAD

**Issue by thomasdashney** [ember-cli/ember-cli#2878]
I tried to change the output directory of app.less, like so:

```javascript
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'app': '/assets/css/web-app.css'
      },
      js: '/assets/js/web-app.js'
    },
    vendor: {
      css: '/assets/css/vendor.css',
      js: '/assets/js/vendor.js'
    }
  }
});
```

Unfortunately it places web-app.css into the default directory: `/assets/web-app.css`. When I uninstalled ember-cli-less and created an `app.css`, it works just fine.

Likely related to #1888?

**Comment by lukesargeant** [comment]
It's not just 'app' that doesn't work. The css hash doesn't work at all with ember-cli-less which just compiles app/styles/app.less to dist/assets/<your-app>.css

**Comment by bosschuyler** [comment]
I'm also dealing with this issue.  I'd like to bump this.  The output path doesn't affect the output of LESS files at all for me.  Any word on this issue?

**Comment by lukesargeant** [comment]
@bosschuyler I've just submitted a pull request that should fix this: https://github.com/gdub22/ember-cli-less/pull/7

**Comment by chadhietala** [comment]
This seems to be an issue with ember-cli-less.  If that's not the case please reopen.
