### ISSUE TITLE
Security Errors on Clean Project

### ISSUE THREAD

**Issue by hcatlin** [ember-cli/ember-cli#2881]
I'm new to ember and ember-cli, but after generating a new ember app via the CLI command, I immediately get a security warning in my Developer Tools. 

I installed the newest stable ember via npm. Then followed the Getting Started guide and installed Bower, etc. 

I generate a new project via ```ember new embertest``` (or any name, I just happened to use that for my very, very clean example).

I start up the server ```ember server``` and load the default page. 

![image](https://cloud.githubusercontent.com/assets/111/5603563/643fc3ca-9340-11e4-87fe-0456b86216ad.png)

````
[Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
````

Kind of stops me in my tracks to start a clean app with so many errors... It seems to be coming from jquery-color. I didn't include that, and don't know what it is or why it's causing errors.

From what I've glanced at, I assume this is some kind of security rule thing I need to go learn about. But, it seems a bit weird that the default clean app violates its own whitelist... :P Kind of throws off the feeling of a nice new app to have to go learn the security configuration. 

Mac Yosemite 10.10.2
Node version: v0.10.33
NPM: 2.1.11

My plan is just to ignore it and hopefully it doesn't mean anything actually important...?

**Comment by rwjblue** [comment]
A newly generated app should not have CSP violations.  These are most likely being caused by an extension that is injecting scripts/styles into the page.  You can confirm by using an incognito window (which does not run extensions by default).

**Comment by hcatlin** [comment]
Aaaaaaand, turns out it was a Chrome extension! It was the Okta plugin that I had to disable to stop this warning. Yo! Okta guys (/cc @rgupta-okta @jontodd), how about having your plugin not inline stuff on pages that aren't secured!
