### ISSUE TITLE
Generating routes/resources removes comments from router.js

### ISSUE THREAD

**Issue by tylergaw** [ember-cli/ember-cli#2882]
I noticed this after updating from `0.14.0` to `0.15.0`. 

Seems related to nested routes/resources generation added in https://github.com/ember-cli/ember-cli/pull/2748

Steps:
- Created a new project with `ember new projectname`
- Added comments to `router.js`. One multi-line with `/**/` and one single-line with `//`

example `app/router.js`
```javascript
import Ember from 'ember';
import config from './config/environment';

/*
  This is an important multi-line comment that I want
  to keep around.
*/
var Router = Ember.Router.extend({
  location: config.locationType
});

// This is a single line comment I want to keep.
Router.map(function() {
});

export default Router;
```

Generate a new resource with 
```
ember g resource items
```

Generates the resource, removes the comments.

```javascript
import Ember from "ember";
import config from "./config/environment";

var Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.resource("items", function() {});
});

export default Router;
```

The same thing happens when generating a route.

**Comment by tylergaw** [comment]
Another thing related, not sure if it's worth opening another issue for, but may cause some confusion when people switch to `0.15.0`. It also now changes all single-quotes to double-quotes.

**Comment by quaertym** [comment]
Yep, I just experienced the single-quote -> double-quote issue.

**Comment by stefanpenner** [comment]
likely related to: https://github.com/ember-cli/ember-router-generator/blob/master/lib/ember-router-generator.js#L174

**Comment by stefanpenner** [comment]
it seems like recast supports comment preservation: https://github.com/benjamn/recast/blob/master/test/comments.js

**Comment by stefanpenner** [comment]
I believe the prettyPrint feature is the culprit. 

https://github.com/benjamn/recast/blob/452c486519fb73d9b83faf8bc3bec688b17d16a9/lib/printer.js#L112
https://github.com/benjamn/recast/blob/452c486519fb73d9b83faf8bc3bec688b17d16a9/lib/printer.js#L65-L67

cc @abuiles

**Comment by abuiles** [comment]
@tylergaw @stefanpenner thanks! I'll try to address this tomorrow.

**Comment by stefanpenner** [comment]
:+1:
