### ISSUE TITLE
Broccoli throws error if `vendor` folder doesn't exist

### ISSUE THREAD

**Issue by mohislm** [ember-cli/ember-cli#2883]
Line 189 in lib/broccoli/ember-app.js

    vendor: fs.existsSync('vendor') ? unwatchedTree('vendor') : null

If the `vendor` directory doesn't exist, Broccoli will spit an error saying:

    Error: Invalid tree found. You must supply a path or an object with a `read` function.

The `.gitkeep` file in `vendor` folder is already doing the trick here (always keeping this empty directory). So, why did you include the `null` value at line 189 at the first place which is doing nothing (in fact it's evil)?

**Comment by stefanpenner** [comment]
we should support remove vendor if it is not used.

**Comment by rwjblue** [comment]
We should be checking to see if vendor tree is falsy before using it. That is why we set to null if the folder is missing. 

If that does not work, we definitely should fix it.

**Comment by abuiles** [comment]
This doesn't seem to be an issue any more? I just tried in a test app, removed vendor and `server`, `test` and `build` worked fine.
