### ISSUE TITLE
How to "name" an initializer (inside an ember-cli addon)

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#2888]
I have a simple initializer in my ember-cli addon but because it's essentially just the initialize function ... how can I name it?

```js
import Store from '../store';

export default function(container, application) {
    application.register('store:main', Store);
    application.inject('controller', 'store', 'store:main');
    application.inject('route', 'store', 'store:main');
}
```

When I attempt to export a true Ember.Application.initializer instead I get the error

"Assertion Failed: An initializer cannot be registered without an initialize function"

```js
import Ember from 'ember';
import Store from '../store';
 
var initializer = Ember.Application.initializer({
    name: 'store',
    initialize: function(container, application) {
        application.register('store:main', Store);
        application.inject('controller', 'store', 'store:main');
        application.inject('route', 'store', 'store:main');
    }
});
 
export default initializer; 
```

**Comment by rwjblue** [comment]
```javascript
export function initialize(container, application) {
  /* do stuff */
}

export default {
  name: 'some-name',
  initialize: initialize
}
```

Or if you don't want to type it all out, just run `ember g initializer some-name` and it will generate one for you (based on [this](https://github.com/ember-cli/ember-cli/blob/master/blueprints/initializer/files/app/initializers/__name__.js) blueprint).

**Comment by rwjblue** [comment]
Also mentioned at http://www.ember-cli.com/#initializers

**Comment by toranb** [comment]
Ah yes :)

looks like the mistake was mine (as usual) - I had exactly what you listed but didn't realize this was in the app/initializers file (not the addon/initializers)

https://github.com/toranb/ember-cli-simple-store/commit/d16e84e97303223dace0add7235a76f3d09ea4f9

thanks for the continued baby sitting (sorry for the wasted issue @rwjblue)

**Comment by rwjblue** [comment]
No worries!
