### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by bmcorser** [ember-cli/ember-cli#2890]
Possibly similar to #2157 and #998

I ran `ember init` and `ember server`, everything seems to run OK, but after I added an `app.import` statement for Lo-dash in my `Brocfile.js`, when I run `ember server` and pay a visit in my browser, I see "define is not defined".

``` bash
$ ember version
version: 0.1.5
node: 0.10.33
npm: 2.1.8
```

**Comment by ChristianGreinke** [comment]
Relates to: #2877

**Comment by bmcorser** [comment]
Could be related...

`ember build` seems to build `vendor.js` properly, but then I get "Could
not find module lodash" from the browser :sadface:

**Comment by jakecraige** [comment]
You cannot just app.import lodash since it doesn't export a module to import. You either need to use the global or use an addon that handles this for you like [ember-cli-lodash](https://www.npmjs.com/package/ember-cli-lodash)

**Comment by bmcorser** [comment]
And there isn't a Lo-dash build that exposes an ES6 module?

**Comment by jakecraige** [comment]
I don't really know, if they do.

I pretty sure we don't support directly importing them anyways. I may be wrong on that front though.

**Comment by rwjblue** [comment]
https://github.com/lodash/lodash-es6

**Comment by foxnewsnetwork** [comment]
Was also having similar trouble, apparently, on 0.1.5 if you:
1. ember new my-project
2. add app.import("some_file/that_does/not_exist") to your Brocfile.js
3. run ember serve

Everything compiles, but when you happily navigate over to your browser, you get an error that defined is not defined. If you inspect your vendor.js file, it's most depressingly blank.

Granted software was meant to give the engineer an inferiority complex as it's always my fault when something goes wrong, but please consider adding some sort of throw error when one attempts to import nonexistent files instead of failing silently.

**Comment by dustinfarris** [comment]
I get this without any app.imports if I `npm link` my addon.

**Comment by ef4** [comment]
I think this is fixed by https://github.com/ef4/broccoli-sourcemap-concat/commit/0669d2014d3405540c60e6c1ad0ced843a72b3f3 which is released as broccoli-sourcemap-concat 0.4.3. If you reinstall node_modules you should pick up that fix.

**Comment by stefanpenner** [comment]
Thanks @ef4

**Comment by stefanpenner** [comment]
We will reopen if that doesn't fix it

**Comment by dustinfarris** [comment]
Upgrading to the new broccoli-sourcemap-concat now gives:

```
Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
```

Should I open an issue there?

**Comment by jakecraige** [comment]
@dustinfarris This question will sound dumb, but does that file exist? The upgrade fixed silent failures due to files not existing. So that showing up sounds like the correct thing, and that you likely don't have that file in your project.

**Comment by dustinfarris** [comment]
@jakecraige the file does exist in an addon that i have `npm link`ed into my project.  Does `npm link` not work for addons that have bower requirements?

**Comment by stefanpenner** [comment]
> @jakecraige the file does exist in an addon that i have npm linked into my project. Does npm link not work for addons that have bower requirements?

npm link should not affect bower related stuff.

bower files should live in bower_components

ps. hopefully we can kill the duel package management crap soon, it makes me so tired.

**Comment by dustinfarris** [comment]
@stefanpenner sorry for the persistent headache, but do I have to bower install this requirement separately in my ember-cli project if I am going to npm link the addon?

**Comment by jakecraige** [comment]
@dustinfarris Yes, we have an automated way to do this though. You create a blueprint with the name of your addon, and in the `afterInstall` hook you run `this.addBowerPackageToProject('the-package')`. The docs [explain how to create a blueprint](http://www.ember-cli.com/#blueprints). You the use `ember install:addon your-addon` and it'll set it up and run the blueprint for you automatically.

**Comment by dustinfarris** [comment]
awesome.  thanks for the quick responses.

**Comment by stefanpenner** [comment]
> @stefanpenner sorry for the persistent headache,

nope, not your fault. I also feel this pain :)

**Comment by sajt** [comment]
I got this error. I only deleted bower_components, node_modules dist and tmp
after it install again with npm install.

**Comment by sajt** [comment]
Update: I found it. It is updated to a new version and needed some changes in the package and bower.json file. Here: https://github.com/ember-cli/ember-cli/releases/tag/v2.3.0-beta.2
But it is needed to change app/app.js line 3 to this:
`import loadInitializers from 'ember-load-initializers';`
