### ISSUE TITLE
I can generate a helper that won't be automatically resolved

### ISSUE THREAD

**Issue by bmcorser** [ember-cli/ember-cli#2891]
`ember generate helper cake` will happily make the helper and test templates, which without a `-` in the name [won't be resolved](http://www.ember-cli.com/#resolving-handlebars-helpers).

If there's no `-`, it would be useful if the generator stopped or maybe just informed the user their new helper must be explicitly registered.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/ember-cli-auto-register-helpers may be of interest to you.

I am unsure how to convey that this won't be auto-resolver without a `-`, maybe including the above add-on is the right thing.

**Comment by bmcorser** [comment]
It would also slim the docs I referred to by a few paragraphs, but that might not be a good thing. Making the mistake meant that I learned something about how Ember automatically loads things.

I think pointing the user to relevant documentation would be a good approach. The message doesn't need to explain everything, something like the below would do the trick:

> The name of your helper doesn't contain a dash, you will need to explicitly register it. Please see: `<docs url>`

The docs could also point to your auto-register addon if people _really_ want single-word helper names :)

**Comment by stefanpenner** [comment]
i suspect we should just bundle the add-on and be done with it.

thoughts @rwjblue ?

**Comment by rwjblue** [comment]
I am not super opposed to including by default, but I think that I would prefer to print a warning that non-dashed helpers will not be automatically resolved, but if that is what you want you can include the addon.

**Comment by knownasilya** [comment]
At least print the warning for now.

**Comment by stefanpenner** [comment]
they are all resolved now
