### ISSUE TITLE
[BUG] Edit Mode During Ember Init Not Saving

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2892]
Trying to upgrade to 0.1.4 to 0.1.5 and when I choose to edit the file VI opens I make changes and then I end up in an infinite loop of inquirer asking me what I want to do with package.json.

![](http://i.imgur.com/QIT60Qv.png)

Doesn't seem to be inquirer it's self as 0.1.4 used the same version.

**Comment by chadhietala** [comment]
Digging into this further [`applyPatch`](https://github.com/ember-cli/ember-cli/blob/602a1c4558fa3af8fef21b75341945099dc9f82a/lib/models/edit-file-diff.js#L33) isn't even getting called. Still investigating...

**Comment by chadhietala** [comment]
So I've been looking at this for some time now and I'm pretty stumped on to why this is happening.  I placed debug statements in `invokeEditor`.

```
  ember-cli:edit-file-diff /Users/chietala/workspace/ember-cli-linkedin/i18n/tmp/edit_file_diff-tmp_difference_dir-w2qMGoRu.tmp +0ms
  ember-cli:edit-file-diff editor: vi +7ms
  ember-cli:edit-file-diff editorProcess Code: 1 +14s
```
Some how the currentDiff.diff file gets lost. I was able to confirm this by switching $EDITOR to sublime. When Sublime launches the contents of the file is there but saving results in an "Unable to save file" error.

I want to try on another machine to see if I can reproduce to make sure it's nothing weird with my system.

**Comment by stefanpenner** [comment]
@rondale-sc you helped implement this originally, any feedback/advice for señor @chadhietala ?

**Comment by rondale-sc** [comment]
@chadhietala What version of Vi(m) and operating system are you on.  Could be something we haven't encountered yet.  Maybe I can replicate.  :)

**Comment by chadhietala** [comment]
I hate software.

vi always exists with 1. vim always exists 0.

[This line](https://github.com/ember-cli/ember-cli/blob/602a1c4558fa3af8fef21b75341945099dc9f82a/lib/models/edit-file-diff.js#L64) is the line that is in question.

**Comment by chadhietala** [comment]
Going to close this as there is no good way to fix this and is known issue. Future travelers can verify by running the following in their terminal.

```
vim foo
echo $? // 0
vi foo
echo $? // 1 trololo
```

**Comment by rondale-sc** [comment]
Weird.  Got ![](http://i.imgur.com/fa6pbWr.png) on my system.  

Vi: 7.3
OSX: 10.9.2
zsh: 5.0.5

Is your vi aliased in any way?

**Comment by chadhietala** [comment]
Vi is the system binary at `/usr/bin/vi`.  There is a history of this with both VI and VIM. Here is an article of where it was [borked in snow leopard](http://tooky.co.uk/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x/).  It have something to do with .vimrc.  I'm using a default install of Janus with vim.

__System Specs:__
Vi: 7.3
VIM: 7.3
OSX: 10.9.5
zsh: 5.0.2

**Comment by rondale-sc** [comment]
Weird.  Hopefully, if anyone else runs into this they'll find this issue.  Thanks for lookin' into it @chadhietala 

Cheers :beers:
