### ISSUE TITLE
add debug command to prune + reset watchman

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2894]
sometimes I do the following

```sh
(for root in $(watchman watch-list | jq '.roots | .[]'); do watchman watch-del $(echo $root | sed 's/"//g') ; done)
```

We need to stop using as many roots when using watchman. Once we can get the tmpdir out, we will be in a much better place to do this.

**Comment by stefanpenner** [comment]
this should by default actually only prune watched roots residing in the current directory

**Comment by jonathanKingston** [comment]
@stefanpenner just to verify the outcome of this is that watchman runs out of instances (On linux here with inotify), I can up my instance allowance or restart the server also to fix this.

Ember serve silently continues to serve the app but doesn't warn about expiration of instances.

Running the following fails:
```
watchman watch /home/user/appName/app/
{
    "version": "3.0.0",
    "error": "A non-recoverable condition has triggered.  Watchman needs your help!\nThe triggering condition was at timestamp=1422192203: inotify-add-watch(/home/user/appName/node_modules/ember-cli/node_modules/bower/node_modules/insight/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/test/number/is-nan) -> No space left on device\nAll requests will continue to fail with this message until you resolve\nthe underlying problem.  You will find more information on fixing this at\nhttps://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n"
}
```

That is what you are trying to clean up here right?

**Comment by stefanpenner** [comment]
i suspect so, i don't use linux so the error manifests differently as such it is hard to confirm with certainty

**Comment by ballPointPenguin** [comment]
Thanks @stefanpenner your bash foo worked for me as well.

**Comment by steveyken** [comment]
FWIW Watchman 3.1.1 also adds `watchman watch-del-all` command. Might save you a few keystrokes from the original bash. Ref https://facebook.github.io/watchman/docs/cmd/watch-del-all.html

**Comment by stefanpenner** [comment]
Yay finally!

**Comment by Aathi** [comment]
@steveyken Tnx, You really saved my time
