### ISSUE TITLE
Ban underscored module names

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2897]
We currently let `route:task-detail` resolve to file `app/routes/task_detail.js`.

But `route:task-detail/child-route` does not resolve to file `app/routes/task_detail/child-route.js`.

This is inconsistent and confusing. Given that dashes are the officially blessed convention, I suggest we ban module names containing underscores, and I suggest we do it at build time rather than the resolver, so the problem does not go unnoticed by people porting away from the global resolver.

Questions:
 - should we throw or deprecate? (I'm suggesting throw.)
 - should we do it at build time or at resolver lookup? (I'm suggesting build time.)
 - should this only apply to directories and not files, since files currently work are therefore safe?

**Comment by stefanpenner** [comment]
> I suggest we ban module names containing underscores, and I suggest we do it at build time rather
+ 1000

**Comment by stefanpenner** [comment]
> should we throw or deprecate? (I'm suggesting throw.)

throw

> should we do it at build time or at resolver lookup? (I'm suggesting build time.)

people may doit by mistake in the resolver, we may want to throw.

> should this only apply to directories and not files, since files currently work are therefore safe?

I am inclined to ban it in files as well, ambiguity serves no-one

**Comment by rwjblue** [comment]
I think we should make the resolver an addon and have it make a default set of tests that check module names for bad patterns (like underscores). Then adding a dile like this would fail a test run.

**Comment by rwjblue** [comment]
Oh, and I agree we should ban everywhere.

**Comment by stefanpenner** [comment]
@ef4 do you have time to work on this?

**Comment by dopin** [comment]
+1
I just hit this today.
I work on both Ember and Rails. Rails has underscored file name convention. So Rails users may confuse, I guess.
It would be nice if Ember-CLI warns or throw errors.
