### ISSUE TITLE
Is it possible to access app configuration from an addon?

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#2898]
I've tried `import config from '../config/environment';` but it doesn't work. Alternatively is there a way for apps to provide configuration to addons' client-side code?

**Comment by jakecraige** [comment]
You can access it in the `app` tree, but not the `addon` tree

**Comment by aexmachina** [comment]
Okay, and is there any way for apps to provide config to addons?

**Comment by jakecraige** [comment]
Not that I'm aware of currently. It could possibly be part of the new config story as that's something this is that's requested a lot, and would definitely have value.

**Comment by aexmachina** [comment]
Okay, yes I agree. Cool thanks.

**Comment by rwjblue** [comment]
It is possible, depending on your scenario.

http://discuss.emberjs.com/t/best-practices-accessing-app-config-from-addon-code/7006

**Comment by jakecraige** [comment]
Ooh nice. Thanks for that link @rwjblue
