### ISSUE TITLE
Option to use custom import name instead of Ember in default Blueprints

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli#2899]
When generating any blueprints that come with Ember CLI, the Ember module is always imported as `Ember`. For example:

```
import Ember from 'ember';
```

The teams I work with prefer to use `Em` across the board and I've seen many code examples across the web doing so too. For example:

```
import Em from 'ember';
```

Manually changing Ember to Em is tedious but so is using Ember everywhere one wants to use Em. Thus, I would like to suggest an option for overriding the variable name Ember is imported as.

I know this isn't the biggest issue in the world so do you think this warrants a custom option? I imagine it would be technically easy - just a template variable and an option in the Brocfile (or something along those lines).

**Comment by Kuzirashi** [comment]
@offtopic
Why one needs to keep this import statement? If I delete this nothing happens I can still use Ember and Em. Also, when I use `import Ember from 'ember'` i still use `Em` all the time and I don't get any errors using Ember CLI. Could someone explain it's purpose? Sorry for offtop.

**Comment by jakecraige** [comment]
You can create custom blueprints to use instead of the built in ones. You could create it as an addon that your team can install in your apps. The docs explain how to do this [here](http://www.ember-cli.com/#blueprints)

I don't think this is something we want to do since it's so minor and you can currently fix it with an addon. 

@Kuzirashi Currently Ember is still exposed as a global so that's why it works. JSHint should complain about it though.

**Comment by abuiles** [comment]
Since this is such a special case I'd say overriding the blueprint as @jakecraige suggest would be the best thing to do, please try that and let us know how it goes.

**Comment by sir-dunxalot** [comment]
I agree that creating custom blueprints is an option for some generators like a model or controller but it's not a sustainable with larger blueprints like app where updating Ember CLI with `ember init` would not update the app as intended.

Thanks for the quick responses.

**Comment by jakecraige** [comment]
Just use `Ember`, hahah :stuck_out_tongue: 

Anyways, we do plan on making the upgrade path less destructive so after the initial init, it may not be a big problem for you.

**Comment by stefanpenner** [comment]
i believe the idea is to allow AST transforms to all blueprints via an add-on. This allows people to do many things

**Comment by sir-dunxalot** [comment]
Sounds great. Thanks!
