### ISSUE TITLE
ember-cli expected ./server/index.js to be the entry for your mock or proxy server

### ISSUE THREAD

**Issue by tmquinn** [ember-cli/ember-cli#2903]
This error will be thrown if you have any file in the ember-cli root that starts with 'server', i.e. 'server.js'

**Comment by rwjblue** [comment]
Yep.  Don't do that. :wink:

**Comment by zeiv** [comment]
Can you explain a bit about why that's a bad idea?

**Comment by stefanpenner** [comment]
@zeiv it is a file/folder ember-cli claims ownership of for when a team needs additional development servers running during `ember s`

**Comment by zeiv** [comment]
Gotcha.  So for a project with an "integrated" API, on node and Express for example, would it be better to make an `api` folder within the ember-cli generated root folder, or to put the ember app into a `frontend` folder in the node root directory?

**Comment by ballPointPenguin** [comment]
Fastboot warning:
if you follow https://github.com/ember-fastboot/fastboot-app-server#quick-start
don't name your file server.js, but something else like fastboot-server.js
