### ISSUE TITLE
Behaviour of pods options is very confusing

### ISSUE THREAD

**Issue by eoinkelly** [ember-cli/ember-cli#2904]
I think the behaviour of the pod options is extremely confusing. To understand what `podModulePrefix` and `usePodsByDefault` actually do I documented the following scenarios:

### Test 1: default behaviour

1. Install ember-cli 0.1.5
1. Change nothing in config
1. The route generator **never** uses pods. Adding the `--pod` flag makes no difference i.e.

    ```
    # both commands produce exact same output
    ember g route blah
    ember g route blah --pod
    ```

### Test 2: Add podModulePrefix

1. Install ember-cli 0.1.5
1. To config add:

    ```
    podModulePrefix: 'podstest/pods',
    ```
1. The route generator **always** uses pods. Adding the `--pod` flag makes no difference i.e.

    ```
    # both commands produce exact same output (both use pods)
    ember g route blah
    ember g route blah --pod
    ```

### Conclusions

So we deduce that the consequences of adding `podModulePrefix` are

* All generators that support pods will use pods
* Makes the --pod flag redundant
* In essence it tells ember-cli to _use pods by default_

### Test 1: usePodsByDefault: false

1. Install ember-cli 0.1.5
1. To config add:

    ```
    podModulePrefix: 'podstest/pods',
    usePodsByDefault: false,
    ```
1. The route generator **always** uses pods. Adding the `--pod` flag makes no difference i.e.

    ```
    # both commands produce exact same output (both use pods)
    ember g route blah
    ember g route blah --pod
    ```

### Test 2: usePodsByDefault: true

1. Install ember-cli 0.1.5
1. To config add:

    ```
    podModulePrefix: 'podstest/pods',
    usePodsByDefault: true,
    ```
1. The route generator **never** uses pods. Adding the `--pod` flag makes no difference i.e.

    ```
    # both commands produce exact same output (neither use pods)
    ember g route blah
    ember g route blah --pod
    ```

### Consequences

* `usePodsByDefault: false` is a noop (as expected)
* * The --pod flag is still redundant
* `usePodsByDefault: true` seems to disable pods completely. _I think this is very unexpected behaviour!_

## Conclusions

* I could not find a scenario where the `--pod` flag actually did anything. Have I missed something?
* To get my app to _"use pods by default"_ I just have to set the `podModulePrefix`. It is unclear to me what setting `usePodsByDefault` achieves.

**Comment by eoinkelly** [comment]
I'm happy to turn this into real test cases or work on a fix btw.

**Comment by trabus** [comment]
I'm unable to recreate the issue that you're encountering. I just created a fresh 0.1.5 project and this was my output:
### Test 1: Default behavior
```
λ ~/Documents/cli/pods-test/ master* ember g route blah  
version: 0.1.5
installing
  create app/routes/blah.js
  create app/templates/blah.hbs
installing
  create tests/unit/routes/blah-test.js
λ ~/Documents/cli/pods-test/ master* ember g route blah --pod
version: 0.1.5
installing
  create app/blah/route.js
  create app/blah/template.hbs
installing
  create tests/unit/blah/route-test.js
```
### Test 2: Default using the -p shortcut
```
λ ~/Documents/cli/pods-test/ master ember g route foo
version: 0.1.5
installing
  create app/routes/foo.js
  create app/templates/foo.hbs
installing
  create tests/unit/routes/foo-test.js
λ ~/Documents/cli/pods-test/ master* ember g route foo -p
version: 0.1.5
installing
  create app/foo/route.js
  create app/foo/template.hbs
installing
  create tests/unit/foo/route-test.js
```
### Test 3: After defining podModulePrefix
```
λ ~/Documents/cli/pods-test/ master* ember g route taco
version: 0.1.5
installing
  create app/routes/taco.js
  create app/templates/taco.hbs
installing
  create tests/unit/routes/taco-test.js
λ ~/Documents/cli/pods-test/ master* ember g route taco -p
version: 0.1.5
installing
  create app/pods/taco/route.js
  create app/pods/taco/template.hbs
installing
  create tests/unit/pods/taco/route-test.js
```
### Test 4: After defining `usePodsByDefault: true`
```
λ ~/Documents/cli/pods-test/ master* ember g route burrito
version: 0.1.5
installing
  create app/pods/burrito/route.js
  create app/pods/burrito/template.hbs
installing
  create tests/unit/pods/burrito/route-test.js
λ ~/Documents/cli/pods-test/ master* ember g route burrito -p
version: 0.1.5
installing
  create app/routes/burrito.js
  create app/templates/burrito.hbs
installing
  create tests/unit/routes/burrito-test.js
```

**Comment by eoinkelly** [comment]
Ahem, turns out I had a forgotten `"pod" : true,` in `~/.ember-cli`. Doh. :cry: Sorry for taking up your time chasing my error.
