### ISSUE TITLE
camelCased URL being requested from REST API instead of hyphenated URL

### ISSUE THREAD

**Issue by cowboy** [ember-cli/ember-cli#2906]
I'm using v0.1.5 of ember-cli with a pod structured app.

* `app/pods/applicant/model.js` contains a relationship where `DS.belongsTo('applicant-state', {async: true})`.
* `app/pods/applicant-state/model.js` is uninteresting in every conceivable way.

When I try to display an applicant, I see a console error like `GET http://api.loc/applicantStates/8 404 (Not Found)`.

Is the camelCasing normal?

My API URLs are all hyphenated, like `http://api.loc/applicant-states/8`

**Comment by stefanpenner** [comment]
can you should how the link is being generated?

no it is not normal.

**Comment by stefanpenner** [comment]
> Is the camelCasing normal?

no

**Comment by cowboy** [comment]
I'm trying to render an applicant by going to the route for an applicant. I'm not doing anything else.

**Comment by stefanpenner** [comment]
> I'm trying to render an applicant by going to the route for an applicant. I'm not doing anything else.

is "going" via direct URL manipulation in the address bar, or via link-to, or via transitionTo or..

**Comment by cowboy** [comment]
Direct URL in the address bar.

**Comment by stefanpenner** [comment]
an, this is the API request that is incorrect. For some reason I though this was the page you navigated to.

**Comment by cowboy** [comment]
Apologies if I was unclear.

FWIW, I've worked around the issue with this code (via @bmac):

```js
export default DS.RESTAdapter.extend({
  pathForType: function(type) {
    var dasherized = Ember.String.dasherize(type);
    return Ember.String.pluralize(dasherized);
  }
});
```

**Comment by stefanpenner** [comment]
@cowboy nah i was multi-tasking and didn't notice the details.

@bmac thanks!

we can keep this issue open here, but it seems like ember-data is normalizing incorrectly so I suspect it is something we need to fix in ember-data.

**Comment by stefanpenner** [comment]
more specifically https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1828-L1830

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/issues/2318 would fix this

**Comment by stefanpenner** [comment]
ember-data bug
