### ISSUE TITLE
addon `npm link` — "define is not defined"

### ISSUE THREAD

**Issue by dustinfarris** [ember-cli/ember-cli#2908]
I have an addon that can be installed via npm without any issues, but fails if i try to npm link it.

```
cd my-addon
npm i
bower i
npm link
cd ../my-ember-cli-project
npm i --save-dev my-addon
npm link my-addon
ember s
```

From the console, everything seems in order, but when i fire up the browser I get a JavaScript error:

```
Uncaught Reference Error: define is not defined
```

**Comment by stefanpenner** [comment]
duplicate: https://github.com/ember-cli/ember-cli/search?q=define+is+not+defined&type=Issues&utf8=%E2%9C%93

**Comment by dustinfarris** [comment]
@stefanpenner are you sure?  I read #2890 and #2877 before filing this.  Both seem to be related to app.imports in Brocfile, which I do not use in my addon.

**Comment by jakecraige** [comment]
@dustinfarris What's in `my-ember-cli-project`, an addon in there could breaking it. That's probably what it is

Pretty much, we need a reproducible case for this. I've been working on an addon today that's linked with no trouble.

**Comment by dustinfarris** [comment]
my-ember-cli-project is a brand new project from `ember new`

The addon is [dustinfarris/ember-django-adapter](https://github.com/dustinfarris/ember-django-adapter).

To reproduce:

```
git clone git@github.com:dustinfarris/ember-django-adapter
cd ember-django-adapter
npm i
bower i
npm link
cd ..
git clone git@github.com:dustinfarris/edatest-web
cd edatest-web
npm i
bower i
npm link ember-django-adapter
ember s
```

Open localhost:4200 in your browser, and you should see the error.
