### ISSUE TITLE
resource generator and inflector bug

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#2917]
how to repo:

```
ember g resource missives                                                                                                               
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create app/models/missife.js
installing
  create tests/unit/models/missife-test.js
installing
  create app/routes/missives.js
  create app/templates/missives.hbs
installing
  create tests/unit/routes/missives-test.js
```

"missife" seems wrong.

`app/models/missife.js`

**Comment by stefanpenner** [comment]
I don't want to fix every possible inflection. Instead maybe we need a way to opt out briefly? Thoughts?

**Comment by eccegordo** [comment]
Not a major issue for me, just seemed curious. Wasn't sure if there was a typo or bigger issue in the inflector. 

But sure something like

```
ember g resource missives  --custom

or 

ember g resource missives  --no-inflection
```
might be nice. But by no means an urgent need.

One question I would curious about is how does this intersect with all the downstream conventions and expectations of the resolver behavior. In other words if I start trying to opt out of pluralization or special irregular inflections, am I going to create more hassle down the road.

I think opting out is fine but needs to be very obvious what the implications are vis-a-vis the resolver etc.

For example I can never remember which is more correct

```
ember g resource post
```

or

```
ember g resource posts
```

That nuance only gets worse with irregular inflections and pluralizations. I also wonder about other languages.

But any rate, just a heads up you can close this issue if not worth fixing.

**Comment by et** [comment]
Is the inflection really necessary? Seems similar to the rails inflector where the cons outweigh the pros (number of issues vs actually benefit).

**Comment by ahacking** [comment]
I have the same trouble remebering which convention should be used where.

IMO inflection conventions are one of the worst features of modern approaches.  The same issue comes up again and again over at json api with endpoint names, doing a get of a singular resource vs get of a collection vs type keys and values within json. Property keys of  person_id, person_ids, and endpoints /people/xx vs /person/xx.  Even with inflections it is still kind of arbitary.

Singular everywhere never has an issue.

If a distinction between the singular case and plural is required then a static prefix or suffix like 'CollectionOfFoo/FooCollection' or 'ListOfFoo/FooList' doesn't require inflections.

Everyone will hate this of course.

**Comment by stefanpenner** [comment]
Maybe we should fix English :p

**Comment by eccegordo** [comment]
@stefanpenner Yeah things would would be so much easier if we just started coding in Latin. Or even Spanish with or some language with regular and predictable conjugations and pluralization rules. :smile:

**Comment by eccegordo** [comment]
@ahacking @stefanpenner I actually kind of like the idea of `FooCollection` or `CollectionOf...`

Just out of curiosity are there sufficient hooks to customize the resolver to behave this way? So that with just a little bit of configuration stuff like this could "just work".

That might be the best release valve for this kind of stuff. Don't have to impose it on everybody. But allows slight configuration.

I am generally in favor of Convention over Configuration. But when comes to the pluralization stuff, that is endless source of hassle. 

I would love to have some some resolver config flag and the ability to configure blueprints in a very transparent way.

**Comment by stefanpenner** [comment]
> Just out of curiosity are there sufficient hooks to customize the resolver to behave this way? So that with just a little bit of configuration stuff like this could "just work".

ya their should be.

**Comment by stefanpenner** [comment]
> I am generally in favor of Convention over Configuration. But when comes to the pluralization stuff, that is endless source of hassle.

ya, scumbag english.

**Comment by stefanpenner** [comment]
For now, i don't think we will fix this. Their __should__ be sufficient hooks to make this work in your app, if they don't work we can fix that. As for a holistic naming convention change, I don't think right now is the right time for that. 

We can consider it once more important things are fleshed out.

**Comment by ahacking** [comment]
So the projects not about to be renamed Brasa just yet :p
