### ISSUE TITLE
ember cli hangs on 'serve' and 'build'

### ISSUE THREAD

**Issue by jyriand** [ember-cli/ember-cli#2924]
I'm running on fedora. After generating new project and trying to 'ember serve' my computer slows noticeably down. Looking at the processes I see that ember is taking constantly 40-55% of CPU and 132MB of memory. Webpage on port 4200 stays loading. Cannot shut down 'ember serve' with Ctrl-C, only manual kill helps. I see same kind of hanging on 'ember build'

```
> ember serve
version: 0.1.5
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
```

version: 0.1.5
http_parser: 2.3
node: 0.13.0-pre
v8: 3.26.33
uv: 0.11.28
zlib: 1.2.3
modules: 14
openssl: 1.0.1i
npm: 2.1.8

**Comment by jakecraige** [comment]
I'm going to a shot in the dark and say it's related to your node version. I don't think anyone has tested with that new of version. We test against 0.10.18(this should probably be bumped), and 0.11 in CI. I would suggest attempting to downgrade to 0.10.x and seeing if that works for you

**Comment by jyriand** [comment]
You are right. I installed node v0.10.35 and everything worked fine

**Comment by dcposch** [comment]
Just ran into this issue today. The ember process takes up all of one core. Even `kill` didn't work, the only way to stop it was `kill -9`. Maybe it goes into an infinite loop?

I think we should fix this. If Ember CLI is incompatible with the installed version of node or iojs, it should print an error message that says so and die.

**Comment by stefanpenner** [comment]
if you have this issue, please open a fresh issue with detailed summary of your issue. Piggy backing, and not providing any actionable information doesn't provide much value.

**Comment by dcposch** [comment]
I did some more investigation. 

*Repro steps:*
* Install ember-cli 0.1.5
* Use iojs: `sudo ln -s /usr/bin/iojs /usr/bin/node`
* Then, in any Ember CLI project:

    $ ./node_modules/ember-cli/bin/ember --version
    version: 0.1.15
    node: 1.1.0
    npm: 2.1.8
    $ /node_modules/ember-cli/bin/ember build
    version: 0.1.15
    Building
    <hangs>

*Alternatively...*
* Same as above, but use node 0.10: `sudo ln -s /usr/bin/nodejs /usr/bin/node`
* In the same project:

     $ ./node_modules/ember-cli/bin/ember --version
    version: 0.1.15
    node: 0.10.25
    npm: 2.1.8
    $ /node_modules/ember-cli/bin/ember build
    version: 0.1.15
    Building
    <works>

I think this is only a problem in Ember-CLI 0.1.x, so maybe not worth fixing. Ember-CLI 0.2.x looks like it can handle iojs.

**Comment by stefanpenner** [comment]
> version: 0.1.15

this is an old and not supported version of ember-cli. And unfortunately it does not support iojs. Unfortunately the issue was in one of our dependencies ncp: see https://github.com/AvianFlu/ncp/issues/79 for more details.
