### ISSUE TITLE
install:addon won't work

### ISSUE THREAD

**Issue by thomasvanlankveld** [ember-cli/ember-cli#2925]
`$ ember install:addon ember-cli-less`

returns

`version: 0.1.4`
`The specified command install:addon is invalid, for available options see ember help.`

The `install` command does not show up in the `help` list.

`$ ember version`:
`version: 0.1.4`
`node: 0.10.33`
`npm: 2.1.10`

**Comment by rwjblue** [comment]
The `install:addon` command was added in 0.1.5.  Please upgrade to use it.
