### ISSUE TITLE
Ember Doctor And Project Diagnostics

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2928]
I have most of these working at various levels locally. I want to throw a list out there for commentary.  The design I have been working with is that there are default "check tasks", similar to `brew doctor`, but with the addition of applications and addons to add their own diagnostic files.

- [ ] Introduce `ember doctor` command
- [ ] Check NPM version
- [ ] Check for outdated packages
- [ ] Check Ember CLI version explicitly
- [ ] Load, merge, and run any target diagnostic files
- [ ] Add Leek metrics
- [ ] Add blueprint to generate `doctor` directory
- [ ] Add blueprint to generate `check` file
- [ ] Allow exclusion flags e.g. `ember doctor --skip-npm --skip-ember-cli`

__App Specific Doctor__
If for some reason you have a need to run adhoc diagnostics on an application or addon, you will be able to do `ember g doctor && ember g check service-health`. This will generate the following in the root of the project.

```
  doctor/
     checks/
        service-health.js
```

These checks will get merged with the default doctor checks that Ember CLI has.

/cc @stefanpenner @rwjblue

Probably can close #2770 in favor of this one.

**Comment by jakecraige** [comment]
Should this be an RFC instead? Mainly for the discussion aspect, since we already decided we want to do it

**Comment by chadhietala** [comment]
[RFC](https://github.com/ember-cli/rfcs/pull/3)

**Comment by stefanpenner** [comment]
closing this issue as we have:

rfc: https://github.com/ember-cli/rfcs/pull/3
pr:  https://github.com/ember-cli/ember-cli/pull/3193
