### ISSUE TITLE
You have to be inside an ember-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#2931]
Completely frsh vagrant box (http://github.com/wayne-o/sonatribe) 

tried creating a new ember cli app - then ember serve - get that error - tried re-installing ember-cli and same - any pointers?

vagrant@vagrant-ubuntu-trusty-64:/vagrant/testapp$ ember new fooapp
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/.gitkeep
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
vagrant@vagrant-ubuntu-trusty-64:/vagrant/testapp$ ember serve
version: 0.1.5
You have to be inside an ember-cli project in order to use the serve command.
vagrant@vagrant-ubuntu-trusty-64:/vagrant/testapp$ npm install -g ember-cli
npm WARN package.json ember-router-generator@0.1.0 No description
/home/vagrant/.nvm/v0.10.33/bin/ember -> /home/vagrant/.nvm/v0.10.33/lib/node_modules/ember-cli/bin/ember
ember-cli@0.1.5 /home/vagrant/.nvm/v0.10.33/lib/node_modules/ember-cli
├── abbrev@1.0.5
├── js-string-escape@1.0.0
├── exit@0.1.2
├── debug@2.1.1 (ms@0.6.2)
├── temp@0.8.1 (rimraf@2.2.8)
├── http-proxy@1.8.1 (requires-port@0.0.0, eventemitter3@0.1.6)
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
├── es6-module-transpiler@0.3.6 (through@2.3.6, optimist@0.3.7)
├── yam@0.0.17 (findup@0.1.5, fs-extra@0.8.1, lodash@2.4.1)
├── broccoli-sourcemap-concat@0.4.3 (combined-stream@0.0.7, mkdirp@0.5.0, rsvp@3.0.16, fast-sourcemap-concat@0.2.0, broccoli-kitchen-sink-helpers@0.2.5, broccoli-caching-writer@0.5.3, lodash-node@2.4.1)
├── broccoli-writer@0.1.1 (rsvp@3.0.16, quick-temp@0.1.2)
├── broccoli-es6modules@0.3.2 (walk-sync@0.1.3, mkdirp@0.5.0, broccoli-kitchen-sink-helpers@0.2.5, broccoli-caching-writer@0.5.3)
└── broccoli-caching-writer@0.5.1 (promise-map-series@0.2.1, rimraf@2.2.8, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.5, rsvp@3.0.16, core-object@0.0.2)
vagrant@vagrant-ubuntu-trusty-64:/vagrant/testapp$ ember serve
version: 0.1.5
You have to be inside an ember-cli project in order to use the serve command.

**Comment by jakecraige** [comment]
You need to cd into the project directory, in this case `fooapp`

**Comment by wayne-o** [comment]
arrr - crap - I am inside the app in my sonatribe project - just running a fresh vagrant up and will test again

**Comment by wayne-o** [comment]
OK

So just did a complete refresh of the vagrant box and then navigated to /vagrant/src/sonatribe-ui (the ember cli app) and here is the output - you can see from the ls command that i am inside the correct folder:

vagrant@vagrant-ubuntu-trusty-64:/vagrant/src/sonatribe-ui$ ls
app               bower.json   config        package.json  README.md    tests
bower_components  Brocfile.js  node_modules  public        testem.json  vendor
vagrant@vagrant-ubuntu-trusty-64:/vagrant/src/sonatribe-ui$ ember server
version: 0.1.5
You have to be inside an ember-cli project in order to use the serve command.

**Comment by jakecraige** [comment]
Looks like the package.json is never being created. That's how ember cli figured out that you are in an ember-cli project.

**Comment by wayne-o** [comment]
But I have a package.json?

**Comment by wayne-o** [comment]
package.json needs to have "ember-cli": "^0.1.2", entry... Sorry for the noise
