### ISSUE TITLE
Naming Ember Addons??

### ISSUE THREAD

**Issue by jmurphyau** [ember-cli/ember-cli#2932]
Is there a proposed naming convention? If not, should there be?

I'm at the point of naming an Haddon and I've got the following options:

- `ember-cli-<name>`
- `ember-addon-<name>`
- `ember-<name>`

Second one seems the most logical to me (personally), but goes against what has become the norm (the first) - but then I've seen some with simply `ember-<name>` (e.g. `ember-moment` - maybe this is because `ember-cli-moment` already existed? If it did..)

**Comment by rwjblue** [comment]
I don't think that we should make an "official" policy regarding naming, but I have been using `ember-cli-*` when I'm extending ember-cli itself (like `ember-cli-content-security-policy` and `ember-cli-inject-live-reload`), and `ember-*` for things to be used within apps (like `ember-waypoints`, `ember-cpm`, or `ember-moment`).

**Comment by jakecraige** [comment]
I'm in agreement with @rwjblue . This same style of convention is used in many other places with npm. Grunt, gulp, yeoman, so I like it. I see no reason to enforce it though. We don't actually use it anywhere. The ember-cli keyword is what we use to determine addons from non-addons

**Comment by jmurphyau** [comment]
When you say 'The ember-cli keyword is what we use to determine addons' - do you mean the ['ember-addon'](https://www.npmjs.com/browse/keyword/ember-addon) keyword or the ['ember-cli'](https://www.npmjs.com/browse/keyword/ember-cli) keyword?

I didn't really find it confusing until I started developing my own addon - before now I assumed anything starting with ember-cli-* was an ember addon - then when deciding what to call my addon I came to have the same sort of thoughts you mention @rwjblue - (that ember-cli-* seems appropriate for ember-cli addons)

**Comment by jmurphyau** [comment]
I understand not enforcing any naming convention though - I'm glad I opened this issue to get a clearer understanding of the situation

**Comment by jakecraige** [comment]
`ember-addon` is the correct one, whoops
