### ISSUE TITLE
Multi-thread?

### ISSUE THREAD

**Issue by marcemira** [ember-cli/ember-cli#2933]
Hello, is it possible to do some multi-threading at compilation/recompilation? i.e. send each filter or task to n available threads/cores, or does it necessarily needs to be a stack of sync tasks ?. Just a thought. Cheers

**Comment by stefanpenner** [comment]
We have further optimizations and improvements planned to broccoli, they aim to reduce the overall work  done. Much low hanging fruit exists on that front, before we consider a concurrent approach.

**Comment by marcemira** [comment]
Ok, thanks a lot!
