### ISSUE TITLE
Using an addon that uses ember-qunit fails in projects that use ember-mocha

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#2935]
I'm creating an addon, which has ember-qunit by default. When I install this in our project, which uses ember-mocha, I get an error message `Path or pattern "passed.png" did not match any files`. I'm not sure where the issue is coming from - ember-cli, ember-qunit or ember-mocha. Should I create an issue for this on one of these projects?

The following makes the issue go away, but then the QUnit UI is also displayed after the mocha UI.

```
npm install --save-dev ember-cli-qunit
bower install ember-qunit-notifications ember-qunit qunit
```

**Comment by jakecraige** [comment]
I know what it is, should have a PR shortly
