### ISSUE TITLE
Integrate broccoli-jscs to enforce code styling and consistency?

### ISSUE THREAD

**Issue by hieuhuynh** [ember-cli/ember-cli#2938]
Any plans to integrate broccoli-jscs in ember-cli?

https://github.com/kellyselden/broccoli-jscs

**Comment by quaertym** [comment]
I think this is discussed before, see https://github.com/ember-cli/ember-cli/issues/2359.

**Comment by abuiles** [comment]
as pointed by @quaertym is a dup of #2359
