### ISSUE TITLE
Can you include css from an ember-cli addon directly (no bower) ?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#2940]
I see in the docs that you can include the usual bower js/ css code but I'm curious if /how I could include some css/scss from an addon itself (no bower install).

The component a friend of mine is writing has a few lines of JS and some basic scss (or css if we transpile it). I'd like to just "include the css" if possible instead of making a bower module purely to include the css.

Is this an option w/ addons today or is bower a *must have* for css ?

**Comment by jakecraige** [comment]
The easiest way currently(that I'm aware of). Is to drop the css file in your addon's `vendor/` dir and then `app.import` it in the `included` hook of your addon

**Comment by rwjblue** [comment]
Confirm.  Easiest to `app.import` a file from your `vendor/` dir.

**Comment by toranb** [comment]
Excellent! What is the prefix on the import (from the production ember app) ?

**Comment by jakecraige** [comment]
I just did this in one of my projects in [this commit](https://github.com/poetic/ember-cli-panels/commit/f9f4216a3a0562a3ab89c6c746681d8be79a3f1f) You can import it within the addon itself which includes it in the consuming application

**Comment by toranb** [comment]
Perfect - thank you ,thank you, thank you!
