### ISSUE TITLE
Register addons with `Ember.libraries` by default.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#2942]
This would add them (and their version) to the listing printed out by debug versions of Ember (along with Ember and Ember Data.

I think it should be done in the `lib/broccoli/ember-app.js` and call `addon.registerLibrary()` which defaults to `true`.

**Comment by jakecraige** [comment]
How does this benefit the user's of ember-cli? 

It feel like it's going to end up being this big list of things that I don't see benefiting me when I develop apps. Looking at the `package.json` *almost* gives me the same info. I just don't find myself working on an app and wondering what version of some library I'm using.

**Comment by rwjblue** [comment]
`Ember.libraries` is what is used by Ember to print the library list when the app boots in the browser.  It is generally best practice to add your library to the list...

**Comment by jakecraige** [comment]
I guess I'm more complaining about that than this issue itself, lol. It feels unnecessary to me. Especially now since the ember inspector shows these if you really want them

**Comment by rlivsey** [comment]
:+1: this would be very useful, currently you have to jump through a few hoops to get `registerLibrary` working. 

In fireplace I had to add the [code to vendor](https://github.com/rlivsey/fireplace/blob/master/vendor/fireplace/register-version.js) & [include it in index.js](https://github.com/rlivsey/fireplace/blob/67867c658f606e637cfb64c6ea68262ca8ba777d/index.js#L7) and I haven't bothered in a number of my other addons, so it would be great if it happened without me as an addon author having to do anything.

**Comment by rwjblue** [comment]
@jakecraige - The ember-inspector uses `Ember.libraries` to know this info too.

**Comment by jakecraige** [comment]
@rwjblue Yeah I'm aware. I'm just complaining about the console.log's it'll do. Perhaps ember could make it configurable, lol. 

For this specifically, will all addons be registered or just the ones that affect the browser app?

**Comment by hhff** [comment]
FWIW - I like the browser logs.  Helps with on boarding / dev handoff 

2c :heart:

**Comment by rwjblue** [comment]
@jakecraige - you can disable the reporting in the console, but I think they need to exist in `Ember.libraries` specifically for tooling such as ember-inspector.

**Comment by stefanpenner** [comment]
sounds good, but not a bug. We will gladly accept something that improves these conventions.

**Comment by jpadilla** [comment]
I'd like to take a stab at this, if there's still interest. I'm thinking that within `lib/broccoli/ember-app.js`'s `_notifyAddonIncluded` we could probably call `Ember.libraries.register()`.

**Comment by stefanpenner** [comment]
That won't work. As that hook is called in node, but register libraries is client side

**Comment by jpadilla** [comment]
@stefanpenner oh yeah you're right. I'll try and figure out where we could do this instead. Any further directions would be appreciated.

**Comment by stefanpenner** [comment]
Pushing into `config/environment` would likely be the easiest. We can likely make some convention of `_addons: [...]` as a member of that structure.
