### ISSUE TITLE
How to tell a host application not to preprocess an addon's static imports

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli#2945]
What is the recommended way to write an addon that imports static files into the host app without those static assets getting further processed by the host app's CLI build process?

For example, we have a ted_bootstrap addon that imports a custom build of Bootstrap. The assets are already compiled/fingerprinted, we just want to import them.

We have an image we include with `app.import`, and shove it into a `ted_bootstrap` folder within the host app's public directory:

      app.import(path.join(otherAssetsPath, 'some_image.png'), { destDir: '/assets/ted_bootstrap' });

The problem is, this image gets fingerprinted (again) by Ember CLI. So, a css rule from ted_bootsstrap

    background-image: url('assets/ted_bootstrap/some_image.png');

breaks.

I essentially am looking for a way to mark an addon as *already compiled*, so CLI doesn't bother with its assets. Perhaps there's an example addon somewhere that does something similar?

**Comment by jakecraige** [comment]
For your specific case with the fingerprinting, you could just tell broccoli-asset-rev to ignore it. [docs here](http://www.ember-cli.com/#fingerprinting-and-cdn-urls)

**Comment by samselikoff** [comment]
Can I do that from the addon? I wouldn't want each host app to have to add this to its Brocfile

**Comment by jakecraige** [comment]
Not that I'm aware of. We should be improving the config story soon and making something like this possible should be in there. I've been meaning to open the RFC for the changes but haven't gotten around to it just yet. I should be able to soon

**Comment by samselikoff** [comment]
Gotcha, thanks. I'm actually wondering if this is an antipattern - should addons store compiled distributable static assets?

Maybe what I should be doing is putting the dist of ted_bootstrap on a builds server, and having the addon add that to bower + import it.
