### ISSUE TITLE
EmberCLI Testing: Is it possible to access API-STUB using Unit Tests ?

### ISSUE THREAD

**Issue by agentVargas2012R** [ember-cli/ember-cli#2946]
Hello EmberCLI Team,

Hope things have been going well for you guys!

I was curious to know for UNIT TESTS, if it is possible to call API-STUB?

I know this is possible with acceptance tests.

Thanks!

**Comment by stefanpenner** [comment]
Although it may work, we don't official support this for unit tests. As I don't believe unit tests should speak to other collaborators (like a server). If you need some targeted tests, using pretender.js or similar is recommended.
