### ISSUE TITLE
Importing an ES6 module from bower_components

### ISSUE THREAD

**Issue by vine77** [ember-cli/ember-cli#2949]
This line in one of my controllers previously worked fine with ember-cli 0.1.4:
```js
// app/controllers/nodes/index.js
import naturalSort from '../../../bower_components/natural-sort/naturalSort';
```
but after upgrading to ember-cli 0.1.5 (or 0.1.6), it now causes the exception, `Uncaught Error: Could not find module bower_components/natural-sort/naturalSort`. Note: I installed this with `bower install --save vine77/natural-sort` (in order to import [naturalSort.js](https://github.com/vine77/natural-sort/blob/master/naturalSort.js)).

Any ideas what changed or what the right way to import modules from `vendor` or `bower_components` is now?

**Comment by jakecraige** [comment]
I was unaware this ever worked. The way to import vendor or bower assets is in the docs at ember-cli.com. You use the `app.import` api. I won't work for es6 assets though to my knowledge.

Hopefully someone else can chime in about this specific issue not working though

**Comment by rwjblue** [comment]
> I was unaware this ever worked. 

Yep, using ES6 import from `bower_components` (or `vendor`) should definitely work.

**Comment by rwjblue** [comment]
@vine77 - Can you remove the relative path, and just `import naturalSort from "bower_components/natural-sort/naturalSort";`?

**Comment by vine77** [comment]
@rwjblue, I get the same behavior without the relative path. 
```js
import naturalSort from 'bower_components/natural-sort/naturalSort';
```
works fine with ember-cli 0.1.4, but causes the exception `Uncaught Error: Could not find module bower_components/natural-sort/naturalSort` when I upgrade ember-cli to 0.1.5 (whether or not ember-cli is the only npm dependency I upgrade, or I go through the full ember init upgrade process). I'll try to reproduce this issue in a trivial new ember project.

**Comment by vine77** [comment]
I created a trivial ember app and it would seem as if this is a regression with ember-cli 0.1.5. https://github.com/vine77/es6-import-test/commit/1a3cb111df80d59218c31f988dcb832c8f6bee20 shows that ES6 modules work with ember-cli 0.1.5+ only when importing something inside of `app`, https://github.com/vine77/es6-import-test/commit/d2869d32443e36bce94241da5607637a6447eb17 shows that they no longer work when importing something from `bower_components`, and https://github.com/vine77/es6-import-test/commit/11ad24132329165ada8644f92257cde8ce41f0b3 shows that they work again after downgrading to ember-cli 0.1.4.

Reproduction steps:
```console
ember init
ember generate controller index
bower install --save vine77/natural-sort
echo "import naturalSort from 'bower_components/natural-sort/naturalSort';" | cat - app/controllers/index.js > /tmp/index.js && mv /tmp/index.js app/controllers/index.js
ember serve
```

Console exception:
```
Error while processing route: index Could not find module bower_components/natural-sort/naturalSort Error: Could not find module bower_components/natural-sort/naturalSort
    at requireModule (http://localhost:4200/assets/vendor.js:65:13)
    at reify (http://localhost:4200/assets/vendor.js:48:30)
    at requireModule (http://localhost:4200/assets/vendor.js:76:17)
    at resolveOther (http://localhost:4200/assets/vendor.js:63103:20)
    at apply (http://localhost:4200/assets/vendor.js:32885:27)
    at superWrapper (http://localhost:4200/assets/vendor.js:32457:15)
    at __exports__.default.EmberObject.extend.resolveController (http://localhost:4200/assets/vendor.js:16957:21)
    at __exports__.default.EmberObject.extend.resolve (http://localhost:4200/assets/vendor.js:16814:45)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:16432:25)
    at resolve (http://localhost:4200/assets/vendor.js:14968:32)
```

**Comment by jayphelps** [comment]
@rwjblue @vine77 I can confirm this is indeed broken. Importing something via ES6 no longer picks it out of the tree, nor does it do any sanity checks. You can `import asdf from 'asdf';` and the only compile-time error you'll get is `'asdf' is defined but never used.` where as before the es6 concat'r would complain about `ENOENT, no such file or directory`.

Looks like it was caused by https://github.com/ember-cli/ember-cli/pull/2727

Cc/ @ef4

**Comment by jayphelps** [comment]
@ef4 Yep. looks like this functionality was in [broccoli-es6-concatenator](https://github.com/joliss/broccoli-es6-concatenator) but is missing in [broccoli-es6modules](https://github.com/ef4/broccoli-es6modules), which superseded it.

**Comment by ef4** [comment]
I deliberately left out the arbitrary dependency walking that broccoli-es6-concatenator used to do, because I think it's weird to start pulling things into the build that are not in any of the broccoli input trees.

I think we should make `app.import` do the right thing with native ES6 dependencies instead, to keep the overall API simpler.

**Comment by jayphelps** [comment]
@ef4 perhaps, but this is a pretty major breaking change that I've seen many many apps have used with as of now how no upgrade path.

**Comment by rwjblue** [comment]
@ef4:

>  I think it's weird to start pulling things into the build that are not in any of the broccoli input trees.

The combined external trees (including `bower_components` and `vendor`) were part of the inputs provided to `broccoli-es6-conatenator`.

> I think we should make app.import do the right thing with native ES6 dependencies instead, to keep the overall API simpler.

To use `app.import` in the case of true ES6 inputs would basically mean `app.import`ing every possible file (because you can't `app.import` directories).  I suppose we could change that (and allow `app.import`ing directories), but that is very odd in the case of non-ES6 imports.

**Comment by jayphelps** [comment]
IMO it's more natural to `import foo from 'foo';` since you have a better idea if you're actually using it or not. (jslint will complain, if you don't) `app.import`'in a directory will mean you distribute everything in that library, even if you only use one small portion of it.

It's yet-another-api, but I think it's the most ideal..how we'll eventually consume most if not all libraries, as more jump on the ES6 bandwagon. I feel like `app.import` is the stop-gap.

**Comment by ef4** [comment]
OK, makes sense.

I will try to find a happy medium so that direct es6 imports work, without
letting the dependency finder crawl arbitrary paths outside the build tree.

**Comment by jayphelps** [comment]
@ef4 <3

**Comment by stefanpenner** [comment]
@ef4 thoughts on `import Foo from 'bower:project/file/in/project` ?

**Comment by ef4** [comment]
That would work. But I wonder if we can't be completely agnostic to where
it's coming from and just have a list of search paths. At least for the
native es6 case.

BTW, we can do one better than the old implementation by distributing these
deps in the vendor bundle instead of the app bundle.

**Comment by stefanpenner** [comment]
> BTW, we can do one better than the old implementation by distributing these
> deps in the vendor bundle instead of the app bundle.

interesting.

**Comment by rwjblue** [comment]
Addon dir for addon's ahould already be in vendor.js.

**Comment by stefanpenner** [comment]
@rwjblue you are correct.

**Comment by stefanpenner** [comment]
I honestly would prefer people use `ember-browserify` when possible over bower

`import lodash from 'npm:lodash'` etc.

**Comment by jayphelps** [comment]
@ef4 @rwjblue This is still a major pain for us. Can't import ES6 libs, gotta use AMD and write `app.import` boilerplate. What's the current thinking?

**Comment by buritica** [comment]
Yeah. Been using ember-browserify and broccoli-dist-es6-module



--

Juan Pablo Buritica

t: @buritica

**Comment by stefanpenner** [comment]
we plan to drop bower_components entirely, likely no extra effort will be spent on this, rather that energy will go towards NPM improvements.

**Comment by jayphelps** [comment]
@stefanpenner is there at least a work around for importing a bower based ES6 distributed module?

**Comment by stefanpenner** [comment]
Yup just use the broccoli es6modules transpiler that is on the ember cli org

**Comment by webark** [comment]
if you intend to move away from bower and focus on npm and browserify, how do you suggest handling packages with css files in them? I attempted to import the css file from a npm package in the brocfile, but it could not find it.

**Comment by kmiyashiro** [comment]
@webark it looks as though npm 3 is embracing frontend modules so I feel like that's the way the world is going. I'm sure there's a way to add `node_modules` as a directory to lookup for whichever CSS tree plugin you are using. For the LESS plugin, it might look something like this:

```js
  var app = new EmberApp(defaults, {
    lessOptions: {
      paths: [
        'bower_components',
        'node_modules'
      ]
    }
  });
```

**Comment by cowboyd** [comment]
I'm still unclear as to what the resolution for this is.

Maybe you could shed some light on your process @jayphelps for consuming native ES6 modules.

In this use-case, I'm trying to include an ES6 module that is distributed via npm in the `src/` directory https://github.com/cowboyd/impagination/tree/extract-to-simple-npm-package

I'm trying to include it using the `broccoli-es6modules` as suggested by @stefanpenner by putting this in my `ember-cli-build.js`:

```javascript
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var ES6Modules = require('broccoli-es6modules');
var MergeTrees = require('broccoli-merge-trees');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {});

  var impagination = new ES6Modules('node_modules/impagination/src', {
    format: 'amd',
    bundleOptions: {
      entry: 'dataset.js',
      name: 'impagination'
    }
  });
  return new MergeTrees([app.toTree(), impagination]);
};
```

The app builds just fine, but it does not appear to include this into `vendor.js`. Is there a separate step that I'm missing?

**Comment by cowboyd** [comment]
Thanks help from @rwjblue, we were able to do this pretty cleanly. Here's the code with which `ember-impagitanion` brings in the `impagination` es6 modules from NPM.

https://github.com/thefrontside/ember-impagination/blob/2fa38d26ef1b27a3db7df109faa872db243e5e4c/index.js
