### ISSUE TITLE
How to edit the ember-cli documentation

### ISSUE THREAD

**Issue by moatazelmasry2** [ember-cli/ember-cli#2950]
Hello,

I'm trying to find out where is the source for the documentation on http://www.ember-cli.com/ to do some edits, but didn't manage to find it so far.
And if it is not there, are there any plans to host it on github.io?

Cheers

**Comment by wayne-o** [comment]
Is it a branch on the main repo?

On Saturday, 10 January 2015, Moataz Elmasry <notifications@github.com>
wrote:

> Hello,
>
> I'm trying to find out where is the source for the documentation on
> http://www.ember-cli.com/ to do some edits, but didn't manage to find it
> so far.
> And if it is not there, are there any plans to host it on github.io?
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/2950>.
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by jakecraige** [comment]
It's on the gh-pages branch of ember-cli/ember-cli
