### ISSUE TITLE
Incorrect warning about files not being in sub directories (Windows)

### ISSUE THREAD

**Issue by sushantdhiman** [ember-cli/ember-cli#2954]
When I upgraded my project to cli@0.1.6 I got warnings like this

version: 0.1.6

```javascript
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\jquery-ui.js` into a s
ubdirectory.
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\themes\base\accordion.
css` into a subdirectory.
Using `app.import` with a file in the root of `vendor/` causes a significant per
formance penalty. Please move `bower_components\jquery-ui\themes\base\all.css` i
nto a subdirectory.
```
Files are clearly in the sub directories.

I think this issue may be linked to platform. I am using Windows 7 (32 bit).

**Comment by hwwan80** [comment]
same here, the following line in https://github.com/ember-cli/ember-cli/blob/6b324adb428f3c1beeb01be73a91c923dceffaa9/lib/broccoli/ember-app.js#877 only use '/' as path seperator while in windows it use '\\'

**Comment by stefanpenner** [comment]
`require('path').sep` should be sufficient to fix this, anyone want to try a pr?

**Comment by rwjblue** [comment]
What version are you updating from?  What does your `Brocfile.js` contain (specifically how are you `app.import`ing)?
