### ISSUE TITLE
Uncaught TypeError: Cannot set property 'compilerInfo' of undefined

### ISSUE THREAD

**Issue by cannect** [ember-cli/ember-cli#2955]
Hi,

I am getting a `Uncaught TypeError: Cannot set property 'compilerInfo' of undefined` error when building with the new Ember-CLI 0.1.6. I have made sure that everything is in place with `ember init`.

What can be happening here?
Also a screenshot of the code:
![error](https://cloud.githubusercontent.com/assets/939500/5702142/0f12c13c-9a56-11e4-9dec-32b5fe191f39.PNG)

Edit: I am using the following:
```
 DEBUG: -------------------------------
ember.debug.js:4155 DEBUG: Ember                          : 1.11.0-beta.1+canary.4df827e5
ember.debug.js:4155 DEBUG: Ember Data                     : 1.0.0-beta.15-canary
ember.debug.js:4155 DEBUG: jQuery                         : 1.11.2
ember.debug.js:4155 DEBUG: Ember Simple Auth              : 0.6.7
ember.debug.js:4155 DEBUG: Ember Simple Auth Cookie Store : 0.6.7
ember.debug.js:4155 DEBUG: Ember Simple Auth OAuth 2.0    : 0.6.7
ember.debug.js:4155 DEBUG: -------------------------------
```

**Comment by cannect** [comment]
This did looklike a Handebars error. So I got it solved when using HTMLBars.

**Comment by hcatlin** [comment]
I have this erorr too... and have no idea what I'm supposed to do to fix it. What do I do with HTMLbars?

**Comment by quaertym** [comment]
@cannect I just got this error. What's the fix for this?

**Comment by adamsrog** [comment]
Encountered this same error after creating up a new ember-cli 0.1.15 app, then upgrading ember to 1.10.0.  I was able to fix it by adding HTMLBars.

    ember install:addon ember-cli-htmlbars

**Comment by quaertym** [comment]
@adamsrog Thank. Mine was because of a dependency (`ic-modal`) removing that fixed it.

**Comment by hcatlin** [comment]
Yeah, mine was caused by Emblem. ;(

**Comment by soundarapandian** [comment]
I am facing the exact issue. I tried running this command `ember install:addon ember-cli-htmlbars`. But it does not solved the problem. 

Do I need to uninstall handlebars and install htmlbars to solve this issue?

**Comment by rwjblue** [comment]
@soundarapandian - Here are the changes to use Ember 1.10 with ember-cli 0.1.15: https://github.com/rwjblue/components-in-subdirs/commit/78e7ed2d072f42d9cf0fd3d9fc2376f106ab762e.

**Comment by soundarapandian** [comment]
@drewcovi :green_heart: I was looking for the exact link you provided. Thank you.

**Comment by drewcovi** [comment]
hmmm what did i do? :)

**Comment by soundarapandian** [comment]
@drewcovi Sorry my mistake. I was intended to mention rwjblue actually.

**Comment by rlynjb** [comment]
thanks @adamsrog this helped me fix the same issue i was having :+1:

**Comment by constantm** [comment]
Emblem is causing this for me too on Ember 1.10.0. Tried install htmlbars with no luck. Any ideas?

**Comment by coladarci** [comment]
As an FYI, I was having the same issue and the fix for me was to use this: https://github.com/Vestorly/ember-cli-emblem-hbs-printer (follow the instructions in the readme).

**Comment by MrJadaml** [comment]
Had the same issue and an `npm update` resolved it for me. (using CLI)
