### ISSUE TITLE
Getting error during 'ember install:bower <anything>'

### ISSUE THREAD

**Issue by tsabolov** [ember-cli/ember-cli#2956]
After installing package [`javascript-audio-fx`](https://github.com/jakesgordon/javascript-audio-fx) using `ember install:bower` I am not able to install any other packages. Keep getting an error 'Invalid version: *'.

That package has no version specification in its `.bower.json` so I've got `"javascript-audio-fx": "*"` in my `bower.json`. I think there must be a check around such cases.

**Comment by wayne-o** [comment]
Shouldn't it just be 

bower install <package> 

?

**Comment by tsabolov** [comment]
I guess that `ember install:bower ...` uses its own local bower. That's the only difference from my POV. I just want devs to know about the problem.

**Comment by jakecraige** [comment]
Yes, `ember install:bower` uses it's own local version. Does running `bower install` by itself work?

and @wayne-o the way going forward should be to use the `install:bower`, `install:npm`, and `install:addon` commands. The bower and npm ones do the same thing as `bower install` and `npm install` with a few options added and they use the local version rather than the global. These commands were added in 0.1.5

**Comment by tsabolov** [comment]
@jakecraige thanks for your answer. Yes, `bower install` works on itself. Even more `./node_modules/ember-cli/node_modules/.bin/bower install` works well too.

**Comment by stefanpenner** [comment]
will be fixed with: https://github.com/quaertym/ember-cli-dependency-checker/pull/22

**Comment by quaertym** [comment]
Will be fixed in master when https://github.com/ember-cli/ember-cli/pull/3363 gets merged.

**Comment by abuiles** [comment]
@tsabolov this should be fixed now, can  you try updating `ember-cli-dependency-checker` in your `package.json` to match 0.0.8 and try again?

**Comment by stefanpenner** [comment]
thanks @quaertym

**Comment by tsabolov** [comment]
@abuiles, I confirm that with the updated `ember-cli-dependency-checker` everything works as expected. Thank you.

@quaertym, @stefanpenner thank you.
