### ISSUE TITLE
baseUrl not set in built index.html if locationType is hash

### ISSUE THREAD

**Issue by jyriand** [ember-cli/ember-cli#2957]
I have configuration:
```
baseURL: '/ember/'
locationType: 'hash'
```
But running 'ember build' produces index.html file without base tag. If instead of 'hash' I have 'auto' then everything is fine. Similar ticket [#1851](https://github.com/ember-cli/ember-cli/issues/1851)

ember version: 0.1.5
node version: 0.10.35
npm version: 2.1.8

**Comment by jnhuynh** [comment]
I can confirm this issue too on Ember CLI 0.2.0.

**Comment by knownasilya** [comment]
Not sure if this is related, but when I do:

```js
baseURL: '/dashboard/'
locationType: 'hash'
```

Everything works fine at `/dashboard/#/`. But if I have the following:

```js
baseURL: '/dashboard/'
locationType: 'auto'
```

The url is `/dashboard/dashboard/`.
