### ISSUE TITLE
I'd like to implement print functionality for my project which is created on ember-cli. any existing addons/plugins available on ember-cli or emberjs?

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [ember-cli/ember-cli#2958]
In a page, I am loading a part of page using a action and like to take a print of that loaded part only... To do that, I am looking for existing addons or plugin in ember or ember-cli.... Anyone please help me for this...

**Comment by manoharank** [comment]
It is something not related to `ember-cli`. Matter of print.css, please google it.

**Comment by vinodhrajamuralidharan** [comment]
I know like using the media queries and using window.print, we can achieve this functionality but if any addons or plugins available like nodejs, we can have some other features  too... that's why I am looking  to know if anything is available already...

**Comment by jakecraige** [comment]
This question is best for something like stackoverflow since it's not an issue with ember-cli itself. Feel free to post it there(and post back here) or continue discussion here, but I'm going to close this for now.

I am unaware of any addons that do this but it's plausible an addon can create something like this.

**Comment by stefanpenner** [comment]
Feel free to continue the discussion here, or on ember's discourse  forum.

**Comment by vinodhrajamuralidharan** [comment]
I have posted already in stackoveflow...http://stackoverflow.com/questions/27905876/existing-addons-plugins-availability-in-ember-cli 
http://discuss.emberjs.com/t/emberjs-printer-addons-availability/7062

Waiting for the responses...
