### ISSUE TITLE
LESS/SASS plugins are implemented differently.

### ISSUE THREAD

**Issue by lukesargeant** [ember-cli/ember-cli#2967]
Hi. I recently added support for multiple outputPaths in ember-cli-less. I did this by investigating how the Sass plugin worked. Although I got this working, I don't understand why the two plugins are wrapped so differently. Broccoli-sass seems to be called directly from style-plugin.js whereas broccoli-less-single has ember-cli-less in-between.

Is one of these approaches preferred over the other? It would be great to have consistency between these two similar addons.

**Comment by jakecraige** [comment]
The inline stuff for various preprocessors is legacy from before addons existed. We could likely remove it in a future release. It would be a breaking change though for anyone currently relying on it

**Comment by jakecraige** [comment]
Ember-cli-sass exists now in favor of broccoli-sass as a standalone addon I believe
