### ISSUE TITLE
Addon creation - missing folders/modules

### ISSUE THREAD

**Issue by rk1** [ember-cli/ember-cli#2972]
I updated to 0.1.6 a couple of days ago and tried to create a new addon.

The initial scaffold was successful, but when I tried to serve it - I got an error:

    Serving on http://0.0.0.0:4200/
    Attempting to watch missing directory: app
    Error: Attempting to watch missing directory: app

I saw that the directory structure is different from a previous addon I've written:

![screen-shot-2015-01-13-at-3 08 47-pm](https://cloud.githubusercontent.com/assets/1324432/5721545/933abfec-9b3b-11e4-9454-614bc65bcd2b.jpg)

I tried creating the app folder, but then noticed the following error:

    ENOENT, no such file or directory '/Users/rossen/Desktop/foo-foo/tmp/funnel-dest_u6mcl0.tmp/index.html'
    Error: ENOENT, no such file or directory '/Users/rossen/Desktop/foo-foo/tmp/funnel-dest_u6mcl0.tmp/index.html'

After that I created index.html (it was not present in previous addons I've created) and a few other folders (styles, etc. to suppress further errors) and got it running, but in the console I saw

    Error: Could not find module dummy/app

At which point I gave up since it seemed that maybe there is something wrong with the addon blueprint.
Anyone experiencing similar issues?

**Comment by jakecraige** [comment]
dup of #2962 ?

**Comment by rk1** [comment]
yep, seems like the same thing
