### ISSUE TITLE
`ember serve` reruns the whole test suite once finished

### ISSUE THREAD

**Issue by balinterdi** [ember-cli/ember-cli#2973]
When the tests are run via `ember serve` and complete, the page is reloaded and the whole suite is run again from start. This results in an infinite running of tests. No error is printed on the console.

When I run the tests "manually", through `localhost:4200/tests`, it does not do that. The suite runs to completion once and then stops.

    $ ember --version
    version: 0.1.6
    node: 0.10.21
    npm: 2.1.8

I am running Ember 1.9.1 and Handlebars 2.0.0.

The machine is a MBP, and Chrome version is 39.0.2171.95 (64-bit) (latest stable).

**Comment by balinterdi** [comment]
Ok, se dug a little deeper and it seems to be a communication issue between the test runner in ember-cli and the browser.

I claim this because if I take the URL (something like `http://localhost:7357/2222/tests/index.html`) while the tests are running and paste it in another browser's tab to run it, then everything happens according to the book and I get to see the progress in the console where I launched `ember test` from:

> ok 1 Firefox 32.0 -
ok 2 Firefox 32.0 -
ok 3 Firefox 32.0 -
ok 4 Firefox 32.0 -
ok 5 Firefox 32.0 -
ok 6 Firefox 32.0 -
ok 7 Firefox 32.0 

Once the tests are finished, the `ember test` task is complete and is killed.

I verified that this works with Firefox, Chrome and Safari. However, the browser, whichever it is, that is launched by the task can never finish the task.

**Comment by tdesmet** [comment]
I am experiencing almost the same, except in my case the tests don't restart when they are done. The chrome window remains open though and nothing is being reported to the console.

I'm running on windows 8 and latest stable chrome Version 39.0.2171.95

**Comment by abuiles** [comment]
@balinterdi could you please give a step by step to reproduce this? I've been trying to do it but I don't see the issue.

**Comment by jgwhite** [comment]
FWIW: I’m grappling with similar behaviour. Are you guys using Pretender, MockJax, or similar?

**Comment by balinterdi** [comment]
@jgwhite Yes, we are using pretender 0.4.2

**Comment by jgwhite** [comment]
@balinterdi same. So I believe Pretender is interfering with Socket.io, causing Testem to attempt reconnection (basically just a reload). Still trying to narrow down exactly how and where.

This issue is not strictly related to ember-cli, but the combination of Pretender and Testem.

**Comment by stefanpenner** [comment]
> @balinterdi same. So I believe Pretender is interfering with Socket.io, causing Testem to attempt reconnection (basically just a reload). Still trying to narrow down exactly how and where.

that seems extremely likely... cc @trek

**Comment by jgwhite** [comment]
Note that it doesn’t affect all browsers. I imagine on some browsers Socket.io will fall back to XHR and—if timings are off—encounter the FakeXHR.

**Comment by jgwhite** [comment]
Downgrading to Testem 0.6.25 fixed the problem. I believe the root cause lies in this commit:
https://github.com/airportyh/testem/commit/13951c27dde11dbff3be718fe7641c73c28bbfca

**Comment by stefanpenner** [comment]
@jgwhite thanks for digging. 

seems like we need to:

* revert testem?
* open a testem issue

**Comment by jgwhite** [comment]
I plan to dig deeper and open an issue on Testem. Seems like they use a heavily patched version of socket.io.

**Comment by stefanpenner** [comment]
@jgwhite awesome, thank you sir

**Comment by trek** [comment]
@stefanpenner very likely. Pretender supports pass-through requests. A pretender ember-addon should also be responsible for configuring passthroughs it needs for xhr that the cli does on the developer's behalf.

**Comment by jgwhite** [comment]
@trek good to know. I’ll try and discern exactly what requests testem tries to make.

**Comment by balinterdi** [comment]
> Note that it doesn’t affect all browsers. I imagine on some browsers Socket.io will fall back to XHR and—if timings are off—encounter the FakeXHR.

FWIW I saw the same behavior in Chrome 39, Safari 8.0.2 and Firefox 32.0.1. Thank you for looking into this.

**Comment by jgwhite** [comment]
I believe we have a patch that fixes against the latest Testem. Formulating now.

**Comment by jgwhite** [comment]
https://github.com/airportyh/testem/pull/455 addresses this issue.

**Comment by jgwhite** [comment]
To try out this patch:

```sh
cd node_modules/ember-cli
npm i Dremora/testem#pretender-fix
cd  ../..
```

Then run the tests and let us know if things improve.

**Comment by balinterdi** [comment]
Unfortunately that fix did not seem to have fixed the issue for me in any of the browsers.

**Comment by jgwhite** [comment]
@balinterdi dang. Can we pair over ScreenHero at some point today? Would be good to get to the bottom of this.

**Comment by jgwhite** [comment]
If that patch doesn’t work, you can also try downgrading testem to `0.6.24`.

Here’s the patch:

```patch
diff --git a/package.json b/package.json
index 9c75b26..bd7569d 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,8 @@
   "scripts": {
     "start": "ember server",
     "build": "ember build",
-    "test": "ember test"
+    "test": "ember test",
+    "postinstall": "./script/downgrade-testem.sh"
   },
diff --git a/script/downgrade-testem.sh b/script/downgrade-testem.sh
new file mode 100755
index 0000000..2a135c7
--- /dev/null
+++ b/script/downgrade-testem.sh
@@ -0,0 +1,2 @@
+cd node_modules/ember-cli
+npm install testem@0.6.24
```

**Comment by zeppelin** [comment]
> To try out this patch:
> [...]

@jgwhite it did fix the issue for me

**Comment by jgwhite** [comment]
@zeppelin cool. Good to know.

**Comment by balinterdi** [comment]
I am sorry to report that neither the patch nor the downgrade works for me. I can't pair this weekend but will ping you if I have some time. I'm balint.erdi on Skype.

Thanks again for your efforts.

**Comment by tdesmet** [comment]
@jgwhite the patched version fixed the issue for me, thx

**Comment by jgwhite** [comment]
@tdesmet good to hear. We’re working with Testem’s maintainers now to make sure the patch lands in the right place.

**Comment by balinterdi** [comment]
I am happy to report that it (doing `npm i Dremora/testem#pretender-fix`) works here, too. My guess is that the last time I tried that were some npm cache issues. Or I just screwed up installing the patch in some way :)

Anyway, @jgwhite, thank you for fixing this, I'll close the issue.

**Comment by jgwhite** [comment]
A fix is pending approval in [airportyh/testem#457](https://github.com/airportyh/testem/pull/457) and should be available in the next release :smile:
