### ISSUE TITLE
Pristine ember-cli addon blueprint fails unit tests with build error of missing `app/` directory

### ISSUE THREAD

**Issue by cowboyd** [ember-cli/ember-cli#2980]
By default the addon blueprint doesn't generate an `app/` directory, and it is conceivable that it might never be present.

```
~/❯❯❯ ember addon bare
version: 0.1.7
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create tests/dummy/app/app.js
  create tests/dummy/app/components/.gitkeep
  create tests/dummy/app/controllers/.gitkeep
  create tests/dummy/app/helpers/.gitkeep
  create tests/dummy/app/index.html
  create tests/dummy/app/models/.gitkeep
  create tests/dummy/app/router.js
  create tests/dummy/app/routes/.gitkeep
  create tests/dummy/app/styles/app.css
  create tests/dummy/app/templates/application.hbs
  create tests/dummy/app/templates/components/.gitkeep
  create tests/dummy/app/views/.gitkeep
  create bower.json
  create tests/dummy/config/environment.js
  create .gitignore
  create package.json
  create tests/dummy/public/crossdomain.xml
  create tests/dummy/public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
  create LICENSE.md
  create config/environment.js
  create index.js
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
~/❯❯❯ cd bare
~/bare❯❯❯ ember test
Build failed.
ENOENT, no such file or directory 'app/'
Error: ENOENT, no such file or directory 'app/'
    at Object.fs.readdirSync (fs.js:654:18)
    at walkSync (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/walk-sync/index.js:14:20)
    at Funnel.processFilters (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:101:15)
    at Funnel.handleReadTree (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:87:10)
    at $$$internal$$tryCatch (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/cowboyd/Code/Ember/bare/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by drapergeek** [comment]
I can confirm this issue. This started happening with the 0.1.6 release (works fine on 0.1.5).

If you create the `app/` directory by hand, you're then presented another error message for a missing `index.html` file:

`ENOENT, no such file or directory '/Users/Someone/Documents/Projects/my-addon/tmp/funnel-dest_XlBc7A.tmp/index.html'`

**Comment by stefanpenner** [comment]
i suspect some pathing issue, i don't believe this exists on master.. Can you guys try?

**Comment by jakecraige** [comment]
@stefanpenner He's using 0.1.7 which was just released though :/

**Comment by stefanpenner** [comment]
@jakecraige yes, but i thought i tried this on master. If that is the case, it might be something that only happens when ember-cli is bundled up and published..

**Comment by jakecraige** [comment]
@stefanpenner

when using: 0.1.7-master-d7df35d9a1 it works
when I hack together using 0.1.7 directly it doesn't work. 

version: 0.1.7-master-d7df35d9a1
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create tests/dummy/app/app.js
  create tests/dummy/app/components/.gitkeep
  create tests/dummy/app/controllers/.gitkeep
  create tests/dummy/app/helpers/.gitkeep
  create tests/dummy/app/index.html
  create tests/dummy/app/models/.gitkeep
  create tests/dummy/app/router.js
  create tests/dummy/app/routes/.gitkeep
  create tests/dummy/app/styles/app.css
  create tests/dummy/app/templates/application.hbs
  create tests/dummy/app/templates/components/.gitkeep
  create tests/dummy/app/views/.gitkeep
  create bower.json
  create tests/dummy/config/environment.js
  create .gitignore
  create package.json
  create tests/dummy/public/crossdomain.xml
  create tests/dummy/public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
  create .npmignore
  create LICENSE.md
  create addon/.gitkeep
  create config/environment.js
  create app/.gitkeep
  create index.js
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
```

```
version: 0.1.7
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create tests/dummy/app/app.js
  create tests/dummy/app/components/.gitkeep
  create tests/dummy/app/controllers/.gitkeep
  create tests/dummy/app/helpers/.gitkeep
  create tests/dummy/app/index.html
  create tests/dummy/app/models/.gitkeep
  create tests/dummy/app/router.js
  create tests/dummy/app/routes/.gitkeep
  create tests/dummy/app/styles/app.css
  create tests/dummy/app/templates/application.hbs
  create tests/dummy/app/templates/components/.gitkeep
  create tests/dummy/app/views/.gitkeep
  create bower.json
  create tests/dummy/config/environment.js
  create .gitignore
  create package.json
  create tests/dummy/public/crossdomain.xml
  create tests/dummy/public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
  create LICENSE.md
  create config/environment.js
  create index.js
Installing packages for tooling via npm..^C% 
```

**Comment by drapergeek** [comment]
I could not get master to work properly @d7df3

**Comment by ksnyde** [comment]
+1 ... had this problem currently with 0.1.6 and then installed 0.1.7 and the problem still exists (i was just starting a component so I just started it from scratch with 0.1.7).

In both cases I'm working on a *addon* and unlike in prior releases the initialisation of the addon does not create the `app` directory automatically. Not sure if this is intended but it means that you can't fire up the watcher until you add this directory (for me I just added a `ember g component comp-name`). Feels like a regression.

Then after the app directory does exist it then complains about `index.html` file not existing:

> ENOENT, no such file or directory 'component-name/tmp/funnel-dest_f0rDKU.tmp/index.html'

**Comment by jgwhite** [comment]
It looks like the bundled ember-cli ships with an incomplete addon blueprint. Investigating the root cause.

**Comment by jgwhite** [comment]
Okay, looks like npm pack takes into all `.npmignore` files it finds, not just the one at the top level.

https://github.com/ember-cli/ember-cli/commit/fef1adbdae0399ae8b99a7b5505758c4f0697cbf added a `.npmignore` which is excluding some parts of the addon blueprint.

Will rename this file to `npmignore` and map the filename in the blueprint. PR in the works.

**Comment by rwjblue** [comment]
@jgwhite - Great sleuthing, thanks for tracking this down!

**Comment by stefanpenner** [comment]
@jgwhite thoughts on _DOT_npmignore for the file template? This could also be used for all other dotfiles

**Comment by jgwhite** [comment]
@stefanpenner seems good. `_DOT_gitignore` `_DOT_jshintrc`. Shall we open a separate issue for that proposal?

**Comment by jgwhite** [comment]
https://github.com/ember-cli/ember-cli/pull/2996

**Comment by jgwhite** [comment]
#2996 should be good to merge once it gets a turn on AppVeyor.

**Comment by piotrpalek** [comment]
Is there a workaround for people using 0.1.7?

**Comment by stefanpenner** [comment]
@piotrpalek copy the files manually from the blueprints dir (not ideal)

we may want a 0.1.8 soon

**Comment by jclem** [comment]
@piotrpalek It was hard for me to suss out what needed to be done for 0.1.7, so this is what I did:

- Manually create `app` and `addon` directories.
- Change require of `ember-app` to `ember-addon` in `Brocfile.js`.

**Comment by piotrpalek** [comment]
@jclem thanks for sharing that :) I was going to try it today and your steps work just fine :+1:
