### ISSUE TITLE
ember t --module "SomeModule" builds the entire app

### ISSUE THREAD

**Issue by quaertym** [ember-cli/ember-cli#2987]
I wonder whether it is absolutely necessary to build the entire app to run a simple unit test for a single module. If it is possible without building, I can work on a PR with some help.

**Comment by rwjblue** [comment]
@quaertym - There is no way to know what is required for a single module without building the app.

**Comment by quaertym** [comment]
@rwjblue  If the tested module does not depend on any other, is this still true?

**Comment by stefanpenner** [comment]
@quaertym currently, we don't do any additional DI related static analysis, so we have to assume this :S

**Comment by quaertym** [comment]
I see, closing.

**Comment by stefanpenner** [comment]
ya for now, we should keep it in mind as we make improvements
