### ISSUE TITLE
background-image: url() breaks with ENV.baseURL = 'anything' if app is served on {base}/anything

### ISSUE THREAD

**Issue by Harris-Miller** [ember-cli/ember-cli#2989]
## Problem ##

When ENV.baseURL is set, and your server is serving the production build of your ember app to a route other than the base, background-image: url()'s break

Here is my example:

https://github.com/Harris-Miller/cssUrlExample

pull that down, `ember install`, and `ember server`
I have 2 images being displayed on screen, one using an <img> tag, and the other using background-image. both load. and both are "/assets/images/tomster.png"

now do `ember build --environment=production`
then run `node app`

app.js is a simple express server that I whipped up and serves the /dist folder to localhost:3000/cssUrlExample

i also have in config/environments.js
```javascript
if (environment === 'production') {
  ENV.baseURL = 'cssUrlExample';
}
```
with that, the <img> tag works fine with just `src="/assets/images/tomster.png"` because of the added <base> tag
however the `background-image: url('/assets/images/tomster.png')` fails to load, because it's looking at "http://localhost:300/assets/images/tomster.png" and not "http://localhost:300/cssUrlExample/assets/images/tomster.png"

## Why this is an issue ##

I can see instances where serving an ember app like I am in my example could become actually quite common. Let's say I have a website built on an everyday server-side MVC. And lets say that we decide that a new sub-section of the site will be an ember app. So the server-side routes will server the production build of /dist from the ember app to that route (just like I am in my example express server). In this case, the background-image: url()'s will all fail if they are servered locally and not through a CDN

## Possible Solution ##

css url rewrites to append ENV.baseURL
e.g.
`ENV.baseURL = "cssUrlExample"`
so `background-image: url('/assets/images/tomster.png');`
becomes
`background-image: url('/cssurlExample/images/tomster.png');`

I'm still looking for the best solution myself on how to accomplish this (trying to find the right npm module to use) and I'll submit a pull request when I find it.

Would like to here thoughts on this and if you agree that this is an issue, or is there is a work around that I'm not aware of right now

The repo I posted about was build on:
```
version: 0.1.7
node: 0.10.35
npm: 2.1.8
```

**Comment by stefanpenner** [comment]
the problem is we set `<base href=''>` this is something i have wanted to kill for ages just have not had time.

**Comment by Harris-Miller** [comment]
Removing `<base href='''>` would break both the `<img>` and `background-image` in my example. Wondering how that could be avoided without a `<base>` set...

**Comment by stefanpenner** [comment]
likely  having ember-cli re-write the paths as part of a build step

**Comment by Harris-Miller** [comment]
Looking into open issues, this is related to #417

**Comment by stefanpenner** [comment]
yup

**Comment by catbieber** [comment]
I have been looking at #417 and it seems related to Ember.HistoryLocation using baseURL and Ember.HashLocation not. Is it worth looking at a smaller fix for that if there's a plan to remove baseURL entirely? I'm not really clear on what the difference is between baseURL and rootURL as they are now.

I'm happy to work on this issue along with the other one if I have an idea of what approach would be acceptable.

**Comment by jdmarshall** [comment]
This also breaks a lot of common uses of SVG, especially around symbols and gradients.  I've figured out how to work around the symbol problem but gradients are still resisting, especially on Chrome.

**Comment by Orthocenter** [comment]
Is there any better solution other than manually rewrite the url?
