### ISSUE TITLE
module.exports = app.toTree({})

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#2992]
In the file `Brocfile.js` the following line
```
module.exports = app.toTree();
```
should be changed to:
```
module.exports = app.toTree({});
```

(Reason is minor, but my syntax checker sticks bothersome squigglies there which bugs me)

**Comment by rwjblue** [comment]
@kgish - Why?  To invoke a function, you do not have to pass arguments.  Also, the argument to `toTree` is an array not an object.

**Comment by kgish** [comment]
My bad, need to adjust my syntax checker I guess.

**Comment by stefanpenner** [comment]
@kgish im curious which editor/syntax checker you are using, maybe their is something on our end we can do to help it. But regardless i would love to hear the resolution.

**Comment by kgish** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/79195/5739340/e3a185ac-9bf8-11e4-9c65-3930b948307f.png)

**Comment by kgish** [comment]
For those with a similar problem, look here:
http://stackoverflow.com/questions/23208864/webstorm-8-how-to-get-rid-of-warning-message
