### ISSUE TITLE
Is './' really needed?

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#2993]
In the file `app.js` and elsewhere wouldn't it be better to change:
```
import config from './config/environment';
```
instead to:
```
import config from 'config/environment';
```

Reason, squigglies in my syntax checker.

**Comment by stefanpenner** [comment]
We do need the `./` as it says relative to the current modules path, find me `config/environment`

By removing the slash it doesn't know it must be relative lookup.

**Comment by kgish** [comment]
I use Webstorm and it turns out that in order to get this to work I have to mark the root project directory as a `resource root`.

Mouse over project directory in the left project pane, right mouse click, mark directory as resource root.

**Comment by joostdevries** [comment]
@stefanpenner Any reason we don't use `<%modulePrefix%>` here?

**Comment by stefanpenner** [comment]
@joostdevries refactoring hazard

**Comment by joostdevries** [comment]
:+1: understandable.
