### ISSUE TITLE
Document debug logging on website.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#2994]
`DEBUG=ember-cli:* ember <command>` will log everything (I think). It would be nice to explain how to use this and what it does on the website.

**Comment by stefanpenner** [comment]
`DEBUG=ember-cli:* ember <command>` will log everything in the ember-cli package, but not its dependencies. `DEBUG=*` can be used to debug everything.

**Comment by stefanpenner** [comment]
@chadhietala mind looking at this one?

**Comment by stefanpenner** [comment]
meh, power-user land.
