### ISSUE TITLE
[DISCUSSION] Roadmap

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#2997]
While there is the [milestones for 1.0.0](https://github.com/ember-cli/ember-cli/milestones/v1.0.0) I'm wondering if we could work on an official roadmap. Ember CLI will hit 1.0.0 at some put this year and I think it would be great to have a list of features and big bets going forward.  Having a roadmap is also a much easier way of shopping it around in a company.

This is in no way criticism, it would just be nice to get ideas out of peoples heads and down on paper even if it is high level. Detailed designs should still go through the RFC process.

**Comment by stefanpenner** [comment]
:+1:

**Comment by jakecraige** [comment]
:+1: this 

A [Wish List](https://github.com/ember-cli/ember-cli/wiki/Wish-List) exists in the wiki, but it hasn't been updated since June.

We could add a roadmap page to the wiki, or readme or create ROADMAP.md. Don't really have a preference personally.

**Comment by chadhietala** [comment]
We could do `ROADMAP.md` or if we don't want to get too committed pre-1.0.0, it could be a working draft until we reach 1.0.0.  I think there are other large features we want to bake before 1.0.0.

**Comment by twokul** [comment]
very nice.

I would route for cleaning up code + tests to make easier to contribute (and for our own sake) and making sure that `ember doctor` works perfectly.

**Comment by twokul** [comment]
@stefanpenner @chadhietala @jakecraige what do you think is missing in ember-cli?

**Comment by chadhietala** [comment]
Heres a list of things:

- The ability to declare/whitelist to code to bundle separately. @bcardarella is going to work on this.
  - Currently everything goes into vendor or the app bundle.
  - This probably starts the happy path for engines
- Non-borked ES6 modules
  - The current module transpiler is old is not spec compliant (@stefanpenner might have fixed this today :smile:). Forces you to do weird things with relative paths.
- A path for ES6 modules code coming from NPM.
   - Should be able to dependend on ES6 code from NPM without creating an addon
   - This involves looking at package.json looking for "jsnext:main" and then funneling it over.
   - Currently ember-browserify just cats non ES6 code
- Environment files instead haphazardly pivoting off of process ENVs
  - I think @jakecraige was going to look at this

**Comment by stefanpenner** [comment]
> Non-borked ES6 modules
> The current module transpiler is old is not spec compliant (@stefanpenner might have fixed this today ). Forces you to do weird things with relative paths.

ya pending some coordination with @ef4 and @rich-harris

**Comment by knownasilya** [comment]
Not requiring a `package.json` in the top level, aka allow the ember-cli stuff to be in a subdirectory without requiring multiple package.jsons.

**Comment by stefanpenner** [comment]
* nested add-ons
* styles in addons
* different handling of styles based on sass, less, XYZ, or vanilla
* tree shaking
* engines for lazy loading.

**Comment by johnnyshields** [comment]
I'm seeing a lot of addons like:

* ember-cli-bootstrap
* ember-cli-moment
* etc etc

whose sole purpose is to include Javascript and/or CSS assets into the project. I think this pattern which should be discouraged, for several reasons:

* the asset version is tied to add-on version; implementer can't specify an asset version of their choosing
* the maintainers are unlikely to be interested in updating their addon packages one year from now
* Browserify and Bower already exist

**Comment by ef4** [comment]
>  I think this pattern which should be discouraged...

I agree. We ideally want to be able to consume upstream packages directly. There are still some significant gaps in standardization that make that annoying, but rather than publish separate ember-cli-specific packages, a better stopgap would be a Homebrew-like system of recipes for importing the upstream packages.

**Comment by stefanpenner** [comment]
> ember-cli-moment 

now ember-moment is mostly fine, as it does provides ember [specific code](https://github.com/stefanpenner/ember-moment/tree/master/addon/helpers) that merely depends on moment. The pure wrapper module is absolutely bad practice, like list-view + ember-data  are today.

I would love to get `ember-browserify` working for add-ons in a reasonable way, and work towards a path for new es6 moduled code to be nicely consumed.

**Comment by ef4** [comment]
`ember-browserify` is pretty close to good enough for Javascript. But we would need a story for non-JS assets too.

**Comment by johnnyshields** [comment]
> we would need a story for non-JS assets too

IMHO the current ad-hoc combination of Bower and the `/vendor` dir is adequate for non-JS assets until there's a better Browserify-like solution that comes along. JS assets are the far larger problem, and I don't think we should let the fact that Browserify isn't used for non-JS assets prevent us from adopting it to solve our (mostly) JS-related pain point.

**Comment by johnnyshields** [comment]
@stefanpenner I would think that if we had first-class support for Browserify, your [ember-moment](http://github.com/stefanpenner/ember-moment) lib (which provides Ember helper methods to wrap moment.js) should be restructured as a Browserify package instead of an Ember-CLI addon, as it does nothing specific to Ember-CLI itself as far as I'm aware. What do you think?

**Comment by stefanpenner** [comment]
@johnnyshields I disagree.

moment should be introduced to the system via browserify as it originates as a NPM distributed CJS module.

The add-on specific code, helpers, initializers, computed properties written in ES6 should continue to enter the system as it does today, via the conventional `app/*` and `addon/*` and allow ember-cli to do its thing.

**Comment by stefanpenner** [comment]
> ember-browserify is pretty close to good enough for Javascript. But we would need a story for non-JS assets too.

There still are issues, mostly stemming from the resolution algorithm. Applying browserify to each addon individually will work but result in a very quick explosion of duplicates. Applying browserify to the entire tree would be ideal unfortunately I do not believe that scenario works correctly yet.
