### ISSUE TITLE
Overeager Dependency Checker

### ISSUE THREAD

**Issue by tomdale** [ember-cli/ember-cli#2998]
Running ember-cli 0.1.7, I got a warning that one of my Bower deps is out of sync iwth my `bower.json` (great!). So then I tried to run `ember install` to update them, but it seems like the dep check happens before that command is run.

Forgive me if I'm missing something here, but it seems like we should specifically disable the dependency check for commands whose purpose is to update dependencies, like `install`, `install:npm`, etc. (I was also a little surprised to see I could not even run `ember -v` when my dependencies were out of date.)

**Comment by stefanpenner** [comment]
you are correct, depenency checker should be disabled for `ember install`, `ember version`, `ember help` and the future `ember doctor`... maybe more?

**Comment by stefanpenner** [comment]
@quaertym got some time to dig in?

**Comment by quaertym** [comment]
@stefanpenner  Yep, I had realized the same issue a few days ago. Since ember install is recently introduced we did not cover that when the dependency checker was first implemented. I am not sure how to detect it and behave accordingly on the cli side. Any suggestions? Maybe first step is to add an option to dependency-checker to skip dependency check.

**Comment by marcioj** [comment]
I am unsure if it makes sense but maybe we could add a new validation option [here](https://github.com/ember-cli/ember-cli/blob/master/lib/models/command.js#L106-L133), like we do today for `Command#works`. Something like this:

```js
if (this.checkDependencies) {
  var EmberCliDependencyChecker = require('ember-cli-dependency-checker');
  new EmberCliDependencyChecker(this.project).checkDependencies();
}
```

The downside of this is that ember-cli-dependency-checker will become an ember-cli dependency and be used like a library instead an addon included in ember apps.

Another alternative is to provide some hook for addons validate the command execution, but I don't know if commands should have such knowledge.

What do you think @stefanpenner @quaertym ?

**Comment by stefanpenner** [comment]
`ember install` is being killed in its current incarnation. Rather it will became the same as the current `ember install:addon`
