### ISSUE TITLE
Unhandled 'error' event when saving files using Sublime Text 3(with atomic saving)

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3000]
When using Sublime Text 3 with atomic saving enabled(which is default setting), after saving file I get an error and ember-cli crashes:
~~~~
file changed templates/components/edit-property.hbs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, stat '/home/user/Projects/appName/app/templates/.sublfb3.tmp'
~~~~
More explanation about default Sublime Text 3 atomic saving: http://stackoverflow.com/a/20639093/2166409

For now I'll just turn it off, but it would be nice to see ember-cli not crashing when working with Sublime Text 3 default options, because it's popular editor.

**Comment by jakecraige** [comment]
This would be good to add to the docs [here](http://www.ember-cli.com/#usage-with-sublime-text)

**Comment by stefanpenner** [comment]
broccoli (or the watcher) needs to guard against this case, the FS is racy. We must assume a file that triggered a change may disappear quickly.
Its a bummer that these fs events in node, don't give a reasonable stack trace...

**Comment by stefanpenner** [comment]
sublime is a big audience, we should sort this out ASAP.

**Comment by quaertym** [comment]
We have the same problem at one of our computer at work.

**Comment by jcope2013** [comment]
having this constantly happen about 10-20 times a day, I will give turning off atomic saving a try

**Comment by Kuzirashi** [comment]
Same problem when I copied and replaced 6 files at once in my app/templates directory on Ubuntu 14.10:
~~~~
file changed templates/xxx/choose.hbs
file changed templates/xxx/men-diets.hbs
file changed templates/xxx/men-diets.hbs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, stat '/home/user/Projects/appName/app/templates/xxx/.goutputstream-GFGKSX'
~~~~

**Comment by raytiley** [comment]
Can people having this problem post there package.json files? I'm interested in what addons / broccoli plugins you might be using. I'm getting no where trying to recreate this. Also OS  and if your using watchman would be helpful. Thanks.

**Comment by raytiley** [comment]
I've tracked down the problem to broccoli-sane-watcher. https://github.com/krisselden/broccoli-sane-watcher/blob/master/index.js#L121-L125

When it catches an error it emits the error and then re-throws but nothing handles it. Soliciting some feedback as to how to solve, hopefully should have a fix in the next release.

**Comment by stefanpenner** [comment]
@raytiley ah, is it in the event emitter itself?

**Comment by raytiley** [comment]
@stefanpenner My comment above is incorrect, I think I was catching a different unrelated exception. After further investigation I figured out that the problem is that broccoli-sane-watcher doesn't subscribe to error events emitted by sane. In node if nothing handles an error event the default behavior is to throw an exception. Since nothing handles the exception nodes default behavior of exiting the process happens.

My PR above to broccoli-sane-writer subscribes to error events from sane and passes them up to ember-cli's watcher class. With that PR the error is printed to the screen and ember-cli will continue to run.

**Comment by rwjblue** [comment]
Reopening until we get an updated broccoli-sane-watcher in ember-cli.
