### ISSUE TITLE
Use Mocha instead of QUnit by default.

### ISSUE THREAD

**Issue by esbanarango** [ember-cli/ember-cli#3001]
Thank you for this project!

Would be great that ember-cli would come with Moche instead of QUnit.

> QUnit is to Ember-cli as Minitest was to Rails!

**Comment by rwjblue** [comment]
@esbanarango - Agreed. I much prefer minitest. :trollface: 

It is very important for us to ensure that both work well going forward, but we are highly unlikely to change the default.

**Comment by stefanpenner** [comment]
this should be configurable via and addon ember-cli-qunit handles the qunit stuff for us, if someone is motivated the mocha version should be relatively simple

**Comment by rwjblue** [comment]
@stefanpenner - It already exists! ember-cli-mocha is an AWESOME addon, and is being kept in lock-step with ember-cli (thanks to much work by @dgeb and crew).

**Comment by cowboyd** [comment]
The only thing that's really missing to achieve full parity with Qunit is the ability to generate addons and apps that are setup for mocha from the get-go. Currently, you have to generate your app or addon, then go through a manual uninstall process for qunit before installing ember-mocha.

Perhaps this ticket should be renamed to "add --skip-qunit" option to app and addon blueprints?

**Comment by esbanarango** [comment]
@cowboyd the `--skip-qunit` option would be great! :+1:
