### ISSUE TITLE
Install error when ember-cli installed one directory up

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3002]
Just putting this out there. Basically 'dashboard' is a subdirectory in a project and both the top directory and this directory have `package.json` files. I forgot to remove the `/node_modules/ember-cli` folder from  a previous refactor, and this is the error I got when trying to upgrade.

```
iradchenko dashboard (develop)$ rm -rf node_modules bower_components dist tmp
iradchenko dashboard (develop)$ ember install:npm ember-cli@0.1.7

undefined:2
  /**
  ^
SyntaxError: Unexpected token /
    at Object.parse (native)
    at Object.me.readFileSync (/Users/iradchenko/workspace/mapgeo2/node_modules/ember-cli/node_modules/yam/node_modules/fs-extra/node_modules/jsonfile/lib/jsonfile.js:23:15)
    at Object.readFile [as read] (/Users/iradchenko/workspace/mapgeo2/node_modules/ember-cli/node_modules/yam/lib/utils/config-file-utils.js:40:13)
    at Yam._createStorageFile (/Users/iradchenko/workspace/mapgeo2/node_modules/ember-cli/node_modules/yam/lib/yam.js:40:66)
    at new Yam (/Users/iradchenko/workspace/mapgeo2/node_modules/ember-cli/node_modules/yam/lib/yam.js:24:8)
    at cli (/Users/iradchenko/workspace/mapgeo2/node_modules/ember-cli/lib/cli/index.js:35:16)
    at /usr/local/lib/node_modules/ember-cli/bin/ember:26:3
    at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:48:21
    at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:127:35
    at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/airadchenko
```

**Comment by twokul** [comment]
@knownasilya seems like yam gives us some grief here.

**Comment by AndyPyeSC** [comment]
I just got this on Windows _without_ the nested directory structure @knownasilya described. I pulled one of my company's repos and ran the following commands (in this order - it's a script we have in the repo):

call npm install -g phantomjs
call npm install ember-cli@0.0.40
call npm install -g bower
call npm install broccoli-concat
call npm install broccoli-static-compiler
call npm install broccoli-merge-trees
call npm install mkdirp
call npm install broccoli-kitchen-sink-helpers
call npm install broccoli-writer
call npm install js-string-escape
call npm install broccoli-merge-trees
call npm install broccoli-uncss
call npm install
call npm update
call bower install

Calling ember, even without any parameters, causes the same error message as the original post.

**Comment by stefanpenner** [comment]
> call npm install -g phantomjs
> call npm install ember-cli@0.0.40
> call npm install -g bower
> call npm install broccoli-concat
> call npm install broccoli-static-compiler
> call npm install broccoli-merge-trees
> call npm install mkdirp
> call npm install broccoli-kitchen-sink-helpers
> call npm install broccoli-writer
> call npm install js-string-escape
> call npm install broccoli-merge-trees
> call npm install broccoli-uncss
> call npm install
> call npm update
> call bower install

this seems to install an extremely old version of ember-cli, also it seems to install dependencies that already come with ember cli. Something seems strange.

**Comment by AndyPyeSC** [comment]
@stefanpenner It could well be that the batch file is incorrect or out of date. We don't touch that repo very often and it was our first CLI project.

I've found that I seem to have a global version of ember (0.1.12) installed too. I'm not on my usual development machine so that could be to blame.
