### ISSUE TITLE
Disabling "The backend rejected the commit because it was invalid” during test.

### ISSUE THREAD

**Issue by esbanarango** [ember-cli/ember-cli#3003]
Hello and thank you guys again for Ember cli.

Right now I'm writing an integration test that covers the failure of saving a record, I'm mocking the response with [Pretender](https://github.com/trek/pretender) to returns an status code of 422 and the proper error messages, then asserting that the error message is properly showed to the user.

````js


import {
  describeModule,
  it
} from 'ember-mocha';

import startApp from './../helpers/start-app';
import Ember from 'ember';

var App;
var server;

describe('Integration - Ink colors',function() {

  // Hooks
  before(function() {
    App = startApp();
    server = new Pretender();
  });

  after(function() {
    Ember.run(App, 'destroy');
  });


  describe('Creation', function() {

    describe('with invalid data', function() {

      // Hooks
      beforeEach(function() {
        server.post('/api/v1/ink_colors', function(request) {
          return [422, {"Content-Type": "application/json"}, JSON.stringify({"errors":{"name":["can't be blank"]}})];
        });

      });

      // Tests
      it('show an error message', function() {

        visit('/ink-colors').click('.create-resource');

        fillIn('.form-field.name input', '');

        click('.submit button');

        andThen(function() {
          expect($('.form-field.name').hasClass('error')).to.equal(true);
        });


      });


    });

  });

});  
````

The issue is that I'm getting this error: `The backend rejected the commit because it was invalid: {errors: [object Object]}`

Is there a way to silence that error during tests? 'cause it makes that test to fail.

![screen shot 2015-01-15 at 12 23 55 pm](https://cloud.githubusercontent.com/assets/1156865/5762642/9a279682-9cb1-11e4-8f82-d1cc10815679.png)

**Comment by Kuzirashi** [comment]
You can catch error with following code:
~~~~
model.save().catch(function(error) {
  # error is not throwed to console
  # however you can log it with console.log(error);
});
~~~~

**Comment by stefanpenner** [comment]
a better venue to ask this is on stack-overflow, we gotta keep the issue tracker on-topic or it will be overrun.  Feel free to cross link

**Comment by lcoq** [comment]
For future readers, there is [the same question on stackoverflow](http://stackoverflow.com/questions/25000090/handle-the-backend-rejected-the-commit-because-it-was-invalid-during-test), but still no acceptable answer since Jul 28 '14.

Use `.catch` as @Kuzirashi said is not an acceptable solution as the idea is to prevent this error to throw only during *tests*.

cc @stefanpenner

**Comment by nathanhammond** [comment]
Note this isn't related to Ember CLI. This is an Ember Data question.

Please stop by the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you have questions about how things work or proposals for changes.

**Comment by lcoq** [comment]
@nathanhammond Really sorry I thought I was on ember-data repo. Apologies!
