### ISSUE TITLE
Brocfile is incorrect when creating an addon

### ISSUE THREAD

**Issue by thoov** [ember-cli/ember-cli#3005]
When creating an addon on via `ember addon foo` I notice 2 things:

1. App and addon folders are missing? This might be by design not sure.
2. The brocfile that is generated is:
```js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();
```

when it used to be:

```js
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

var app = new EmberAddon();
```

**Comment by thoov** [comment]
this is with v0.1.7

**Comment by rwjblue** [comment]
This is a dup (was an issue with published/packed versions only). Should be fixed in master and ready for the next version.

**Comment by thoov** [comment]
@rwjblue thanks
