### ISSUE TITLE
`ember install:npm <package>` eschews SemVer by default.

### ISSUE THREAD

**Issue by crazymykl** [ember-cli/ember-cli#3006]
This behavior, introduced in commit fcb3f70e3712c9566e5162ce9dce2f2ce8c02e1e, is very different than standard practices. If users wish to lock down their versions, or even shrinkwrap, they certainly can, but the default should be Semantic Versioning.

**Comment by stefanpenner** [comment]
@chadhietala thoughts?

**Comment by chadhietala** [comment]
Having exact versions is exactly what the [SemVer specification says](http://semver.org/). NPM decided to create their [own flavor of semver](https://github.com/npm/node-semver) which adds non-spec compliant ranges at the beginning of the version.

NPM's current state of shrinkwrap is pretty broken leaving you without a reliable lock file. For instance I just ran `npm skrinkwrap` on a 0.1.7 addon and I simply can't shrink wrap it.

```
→ npm shrinkwrap  
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/chietala/.nvm/v0.10.33/bin/npm" "shrinkwrap"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.12

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: broccoli-test-helpers@0.0.1 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/broccoli-test-helpers
npm ERR! extraneous: rsvp@3.0.16 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/rsvp
npm ERR! extraneous: walk-sync@0.1.3 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/walk-sync
npm ERR! extraneous: fs-extra@0.14.0 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/fs-extra
npm ERR! extraneous: chai@1.10.0 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/chai
npm ERR! extraneous: broccoli-stew@0.1.6 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/broccoli-stew
npm ERR! extraneous: broccoli-merge-trees@0.2.1 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/broccoli-merge-trees
npm ERR! extraneous: mocha@2.1.0 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/mocha
npm ERR! extraneous: broccoli@0.13.3 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/broccoli
npm ERR! extraneous: ember-cli-esnext@0.1.1 /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/node_modules/ember-cli-esnext
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chietala/workspace/shift/ember-cli-linkedin/l10n/npm-debug.log
```

As a rule of thumb, when you do a deployment the contents should be immutable and not have "helpful" upgrades that potentially break the build and are hard to track down.

**Comment by crazymykl** [comment]
I don't disagree with your central point, so concisely rendered in your "tl;dr", but I think that making changes based on the brain-damagedness of `npm shrinkwrap` should not be driving design decisions here. (Deleting the "extraneous" directories might make that work, bee tea dubs.)

Yes, the Node community's semver is a "unique" interpretation of the specification, but fighting against it is swimming upstream, imo.

**Comment by stefanpenner** [comment]
I am unsure which course is the correct one. I am leaning towards stricter until some of the underlying NPM issues are sorted out.

This is a loosely held opinion, my only goal is to pave a reasonable path through the crazy for our users.

**Comment by stefanpenner** [comment]
stricter for now, open to being convinced though.

**Comment by crazymykl** [comment]
Do you believe it is desirable for `npm update` to be a no-op on the ember-cli golden path?

**Comment by dafortin** [comment]
Hi guys,

We are currently working on an addon that will install a set of packages in a file [ember-cli-ecosystem-installer](https://github.com/ciena-blueplanet/ember-cli-ecosystem-installer ). 

The basic concept of that tool is the following:
1. You do an `ember install ember-cli-ecosystem-installer`
1. The tool willl prompt you with a list of packages to install and it will also check the packages installed
1. The user can choose packages
1. The tool will install/unistall all those packages

We noticed that even if we are requesting a version respecting semver format ember is installing a fixed version. For us it's very important to install the version requested and not a fixed version.

We are using `npm shrinkwrap` for other projects and it's working fine. 

Will it be possible to reopen this discussion and determine if it will be possible to have a better handling of semver version to get `~`, `^` and `>>=<<=` working?

**Comment by nathanhammond** [comment]
@dafortin I'd still like to see a PR for #6386! That would address your problem here.

**Comment by dafortin** [comment]
@nathanhammond
We did try to implement this, but even if we were setting the save exact to false we were still getting the exact version. There is no value submitting this if it's not working.
