### ISSUE TITLE
[Feature Request] Blacklist pods

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3012]
Ok so I want to enable POD structure by default in `.ember-cli` file, but I only do pods for `controllers`, `views`, `templates`, and `routes`.

So If there was an option to blacklist other types from going into the pod structure, when doing `ember g`, that would make this actually useful, otherwise I keep doing `ember g ... --pod ...`.

Maybe something like `ignorePods: ['models', 'mixins']`.

**Comment by trabus** [comment]
I like this for the fact that it would provide a place to explicitly define what blueprints do and don't support pod structure. Currently there are several blueprints that don't support pod format and simply ignore the `--pod` flag (mixins being one of them). 

This would mainly affect blueprints like model, that do support pod format, but are often preferred in the type structure. It would also allow blueprints like resource to generate the route and template in pod structure, but the model would generate in type structure.

**Comment by knownasilya** [comment]
>  It would also allow blueprints like resource to generate the route and template in pod structure, but the model would generate in type structure.

That would be a nice by-product.

**Comment by stefanpenner** [comment]
seems to have gone stale

**Comment by knownasilya** [comment]
Is this part of the alternate pod structure? How is that coming along?

**Comment by stefanpenner** [comment]
> Is this part of the alternate pod structure? How is that coming along?

unknown
