### ISSUE TITLE
[Feature Request] Config: Set different test server port to app server port

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/ember-cli#3022]
When setting `port` in the `.ember-cli` config file, it sets the same port for both the regular app and the testing server. This means you have to run one of them with the `--port` flag if running them simultaneously.

Out-of-the-box Ember CLI sets two different ports for the app (4200) and the testing server (7357), it would be nice if you could also set the the app and testing ports separately in the config file.

If this is a change you guys would like to make, I'd be happy to put together the PR for it.

**Comment by technomage** [comment]
I second this.  We are running multiple Ember UIs for one project and need to allocate non-colliding ports for the app servers and the tests on each of them.

**Comment by stefanpenner** [comment]
> If this is a change you guys would like to make, I'd be happy to put together the PR for it.

ya, seems pretty annoying. What do you propose? 2 config options, or 1 and an offset, or a combination of both?

**Comment by sandinmyjoints** [comment]
Maybe a combination: offset from `port` by default, with ability to override via config?

**Comment by patocallaghan** [comment]
Like @sandinmyjoints I like the combination idea. Have an offset by default but if you want to override it, you can.

Any ideas for the config name? `testsPort`? `testPort`?

**Comment by stefanpenner** [comment]
testPort

**Comment by patocallaghan** [comment]
Thanks, I'll put this together this weekend.

**Comment by stefanpenner** [comment]
@patocallaghan :)
