### ISSUE TITLE
Upgrade to ember-cli 0.1.7 (from 0.1.5) increases build time threefold

### ISSUE THREAD

**Issue by pedrokost** [ember-cli/ember-cli#3023]
With ember 0.1.5, build times were at 3 seconds. After upgrade to 0.1.7 build times are at 10seconds.

```
Build successful - 10305ms.

Slowest Trees                  | Total          
-------------------------------+----------------
ES6Modules                     | 1412ms         
Funnel: App JS Files           | 1304ms         
Concat: App                    | 954ms          
Concat: Vendor                 | 913ms          
SassCompiler                   | 529ms          
Concat: Test Support JS        | 523ms          
```

**Comment by xcambar** [comment]
Same as https://github.com/ember-cli/ember-cli/issues/2856

**Comment by pedrokost** [comment]
Right, sorry for the duplication. It seems build times get worse with each new release, instead of decreasing.

**Comment by stefanpenner** [comment]
This trade-off was to get better source maps. We can likely reduce it again, it just needs someone with some extra time

**Comment by joostdevries** [comment]
@pedrokost You might want to look at [ember-cli-ramdisk](https://www.npmjs.com/package/ember-cli-ramdisk) to speed up rebuilds.

**Comment by pedrokost** [comment]
@joostdevries Thanks for the tip. This allowed me to half build times. Now they take 4 seconds instead of 10 on an i7 computed wish SSD, using Vagrant. On a much slower laptop with slow hard drive, I was able to speed it up from 28s to 4 seconds as well!

I hope ember-cli reduces it's build time in following releases. Not everyone works with SSD's and i7 (which even prove too slow for these specs), but regular laptops with slow HDDs.

**Comment by stefanpenner** [comment]
> using Vagrant.

this is likely your issue, some slow file sharing mechanism is your bottle neck

**Comment by pedrokost** [comment]
I am using `nfs: true`. Shouldn't this eliminate the problem?

Out of curiosity, are 3 seconds builds the norm, or are builds faster for most ember-cli users?

**Comment by stefanpenner** [comment]
@pedrokost depends on the size of your vendor and app.
