### ISSUE TITLE
HTMLBars Helpers are not bound by default

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#3027]
I'm not sure if this is an ember-cli issue or one that should be opened in ember.js itself. After upgrading from handlebars to htmlbars for an addon, helpers that were previously using bindings are no longer doing so. It seems that HTMLBars' HandlebarsCompatibleHelper is being used instead of makeBoundHelper.

According to the source, this may be expected: https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/compat/make-bound-helper.js#L35-L36 however, I would argue that this is breaking SemVer considering helpers in ember-cli were previously bound with Handlebars.

**Comment by rwjblue** [comment]
The default behavior of exporting a function in app/helpers/foo-bar.js should not have changed between 1.9 and 1.10.

Would you mind providing a simple reproduction repo demonstrating the issue, to help track this down?

**Comment by bcardarella** [comment]
@rwjblue see this PR for `ember-cli-i18n` https://github.com/dockyard/ember-cli-i18n/pull/61

The `t` helper is not properly retrieving bound values passed to it.

**Comment by bcardarella** [comment]
@rwjblue specifically, see this line: https://github.com/dockyard/ember-cli-i18n/blob/bc-update-to-ember-1.10/tests/dummy/app/templates/application.hbs#L8

**Comment by rwjblue** [comment]
Using a plain function as a helper has always been unbound.  Using a function wrapped in `makeBoundHelper` will be bound. This is consistent with all versions of Ember that I checked (JSBins below for 1.4 through 1.10).  This API has been remarkably stable as you can see from the fact that these JSBin's all work without changes.

* 1.10.0-beta.4 - http://emberjs.jsbin.com/rwjblue/242/edit
* 1.9.1 - http://emberjs.jsbin.com/rwjblue/236/edit
* 1.8.0 - http://emberjs.jsbin.com/rwjblue/237/edit
* 1.7.0 - http://emberjs.jsbin.com/rwjblue/238/edit
* 1.6.0 - http://emberjs.jsbin.com/rwjblue/239/edit
* 1.5.0 - http://emberjs.jsbin.com/rwjblue/240/edit
* 1.4.0 - http://emberjs.jsbin.com/rwjblue/241/edit

I will look into the ember-cli-i18n issue tonight (or possibly tomorrow morning), and will update the issue over there with details on how to deal the particular bug in that library.

**Comment by bcardarella** [comment]
If that is the case why the `t` helper working prior to HTMLBars?

**Comment by rwjblue** [comment]
@bcardarella - Not sure yet, I was triaging the potential bound/unbound helper bug in Ember first.  Will be looking into the ember-cli-i18n specific case next.

**Comment by bcardarella** [comment]
Everything is working as expected

**Comment by chadhietala** [comment]
@bcardarella What was the solution to this?

**Comment by bcardarella** [comment]
@chadhietala it seems that because of how `ember-cli-i18n` was written the bound helpers were being simulated via streams instead of actually relying on `makeBound`. So in short, I was mistaken.
