### ISSUE TITLE
[Feature Request] ember addon [name] --type [type]

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3032]
Generate addons by type, sample types could be:

* __component__ - asks for a name, and generates `addon/components/[name].js` & `app/templates/components/[name].hbs`, `app/components/[name].js` and does an import here.
* __service__ - asks for a name, and generates `addon/service/[name].js` &
`addon/initializers/[name]-service.js`.
* __adapter__ - generates adapter/serializer for ED
* __mixin__ - generates a mixin
* etc..

**Comment by trabus** [comment]
This would be good for command based addons. They have a totally different setup test-wise. We could make an addon that contains a whole set of built-in blueprints for the different types of addons.

**Comment by jakecraige** [comment]
I agree it would be nice to have this as an addon. 

I see one problem with the addon system currently though and that's that this command works outside a project. Currently, I think you can only add commands that work within a project. The reason being that we scan for addons from the addon's package.json. 

Ideally there are some sort of global addons that could provide this feature and we could simply have all the addon generators in it's own addon that contains all of this functionality

**Comment by stefanpenner** [comment]
seems like just getting generators working correctly when working in ad addon would solve this?

cc @jgwhite

**Comment by jgwhite** [comment]
Addons that add global tools seem good to me. This would allow for an ember-cli-addon-blueprints package that implements this feature request.

**Comment by jakecraige** [comment]
With addon's that provide global tools. Does anyone have an idea of how we could detect them?

**Comment by knownasilya** [comment]
@jakecraige can you expand on "detect them".

**Comment by jgwhite** [comment]
@knownasilya there’d be no `package.json` to look in. We’d have to scan globally installed packages somehow.

**Comment by jgwhite** [comment]
@knownasilya in order to make them available through the `ember ...` command.

**Comment by knownasilya** [comment]
@jgwhite Maybe we should have a look at how [Yeoman](https://github.com/yeoman/yeoman) does it.

**Comment by jgwhite** [comment]
@knownasilya good call :+1:

**Comment by knownasilya** [comment]
https://github.com/yeoman/yo & https://github.com/yeoman/generator

**Comment by jgwhite** [comment]
https://www.npmjs.com/package/npm-keyword

**Comment by knownasilya** [comment]
Nice!

**Comment by jakecraige** [comment]
@jgwhite Looks like that just searches the npm registry, don't we need it to search the local machine instead?

**Comment by jakecraige** [comment]
https://github.com/yeoman/environment is how they look up deps it looks like

**Comment by stefanpenner** [comment]
seems to ahve gone stale
