### ISSUE TITLE
addon/ folder not included in ember build output

### ISSUE THREAD

**Issue by igillis** [ember-cli/ember-cli#3034]
I'm working on an ember-cli addon at https://github.com/Addepar/ember-widgets/tree/igillis/try_addon_folder. 

Originally I had everything in the `app/` folder and all was well. I tried to move implementation code into the `addon/` folder and update the import statements to be like `{my_addon_name}/components/foo`, but the imports fail. There are no build errors.

I looked in `dist/` and there is no sign of my transpiled code. I did a sanity check on some other ember-cli addon projects, and it seems that their addon folder is appended to `dist/assets/vendor.js`. Mine is not there. Any ideas? Maybe some error getting swallowed?

**Comment by jakecraige** [comment]
I *think* it's not going to work since they're in coffeescript. I could be wrong though

**Comment by stefanpenner** [comment]
@jakecraige ya, i suspect this falls into the addon of and addon category of problems. It requires some clever trickier to made it work today.

**Comment by igillis** [comment]
@stefanpenner any ideas what kind of cleverness would be required? A blueprint with custom logic for compiling/copying everything into `dist/`?

**Comment by stefanpenner** [comment]
not a blueprint, but the emberaddon entry file

**Comment by igillis** [comment]
@stefanpenner sounds good! Thanks for your help.

**Comment by stefanpenner** [comment]
addon of addons work now, i suspect this has been resolved. If it has not, steps to reproduce / example addon would be great.
