### ISSUE TITLE
Exports option of app.import not working properly

### ISSUE THREAD

**Issue by wbyoung** [ember-cli/ember-cli#3041]
Based on [the docs](http://www.ember-cli.com/#standard-amd-asset), it seems that I should be able to do something like this after a `bower install --save marked`:

```js
// Brocfile.js
app.import('bower_components/marked/lib/marked.js', {
  exports: {
    'marked': ['default']
  }
});

// in a controller
import marked from 'marked';
```

I'm getting a require error of _could not find module marked_, though. Based [on the source](https://github.com/ember-cli/ember-cli/blob/v0.1.7/lib/broccoli/ember-app.js#L864), it doesn't seem like `app.import` supports this `exports` option. Are the docs wrong or out of date here?

**Comment by stefanpenner** [comment]
that error is saying their is no module called `marked` in the client side registry.

**Comment by stefanpenner** [comment]
unfortunately at this time, we do not support anonymous AMD modules. We have the tools in place to fix this, just haven't had time to stitch it together yet.

cc @abuiles

**Comment by wbyoung** [comment]
@stefanpenner thanks for the quick response. I'm happy at taking a stab at stitching it together as well if you or @abuiles are able to point me in the right direction.

Otherwise, the global export is working fine for now.

**Comment by stefanpenner** [comment]
@abuiles we should start a quick RFC on this, so others can join in.

**Comment by wbyoung** [comment]
@stefanpenner is there a plan to fix this in the future or document it better now? Sorry, I'm not familiar with the development process & issue management for Ember CLI.

**Comment by stefanpenner** [comment]
@wbyoung for now, you can use it as a global.

**Comment by Cryrivers** [comment]
when can we import AMD/UMD modules without using it as a global?
