### ISSUE TITLE
Addon imports broken using coffeescript

### ISSUE THREAD

**Issue by TayHobbs** [ember-cli/ember-cli#3043]
I am trying to write an addon that uses components with coffescript, but when I try to import my component to get in into the namespace, it bombs out saying: `Uncaught Error: Could not find module path/to/module`

If I switch the files to be .js files they import totally fine.
Am I missing something or is this an issue?

**Comment by mszoernyi** [comment]
How so you define your imports? We have to use `import foo from 'bar'`
