### ISSUE TITLE
Inject EMBER_INSPECTOR_CONFIG into index.html

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-cli#3045]
Discussed over irc. 

Potential use-cases:
- Easily feed the inspector relevant app config bits like `modulePrefix` and `podModulePrefix`
- Allow addons to send additional config/data to the inspector
- ...

@stefanpenner @teddyzeenny suggestions/additions/comments welcome. Hope to play around with this over the weekend.

**Comment by stefanpenner** [comment]
:+1:

**Comment by teddyzeenny** [comment]
:+1: 

For the new deprecation tab, the inspector needs `{ isEmberCli: true, modulePrefix: 'my-app', podModulePrefix: 'my-app', hasSourceMaps: true }`

**Comment by jakecraige** [comment]
Is this something an inspector addon could do with the `contentFor` hook?

**Comment by stefanpenner** [comment]
@jakecraige i think it needs to be bundled in the module code, as it should always be available and shouldn't troll CSP

**Comment by rwjblue** [comment]
@stefanpenner - It can be added in the addon's `included` hook (via `app.import` of a generated file).

**Comment by stefanpenner** [comment]
@rwjblue :+1:

**Comment by jakecraige** [comment]
nice, sounds good

**Comment by stefanpenner** [comment]
this should be doable given current addon hooks.
