### ISSUE TITLE
update core-object

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3046]
@jgwhite 0.0.4 of core-object is branched, and now frozen. I have now merged my unfortunately large revamp branded as `benchmarks` https://github.com/ember-cli/core-object/commit/da8f632e20f97db88ffc1499c494d832c4dd7135

highlights:

* `this._super` actually works with multiple depths
* fast (and benchmarks to keep it that way)
* `init` works in a reasonable fashion (feel free to ask me in more detail about this one)
* many tests

what we need to do, is update ember-cli's usage of core-object to match, and fix issues in core-object that arise. Feel free to open issues on core-object, and we can fix quickly. 

Note:  this isn't a backwards compatible update, but it is a much more reasonable foudnation.

**Comment by stefanpenner** [comment]
@jgwhite i have assigned you, per your request https://github.com/ember-cli/blueprint/issues/2#issuecomment-70741790

I will gladly help were you see fit, and don't hesitate to reach out if you have thoughts/questions/concerns/ideas

**Comment by jgwhite** [comment]
:ok_hand:

**Comment by jgwhite** [comment]
I’ve begun to dig into this. Couple thoughts so far:

- Feels like we should strongly advise constructor signature `new Klass({ attr: value })` to avoid confusing Liskov violations in the wild.
- Numerous addons using `this._super.someMethod(...)`. Do we want core-object support both call signatures to ease this transition?

**Comment by stefanpenner** [comment]
> Feels like we should strongly advise constructor signature new Klass({ attr: value }) to avoid confusing Liskov violations in the wild.

:+1: 

> Numerous addons using this._super.someMethod(...). Do we want core-object support both call signatures to ease this transition?

I don't think its possible to do this correctly with multiple levels of super.

**Comment by jgwhite** [comment]
PR for reference #3056

**Comment by stefanpenner** [comment]
@jgwhite got any time coming up?
