### ISSUE TITLE
[Feature Request] Record steps in Ember app for use tests

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#3051]
It would be a nice feature to be able to be able to record steps in an app to them be added to an integration test.

For example if I was to click on a button and wait for some stuff to happen it would record this:

```js
test("Checking navigation ",function(){
  expect(1);
  visit('/hub');
  click('#btnLogin');

});

```

and if some some asynchronous stuff was being done it that would have required an andThen in test, it would generate a new block of actions.

**Comment by stefanpenner** [comment]
Cool idea, but this would be the place of an addon.  I am closing this as it is not an issue, but feel free to continue the discussion

**Comment by QuantumInformation** [comment]
Cool, I could create a repo for this addon and then ask for some guidence from the community, if this would be a poular thing.

**Comment by jakecraige** [comment]
This sounds like an awesome idea. I would definitely be interested

**Comment by QuantumInformation** [comment]
It would be tricky to write handler to catch events for non standard inputs, eg select2. Perhaps we could find listeners used for recording in other frameworks, perhaps selenium.

**Comment by joostdevries** [comment]
:heart_eyes:

**Comment by jakecraige** [comment]
I would probably start by keeping it simple. Use standard inputs for now, add that stuff later. MVP it

The user can manually select that stuff in their test for now if they must.

**Comment by QuantumInformation** [comment]
So should we add a custom mouse click handler to the page and output to console for a start. How do we integrate this into an ember app?

**Comment by jakecraige** [comment]
Since we'd probably want it in an ember environment at some point. You could probably set up a service that binds to the events and handles whatever it needs to do

**Comment by QuantumInformation** [comment]
I suppose if we assume that any button click triggers a UI action when a tester is testing we could just record that. I suppose after each button click we should record inside a new ```andThen``` block.

**Comment by QuantumInformation** [comment]
OK, I'll create a repo called ember-cli-test-recorder unless anyone has another preference.

**Comment by QuantumInformation** [comment]
I've created a repo and will generate an addon with the CLI, over the weekend.

https://github.com/QuantumInformation/ember-cli-test-recorder

Feel free to help me get started if you have any experience with this sort of addon.

**Comment by QuantumInformation** [comment]
I'm planning inject some code into one of the content-for blocks in a CLI app using this addon. This will show a div with record start+stop buttons and a mini console with the record statements.

**Comment by QuantumInformation** [comment]
So atm I've put the record steps in a component that listens to button clicks, and would now like to record final route changes and perform diffs on visual changes (such as elements disappearing/appearing). I will try do this in the component if possible.
