### ISSUE TITLE
Improved labels:

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3055]
@wagenet has come up with a good set of labels for ember proper, i think we should  consider using them as well https://gist.github.com/wagenet/2be9abdafb9ba8f9f8fb

@team thoughts?

**Comment by Mawaheb** [comment]
Is there any chance of using "Good for new contributors" label as well ? ;)

**Comment by stefanpenner** [comment]
@Mawaheb ah, that is a good one! ping @wagenet

**Comment by jakecraige** [comment]
Looks good to me. I like how they all have real meaning behind them. Something someone could act on

**Comment by wagenet** [comment]
I just updated my list with more detail: https://gist.github.com/wagenet/2be9abdafb9ba8f9f8fb.
