### ISSUE TITLE
DS.FixtureAdapter not loading fixtures using ember-cli w/ ember-data

### ISSUE THREAD

**Issue by jsalva** [ember-cli/ember-cli#3057]
Hi,

It seems my ember-cli app isn't using fixtures after using the FixtureAdapter in adapters/application.js and adapters/campaign.js

Adding a console.log() statement never executes in the adapters after compiling.

Is there something I'm missing? Why are the adapters not being used?

```javascript
//adapters/campaign.js
import DS from 'ember-data';
console.log('in adapters/campaign.js');
export default DS.FixtureAdapter.extend({});


// models/campaign.js (should have fixtures loaded...)
import DS from "ember-data";

var Campaign = DS.Model.extend({
  name: DS.attr('string'),
  isComplete: DS.attr('boolean')
});

Campaign.reopenClass({
  FIXTURES: [{id: 0,
    name: "item1",
    isComplete: false},
    {id: 1,
    name: "Item2",
    isComplete: false}]});

export default Campaign;

//routes/campaigns.js
import Ember from 'ember';

var CampaignsRoute = Ember.Route.extend({
  model: function(){
    return this.store.all('campaign');
  }})

export default CampaignsRoute;

//appname.js (post-"ember build") & seems compiled...
define("appname/adapters/application",
  ["ember-data","exports"],
  function(__dependency1__, __exports__) {
    "use strict";
    var DS = __dependency1__["default"];
    console.log("in adapters/application.js");
    __exports__["default"] = DS.FixtureAdapter.extend({});
  });
define("appname/adapters/campaign",
  ["ember-data","exports"],
  function(__dependency1__, __exports__) {
    "use strict";
    var DS = __dependency1__["default"];

    console.log("in adapters/campaign.js");

    __exports__["default"] = DS.FixtureAdapter.extend({});
  });
...


```

The ember inspector shows the store is empty and fixtures don't seem to be loaded at all, despite declaring the Application and 'campaign' adapter to be fixture adapters...

Any help would be appreciated. Thanks everyone

--------------------------------------------------------------------------------------------------------------------------------------------
Potentially relevant? Maybe not?:

app directory structure
.
├── adapters
│   ├── application.js
│   └── campaign.js
├── app.js
├── components
├── controllers
│   ├── campaigns
│   │   ├── index.js
├── helpers
├── index.html
├── models
│   └── campaign.js
├── router.js
├── routes
│   ├── campaigns.js
├── styles
│   └── app.css
├── templates
│   ├── application.hbs
│   ├── campaigns
│   │   ├── index.hbs
│   ├── campaigns.hbs
│   ├── components
│   ├── index.hbs
└── views

```javascript
//bower.json
{
  "name": "appname",
  "dependencies": {
    "handlebars": "~1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-resolver": "~0.1.11",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0"
  }
}

//Brocfile.json
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();


// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

module.exports = app.toTree();


//package.json
{
  "name": "appname",
  "version": "0.0.0",
  "description": "description",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "ember-cli": "0.1.7",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "1.0.0-beta.14.1",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}

```

**Comment by jsalva** [comment]
also, I'm using ember-cli 0.1.7

**Comment by jsalva** [comment]
And relevant directory structure inside app/

.
├── adapters
│   ├── application.js
│   └── campaign.js
├── app.js
├── components
│   ├── card-select.js
│   ├── check-box.js
│   ├── dropdown-button.js
│   ├── flatly-radio-button.js
│   ├── radio-button.js
│   └── text-field.js
├── controllers
│   ├── campaign.js
│   ├── campaigns
│   │   ├── index.js
│   │   ├── new
│   │   │   ├── confirm.js
│   │   │   ├── design.js
│   │   │   ├── recipients.js
│   │   │   ├── setup.js
│   │   │   └── template.js
│   │   └── new.js
│   ├── list.js
│   └── lists.js
├── helpers
├── index.html
├── models
│   └── campaign.js
├── router.js
├── routes
│   ├── campaign.js
│   ├── campaigns
│   │   ├── new
│   │   │   ├── recipients.js
│   │   │   ├── setup.js
│   │   │   └── template.js
│   │   └── new.js
│   ├── campaigns.js
│   └── lists.js
├── styles
│   └── app.css
├── templates
│   ├── application.hbs
│   ├── automation.hbs
│   ├── campaign
│   │   ├── edit.hbs
│   │   ├── index.hbs
│   │   └── report.hbs
│   ├── campaigns
│   │   ├── index.hbs
│   │   ├── new
│   │   │   ├── design.hbs
│   │   │   ├── recipients.hbs
│   │   │   ├── setup.hbs
│   │   │   └── template.hbs
│   │   └── new.hbs
│   ├── campaigns.hbs
│   ├── components
│   │   ├── card-select.hbs
│   │   ├── check-box.hbs
│   │   ├── dropdown-button.hbs
│   │   ├── flatly-radio-button.hbs
│   │   └── text-field.hbs
│   ├── index.hbs
│   ├── lists.hbs
│   ├── reports.hbs
│   └── templates.hbs
└── views

**Comment by jsalva** [comment]
hmm.. seems the adapters are being built, just never used to load fixtures...

```javascript
//application-name.js (post-broccoli) seems compiled...
define("quailmail/adapters/application",
  ["ember-data","exports"],
  function(__dependency1__, __exports__) {
    "use strict";
    var DS = __dependency1__["default"];
    console.log("in adapters/application.js");
    __exports__["default"] = DS.FixtureAdapter.extend({});
  });
define("quailmail/adapters/campaign",
  ["ember-data","exports"],
  function(__dependency1__, __exports__) {
    "use strict";
    var DS = __dependency1__["default"];

    console.log("in adapters/campaign.js");

    __exports__["default"] = DS.FixtureAdapter.extend({});
  });
...

//adapters/campaign.js
import DS from 'ember-data';
console.log('in adapters/campaign.js');
export default DS.FixtureAdapter.extend({});


// models/campaign.js (should have fixtures loaded...)
import DS from "ember-data";

var Campaign = DS.Model.extend({
  name: DS.attr('string'),
  isComplete: DS.attr('boolean')
});

Campaign.reopenClass({
  FIXTURES: [{id: 0,
    name: "item1",
    isComplete: false},
    {id: 1,
    name: "Item2",
    isComplete: false}]});

export default Campaign;

//routes/campaigns.js
import Ember from 'ember';

var CampaignsRoute = Ember.Route.extend({
  model: function(){
    return this.store.all('campaign');
  }})

export default CampaignsRoute;
```

The ember inspector shows the store is empty and fixtures don't seem to be loaded at all, despite declaring the Application and 'campaign' adapter to be fixture adapters...

Any help would be appreciated. Thanks everyone

**Comment by jsalva** [comment]
updates:

This worked with .find() in the route but and not with .all();
The console.log statements still never logged (not 100% why not).

**Comment by sio4** [comment]
as I know, all() and find() are different. all() returns data from POPULATED store but find() will populate it by it self then returns.
