### ISSUE TITLE
Custom location API breaks server-side routing

### ISSUE THREAD

**Issue by rafalp** [ember-cli/ember-cli#3061]
I'm using custom location API that extends HistoryLocation and adds trailing slash to ember urls:

https://github.com/rafalp/Misago/blob/master/misago/emberapp/app/initializers/trailing-slash.js

However this breaks `ember serve` server-side routing behaviour.

For example, when I go to `localhost:4200/privacy-policy/`via `link-to`, it works. When I change something in files, autoreload makes page refresh, producing `Can't serve GET /privacy-policy/` error.

When I keep default location setting, `auto`, boot ember server and then change setting to my location API, then it is used and page refreshes successfully load index.html and let ember.js app handle routing for me.

I am using Ember 1.10 Beta 4 and Ember Data Beta 14 and Ember CLI 0.1.7:
https://github.com/rafalp/Misago/blob/master/misago/emberapp/bower.json
https://github.com/rafalp/Misago/blob/master/misago/emberapp/package.json

**Comment by joostdevries** [comment]
This is not a bug with Ember CLI but default behavior from the Express server. You can modify this by adding additional middleware like [express-slash](https://github.com/ericf/express-slash).

**Comment by rafalp** [comment]
I see, thank you for your time and explanations.
