### ISSUE TITLE
Cannot read property 'dasherize' of undefined - On fresh install

### ISSUE THREAD

**Issue by Ghosh** [ember-cli/ember-cli#3062]
I created a new ember project, upon doing `ember serve` i just see an empty page with the following in the console
```
Uncaught TypeError: Cannot read property 'dasherize' of undefined
```

The error corresponds to the following line in `vendor.js`
```
return split[0] + ':' + Ember.String.dasherize(split[1].replace(/\./g, '/'));
```

**Comment by stefanpenner** [comment]
What version of ember
What version of node
What version of npm 
What os

**Comment by Ghosh** [comment]
Oh sorry, should have added that too:-

Ember - v0.1.7
Node - v0.10.35
NPM - v2.1.8

I also get `Could not find watchman, falling back to NodeWatcher for file system events` and I installed node through NVM

**Comment by stefanpenner** [comment]
> I also get Could not find watchman, falling back to NodeWatcher for file system events

thats fine, watchman is optional

**Comment by stefanpenner** [comment]
@ghosh me and CI can't replicate, i suspect your cache or node_modules is borked

try

```
npm cache clear
rm -rf node_modules
npm install
```

**Comment by Ghosh** [comment]
Thank you for reply so quickly. Unfortunately..it's still not working. Here are some more stats just in case..
The ember version is - 1.1.8
The handlebars is - 1.3.0
The jQuery is - 1.11.2

![screen shot 2015-01-22 at 11 41 46 pm](https://cloud.githubusercontent.com/assets/4667682/5861539/4a15b57c-a290-11e4-8be8-d9bbb6991a8a.png)

**Comment by stefanpenner** [comment]
oh the issue is client-side, i assumed server-side.

Something is still funky, i cannot replicate and CI runs this and it also doesn't replicate.

I am seeing a pretty slow build time,  are you sure this is fresh project?

**Comment by Ghosh** [comment]
@stefanpenner Yes..I am create a new project with `ember new <project-name>` and then cd into it and run 'ember-serve'. It just keeps showing a blank screen with the error mentioned above.

Also the terminal just shows that much..as in the ES6Modules is the one and only item for which the time is being shown..there is nothing after it.

**Comment by stefanpenner** [comment]
i've seen others recently with this, i wonder if something is watching your tmp dir, dropbox?backup? encryption? your editor?

**Comment by Ghosh** [comment]
umm..ok. I'm not really sure of what I should do now. Please let me know if you have something in mind. Thanks.

**Comment by Ghosh** [comment]
@stefanpenner So this seems to be a problem only when the project folder is called `Ember`. I changed the folder name and its working now.

**Comment by stefanpenner** [comment]
ah, we should likely add `ember` to the application name blacklist

**Comment by stefanpenner** [comment]
interestingly it already is... https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/valid-project-name.js#L4

**Comment by stefanpenner** [comment]
```js
% ember new ember
version: 0.1.9
We currently do not support a name of `ember`.
```

**Comment by jgwhite** [comment]
@stefanpenner we don’t protect against `ember new Ember` though…

**Comment by stefanpenner** [comment]
@jgwhite ahh good catch, we should toLower that check
