### ISSUE TITLE
Error while processing route on IE8.

### ISSUE THREAD

**Issue by luiskhernandez** [ember-cli/ember-cli#3065]
i am using

ember: 1.8.1
ember data: 1.0.0-beta.12
ember-cli : 0.1.7

```javascript
OfferRoute = Ember.Route.extend
  model: (params)->
    @store.find('offer',params.offer_id)
```

it works fine on Chrome but on IE8 i get "Error while processing route"

I think the issue is with the ```@store```because if i use a json object instead of ```@store.find´´´work fine. Maybe something related with IE8 and js promises?

**Comment by stefanpenner** [comment]
Sorry doesn't seem like an ember-cli issue, I would recommend opening a stack-overflow post. My apologies, if we had more time we would gladly help with non-ember-cli bugs.
