### ISSUE TITLE
should be able to re-blueprint an addon

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3067]
```sh
ember init // should re-blueprint the add-on
```

i would also settle for

```sh
ember addon // should re-blueprint the add-on
```

**Comment by jakecraige** [comment]
related to #2544 I think?

**Comment by rwjblue** [comment]
ember init should work actually. 

@stefanpenner - Did you try that and get an error?

**Comment by stefanpenner** [comment]
@rwjblue it just does not blueprint everthing.

```
ember addon foo
rm -rf foo/app
rm -rf foo/addon/

cd foo
ember init
```

app and addon are not re-created

**Comment by bcardarella** [comment]
strange

**Comment by rwjblue** [comment]
I do not think that `.gitkeep` files will be recreated after initial blueprinting. `app` and `addon` only contain a `.gitkeep` file in the blueprint.

**Comment by rwjblue** [comment]
That is done here: https://github.com/ember-cli/ember-cli/blob/42daf4d72f5ad134e71364243f10c865b2aae43f/lib/models/blueprint.js#L1152-L1155
