### ISSUE TITLE
ES6 Module Import Regression: Can only import a module once.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3078]
Issue reported upstream: https://github.com/esperantojs/esperanto/issues/63

Currently, the following:

```javascript
import foo from "foo";
import { bar } from "foo";

foo.stuff();
bar.otherStuff()
```

Will result in the following output (using single module + strict mode):

```javascript
define(['foo', 'foo'], function (foo, foo) {

    'use strict';

    foo['default'].stuff();
    foo.bar.otherStuff()

});
```

This throws an error as we have two function arguments with the same name.

----

Opening an issue here, as any users that test the recently release 0.1.8 may hit this bug.

/cc @Rich-Harris @stefanpenner

**Comment by stefanpenner** [comment]
word on the street is a fix is current in progress, hopefully we will get it out asap.

**Comment by zeppelin** [comment]
@rwjblue confirmed, i did hit this bug

**Comment by Rich-Harris** [comment]
Just published esperanto 0.6.4 which fixes this issue

**Comment by cowboyd** [comment]
No longer relevant, but the workaround would be `import foo, { bar } from "foo";`, no?

**Comment by jgwhite** [comment]
Excellent. Thanks @Rich-Harris!

For anyone who hits this issue, running the following will get you up on the latest esperanto:

```sh
rm -rf node_modules
npm cache clean
npm install
```

**Comment by kmkamruzzaman** [comment]
Happy!!!
