### ISSUE TITLE
App JSHint runs on addons' `test-support` folders

### ISSUE THREAD

**Issue by zeppelin** [ember-cli/ember-cli#3083]
When `EmberApp` [creates the `jshintedTests` tree from the `tests` tree](https://github.com/ember-cli/ember-cli/blob/05e1117df1faebf15afa2a134494da3db1405e27/lib/broccoli/ember-app.js#L704), the addons' `test-support` folders are [already merged in](https://github.com/ember-cli/ember-cli/blob/05e1117df1faebf15afa2a134494da3db1405e27/lib/broccoli/ember-app.js#L522-L523).

This can lead to failing tests when an addon is either accidentally published with failng jshint tests, or has a different jshint config than the host app.

**Comment by rwjblue** [comment]
Agreed.   We should only be hinting app tests, not addon tests.

**Comment by rwjblue** [comment]
Will be fixed with https://github.com/ember-cli/ember-cli/pull/3086.

**Comment by zeppelin** [comment]
@rwjblue ah, was just about submitting the same patch :)

Got time to work on #2359? No rush, just thought I mention it here, since the issue is somewhat similar: app-addon files are merged in before broccoli-jscs (used as an ember-addon) runs on the app tree.
