### ISSUE TITLE
Error: EISDIR, illegal operation on a directory after updating to the latest version of ember-cli

### ISSUE THREAD

**Issue by hiromipaw** [ember-cli/ember-cli#3087]
Hello,
I have just updated to the latest version of ember-cli and now, either when I try to run ember init on a old project or I try to create a new ember app, or I just try to execute ember -v, I run into the following error:

    $ ember install
        fs.js:488
        var r = binding.read(fd, buffer, offset, length, position);
                  ^
        Error: EISDIR, illegal operation on a directory
            at Object.fs.readSync (fs.js:488:19)
            at Object.fs.readFileSync (fs.js:322:28)
            at readFile (/Users/hiromi/Documents/workspace/walks/node_modules/ember-cli/node_modules/yam/lib/utils/io-utils.js:19:21)
            at new Config (/Users/hiromi/Documents/workspace/walks/node_modules/ember-cli/node_modules/yam/lib/config.js:15:12)
            at new Yam (/Users/hiromi/Documents/workspace/walks/node_modules/ember-cli/node_modules/yam/lib/yam.js:37:5)
            at cli (/Users/hiromi/Documents/workspace/walks/node_modules/ember-cli/lib/cli/index.js:40:16)
            at /usr/local/lib/node_modules/ember-cli/bin/ember:26:3
            at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:48:21
            at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:127:35
            at /usr/local/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:99:39

I am on Mac OSX Yosemite 10.10.1.

    npm --version
    1.4.28

    node --version
    v0.10.35

**Comment by joostdevries** [comment]
@hiromipaw Have you tried `rm -rf node_modules && npm cache clean && npm install` in your project root?

**Comment by hiromipaw** [comment]
Yep, but let me try it again. The thing is that I get the same error even if I try to create a new app in a different directory.

**Comment by stefanpenner** [comment]
> npm --version
> 1.4.28

we don't support npm this old (it is riddled with bugs), please upgrade to  `>= 2.2.x`, clear the cache and remove the node_modules

**Comment by hiromipaw** [comment]
Sorry about npm. I had uninstalled node completely earlier today, and reinstalled it from the package and went into the assumption that it should have installed also the latest version of npm.
Now I am running on:

   npm -v
   2.3.0

Removed everything to reinstall ember-cli as per: https://github.com/ember-cli/ember-cli/releases
Tried to run again
    rm -rf node_modules && npm cache clean && npm install

But I still get the same problem.

**Comment by stefanpenner** [comment]
> Sorry about npm. I had uninstalled node completely earlier today, and reinstalled it from the package and went into the assumption that it should have installed also the latest version of npm.
> Now I am running on:

not your fault.

@twokul any ideas, it appears to origin in yam. You may quickly notice the issue

**Comment by twokul** [comment]
@stefanpenner looking

**Comment by twokul** [comment]
@hiromipaw hm, it seems to be working for me :confused: do you have `.ember-cli` files under home directory or in your existing project? `ember -v` definitely works for me. @stefanpenner dude, do you mind double checking if `ember -v` and `ember new` work for you?

**Comment by hiromipaw** [comment]
@twokul thanks for looking into this. I have a <code>.ember-cli</code> folder both in my home and in the project folder...

**Comment by stefanpenner** [comment]
> @stefanpenner dude, do you mind double checking if ember -v and ember new work for you?

yes it works for me

**Comment by twokul** [comment]
@hiromipaw I'm gonna try running it again with `.ember-cli` files. currently at the airport so might take 2-3 hours before I get back to you

**Comment by twokul** [comment]
@hiromipaw can you paste the contents of your `.ember-cli` files here? `Error: EISDIR` means that the target of the operation (read) is a directory.

**Comment by hiromipaw** [comment]
Sure. Will update tonight. Thanks for helping out with this.

**Comment by hiromipaw** [comment]
Sorry for being late with this.

.ember-cli in project folder:

    {
      /**
        Ember CLI sends analytics information by default. The data is completely
        anonymous, but there are times when you might want to disable this behavior.
    
        Setting `disableAnalytics` to true will prevent any data from being sent.
      */
      "disableAnalytics": false,
      "liveReload" : true,
      "environment" : "mock-development"
    }

.ember-cli in home folder:

    $ ls .ember-cli/
    ARCHITECTURE.md	LICENSE.md	appveyor.yml	dev		node_modules
    CHANGELOG.md	README.md	bin		fixtures	package.json
    CONTRIBUTING.md	RELEASE.md	blueprints	lib		tests

**Comment by hiromipaw** [comment]
Ok :) so I have now deleted the .ember-cli folder in my home directory. Followed the procedure again from: https://github.com/ember-cli/ember-cli/releases and it is now working again.

**Comment by krisselden** [comment]
@twokul did yam switch how stuff was stored from being a directory in one version to a file?

**Comment by hiromipaw** [comment]
I have to add that I had not updated this project for a long time and was created with one of the very first versions of ember-cli.

**Comment by stefanpenner** [comment]
> @twokul did yam switch how stuff was stored from being a directory in one version to a file?

i think it was always a file

**Comment by twokul** [comment]
@krisselden it didn't. agreed that it should check, I'll try to find time this weekend to update yam

**Comment by twokul** [comment]
upstream fix in [yam](https://github.com/twokul/yam/pull/9)

**Comment by knasim** [comment]
was there any solution to this problem ?

**Comment by RichardSilveira** [comment]
@knasim : So, let me check something, should i uninstall npm an reinstall it as my current user?

**Comment by knasim** [comment]
@RichardSilveira  yes i would def. give that a whirl.

**Comment by muzishuiji** [comment]
But I still getting the same problem.

**Comment by sleeparrow** [comment]
to people getting here from google:
blowing away my `~/.pnpm-store` fixed it for me.

(sorry ember-cli guys i'm not even using ember-cli; you're just a top result)
