### ISSUE TITLE
[IDEA] Alias `ember g partial xxx` to `ember g template xxx`

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3089]
I think symlinking/aliasing of `ember g partial xxx` to `ember g template xxx` would be a good idea, because it would improve developer workflow. You think of a partial when you think about it's purpose and want generate template for it. I think it would be more intuitive just to use `ember g partial`.
Or another idea for this is to let ember-cli user specify default directory for partial templates(or use convention over configuration and specify default directory to `partial/`) so `ember g partial xxx` would run like:
`ember g template partial/xxx`.
Downside of second approach is that people might forget to use partial/ before partial template name in partial helper.

**Comment by stefanpenner** [comment]
seems interesting

@jgwhite  thoughts?

**Comment by jgwhite** [comment]
I’m not a big user of partials personally but would welcome a new blueprint for partial generation. @Kuzirashi are you interested in submitting a PR so we can bikeshed this idea a little more?

**Comment by Kuzirashi** [comment]
@jgwhite I'm interested. It would be a pleasure to try to help.

**Comment by rwjblue** [comment]
@Kuzirashi - Considering the future of Ember ([read more here](https://github.com/emberjs/rfcs/pull/15)), I believe that partials will be deprecated (and potentially removed).  I would prefer not to add generation of something that we may be deprecating (eg: it helps our users upgrade a bit easier if they don't have partials).

**Comment by jgwhite** [comment]
In light of @rwjblue’s comments, can I suggest an alternative contribution:

Add a friendly warning when we detect partials being generated. Something like:

```
It looks you’re generating a partial. Have you considered using a component instead?
```

Perhaps with a link to the RFC.

This opens the question of *how* exactly we detect when folks are generating partials. @Kuzirashi it seems like you’re well placed to answer this.

**Comment by Kuzirashi** [comment]
@rwjblue Ok, I agree. That's why I'm not using Array and Object controller now. Didn't know partials are part of stuff that will be dropped in the future.

@jgwhite But if we place link then people should easily find part of site where they can read about partials being deprecated. I'm using searching for `partial` here - https://github.com/emberjs/rfcs/pull/15 . And I can't find anything that will tell me more about it.

**Comment by jgwhite** [comment]
@rwjblue maybe time this is raised in the RFC thread?

**Comment by rwjblue** [comment]
@jgwhite - Ya, agreed.

**Comment by jgwhite** [comment]
@Kuzirashi thank you for prompting this discussion.

If consensus if reached that partials are to be deprecated/discouraged then we’ll revisit the idea of adding a friendly warning.

@Kuzirashi are you happy for me to close this issue?

**Comment by Kuzirashi** [comment]
Yes. Seems like I should re-think using partials in my app...
