### ISSUE TITLE
I can't find any docs on Cross Domain policy

### ISSUE THREAD

**Issue by mgenev** [ember-cli/ember-cli#3090]
I see an xml file in the public folder but it seems to have no effect when I uncomment the section that says "most permissive policy".

When I try to use Ember.$.ajax and follow the jQuery docs on how to enable cors, my requests still don't contain the headers which jQuery is meant to be setting and it doesn't work.

I seem to remember that in the past there was a part of ember-cli which enabled cors. How can I do it currently?

**Comment by hhff** [comment]
check [this](https://github.com/rwjblue/ember-cli-content-security-policy) addon @mgenev 

it comes bundled with all new CLI apps - the readme explains how to configure it!

**Comment by mgenev** [comment]
Thanks. OK So it says

```  'connect-src': "'self' https://api.mixpanel.com http://custom-api.local", ```

I set 
``` 'connect-src': "'self' https://maps.googleapis.com",``` 
and my request to ```https://maps.googleapis.com/maps/api/place/nearbysearch/json? ```
still gets shut down for ``` No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.```

**Comment by mgenev** [comment]
I also always get this:
```
The Content Security Policy 'default-src *; font-src *; connect-src 'self' https://maps.googleapis.com ws://localhost:35729 ws://0.0.0.0:35729; img-src *; style-src *; frame-src *; script-src 'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729; media-src 'self';' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
```

**Comment by stefanpenner** [comment]
@mgenev unfortunately that is a bug in google maps, they aren't CSP compliant :(

**Comment by mgenev** [comment]
@stefanpenner Thanks for the clarity. I will do that. I tried so many things with jQuery's CORS options and CSP and nothing works with that API. 

At this point my only other option is to use their js lib for connecting to their API and that better work.

**Comment by stefanpenner** [comment]
@mgenev we have docs

* http://www.ember-cli.com/#content-security-policy
* http://www.ember-cli.com/#deploy-content-security-policy
* https://github.com/rwjblue/ember-cli-content-security-policy

**Comment by mgenev** [comment]
Doh, you're right, I was searching for "cross" and "domain"

**Comment by stefanpenner** [comment]
@mgenev no problem, we are slowing re-working the site to be slightly more digestable, the current one has grown quite a bit so its hard to track stuff down.
