### ISSUE TITLE
Intent to support ESLint

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3091]
Mostly as a question, ESLint allows a much more granular control than JSHint, once they support all ECMA 6 features that ember-cli supports out of the box is there any intent to switch over?

Resources
- Features required to get full ECMA 6 https://github.com/eslint/eslint/labels/es6jsx
- Rules:
    - JSHint http://jshint.com/docs/options/
    - ESLint http://eslint.org/docs/rules/

Yes it's slower, however I believe the flexibility on having a defined strict ember-cli set of rules/plugins is worth it.

I actually ESLint having the ability for plugins will give a cleaner set of native tests for what is best practice in ember-cli also.

**Comment by stefanpenner** [comment]
> Yes it's slower,

how much slower?

**Comment by stefanpenner** [comment]
> Mostly as a question, ESLint allows a much more granular control than JSHint, once they support all ECMA 6 features that ember-cli supports out of the box is there any intent to switch over?

I believe it and jshint being and addon is appropriate.

**Comment by jonathanKingston** [comment]
>> Yes it's slower,

>how much slower?

ESLint states it's around 2-3 times slower however it depends on the rules chosen; that notice is also a little older; I know the internal parser has changed since then in aid of making it faster.

Can the checking be done post build instead perhaps? (So the application can be served then checked - if the difference is noticable)

**Comment by jonathanKingston** [comment]
Perhaps an ESLint npm for support to swap out the JSHint checks to ESLint might be a better direction?

**Comment by chadhietala** [comment]
I would lean towards plugability.  You're going to incur parse and traversal time.  If you're doing SA in other parts of the build, it's probably best to parse once and passing the AST along until all SA is done.

**Comment by jonathanKingston** [comment]
@chadhietala ESLint uses Espree which is its own fork of Esprima. Surely for reliability depending on / injecting a different AST output into a package is not a good idea?

JSHint doesn't use AST though does it (It was listed as one of the benefits to ESLint - I have not worked with JSHint enough to know)? If that's the case then it's likely not to make much of a performance hit.

However I do think it could be beneficial to lint after serving to reduce the time it takes live update.

I had a quick look at the steps ember-cli takes and it looks like it could be made pluggable to use either package fairly simply.

**Comment by chadhietala** [comment]
Looks like linting will be plugable. https://github.com/ember-cli/ember-cli/pull/3094

**Comment by jonathanKingston** [comment]
Just saw that :+1: - I suspect the work then would be to make the JSHint linting a npm in its own right (which could be installed by default).

**Comment by twokul** [comment]
I'm gonna close this in favour of #3094.
