### ISSUE TITLE
Resource blueprint does not use custom test generators

### ISSUE THREAD

**Issue by jluckyiv** [ember-cli/ember-cli#3095]
Using `ember generate resource foo` fires the **ember-cli** test generators instead of custom test generators. I have created a [demo](https://github.com/jluckyiv/ember-cli-mocha-resource-generator) here, using [ember-cli-mocha](https://github.com/switchfly/ember-cli-mocha). This issue has been [reported in that project](https://github.com/switchfly/ember-cli-mocha/issues/23), but I think it correctly states that the issue is with **ember-cli**'s handling of the resource blueprint.

In the demo, the `name-model` class and route were generated with `ember g model` and `ember g route`, and correctly generated the model and route tests with the custom generator. The `name-resource` class was generated with `ember g resource`, and incorrectly generated the model and route tests with the default generators.

I am working on a pull request with a failing test. I will link to it when it's complete. I'm going to try to make the test pass on my own, but my JavaScript skills probably aren't up to snuff.

**Comment by bcardarella** [comment]
This is likely due to this function: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1023-L1027 trying to lookup the blueprint name: https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L29

**Comment by jluckyiv** [comment]
Thanks @bcardarella. I'll try to reason my way through those areas to figure out how to point toward custom generators. This is deep diving for me, but I'll give it a shot.

**Comment by bcardarella** [comment]
@jluckyiv I'm just guessing but it seems that there might be a relative path lookup issue here, instead of finding the ember-cli-mocha blueprint.

**Comment by jluckyiv** [comment]
@bcardarella I think I fixed it. My tests are passing. I'm going to do a PR (my first).

**Comment by bcardarella** [comment]
@jluckyiv awesome!

**Comment by jluckyiv** [comment]
@bcardarella Thanks for the pointers and encouragement.
