### ISSUE TITLE
Editor settings for WebStorm

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#3097]
Something for the editors section of the ember-cli website.

In order to configure WebStorm for use with ember-cli, see below.

`File > Settings > Languages & Frameworks > JavaScript > ECMAScript6`

Right mouse on the following directories and mark accordingly.

Mark as `excluded`:
* /tmp

Mark as `resource route`:
* /
* /bower_components
* /bower_components/ember-qunit/lib
* /public

Mark as `test sources root`:
* /tests

Add the following line to `.gitignore`
```
.idea
```

**Comment by Kuzirashi** [comment]
This would be more suitable for `.gitignore` - https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by twokul** [comment]
@kgish do you mind submitting a PR to the website's `Editors` section?

**Comment by stefanpenner** [comment]
for reference, the website repo is a branch of this one and resides at https://github.com/ember-cli/ember-cli/tree/gh-pages

**Comment by jluckyiv** [comment]
I've made the suggested changes and submitted a PR. Caveat: I have no experience with WebStorm, so it's a copy-and-paste job, with formatting.

**Comment by twokul** [comment]
@jluckyiv commented

**Comment by kgish** [comment]
Where's the ember-cli website kept?

For future reference so I can make pull requests myself from now on.

**Comment by wayne-o** [comment]
Read previous messages, it's a branch on the main repo

On Monday, 26 January 2015, Kiffin Gish <notifications@github.com> wrote:

> Where's the ember-cli website kept?
>
> For future reference so I can make pull requests myself from now on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3097#issuecomment-71427494>
> .
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by stefanpenner** [comment]
@kgish https://github.com/ember-cli/ember-cli/tree/gh-pages

**Comment by kgish** [comment]
Thanks.

**Comment by jluckyiv** [comment]
@kgish I'm dumb, so I go straight to the website and click on the pencil icon, which gives an idiot-proof way to patch the repo and submit a PR.

**Comment by kgish** [comment]
@jluckyiv Perhaps idiot proof, but I still prefer to test my changes before submitting a PR.
