### ISSUE TITLE
[Proposal] Better early warning on dependency management

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#3107]
Standard caveats:
- probably not strictly an ember cli concern
- pre release dev cycle is fast and dependencies move quickly, not 1.0 yet
- etc...

But... can we as a community figure out a better way on the dependency management "dll hell"?

Concrete example, last night I upgraded Ember CLI 0.1.9, boom some breakage with liquid-fire. Find the git issue real quick learn there is something up with esperanto module compiler compatibility.

https://github.com/ef4/liquid-fire/issues/165

Not a knock on either project, both great projects, but wondering if there is something that can be done to address these pain points? As the add-on ecosystem grows this is only going to get more complex and dependency management more onerous.

#### Proposal: Federate add-on examples, and integrate with travis or CI to provide early warning of dependency breakage.

- Encourage add-on developers to submit minimalist ember cli example app using their add-on, and potentially relevant and related add-ons. 
- Submit  example to centralized repos that track with Ember CLI releases and some continuous integration process.
- Provide dashboard that gives heads up when a dependency breaks.

Pros:
- Provides visibility to ember cli contributors and core team how breaking a change can be
- Provides visibility to add-on developers when something upstream causes their add-on to break
- Provides users with specific visibility into potential trouble spots and potentially avoid tricky ugrade

Cons:
- Someone has to maintain this
- Will never be comprehensive
- Herding cats is hard. 

While I don't expect this to be something that the core needs to tackle directly, I believe that add-on quality and stability of the overall ecosystem benefits everybody. So if there is some basic infrastructure that core team can setup to facilitate the above that would be awesome. Maybe something like the above already exists.

**Comment by bcardarella** [comment]
@eccegordo this should go in [rfcs](https://github.com/ember-cli/rfcs)

**Comment by stefanpenner** [comment]
RFC
