### ISSUE TITLE
CORS issue with http-mocks

### ISSUE THREAD

**Issue by christophermlne** [ember-cli/ember-cli#3109]
I am trying to use http-mock to replace fixtures and getting the same error I believe anyone else would get when trying to use this for the first time. (I have no experience with ExpressJS outside of EmberCLI)

So far, I've set the content security policy settings in environment.js:

```javascript
if (environment === 'development') {
    ...
    ENV.contentSecurityPolicy = {
      'default-src': "'self' http://localhost:4200",
      'connect-src': "'self' http://localhost:4200 http:localhost:35729"
    }
  }
```

and in my route I am requesting the resource like this:

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    var artistObjects = [];
    Ember.$.getJSON('http://localhost:4200/api/artists', function(artists) {
      artists.forEach(function(data){
        artistObjects.pushObject(Ember.Artist.createRecord(data));
      });
    });
    return artistObjects;
  }
});

```

But I am still getting this error:
```
XMLHttpRequest cannot load http://localhost:4200/api/artists. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:4200' is therefore not allowed access.
```

Suspecting I needed to adjust some settings on the Express server, I googled for an embarassingly long time and eventually found an npm package called 'ember-cli-cors' (which doesn't work or have any docs). examining the source code, I found:
```javascript
module.exports = {
  name: 'ember-cli-cors',

  config: function(environment /*, appConfig */) {
    return {};
  },

  serverMiddleware: function(config) {
    config.app.use(function(req, res, next) {
      res.setHeader('Access-Control-Allow-Origin', '*');
      next();
    });
  }
};
```
Where would I add these CORS settings in my app code? How do I configure CORS on the express server and move on with my life? Why doesn't the CLI configure this stuff?

**Comment by christophermlne** [comment]
i found that adding the line
```
res.setHeader('Access-Control-Allow-Origin', '*');
```
to the server/mocks/artists.js file like this fixes the issue:
```
module.exports = function(app) {
  var express = require('express');
  var artistsRouter = express.Router();
  artistsRouter.get('/', function(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.send({"artists":[{
        id: 1,
        name: 'Pearl Jam'
      },{
        id: 2,
        name: 'Bon Jovi'
      },{
        id: 3,
        name: 'Anthrax'
      }]
    });
  });
  app.use('/api/artists', artistsRouter);
};
```

**Comment by stefanpenner** [comment]
what is the host you are navigating to? I suspect if you made the API requests relative to the host rather then including the host your problem will go away


> res.setHeader('Access-Control-Allow-Origin', '*');

this now just bypasses CORs all together, which defeats the point

**Comment by christophermlne** [comment]
hmm well now i'm confused. i removed the line below from server/mocks/artists.js in order to try your suggestion and restarted the server BUT the CORS issue did not reappear as expected.

```
res.setHeader('Access-Control-Allow-Origin', '*');
```

in the meantime i have switch to relative links with no problem.

**Comment by stefanpenner** [comment]
@chriseldredge although the CORs stuff is a pain, i would suggest reading up on it, as the security model in the web aims to protect you and your users. It unfortunately is easy to mitigate it, so be careful and don't hesitate to ask or do the research needed to feel confident.

**Comment by chriseldredge** [comment]
Looks like the wrong `@chris...` got autocompleted?

**Comment by christophermlne** [comment]
@stefanpenner thanks for taking the time to look into my issue

**Comment by stefanpenner** [comment]
@chriseldredge my apologies, @christophermlne was the intended recipient .
