### ISSUE TITLE
locationType 'auto' is not working for production builds.

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#3112]
For production builds,  routes are not working with having the ```locationType``` set to ```'auto'```.

All works fine with development builds but as soon as I build a production build with the ```locationType``` set to ```'auto'``` which is default, the route doesn't work and I can not access any routes except the application route.
When I set back ```locationType``` to ```'hash'``` for a production build,  routes start working.

My environment information is below and
```
version: 0.1.9
node: 0.10.32
npm: 2.1.8
```
I tested this in the following plain ember-cli application with minimal routes / environment.js configured and
You can see my test repo in the following link. https://github.com/vsymguysung/emberCLIV019Test
I am sure you can test this easily by creating an app like the one above.
Thanks.

**Comment by stefanpenner** [comment]
> All works fine with development builds but as soon as I build a production build with the locationType set to 'auto' which is default, the route doesn't work and I can not access any routes except the application route.

i just tried to replicate using your example app, and everything appears to work for me.

What did:

```
git clone https://github.com/vsymguysung/emberCLIV019Test
cd emberCLIV019Test
npm i
bower i
ember s --env production
```

1. navigate to /
2. navigate to /dashboard

both appear to work.

**Comment by vsymguysung** [comment]
I should be more specific on this issue.
Yes, running ```ember s --env production``` works but
it doesn't work when I copy the ```dist``` folder and put it in the ```/Library/WebServer/Documents``` which is my local web server document root in my Mac and try to access ``` localhost/``` or ```localhost/dashboard```.
Have you ever try to put your the dist folder to the local web server and test it?
I must have missed something, any idea appreciated.
Thanks in advance.

**Comment by vsymguysung** [comment]
To be more specific my testing result, when I fist hit ```http://localhost/dashboard```, I got the ```Not Found``` error so  I changed the url to ```http://locahost/#/dashboard``` then I got the dashboard route loaded successfully with the url got changed back to ```http://localhost/dashboard``` automatically.

**Comment by stefanpenner** [comment]
> I must have missed something, any idea appreciated.

yup, with location auto, you must have a server that re-serves the root regardless of the URL served.

**Comment by vsymguysung** [comment]
>you must have a server that re-serves the root regardless of the URL served.

Could you give more explanation on this?
How to make my local web server re-serve the root? I have no idea on this.
Thanks.

**Comment by stefanpenner** [comment]
the webServer must serve index.html for every possible URL your apps serves. If you are using http://discuss.emberjs.com/t/apache-rewrite-rule-for-html5-browser-history-url-bookmarkability/1013

**Comment by vsymguysung** [comment]
This is great answer! now I got it. I missed the point that it actually made a GET request when I hit ```http://localhost/dashboard``` for first time which caused "Not found" error.
Appreciate for your time.

**Comment by stefanpenner** [comment]
> Appreciate for your time.

not a problem, I feel bad for not being able to explain it better  off the bat.
