### ISSUE TITLE
Cannot call method 'slice' of null

### ISSUE THREAD

**Issue by ktei** [ember-cli/ember-cli#3129]
Installed latest ember-cli. Created a new app and ran `ember server`. Got this:
```shell
TypeError: Cannot call method 'slice' of null
    at version (c:\dev\playground\ember\tasker\node_modules\ember-cli-app-versio
n\node_modules\git-repo-version\index.js:15:50)
```
I had a look at the index.js file and found
```javascript
info.sha.slice(0, shaLength || 8);
```
Not sure why sha is null, but I changed it to:
```javascript
(info.sha || '').slice(0, shaLength || 8);
```
This temporarily solves my problem.

Is this a known issue or I missed out something? Thanks

**Comment by joostdevries** [comment]
@ktei This is a problem with git-repo-version. Stef already opened a PR there to fix this problem.

**Comment by joostdevries** [comment]
@ktei out of curiousity: Did you create the new app with ``--skip-git`?

**Comment by cibernox** [comment]
Bugfix is coming, but probably won't land until people in the west coast wake up. 

Just a few hours.

**Comment by ktei** [comment]
@joostdevries Hi, I actually didn't know there is --skip-git option. Good to know that. Thank you.

**Comment by joostdevries** [comment]
@cibernox :+1:
@ktei Did you manually delete the `.git` folder then? Because running the following code works fine for me:

```bash
$ ember new tester
version: 0.1.1
installing
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
$ cd tester/
$ ember serve
version: 0.1.1
Livereload server on port 35729
Serving on http://0.0.0.0:4200

Build successful - 387ms.
```

**Comment by ktei** [comment]
@joostdevries I didn't delete anything. I ran `ember new tasker` and then ran `ember server`, and then got the error straightaway.

**Comment by joostdevries** [comment]
@ktei Hmm I just noticed it's loading the wrong ember-cli version.. hold on..

**Comment by joostdevries** [comment]
@ktei could you run `git log` in your project directory?

**Comment by ktei** [comment]
@joostdevries 
`git log` gives me this:
```
fatal: bad default revision 'HEAD'
```

`ember new test-app` output:
```
$ ember new test-app
version: 0.1.11
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitk
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
```

**Comment by joostdevries** [comment]
@ktei I guess for some reason, git initialization fails on your environment. @stefanpenner as I mentioned in #1369 maybe we should actually log some sort of error message (but not fail the command on it). What do you think.

**Comment by ktei** [comment]
@joostdevries 
It might be so. I'm using Windows 7 at the moment and Git always has some small issues on Windows, to which I'm not surprised. However, it'd be better that if this indeed happens, ember-cli can output some warning message at the end of `ember new` command.

**Comment by jakecraige** [comment]
The new tomster commit message was breaking the initial commit. 

Was just fixed in #3126 and released in 0.1.11 :)

**Comment by igorrKurr** [comment]
Thanks! :+1:

**Comment by medievalspawn** [comment]
Looks like it's been fixed by changing the version of ember-cli-app-version in the package.json file in the project you create, from 0.3.0 to 0.3.1. The patch should be out shortly.

**Comment by jakecraige** [comment]
Thanks for the steps to fix it @medievalspawn :+1:

**Comment by testica** [comment]
@medievalspawn I changed to 0.3.1, and my output is:
`Missing npm packages:`
`Package: ember-cli-app-version`
 ` * Specified: 0.3.0`
 ` * Installed: 0.3.1`
`Run npm install to install missing dependencies. `

**Comment by ktei** [comment]
@testica it means you have an installed that version yet. Run npm install to do that.

**Comment by testica** [comment]
I ran that command but it repair the changes that I made, so 0.3.0 appears again in package.json.

**Comment by medievalspawn** [comment]
All you should have to do is go into the package.json of the project and change it to 0.3.1 then go back to the proj directory and run npm install and it should tell you that it did the update. It's all I had to do.

**Comment by rwjblue** [comment]
Yes, @medievalspawn is correct.
