### ISSUE TITLE
Travis CI "use esnext option"

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#3131]
We have a build at:

https://travis-ci.org/wayne-o/sonatribe-ui

Which is for my ember-cli repo at:

https://github.com/wayne-o/sonatribe-ui

But keeps failing because of "use esnext option"

How do I sort this? AFAIK use esnext is set?

**Comment by rwjblue** [comment]
You do not have the `.jshintrc` file checked into the repo (which is what the `esnext: true` warning is all about).
