### ISSUE TITLE
Compiling very slow since update to 0.1.10 (6to5)

### ISSUE THREAD

**Issue by cannect** [ember-cli/ember-cli#3136]
Hi,

Please look at the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/939500/5939445/0c037508-a704-11e4-89b6-b98d815a5962.PNG)

That is 8 minutes for the `ember server` command.

Some data:
- Normal the first compiling took around 20 seconds.
- Normal the following compiling took around 8 seconds.
- Windows 8 x64
- Large project

As you see 6to5 is the slowest tree. Is there anything I can do about it? I run `cmd` with administrator rights and have followed the Windows instructions on ember-cli.com.

Edit: can I go back to esnext?

**Comment by stefanpenner** [comment]
@cannect quick solution is to remove 6to5 from the package.json, it does mean other the modules, you wont get any fancy ES6 features.

cc @sebmck 6to5 may have had a regression

**Comment by stefanpenner** [comment]
> @cannect

what were your times before the upgrade and without 6to5

**Comment by sebmck** [comment]
@stefanpenner This doesn't make any sense. @cannect Do you have any steps to reproduce?

**Comment by stefanpenner** [comment]
> @stefanpenner This doesn't make any sense.

Ya, it __may__ be something unrelated to 6to5.  I wont have time to investigate till late tonight

**Comment by cannect** [comment]
@stefanpenner before upgrade (without 6to5) I had a 20 seconds for the first build, and 8 seconds for all following builds after editing my code.

So lets have some simple stats:

First build / changes build
**Before upgrade to 0.1.10 without 6to5**
20s/~8s

**After upgrade with 6to5**
8 **minutes** / 3.4s 
( holy moly I never got the **first build** that slow and **changes build** that fast! )

**After upgrade without 6to5**
16s/3.4s 

So we can conclude that 6to5 is 'the problem' however, where it lies I can't see. If anybody is interested in my setup, we can do a Teamviewer session or what you want.

**Comment by stefanpenner** [comment]
> and 8 seconds for all following builds after editing my code.

that still seems slow, but windows support is still "meh"

**Comment by cannect** [comment]
> that still seems slow, but windows support is still "meh"

I know but it is my preferred working environment ;-) However, I now got 3.4sec with the new 0.1.10 version what is very fast for my project!

**Comment by stefanpenner** [comment]
> After upgrade with 6to5
> 8 minutes / 3.4s 
> ( holy moly I never got the first build that slow and changes build that fast! )

to help isolate if it is indeed 6to5, can you swap in `"ember-cli-6to5": "0.2.1",` in your package.json ?  if that restores the problem, then it is likely 6to5 otherwise it is some regression in ember-cli's pipeline.

**Comment by sebmck** [comment]
Hopefully it's not `6to5` because that'll be extremely hard to track down without the entire codebase.

**Comment by cannect** [comment]
Aww, it is 6to5 unfortunately because I am already on some minutes build time right now.

**Comment by sebmck** [comment]
@cannect So you still suffer the same performance when using `ember-cli-6to5@0.2.1`?

**Comment by stefanpenner** [comment]
> @cannect So you still suffer the same performance when using ember-cli-6to5@0.2.1?

if the problem persists, then it likely has to do with the recent linting hook refactor.

**Comment by cannect** [comment]
@sebmck Yes, see comment above. 

For reference this is my package.json:
```
"devDependencies": {
    "ember-cli": "0.1.10",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-htmlbars": "^0.6.0",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.0",
    "ember-cli-app-version": "0.3.0",
    "ember-cli-simple-auth": "^0.7.2",
    "ember-cli-simple-auth-cookie-store": "^0.7.2",
    "ember-cli-simple-auth-oauth2": "^0.7.2",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
```

Yes indeed no assets revision, because do not need that functionality.

**Comment by stefanpenner** [comment]
@cannect actually, in 0.1.10 did you use 6to5 or not at all.

**Comment by cannect** [comment]
> Just so we're clear, you're still suffering the same bad performance when using ember-cli-6to5@0.2.1?

@sebmck @stefanpenner Yes, the exact same bad performance persists. Still building with ember-cli-6to5@0.2.1

**Comment by stefanpenner** [comment]
I gotta jump on some client work, @rwjblue / @raytiley are going to jump in and see if he can help track down the issue.

I'll check back in after work.

**Comment by cannect** [comment]
> @cannect actually, in 0.1.10 did you use 6to5 or not at all.

@stefanpenner As stated in the first post, I am using 0.1.10 now. Before that I used a version around 0.1.6  without 6to5

**Comment by rwjblue** [comment]
@cannect - A few questions to help track this down:

* What version of ember-cli are you upgrading from?
* Prior to upgrading to 0.1.10/0.1.11 did you use ember-cli-6to5?
* When you are testing switching versions, are you running `rm -rf node_modules && npm cache clear && npm install` between switching versions?

**Comment by sebmck** [comment]
I'm off to bed, ping me if you manage to isolate this issue and are sure that it's 6to5 and I'll try and track it down. Thanks!

**Comment by cannect** [comment]
@rwjblue 
> What version of ember-cli are you upgrading from?
I come from version 0.1.6 without 6to5 (6to5 was not into play I think)
> Prior to upgrading to 0.1.10/0.1.11 did you use ember-cli-6to5?
No.
> When you are testing switching versions, are you running rm -rf node_modules && npm cache clear && npm install between switching versions?
I carefully follow the installation instructions with each upgrade. I am on windows so I delete the folders by hand.

**Comment by rwjblue** [comment]
> Before that I used a version around 0.1.6 without 6to5

If you are coming from 0.1.6, then you were previously using ember-cli-esnext (not ember-cli-6to5) or no ES6 syntax addon at all (see [0.1.6 default package.json](https://github.com/ember-cli/ember-cli/blob/v0.1.6/blueprints/app/files/package.json)).

When you were running 0.1.6, did you use `ember-cli-esnext`?

**Comment by cannect** [comment]
> When you were running 0.1.6, did you use ember-cli-esnext? 

Yes I used esnext as long as it came shipped with Ember CLI.

**Comment by rwjblue** [comment]
OK, so the regression in build time is not related to 6to5 3.0.0, but rather it is from moving from ember-cli-esnext to ember-cli-6to5.

@cannect - For now, you can either remove ember-cli-6to5 from your `package.json` completely (if you are not using ES6 features other than modules), or revert back to `ember-cli-esnext` at the version you were using previously (it should work exactly as it has previously).

**Comment by cannect** [comment]
@rwjblue thanks! I will switch back to `ember-cli-esnext`.

**Comment by raytiley** [comment]
I'm not able to reproduce this in my project. I went from 0.1.5 to 1.1.11

```
ember serve --proxy="http://localhost"
version: 0.1.5
Proxying to http://localhost
Livereload server on port 35729
Serving on http://0.0.0.0:4200/


Build successful - 10867ms.

Slowest Trees                  | Total
-------------------------------+----------------
ES6Modules                     | 1888ms
SixToFive                      | 1279ms
ES3SafeFilter                  | 1125ms
JSHint - App                   | 1016ms
Class                          | 660ms
Funnel                         | 626ms
```

```
D:\code\cablecast\Web\cablecast-ui>ember serve --proxy="http://localhost"
version: 0.1.11
Proxying to http://localhost
Livereload server on port 35729
Serving on http://0.0.0.0:4200/


Build successful - 9058ms.

Slowest Trees                  | Total
-------------------------------+----------------
JSHint app- QUnit              | 1256ms
SixToFive                      | 1206ms
ES6Modules                     | 1182ms
ES3SafeFilter                  | 914ms
Funnel: App JS Files           | 793ms
TemplateCompiler               | 511ms
```

**Comment by stefanpenner** [comment]
@raytiley whats your incremental times?

Something is really fishy to get a 8 minute build, something has gone very wrong :P

**Comment by raytiley** [comment]
@stefanpenner 

```
D:\code\cablecast\Web\cablecast-ui>ember build
version: 0.1.11
Built project successfully. Stored in "dist/".

D:\code\cablecast\Web\cablecast-ui>ember serve --proxy="http://localhost"
version: 0.1.11
Proxying to http://localhost
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

Build successful - 11553ms.

Slowest Trees                  | Total
-------------------------------+----------------
SixToFive                      | 1906ms
TemplateCompiler               | 1402ms
JSHint app- QUnit              | 1360ms
ES3SafeFilter                  | 1115ms
ES6Modules                     | 706ms
Funnel: App JS Files           | 692ms

file changed router.js

Build successful - 5669ms.

Slowest Trees                  | Total
-------------------------------+----------------
Funnel: App JS Files           | 747ms
TreeMerger (vendor)            | 644ms
Concat: Vendor                 | 480ms
ES6Modules                     | 399ms

```

**Comment by tehmaestro** [comment]
Hi. I just upgraded to 0.1.12 and it really is so much slower than 0.1.3 (yes, on windows).
  It helped when I remove 6to5, inject-live-reload, and qunit. After removing these lines from package.json,  I went from 12s initial build - 5s incremental, to 7.6s - 3.1s

**Comment by sebmck** [comment]
@tehmaestro Can you try running:

```sh
$ set DEBUG=6to5
```

and then running ember and check the 6to5 debugging results to see if there's anything suspicious like spending lots of time on one file?

**Comment by tehmaestro** [comment]
Sorry, where should I run that command? :)

**Comment by sebmck** [comment]
@tehmaestro Just on your command line before you run your ember command.

**Comment by tehmaestro** [comment]
Nope, it's ok, 1ms, doesn't hang on a particular file.
  As I said, I removed 6to5 completely along with other modules, and I still get 7,8 seconds, versus 4 seconds in Ember CLI 0.1.3.

**Comment by stefanpenner** [comment]
the only regression is due to sourceMapConcat, we are tracking that elsewhere.
6to5 now babel is just slower. In theory a cache can be created, but the invalidation phase is non-obvious
