### ISSUE TITLE
Ember CLI to work with Ember 1.9.1 (and Handlebars 2.0)

### ISSUE THREAD

**Issue by dgtman** [ember-cli/ember-cli#3137]
Due to the bug in Ember CLI wherein you cannot pass a parameter to a component if it is in a sub folder (which is fixed in Handlebars 2.0 per this post: http://emberjs.com/blog/2014/10/16/handlebars-update.html), we are trying to get our CLI project (CLI version 1.4) running with Ember 1.9.1.

So we upgraded CLI to 1.9 first.  Then downloaded the Starter Kit for Ember 1.9.1 and tried updating the Bower.json file with the appropriate versions of the dependencies I want.

```
"ember-data": "1.0.0-beta.14.1", 
"handlebars": "2.0.0",
"ember": "1.9.1",
"ember-cli": "^0.1.9",
```

After doing all that, the app still blows up in the browser, complaining about some Eval() not finding a function definition deep in the heart of Ember.js.  

Assumption - some other dependency needs to be updated but I haven't the slightest idea which one.

Question - when will Ember CLI be updated to work with Ember 1.9.1 and Handlebars 2.0?

**Comment by agentVargas2012R** [comment]
Experiencing the same issue here. 

I attempted to follow this procedure but with no avail:
http://emberjs.com/blog/2014/10/16/handlebars-update.html

**Comment by dgtman** [comment]
The actual line is:

```
 Error while processing route: index Unknown template object: function Error
    at http://localhost:4200/assets/vendor.js:10603:25
    at http://localhost:4200/assets/vendor.js:10607:3
    at http://localhost:4200/assets/vendor.js:10461:42
    at http://localhost:4200/assets/vendor.js:10463:2
```
```
Ember.js 26274
Ember.Logger.error.apply(this, errorArgs);
```

**Comment by abuiles** [comment]
@dgtman did you try all the steps listed here http://ugisozols.com/blog/2014/12/29/ember-cli-with-latest-emberjs-and-ember-data/ ?

**Comment by gdub22** [comment]
@dgtman that error means you have a Handlebars 1.x template precompiled somewhere, which is not compatible with Handlebars 2.x.  Look for any occurrences of `Ember.Handlebars.template(...)` and remove/replace.

**Comment by stefanpenner** [comment]
> when will Ember CLI be updated to work with Ember 1.9.1 and Handlebars 2.0?

works today, most of my apps are running with it

**Comment by stefanpenner** [comment]
> Due to the bug in Ember CLI wherein you cannot pass a parameter to a component

are you sure this is a bug in ember-cli? Seems htmlbars/handlebars related

**Comment by dgtman** [comment]
@gdub22 We don't do any template compilation, Ember CLI manages all of that.

@stefanpenner I can't say for sure it's a CLI bug, I don't have great visibility into the error.  All I can say is that when we try to migrate our 1.4 CLI app to 1.9, it gives those errors.   I'm not sure what other options we have to do the migration/upgrade other than what we have already tried.

I'm open to any and all suggestions.

**Comment by dgtman** [comment]
@stefanpenner  I just created a brand new Ember app (ember new myapp) using CLI v1.9, and based on what I see in the bower.json it generated, CLI  does not use Handlebars 2.0.0, rather it uses:

```
"handlebars": "~1.3.0",
```

**Comment by gdub22** [comment]
@dgtman Check your addons / 3rd party app.import's for `Handlebars.template` since the error is coming from vendor.  The error message is handlebars related.

**Comment by stefanpenner** [comment]
> bower.json it generated, CLI does not use Handlebars 2.0.0, rather it uses:

we don't bundle the new stuff yet, but it works if you upgrade it yourself.
We are pending some config related work to add ons to make it sufficient to ship it.

**Comment by john-griffin** [comment]
@stefanpenner could you point us at these issues so we can assist/track? Thanks!

**Comment by stefanpenner** [comment]
@john-griffin https://github.com/ember-cli/ember-cli/pull/2714

**Comment by dgtman** [comment]
Will this drop as part of 1.12?  I am curious, because I believe 1.12 is where the first of the "roadmap to 2.0" features will drop.   We are trying to migrate away from Views to components, but since components lack the visibility that a View has, this is a major struggle.  We are hoping to see some of these capabilities be included into Components, so we're anxious to see what improvements to Components version 1.12 brings.

**Comment by stefanpenner** [comment]
> Will this drop as part of 1.12? I am curious, because I believe 1.12 is where the first of the "roadmap to 2.0" features will drop

I don't know what "this" is

**Comment by dgtman** [comment]
@stefanpenner "this" refers to your prior comment:
```
We are pending some config related work to add ons to make it sufficient to ship it.
```

Assuming my understanding is correct about when the "roadmap to Ember 2.0" stuff starts getting included, when can we expect to see these Ember 1.12.x in CLI?

**Comment by stefanpenner** [comment]
> Assuming my understanding is correct about when the "roadmap to Ember 2.0" stuff starts getting included, when can we expect to see these Ember 1.12.x in CLI?

should be, but let me repeat what i said above. You as a user should be able to use these features today, we just can't bundle them by default just yet. So this in no-way should be a blocker for app developers.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/ember-jobs/blob/master/package.json#L26

**Comment by stefanpenner** [comment]
This doesn't appear to be an ember-cli bug. #2714 will make it easier for people to upgrade, as it will be bundled.. If a further issue exists, I suspect its ember / handlebars / htmlbars. If someone can demonstrate and ember-cli bug here, we can reopen.
