### ISSUE TITLE
tests/.jshintrc is being used to lint app after upgrade to ember-cli@0.1.10

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli#3139]
I'm suddenly getting lots of jshint errors after upgrading to ember-cli@0.1.10 due to something changing with how linting is done now.

For example,

```javascript
let equal = Ember.computed.equal;
```

in my app is triggering

```
models/commission.js: line 4, col 5, Redefinition of 'equal'.
```

**Comment by quaertym** [comment]
See https://github.com/ember-cli/ember-cli/pull/3132

**Comment by tim-evans** [comment]
@quaertym thanks! I'll mark this as closed.
