### ISSUE TITLE
Ember install not working properly? (Cannot find module 'broccoli-static-compiler')

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#3140]
was following the upgrade steps (all of them starting from 1 in setup)

"3. ember install -- Reinstall NPM & bower dependencies."

https://github.com/ember-cli/ember-cli/releases

and i got this error

```
Lawrences-iMac:InboxDashboard JoshuaCope$ ember install
version: 0.1.11
Cannot find module 'broccoli-static-compiler'
Error: Cannot find module 'broccoli-static-compiler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/JoshuaCope/Desktop/InboxDashboard/index.js:5:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

I then ran 
```
bower install
npm install 
```

and it worked fine (which is supposed to be what ember install is doing I believe)

Versions

ember - 1.9.1
ember-cli - 0.1.11
node - 0.11.14
npm - 2.0.0
OS X - 10.10

**Comment by stefanpenner** [comment]
I'm unsure how `ember install` ended up servicing this need. As it is not possible to satisfy it's own dependencies. In theory we could support this, but it would require a dramatically different approach.

The original intent of `ember install` was for install add-ons.

**Comment by jcope2013** [comment]
the release notes changed for 0.1.10 and 0.1.11, it used to say

npm install -- Reinstall NPM dependencies.
bower install -- Reinstall Bower dependencies.

now it just says 

ember install -- Reinstall NPM & bower dependencies.

it seems to suggest that should do the same thing as above? maybe it was just a mistake and not intended to read that way

**Comment by rwjblue** [comment]
I'm happy to change the release notes, I updated them for 0.1.10 and 0.1.11 to match the instructions on our website.

@jakecraige - You added `ember install`, should it be used as described in www.ember-cli.com/#project-update and the release notes?

**Comment by stavarotti** [comment]
I can confirm that this fails for me as well.

**Comment by jakecraige** [comment]
As initially said `ember install` runs the bower install and then npm install. @stefanpenner `ember install:addon` is used for installing addons.

There's another open issue referencing what the install steps should say.

This is an interesting case though. If a module ember-cli uses to run the install task, but isn't installed locally it will fail. If we could force it to use the global ember-cli instead of the local one then `ember install` should work I think, but that seems a little confusing.

**Comment by stefanpenner** [comment]
> As initially said ember install runs the bower install and then npm install.

this doesn't really make sense, as without node_modules present, ember-cli won't have its local deps to satisfy the requirements to run the install.

**Comment by rwjblue** [comment]
> When this feature was proposed, I assumed it was for installing add-ons

Yes, I believe that was my initial thought also. I can change the release notes to whatever we want, but them not being in sync with the website is confusing.

**Comment by stefanpenner** [comment]
> Yes, I believe that was my initial thought also. I can change the release notes to whatever we want, but them not being in sync with the website is confusing.

as it stands now `ember install` only works if node_modules is already atleast partially in-sync, it can't be used by users for a new-checkout. I believe `ember install` should just be for add-ons.

**Comment by jakecraige** [comment]
@stefanpenner I'm a little confused on what behavior you want. You want it to find addon's in the package.json and install them/run their generator?

Does that also mean you don't want `ember install:npm` and `ember install:bower` or is that a separate thing ?

**Comment by stefanpenner** [comment]
> @stefanpenner I'm a little confused on what behavior you want. You want it to find addon's in the package.json and install them/run their generator?

```js
ember install <addon-name>
``

**Comment by jakecraige** [comment]
@stefanpenner So would you want to remove `install:addon`, `install:npm`, and `install:bower`? Keep `install` and have that work with addons. You're correct in that we couldn't make it work with no args to install addons.

Then we just have people use the npm for regular packages, bower for bower ones, and `ember install` for addons?

**Comment by stefanpenner** [comment]
@jakecraige i believe `ember install <rendom npm package>` should likely also work.

As for bower, I hope we soon abandon it entirely. So i am indifferent about it.

As for installing the projects own node_modules, `npm install` is likely the best mechanism for now.

**Comment by stefanpenner** [comment]
@jakecraige sorry, I didn't catch this edge case when you initial did the work. I can't believe i missed it .

**Comment by jakecraige** [comment]
@stefanpenner Here's my thoughts

- Remove all the `install:*` commands. 
- Update the `install` command to install exclusively addons from npm.

Looking back, all these extra commands are confusing. We should just have people use the ones they know already npm/bower and add a special one for our special case, addons. I can throw an error if you try to use it with something that isn't an addon. 

With that in mind, I kind of want it to be called `install-addon` to be clear on what it does.

Thoughts?

**Comment by stefanpenner** [comment]
> With that in mind, I kind of want it to be called install-addon to be clear on what it does.

i would prefer `install` (less characters to type)

**Comment by joostdevries** [comment]
my two cents: clarity over less typing. `install-addon` would be clearer.

**Comment by jakecraige** [comment]
`ia` as an alias could also work. 

Though on the other hand, if we use it for exclusively ember addons, it makes sense that the `ember install` command would install ember-only things. 

I'm kind of indifferent now, lol

**Comment by stefanpenner** [comment]
ember install is now only for installing addons, not for doing an npm install
