### ISSUE TITLE
Addons - Failing test for newly created initializer

### ISSUE THREAD

**Issue by stavarotti** [ember-cli/ember-cli#3143]
A newly created initializer test fails, with the following message:

```
Uncaught Error: Could not find module my-button/initializers/awesome-init

Uncaught Error: 
Could not find module my-button/initializers/awesome-initloader.js:58 
requireModuleloader.js:41 
reifyloader.js:69 
requireModuletest-loader.js:14 (anonymous function)
```
This is after running:

```
ember g initializer awesome-init
```
in a newly created addon and then navigating to localhost:4200/tests

Environment details:

```
ember-cli - 0.1.5
node - 0.10.36
npm - 1.4.28
Windows 7 64 Bit
```

package.json:

```
{
  "name": "my-botton",
  "version": "0.0.3",
  "description": "A nice addon button.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "broccoli-merge-trees": "^0.2.1",
    "broccoli-static-compiler": "^0.2.1"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "ember-cli": "0.1.5",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  },
  "keywords": [
    "ember-addon"
  ],
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by jakecraige** [comment]
There is an open issue by me about generators not working in addons. This is that

**Comment by jakecraige** [comment]
If you create it manually and you still have problems feel free to reopen this though

**Comment by stavarotti** [comment]
Is this specific to initializers?  Components and helpers seems to work fine.

**Comment by jakecraige** [comment]
It may happen with others, here's what's happening.

When you generate the initializer it's adding it into the `app` tree. So when the tests run it's within the `dummy` namespace(a dummy app we include with ember addons). If you change it to import from `dummy/initializer/awesome-init` it will work. 

If you move the initializer into a folder called `addon` instead of the `app` it generates in, it will also make this work.

So this is a bug with the generators within addons, though I think a little different than the one I reported. 

Pretty much with how generators currently work, the quick fix would be to make sure the import is set to use the `dummy` namespace for now when inside an addon.

**Comment by stavarotti** [comment]
Thanks @jakecraige.  Is this something that we want to document for addon developers?

**Comment by jakecraige** [comment]
The difference between app / addon trees, the dummy app, or this bug?

app/addon trees - It absolutely should be documented. It's a concept that's important for addon developers to understand.

the dummy app - Same thing, for addon devs to test their addon this is the way we do it and it's important to be aware of.

this bug - this issue can serve as documentation on how to fix it locally. Hopefully it'll be fixed soon 

(ping @jgwhite for some insight into how we could fix this)

**Comment by jgwhite** [comment]
Thanks for the ping. I wasn’t aware of this issue. Should be fairly easy to adapt the `initializer` blueprint to detect whether it’s within an addon project and adjust the import namespace accordingly.

I’ll work on it soon as I have a chance but if anyone wants to tackle it sooner please do (…and If you want help getting started ping me on IRC).

**Comment by jakecraige** [comment]
Probably can use [Project.prototype.isEmberCLIAddon](https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L110-L112) to detect if we're in an addon and make the changes we need to

**Comment by jgwhite** [comment]
It looks like simply using a relative import in the blueprint for initializer test will do the trick. @stavarotti is on it.
