### ISSUE TITLE
Can't generate `locals` or `fileMapTokens` asynchronously in current blueprints

### ISSUE THREAD

**Issue by mattmarcum** [ember-cli/ember-cli#3146]
I'm trying to create a complex blueprint for an addon, and some of the lookups it needs to do for both the `locals` and `fileMapTokens` must be done asynchronously (via a promise).  Unfortunately both these hooks are run synchronously and the `beforeInstall` hook doesn't have access to the `locals` var in order to modify it.  

I create a pr that just adds the `locals` var as a second param to the beforeInstall hook.
https://github.com/ember-cli/ember-cli/pull/3199

**Comment by trabus** [comment]
Closing, as #3199 was merged.
