### ISSUE TITLE
run /tests in test environment

### ISSUE THREAD

**Issue by bjornstar** [ember-cli/ember-cli#3148]
I originally posted [this as an issue for ember-simple-auth](https://github.com/simplabs/ember-simple-auth/issues/415) but it probably belongs here.

I want to be able to run one server using the `development` environment, open my app http://localhost:4200 in one tab using the `development` environment and in another tab open my tests http://localhost:4200/tests using using the `test` environment

I've already put in some gross hacks to change specific settings based on `window.location.pathname`, but it feels so very wrong to do this.

Here are some examples of the hacks I had to do to get my tests working:
``` coffeescript
# app/adapters/application.coffee
adapter = DS.ActiveModelAdapter.extend
  host: (->
    # This is a hack to get our mocha tests to use our http-mocks instead of our real api server
    # See this issue on ember-cli - https://github.com/ember-cli/issues/3148

    if window.location.pathname == '/tests'
      return 'http://localhost:4200'

    #default to config.host
    return config.host
  ).property().volatile()

  namespace: (->
    if window.location.pathname == '/tests'
      return 'api'

    #default to config.namespace
    return config.namespace
  ).property().volatile()
```
and
``` javascript
// app/initializers/simple-auth.js
  initialize: function(container, application) {
    var config = ENV['simple-auth']

    // This is a hack to get our mocha tests to use the ephemeral store instead of local-storage
    // Filed an issue -- https://github.com/simplabs/ember-simple-auth/issues/415

    if (window.location.pathname === '/tests') {
      config.store = 'simple-auth-session-store:ephemeral';
    }

    Configuration.load(container, config || {});
    setup(container, application);
  }
```

I *really* don't want to keep making hacks like this just to get a decent testing experience.

Is there a unified place I can put these hacks? I tried putting those hacks in `config/environment.js` but functions get stripped out.

**Comment by stefanpenner** [comment]
> Is there a unified place I can put these hacks? I tried putting those hacks in config/environment.js but functions get stripped out.

that file exists to generate a JSON config

> Is there a unified place I can put these hacks?

their should be

> run /tests in test environment

Ya, it would be really swell to cleanup this part, so /test runs nearly identically to what happens with `test --server`

**Comment by rwjblue** [comment]
> Ya, it would be really swell to cleanup this part, so /test runs nearly identically to what happens with test --server been a pet peeve for some time.

This is already happening as long as you use the config from meta.  On `tests/index.html` we use `tests` environment in that meta tag, on `app/index.html` we use `development` or `production` (depending on what is being built).

**Comment by rwjblue** [comment]
> Is there a unified place I can put these hacks? I tried putting those hacks in config/environment.js but functions get stripped out.

Yes, the result of the `config/environment.js` function is turned into JSON.  All you need to do is make `config.host` and `config.namespace` (which I assume is `import config from '../config/environment';`) set to the correct values in test environment.

For example, the following in your `config/environment.js` file should take care of this without the snippet that you pasted above:

```javascript
// inside config/environment.js exported function

  if (environment === 'test') {
    ENV.host = 'http://localhost:4200';
    ENV.namespace = 'api';
  } else {
    // put your normal non-test values here
    ENV.host = 'http://some.awesome.server.com';
    ENV.namespace = 'flooobarb';
  }
```

**Comment by stefanpenner** [comment]
@rwjblue this got me thinking, i wonder if allow people to easily override entire modules in test env makes sense or not. I suspect it is overly complex, and really just the result of `container.register` working in reverse of how people want it to. (due to other deficiencies in the container stuff)

**Comment by rwjblue** [comment]
@stefanpenner - I believe that it should now be possible via Ember canary's container/registry split.

**Comment by rwjblue** [comment]
Closing as the initial question should be resolved by https://github.com/ember-cli/ember-cli/issues/3148#issuecomment-72031429.

**Comment by stefanpenner** [comment]
> @stefanpenner - I believe that it should now be possible via Ember canary's container/registry split.

soon.

**Comment by bjornstar** [comment]
> This is already happening as long as you use the config from meta. On tests/index.html we use tests environment in that meta tag, on app/index.html we use development or production (depending on what is being built).

Ok, looking into our app, it seems we are not using meta config because we have a mobile app and we don't want to have config changes require re-submitting to the AppStore. If I could just apply that setting to /tests it would 

Turning that on, I do indeed get the `test` config, but that causes other problems because `test` is configured for testem to run `/tests` and fails.

I guess what I'm really asking for is to be able to override config entries at runtime.

**Comment by rwjblue** [comment]
> it seems we are not using meta config

Ya, this is a bummer since this was precisely the thing that would have given you what you wanted.  The alternative to storing the configuration in a `<meta>` tag is storing it inside the actual compiled JS file.  The fact that your JS file has hard-coded environment settings embedded is what the actual problem is (and what config in meta solves).

> I guess what I'm really asking for is to be able to override config entries at runtime.

You can override whatever config items you would like at runtime.  Simply import the module, and change the object's values.
