### ISSUE TITLE
http-mock and RESTAdapter incompatible by default

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#3149]
The `RESTAdapter` pluralizes model names for the URLs. But the `http-mock` blueprint will generate singular API routes. This is also an error in the [Ember.js documentation](http://emberjs.com/guides/models/the-rest-adapter/#toc_url-conventions), which lists example URLs that are not pluralized.

```
ember g model band
ember g adapter application
```
Add `namespace: 'api'`.

```
ember g http-mock band
```
Registers the `/api/band` route.

`this.store.find('artist');` now generates this URL: `http://localhost:4200/api/artists` Note the plural s.

This is either an error in the `http-mock` blueprint and the docs or in Ember Data.

**Comment by buschtoens** [comment]
FYI: [Here the docs](http://emberjs.com/guides/models/customizing-adapters/#toc_path-customization) mention the pluralization. So this is an error with the blueprints and [this page in the docs](http://emberjs.com/guides/models/the-rest-adapter/#toc_url-conventions).

**Comment by buschtoens** [comment]
Quick Fix:
```
// adapters/application.js
import DS from 'ember-data';

var ApplicationAdapter = DS.RESTAdapter.extend({
  namespace: 'api',
  pathForType: function(type) {
    return Ember.String.camelize(type);
  }
});

export default ApplicationAdapter;
```

**Comment by justin-hackin** [comment]
I'm super noob with this , but how about  just modify the mock server file to add the s to the endpoint:

app.use('/api/bands', bandRouter);

**Comment by joostdevries** [comment]
@buschtoens The CLI doesn't mention anywhere whether you need to pass a resource. It actually states that you need to pass an `endpoint path` which, if you follow ED conventions should be plural.
