### ISSUE TITLE
Test Middleware: Incorrect Handling of Static Assets

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3150]
In the [TestServerAddon](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/tests-server/index.js) we are not properly handling any static assets in `tests/` directory.  All requests are re-written to `/tests/index.html` regardless of whether they are for an existing file in the broccoli builds output directory.

A few things need to be updated to handle this properly:

- [ ] Only rewrite the request URL **if** the requested asset does not already exist. The HistorySupport middleware does this properly, and we can completely steal its implementation :).  [See here](https://github.com/ember-cli/ember-cli/blob/b509978e1c82b067a1547254b611723d14a15bf2/lib/tasks/server/middleware/history-support/index.js#L31-L32).
- [ ] Add tests to confirm that any files in `tests/` other than `index.html` can be retrieved.  A nice base test to start with is [here](https://github.com/ember-cli/ember-cli/blob/master/tests/unit/tasks/server/express-server-test.js#L378-L398), and it needs to be tweaked to request a static asset in the output dir (like [this test](https://github.com/ember-cli/ember-cli/blob/master/tests/unit/tasks/server/express-server-test.js#L450-L460)) and confirm its contents.

---

This definitely affects ember-cli apps that want to have other files in `tests/` be requested from their `tests/index.html`, but where this was noticed primarily is in third party libraries using ember-cli simply for building.  Specifically:

*  https://github.com/tildeio/htmlbars - This used to use `test/` to avoid the bizarre issues here (before they were understood), but this issue surfaced recently when `test/` was moved to `tests/`.  Reproduction: run `ember serve` in HTMLBars repo, and navigating to `localhost:4200/tests/index.html`. You will see that tests do not run properly (because other configuration files are loaded from `tests/`, but this middleware is rewriting these requests to `tests/index.html`).

**Comment by stefanpenner** [comment]
> The HistorySupport middleware does this properly, and we can completely steal its implementation :)

is it possible to share the implementation? (although this may be your intent)

**Comment by rwjblue** [comment]
> Is it possible to share the implementation?

Not sure, basically the "fix" is guarding the actual logic with something like the following (right inside of the `watcher.then(function(results) {`):

```javascript
var assetPath = req.path.slice(baseURL.length);
if (!fs.existsSync(path.join(results.directory, assetPath))) {
  next();
  return;
}
```

Because these require closure scoped access to the middlewares `next` function, the watchers results object, and the request itself it seems that sharing this guard would actually be harder than adding it to the specific places where we rewrite the request (I am not opposed to a util function that takes the three args though).
