### ISSUE TITLE
New Initializers Format for Fastboot

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-cli#3159]
Hi,

I've been following along trying to get my Ember CLI app into good shape to use Fastboot & think I have an understanding of the changes to be made following on from these issues:

https://github.com/emberjs/ember.js/issues/10177
https://github.com/emberjs/ember.js/issues/10067

& the deprecation document written by @tomdale https://github.com/emberjs/website/blob/app-instances/source/guides/deprecations/1.11/instance-initializers.md

At the moment though I am structuring my initializers as per the ember-cli docs ie

http://www.ember-cli.com/#initializers

```js
1 // app/initializers/observation.js
2 export default {
3   name: 'observation',
4   initialize: function() {
5     // code
6   }
7 };
```

whereas the updated approach looks like it should be like this

```js
App.initializer({
  name: "clock",

  initialize: function(registry) {
    registry.register("clock:main", Clock);
  }
});

App.instanceInitializer({
  name: "clock",

  initialize: function(instance) {
    var clock = instance.container.lookup("clock:main");
    clock.setStartTime(Date.now());
  }
});
```

Does this mean we should now create a new directory for the instance-initializers in our projects?

Totally understand that this is probably a question which will be addressed in time & sorry if i'm just being too keen.

**Comment by stefanpenner** [comment]
> Totally understand that this is probably a question which will be addressed in time & sorry if i'm just being too keen.

Nope, this is an important question to ask! (and maybe help move forward)


> Does this mean we should now create a new directory for the instance-initializers in our projects?

I believe yes, we will add another directory of `instance-initializers`. Lets pull @tomdale in to confirm.

**Comment by tomdale** [comment]
Yep, you've got it exactly right.

**Comment by stefanpenner** [comment]
so, we need to:

- [ ] update the existing initializer, to use the right names of argument (and only  1 arg by default)
- [ ] add the instance-initializer hook
- [ ] have the runIinitializers code, run both instance and non-instance declarations

**Comment by rwjblue** [comment]
@stefanpenner - Yep, looks right to me.

**Comment by atomkirk** [comment]
Can this be made high priority now that ember 1.12 spews deprecation warnings in our console?

**Comment by badazz91** [comment]
How do I deferReadiness of the application with this new instance-initializer pattern?

**Comment by herom** [comment]
Also, is there a possibility to declare `before:` or `after:` properties like in the "previous" initializers?

**Comment by stefanpenner** [comment]
> How do I deferReadiness of the application with this new instance-initializer pattern?

this is likely a good stackoverflow question

**Comment by stefanpenner** [comment]
> Also, is there a possibility to declare before: or after: properties like in the "previous" initializers?

yup this should work, as they are implemented the same way (using a dag)

**Comment by herom** [comment]
Thanks a lot @stefanpenner - is there any work on docs for this new implementation of initializer/instance-initializer workflow?

**Comment by stefanpenner** [comment]
http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers

**Comment by piotrpalek** [comment]
@stefanpenner is there an alternative to `deferReadiness` or is it discouraged entirely? If so I think it would be good to provide that info somewhere in the deprecation docs, as many people are probably using it, including me (it would be nice to provide a migration path from `deferReadiness` as well)
