### ISSUE TITLE
Remove MIT license from addon blueprint

### ISSUE THREAD

**Issue by aceofspades** [ember-cli/ember-cli#3161]
Assuming assumptions about licenses should not be made. This can sneak its way into an addon during an upgrade and inadvertently advertise the wrong license. Comments?

**Comment by Kuzirashi** [comment]
I agree. I didn't notice that I had license: mit in my project and deleted it immediately. If someone develops commercial  project he has to remember to delete open-source license.

**Comment by stefanpenner** [comment]
what should the default be?

**Comment by lukemelia** [comment]
I am +1 for MIT as default license for addons. The culture of the Ember
community is to share the development burden of common functionality.

**Comment by aceofspades** [comment]
New rails engines and bundler gems default to the MIT license so that does indeed seem like a reasonable convention (at least when creating a new addon). Ideally `ember init` wouldn't try to override an existing license, easy to make a mistake and not realize it.
