### ISSUE TITLE
[Feature Request] ember uninstall:addon <name>

### ISSUE THREAD

**Issue by stavarotti** [ember-cli/ember-cli#3163]
An inverse of `ember install:addon <name>`.

I often find myself going through the following steps to remove an installed addon from my apps:

- Check the addons' blueprint/index.js for potential devDependencies added to my app's bower/package.json files
- `ember d <addonname>` (not sure if this is necessary but I do so as an inverse of `ember g <addonname>`)
- `npm uninstall awesome-addon --save-dev`
- `npm uninstall ...` for the devDependencies added by the addon
- `bower uninstall ...` for the devDependencies added by the addon

**Comment by rwjblue** [comment]
IMHO, if we are advising folks to install addons with `ember intall:addon` it does make sense to have a `ember uninstall:addon`.

**Comment by jakecraige** [comment]
I'm :+1: I had mentioned in IRC to @stavarotti that we may want to call it `uninstall` since I believe we are planning on changing `install` to do what `install:addon` currently does, and we'll remove `install:addon`. Based on https://github.com/ember-cli/ember-cli/issues/3140

**Comment by joostdevries** [comment]
sounds sensible.

**Comment by ipranay** [comment]
Very important to have. Is there a work around in the meantime to remove an addon?

**Comment by kushdilip** [comment]
@ipranay plain `npm uninstall [package-name] --save-dev` should work.

**Comment by swashcap** [comment]
:+1:

**Comment by stefanpenner** [comment]
low priority, the work around @kushdilip suggested is fine for today.

**Comment by marcemira** [comment]
If the addon uses bower deps, these won't be uninstalled along with the npm package. :/

**Comment by stefanpenner** [comment]
> If the addon uses bower deps, these won't be uninstalled along with the npm package. :/

Correct, nor should they be. As we have no idea if another addon added them or not.
Ultimately we are planning to drop bower entirely, so I have very little motivation to attempt to solve this.

**Comment by jakecraige** [comment]
Currently addons can implement the `afterUninstall` hook and do some cleanup there. Remove bower deps maybe, but as stef said that has it's own problems. Ugh package management

**Comment by stefanpenner** [comment]
we will implement this to:

* as basically an alias for `npm uninstall --save-dev` to enable symmetry

we will NOT implement this to remove bower deps, as:

* under closer inspection this is a more complex and a naive approach results in ahazard (removing a different add-ons similar bower-dep)
* we plan to drop bower all-together, and `npm uninstall --save-dev` does the right thing in its eco-system

**Comment by buschtoens** [comment]
Is there already an issue for the removal of bower?

Cross reference for installing (and removing) multiple addons in one go: https://github.com/ember-cli/ember-cli/issues/4176

**Comment by buschtoens** [comment]
What about some (optional) form of automated blueprint destruction?

**Comment by Frozenfire92** [comment]
+1

**Comment by stefanpenner** [comment]
seems to have gone stale, feature requests are not via RFC issues or fleshed out RFC.


We will revisit this later this year, when we revamp the addon/package managment integration.

**Comment by tennisonchan** [comment]
+1. For the symmetry, It makes sense to have `ember uninstall:addon` when there is `ember install:addon`.

**Comment by Fallenstedt** [comment]
I agree! This should be added.

**Comment by kellyselden** [comment]
@Fallenstedt It's in the works.
