### ISSUE TITLE
Setting outputPath to parent directory overwrites app/index.html

### ISSUE THREAD

**Issue by novaugust** [ember-cli/ember-cli#3169]
With the following directory structure,
```
| core 
    | client (ember app)
    | server (node app)
        | views
           | default.hbs
```
I'm trying to output the built `index.html` to `core/server/views/default.hbs`.

Here's my brocfile
```js
var app = new EmberApp({
  outputPaths: {
    app: {
        html: '../../../server/views/default.hbs'
    }
  }
});
```
Upon doing `ember build`, a symlink is created in the correct location, but my `core/client/app/index.html` gets clobbered with the dist build in the process.

You can see in this diff that `app/index.html` is being overridden with the build

![screen shot 2015-01-31 at 14 12 37](https://cloud.githubusercontent.com/assets/1207005/5989859/4ec31870-a953-11e4-8ae5-a972b7dfce9f.png)

Obviously, app/index.html isn't changed if I change my outputPath back to the default and do an ember build. I can only get this behaviour when the outputPath begins with `../`

This also happens on the latest ember-cli (0.1.12)

**Comment by rwjblue** [comment]
WAT, seems nuts

**Comment by novaugust** [comment]
Iknorite? I repro'd it in a simpler repo,
```sh
ember new output-test
cd output-test
```
```js
// edit Brocfile.js
var app = new EmberApp({
  outputPaths: {
    app: {
      html: '../index.html'
    }
  }
});
```

```sh
ember build
gst #the proof
#=> modified: app/index.js
```

**Comment by rwjblue** [comment]
@novaugust - Can you publish the simple repro repo?

**Comment by novaugust** [comment]
@rwjblue done: https://github.com/novaugust/ember-cli-output-paths-bug

**Comment by StevenNunez** [comment]
:+1: This is a pain.

**Comment by stefanpenner** [comment]
> This is a pain.

Should be easy to avoid no? Kinda like saying, `rm -rf` of my app deleted my app, sorta expected?

**Comment by StevenNunez** [comment]
Nope. The act of running ember build overrides the original index.html file when you change the output path. This is crazy not expected.

**Comment by stefanpenner** [comment]
Although the above does seem funky, I don't believe it to be something we expected to work. It is more or less in undefined behavior land.

The point of this api, is to change the output, but within the shared root.

To accomplish this more idiomatically, i would recommend either:

0. use a symlink to provide dist elsewhere
1. use a smlink from dist/file -> other/place
2. ember s --output-dir=some-alternative/place
