### ISSUE TITLE
Handlebars partial rendering

### ISSUE THREAD

**Issue by Tonkonozhenko** [ember-cli/ember-cli#3172]
Hello

I have a simple blog app written with Ruby on Rails. It provides REST API for blogs and users.

I have created Ember app using `ember-rails` gem and sprockets. Everything works: http://joxi.ru/D2PjBk6cpDwzr3

But when I migrated ember to Ember CLI I had some problems: http://joxi.ru/krDp9W7HEPGorp

In Rails console I see that it makes response but there are problems with rendering.

My code you can see here: https://github.com/Tonkonozhenko/embernoise/tree/ember-cli/app/frontend

**Comment by stefanpenner** [comment]
I'm dubious that is ember-cli related.

attempted to get you example app running, but it appear several deps are missing from the frontend, and the backend is dependent to non-existent branches.

Please provide an isolated example.

**Comment by Tonkonozhenko** [comment]
My project is on `ember-cli` branch.
I think problems are with handlebars.
Maybe I include wrong version.

Console outputs:
Good console output: http://joxi.ru/J2be5oJhXkJNm6
Bad console output: http://joxi.ru/bmooOeBHxpL4my

What debs are missing at frontend and what problem with backend?
At backend I used branches to make gems working with rails 4.2.
If something missing you can use master branch.

**Comment by stefanpenner** [comment]
> My project is on ember-cli branch.
> I think problems are with handlebars.
> Maybe I include wrong version.

yes i tried, after adding some missing deps to both gemfile + package.json it booted, but `rake db:seeds` failed, so i was unable to make further progress

* you are missing simple auth stuff from  `https://github.com/Tonkonozhenko/embernoise/blob/ember-cli/app/frontend/bower.json`
* https://github.com/Tonkonozhenko/embernoise/blob/ember-cli/Gemfile#L23 is a non-existent branch

**Comment by stefanpenner** [comment]
your partials are underscored, their is no underscoring in ember-cli all dashes or omit them. I am unsure if that is the problem.

Again, I don't believe this to be an ember-cli issue, but more likely a bug in your code.

**Comment by Tonkonozhenko** [comment]
I fixed seeds so it should work (it's caused because of Nokogiri xml parser, I disabled it).
Partials with underscore work.
Also I added `ember-simple-auth`.
I tried a lot with `bower.json` so I accidentally deleted it.
Maybe it also need [ember-cli-simple-auth-devise](https://github.com/simplabs/ember-cli-simple-auth-devise), it isn't in `bower.json` but it's in `package.json`

**Comment by stefanpenner** [comment]
this doesn't appear like an ember-cli issue, I suggest moving this Question to stackoverflow.

Sorry, we have limited time and energy to also do QA as part of our issue tracking. Additionally SO is a much better venue for such dialog.

If a bug does turn up, feel free to report it. Until then, I am closing this.
