### ISSUE TITLE
test-breadcrumbs debugger calls

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#3173]
When I run my app with the chrome dev tools window open, the loading is interupted by test-breadcrumbs calling ```debugger``` 3 times - it's very annoying!

What is this? How can i stop it? Is it needed?

**Comment by rwjblue** [comment]
This is almost certainly not an ember-cli issue.

Debugger's in code that is running are like adding breakpoints, they will pause execution if you have the dev tools open. 

You either have debugger in your project, or one of your included dependencies does.

**Comment by wayne-o** [comment]
What is test-breadcrumbs? I've not added that.

On Sunday, 1 February 2015, Robert Jackson <notifications@github.com> wrote:

> This is almost certainly not an ember-cli issue.
>
> Debugger's in code that is running are like adding breakpoints, they will
> pause execution if you have the dev tools open.
>
> You either have debugger in your project, or one of your included
> dependencies does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3173#issuecomment-72364136>
> .
>


-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by stefanpenner** [comment]
never heard of it

**Comment by rwjblue** [comment]
> What is test-breadcrumbs? I've not added that.

Neither did we :smiley:

**Comment by stefanpenner** [comment]
mysterious

**Comment by wayne-o** [comment]
this seems to be an issue with cli-bootstrap

I'll post the issue there - apologies for the noise

On Sun, Feb 1, 2015 at 2:23 PM, Stefan Penner <notifications@github.com>
wrote:

> mysterious
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3173#issuecomment-72366596>
> .
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by dukedave** [comment]
Here's the issue over there: linstula/ember-cli-bootstrap#38
