### ISSUE TITLE
Difference between staging and production build not specified in cli arguments or guide

### ISSUE THREAD

**Issue by jeffcressman** [ember-cli/ember-cli#3176]
Hi,

I ran into an issue on a project where `ember build --environment` and `ember build --production` resulted in different builds. 

Specifically, the codebase was making use of `__container__` calls, which were fine in the staging build but caused reference errors in the production build.

We've switched the use of `__container__` to the the preferred `this.container` format but I'm unclear and can't find any documentation on why the two builds are different. To me a staging build is supposed to be identical to a production build so that you're doing a final check on things exactly as they will appear in production before actually pushing a build for production live.

We could do a `ember build --environment=production` on our staging server but we need to specify a staging backend in `environment.js`. 

Any clarification on what the difference in builds is and how to either do a production code build but with different environments specified in `environment.js` or how to make a staging build produce the same output as a production build (I'm guessing changes to `Brocfile.js`) would be greatly appreciated.

Thanks,
Jeff

**Comment by stefanpenner** [comment]
> Specifically, the codebase was making use of __container__ calls,

`__container__` is private never use it, hence no documentation.

**Comment by stefanpenner** [comment]
> To me a staging build is supposed to be identical to a production build so that you're doing a final check on things exactly as they will appear in production before actually pushing a build for production live

if you staging build does not minify, the you will have trouble. Typically I deploy my production build to staging, and then production. So i know they are binary equivalent, other then the `meta` tag filled with configuration.

**Comment by jeffcressman** [comment]
Thanks @stefanpenner. 

We're on ember-cli 0.1.5

Is there a reason the staging build does not minify by default when executing `ember build --environment staging`?

I'm not clear on how I can get my staging configuration into the `meta` tag for a production build. 

Unless I am mistaken, `ember build --environment production` will hit this block during the build 
```javascript
// environment.js
if (environment === 'production') {
    ENV.api_host = '//api.ourdomain.me';
  }
```

If I put that build on our staging server it will connect to the wrong api, which should be coming from

```javascript
  // environment.js
  if (environment === 'staging') {
    ENV.api_host = '//api-stage.ourdomain.me';
  }
```

Is the only difference between the staging build and production build the minify step? If so, how would I enable that?

Thanks!

**Comment by stefanpenner** [comment]
> Is the only difference between the staging build and production build the minify step? If so, how would I enable that?

unsure, just use production ;)

**Comment by rwjblue** [comment]
ember-cli does not support a `staging` environment by default.  We only ship with `development` and `production`.  If you have custom configured a `staging` then you would have to review how that is configured in your project to determine why it isn't minified.  If you have not changed the default build at all, then specifying `--environment staging` is likely just defaulting to development assets (since `development` is the default environment).

**Comment by stefanpenner** [comment]
> ember-cli does not support a staging environment by default.

yet, but we will.

**Comment by rwjblue** [comment]
> yet, but we will.

yep, and when we add it, we will think it through to do this properly :wink: 

IMHO it should be exactly the same as `ember build --environment=production`

**Comment by jeffcressman** [comment]
Thanks @rwjblue, @stefanpenner 

Indeed, we're passing `--environment staging` with a default build (development). It seemed natural and ember-cli didn't complain so I assumed it was an actual build type.

I've looked and I can't see a way to do a production build and configure the `api_host` differently depending on which server we're targeting.

Is there any other way to pass a flag into ENV, other than the ember-cli `--environment` flag?

**Comment by stefanpenner** [comment]
We may want to make it complain until the story is corrected

**Comment by msalahz** [comment]
Hi Everyone, In my case I have four environments Development, QA, Stage and Production while QA & Stage should have the same build output for production build with different configurations. 
@rwjblue, @stefanpenner, Is there a way to defaulting none development builds to production instead of development ?

**Comment by stefanpenner** [comment]
Our configuration story will be refreshed once we settle the addon refactoring .  For now I suggest you shim your staging and stuff into what ember cli perceives as production

**Comment by lil25** [comment]
I've got solution for this. You can control build from config. I set up only minify flag for certain environments, but in general you can set any configuration.

//ember-cli-build.js
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var EmberAppConfig = require('./config/environment.js');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
      
      minifyCSS: {
          enabled: EmberAppConfig(EmberApp.env()).isMinify
      },
      minifyJS: {
          enabled: EmberAppConfig(EmberApp.env()).isMinify
      },
      sourcemaps: {
          enabled: !EmberAppConfig(EmberApp.env()).isMinify
      },
      tests: !EmberAppConfig(EmberApp.env()).isMinify,
      hinting: !EmberAppConfig(EmberApp.env()).isMinify
  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.

  return app.toTree();
};

**Comment by remkoboschker** [comment]
I found this very usefull

http://ember-cli.com/ember-cli-deploy/docs/v0.4.x/fingerprinting-options-and-staging-environments/

**Comment by skaterdav85** [comment]
Anyone know of a way to remove the `DEBUG: ....` console.log statements for an environment that isn't production?

**Comment by lukemelia** [comment]
@skaterdav85 The recommendation is not to use an environment that is not test, development, or production, as these are the only environments that ember-cli understand. @LevelbossMike has [a good writeup on this and how to address using ember-cli-deploy](http://blog.firstiwaslike.com/staging-environments-with-ember-cli-deploy/).

If you prefer not using ember-cli-deploy, you can use an environment variable instead and check `process.env.YOUR_ENVIRONMENT_VAR` in your `environment/config.js` file.

**Comment by nikdojo** [comment]
> yet, but we will.

2018. Any updates, Ember?

**Comment by kellyselden** [comment]
@nikdojo 

@lukemelia's answer is the currently defacto was. build envs and deploy envs are completely separate, and we don't plan on making any more than dev and prod.

**Comment by nikdojo** [comment]
@kellyselden Ok. Then what simple solution you suggest when multiple envs are required?

**Comment by kellyselden** [comment]
Simplest is `CUSTOM_ENV=staging ember build --environment=production`. You end up separating a build env and a deploy target this way. I use [config](https://www.npmjs.com/package/config) for another project, and [ember-cli-deploy](http://ember-cli-deploy.com) for others.
