### ISSUE TITLE
resolver inconsistent between camelCase and dasherized

### ISSUE THREAD

**Issue by cah-briangantzler** [ember-cli/ember-cli#3178]
I recently converted to ember-cli from ember/grunt. All belongs to and has manys had to be converted to dasherized syntax, yet store find still works with camelCase. I had expected camelCase to work on the relationships as well. What is the desired behavior? (FYI Serializers and Adapters are also custom, but are found)

I noticed that all the examples use single word models (post, articles) should make sure the examples and tests are using multi word models to test this.

Now attempting to use http-mock in testing. Using store find and a camelCase model name, it fails to find the model (I dont now if it would have found the adapter as it doesnt get that far). If I use a dasherized model name it finds the model but fails to find the adapter.

After a lot of digging it appears the resolver in test is not altered the same way as it is in non test. Specifically the following line in the build container doesnt seem to happen in test, leaving the normalizeFullName method just a return of the passed in param.

      container.normalizeFullName = container.resolver.normalize;

I am not quite sure where this should happen in test or I would suggest a solution. Does anyone have http-mock working with model names that are dasherized?

**Comment by stefanpenner** [comment]
ember-cli only supports dasherized.

**Comment by cah-briangantzler** [comment]
Both of these problems seem to stem in the resolver. Since a custom resolver is supplied by CLI and the resolver is the one not resolving, are you sure the issue isn't here?

**Comment by stefanpenner** [comment]
> CLI only supports dasherized. From reading the documentation I wasn't aware of this. Looking back I see that is says "Dasherized file and folder names are recommended" not required which may have been the source of the confusion.

thanks fixed: CLI only supports dasherized. From reading the documentation I wasn't aware of this. Looking back I see that is says "Dasherized file and folder names are recommended" not required which may have been the source of the confusion.

**Comment by stefanpenner** [comment]
> Both of these problems seem to stem in the resolver. It was noted that if dasherized IS used for the model in testing, it fails to find the custom adapter.

I use this in the many apps i work on, and it works correctly. I suspect you need to ensure everything is actually dasherized.

I added a comment to the `ember doctor` rfc https://github.com/ember-cli/rfcs/pull/3

If the problem persists please provide a reproducable example preferrably as a gtihub repo and I will gladly debug it for you.

**Comment by cah-briangantzler** [comment]
https://github.com/cah-briangantzler/ember-cli-custom-adapter.git

is a repo demonstrating that customer adapters of more than one word are not found in tests but are found in development.

**Comment by stefanpenner** [comment]
valid: https://github.com/cah-briangantzler/ember-cli-custom-adapter/blob/master/app/routes/application.js#L13
invalid: https://github.com/cah-briangantzler/ember-cli-custom-adapter/blob/master/app/routes/application.js#L12

**Comment by cah-briangantzler** [comment]
Was just showing that they BOTH work correctly in development, was just a point that both are supported although maybe not intentially.

Please look the test distributor-type-test.  In that test it is using the dasherized version and failing to find the custom adapter.

Its the tests that are not working as expected, running the code NOT in a test work as expected

**Comment by cah-briangantzler** [comment]
I tried to make some changes to the repo to make it more clear as to the problem. The test is written not to succeed if the correct adapter is found, and now fails because the correct adapter is not found.

I hope the changes make it more clear as to the problem. Please pull the updates

**Comment by stefanpenner** [comment]
let me review after work.

Does everything  work if you stick to the prescribed naming convention?

**Comment by cah-briangantzler** [comment]
No it does not work when using the prescribed naming convention.

**Comment by stefanpenner** [comment]
just reviewed the failing example, as I suggested above the bug is in ember-data. Which mistakenly normalizes to a internally camelized typeKey.

The only entity in the system that should have normalization control is the resolver, ember-data is violating this contract.

Please reopen this issue at http://github.com/emberjs/data

**Comment by bmatmentel** [comment]
Hi,
I am having this exact problem right now using ember 1.13, where the typeKey is camelcased, and the model is then not found, as its name is dasherized. 
I don't seem to find a solution here. Can somebody pin point a link? 
Thnaks
