### ISSUE TITLE
Integration tests hang on run in 0.1.12

### ISSUE THREAD

**Issue by theworkerant** [ember-cli/ember-cli#3180]
After upgrading an app from `0.0.47` to most recent (`0.1.12`) my integration tests stop working. They just hang without any helper output. Also did a fresh install of `0.1.12` and got the same thing. The only thing I added was coffeescript.

```
-------------------------------
ember.js:15373 DEBUG: Ember      : 1.8.1
ember.js:15373 DEBUG: Ember Data : 1.0.0-beta.12
ember.js:15373 DEBUG: Handlebars : 1.3.0
ember.js:15373 DEBUG: jQuery     : 1.11.2
-------------------------------
```

```
`import Ember from "ember"`
`import { test } from "ember-qunit"`
`import startApp from "../helpers/start-app"`

App = null

module('Sanity Test', {
  setup: -> App = startApp()
  teardown: -> Ember.run(App, App.destroy)
})

test "Can see the homepage", ->
  expect 1

  console.log "HERE I AM"
  ok true
```
Logs never show "HERE I AM"... in fact the logs show almost nothing except a deprecation warning for `.then` and the version debug statement before it.

![captura de pantalla 2015-02-02 a la s 14 14 32](https://cloud.githubusercontent.com/assets/58770/6003839/da9675ca-aae5-11e4-95d2-90779cdd230e.png)

**Comment by abuiles** [comment]
The problem here is the return value from setup, startApp returns a promise and that seems conflictive with the version of qunit.

Try

```
module('Sanity Test', {
  setup: -> App = startApp() && null
  teardown: -> Ember.run(App, App.destroy)
})
```

**Comment by rwjblue** [comment]
The blueprints from ember-cli-coffeescript need to be updated to avoid this automatic returning.

**Comment by theworkerant** [comment]
fweird... thanks.
