### ISSUE TITLE
addons added with npm link don't install correctly

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3185]
I have create an add-on with a default blueprint. I've used `npm link` to reference my add-on in my package while I work on it.

Running `npm install` doesn't install the default blueprint.
Running `ember install:addon` throws an error stating that my package can't be found in npm registry.

It seems the `ember install` command fails to identify that my package is local.

**Comment by stefanpenner** [comment]
@olivierlesnicki you must add it to the package.json, or we will not detect its existence.

**Comment by jakecraige** [comment]
> Running `npm install` doesn't install the default blueprint.

It is not supposed to

> Running `ember install:addon` throws an error stating that my package can't be found in npm registry.

You need to pass in the name of your addon. It's required. We should probably throw an error stating that when it's not present.

**Comment by olivierlesnicki** [comment]
@stefanpenner yes it is added to the package.json

**Comment by olivierlesnicki** [comment]
@jakecraige let me try to pass the name of the addon and see if it actually works with npm-linked addons.

**Comment by stefanpenner** [comment]
> @stefanpenner yes it is added to the package.json

ah ok thanks

**Comment by stefanpenner** [comment]
this works fine for me, can you provide steps to reproduce the issue?

**Comment by givanse** [comment]
@olivierlesnicki http://www.ember-cli.com/#link-to-addon-while-developing

**Comment by slindberg** [comment]
Updated link: http://ember-cli.com/extending/#link-to-addon-while-developing
