### ISSUE TITLE
Lint app directory in addons

### ISSUE THREAD

**Issue by jkarsrud** [ember-cli/ember-cli#3187]
When developing a reuseable data library (ED adapters, serializers and models) through an addon, I noticed that files in the `app/`-directory are never linted, neither in in-repo-addons or external ones. This seems to be a bug, as you might write addons where the files live in the `addon`-directory. Not sure how to solve this in a good way by looking at the source, but I'm sure we can find a good solution!

**Comment by stefanpenner** [comment]
sounds like a bug

**Comment by rwjblue** [comment]
Yes, it is definitely a bug.

**Comment by stefanpenner** [comment]
Seems to have gone stale
