### ISSUE TITLE
ember init doesn't allow editing diffs on windows when upgrading

### ISSUE THREAD

**Issue by jesse-black** [ember-cli/ember-cli#3195]
Is there a reason for [this](https://github.com/ember-cli/ember-cli/blob/602a1c4558fa3af8fef21b75341945099dc9f82a/lib/models/file-info.js#L50) line disallowing windows from editing diffs?

    function canEdit() {
      return ! /^win/.test(process.platform) && process.env.EDITOR !== undefined;
    }

I'm willing to help if it needs more work to support windows here.

**Comment by stefanpenner** [comment]
> I'm willing to help if it needs more work to support windows here.

because it isn't currently supported. If you are able to help enable support, then +10000 :)
