### ISSUE TITLE
Update test blueprint module setup/teardown to keep up to date with qunit

### ISSUE THREAD

**Issue by taddeimania** [ember-cli/ember-cli#3196]
I noticed in the qunit 1.16.0 release notes that module setup and teardown were deprecated in favor of beforeEach and afterEach.

https://github.com/jquery/qunit/commit/289e362579e4d6f39238871649524c9d4906f2dd

If this is a :+1: i'm sure I can whip up a PR fairly quickly.

**Comment by rwjblue** [comment]
I have been working on this the last few days.  Submitted https://github.com/ember-cli/ember-cli/pull/3197, can you review?

**Comment by taddeimania** [comment]
Nice work on this, submitted a small PR to your branch to add some globals comments.
