### ISSUE TITLE
How to make a conditional helper with ember-cli

### ISSUE THREAD

**Issue by erichonkanen** [ember-cli/ember-cli#3198]
Hello,

I am trying to achieve something similar to the form of:

```
{{#if has-permission "my_permission"}}
    // do some stuff here
{{else}}
    // fallback
{{/if}}
```
OR
```
{{#hasPermission session.user.permissions "my_permission"}}
```
I cannot for the life of me figure this out. I've read [this](http://www.ember-cli.com/#helpers) but there isn't much explaining on anything other than helpers that render content or alter it e.g. {{render "something"}}

When I try to make it a conditional I get this:
```
registerBoundHelper-generated helpers do not support use with Handlebars blocks.
```
Any help greatly appreciated, thanks!

PS Im using ember 1.9.1, latest data and handlebars 2.0

**Comment by stefanpenner** [comment]
this doesn't seem like an ember-cli bug. StackOverflow is a much better venue to ask this sorts of questions.

**Comment by erichonkanen** [comment]
@stefanpenner perhaps... but the ember-cli documentation is nil and not very encouraging around this topic...

**Comment by stefanpenner** [comment]
> but the ember-cli documentation is nil and not very encouraging around this topic...

The syntax you are using for both forms isn't valid handlebars syntax, covering that syntax especially for helpers and subexpressions is not in scope for the ember-cli docs.
