### ISSUE TITLE
Remove assert and debug code from production builds of app.js

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-cli/ember-cli#3200]
Since Ember assert and debug modules are replaced with noop function in production builds, does it make sense to strip away assert and debug code from app.js? Would definitely lead to a smaller footprint in the minified file. This would definitely motivate everyone to write more assert and debug messages.

**Comment by rwjblue** [comment]
Yes, this should (very recently) be possible with [ember-cli-defeatureify](https://github.com/jkarsrud/ember-cli-defeatureify).  I believe it may need a little more work to be compatible with CSP, but generally it looks really good.

**Comment by sivakumar-kailasam** [comment]
awesome, anything I can do to help out?

**Comment by jkarsrud** [comment]
@sivakumar-kailasam I've pushed some docs and updated the code in [ember-cli-defeatureify](https://github.com/jkarsrud/ember-cli-defeatureify) to be CSP compatible after #3218. It works if you run off `master` now, but also when 0.1.13 ships.

**Comment by sivakumar-kailasam** [comment]
Awesome :+1:  just tried it on my app. From the ember source code this looks particularly useful to strip away code based on canary/any specific features during build. But in apps like mine where we just want to strip away debug and assert messages now we have to add an extra if wrapper around it to achieve that. This is a big step over what we have today but I'm wondering if there could be a simpler way to achieve this by just dropping an addon without changes to existing code.

**Comment by jkarsrud** [comment]
It should strip out debug and assert messages if you pass them in to `debugStatements` array along with `enableStripDebug` under the `defeatureify` object in your config.

**Comment by rwjblue** [comment]
I've been chatting with @mmun and I think we can also make a way to do the same kind of stripping for templates (by walking the AST on precompile), ember-cli-defeatureify seems like a great place for this...

**Comment by sivakumar-kailasam** [comment]
I tried two different configs from what I could figure from the docs and both don't seem to work.
```
defeatureify: {
		'strip_debug': {
			options: {
				'enableStripDebug': true,
				'debugStatements': [
					'Ember.warn',
					'Ember.assert',
					'Ember.deprecate',
					'Ember.debug',
					'Ember.Logger.info'
				]
			}
		},
		'features': {

		}
	}
```

and 

```
defeatureify: {
         'enableStripDebug': true,
         'debugStatements': [
			'Ember.warn',
			'Ember.assert',
			'Ember.deprecate',
			'Ember.debug',
			'Ember.Logger.info'				
        ],
	'features': {

		}
}
```

**Comment by mmun** [comment]
cc @alexBaizeau

**Comment by sivakumar-kailasam** [comment]
After adding the Ember.default.* versions of debug and assert in my config the messages were stripped out. Thanks @jkarsrud :100:

**Comment by jkarsrud** [comment]
@sivakumar-kailasam That makes sense, as this addon runs after the module transpilation step. Glad you figured it out! :smiley: 

@rwjblue Are you thinking of stripping the templates based on feature flags? If so, that would be a really useful feature, and one that could definitely be built into ember-cli-defeatureify at some point!

**Comment by alexBaizeau** [comment]
:+1:  for "defeaturifying" templates.

My use case would be able to ship features both in JS and templates to our staging environment but strip them out of our production code.
 
The main reason is that I'd like to be be able to QA and demo some half finish features but hide them from my users. A beneficial side effect would be to be able to be stealthy about our roadmap as inspecting the code/templates would not reveal what's still in progress.

**Comment by stefanpenner** [comment]
this seems to be handled by the `ember-cli-defeaturify` addon

**Comment by notmessenger** [comment]
To save anyone typing later, this is the configuration I am using to strip all debug statements:

```
        defeatureify: {
            'enableStripDebug': true,
            'debugStatements': [
                'Ember.default.warn',
                'Ember.default.assert',
                'Ember.default.deprecate',
                'Ember.default.debug',
                'Ember.default.Logger.assert',
                'Ember.default.Logger.debug',
                'Ember.default.Logger.error',
                'Ember.default.Logger.info',
                'Ember.default.Logger.log',
                'Ember.default.Logger.warn',
                'console.assert',
                'console.clear',
                'console.count',
                'console.debug',
                'console.dir',
                'console.dirxml',
                'console.error',
                'console.group',
                'console.groupCollapsed',
                'console.groupEnd',
                'console.info',
                'console.log',
                'console.profile',
                'console.profileEnd',
                'console.select',
                'console.table',
                'console.time',
                'console.timeEnd',
                'console.trace',
                'console.warn'
            ],
            'features': {}
        }
```
