### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3201]
Import of files in tests that don't exist seems to not trigger any error but then skips lots of tests.

Example:
```
///file: tests/unit/adapter/application-test.js
import storeSetup from '../../helpers/store-setup';
```

If the helper does not exist then the tests seem to be skipped.

The issues I have here are:
- [ ] Missing files in tests should not fail safe
- [ ] Testem numbers the TAP tests when I am not specifying the test numbering
  - [ ] Rather than force the number of tests, at least a sanity check that a test came out of each test file would be nice
- [ ] Fatal errors like this should cause the TAP to `Bail out!`

**Comment by jonathanKingston** [comment]
Currently checking this with the latest QUnit updates

**Comment by rwjblue** [comment]
Some of this should have been fixed (specifically https://github.com/ember-cli/ember-cli-test-loader/pull/7 should have helped the case when an import is wrong that most tests are ignored/lost).

**Comment by jonathanKingston** [comment]
@rwjblue I have the latest 'ember-cli/ember-cli-test-loader#0.1.1' and any test with a broken include in gets skipped.

so:
```
import thing from 'abrokenfile';

... valid test code
```

All the valid test code gets skipped with no warnings.

**Comment by rwjblue** [comment]
@jonathanKingston - Yes, any module with parse errors at the root level will be skipped.  That cannot be fixed.

The test loader iterates the list of modules and loads them (if they end in `-test`).  Prior to the PR that I mentioned, an error in the root of a module would have caused ALL other modules to be skipped too.

**Comment by jonathanKingston** [comment]
@rwjblue yeah I noticed the skipping lots of tests which made me very paranoid and raise this issue.

Would it be possible to parse the test before calling it? So for example using esprima to locate the include and check it exists.
I'm just worried that removing any dependency from a project will allow tests to be ignored that may be broken.

Any error like this could spit out a 'Bail out!' TAP message so projects with multiple test streams can detect fatal errors easily.

**Comment by rwjblue** [comment]
OK, I think that https://github.com/ember-cli/ember-cli/pull/3298 is about as good as we can get here.  It will cause a failing test if a test module cannot be loaded.

**Comment by jonathanKingston** [comment]
@rwjblue brilliant thank you!
