### ISSUE TITLE
Addon testing - components depending on services

### ISSUE THREAD

**Issue by rk1** [ember-cli/ember-cli#3202]
I'm trying to write tests for my addon, but encountering some weird behaviour.

I have created a service (via ember-cli generate), which is used inside a component. When an actual application is running everything is working fine.

However, when testing the component I get an error saying that the service is undefined when trying to access any of its properties/methods.

In the test i've put the service in "needs" like so:

`needs: ['service:my-service']`

as mentioned in [in the documentation](http://www.ember-cli.com/#moduleformodelname-description-callbacks)

"Needing" other components (e.g. child ones used inside) works as expected, services strangely fail.

Are there any additional steps that need to be done when testing components depending on services?

I cannot find any documentation on whether I need to do something besides "needs" in the test.
Also, I can't find any realted issues, maybe I'm searching for something too narrow and this is a general issue regarding service lookups?

Here is a sample repository, using only one component and only one service replicating my original setup - [https://github.com/rk1/foobar](https://github.com/rk1/foobar)

Running ember-cli 0.1.12.

**Comment by rk1** [comment]
I was able to get this working by injecting the service using the [new API](http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_injected-properties) introduced in the latest Ember 1.10 release.

I will leave the issue open for now, as injecting a service via an initializer is a different scenario and I can't seem to get the tests in the repo linked above working, nor find any documentation about it.

**Comment by mike1o1** [comment]
Not sure if this helps, but the way I've been testing components that rely on services is to simply inject them myself when I create the component in my test.

For example, your test setup would be:

```
import logger from 'dummy/services/logger';
var App, loggerService;

moduleForComponent('x-button', 'XButtonComponent', {
  setup: function() {
    App = startApp();
    loggerService = logger.create();
  },
  teardown: function() {
    Ember.run(App, App.destroy);
  },
  // specify the other units that are required for this test
  // this isn't really necessary, since we're injecting ourself
  //needs: ['service:logger']
});
```

Then, when you instantiate your component, pass in the logging service you created in setup.

```
test('it logs', function() {
  var component = this.subject({
    loggerService: loggerService
  });

  // console.log(component.loggerService);
  component.click(); //Cannot read property 'log' of undefined
});
```

**Comment by rk1** [comment]
Thanks a lot for your input. I guess `needs` is not the way to go when relying on services. As mentioned above, I've migrated to injecting services using the new API for injected properties, but I will use your approach whenever the service is injected via an initializer. Thanks again.

**Comment by rwjblue** [comment]
`needs` is definitely not going to work for services. The new `Ember.inject` API should replace `needs` at some point in the future (pre 2.0).

**Comment by rk1** [comment]
Great, thanks for clearing that up!
