### ISSUE TITLE
Remove install:addon, install:bower, install:npm

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#3204]
This comes based on this discussion https://github.com/ember-cli/ember-cli/issues/3140#issuecomment-72037408

- Remove `install:*` commands
- Update `install` command to exclusively install addons from npm

My reasoning is that these commands add extra complexity that doesn't really add value(imo). There's no difference between `ember install:npm` and `npm install` and it's bower counterpart. The only unique one was the `install:addon` command so we are keeping that around.

**Comment by lolmaus** [comment]
:+1:
