### ISSUE TITLE
ember-cli mis-pronunciation appears rampant 

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3205]
the website should include the correct pronunciation before this gets out of hand. IN whatever phonetical system makes sense.

for reference it is pronounced: "ember C L I", not ember clei or ember clie

**Comment by ballPointPenguin** [comment]
Like "Em-Berkley" right?

**Comment by runspired** [comment]
+1 for ember-slee-ve ;)

**Comment by stefanpenner** [comment]
> +1 for ember-slee-ve ;)

you should record yourself saying this, i have no idea what it would sound like

**Comment by runspired** [comment]
ember + sleeve, but the sleeve is elongated for dramatic effect.

**Comment by btecu** [comment]
**\*rampant** :trollface:

**Comment by jakecraige** [comment]
whoa, this is a thing? haha

**Comment by stefanpenner** [comment]
> *rampant

thanks fixed :P

**Comment by taddeimania** [comment]
i dunno, this seems like something that the community would naturally solve as a group in any large in-person gathering. :heart_eyes_cat:

**Comment by joostdevries** [comment]
I am in favor of getting this featured on https://www.youtube.com/channel/UCqDSLtXeZsGc3dtVb5MW13g

**Comment by tubbo** [comment]
I've been calling it "Ember Clyde"...

**Comment by taddeimania** [comment]
Thanks to this discussion I now refer to this project as embercleese.

**Comment by runspired** [comment]
@taddeimania it's the Hercules of Javascript

**Comment by ballPointPenguin** [comment]
I'm going with "Em-Berkeley", after discarding "Emb-R-Kelly"

**Comment by stefanpenner** [comment]
> "Emb-R-Kelly"

i can be convinced

**Comment by stefanpenner** [comment]
@chnn ^^ website stuff :P

**Comment by Twinkletoes** [comment]
just for fun, you've committed the horrific error of spelling pronunciation incorrectly in the title, just the way most people mispronounce pronunciation ;-)

**Comment by stefanpenner** [comment]
@Twinkletoes lol, spelling isnt... my specialty. Thank god VIM has auto-complete

**Comment by Twinkletoes** [comment]
:( you broke the joke

**Comment by runspired** [comment]
Ember o'clihan
