### ISSUE TITLE
acceptance tests for master are failing locally (mac osx)

### ISSUE THREAD

**Issue by mattmarcum** [ember-cli/ember-cli#3206]
I'm getting 12 failing tests in master, all are acceptance tests for routes and resources.  It looks like they are are all expecting the generated files to use single quotes, but they have double quotes instead:

```
expected app/router.js:

import Ember from 'ember';
import config from './config/environment';

var Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.resource("foos", function() {});
});

export default Router;

to contain:

this.resource('foos', function() {});
: expected false to equal true
```

You can see this test is expecting `'foos'` and it got `"foos"`.   Looks like the ember-router-generator is giving back different output than expected? Since this isn't showing up on appveyor I'm wondering if it is platform specific?  I'm sure I'm not the only person using bash on mac osx to dev.  Can anyone else verify?

**Comment by rwjblue** [comment]
`rm -rf node_modules && npm cache clear && npm install` should fix.  You have an old version of `ember-route-generator`.

**Comment by stefanpenner** [comment]
I feel like we telephone support staff. "Have you tried turning in on and off again"?

This clearly isn't the authors fault, but I'm astounded by what % of our bugs are NPM related.

**Comment by mszoernyi** [comment]
+1 Stefan. Every bug I can't track down directly leads me to remove
node_modules and install them again. Which helps in some cases :-) Quite
annoying to be honest and still not sure why it happens but it seems npm
seems to be kinda unstable or my setting is somehow broken.
