### ISSUE TITLE
ember http-mock request.body is undefined

### ISSUE THREAD

**Issue by user9821** [ember-cli/ember-cli#3208]
not sure if this a bug or the api has changed.

just migrated to ember-cli 0.1.12 and now http-mock is not working for me.

Its working fine for get request . request.query returns all the query parameters.

However for POST request i cannot get the request parameters as i get request.body is undefined in the mocks defined in the server routes.

Can some one let me know how to access the request body in ember http-mock?
There is hardly any documentation i can find for this.

**Comment by joostdevries** [comment]
@user9821 Did you regenerate the server? Because in #2568 the bodyparser (which gives you a POST/PUT body) has been removed. You'll have to add it to package.json and server/index.js again yourself.
