### ISSUE TITLE
Option to ignore jquery inclusion

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3209]
I would like to be able to pass an argument to ember build and ignore jquery since the ember app is part of larger application that includes jquery already.

Right now I've edited the vendor files with something like this:
`
    'jquery.js': null, isProduction ? null : this.bowerDirectory + '/jquery/dist/jquery.js',
` 

Obviously it's not elegant and I would have to change it every time I update ember-cli.

**Comment by rwjblue** [comment]
There is an option, it is `vendorFiles` (as I believe that you mentioned above).

Something like the following should work (and seems like what you may already have):

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var isProduction = EmberApp.env() === 'production';
var jQueryPath = isProduction ? null : this.bowerDirectory + '/jquery/dist/jquery.js';

var app = new EmberApp({
  vendorFiles: {
    'jquery.js': jQueryPath
  }
});

module.exports = app.toTree();
```
