### ISSUE TITLE
Can I have nested model / serializer

### ISSUE THREAD

**Issue by chandruaskutty** [ember-cli/ember-cli#3210]
Hi ,

My application requires nested model directory structure , So I have created two model named facebookusers/list , twitterusers/list and created the same in serializer . Model js files are loads but not serializer js files.

ember generate model facebookusers/list
ember generate serializer leads/folders

ember generate model facebookusers/list
ember generate serializer twitterusers/list

I am trying get the response like this

this.store.find("facebookusers/list") response received successfully but where do I need to serialize ?

Regards
Chandru.

**Comment by joostdevries** [comment]
@chandruaskutty As stated in the [contributing guidelines](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md), the issue tracker is only for bugs, feature requests and Ember CLI source-code related issues. Your question is probably better under the [Ember CLI tag on Stackoverflow](stackoverflow.com/questions/tagged/ember-cli).
