### ISSUE TITLE
Default component test DEPRECATION this.append()

### ISSUE THREAD

**Issue by seawatts** [ember-cli/ember-cli#3214]
I get this error when running tests when after I generate a component.
`ember g component user-object`

`DEPRECATION: this.append() is deprecated. Please use this.render() instead.`

**Comment by rwjblue** [comment]
This was fixed in https://github.com/ember-cli/ember-cli/pull/3170 on master, and will be included in the next release.

**Comment by seawatts** [comment]
Great! Thanks
