### ISSUE TITLE
Template not found after generating nested resource

### ISSUE THREAD

**Issue by manuel-reil** [ember-cli/ember-cli#3219]
Hi,
when generating a nested resource, I get the following error:

```
Could not find "dashboard" template or view. Nothing will be rendered Object {fullName: "template:dashboard"}
Could not find "dashboard.index" template or view. Nothing will be rendered Object {fullName: "template:dashboard.index"}
```
```
ember generate resource main/dashboard --pod
installing
  create app/pods/main/dashboard/model.js
installing
  create tests/unit/pods/main/dashboard/model-test.js
installing
  create app/pods/main/dashboard/route.js
  create app/pods/main/dashboard/template.hbs
installing
  create tests/unit/pods/main/dashboard/route-test.js
```

**Versions:**
Ember-CLI: 0.1.12
Ember : 1.8.1 (also tried 1.9.1)
Ember Data : 1.0.0-beta.12
Handlebars : 1.3.0 (also tried 2.0.0)
jQuery : 1.11.2

**Comment by teddyzeenny** [comment]
It looks like all the created file paths are wrong. You should remove `main` from all of them since resources reset the namespace.
Until this is fixed, I think it's easier to just use `ember generate resource dashboard` and fix `router.js` manually to nest `this.resource('dashboard')` under `main`.
