### ISSUE TITLE
Namespace window[appName] to prevent collision with global objects

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3220]
I did `ember new map`, and now I cant do `new Map()`..

The best solution would be to namespace: `EmberCLI.Map` or `$Map`.

This really limits the names you can use for your app.

**Comment by rwjblue** [comment]
Remove https://github.com/ember-cli/ember-export-application-global from your `package.json`.  We cannot prevent every possible collision.  I personally think we shouldn't ship with ember-export-application-global by default, but I was overruled ;)

**Comment by rwjblue** [comment]
I do not think that we should change the default from `window[classifiedName]`, but we could do a quick check before clobbering things. Something like:

```javascript
if (config.exportApplicationGlobal && !window[classifiedName]) {
  window[classifiedName] = application;
}
```

Here: https://github.com/ember-cli/ember-export-application-global/blob/master/app/initializers/export-application-global.js#L7-L9

**Comment by knownasilya** [comment]
And if there is a collision, then namespace it.
On Feb 6, 2015 4:54 PM, "Robert Jackson" <notifications@github.com> wrote:

> I do not think that we should change the default from
> window[classifiedName], but we could do a quick check before clobbering
> things. Something like:
>
> if (config.exportApplicationGlobal && !window[classifiedName]) {
>   window[classifiedName] = application;
> }
>
> Here:
> https://github.com/ember-cli/ember-export-application-global/blob/master/app/initializers/export-application-global.js#L7-L9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/3220#issuecomment-73319583>
> .
>

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by knownasilya** [comment]
Also it's weird that the name is classified, since it's not a class.
On Feb 6, 2015 5:01 PM, wrote:

> And if there is a collision, then namespace it.
> On Feb 6, 2015 4:54 PM, "Robert Jackson" <notifications@github.com> wrote:
>
>> I do not think that we should change the default from
>> window[classifiedName], but we could do a quick check before clobbering
>> things. Something like:
>>
>> if (config.exportApplicationGlobal && !window[classifiedName]) {
>>   window[classifiedName] = application;
>> }
>>
>> Here:
>> https://github.com/ember-cli/ember-export-application-global/blob/master/app/initializers/export-application-global.js#L7-L9
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ember-cli/ember-cli/issues/3220#issuecomment-73319583>
>> .
>>
>

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by rwjblue** [comment]
> Also it's weird that the name is classified, since it's not a class.

This is a somewhat legacy thing, for example the app instance in ember-rails was either `window.App` or `window.MyAppName` and that is what we copied.  

Like I said, I don't like adding the global at all.  Feel free to PR upstream with tests fixing the clobbering behavior (though I do not think we should namespace if there is a collision, just don't set up the global).

I'm going to close this issue, as I believe that it 1) isn't a bug and 2) we have a path forward if someone wants to do the work.
