### ISSUE TITLE
can't access service from another service, no documentation about it

### ISSUE THREAD

**Issue by mgenev** [ember-cli/ember-cli#3221]
I first filed this issue with ember, but seeing that a service is a plain object and that the cli does some magic to register them, I think this might be a ember-cli bug actually

https://github.com/emberjs/ember.js/issues/10374

I've done this before with controllers and an initializer, 'register' and 'after'.  This time, I'm using ember-cli, I generate a service. The blueprint also makes me an initializer. I do it again for another service.

The services cannot access each other even after I use 'after' like this:

```
export function initialize(container, application) {
    application.inject('route', 'first', 'service:first');
    application.inject('controller', 'first', 'service:first');
    application.inject('view', 'first', 'service:first');
};

export default {
    name: 'first-service',
    initialize: initialize
};
```

```
export function initialize(container, application) {
  application.inject('route', 'geoService', 'service:geo');
  application.inject('component', 'geoService', 'service:geo');    
}

export default {
  name: 'geo-service',
  after: 'first-service',
  initialize: initialize
};
```
Both services are accessible in a route, but first-service is not accessible from geo-service. If I misspell 'first-service' in the after, ember breaks saying there is no such service, so I know that is being evaluated but it makes no difference when the name is accurate.

It seems to me the issue might be because 'after''s logic depends on 'register'. I saw that this service generation from the blueprint is missing a 'register' line like you had to do with controllers, but here it says that I don't need that with services, and that's what I infer from some change logs in ember-cli
http://stackoverflow.com/questions/25387055/ember-cli-cannot-register-a-service

The Ember docs only make a reference to using controllers as a service here and register is being used:
http://emberjs.com/guides/understanding-ember/dependency-injection-and-service-lookup/

But there is nothing that I can find about the services ember-cli generates and how to make them depend on other services.

The API docs entry for Service doesn't tell me anything about that either:
http://emberjs.com/api/classes/Ember.Service.html

Is this feature finished? Should I be using a regular controller and register it? Should this bug be filed with ember-cli because of the way it generates these services and initializers?

**Comment by stefanpenner** [comment]
I do no not see any part of your example that injects services on other services. Can you provide a more thorough example, maybe a quick ember-cli based repo that demonstrates the issue?

**Comment by stefanpenner** [comment]
lets not duplicate issues
