### ISSUE TITLE
Feature Request: ember g controller and ObjectController

### ISSUE THREAD

**Issue by seawatts** [ember-cli/ember-cli#3235]
I just ran into an issue where I would generate a controller and my model stopped rendering. After some searching I found out that I should be creating an ObjectController. It would be nice to see a generate function for ObjectController.

**Comment by nathanpalmer** [comment]
AFAIK the ObjectController is going away in [Ember 2.0](https://github.com/emberjs/rfcs/pull/15). See the notes in _Routeable Component_ under _Transition Plan_.

**Comment by seawatts** [comment]
Alright thanks.
