### ISSUE TITLE
Livereload on linked add-ons

### ISSUE THREAD

**Issue by matthiasleitner** [ember-cli/ember-cli#3241]
For working on larger ember-cli based applications which utilize multiple internal add-ons it would be great to have the ability to extend live-reload to changes which occur in linked node_modules.

I already gave it a try by adding watchers similar to the server watcher to all symlinked directories in the node_modules directory. Unfortunately I haven't been able to figure out how to expand the broccoli-sane-watcher to also take care of the linked dependencies.

Any suggestions on how to approach this or other ways to improve the add-on development workflow?

**Comment by stefanpenner** [comment]
their is a not-well documented method you can add to your ember-addon entry file.

```js
isDevelopingAddon: function() {
  return true
}
```

and it will become "live". I hope eventually to make them all live, but we have some limitations in-regards to file-watching we need to fixup first.

**Comment by matthiasleitner** [comment]
@stefanpenner thanks!

**Comment by stefanpenner** [comment]
@matthiasleitner we should likely document this :P
