### ISSUE TITLE
Package ember-cli-test-loader not found

### ISSUE THREAD

**Issue by stebru** [ember-cli/ember-cli#3264]
Trying to run `bower install --save ember-cli-test-loader#0.1.1` as described here: https://github.com/ember-cli/ember-cli/releases/tag/v0.1.13, resulted in  `Package ember-cli-test-loader not found`

**Comment by rwjblue** [comment]
Should be fixed, please try again...

**Comment by stebru** [comment]
That was quick. Works, thx :)

**Comment by rwjblue** [comment]
Awesome!
