### ISSUE TITLE
Correct ember bower version

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3274]
The update to ember-qunit required ember 1.10.0

However the init method runs from the app blueprint which specifies 1.8.1.

https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L6

I assume it is safe to update to the latest 1.10.0?

**Comment by rwjblue** [comment]
No, it is not possible to change the default to 1.10.0 yet.  ember-qunit needs to make it a dev-dep I think.

/cc @dgeb

**Comment by jonathanKingston** [comment]
@rwjblue thanks for the quick response.

**Comment by jonathanKingston** [comment]
@rwjblue worth considering putting resolutions for core packages in the bower.json? That way running `bower install` will install all the ember-cli defaults and if developers want to change they would do at their own risk.

**Comment by jonathanKingston** [comment]
I'm closing this as 0.2.0-beta.1 defaults us to 1.10.0 and this is not likely to be fixed in time for this to still be an issue here.

Thanks for your help both.
