### ISSUE TITLE
Do not reorganize package.json after addon installation

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#3275]
I like to keep clear diffs for my commits. And I like to list the packages in package.json however I see fit. Doing:

```
ember install:addon ember-select-2
```

Will update `package.json`, but it will re-order the packages alphabetically, which is not what I want. `bower` and `npm` do not do this.

Just add the new package at the end of package.json, so we can see clearly what has changed.

**Comment by rwjblue** [comment]
This is an `npm` default, not something that ember-cli is doing specifically.

**Comment by rwjblue** [comment]
If you prefer to add them manually, you can absolutely do that, just add to the specific location in your `package.json` and run the generator (like `ember generate ember-select-2`).

**Comment by gonvaled** [comment]
@rwjblue - are you sure?

I have just:

```
npm install --save-dev forever
```

And the ordering of they keys in my package.json was preserved. `"forever": "~0.14.1"` was added at the **end** of the `devDependencies` (and yes, I have them out-of-alphabetical order).

So I think ember-cli is doing indeed something funky here.

**Comment by rwjblue** [comment]
What version of NPM are you using locally? Ember CLI is using 2.x on init and ember install. 

You may be using a version prior to them auto ordering.

**Comment by gonvaled** [comment]
Ok, I guess you are right.

```
» ember --version
version: 0.1.15
node: 0.10.25
npm: 2.1.8

» npm --version
1.3.10

» node --version
v0.10.25

» bower --version
1.3.12
```

(Which I must say surprises me a bit: I expected ember-cli to use the global npm)

**Comment by rwjblue** [comment]
@gonvaled - Your NPM is super old, we cannot use the global one for this exact reason.  The older NPM's have massive issues that have been fixed in 2.x.x....

**Comment by gonvaled** [comment]
It seems Ubuntu 14.04.1 LTS is indeed a bit behind ...

For reference:

```
» sudo apt-get install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version.

» lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```
