### ISSUE TITLE
Deploy Ember CLI App to Azure Website

### ISSUE THREAD

**Issue by tehmaestro** [ember-cli/ember-cli#3276]
Hi. I'm trying to deploy an ember-cli app to Azure Websites.
  When deploying to azure, you run a deployment script, which does the following:
 - npm install bower
 - npm install ember-cli
 - bower install
 - npm install
 - ember build

Well, it all seems to go well, until it hits the `ember build` step. I get an error:
```
this._handle.open(options.fd)

Error: EINVAL, Invalid argument
      at new Socket (net.js:156:18)
      at process.stdin (node.js:664:19)
      at ..... ember-cli\bin\ember:28:25
```

Searching around I found this link regardint the same problem with Grunt https://github.com/TryGhost/Ghost/pull/3608 
So, how would I disable stdin in Ember CLI? Any way I can do that, or any workaround so I can deploy the app?
  Thank you so much!

**Comment by stefanpenner** [comment]
Ember cli builds static assets you can deploy to any webserver

**Comment by tehmaestro** [comment]
Thank you, I was trying to make the build process run on azure .. I was wondering if someone else tried this. I guess I'll post this on stackoverflow.
