### ISSUE TITLE
Conflicts with ember-cli 0.1.15

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#3277]
```
» ember new yyy
version: 0.1.15
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installing browser packages via Bower...
  conflict Unable to find suitable version for ember
    1) ember >=1.4 <2
    2) ember 1.8.1
    3) ember >= 1.8.1 < 2.0.0
    4) ember > 1.5.0-beta.3
    5) ember ^1.10.0
[?] Answer: 
```

Some context:
```
» ember --version
version: 0.1.15
node: 0.10.25
npm: 2.1.8

» bower --version
1.3.12

» lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

**Comment by msalahz** [comment]
I think you should answer by 2 as ember 1.8.1

**Comment by gonvaled** [comment]
Maybe, but why this conflict? Is this a problem with my setup, or a problem with ember-cli 0.1.15?

**Comment by ohcibi** [comment]
I just did a clean `ember new embertest` and the conflict didn't happen.

**Comment by gonvaled** [comment]
I have verified: for me it does happen. @ohcibi : what ember version are you using? (I have added this info to the issue, for my setup)

**Comment by ohcibi** [comment]
I'm using 0.1.15 like you. I was telling it because I'd say it must be related to your personal setup. I do have a more recent node in fact, and whats your bower version?

```
~/test $ ember --version
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.36
npm: 2.1.8
~/test $ ember new embertest
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
ember new embertest  24.44s user 12.82s system 109% cpu 34.069 total
~/test $ cd embertest
~/test/embertest/ $ ember --version
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.36
npm: 2.1.8
~/test/embertest/ $ bower --version
1.3.12
```

**Comment by gonvaled** [comment]
@ohcibi - Bower same as you

**Comment by ohcibi** [comment]
I'm on OS X but that should not be important. Did you `npm cache clear && bower cache clean` ?

**Comment by gonvaled** [comment]
That solved the problem, but I do not like this solution. Why should I be forced to clean the global npm / bower cache? I have maybe important stuff there, used globally for other projects. Now I do not know what has broken in other projects: if ember-cli has a dependency on the global npm / bower (it obviously has, since cleaning the cache has solved the issue), I am pretty sure other packages have also dependencies there.

It would be know to know what was causing the conflict. I know that it was not npm (I have recovered it, was in version control), but I can not check the old bower cache (it was not kept under version control)

**Comment by ohcibi** [comment]
If you have stuff in your **cache** that cannot be recreated when needed, then there is something wrong with your other projects. It might be annoying to be forced to re download the stuff in other projects, but if they break because you cleared the cache, you need to fix those other projects.

You might file a feature request for npm and bower to be able to store caches locally or anything, but that's not an issue of ember-cli.

**Comment by joostdevries** [comment]
@gonvaled While it's far from ideal it's recommended to `npm cache clear && bower cache clean` on every upgrade.

**Comment by gonvaled** [comment]
@ohcibi & @joostdevries : ok, I think I was misunderstanding this. If I get it now, the npm / bower cache is only used to install **locally** the packages. That means, the cache is not used to run any command, but to install commands locally (or globally, depending on what you are telling npm / bower). So the only inconvenience is that a reinstall requires a re-download of (hopefully) the same packages used in the original install (if package.json and bower.json have not changed, of course)

That seems like a minor inconvenience, so it is ok.

But, that does not explain why was I getting a conflict ... `ember new` should be *using the right package in the cache*. Why is the cache broken? Stuff in the cache is versioned, so no conflict should arise ...
