### ISSUE TITLE
injecting bower dependencies from an addon into the client project

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#3280]
Project structure
--------------------
ember-cli-tooltipster (third party ember-cli addon project)
boilerplate (my own ember-cli addon that has ember-cli-tooltipster installed)
myProject (my own regular ember-cli project that has boilerplate installed)

Problem
-----------
ember-cli-tooltipster requires the tooltipster bower dependency, however I get the following error when running myProject.

```
Path or pattern "bower_components/tooltipster/js/jquery.tooltipster.min.js" did not match any files
```

I have tried adding the following to my boilerplate projects index.js file but the dependency is still not working:

```javascript
    afterInstall: function() {
        return this.addBowerPackageToProject('tooltipster');
    }
```

I don't want to have to add the tooltipster bower dependency to myProject as I have a number of projects using boilerplate and it would get unwieldy.  

Any ideas how to accomplish this?

**Comment by joostdevries** [comment]
some info on this was just added to the site in #3283 http://www.ember-cli.com/#default-blueprint
