### ISSUE TITLE
JS minification doesn't work outside of the dist folder

### ISSUE THREAD

**Issue by declanwhelan** [ember-cli/ember-cli#3284]
# Issue
When an outputPath is set in the brocfile to be anywhere outside the dist folder, minification is not performed on the JS files.

A full example of this can be found here: https://github.com/declanwhelan/ember-cli-uglify-bug. I have included coffeescript as that is what i use in the project this showed up in, but the bug is there even without coffeescript. 

# To Reproduce
Check out https://github.com/declanwhelan/ember-cli-uglify-bug/blob/master/Brocfile.js to see the outputPaths section has been set to show up in the main application folder in a subfolder called uglify-test. To see the issue, remove the outputpaths section and run 'ember build -prod' and look at the minified files, then run again with the paths reinstated and there'll be no minification.

**Comment by rwjblue** [comment]
Specifying an outputPath outside of the project directory roughly causes the concatenated output to be saved to that location directly during the concat step and is not maintained in the broccoli tree that is provided for uglification.

Concat step is done [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L836-847).

**Comment by rwjblue** [comment]
I suppose the solution to this would be to ignore outputPaths during the build pipeline, and do the moves from the default locations in the `postprocessTree` hook....

**Comment by btecu** [comment]
I'm running into this issue with `0.2.0`.

Example: https://github.com/btecu/path-min

**Comment by rwjblue** [comment]
The solution is to move the files to the specified outputPath's after postprocessTree has completed, that would ensure that the right files were minified, and then move them to the final location.
