### ISSUE TITLE
Chrome tries to load map files ember test --server debugger

### ISSUE THREAD

**Issue by seawatts** [ember-cli/ember-cli#3287]
I'm trying to have a `debugger` statement in an ember test. When running the tests I open chrome developer tools in the testem chrome window. It does not show any source because it is waiting to load the source maps:
```
// Please wait a bit.
// Compiled script is not shown while source map is being loaded!
```
Some of the tests work because the map files have already loaded by the time it gets to that test.

If I turn source maps and minification off then it will load just fine.

**Comment by rwjblue** [comment]
@seawatts - Using the latest version of ember-cli-qunit (0.3.7) and ember-cli-test-loader (0.1.1) should fix this issue.

**Comment by seawatts** [comment]
Thanks
