### ISSUE TITLE
Why executing ember serve build new version to dist directory with each change ? 

### ISSUE THREAD

**Issue by msalahz** [ember-cli/ember-cli#3290]
Hi , I'm using the last version 0.1.15 form ember-cli and today I noticed executing ` ember server ` initial build and incremental build regenerate new build to dist directory, Is this something normal ?

**Comment by rwjblue** [comment]
Yep, it is absolutely intentional.

**Comment by msalahz** [comment]
@rwjblue ,Is there a way to stop that ?

**Comment by rwjblue** [comment]
No there is no way to stop it, why would you want to?

**Comment by msalahz** [comment]
I thought I can always have a stable production build in it. and you use tmp directory for development build and building to dist directory is a blus and skipping it will enhance my build time  
Excuse me I'm new with ember-cli and I'm trying to get familiar with it

**Comment by rwjblue** [comment]
You can provide the `--output-path` option to use something other than `dist/`.  You could build to one directory for dev and a different one for prod, for example.

**Comment by msalahz** [comment]
Thank you very much for your fast response and such a great tool, You are doing an extraordinary effort.
