### ISSUE TITLE
Ember addon dummy app and helpers

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli#3291]
Writing helpers in an Ember addon, specifically how they are accessed by the dummy app, is not consistent with whether or not they are accessible by a consuming Ember application.

A simple example:

```js
// addon-name/addon/helpers/capitalize-string.js

export default function(string, options) {
  return string.capitalize();
}
```

```js
// addon-name/app/helpers/capitalize-string.js

import capitalize from 'addon-name/helpers/capitalize-string';

export default capitalize;
```

```hbs
{{!--addon-name/tests/dummy/templates/index.hbs--}}

{{capitalize-string 'hello'}} {{!--This works even though it shouldn't--}}
```

The above code makes the helpers work in the dummy app. However, installing the above addon in a consuming app will render an error along the lines of `cannot find component or property named capitalize-string`.

The way to make the helper accessible in the consuming application is:

```js
// addon-name/addon/initializers/register-helpers.js

import Ember from 'ember';
import capitalizeString from 'addon-name/helpers/capitalize-string';

export function initialize(/* container, app */) {
  Ember.Handlebars.registerHelper('capitalize-string', capitalizeString);
}

export default {
  name: 'register-helpers',
  initialize: initialize
};
```

```js
// addon-name/app/initializers/register-helpers.js

import Initializer from 'addon-name/initializers/register-helpers';

export default Initializer;
```

Shouldn't the dummy app behave the same way as a consuming app?

**Comment by ahouchens** [comment]
This is definitely something important to add to the documentation: How to use addon components/utils/helpers in your dummy app.

**Comment by stefanpenner** [comment]
> Shouldn't the dummy app behave the same way as a consuming app?

yes it should, and it appears to in all examples I have tried (and use)
