### ISSUE TITLE
Support root level proxies from testem and document onlyContentTypes

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3293]
To get parity with ember-cli proxy feature we should document the use of 'onlyContentTypes':
https://github.com/airportyh/testem/issues/496

As mentioned in the original issue, proxying at the root level isn't possible with Testem as it breaks the testing, https://github.com/ember-cli/ember-cli/issues/3227#issuecomment-73463386

The work here is:
- [X] Wait for the next testem relesase to be cut
- [X] Increment any package references, blueprints and documentation
- [ ] Add documentation around using the new key
- [ ] Add a block into http://www.ember-cli.com/#commonissues describing the symptom of the test server not working.

**Comment by jonathanKingston** [comment]
This is now in the prerelease of Testem: `testem@0.7.0-1`

**Comment by stefanpenner** [comment]
@jonathanKingston woohoo

**Comment by jonathanKingston** [comment]
@stefanpenner would you like me to document this and add to common issues also?

**Comment by stefanpenner** [comment]
@jonathanKingston ya

**Comment by stefanpenner** [comment]
@jonathanKingston friendly ping

**Comment by williscool** [comment]
So ive installed the latest testem and this is what my testem.json looks like

``` javascript
{ 
 "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "launch_in_ci": [
    "PhantomJS"
  ],  
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ],  
  "proxies": {
    "/api": {
      "target": "http://localhost:3000",
      "onlyContentTypes": ["xml", "json"]
    }   
  }
 }
  
```

and its not using the proxy at all :(

**Comment by stefanpenner** [comment]
@jonathanKingston friendly ping

**Comment by stefanpenner** [comment]
will gladly reopen if someone would like to champion this
