### ISSUE TITLE
Unable to pass -g (growl) option to testem via ember test command

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3294]
I'm unable to pass -g (growl) option to testem via ember test command, this should be enabled. Or is there any other way to enable notifications when running only PhantomJS in `ember test -s`?

**Comment by joostdevries** [comment]
You should be able to set `growl: true` in testem.json.

**Comment by Kuzirashi** [comment]
Thanks I haven't tried that because it wasn't listed in `Config-level options` [here](https://github.com/airportyh/testem/blob/master/docs/config_file.md).
