### ISSUE TITLE
Clean pull w/ failing tests

### ISSUE THREAD

**Issue by MrJadaml** [ember-cli/ember-cli#3296]
Did a pull of CLI and ran the test suite and got 11 failing. Is this a known thing or should I wait to make a PR until those have been resolved? Ran the tests again after my addition and still got 11 failing (no new fails)

**Comment by rwjblue** [comment]
There should be no failing tests on master, most likely the failures are due to a missing dependency.

This is usually solved with a `rm -rf node_modules .node_modules-tmp .bower_components-tmp && npm cache clear && npm install`.

**Comment by rwjblue** [comment]
Closing, but please let us know if the above does not fix it and I'll reopen.

**Comment by pzuraq** [comment]
I am also having tests fail, even after clearing node_modules and the tmp directories.

This test fails every time, without fail:

```
2) Acceptance: smoke-test ember new foo, build development, and verify generated files:
     AssertionError: expected fewer than 21 files in dist, found 21: expected [ Array(21) ] to have a length below 21 but got 21
```

Here's a list of the files it finds:

```
[ '.metadata_never_index',
  'assets/',
  'assets/ember-data.js.map',
  'assets/failed.png',
  'assets/passed.png',
  'assets/some-cool-app.css',
  'assets/some-cool-app.js',
  'assets/some-cool-app.map',
  'assets/test-loader.js',
  'assets/test-support.css',
  'assets/test-support.js',
  'assets/test-support.map',
  'assets/vendor.css',
  'assets/vendor.js',
  'assets/vendor.map',
  'crossdomain.xml',
  'index.html',
  'robots.txt',
  'testem.js',
  'tests/',
  'tests/index.html' ]
```

My thought is `.metadata_never_index` might be causing the problem?

There are three other tests that fail inconsistently, below is one of them, I can't get the other two to fail right now but if I do I'll post them as well.

```
 1) Acceptance: express server restart Server restarts successfully on multiple copies:

      Test file has correct contents after second copy.
      + expected - actual

      +"true true"
      -"Copy2 contents of A. Copy2 contents of B."
```
