### ISSUE TITLE
Test-specific EmberENV

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#3299]
If you run `ember serve` in dev mode, and visit the `/tests`, you end up with two conflicting EmberENV configs.

The one in `<meta>` correctly contains the test environment, but it gets ignored. The one at the start of `vendor.js` will contain the dev environment, and it gets used.

**Comment by bjornstar** [comment]
Yeah, this is very frustrating.

I get the feeling that `ember test --server` is the "standard" for testing and visiting `/tests` on `ember serve` is not supported. Personally, I prefer running `ember serve` so that I can run my app and my tests at the same time against the same code.

**Comment by stefanpenner** [comment]
Both should be made to works as expected

**Comment by rwjblue** [comment]
Agreed, I'm pretty sure this can be fixed fairly easily. Will look at it in more detail in the morning.

**Comment by sohara** [comment]
:+1: We are using `baseURL` in one of our apps. Testem needs baseURL to be set to '/' but that prevents us from simply hitting '/tests' in our dev environment to run the tests.

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/ember-cli/ember-cli/issues/4535
