### ISSUE TITLE
Tests are failing locally but Travis & Appveayor are green

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-cli#3304]
I just encountered a weird problem where `npm test` on local produces 1 failing test on 2 separate machines but it TravisCI & AppVeayor are green for the same commit. 

Why could this be?

![banners_and_alerts_and_1__tarasmankovski_tarass-macbook-pro____repositories_ember-cli__zsh_](https://cloud.githubusercontent.com/assets/74687/6220881/b0ba4932-b609-11e4-87f8-954c5265e348.png)

/cc @rwjblue

**Comment by alexlafroscia** [comment]
Mine was the other machine that had this happen locally, if I can be of any help figuring this out.

**Comment by rwjblue** [comment]
This was fixed a day or two ago (was a missing return in a test), don't have the PR handy though.
