### ISSUE TITLE
Memory leak v0.1.12

### ISSUE THREAD

**Issue by bjornstar** [ember-cli/ember-cli#3305]
PID 1672 was running for a few days
PID 18167 was a fresh start

| PID | USER   |   PR | NI |   VIRT  |  RES  |  SHR | S | %CPU | %MEM |    TIME+ | COMMAND |
|------|------------|--------|-----|----------|--------|------|----|------|-------|--------|--------|
| 1672 | bjorn  |   20 |   0 | 2469088 | 1.490g |  8852 | S |  0.0 | 9.6 | 19:01.76 | ember |
| 18167 | bjorn |    20 |  0 | 1097528 | 186104 |  8824 | S |  0.0 |  1.1 |  0:18.48 | ember |

I can take a heapdump once it grows again and see what's being held onto.

Not sure if previous versions also suffered the same issue.

**Comment by bjornstar** [comment]
It looks like broccoli's `allTreesRead` is growing without bounds. It's got references to everything and never gets cleaned up.

**Comment by stefanpenner** [comment]
@bjornstar ya, I am aware of this.

This issue should be reported on the broccoli repo: https://github.com/broccolijs/broccoli

**Comment by stefanpenner** [comment]
Closing this, as it isn't actionable from the this project. We can continue tracking and discussion on the broccoli side of things.
