### ISSUE TITLE
[META] Improve docs structure

### ISSUE THREAD

**Issue by joostdevries** [ember-cli/ember-cli#3307]
The emberjs.com guides will start using Ember CLI examples in the rewrite that is starting now (meta-issue: emberjs/website#1994). Tracking the ember-cli.com part of this effort in this issue. 

The idea for the final situation is that emberjs.com contains all info relevant for Ember app developers and ember-cli.com will focus on Blueprint and Addon developers.

We've had plenty of docs issues (#2589, #2120) but I want to have a sitemap which clearly states what goes where first, then we can look at implementation (perhaps reopening #2589).

### About
- Rationale
- Overview
- Community (Tutorials, Stackoverflow, GH, IRC)
- Contributing

### Guide (will move to emberjs.com)
- Installing (getting started)
- Creating your app (getting started, scaffolding, naming, ember data)
- Configuration (environments)
- Tests
- Managing dependencies (asset compilation, using addons)
- Upgrading Ember CLI
- Common issues (Editors, common issues, deployment issues)

### Addons
- What is an Addon (core concepts, architecture)
- Client-only or integrated (If people are just redistributing a component we should minimize their exposure to CLI internals IMO)
- Hooks (link to API docs)

### Blueprints
- What is a blueprint (core concepts, architecture)
- Hooks (link to API docs)

### Other changes
- Remove changelog (point to GH)
- Compress Overview + Why into few sentences on home

## Process
- Figure out how to easily publish API docs

**Comment by joostdevries** [comment]
@chnn thoughts?

**Comment by chnn** [comment]
Looking great! I'm real happy to see everything under the *Guide* section moving to emberjs.com. I have no issues with this structure and thing the nesting is logical. Somethings things I wonder:

- Is the *Blueprints* section exclusively for developing blueprints? Or just using them through `ember generate`? I always thought it strange how the current site groups together both how to consume and how to develop blueprints. Seems like the usage of blueprints through `ember generate` would go best in the guide (this may already be the plan).
- Right now there's an `ADDON_HOOKS.md` in the root of the repo which serves as the docs for addon hooks. It seems with the guide moving to emberjs.com, ember-cli.com becomes much more geared towards advanced users looking to extend ember-cli. In this case, I think the content of `ADDON_HOOKS.md` would be better directly included in the site.

I think it's also worth considering how to integrate the link to the guide, links to api docs, and content on the ember-cli.com site so it feels cohesive, but that may be worth tackling after this gets further along (e.g. we should integrate/theme the generated YUIDocs so they feel good alongside the *Addons* and *Blueprints* section).

**Comment by joostdevries** [comment]
@chnn **yes**:
- Blueprint consumption and development are indeed two separate worlds. The first belongs in the Guides section, the second in a separate section
- Personally, I think ADDON_HOOKS should be a temp thing and should ultimately be fixed in API docs.
- The entire thing should be cohesive. For a first shot we can get away with the default yuidoc template but ultimately having a more integrated feel would be awesome.

**Comment by joostdevries** [comment]
@chnn @jonharmon I just noticed that the proposed structure could probably fit in the current design too, by using an accordeon and dropping the infinite scroll. The `User guide` button on the home page would then be split into `About` `Guide` `Addons` `Blueprints`.

**Comment by chnn** [comment]
@joostdevries I like that idea a lot. I'm a little overloaded between work and EmberConf right now, but in a few weeks I'm happy to make a PR for ember-cli.com with a more nested navigation. It like an nonintrusive change that adds a lot of value.

**Comment by filipelinhares** [comment]
@chnn if you need some help, let me know.

**Comment by joostdevries** [comment]
Fixed in #3431
