### ISSUE TITLE
How do I skip certain files in Ember Build?

### ISSUE THREAD

**Issue by sameersegal** [ember-cli/ember-cli#3308]
I am interested in creating a vendor.js from (bower dependencies + static scripts) and place it at a CDN. I have a few Ember-Cli projects but I want to have a common project for dependencies. 

I would like to skip app and tests folder, but I keep getting errors unless I create app/index.html and app/styles.

```
.
├── Brocfile.js
├── app
│   ├── index.html
│   └── styles
├── bower.json
├── bower_components
├── node_modules
├── package.json
└── tmp
```

Brocfile.js
```
/* global require, module */

var removeFile = require('broccoli-file-remover');

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// app.import("vendor/css/common.css");
// app.import("vendor/js/utils.js");
// app.import("vendor/js/md5.js");

/* Bootstrap assets */
app.import('bower_components/bootstrap/dist/css/bootstrap.min.css');
app.import({
	development: 'bower_components/bootstrap/dist/js/bootstrap.js',
	production: 'bower_components/bootstrap/dist/js/bootstrap.min.js'
});

// Doesn't seem to be working
var filteredTree = removeFile(app.toTree(), {
  paths: ['app/index.html','tests/index.html']
});


module.exports = filteredTree;
```

dev build (ember build) results in an error unless tests/index.html exists. ember build --environment production works however

I get the following error:
```
$ ember build
version: 0.1.15
Building.Warning: failed to stat config
Build failed.
Path or pattern "index.html" did not match any files
Error: Path or pattern "index.html" did not match any files
```

**Comment by stefanpenner** [comment]
ya we should make more stuff optional

**Comment by rwjblue** [comment]
> ya we should make more stuff optional

I agree, but I don't think making the app optional makes much sense.  All of our vendor deps are already optional, and if you just need to concat files for vendor, there are much better tools for that.

**Comment by sameersegal** [comment]
I agree with you. However,  `removeFile` doesn't seem to be working. Is there a work around - happy to implement things if you can point where I can start.

```
// Doesn't seem to be working
var filteredTree = removeFile(app.toTree(), {
  paths: ['app/index.html','tests/index.html']
});
```

**Comment by stefanpenner** [comment]
seems to have gone stale, will likely be improved as part of some future work

**Comment by afn** [comment]
FYI, `removeFile` does seem to work, but your paths were slightly off, and the key should be `files`, not `paths`:

```javascript
var filteredTree = removeFile(app.toTree(), {
  files: ['index.html','tests/index.html']
});
```

In my build, I also remove `testem.js` and the entire `tests` directory:

```javascript
var filteredTree = removeFile(app.toTree(), {
  files: ['index.html', 'testem.js'],
  paths: ['tests']
});
```

**Comment by stefanpenner** [comment]
@afn if you have a chance, might be a good submission to the website. Maybe señior @leo has some suggestions.

**Comment by stefanpenner** [comment]
@afn are you using https://github.com/rwjblue/broccoli-file-remover ?

**Comment by stefanpenner** [comment]
i've opened an issue on BFR https://github.com/rwjblue/broccoli-file-remover/issues/8

**Comment by leo** [comment]
@afn @stefanpenner Sounds like a great addition! I'd say add a section called "Skip certain files", but I'm not sure to which section. What do you guys think? "Asset compilation", maybe (although those files aren't necessary assets)? Or "Deployment"?

**Comment by stefanpenner** [comment]
I believe we should add a new section called "the build" or similar, this can discuss how to configure/enhance the build.

**Comment by leo** [comment]
Great idea! As you can see, I've created a PR containing the new section. I think we, @afn and @sameersegal should discuss there what should be added. :blush:

**Comment by stefanpenner** [comment]
:)
