### ISSUE TITLE
Some acceptance tests are false positives

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#3310]
I'm trying to test some custom blueprints for initial project setup, so I was looking how we test `ember new`. Then I noticed that we have several false positives.  For instance, [this test](https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/new-test.js#L58) will always be true due to the fact that `confirmBlueprinted ` [returns a closure](https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/new-test.js#L35).

**Comment by stefanpenner** [comment]
cc @trabus / @twokul  / @joostdevries

**Comment by joostdevries** [comment]
this was introduced in #462. Personally I'm afraid we're going to have this happen a lot unless we start documenting our helpers.

**Comment by stefanpenner** [comment]
> Personally I'm afraid we're going to have this happen a lot unless we start documenting our helpers (more)

yes, agreed.

**Comment by stefanpenner** [comment]
largely fixed
