### ISSUE TITLE
How can I distinguish between files from addon packages and those from the current project?

### ISSUE THREAD

**Issue by sglanzer** [ember-cli/ember-cli#3318]
I'm working on an enhancement to the code coverage in ember-cli-blanket and I'd like to scope the coverage to only the files that are found in the current project.

Currently all files in or copied to the app directory during the build are instrumented, so the coverage reports include addon projects.  Is there a particular brocolli tree I can query to get this information or a better hook for instrumenting the classes?

Also, utility classes (and other classes that must be explicitly imported) don't appear in the requirejs module listing.  How/when are those classes loaded?  I'd like to make sure all files in the current project have coverage.

**Comment by stefanpenner** [comment]
Not currently, in all honestly `app/*` in an add-on should be extremely thin and likely wont cause much grief.  That being said, I can imagine some more aggressive style guides that may conflict.

**Comment by sglanzer** [comment]
Fair enough, you're right that best practices for addons should minimize this and it's certainly not a pressing need.

That said, I've seen enough addons that pollute the app space to say that this is still something I'm interested in eventually.

On a side note - addon development is still somewhat magical and requires a lot of digging in the source/addon repos.  Is there any current activity to address the lack of documentation around the process?

**Comment by stefanpenner** [comment]
> On a side note - addon development is still somewhat magical and requires a lot of digging in the source/addon repos. Is there any current activity to address the lack of documentation around the process?

some API hooks: https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md

@rwjblue has also been teasing a related blog post. Although I am unsure of the eta.

**Comment by sglanzer** [comment]
Cool, I'll look forward to that blog post.

Obviously this is still in flux during pre-1.0 development, so I know digging through code is the standard.  I had seen the addon hooks page, definitely useful, but still missing some things (e.g. treeFor examples).

I'm pretty much completely off topic at this point, just wanted to highlight the experience.  The best analogy I can think of currently is the experience a few months ago of reading the examples on the Ember site, then trying to translate into using ES6 in ember-cli; I have the same experience looking at broccoli examples and then trying to create addons for ember-cli.

Not that it'll stop me, just slow me down for a bit.

**Comment by Turbo87** [comment]
@sglanzer is this issue still relevant?

**Comment by sglanzer** [comment]
@Turbo87 Probably not relevant enough - we have workarounds for now and I would imagine this will change once the new file structure system comes in, so it's fine to de-prioritize/close this.

**Comment by Turbo87** [comment]
@sglanzer okay, thanks for the feedback
