### ISSUE TITLE
Simplified update/install process

### ISSUE THREAD

**Issue by technomage** [ember-cli/ember-cli#3320]
It would be helpful for new users, or simplified projects to have a more streamlined install process.  I suggest the following options be added to "ember install" and "ember update" --clean will remove bower_components and node_modules and clear caches.  This can resolve many issues and should be easy to invoke.  Second, add --auto to automatically update npm modules, then do any required generate, then update bower modules.  This may require a hook for the add-ons to specify a default generate that updates bower dependencies.  Basically there should be a set of options that "just does the right thing" and gets a project in a state consistent between specified add ons and all dependencies in both package managers.

**Comment by stefanpenner** [comment]
if you have a proposal, https://github.com/ember-cli/rfcs is a better venue.

please review: https://github.com/ember-cli/rfcs/blob/master/0000-template.md and other proposals for a reference on how this proposal should be formed.

**Comment by technomage** [comment]
Thanks.  I saw the ember rfcs process, but given the different org, was not sure this followed that.  Will do.

**Comment by stefanpenner** [comment]
> Thanks. I saw the ember rfcs process, but given the different org, was not sure this followed that. Will do.

it is the same org
