### ISSUE TITLE
Running ember test for addons under 0.2.0.beta-1 doesn't produce any output

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli#3321]
See https://travis-ci.org/paddle8/ember-document-title

When I run the tests via `ember server`, I can run tests. For some reason, `ember test` doesn't work though. :/

**Comment by stefanpenner** [comment]
@tim-evans did u confirm all the bower deps and package.json deps updated? I believe i ran into this earlier and but the `ember init` update seemed to resolve it.

**Comment by tim-evans** [comment]
Yeah, I just ran ember init and everything's up to date

**Comment by stefanpenner** [comment]
thanks for checking

**Comment by tim-evans** [comment]
The tests just passed. Weird. Maybe it was how the component works? @_@

**Comment by stefanpenner** [comment]
also seem to work for me... Let's close this until we have a reproducible issue.
