### ISSUE TITLE
CTRL+C does not abort `ember build` process.

### ISSUE THREAD

**Issue by robertolicious** [ember-cli/ember-cli#3324]
**Expected:**

    $ ember build -w
    Building..^C
    $ 

**Got:**

    $ ember build -w
    Building..^C^C^C^C^D^D^X^X^Z
    // ember-cli continues to build

**Scenario:**

I have a large project and want to stop build midway because I recognized a mistake. I'm used to closing apps with `ctrl+c`, so I try combo, but it does not terminate the process. Instead it caries on with processing, then displaying JSHint output, and only then terminating.

**Node environment**

    $ node -v
    v0.12.0
    $ npm -v
    2.5.1

**System**

    $ sw_vers 
    ProductName:    Mac OS X
    ProductVersion: 10.9.3
    BuildVersion:   13D65

**Ember-CLI**

    ember -v       
    version: 0.2.0-beta.1
    node: 0.12.0
    npm: 2.1.8
    
(interesting to note that npm -v is different from ember -v npm version)

**Comment by Kuzirashi** [comment]
I'm experiencing same issue in similiar circumstances.

**Comment by stefanpenner** [comment]
i _believe_ this is a node deficiency :(

**Comment by rwjblue** [comment]
Most of the I/O in Broccoli-land is synchronous, and therefore cannot be killed with Ctrl+C.  I do not think this is possible to fix in ember-cli.
