### ISSUE TITLE
Replace broccoli-sass integration with ember-cli-sass

### ISSUE THREAD

**Issue by ventismith** [ember-cli/ember-cli#3325]
Currently on the website, the suggested integration for getting sass to work in ember-cli is to use broccoli-sass and it gives the code `ember install:npm broccoli-sass`. Unfortunately, with the current build of node (0.12.0), this doesn't work at all.

[broccoli-sass](https://github.com/joliss/broccoli-sass) requires an old version of node-sass that is incompatible with node 0.12.0. You can get around this by npm installing either from a pull request that has been submitted with the fix or by downloading the source file, editing it's dependencies yourself and then installing. I tried both of the solutions above and in the absence of any further integration instructions on the website, both my css and sass files refused to compile. In any case, neither of these are long term solutions and make addon management problematic.

After much trial and error (about a week's worth), my suggestion would be to integrate [ember-cli-sass] (https://github.com/aexmachina/ember-cli-sass) instead. The project seems to be more active and the instructions for getting sass running worked flawlessly.

**Comment by stefanpenner** [comment]
Is there an issue open on broccoli-sass ?

**Comment by ventismith** [comment]
There are a couple, and open PR's with fixes.

**Comment by walter** [comment]
I worked around the issue by editing package.json to use 0.6.0 of broccoli-sass (was previously 0.3.3).

**Comment by stefanpenner** [comment]
broccoli-sass latest should work correctly here.
