### ISSUE TITLE
ember build generates improper dist/index.html

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3327]
With 0.1.15

None of the build/server related command generate the correct `dist/index.html`.
The assets are always finger printed, but the finger prints do not match up, even when the assets have finger prints.

I deleted the `dist` and `tmp` folders, but still no luck..

**Comment by stefanpenner** [comment]
@knownasilya it sounds like one of your dependencies is out-of-sync. Likely broccoli-asset-rev.

**Comment by knownasilya** [comment]
I also did `npm cache clean && bower cache clean && rm -rf node_modules bower_components && npm install && bower install`

**Comment by knownasilya** [comment]
The version of `broccoli-asset-rev` is 2.0.1 in the node modules and 2.0.0 in the package.json

**Comment by knownasilya** [comment]
Using 2.0.0 doesn't fix it.

**Comment by knownasilya** [comment]
Seems like checking everything out fresh fixed it.. not sure what it was though..
