### ISSUE TITLE
broccoli-emblem-compiler causes crash

### ISSUE THREAD

**Issue by satansdeer** [ember-cli/ember-cli#3328]
There is a problem with broccoli-emblem-compiler (0.3.19) in ember-cli 0.1.9, 0.1.15, 0.2.0-beta.1

Steps to reproduce:
1. Create new project with `ember new`
2. Install broccoli-emblem-compiler package
3. Change app/templates/application.hbs to emblem template
4. Add "If" statement. For example:
``` javascript
if test
    p Test
```
Run `ember s`
You will get an error
`Cannot read property 'original' of undefined`

**Comment by stefanpenner** [comment]
I don't think emblem works correctly anymore, but it doesn't have anything to do with ember-cli. Rather emblem doesn't work with handlebars correctly.

cc @mixonic  I believe you are working on something related.

**Comment by mixonic** [comment]
I'm not familiar with this error. @satansdeer you are sure you are using a compatible version of Emblem and Ember/Handlebars?

I suggest you report this upstream on broccoli-emblem-compiler, or on the addon repo.

**Comment by stefanpenner** [comment]
feel free to continue the discussion, I suspect the emblem side of things just is not compatible with the latest ember and htmlbars.

**Comment by satansdeer** [comment]
@mixonic how to make sure that version is compatible? I just tried to use latest versions. Anyway I'm going to open an issue on broccoli-emblem-compiler.

**Comment by aruseni** [comment]
Currently this can be fixed with specyfing emblem version in package.json:
    …
    "emblem": "0.3.18",
    …
