### ISSUE TITLE
Remove Support for Node 0.10

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3329]
A warning was added in https://github.com/ember-cli/ember-cli/pull/3326, and will live through the 0.2.x series.  

This issue is meant to keep track of removing support for 0.10 in 0.3.0.

- [x]  ensure common c-extension all work

**Comment by stefanpenner** [comment]
as large swaths of my employer's infrastructure is stuck on 0.10, we will likely not make this change for some time... closing.

**Comment by ErisDS** [comment]
I'm a bit confused as to what is happening with 0.10 support and wanted to come by to check. This issue says it's not being dropped, yet, but the error message says:

> DEPRECATION: Node v0.10.38 is no longer supported by Ember CLI. Please update to a more recent version of Node

This makes it sounds like 0.10 support is gone completely already?

Ghost is following Node LTS, so if Ember-cli or Ember drop support for 0.10 before LTS ends in October, we're going to end up in a really difficult situation where our software cannot be built on a platform that we officially support, or we're going to have to drop behind in terms of our ember/ember-cli versions cc @kevinansfield.

**Comment by stefanpenner** [comment]
We can change the warning to match nodes lts stance on 0.10

**Comment by ErisDS** [comment]
@stefanpenner that'd be great, I was more interested in what the official ember-cli plan is :wink:

**Comment by rwjblue** [comment]
@ErisDS - TBH, I don't think we have an official plan on this just yet.  I agree that we should decide on our position and make it clear on the website/deprecations/etc.

**Comment by stefanpenner** [comment]
So the reality is, we really don't want to support the `npm` that is shipped with node 0.10, as that version of NPM (1.x) is basically foo-bar'd, and using it is basically rolling the dice each and every time. This is likely incompatible with your `LTS` plan, but you can tell node 0.10.x users to upgrade to a reasonable `npm` (maybe something in 2x) and they will have a better time.

**Comment by ErisDS** [comment]
There is a special release of npm with the latest node 0.10, with a banner warning, and the next version (0.10.42) should ship with npm 2. I think it's sensible to get people to upgrade to npm 2, I'm all too aware of how much pot luck there is with in stalls on npm 1 :) 

Node 0.10 usage generally falls into 2 categories now I think - 1) people who have ubuntu LTS and get 0.10.25, and 2) new users who installed the latest version and so at least have something in the high 30's. For security reasons, it's also generally a good idea to encourage users to at least be running the most recent version of 0.10.

**Comment by stefanpenner** [comment]
We should update our warnings to take this into account.

**Comment by stefanpenner** [comment]
I think we accomplished our goals, without need to drop 0.10.x. my work and some of our consumers (like ghost still need it) So we will keep it around for some time yet..
