### ISSUE TITLE
double quotes appearing in some files

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-cli#3330]
I just started a bunch of ember projects

*ember new project-name*

In one of the projects, the router.js has double quotes. I keep running into files with double quotes. I'm trying to keep track. index.html has double quotes in both projects. Is this on purpose?

![screen shot 2015-02-20 at 12 35 24 pm](https://cloud.githubusercontent.com/assets/2066617/6308910/1eac5106-b8fd-11e4-9df9-35ec4022467d.png)

![screen shot 2015-02-20 at 12 36 07 pm](https://cloud.githubusercontent.com/assets/2066617/6308912/22d2a32a-b8fd-11e4-8c28-5f6878a2247f.png)

Looks like the double quotes only show up in the router.js - after you generate a route

**Comment by rwjblue** [comment]
This was fixed in https://github.com/ember-cli/ember-cli/pull/3182, and has been released in versions since 0.1.13.

**Comment by sheriffderek** [comment]
Cool.

I'm using version 0.1.5 - for the record.

**Comment by stefanpenner** [comment]
@abuiles ^^

**Comment by stefanpenner** [comment]
> I'm using version 0.1.5 - for the record.

the problem manifests in 0.1.5 still?

**Comment by rwjblue** [comment]
@stefanpenner  - 0.1.5 is less than the fixed version of 0.1.13.

**Comment by stefanpenner** [comment]
i can't math
