### ISSUE TITLE
Improve blueprint help output method (markdown support)

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3331]
As per discussion in [#3316](https://github.com/ember-cli/ember-cli/pull/3316#issuecomment-75205628), we should simplify the way blueprint help content is added. With the addition of #3316 we can add a `printDetailedHelp` hook to print help output. The [current way the output is built](https://github.com/ember-cli/ember-cli/blob/master/blueprints/model/index.js#L51) is pretty primitive and not a pattern I'd like to endorse moving forward.

I'm thinking that we can simplify this by adding a default printDetailedHelp method that will look for a `README.md` or `HELP.md` in the blueprint root folder then parse (likely a specific section of it) and return the output formatted for the terminal. 

Writing the help text in a format that can be parsed into color text may be a bit challenging, but I figured we could write a lexer for it. The [marked](https://github.com/chjj/marked) library looks pretty good, and [ought to do the job](https://github.com/chjj/marked#access-to-lexer-and-parser).

**Comment by trabus** [comment]
Looks like [marked-terminal](https://github.com/mikaelbr/marked-terminal) may do most of what I need out of the box. Though custom color markup (and a lexer to recognize it) will need to be defined. I was thinking something like `^color^` could work for marking the different colors. So `^cyan^text goes here^cyan^` would be for cyan, `^yellow^` for yellow, and so on.

**Comment by stefanpenner** [comment]
This is a great idea

**Comment by trabus** [comment]
So after some investigation, it appears that marked it isn't as easily extensible as I'd hoped. You can override existing tokens, but adding new ones is a whole different story. 

What I'm intending on doing instead is parsing the `README.md` with marked first, then doing a string replace afterwards to support the custom color tokens. Something like:
```
var tokens = {
  cyan: /(?:\^cyan\^)(.*?)(?:\^cyan\^)/,
  green: /(?:\^green\^)(.*?)(?:\^green\^)/
};
var renderer = {
  cyan: function cyan(match, p1){
    return chalk.cyan(p1);
  },
  green: function green(match, p1){
    return chalk.green(p1);
  }
};

// then later
marked(input).replace(tokens.cyan,renderer.cyan);
```

I'll probably get an array of the tokens used in the string, then loop through them to run the replacement. I'm probably going to add something to look for [these patterns too](https://github.com/ember-cli/ember-cli/blob/master/ARCHITECTURE.md#formatting-colors), that would occur before the `^color^` tokens so they could be overridden if needed.

**Comment by trabus** [comment]
Ignore the content of the test md file, but I think I've got a pretty good start. The first section is the first pass with marked, then the second section is after parsing the color tags. I'm going to put it into a util method tomorrow and get a PR started for review.

![7u9mw5trym-2000x2000](https://cloud.githubusercontent.com/assets/324797/6318531/154f2a98-ba4c-11e4-9a40-82ebbc2fac4c.png)

**Comment by joostdevries** [comment]
@trabus this looks awesome.

**Comment by stefanpenner** [comment]
this has landed!
