### ISSUE TITLE
Watching files in directory with specified handler/task in Addon

### ISSUE THREAD

**Issue by Panoplos** [ember-cli/ember-cli#3334]
Hello, I am working with an Addon that currently depends on an external build system (Gulp), and I would like to be able to invoke this builder whenever certain files in (a) specified directory/ies have changed. Right now, I am using an RSVP Promise when the `.included(...)` hook is called, but this is not a great solution.

### Ideal Solution

Inside of the Addon's `package.json` file, be able to specify a list of directories/files and an assets "changed" handler, like:

```js
"ember-addon": {
  "main": "addon-main.js",
  "watch": {
    "assets" :  {
      "path/to/assets/dir",
      "path/to/other/assets/file.ext",
      ...
    },
    <optional: otherwise defaults to Addin.assetChanged>
    "changed" : "tasks/change-handler.js"
    </optional>
  },
  ...
```

This would result in either `Addon.assetChanged(tree)` being called with a `tree` of the changed assets, or the `changed` task being run with the same. Of course, all the `preBuild`, `postBuild`, etc. hooks would still be invoked.

From what I understand currently is that you can only register "preprocessors" for certain file types, which really limits the ability to do something like RT rebuilding of resources that depend on different tool chains, like Semantic UI (which depends on Gulp).

**Comment by stefanpenner** [comment]
This doesn't appear to be on anyones critical path, if it is I would recommend taking the RFC route.
https://github.com/ember-cli/rfcs/
