### ISSUE TITLE
Test addon blueprints and other non-running-app-related stuff

### ISSUE THREAD

**Issue by ohcibi** [ember-cli/ember-cli#3340]
When trying to write tests for the ember-cli-coffeescript addon, I noticed that with the defaults test setup, one cannot test cli-related stuff, that is provided by addons (e.g. blueprints). The tests run with qunit, which must run in a browser, which cannot issue any special cli commands like for example `ember generate`.

I tried to overcome this by using mocha and node as test runner, which allows access to cli. However the dummy app in `tests/` is not actually involved with cli. `ember generate` would even use the addons blueprints, but would install them into the addons `app/` directory, which is not the right thing for a test.

So it feels like ember-cli is not quite ready for this?.

**Comment by stefanpenner** [comment]
seems like we may want test helpers to enable this in addons

**Comment by ohcibi** [comment]
Yep. Something like

```javascript
module("Acceptance: command", {
    setup: function() {
        initApp();
    },
    teardown: function() {
        purgeApp();
    }
});

test("a command", function() {
    runCommand("generate", "controller", "foo");
    wait();
    assertFile(....);
});
```

**Comment by mattmarcum** [comment]
I'm in the same boat, I've got some very complex blueprints that I need to unit test.  I wrote a unit test for an ember-cli feature not to long ago: https://github.com/ember-cli/ember-cli/pull/3199 and I extended the unit tests that existed before for model/blueprint.  So I think we could structure a helper very similar to that one.  I'm at the airport about to fly out to pdx for emberconf, so hit me up if you want to pair on this.

**Comment by mattmarcum** [comment]
This is actually tougher than I thought because we'd want to run some tests in node and others under a browser (phantom/chrome/ff/etc)...  I'm not seeing a good way to get testem to do that.

**Comment by stefanpenner** [comment]
I agree, but this needs RFC. Closing as now that we have an RFC process these "wish" issues are no longer needed

**Comment by nathanhammond** [comment]
https://github.com/ember-cli/ember-cli-blueprint-test-helpers
