### ISSUE TITLE
Intent to support a default disable of native type extensions

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3342]
Because of the very justified limitation in Babel to isolate Realms: https://github.com/babel/babel/issues/868#issuecomment-75477497

To reduce the risk of users needing to migrate lots of code, I suggest either:
- Warning users in the documentation
- By default setting `EXTEND_PROTOTYPES` to false.

and providing documentation linking to this article: http://emberjs.com/guides/configuring-ember/disabling-prototype-extensions/

The post native code could provide a shim per module instead perhaps?
Similar code to:
```
import extender from 'Ember';
extender();
```

**Comment by stefanpenner** [comment]
> By default setting EXTEND_PROTOTYPES to false.

disabling this has some pretty hefty implications, especially around performance. I do have plans from ember 2 -> 3 to remove the need for this

**Comment by jonathanKingston** [comment]
I think I'll be changing all my app code to using computed properties so migrating to native (whenever that will be - 5 years for decent adoption perhaps) will be lighter.

Is it worth a mention in the documentation that the change might happen?

**Comment by rwjblue** [comment]
I'd be in favor of disabling all but the array extensions (`Function` and `String` extensions can be disabled independently of the others), but we already have a large enough issue with documentation being different than what is taught on emberjs.com that I am hesitant to actually suggest this.

**Comment by jonathanKingston** [comment]
@stefanpenner also by performance do you mean developer writing code performance or cpu/memory out of interest.

Is there any upcoming change in the these prototypes in the Ember roadmap?

**Comment by rwjblue** [comment]
@jonathanKingston - By not extending the native array prototypes, Ember has to extend every array that it returns from many of the internal methods.  So, disabling prototype extensions leads to a negative performance impact of the application at runtime.

**Comment by stefanpenner** [comment]
> @jonathanKingston - By not extending the native array prototypes, Ember has to extend every array that it returns from many of the internal methods. So, disabling prototype extensions leads to a negative performance impact of the application at runtime.

yes this, although their is a solution to this as well.  `Ember.pushObject(array, object)` etc.

> I'd be in favor of disabling all but the array extensions (Function and String extensions can be disabled independently of the others), but we already have a large enough issue with documentation being different than what is taught on emberjs.com that I am hesitant to actually suggest this.

I personally also like this.

**Comment by jonathanKingston** [comment]
Hmm that is a real shame that browsers have such a poor ability to extend natives.

So to save me time from extracting the ember code, I used the code from here: http://www.bennadel.com/blog/2292-extending-javascript-arrays-while-keeping-native-bracket-notation-functionality.htm

To make this perf:
http://jsperf.com/array-collection-native-perf

Even the method usage is much slower. I get that these methods are being pretty dumb however clearly explains the perf issue here.

---

Which long term means the inject methods after importing Ember might be the simplest option for migration.

**Comment by stefanpenner** [comment]
Closing this, as I don't believe this is really an ember-cli thing. Rather it seems like an RFC for ember itself to move away from prototype extensions.

**Comment by jonathanKingston** [comment]
:+1: @stefanpenner thanks for all the help. I will raise an RFC at some point soon and copy you in for your thoughts there, unless you beat me to it of course.

**Comment by stefanpenner** [comment]
@jonathanKingston i likely wont have time soon, but I would like to help you explore the idea.
