### ISSUE TITLE
Updating to latest global ember-cli has reverted my global install to a much older version

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-cli#3346]
Hi,

Sorry if this is an obvious mistake on my part but can't seem to work out what is going on.

```bash
mycomputer:~/git|⇒  ember -v
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.30
npm: 2.1.8

mycomputer:~/git|⇒  npm install -g ember-cli

npm WARN package.json broccoli-es3-safe-recast@0.0.8 No README data
npm WARN package.json pleasant-progress@1.0.1 No README data
/usr/local/bin/ember -> /usr/local/lib/node_modules/ember-cli/bin/ember
npm WARN unmet dependency /usr/local/lib/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/connect-timeout requires debug@'*' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/local/lib/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/express-session requires debug@'0.7.4' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
ember-cli@0.0.42 /usr/local/lib/node_modules/ember-cli
├── abbrev@1.0.5
├── js-string-escape@1.0.0
├── broccoli-writer@0.1.1 (rsvp@3.0.17, quick-temp@0.1.2)
├── yam@0.0.13 (findup@0.1.5, fs-extra@0.8.1, lodash@2.4.1)
├── core-object@0.0.1 (lodash-node@2.4.1)
├── broccoli-filter@0.1.6 (promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, quick-temp@0.1.2, rsvp@3.0.17, broccoli-kitchen-sink-helpers@0.2.6)
└── tmp-sync@1.0.1 (fs-sync@0.2.5)

mycomputer:~/git|⇒  ember -v
version: 0.0.42
node: 0.10.30
npm: 1.4.23
```

After running `npm install -g ember-cli` it looks like i'm back on 0.0.42, whereas I was expecting 0.1.15

Much appreciate any help.

**Comment by stefanpenner** [comment]
crazy. 

> npm: 2.1.8
> npm: 1.4.23

My suspicion is that you have multiple NPM/Nodes' installed, and this is likely causing you pain. My recommendation would be to try and prune your nodes, and consider using something like nvm exclusively to manage your node versions.

**Comment by chrism** [comment]
Thanks so much for getting back to me on this — sorry it took a couple of days for me to reply. I didn't want to start messing around with my installations until I had a bit of time to spend on it...

Long story short -> nvm fixed it :tada: 

I had installed node via homebrew & it doesn't look like there were multiple versions as a brew uninstall appeared to remove it but nevertheless I followed http://stackoverflow.com/a/11178106/1787262 to expunge everything I could and then started again with nvm as per http://www.wenincode.com/installing-node-jsnpm-without-sudo/

So far all seems good (fingers crossed) & i'd recommend anyone in the same position to take the plunge and switch to nvm.

Thanks again :smile:

**Comment by stefanpenner** [comment]
> So far all seems good (fingers crossed) & i'd recommend anyone in the same position to take the plunge and switch to nvm.

great, keep me posted if more issues occure.
