### ISSUE TITLE
addons on master appear in a bad state.

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3348]
I need to review some other work before I can dig in. 

What i have noticed so far

* addons `app/**/*.js` and `addon/**/*.js` don't appear to be included in the app.
* I have no idea how this isn't getting caught in our tests

related: https://github.com/paddle8/ember-document-title/issues/4

example app: https://github.com/stefanpenner/__addon-example-issue
Manifestation: the code provided by the `ember-document-title` addon do not get included.

**Comment by rwjblue** [comment]
It is likely related to my recent changes.  I'll take a look now...

**Comment by raycohen** [comment]
against ember-cli master, we're not seeing ember-data get included.

we tracked it down to inside 

`AddonDiscovery.prototype.resolvePackage`

where the line

`var entryModulePath = resolve.sync(packageName, { basedir: root });`
raises an error when packageName is `ember-data`

cc @lukemelia

**Comment by lukemelia** [comment]
May be related to modules that have a non-standard `main` node

**Comment by rwjblue** [comment]
> > var entryModulePath = resolve.sync(packageName, { basedir: root });
> raises an error when packageName is ember-data

https://github.com/emberjs/data does not have an entry point module (no `main` specified in `package.json`, and no `index.js`).

**Comment by rwjblue** [comment]
We need to enforce that addons be validly formatted NPM packages (generated ones are properly formatted), but perhaps we need to deal with this error and attempt discovery via the older (always assume `node_modules/<addon-name>` mechanism) with a warning/deprecation...

**Comment by green-arrow** [comment]
Just to clarify, this happens to freshly generated addons as well. Generating a fresh addon and adding a component / helper / anything fails to work (component / helper lookup fails). The helper / addon does not get included in the dummy application.

**Comment by rwjblue** [comment]
@green-arrow - The issue that @lukemelia referenced is *not* what this issue was created to track down (it was discovered while looking into it), but it will need to be addressed as well.    I am still working on the issue of "none of the app/ or addon/ code shows up"...

**Comment by green-arrow** [comment]
@rwjblue - Sorry, I didn't mean to refer to the issue @lukemelia reference. I just wanted to make sure I understood the issue correctly to verify that this is the same issue I'm facing when developing an addon locally (none of the app/ or addon/ code shows up in the dummy app). Thanks for working on this issue :smile:

**Comment by rwjblue** [comment]
@stefanpenner - I believe that https://github.com/ember-cli/ember-cli/issues/3349 should have fixed the real issue here (the `ember-document-title` thing was a bad package).  Can you confirm?

@green-arrow - If https://github.com/ember-cli/ember-cli/issues/3349 didn't address the issue you were referring to, can you create a demo repo so I can help track it down?

**Comment by stefanpenner** [comment]
> @stefanpenner - I believe that #3349 should have fixed the real issue here (the ember-document-title thing was a bad package). Can you confirm?

confirming

**Comment by green-arrow** [comment]
@rwjblue - Updated to use master. Received the log about `ember-data` not being a properly formatted package. However, it doesn't look like the JS inside of `app` or `addon` are being included in the consuming application.

Repo is at https://github.com/green-arrow/ember-cli-chosen and `package.json` has been updated to pull `ember-cli` from master.

I have a blueprint in there and am doing some work in `index.js`, but I hope that this is stripped down enough to demonstrate the issue. If it's not, let me know and I'll spin up a more stripped down repo.

**Comment by stefanpenner** [comment]
lets see whats wrong with the ember-cli-chosen

**Comment by green-arrow** [comment]
@stefanpenner - I spun up a fresh addon using master and didn't encounter the same problem. Looks like something specific to my addon that's messing things up.

Good news is that #3349 looks like it fixes this issue.

**Comment by stefanpenner** [comment]
@green-arrow ya i noticed that too, lets close this. Let me know if you have further issues with your addon.

**Comment by green-arrow** [comment]
@stefanpenner - thanks man. Issue is two-fold. I was bugging up `treeFor` and was using the wrong namespace when importing my component. 

Thanks again for everyone's work on this.

**Comment by rwjblue** [comment]
Submitted https://github.com/green-arrow/ember-cli-chosen/pull/1 to fix ember-cli-chosen.

**Comment by stefanpenner** [comment]
@rwjblue good catch.
