### ISSUE TITLE
IE9 white screen on relative path for ember app

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3351]
When loading URL's in IE9 that are not the base path, the app doesn't initialise the code.

Example URL:
https://emberflare.com/about

From what I can see is the issue is how it comprehends hash links and handles redirects to the URL.

The behaviour is a white screen of death.

Related to: #2989

I think the solution is to kill `<base` for at least apps wishing to support IE9.

**Comment by stefanpenner** [comment]
http://caniuse.com/#search=history  history API isn't supported in IE9. You must use `auto` or `hash`

**Comment by jonathanKingston** [comment]
@stefanpenner sorry I think I was not clear enough. I am using auto; the # in the URL seems to cause the issue when loading a page that is not the top level URL.

The app is working fine when I browse to '/' in IE9 then click links. 

I found some stackoverflow articles mentioning the base URL isn't considered when hashes are used - however I'm not a massive fan of linking to poor quality articles.


IE9 also works in this situation if the index.html is manually edited with the prefix.

**Comment by stefanpenner** [comment]
ah IE + baseURI + location hash issue.

**Comment by jonathanKingston** [comment]
@stefanpenner would this be worthy of a fork of broccoli-asset-rewrite for my other issue: #3498
I have seen somewhere the intent to ditch the base tag usage, all could be resolved by the same plugin for rewriting URLs.

**Comment by rwjblue** [comment]
@jonathanKingston - broccoli-asset-rewrite was split specifically to support the removal of the base tag.  I do not see why we would need to fork for this...

**Comment by jonathanKingston** [comment]
@rwjblue I guess I should have asked the question: what is the issue with using broccoli-asset-rewrite by default rather than using base?

Like I said, I saw some mention of transitioning to remove the base tag, what is blocking that?

However #3498 if there is no interest to merge in will likely need a different solution like removing the meta tag for config as any mention of an asset in the config breaks it.

**Comment by rwjblue** [comment]
> I saw some mention of transitioning to remove the base tag, what is blocking that?

Time.  I have offered to pair with someone on the initial spike if they will take it the rest of the way....

**Comment by jonathanKingston** [comment]
@rwjblue I'm certainly interested in isolating the issues, as for time I can't guarantee that I will be able to contribute as much as you will need.

**Comment by jonathanKingston** [comment]
I guess this relates very closely to the outcome of this: https://github.com/emberjs/rfcs/pull/45

**Comment by stefanpenner** [comment]
seems to ahve gone stale, will reopen if a reproduction on latest is provided
