### ISSUE TITLE
Cannot modify files insite dist/

### ISSUE THREAD

**Issue by dongliutony** [ember-cli/ember-cli#3352]
In my project, I put some static assets, such as images and icons into the /dist/static/image directory. Then I build the project (I forgot the details in this part).
Then when I want to modified some picture inside that folder (I wanted to change some parts to be transparent), I found that I cannot change anything inside.
For example, when I used a new pic to replace the old one, and then I run ember, I found that the new pic was replaced by the old one automatically.
I am not so sure about the internal mechanism, and I tried to use git, but that didn’t help.

**Comment by stefanpenner** [comment]
you should put them in `public`

**Comment by dongliutony** [comment]
Ok, let me try.

Thank you!

**Comment by stefanpenner** [comment]
:+1: report back if it doesn't work for you.
