### ISSUE TITLE
Customize Addon blueprints to keep all addon code in the addon tree.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3354]
Quoting @trabus from https://github.com/ember-cli/ember-cli/pull/3339#issuecomment-75671359:

I think what we should do is break the addon rexport code into its own blueprint (component-addon for instance), similar to what we do for tests, and conditionally install them from the generate-from-blueprint.js task.

We can add one more token for the root folder, so in /files of your blueprint, you'd have: `__root__/__path__/__file__.js` 
For instance when generating a component blueprint into an addon, the `__root__` token would be "addon", but otherwise it would be "app" for a regular project.

The addon rexport blueprint would be appended with -addon, so we could look it up in the same manner we do for test blueprints. We'd add a check in the task for addonBlueprint, and install them if they exist just like we do for test blueprints.

**Comment by trabus** [comment]
Breaking into tasks for later:
- [ ] add support for `__root__` fileMapToken
- [ ] add `*-addon` support for Blueprint.lookupBlueprint method
- [ ] add install addonBlueprint to the generate-from-blueprint task
- [ ] identify any additional values that are needed for generating addonBlueprints
- [ ] create component-addon blueprint
- [ ] update component blueprint with addon support
- [ ] tests!
