### ISSUE TITLE
Limited number of hooks into the build process available to add-ons

### ISSUE THREAD

**Issue by endash** [ember-cli/ember-cli#3362]
*** disclaimer: it's entirely possible I'm missing something obvious that turns this on its head in which case please put me out of my misery and then close ***

I'm currently working on integrating grid style sheets with ember via the ember-cli-gridstylesheets add-on. It's pretty straightforward at the moment: bring in a bower dependency, add a preprocessor to zip up any *.gss files in the app, and then some `contentFor` HTML strings to link to the bundled GSS file.

After going over `ember-app` carefully, and trying a couple preprocessing hooks, I decided on tying into the css preprocessing. The logic was: they're stylesheets too, and I figured I could just return a merger between the original tree passed to my preprocessor and the tree generated by my one call to `broccoli-concat`, to ensure that any other add-ons would be able to still see the original tree. I'm now pretty sure that logic was fatally flawed, as any other add-on could in theory just pluck out any files it cared about and leave mine in the dust. I think. I still don't entirely grok broccoli. 

So, I was kinda uneasy about it at the time, but the fact that I created the add-on to serve as the basis for ANOTHER add-on, and jumped directly from one to the other without actually using it in an app in between led me to miss that adding any CSS preprocessor disables the standard zip-up-all-css-files processing of stylesheets. Oops. No stylesheets for you.

Thus, my initial uneasiness: totally validated in hindsight. However, I cannot figure out any other avenue of attack short of monkeying with ember-app from my add-on (which, to be clear, I am *not* planning on doing). Ember-app does a pretty thorough job of ensuring only the files it cares about get moved along through the various steps and into the final build, and rightly so.

I'm envisioning three possibilities here:

(1) There's already a workaround/broccoli voodoo that doesn't involve totally monkeying with ember-app's internals, and I've just missed it. This would be ideal, in the short term at least. Maybe a public way to get an add-on count so my add-on could see if it was the only preprocessor, and introduce the default behaviour if so? Still seems hacky, and doesn't fix the basic incompatibility between the current css preprocessing hook and what I'm actually trying to do with it.

(2) A new, separate, last-chance hook for add-ons to get access to the original unfiltered tree and return a tree guaranteed to make it into `dist`. Fairly simple to implement (Maybe?) but potentially ripe for abuse.

(3) Bump the various build stage functions to first-class entities in their own right (they are conveniently already called serially and separately in `toArray`) and expose a way for add-ons to add additional 'build verticals.' This seems like it would be somewhat easy in `ember-app` since they're already halfway there, they'd just need to go from explicit calls to some sort of dynamic approach. Preprocessors may or may not need more work depending on how desirable it would be to refactor existing behaviour into generic forms. I don't have any clue what the mechanism for add-ons being able to provide new 'build verticals' would look like. In short: more complex than (2), and hopefully with the right admonitions and guidelines it'd be less ripe for abuse? Would also allow add-ons to tie into a common add-on's base functionality via the high level hooks.

I'd frankly love to see (3), as the next problem for me to tackle is how to get GSS files from add-ons, which naturally only get queried for the handful of built-in 'verticals.'

That said, I'm having trouble coming up with a further use case beyond my own (maybe something involving images?), so it might not be worth all the bother.

**Comment by rwjblue** [comment]
I do not really understand what you are trying to do from the addon, so I'm having a hard time understanding what the right solution is.

Can you describe your inputs (to the addon) and expected outputs (what should end up in `dist/`)?

**Comment by stefanpenner** [comment]
maybe an example app would also help

**Comment by sglanzer** [comment]
Steps copied from the issue on ember-cli-gridstylesheets:

    1. ember new gss-testbed
    2. cd into gss-testbed, ember install:addon ember-cli-gridstylesheets
    3. ember generate component gss-box
    4. modify the gss-box component to include classNames: ['gss-box', 'gss-box--red']
    5. modify styles/app.css to include

````
.gss-box {
  display: inline-block;
  width: 100px;
  height: 100px;
}

.gss-box--red {
  background-color: red;
}
````

    6. modify application.hbs to include {{gss-box}}
    7. ember server - no red box appears
    8. npm uninstall --save-dev ember-cli-gridstylesheets
    9. ember server - red box appears

**Comment by sglanzer** [comment]
The issue as far as I can tell is that the gss addon registers a pre-processor against 'css', but handles files with a .gss extension, leaving the css files alone.  This results in an empty css stylesheet.

I believe what @endash is looking for is either a recommendation for how to handle gss concatenation/processing via another hook (treeFor?) or a way to register a gss pre-processor that executes correctly in the build process and doesn't override the css processing.

**Comment by endash** [comment]
The addon is pretty simple. 

(1) It includes "GSS", grid style sheets, a JS library for applying cassowary constraint solutions. GSS works by a parallel system of stylesheets to CSS that do not compile down to CSS. They remain their own separate GSS format and separate files that get interpreted by the GSS runtime in addition to regular CSS styles being applied by the browser.

(2) It takes, or attempts to take, any "GSS" files in `app/styles` and concatenates them into `your-app.gss` and places the resulting file in `/assets`. Currently this concatenated file is the *end product* and does not get turned into "real CSS" or anything else.

`[app/styles/app.gss, app/styles/my-component.gss]` concat => `/dist/assets/my-app.gss`

This currently works fine on its face, using an (ostensibly) 'css preprocessor.' 

(3) Via `contentFor` it injects a `<link>` tag to the resulting GSS file which is interpreted by the bundled runtime.

My functionality currently works. The problem is due to the semantics and implementation, preprocessors:css is not a valid hook for this after all, for a number of reasons the most glaring of which is the fact that adding any preprocessor of type 'css' has the effect of disabling the basic and automatic CSS processing behaviour. 

I'll create a trivial app to show that adding ember-cli-gridstylesheets knocks out regular CSS support.

**Comment by endash** [comment]
https://github.com/endash/ember-cli-css-gss-problem-demo is a simplest case demonstration of the current behaviour. A new 0.2.0-beta.1 project is completed. A simple rule is added to `app/styles/app.css` to make the page background blue. Then, after `ember install:addon ember-cli-gridstylesheets` there is no longer a CSS file in `dist/assets` and so the style no longer is applied.

**Comment by stefanpenner** [comment]
A thorough audit and cleanup of the hooks seems like a good idea. and will come with time.
