### ISSUE TITLE
ember install --safe

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3364]
It would be very handy if `ember install` had an option where will **only** call `npm install` and `bower install` if there's a dependency missing. One way would be to make use of `ember-cli-dependency-checker` that's already included in `ember-cli`.

I use `ember install` in my current build process, and `npm` and `bower` calls are very expensive (network).

I could directly call `npm` and `bower` but I wasn't able to find any documentation regarding this feature.

**Comment by stefanpenner** [comment]
`ember install` is borked, it will soon become just an alias for `ember install:addon <addon-name>`

**Comment by stefanpenner** [comment]
tracking this here: https://github.com/ember-cli/ember-cli/issues/3204
