### ISSUE TITLE
ember build throws for the app.css when outputPaths is set

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3365]
When using `outputPaths`, if the extension is not `css` or `js` (say I want my file to be `scss` - unprocessed), every ember build will throw an exception **EEXIST: file already exists**, but it works fine for `css` and `js` extensions.

I'm outputing my app `css` to `my-app.scss` because is part of a larger build.
This issue doesn't seem to apply to the vendor style, just the app style.

I don't know if this is on purpose or a problem. Is there a way to get around it?

**Comment by btecu** [comment]
It looks like the extension is not the problem, but `ember-cli` will throw if you have any **application** (not vendor) **css** in the `outputPaths`:

```
EEXIST: file already exists, open 'd:\Code\build\Ember\app.css'
Error: EEXIST: file already exists, open 'd:\Code\build\Ember\app.css'
    at Error (native)
    at Object.fs.openSync (fs.js:540:18)
    at Object.fs.writeFileSync (fs.js:1143:15)
    at Object.copyDereferenceSync (D:\Code\src\Ember\node_modules\ember-cli\node_modules\symlink-or-copy\node_modules\copy-dereference\index.js:26:8)
    at symlinkWindows (D:\Code\src\Ember\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:92:13)
    at Function.symlinkOrCopySync (D:\Code\src\Ember\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:56:5)
    at Funnel._copy (D:\Code\src\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:241:17)
    at Funnel.processFile (D:\Code\src\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:232:8)
    at Funnel.processFilters (D:\Code\src\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:151:12)
    at Funnel.handleReadTree (D:\Code\src\Ember\node_modules\ember-cli\node_modules\broccoli-funnel\index.js:129:10)
```

**Comment by btecu** [comment]
It currently works in dist (default) because the folder is deleted and then created again. The issue is with `copy-dereference` which throws an exception if the file exists (I don't understand why it doesn't just overwrite the file).

@rwjblue any suggestions on how to get outputPaths fixed?

**Comment by rwjblue** [comment]
I don't understand what is being done here, can you provide a failing repo to demonstrate the issue and setup you are trying to use?

**Comment by btecu** [comment]
See https://github.com/btecu/css-error

Run `ember s`. The first time it will work fine. Then save anything and you'll see how it throws an exception.
It only throws for the app css, vendor css works fine.

**Comment by jasonmit** [comment]
@btecu this was an issue with ramraf.  Follow the directions here: https://github.com/ember-cli/ember-cli/issues/3413

* remove node_modules (it didn't work otherwise for me)
* add ramraf 2.8.8 as a dependency (not a devdep)
* npm install

**Comment by btecu** [comment]
I don't think that's the case. I still get the same error.
Note that the error I'm getting is not related to a symlink or temporary file, but the output file (usually in dist).

**Comment by jasonmit** [comment]
@btecu when ember-cli builds it removes and clears the output path, `dist` by default.  In this case, ember-cli has no idea that you're copying files to somewhere other than the output path.  This is done here https://github.com/ember-cli/ember-cli/blob/18d377b264859548f41aba6c3ea2015b90978068/lib/models/builder.js#L85

You would need to some how, prebuild, clear your custom output path for your css `build` directory.  This could be done using an addon's preBuild hook https://github.com/ember-cli/ember-cli/blob/18d377b264859548f41aba6c3ea2015b90978068/ADDON_HOOKS.md#prebuild

I'm not sure what your use-case is, but if all you're trying to do is change the output path you can use: `ember s --output-path=build/`

**Comment by btecu** [comment]
I'm not copying the files (manually) anywhere, but using `outputPath`, which I assume is the same as ``--output-path`. 

You can see in the repo that demonstrates the problem the setting: https://github.com/btecu/css-error/blob/f3078ddb4964023e0d30ada9138b197a033e63e4/Brocfile.js#L9 

My guess is that it's a bug, because this one works just fine:
https://github.com/btecu/css-error/blob/f3078ddb4964023e0d30ada9138b197a033e63e4/Brocfile.js#L13

So it's only app css that crashes, but vendor css works fine.

**Comment by btecu** [comment]
This issue is still present with version `0.2.0`.

What's the reason for `ember build` to not overwrite the destination files?

**Comment by stefanpenner** [comment]
will reopen if a reproduction on latest is provided
