### ISSUE TITLE
Add an automated way to add license text

### ISSUE THREAD

**Issue by iagox86** [ember-cli/ember-cli#3366]
At work, we're required to put a license header comment on every file checked into the repository. Since most of them are auto-generated, I asked Stef about whether it's possible to do, and he told me to open a feature request. :)

**Comment by stefanpenner** [comment]
@iagox86 some questions:

* do we want new files generated with such a license?
* as the project is ultimately concatenated, do we need to retain the license per file? 100 modules resulting in 100 license headers in the concatenated output seems like a bad idea.
* rather then license per file, can we merely ensure your license at the project root is prepending to the concatenated output?
* what about template files, do we need some sort of license in them as well?

**Comment by stefanpenner** [comment]
@jgwhite @trabus this may be something we want to ensure the blueprinting system can support, and that we can utilize via an add-on.

**Comment by iagox86** [comment]
The license I'm applying is Apache 2.0, and it says: "Each original source document (code and documentation, but excluding the LICENSE and NOTICE files) SHOULD include a short license header at the top." - that's basically what I need. I asked our OSS team whether or not it applies to generated files that I didn't add any code to - like router.js and all my empty tests - and they said yes, those need it to.

For distribution, when the project is concatenated, I'm not really sure. I have to imagine that one blurb at the top is sufficient, but that makes things more difficult most likely. :)

Sadly, a license at the project root is required in addition to the file headers.

I assume by template you mean the .hbs files - and yes, I think the .hbs and .html also require license text.

It seems silly, but it's not my call - our team is pretty particular about following the OSS licensing guidelines. Thanks for considering it! :)

**Comment by stefanpenner** [comment]
> It seems silly, but it's not my call - our team is pretty particular about following the OSS licensing guidelines. Thanks for considering it! :)

Although i believe it wont be high priority, I would like to support it.
I would like to chat with someone about the implications of licensing generated files, as it seems like a confusing topic.

**Comment by stefanpenner** [comment]
Also, we can't put a license in package.json.

Additionally, I am dubious of the final byte-size this will produce. Ultimately gzip should handle it somewhat.

**Comment by stefanpenner** [comment]
I am reaching out to our OSS licensing guy as well.

**Comment by iagox86** [comment]
Yeah, I'm unsure about how or if to license non-code files (.yaml, .json, etc.) and asked our internal OSS guys. Reaching out to yours sounds like a good plan!

**Comment by iagox86** [comment]
There's no urgency on my end, so low priority is fine. I'm just doing it manually for the time being. :)

**Comment by trabus** [comment]
@jgwhite and I were going to talk to @abuiles about his ideas for post processing hooks (to do AST transforms, etc) for blueprints at EmberConf. This seems like something that is totally doable and would likely be something that could be configurable or put into addon.

**Comment by stefanpenner** [comment]
@trabus related to todays blueprint discussion.

**Comment by stefanpenner** [comment]
seems to have gone stale, would love this. But not on anyones critical path

**Comment by iagox86** [comment]
Agreed @ stale. I don't need it anymore. :)
