### ISSUE TITLE
Config store race condition with parallel builds?

### ISSUE THREAD

**Issue by dspangen** [ember-cli/ember-cli#3368]
We have four ember projects that we build in parallel in the same code repo. When we do this we sometimes get the following exception:

From our automation provider (we've also seen it locally in OS X Yosemite):
```
/home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/configstore/configstore.js:90
	config[key] = val;
	            ^
TypeError: Cannot set property 'client-id' of null
    at Object.Configstore.set (/home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/configstore/configstore.js:90:14)
    at clientId (/home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/lib/cli/index.js:31:17)
    at cli (/home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/lib/cli/index.js:46:19)
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/bin/ember:26:3
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/resolve/lib/async.js:48:21
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/resolve/lib/async.js:127:35
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/resolve/lib/async.js:99:39
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/resolve/lib/async.js:65:30
    at /home/ubuntu/dandelion/client/salsify/node_modules/ember-cli/node_modules/resolve/lib/async.js:23:18
    at Object.oncomplete (fs.js:107:15)
```

Is there a race condition somewhere in ember-cli that would cause this?

**Comment by joostdevries** [comment]
Reasonably sure this is caused by yeoman/configstore#20

**Comment by stefanpenner** [comment]
any ideas? I am unsure how to move forward on this..

**Comment by stefanpenner** [comment]
i don't believe this is something we can solve :(

**Comment by lai** [comment]
This can happen quite frequently with a CI setup that builds on multiple types of repo changes (PR merge and master branch update can trigger builds simultaneously).

Is there plans for ember-cli to update the `configstore` dependency to v1.2.1 with the fix in yeoman/configstore#25? It's noteworthy that `configstore` introduced a breaking change at 1.0.0 to switch from yaml to json.

**Comment by john-kurkowski** [comment]
Agreed. Can we reopen this to track updating the `configstore` dependency?

**Comment by stefanpenner** [comment]
@twokul got a chance to update yam ?

**Comment by john-kurkowski** [comment]
Thanks!
