### ISSUE TITLE
Feature Request: 'ember clean' or 'ember reset' command

### ISSUE THREAD

**Issue by jmurphyau** [ember-cli/ember-cli#3371]
Or something similar..

When doing things like changing branches I find myself sometimes having to do the following:
`rm -rf ./dist/ ./tmp/ ./node_modules/ ./bower_components/`
`npm install`
`bower install`

There is also a similar flow when upgrading ember-cli versions. If this was wrapped up in a single command it would make explaining the process to others (new users on the team for example) it might make life easier.

**Comment by stefanpenner** [comment]
feature requests should likely go through the RFC process https://github.com/ember-cli/rfcs
