### ISSUE TITLE
Overriding adapter in acceptance tests

### ISSUE THREAD

**Issue by zilkey** [ember-cli/ember-cli#3372]
Is there a simple way that we can have a `RESTAdapter` in the main app, and override that with a `FixtureAdapter` in integration tests in ember-cli?  In my acceptance tests, before my `module` imports, I have:

```js
Ember.Application.initializer({
  name: 'my-fixture-store',

  initialize: function(container, application) {
    var store = DS.Store.extend({ adapter: DS.FixtureAdapter.extend() });
    container.unregister('store:main');
    container.register('store:main', store);
  }
});
```

It doesn't raise any errors, but also doesn't work (requests still go to `localhost:4200`).  There's a ton of information online about various ways of accomplishing this, and I'm having trouble getting anything to work in integration tests.

PS - It could be that I don't understand enough about ember itself to make this work, so if this is off-topic please close.  Otherwise I'd be happy to take whatever answer is here and add it to the docs.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/3306
