### ISSUE TITLE
Can't find store.find('~~');

### ISSUE THREAD

**Issue by pcjpcj2** [ember-cli/ember-cli#3374]
I use Ember Cli 0.1.15, I use http-mock for model but I recieved message below..

➜  ember-blog git:(master) ✗ ember serve
version: 0.1.15
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
FSEventStreamStart failed
Error: FSEventStreamStart failed
    at null.<anonymous> (/Users/ChangJooPark/Development/ember-blog/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:765:14)
    at emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Readable.push (_stream_readable.js:128:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/ChangJooPark/Development/ember-blog/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

I update all of npm, node, brew. 

is this watchman problem?

**Comment by leandrocp** [comment]
@pcjpcj2 what `npm -v` and `ember -v` says ?

**Comment by pcjpcj2** [comment]
@leandrocp npm - 2.1.8 , ember 0.1.15, node 0.10.35

**Comment by pcjpcj2** [comment]
Why cant find model..

**Comment by stefanpenner** [comment]
> Why cant find model..

seems unrelated to the model.

what is the result of `watchman watch-list`

**Comment by pcjpcj2** [comment]
➜  ember-blog git:(master) ✗ watchman watch-list
{
    "version": "3.0.0",
    "roots": [
        "/Users/ChangJooPark/Development/ember-blog/bower_components/bootstrap/dist/css",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-qunit-notifications",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/loader.js",
        "/Users/ChangJooPark/Development/ember-blog/config",
        "/Users/ChangJooPark/Development/ember-blog/app",
        "/Users/ChangJooPark/Development/ember-blog/tests",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-load-initializers",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-resolver/dist/modules",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-cli-shims",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/qunit-notifications",
        "/Users/ChangJooPark/Development/ember-blog/public",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/handlebars",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/bootstrap/dist/js",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-data",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/jquery/dist",

        "/Users/ChangJooPark/Development/ember-blog/bower_components/qunit/qunit",
        "/Users/ChangJooPark/Development/ember-blog/bower_components/ember-qunit"
    ]
}

**Comment by pcjpcj2** [comment]
Strange thing.. 

import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    // return this.store.find('item');
    return [{id:1, title:'test'}, {id:2, title:'test2'}];
  }

});


this is my routes file.

uncommented return this.store.find("item"), then occur this problem.

I have already item model..

**Comment by stefanpenner** [comment]
> is this watchman problem?

ya it seems like it. We have had some users have issues with sublime/webstorm + watchman, but it doesn't seem to affect everyone. Alternatively something like dropbox may cause grief?

**Comment by stefanpenner** [comment]
> I have already item model..


> Strange thing..
> 
> import Ember from 'ember';
> 
> export default Ember.Route.extend({
>   model: function() {
>     // return this.store.find('item');
>     return [{id:1, title:'test'}, {id:2, title:'test2'}];
>   }
> });
> this is my routes file.
> 
> uncommented return this.store.find("item"), then occur this problem.
> 
> I have already item model..

strange

**Comment by pcjpcj2** [comment]
I dont use dropbox

I'll try remove all about node npm ber things..

**Comment by pcjpcj2** [comment]
remove and install. but still occured same problem

**Comment by pcjpcj2** [comment]
https://github.com/ember-cli/ember-cli/issues/2683

I found this problem.
