### ISSUE TITLE
Minification for JS and CSS?

### ISSUE THREAD

**Issue by dj-hedgehog** [ember-cli/ember-cli#3376]
The guide on http://www.ember-cli.com/asset-compilation/ suggests that Ember CLI minifies CSS and uglifies JS when building for production but they modules aren't even installed with the latest Ember-CLI.

What happened to them?

EDIT: I just found https://github.com/ember-cli/ember-cli-uglify . The documentation on http://www.ember-cli.com/asset-compilation/ needs to revised anyways.

**Comment by stefanpenner** [comment]
I'm pretty sure they are included..

**Comment by karelvuong** [comment]
My `package.json` lists `ember-cli-uglify` under `devDependencies` after calling `ember new` on both ember-cli v0.1.15 and v0.2.0-beta.1.

```
"devDependencies": {
  ...
  "ember-cli-uglify": "1.0.1",
  ...
}
```

Upon installing the packages and running `ember build -prod`, the CSS and JS are correctly minified and uglified.

**Comment by rwjblue** [comment]
The default generated `package.json` for a new app includes `ember-cli-uglify` (see [here](https://github.com/ember-cli/ember-cli/blob/b6b6c4d6f140401c92777f34e36f39fad027e1c6/blueprints/app/files/package.json#L32)) and we depend on [broccoli-clean-css](https://github.com/ember-cli/ember-cli/blob/b6b6c4d6f140401c92777f34e36f39fad027e1c6/package.json#L90) (which uses [clean-css](https://github.com/jakubpawlowicz/clean-css)).

Please provide steps to reproduce a repo that does not automatically minify JS and CSS when running `ember prod --environment=production`.
