### ISSUE TITLE
Examine Addon-trees for big files

### ISSUE THREAD

**Issue by dj-hedgehog** [ember-cli/ember-cli#3377]
I find myself uncomfortable with the size of my exported vendor.js and vendor.css.
To get a better understanding on what is going on I added this to my Brocfile.js 
`console.log(app.javascript().inputTrees[0].inputFiles)`

At thise time all Ember-CLI addons are already concatenated so I'd like to know what's going on in the addon-trees themselves.

What would be the best way to achieve this? Are there plugins showing the size of each tree-element I could use?

**Comment by stefanpenner** [comment]
> What would be the best way to achieve this? Are there plugins showing the size of each tree-element I could use?

might be something neat to add to https://github.com/stefanpenner/broccoli-stew

**Comment by dj-hedgehog** [comment]
I'll see what I can do with your broccoli-stew and Ember CLIs addon hooks.

**Comment by jrhe** [comment]
@dj-hedgehog Did you come up with a solution for this? It would be good to have something like this baked into ember-cli as I can see the problem becoming more common as ember is used for more and more "ambitious" apps.
