### ISSUE TITLE
Sourcemap uses relative path

### ISSUE THREAD

**Issue by chopper** [ember-cli/ember-cli#3379]
When building my assets, the `sourceMappingURL` is set to include the `assets/` directory, resulting in
```
//# sourceMappingURL=assets/app-34b3a9c09b99a6c2de838be3e7f1f43e.map
```
The issue is that the source map is in the same directory as the JS, so this results in 404/403 errors. The correct `sourceMappingURL` is
```
//# sourceMappingURL=admin-34b3a9c09b99a6c2de838be3e7f1f43e.map`
```

**Comment by stefanpenner** [comment]
https://github.com/rickharrison/broccoli-asset-rev/ is likely the better place to investigate this.
