### ISSUE TITLE
Proposal: add option to have git/bower use local caches only

### ISSUE THREAD

**Issue by eoinkelly** [ember-cli/ember-cli#3380]
There are a number of cli commands that depend on `npm` and `bower` which currently do not work properly without Internet access e.g. `new`, `init`, `addon`, `install`. 

I think it would be great to have something like an `--offline` option to these commands that would instruct bower and git to use their local caches rather than remote repositories. Currently:

* `bower` commands accept an `--offline` flag which does what we need
* `npm` is [discussing a similar flag](https://github.com/npm/npm/issues/2568) but in the meantime `npm install foo bar --cache-min 99999999` appears to work.

This would make `ember-cli` more usable in situations with no/bad/expensive Internet. I am happy to attempt a PR for this if it something that the core team is interested in exploring further.

**Comment by rwjblue** [comment]
:+1: - We definitely want a `ember new foo --offline` flag that does roughly what you are suggesting.  I am not certain of the implementation that we should settle on, but trying the `--offline` and `--cache-min` flags sounds like a good thing to try first.

**Comment by eoinkelly** [comment]
I'll have a go and then we will have something concrete to discuss.

**Comment by rwjblue** [comment]
Sounds great!

**Comment by stefanpenner** [comment]
:+1: Ya we promised this feature to @tomdale and @wycats for ember-conf. Would love to see some other peoples attempt

One thought I had, was to create and additional package ember-cli-offline, that bundled all the missing assets for that version.

**Comment by eoinkelly** [comment]
I have spiked out an `--offline` flag implementation at https://github.com/ember-cli/ember-cli/compare/master...eoinkelly:better-offline?expand=1 - it works but there are a few things I would like some feedback on:

1. General direction
1. I'm not in love with `--offline` as the flag name but I can't think of anything better. bower uses `--offline`, it seems like npm will do the same but bundler uses `--local`.
1. Obviously we will still error if the required packages are not in the npm/bower caches. We can't recover from this but perhaps we could analyse which packages are required and let the user know in a nice way. While this would be a preferable from a UX point of view I'm not sure it is worth the effort. Thoughts? 

@stefanpenner I'm not sure I understand your suggestion (sorry if I'm being dumb).

**Comment by twokul** [comment]
I like `--local` option better than `--offline`. It seems like `bower` might go away soon-ish (@stefanpenner) ? We do need a way to verify local cache for the packages that app needs to boot up correctly. (ember-cli/addons)

**Comment by eoinkelly** [comment]
I explored verifying the local cache:

* npm does not [yet](https://github.com/npm/npm/issues/3505) have `--dry-run` functionality 
* We don't want to depend on any internals of npm. The npm cache code is due for a rewrite soon (see point 2 in [the npm roadmap](https://github.com/npm/npm/wiki/Roadmap) )
* I explored parsing the output of `npm cache list` on the theory that its output would be more stable than the internals. I [got something working](https://github.com/eoinkelly/npm-cache-introspect) for the normal case but once I started trying to cover the other ways you can specify packages (e.g. git repos) it started to feel very brittle.

Given that our gain from verifying the local cache is a better error message and not recovery from an error I don't believe that this cache introspection is currently worth the brittle dependency on npm. This may change once the npm cache rewrite is complete and we (hopefully) get a stable programmatic API to the cache.

**Comment by eoinkelly** [comment]
Also I did some digging for a better name. Here are some options

* `--offline` (used by bower, also in discussion for future npm offline functionality)
* `--no-registry` (an old npm option that used to work)
* `--no-registries`
* `--cache-only` (a suggestion for future npm offline functionality)
* `--local` (used by Bundler)

**Comment by stefanpenner** [comment]
> --cache-only (a suggestion for future npm offline functionality)
> --local (used by Bundler)

either of these sound good.

**Comment by parautenbach** [comment]
+1

**Comment by stefanpenner** [comment]
@eoinkelly can i unblock you in any way?

**Comment by eoinkelly** [comment]
Have set aside time this coming weekend so will have PR by monday (sorry, work/life overtook)

**Comment by stefanpenner** [comment]
@eoinkelly no worries, work/life takes a higher priority. But we welcome the contribution whenever you have a chance.

**Comment by stefanpenner** [comment]
seems to have gone stale
