### ISSUE TITLE
Change `ember serve` to show http://localhost:4200 instead of http://0.0.0.0:4200.

### ISSUE THREAD

**Issue by oskarrough** [ember-cli/ember-cli#3381]
Hi, without having dug too deep it seems `0.0.0.0` isn't supposed to work as a URL and since some time Chrome is now redirecting that url to a search result. Instead the internet suggests to use localhost.

I propose ember-cli adapts to use `localhost:4200` instead. It's also faster to pronounce than all those pesky numbers.

([resource](http://stackoverflow.com/questions/28112933/how-to-stop-chrome-from-searching-when-manually-typing-in-local-dev-addresses))

**Comment by stefanpenner** [comment]
> 0.0.0.0 isn't supposed to work as a URL and since some time Chrome is now redirecting that URL to a search result.

it should totally work, in-fact if it doesn't this would break many things.  

> I propose ember-cli adapts to use localhost:4200 instead. It's also faster to pronounce than all those pesky numbers.

you can use localhost, 0.0.0.0 is just the ensure local loopback.

**Comment by raytiley** [comment]
So its possible the confusion here is that `ember s` says its serving on `http://0.0.0.0:4200` which just means that its not binding to a specific IP address. You can get to it just fine by going to localhost or 127.0.0.1.

Going to http://0.0.0.0:4200 in google on my machine is indeed impossible. Should we update the output of `ember s` to give less confusing message?

**Comment by rwjblue** [comment]
> Should we update the output of ember s to give less confusing message?

Yes.

**Comment by stefanpenner** [comment]
0.0.0.0 should always work, when does it not work?

**Comment by stefanpenner** [comment]
is this a windows-ism ?

**Comment by raytiley** [comment]
@stefanpenner https://www.youtube.com/watch?v=e7xDNFPmceQ&feature=youtu.be

**Comment by stefanpenner** [comment]
@raytiley https://www.youtube.com/watch?v=aTOmlcAZ3mg&feature=youtube_gdata_player

**Comment by lukemelia** [comment]
See https://code.google.com/p/chromium/issues/detail?id=428046

**Comment by stefanpenner** [comment]
fixed, now we show localhost :)
