### ISSUE TITLE
Add `ember generate <blueprint> --add` to diff existing generated blueprint and add to it

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3382]
We should be able to add content to already generated blueprints (specifically models) that take params to generate content. For instance we should be able to generate `ember g model foo name:string` then call `ember g model foo description:string --add` to add the description property to the foo model. The process would generate the new blueprint, then diff the existing file, and add the diff to the existing generated blueprint.

It may be better to make it part of the [confirmOverwrite](https://github.com/ember-cli/ember-cli/blob/master/lib/models/file-info.js#L26) method as an additional option (a) instead of a flag. 

```
ember g model user name:string
version: 0.2.0-beta.1
installing
[?] Overwrite app/models/user.js? (Yndah) Add
  adding to app/models/user.js
``` 
The main point is that the files are diffed then added in. We can then use an AST transform, adding in the diff to the content of the existing generated file(s).

**Comment by stefanpenner** [comment]
neat idea, seems to have gone stale

**Comment by trabus** [comment]
@stefanpenner I definitely want this for blueprints in the future in some shape or form.

**Comment by stefanpenner** [comment]
@trabus ya, we can remember as we work on that. I am trying to get the issue tracker focusing on active bugs when possible.

Hopefully that doesn't cause to much of an issue, or annoyances.

**Comment by trabus** [comment]
@stefanpenner not at all, just making note for the future so I remember.

**Comment by stefanpenner** [comment]
:)
