### ISSUE TITLE
Can't create new app with windows behind proxies

### ISSUE THREAD

**Issue by 20v100** [ember-cli/ember-cli#3385]
I'm rookie and maybe this is not the right forum but here is my issue:

I'm getting following error with "ember new" command: Failed to execute "git ls-remote --tags heads git://github.com/ember-cli/loader.js.git", exit code #128

I'm running Windows 7 behind proxies. I run the latest version of nodes, npm and ember (downloaded last week). I have search for days trying to make this work. Some of the solutions I have tried with no success: 
- Change the global config file (and confirmed the changes with git  config --list):

  http.proxy=http://<myid>:<mypassword>@proxy.xx.ca:1080",
  https.proxy=https://"<myid>:<mypassword>@proxy.xx.ca:1080"

- Creating a app without GIT with command: ember new mktk --skip-git

I don't know what to do next. Git keeps hitting git://github. Is ember-cli configuration issue? I'm back building a global app.

If this issue is not related to Ember-CLI, My apologies. Please close this ticket. Most of all tanks for your awesome work with Ember and Ember-CLI! Just hope that I will be able to convert to ember-cli some day... 

Thanks

**Comment by stefanpenner** [comment]
> I'm getting following error with "ember new" command: Failed to execute "git ls-remote --tags heads git://github.com/ember-cli/loader.js.git"

we can release these as npm packages and be done with it.

that being said, there is a simple solution: http://stackoverflow.com/questions/5529218/how-to-use-git-behind-a-proxy

**Comment by rwjblue** [comment]
Tagged releases should be downloaded as `.tar.gz` from bower (not `git://`).

**Comment by stefanpenner** [comment]
i suspect it may also be an old version of NPM.

**Comment by 20v100** [comment]
So, if I understand this right, a new tagged version of ember-cli will be available in the future solving my issue?
I have tried with no avail: http://stackoverflow.com/questions/5529218/how-to-use-git-behind-a-proxy

- git clone http://github.com/ember-cli/ember-cli-shims.git return "fatal: unable to access 'http//github...' " error 407.

- Cygwin does not seems to have a socat package anymore.

My mpn version is: 2.5.1.

But at this point, I think my issue must be due to my lack of knowledge of GIT, bower, broccoli etc. This is certainly of to the core team to help me with this. I will wait a newer version of Ember-cli.

Thanks for everything.

**Comment by barneycarroll** [comment]
I'm behind a proxy and failed to build previous Ember projects relying on a combination of Git, Bower & NPM. I resolved these issues step by step via individual configurations for each tool. Now I'm running `ember new` and getting this. I tried global SSH config over the top of it, no result.

> we can release these as npm packages and be done with it.

That's a really nice idea. Why was the issue closed without implementing this?

**Comment by stefanpenner** [comment]
> Why was the issue closed without implementing this?

We do not consider it a bug that restrictive firewall rules block some valid forms of internet traffic. We will be moving away from bower for other reasons which will incidentally improve the experience for such users.

**Comment by 20v100** [comment]
This is not a solution but I ended up using Nitrous IDE cloud services to circumvent the issue of my Enterprise firewall. However, Nitrous service has been deteriorating lately. Looking forward to see if moving away from Bower will help.

**Comment by barneycarroll** [comment]
> We will be moving away from bower for other reasons

Can I help you with that? Say, fork `ember-cli` to get maintained internal deps from github directly? Or should I stop pestering and just use another tool?

**Comment by stefanpenner** [comment]
@barneycarroll I have worked in several quite restrictive corporate environments.

The following https://coderwall.com/p/sitezg/force-git-to-clone-with-https-instead-of-git-urls worked in most cases.

In others, a specific proxy was provided, and http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server worked correctly.

Git has built in facilities to mitigate this problem.

**Comment by barneycarroll** [comment]
Apologies @stefanpenner - I had a lurking higher order misconfiguration of `https proxy` which was causing the issue. My mistake was in having too many configuration files that I wasn't keeping track of. The totality of the solution for my particular variation of problem was in configuring `.bowerrc`, `.gitconfig` & `.npmrc` with the correct `http` && `https` properties pointed to the relevant `protocol://username:password@server:port` strings.

Thanks for your patience and prompt replies.

**Comment by stefanpenner** [comment]
@barneycarroll no problem, many moving parts gets problematic at times. We will strive to remove some of these moving parts.

**Comment by marcusjwhelan** [comment]
@20v100 You should try cloud9.io or c9.io. It is developing fast and I have been able to make many apps on its environment with ease.
