### ISSUE TITLE
[Feature Request] Don't do a full page reload when scss/css changes

### ISSUE THREAD

**Issue by cjroebuck** [ember-cli/ember-cli#3388]
It would be really nice to have styles auto-update in the browser without requiring a full page refresh.
 
I tried to prevent brocolli / ember-cli from live reloading my browser on scss/css files using the `liveReloadFilterPatterns` in BrocFile.js and also the server/index.js hack from #2481 but had no luck. 

The reason I wanted to prevent ember-cli from auto-reloading on style changes was so that I could try and experiment with using a gulp workflow using browsersync or takana to update the styles without refreshing the page every time. 

Is this something that might be possible to have as an ember-cli addon or perhaps the default action for css changes?

**Comment by stefanpenner** [comment]
dupe: https://github.com/ember-cli/ember-cli/pull/2465

also if you want to request something, feel free to use the rfc process https://github.com/ember-cli/rfcs
