### ISSUE TITLE
Nested acceptance tests generated with --pod don't require startApp properly

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#3389]
Simple to reproduce:

`ember g acceptance-test post/new --pod` will generate a file named `tests/acceptance/post/new-test.js` like this:

```js
import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from '../helpers/start-app';

var application;

module('Acceptance: PostNew', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('visiting /post/new', function(assert) {
  visit('/post/new');

  andThen(function() {
    assert.equal(currentPath(), 'post/new');
  });
});
```

The wrong bit is that the line `import startApp from '../helpers/start-app';` should be `import startApp from '../../helpers/start-app';`.

Detected in 0.2.0-beta.1, but I haven't tried in master. However, I haven't seen any PR related to this in the last days.

I'm going to fix it myself this afternoon, but I put it for the record, because I have a terrible memory.

**Comment by rwjblue** [comment]
Should be fixed on master in https://github.com/ember-cli/ember-cli/pull/3353, please close once you confirm...

**Comment by cibernox** [comment]
Ok, the absolute path fixes it. I didn't see the PR because the text was not descriptive.

You're too efficient. One cannot even contribute back because some of you already did!
