### ISSUE TITLE
Running test cases with different configs

### ISSUE THREAD

**Issue by sameersegal** [ember-cli/ember-cli#3390]
Hi, I want to run my tests with different configs. I tried to set the new config in the `<meta>` using the following in my `beforeEach` but it didn't work

``` $("meta[name='app/config/environment']").attr("content", newConfig) ```

I even tried:

```
define('app/config/environment', ['ember'], function(Ember) {
  return { 'default': newConfig };
});
```

Any tips on how to do this will be most appreciated. Thanks

**Comment by rwjblue** [comment]
@sameersegal - Just import the config object, and mutate it (then set it back to original value in `afterEach`).

Something like what I am doing in https://github.com/ember-cli/ember-export-application-global/blob/master/tests/unit/initializers/export-application-global-test.js#L8-L25.

**Comment by sameersegal** [comment]
Thanks @rwjblue - this is really helpful!
