### ISSUE TITLE
Best way to Extend Resolver from Ember Addon?

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#3392]
HI Guys!

Working on an addon that will require some extra template resolving logic.  

Feel like the below should work, but no dice:

(Initializer from addon's `app` directory)

```js
export function initialize(container, application) {
  application.Resolver.reopen({
    resolveTemplate: function(parsedName) {
      this._super.apply(this, arguments);
      console.log('Hello World!');
    }
  });
}

export default {
  name: 'add-template-resolving-logic',
  initialize: initialize
};
```

Will document how to do this once it's worked out - any clues?

**Comment by lukemelia** [comment]
AFAIK, you would need to have the end-user specify your resolver in his or her `app.js`.

**Comment by hhff** [comment]
Thanks @lukemelia!
