### ISSUE TITLE
Can I disable test in development build ?

### ISSUE THREAD

**Issue by msalahz** [ember-cli/ember-cli#3393]

**Comment by Evkin** [comment]
//Brocfile.js
var app = new EmberApp({
  **tests: false**
});

**Comment by msalahz** [comment]
Thank you @Evkin.
Is this documented anywhere ?

**Comment by Evkin** [comment]
I don't know... :-)   My solution is based on source code

**Comment by msalahz** [comment]
Thanks again @Evkin
