### ISSUE TITLE
SilentError breaks handlebars error messages

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#3395]
This line in handlebars:

https://github.com/wycats/handlebars.js/blob/64ab232d723f5935e21b0e470d04dcf369986172/lib/handlebars/exception.js#L15

expects to be able to `call` the `Error` constructor and get back a value. But it looks like ember-cli is replacing `Error` with `SilentError`, and the above line ends up with `tmp` undefined, resulting in a new exception that obscures the underlying exception.

To reproduce, just drop this template into your application:

````handlebars
{{#misspelled-componen}}
{{/misspelled-component}}
````

**Comment by twokul** [comment]
@ef4 which version are you referring to? I believe `ember build` will fail to run for the template above if you're on the latest `ember-cli`
![screen shot 2015-03-02 at 9 25 53 am](https://cloud.githubusercontent.com/assets/1131196/6446186/2bd34308-c0be-11e4-9fac-1cf45e53a8eb.png)

**Comment by twokul** [comment]
@ef4 regardless of version, we should fix. I'll look into it today.

**Comment by stefanpenner** [comment]
What the shit, why are we replacing the global Error...

**Comment by stefanpenner** [comment]
found it.

**Comment by twokul** [comment]
@stefanpenner I was just about to commit it

**Comment by stefanpenner** [comment]
@twokul sure sure

**Comment by stefanpenner** [comment]
https://www.youtube.com/watch?v=pkdmu2M7qFo
