### ISSUE TITLE
Content-for documentation missing

### ISSUE THREAD

**Issue by seb2411** [ember-cli/ember-cli#3397]
Hello,

I'm just beginning to test Ember-Cli as I want to develop some applications with EmberJs. But I have a problem. Ember-Cli is generating some {{content-for ... }} tags and in the index file. I have no idea how they works.I can guess the idea but I can't found any example/documentations/information.

Someone can help me ?

Thanks,
Sebastien.

**Comment by Dhaulagiri** [comment]
There is some documentation on that [here](http://www.ember-cli.com/#appindexhtml)

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#contentfor
