### ISSUE TITLE
The index route and template in the pods don't work.

### ISSUE THREAD

**Issue by imfly** [ember-cli/ember-cli#3404]
Hi, when i use the --pod, i find the follow problem, don't know it's why.

```
#config/environment
var ENV = {
    modulePrefix: 'todos',
    podModulePrefix: 'pods', 
...
```

1. 
```
ember g route todos --pod

installing
  create app/pods/todos/route.js
  create app/pods/todos/template.hbs
installing
  create tests/unit/pods/todos/route-test.js
```

but when call http://localhost:4200/todos it doesn't work.

2.
```
ember d route todos --pod
ember g route todos

installing
  create app/routes/todos.js
  create app/templates/todos.hbs
installing
  create tests/unit/routes/todos-test.js
```

This's ok.

Anyone knows it's why.

My Versions:
Ember-cli  0.2.0-beta.1
Ember 1.10.0
Ember Data 1.0.0-beta.15
jQuery 1.11.2

**Comment by karelvuong** [comment]
Hey @imfly, try changing your `podModulePrefix` in `config/environment.js` to:

```js
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'todos',
    podModulePrefix: 'todos/pods',
    ...
}
```

As seen in http://www.ember-cli.com/#pod-structure, the POD path should use the following format: `{appname}/{poddir}`.

:smile:

**Comment by imfly** [comment]
Thanks @karelvuong . Well, I need to take a good look at the document. It will still have problems to use Ember-cli with RoR's mind.If in rails, i think that it don't need 'appname' which has been set by 'modulePrefix'.

**Comment by twokul** [comment]
@imfly as suggested by the docs, the pod path should be `{app-name}/{pod-dir}`.
