### ISSUE TITLE
Every time generate http-mock is run npm tries to install package connect-restreamer

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#3406]
I'm not sure this is by design but every subsequent run of `generate http-mock .. ` npm tries to install package connect-restreamer, does this have to be attempted each time?

**Comment by lolmaus** [comment]
Also experiencing `npm install` running on every `ember g http-mock ...`.

**Comment by QuantumInformation** [comment]
I also find that if I do `http-mock app/foo` I will get  model inside an models/app/foo.js folder, is this by design?

**Comment by lolmaus** [comment]
> @QuantumInformation 
> I also find that if I do http-mock app/foo I will get model inside an models/app/foo.js folder, is this by design?

I do not observe that behavior (0.1.15).

**Comment by QuantumInformation** [comment]
Was also wondering if we could include a check for server mocks when we do an ember init. We could add the required packages  to the package.json:
eg:

```js
   "express": "^4.12.3",
    "glob": "^4.5.3",
   "morgan": "^1.5.2"
```

Although its also fine to expect users to maintain their own dependancies after upgrade.

**Comment by abuiles** [comment]
@ef4 based on https://github.com/ember-cli/ember-cli/commit/f67a6dc9c1f7dc91eb2b64b12bc98bd17160d697 it looks we can actually kill connect-restreamer here too?

**Comment by ef4** [comment]
Yes, I think it's unintentional that the http-mock blueprint still mentions connect-restreamer. The actual mock file doesn't try to require it.

**Comment by stefanpenner** [comment]
Ya. Kill it with fire!
