### ISSUE TITLE
JavaScript error when loading production build: Uncaught #<o>  Win8.1 Ember CLI 0.2.0-beta.1

### ISSUE THREAD

**Issue by durkes** [ember-cli/ember-cli#3415]
I cannot successfully build using ember CLI in Windows. The preview on :4200 works, but production build will not. I changed as little as possible to re-create the error. The error is thrown from the vendor...js around:
```js
"cancelRouterSetup")&&(this._setupRouter(t,r),n.register("view:default",U),n.register("view:toplevel",H.extend()),r.onUpdateURL(function(e){i.handleURL(e)}),"undefined"==typeof o&&(o=r.getURL()),e=this.handleURL(o),e&&e.error))throw e.error}
```

To recreate the issue, I am using:
Windows 8.1
ember -v
version: 0.2.0-beta.1
node: 0.12.0
npm: 2.1.8

My steps:
ember new nochanges
changed one line environment.js:
```js
  if (environment === 'production') {
    ENV.baseURL = '/dist/';
  }
```
```
ember build --environment=production
```

Uploaded dist folder to /dist on webserver. Accessed /dist/index.html and error occurs.

Please let me know if I need to provide additional information. Thank you

**Comment by durkes** [comment]
This issue is the same as https://github.com/ember-cli/ember-cli/issues/3416
I did another test and set locationType to none - and no error.

FYI: I just uninstalled and reinstalled according to the ember-cli release notes and the issue is still present.

**Comment by Lxrd-AJ** [comment]
Just to further comment on what @durkes wrote, i had the same issue when i changed the baseURL to a custom one and i had the same error. I follow what @durkes wrote and changed the locationType to none and it worked!
