### ISSUE TITLE
New ember-cli generated app doesn't report errors properly

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#3416]
Reproduction steps:
- Create a new ember-app (`ember new test-app`) and start the server (`cd test-app && ember s`)
- Load the app in a browser and try accessing a nonexistent route by changing the URL
- Observe console error

Using Ember.JS 1.10 via globals (on JSBIN):
```
Error: Assertion Failed: The URL '/not-a-real-route' did not match any routes in your application
```

Error seen in the just-created app:
```
Uncaught #<UnrecognizedURLError>
```

Version information:
```
$ ember -v
version: 0.2.0-beta.1
node: 0.12.0
npm: 2.1.8
```

**Comment by stefanpenner** [comment]
although this seems like a pain, this isn't a bug in ember-cli. Rather something funky on the ember side, but i'll take a look

**Comment by stefanpenner** [comment]
it seems like `UnrecognizedURLError` isn't a subclass of `Error`.

**Comment by SaladFork** [comment]
Hmm.. any idea why it seems to behave properly in JSBin despite both using Ember 1.1.0?

**Comment by stefanpenner** [comment]
seems to be fixed by: https://github.com/tildeio/router.js/pull/151



> Hmm.. any idea why it seems to behave properly in JSBin despite both using Ember 1.1.0?

maybe the eval + cross iframe stuff? I suspect that might be it.

**Comment by stefanpenner** [comment]
@SaladFork do you mind, pushing the updated router.js into ember? I wont have time to do that right now.

**Comment by SaladFork** [comment]
I don't know how to do that but wouldn't mind at all.

**Comment by SaladFork** [comment]
Would I just make a pull request to make the same changes to [Ember's router.js](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js)?

**Comment by stefanpenner** [comment]
related error: https://github.com/emberjs/ember.js/issues/10571

> Would I just make a pull request to make the same changes to Ember's router.js?

it comes via bower: https://github.com/emberjs/ember.js/blob/master/bower.json#L11

**Comment by SaladFork** [comment]
Anything else I need to do?

**Comment by stefanpenner** [comment]
@SaladFork yes https://github.com/emberjs/ember.js/issues/10571

**Comment by SaladFork** [comment]
I've submitted PR emberjs/ember.js#10572

**Comment by stefanpenner** [comment]
@SaladFork ah awesome, for some reason i didn't see that.

**Comment by erichonkanen** [comment]
im getting this in a brand new ember/ember-cli app using latest 2.5.1
