### ISSUE TITLE
Ability to add an addon's dependencies to a project when its a dependency of another addon

### ISSUE THREAD

**Issue by cristinawithout** [ember-cli/ember-cli#3418]
Use case:

There are 3 addons.

Addon-b has a dependency on addon-a. Inside addon-b's default blueprint, it uses `addPackageToProject('addon-a')`.

Running `ember install:addon addon-b` adds addon-b and addon-a to the project.

Addon-c has a dependency on addon-b. Inside addon-c's default blueprint, it uses `addPackageToProject('addon-b')`.

Running `ember install:addon addon-c` adds addon-c and addon-b to the project. But addon-a, which is a dependency of addon-b is not added to the project.

A simple 'solution' is to add `addPackageToProject('addon-a')` to addon-c's blueprint. But that's not ideal since addon-c should not need to know all of the dependencies of addon-b.

If addon-b's default blueprint were run when it was added to the project by addon-c's blueprint, all 3 addons would be added to the project as needed.

**Comment by stefanpenner** [comment]
As of recently @ef4 added the ability to find the root app. We will also continue to tackle this as @chadhietala's work evolves.

Closing as now that we have an RFC process these "wish" issues are no longer needed. This is totally on the radar as a "thing that sucks" but the current state is by-design, we hope to improve going forward.
