### ISSUE TITLE
Make ember-cli compatible for legacy dojo or require AMD

### ISSUE THREAD

**Issue by ffaubry** [ember-cli/ember-cli#3420]
I'm logging this issue following a discussion at EmberConf 2015 with @stefanpenner.
I need to use a dojo AMD based library (https://developers.arcgis.com/javascript/). 
Up to today I was loading ember as a legacy js lib using the following dojo config:
```
<script>
window.dojoConfig = {
  async: true,
  baseUrl: "./",
  packages: [
    {"name": "esri", "location": "js/jsapi/esri"},
    {"name": "dojo", "location": "js/jsapi/dojo"},
    {"name": "dijit", "location": "js/jsapi/dijit"},
    {"name": "dojox", "location": "js/jsapi/dojox"},
    {"name": "dashboard", "location": "js/dashboard"}
  ],
  paths: {
    "jquery-lib": "libs/jquery/jquery-2.1.1.min",
    "handlebars-lib": "libs/ember/handlebars.min",
    "ember-lib": "libs/ember/ember.min"
  }
};
</script>
<script src="js/jsapi/dojo/dojo.js"></script>
<script src="js/dashboard/run.js"></script>
```

Then in my run.js, I could control the sequence:

```
    require(["handlebars-lib", "jquery-lib"], function (handlebars) {
      window.Handlebars = handlebars;
      require(["ember-lib"], function () {
        require(["dashboard/main"]);
      });
    });

```

Basically, I was loading Ember thru the dojo loader.

I have difficulties to understand how this would work under ember-cli:
a) How can we import dojo AMD modules in my app modules?
b) The ember-cli AMD loader seems to have been optimized to load named modules and the whole asynchronous loading has been removed. I could compile the whole dojo into a single file but it's defeating my goal. I was hoping that my dojo dependencies would be merged in the vendor.js file.

**Comment by stefanpenner** [comment]
I think one approach, is the ability to build an ember-cli app (easily) in a no-conflict mode.

**Comment by jrowlingson** [comment]
@stefanpenner could you expand a bit on how to build an ember-cli app in a no-conflict mode?

**Comment by stefanpenner** [comment]
> @stefanpenner could you expand a bit on how to build an ember-cli app in a no-conflict mode?

it is a proposed solution, not an actual solution.

**Comment by stefanpenner** [comment]
> This is unfortunately low on my priority list so I am unsure when I personally will get to it. Maybe for someone else it is higher priority, if so. Written up a proposal in the form on a RFC @ https://github.com/ember-cli/rfcs would likely be a good start.

**Comment by stdavis** [comment]
Did anything ever happen with this that you know of?

**Comment by jrowlingson** [comment]
@stdavis https://github.com/ember-cli/ember-cli/pull/5976 made some progress towards partial support for anonymous modules. async modules are not supported that I know of yet - I don't see an easy path to do so either. Some folks created an addon, [ember-cli-amd](https://github.com/Esri/ember-cli-amd), as a workaround but this is more of an epic hack to support loading async/anon modules into the ember build pipeline which is looking for sync/named modules. essentially it loads dojo's modules via dojo's loader and then [pulls them into](https://github.com/jrowlingson/loader.js/commit/99cd1efe085a19a1744c4acb54c4cb10bbc64fdc) ember's module registry.

**Comment by stdavis** [comment]
Thanks for the update.
