### ISSUE TITLE
[Proposal] Remove `podModulePrefix` from ember-cli

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3424]
As a step towards using [pods as the default structure](https://github.com/ember-cli/ember-cli/issues/2646) for ember-cli, I believe we should get rid of the `podModulePrefix` and just put pods in the app folder. Because the value is customizable, it causes a break in our convention when looking up modules. Most people use the default `pods` anyhow, but the fact that it is customizable means that looking up a pod in your project could be different than how developers [structure pods in their addon](#2768).

**Comment by rwjblue** [comment]
I **hate** podModulePrefix. I'm definitely 👍 for removing it (with a deprecation period).

**Comment by twokul** [comment]
this is nice.

**Comment by trabus** [comment]
I'm going to start work on this likely next week. First I'm going to try and get ember-cli-podify finished, and add support to remove the `podModulePrefix` through a flag `ember podify --noprefix`.

I'm also going to finally get a dev blog setup and will write up a post on how to use ember-cli-podify to update your project so you don't have to do it manually (though I'll include manual instructions as well for those who'd rather do it themselves).

**Comment by trabus** [comment]
I got a bit derailed with replacing marked with markdown-it, but should have some time to pick this back up tomorrow. I'l like to get the deprecation warning in as soon as possible, preferably in the next release.

I'll write up some manual instructions on what needs to be done to move existing files away from using podModulePrefix, since I'm not sure I'll have much time to get the podify addon done before next week.

**Comment by rwjblue** [comment]
@trabus - Deprecation (but still functionally the same) for a version sounds exactly correct.

**Comment by rwjblue** [comment]
The deprecation has landed in ember-resolver (in https://github.com/ember-cli/ember-resolver/pull/88).  

Now ready to update the `generate`/`destroy` commands and bump the included version of the `ember-resolver` to 0.1.13.

@trabus - Thanks for keeping on this..

**Comment by SaladFork** [comment]
I was concerned about this deprecation warning as we have a "services" route and with pods being moved to the `app` folder it seemed we would have to put the JS files alongside Ember services, such as:

```
// Before:

app/pods/services/route.js
app/pods/services/controller.js
app/services/geolocation.js

// After:

app/services/route.js
app/services/controller.js
app/services/geolocation.js
```

Similar cases exist if you had a "templates" or "styles" route, for example.

I brought this up on IRC and was informed that you can pod services (and styles -- not sure how?) now so this is may not be a big issue, but I wanted to capture the concern.

Example of "podded" service:
```
app/services/route.js
app/services/controller.js
app/geolocation/service.js
```

**Comment by stefanpenner** [comment]
if we drop legacy mode entirely this would be fine, but i don't see how to do this incrementally safely without `pods` like directory.

**Comment by trabus** [comment]
Services are currently not one of the blueprints that supports pods right now, but they can easily do so if desired. The initial idea of removing `podModulePrefix` was to standardize the path the resolver uses for pod lookups so addons could start using pods.

If we need to temporarily disable the deprecation warning for now we can easily comment it out. There was no change to support for `podModulePrefix`, so nothing to revert there.

If pods are the intended future, maybe flipping things and moving non-pod assets to a standardized location would be beneficial. Maybe capitalizing or prepending the non-pod folders with something could signify a difference. Whatever happens, we'll need to find a way for the two structure types to live together.

**Comment by dfreeman** [comment]
I love the idea of standardizing pod resolution, but it feels like intermingling pods with directories for non-pod entities like `services` makes it harder to tell at a glance what you're looking at, particularly for someone new to Ember.
I definitely understand wanting to avoid excessive nesting, but I hope there's a solution that doesn't eliminate all visual distinction in the file structure between pods and everything else.

**Comment by samselikoff** [comment]
Is there an alternative way to specify a pods directory? I like pods because, that's where code directly related to my UI/view hierarchy lives. Mashing those dirs up with everything else would be really messy.

**Comment by trabus** [comment]
@samselikoff what types of assets do you have that don't live in the pod folder?

I think there is definite value in having certain types of assets in the basic structure, and I can see how being able to keep them separate from your pods is desirable. Maybe going forward we can keep `app/pods` and enforce that as the standard, rather than getting rid of `podModulePrefix`. Again, my main goal for removing it was to standardize a convention so we can use pods in addons.

I'm starting to think that the future version of ember where we're primarily using components, routes, and services should be the time to revisit the structure. Maybe we create another version of the resolver for ember 2.0, and allow the user to select their resolver, much like the [plugin(s) ember 2.0 will provide](https://github.com/emberjs/rfcs/blob/6e0fba702c93b4305741c8a449fb8da060ab15cb/active/0000-the-road-to-ember-2-0.md#transition-plan-6) for backward compatibility. Maybe removing it now is optimizing too early. :\

**Comment by samselikoff** [comment]
Im all components and services now, but `/pods` still makes sense to me. Maybe I'm missing something - you're talking about removing a separate `/pods` (or whatever its named) directory at all, correct?

Here's the structure for my current project:

```
app
  adapters
  helpers
  initializers
  mirage
  mixins
  models
  pods
    application
    components
    inbound
    logs
    modals
    network-record
    outbound
    talk-finder
    xml-imports
  serializers
  services
  styles
  transforms
  transitions
  utils
config
public
tests
```

and my router

```js
Router.map(function() {
  this.route('network-record', {path: '/'});

  this.route('inbound', function() {
    this.route('completed', function() {
      this.route('ingest', {path: '/:ingest_id'});
    });
  });

  this.route('outbound', function() {
    this.route('active');
    this.route('summary', {path: '/'});

    this.route('completed', function() {
      this.route('outbound-transfer', {path: '/:outbound-transfer_id'});
    });

    this.modal('modals/new-transfer', {
      withParams: 'newTransfer',
      dialogClass: 'modal-dialog',
      actions: {
        createTransferRequest: 'createTransferRequest'
      }
    });
  });

  this.route('talk-finder', function() {
  });

  this.route('xml-imports', function() {
    this.route('completed', function() {
      this.route('fcpxml', {path: '/:fcpxml_id'});
    });
  });

  this.route('logs');
});
```

You can see everything under `/pods` is directly related to my UI hierarchy - makes it really nice for anyone (whether they're familiar with the project) to look at a particular route and know where to go. 

All the stuff outside of pods is app-wide: services, models etc. I think it's very nice to separate the UI-related from code that's not directly related to UI. You can see this project would be pretty messy if all the pods were moved to `/app`.

**Comment by trabus** [comment]
@rwjblue I think maybe we should hold off on the deprecation warning for another release, or at least until we've got a solid plan moving forward. I can work on the PRs to do this if you're :+1: 

@samselikoff not to derail this into a [pod structure proposal thread](https://github.com/ember-cli/ember-cli/issues/3234) but would something like this work for you?
```
app
  helpers
  initializers
  mirage
  mixins
  data
    network-record
       model
       adapter
       serializer
  ui
    application
    components
    inbound
    logs
    modals
    network-record
    outbound
    talk-finder
    xml-imports
  services
  styles
  transforms
  transitions
  utils
config
public
tests
```

**Comment by samselikoff** [comment]
yep ui would work, does that mean I'd need to nest all my routes under `this.route('ui')`?

**Comment by runspired** [comment]
@trabus out of curiosity, what is mirage for?

I'm also against putting pods directly in `/app`, and I'm not a fan of this `ui` approach. What I'd really like to see is a standardized pod structure sort of like this.

```
app/
    helpers/
    initializers/
    mixins/
    models/
        foo-model/
            adapter.js
            serializer.js
            model.js
    components/
        bar-component/
            component.js
            layout.hbs
            default.css
    
resources/        //really a resource ;)
        application/
            controller.js
            view.js
            template.hbs
            index/                 //routes go in their relative resource
                controller.js
                view.js
                template.js
        spam-resource/
            index/
                controller.js
                view.js
                template.js
        egg-route/                //top level routes go in here too
            controller.js
            view.js
            template.js
            egg-sub-route/        //routes within routes are nested just like routes within resources.
                controller.js
                view.js
                template.js
            
```

**Comment by trabus** [comment]
@samselikoff No, the `ui` would replace `pods` as the `podModulePrefix`. The resolver would also have rules for `data` when looking up models, adapters, and serializers. What you were saying just solidified an idea for me, along with what some of the [proposals](https://github.com/ember-cli/ember-cli/issues/3234) [in the thread](https://github.com/ember-cli/ember-cli/issues/3234#issuecomment-75652883).

The idea of one pod namespace might be too much weight for it to bear. Separating the concerns into a few pod namespaces and standardizing that may be a path forward that could work for everyone.

**Comment by trabus** [comment]
@runspired I was just spitballing really, I'm not married to any specific structure yet, just playing with the idea. Your structure you describe, from what I was thinking `ui` would be it's equivalent of `resources`, and `resources` is probably a better name for it.

Ultimately this is what I wanted to achieve with the [Structures rfc](https://github.com/ember-cli/rfcs/pull/5), is a way to create these experimental structures, then provide a way to [safely convert your project](https://github.com/trabus/ember-cli-podify) between them.

I'm now realizing this probably should have been an RFC before it was acted upon. :\

**Comment by runspired** [comment]
@trabus I realized I'd left my top level out of application, so I just adjusted that.  I also forgot I also really want nested components, so I just added that.  I'd love to see an RFC for this.

**Comment by samselikoff** [comment]
btw nested components exist, i do this now ( put them in my pods )

@trabus i really like having a pod for top-level routeable components and a different pod for data (models/adapters/serializers). Really coo.

**Comment by runspired** [comment]
@samselikoff eesh, never saw that was a feature anywhere (and didn't notice the resolver log looking there) so never tried it.  *exits to refactor*

**Comment by trabus** [comment]
What @runspired has actually covers a few of the concerns I've seen, global ui (`app/components`), route specific ui (`app/resources`), and data(`app/models`, though I'd use `app/data` to not collide with the existing models dir).

Also @runspired, the mirage directory is from [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage), an awesome data mocking project by @samselikoff.

**Comment by nathanpalmer** [comment]
Throwing my 2cents in here. 

Just removing podModulePrefix doesn't quite work for us as it mixes concerns too much and I was surprised when I saw the deprecation warning. Much of my pod structure feedback you can see in [the alternate pod structure proposal](3234). I'm in favor of @runspired's comment which is pretty similar to [my namespaced proposal](3234#issuecomment-73759572) and is in-fact what we use in our apps. Getting to use that format required a custom resolver including an entire set of blueprint overrides to make sure files get generated in the right place.

_Somewhat related_: We also use nested components under resources and routes for very specific  route components.

**Comment by trabus** [comment]
@nathanpalmer I'm working on the pods RFC and should have it posted by the end of the week. I'm starting to see a lot of "cowpaths" forming around breaking data, routes, and components into pod namespaces, and leaving the rest as is. I'm currently working out how to best deal with this and not introduce additional complexity.

**Comment by jayphelps** [comment]
@trabus What's the latest on this? If an RFC was posted elsewhere, can you link us?

**Comment by trabus** [comment]
I halted work on my RFC since @chadhietala was [already working on one](https://github.com/emberjs/rfcs/pull/44). 

I believe that currently, the state of pods is dependent upon the implementation of engines, as it should provide namespacing that will help solve some of the concerns around removing the podModulePrefix.

**Comment by runspired** [comment]
@trabus @jayphelps I kinda delayed mine to see what the others and engines looked like too.  Regardless, I think there's a solid consensus around the general direction of structure and mostly it comes down to a few naming conventions at the end.

**Comment by drewbaker** [comment]
I just wanted to throw out something I haven't seen mentioned. If you remove the `/pods` structure, and put everything in the `/app`, don't you then also stop people from ever having a `/models` or `/controllers` route? What if I'm building a site for a scale model maker? Or a video game controller manufacture?

**Comment by devinus** [comment]
@samselikoff What project allows you to use `this.modal` in your router?

**Comment by samselikoff** [comment]
Liquid fire, though I'm using ember-modal-dialog for modals now these days

**Comment by justtal** [comment]
I really like @runspired structure. Put all pods in app is just confusing and mixed up things.

**Comment by stefanpenner** [comment]
this will likely stick around for now, but when the new modules work lands will be revisited (although we will do our best to support this until it is reasonable to remove it)
