### ISSUE TITLE
Import path is not filesystem path

### ISSUE THREAD

**Issue by janmisek** [ember-cli/ember-cli#3427]
Relative filesystem path is:
```import {util} from 'project/app/utils/file2```

but Ember CLI expect import path: 
```import {util} from 'project/utils/file2'````

I am using IDE (webstorm) for rapid development, this import notation makes IDE unable to resolve the files, even when changing resource root because there is "app" segment missing.

Also there could be confusion regarding to relative import paths (../../file2). These are the filesystem path compatibile.

**Comment by janmisek** [comment]
Found out workaround:
```
# Brocfile.js
//...
var app = new EmberApp({
  name: 'project/app'
});
//...
```
and
```
# config/environments.js
//...
modulePrefix: 'project/app',
//...
```
Now imports respect the filesystem paths ```import {util} from 'project/app/utils/file2```. IDE works as expected - e.g. I can inspect class when clicking on imports, code completion works and so on.

There is also side effect which builds css and js to ```dist/assets/project/app.js```  instead of ```dist/assets/project.js```.  

Anyway can someone experienced with Ember CLI internals explain to me whether there is a reason to remove the "app" segment from imports.

Also I can do pull request to fix this by default, but it would be BC to existing apps and addons. On the other side I consider this as serious drawback of Ember CLI when using of advanced javascript editors as WebStorm.

**Comment by janmisek** [comment]
Also build side effect could be fixed:

# Brocfile.js
//...
var app = new EmberApp({
  name: 'phone/app',
  outputPaths: {
    app: {
      html: 'index.html',
      css: {
        'app': '/assets/phone.css'
      },
      js: '/assets/phone.js'
    }
  }
});
```

**Comment by stefanpenner** [comment]
Im not at all apposed to making this change. It will just require appropriate deprecation  and likely an upgrade script for people


@wycats r?

**Comment by rwjblue** [comment]
@stefanpenner - I've been in favor of making these match for quite some time.  We will have to come up with a path forward for existing users (possibly enlist @abuiles to add to his `ember watson`?), but it results in a massively easier way to reason about file location vs module location...

**Comment by jesse-black** [comment]
:+1: this would also fix error messages and make it easier for editors to link error messages to the right file.

**Comment by stefanpenner** [comment]
some stuff, we may address as we work on the over-all packaging story.

**Comment by gitowiec** [comment]
Hi, what's going on with this issue? Any decisions regarding it and forthcoming Ember 2.0?
Missing Ide resolving names is PITA!

**Comment by stefanpenner** [comment]
this will be a breaking change, future versions will likely explore this to improve IDE integrations.
