### ISSUE TITLE
0.2.0.beta.1 fails to create add on when installed sudo nom install -g ember-cli

### ISSUE THREAD

**Issue by technomage** [ember-cli/ember-cli#3429]
MBP:projects lattam$ ember addon ember-cli-clean
version: 0.2.0-beta.1
EACCES, permission denied '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
Error: EACCES, permission denied '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Class.module.exports.generatePackageJson (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:29:8)
    at Class.module.exports.files (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:81:10)
    at Class.Blueprint.install (/usr/local/lib/node_modules/ember-cli/lib/models/blueprint.js:341:36)

It appears to be writing to the blueprint which is owned by root rather than the current user.

**Comment by stefanpenner** [comment]
Installing and using `npm` and things in this ecosystem with `sudo` is not supported. 

resources:
* http://stackoverflow.com/questions/16724259/npm-command-sudo-or-not
* https://github.com/danielchatfield/npm-sudo-fix

**Comment by technomage** [comment]
Understood.  I will change my practices.  But, writing to the installation directory for each execution of the blueprint also has a "code smell" to me.

**Comment by shaunc** [comment]
I have run into this problem. I have tried to fix using https://github.com/danielchatfield/npm-sudo-fix ... now I can install globally without sudo. However, I still get 0.2.7 rather than 1.13.1 after install. Any pointers where the stuck files may be?
