### ISSUE TITLE
Proxying not working with rails api

### ISSUE THREAD

**Issue by salemtalha** [ember-cli/ember-cli#3432]
Hi,

I have a rails server that provides an api (for example, /api/foo.json) and when I set a brand new ember app to proxy to it I can't get the expected response. Instead I get the ember application layout.

However, when I curl the proxy url in a terminal I get the expected json object. 

I found out that that the 'text/html' in the accept header in the request to the proxy url is what causes this discrepancy. ie, when it's not there, I get what I want, but when it is I don't. But from what I understand this is set by the browser so not something I can change. 

Where would the problem be located here?

I'm using 
ember version: 0.2.0-beta.1
node: 0.12.0
npm: 2.1.8

Sorry if this is unclear, happy to clarify if there's any confusion.

**Comment by Dhaulagiri** [comment]
This seems like the kind of question that is better suited for StackOverflow. I suspect there is something amiss with how you are trying to proxy the request from your Ember app, but it's hard to tell without learning more about how you are proxying those requests.  If you post a question on SO with some more detail on how you are trying to proxy the requests you should be able to get this sorted out.

**Comment by salemtalha** [comment]
I'm only using the ember serve --proxy localhost:3000 command. That url is where my app lives

**Comment by drewnichols** [comment]
I'm having this exact same issue. Whenever a request is submitted to the node server on the path '/api/...' even with the proxy enabled it's not proxied when the request has an header of `Accept: text/html,*/*`.

has anyone devised a work around for this?

**Comment by abuiles** [comment]
@drewnichols are you using `--proxy`?

**Comment by drewnichols** [comment]
yep, although I realized after posting this that I'm seeing this problem on a older version of ember cli. it's 0.1.15 currently. I'm going to try and upgrade this app to see if that fixes it.

**Comment by drewnichols** [comment]
no luck after upgrading to CLI 0.2.5

**Comment by stefanpenner** [comment]
are you using body-parser?

**Comment by stefanpenner** [comment]
i just confirmed that a vanilla ember-cli works correctly.

steps to reproduce:

```sh
# set up a listener
nc -l -p 1234
```

```sh
# spawn ember-cli that proxies to the listener
ember s --proxy http://localhost:4200
```

```sh
# curl "as ajax"
curl -H 'X-Requested-With: XMLHttpRequest' -H 'Accept: application/json' localhost:4200/api/foo
```

result in the listener:

```sh
  % nc -l -p 1234                                                        !11994
GET /api/foo HTTP/1.1
accept: application/json
x-requested-with: XMLHttpRequest
host: localhost:1234
user-agent: curl/7.37.1
connection: close
```

as such it appears that the correct accept headers are being sent.

**Comment by stefanpenner** [comment]
ah, this was specifically for: `curl -H 'Accept: text/html,*/*' localhost:4200/api/foo` yes, this does not proxy.

**Comment by drewnichols** [comment]
I found a workaround. I generated an http-proxy using `ember generate http-proxy` and then used a path of `/api` and proxied all requests to /api to my backend and that seems to be working fine.

**Comment by stefanpenner** [comment]
> I found a workaround. I generated an http-proxy using ember generate http-proxy and then used a path of /api and proxied all requests to /api to my backend and that seems to be working fine.

Awesome, that is likely the approach I would recommend. `--proxy` is a nice quick & dirty setup for the odd proxy scenario.
