### ISSUE TITLE
usePods shouldn't require podModulePrefix to be set

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#3437]
I just set `"usePods": true`, but my CLI generators wouldn't actually create under the `/pods` directory until I explicitly set my `podModulePrefix`.

CLI version 0.1.15

Most people are probably using `app-name/pods` here - feel like that should be the default?

**Comment by trabus** [comment]
This is correct behavior. We're actually going to be deprecating `podModulePrefix` soon, so generating them in your `app/` directory is what you will want to be doing anyhow.

**Comment by hhff** [comment]
oh i see.  kk thanks @trabus
