### ISSUE TITLE
import swagger-client

### ISSUE THREAD

**Issue by ashrafhasson** [ember-cli/ember-cli#3441]
Hi there,

I'm trying to load swagger-client in an ember-cli 0.2.0.beta.1 project and failing to get it to work. 
I've installed `swagger-client.js` and `shred.bundle.js` via npm and tried to load the client with [ember-browserify](https://www.npmjs.com/package/ember-browserify) in an initializer but this approach yields an empty object when I use `import Swagger from 'npm:swagger-client'`, I'm not sure if that's because it relies on shred and that's not loaded?

Instead, I tried to incorporate them by placing them in `vendor/` to see if `SwaggerApi` is available as a global but it complains that it can't find some core node modules like `http`.

I apologize if this question is not supposed to be posted here, but really after understanding why it's not working in this way and how should it work instead, I already have an [SO](http://stackoverflow.com/questions/28824545/how-to-setup-ember-cli-project-with-swagger-client-to-use-dreamfactory-rest-serv) for this.

Appreciate any hints to help me understand, please.

**Comment by stefanpenner** [comment]
this is a better question to be asked on stackoverflow
