### ISSUE TITLE
Set prototype extensions to false by default for addons

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#3443]
See: https://github.com/dockyard/ember-validations/blob/master/tests/dummy/config/environment.js#L10

In ember-validations I have disabled prototype extension for the test suite. I believe that all addons should be developed with prototype extensions turned off to ensure the widest compatibility with how Ember is being used.

I don't have the time to add this into ember-cli, if anyone else wants to tackle that would be great. I'm not sure how best to accomplish this but the addon generator should be relying upon the `config/environment.js` from the app generator then modify the `EmberENV` object in the file to disable prototype extensions rather than generating its own file.

**Comment by hhff** [comment]
:+1:

**Comment by stefanpenner** [comment]
:+1:
