### ISSUE TITLE
skip-git flag is still looking for git

### ISSUE THREAD

**Issue by lmcardle** [ember-cli/ember-cli#3447]
Creating a new ember app with "ember new my-app --skip-git" throws an error that git is not in my path.  I am on a machine that does not have git and I do not want to put git on this machine.  I am on ember-cli version 0.2.0-beta.1

**Comment by raytiley** [comment]
I wonder if this is because we include `ember-cli-app-version` by default now. @taras will ember-cli-app-version gracefully fail if git isn't installed?

**Comment by taras** [comment]
@raytiley I will look into it this weekend.

**Comment by rwjblue** [comment]
It doesn't use git at all (at least my primitive lib that is built upon does not). It reads data from .git folder via standard fs functions

**Comment by taras** [comment]
@raytiley I just tested creating a new app with `--skip-git` and I didn't get a problem.
