### ISSUE TITLE
Addons depending upon addons is broken

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#3448]
I believe it was broken in 7d4f5d8c /cc @lukemelia 

Prior to this version addons were allowed to depend upon other addons. For example, ember-admin depends upon ember-cli-async-button. However, after this commit this functionality is now broken as dependent addons are no longer discoverable. This should be considered a regression and blocker for 0.2.0 IMO

**Comment by rwjblue** [comment]
I do not believe this is broken, but I am happy to track down what is going on. Please provide a reproduction.

**Comment by bcardarella** [comment]
@rwjblue its not working, I've confirmed with updating ember-admin to 0.2.0-beta.1. The `_notifyIncludedAddons` function does not have any dependent addons available to assign the `EmberApp` instance to.

**Comment by bcardarella** [comment]
Crisis averted, `master` seems to be OK.
