### ISSUE TITLE
File already exists "tmp/class-tmp_cache_dir-paLrsWyJ.tmp".

### ISSUE THREAD

**Issue by narayand4** [ember-cli/ember-cli#3453]
when i run ember serve in terminal then showing an error "file already exists tmp/class-tmp_cache_dir-paLrsWyJ.tmp". I have attached image of this error. please suggest me what i'm doing wrong?
![screenshot from 2015-03-07 18 35 07](https://cloud.githubusercontent.com/assets/214795/6541479/630be9ee-c4f9-11e4-987c-14764a3bc2f3.png)

**Comment by zjrosen1** [comment]
Please see #3413 and d4ec617

**Comment by narayand4** [comment]
thanks @zjrosen1 i have delete this line in package.json "glob": "^4.0.5" and then run rm -rf node_modules bower_components dist tmp; ember install. now my issue has been solved.
