### ISSUE TITLE
Build command should error with unknown environment

### ISSUE THREAD

**Issue by alexspeller** [ember-cli/ember-cli#3457]
```
ember build -prod   # works great
ember build -e prod # silently doesn't build in production mode
```

This is pretty confusing - shouldn't it error out if providing an unknown environment, or at least have shortcuts that are consistent?

**Comment by trabus** [comment]
@alexspeller the help lists out the shorthand option for environment as such:
```
  --environment (String) (Default: development)
    aliases: -e <value>, -dev (--environment=development), -prod (--environment=production)
```
We should definitely warn when an unknown environment is used. We can even refer to the proper use of the flag if you think it would be helpful.

**Comment by rwjblue** [comment]
We do not currently have a way to know what are known and unknown environments. I believe that @lukemelia and I have a proposal to fix that (hopefully more on that soon).

**Comment by stefanpenner** [comment]
:+1:
