### ISSUE TITLE
Lots of EEXIST on Windows

### ISSUE THREAD

**Issue by johnnyshields** [ember-cli/ember-cli#3461]
Using version 0.1.12 on Windows. Recently I did a clean NPM install and running `ember server` after the initial build I see this for subsequent builds:

```
EEXIST, file already exists 'C:\workspace\ts_ember\tmp\class-tmp_cache_dir-G3XrgJDe.tmp'
Error: EEXIST, file already exists 'C:\workspace\ts_ember\tmp\class-tmp_cache_dir-G3XrgJDe.tmp'
```

This is probably in some Ember CLI subcomponent which is not immediately obvious why. Filing issue here for now.

**Comment by okket** [comment]
Please see #3413
