### ISSUE TITLE
Add BrowserSync

### ISSUE THREAD

**Issue by oskarrough** [ember-cli/ember-cli#3462]
The [BrowserSync](http://www.browsersync.io/) package provides some really useful features for cross-device testing like synchronized livereload and interactions. It works great in [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp).

Would you be open for adding this to ember-cli as well? If not for all the features, the livereload alone could be worth it. Or should it rather be a broccoli wrapper or an ember-addon. Not entirely sure what would fit best.

Also see https://github.com/ember-cli/ember-cli/pull/2465 and https://github.com/ember-cli/ember-cli/issues/3388.

**Comment by rwjblue** [comment]
It should absolutely be possible to make an addon for this, but I do not think it requires integration in ember-cli itself.

**Comment by stefanpenner** [comment]
+1 for an addon. Even internals are ideally written as addons. So if it turns out to be great we can always pull it in

**Comment by stefanpenner** [comment]
not a bug, would accept PR or addon.
