### ISSUE TITLE
ember test ci --silent outputs warnings

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3466]
Running test in ci mode should *only* output test results so that test parsers will work. 0.2.0 is better than 0.1.15 which also pushed jshint to stdout, but is still broken.

If it is really hard to stop addons and plugins from writing to stdout, perhaps there should be a new test option *-out filename* which writes only the test output to that file. This way we wouldn't need the --silent flag and we wouldn't be broken by rogue addons.

```
G:\Projects\insm-ui>ember test ci --silent
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/rou
te-recognizer.js because ENOENT, no such file or directory 'G:\Projects\insm-ui\
tmp\tree_merger-tmp_dest_dir-B9sZ9zdA.tmp\bower_components\route-recognizer\dist
\route-recognizer.js.map'
<xml follows.../>
```

**Comment by Twinkletoes** [comment]
Workaround:
```
ember test ci --silent > ./build/reports/testresults.xml
cat ./build/reports/testresults.xml

sed -i '/^Warning:/d' ./build/reports/testresults.xml

cat ./build/reports/testresults.xml
```

**Comment by rwjblue** [comment]
Prior to 0.2.0 addons did not have the ability to access the internal 'ui' object which was aware of the log level (in the case of --silent this is set to log errors only). Now that addons can access this, they should be updated to use 'this.ui.writeLine' instead of 'console.log'. 

Please file a bug against the addons in question...

**Comment by Twinkletoes** [comment]
This would mean that every addon would need to do this and any addon in future could break testing. Better, surely that ember test could output just the tests to a file, meaning we weren't reliant on addons being perfect?

**Comment by Twinkletoes** [comment]
Plus, "logging errors only" would also break the xml formatted output.

**Comment by rwjblue** [comment]
As I mentioned in another issue, the test output from `ember test` is generated by [Testem](https://github.com/airportyh/testem). I am unsure if it has an option to write the output file to disk, if it does I'd gladly support it.

**Comment by jschilli** [comment]
@Twinkletoes @rwjblue  there is this xunit specific option: https://github.com/airportyh/testem/pull/384 for testem but to my knowledge there is currently no general way in testem to specify an output file

I won't share the very hacky way that I extract the xml output for consumption by jenkins

**Comment by Twinkletoes** [comment]
There doesn't appear to be any way to do that in testem. But I did find https://www.npmjs.com/package/intercept-stdout which would allow capture of testem output and then saving that to a file in *ember test*

**Comment by jschilli** [comment]
@Twinkletoes I agree that it's a PITA but going upstream on this one is the right answer for ember-cli - need to solve the output problem in testem.  will be easy then to solve in ember-cli

**Comment by Twinkletoes** [comment]
Unfortunately  airportyh/testem#384 isn't accepted yet... I just want to be productive - currently every time I upgrade ember-cli I get some nice stuff, but critical build process things fail. I'm spending about 10% of my dev time just coping with regressions.

**Comment by jschilli** [comment]
@Twinkletoes I feel you.  I'm just being realistic that although there is a roughly zero chance of every addon being quiet.  My approach is to assemble custom branches of upstream projects and lean on the PR process to get them fixed.

**Comment by Twinkletoes** [comment]
Exactly why I think the silent option should be deprecated and we should just chuck the testem stdout into a file

**Comment by Twinkletoes** [comment]
Because the silent option only means anything if every addon implements it perfectly

**Comment by rwjblue** [comment]
@Twinkletoes:

> I'm spending about 10% of my dev time just coping with regressions.

I'm sorry to hear that, we definitely need to make this easier! As I mentioned above, I'm absolutely open to supporting an output file option for testem when it supports it.  That should solve most of these issues I think.

To prevent future regressions within ember-cli itself (though it sounds like much of your pain is coming from addons), I'd suggest you add an acceptance test to ember-cli to confirm that the xml output is generated properly and ember-cli itself does not get in the way of the output.

**Comment by rwjblue** [comment]
Also, the last comments in https://github.com/airportyh/testem/pull/384 indicate that a PR adding this output file option for all reporters would be much more likely to be accepted.  That definitely seems like the best avenue forward on this issue...

**Comment by Twinkletoes** [comment]
Yes, I'm looking at that option

**Comment by Twinkletoes** [comment]
Looks like this is the one we need: https://github.com/airportyh/testem/pull/509

**Comment by jschilli** [comment]
Sweet!

**Comment by stefanpenner** [comment]
@KatieGengler I'm not entirely clear how practical this is, but add-ons using `ui` and not polluting `stdout` with `console.log` might be a good metric when rating them on emberobserver.com

**Comment by Twinkletoes** [comment]
With the testem PR above we wouldn't care what addons did on stdout - the test output would be guaranteed clean from the reporter

**Comment by stefanpenner** [comment]
> I just want to be productive - currently every time I upgrade ember-cli I get some nice stuff, but critical build process things fail. I'm spending about 10% of my dev time just coping with regressions.

Thats a bummer, the solution is to help catch the problems sooner. We plan to get into a steady release cadence, if you can try `master` in your app at some interval and report regressions, we can catch them sooner.

We do have a thorough test suite, but it can always be improved. If we tend to regress on some scenario that hits you hard, help us by adding regression tests to cover it.

**Comment by Twinkletoes** [comment]
On this one I'd say this is awaiting dependency fix with airportyh/testem#509

**Comment by stefanpenner** [comment]
@Twinkletoes thanks dude!

**Comment by rwjblue** [comment]
> With the testem PR above we wouldn't care what addons did on stdout - the test output would be guaranteed clean from the reporter

That is absolutely true, but we still want addons to use `ui` for logging.  It is a generally good and useful thing (regardless of the test output issue here).

**Comment by Twinkletoes** [comment]
Absolutely, but if we push test output sideways into a file then addons don't need to take account of the silent flag and can log what they need to stdout. 

The only reason we seem to need silent is in order to have parseable test output.

**Comment by rwjblue** [comment]
> The only reason we seem to need silent is in order to have parseable test output.

That is **your** only reason to care, not mine. :wink: 

> Absolutely, but if we push test output sideways into a file then addons don't need to take account of the silent flag and can log what they need to stdout.

Pushing the test output into a separate file (as we have both mentioned above) is absolutely the right move, but saying that addons should not honor the apps request for specific logging levels is definitely beyond the scope of ensuring test output is valid.

**Comment by Twinkletoes** [comment]
Hence the word *seems* in my post. What other reasons are there for silent?

**Comment by johanneswuerbach** [comment]
I just released 0.7.3 of testem, which includes this feature.

**Comment by stefanpenner** [comment]
as we bundle testem, we will need to cut a new release.

going forward, maybe we can stop bundling testem https://github.com/ember-cli/ember-cli/blob/master/package.json#L79

**Comment by johanneswuerbach** [comment]
I'll PR bump the testem version as soon https://github.com/airportyh/testem/pull/514 is green and released so we can ensure that the fix is distributed.

**Comment by stefanpenner** [comment]
testem stuff seems in.

**Comment by Twinkletoes** [comment]
My build server is now running tests and reporting results again :)

**Comment by stefanpenner** [comment]
> My build server is now running tests and reporting results again :)

:)P

**Comment by PratheepV** [comment]
Is there any way to set the log level while running tests.
