### ISSUE TITLE
Ember test ci does not escape xml correctly

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3467]
Double quotes in example below should have been escaped before being included in xml attribute.
 
```
<testcase name="PhantomJS 1.9 TestLoader Failures: insm-ui/tests/unit/mixins/ember-data-tree-view-node-controller-test: could not be loaded"><failure name="TestLoader Failures: insm-ui/tests/unit/mixins/ember-data-tree-view-node-controller-test: could not be loaded" message="Died on test #1     at http://localhost:7357/assets/test-support.js:2535
build	09-Mar-2015 10:52:35	    at http://localhost:7357/assets/test-support.js:5297
build	09-Mar-2015 10:52:35	    at http://localhost:7357/assets/test-loader.js:31
build	09-Mar-2015 10:52:35	    at http://localhost:7357/assets/test-loader.js:21
build	09-Mar-2015 10:52:35	    at http://localhost:7357/assets/test-loader.js:40
build	09-Mar-2015 10:52:35	    at http://localhost:7357/assets/test-support.js:5301: 'undefined' is not a function (evaluating 'ember_qunit.module("EmberDataTreeViewNodeControllerMixin")')"></failure></testcase>
```

**Comment by rwjblue** [comment]
Ember CLI is simply using testem for this reporting, any errors in this output would be upstream in testem itself.

**Comment by Twinkletoes** [comment]
Added a PR: https://github.com/airportyh/testem/pull/512

**Comment by rwjblue** [comment]
Awesome!

**Comment by Twinkletoes** [comment]
merged into testem:
https://github.com/airportyh/testem/commit/8602eaa49c2cb6876890ccd41e84efd7b80b9951

**Comment by stefanpenner** [comment]
@johanneswuerbach  let us know when this is in a released version!

**Comment by Twinkletoes** [comment]
Apparently (hopefully) tomorrow

**Comment by johanneswuerbach** [comment]
0.7.2 includes this fix.

**Comment by Twinkletoes** [comment]
Confirmed working on my build server. I think this issue can be closed.

**Comment by rwjblue** [comment]
:+1:

@Twinkletoes - Thanks for helping out here!

Also, not sure if you knew, but the GH interface allows the person that opens an issue to close it.

**Comment by Twinkletoes** [comment]
How? Looked for a Close button but couldn't find it

**Comment by rwjblue** [comment]
The button is just below the comment field:

![pic](http://monosnap.com/image/viPZKaALgjuUwkdpoUqzxEAaA7x3RV.png)

**Comment by Twinkletoes** [comment]
Aha! I was looking at the top around the issue management buttons.
