### ISSUE TITLE
Move template compiler to deps instead of devDeps when generating addon templates.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3471]
When inside an addon and we run `ember g component foo-bar` (which now creates the template in `addon/templates`) we should move `ember-cli-htmlbars` from the addon's `devDependencies` into `dependencies`.

Currently, running generator without moving the dep results in an informative build error, but we can just take care of moving the dep from within the generator.

Steps to reproduce the build error:

```
% ember addon super-awesome-addon
% cd super-awesome-addon
% ember generate component foo-bar
% ember build

An `addon/templates` tree was detected, but there are no template compilers registered for
`super-awesome-addon`. Please make sure your template precompiler (commonly
`ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in
`super-awesome-addon`'s `package.json`.
```

**Comment by stefanpenner** [comment]
seems to have gone stale
