### ISSUE TITLE
[0.2.0] Component blueprint imports layout module regardless of pod structure

### ISSUE THREAD

**Issue by mihai-scurtu** [ember-cli/ember-cli#3472]
Firstly, I have set ` "usePods": "true"` in my `.ember-cli` file.

If I use `ember generate component x-foo`, it correctly generates the files in `/app/pods/components/x-foo/`, but the component class tries to import the layout from the "pod-less" structure.

```javascript
// app/pods/components/x-foo

import Ember from 'ember';
import layout from '../templates/components/x-foo`;

export default Ember.Component.extend({
  layout: layout

  columns: {
    
  }
});
```

This, in turn, throws the error 
```
Uncaught Error: Could not find module `<project>/pods/components/templates/components/x-foo` imported from `<project>/pods/components/x-foo/component`
```

**Comment by mihai-scurtu** [comment]
A simple fix would be to change line 2 to `import layout from './template';` if a pod structure is detected.

**Comment by rwjblue** [comment]
So this is from within an addon then?  The non-addon version of the component blueprint should not be attempting to import the layout at all...

**Comment by mihai-scurtu** [comment]
I don't know how I should be linking files, so if I'm doing it wrong please let me know.

It's not from within an addon. If you look in https://github.com/ember-cli/ember-cli/blob/master/blueprints/component/files/__root__/__path__/__name__.js it should add the layout key, but judging from https://github.com/ember-cli/ember-cli/blob/master/blueprints/component/index.js it should correctly identify whether the project uses pod structure.

I feel like I'm missing something.

**Comment by jankrueger** [comment]
'locals' (https://github.com/ember-cli/ember-cli/blob/master/blueprints/component/index.js#L44) is called with `options.pod == false`

**Comment by trabus** [comment]
@jankrueger Let me look into this, I'll see if I can get you some info to guide how to fix.

**Comment by trabus** [comment]
@mihai-scurtu thanks for reporting this, you found a bug with `usePods`.
In the meantime, you can manually fix it with `import layout from './template'`, or remove the layout import entirely, as it's technically not needed (or preferred) inside a regular project. 

The layout import will be removed for in-project blueprints in a future release.
