### ISSUE TITLE
0.2.0 addon blueprint -- acceptance test startApp import path

### ISSUE THREAD

**Issue by Samsinite** [ember-cli/ember-cli#3474]
When generating an acceptance test using the acceptance test blueprint for an ember-cli addon named `xyz`, the blueprint generation output for the `startApp` `import` was:
```js
import startApp from 'xyz/tests/helpers/start-app'
```
instead of:
```js
import startApp from ''../helpers/start-app'

**Comment by abuiles** [comment]
@Samsinite this is intentional see https://github.com/ember-cli/ember-cli/pull/3353 at the end it will resolve to the same module.

**Comment by Samsinite** [comment]
Cool beans.  Are we interested in documenting this on the ember-cli.com
website for now so it helps others who run into the same issue? Or add a
comment to the file for now?

**Comment by stefanpenner** [comment]
@Samsinite maybe the site? Is the issue being unaware what the relative paths resolve to or...?

**Comment by Samsinite** [comment]
No, the issue was more so thinking that the generated code wasn’t wrong :p.
