### ISSUE TITLE
ember-cli v0.2.0: The package `ember-data` is not a properly formatted package

### ISSUE THREAD

**Issue by visualjeff** [ember-cli/ember-cli#3477]
Any idea why the following message shows up when using ember 0.2.0?  

The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/CoolThing/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).

I'm running ember-cli v0.2.0 within a docker container.  Its when I ran the docker container, created a new ember app then attempted to build it that I noticed this message.

**Comment by rwjblue** [comment]
The message explains what is wrong, the NPM package for ember-data is malformed (no entry point script).  It has been fixed upstream in https://github.com/emberjs/data/pull/2842, and the next version of ember-data will have this corrected.

**Comment by rwjblue** [comment]
Leaving this open so that we can close it when another version is published (and to help others find the open issue)...

**Comment by fishermand46** [comment]
I'm still getting this warning in ember-data 1.0.0-beta.16.

**Comment by wagenet** [comment]
@fishermand46 Are you sure you updated the package.json? or did you just update the bower.json? This warning comes from the addon installed via npm. I just tested now and beta.16 works fine for me (beta.15 gives the error).

**Comment by fishermand46** [comment]
I had just updated the bower.json. Works fine now. Thanks!
