### ISSUE TITLE
Library "app-name" is already registered with Ember. -- ember-cli-app-version Issue

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#3478]
I started seeing warnings like this in chrome when I do ember test --server

WARNING: Library "myapp" is already registered with Ember.

I did update to ember 1.11 around the same time so this could have complicated the issue. Just curious why I see this showing up.

thanks!

**Comment by rwjblue** [comment]
This is an issue upstream, and https://github.com/embersherpa/ember-cli-app-version/pull/14 should fix it.  For now you can remove ember-cli-app-version from your app...

**Comment by rwjblue** [comment]
Keeping open until we have an updated ember-cli-app-version (the pull request that updates can close this issue).

**Comment by toranb** [comment]
Thanks guys!
