### ISSUE TITLE
populateLegacyFiles invoked before addons are notified.

### ISSUE THREAD

**Issue by krisselden** [ember-cli/ember-cli#3479]
On the EmberApp populateLegacyFiles() is called before addons have a chance to modify vendorFiles.

**Comment by krisselden** [comment]
Instead, I think a better idea is to turn vendorFiles into a configuration like http://requirejs.org/docs/api.html#config-shim and have a broccoli step that builds shims, that way when we do the Packager abstraction we can just deal only with packaging loose modules.

**Comment by stefanpenner** [comment]
touring complete configuration something like how in ruby use have a nice DSL for routing ala `config.ru` would be great for describing these things.

We have some ideas, and will flesh this out once we get the issue triaging under control
