### ISSUE TITLE
0.2.0: npm test throws unhandled error

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#3480]
I'm seeing this for fresh apps and addons, likely an updated dependency since this wasn't happening last week.

```
$ npm test

> testaddon@0.0.0 test c:\Projects\GitHub\testaddon
> ember test

version: 0.2.0-beta.1
Built project successfully. Stored in "c:\Projects\GitHub\testaddon\tmp\class-te
sts_dist-guQcj4VZ.tmp".

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
npm ERR! Test failed.  See above for more details.
```

Steps to reproduce:

1) ```ember new testapp``` or ```ember addon testaddon```
2) cd into the new folder
3) ```npm test```

My environment:

Windows 7 Home
ember-cli: 0.2.0-beta.1
node: 0.12.0 (also tried on 0.10.33)
npm: 2.1.8

**Comment by rwjblue** [comment]
The "no such file or directory" error that testem throws is when it is attempting to spawn a child process to run the tests.

* Can you confirm that you have phantomjs installed?
* Did this work at some past ember-cli version for you, if yes which version?

**Comment by elwayman02** [comment]
@rwjblue this worked on 0.2.0-beta.1 last week.  Same version I have now, the only difference is that I've blown away all the packages and done a fresh install since last week.

**Comment by rwjblue** [comment]
@elwayman02 - Can you do the following: `npm install testem@0.7.0`?  I want to see if the error might be caused by 0.7.1 (I think that 0.7.0 is what shipped with the initial 0.2.0-beta.1).

**Comment by elwayman02** [comment]
@rwjblue moving to 0.7.0 did not alleviate the issue

**Comment by elwayman02** [comment]
@rwjblue I'm noticing a slightly different error on 0.7.0, however.

```
$ phantomjs --version
1.9.8

Axle@J-BOMB /c/Projects/GitHub/testme (master)
$ npm test

> testme@0.0.0 test c:\Projects\GitHub\testme
> ember test

version: 0.2.0-beta.1
Built project successfully. Stored in "c:\Projects\GitHub\testme\tmp\class-tests
_dist-K3e2bbwI.tmp".
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
npm ERR! Test failed.  See above for more details.
```

You'll note that I just checked the phantomjs version right before executing npm test, so I know it's installed and the PATH is correctly setup.

**Comment by rwjblue** [comment]
This definitely feels like a Testem issue, but we need to figure out how we can get better insight into what is happening, and what we can do to fix it....

**Comment by rwjblue** [comment]
@johanneswuerbach - Any ideas here?

**Comment by elwayman02** [comment]
I'm happy to help however I can, since this seems to be windows-specific.  Maybe @raytiley can try reproducing to confirm?

**Comment by johanneswuerbach** [comment]
@elwayman02 how did you install phantomjs? Manually or using chocolatey? If via chocolatey, which version of chocolatey did you use?

**Comment by stefanpenner** [comment]
this appears to  be an orphaned tester runner (phantomjs) in this case. https://github.com/airportyh/testem/issues/334 is tracking this.

**Comment by elwayman02** [comment]
@stefanpenner  I have applied the testem upgrade to my machine locally and still see this error occurring.

**Comment by stefanpenner** [comment]
> @stefanpenner I have applied the testem upgrade to my machine locally and still see this error occurring.

do you have a phantom phantomjs running?

**Comment by elwayman02** [comment]
No, I completely restarted my computer to be sure and it failed the first time running.  Again, testing on Windows 7 Home.

**Comment by stefanpenner** [comment]
how was phantomjs installed?

**Comment by stefanpenner** [comment]
@johanneswuerbach  any thoughts?

**Comment by elwayman02** [comment]
```npm install -g phantomjs@1.9.8```

**Comment by stefanpenner** [comment]
grumble grumble windows

**Comment by felixrieseberg** [comment]
Grumble indeed. I'll take a look next week, this seems fixable with enough determination (I'll be looking at some stack traces for hours :dancers:).

**Comment by stefanpenner** [comment]
@felixrieseberg  i'll likely be available to pair/discuss/bounce ideas off.  I haven't gotten this far down my triage list yet, but will get to it eventually if you don't have time.

ALso, so far the windows addon, has been very helpful for our windows users. I wonder if we should bundle it someway?

**Comment by felixrieseberg** [comment]
Oh yeah, I just wanted to make sure it runs well for a bunch of users before proposing ways to bundle it / reference it (somebody added Windows 7 support for instance, which is pretty cool). Let's chat next week? I'm basically happy to PR whatever you're comfortable with merging.

**Comment by stefanpenner** [comment]
> Let's chat next week? I'm basically happy to PR whatever you're comfortable with merging.

sounds good, wednesday or thursday work best.

**Comment by raytiley** [comment]
@elwayman02 If it is indeed failing to find phantomjs can you try installing phantomjs with (chocolatey) https://chocolatey.org/ 

Basically npm installs phantom in such a way that it tries to execute it via a bat file. This works fine from he shell, but bat files don't work from `spawn` (https://github.com/joyent/node/issues/23180)

If I use npm phantomjs I get an error, but everything works if I use the choclatey version of phantom. I had to do this a while back on ember-cli's windows CI.

Hope this helps.

-ray

**Comment by stefanpenner** [comment]
we need some way to detect this scenario and provide some useful feedback.

**Comment by rwjblue** [comment]
@stefanpenner - Agreed. We (ember-cli) are not attempting to spawn `phantomjs`, so the fix is almost certainly in testem itself (they seem very open to fixes/additions from us).

**Comment by stefanpenner** [comment]
@johanneswuerbach cc ^

**Comment by felixrieseberg** [comment]
Just to pile on - we (Microsoft) probably can't fix the underlying bat spawn issue easily, but I can certainly help out with better reporting (and maybe ps1 workarounds).

**Comment by johanneswuerbach** [comment]
Thanks @stefanpenner I created a testem issue for this https://github.com/airportyh/testem/issues/518, but need to find some time to get my expired Win VM renewed.

@rwjblue I did some testem maintenance (and became maintainer) while implementing htmlbars cross-browser testing and am an ember-cli user myself, so ember-cli fixes are definitely welcome.

**Comment by felixrieseberg** [comment]
Okay, I'll spin us up a Windows VM next week in Azure. I'll give y'all an account.

**Comment by smartlaksh** [comment]
I was getting the same exception

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

But when i ran the ember test --server it works and runs the test through PhantomJS.  But now i'm getting the same exception again when i'm running the npm test through my jenkins build script.

**Comment by elwayman02** [comment]
I am seeing the same behavior as @smartlaksh.  The tests run with ember test -server, but not with ember test/npm test

**Comment by ultimatemonty** [comment]
I'm seeing the issue with ember test --server
I recently went back to qunit after briefly trying mocha - not sure if that affects anything here

Windows 8.1 x64
Ember-CLI 0.2.0
PhantomJS 1.9.8
Node 0.10.37
NPM 1.4.28

Happy to provide some logs if someone can provide some instructions

**Comment by stefanpenner** [comment]
I think phantomjs installed via chocolaty works?

I also think after this week, I will move one of my days to just be windows improvements again.

**Comment by johanneswuerbach** [comment]
@stefanpenner yes, `npm install -g phantomjs` is generating a `bat` file, which testem can't spawn. I know how to fix this, but sadly had no time yet :cry:

**Comment by stefanpenner** [comment]
@johanneswuerbach is there an issue we can track?

**Comment by johanneswuerbach** [comment]
yep https://github.com/airportyh/testem/issues/518

**Comment by raytiley** [comment]
sorry I can't help push this forward more.... busy work time, hope to re-engage mid April.

**Comment by stefanpenner** [comment]
No worries @raytiley. Works takes priority :) that being said, I can't wait till you have more time again

**Comment by smartlaksh** [comment]
Thanks for your help @johanneswuerbach

**Comment by ultimatemonty** [comment]
thanks guys! :+1: :+1: :+1:
