### ISSUE TITLE
Why do you recommend relative instead absolute paths for modules?

### ISSUE THREAD

**Issue by nathanpalmer** [ember-cli/ember-cli#3482]
The ember-cli documentation recommends relative paths

> If you like you can reference a module by an absolute path, but keep in mind that using relative paths is considered best practice for accessing modules within the same package. To reference a module using an absolute path begin the path with the name defined in package.json:

I didn't see the reasoning behind it and in many scenario's the relative paths are much harder to follow. Here is an example

```javascript
import Ember from 'ember'
import CampaignStatus from '../../../../../mixins/campaign-status'
import CampaignsStat from '../../../../../mixins/campaigns-stat'
import SegmentsStat from '../../../../../mixins/segments-stat'
```

We're at the point of recommending that all of our paths are absolute because of this. Before stepping into that though I'd like to know if there was some deeper reasoning behind this recommendation that I'm missing.

**Comment by stefanpenner** [comment]
that should be re-phrased, to say you can use either relative or absolute. Use your own best judgement.

**Comment by nathanpalmer** [comment]
Docs were updated in #3513

**Comment by stefanpenner** [comment]
thanks!
