### ISSUE TITLE
Nested Addon's SourceMap Config Incorrect

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#3485]
A nested addon will not receive the proper source map configuration [here](https://github.com/ember-cli/ember-cli/blob/07bed6ff78553845a5c114001633d5c0c11214db/lib/models/addon.js#L131) in a nested addon because `this.app.options` will be `undefined` (since `this.app` is the parent addon and will not have `options` set on it).

This is just another situation where our configuration story kinda sucks right now.  Logging this here in case others run into it.  Hoping that the proposal that @lukemelia @raytiley and I discussed will solve this issue (along with many others).

**Comment by stefanpenner** [comment]
seems to have gone stale
