### ISSUE TITLE
0.2.0: Terminating ember test --server with Ctrl+C leaves cursor hidden

### ISSUE THREAD

**Issue by jcttrll** [ember-cli/ember-cli#3487]
Running `ember test --server` causes your cursor to be hidden, presumably just for visual appeal. If you terminate with Ctrl+C, your cursor will remain hidden when you are returned to your command prompt.

**Comment by stefanpenner** [comment]
@jcttrll which OS/node/npm versions?

**Comment by stefanpenner** [comment]
also, node is jank town. Can you instead use teste's  `q` to exit?

**Comment by stefanpenner** [comment]
I have confirmed this is an issue on the testem side, as it happens when testem is used independently of ember-cli and exited via `<ctrl>-c`

**Comment by maxwerr** [comment]
Noticed that as well. Also has the habit of leaving rogue phantomjs
processes in the background.

**Comment by stefanpenner** [comment]
https://github.com/airportyh/testem/issues/334

**Comment by stefanpenner** [comment]
I have opened an issue on testem: https://github.com/airportyh/testem/issues/513

I am closing this, as it isn't something we can fix on our side (I think)

**Comment by toranb** [comment]
@stefanpenner thanks for the followup /doing the research to figure out this was a core testem problem!
