### ISSUE TITLE
0.2.0: CLI commands in Win 7 throw unhandled ETIMEDOUT error

### ISSUE THREAD

**Issue by meharg** [ember-cli/ember-cli#3489]
I'm seeing this on any ember CLI command after upgrading from 0.2.0-beta.1 and Node 0.10 to CLI 0.2.0 and Node 0.12.0

`C:\Temp\ember>ember new my-app`
`version: 0.2.0`
`events.js:85`
      `throw er; // Unhandled 'error' event`
            `^`
`Error: connect ETIMEDOUT`
    `at exports._errnoException (util.js:746:11)`
    `at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)`

**My environment:**
Windows 7 Enterprise - behind firewall
ember-cli: 0.2.0
node: 0.12.0
npm: 2.5.1 
https-proxy = "http://companyproxy.com:80/"
proxy = "http://companyproxy.com:80/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

**Comment by stefanpenner** [comment]
@meharg strange, can you re-run with the env var `DEBUG` set to 'ember-cli*` and gist the output?

cc @raytiley, i have no idea how to do this on windows.

**Comment by meharg** [comment]
https://gist.github.com/meharg/c5eca3ce1d64ea8d51ee

**Comment by leoeuclids** [comment]
I was getting the same error, but after adding `"checkForUpdates" : false` to .ember-cli file, the error stopped.

@meharg can you confirm that this "fix" works?

**Comment by meharg** [comment]
Thanks @stefanpenner.  Found a work-around for this issue with this *.ember-cli* file in the home dir:
`{`
`  "checkForUpdates" : false`
`}`

**Comment by stefanpenner** [comment]
should be fixed by: https://github.com/ember-cli/ember-cli/pull/3488

**Comment by frankstallone** [comment]
OSX Yosemite - behind firewall
ember-cli: 0.2.0
node: 0.12.0
npm: 2.7.0

Same issue but setting checkForUpdates to false works.

**Comment by shturm** [comment]
version: 0.2.0
node: 0.10.32
npm: 2.7.0

Same issue but setting `checkForUpdates` to `false` works.

**Comment by rockinho** [comment]
Hey there! 

Where's the .ember-cli file located? 
I'm behind a corporate proxy, can this be the source of the error?

best regards

**Comment by leoeuclids** [comment]
@rockinho should be in your project's root folder, but if doesn't exist you can create it with this content
```javascript
{
  "checkForUpdates" : false
}
```

**Comment by rockinho** [comment]
Hey! Same Error.

>> ember new testapp

I created the folder testapp and put a  ".ember-cli" file and added the suggested lines..
this is the output: 

version: 0.2.0
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

Thanks again!

**Comment by leoeuclids** [comment]
@rockinho try to enter the folder you created, with the `.ember-cli` file inside, then run `ember init`

**Comment by rockinho** [comment]
Hey!  It works.

Thank you very much.

**Comment by stefanpenner** [comment]
@rockinho please try 0.2.1 as it fixes a similar error

**Comment by stefanpenner** [comment]
@rockinho please try 0.2.1 as it fixes a similar error

**Comment by leoeuclids** [comment]
@rockinho try @stefanpenner's suggestion, it should work

**Comment by rockinho** [comment]
@stefanpenner & @leoeuclids   

I installed the updated ember-cli and now after a bit googling it works:
But at first i had to set: 
>> npm config set registry http://registry.npmjs.org/ 
to get bower working.. 

i'm curious.

thanks!

**Comment by stefanpenner** [comment]
> i'm curious.

what are you curious about?

**Comment by leoeuclids** [comment]
@rockinho since you are behind a proxy, some issues may appear from time to time. 

To avoid most of them, configure the proxy environment variables and also git / npm / bower individually, with the files `.gitconfig` / `.npmrc` / `.bowerrc`. They can be inside your project's root folder (local) or your user folder (global)

My files look like this:
```javascript
//.gitconfig
[http]
  proxy = http://<proxy.ip>:<proxy.port>
[https]
  proxy = http://<proxy.ip>:<proxy.port>

//.npmrc
{
  proxy=http://<proxy.ip>:<proxy.port>
  https-proxy=http://<proxy.ip>:<proxy.port>
  strict-ssl=false
  registry=http://registry.npmjs.org/
}

//.bowerrc
{
  "proxy":"http://<proxy.ip>:<proxy.port>",
  "https-proxy":"http://<proxy.ip>:<proxy.port>"
}
```

More info on how to configure them
Git: http://git-scm.com/docs/git-config
Npm: https://docs.npmjs.com/files/npmrc
Bower: http://bower.io/docs/config/

With this setup you should be fine.
