### ISSUE TITLE
live reload improvements

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#349]
- [ ] share same port as web server
- [ ] fall back to polling for IE support (maybe using socket.io directly or indirectly)
- [ ] `--live=false` https://github.com/stefanpenner/ember-cli/issues/365

(cc @MajorBreakfast )

**Comment by MattNguyen** [comment]
You can also declare the live-reload port in the `.ember-cli` file:

```json
{
  "live-reload-port": 35729
}
```
