### ISSUE TITLE
Getting .less styles to work with addons

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#3490]
I believe it should be possible to have .less styles from either the addon/styles directory or app/styles directory to be copied into the consuming application, to bundle styles with the addon. I have been trying using ember-cli-less, and no styles ever end up in app.css or vendor.css. Not sure if another broccoli package needs to be used or what.

I believe the issue here is ember-cli-less. It wants me to have tests/dummy/app/styles/app.less, which is not where I want it to be doing anything. I want either addon/styles/addon.less or app/styles/app.less to work. Do I need a different package? Perhaps one of the broccoli less ones? My addon code is here: https://github.com/rwwagner90/ember-x-editable-addon

I would also like to make my addon depend on the bootstrap addon instead of including the bootstrap code myself. Is there a way to make an addon depend on an addon?

**Comment by jonathanKingston** [comment]
For dependencies in my addon I import them in with broccoli and my addons themselves I serve a file from `vendor/` that gives me three options in my app:
- Import from broccoli
- Import via another style tag
- Import with an @import pointing at `vendor/addon-name/name.less`

**Comment by rwwagner90** [comment]
The styles should work with less and scss though. No one is going to use .css anymore.

**Comment by jonathanKingston** [comment]
That was the only way I could get it working, I should have said :grinning:

Long term .css will have the flexibility of LESS and both will die. Tools like myth are something I want to mature more.

**Comment by rwwagner90** [comment]
Yeah, I don't know if it's possible with the current tools out there. I was looking at using broccoli-less-single and converting my less to css perhaps. Do you know if something like that might work?

**Comment by jonathanKingston** [comment]
@rwwagner90 I haven not had time to debug but my chosen implementation is:

addon style code in: addon-name/vendor/addon-name/styles/app.less

In my app.less:
```
@import "vendor/addon-name/styles/app.less";
```

It's not perfect as it makes a LESS coupling between both however it works for my use-case. I have however not had any time to check if this is still an issue of late.

**Comment by rwwagner90** [comment]
@jonathanKingston Is this inside your addon or the consuming application? I cannot even get app.less to export any styles outside of the addon. The only way I can do it, is convert to css, put in vendor folder, put it in index.js in included.

**Comment by rwjblue** [comment]
@rwwagner90:

>  I believe it should be possible to have .less styles from either the addon/styles directory or app/styles directory to be copied into the consuming application, to bundle styles with the addon.

`addon/styles` is absolutely something that we should support and will be processed by the addon's own preprocessors.

`app/styles` in an addon will be processed by the applications own preprocessors, and therefore cannot be guaranteed to work as you might expect.

> My addon code is here: https://github.com/rwwagner90/ember-x-editable-addon

I'll try to take a look in more detail later tonight/tomorrow.

> I would also like to make my addon depend on the bootstrap addon instead of including the bootstrap code myself. Is there a way to make an addon depend on an addon?

Yes, just add it to your addons dependencies in `package.json`. If it is setup properly, it should work just fine.

@jonathanKingston:

I would prefer to allow the `addon/styles/addon.less` be precompiled by the addon and not require the consuming app to also use `less`.  Obviously, in many cases this coupling is totally fine (especially when you are creating both the app and the addon and are able to force them to use the same preprocessors).

**Comment by jonathanKingston** [comment]
@rwwagner90 the include was inside my consuming app.

@rwjblue 100% agree, just explaining the shortest path that worked whilst I was rushing to get a product live. The styles directory I will be moving to the addon dir when the native support is there in ember-cli-less.

**Comment by rwwagner90** [comment]
@rwjblue I have tried using ember-cli-less with addon/styles/addon.less and app/styles/app.less both inside my addon. Neither of these seem to actually update dummy.css or vendor.css though. If I use addon/styles/addon.css, it works with the vanilla css and adds those styles to vendor.css. I would very much like to have it convert my less to css and concat it with vendor for me. I could even switch to scss instead of less potentially, but some preprocessor needs to work with addon styles.

**Comment by jonathanKingston** [comment]
@rwwagner90 the only way I got my dummy app working in the addon was using the same code in app.less there too.

So tests/dummy/app/styles/app.less has:
```
@import "vendor/addon-name/styles/app.less";
```

**Comment by notmessenger** [comment]
@jonathanKingston Can you point me to a code example of what you describe in https://github.com/ember-cli/ember-cli/issues/3490#issuecomment-78132502 ?

**Comment by notmessenger** [comment]
I have been able to compile LESS source files in an addon and have them imported into the app's *vendor.css* file via the code at https://github.com/softlayer/sl-ember-components/blob/v0.11.0/index.js#L38-L52 which I have also included here in case the reference branch gets removed.

```javascript

    /**
     * Adds LESS-generated CSS into vendor tree to be imported in included()
     *
     * @param {Object} tree
     * @returns {Object}
     */
    treeForVendor: function( tree ) {
        var appTreePath = 'app';
        var addonTreePath = path.join( this.nodeModulesPath, '../', 'app' );
        var appTree = new Funnel( this.isAddon() ? appTreePath : addonTreePath );

        var compiledLessTree = compileLess(
            appTree,
            'styles/' + this.name + '.less',
            this.getCssFileName()
        );

        return ( this.isAddon() ) ?
            mergeTrees([ tree, compiledLessTree ]) :
            compiledLessTree;
    },
```

**Comment by rwwagner90** [comment]
This is no longer an issue, that I know of. I have since switched to sass. Closing.
