### ISSUE TITLE
ember-cli 0.2.0 upgrading from 0.1.15 gives "Error: Cannot find module 'package.json'"

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#3491]
I followed the instructions for upgrading the ember-cli and it worked fine until I ran ```"ember install:npm ember-cli@0.2.0"``` but  I got an error saying ```Error: Cannot find module 'package.json'``` from running ```"ember install:npm ember-cli@0.2.0"```.

My environment is below.
```
$ ember -v
version: 0.2.0
node: 0.12.0
npm: 2.7.0
```
Any idea?

**Comment by stefanpenner** [comment]
please use `npm install ember-cli@0.2.0 --save-dev`

**Comment by vsymguysung** [comment]
First , the instruction that I was referring to is in the following url.
http://www.ember-cli.com/#project-update
 It seemed it needs to be revised.

After I followed your suggestion by running ```npm install ember-cli@0.2.0 --save-dev```, I got the same   error message when I was running the ```ember install``` command.
Even when I tried ```ember -v``` in the project folder, I got the same error but it's ok when I run ```ember -v``` outside of the project folder.

The details of the error message is below.
```
$ ember install
Cannot find module 'package.json'
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
Thanks in advance.

**Comment by stefanpenner** [comment]
@vsymguysung thanks for pointing that out, fixed: https://github.com/ember-cli/ember-cli/commit/c5ede49e5e9a001cd250f6bf5f59667591d8217b
