### ISSUE TITLE
updateChecker does not take into account dev builds with `v0.2.0-sha-checksum` 

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3494]
https://github.com/ember-cli/ember-cli/blob/master/lib/models/update-checker.js#L60

cc @twokul

**Comment by twokul** [comment]
will look into it

**Comment by xomaczar** [comment]
@twokul got some time need help?

**Comment by twokul** [comment]
![screen shot 2015-03-20 at 8 14 07 am](https://cloud.githubusercontent.com/assets/1131196/6754335/1d91ab08-ced9-11e4-97e1-1b4a836dcf78.png)

seems weird, let's seem what's happening
