### ISSUE TITLE
Unexpected Component/Template Inheritance?

### ISSUE THREAD

**Issue by jmurphyau** [ember-cli/ember-cli#3496]
I'm trying to work out if it's possible to subclass a component while also 'subclassing' its template (parent template calls {{yield}}, child template gets displayed within)

I've run into an issue where it doesn't always work as expected - from what I can tell it happens because when a component is resolved there are cases (all cases?) where it resolves the components template first (setting the template and/or layout properties?), then associates the component object as a second step. 

I've created a repo that gives an example of what I'm talking about:

https://github.com/jmurphyau/component-template-issue

[This commit](https://github.com/jmurphyau/component-template-issue/commit/c342c95528895a0537e5b350115ebbe1c55b236a) is the code I would expect to work and [this commit](https://github.com/jmurphyau/component-template-issue/commit/76f8d157e9a49fcecf3fe501e514f55d1494d574) is how I work around the behaviour. I previously worked around the behaviour by putting the components template in a different place all together - but v2.0.0 revealed a better way of doing it by renaming the template file.

**Comment by jmurphyau** [comment]
Below is a screenshot of the app output.

![screen shot 2015-03-11 at 12 25 40 pm](https://cloud.githubusercontent.com/assets/445432/6588726/cd0cd14e-c7e9-11e4-9dc5-ef1664998e0b.png)

**Comment by stefanpenner** [comment]
This doesn't seem like a bug. Although interesting stackoverflow is likely a better venue to ask these sorts of questions. Feel free to cross link with this issue.

**Comment by jmurphyau** [comment]
@stefanpenner is my assumption about order or resolution correct? 

If so, is there any technical reason the resolution couldn't first lookup component object then lookup a template? Is it just looking up template as preference because template existed before components maybe (taking a stab in the dark there)?

**Comment by jmurphyau** [comment]
scrap that thought - fragments/elements clearly make using the template file as a preference logical.
