### ISSUE TITLE
Config rewriting issue

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3498]
So I have come across a issue where the config meta tag gets rewritten to be a URL, I have fleshed this out in the broccoli-asset-rewrite issue below (And submit a pull request).

I get the feeling this will likely be rejected as it isn't really part of the core intent of the library:
https://github.com/rickharrison/broccoli-asset-rewrite/issues/13

I think there are two other options:
- Change the compilation order to make the meta tag run after broccoli-asset-rev.
- Fork broccoli-asset-rev to be ember-cli specific

**Comment by stefanpenner** [comment]
this is fixed upstream

**Comment by jonathanKingston** [comment]
:+1: sorry was aiming to do a spring clean of my issues this weekend. Thanks
