### ISSUE TITLE
Getting qunit's stack trace to use sourcemaps

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#3499]
I realize this is beyond the scope of ember-cli but I thought this would be a good place to start the conversation. It would be very nice if we could coerce QUnit's stack traces to give the file path + line number from the source maps rather than from vendor.js or app.js

Any thoughts on if this is possible? /cc @ef4

**Comment by ef4** [comment]
I have a partial solution to this problem in my mocha reporter (
https://github.com/ef4/better-mocha-html-reporter).

It puts a link next to each stack trace that dumps it to the console on
demamd. The console automatically sourcemaps it.

To sourcemap them directly in the page you'd need to implement the whole
lookup process. The browser doesn't expose that capability.

**Comment by stefanpenner** [comment]
would be cool, but out-of-scope for now. Feel free to continue the conversation though.

**Comment by cs3b** [comment]
Just got in to this ticket when doing research (I will leave here a link that might help in implementing this)

https://github.com/novocaine/sourcemapped-stacktrace

**Comment by stefanpenner** [comment]
@cs3b i would recommend continuing discussion on the QUnit repo

**Comment by stephanebruckert** [comment]
I'm using https://github.com/san650/ember-qunit-source-map and it helps a lot
