### ISSUE TITLE
Ability to specify additional node modules to install within the .ember-cli config

### ISSUE THREAD

**Issue by davidrhyswhite** [ember-cli/ember-cli#3502]
From personal experience just thought it would be a nice feature to have to specify some additional node modules for installation when creating a new app. Specifically I tend to always run `ember install:npm broccoli-sass`, after installing a new application.

```
{
  ...,
  "nodeModules": [{
    "broccoli-sass"
  }]
}
```

It could probably be extended to work with Bower components too, as there are certainly a few I install more often than not on a project.

**Comment by stefanpenner** [comment]
Blueprints are the way to do this. You can even pass a url to a foreign blueprint. This gives you full customizability
