### ISSUE TITLE
Anonymous functions being transpiled to named functions in 0.2.0

### ISSUE THREAD

**Issue by pmdarrow** [ember-cli/ember-cli#3503]
Something in the build pipeline (babel?) is rewriting anonymous functions as named functions in Ember-CLI 0.2.0 and giving me an error in one of my tests. Example:

```js
import myFunc from './my-func';

function test() {
  var myObj = {
    myFunc: function() {return true;} // anonymous function
  };
  myFunc();
}
```
is transpiled to:
```js
...

function test() {
  var myObj = {
    myFunc: function myFunc() {return true;} // named function
  };
  myFunc(); // "myFunc is not defined"
}
```

I fixed the issue by using an arrow function for the anonymous function, but I wanted to know if this is expected behaviour and why my anonymous function is being transpiled to a named one?

**Comment by rwjblue** [comment]
It is being done by babel during transpilation (see [example](https://babeljs.io/repl/#?experimental=false&playground=false&evaluate=false&loose=false&spec=false&code=var%20blah%20%3D%20%7B%0A%20%20someCoolThing%3A%20function()%20%7B%20return%20'blah'%3B%20%7D%0A%7D). Giving the function a name should not affect your codes functionality, and makes debugging much easier.

Does this pose a problem with your application or was this more of a curiosity thing?  If it does pose a problem, can you provide an example where this auto-naming breaks your code?

I am going to close this, as I do not think it is an issue in general (once you know when it is happening), and if it is it will need to be fixed in babel and ember-cli-babel.

**Comment by pmdarrow** [comment]
It actually did pose a problem in one of our tests, here's a concrete example:

```js
// foo.js
export function foo(obj) {
  return obj.foo();
}

```js
// foo-test.js
import foo from './foo';
import { module, test } from 'qunit';

module('foo-test');

test('it returns the result of the object's foo method',
    function(assert) {
  var obj = {
    foo: function() {return true;}
  };
  assert.ok(foo(obj));
});
```
Running the above results in `foo is not defined`. I realize this might look a bit contrived, but we have a scenario like this in our test suite. I'm ok with this behaviour, it's just nice to know now it's intentional.

**Comment by stefanpenner** [comment]
this looks fixed on the latest babel: http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=true&spec=false&code=%2F%2F%20foo-test.js%0Afunction%20foo()%20%7B%0A%20%20return%201%3B%0A%7D%3B%0A%0Avar%20bar%20%3D%20%7B%0A%20%20foo%3A%20function()%20%7B%20return%20foo()%3B%20%7D%0A%7D%3B%0A%0Aconsole.log(bar.foo())%3B%0A

what version are you using?

**Comment by stefanpenner** [comment]
just confirmed, latest babel in ember-cli works as expected:

![screen shot 2015-03-11 at 9 12 13 am](https://cloud.githubusercontent.com/assets/1377/6600766/bc310d4c-c7ce-11e4-926c-a48c21ef3304.png)

![screen shot 2015-03-11 at 9 11 37 am](https://cloud.githubusercontent.com/assets/1377/6600758/b134d6c6-c7ce-11e4-81ac-477c4686ea52.png)

**Comment by pmdarrow** [comment]
I'm using `ember-cli-babel` which somewhere down the dependency tree depends on babel-core@4.7.8. What version of babel do you have installed?

**Comment by stefanpenner** [comment]
```
± % npm ls | grep babel-core                                                                                                                                                                                                                                                                                                                                                                                                       !3517
│ │ ├─┬ babel-core@4.7.4
```

**Comment by stefanpenner** [comment]
let me purge NPM and see what happens

**Comment by stefanpenner** [comment]
babel repl agree's with you.
opening an issue

**Comment by stefanpenner** [comment]
> // foo.js
> export function foo(obj) {
>   return obj.foo();
> }

should be `export default function foo() { }`

**Comment by pmdarrow** [comment]
Sorry, I built the contrived example from a piece of our test code and forgot that when copying it. Should still exhibit the same issue.

**Comment by stefanpenner** [comment]
@pmdarrow please provide an example that demonstrates the issue.

1. pre-transpiled code example
2. expected console.log output
3. actual console.log output

**Comment by pmdarrow** [comment]
@stefanpenner would you like a small example repo demonstrating the issue instead?

**Comment by stefanpenner** [comment]
> @stefanpenner would you like a small example repo demonstrating the issue instead?

sure

**Comment by pmdarrow** [comment]
See https://github.com/pmdarrow/ember-cli-issue-3503, specifically `tests/helpers/foo-test.js`. You'll see `ReferenceError: foo is not defined` when you run the tests.

**Comment by stefanpenner** [comment]
Alright, so this isn't a babel bug, babel appears to work correctly. Rather a bug in esperanto.

```js
    var obj = {
      foo: function foo() { // function foo, is only available in this context, it does not leak out.
        return true;
      }
    };

    assert.ok(foo(obj)); // this is a bug in esperanto
```

demonstrating that function is scoped as we expected:
```js
function bar() {
  return 1;
}

console.log(bar());
var a = {
  bar: function bar() {
    return 2;
  }
};

console.log(bar());
```

**Comment by stefanpenner** [comment]
opened an issue on esperanto: https://github.com/esperantojs/esperanto/issues/122

**Comment by stefanpenner** [comment]
master no longer uses esperanto.
