### ISSUE TITLE
Updating to latest fails

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#3504]
I'm getting:

```The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/waynedouglas/sonatribe-ui/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The package `torii` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/waynedouglas/sonatribe-ui/node_modules/torii`. This is generally caused by an addon not having a `main` entry point (or `index.js`).```

Here is my package.json:

```
{
  "name": "sonatribe-ui",
  "version": "0.0.0",
  "description": "Small description for sonatribe-ui goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "^0.2.0",
    "ember-cli-app-version": "^0.3.2",
    "ember-cli-babel": "^4.1.0",
    "ember-cli-dates": "1.1.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "^0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "^0.3.9",
    "ember-cli-sass": "^3.1.0-beta",
    "ember-cli-simple-auth": "~0.7.2",
    "ember-cli-simple-auth-oauth2": "~0.7.2",
    "ember-cli-simple-auth-torii": "~0.7.2",
    "ember-data": "^1.0.0-beta.15",
    "ember-export-application-global": "^1.0.0",
    "ember-idx-forms": "^0.5.1",
    "ember-idx-modal": "~0.1.2",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "node-sass": "^2.0.0-beta",
    "torii": "~0.2.2"
  },
  "dependencies": {
    "moment": "^2.9.0"
  }
}

```

and here is my Bower.json

```
{
  "name": "sonatribe-ui",
  "dependencies": {
    "jquery": "^1.11.1",
    "ember": "1.10.0",
    "ember-data": "1.0.0-beta.15",
    "ember-resolver": "~0.1.12",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "ember-simple-auth": "0.7.2",
    "bootstrap": "~3.3",
    "ember-addons.bs_for_ember": "~0.7.0",
    "font-awesome": "~4.3.0",
    "cloudinary_js": "~1.0.22",
    "jquery-file-upload": "~9.9.3",
    "jquery-ui": "~1.11.3",
    "ember-cli-moment-shim": "~0.0.3"
  },
  "devDependencies": {
    "ember-addons.bs_for_ember": "~0.7.0",
    "bootstrap": "~3.3.1",
    "lodash": "~2.4.1"
  },
  "resolutions": {
    "ember": "1.10.0",
    "ember-data": "1.0.0-beta.15",
    "ember-cli-test-loader": "0.1.3"
  }
}
```

**Comment by stefanpenner** [comment]
those are bugs in those dependencies, not in ember-cli. We will try to keep compatibility for them until 0.3.

**Comment by wayne-o** [comment]
waynes-MacBook-Pro:sonatribe-ui waynedouglas$ ember server
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/waynedouglas/sonatribe-ui/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The package `torii` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/waynedouglas/sonatribe-ui/node_modules/torii`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Cannot call method 'writeLine' of undefined
TypeError: Cannot call method 'writeLine' of undefined
    at AddonDiscovery.<anonymous> (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon-discovery.js:109:22)
    at Array.map (native)
    at AddonDiscovery.discoverFromDependencies (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon-discovery.js:94:68)
    at AddonDiscovery.discoverChildAddons (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon-discovery.js:61:31)
    at Class.Addon.discoverAddons (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon.js:172:40)
    at Class.Addon.initializeAddons (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon.js:188:8)
    at setupRegistryForEachAddon (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/preprocessors.js:46:3)
    at Class.Addon (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/lib/models/addon.js:83:5)
    at new Class (/Users/waynedouglas/sonatribe-ui/node_modules/ember-cli/node_modules/core-object/core-object.js:16:17)

**Comment by wayne-o** [comment]
FTR both ember-data and torii have these in package.json 

ember-data:

  "ember-addon": {
    "main": "lib/ember-addon/index.js"
  },

torii:

  "ember-addon": {
    "main": "lib/ember-addon/index.js"
  },

**Comment by wayne-o** [comment]
Surely ember-data - latest should be compatible no?

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/2842

**Comment by wayne-o** [comment]
Is that what is causing the ```Cannot call method 'writeLine' of undefined``` though? or am I getting mixed up?

**Comment by stefanpenner** [comment]
sorry to be rude, but searching https://github.com/ember-cli/ember-cli/search?q=writeLine+of+undefined&type=Issues&utf8=%E2%9C%93

reveals: https://github.com/ember-cli/ember-cli/issues/3468
and https://github.com/ember-cli/ember-cli/pull/3483
and 
> @adamsrog - It has landed, and you can use master (or the specific sha) for now. I suspect we will ship 0.2.1 after a few more bugs are straightened out (but within a couple days).

**Comment by adamsrog** [comment]
Can confirm that this solution worked for me.

@wayne-o follow these instructions: https://github.com/ember-cli/ember-cli#working-with-master
