### ISSUE TITLE
Locally npm installed addon not watched in consuming application

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#3506]
I have an addon locally, for common code between multiple apps, and I need it to be watched by each of the multiple consuming apps for changes. I've talked briefly with @rwjblue about it, and I created a repo to show that it doesn't currently work: https://github.com/rwwagner90/ember-addon-update-test

**Comment by floriankrb** [comment]
If I understand well, you are expecting the following : 
 run "ember server" in your test-app folder
 change a file in your addon (test-addon/addon/components/test-stuff.js)
 don't tell the app that the addon changed
 but the ember server should trigger  and reinstalling the addon and restart the server
Is it the expected behaviour ?
I would love to have this too.

**Comment by rwwagner90** [comment]
It shouldn't even need to reinstall, ideally, just watch the addon files too. In-repo-addons are supposed to do this, I think, but then it's in the repo and not common code. I'd be fine not using an addon too, just need a common folder of ember components and everything outside of my apps, to be used in multiple apps.

**Comment by rwwagner90** [comment]
@rwjblue did you get a chance to look at the repo I put up? Can you confirm that it does not work and I didn't just do something wrong?

**Comment by rwjblue** [comment]
@rwwagner90 - I lost track.  Will try to repro locally today...

**Comment by rwwagner90** [comment]
Thanks @rwjblue. I really appreciate it!

**Comment by rwwagner90** [comment]
Was anyone able to use the repo I created to reproduce the issue and look at it?

**Comment by janmisek** [comment]
+1

**Comment by janmisek** [comment]
Hello @rwwagner90 

I just ran into same problem and I can confirm that in-repo-addons are not watched. Solution is not use in-repo-addons, but standard addons with `npm link`. By the way I did started with in-repo-addons but current npm link solution looks to me much more clean preserving all features of in-repo ones.

To create "in repo addon" with npm link addod do the following:
 
1.Create an addon somewhere `ember addon utils`
2. `cd utils && sudo npm link` will create global module `utils`
3. go to app dir and run `npm link utils` to create symlink in `node_modules` of the app
4. add `"utils" : "0.0.0"` to package.json of the app 

Then there is addon which is watched, could be modified without `npm install` and does not need to be in remote repository. If you want the addon to be part of the application git repository - just copy addon somewhere inside repo, delete addon's `.git` dir `add` and `commit` the app.   


By the way, documentation regarding the in-repo-addons on official ember-cli page is little bit misleading. I would suggest to replace in-repo-addons with npm link solution as it provides same functionality, better documentation and support in ember-cli code.

**Comment by visualjeff** [comment]
$ ember new goofy

$ cd goofy/

$ npm link ember-cli-pretender
/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli-pretender -> /usr/local/lib/node_modules/ember-cli-pretender -> /home/jeffg/WebstormProjects/ember-cli-pretender

$ vim package.json and add ember-cli-pretender: "*" to dev dependencies.
 
$ ember b
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
__Build failed.__
Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
Error: Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
    at Object.multiGlob (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:339:13)

No worky...

**Comment by visualjeff** [comment]
Same thing but with my own local addon for e164 internation phone formats:

$ ember new goofy

$ cd goofy/

$ npm link ember-cli-e164-phones-countries
/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli-e164-phones-countries -> /usr/local/lib/node_modules/ember-cli-e164-phones-countries -> /home/jeffg/WebstormProjects/ember-cli-e164-phones-countries

$ edit package.json and add ember-cli-e164-phones-countries: "1.0.3" to dev dependencies.

$ ember build
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
__Build failed.__
Path or pattern "bower_components/ember-cli-e164-phones-countries/dist/e164-phones-countries.min.js" did not match any files
Error: Path or pattern "bower_components/ember-cli-e164-phones-countries/dist/e164-phones-countries.min.js" did not match any files
    at Object.multiGlob (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/jeffg/WebstormProjects/goofy/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:339:13)

**Comment by rwwagner90** [comment]
@rwjblue should normal addons be watched? If they should not be, then perhaps the npm link solution that @janmisek suggested would work? I have yet to try it out, but will tinker with it this weekend.

**Comment by stefanpenner** [comment]
> @rwjblue should normal addons be watched? I

not by default.

**Comment by stefanpenner** [comment]
> If they should not be, then perhaps the npm link solution that @janmisek suggested would work?

im unsure if npm link will work by default, it depends on if the watcher you chooses recurses symlinks and if that addon is marked for development

**Comment by rwwagner90** [comment]
@stefanpenner well the ```isDevelopingAddon``` flag didn't do anything for me. What watcher should I be using?

**Comment by stefanpenner** [comment]
> @stefanpenner well the isDevelopingAddon flag didn't do anything for me. What watcher should I be using?

unknown, I have not run into the issue you describe so I am un-aware. Merely provide ideas for your debugging.

**Comment by janmisek** [comment]
@stefanpenner is right without special tweaking npm linked module will not be watched. To have npm linked addon watched add following extra code to yout  Brocfile:

```
// Custom inherited EmberApp to include own compilations
var MyApp = function () {
    return MyApp.super_.apply(this, arguments);
};
util.inherits(PhoneApp, EmberApp);

MyApp.prototype.watchExtraDir = function(watchedDir) {
    // watch input tree, but filter to empty output tree, suppose  there is not 'null' dir in sources
    return funnel(path.join(__dirname, watchedDir), {srcDir: 'null'});
};

// overriden to include custom compilations/watching trees
MyApp.prototype.toArray = function () {
    var trees = EmberApp.prototype.toArray.apply(this, arguments);

    // extra watchers
    trees.push(this.watchExtraDir('/node_modules/ember-utils/addon'));
    trees.push(this.watchExtraDir('/node_modules/ember-dabl/addon'));

    // ... additional compiled trees
   
    return trees;
};

**Comment by stefanpenner** [comment]
This seems pretty fishy.

**Comment by janmisek** [comment]
> This seems pretty fishy.

 At least ```{srcDir: 'null'}``` is fishy :) But currently this is best solution I was able to came up to share code between apps and addons during active development. In-repo addons did not work for me at all because they are not intended for code sharing. On the other hand addons linked by npm ( as described in docs) works perfectly for my needs, only missing feature was watching.

In-repo addos as documented did not worked for me, because they are not intended for sharing code among apps/addons. Also there is little documentation on topic.

So even it's fishy I shared the solution.

**Comment by stefanpenner** [comment]
> So even it's fishy I shared the solution.

Ya, I meant the problem is fishy not the work around. Although it is unfortunate that the work-around is needed.

**Comment by janmisek** [comment]
@visualjeff Looks like you are missing some bower dependencies

**Comment by stefanpenner** [comment]
we plan to support this more closely post broccoli 1.0, as it will remove `tmp` from the project reducing much of the file watching overhead.
