### ISSUE TITLE
running test for component with layoutName fails

### ISSUE THREAD

**Issue by spruce** [ember-cli/ember-cli#3510]
Hey,
I'm using ember-cli together with https://github.com/indexiatech/ember-forms
When having a component of my project which uses this addon I always get an error when executing the tests for my project which currently only try to render the component which fails with:
```
Assertion Failed: You specified the layoutName components/em-form-group for <(subclass of Ember.Component):ember440>, but it did not exist.
```

What can be done to fix this? I don't know what should be changed.

We didn't find a solution on the other repo that's why I'm asking here. (Issue: https://github.com/indexiatech/ember-forms/issues/87)

Thanks for the great work.

**Comment by neaket** [comment]
+1 I ran into this issue before.  Be nice to know the proper fix or cause.

I fell back to the default layout name for my component.  I think if you remove the layoutName property from ember/forms/addon/group.js it would work.

**Comment by stefanpenner** [comment]
layoutName i deprecated

**Comment by wagenet** [comment]
@stefanpenner this is not deprecated.

However, the correct fix here is to specify the template name in your needs:

```
needs: ['template:components/em-form-group']
```

**Comment by johnnyshields** [comment]
@wagenet thank you.
@stefanpenner did you mean to say "layoutName is deprecated but use templateName instead?"

**Comment by he9qi** [comment]
@wagenet +1  thank you!
