### ISSUE TITLE
ZenHub: Issue Management Boards

### ISSUE THREAD

**Issue by karelvuong** [ember-cli/ember-cli#3521]
Hey guys,

**So this isn't an issue.** This is to inform `ember-cli` contributors of the existence (if you are not already aware) of a tool called [ZenHub](https://www.zenhub.io/) to help you all better manage and triage the project's issues and pull requests.

![hero-boardview](https://cloud.githubusercontent.com/assets/2213571/6631025/1fc6f588-c8dd-11e4-81e6-534a6d934671.png)

It's a project management tool that is fully integrated in GitHub and allows you to manage issues and pull requests in a Kanban fashion. If you're familiar with **Trello or JIRA Agile**, it behaves similarly.

**If you're already put off by this advertisement-like post (it's not, I promise), I've added a couple use cases below where this tool could be of assistance to the `Ember.js` community. Or to `ember-cli` at the very least.**

# Features

**Issues or pull requests can be dragged and dropped into their appropriate bucket** or 'pipeline' depending on how you guys set up the workflow.

Like the issues and pull requests tab, ZenHub has all the functionality of **filtering for specific labels, milestones, and assignees**. The value that is added with ZenHub is that management is now a bit more visual with the power of additional categories via pipelines.

Clicking onto the issue 'card' in a pipeline will link you directly to the issue page you are familiar with.

There is the concept of **+1-ing** a comment. This helps you focus on the discussion instead of cluttering issues with agreement (:+1:).

![feature-plusone](https://cloud.githubusercontent.com/assets/2213571/6631472/15dbda96-c8e4-11e4-94a1-2d44dd457bc8.jpg)

There will be times when you want to **switch back to the traditional issue list** and this can be easily done via the sidebar:

![sidebar](https://cloud.githubusercontent.com/assets/2213571/6631391/9acd955c-c8e2-11e4-915f-a25cd7431bb5.png)

It is completely **free for public and open-source** repositories (https://www.zenhub.io/pricing):
> Public or open-source repositories only? ZenHub will always be free for you.

**Getting setup is as easy as:**

1. Installing the Zenhub chrome extension
2. Authenticating with your GitHub account
3. You're done and you can use ZenHub across all of your projects.

There's **no risk** of losing your issues or current functionality. Everything stays the same with the addition of a single button to your repository sidebar.

![single-addition](https://cloud.githubusercontent.com/assets/2213571/6631647/9b4993b0-c8e6-11e4-80af-76f6a82aefff.png)

# Applying this to ember-cli

## The Board

This is how ember-cli's 'board' currently looks like. This is the default setup, but it can be configured to your liking:

![ember-cli-board](https://cloud.githubusercontent.com/assets/2213571/6631280/89d6138e-c8e0-11e4-9a80-ebefea07ff98.png)

Here it is filtering for issues and pull requests related to `milestone v0.3.0`:

![ember-cli-board-milestone](https://cloud.githubusercontent.com/assets/2213571/6631269/65e3298a-c8e0-11e4-9ed7-426a219b3fa4.png)

And finally, here it is filtering for issues with the `bug` and `blocking` labels:

![ember-cli-board-labels](https://cloud.githubusercontent.com/assets/2213571/6631322/0595b326-c8e1-11e4-9640-b0a42b13a65c.png)

The current board is a bit heavy on the sides (New Issues and Closed) as it hasn't been set up for `ember-cli`. Any modifications made to issues or pull requests and which pipeline they are located in are real-time and affect all users who have the ZenHub chrome extension.

## Use Cases

* While labels or tags are nice, they're not as visual as having an entire column dedicated to them. Pipelines help inform everyone of an issue's state at a single glance without needing to filter them.
* Instead of the `in progress`, `needs investigation`, or other state-related label, why not place them into columns/pipelines and make labels indicate the issue or pull request's type. Type is almost always static, but state is variable. This way, you can easily move issues or pull requests across the board's columns as they are investigated, worked on, reviewed, and finally closed.

This is already a pretty lengthy, so I'll end it here. If you want more information, feel free to comment below! Otherwise, just try it out - there's no harm in it! 

--

### Thanks for reading! I hope this tool can prove useful for the Ember.js community. :smile: 

--

**Note:** I have no affiliation with ZenHub in any way and am merely a fan.

**Comment by elwayman02** [comment]
Seems useful.  Issue triage on GitHub is kinda difficult for large projects.

**Comment by knownasilya** [comment]
:+1: better then https://huboard.com

**Comment by stefanpenner** [comment]
I plan to evaluate this, I just haven't had a chance yet.

**Comment by stefanpenner** [comment]
apparently to busy to try this out :(
