### ISSUE TITLE
Blueprint#addPackagesToProject fails when npm install spawns a child process.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#3523]
I have a NPM package called `screenshot-server` that I add via `addPackagesToProject`:
[ember-cli-qunit-screenshot](https://github.com/nathanhammond/ember-cli-qunit-screenshot/blob/master/blueprints/ember-cli-qunit-screenshot/index.js)

It has a dependency of `selenium-webdriver` which spins up a child process during its install, at which point the bower package proceeds to install, succeed, and then the overall process seems to exit before allowing the child process of `npm install` to complete its tasks.

I've seen it work once because of a Bower configuration issue which left it open and waiting for input, during which the `screenshot-server` package finished installing.

### Reproduction:

```
ember new addPackagesToProjectFail
cd addPackagesToProjectFail
ember install:addon ember-cli-qunit-screenshot
```

(Note: it fails in odd ways because of the inherent race condition.)

**Comment by rwjblue** [comment]
Is this an issue or no? So confused.... :wink:

**Comment by nathanhammond** [comment]
I can't get it to fail in a minimized test case with ember-cli#master. The best I've got is "maybe," but I can neither confirm nor deny. Closed for now unless it shows up again.
