### ISSUE TITLE
Proxy not working in 0.2.0

### ISSUE THREAD

**Issue by AndyPyeSC** [ember-cli/ember-cli#3525]
I've upgraded to CLI 0.2.0 and am running the following command:

ember serve --proxy=https://our-backend

All requests are still going to localhost:4200 though. The only reasons I've found for this have been for old versions of CLI (0.0.xx) but from what I can tell the way proxying is set up has changed since then.

**Comment by jonathanKingston** [comment]
Related/solution: https://github.com/ember-cli/ember-cli/issues/3293

**Comment by AndyPyeSC** [comment]
Thanks Jonathan. I've found this morning that proxying _is_ actually working - it's the 3rd-party backend we're communicating with that isn't.
