### ISSUE TITLE
Test regression in 0.2.0

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3530]
I have a component that yields if a security check passes, thus hiding content the user is not allowed to see.  Tests passed in 0.1.10, but fail in 0.2.0 with 

*Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.*

In the below code I tried changing Handlebars to HTMLBars but get same error.

Is this the right way to test if a yield happened correctly? Is there a simpler/easier/more correct way to do it? Or have I found a regression?

```
test('shows content when may do activity', function (assert) {
  assert.expect(1);

  // creates the component instance
  var component = this.subject({
    securityService: createMockSecurityService(true),
    template: Ember.Handlebars.compile('<div id="if-may-test-div" />')
  });

  // appends the component to the page
  var $component = this.append();

  assert.equal($component.find('div#if-may-test-div').length, 1);
});
```

**Comment by stefanpenner** [comment]
which version of ember are you using?

Also, i would suggest using @ef4's new test helper for these things: https://github.com/switchfly/ember-test-helpers/pull/21/files as it hides away all the raw "compile" details.

**Comment by Twinkletoes** [comment]
Using whatever ember-cli 0.2.0 uses...er...looking... 1.10.0

**Comment by rwjblue** [comment]
@stefanpenner - That is not exposed yet via ember-quint or ember-mocha. We are working on the specific API's for each still.

**Comment by stefanpenner** [comment]
> Using whatever ember-cli 0.2.0 uses...er...looking... 1.10.0

sorry, these can diverge if the user chooses. (just trying to get all the facts before someone digs in)

**Comment by rwjblue** [comment]
We do not ship with the template compiler in any environment. If you want to be able to compile templates at runtime, you will have to 'app.inport' the template compiler.

**Comment by Twinkletoes** [comment]
test helper looks interesting but can't see how to use it - are there any examples you know of? The readme doesn't give much detail

**Comment by rwjblue** [comment]
It was a fairly important change, and I should have realized it and called it out in the changelog. 

I'll add that to the changelog/release notes for 0.2.0 shortly.

**Comment by rwjblue** [comment]
In the end, I believe this is essentially a dupe of https://github.com/ember-cli/ember-cli/issues/3497

**Comment by stefanpenner** [comment]
@rwjblue when we do include the compiler (for that helper) we should be sure it is private, and not re-exposed for users to cause false-positives as it did in the past.

@Twinkletoes sorry for the pain here, we made the call to remove the compiler by default. Because it is something we don't want people to use by accident in-production. Apparently we forgot to add it to the change-log. Thanks for catching this!

**Comment by Twinkletoes** [comment]
so it used to be included and now it's not, so the fix is to add the following in Brocfile.js?

```
app.import('ember-template-compiler.js');
```

I would only want to do this when testing and not in production - what's the best way to do that?

**Comment by Twinkletoes** [comment]
Alternatively is there a better way to do that test without needing the compiler?

**Comment by rwjblue** [comment]
@stefanpenner - I actually intend to keep even the inline templates compiled in node-land. So that I don't accidentally deploy a broken prod build again :wink:

@twinkletoes - yes roughly that, but the path to the compiler is likely 'bower_components/ember/ember-template-compiler.js'. And you can wrap it in an "if (app.env === 'test')" so that it is only run in test env.

**Comment by stefanpenner** [comment]
@rwjblue interesting, although it would prevent people from doing an import or generating templates via js

**Comment by Twinkletoes** [comment]
Yay! That's another 6 tests fixed - Down from 250 tests that broke in 0.2.0 to just 70 :)

**Comment by stefanpenner** [comment]
@Twinkletoes hopefully the above helper, when it lands will help ensure future smooth sailing. As you discover various brittle points, report back. I want to make sure we have a solution, or atleast have one on the roadmap.

**Comment by Twinkletoes** [comment]
http://emberjs.com/guides/testing/test-helpers/

The example at the bottom suffers from this regression

**Comment by rwjblue** [comment]
@Twinkletoes - Good catch!  The JSBin's in the guides are being removed as part of a rewrite of the guides to be more ember-cli focused, so this should be removed in the next few days/week.
