### ISSUE TITLE
Add addonPostprocessTree for type 'style'

### ISSUE THREAD

**Issue by jschilli** [ember-cli/ember-cli#3534]
Currently addon postprocessors that wish to postprocess style files have to run on type 'all'

when running ember serve and changing only a .js file addons that postproceesTrees for 'all' will run even though no style file changes have occurred.

I will try to look into a PR for this next week.

ref: https://github.com/kimroen/ember-cli-autoprefixer/pull/11

cc: // @kimroen

**Comment by rwjblue** [comment]
Definitely :+1: on this.  We should have `"js"`, `"all"`, and `"css"` types for `postprocessTree`.

**Comment by jschilli** [comment]
@rwjblue did you mean `"js"`, `"all"` and `"styles"` iso `"css"` 

I'm assuming `styles` as that is what we call addonTrees for in other places

**Comment by rwjblue** [comment]
The preprocessors that have in the registry are `"js"`, `"template"`, and `"css"`, so I believe it should match that.

**Comment by rwjblue** [comment]
Code for preprocessor helper functions is at: https://github.com/ember-cli/ember-cli/blob/master/lib/preprocessors.js

**Comment by jschilli** [comment]
gotcha, so I'll change it to 'css' but it seems odd that we call `this.addonTreesFor('styles');` so from an addon author's perspective i'm dealing with 'styles' sometimes and 'css' in others

**Comment by rwjblue** [comment]
Yes, totally agreed.  We should consolidated (likely on `styles`).

**Comment by stefanpenner** [comment]
This is causing merge collisions for me, going to try and investigate.

**Comment by stefanpenner** [comment]
I believe this is the result of a mis-behaving add-on, and isn't the fault of this change.
