### ISSUE TITLE
Error while trying to build ember js project

### ISSUE THREAD

**Issue by Vishwaas** [ember-cli/ember-cli#3547]
Hi
I am facing the below issue when i try to build ember. Any help appreciated!

[error-while-trying-to-build-ember-js-project](http://stackoverflow.com/questions/29028939/error-while-trying-to-build-ember-js-project)

**Comment by stefanpenner** [comment]
@Vishwaas could you also provide a repo demonstrating this issue, it will make it easier to debug

**Comment by xomaczar** [comment]
@Vishwas disable sourceMapping in your Brocfile when building. just noticed it today. @stefanpenner before 0.2.beta had no issue. Is this upstream issue?

**Comment by Vishwaas** [comment]
@xomaczar  yes you are right!, i did it based on a suggestion on stackoverflow and it worked. : )
@stefanpenner  - xomaczar  is right

This should not have been an issue i guess but considering that i was not getting any issue earlier but now i am getting it, i guess there is some issue in the way build is happening now! So its ur call if it has to be made invalid or checked further!

**Comment by xomaczar** [comment]
@Vishwaas Great. should have scrolled that stackoverflow responses. Glad all works.

**Comment by stefanpenner** [comment]
it seems to be a valid issue, although unlikely an issue with ember-cli itself, rather some dep provided source maps that uglify-js cant consume. Either that are actually invalid or uglify has a bug.

This needs further investigation
