### ISSUE TITLE
when creating mixin in an addon project it generate the mixin file in the app/mixins folder

### ISSUE THREAD

**Issue by oriSomething** [ember-cli/ember-cli#3548]
when creating `mixin` in an `addon` project it generate the `mixin` file in the `app/mixins` folder instead of the `addon/mixins` folder.

version: `ember-cli 0.2.0`

is it supposed to be like that and i missed something?

**Comment by rwjblue** [comment]
No, your understanding is correct.  This should be generated in `addon/` not `app/`.  Many of the blueprints will need to be reviewed and fixed up to put custom code in `addon/` instead of `app/`...

**Comment by trabus** [comment]
@rwjblue I think I can knock this out pretty quickly (as well as any others that should fixed sooner than later). 

Just to clarify, should it follow the same pattern as the components, generating into `addon/mixins` with a `app/mixins` counterpart importing it from the addon namespace?

**Comment by rwjblue** [comment]
@trabus - In the case of `mixins` we do not need a re-export in `app/` tree, because it will need to be imported by the consuming app anyways (it isn't auto-looked up by the resolver, it is instead provided to a factory at `extend` time).

**Comment by trabus** [comment]
@rwjblue Ah, that makes sense.
