### ISSUE TITLE
ember server now requires internet connection

### ISSUE THREAD

**Issue by downie** [ember-cli/ember-cli#3549]
This looks to be a recent change. As of ember-cli v0.1.15, we could run `ember server` without issue, even if the internet was down.

However, running `ember server` on v0.2.0 with the internet disabled shows this error:
```
version: 0.2.0

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

This also shows up when running `ember test --server`

PS: There's also this output; I know I need to upgrade things, but I don't think this would be causing the issue. Let me know if I'm wrong and I just need later versions of things to fix this.
```
chris$ ember server
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/chris/usermind/src/github.com/usermindinc/skylab/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Future versions of Ember CLI will not support v0.10.33. Please update to Node 0.12 or io.js.
```

**Comment by rwjblue** [comment]
I just tested a freshly generated (and empty) ember-cli@0.2.0 app without a network connection, and it built and is serving assets properly.  It is possible this is coming from an addon that you are using, can you share your `package.json`'s deps and devDeps?

**Comment by rwjblue** [comment]
While testing I did discover an issue with ember-cli-yuidoc (and reported it here: https://github.com/cibernox/ember-cli-yuidoc/issues/15). This *might* be the issue you are seeing, but that addon isn't included in the default blueprint so I'm unsure...

**Comment by downie** [comment]
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "commander": "^2.6.0",
    "ember-cli": "^0.2.0",
    "ember-cli-app-version": "0.3.2",
    "ember-cli-babel": "^4.1.0",
    "ember-cli-compass-compiler": "0.0.18",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-pretender": "0.3.1",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-simple-auth": "0.7.2",
    "ember-cli-simple-auth-oauth2": "0.7.2",
    "ember-cli-simple-auth-testing": "0.7.3",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.2",
    "emblem": "0.3.18",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "json-diff": "^0.3.1",
    "performance-now": "^0.2.0",
    "request": "^2.51.0",
    "selenium-webdriver": "^2.44.0",
    "sprintf-js": "^1.0.2"
  },
  "dependencies": {
    "broccoli-emblem-compiler": "0.3.18",
    "phantomjs": "^1.9.15"
  }
```

**Comment by rwjblue** [comment]
@downie - Can you remove deps one at a time without a network connection, and let us know which one is triggering this?

**Comment by stefanpenner** [comment]
this seems related to the recent update-checker stuff, which I believe is fixed on master.

**Comment by stefanpenner** [comment]
from the error, i am unsure if it was actually a disabled connection and more like the internet was just down/broken.

**Comment by downie** [comment]
Dropping my internet connection now, everything seems to work, even before I remove any deps. Which makes me think it was some old package that has since been blown away by a newer one that now resides in my local cache. 

@theazureshadow you were able to repo this issue too, right?

**Comment by stefanpenner** [comment]
going to close this, will reopen with a repo + steps the reproduce (or sufficient convincing)

**Comment by downie** [comment]
@stefanpenner it was discovered when tethering to a phone that had no service. So, strong wifi connection but no internet connection. I believe a coworker saw the same issue by disabling wifi locally.

**Comment by stefanpenner** [comment]
>  tethering to a phone that had no service. So, strong wifi connection but no internet connection. 

this would make sense, let me know if it continues. we can re-investigate. I suspect the updateChecker is at fault.

**Comment by rwjblue** [comment]
@stefanpenner - I do not believe that we (ember-cli) have an issue with requiring internet to run `ember s` (I run without internet for 2-4 hours daily), but some addons are absolutely doing things that go boom (even if they aren't needed). For example see https://github.com/cibernox/ember-cli-yuidoc/issues/15.

We can address these issues as they come up, most likely in the actual addon at faults repo...

**Comment by xomaczar** [comment]
@rwjblue - I believe this is exactly the case, as of right now. Ember-cli "requires internet connection" regardless of the command you execute (well, except when in test or running an 'update' command). The updateChecker's http.get() fails, blocking any command execution.
It's quite reproducible, new ember-cli@2.0.xxxx project, no internet connection, and
rm -rf  ~/.config/configstore/*.
PR #3448 should have a fix.

**Comment by stefanpenner** [comment]
i have also not been able to reproduce this, which OS and node versions are you on ?

**Comment by xomaczar** [comment]
Mac@10.8.5 and node@0.10.35

**Comment by stefanpenner** [comment]
> Mac@10.8.5

hmm, might be something to do with node DNS resolving on this os version?

**Comment by xomaczar** [comment]
I doubt it's related, same thing at work on ubuntu 14.04 with proxy. Just tried with ember-cli/master with no connection and empty configstore. unhandled error

**Comment by stefanpenner** [comment]
i'll try linux tomorrow at work.

**Comment by xomaczar** [comment]
Same here, thanks

**Comment by cibernox** [comment]
I've released version `0.6.1` of [ember-cli-yuidoc](https://www.npmjs.com/package/ember-cli-yuidoc). Try the new version to see if it's the root of your issue.

**Comment by mfeckie** [comment]
I've just had the same problem trying to work on a flight.

```
version: 0.2.0
events.js:141
throw er; // Unhandled 'error' event
^
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
at errnoException (dns.js:25:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)
```

Total first world problem I know, but it was a surprise!

**Comment by mfeckie** [comment]
As an FYI, I don't have ember-cli-yuidoc in my package.  OSX with iojs rather than node is my platform.

**Comment by xomaczar** [comment]
@mfeckie  Can you double check that you are running the latest master:ember-cli, and not loading project specific ember-cli. The changes were pushed to the master, which have not been published to npm. If you try to run ember whatever-command inside the project that has a non-master version, ember-cli will run that version, i.e. Ignoring the fix. Let me know what you find out.
cc @stefanpenner

**Comment by xomaczar** [comment]
Actually based on your output seems you are running 2.0.0 version, the changes were made to 2.0.0-sha

**Comment by stefanpenner** [comment]
I suspect his problem will be solved when we release the next version. Which will likely be this weekend

**Comment by mfeckie** [comment]
OK cool, thanks for the feedback folks!  Keep up the awesome work you all do :smile:

**Comment by foster** [comment]
Chiming in: I just encountered this error on an airplane with 0.2.0 installed from npm. Now that I have connectivity, I upgraded to ember-cli from master and am able to work offline.

**Comment by Siyamala** [comment]
Hi,
 While upgrading to 0.2.0 we got the below 

Future versions of Ember CLI will not support v0.10.30. Please update to Node 0.12 or io.js.
version: 0.2.0

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

But we are behind a proxy. Is that the issue? Please let me know if anyone had the same issue and the solution for it. thanks in advance.
Note : We have all proxy setup running and it was not any creating issue till 0.1.7 version

**Comment by stefanpenner** [comment]
> But we are behind a proxy. Is that the issue? Please let me know if anyone had the same issue and the solution for it. thanks in advance.
> Note : We have all proxy setup running and it was not any creating issue till 0.1.7 version

this is fixed on master, and will be fixed in the next release. For now you can disable analytics in the rc file

**Comment by Siyamala** [comment]
Sure will check on that. Thanks for the quick response.
