### ISSUE TITLE
Proposal: flag for utils-based helpers

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#3552]
A common pattern when writing helpers is to write them as pure functions in `app/utils/` and then call `makeBoundHelper` separately:
```js
// app/helpers/my-helper.js
import Ember from "ember";
import myHelper from "my-app/utils/my-helper";
export default Ember.Handlebars.makeBoundHelper(myHelper);

// app/utils/my-helper.js
export default function() {
  return "something";
}
```

This makes testing much easier since the tests don't have to do any DOM rendering.

I'd love to have `ember g helper my-helper --utils` generate `app/helpers/my-helper.js`, `app/utils/my-helper.js`, and `tests/unit/utils/my-helper-test.js`.

**Comment by stefanpenner** [comment]
@tomdale refresh my memory, but in glimmer land are all helpers pure functions + bound by default? If so, I would prefer to wait and just remove the bound constructs all-togheter.

**Comment by jamesarosen** [comment]
If that's the future, it's a future I want to be in!

**Comment by stefanpenner** [comment]
> If that's the future, it's a future I want to be in!

yes, likewise.

**Comment by rwjblue** [comment]
running `ember g helper foo-bar` does the following today:

* generates a helper structured as you are suggesting with a separate export for the actual helper function.  See [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/helper/files/app/helpers/__name__.js).
* generates a test that imports the function and invokes it directly. See [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/helper-test/files/tests/unit/helpers/__name__-test.js).

Given these two things, why move the helper function out of the helper file and into `app/utils` that makes it unclear what the function is used for?

**Comment by jamesarosen** [comment]
I didn't notice that when I generated a helper. The multiple-exports
version is great!

I'll switch our project over to that 😀
