### ISSUE TITLE
[Proposal] Optionally generate a failing test with built-in blueprints

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3553]
[As seen on Twitter](https://twitter.com/bcardarella/status/577665064234295296). We should allow the option to generate a failing test inside generated test blueprints. This should be available through a command option, as well as configurable project-wide as an option inside the `.ember-cli` file.

**Comment by trabus** [comment]
The command option could be `ember g component taco-shell --fail` with an alias of `-f`, and the `.ember-cli` property could be `generateWithFailingTest`.

@ember-cli/owners thoughts?

**Comment by bcardarella** [comment]
while I think it is a step in the right direction I question how many people will opt-in. IMO a generated passing test that doesn't fail either on generation or at least when the addon code changes should be suspect. For example, the component test blueprint: https://github.com/ember-cli/ember-cli/blob/master/blueprints/component-test/files/tests/unit/__path__/__test__.js all this does is assert that the component is inDOM. I believe this is a bad test for two reasons:

1. it won't fail when the developer makes any changes, even major ones
2. it seems to be testing that Ember itself is working, which I don't think is something we should be promoting as a testing scenario for people's apps

to continue using the component test as an example, it would be far more useful if the test generated a failure with some comments on how one might go about unit testing a component

/2cents

**Comment by trabus** [comment]
@bcardarella I'm all for promoting best practices, and making the path to writing useful tests clearer is definitely in everyone's best interests. However, I think that changing it to have failing tests as the default without providing some way to opt out (at least at first) may come with resistance. I think maybe starting an opt-out approach would be better, at least for a transitional period, then maybe make it the default.

I'm in agreement that the default test isn't very useful aside from showing what a test looks like, and if it's harmful, it should probably be removed, leaving no tests as the default when opting out.

**Comment by jgwhite** [comment]
Focusing on the component example for simplicity, are we imagining the failing test would be something like:

```js
import {
  moduleForComponent,
  test
} from 'ember-qunit';

moduleForComponent('FooBarComponent');

test('someProperty', function(assert) {
  var component = this.subject();
  // Specify your component’s behaviour here:
  // assert.equal(component.get('someProperty'), 'expected value');
});
```

Which will fail with `expected at least one assertion` and force the developer to either specify behaviour or delete the test :trollface:

**Comment by jgwhite** [comment]
While we’re on the subject of the component test, I’ve found the default test to be a reasonable indicator when a component:

1. Does not handle missing attributes well
2. Depends on many other components (big nasty `needs` list)
