### ISSUE TITLE
[Proposal] Denote which blueprints support pod structure in help output

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3554]
Since not all of the built-in blueprints support pod structure, we should somehow denote which blueprints support generating in pod structure in the command line help output. This will help clarify the behavior of blueprints that don't support pod structure ignoring the `--pod` option and generating in the basic structure.

**Comment by stefanpenner** [comment]
> ignoring the --pod

seems like they should error if they do not support the flag?

**Comment by trabus** [comment]
I forgot that they do warn when generated, but I thought it might be helpful to identify them somehow in the help. Not super important, more just to make things more clear.

**Comment by stefanpenner** [comment]
Tagging capabilities does seem like a win
