### ISSUE TITLE
in 0.2.0 using module in tests doesn't give deprecation warning

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3557]
Old code, generated by ember-cli, no longer works but there is no deprecation warning

```
import Ember from 'ember';
import AjaxMixin from 'insm-ui/mixins/ajax';
import {
  module,
  test
} from 'ember-qunit';

module('AjaxMixin');  // <----------- deprecated???

// Replace this with your real tests.
test('it works', function(assert) {
  var AjaxObject = Ember.Object.extend(AjaxMixin);
  var subject = AjaxObject.create();
  assert.ok(subject);
});
```

**Comment by Twinkletoes** [comment]
I've fixed the test with a change to modelFor:

```
import Ember from 'ember';
import AjaxMixin from 'insm-ui/mixins/ajax';
import {
  moduleFor,
  test
} from 'ember-qunit';

moduleFor('mixin:ajax');

// Replace this with your real tests.
test('it works', function(assert) {
  var AjaxObject = Ember.Object.extend(AjaxMixin);
  var subject = AjaxObject.create();
  assert.ok(subject);
});
```

**Comment by rwjblue** [comment]
`module` was never available from `ember-qunit`, it should be `import { module } from 'qunit';`.  If that import statement was generated by one of our generators it is wrong, and needs to be updatd.

**Comment by rwjblue** [comment]
Looks like the mixin generator uses `import { module, test } from 'qunit';` (properly):

https://github.com/ember-cli/ember-cli/blob/master/blueprints/mixin-test/files/tests/unit/mixins/__name__-test.js#L3

**Comment by Twinkletoes** [comment]
@rwjblue 

Yes, that's what the mixin generator does, and how our tests were written.

In ember-cli 0.10 those tests passed. In ember-cli 0.2.0, module doesn't work, and moduleFor seems to work as a replacement. 

This is either an unintentional regression, or a deprecation that hasn't been warned.

**Comment by rwjblue** [comment]
Looking at the history of [the mixin test file](https://github.com/ember-cli/ember-cli/commits/master/blueprints/mixin-test/files/tests/unit/mixins/__name__-test.js) shows that `module` was never imported from `ember-qunit` in the mixin generator.

> In ember-cli 0.2.0, module doesn't work

`module` works just fine (and is provided by QUnit not Ember CLI or ember-qunit), but it is not added to the list of globals in `tests/.jshintrc`. If you take the `tests/.jshintrc` change (removing `module` and `test` from globals), you will also have to update your test files to either `import { module, test } from 'qunit';` or use `QUnit.module` to avoid JSHint failures.

>  and moduleFor seems to work as a replacement.

`moduleFor` doesn't really make sense in the context of a mixin since you don't need/want the augmentation that ember-qunit provides.

**Comment by Twinkletoes** [comment]
If you look at my code, you can see that it did import module from QUnit. Changing that to moduleFor fixed the problem

**Comment by rwjblue** [comment]
@Twinkletoes - No the lead in description has:

```
import {
  module,
  test
} from 'ember-qunit';
```

Which is **NOT** the same as:

```
import {
  module,
  test
} from 'qunit';
```

**Comment by Twinkletoes** [comment]
Oooooh my bad. Subtle!

OK, will log the deprecation against ember-qunit

**Comment by rwjblue** [comment]
@Twinkletoes - It isn't an issue or deprecation on either library, that is what I am saying.

**Comment by rwjblue** [comment]
`module` was *never* available to import from `ember-qunit`, why would ember-qunit deprecate a thing it never had?

**Comment by Twinkletoes** [comment]
It worked in ember-cli 0.1.10 and its dependencies, doesn't work in 0.2.0 and its dependencies - that's a deprecation or a regression isn't it?

**Comment by Twinkletoes** [comment]
I suddenly have no confidence in my code - I'm going to diff against the version that worked and confirm I'm not going mad

**Comment by rwjblue** [comment]
> It worked in ember-cli 0.1.10 and its dependencies, doesn't work in 0.2.0 and its dependencies

Using `module` without any import still works fine in 0.2.0, but unless you change the `tests/.jshintrc` file to add it back to the list of allowed globals you will get a JSHint failure.

**Comment by Twinkletoes** [comment]
This is my diff on this file back to ember-cli 0.1.10

diff --git a/tests/unit/mixins/ajax-test.js b/tests/unit/mixins/ajax-test.js
--- a/tests/unit/mixins/ajax-test.js
+++ b/tests/unit/mixins/ajax-test.js
@@ -1,11 +1,11 @@
 import Ember from 'ember';
 import AjaxMixin from 'insm-ui/mixins/ajax';
 import {
-  module,
+  moduleFor,
   test
 } from 'ember-qunit';
 
-module('AjaxMixin');
+moduleFor('mixin:ajax');
 
 // Replace this with your real tests.
 test('it works', function(assert) {

As you can see the generator back then generated ember-qunit imports, and all I've changed to make the test pass is changed module to moduleFor

So this still feels like a regression or deprecation.

**Comment by Twinkletoes** [comment]
I've been through most of my other tests and they all import from ember-qunit and not qunit directly like this. They were all generated using the ember-cli generators.

```
// tests/models/player-test.js
import {
  moduleForModel,
  test
} from 'ember-qunit';
```

**Comment by stefanpenner** [comment]
@Twinkletoes hmm, this sure is a puzzle, I am baffled that the `import { module } from 'ember-qunit'` ever worked.

**Comment by Twinkletoes** [comment]
I think there must be a cockup at my end somewhere - if this was never in your changelog then it can't be a problem your end.

I'm going through fixing about 200 (50%) of our tests which were broken by the upgrade from 0.1.10 to 0.2.0. All sorts of reasons in there from nicely warned deprecations in cli to changes in ember-data that weren't flagged as deprecation, to bugs in testem, to all the globals being removed from jshint (luckily regex saved my ass there). So I wonder if I've made a global change somewhere and changed this code as an accidental byproduct. 

I'd say stop looking for a problem unless someone else reports this.

So are we saying (after all that) that this is correct:
```
import {
  moduleForModel,
  test
} from 'ember-qunit';
```
and this is correct:
```
import {
  module,
  test
} from 'qunit';
```

And you're recommending against the use of moduleFor for testing mixins? 

In which case is there a case to say that for ease of use and balanced code, ember-qunit should export { module } and map it directly onto an import from qunit? Then the developer can use ember-qunit everywhere and not have special cases.

**Comment by stefanpenner** [comment]
> And you're recommending against the use of moduleFor for testing mixins?

as mixins don't need any setup, you can typically just import them directly and test them, no need to go through anything else



> ember-qunit

these provides ember specific test helpers like `moduleFor` and `moduleForComponent`

> qunit

this provides the vanilla qunit  `module` that we leave untainted.

Because of this, I will likely advocate they be kept seperate.
