### ISSUE TITLE
Split compiled templates into separate templates.js file

### ISSUE THREAD

**Issue by j-carvalho** [ember-cli/ember-cli#3558]
I'm currently having some issues with debugging an ember-cli application, using both Firefox and Chrome.

The issue seems to be related with the project size and the generated [app-name].js file size. Firefox just freezes and Chrome keeps showing a message "Waiting for source map...".

Would it make sense to split the compiled templates into a separate file to have a smaller [app-name].js file?

**Comment by stefanpenner** [comment]
this needs to be opened as chrome and firefox issue.

**Comment by knownasilya** [comment]
I've also had this issue, particularly when debugging services/initializers..

**Comment by j-carvalho** [comment]
Of course, Chrome and Firefox should be able to read them no matter what, but given that most likely you won't debug the compiled templates, wouldn't it make sense to split them?

**Comment by knownasilya** [comment]
Also not sure why *.jshint files are being served..

**Comment by stefanpenner** [comment]
i will consider splitting as quick fix, but only if this issue is actually being tracked by FF/Chrome.

**Comment by stefanpenner** [comment]
This seems to have gone stale.

resolution:

* report FF bug
* report Chrome bug

as they will fix the underlying issue

* will accept a clean refactoring that enables splitting, but don't have intention of implementing that right now. The current refactoring approach may make this easier, but it takes higher priority.
