### ISSUE TITLE
Can't use unnamed AMD modules

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli#3563]
It seems that unnamed AMD modules are [preferred](https://groups.google.com/forum/#!topic/amd-implement/VAtOIIyVrOs) over named AMD modules and most browser packages are only setup to use unnamed AMD.

[The docs](http://www.ember-cli.com/#standard-amd-asset) only show an example for named AMD modules and I have been unable to get unnamed modules to work. Is it possible to use Ember CLI with unnamed modules and, if not, are there plans to add this compatibility?

**Comment by stefanpenner** [comment]
duplicate: https://github.com/ember-cli/ember-cli/search?q=unnamed+AMD+modules&type=Issues&utf8=%E2%9C%93

TL;DR not supported, will likely support at some-point. 

related libraries: https://github.com/stefanpenner/petal

issues to follow: https://github.com/ember-cli/ember-cli/issues/2177
