### ISSUE TITLE
How to check model's existence

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3568]
I've extended the Store to introduce polymorphism in my app:
http://vimeo.com/115987599 (7:21)

```js
export default DS.Store.extend({

  init: function() {
    return this._super.apply(this, arguments);
  },

  /**
   * Polymorphic type support: http://vimeo.com/115987599 (7:21)
   */
  push : function(type, data, _partial) {

    var dataType, modelType, oldRecord, oldType;

    modelType = oldType = type;
    dataType = data.type; // The type parameter is required in the payload with the subclass name

    if (dataType && (this.modelFor(oldType) !== this.modelFor(dataType))) {

      modelType = dataType;

      if (oldRecord = this.getById(oldType, data.id)) {
          this.dematerializeRecord(oldRecord);
      }

    }

    return this._super(this.modelFor(modelType), data, _partial);

  }

});

```

However when the API services return a model with a type attribute value that doesn't exist as a model the app crashes. I'd like to be able to check that a model exists before enabling instantiation of the subclass.

Any insights?

**Comment by stefanpenner** [comment]
hey @olivierlesnicki good question, unfortunately this is `ember-cli`'s issue tracker, which we need to keep focused to issues or bugs with ember-cli itself. The best medium for your question is likely Stackoverflow, or the ember/data issue tracker.

**Comment by olivierlesnicki** [comment]
@stefanpenner you're right this should have been raised against ember/data.
And I've discovered I can use `modelFactoryFor()`.
