### ISSUE TITLE
[proposal] Addons need a better config story

### ISSUE THREAD

**Issue by runspired** [ember-cli/ember-cli#3575]
## Improving Addon Configuration

Addons needs a better config story.  I have a proposal I want to bounce around before possibly submitting an RFC.

This is related to https://github.com/ember-cli/ember-cli/issues/2135 and https://github.com/ember-cli/ember-cli/issues/2823

### Problems

- Some addons require or allow end user configuration.
- Some addons require or allow a user to select a permanent "addon mode" (similar to `usePods`)

### Pain points

`config/environment` is not a great place to store addon configuration, both because it quickly leads to a large bloated config and because it forces the addon to place files in `/app` when it needs access to configurations (among other troubles this causes, it makes a generic solution for compiling addons for use in non ember-cli apps and jsbins much more difficult).

Some addons need to store permanent configuration settings that aren't part of the app but part of the addon's functionality.  In `ember-cli-cordova` I have a PR waiting for a way to store a user set configuration that is set once when a blueprint is first used (in this case, whether to structure the cordova portion as one app or multiple apps).

With currently available packages, `.ember-cli` isn't writeable without erasing the comments in it, but even if it were that doesn't seem to be the right location for addons to add permanent configuration settings.

#### use `config/`
There is already a `config/` folder within each ember app, and it only contains `environment.js`.  It seems as though someone at some point rightly thought there would be need for more configs than just environment.

#### Namespaced subfolders
The configs for the addon `liquid-fire` would be in `config/liquid-fire/`

#### Multiple config types
Sticking with the `liquid-fire` addon example.
- permanent settings would be in flat/writeable file `config/liquid-fire/.liquid-fire-setup`
- environment based settings would be in `config/liquid-fire/environment.js`

#### In the Addon
The addon's `config/` folder would be copied into `config/<addon-name>/` during `ember install:addon`

#### Updating Addons
`ember update:addon` would update the addon the a specified (or latest) version and allow per-file diffing of the changes in the files installed by the default blueprint and config with both the previously installed version and the user's modifications.

**Comment by stefanpenner** [comment]
cc @lukemelia 

@rwjblue do you have a link to my old config proposal?

**Comment by rwjblue** [comment]
My proposal is the following: https://gist.github.com/rwjblue/ecb483b15da77582d0b9

**Comment by stefanpenner** [comment]
this should likely take the form of an RFC

**Comment by runspired** [comment]
@stefanpenner submitting an RFC was my intention, I just wanted to get some early feedback before diving in entirely the wrong direction.

@rwjblue's proposal is interesting.  I'd love a few points of clarification on it, specifically because I want to ensure that the end result here solves the use case for *permanent configuration settings* used by an addon's blueprints and commands.

```
var config = require('ember-cli/config/environments/production.js'); 
```

This looks to be the default template for a config.  Let's say an addon extends it (perhaps a config file in the default blueprint?).  With this setup, could an addon module access the finalized version of the config without needing to be in the `/app` directory?  (Perhaps via `import config from `ember-cli/config/environment`;)

What about access to the final server config from a command?  Would it be exposed on `this.project`? (e.g. https://github.com/poetic/ember-cli-cordova/blob/master/lib/tasks/cordova.js )

**Comment by stefanpenner** [comment]
RFC is the best place for feedback, as it then allows future readers to view the changes over time and get context

**Comment by runspired** [comment]
@stefanpenner noted.  I'll link back to here when I submit something to include this context as well.
