### ISSUE TITLE
add ember uninstall:bower and ember uninstall:npm

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#3582]
I was using `ember install:bower` on a fresh VM without bower installed globally. I made a mistake and wanted to uninstall. I think it makes sense to have a `ember uninstall:bower` and `ember uninstall:npm` to use the local versions.

I can implement this if there is consensus.

**Comment by stefanpenner** [comment]
* we are deprecating bower
* `ember install:addon` will become `ember install`
* this suggests `ember uninstall` should be `ember uninstall:npm` you propose.

**Comment by kellyselden** [comment]
Merged in #3593
