### ISSUE TITLE
Pod templates inside addons don't get compiled

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3586]
Currently there seems to be an issue with templates being imported from pods inside in-repo-addons (I haven't yet verified if the same issue affects addons as well). [This repo](https://github.com/trabus/in-repo-addon-pod-template) illustrates it, where trying to load a pod based component's template fails. The non-pod component is able to load with no issue, but the pod component fails because the template is not compiled.

Running the example app above, the following error occurs:
```
 Uncaught Error: Could not find module `foo-bar/components/foo-bar/template` imported from `foo-bar/components/foo-bar/component`
```

The error is not present when the `foo-bar` component is removed from the `application.hbs`.

I believe the issue lies with the way the templates are processed in addons. The [tree passed]( is `addon/templates`, so) into [compileTemplates](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L443)  is `addon/templates`, so it seems the `addon` tree is missing templates inside pod structure folders.

**Comment by rwjblue** [comment]
I updated the title to reflect that the same thing affects normal addons (there really is only a small difference between in-repo and normal addons).
