### ISSUE TITLE
[Proposal] command - ember cleanup

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3588]
Background
---------------
When I build my app using ember-cli I often generate, for example, routes. Then not to duplicate my template code, I use [templateName](http://emberjs.com/api/classes/Ember.Route.html#property_templateName). When I do this multiple times I may forget that I leave templates generated just with `{{outlet}}` as their content.
Also, after some time of developing an application I have controllers that just extend `Ember.Controller` and nothing more.
I think both default templates and default controllers aren't needed in my app's source. Also, one might forget to clean some imports in files which are no longer needed.
I believe if ember-cli had a command to just cleanup all these things, it would be easier to maintain application(reducing number of files, reducing confusion, [<i>reducing byte size? are default templates, default controllers striped from source code? I don't think so.</i>]).

Proposal
------------
Create `ember cleanup` command which:
- deletes all not used imports in files
- deletes controllers with default content(just extending from `Ember.Controller`) - <i>I'm trying to find some cases where it would cause issues, but I think programatically auto-generated controllers can do the same.</i>
- deletes templates with just `{{outlet}}` as their content

More
-------
I think it could also be extended to:
- check for unnecessary bower(<i>I know it's going to be deprecated, so maybe some replacement for bower</i>), npm packages - <i>this is similiar to `ember doctor` concept but it would be possible to delete dependencies programatically</i>
- check for no longer referenced components, helpers, templates, controllers and eventually delete them
- check for CSS/SCSS/other which is not used by application code anymore and eventually remove it
- check for class names not being dasherized and eventually rename it both in .css and templates, js files

CLI users should be given options to cleanup only things they want.

Do you think it would be worth to have?

**Comment by stefanpenner** [comment]
interesting, but proposals should follow the rfc process https://github.com/ember-cli/rfcs

**Comment by Kuzirashi** [comment]
Created RFC here: https://github.com/ember-cli/rfcs/pull/9.
