### ISSUE TITLE
npm link to globally installed bower instead of bundling it

### ISSUE THREAD

**Issue by jayphelps** [ember-cli/ember-cli#3589]
We could save a nice chunk of MB's if we don't bundle/install bower.
Pseudo code on how to do this: https://gist.github.com/jayphelps/e955a9b407559ac1830a

Thoughts?

**Comment by rwjblue** [comment]
If we did this, then users would be required to have bower installed globally. This would mean that our install instructions would have to instruct users to 'npm install -g bower'. Since we plan to kill bower requirement relatively soon, I'm not sure we should start telling folks to install bower in our instructions now...

**Comment by stefanpenner** [comment]
-1 for global link.

we have no idea what version of bower they have installed, relying on this (as we did in the past) is a disaster.

The are plan is to actually drop bower entirely (although we will move it to an addon first, for backwards compatibility). This will likely be the best soution to this problem.

**Comment by jayphelps** [comment]
Cool beans. Btw, the install instructions DO tell you bower is required to be installed globally and shows you how. :p also, Stef clearly didn't read the gist.

**Comment by jayphelps** [comment]
![image](https://cloud.githubusercontent.com/assets/762949/6766062/b508934e-cfb4-11e4-81e4-83b9b5b909e4.jpg)

**Comment by stefanpenner** [comment]
Ya I think so.

Btw if you are interested in helping with the bower killing. Let me know

**Comment by thomblake** [comment]
@stefanpenner Is killing bower still a thing that's going to happen? Is there a relevant issue to follow?

**Comment by stefanpenner** [comment]
yes, https://github.com/ember-cli/ember-cli/issues/4546
