### ISSUE TITLE
Lazy install certain npm dependencies (testem, maybe more?)

### ISSUE THREAD

**Issue by jayphelps** [ember-cli/ember-cli#3590]
To make initial npm installs quicker, perhaps we can lazily install certain dependencies?
testem in particular is a sizable project which is only needed (AFAIK) when the `test` command -> task is run. I think a lot of people would rather pay that cost later Just-In-Time, than initially when they create/install their app and probably just want to do `npm start`.

(without looking much at it, this looks similar in theory https://www.npmjs.com/package/lazy-install)

**Comment by rwjblue** [comment]
:+1: on lazy installing what we can

:-1: on making testing that thing :stuck_out_tongue_winking_eye:

**Comment by stefanpenner** [comment]
on this note, as we make progress on the anti-bower movement. We will soon be able to remove bower from the default install, bower is honestly the biggest and baddest dependency. 

As for lazy-dependencies. This is truely unfortunate failure of `npm`, all these deps are essentially local already. The should be zero cost.  We can in-theory have a `fast` dependency mode instead, where we just use symlinks to install some dependencies?

It would be great to actually compose a list of our worst offending dependencies, and see if we can drop them, improve them or finally explore the lazy option.

**Comment by stefanpenner** [comment]
cool idea, but something someone will need to champion.

I think the big cost (for testem) is now fixed, as we have patched its deps to no longer have native deps.
