### ISSUE TITLE
[Feature Request] Add Rename command

### ISSUE THREAD

**Issue by stavarotti** [ember-cli/ember-cli#3595]
E.g. `ember rn <blueprint> <old_name> <new_name>`

I often find myself coming up with better names (especially with components) soon after running the generate command and adding some bit of code.  If I haven't added any code, it's simple enough to run `ember d <blueprint> <name>` however, if I have added some code, I tend to use `REN old.js new.js` (Windows) or `mv old.js new.js` on each generated file in addition to changing the export name.  While not difficult, it is mildly inconvenient to rename each individual file especially when more than one file is generated from the `blueprint`.

Thoughts?  I can flesh out an RFC if this is deemed useful.

**Comment by stefanpenner** [comment]
> Thoughts? I can flesh out an RFC if this is deemed useful.

i would love exploration into refactoring tools that this.

**Comment by hhff** [comment]
I would love this

**Comment by trabus** [comment]
This is something I've wanted for a while, but it should probably be considered for an addon. I proposed something like this a while back, but @rwjblue suggested that we shouldn't try and make ember-cli core do everything, but rather add functionality like this through addons. If it's determined that enough people want it in by default, we can just add it to the package.json.

I would definitely have some interest in helping with this, as it's essentially a command/task that I could reuse for ember-cli-podify.

I'd like it to be git aware, making use of `git mv` when git is present in the project, keeping history is important to me. One other part of this is updating any imports of the old file path to the new file path. Would probably want to use [recast](https://github.com/benjamn/recast) for that.

**Comment by stefanpenner** [comment]
closing this, in-favor of a RFC.

**Comment by stavarotti** [comment]
> i would love exploration into refactoring tools that this.

Sounds good.  I will go ahead and dig into this later this week.

> I would definitely have some interest in helping with this, as it's essentially a command/task that I could reuse for ember-cli-podify.

@trabus I could use your help in drafting up an RFC.  Can we chat on irc about the details?
