### ISSUE TITLE
Creating JSbins/JSfiddles

### ISSUE THREAD

**Issue by domchristie** [ember-cli/ember-cli#3597]
JSbin/JSfiddle have been invaluable tools in helping debug ember issues, and are recommended on the ember contributing guide. With a move towards modules and an ember-cli build system, replicating a problem in a JSbin becomes a bit harder.

Is there some way we can make creating JSbins/JSfiddles easier from ember-cli?

**Comment by stefanpenner** [comment]
cc @joostdevries

**Comment by domchristie** [comment]
Cool. Is there an open issue for this? It was a tricky issue to search for!

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/search?q=JSbins&type=Issues&utf8=%E2%9C%93 led me to https://github.com/ember-cli/ember-cli/issues/3050

**Comment by stefanpenner** [comment]
closing, as the discussion can be continued: https://github.com/ember-cli/ember-cli/issues/3050#issuecomment-70970126

**Comment by domchristie** [comment]
:+1: Cool.

(FWIW, I didn’t search for closed issues)

**Comment by stefanpenner** [comment]
@domchristie ya not sure what to do about those, good topics. But not actionable in the scope of ember-cli itself. But discussions should continue..

**Comment by domchristie** [comment]
Cool. Yes I’d hesitated to raise them before, because I was not entirely sure where they fit, but given the recent discussions I’d thought I’d mention them. Thanks for your responses :)
