### ISSUE TITLE
Strange route asked

### ISSUE THREAD

**Issue by Leryan** [ember-cli/ember-cli#3599]
Hi,

I am new to Ember, but I got a successful "app" with it, then i'm trying to "port" it to ember-cli.

I have a quite empty main page, and a link to the about page: main and about routes are defined.

However I got a `404 "/mains" not found` when accessing `/`… why the hell is he adding an extra "s"?

I've uploaded the project:

https://github.com/Leryan/testember

You'll see a picture with the problem.

**Comment by stefanpenner** [comment]
questions a typically better asked on stackoverflow, as we try to keep this issue tracker focused on tracking bugs and issues.

Feel free to cross-link with this issue, and I will do my best to answer your SO question.

**Comment by Leryan** [comment]
Thanks for your answer, you're right, I opened a topic here: http://stackoverflow.com/questions/29187681/ember-ember-cli-impossible-url-fetched-while-routing
