### ISSUE TITLE
Remove __test__ token in blueprints and replace it with __name__-test

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3600]
Since [this commit](https://github.com/ember-cli/ember-cli/commit/6623c3c1937a3a4b466e37cfc0c398ed713d071e) test blueprints are generated in the same structure as the blueprint they're generated with, so there is no longer a need to specify a `__test__` token. We can use the `__name__`  token for tests generated in both basic and pod structures.

The fix would be to simply remove the `__test__` token, and replace any instance of it with `__name__ + '-test'` (or rename/git mv `__test__.js` to `__name__-test.js` for the file paths).

**Comment by rwjblue** [comment]
We need to make sure that we still support both though, since there are a number of projects that override these blueprints that we do not want to break...

**Comment by trabus** [comment]
@rwjblue good point. We should definitely leave it in for backward compatibility, though at some point we may want to phase it out with a deprecation warning. It's easy enough to add the token to the overridden blueprint, or change to use the preferred style.

**Comment by rwjblue** [comment]
I'm totally fine with deprecating once we remove the need internally, I think we could ship one version with the deprecation then remove support. That should give addons like ember-cli-mocha and ember-cli-coffeescript enough time to update without having to rush.

**Comment by trabus** [comment]
I'll gladly search for and make PRs on repos that use the `__test__` token.  :)

**Comment by stefanpenner** [comment]
:+1:
