### ISSUE TITLE
Bug in default acceptance tests blueprints

### ISSUE THREAD

**Issue by Ferdev** [ember-cli/ember-cli#3602]
Hi all,

I don't know if it's my setup but I just find out default acceptance tests created by ember-cli's generator doesn't work.

My environment:

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.2
    BuildVersion:	14C1510
    $ ember -v
    version: 0.2.0
    node: 0.12.0
    npm: 2.7.0

I've created an empty app to help you replicate the bug:

 https://github.com/Ferdev/ember-cli-acceptance-tests-bug

Steps I followed to create the app with the empty acceptance test:

    $ ember new acceptance-tests-bug
    ...
    $ cd acceptance-tests-bug
    $ ember g acceptance-test index

Then, just calling `ember test` shows the error:

    not ok 1 PhantomJS 1.9 - Acceptance: Index: visiting /index
        ---
            actual: >
                null
            message: >
                Died on test #1     at http://localhost:7357/assets/test-support.js:2535
                    at http://localhost:7357/assets/acceptance-tests-bug.js:146
                    at http://localhost:7357/assets/vendor.js:150
                    at tryFinally (http://localhost:7357/assets/vendor.js:30)
                    at http://localhost:7357/assets/vendor.js:156
                    at http://localhost:7357/assets/test-loader.js:29
                    at http://localhost:7357/assets/test-loader.js:21
                    at http://localhost:7357/assets/test-loader.js:40
                    at http://localhost:7357/assets/test-support.js:5301: /index
            Log: >
        ...
    ok 2 PhantomJS 1.9 - JSHint - acceptance: acceptance/index-test.js should pass jshint
    ok 3 PhantomJS 1.9 - JSHint - .: app.js should pass jshint
    ok 4 PhantomJS 1.9 - JSHint - helpers: helpers/resolver.js should pass jshint
    ok 5 PhantomJS 1.9 - JSHint - helpers: helpers/start-app.js should pass jshint
    ok 6 PhantomJS 1.9 - JSHint - .: router.js should pass jshint
    ok 7 PhantomJS 1.9 - JSHint - .: test-helper.js should pass jshint
    
    1..7
    # tests 7
    # pass  6
    # fail  1

I've been looking in the issues list but haven't been able to find any related bugs. Any hints would be greatly appreciated :)

Thanks for the hard work!

**Comment by twokul** [comment]
@Ferdev acceptance test blueprint [uses](https://github.com/ember-cli/ember-cli/blob/master/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js#L21) test name as a route name. In your test app, you don't have a route with a path `index`. That's why `visit('/index');` fails with `UnrecognizedURLError`. If you change it to `/`, it should work fine.

**Comment by Ferdev** [comment]
Wow, sorry a lot for such a big mistake. Yes, what you say makes total sense. Anyway, how's that I didn't get he UnrecognizableURLError in my tests output?

Thanks for your time, @twokul

**Comment by stefanpenner** [comment]
I think a bug in ember that has since been fixed

**Comment by Ferdev** [comment]
Thanks for letting me know, @stefanpenner
