### ISSUE TITLE
Separate fingerprinting and asset path prepending.

### ISSUE THREAD

**Issue by mariusz360** [ember-cli/ember-cli#3605]
Currently, you can only prepend to an asset if you enable fingerprinting. My thinking is that these should be separate concepts.

I'm running into trouble setting up a development environment for my EmberCLI + Rails app using the process from "Lightning Fast Deployments". My local index.html is in Redis, and it references the assets in the public/my_app/ folder of my rails app. In the script I use to start my dev environment, I have 

`ember build --environment development --output-path $RAILS_APP_PATH/public/my_app --watch`

and this updates the assets in my rails public folder whenever my frontend app is changed. However, I want the assets to be nested under the public/my_app folder so its cleaner and I can easily .gitignore it. To get this, I need to prepend the assets with "my_app/". However, if I want to prepend, I need to enable fingerprinting. After enabling fingerprinting, the index.html file in Redis won't be aware of any asset changes and my app will break because it references old fingerprinted files.

Is it possible to separate fingerprinting from prepending? Any suggestions on alternative development setups would be helpful as well!

**Comment by mariusz360** [comment]
A workaround for Rails:

1. Create a folder `app/assets/homepage_ember_app`.
2. Add the folder's assets to Rails assets path: 
  ```ruby
   # config/initializers/assets.rb
   if Rails.env.development?
     Rails.application.config.assets.paths << Rails.root.join('app', 'assets', 'homepage_ember_app', 'assets')
   end
  ```

3. Start ember build with the updated path:
  ```
ember build --environment development --output-path $RAILS_APP_PATH/app/assets/homepage_ember_app --watch
  ```

**Comment by stefanpenner** [comment]
so this is because we use brococli-asset-rev to do the pre-pending. But it would seem we should still use it when we don't finger print, just disable the fingerprinting.

**Comment by briangonzalez** [comment]
FYI: https://github.com/rickharrison/broccoli-asset-rev/issues/59

**Comment by stefanpenner** [comment]
seems to be specific to asset-rev, should be handled on that side of things.
