### ISSUE TITLE
ember server only available with internetconnection!?

### ISSUE THREAD

**Issue by svox1** [ember-cli/ember-cli#3606]
Hi,

if I disable my wlan and try:
`ember server`

I get this error:
```
version: 0.2.0
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND registry.npmjs.org
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```
Is it not possible to work with my local server when Iam offline or is this a bug?

**Comment by rwjblue** [comment]
It was a bug in 0.2.0, it's fixed on master and will be released in 0.2.1 soonish.

**Comment by svox1** [comment]
Thx again for the quick reponse! :+1:

**Comment by stefanpenner** [comment]
TL;DR this is ember-cli checking to see if it needs an update. And as @rwjblue mentioned, it is fixed on master.
