### ISSUE TITLE
Generated initializer test isn't useful

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#3609]
Initializer test doesn't load the application, so if the initializer uses any types (in my case I'm injecting models into the store) it fails to resolve them.

I ended up using an acceptance test instead which does generate useful boilerplate.

**Comment by stefanpenner** [comment]
the generated initializer test is primarly focused on testing unit level concerns. Likely most initializers don't have much algorithmic complexity so yes the unit level tests are likely pretty useless.

I do like the idea of generating an acceptance level test though...

**Comment by Twinkletoes** [comment]
The acceptance boilerplate worked perfectly for my example.
1. start app (runs all initializers)
2. find in the store and see if correct models are in there

This would mean that we'd just have to modify the initializer generator to build the same boilerplate as the acceptance test. Simple copy-paste modify. Would you like a PR?

**Comment by Twinkletoes** [comment]
In the general case, an initializer test should just check the state of the application, possibly using the container to check that dependencies have been injected etc.

So we should make the application and the container available to the test.

**Comment by stefanpenner** [comment]
it should not expose the container, as it is an internal detail not to be exposed. rather the entity the injection was performed on in it natural setting.

I actually believe this falls into the integration testing last, we don't really have properly fleshed out yet.

**Comment by Twinkletoes** [comment]
Say you were testing an initialiser that does an application.inject.
What would the test code look like?

My initial guess of pseudo code would be:

Create a (eg) LoginController using an import.
Assert the controller.myservice property is not null.

In this case no container is required.

Would that work?

**Comment by stefanpenner** [comment]
maybe the container is handy. I would prefer it if we could hide that implementation detail but maybe that is  pre-mature, until we land some nice test helper for this.

**Comment by stefanpenner** [comment]
to test actual injections, the following (Assuming integration: true is implemented) may look like

```js
moduleFor('server:apple', {
  integration: true
});

test("server:apple has its injection: ", function(assert) {
  assert.ok(this.subject().thingThatWasInjected);
});
```

this though, only tests 1 entity, but likely the level of test something like DI injection really wants to live at.

**Comment by Twinkletoes** [comment]
The test I wrote was

```
import Ember from 'ember';
import {
  module,
  test
} from 'qunit';
import startApp from 'insm-ui/tests/helpers/start-app';

var application;

module('Acceptance: BaseTemplateInitialize', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('Image template has been added to store', function(assert) {
  var store = application.__container__.lookup('store:main');

  var templates = store.all('template')
                  .toArray()
                  .filterProperty('displayName', 'Image');

  assert.equal(templates.length, 1);
});
```

I don't like the `application.__container__` part. Should I instead use `moduleFor('store:main')`?

**Comment by stefanpenner** [comment]
i believe my above example, if `integration` or maybe we need a new flag `app: true` would be the ideal solution.

```js
import Ember from 'ember';
import { test } from 'qunit';
import { moduleFor  } from 'ember-qunit';

moduleFor('store:main, 'Acceptance: BaseTemplateInitialize', {
  app: true // or something like this, basically do the start/App crap behind the scenes
});

test('Image template has been added to store', function(assert) {
  var templates = this.subject().all('template')
                  .toArray()
                  .filterProperty('displayName', 'Image');

  assert.equal(templates.length, 1);
});
```

**Comment by Twinkletoes** [comment]
Rewriting my test in this fashion I get an error:

```
import Ember from 'ember';
import {
  moduleFor,
  test
} from 'ember-qunit';

import startApp from 'insm-ui/tests/helpers/start-app';

var application = null;

moduleFor('store:main', 'Acceptance: BaseTemplateInitialize', {
  integration: true,
  
// beforeEach/afterEach to be replaced by app: true later
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }

});

test('Image template has been added to store', function(assert) {
  var store = this.subject();

  var templates = store.all('template')
                  .toArray()
                  .filterProperty('displayName', 'Image');

  assert.equal(templates.length, 1);
});
```

I get an error: 

```
Died on test #1     at Object.test (http://localhost:7357/assets/test-support.js:1712:11)
    at http://localhost:7357/assets/insm-ui.js:13301:15
    at mod.state (http://localhost:7357/assets/vendor.js:150:29)
    at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
    at requireModule (http://localhost:7357/assets/vendor.js:148:5)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18): Cannot read property 'create' of undefined@ 54 ms
Source: 	
TypeError: Cannot read property 'create' of undefined
    at exports.default.klassy.Klass.extend.defaultSubject (http://localhost:7357/assets/test-support.js:2199:21)
    at Object.context.(anonymous function) [as subject] (http://localhost:7357/assets/test-support.js:2219:41)
    at Object.<anonymous> (http://localhost:7357/assets/insm-ui.js:13302:22)
    at Object.wrapper (http://localhost:7357/assets/test-support.js:1700:29)
    at Object.Test.run (http://localhost:7357/assets/test-support.js:3329:28)
    at http://localhost:7357/assets/test-support.js:3458:11
    at process (http://localhost:7357/assets/test-support.js:3017:24)
    at begin (http://localhost:7357/assets/test-support.js:3062:2)
    at http://localhost:7357/assets/test-support.js:3078:4
```

**Comment by stefanpenner** [comment]
> Rewriting my test in this fashion I get an error:

yes, the above is a proposal

**Comment by Twinkletoes** [comment]
If you look at my code, I've replaced 'app:true' with the startApp/destroy code that was in my acceptance test before. I understood that app:true was a proposal. If we can make this work without it then I can create a PR

**Comment by stefanpenner** [comment]
in your example, you have created 2 different containers, one manually with startApp and one internally with integration: true, and they have diverged.

**Comment by Twinkletoes** [comment]
Aha! of course. So how does a controller test work - does that not create an application if `integration:true` is added? Why when I take out the startApp etc does the test still fail with the same error?

**Comment by stefanpenner** [comment]
@Twinkletoes it sets up an integrated container, but it doesn't currently include booting the app and running initializers. https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module.js#L208-L224

**Comment by Twinkletoes** [comment]
Ah ok. So it feels to me like an integration test should run in a fully booted application. What's the downside of doing that (other than speed)

**Comment by stefanpenner** [comment]
> What's the downside of doing that (other than speed)

I think internally it can be a fully booted application, but we still want to ensure focus on internals and not the entire app. Acceptance you are focusing out-side in, so the app is front and center.

**Comment by Twinkletoes** [comment]
so we could always create a booted application when `integration` is `true` or we could have a second param called
`bootApp` or `runInitializers` or `app` which causes `_setupIntegratedContainer` to also boot the application.

If there is no downside to always creating the booted application then that would be most easy to work with as a test developer. Alternatively my vote is for one of `bootApp` or `runInitializers` to cause the app to be booted.

**Comment by stefanpenner** [comment]
> If there is no downside to always creating the booted application then that would be most easy to work with as a test developer. Alternatively my vote is for one of bootApp or runInitializers to cause the app to be booted.

ya, i think it might be fine, would like @dgeb and @rwjblue's thoughts

**Comment by stefanpenner** [comment]
thoughts here should be fleshed out and presented to: https://github.com/switchfly/ember-test-helpers/ which is the repo for our test helpers
