### ISSUE TITLE
[0.2.0]path incorrect when generating components

### ISSUE THREAD

**Issue by hxlniada** [ember-cli/ember-cli#3610]
![image](https://cloud.githubusercontent.com/assets/3838586/6783797/c34e3b26-d1b6-11e4-8cfe-f294873be0e9.png)

**Comment by stefanpenner** [comment]
I believe this is fixed on master.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/3515

**Comment by hxlniada** [comment]
sorry, I didn't notice.
