### ISSUE TITLE
Paths printed in console not correct on Windows

### ISSUE THREAD

**Issue by jbrown** [ember-cli/ember-cli#3613]
![paths](https://cloud.githubusercontent.com/assets/47560/6787672/b262bd9c-d16a-11e4-891b-a019f6b14414.PNG)

**Comment by stefanpenner** [comment]
@trabus interest in sorting this one out?

**Comment by jbrown** [comment]
Happy to submit a PR if you can give me some direction.

**Comment by trabus** [comment]
@jbrown does this appear to be the case with all pod based blueprints?

**Comment by jbrown** [comment]
@trabus My podModulePrefix is standard `'appname/pods'` and yes it seems to happen on the pod based blueprints. FWIW, I didn't try them all, just some common ones like model, route, and component.

![paths2](https://cloud.githubusercontent.com/assets/47560/6789481/f537bfbc-d176-11e4-95ed-e15a9d4b441a.PNG)

**Comment by trabus** [comment]
@jbrown when you run without the --dry-run flag, does it actually generate into the proper location?

Basically, it seems like something is happening where the [displayName](https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L580) is getting set with a mix of `path.join` and string replacement, but I'm not exactly sure how this is happening on windows.

**Comment by jbrown** [comment]
@trabus It's generating them into the proper locations.

**Comment by swelham** [comment]
@jbrown are you just referring to the backslash in the path name?

If so I have literally just fixed this for me locally, so can submit a PR if that will solve this issue.

**Comment by stefanpenner** [comment]
`path.normalize` to the path before we print it to the console is likely sufficient

**Comment by jbrown** [comment]
@swelham Yes

**Comment by swelham** [comment]
cool, I will find some time and put in a PR.

**Comment by jbrown** [comment]
@swelham Thanks buddy, much appreciated! :+1:
