### ISSUE TITLE
[Proposal] Addon options

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3626]
Doing something similar to what Yeoman does would be awesome.

![from yeoman](http://yeoman.io/assets/img/codelab/image_8.5a17.png)

Basically exposing some of those cli attributes as questions, and being able to add additional addons/settings/files based on user's answers.

Like Less, Bootstrap, FontAwesome, etc..

This would also make addons much more powerful, since they can ask the user critical questions, and not always assume. This would also make ember-cli more powerful, and as we draw closer to a core cli, these features will be more important for wider adoption.

**Comment by abuiles** [comment]
@knownasilya can you cross-post please to https://github.com/ember-cli/rfcs? thanks!

**Comment by knownasilya** [comment]
@abuiles felt like that was the wrong place, since I was not writing up exactly how it works, why, etc.. But, I'll do that.

**Comment by abuiles** [comment]
@knownasilya we can start with the idea and flesh out the details there, once we agree on something you can go ahead with a PR :)

**Comment by knownasilya** [comment]
https://github.com/ember-cli/rfcs/pull/7
