### ISSUE TITLE
Asset fingerprinting causes Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by craigteegarden** [ember-cli/ember-cli#3627]
One of the css files in our project is named `ie.css`, and when it is fingerprinted and the filename is replaced in the various source files, it seems to be incorrectly replaced in some parts of the `vendor.js` file.

When running the minified, production build in Chrome I get the error:

```
Uncaught SyntaxError: Unexpected token ILLEGAL
```

Firefox gives a slightly more helpful message:

```
SyntaxError: identifier starts immediately after numeric literal  vendor-e8428f169f3b87e0d29fb6a730f7778a.js:1:10382
```

which shows code that looks like this:

```
r!==n&&(e[n]=o,delete e[r]),a=ie-694e56ccaf670ce486403b878409183c.cssHooks[n],a&&"expand"in a)
```

You can obviously see the fingerprinted filename in the js source. This file shouldn't be referenced in `vendor.js`, so it appears that the asset fingerprinting step is matching js source and replacing it with the fingerprinted filename and causing the syntax error.

I made a sample repository based on ember-cli 0.2.1 where the only addition is the single css file. Building it with `environment=production` will show the error.

https://github.com/craigteegarden/ember-cli-fingerprint-breaks-js-files

Renaming the file to something less-likely to be found in the js source works (like `awesome-fixes-ie.css`), but this situation is very frustrating to figure out and seems like it should be fixed if possible.

**Comment by stefanpenner** [comment]
wow thats seems crazy

**Comment by craigteegarden** [comment]
oops, wrong button

**Comment by stefanpenner** [comment]
will reopen if this is still an issue (with a repro on latest)
