### ISSUE TITLE
move postprocessTree('css') after merge with vendor styles

### ISSUE THREAD

**Issue by jschilli** [ember-cli/ember-cli#3628]
currently postprocessTree is being called after preprocessing app styles only

to make universally useful it should be called with the merged vendor + app styles tree.

This causes an issue with ember-cli-concat (https://github.com/sir-dunxalot/ember-cli-concat/issues/13) which itself was the result of https://github.com/ember-cli/ember-cli/pull/3581

This would also enable css minification to become an addon iso core

working on PR

**Comment by rwjblue** [comment]
Makes sense.  I agree that postprocessTree should be all css/styles (not just app).
