### ISSUE TITLE
[documentation] Add a reminder about the dash in ember component names

### ISSUE THREAD

**Issue by bartocc** [ember-cli/ember-cli#3632]
Someone following the [DEVELOPING ADDONS AND BLUEPRINTS](http://www.ember-cli.com/#developing-addons-and-blueprints) part on the ember-cli website is not reminded that ember component names must contain a dash in their name.

This info is present in a note on the top of the [DEFINING A COMPONENT](http://emberjs.com/guides/components/defining-a-component/) page on the emberjs.com website and repeating it on the ember-cli website could help avoid mistakes

**Comment by stefanpenner** [comment]
we are currently pushing to remove ember.js related docs from ember-cli.com rather having emberjs.com's docs be ember-cli compliant.

@joostdevries is helping push that forward.

**Comment by stefanpenner** [comment]
i think the guides push superseeds this https://github.com/emberjs/guides/issues/9
