### ISSUE TITLE
broccoli builder does not clean up after running test-server task

### ISSUE THREAD

**Issue by ragiragi** [ember-cli/ember-cli#3635]
```shell
$ ember test -s

# press q to quit testem

$ ls tmp/

#  so many files are listed...
```

`process.exit()` is called when exit testem.
https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/test-server.js#L16

But cleaning up function is not occurred on process exit.
https://github.com/ember-cli/ember-cli/commit/85a4782b555f9d51bf0457f073cda5e3b2ca7e4a#diff-53c8b5d6578c6f2fb2869c4d31bdc3a1L31
https://github.com/broccolijs/broccoli/issues/210

**Comment by stefanpenner** [comment]
> process.exit() is called when exit testem.
> https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/test-server.js#L16

correct, this is pre-mature. This is known, just no-one has had a chance to resolve this.

**Comment by stefanpenner** [comment]
fixed
