### ISSUE TITLE
Ubuntu 14.04 & watchman - Inotify limit too low.

### ISSUE THREAD

**Issue by jimbeaudoin** [ember-cli/ember-cli#3638]
Ok, Live Reload is not working with Watchman under Ubuntu 14.04

Maybe it's because I work with an Encrypted Hard Drive?

If I remove Watchman, it's working.

**Comment by stefanpenner** [comment]
> Maybe it's because I work with an Encrypted Hard Drive?

potentially, also running ember-cli's tmp dir on an encrypted drive will result in sub-optimal builds, so be 
weary.

You can also force the node watcher by doing:

```
ember s --watcher node
```

if the above works, then this is an issue that must be fixed on the watchman side.

**Comment by jimbeaudoin** [comment]
Yes, NodeWatcher work well. I'm going to check/open an issue in the facebook/watchman repo.

Thanks and Good Evening.

**Comment by stefanpenner** [comment]
@jimbeaudoin please cross-link

**Comment by jimbeaudoin** [comment]
https://github.com/ember-cli/ember-cli#problems 
https://github.com/ember-cli/ember-cli/issues/1054

I think this is related to my problem with watchman. Anyway I don't really like low level tool like watchman. I don't like when something mess with my filesystem.

I do not like that command!
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by jimbeaudoin** [comment]
I'm sorry if I'm not really helpful. You have to understand how much I loose when I took hours to solve simple problem like this. I do not have a lot of money, I eat ramens, I put all my energy & time into my company. For me, an hour is like a day. I need to put bread on my table. When the time will come I will be really happy to share and help others, but for now I must survive.

**Comment by jimbeaudoin** [comment]
By the way, I am in the process of learning english.

**Comment by jimbeaudoin** [comment]
If you want, I can make tests. I'm ready to help you but I don't like the above command, Sry but like I said, NodeWatcher is working good and I'm good with that to start learning ember.

**Comment by stefanpenner** [comment]
@jimbeaudoin ya, it would be lovely is OSX didn't ship a broken file watcher :(

**Comment by jimbeaudoin** [comment]
I'm going to re-open this issue and change the title for a better one. The workaround seem to be the thing to do but I'm going to work on this problem. Because the default for `/proc/sys/fs/inotify/max_user_watches` is `8192` on my system. I do not want to put `524288`. The gap is HUGE and I think it can mess with other part of my system (like memory) if I change this for a too high number.

http://stackoverflow.com/a/535796
http://www.linuxjournal.com/article/8478
http://www.monodevelop.com/documentation/inotify-watches-limit/

MonoDevelop use `16384`

**Comment by jimbeaudoin** [comment]
Ok in my opinion the number `524288` is too high. You are telling your system to make available 524288 watch handles. I test with `16384` and it work. It seem to me that this number is a more reasonable number. 

I use this command to make watchman work:
```sh 
echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by stefanpenner** [comment]
then this is likely a duplicate of https://github.com/ember-cli/ember-cli/issues/2643 when using watchman, we could watch many less trees then if we use node-watcher of similar.

**Comment by jimbeaudoin** [comment]
I suggest a command like `sudo ember setup-linux` who get input from the user but with suggested values like the Inotify. Because on Ubuntu the limit is too low by default for this kind of work and you cannot change this value without being root.

or

We can take example on this project for the documentation and explain why:
http://www.monodevelop.com/documentation/inotify-watches-limit/

Because this is not really a problem with ember-cli or watchman. It's only this settings is too low for a dev-box by default.

**Comment by stefanpenner** [comment]
@jimbeaudoin this is already present in our readme https://github.com/ember-cli/ember-cli#problems

**Comment by jimbeaudoin** [comment]
Ok, but this not an ember-cli problem in my opinion. It's only this settings is too low for a dev-box by default on Ubuntu.

**Comment by stefanpenner** [comment]
@jimbeaudoin yes correct, but we are unlikely to get ubuntu to fix, so many we can provide a script as you suggested to auto-correct.

**Comment by jimbeaudoin** [comment]
:+1:

**Comment by jimbeaudoin** [comment]
@stefanpenner But we should test the number before. I'm going to work with this setup `fs.inotify.max_user_watches = 16384` for a day or two and Give you my feedback here.

**Comment by jimbeaudoin** [comment]
> so many we can provide a script as you suggested to auto-correct.

https://github.com/felixrieseberg/ember-cli-windows

This project is cool & we should have the same thing for Linux.

**What this addon should do:**
- [ ] Update `fs.inotify.max_user_watches` to a decent number  
I use `16384` right now without problems (default: `8192`, README: `524288`)  
`echo fs.inotify.max_user_watches=16384 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`  
*To know more about Inotify:*  
http://www.linuxjournal.com/article/8478

Linux + Ember Users Around Here? Any Suggestions for a Linux Addon?

**Comment by jimbeaudoin** [comment]
Issue Closed

1. This is not an ember-cli issue
2. This is written in the README https://github.com/ember-cli/ember-cli#problems
3. A Linux Programmer is aware of things like that & he should know how to do research on the subject.

I still think the suggested value is too high because I use `16384` without problems but you know, my opinion & nobody listen to the new guy! :smile:

**Comment by stefanpenner** [comment]
> I still think the suggested value is too high because I use 16384 without problems but you know, my opinion & nobody listen to the new guy!

you are likely very correct
