### ISSUE TITLE
Command help broken by ember-cli-sass

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#3644]
This is a funny one:

```
$ ember --help

  Wrapper around libsass
```

That is all the output I get when I try to access the help.

It happens to be a brand new addon, and the only extra dependency in the `package.json` is:
```
"ember-cli-sass": "^3.2.1",
```

Uninstalling the addon make everything back to normal. I reported it here because, even if it's an error in the addon, ember-cli's very basic commands should be broken by 3rd party stuff.

**Comment by mkwallace** [comment]
I'm seeing this error as well. If I have some time in the near future, I'll look into it and try to confirm/deny that it seems to be caused by the ember-cli-sass addon, as cibernox reported.

**Comment by stefanpenner** [comment]
will reopen if a reproduction can be provided
