### ISSUE TITLE
Ember generate multiple addon blueprints 

### ISSUE THREAD

**Issue by offirgolan** [ember-cli/ember-cli#3650]
Running the following command:

```
ember g addon1 addon2
```
Only runs the generator for addon1. Functionality wise, it should run both addon1 and addon2 generator.

**Comment by stefanpenner** [comment]
+1

**Comment by swelham** [comment]
I have had a go at this, really in need of some feedback on it #3724

**Comment by stefanpenner** [comment]
Doesn't seem like on anyones critical path
