### ISSUE TITLE
allow upgrade with ember init without overwriting all dependencies installed to a project using ember install

### ISSUE THREAD

**Issue by justin-hackin** [ember-cli/ember-cli#3651]
It seems this could be easily achieved by comment-delimiting the section of user installed packages.  Apparently there used to be a feature allowing edit with 'e' after choosing 'd' for diff but this seems to not work in latest 0.21 upgrade process

**Comment by stefanpenner** [comment]
@justin-hackin elaborate on "not working"

**Comment by igorsantos07** [comment]
There's is no "edit" option on the diff during upgrades anymore.

**Comment by igorsantos07** [comment]
Here's a sample of the issue:
![selecao_011](https://cloud.githubusercontent.com/assets/532299/7671806/c6234e72-fcb3-11e4-80d7-0b142e24b6a3.jpg)

**Comment by stefanpenner** [comment]
There is an edit option if you have $EDITOR set.

Unfortunately comments are not valid json, and npm orders alphabetically. So I am unsure how to proceed

**Comment by igorsantos07** [comment]
A suggestion for organizing the dependency files would be reading the each of those JSON files, adding/updating dependencies programatically on that structure, and then re-writing the new structure to the files. This way we would get updated dependencies without losing custom ones.

About other replaced files, such as `router.js`, `app.js` and `environment.js`:
Maybe there could be an option for "leave as conflicted" when asked what to do (yes replace, no replace, diff, conflict, help)? Then:
**A)** we could open the file in an editor later and merge manually
**B)** the tool would move the current file into a `.old` version, and we would do the merge as well
I think **A)** is better as it's more obvious on what's going on. Blindly ask for replacing seems a bad behaviour.

**Comment by stefanpenner** [comment]
Leave as conflicted seems ok. But it may cause issues as the second part of init is to do an npm install. Which fails horribly if the package.json is not well formed.

This should be transitioned to an rfc so the details can be nailed

**Comment by jimbeaudoin** [comment]
I think ember-cli should use 3 dependency file. One for the default `default_package.json`, one for the installed addon `addons_package.json` and one `package.json` for npm. `ember update` should only  use `default_package.json`. `ember install` should only use `addons_package.json` & merge it with `default_package.json` to create `package.json`. A the end of the `ember init` process, you can merge both `default_package.json` & `addons_package.json` to create a new `package.json` for npm without loosing anyting.

**Comment by stefanpenner** [comment]
@jimbeaudoin this sounds like many moving parts though.

**Comment by igorsantos07** [comment]
There's another issue @jimbeaudoin idea don't tackle: you're not thinking
outside of Emberland. A project dependencies will not always be only Ember
or addons. Look at my sample for instance.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by igorsantos07** [comment]
I'll write an RFC later and reference it here, with the suggestions better
organized :)

**Comment by Dynasty9** [comment]
:+1:  every time I upgrade I have to manually merge my dependancies with the changes to ember dependencies. If it just updated the ones that ember setup in the first place that would be preferable to me.

**Comment by wolfbiter** [comment]
+1

**Comment by crotwell** [comment]
Another possibility would be for "ember install xyz" to be save the fact that "xyz" was installed to a file, like ember_install.json. Then "ember init" could rerun "ember install xyz" after finishing the upgrade? At least then if I take the default to overwrite package.json, the replay of ember install will reinstall the xyz package and I won't have to do it manually?

This doesn't help if someone manually edits package.json, but at least if you go via "ember install" you are covered.

**Comment by stefanpenner** [comment]
this is quite complicated, if someone wants to flesh out a proposed solution. an RFC would be best

Otherwise we will just continue to incrementally reduce this pain.

**Comment by CHIEFnChowCombo** [comment]
How about ember just does what the rest of the javascript world does and maintain a list of it's own dependencies?

I spend hours each day trying to figure out if the transpile bugs in my app are caused by issues based on the dependencies that ember-cli wants you to install on their behalf.  Hint... they *always* are.

**Comment by stefanpenner** [comment]
> I spend hours each day trying to figure out if the transpile bugs in my app are caused by issues based on the dependencies that ember-cli wants you to install on their behalf. Hint... they always are.

This is a fine path of reasoning, improvements to the `init` and upgrade story should be explored as an RFC. These choices need to be fleshed out, once they are someone can implement. The current path is extremely naive, likely any more advanced merge strategy would be better.

**Comment by CHIEFnChowCombo** [comment]
Basically, I'm saying that `ember install` should go away entirely.  the blueprint stuff can all be handled via `postinstall` natively with npm.  That means ember.js would be it's own npm package, with it's own dependencies, and you could shed the need to install ember-cli globally, instead being able to use it locally within each project.

Right now, it's like once I start a project on my machine with ember-cli, I'm basically stuck with that version of cli, or I'm forced to refactor all the other ember projects on my machine to be compatible with the latest updates brought on by all the dependencies ember-cli installs.

The only command that should alter the `package.json` file directly should be `npm`.  You can get all the same ember-cli functionality you have now, without all the overhead and cross-cutting radioactivity.

I *was* working on an RFC to show how to use the `postinstall` feature, but I got moved onto other projects, and my focus will no longer be on working with Ember, and so I'm not going to commit to the time required to submit a proper RFC.

Let me know though if you'd like to discuss privately.

**Comment by stefanpenner** [comment]
> the blueprint stuff can all be handled via postinstall natively with npm.

this isn't true, initial install and secondary install are different.

> Right now, it's like once I start a project on my machine with ember-cli, I'm basically stuck with that version of cli, or I'm forced to refactor all the other ember projects on my machine to be compatible with the latest updates brought on by all the dependencies ember-cli installs.

haven't we already discussed this, ember-cli is resolved locally to the project. Isolated each project.

> The only command that should alter the package.json file directly should be npm

npm is the only command that alters package.json during `ember install`

> I was working on an RFC to show how to use the postinstall feature, but I got moved onto other projects, and my focus will no longer be on working with Ember, and so I'm not going to commit to the time required to submit a proper RFC.

Please take above above recommendation into account. We are also working to remove the need of postInstall like behavior, but exploring an improved installer that offers constraint based installation of ember-addons as peerDependencies (a gap NPM is intentionally leaving open for such custom implementations) There is an idea to allow optional resolving strategies but the NPM folk would prefer to see this in user-land first.

**Comment by stefanpenner** [comment]
Someone exploring an enhanced merged strategy for `ember init` or similar, would be very nice. Should be pretty easy, and will reap good wins.
