### ISSUE TITLE
Allow running an overridden blueprint

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli#3652]
I'm in the process of migrating my Global App to CLI.

I know the community doesn't like CoffeeScript, as everyone has made abundantly clear. However, we need to port our legacy codebase and tests over as CoffeeScript and start moving to ES2015 syntax over time.

It would be really great we could choose to run an overridden blueprint at the command line level. Consider this situation:
+ I'm porting over a Service I've already written tests for in CoffeeScript. In this case, I need to `ember g service foo` and have the CoffeeScript App and Test files to easily port my existing source code. In this case, the standard CLI workflow as it exists today works.

Here's another situation:
+ As I'm porting over my application, I realize I need a new mixin. Because the community doesn't like CoffeeScript, I'd like to write this as an ES2015 module. Currently, I have to copy a blueprint from the Ember-CLI repo and remove the local variables to get it working. It would be really great if I could say `ember g ember-cli:mixin new` instead of copy/pasting.

I looked through the source code and it doesn't look like this is available now, but it would be really handy.

**Comment by stefanpenner** [comment]
you can add your own blueprints that support coffee-script

**Comment by blimmer** [comment]
I definitely understand that the core team can't support CoffeeScript. What I'm asking about, specifically, is easily being able to call a blueprint defined in another add-on, that's overridden by an add-on.

In my case, `ember-cli` and `ember-cli-coffeescript` both provide blueprints for the base generators (mixin, route, controller, etc.). As we migrate our old Ember Global App over to Ember CLI, it's handy to be able to `ember g route` and have`ember-cli-coffeescript` handle the blueprint (as it does when installed).

However, there are new features that we'd like to start developing in JavaScript, as recommended by the community. As implemented today, since `ember-cli-coffeescript` overwrites the default ember-cli blueprints, I have to [flip a switch](https://github.com/kimroen/ember-cli-coffeescript/tree/v0.10.0#blueprints) every time in my configuration, which [short-circuits](https://github.com/kimroen/ember-cli-coffeescript/blob/v0.10.0/index.js#L26) the `blueprintsPath` in `ember-cli-coffeescript` which makes default ember-cli blueprints available (since the add-on is no longer overriding the blueprint definition).

What I'm proposing is having an easier way to run a different add-on's blueprint from the command line. For instance, instead of flipping the switch in the configuration file, it'd be great if I could leave `ember-cli-coffeescript` add-on in tact and tell `ember generate` that I want to run the blueprint from the base `ember-cli` package, instead of `ember-cli-coffeescript`'s overridden version.

I imagine this would be something like
```
ember generate ember-cli:route
```

This would force the `ember-cli` route blueprint to execute, instead of the overriden `ember-cli-coffeescript` route blueprint.

**Comment by stefanpenner** [comment]
Ah

**Comment by jimbeaudoin** [comment]
@blimmer take a look at this https://github.com/ember-cli/rfcs

**Comment by blimmer** [comment]
Thanks @jimbeaudoin , I opened an [RFC](https://github.com/ember-cli/rfcs/pull/10) on the issue.
