### ISSUE TITLE
`ember update` status is misleading

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#3653]
I have ember-cli 0.2.1 installed globally. But I also have a project with ember-cli 0.1.12 as its local dep. If I run `ember update` inside that project, it says:

```
version: 0.1.12
✓ You have the latest version of ember-cli (0.1.12).
```

Which is not true.

**Comment by rwjblue** [comment]
Ember update was completely broken until 0.2.1 :(

**Comment by stefanpenner** [comment]
It still has some bugs. Although it's better now.  Let's leave this open as a tracking but.

**Comment by stefanpenner** [comment]
this one is fixed, many other issues with update exist though.
