### ISSUE TITLE
Double "code deoptimized" warning for files exceeding 100KB

### ISSUE THREAD

**Issue by melnychuk** [ember-cli/ember-cli#3654]
Hi there. I have a fixtures file with mock data that exceeds 100 KB and whenever I run ember server, I get these warnings:

    Note: The code generator has deoptimised the styling of "app/models/item.js" as it exceeds the max of "100KB".
    Note: The code generator has deoptimised the styling of "app/models/item.js" as it exceeds the max of "100KB".

It seems like it's either trying to optimize the same file twice, or just gives you two warnings.

Might be that there's something with my setup:

ember-cli: 0.2.1
ember: 1.12.0-beta.1+canary.d346ebbb
platform: Windows 10 TP

**Comment by stefanpenner** [comment]
Can you provide a small example app that demonstrates this?  It would make it easier to track down the issue

**Comment by martypenner** [comment]
The message is coming from babel-core: https://github.com/babel/babel/blob/master/src/babel/messages.js#L22.

It occurs when `compact` is set to **auto** and the filesize exceeds 100KB. Not sure why it's trying to optimize twice, though.

**Comment by stefanpenner** [comment]
thats worth investigating.

**Comment by martypenner** [comment]
I can't repro on:
- ember-cli 0.2.3
- ember 1.11.3
- ember-data 1.0.0-beta.16.1

I've generated several hundred records and output them in a basic list. You can see the JSBin here:
http://jsbin.com/ribagi/2/edit?html,js,output

I receive one warning from babel, as expected. @melnychuk Does upgrading to ember-cli 0.2.3 solve the problem?

**Comment by melnychuk** [comment]
@martypenner I was getting the error from 0.2.3 as well... Unfortunately, I can't provide you with the data file I've used, since it contains company data.

**Comment by martypenner** [comment]
Can you share your Brocfile.js and package.json?

**Comment by melnychuk** [comment]
Sure thing!

bower.json:
```
{
  "name": "appname",
  "dependencies": {
    "jquery": "^2.1.3",
    "ember": "components/ember#canary",
    "ember-data": "components/ember-data#canary",
    "ember-resolver": "~0.1.15",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.1",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "~1.18.0",
    "moment": "~2.10.2",
    "ember-inflector": "~1.3.1",
    "jquery-masonry": "~3.3.0",
    "imagesloaded": "~3.1.8"
  },
  "resolutions": {
    "ember": "canary",
    "ember-data": "canary"
  }
}
```
package.json
```
{
  "name": "appname",
  "version": "0.0.0",
  "description": "Description",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "glob": "^5.0.5",
    "broccoli-asset-rev": "^2.0.3",
    "ember-cli": "0.2.3",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-flash": "^1.1.2",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-ic-ajax": "^0.1.2",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-less": "^1.3.2",
    "ember-cli-qunit": "0.3.11",
    "ember-cli-uglify": "1.0.1",
    "ember-cli-windows-addon": "^1.2.2",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-masonry-grid": "^0.4.1",
    "ember-truth-helpers": "0.0.5",
    "liquid-fire": "0.19.3"
  }
}
```

**Comment by martypenner** [comment]
Still not double-deoptimising for me. @melnychuk  As Stefan asked, could you create the smallest test case that reproduces your problem?

**Comment by melnychuk** [comment]
Interestingly, we've stripped a bunch of unnecessary fields from the file that was causing it, and now it only gives the warning once. File size used to be around 380 Kb and now it's only 110 or so. I wonder if there was some badly formatted string in that file that could've caused it. It was reproducible on all 5 dev. machines.

**Comment by martypenner** [comment]
Hmm. Out of curiosity, I added more fake data to my test fixtures to bring the file size up to 463KB and ran `ember serve` on Windows 10 Tech Preview. Still only one warning. Strange.

**Comment by kaungst** [comment]
May not help at all, but I was getting this error when I ran 'bower install moment -save' in the '<project>/app' directory. The fix for me was to delete the incorrectly generated bower_components directory(<project>/app/bower_components).

**Comment by momer** [comment]
@kaungst That was definitely the fix for me

**Comment by stefanpenner** [comment]
> May not help at all, but I was getting this error when I ran 'bower install moment -save' in the '/app' directory. The fix for me was to delete the incorrectly generated bower_components directory(/app/bower_components).

ah, how did that happen?
