### ISSUE TITLE
test failed with no clear reason when a utils test failed with a promise reject 

### ISSUE THREAD

**Issue by xudaiqing** [ember-cli/ember-cli#3656]
when a utils test failed with a promise reject, test output these information

    not ok 24 PhantomJS 1.9 - JSHint - utils: global failure
        ---
            actual: >
                null
            message: >
                123
            Log: >
    ...

it doesn't provide any information of which test cause the failure.

reproduce the problem:

ember generate util utility-test
replace test file with following code

    import utilityTest from '../../../utils/utility-test';
    import { module, test } from 'qunit';
    import ember from 'ember';
    
    module('utilityTest');
    
    // Replace this with your real tests.
    test('it works', function(assert) {
      var result = utilityTest();
      var res = new ember.RSVP.Promise(function(resolve,reject){
    		reject('123');
    	});
      assert.ok(result);
    });

run ember test

**Comment by stefanpenner** [comment]
You need to return res so qunit knows it's a promise and displays the rejection reason

**Comment by xudaiqing** [comment]
problem is this is the default behaviour when you generate a utility and if the utility rejected when input is undefined. this is the result. 
it's really confusing and force me to repoduce all the changes from last successful bit by bit to find the cause

**Comment by stefanpenner** [comment]
@xudaiqing yes, unfortunately that is likely an issue with QUnit itself or the reporter used by testem.

**Comment by xudaiqing** [comment]
looks like my first post have a bug. it's really assert.ok(res); not assert.ok(result);
so it should be 

    test('it works', function(assert) {
      var res = new ember.RSVP.Promise(function(resolve,reject){
           reject('123');
        });
      assert.ok(res);
    });

the result is same though

**Comment by xudaiqing** [comment]
also if same thing happen to a route test it will return enough information

import {
  moduleFor,
  test
} from 'ember-qunit';
import ember from 'ember';

moduleFor('route:index', {
  // Specify the other units that are required for this test.
  // needs: ['controller:foo']
});

test('it exists', function(assert) {
  var route = this.subject();
  var res = new ember.RSVP.Promise(function(resolve,reject){
       reject('123');
    });
  assert.ok(res);
});

the output is 

not ok 12 PhantomJS 1.9 - route:index: it exists
    ---
        actual: >
            null
        message: >
            123
        Log: >
    ...

**Comment by stefanpenner** [comment]
seems like a QUnit or testem issue, not sure we can do anything here. Will reopen if that is demonstrated to not be true.
