### ISSUE TITLE
`ember update`: when running `ember init` prompts an ember-cli version downgrade

### ISSUE THREAD

**Issue by wagenet** [ember-cli/ember-cli#3659]
![image](https://cloud.githubusercontent.com/assets/9835/6851074/f92da382-d399-11e4-855e-9142d54ed9bb.png)

As you can see, it's prompting me to downgrade to 0.2.0 but I just upgraded to 0.2.1. I'm wondering if this is some sort of race condition.

**Comment by stefanpenner** [comment]
yes its broken.

**Comment by knownasilya** [comment]
Also it doesn't upgrade the version of ember properly in bower.json.

**Comment by stefanpenner** [comment]
@wagenet `0.2.0` ember update is broken `0.2.3` is better, but still has some issues

**Comment by knownasilya** [comment]
@stefanpenner I used `ember update` from 0.2.2 to 0.2.3 and had both issues. When was it fixed?

**Comment by davewasmer** [comment]
Saw this upgrading from 0.2.3 to 0.2.4. After running `ember update` and confirming that I want to upgrade:

```sh
$ ember update
version: 0.2.3

A new version of ember-cli is available (0.2.4). To install it, type ember update.

A new version of ember-cli is available (0.2.4).
[?] Are you sure you want to update ember-cli? Yes
Updating ember-cli..  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

~ snip ... ~

├── markdown-it-terminal@0.0.2 (ansi-styles@2.0.1, cli-table@0.3.1, cardinal@0.5.0, lodash-node@3.8.0)
└── testem@0.8.3 (growl@1.8.1, styled_string@0.0.1, did_it_work@0.0.6, consolidate@0.12.1, charm@1.0.0, colors@1.1.0, xmldom@0.1.19, async@0.9.0, mustache@2.0.0, cross-spawn@0.2.9, commander@2.8.1, mkdirp@0.5.1, glob@5.0.6, backbone@1.2.0, fileset@0.1.5, npmlog@1.2.0, js-yaml@3.3.1, fireworm@0.6.6, tap@0.7.1, socket.io@1.3.5)
Updating ember-cli...

✓ ember-cli was successfully updated!
```

It then asked if I wanted to run `ember init`, which I did:

```sh
To complete the update, you need to run ember init in your project directory.
[?] Would you like to run ember init now? Yes
installing
[?] Overwrite package.json?
```

The diff of the package.json and bower.json changes looked like it was trying to `init` 0.2.3's blueprint rather than 0.2.4's:

```
# bower.json
+    "ember": "1.11.1",
-    "ember": "1.12.0-beta.1",

# package.json
+    "ember-cli": "0.2.3",
-    "ember-cli": "0.2.4",
```

During the middle of the init, I checked the actual, on-disk version of ember-cli:

```sh
$ grep version node_modules/ember-cli/package.json
  "version": "0.2.3",
```

There was no version printed out with the npm output from the first step where the new version was installed, but it seems like the package.json is updating to the new version but the actual module isn't.

**Comment by atomkirk** [comment]
Saw this upgrading from `0.2.5` to `0.2.6`. Sincere question, how come this isn't as simple as running `npm install` as part of, and at the end of `ember update`? Maybe you already are, but that's how I have to make this work. I run `ember update`, reject the offer to run `ember init` immediately after, run `npm install` first, then run `ember init` and it all works.

**Comment by stefanpenner** [comment]
Unsure. Haven't had time to investigate, maybe you should dig in and report back ;)

**Comment by stefanpenner** [comment]
ember upgrade is gone

**Comment by knownasilya** [comment]
Woot!
