### ISSUE TITLE
`ember update` name is misleading

### ISSUE THREAD

**Issue by wagenet** [ember-cli/ember-cli#3660]
It's updating ember-cli not ember itself. Maybe something like `ember update:cli`?

**Comment by stefanpenner** [comment]
+1

**Comment by rwjblue** [comment]
* `ember init` does not "initialize ember" either
* `ember build` does not build ember
* `ember generate *` does not generate Ember

The `ember` command is referring to Ember CLI in all cases, why call it out only for `update`?

**Comment by stefanpenner** [comment]
interestingly, when upgrading ember-cli you also do get the most recent ember that it was bundled with.

**Comment by jakehow** [comment]
Maybe `upgrade` vs `update`, I would expect `update` to do `init` for an existing project, which I am thinking is what @wagenet might be getting at.

**Comment by wagenet** [comment]
@rwjblue none of those options make sense, so it's logical to rule them out. But in this context update could logically refer either.

**Comment by rwjblue** [comment]
@wagenet - But `ember upgrade` does actually upgrade ember-cli and ember (iirc)...

**Comment by wagenet** [comment]
@rwjblue it seems like it might be nice to separate that, since you won't always update in tandem. Also, it would be nice to have a command to update beta or canary versions of ember. I guess it's ok if `update` does both together, but `update:cli` or `update:ember` could be nice.

**Comment by stefanpenner** [comment]
@wagenet you may be forgetting that upgrading ember-cli updates ember by way of reblueprinting. I believe this will always be the latest ember compatible with ember-cli.

**Comment by wagenet** [comment]
@stefanpenner good point. It seems like long term it would be nice if there was a way to split the two a bit more. I can definitely see someone wanting to upgrade one but not the other.

**Comment by stefanpenner** [comment]
> @stefanpenner good point. It seems like long term it would be nice if there was a way to split the two a bit more. I can definitely see someone wanting to upgrade one but not the other.

Ya, I think after we move everything from bower to npm, we will revisit that. `ember update` i think will continue to update your app to the most recent ember-cli version, and then try to sync it to the most recent blueprint.

**Comment by stefanpenner** [comment]
other issue is tracking this
