### ISSUE TITLE
Generate component in addon

### ISSUE THREAD

**Issue by BenjaminHorn** [ember-cli/ember-cli#3661]
I try to make an addon using ember-cli. Here it is step by step what I have done so far:

```
ember addon test-addon
cd test-addon
ember serve
```

now the server runs and on localhost:4200 I can see the test/dummy app's application hbs.
Its time to make some components for the addon:
```
ember g component my-form
```
In the tests/dummy/app/templates/application.hbs I added {{my-form}}

And now I'm getting the following js error:
*Uncaught Error: Could not find module test-addon/components/my-form imported from dummy/components/my-form*

Ember CLI version: 0.2.1

```Javascript

```

**Comment by trabus** [comment]
I'm currently working on documenting generating inside addons, I can look into this later today.

**Comment by BenjaminHorn** [comment]
Here is the same question on stackoverflow , with some extra information : http://stackoverflow.com/questions/29282148/ember-cli-generate-component-in-an-addon

**Comment by BenjaminHorn** [comment]
After restarting my computer this morning, it looks like it works as expected. Wired...

**Comment by trabus** [comment]
Was going to report last night that I couldn't replicate, but remembered that I was using master and not 0.2.1 :trollface:

Was going to revert and try again today, but never mind now! :)

Glad it's resolved for you, and thanks for reporting back!

**Comment by Propertyinsight** [comment]
I'm having the exact same issue using Ember CLI 0.2.2.  I'm using pods and the component seems to be having trouble importing the template:

```
import layout from './template';
```

Here's the error:

```
Uncaught Error: Could not find module `ember-cli-collapsible-navbar/components/collapsible-navbar/template` imported from `ember-cli-collapsible-navbar/components/collapsible-navbar/component`
```

**Comment by johnnyoshika** [comment]
I'm having the exact same issue using Ember CLI 0.2.2.  I'm using pods and the component seems to be having trouble importing the template:

```
import layout from './template';
```

Here's the error:

```
Uncaught Error: Could not find module `ember-cli-collapsible-navbar/components/collapsible-navbar/template` imported from `ember-cli-collapsible-navbar/components/collapsible-navbar/component`
```

**Comment by johnnyoshika** [comment]
It turns out that my problem was that I was using pods (`"usePods":true` in .ember-cli file).  Once I reverted to not use pods, it worked just fine.

**Comment by trabus** [comment]
Yeah, unfortunately templates in pod structure are not picked up inside addons currently. There is a story to fix that [here](https://github.com/ember-cli/ember-cli/issues/3586).

**Comment by rajzshkr** [comment]
I installed **ember-cli-htmlbars** as npm dependencies, earlier it is installed as dev-dependencies, My issue got resolved.
