### ISSUE TITLE
 npm install -g ember-cli Fails

### ISSUE THREAD

**Issue by gap** [ember-cli/ember-cli#3665]
I'm trying to install on Digital Ocean.  I've tried under ubuntu and centos.  The following command gives the following error.

npm install -g ember-cli
[trimmed message...]

npm http 304 https://registry.npmjs.org/markdown-it-terminal/0.0.1
npm http 304 https://registry.npmjs.org/broccoli-es6modules
npm ERR! Error: No compatible version found: exit@'^0.1.2'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-123.8.1.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
npm ERR! cwd /usr/src
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/src/npm-debug.log
npm ERR! not ok code 0

**Comment by stefanpenner** [comment]
both node and npm versions are quite old. I recommend upgrading to at-least, `npm` version `2.7.x` and that will fix you problem.

**Comment by gap** [comment]
Thanks!  That worked.  I used 

npm update npm -g
