### ISSUE TITLE
Opt-in to unnecessary features during `init` or `new`?

### ISSUE THREAD

**Issue by blesh** [ember-cli/ember-cli#3667]
Currently whenever I create a new Ember project or (previously) when I upgrade a project with `init`, I have to do the following *everytime*:

```sh
ember new project
npm uninstall -D ember-data
npm uninstall -D ember-cli-content-security-policy
```

I only see this growing over time.

I understand that the powers that be want to push ember-data or content-security-policy on us as a "best practice", but it's sort of like buying a PC with some "office suite" and "super anti-virus" installed. I understand that someone is trying to help me, but I don't like it and don't want it.

If there are a certain set of addons that you *really, really* think I should use, that aren't critical, why not ask? Like:

```sh
RECOMMENDED: Would you like to use ember-data? (more info: http://shorturlhere) [Yn]: 
RECOMMENDED: Would you like to use ember-cli-content-security-policy? (more info: http://shorturlhere) [Yn]: 
```

They can even default to "yes" and give links with information about how someone might benefit from them.

Lazy noobies will likely just <kbd>ENTER</kbd> <kbd>ENTER</kbd> <kbd>ENTER</kbd> their way through them and you'll get your desired result.

**Comment by abuiles** [comment]
Similar to https://github.com/ember-cli/rfcs/pull/7, we could also read this from `.ember-cli` so we don't ask the same thing all the time.

```
use-ember-data: false,
user-ember-cli-content-security-policy: true
```

**Comment by rwjblue** [comment]
This isn't a bug per se, but a general annoyance to you (understandably so), and we like to keep the issue tracker for tracking things that are broken.

Seems like this might be a proposal, if it is please submit (with more details) to github.com/ember-cli/rfcs instead.

**Comment by stefanpenner** [comment]
seems like a blueprint has (or nearly) has the power to accomplish this

**Comment by abuiles** [comment]
Created the following RFC https://github.com/ember-cli/rfcs/pull/8

**Comment by stefanpenner** [comment]
continuing discussion on the RFC
