### ISSUE TITLE
render breaks with 'underscore_in_template_name' 

### ISSUE THREAD

**Issue by cameronlinden** [ember-cli/ember-cli#3668]
When I have an underscore in the name like `render 'tos_modal'` Ember doesn't find the file, even though `tos-modal` works. Please advise.

**Comment by btecu** [comment]
Follow naming conventions:
http://www.ember-cli.com/#naming-conventions

**Comment by abuiles** [comment]
@cameronlinden as suggested by @btecu you should follow the naming convention, try that and let us know if it fixes the problem.
