### ISSUE TITLE
Update breaking dependencies

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#3670]
The following dependencies can't be updated to the latest version because they break some tests:
- [ ] broccoli-clean-css
- [ ] core-object
- [ ] inquirer
- [x] lodash-node
- [x] markdown-it
- [x] markdown-it-terminal
- [x] nock

**Comment by stefanpenner** [comment]
> core-object

i suspect this one will be tricky, and a WIP exists: https://github.com/ember-cli/ember-cli/pull/3056

**Comment by rtm** [comment]
What tests do later versions of broccoli-clean-css cause to fail? I'm interested in using it (1.0.0) because it supports the new sourcemap feature in the latest version of clean-css.

**Comment by stefanpenner** [comment]
> What tests do later versions of broccoli-clean-css cause to fail? I'm interested in using it (1.0.0) because it supports the new sourcemap feature in the latest version of clean-css.

unsure, got time to look into it and report back.

**Comment by stefanpenner** [comment]
seems to have gone stale, if someone wants to help upgrade stale / outdated deps PR welcome :)
