### ISSUE TITLE
PhantomJS dependency

### ISSUE THREAD

**Issue by visheshjoshi** [ember-cli/ember-cli#3678]
Currently ember-cli doesn't have phantom.js as a dependency, and we need to install it separately. Is there a reason for that? 

What would it take to bundle phantom.js with ember-cli?

**Comment by stefanpenner** [comment]
it is unfortunate that the install instructions are 2 steps (after install npm), i wonder if we can mitigate this reasonably.

**Comment by rwjblue** [comment]
phantomjs isn't really required by ember-cli at all, if you do not need to use it for testing remove it from `testem.json`.

**Comment by stefanpenner** [comment]
@rwjblue although technically not required, I do suspect phantomjs (hopefully Phantomjs 2.0) is part of a healthy developer setup. Can we bundle to simplify further

**Comment by rwjblue** [comment]
There are a few CI environments that do not require Phantom for testing.  For example, CircleCI allows you to test with Chrome.

**Comment by rwjblue** [comment]
If we had phantom as a dep, I am unsure if testem would find it?  Perhaps @johanneswuerbach would know...

**Comment by johanneswuerbach** [comment]
When phantomjs is added to the generated project, testem should find it. Let me verify that this works as expected.

**Comment by runspired** [comment]
I think at a min the docs should be updated to clarify that it's not required, just recommended/easiest way to get up and running tests.  It being a perceived requirement seems to be causing some grumbling.

**Comment by stefanpenner** [comment]
@visheshjoshi any luck on those above questions?

**Comment by stefanpenner** [comment]
this has gone stale

**Comment by runspired** [comment]
@stefanpenner I also updated the docs around phantomjs a while back so it's less of an issue.

**Comment by stefanpenner** [comment]
> @stefanpenner I also updated the docs around phantomjs a while back so it's less of an issue.

thanks !
