### ISSUE TITLE
Watchman Never Shutdown on Linux

### ISSUE THREAD

**Issue by jimbeaudoin** [ember-cli/ember-cli#3689]
When I use the command `ember server` the watchman server start like it is supposed to. 

But when I stop the `ember server` with `ctrl+c`, the watchman server do not shutdown. 
I need to shutdown the server manually with the command `watchman shutdown-server` every time.

**Comment by stefanpenner** [comment]
Watchman is a persistent service that is shared between all consumers. This is expected behaviour

**Comment by jimbeaudoin** [comment]
Ok Thanks!
