### ISSUE TITLE
Accessing build options in setupPreprocessorRegistry

### ISSUE THREAD

**Issue by gpoitch** [ember-cli/ember-cli#3701]
I'm updating an addon to use the new `setupPreprocessorRegistry` hook.  The preprocessor needs to be configured with build options the user defines in their Brocfile.  However, this hook is called before `included` so it has no context of the `EmberApp` yet.

**Comment by stefanpenner** [comment]
yes this is borked.

**Comment by Turbo87** [comment]
@gdub22 @stefanpenner is this still an issue?

**Comment by stefanpenner** [comment]
I believe so.

**Comment by MiguelMadero** [comment]
Is this an option: https://github.com/runspired/ember-hammertime/blob/master/index.js#L35

**Comment by jrjohnson** [comment]
Just adding a note: this is still and issue in `3.0.0`. Workaround seems to be to calling it from `included` as in https://github.com/kimroen/ember-cli-coffeescript/blob/master/index.js#L43

**Comment by rwjblue** [comment]
This is fixed in https://github.com/ember-cli/ember-cli/pull/7059 (included in 2.14+ AFAICT): 

https://github.com/ember-cli/ember-cli/blob/eb544f2219148e1b5499d3d43a8196ff04a73bc0/lib/broccoli/ember-app.js#L142
