### ISSUE TITLE
should work gracefully without git installed

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3702]
http://discuss.emberjs.com/t/ember-cli-the-ramcat-way/7666/25?u=stefan
- [ ] bower explicitly depends on git --- we have plans to kill bower entirely, but lots of work is still left

**Comment by runspired** [comment]
Reference material for updating documentation: https://github.com/bower/bower#windows-users

**Comment by stefanpenner** [comment]
we are ever so close now.

**Comment by rwjblue** [comment]
We do not currently depend on `bower`, and it is only used for `ember install` or `ember new`.  

Closing this issue, but there will be a "death to bower" meta issue soon with more information.
