### ISSUE TITLE
`ember update` will detect new version, but not update to it till second try.

### ISSUE THREAD

**Issue by bravely** [ember-cli/ember-cli#3707]
Encountered this when checking for an update:

```
$ ember update
version: 0.2.1
0.2.2

✓ You have the latest version of ember-cli (0.2.1).
$ ember -v
version: 0.2.1

A new version of ember-cli is available (0.2.2). To install it, type ember update.
node: 1.4.3
npm: 2.7.3
$ ember update
ersion: 0.2.1

A new version of ember-cli is available (0.2.2). To install it, type ember update.

A new version of ember-cli is available (0.2.2).
[?] Are you sure you want to update ember-cli? Yes
...
```
Not a big thing, but if it's able to detect a new version, it should propose updating to it, right?

**Comment by stefanpenner** [comment]
I'm on my phone. But I'm pretty sure this is a duplicate

**Comment by bravely** [comment]
I did a search and didn't spy anything, if it is, I apologize.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/issues/3653, although this issue is more descriptive.

**Comment by vire** [comment]
Maybe I would add, that after ember update, e.g 0.2.1 -> 0.2.2 there is the ember init command suggested as next step, which is good to do when diffing package.json and bower.json. But after the embe update and npm install, it's necessary to run again ember init and diff the package descriptors for npm and bower and bump versions of ebmer, qunit etc, maybe the ember could autobump version of all non-user added libraries...

**Comment by bravely** [comment]
That can cause issues either in your own code or with libraries you might be using that might be using out of date APIs. Updating one by one, especially in older, larger apps is ideal, and the difference in effort isn't very large.

**Comment by stefanpenner** [comment]
`ember update` has been removed

**Comment by bravely** [comment]
Has it been replaced in any way? Anyplace I might see discussion on the removal?

**Comment by stefanpenner** [comment]
documentation on http://ember-cli.com outlines this.

**Comment by bravely** [comment]
Thanks
