### ISSUE TITLE
EXTEND_PROTOTYPES = false and Add-ons

### ISSUE THREAD

**Issue by blesh** [ember-cli/ember-cli#3708]
[I received a bit of feedback on our graph component add-on related to this.](https://github.com/Netflix/ember-cli-nf-graph/issues/8)

Apparently, if the consuming app has `EXTEND_PROTOTYPES: false`, then add-ons that use Ember prototypes (such as `function() { /*...*/ }.property()`) will break? I haven't confirmed this, but is there anything on the road map for Ember-CLI to alleviate this issue, or should all add-on developers develop with EXTEND_PROTOTYPES: false by default?

**Comment by rwjblue** [comment]
Yes, addons should be developed with extensions disabled, and as of 0.2.2 a newly blueprinted addon will do this automatically for you (via an optional addon of course).
