### ISSUE TITLE
`ember test` in CI mode does not exit on Build failed. 0.2.2

### ISSUE THREAD

**Issue by ezpuzz** [ember-cli/ember-cli#3712]
I think due to the new "display errors in browser on autoreload" functionality, `ember test` does not immediately exit when there are compilation errors in CI mode.

Workaround for now is to use `ember build -e test` and then run `ember test` if that succeeds (but involves recompiling it), but I think in CI mode the `ember test` command should fail immediately on build errors as it used to.

**Comment by stefanpenner** [comment]
You raise a good point

**Comment by rwjblue** [comment]
Agreed.
