### ISSUE TITLE
Cannot find module 'rsvp'

### ISSUE THREAD

**Issue by mfpiccolo** [ember-cli/ember-cli#3714]
Using ember-cli v0.2.2 I am getting this error:

`ember -v` or running any ember command

``` 
module.js:338
    throw err;
          ^
Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mfpiccolo/node_modules/ember-cli/lib/ext/promise.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Here are my global versions:

```
npm list -g --depth=0
/usr/local/lib
├── bower@1.4.0
├── csslint@0.10.0
├── ember-cli@0.2.2
├── express@4.12.3
├── express-generator@4.12.1
├── fixmyjs@1.0.3
├── jshint@2.6.0
├── npm@2.5.1
└── phantomjs@1.9.16
```

**Comment by stefanpenner** [comment]
Please share node and npm versions and os

**Comment by knownasilya** [comment]
Can also confirm that I was having this same issue, but with 0.2.1, since yesterday.

**Comment by rwjblue** [comment]
Can you `rm -rf node_modules && npm cache clear && npm install`?

**Comment by mfpiccolo** [comment]
Node version is 0.12.1
npm version is 2.7.4
os is OSX Yosemite 10.10.2

@rwjblue I swore I ran those commands last night multiple times while debugging but I just tried it this morning and reinstalled ember and bower globally and it seems to have resolved the issue.

Thanks.

**Comment by olivierlesnicki** [comment]
This issue does seem to creep up from time to time. Just encountered it. It's not the most effective solution having to "npm cache clear" every time.

**Comment by knownasilya** [comment]
@olivierlesnicki the issue is with npm being brittle, so the workaround is an npm solution. :+1:

**Comment by rikkitherockett** [comment]
+1

**Comment by chriskrycho** [comment]
Worth note: npm 3 did *not* solve this. However, `npm cache clean` does still fix it.
