### ISSUE TITLE
[DOCS]Unify different styles for `Note` for users

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#3717]
Notes on site have different styles. Sometimes `Note` is italics, sometimes it's bold Notes(instead of note) and no italics, sometimes it's big quote-like element.

Examples:
![zrzut ekranu z 2015-03-31 14 07 52](https://cloud.githubusercontent.com/assets/4950658/6918490/73f1c4c2-d7af-11e4-977c-c4c994474e37.png)
![zrzut ekranu z 2015-03-31 14 08 00](https://cloud.githubusercontent.com/assets/4950658/6918492/73fbb05e-d7af-11e4-80a3-3d13a921d950.png)
![zrzut ekranu z 2015-03-31 14 08 08](https://cloud.githubusercontent.com/assets/4950658/6918491/73f5dc92-d7af-11e4-87fc-7ad40e45244d.png)
![zrzut ekranu z 2015-03-31 14 08 23](https://cloud.githubusercontent.com/assets/4950658/6918493/73fbbcb6-d7af-11e4-88b4-3ab1f8abdd18.png)

In every book you will see that they give you one style for every `Note` so it's organised and elegant. I think one style should be chosen.

**Comment by stefanpenner** [comment]
:+1:

**Comment by Kuzirashi** [comment]
I don't feel like it's no longer an issue. : d
