### ISSUE TITLE
[bug] acceptance-test creates a failing test

### ISSUE THREAD

**Issue by mariogintili** [ember-cli/ember-cli#3719]
Hello guys,

I'm using ember-cli `0.2.2`. And as the title suggests, generating an `acceptance-test` yields a failing test. Reproduction steps:

- Generate acceptance test```ember g acceptance-test resource/action``` 

- Test is generated

```js
// ...
test('visiting /calendar/personal', function(assert) {
  visit('/calendar/personal');

  andThen(function() {
    assert.equal(currentPath(), 'calendar/personal');
  });
});
```

- Test fails with output:

```
Expected: 	
"routes/new"
Result: 	
"routes.new"
```

Looks like the helper `currentPath()` is returning the route action rather than the path itself resolved. I would like to take a go at fixing if you guys dont mind :)

**Comment by jgwhite** [comment]
You’re correct, this should use `currentURL()` rather than `currentPath()`. Thanks for offering to fix. Looking forward to your pull request.

**Comment by mariogintili** [comment]
Excellent! thanks @jgwhite will post a PR soon.

**Comment by jgwhite** [comment]
:+1:

**Comment by cibernox** [comment]
I also find this unexpected. I would expect `currentPath()` to return `calendar/personal`, whether `currentRouteName` is the one that should return `calendar.personal`.

**Comment by jgwhite** [comment]
@cibernox yeah, it’s non-obvious for sure.

**Comment by cibernox** [comment]
Then, is it intended (and therefore a poorly chosen name) or is a bug in the method?
What is the difference between `currentPath` and `currentRouteName`?

**Comment by jgwhite** [comment]
```js

Router.map(function() {
  this.resource('products', function() {
    this.resource('product', { path: ':product_id' });
  });
});

currentURL()       // => /products/1
currentPath()      // => products.product
currentRouteName() // => product
```

**Comment by jgwhite** [comment]
https://github.com/emberjs/ember.js/blob/980fa0f24bfa2653ad4d903f0a717ed6df0eb8fe/packages/ember-routing/lib/system/router.js#L873-L885

**Comment by stefanpenner** [comment]
@jgable @cibernox i think the naming is fine?

**Comment by jgwhite** [comment]
I’m cool with the naming too. It’s been this way so far without causing major headaches.

**Comment by stefanpenner** [comment]
@jgwhite are you able to land the above fix, or should I

**Comment by jgwhite** [comment]
@stefanpenner @mariogintili is on it

**Comment by stefanpenner** [comment]
awesome

**Comment by cibernox** [comment]
I've found **path** suffix misleading, since I was expecting a path in the classical meaning of the word (a relative path, meaning like the URL without the host). I expected `currentURL` to return a fully qualified URL and `currentRouteName` to return `products.product`.

**Comment by stefanpenner** [comment]
@cibernox ya... RoutePath and Path may have been more appropriate.

**Comment by mariogintili** [comment]
@jgwhite A fix is available on #3755 :) CI is running now

**Comment by jgwhite** [comment]
:smile:

**Comment by dukex** [comment]
I create a app with a route "my-test" and a acceptance test with command `ember g acceptance-test my-test`, when a run the tests I had 1 test failed, currentURL() returns a empty string.

To reproduce: 

```
$ ember new dummy-app-acceptance-test
$ cd dummy-app-acceptance-test
$ ember g acceptance-test my-test
$ ember test
not ok 1 PhantomJS 1.9 - Acceptance | my test: visiting /my-test
    ---
        actual: >

        expected: >
            /my-test
        Log: >
```

I updated the app to https://github.com/dukex/dummy-app-acceptance-test see the CI https://travis-ci.org/dukex/dummy-app-acceptance-test

**Comment by mariogintili** [comment]
@dukex what is `currentPath()` returning ? that's quite odd

**Comment by theazureshadow** [comment]
@mariogintili: I'm encountering the same issue with a new project with only a route and an acceptance test. I created a breakpoint where the test failed, and here's some console output:

```
> currentURL()
< ""
> currentPath()
< "oboe"
```

Version information:

```
> ember --version
version: 0.2.7
node: 0.10.26
npm: 2.11.0
```

**Comment by dukex** [comment]
@mariogintili the `currentPath()` is ok, returns `my-test`, I update my acceptance test to check the `currentPath()` https://travis-ci.org/dukex/dummy-app-acceptance-test

**Comment by theazureshadow** [comment]
Here's `currentURL`:

```
var router = app.__container__.lookup("router:main");
return property_get.get(router, "location").getURL();
```

Using the debugger, I saw that `router.location.setURL` isn't called in `visit` unless `app._readinessDeferrals > 0`. But, I think there is already a bugfix that is in `1.12.1`, but which landed after `1.13.0-beta.1` was cut.

https://github.com/emberjs/ember.js/pull/11201

**Comment by theazureshadow** [comment]
Based on the explanation above, you can also work around it by visiting something else first:

```
visit('/');
visit('/my-path');
```

**Comment by mariogintili** [comment]
@theazureshadow awesome

> But, I think there is already a bugfix that is in 1.12.1, but which landed after 1.13.0-beta.1 was cut.

I'll try to generate an acceptance test on the version of ember that has a fix, will update :)

**Comment by dukex** [comment]
Great catch @theazureshadow!
I update my dummy app with ember 1.13.0-beta,2, https://travis-ci.org/dukex/dummy-app-acceptance-test, **now all tests is green**

**Comment by mariogintili** [comment]
@dukex Perfect, we can close this now :)
