### ISSUE TITLE
Addon importing bower package from forked repo / branch but consuming project gets main

### ISSUE THREAD

**Issue by mbcomer** [ember-cli/ember-cli#3723]
I am writing an addon to wrap the xdan jquery datetimepicker library. I am specifically interested in using a version of that package which is currently sitting in a branch in a contributor's forked repo (a PR is still  pending for these changes). I am importing this in my addon's bower.json like so:

  "devDependencies": {
    "datetimepicker": "jazdw/datetimepicker#moment-js"
  }

I have the usual code in my addon to add this component to consuming projects.

However when I install:addon into a consuming project this ends up in that project's bower.json:

    "datetimepicker": "~2.4.1"

This is the original version of the library which the contributor's code was forked from.

I don't think I understand how the package resolution is working here, and I don't know if I am doing something wrong in my addon code. Can anyone help? Is this a bug in how addon package importing works or is my use case not valid?

**Comment by kellyselden** [comment]
Can you show us your blueprint code that has the `addBowerPackageToProject` call?

**Comment by mbcomer** [comment]
Hmmm, ok - your question pointed me right to the problem.

module.exports = {

  afterInstall: function() {
    var that = this;

    return this.addBowerPackageToProject('datetimepicker').then(function() {
      return that.addBowerPackageToProject('moment');
    });
  }
};

I guess I did not realize that this code is very literal - it is directly adding the package 'datetimepicker' to the consuming project's bower.json here. I guess I thought it was a little more clever than that and would use the dependency defined in the addon's bower.json. Is there any way to do that so I don't have to duplicately say 'jazdw/datetimepicker#moment-js' here? Once the PR is accepted in this package it would be nice to only have to update my addon's bower.json to define the proper dependency.

**Comment by kellyselden** [comment]
You could take the package out of your addon's bower.json. It's not being used. Then only one instance of it.
