### ISSUE TITLE
#each broken in the test dummy apps generated by ember addon

### ISSUE THREAD

**Issue by foxnewsnetwork** [ember-cli/ember-cli#3734]
After you start out a new addon with ember addon, the each handlebars directive breaks down and becomes unable to recognize basic arrays:

Here's the problem repo:
https://github.com/foxnewsnetwork/table-grid-2d/tree/each-broken-in-addons

This is the default setup after you run:

```bash
ember addon my-addon-name
```

All I did was go into dummy/app/controllers/application.js and add:

```javascript
// tests/dummy/app/controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  colNames: "abcdefg".split("")
});
```

and
```handlebars
<!-- tests/dummy/app/templates/application.hbs -->
<h2 id="title">Welcome to Ember.js</h2>

<ul>
  {{#each colName in colNames}}
    <li>{{colName}}</li>
  {{/each}}
</ul>
```

I then ran:
```bash
ember serve
```
Everything built, but upon visiting localhost:4200

I am greeted with the following error:

```
Uncaught Error: Assertion Failed: The value that #each loops over must be an Array. You passed [a,b,c,d,e,f,g] 
```
Somehow, arrays aren't passing each's array assertion. 

This bug doesn't exist in regular ember apps despite my many attempts to reproduce on codepen:

http://codepen.io/foxnewsnetwork/pen/wBZKzx?editors=101

**Comment by rwjblue** [comment]
We disable prototype extensions by default, you need to wrap any arrays that you each over with 'Ember.A(['some', 'array'])'.

**Comment by stefanpenner** [comment]
the reason why we now disable prototype extensions (this is new) is because not all add-on consumers run with prototype extensions enabled.

This particular error is unfortunate though, although that I would consider an ember bug.

**Comment by foxnewsnetwork** [comment]
Oh... In that case, I would like to do a PR to ember where, in similar situations, the assert would spit out something like "you passed in an array to each but prototype extensions are disabled, perhaps you should wrap your array in Ember.A". This way, wayward addon developers could more easily atone for their mistakes and get back on the right path; admittedly, when I encountered this "bug", I was completely at sea as to what could be causing it.

**Comment by foxnewsnetwork** [comment]
Or perhaps would it better to have each auto-wrap non-Ember.Array arrays?

**Comment by stefanpenner** [comment]
> Oh... In that case, I would like to do a PR to ember where, in similar situations, the assert would spit out something like "you passed in an array to each but prototype extensions are disabled, perhaps you should wrap your array in Ember.A".

yup, likely detect if PROTOTYPE_EXTENSIONS are false, and add some additional piece of information to that assertion.

**Comment by stefanpenner** [comment]
> Or perhaps would it better to have each auto-wrap non-Ember.Array arrays?

:-1:
