### ISSUE TITLE
Handling of node_modules outside of project path

### ISSUE THREAD

**Issue by jakehow** [ember-cli/ember-cli#3735]
This is related to #3679

The documentation for NODE_PATH and the default behavior can be found here -> https://nodejs.org/api/modules.html

I am currently trying to figure out if we can install node dependencies in $HOME/.node_modules which is one of the default search paths according to the node documentation.  It appears based on the stacktrace that code is being loaded from this path but I run into an error.

When I test this with ember-cli-todos by running `ember test` I get the following error:

```shell
➜  ember-cli-todos git:(docker-development-support) ✗ docker-compose run todos ember test
Future versions of Ember CLI will not support v0.10.38. Please update to Node 0.12 or io.js.
version: 0.2.1
0.2.2

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Building...
Missing template processor
Error: Missing template processor
    at module.exports.preprocessTemplates (/root/.node_modules/ember-cli/lib/preprocessors.js:164:11)
    at EmberApp._processedTemplatesTree (/root/.node_modules/ember-cli/lib/broccoli/ember-app.js:532:10)
    at EmberApp.appAndDependencies (/root/.node_modules/ember-cli/lib/broccoli/ember-app.js:773:24)
    at EmberApp.javascript (/root/.node_modules/ember-cli/lib/broccoli/ember-app.js:838:34)
    at EmberApp.toArray (/root/.node_modules/ember-cli/lib/broccoli/ember-app.js:1155:10)
    at EmberApp.toTree (/root/.node_modules/ember-cli/lib/broccoli/ember-app.js:1177:30)
    at Object.<anonymous> (/opt/app/Brocfile.js:20:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Here are the contents of /root/.node_modules:

```shell
➜  ember-cli-todos git:(docker-development-support) ✗ docker-compose run todos bash -c "ls /root/.node_modules"
broccoli-asset-rev		   ember-cli-inject-live-reload
ember-cli			   ember-cli-qunit
ember-cli-app-version		   ember-cli-uglify
ember-cli-babel			   ember-data
ember-cli-content-security-policy  ember-export-application-global
ember-cli-dependency-checker	   express
ember-cli-htmlbars		   glob
ember-cli-ic-ajax
```

**Comment by stefanpenner** [comment]
we explicitly try to not inherit `node_modules` four our preprocessors and add-ons because this allows easy pollution (imagine if you have nested projects, with different dependency versions).

**Comment by jakehow** [comment]
@stefanpenner would it be possible to add a flag or add to the search paths explicitly for preprocessors and add-ons in `.ember-cli`?

**Comment by stefanpenner** [comment]
@jakecraige have you though of just using a symlink to pull in node_modules?

**Comment by jakehow** [comment]
@stefanpenner end goal is mounting the project path as a volume in  the docker container and the volume semantics prevent this from working correctly (volumes are mounted at container runtime which removes structure you might have setup in the directory via the Dockerfile).

**Comment by stefanpenner** [comment]
> prevent this from working correctl

is `this` using a symlink or ...

**Comment by jakehow** [comment]
@stefanpenner yeah.  It just occurred to me we can do this at runtime after container start, but this seems pretty messy for most users.

For instance instead of just running ember serve, I can do something like this in a wrapper:

```shell
docker-compose run todos bash -c "ln -s /root/.node_modules /opt/app/node_modules && ln -s /root/bower_components /opt/app/bower_components && ember server"
```

**Comment by jakehow** [comment]
@stefanpenner a little bit of a timeline of why this doesn't work the standard way.

Say you build an image with a symlink from `/root/.node_modules` to `/opt/app/node_modules`

When you run the image with the symlink in the manner described this happens:

1. Docker boots up the container (the symlink is here now)
2. When you run the container with `-v ~/my-projects/ember-cli-todos:/opt/app` , docker mounts your project directory (ex: ~/my-projects/ember-cli-todos) as a volume inside the cointainer at /opt/app (the symlink is now gone since the volume has replaced this directory entirely)
3. You run ember serve and can't find dependencies

**Comment by jakehow** [comment]
@stefanpenner I think I missed this comment(https://github.com/ember-cli/ember-cli/issues/3735#issuecomment-88255816), must have been inflight when I replied.

Do flags map directly to optional arguments right now and that's the reason to minimize?

Would an `EMBER_CLI_NODE_PATH` or other env variable be more appropriate?

I can see why the default loading behavior was undesirable for ember-cli apps (especially with all the dependency management pain discussions), but it would be good to have a way to let the developer override this if possible.
