### ISSUE TITLE
uglification breaks jquery

### ISSUE THREAD

**Issue by shwoodard** [ember-cli/ember-cli#3737]
On 0.2.2, although I can't say exactly which version changed the outcome because I jumped a few versions, calling `jQuery#css({property: value})` results in `Uncaught ReferenceError: d41d8cd98f00b204e9800998ecf8427e is not defined` or other guid.  This is raised in `jQuery#style`.

**Comment by stefanpenner** [comment]
@shwoodard mind dropping a repo that contains a reproduction, would live to see it (i haven't been able to repro)

**Comment by shwoodard** [comment]
I cannot reproduce this in a smaller context.  Closing for now: I think it is a problem within our app.

**Comment by shwoodard** [comment]
@stefanpenner I had a file in my app, `app/styles/ie.scss`.  In env production, the cache-busting string on the file name was actually showing up in the src of `vendor.js`, as `ie-{sha}` and then being accessed with dot operator like, `ie-{sha}.cssName` or the like.  Does this ring any bells?

**Comment by stefanpenner** [comment]
seems funky

**Comment by stefanpenner** [comment]
cc @rickharrison anything come to mind?

**Comment by rickharrison** [comment]
Was the filename of ie.scss present in the source code of vendor.js? Thats the only reason I could see why it would be re-writing that inside that file.

**Comment by shwoodard** [comment]
I'm afraid not: I did a git grep for ie.scss and ie.css and not to be found.

**Comment by rickharrison** [comment]
Hmmm without having some sort of reproducible case, I'm not really sure where to go from here.

**Comment by stefanpenner** [comment]
> Hmmm without having some sort of reproducible case, I'm not really sure where to go from here.

:+1:  will reopen if that can be provided
