### ISSUE TITLE
Newlines trimmed from hbs files by default?

### ISSUE THREAD

**Issue by treyhunner** [ember-cli/ember-cli#3738]
#3440 causes hbs files to trim final newlines by default.

Maybe `insert_final_newline` should be a non-standard value to force EditorConfig to use the editor defaults (e.g. `varies` or `ignore`)?

I didn't understand @jclem's original issue so I'm not certain what the appropriate resolution is.

**Comment by jclem** [comment]
@treyhunner When I save a .hbs file and the text editor appends a final newline character, this results in a [Text](https://developer.mozilla.org/en-US/docs/Web/API/Text) node containing a newline character to be a part of the rendered template.

In most cases, this is not be expected behavior. This is such a difficult issue to debug (the unexpected source of the unwanted newline is in the editor, not even the code one thinks one is writing) that I think it makes more sense to prevent newlines on .hbs files unless a user explicitly overrides this setting.

**Comment by treyhunner** [comment]
I understand the issue now. I was surprised to see my `.editorconfig` and the behavior of my hbs files change.  This is a one-time standard change so I don't think it's a problem going-forward.

**Comment by jclem** [comment]
@treyhunner Your questions caused me to do a little bit more investigation than I did before. I should be clear that it's not always an extra single Text node. An extra Text node is appended, for example, if I end my template file with a binding (for example if my template ends with `{{foo}}`), and the editor then appends a newline. Without the newline, Ember still appends an empty Text node (the metamorph text node), but this is much less problematic than an actual newline. If my template consists of just text, the single Text node in the rendered element has a newline in it, which my not be expected.

**Comment by treyhunner** [comment]
Maybe the hbs file processor/parser should handle stripping the last newline.  That seems like it would be easier to deal with than stripping final newlines exclusively from hbs files.

Using a different newline insertion rule for commonly edited files basically requires users to install EditorConfig.  Encouraging EditorConfig usage is excellent, but requiring it for sane file editing seems a bit harsh.

**Comment by jclem** [comment]
Trimming the new line could have an effect on components with "whitespace: pre". I don't believe Ember CLI should alter template content at all.

**Comment by jclem** [comment]
Also, it's not "required", per se, but it does help eliminate a really tricky edge case for some who do use EditorConfig. Though to be fair, I didn't before I ran into this.

**Comment by treyhunner** [comment]
It's required in that your editor will not maintain two different newline endings by default.  If two different newline endings are enforced in your project and you don't use EditorConfig but someone else on your team does, their editor will start correcting all of your incorrect line endings which makes for a mess.

**Comment by jclem** [comment]
True, but I think that's a problem for the team to solve. Ember CLI can at least make a sound suggestion here by including this setting.

**Comment by treyhunner** [comment]
I see files relying on no trailing newline due to `pre` wrappers as something for the team to solve.  The use case trimming newlines solves is a very narrow one.  It seems like it would be more elegant for all to make a `.editorconfig` rule excluding just the relevant files from newline insertions when/if particular newline(s) become a problem on a project.

**Comment by jclem** [comment]
@treyhunner One example of a case where these newline nodes can cause problems is when it is necessary to read a value manually from the DOM. Doing so is generally wrong, but sometimes unavoidable when working with nodes that are `contenteditable`, for example.

Even though this may be an edge case, I think that the default `.editorconfig` should be configured such that it does not cause unexpected changes to the template output, however trivial the changes in output may be.

**Comment by stefanpenner** [comment]
this seems unrelated to ember-cli, rather the HTMLBars compiler
