### ISSUE TITLE
ember-cli 0.2.2 can send null messages to testem which breaks xunit ci

### ISSUE THREAD

**Issue by Twinkletoes** [ember-cli/ember-cli#3742]
Tests worked in 0.2.0, failed in 0.2.2 (invalid CI xml)

Fixed upstream in testem PR https://github.com/airportyh/testem/pull/531

testem will now handle nulls

Please link to new version when PR is merged

**Comment by Twinkletoes** [comment]
Now merged in https://github.com/airportyh/testem/commit/2a9811e98ce3a7f4dddce61e42ba78c81426e94b

**Comment by stefanpenner** [comment]
very nice!

**Comment by stefanpenner** [comment]
next ember-cli release will allow testem to drift along semver https://github.com/ember-cli/ember-cli/pull/3743

**Comment by Twinkletoes** [comment]
*blush*

**Comment by johanneswuerbach** [comment]
Released in testem v0.7.7.

**Comment by stefanpenner** [comment]
this will be available with `v0.2.3`

**Comment by Twinkletoes** [comment]
I like this community :) Thanks for the fast fix

**Comment by Twinkletoes** [comment]
Working again on my build server since late last week :)
