### ISSUE TITLE
generated objects not found in tests

### ISSUE THREAD

**Issue by dagda1** [ember-cli/ember-cli#3744]
I've just upgraded to ember-cli 0.2.2 and if I generate a mixin from an addon project:
```
ember g mixin foo
```
And run
```
ember test
```
I get the following output
>  ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2779
                at http://localhost:7357/assets/test-support.js:5541
                at http://localhost:7357/assets/test-loader.js:31
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:5545: Could not find module `dummy/mixins/foo` imported from `dummy/tests/unit/mixins/foo-test`
        Log: >

The generated test has the following imports:
```
import Ember from 'ember';
import FooMixin from '../../../mixins/foo';
import { module, test } from 'qunit';
```

If I generate a component:
```
ember g component x-autosuggest
```
and run ```ember test```, or ```ember server``` I get this output:

> An `addon/templates` tree was detected, but there are no template compilers registered for `emberx-autosuggest`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `emberx-autosuggest`'s `package.json`.

I had to manually move:
```
    "ember-cli-htmlbars": "0.7.4"
```
From devDependencies into dependencies.

**Comment by vinilios** [comment]
I just faced both issues in an fresh ember addon tree. I'm using ember-cli 0.2.2.

**Comment by rwjblue** [comment]
This should be resolved as of https://github.com/ember-cli/ember-cli/pull/3690.

@trabus - Can you confirm?

**Comment by dagda1** [comment]
I am currently on 0.2.2.  Is it possible for me to overwrite my version with the version that has the fix?

**Comment by trabus** [comment]
I'll take a look in an hour or so.

**Comment by trabus** [comment]
Hmm, I think we'll need to change the tests to import from the addon path when generating inside an addon:
```
import Ember from 'ember';
import FooMixin from 'my-addon/mixins/foo';
import { module, test } from 'qunit';
```

In regards to the compiler warning, that is currently expected behavior for the time being. We could probably update the package.json with the dependencies statement when generating a component, but I'd defer to @rwjblue  on that.

**Comment by Fed03** [comment]
I can confirm the issue for the Mixin generation

**Comment by knownasilya** [comment]
I also have this issue, but I'm using the `ember-notify` addon and get a similar error: https://github.com/aexmachina/ember-notify/issues/53

**Comment by stefanpenner** [comment]
the reported issue appears to be fixed in 0.2.5

```
± % ember g mixin foo                                                                                                                                                         !12268
version: 0.2.5
installing
  create app/mixins/foo.js
installing
  create tests/unit/mixins/foo-test.js

stefanpenner@trustdream-lm ~/tmp/my-testing-thing [master *]
± % ember test                                                                                                                                                                !12269
version: 0.2.5
Built project successfully. Stored in "/Users/stefanpenner/tmp/my-testing-thing/tmp/class-tests_dist-lCxqMxw3.tmp".
ok 1 PhantomJS 2.0 - JSHint - .: app.js should pass jshint
ok 2 PhantomJS 2.0 - JSHint - helpers: helpers/resolver.js should pass jshint
ok 3 PhantomJS 2.0 - JSHint - helpers: helpers/start-app.js should pass jshint
ok 4 PhantomJS 2.0 - JSHint - mixins: mixins/foo.js should pass jshint
ok 5 PhantomJS 2.0 - JSHint - .: router.js should pass jshint
ok 6 PhantomJS 2.0 - JSHint - .: test-helper.js should pass jshint
ok 7 PhantomJS 2.0 - Unit | Mixin | foo: it works
ok 8 PhantomJS 2.0 - JSHint - unit/mixins: unit/mixins/foo-test.js should pass jshint

1..8
# tests 8
# pass  8
# fail  0

# ok
```

**Comment by knownasilya** [comment]
Doesn't seem to be fixed when using an addon's files..

**Comment by stefanpenner** [comment]
Is there a repro repo I can poke at @knownasilya ? I would love to sort it out for you

**Comment by knownasilya** [comment]
@stefanpenner I'll make one

**Comment by stefanpenner** [comment]
> @stefanpenner I'll make one

thanks

**Comment by knownasilya** [comment]
@stefanpenner after trying to replicate it seems like it was an issue somewhere else.. unfortunate that the error didn't come through for whatever it was, but I fixed it.

**Comment by stefanpenner** [comment]
@knownasilya ah ok. I will close then, if you discover the other issue please report and we can dig in.

**Comment by galfert** [comment]
@knownasilya I have the exact same problem right now. Could you elaborate what your underlying issue was or how you found it?

**Comment by knownasilya** [comment]
@galfert it came down to syntax errors that weren't being exposed on the cli..

**Comment by balinterdi** [comment]
I get the same error (see below) with ember-cli 0.2.7.

> Addon templates were detected, but there are no template compilers registered for `ember-cli-star-rating`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ember-cli-star-rating`'s `package.json`.

Manually moving `ember-cli-htmlbars` from devDependencies to dependencies solved the issue. Do I understand correctly that creating the package.json with the template compiler lib already in `dependencies` would be too much, and unnecessary unless the addon includes templates?

**Comment by knownasilya** [comment]
The addon needs to add `ember-cli-htmlbars` to it's dependencies, so that the templates that it provides get precompiled.
