### ISSUE TITLE
Why I get Slowest Trees (cumulative) plus normal Slowest Trees and it takes longer to build ?

### ISSUE THREAD

**Issue by msalahz** [ember-cli/ember-cli#3745]
Hi,

My environment details are :
OS: Windows 8.1
Ember-Cli: 0.2.2
npm version:{ tugg: '0.0.0',
  npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }

recently I notice that I get Slowest Trees (cumulative) plus normal Slowest Trees in cmd and it takes longer to build my ember-cli project

My build time is :
```
Build successful - 6456ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 1951ms
ES6: App Tree                                 | 613ms
TemplateCompiler                              | 473ms
Funnel: App JS Files                          | 432ms
Concat: Vendor                                | 418ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (1)                                     | 1951ms
ES6: App Tree (1)                             | 613ms
TemplateCompiler (1)                          | 473ms
Funnel: App JS Files (1)                      | 432ms
Concat: Vendor (1)                            | 418ms
```

My incremental build time is :
```
Build successful - 4718ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ES6: App Tree                                 | 1170ms
Funnel: App JS Files                          | 458ms
TreeMerger (appAndDependencies)               | 353ms
TreeMerger (vendor)                           | 353ms
Concat: Vendor                                | 279ms
Babel                                         | 265ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
ES6: App Tree (1)                             | 1170ms
Funnel: App JS Files (1)                      | 458ms
TreeMerger (appAndDependencies) (1)           | 353ms
TreeMerger (vendor) (1)                       | 353ms
Funnel (67)                                   | 306ms (4 ms)
Concat: Vendor (1)                            | 279ms
Babel (1)                                     | 265ms
```

**Comment by stefanpenner** [comment]
if im reading this correctly you are bringing up two things, a question and an issue? or...

**Comment by msalahz** [comment]
Yes @stefanpenner , Sorry if I didn't make myself clear.

My Question :  Why I get Slowest Trees (cumulative) plus normal Slowest Trees in cmd while I have other Ember-Cli projects and doesn't have that and also my colleges  with the same project on MAC doesn't have it ? Is this something new ?

My Issue: Why My build time is slower now ?

**Comment by rwjblue** [comment]
The cumulative listing is new and does not add significant time to the total build.  It is pretty helpful to see what kind of trees are totalling for more time during a build (vs the individual slower trees).

**Comment by msalahz** [comment]
Thank you @rwjblue & @jimbeaudoin , I got the chance during this weekend to go through a comparison between the branch for my project with slower incremental build time as (4500ms - 7000ms) and the old one which had (2500ms - 3500ms) incremental build time and I found only two changes have effect on build time :
The first change was installing ember-cli-scss npm package and my build time went slower by around 500ms after this change.
The second change was changing project structure to follow pods style and this made my build slower with around 2000ms.

I tried the slower branch on MAC and I was frustrated with the 850ms build time and I'm really thinking about change my environment to MAC but do you think this is the solution for my situation ?

I had a hard time last month to have 3000ms build time after following Windows pest practices and disable features like tests and es3Safe and applying manual clean for bower packages and I was happy with that but now my productivity is slower and this will have bad effects on my career on general Please let me know when you will consider windows slow build as one of your top priorities ? and what I can do to help with that ? I'm welling to give you all my free time I can get .

Thanks.

**Comment by msalahz** [comment]
Switched to OS X
