### ISSUE TITLE
Failing tests on fresh checkout

### ISSUE THREAD

**Issue by jakehow** [ember-cli/ember-cli#3749]
When I checkout ember-cli and try to run the test suite as described in https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md there are failing tests.

I am running `npm install && npm run test-all`

Test suite output here -> https://gist.github.com/jakehow/58405aad30b5295fe0b5

npm-debug.log -> https://gist.github.com/jakehow/b5a212030ad414c43cdc

This is a fresh checkout of master on Yosemite, npm@2.7.1, node@v0.10.37

**Comment by rwjblue** [comment]
> No tests were run, please check whether any errors occurred in the page
> (ember test --server) and ensure that you have a test launcher
> (e.g. PhantomJS) enabled.

Do you have `phantomjs` installed?

**Comment by jakehow** [comment]
@rwjblue nope, just figured that out.  Re-running and will create a PR listing requirements in CONTRIBUTING.md

**Comment by stefanpenner** [comment]
we may also want to give a more descriptive error
