### ISSUE TITLE
Can't build to a directory outside the project directory structure

### ISSUE THREAD

**Issue by terryroe** [ember-cli/ember-cli#3751]
I have the following directory structure:
```
~/my.dev
~/my
```
My project is located in ~/my.dev.  I want to build to the ~/my directory.  When I use this command `ember build -w -o ../my/` (or similar, ie. full path like so `/home/troe/my/`) I get the following error (twice as shown):
```
Using a build destination path of `/home/troe/my` is not supported.
Using a build destination path of `/home/troe/my` is not supported.
```
I'm using ember-cli 0.1.5.  Is this a know problem?  Has it been fixed in a later release perhaps?

**Comment by terryroe** [comment]
I've found a workaround that works for me.  I do a symbolic link from `~/my.dev/dist` to `~/my`.  One would expect the output-path to be able to work as described above, but the workaround is fine for now.

**Comment by rwjblue** [comment]
We are trying to protect users from building their output into a parent directory (and therefore deleting their work project). My guess is that we are doing a regexp type search and incorrectly determine that `~/my` is a parent of `~/my.dev`.

**Comment by rwjblue** [comment]
This is coming from: https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L41

If you replace that with a more standard walking of the parent directories to confirm the specified `--output-path` is or is not a parent directory that would fix this problem for you.

**Comment by terryroe** [comment]
Thank you Robert.  For my purpose, the symbolic link works.

**Comment by stefanpenner** [comment]
+1 for the current conservative approach, but also +1 for a more advanced detection method.

**Comment by choclaudio** [comment]
I would argue that this is not actually solved. Even if the intention is to avoid accidental overwrite of the ember project itself, the check itself identifies  false positives. Either that or I don´t actually know what it is trying to avoid.

eg.

if I have an Ember project in "c:\project\ember" and I execute ember b --output-path= "..\dist\wwwroot" then it would fail. From my point of view Ember CLI should not try to protect things outside its domain, in this case that would be outside the ember directory.

**Comment by choclaudio** [comment]
I will revoke my statement, apparently since I had a space after the equals sign eg. --output-path= ../dist/wwwroot it did not understand it and assumed that I was trying to build into the same directory. Just by removing this blank character everything worked.
