### ISSUE TITLE
ember-cli is 137mb

### ISSUE THREAD

**Issue by tkellen** [ember-cli/ember-cli#3752]
This is pretty dang painful to install from a 3G connection abroad.  Can we do better?

Here is are the top offenders for `du -ck -d1 | sort -nr` in `node_modules`:

```
44008	./bower
16752	./testem
16660	./npm
6628	./broccoli-es6modules
6464	./inquirer
6328	./leek
6184	./broccoli-sourcemap-concat
5884	./markdown-it-terminal
5860	./broccoli
4672	./broccoli-caching-writer
4500	./broccoli-es3-safe-recast
3320	./markdown-it
2732	./bower-config
2432	./configstore
2212	./core-object
2032	./ember-router-generator
2016	./lodash
1784	./tiny-lr
1776	./express
1764	./broccoli-writer
1580	./broccoli-sane-watcher
1016	./promise-map-series
```

**Comment by stefanpenner** [comment]
We have wip to drop bower entirely from the ecosystem. That will help dramatically. We also have plans for a better offline mode, it also looks like npm3 will have improved cache utilization. Which will help

Reasons for bundling and having these deps; stability e can't guarantee without.

**Comment by tkellen** [comment]
Thanks for the quick reply @stefanpenner!

I suspect quite a bit of space could be saved by checking deps for unneeded files and submitting PRs or issues to dependencies to update their .npmignore. I did a bit of this for gulp a few months back and it was very successful in cutting down size.

I hope this raised awareness a bit for anyone who gets emails for issues on this project--I'm going to give this a close because I don't have the bandwidth to do this for ember-cli, and I don't want to leave an orphan issue in your tracker. Feel free to re-open if someone wants to take up the torch!

**Comment by tkellen** [comment]
PS: thanks for all the work ya'll do, I use this tool a **ton** in my work <3
