### ISSUE TITLE
ember serve terminates with no errors

### ISSUE THREAD

**Issue by rtm** [ember-cli/ember-cli#3753]
When I run ember serve, it terminates with no errors:

    C:\wrk\connect>ember serve --proxy=http://proxy.com
    The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `C:\wrk\connect\node_modules\ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
    version: 0.2.1

    A new version of ember-cli is available (0.2.2). To install it, type ember update.
    The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `C:\wrk\connect\node_modules\ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
    Proxying to http://proxy.com
    Livereload server on port 35729
    Serving on http://localhost:4200/
    Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory 'C:\wrk\connect\tmp\tree_merger-tmp_dest_dir-EeFwi5Yd.tmp\bower_components\route-recognizer\dist\route-recognizer.js.map'

    C:\wrk\connect>

I could provide more information (package.json, bower.json) if relevant, but there's nothing really controversial in there. 

What could account for `ember serve` just stopping without any hint of an error?

**Comment by stefanpenner** [comment]
can you provide more actionable information

which  version of node/npm/os

* Also, it appears you are using a slightly outdated version of ember-cli
* does it work without `--proxy`

**Comment by rtm** [comment]
Thanks for quick response:

    $ ember version
    version: 0.2.1
    node: 0.12.0
    npm: 2.7.3

Same thing happens with no proxy.
Did complete cache clean, deletion of node_modules and bower_components and reinstall.

Here is package.json:

    {
      "name": "xxxx",
      "version": "0.0.0",
      "private": true,
      "directories": {
        "doc": "doc",
        "test": "tests"
      },
      "scripts": {
        "start": "ember server",
        "build": "ember build",
        "test": "ember test"
      },
      "repository": "",
      "engines": {
        "node": ">= 0.10.0"
      },
      "author": "",
      "license": "MIT",
      "devDependencies": {
        "broccoli-asset-rev": "2.0.1",
        "broccoli-sass": "0.6.1",
        "broccoli-static-compiler": "0.2.1",
        "connect-restreamer": "1.0.1",
        "ember-cli": "0.2.1",
        "ember-cli-app-version": "0.3.2",
        "ember-cli-babel": "4.3.0",
        "ember-cli-content-security-policy": "0.3.0",
        "ember-cli-dependency-checker": "0.0.8",
        "ember-cli-htmlbars": "0.7.4",
        "ember-cli-i18n": "0.0.6",
        "ember-cli-ic-ajax": "0.1.1",
        "ember-cli-inject-live-reload": "1.3.1",
        "ember-cli-moment": "0.0.1",
        "ember-cli-pretender": "0.3.1",
        "ember-cli-qunit": "0.3.9",
        "ember-cli-uglify": "1.0.1",
        "ember-cli-windows-addon": "^1.2.0",
        "ember-data": "1.0.0-beta.15",
        "ember-export-application-global": "1.0.2",
        "express": "4.12.2",
        "glob": "4.0.5",
        "liquid-fire": "0.16.3",
        "morgan": "1.5.1"
      }
    }

Here is bower.json:

    {
      "name": "xxx",
      "dependencies": {
        "handlebars": "2.0.0",
        "jquery": "^1.11.1",
        "ember": "1.10.0",
        "ember-data": "1.0.0-beta.15",
        "ember-resolver": "0.1.12",
        "loader.js": "ember-cli/loader.js#3.2.0",
        "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
        "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
        "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
        "ember-qunit": "0.2.8",
        "ember-qunit-notifications": "0.0.7",
        "qunit": "~1.17.1",
        "accounting": "openexchangerates/accounting.js",
        "hammerjs": "1.1.3",
        "ember-hammer": "~1.0.0",
        "tinymce": "4.1.9",
        "t17-ember-upload": "~0.4.0",
        "slick.js": "~1.4.0",
        "bind-polyfill": "~1.0.0",
        "pretender": "0.1.0"
      }
    }

**Comment by rtm** [comment]
Upgrading to ember-cli 2.2 both globally and in the project does not solve the problem. The only difference is the following irrelevant messages:

    [Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: liquid-fire]
    [Deprecated] this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: liquid-fire]

**Comment by kellyselden** [comment]
@rtm Those new warnings are fixed in https://github.com/ef4/liquid-fire/pull/227

**Comment by rtm** [comment]
This is getting quite annoying. Re-installed node to no avail. Upgraded to ember-cli 0.2.3. Bug manifests itself whether in regular command window or command window in administrator mode (also powershell). Is there any kind of log or verbose option?

When running "ember serve", the server comes up momentarily and handles one request, then craps out. The broccoli build timings are never displayed.

**Comment by stefanpenner** [comment]
Yes, one can set an env car as such(although this is for OS X/Linux, I forget the incantation for windows cc @raytiley maybe you remember?)

```
DEBUG=* ember s
```

**Comment by rtm** [comment]
DEBUG=* yielded the following:

    broccoli-caching-writer  cache eviction due to:
    - {directory, ., 16822, 0, 0, 1428420941222}
    - {undefined} +0ms

**Comment by stefanpenner** [comment]
I'm sure it yielded more? Mind gisting it

**Comment by rtm** [comment]
Not quite sure how to gist 8000 lines.
Here's the file:
https://www.dropbox.com/s/cyd193x4pv08a8z/ember-serve.out?dl=0

**Comment by rtm** [comment]
I have determined that omitting broccoli-sass from my package.json file (without removing it from node_modules) seems to cause the bug to go away. I would guess that broccoli is picking up the broccoli-plugin keyword from node_modules/broccoli-sass/package.json and that is somehow the source of some problem. BTW I am using broccoli-sass-0.6.3. 0.6.1 won't compile my SCSS for some reason, and for some other reason 0.6.2 won't install on my box.

So is it time to move this issue somewhere else?

**Comment by stefanpenner** [comment]
broccoli-sass does depend on a c extension, it is possible something didn't build right?

Very strange that it just dies with no errors.

**Comment by stefanpenner** [comment]
is it possible to share a reproduction case, without debugging i have no idea :(

**Comment by tehmaestro** [comment]
Getting this too.

**Comment by petetnt** [comment]
I am having this issue on Windows 7/IE9 virtual machine (downloaded from https://www.modern.ie/en-us/virtualization-tools#downloads). The exact same folder/project serves correctly on the actual OS (Windows 8.1.). 

Above is the real PC, below it is the VM:

![VM vs real](https://cloud.githubusercontent.com/assets/7641760/7410167/0aae7026-ef35-11e4-9daf-69c53b2f0dc0.png)

Steps to reproduce:
1. ember new test-2
2. cd test-2
3. ember serve 

Which pretty gives me... nothing?

**Comment by stefanpenner** [comment]
> 1. ember new test-2
> 2. cd test-2
> 3. ember serve

i don't think this is actually correct. I can run ember on windows without trouble. Even our CI runs on windows.

If someone can provide me an actionable reproduction the I can run. I will gladly dig into this.

**Comment by petetnt** [comment]
@stefanpenner yeah I guess I was a bit unclear...

I meant those steps on the VirtualBox Windows 7 w/ XP downloaded from the `modern.ie` site. It's the same exact project from the save hardware with similar installation, it runs correctly on the real PC (running Windows 8.1., the upper screenshot) but doesn't run on the Windows 7 Virtual Machine, but just quits without saying anything. I have been running Ember on various Windows installations myself, but that VM was the first one I ran into this issue with.

There's no errors or anything else, so it's rather hard to produce any other steps. I guess you could try downloading the VM yourself and give it a try :8ball: Steps would be 1. Install Virtual Box, 2. download that VM, 3. install newest node, 3. install `ember-cli` with npm (and any other dependencies), then run those 3 steps from the before. But I am willing to be that it's just random.

**Comment by petetnt** [comment]
Tried out that exact same setup on my home PC and it worked correctly as I expected. I can try out and see if I can pull out some more info from my work PC tomorrow.

**Comment by stefanpenner** [comment]
> Tried out that exact same setup on my home PC and it worked correctly as I expected. I can try out and see if I can pull out some more info from my work PC tomorrow

strange mystery.

@raytiley got any ideas?

**Comment by raytiley** [comment]
Not without trying the VM. Best guess is that there is some sort of security software on the VM killing the process? Opening ports is a common thing that security software will flag.

**Comment by stefanpenner** [comment]
without reproduction case, this appears non-actionable. Closing until it can be reproduced
