### ISSUE TITLE
ember-cli 0.2.2 upgrading error "The morph before which the new morph ..."

### ISSUE THREAD

**Issue by vsymguysung** [ember-cli/ember-cli#3757]
I upgraded to version 0.2.2 today and getting tons of this errors that eventually crash the browser.
```
The morph before which the new morph is to be inserted is not a child of this morph.
```
This error is actually coming from the newly added method ``` Morph.prototype.insertBeforeMorph ``` in the ```ember.debug.js```.

What could be possibly wrong here? Any idea?
Any help would be much appreciated.

**Comment by stefanpenner** [comment]
this is an ember regression. https://github.com/emberjs/ember.js/issues/10792 I believe another point release will land within a day or two to fix this.

**Comment by vsymguysung** [comment]
@stefanpenner Thanks always.
