### ISSUE TITLE
Compiling assets into two (or more) JS files

### ISSUE THREAD

**Issue by RCanine** [ember-cli/ember-cli#3760]
I've got a project with a need for multiple JS files. Some use cases:

* IE-only polyfills I include with a conditional comment and don't want mobile devices to download
* Large files not included on a landing page that I want to lazy load

It appears that ember cli allows for multiple CSS files, but not multiple JS files:

```javascript
var app = new EmberApp({
  outputPaths: {
    app: {
      js: {
        app: '/assets/app.js',
        ie: '/assets/ie.js'
      }
    }
  }
});
```

Errors:

```
Object #<Object> has no method 'slice'
TypeError: Object #<Object> has no method 'slice'
    at module.exports (/Users/<me>/Projects/<my-app>/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/index.js:15:30)
    at EmberApp.concatFiles (/Users/<me>/Projects/<my-app>/node_modules/ember-cli/lib/broccoli/ember-app.js:261:10)
    at EmberApp.javascript (/Users/<me>/Projects/<my-app>/node_modules/ember-cli/lib/broccoli/ember-app.js:864:16)
    at EmberApp.toArray (/Users/<me>/Projects/<my-app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1159:10)
    at EmberApp.toTree (/Users/<me>/Projects/<my-app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1181:30)
    at Object.<anonymous> (/Users/<me>/Projects/<my-app>/Brocfile.js:35:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

There's nothing in the guides about multiple JS files other than vendor; is there something I'm missing or is this a missing feature?

**Comment by stefanpenner** [comment]
> is this a missing feature?

missing feature, we are currently restructuring the internals to enable this nicely though.

cc @chadhietala

**Comment by stefanpenner** [comment]
wil be part of a future iteration of the build pipeline

**Comment by djsegal** [comment]
@stefanpenner do you know which iteration yet?

**Comment by adorum** [comment]
Hi guys, I am facing the same issue, is there already working solution to split output JS into multiple files?

**Comment by amk221** [comment]
Me too, I'd like to be able to compile the usual vendor.js, but separately load a large charting library, but retain the benefits that ember-cli gives you, like minification etc

**Comment by djsegal** [comment]
The only way I've been able to do it is through the method described in this blog post:

+ https://karl-sjogren.com/ember/javascript/2015/08/05/lazy-loading-extra-scripts-in-ember.html

**Comment by amk221** [comment]
That blog post is about loading extra scripts, but this issue is about compiling extra assets.
I managed to load the scripts [like so](https://gist.github.com/amk221/124fbd22cf0daf820c654c3dc8ef1587), but they are not going to be minified or anything

**Comment by aexmachina** [comment]
Is there any update on this? This is still something that I'd very much like to be able to do.

**Comment by nathanhammond** [comment]
@aexmachina Lazy Ember Engines will allow for this. There is also `outputFile` on `app.import`.

**Comment by aexmachina** [comment]
Okay thanks @nathanhammond. FWIW I can't find any documentation for this on ember-cli.com.

**Comment by nathanhammond** [comment]
@aexmachina Once you figure it out would you write some? ❤️ It's incredibly hard to go back and document all the things that we aren't actively using.

**Comment by aexmachina** [comment]
@nathanhammond I'll try, but we've moved on and don't need this any more. Will certainly do so if I do use it!

**Comment by terryroe** [comment]
Has anyone found out how to make this work, or found a workaround to "build" separate JS files as part of an Ember project?  I'm sure it's possible since the build tools are already part of the project, but I don't have enough knowledge or skill to wield them well enough to do this.  Any help is greatly appreciated.

**Comment by aexmachina** [comment]
I think you specify `outputFile` on the call to `app.import`. I'm guessing it's something like:

```js
app.import('app/some/file.js', { outputFile: 'foo.js' })
```

But I haven't tried it yet.

**Comment by terryroe** [comment]
@aexmachina,

Thanks!  That is just what I needed!  I specified the same `outputFile` for several `app.import` calls and they get concatenated together perfectly!  I wish this were documented somewhere.  I couldn't find it except by searching the ember-cli source.

Thanks again!  tr

**Comment by aexmachina** [comment]
Someone really should document it. Maybe that person is you @terryroe? See [nathanhammond's](https://github.com/ember-cli/ember-cli/issues/3760#issuecomment-256561683) comment above 👍

**Comment by terryroe** [comment]
@aexmachina Looks like someone did the documentation work already (see above related issue).

**Comment by aexmachina** [comment]
Great, thanks @terryroe

**Comment by mm2ha** [comment]
Did anyone figure out a way how to compile Ember JS assets into 2 different versions? We would like to serve non-transpiled versions of the bundle to browsers that support new features and transpiled ones  to all others.
