### ISSUE TITLE
get host url and port in environment.js

### ISSUE THREAD

**Issue by sbounmy** [ember-cli/ember-cli#3765]
Hello,

I am currently using torii https://github.com/Vestorly/torii and I need to specify the following setting:
```js
module.exports = function(environment) {
....
  if (environment === 'development') {
    ENV.torii = {
      sessionServiceName: 'toriiSession',
      providers: {
        'stripe-connect': {
          apiKey:      my_api_key,
          redirectUri: currently_running_host_url
        }
      }
    };
  }
```

Is there a way to get ```currently_running_host_url``` ?
Example :
```ember serve --port=4242```
currently_running_host_url would be ```http://localhost:4242```

**Comment by stefanpenner** [comment]
this is not something we currently support. If one is to redirect back, it would seem torri could just gather this information at runtime from the navigator..

**Comment by rwjblue** [comment]
I actually opened an issue in Torii to get the example updated, and found out that the default rediectUri is current location.

https://github.com/Vestorly/torii/issues/161#issuecomment-89060188

**Comment by stefanpenner** [comment]
ah so, this is the existing behavior as of that fix

**Comment by sbounmy** [comment]
thanks a lot, so I guess this is not supported at the moment, or maybe I could initialize ENV.torii somewhere where I have access to ```document.location.href```
