### ISSUE TITLE
inotify_init error: Too many open files

### ISSUE THREAD

**Issue by BenjaminHorn** [ember-cli/ember-cli#3766]
Today I started a new addon. After 

```
ember addon ember-fm-form
cd ember-fm-form
ember serve
```
I'm getting the following error multiple times:
```
unable to resolve root /home/bh/projects/ember-fm-form/tests/dummy/public: watch(/home/bh/projects/ember-fm-form/tests/dummy/public): inotify_init error: Too many open files

Error: unable to resolve root /home/bh/projects/ember-fm-form/tests/dummy/app/templates: watch(/home/bh/projects/ember-fm-form/tests/dummy/app/templates): inotify_init error: Too many open files
    at null.<anonymous> (/home/bh/projects/ember-fm-form/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/home/bh/projects/ember-fm-form/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
```

since I already had this issue before I followed some instruction and now i have in etc/sysctl.conf
```
fs.inotify.max_user_watches=524288
fs.file-max = 100000
```
It seemed to solve the problem, but it appeared again.

**Comment by stefanpenner** [comment]
you may want to investigate what other files are open, and go from there.

**Comment by BenjaminHorn** [comment]
No other files are open. 
  -  I have just restarted my computer
  - First I started node with ```nvm install 0.12.1``` (I installed without sudo)
  - Then ```ember serve```
  - The same, but the server runs and I can navigate to  http://localhost:4200/


Ember CLI:  0.2.2

OS: Ubuntu

**Comment by stefanpenner** [comment]
Watchman 3.1 adds the watch-project command. Which will likely simplify some of our usages and will help us easily reduce the file watch count
