### ISSUE TITLE
Running ember upgrade causes placeholders to remain

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#3772]
After ember init runs I had these files generated:, needless to say they don't run.

package.json
```js
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "<%= emberCLIVersion %>",
```

dummy/app/index
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= namespace %></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/<%= name %>.css">

    {{content-for 'head-footer'}}
  </head>
  <body>
    {{content-for 'body'}}

    <script src="assets/vendor.js"></script>
    <script src="assets/<%= name %>.js"></script>

    {{content-for 'body-footer'}}
  </body>
</html>
```

**Comment by stefanpenner** [comment]
Related to: https://github.com/ember-cli/ember-cli/issues/3754


I am surprised this is getting past our test suite.

@trabus / @jgwhite any ideas?

**Comment by trabus** [comment]
Will try and look into this over the weekend.

**Comment by stefanpenner** [comment]
@trabus awesome, I have also added this to my queue. Maybe i'll flush my queue quick enough to help :)

**Comment by QuantumInformation** [comment]
sorry I found this before the easter holiday)

**Comment by davewasmer** [comment]
@stefanpenner FWIW, it could be related to #3237. If a template errors during the rendering (i.e. if there is a variable referenced and it's undefined, throwing a ReferenceError), the template falls back to the source string. I mentioned in that PR that this could lead to confusing behavior (the same symptoms here, in fact), but wasn't sure if I should have changed the original intent of the code, which appear to be not to warn on templating errors.

**Comment by stefanpenner** [comment]
@davewasmer ah thanks for the reminder.

**Comment by davewasmer** [comment]
No worries - happy to submit a PR to print warnings (but not fail) in that scenario, if that would be helpful.

**Comment by stefanpenner** [comment]
> No worries - happy to submit a PR to print warnings (but not fail) in that scenario, if that would be helpful.

yes that would be great.

now I'm curious if we should actually fail faster?

**Comment by davewasmer** [comment]
My concern with failing immediately was if someone was using the `<%=` markers in their own source, and the CLI attempting to template those and failing. Is it possible to change those markers? And if so, does the install process for a blueprint respect the **addons** version of those settings, rather than the parent app? I'll do some digging, just wondering if anyone knows off the top of their head.

If yes to both, then we could fail immediately, and the error message could document how to change those markers. If not, then failing effective means you can use those interpolation markers anywhere in your code.

**Comment by stefanpenner** [comment]
> <%= markers in their own source, and the CLI attempting to template those and failing.

I think this is correct to fail, as the result will be unexpected.

**Comment by davewasmer** [comment]
PR is up (#3786). @QuantumInformation you might want to try using that PR.

Currently, when the CLI attempts to replace those placeholders, it will swallow any errors (like a ReferenceError if you reference a variable that isn't defined) and abort (returning the template source itself, what you pasted above).

With the PR, any errors while replacing the placeholders will abort the entire process, and dump the error to the console.

**Comment by QuantumInformation** [comment]
Thanks, I'll pull that branch shortly and test.




-- 

Kind regards
Nikos

**Comment by QuantumInformation** [comment]
So it ran the upgrade script and had no errors this time, so think the issue may be how the ember upgrade command works

```js
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli@0.2.2
npm install ember-cli@0.2.2 --save-dev
rm -rf node_modules bower_components dist tmp
npm install
bower install
ember init
```

**Comment by stefanpenner** [comment]
U.S. Ember upgrade is in a bad spot at the moment. We will have to fix that soon

**Comment by QuantumInformation** [comment]
Its hard to see how it would improve beyond the the way outlined in the upgrade docs (cache cleaning), unless it kept track of every possible permuation of dependancy settings. I'm quite happy using the blast approach for now :)

**Comment by QuantumInformation** [comment]
I run ember upgrade on a windows project and the bower and package didn't actually change after ember init with the `y` option

**Comment by stefanpenner** [comment]
this appears fixed
