### ISSUE TITLE
Install ember-cli 0.2.2 or 0.2.1 is killed on cloud9 or nitrous

### ISSUE THREAD

**Issue by severinedarlot** [ember-cli/ember-cli#3773]
When you want try ember-cli on a WebIDE on the cloud as Cloud9 or Nitrous, the command `npm install -g ember-cli` is killed. 

It seems that it is because the installation takes a lot of memory. Cloud9 suggested me to upgrade my free workspace (512MB Ram) to a commercial workspace but I don't want buy a lot of memory only for a sample.

It seems to me that problem gives a bad image of ember-cli.

The problem appeared from 0.2.1 because I installed the 0.2.0 version without problem

**Comment by karelvuong** [comment]
Encountered the same issue on DigitalOcean (512 MB). Though, the installation magically ran after restarting the server and trying again several times.

**Comment by stefanpenner** [comment]
Hmm. Ya worth looking into this.

This may be s result of upgrading npm, maybe it changed how is decompresses stuff. 

We have plans to decrease the overall file size and dependencies. The biggest offender is bower, and although it is on the chopping block we have more work to do.

**Comment by stefanpenner** [comment]
Hmm. Ya worth looking into this.

This may be s result of upgrading npm, maybe it changed how is decompresses stuff. 

We have plans to decrease the overall file size and dependencies. The biggest offender is bower, and although it is on the chopping block we have more work to do.

**Comment by stefanpenner** [comment]
I did notice cloud9 is using npm 1.3.x by default, upgrading to 2.x is recommended

```
npm install -g npm
```

**Comment by stefanpenner** [comment]
Ya, so i have confirmed it is totally because of the single large tarbal due to bundling. Likely primarily a problem cause by bower.

The issue that resulted in us bundling, was just the shear number of requests we had to make to satisfy an ember-cli install. The best solution is dropping the largest dependency, `bower` which we hope to drop soon. Until then it is a tricky situation.

We can try another release with `bower` unbundled and see if `npm` can handle the number of additional requests this time. (I suspect it is possible)

**Comment by BiosElement** [comment]
If anyone needs testing done for this, I'd be happy to lend my time towards helping fix this.

**Comment by kidGodzilla** [comment]
I got this running on cloud9 on a plan with upgraded ram (1024mb). I'm not sure if that's available in their free account or if that helps anyone.

**Comment by ponchoblesa** [comment]
I managed to have ember on cloud9 with 512mb. I've just copied manually all the files of one ember-cli already installed where cloud9 stores the node modules, create manually the symbolic links and set the correct permissions. It is a hack, but worked for me.

I developed one script to do this with one ember 0.2.6. Type in console:

`wget -qO- http://www.bleasy.net/resources/ember_c9.sh | bash`

I hope this helps.

**Comment by ranmocy** [comment]
There is a way to limit how many memory nodeJS can use described here: https://github.com/joyent/node/wiki/FAQ#what-is-the-memory-limit-on-a-node-process
And npm is just a JS script.

Which means you can do this:
```bash
~/.nvm/v0.10.35/bin/node --max_old_space_size=256 ~/.nvm/v0.10.35/bin/npm install -g ember-cli
```
For node v0.12.7, size 275 barely works.

Problem. Solved.

**Comment by stefanpenner** [comment]
@ranmocy I suspect installing with `npm` v3 will also help dramatically, our friends over at azure (cc @felixrieseberg) have had great success with v3 keeping memory down while installing.

**Comment by ranmocy** [comment]
@stefanpenner I tried but still be killed.
Though it do help. For node v0.12.7 and npm v3.0, memory limit 256mb works.

For who may have interest in v3, here is the code `npm install -g npm@3.0-latest`

**Comment by stefanpenner** [comment]
`npm v3` seems to sort out this issue nicely. Ember-cli itself works with v3, addons that don't should be reported to the addon in question

**Comment by omouse** [comment]
I installed npm v3.3.5 and have 512MB of RAM, still getting an issue with this.

I tried it again and set the memory limit to 512:

```
node --max_old_space_size=512 $(which npm) install -g ember-cli
```

And it still gets killed.

I'm running this on Cloud9 IDE and I'm not sure what I can do to make it work aside from packaging up ember-cli from another VM or increasing RAM to 1gb.

**Comment by kellyselden** [comment]
Does `npm install -g ember-cli --no-optional` help?

**Comment by omouse** [comment]
@kellyselden still an issue, it worked for a few seconds longer. Not sure what the acceptable solution is. I'm wondering how npm installs are working in small docker containers if I'm struggling on a VM that has 512mb RAM.

**Comment by akhayoon** [comment]
@stefanpenner I'm using npm v3 and the same issue is still happening on cloud9. Could you please re-open the issue?

**Comment by omouse** [comment]
@akhayoon my solution is to avoid ember-cli and just use ember starter kit (and if I need ember-cli I'm going to go with a local VM that has enough RAM, too cheap to upgrade my cloud9 vm)

**Comment by royels** [comment]
For anyone else who arrives to this thread for the same problem, upgrading to 1 GB RAM and npm v3 did solve it for me. (Running on a Digitalocean droplet)

**Comment by stefanpenner** [comment]
about to give this a whirl again, now that we are no longer bundling deps...
