### ISSUE TITLE
Using .property() while developing component for an addon 

### ISSUE THREAD

**Issue by BenjaminHorn** [ember-cli/ember-cli#3774]
Today I encountered a wired issue while developing an addon.
```
ember addon property-check-addon
cd property-check-addon/
property-check-addon$ ember g component tm-button
version: 0.2.2
installing
  create addon/components/tm-button.js
  create addon/templates/components/tm-button.hbs
installing
  create tests/unit/components/tm-button-test.js
installing
  create app/components/tm-button.js
```

After that I tried to start the server, but it needs a template compiler:

*An `addon/templates` tree was detected, but there are no template compilers registered for `property-check-addon`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `property-check-addon`'s `package.json`.*

After this, server starts.
**tests/dummy/app/templates/application.hbs**
```
{{tm-button}}
```

**addon/components/tm-button**
```javascript
import Ember from 'ember';
import layout from '../templates/components/tm-button';

export default Ember.Component.extend({
  layout: layout,
  tagName: 'button',
  classNames: ['btn'],
  classNameBindings: ['typeName'],
  typeName: function(){return "foo";}.property()    // <-debuger underlines here
});
```
causing 
*Uncaught TypeError: undefined is not a function*.

There is an additional error line in the Chrome console: 
*VM86:1006 Uncaught TypeError: undefined is not a function*

Which leads back to:
**ember-debug/libs/source-map**
```javascript
      sourceMapCache: function() {
        return {};
      }.property(),
```

The same code works as expected here http://emberjs.jsbin.com/tanowekezo/1, and if I make the same component in ember **app**, but not in an **addon**.

**Comment by stefanpenner** [comment]
This is expected, ember-addons are built/run with prototype extensions disabled. As extensions are meant to be shared not all consumers run with extensions enabled.

Ember itself is going to move away from prototype extensions entirely, although that will take some time.

```js
function() { }.property('foo');
```

```js
Ember.computed('foo', function() { })
```

**Comment by rwjblue** [comment]
Take a look at http://guides.emberjs.com/v1.11.0/configuring-ember/disabling-prototype-extensions/ for more details.

**Comment by BenjaminHorn** [comment]
Thank you! It makes absolutely sense.

**Comment by stefanpenner** [comment]
thanks @rwjblue
