### ISSUE TITLE
ember new app --blueprint [github-repo-url] broken

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3777]
Doing this:

```sh
ember new my-app --blueprint https://github.com/knownasilya/app-blueprint
```

Getting this:

```no-highlight
version: 0.2.2
Unknown blueprint: /Users/iradchenko/sandbox/https:/github.com/knownasilya/app-blueprint
```

similar with: `--blueprint github.com/knownasilya/app-blueprint` and `--blueprint knownasilya/app-blueprint`.

**Comment by knownasilya** [comment]
Works with a path though.

**Comment by knownasilya** [comment]
Looks like issue in `models/command.js` `parseArgs` method returns invalid blueprint value after parsing.

**Comment by stefanpenner** [comment]
> Looks like issue in models/command.js parseArgs method returns invalid blueprint value after parsing.

seems like this is something `nopt` is doing

**Comment by knownasilya** [comment]
Yes, just got there :+1:

**Comment by knownasilya** [comment]
Looks like the check `isGitRepo` is wrong?

```no-highlight
'https://github.com/knownasilya/app-blueprint'
> isGitRepo(val)
```

**Comment by knownasilya** [comment]
Url **has** to be of the form `git+https://github.com/knownasilya/app-blueprint`

**Comment by stefanpenner** [comment]
> Url has to be of the form git+https://github.com/knownasilya/app-blueprint

ya, but thats lame :P

**Comment by stefanpenner** [comment]
> Url has to be of the form git+https://github.com/knownasilya/app-blueprint
> ya, but thats lame :P

see any reason why we couldn't remove the `git+` and just assume something like a URL is gittable?

**Comment by knownasilya** [comment]
Something like `(/^((git\+)*(ssh|https?))?:\/\//i).test('git+https://github.com/knownasilya/app-blueprint')`?

**Comment by knownasilya** [comment]
Maybe add git:// while we're at it as well.

**Comment by stefanpenner** [comment]
lets make

`git://` and `https://` both work, no need to do `git+https` as we only support git downloads anyways.

**Comment by stefanpenner** [comment]
@knownasilya can you also make `user@host.com:path/to/file` work?

`/.*\@.*:/` may be enough?

**Comment by knownasilya** [comment]
Maybe it'd be worthwhile to create an npm module to do this.

**Comment by stefanpenner** [comment]
> Maybe it'd be worthwhile to create an npm module to do this.

Ya, very likely. Do you want do our should I?

**Comment by knownasilya** [comment]
@stefanpenner I think I'll tackle it this weekend, with tests and all.

**Comment by stefanpenner** [comment]
> @stefanpenner I think I'll tackle it this weekend, with tests and all.

awesome.

**Comment by knownasilya** [comment]
Actually looks like it's done already.. https://www.npmjs.com/package/is-git-url

**Comment by stefanpenner** [comment]
> Actually looks like it's done already.. https://www.npmjs.com/package/is-git-url

:shipit:

**Comment by knownasilya** [comment]
Bah, it requires a `.git` postfix..
