### ISSUE TITLE
OSX CI

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3783]
- [ ] lets hope travis is able to enable this for us.

**Comment by stefanpenner** [comment]
@drogus any way we can get on the OSX stuff?

**Comment by stefanpenner** [comment]
maybe some-day Travis will hook us up. cc @drogus

**Comment by drogus** [comment]
Sorry for no reply, I screwed up my e-mail filters and most of the GitHub notifications were archived. Do you still want to try testing on OSX?

**Comment by stefanpenner** [comment]
@drogus yes sir :)

**Comment by drogus** [comment]
@stefanpenner I enabled it yesterday and I see that new builds are already built on OSX. Let me know if you need any further help with that.

**Comment by stefanpenner** [comment]
@drogus awesome thanks. Looks like we are having some quirks with phantomjs, but likely nothing we cant sort out.

I'll let you know if we hit some wall.
