### ISSUE TITLE
component simple parameter / argument

### ISSUE THREAD

**Issue by sbounmy** [ember-cli/ember-cli#3788]
Hello!

In ember 1.8.X I was able to use a component with a string argument: 
```js
{{icon 'clock'}}
// or even
{{icon 'clock' class='big'}}

// vs (component way) 
{{f-icon name='clock}}
```
This was possible by creating a component and registering it as a helper:
```js
// app/components/f-icon.js
export default Ember.Component.extend({
  tagName: 'i',
  classNames: ['fa'],
  classNameBindings: ['iconName'],
  layout: Ember.Handlebars.compile('{{yield}}'),

  iconName: function() {
    return 'fa-' + this.get('name');
  }.property('name')
});

//app.js
import fIcon from 'my-app/components/f-icon';

Ember.Handlebars.registerHelper('icon', function(name, options) {
  options.hash.name = name;
  return Ember.Handlebars.helpers.view.call(this, fIcon, options);
});
```

As stated in ember-cli, helpers need to use ``registerBoundHelper``, by doing so ```Ember.Handlebars.helpers.view.call(this, fIcon, options);``` return an ```undefined function error```

I would appreciate if anyone can give me an insight on this,

Thanks!

**Comment by stefanpenner** [comment]
This doesn't seem like an ember-cli issue, stackoverflow of the forms are likely better places to ask for help. (we need to keep this tracker focused).

If you post to stackoverlfow, and cross link here. I will gladly answer you question.
