### ISSUE TITLE
Linting error in generated app.js

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3793]
When running ESLint in a newly generated app I get the following error:

```
app.js
  8:0 error All "var" declarations must be at the top of the function scope vars-on-top
```

This can be fixed by moving the app declaration to the top of the file.

**Comment by rwjblue** [comment]
I am not opposed to a pull request fixing, but it seems like a somewhat silly rule...

**Comment by jonathanKingston** [comment]
@rwjblue it can be a little, in this case it is a little pedantic however it prevents declaring a variable down the block and relying on hoisting.

This is the only one I have found so far so have been meaning to raise it for a while (It wasn't until someone asked me about it when using ember-cli-eslint that I decided to raise).
