### ISSUE TITLE
Improve internal docs.

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3805]
http://inch-ci.org/github/ember-cli/ember-cli/branch/master

**Comment by trabus** [comment]
Odd that it isn't picking up the blueprint model, that's probably got the most documentation of any file in the project.

**Comment by stefanpenner** [comment]
@trabus strange.. we can report to them? Maybe it can't parse something

**Comment by trabus** [comment]
So they found one part of the issue and is working on a few others, but the report is looking much better!

**Comment by stefanpenner** [comment]
> So they found one part of the issue and is working on a few others, but the report is looking much better!

:)

**Comment by stefanpenner** [comment]
ongoing effort
