### ISSUE TITLE
`ember update` doesn't roll back to previous version on failure

### ISSUE THREAD

**Issue by tlantz** [ember-cli/ember-cli#3813]
Here are the steps to reproduce (on OSX):

- Install ember-cli as sudo
- Later run ember update when a new version is available without sudo
- This should error with an access violation

    $ ember update
    version: 0.2.0
    Could not find watchman, falling back to NodeWatcher for file system events
    
    A new version of ember-cli is available (0.2.2). To install it, type ember update.
    
    A new version of ember-cli is available (0.2.2).
    [?] Are you sure you want to update ember-cli? Yes
    Updating ember-cli...
    There was an error – possibly a permissions issue. You may need to manually run npm install -g ember-cli.
    EACCES, unlink '/usr/local/lib/node_modules/ember-cli'
    Error: EACCES, unlink '/usr/local/lib/node_modules/ember-cli'
    at Error (native)

Expected: I can rerun sudo ember update using the last version of ember cli installed. 
Actual: ember is no longer installed at all. 

    $ ember
    -bash: /usr/local/bin/ember: No such file or directory

**Comment by abuiles** [comment]
@tlantz please see the comment here https://github.com/ember-cli/ember-cli/issues/3429#issuecomment-77420638  and here http://www.ember-cli.com/#npm-package-management-with-sudo

Basically, don't use npm with sudo.. the following is a great tutorial to install npm without sudo http://www.wenincode.com/installing-node-jsnpm-without-sudo/

**Comment by tlantz** [comment]
Got it. It might be nice, if possible, to have the installation error out or warn initially if sudo is used in this case (though perhaps that's more of an npm thing than ember-cli). 

Thanks!
