### ISSUE TITLE
switch from string-concat to estemplate for blueprints

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3815]
https://github.com/estools/estemplate

- [ ] estemplate needs to be upgraded to use babel's acorn

Why?

- string concat of blueprints doesn't ensure we emit actual JS
- better composition
- stuff like this: https://github.com/ember-cli/ember-cli/blob/master/blueprints/adapter/index.js#L16
- this may unlock our ability to blueprint code based on the style or .editorconfig of the current project

questions:

- do we need to compose some additional helpers  to make composition somewhat more ergonomic.

cc @RReverser @thejameskyle

**Comment by stefanpenner** [comment]
@trabus / @jgwhite this may interest you.

**Comment by sebmck** [comment]
> estemplate needs to be upgraded to use babel's acorn

Not sure how practical that is. It'd require doing `require("babel-core").acorn;`

**Comment by stefanpenner** [comment]
> Not sure how practical that is. It'd require doing require("babel-core").acorn;

the goal is just to be sure to support the same syntax as babel

**Comment by RReverser** [comment]
If @sebmck doesn't mind, I'd just wish to have features backported to Acorn itself, so that commonly used ES7 stuff could be used by any Acorn consumer. As for JSX and so, I don't think you guys want to have "the same syntax support" here :)

**Comment by stefanpenner** [comment]
this will be a nice to have, but not really a short term bug we will tackle.

If someone has time and is motivated, this would be a great addition.

**Comment by RReverser** [comment]
I kinda love issues which can be closed after some amount of time without any action needed :P

**Comment by stefanpenner** [comment]
> I kinda love issues which can be closed after some amount of time without any action needed :P

i've been thinking of writing a bot, that assigns issues a half-life based on interaction and labels. Eventually they decay to some threshold and get closed, and finally closed for comments.

**Comment by RReverser** [comment]
> and finally closed for comments

Do they bother that much? Why not just leave them for re-opening later?

**Comment by stefanpenner** [comment]
> Do they bother that much? Why not just leave them for re-opening later?

On popular repo's yes, its noise that often hides more important issues. Making it hard for others to triage.

**Comment by RReverser** [comment]
Too bad GitHub doesn't remember filters for repos, that could help.

**Comment by stefanpenner** [comment]
> Too bad GitHub doesn't remember filters for repos, that could help.

Ya absolutely, better tooling to "ice-box" would be great. Although typically, a filter of aging out is likely fine. Massive backlogs that never get completed are toxic. 

If something has gone stale, and not reopened it may be terribly significant.

**Comment by trabus** [comment]
Sorry, I missed this the first time around. I'm all for this, but don't have time for it atm.
