### ISSUE TITLE
Autocompiling when contents of a symlink directory are changed

### ISSUE THREAD

**Issue by jdmaurer** [ember-cli/ember-cli#3819]
I am working on a front-end project where a base styleguide project is separated as its own thing, and reused across multiple apps (to maintain a consistent styleguide). I need the Ember project to recompile when a file is changed in the Styleguide project (I'm importing the global stylesheet into ```app.scss```). I tried creating a symlink to the styleguide directory in ```app/styles/``` so it would detect changes, but when a file is changed in the styleguide, it does not recompile. It works if I restart the ember server, but that is a pain to do after every change in the styleguide.

I can't use ```app.import``` in ```Brocfile.js```, because I need the SCSS imported rather than the CSS (to reuse variables defined in the styleguide).

Is there a better way to do this, or is there a bug that prevents ember-cli/broccoli from detecting changes in symlinks? Enlighten me.

**Comment by steveax** [comment]
We have a similar setup. Kinda kludgy, but when working on the addon styles, I npm link the styles addon and then have a simple watcher in the addon that `touch`es the host app's main sass file when changes are made to the addon. Would love to have a better solution.

**Comment by stefanpenner** [comment]
not something currently supported, but will re-visit in the future.
