### ISSUE TITLE
Defining `availableOptions` on a custom blueprint does not work

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#3824]
User generated custom blueprints with `availableOptions` defined currently do not register their `availableOptions` with the generate command. 

Given a blueprint in the following example, the `--user-type` option (along with `-basic` and `-paid` aliases) should be available in the generate command.
```
// custom-acceptance-test
module.exports = {
    description: 'Custom Acceptance Test',
    availableOptions: [
        {
            name: 'user-type',
            type: String,
            values: ['basic', 'paid'],
            default: 'paid',
            aliases:[
                {'basic': 'basic'},
                {'paid': 'paid'}
            ]
        }
    ]
}
```
`ember g custom-acceptance-test foo -basic` should pick up the command option, but currently does not. 

This is due to the `lookupBlueprint` method failing in the `beforeRun` hook, since the paths for project blueprints are not included (my fault btw). The lookup should follow the pattern used by the `generate-from-blueprint` task, as it properly includes the project blueprint paths.

Expect a PR tonight. :)

**Comment by AO16** [comment]
:+1:
