### ISSUE TITLE
Incorrect layout path in nested component

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3828]
When generated a nested component using ember-cli the templates reference is incorrect:
```
ember g component dir/nested-component
```
The layout path is:
```
../templates/dir/nested-component.hbs
```
Instead of:
```
../../templates/dir/nested-component.hbs
```

**Comment by rwjblue** [comment]
This was reported with an earlier version of ember-cli, but it was my impression that it is fixed in 0.2.2 and above. Can you tell us what version you are using?

**Comment by olivierlesnicki** [comment]
`0.2.0`

**Comment by rwjblue** [comment]
Awesome: the good news is that you can update to 0.2.3 and it's all fixed!

**Comment by olivierlesnicki** [comment]
Thanks @rwjblue
