### ISSUE TITLE
The 'component-test' blueprint does not support generating inside addons.

### ISSUE THREAD

**Issue by martndemus** [ember-cli/ember-cli#3829]
Same for goes for all `*-test` generators.

I suspect #3690 is the culprit which introduced this. Particularly the following:

[/lib/models/blueprint.js](https://github.com/ember-cli/ember-cli/blob/a18d9c0ad7741874ca37d8516546dacb6925ccaf/lib/models/blueprint.js#L734)
```javascript
Blueprint.prototype.supportsAddon = function() {
  return this.files().join().match(/__root__/);
};
```

As test generators don't include `__root__` in their path name.

**Comment by trabus** [comment]
I'll get right on this, should be an easy fix. I missed it because the generate tests don't check for generating tests by themselves, they're generated along with the file they're testing.

**Comment by mihai-scurtu** [comment]
This may or may not be related, but I also can't use `ember generate lib <foo>` and get the same error.

I may be wrong, but wouldn't `/addon/lib/` be the place to put auxiliary "classes"?

**Comment by trabus** [comment]
Yes, this is related. See my comments on [#3840](https://github.com/ember-cli/ember-cli/issues/3840#issuecomment-91663904)
