### ISSUE TITLE
ember g route anything/index

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#3834]
This "works," but doesn't add a function definition to `this.route` so that it actually renders.

**Comment by abuiles** [comment]
Seems like we need this https://github.com/ember-cli/ember-cli/blob/master/blueprints/route/index.js#L55  to be /^index$/

**Comment by abuiles** [comment]
We could be more smart about it, if the route name is index, then we just need to include the empty function. 

```
this.route('anything', function() {})
```
