### ISSUE TITLE
ember update is failing with an error

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#3835]
![screen shot 2015-04-07 at 4 42 38 pm](https://cloud.githubusercontent.com/assets/18524/7033042/2b310658-dd45-11e4-9ecd-95f5ea214687.png)

**Comment by bcardarella** [comment]
I think this might be my dev environment. Node is bombing out on everything right now. I have v0.12.0 and tried uninstalling/install ember with npm nombom and now I'm getting 
![screen shot 2015-04-07 at 4 50 42 pm](https://cloud.githubusercontent.com/assets/18524/7033166/438c725e-dd46-11e4-9154-ad4ee53761d7.png)

**Comment by stefanpenner** [comment]
i believe ember update failed midflight and put your node_modules in a bad state.

im surprised nombom didn't fix it.

**Comment by bcardarella** [comment]
I'm going to try `sudo rm -rf /` and report back my results

**Comment by stefanpenner** [comment]
> I'm going to try sudo rm -rf / and report back my results

rofl

**Comment by stefanpenner** [comment]
@bcardarella you may have run out of file handles, watchman currently leaks them. (FB as a different use case)

my extremely short term solution: https://gist.github.com/stefanpenner/1a215bc10257d10a7cfd
short term solution will land soon hopefully: https://github.com/facebook/watchman/pull/93#issuecomment-90726780
long term solution, i have gotten reopened: https://github.com/facebook/watchman/issues/63#issuecomment-89072998

**Comment by stefanpenner** [comment]
closing, unless the fixing of npm/node didn't fix it.
