### ISSUE TITLE
ember init stomps all over packages.json. Diffing is harder than necessary

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#3837]
I'd like to rewrite ember init to preserve the application's dependencies and only update ember-cli dependencies. I've looked through the source and can't see how it works. I think `npm-install.js` has something to do with it but I can't see where `options.packages` comes from, or where the code is that overwrites `packages.json`

Can anyone guide me so I can make a PR?

**Comment by stefanpenner** [comment]
> I'd like to rewrite ember init to preserve the application's dependencies and only update ember-cli dependencies.

we need to figure out how to disambiguate these.

**Comment by Twinkletoes** [comment]
27 seconds - this must be a record!
I was planning to load the file as an object, load the required packages as an object, then merge then using magic fairy dust

**Comment by Twinkletoes** [comment]
keep anything that's not in the cli packages.json untouched

**Comment by stefanpenner** [comment]
so we can like do:


* don't remove keys the user has added
* keep the contents of dependencies alphabetical
* read: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L21-L35 as the only deps we update.

**Comment by Twinkletoes** [comment]
sounds like a plan. I'd even say try not to touch the user's ordering, so that a diff is much easier to read.

**Comment by Twinkletoes** [comment]
so is the code for ember init in a blueprint?

**Comment by abuiles** [comment]
@Twinkletoes @stefanpenner the following in the blueprint model could be useful https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L869

We could include package.json only if it is not present, and then call `addPackagesToProject`

**Comment by Twinkletoes** [comment]
Maybe I'm just being stupid but I can't find any documentation on how to build a blueprint that does something more than copy some files - where should I be looking?

**Comment by abuiles** [comment]
@Twinkletoes check the file linked above :)

**Comment by Twinkletoes** [comment]
Is there a docs page that goes with it?

**Comment by Twinkletoes** [comment]
ok, I found the init blueprint tests, but I can't find the init blueprint itself. Where's the code that builds the tree and decides what to install? The code you linked to appears (to me) to just be a generic blueprint example

**Comment by trabus** [comment]
@Twinkletoes there is actually no init blueprint, it is using the current `app` blueprint and installing over the existing project, prompting at each file.

**Comment by Twinkletoes** [comment]
so that's in blueprints/app/index.js?

**Comment by Twinkletoes** [comment]
Hmm - autotest appears not to like ember-cli. Any ideas? Google, she know not anything.

```
G:\Projects\ember-cli>autotest
[autotest] running tests
G:\nodejs\node_modules\autotest\autotest.js:57
                process.chdir(pwd);
                        ^
Error: Bad argument.
    at Error (native)
    at startTests (G:\nodejs\node_modules\autotest\autotest.js:57:11)
    at Object.<anonymous> (G:\nodejs\node_modules\autotest\autotest.js:230:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by stefanpenner** [comment]
> Hmm - autotest appears not to like ember-cli. Any ideas? Google, she know not anything.

this is not supported

**Comment by Twinkletoes** [comment]
> this is not supported

The docs need an edit then...?

<h2>Working with the tests</h2>

Use `npm run autotest` to run the tests after every file change (Runs only fast tests). Use `npm test` to run them once.

**Comment by Twinkletoes** [comment]
How do you debug tests?

**Comment by stefanpenner** [comment]
> How do you debug tests?

@Twinkletoes https://nodejs.org/api/debugger.html  + https://github.com/ember-cli/ember-cli/blob/master/package.json#L13 +  http://jaketrent.com/post/run-single-mocha-test/

**Comment by Twinkletoes** [comment]
Ta

**Comment by jonathanKingston** [comment]
I was thinking of this today actually. Package by package removal and additions might be more relevant perhaps in the tool?

**Comment by Twinkletoes** [comment]
I'm working on a PR - will take me some time though - lots of tests to write

**Comment by rwjblue** [comment]
@Twinkletoes - This likely should go through an RFC so that we can generally agree on direction first.  I'd hate for you to spend a bunch of time on one avenue, only to have to change out the implementation later for something else after review.

**Comment by tim-evans** [comment]
Could we make the dependency lists always be in alphabetic order as a start? I think that's a reasonably sane default.

**Comment by stefanpenner** [comment]
We do typically insert them this way.

**Comment by tim-evans** [comment]
Yes, but there's a few out of place every once in a while. The friction of updating ember-cli stems mostly from the updating the dependencies in bower.json and package.json. The rest of ember init is noise to me.

**Comment by stefanpenner** [comment]
> Yes, but there's a few out of place every once in a while. The friction of updating ember-cli stems mostly from the updating the dependencies in bower.json and package.json. The rest of ember init is noise to me.

we should add a test to ember-cli test suite that ensures these remain alphabetical

**Comment by stefanpenner** [comment]
> The friction of updating ember-cli stems mostly from the updating the dependencies in bower.json and package.json.

although i suspect most people screw this up themselves by not using the tooling npm/bower to insert/remove/upgrade entries

**Comment by tim-evans** [comment]
@stefanpenner :heart: thanks for the task
