### ISSUE TITLE
console.log('a', b) in test files is not supported

### ISSUE THREAD

**Issue by mgenev** [ember-cli/ember-cli#3838]
When I try that and run `ember test`, just 'a' logs out.

With the huge outputs from tests and no keyword to ctrl+f and grab what I'm trying to log out, debugging is quite difficult.

**Comment by stefanpenner** [comment]
> When I try that and run ember test, just 'a' logs out.

`b` is likely `undefined` so it wont log

**Comment by mgenev** [comment]
I was using the https://www.npmjs.com/package/ember-sinon Module
Sinon did turn out to be available, I also tried with the `moduleFor`  function as `b`, same behavior

**Comment by mgenev** [comment]
Example file I'm logging in:

```
import {
    moduleForComponent,
    test
} from 'ember-qunit';

import { initialize } from '../../../../../initializers/ember-moment';

console.log('TEST123 ', moduleForComponent);

moduleForComponent('event-card', 'EventCardComponent',  {integration: true});
```

And example Output
```
ok 1 PhantomJS 1.9 - JSHint - adapters: adapters/application.js should pass jshint
    ---
        Log: >
            TEST123 
    ...
ok 2 PhantomJS 1.9 - JSHint - .: app.js should pass jshint
```

**Comment by rwjblue** [comment]
https://github.com/airportyh/testem/pull/536 should fix

**Comment by stefanpenner** [comment]
Nice @rwjblue
