### ISSUE TITLE
Add support for package removal in blueprints

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#3841]
I would like to add the feature of removing packages in blueprints like this:
```
this.removePackageFromProject('ember-cli-qunit');
```

As per the discussion here:
https://github.com/switchfly/ember-cli-mocha/pull/47#discussion_r27931596

**Comment by stefanpenner** [comment]
I think I would prefer if addons didn't automatically remove dependencies. I think it is often far to ambiguous to do this reasonably.

Rather, I believe add-ons should provide health-checks that could be used by the `ember doctor` idea https://github.com/ember-cli/ember-cli/pull/3193

Basically, I don't feel we can haphazardly remove dependencies.

**Comment by jonathanKingston** [comment]
Yup I agree, I had not spotted the `registerDiagnostics` hook for Ember Doctor.

This is probably worth deprecating as soon as that lands I think.
