### ISSUE TITLE
suddenly lost all support for ember generate in addons in 0.2.3

### ISSUE THREAD

**Issue by foxnewsnetwork** [ember-cli/ember-cli#3860]
Starting in 0.2.3 , all commands under the generate namespace in ember are now broken for addon developers. For example, upon running:
```bash
ember generate acceptance-test dog-food
```
I am now greeted with:
```
The 'acceptance-test' blueprint does not support generating inside addons.
```
This is probably intentional on the part of ember-cli since occasionally the generated blueprints would be wonky, but slightly broken functionality is still by far superior to no functionality whatsoever, so is there any chance we can get ember generate in addons back?

If EmberJS is modern China, then being an app developer is analogous to being a government bureaucrat while being an addon developer is analogous to being a farmer. Despite the fact literally everyone in China must eat (use addons), the farmers (addon publishers) are the second class citizens (unpaid junior programmer) of China (EmberJS) and looked down upon with much disdain. In addition, we are denied basic human rights (access to prototype extensions), and if we work up the courage to escape to Canada (AngularJS) or the United States (ReactJS), we find that everything we've done is now defunct and we have to start all over again at the bottom by working at a foot massage parlor in San Gabriel, CA (building hello world programs in our spare time) while learning Spanish (JSX) or Canadian English (appending ng-, "directives", "transclusion", etc).

**Comment by stefanpenner** [comment]
i suspect https://github.com/ember-cli/ember-cli/pull/3845 fixes this

**Comment by trabus** [comment]
@stefanpenner confirm.

**Comment by spruce** [comment]
Also I can not install ember-cli-github-pages. I don't know whether it has to do something with this issue or can be fixed by ember-cli-github-pages. Just wanted to ask that.

Thanks for the help in advance.

**Comment by eccegordo** [comment]
> If EmberJS is modern China, then being an app developer is analogous to being a government bureaucrat while being an addon developer is analogous to being a farmer. Despite the fact literally everyone in China must eat (use addons), the farmers (addon publishers) are the second class citizens (unpaid junior programmer) of China (EmberJS) and looked down upon with much disdain. In addition, we are denied basic human rights (access to prototype extensions), and if we work up the courage to escape to Canada (AngularJS) or the United States (ReactJS), we find that everything we've done is now defunct and we have to start all over again at the bottom by working at a foot massage parlor in San Gabriel, CA (building hello world programs in our spare time) while learning Spanish (JSX) or Canadian English (appending ng-, "directives", "transclusion", etc).

@foxnewsnetwork I just have to say I really +1 this comment. Very well done!
Also clever screen name.

**Comment by leojh** [comment]
Seems to be working as of 0.2.5
