### ISSUE TITLE
Apps in server subdirectories (http://myhost/ember-app/index.html) - Uncaught UnrecognizedURLError

### ISSUE THREAD

**Issue by sandreas** [ember-cli/ember-cli#3861]
Hello,

i am trying to deploy an ember application in a subdirectory (e.g. http://myhost/ember-app/index.html) and i am getting following error:

```
Uncaught UnrecognizedURLError: /index.html
```
No further info. Deploying to http://ember-app/index.html works as expected. So it seems to have something to do with the subpath.

Environment:
- Microsoft IIS 7.5
- ember-cli 0.2.3

Steps to reproduce:

```
1.) create a new ember app 
cd C:/inetpub/wwwroot
ember new test-app

2.) deploy app
cd test-app
ember build

3.) open test-app in browser
http://localhost/test-app/dist/index.html
```

Removing or correcting "baseURL" to /test-app/dist in config/environment.js has no effect.
I traced things back to the recognizer, which seems to have no valid return value:

```javascript
    // [...]
    // path param contains "/index.html"
    recognize: function(path) {
        var states = [ this.rootState ],
            pathLen, i, l, queryStart, queryParams = {},
            isSlashDropped = false;

        queryStart = path.indexOf('?');
        if (queryStart !== -1) {
          var queryString = path.substr(queryStart + 1, path.length);
          path = path.substr(0, queryStart);
          queryParams = this.parseQueryString(queryString);
        }

        path = decodeURI(path);

        // DEBUG GROUP path

        if (path.charAt(0) !== "/") { path = "/" + path; }

        pathLen = path.length;
        if (pathLen > 1 && path.charAt(pathLen - 1) === "/") {
          path = path.substr(0, pathLen - 1);
          isSlashDropped = true;
        }

        for (i=0, l=path.length; i<l; i++) {
          states = recognizeChar(states, path.charAt(i));
          if (!states.length) { break; }
        }

        // END DEBUG GROUP

        var solutions = [];
        for (i=0, l=states.length; i<l; i++) {
          if (states[i].handlers) { solutions.push(states[i]); }
        }

        states = sortSolutions(solutions);

        var state = solutions[0];

        if (state && state.handlers) {
          // if a trailing slash was dropped and a star segment is the last segment
          // specified, put the trailing slash back
          if (isSlashDropped && state.regex.source.slice(-5) === "(.+)$") {
            path = path + "/";
          }
          return findHandler(state, path, queryParams);
        }
      }
    // [...]
```

**Comment by stefanpenner** [comment]
you likley need to set: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js#L7 for that env

**Comment by sandreas** [comment]
Like I said before:
> **Removing** or **correcting** "baseURL" to **/test-app/dist** in config/environment.js **has no effect**.

Or did I miss something?

**Comment by Octagon** [comment]
I guess the second option is correct, I had to set yet another parameter like

  if (environment === 'production') {
    ENV.baseURL = '/dist/';
    ENV.locationType = 'none';
  }

before I have seen the Ember "Hello World" in a browser at /dist/index.html.

**Comment by sebastienluquet** [comment]
Did you manage to make it works ?

**Comment by GendelfLugansk** [comment]
I had the same problem and locationType: 'none' helped me. Thx, @Octagon

**Comment by Geokoumpa** [comment]
+1 locationType none worked for me too, thanks a lot!

**Comment by irnc** [comment]
Setting `location: 'none'` will make your routes unlinkable, as user navigating to them would not see location in browser's address bar updated.

**Comment by GendelfLugansk** [comment]
@irnc yes, later I noticed this problem and changed my setting to these:

    baseURL: null,
    locationType: 'hash'

Now it works.

**Comment by hemantoswal** [comment]
following entry in config/environment.js worked for me
ember-shares is sub folder name under root

if (environment === 'production') {
    // here you can enable a production-specific feature
	ENV.rootURL = '/ember-shares/'
  }
