### ISSUE TITLE
can't install mutliple bower packages 

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-cli#3864]
I am quite accustomed to installing a Bower dependency in the `afterInstall` hook of the index.js in an addon but I was surprised to see that there was no obvious mechanism to install multiple bower dependencies. 

My first assumption that this should be as easy as: 

    afterInstall: function() {
      this.addBowerPackageToProject('fontawesome');
      return this.addBowerPackageToProject('animate.css');
    }

This seemed to execute both bower commands (output was visible to the command line) but the packages don't actually install! I'm guessing this might not be as synchronous as I was assuming.

I then tried passing an array of packages to the `addBowerPackageToProject` method. Fail. I'm sure the most common use-case is a single dependency package but I think we need some way to do multiple. 

> if I'm just missing something stupid please just let me know

**Comment by rwjblue** [comment]
`addBowerPackageToProject` returns a promise so you have to chain them:

```
afterInstall: function() {
  var blueprint = this;

  blueprint.addBowerPackageToProject('fontawesome')
    .then(function() {
      return blueprint.addBowerPackageToProject('animate.css');
    });
}
```

You should also check out `addBowerPackagesToProject` (see [example](https://github.com/ember-cli/ember-cli-qunit/blob/d6bd438b6e43aa92f6c6a4d628fcc7ed558e8d2f/blueprints/ember-cli-qunit/index.js#L9-L14)).

**Comment by ksnyde** [comment]
Ahhh. I had thought that maybe promises were in the works but general fatigue got in the way of checking. Glad to see this requirement is so well covered. :+1:

**Comment by stefanpenner** [comment]
or use:  `blueprint.addBowerPackagesToProject` which takes an array

https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L919-L953
