### ISSUE TITLE
build fails with ENOENT, no such file or directory

### ISSUE THREAD

**Issue by saitheexplorer** [ember-cli/ember-cli#3870]
I'm migrating an existing app to ember-cli, so I ran `ember init` in the directory. Now I'm trying to run `ember build` just to get the base files working before I refactor my app, but the command keeps failing-

```
Build failed.
ENOENT, no such file or directory '/Users/sgunturi/Projects/bhajan-db/tmp/funnel-dest_noIJv8.tmp/'
```
The exact filename is different each time, but it's the same error.

Running `node@v0.10.36`, `npm@2.7.4`, `ember-cli@0.2.3`.

**Comment by stefanpenner** [comment]
It sounds like you have a unique project upgrading and all. Without an example for me to debug I will likely not be able to help

**Comment by saitheexplorer** [comment]
That's what I thought too, but I overwrote all the files during the init - `package.json` specifically. I didn't have an `app/` dir before either, so anything `ember init` created should be boilerplate, right? At this part of the process, there *theoretically* should be nothing different from my project and a brand new project created with `ember new` - that's what I need help with. Would there be anything different?

**Comment by stefanpenner** [comment]
> Would there be anything different?

a diff tool may help you

**Comment by saitheexplorer** [comment]
Will look into that - thanks

**Comment by pangratz** [comment]
@saitheexplorer I recently had a similar error message which was caused by not having a `app/styles` directory, since I removed this manually as the styles are handled by the parent project. Maybe this helps ...

**Comment by jeradg** [comment]
@pangratz I just ran into this problem, and adding an empty `app/styles` directory solved it. (All of my styles are in the main Rails app, so I had removed the Ember styles app entirely.)
