### ISSUE TITLE
Installing ember-cli is slow

### ISSUE THREAD

**Issue by MichaelVdheeren** [ember-cli/ember-cli#3871]
*Use case:*
We have a CI server (shippable) which installs all dependencies every time. Hence it executes npm install every time installing the ember-cli module.

*Problem:*
This takes a tremendous amount of time and it's size is enormous (75MB). Is there a way to speed this up apart from checking it in our repo?

**Comment by stefanpenner** [comment]
You can symlink ember-cli in as part of your CI script. Obviously check the versions before symlinking you don't want to bring in a stale version 

Long term: the bower dependency makes up the vast majority of file count(which is actually one of the main problems with the performance). We are slowly making progress to drop this dependency entirely.

Both @chadhietala (who's helping with the ember cli side) and @seanpdoyle (who's helping with the ember build and dep side) are making progress. Lots of work to do, but hopefully soon we can shed it as a core dependency

**Comment by MichaelVdheeren** [comment]
I'm mostly interested in the long term. Why not assume people have bower and testem installed? We have a rails app using ember-cli-rails and serving 3  ember-cli apps. It's a fairly high load if we use our CI on that.

But indeed a symlink would do for now and some better ordering of how things are installed such that CI can use the cache more frequently.

**Comment by stefanpenner** [comment]
> I'm mostly interested in the long term. Why not assume people have bower and testem installed?

we did this in the past, but this lead to constant version and integration incompatibilities

**Comment by MichaelVdheeren** [comment]
For info: would it be an option to have sort of a CI build of ember CLI which doens't vontain things like socket.io which take a lot of time to build when installing?

**Comment by seanpdoyle** [comment]
@MichaelVdheeren that sounds like an interesting approach! I'm sure the ember-cli team would be open to such a thing if you'd like to open an issue or a PR: https://github.com/ember-cli/ember-cli/issues

**Comment by stefanpenner** [comment]
Or we can continue to work so we can remove bower entirely. Socket.io comes from testem, but really the c extension isn't needed for this sort of tool, maybe they are interested in exploring sockst.io without the c extension to increase portability

**Comment by seanpdoyle** [comment]
Sorry @MichaelVdheeren I lost context on where this comment lived. 

I thought it was in https://github.com/rwz/ember-cli-rails. 

I sincerely didn't mean to be snarky. :+1:
