### ISSUE TITLE
Component blueprint locals - not accurate pod condition

### ISSUE THREAD

**Issue by gczene** [ember-cli/ember-cli#3875]
Given:
.ember-cli: 

```javascript
{ "usePods": true}
```
The problem: `ember g component XXX` uses the default `templatePath` since the condition in `locals` is
```javascript
    if (options.pod) {
      templatePath = './template';
    }

```
and the passed options object has: 
```javascript
{
....
    pod: false,
   usePods: true
....
}
```
therefore the condition is true only in the case when you pass the `--pod` directly

**Comment by trabus** [comment]
I'll try and look into this later today.

**Comment by gczene** [comment]
@trabus  I guess this https://github.com/ember-cli/ember-cli/pull/3481 covers it, doesn't it ?

**Comment by stefanpenner** [comment]
@trabus has been doing some great work on blueprints and pods, I believe this has been addressed. If not, providing reproduction of the issue on latest will reopen this issue.
