### ISSUE TITLE
[Question] how to run headless tests with ember-cli using firefox and/or chrome?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#3876]
With all the pain associated with phantomjs I'm looking for alternatives to get better feedback during local development. One such option is running firefox or chrome headless using xvfb and testem does support this like so

```
xvfb-run testem -l firefox
xvfb-run testem -l chrome
```

How can you (optionally) configure ember-cli to run firefox or chrome in this way?

**Comment by stefanpenner** [comment]
Ya. It's just another testem runner. 

Interestingly phantomjs 2.0 seems to be way way better, I've been using it lately without trouble

**Comment by toranb** [comment]
Do you still need to build phantomjs 2.0 from source or can you npm install it? If the runner syntax is more of a testem question I'll poke around on that project :)

thanks for the blazing fast reply as always!

**Comment by hhff** [comment]
@toranb can you post ur findings here?  recently hit a stumbling block here

**Comment by stefanpenner** [comment]
If you take a look at rsvp Travis.yml it shows how to download the binary

**Comment by toranb** [comment]
For local development on linux you can get headless firefox (along side phantomjs) like so
```
1) install xvfb (using yum / apt-get / etc)
2) add firefox to your testem.json file
3) xvfb-run ember test --server
```
Not sure how to get xvfb on OSX and a quick search turns up some really wonky hacks.

**Comment by stefanpenner** [comment]
Oh. Cool!
