### ISSUE TITLE
Doesn't refresh if arguments are provided on model

### ISSUE THREAD

**Issue by kronstadt1988** [ember-cli/ember-cli#3878]
Hello:

I have got my model data in Route.js this way and works fine. What the following code does is load the model and next on refresh unload all the records and looking for fresh data using query params

          model : function(){
             return new Ember.RSVP.hash({
             hotTopics: this.store.find('hot-topic')
             });
          },

           refresh:function(){
              var self = this;
              var type = self.controller.get('model.hotTopics').type
              self.controller.get('model.hotTopics').store.unloadAll(type);                
              self.controller.get('model.hotTopics').store.findQuery('hot-topic' , 
                    {
                        periodtype : "lol", sortby : "lolo", touchpointid: "agarg"
                        
                    }
                );

However, if I specify in the model parameters like :

         model : function(){
             return new Ember.RSVP.hash({
             hotTopics: this.store.find('hot-topic',
                {
                        periodtype : "lol", sortby : "lolo", touchpointid: "agarg"        
                })
              });
          },

My model keeps still unloading all the records but not loading them again. The GET request is properly done again but the data is not being introduced in my model again. 

The strange thing is that using Ember Inspector the data is properly loaded again on the model after the unload.

Thank you very much !

Alberto

**Comment by stefanpenner** [comment]
@kronstadt1988 this doesn't appear to be related to ember-cli at all, Rather a question about ember. I suggest opening a stackoverflow question as that is a better venue to ask for this sort of help.
