### ISSUE TITLE
Generated Adapters and Serializers don't inherit properly

### ISSUE THREAD

**Issue by tehviking** [ember-cli/ember-cli#3879]
Currently, generating an adapter inherits from ApplicationAdapter, even if there is no ApplicationAdapter.
Generating a serializer never inherits from ApplicationSerializer, even if there is one.

Here's a cool gif:

![](http://brandonhays.com/Pics/serializer-generator-bug.gif)

**Comment by stefanpenner** [comment]
it should likely generate the application adapter if it depends on it and it is missing.

**Comment by stefanpenner** [comment]
These now live in ember-data
