### ISSUE TITLE
New project init does not satisfy shinkwrap (bower is missing github)

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli#3885]
In a freshly generated 0.2.3 project shrinkwrap cannot run:

![](https://api.monosnap.com/rpc/file/download?id=T9Gq0EvGHFdPiwJP8SaAsjucmjTXZ5)

It appears github is not installed in `node_modules`:

![](https://api.monosnap.com/rpc/file/download?id=PjaKqqgeZy8hhSG35RjArrwGoyNjnR)

Though ember-cli is pinned to `^1.3.12`, `1.4.1` seems to be installed. It would be bizarre if deps for `1.3.12` were still in the pack. Regardless something in the pack seems wrong?

**Comment by stefanpenner** [comment]
This is a bug in npm (which is reported) and master of ember cli moved github to deps so it doesn't get stripped

**Comment by stefanpenner** [comment]
Please confirm with master and report back

**Comment by rwjblue** [comment]
I agree that this is likely fixed, but it is hard to confirm via a normal 'npm link' setup with master (due to the published versions including bundled deps). 

The way to confirm "for real" would be to 'nom && npm pack && npm install -g ./tarball-just-made.tgz'.

**Comment by stefanpenner** [comment]
I confirmed when I fixed. But it is inherently brittle.

We can instead add the shrinkwrap step to our release process and that way ensure we don't get trolled by npm

**Comment by mixonic** [comment]
Great, will try to confirm the fix tomorrow AM. Thanks @stefanpenner

**Comment by stefanpenner** [comment]
I'm hoping to cut 0.2.4 tomorrow evening.  So hopefully it will be ready for you next week

**Comment by mixonic** [comment]
I tried to confirm the fix but could not. However I'm also very uncertain I'm testing this correctly :-/

**Comment by stefanpenner** [comment]
> I tried to confirm the fix but could not. However I'm also very uncertain I'm testing this correctly :-/

what did you try?

**Comment by broerse** [comment]
I don't know if it is related but in 0.2.2 and 0.2.3 `ember new` only works the second time. See:

```
C:\>cd dev

C:\dev>ember new xxxxx
version: 0.2.2
0.2.3

installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
ENOENT, open 'C:\dev\package.json'
Error: ENOENT, open 'C:\dev\package.json'
    at Error (native)

C:\dev>ember new xxxxxx
version: 0.2.2

A new version of ember-cli is available (0.2.3). To install it, type ember upd
e.
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create app/views/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.

C:\dev>
```

**Comment by stefanpenner** [comment]
> I don't know if it is related but in 0.2.2 and 0.2.3 ember new only works the second time. See:

really strange, Im going to add a delay to the `process.chdir` and see if that mitigates this problem. Its really a bummer it doesn't happen every time. That would be easy to fix

**Comment by akappen** [comment]
I am running into the same issue as @mixonic but I also see complaints when I run any npm command.

    $ npm ls
    . . .
    npm ERR! missing: github@^0.2.3, required by bower@1.4.1

I would be happy to test any fixes, but I'm pretty new to npm. If I wanted to install ember-cli from master to get the added github dependency, is this the right upgrade path?

    $ npm uninstall -g ember-cli
    $ npm install -g github:ember-cli/ember-cli
    $ npm install
    $ bower install

Thanks!
