### ISSUE TITLE
Feature Request: Watch npm-linked modules for changes

### ISSUE THREAD

**Issue by kumavis** [ember-cli/ember-cli#3888]
I often develop multiple modules simultaneously.
[`npm link`](https://docs.npmjs.com/cli/link) is very useful for this workflow.
However, I have to manually trigger a refresh for ember-cli / broccoli to rebuild that part of the tree.

Not sure how best to check which deps are npm-linked. They are identified in `npm ls`, and they are implemented as symlinks, so perhaps we could just check `node_modules` for symlinks when starting the build process.

**Comment by stefanpenner** [comment]
this is supported but it is currently opt-in, checkout: https://github.com/ember-cli/ember-cli/blob/0302774001f2218f98815f29c71a22c6e8cb340e/ADDON_HOOKS.md#isdevelopingaddon

I would love to watch all add-ons by default, unfortunately file handles are apparently a scarce resource so we must use them sparingly.

With broccoli 0.15.x we now start having the ability to remove `tmp` from the apps directory, this coupled with future plans to improve our usage of watchman, may unlock the ability for us to just watch everything.

**Comment by kumavis** [comment]
:+1: thanks stef

**Comment by stefanpenner** [comment]
@kumavis  :)

**Comment by xdumaine** [comment]
@stefanpenner is there a way to do this when the npm-linked module is not an ember addon?
