### ISSUE TITLE
git bisect is difficult when npm or bower dependencies change

### ISSUE THREAD

**Issue by kcgolden** [ember-cli/ember-cli#3892]
When using `git bisect`, it is difficult to jump between commits if there were any npm or bower dependencies changed in the interim. I'm having to stop `ember serve`, delete the npm module and bower component directories, then npm install and bower install just to be sure everything is cleaned up.

It would be a lot better if ember serve had the ability to detect changes in bower.json and package.json such that it could handle these gracefully, such as reinstalling the dependencies and then rebuilding the assets accordingly - perhaps simply abstracting the process I described in the first paragraph.

**Comment by Twinkletoes** [comment]
I'd like to see it detect changes in brocfile too

**Comment by kcgolden** [comment]
So - I wonder if there's simply a config that could say "watch these files, if any change, run these commands and restart"

**Comment by stefanpenner** [comment]
Yes this would be cool, and I would love it.

likely once we refactor out the tmp-dir, we will re-visit this.
