### ISSUE TITLE
Addon code in `/app` using conventional structure does not get included when using pods

### ISSUE THREAD

**Issue by runspired** [ember-cli/ember-cli#3893]
As far as I've thus far ascertained, this issue began in ember-cli 0.2.2

When an Ember app is using pods, code within and addon's app directory in the conventional structure (e.g. `app/components` or `app/controllers`) is not included in the final build.

**Comment by stefanpenner** [comment]
@runspired mind providing a repo reproducing, it will make it easier to diagnose

**Comment by stefanpenner** [comment]
pods are being re-worked entirely, the current state will unlikely be getting any such fixes

**Comment by runspired** [comment]
I also haven't hit this since, might have been something that got magically fixed at some point.

**Comment by stefanpenner** [comment]
> I also haven't hit this since, might have been something that got magically fixed at some point.

fingers crossed ;P
