### ISSUE TITLE
Test setup fails with PhantomJS 2.0

### ISSUE THREAD

**Issue by jakemauer** [ember-cli/ember-cli#3894]
Software versions:
* ember-cli: 0.2.3
* PhantomJS: 2.0.0

My basic suite of unit and acceptance tests passes when using PhantomJS 1.9.8. I have a new test that requires some of the fixes present in PhantomJS 2.0.0. I also have `'bail_on_uncaught_errors': true` set in testem.json. 

*Occasionally* the test suite will run and all tests will pass. However 75% of the time on my local machine (OSX 10.10.2) and 100% on CircleCI (running PhantomJS 2.0) the test errors out with something like:

`not ok 1 PhantomJS 2.0 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/test-loader.js, line 3`

or
````
`SyntaxError: Unexpected token '.' vendor.js:38923
````

I've diff'd the vendor.js files from a time when the suite hung and when it ran fully, the files were identical. 

I'm opening the issue here but I realize this also touches testem and PhantomJS itself. I'm working on setting up a demo repo to see if I can replicate it. What else can I provide that would be helpful?

Also, thank you to the ember-cli team for all your work on this project.

**Comment by jakemauer** [comment]
Well chalk this up under "computers are weird and stupid." Turns out a single line of our print stylesheet was breaking PhantomJS. It took me forever to debug because EVERY error I could wring out of PhantomJS pointed at JS problems. 

Anyways, in case someone comes across this same issue, the offending line was 
````
@media 'print {
  * {
       //some print only styles here
    }
  }
````

I'm going to open a bug on the PhantomJS project and see if that leads anywhere. Closing this issue. Thank you again!

**Comment by seawatts** [comment]
@jakemauer did you open up a ticket on phantom? I'm also running into this same issue however. I can't seem to track it down.

**Comment by awochna** [comment]
I'm also running into a similar issue and I have print styles applied to every element.

@jakemauer Was that line offending because:

* PhantomJS seems to have a weird issue with print styles?
* PhantomJS couldn't parse the `'` in your style?
* Something else?

I realize we're approaching a year since you fixed this issue for yourself, but, like @seawatts, I'm having a hard time tracking a very similar error down.

**Comment by wagenet** [comment]
I'm seeing issues too. AFAICT, any @media queries in CSS cause issues.

**Comment by wagenet** [comment]
On further inspection, this issue is intermittent for me. `@media` queries don't appear to be the cause. I suspect this is a Phantom bug, but I'm going to reopen this issue for others to find.

**Comment by stefanpenner** [comment]
> but I'm going to reopen this issue for others to find.

hmm, typically we don't keep issues open that we can't really solve. Is there a reasonable hope we can address this ?

**Comment by wagenet** [comment]
@stefanpenner fair enough. I'm actively investigating this and I might have some ideas for things we can do to solve at least some scenarios. If this stays inactive for long, feel free to close.

**Comment by wagenet** [comment]
In my case, this error happend when trying to `@import` a custom font from Google in my CSS files. Removing this `@import` line causes everything to work correctly. Since I don't really want to remove my custom fonts I did a bit more research and discovered that if I block the request on Phantom's end then things also work fine.

**tests/phantom-runner.js**
```js
// Custom version of the Testem PhantomJS runner.
//   This exists to block requests to fonts.googleapis.com because this can cause
//     Phantom to incompletely load JS files causing bizarre syntax errors.
//   See https://github.com/ariya/phantomjs/issues/14173.
var system = require('system');
var page = require('webpage').create();
var url = system.args[1];
page.viewportSize = {
  width: 1024,
  height: 768
};
// The magic!
page.onResourceRequested = function(requestData, networkRequest) {
  if (requestData.url.match('fonts.googleapis.com')) {
    networkRequest.abort();
  }
};
page.open(url);
```

**testem.js**
```js
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launchers": {
    "AltPhantom": {
      "exe": "phantomjs",
      "args": ["tests/phantom-runner.js"],
      "protocol": "browser"
    }
  },
  "launch_in_ci": [
    "AltPhantom"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};
```

**Comment by wagenet** [comment]
It appears that there may be other things that can cause Phantom to load incorrectly, but it's definitely worth investigating whether your CSS tries to fetch any external resources.

**Comment by les2** [comment]
I feel like you are guaranteed to get this problem if you include an external link (e.g., fonts from googleapis) in your CSS file.

Wish there was a way to make this just work for ember users. This was relatively difficult to debug. :(

**Comment by hhff** [comment]
thanks so much @wagenet - your example worked perfectly!

**Comment by duro** [comment]
@wagenet and @hhff I am attempting this approach but getting:

```
ot ok 1 Browser "PhantomJS tests/phantom-runner.js http://localhost:7357/1114/tests/index.html?hidepassed" failed to connect. testem.js not loaded?
```

Here is my phantom-runner.js

```
// Custom version of the Testem PhantomJS runner.
//   This exists to block requests to fonts.googleapis.com because this can cause
//     Phantom to incompletely load JS files causing bizarre syntax errors.
//   See https://github.com/ariya/phantomjs/issues/14173.
import system from 'system';
import webpage from 'webpage';

const page = webpage.create();
const url = system.args[1];

page.viewportSize = {
  width: 1024,
  height: 768
};

// The magic!
page.onResourceRequested = (requestData, networkRequest) => {
  if (requestData.url.match('fast.fonts.net')) {
    networkRequest.abort();
  }
};

page.open(url);
```

And my `testem.js`:

```
/*jshint node:true*/
module.exports = {
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launchers": {
    "AltPhantom": {
      "exe": "PhantomJS",
      "args": ["tests/phantom-runner.js"],
      "protocol": "browser"
    }
  },
  "launch_in_ci": [
    "AltPhantom"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
};
```

Before trying this approach, I was at least getting the tests to run about 50% of the time. So I know my tests run. Any idea what I am doing wrong?

**Comment by wagenet** [comment]
@duro I haven't seen an error like that before. Sorry.

**Comment by nathanhammond** [comment]
@duro please stop by #-ember-cli in the Ember Community Slack. This likely needs back and forth discussion to help you diagnose. 😄 It may or may not be a bug but there is definitely more investigation required.

**Comment by okachynskyy** [comment]
@wagenet, I have created tests/phantom-runner.js, and I have a linter errors:
`
not ok 667 PhantomJS 2.1 - ESLint | tests: phantom-runner.js
    ---
        actual: >
            false
        expected: >
            true
        stack: >
            http://localhost:7357/assets/tests.js:9585:14
            runTest@http://localhost:7357/assets/test-support.js:3884:34
            run@http://localhost:7357/assets/test-support.js:3870:13
            http://localhost:7357/assets/test-support.js:4076:15
            advance@http://localhost:7357/assets/test-support.js:3529:26
            begin@http://localhost:7357/assets/test-support.js:5341:27
            http://localhost:7357/assets/test-support.js:4455:11
        message: >
            phantom-runner.js should pass ESLint
            
            5:14 - 'require' is not defined. (no-undef)
            6:12 - 'require' is not defined. (no-undef)
        Log: |
    ...
`

**Comment by scottharris86** [comment]
@wagenet you are a hero!!. how did you even begin to figure this out?
