### ISSUE TITLE
ember app default options when environment is not `production`

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3896]
`ember build` sets a number of default options when `environment` is `production` (remove source maps, disable tests, minify css, minify js, etc...). I'm searching for a way to inherits these defaults when `environment` is set to something else, such as `staging`, `pre-production`, `prod` or `live`.

Right now, we're forced to set a proccess.env to distinguish those "target environments" and always set the actual -environment variable to production.

Any recommendations for a better integrated solution?

**Comment by stefanpenner** [comment]
> . I'm searching for a way to inherits these defaults when environment is set to something else, such as staging, pre-production, prod or live.

we do not yet support anything other then dev and production. A future plan configuration overall should unlock this.

**Comment by olivierlesnicki** [comment]
The `isProduction` variable is currently computed as part of the `broccoli/ember-app` constructor. It wouldn't be much of an effort to allow the user to overwrite it through an option.

**Comment by abuiles** [comment]
@olivierlesnicki how's your CI flow? do you roll your own or are you using something like circle/codeship?

**Comment by stefanpenner** [comment]
@olivierlesnicki this isn't something we will add support for. Until the configuration story lands, ember cli has only 2 envs. Anything else needs to be layered on.

**Comment by olivierlesnicki** [comment]
@abuiles we use our own CI flow, and we have multiple test servers for different purposes. Code shipped on the pre-production servers needs to be as close as possible as the one shipped on production servers. However, because they have different API we need to specify different keys and client_ids inside `config/environment`

**Comment by olivierlesnicki** [comment]
@stefanpenner What is the configuration story, and where can we read about/track it? Making EmberApp extendable could maybe help ...

**Comment by rwjblue** [comment]
See https://github.com/ember-cli/ember-cli/pull/2164 for more background (and a work around for now).

**Comment by abuiles** [comment]
Closing, this is something now, and there are other issues related with this too.
