### ISSUE TITLE
Generated addon helper tests failing out of the box in 0.2.3/Master

### ISSUE THREAD

**Issue by clekstro** [ember-cli/ember-cli#3897]
After generating a new helper with `ember g helper data-test` within an addon, the tests immediately fail. Unfortunately, this isn't an assertion-based failure that a developer can recognize as a starting point and recover from.  It appears the generated tests simply fail because they cannot resolve the object under test:

```bash
✘ Died on test #1     at http://localhost:7357/assets/test-support.js:2809
        at http://localhost:7357/assets/test-support.js:5574
        at http://localhost:7357/assets/test-loader.js:31
        at http://localhost:7357/assets/test-loader.js:21
        at http://localhost:7357/assets/test-loader.js:40
        at http://localhost:7357/assets/test-support.js:5578: Could not find module `ember-data-test/index` imported from `ember-data-test`

DataTestHelper: it works
    ✘ Died on test #1     at http://localhost:7357/assets/test-support.js:2809
        at http://localhost:7357/assets/dummy.js:254
        at http://localhost:7357/assets/vendor.js:150
        at tryFinally (http://localhost:7357/assets/vendor.js:30)
        at http://localhost:7357/assets/vendor.js:156
        at http://localhost:7357/assets/test-loader.js:29
        at http://localhost:7357/assets/test-loader.js:21
        at http://localhost:7357/assets/test-loader.js:40
        at http://localhost:7357/assets/test-support.js:5578: 'undefined' is not a function (evaluating 'data_test.dataTest(42)')
```

I have tried this with master following the advice in [this issue](https://github.com/ember-cli/ember-cli/issues/3796), but still get these failures.  In other addons (e.g. [ember-cli-dates](https://github.com/johnotander/ember-cli-dates/blob/master/app/initializers/ember-cli-dates.js)), I have seen the use of initializers to ensure that the helper is loaded, but would assume that if this were required that the initializer would be generated by default.

You can view the repo [here](https://github.com/fauxton/ember-data-test)

**Comment by clekstro** [comment]
Did not see this before, but perhaps this is already fixed in https://github.com/ember-cli/ember-cli/pull/3891?

**Comment by marcioj** [comment]
Hi @clekstro, the PR that you mentioned should fix your second error: `'undefined' is not a function (evaluating 'data_test.dataTest(42)')`.

I'm unsure of what is causing your first error, but in my tests if you create an app ending with `-test` you receive it. ember-cli has some [reserved project names](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/valid-project-name.js#L6), `test` is one these, but I believe that `something-test` is expected to work.

**Comment by clekstro** [comment]
@marcioj Thanks for the feedback.  

I don't think the `-test` is relevant for addons, though it's interesting that the results are similar.  I would have expected it to warn me if that was an issue.  Also, there are addons like [ember-cli-test-recorder](https://github.com/QuantumInformation/ember-cli-test-recorder) on emberaddons.com.

**Comment by marcioj** [comment]
`ember-cli-test-recorder` works, but `ember-data-test` or `my-addon-test` don't. The `-test` I meant is in the end of the name.

**Comment by marcioj** [comment]
There is no warning because I think it isn't intended to work in this way.
I created a PR in ember-cli/ember-cli-test-loader#10 which should solve this problem.

**Comment by stefanpenner** [comment]
@marcioj that PR landed, can you confirm it works in ember-cli now?

**Comment by clekstro** [comment]
@marcioj Thanks for the clarification and the PR!

**Comment by marcioj** [comment]
Glad to help @clekstro!

@stefanpenner using both the changes in ember-cli/ember-cli-qunit#59 and #3891 it works.
We need to bump a new version in ember-cli-qunit to bring these changes to ember-cli.

**Comment by clekstro** [comment]
@stefanpenner @marcioj Anything else I can help with here?
