### ISSUE TITLE
Warn about security threat

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#3900]
So whenever a new security fix is released for ember.js it would be nice it ember-cli was aware, checked your version, and warned you whenever you did anything in the project.

This would require a resource of security patches for each version of ember.js builds.

**Comment by stefanpenner** [comment]
`npm outdated` provides this information when asked (not idea ya) once ember is on npm we can use that channel maybe.

**Comment by stefanpenner** [comment]
Not apposed to this. But not a priority currently. If someone wants to champion this I am all ears, and as such likely needs a detailed RFC.

I suspect the solution of `npm outdated` will "just work" once we move ember away from bower
