### ISSUE TITLE
Support for loader plugins

### ISSUE THREAD

**Issue by OrKoN** [ember-cli/ember-cli#3902]
Hi,

it's not a bug but rather a proposal of an enhancement. It would be great if ember-cli supported importing of templates as ES6 modules. For example,

```
import tmpl from './tmpl.hbs!';

export default Ember.Component.extend({
  layout: tmpl
});
```
This code imports a hbs template and compiles it on-the-fly (the syntax with ! comes from jspm, I am not completely sure if it's standard).

Supporting this would give a possibility for non-ember-cli projects to expose their code as ember-cli addons which would be beneficial for the ember/-cli eco system eventually.

Please let me know if this may work some day or if it's not possible at all.

**Comment by stefanpenner** [comment]
> it's not a bug but rather a proposal of an enhancement. It would be great if ember-cli supported importing of templates as ES6 modules. For example,

this works today.

**Comment by OrKoN** [comment]
I tested in ember-cli 0.2.3 with the following code in `components/my-component.js`:

```
import Ember from 'ember';

import tmpl from './tmpl.hbs!';

export default Ember.Component.extend({
  layout: tmpl
});
```

Shows this error: Uncaught Error: Could not find module `foo/components/tmpl.hbs!` imported from `foo/components/my-component` although the tmpl.hbs is there.

Is this feature described somewhere in details?

**Comment by rwjblue** [comment]
The template is compiled to JS, and the extension is stripped for modules (so the module name is the path without extension).

```javascript
import Ember from 'ember';

import tmpl from './tmpl';

export default Ember.Component.extend({
  layout: tmpl
});
```

**Comment by rwjblue** [comment]
The following test fixture demonstrates the technique: https://github.com/ember-cli/ember-cli/tree/master/tests/fixtures/addon/component-with-template.

**Comment by stefanpenner** [comment]
@OrKoN apparently we need to doc this, any ideas where best to document this?

**Comment by OrKoN** [comment]
@rwjblue I see. Thanks! Well, it does not seems to be aligned with what systemjs offers. Systemjs supports loading of various file types via plugins https://github.com/systemjs/systemjs#plugins so the pre-compilation step is built-in. Does the ember-cli's loader support plugins? 

@stefanpenner I am not very familiar with the entire ember-cli guide therefore I would expect to find docs about this feature in the chapter related to addons but now I think that a better place is either [here](https://github.com/ember-cli/ember-cli/blob/gh-pages/_posts/2014-04-02-using-modules-and-the-resolver.md) or maybe even in the [overview](http://www.ember-cli.com/#modules). Actually now when I know how it works and what to search for, I see that one can figure it out based on pieces from various chapters. Maybe, a note for people using jspm would be enough.

**Comment by OrKoN** [comment]
I've reconsidered the issue. So I renamed this issue and created a pull request in the loader project https://github.com/ember-cli/loader.js/pull/44 I think that this PR will solve the issue for 3rd party code that uses loader plugins, at least for the templates. Please comment if it makes sense.

**Comment by stefanpenner** [comment]
Why do we need loader plugins in the first place, isn't this just a build tool concern?

**Comment by OrKoN** [comment]
There are some advantages(as well as disadvantages) of using loader plugins instead of delegating everything to the build tool. Among advantages I would list the following:

- in development, the possibility to reload a single file instead of running a full build process 
- a possibility to import all assets in a single place. E.g. component.js imports component.css and component.tmpl all together and this works in the browser without a traditional build tool
- hopefully, with advancements of http protocol the build step becomes less relevant for apps which are structured to lazy load modules

I believe that the support for loader plugins will make ember-cli more open. Of course, it's not something to be done in the first place. That's just my thoughts. To make this more practical: we develop an internal library of Ember components but our build process is based on jspm. And at the moment we cannot use it as is with both ember-cli and jspm. I am still looking for a solution though...
  
If you think that the issue is not relevant for ember-cli, please close.

**Comment by stefanpenner** [comment]
The points you raise re: individual modules for http2 fun and build performance are part of @chadhietala and my current effort and is accomplished primarily as refactoring a to our existing build process. This effort will unlock those points, but also lay the foundation for the build tool portion of our planned engine work.

As part of this effort we plan to expose a more pluggable packager  which may address the openness concerns. 


I prefer to continue to improve our system until we hit some real technical limit rather then  layering on some additional concept.

At some point we may hit a real limit we're introducing some additional concept makes sense. But I do not believe we are there today.
