### ISSUE TITLE
Unnecessary reprocessing of styles

### ISSUE THREAD

**Issue by dfreeman** [ember-cli/ember-cli#3903]
I'm finding that when I have an addon that includes an `addon` tree, my CSS preprocessors are being re-executed any time I change any file in my `app` tree, not just styles.

For instance, with `liquid-fire` installed, changing `app.js` resulted in `ember-cli-sass` and `ember-cli-autoprefixer` re-executing. Without it, or if I just blew away the `liquid-fire` package's `addon` directory, everything ran as expected. I also tested with `ember-inline-svg`, a simpler package with an `addon` tree, and saw the same behavior.

Just to verify it wasn't anything particular to the Sass or Autoprefixer addons, I also checked and saw the behavior with `ember-cli-less`. With debug logging turned on, I'm noticing a cache eviction for `vendor/addons.css` that's seemingly related -- it shows up in exactly the same scenarios when the re-execution occurs:

```
  broccoli-caching-writer  cache eviction due to:
     - {file, vendor/addons.css, 33188, 0, 0, 1429049424000}
     - {file, vendor/addons.css, 33188, 0, 0, 1429049416000} +4s
```

Relevant version info:
```
ember --version
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```

Repo that reproduces the issue: https://github.com/dfreeman/reprocess-styles

**Comment by jschilli** [comment]
@dfreeman this is most likely an issue with the add ons themselves.

Prior to the resolution of this issue: https://github.com/ember-cli/ember-cli/issues/3534 there wasn't any option other than post processing when the entire tree was requested.

It is now possible to do so just when the `css` tree changed.

I'm delinquent in patching ember-cli-autoprefixer

see https://github.com/kimroen/ember-cli-autoprefixer/pull/11 for discussion on issue

**Comment by dfreeman** [comment]
@jschilli Thanks for the explanation; that makes some sense.
It's not clear to me though why having an `addon` tree in an addon would trigger this condition, though. An addon exposing an `app` tree instead, for instance, doesn't cause it to happen. Any insight?

**Comment by dfreeman** [comment]
Actually, I just confirmed `ember-cli-sass` doesn't use the `postprocessTree` hook at all, so it seems like there's something else in play here.

**Comment by stefanpenner** [comment]
This is a bug affecting all apps actually. The eviction warning you see is something I actually added (and am continuing to add) to our dependencies, so detecting these issues becomes more transparent. I am extremely glad you used it and it pointed to the same issue that motivated the instrumentation in the first place.

**Comment by jschilli** [comment]
I would agree

**Comment by stefanpenner** [comment]
I believe we are still missing the instrumentation in some important places, so we likely don't have a full picture. My guess is that this is the result of the source-map-concat code. I think we may have regressed and caused additional invalidations when we introduced it. Although it may just be a coincidence.

**Comment by aexmachina** [comment]
I've just been investigating this problem and ended up here. I can confirm @dfreeman's observation that the presence of an `addon/` directory in any addon causes the problem. What's the status of this issue? Do we have any workarounds for this?

**Comment by mutewinter** [comment]
We're migrating a large app to Ember CLI and this is causing a major development slowdown. Would love to see a fix.

**Comment by stefanpenner** [comment]
> We're migrating a large app to Ember CLI and this is causing a major development slowdown. Would love to see a fix.

Ya me2 :P

**Comment by stefanpenner** [comment]
Our apps now no longer do this. If someone has an example on master, please provide a repo that demonstrates the issue
