### ISSUE TITLE
[QUESTION]: How do I deprecate something in my addon?

### ISSUE THREAD

**Issue by williamsbdev** [ember-cli/ember-cli#3905]
I've noticed that in Ember there is an `Ember.deprecate` function that will output to the console when running the app based on the second parameter's truthy condition. What is the proper way in an ember-cli addon to document a deprecation? Should I be using `Ember.deprecate`? Is there another more preferred way to do this? After I know how to deprecate something, is there a way to test that the deprecation warning is logged? Again I noticed the `expectDeprecation` function in Ember for testing.

**Comment by stravid** [comment]
I have a similar question, how do I correctly deprecate a test helper provided by my addon? I already [asked on the forum](http://discuss.emberjs.com/t/best-practice-for-deprecating-test-helpers-of-an-addon/7599) but never got an answer how to do that :-(

**Comment by stefanpenner** [comment]
@rwjblue I seem to remember you mentioning you had an add-on for this. I just tried to skim your repo's but spotted nothing related.

**Comment by rwjblue** [comment]
Use Ember.deprecate, and ember-cli-defeatureify to strip from prod builds.

**Comment by stefanpenner** [comment]
> Use Ember.deprecate, and ember-cli-defeatureify to strip from prod builds

that was it, thanks!

**Comment by williamsbdev** [comment]
Thank you @rwjblue and @stefanpenner! I appreciate the validation on using Ember.deprecate.

**Comment by lukemelia** [comment]
Here are @rwjblue's current recommendations: http://rwjblue.com/2017/05/01/enabling-debug-code-stripping/
