### ISSUE TITLE
inject testing helpers by default in component unit test

### ISSUE THREAD

**Issue by tsing80** [ember-cli/ember-cli#3907]
I have always a need of using testing helper  like click(),pauseTest() for component tests
I always need to add the following boilerplate  copy from the acceptance test to enable test helper:

```
import startApp from '../../../helpers/start-app'
var application;
.......

  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
```
It would be nice if test helper is enabled by default in component test or the above is added to the default bluepoint of component test

**Comment by stefanpenner** [comment]
this is not something currently supported. The test helpers reside here: https://github.com/switchfly/ember-test-helpers the following PR may interest you https://github.com/switchfly/ember-test-helpers/pull/38
