### ISSUE TITLE
"asset-compilation" guide image path issues

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#3910]
The [asset-compilation guide](http://www.ember-cli.com/asset-compilation/) ([source](https://github.com/ember-cli/ember-cli/blob/gh-pages/_posts/2013-04-09-asset-compilation.md)) says,

> To add images, fonts, or other assets, place them in the `public/assets` folder. For example, if you place `logo.png` in `public/assets/images`, you can reference it in templates with `assets/images/logo.png` or in stylesheets with `url('/assets/images/logo.png')`.

 1. Since all of `public/` is copied to `dist/`, why not put that file in `public/images/logo.png` and reference it as `images/logo.png` in HTML? This would save bytes.
 2. The documented stylesheet reference is `url('/assets/images/logo.png')`, which is *absolute*, but Ember apps can be mounted at paths. (This is precisely why `index.html` references the JS and CSS as relative paths -- relative to `document.baseURI`.) With the images in `public/assets/images/`, the reference should be `url('images/logo.png')`.

**Comment by jamesarosen** [comment]
### On point 1:

I should note that the image, JS, and CSS references in HTML are relative to `document.baseURI`, but the image references in CSS are relative to the stylesheet path, which is going to be `assets/app.css` (itself relative to `document.baseURI`). Thus, if you were to put the logo in `public/images/logo.png`, you'd have to reference it from CSS as `url(../images/logo.png)`, which may not be desirable.

**Comment by MiguelMadero** [comment]
That's good to know, we were using the static compiler to add them. doh!

**Comment by jamesarosen** [comment]
I should clarify. (1) is a matter of opinion. I disagree with the guide, but it's just my opinion. (2) seems like an actual mistake.

**Comment by stefanpenner** [comment]
doesn't seem like a bug, but rather a proposal. Feel free to flesh out an RFC so we can nail the details.

**Comment by jamesarosen** [comment]
2 is definitely a bug with an existing feature.

**Comment by Benjy1979GitHub** [comment]
If you have changed base url, there is something funny going on with the CSS image-paths like if you have background:url("");
It is possible that you want to ship the app out to different subdirectories
 ENV.baseURL = '/impey'; 
 ENV.baseURL = '/roomviewer'; 

I find that the css paths are impossible to get right for both. Either one is broken or the other is.
I don't want to have to write the baseURL into the CSS image paths. But yet if I don't they don't seem to behave themselves.
