### ISSUE TITLE
over 20k of files in node_modules/ember-cli

### ISSUE THREAD

**Issue by hashjoin** [ember-cli/ember-cli#3911]
is this normal?  I had put my app in a dropbox folder and it just killed it:

vmbp:node_modules mve$ find  broccoli-asset-rev | wc -l
     486
vmbp:node_modules mve$ find  ember-cli | wc -l
   21621
vmbp:node_modules mve$ find  ember-cli-app-version | wc -l
     111
vmbp:node_modules mve$ find  ember-cli-babel | wc -l
    2973
vmbp:node_modules mve$ find  ember-cli-content-security-policy | wc -l
     215
vmbp:node_modules mve$ find  ember-cli-dependency-checker | wc -l
      81
vmbp:node_modules mve$ find  ember-cli-htmlbars | wc -l
     343
vmbp:node_modules mve$ find  ember-cli-ic-ajax | wc -l
      23
vmbp:node_modules mve$ find  ember-cli-inject-live-reload | wc -l
       5
vmbp:node_modules mve$ find  ember-cli-qunit | wc -l
    1005
vmbp:node_modules mve$ find  ember-cli-uglify | wc -l
     913
vmbp:node_modules mve$ find  ember-data | wc -l
      11
vmbp:node_modules mve$ find  ember-export-application-global | wc -l
      11
vmbp:node_modules mve$

**Comment by stefanpenner** [comment]
Yup normal. Npm inlines everything by default. We plan to drop bower sometime soon, which will dramatically reduce the file size.
