### ISSUE TITLE
Failing CI tests with "Map"

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-cli#3912]
As I am becoming more enamoured with ES6 language features I every once in a while bump into problems as a result. I suspect this fits into this category but I am hoping that maybe there is something I can do (and eventually Ember-CLI can automate) so that other folks don't have the same problem:

>             Died on test #1     at http://localhost:7357/assets/test-support.js:2739
                at test (http://localhost:7357/assets/test-support.js:1733)
                at http://localhost:7357/assets/dummy.js:1026
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:5508: Can't find variable: Map

This error can be found at Travis here: [travis report](https://travis-ci.org/lifegadget/ui-code-highlight/builds/58726493). Admittedly I do find it hard to explain though that when I run `ember test` locally I get no errors, when I run **http://localhost:4200/tests** I also get no errors. Why the discrepancy? 

![2015-04-16_10-07-25](https://cloud.githubusercontent.com/assets/980757/7177760/238b7568-e421-11e4-9959-9a469eeb1530.png)

**Comment by ksnyde** [comment]
Oh btw, the only reference to `Map` in my code, is here:

    // addon/components/ui-code-highlight.js
    let fixer = new Map([
      ['js', 'javascript'],
      ['hbs', 'handlebars'],
      ['md', 'markdown']
    ]);

this *is* wrapped in an observer:

    _languageObserver: Ember.on('init', Ember.observer('language', function() { ... });

I mention this only because maybe there is a timing/async issue at hand here?

**Comment by stefanpenner** [comment]
We don't bundle the polyfil automatically. You must include it manually for now.

We have plans to auto include these polyfills as we need them, but that work isn't quite finished yet.

**Comment by rwjblue** [comment]
When you run locally, it looks like you are using Chrome (which has `Map`), but Travis is running in phantomjs 1.x which does not have `Map` (and is missing many other features).  

See http://kangax.github.io/compat-table/es6/#Map for a detailed browser support matrix.

**Comment by ksnyde** [comment]
Thanks guys. My initial thought was it was probably PhantomJS related but then somehow I got thrown off the plot. Here's my stupid question for the day ... I had thought that by using Babel it would have transpiled all of my ES6 syntax to ES5-friendly code at run time. Is that not true? 

Do you guys have any resources/reading you'd recommend to someone trying to become better grounded in all of this?

**Comment by ksnyde** [comment]
Oh also, just a clarification on the kangax chart ... Android's chrome browser is not listed does that mean it follows the same path as the Chrome desktop (or is that just wishful thinking on my part).

**Comment by stefanpenner** [comment]
The babel site is your best resource. It explains that the core-js is required for es6 polyfills and regenerator is needed for generators and async functions.

As mentioned above, we plan to auto include based on usage. As I did not feel it was appropriate to include the entire set of polyfills if the user isn't using them. In addition, I have worked with babel to enable more selective inclusion detection on there end which enables us to do the same. I believe the babel is more or less complete on this side. And @chadhietala work will enable selective builds.

Until then. Include core-js as a build dep and you will get what you desire

**Comment by ksnyde** [comment]
thanks @stefanpenner

**Comment by stefanpenner** [comment]
No prob. I do admit the current state leaves much to be desired. Sometime soon it will be better

**Comment by ksnyde** [comment]
:+1: I like the non-comital optimism. I agree too. Stepping into the promised land always involves stepping over mines. :)

**Comment by ksnyde** [comment]
@stefanpenner I installed the runtime with `npm install babel-runtime --save`.

      "dependencies": {
        "babel-runtime": "^5.1.10",
        "ember-cli-babel": "^5.0.0",
        "ember-cli-htmlbars": "0.7.4"
      },

I think I must be missing a step though, right? Still getting the same error. How do I get `babel --optional runtime script.js` or the equivalent into build pipeline for Ember-CLI/Broccoli? Just looking for an example to work off of.

**Comment by stefanpenner** [comment]
> I think I must be missing a step though, right?

yup, this doesn't inform ember-cli how to find any of those files.

**Comment by ksnyde** [comment]
Yes that's where I was going with my prior question ... are there any examples of how to do this within an Ember-CLI project? 

p.s. I really appreciate all the amazing work you have and continue to put into Ember but rather than wait for the silver bullet (aka, auto-detection) on this one if there's an easy way to empower the masses to solve manually I think it would be well worth it. If you think putting this question out onto a forum like SO would be a better place to service this knowledge sharing I'm happy to do that too.

**Comment by shotgundebugging** [comment]
Any update on this?

**Comment by ksnyde** [comment]
If you're developing an addon which adding the polyfil into the dependency chain then you'd add something like this to the `index.js`:

    module.exports = {
      name: 'ember-wow',
      description: 'you\'re awesome addon',
      included: function(app,parentAddon) {
        var target = (parentAddon || app);
        target.options.babel = target.options.babel || { includePolyfill: true };

      }

If it's an app then just add `includePolyfill` declaration in your environment. Personally I just try and avoid the polyfil for now. The Babelified part ES2015 is a livable space. :)

**Comment by shotgundebugging** [comment]
Thanks!
