### ISSUE TITLE
Tests stall when testing a nonexistent controller

### ISSUE THREAD

**Issue by cdl** [ember-cli/ember-cli#3920]
Noticed this today after a code refactor, but it seems like tests stall when trying to test a nonexistent controller, with no indication as to what test it's stalled on, rather than failing. Using `ember-cli 0.2.3` and `node 0.12.2`.

**Steps to reproduce:**

- Initialize a new app with `ember new test`
- Generate a controller with `ember g controller foo`
- Delete the controller at `app/controllers/foo.js`, or rename it, keeping the generated test file
- Try to run tests with `ember test`

**Expected results:**

- Tests fail on the deleted controller, as it does not exist.

**Actual results:**

- Tests hang when trying to test the controller, without any indication as to what file it's hanging on.

[Here's a .zip of an app where this is occurring](https://www.dropbox.com/s/l42j5qxhzmx7u1n/testapp.zip?dl=0) - you'll have to `npm install` and `bower install`.

**Comment by stefanpenner** [comment]
@johanneswuerbach any immediate thoughts?

**Comment by blesh** [comment]
Same issue. Using `io.js v1.7.1`.

Jumping into it in node-inspector wasn't super helpful, other than to say it was inside `testem` where it's hung up.

Possibly related, I noticed Testem wasn't working well in other projects I have yesterday. It's seems to always be "waiting for runners".

**Comment by elidupuis** [comment]
Any more info on this issue? Our tests are stalling but we haven't been able to track down why...

**Comment by gmurphey** [comment]
As a side-note: running the tests in a browser using `ember test --server` usually gives a better idea of what dependencies are missing.
