### ISSUE TITLE
Should be more obvious what to do when no template compilers registered error message occurs

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#3923]
The error in #3373 could be more explicit, and should perhaps happen when generating a component and or template the first time.

As a novice trying to generate an addon from scratch and generate a component it is fairly cryptic when this fails (see below).

Also the failure is somewhat obscure because the error does not seem to happen right away. In some scenarios it is possible to create an add-on, generate a component and launch tests and get a cryptic test failure. So you can have a failing test from a freshly generated component and have never even seen the `no template compilers...` error message.

It is great that there is an error message though.

Perhaps more explicit documentation might be needed.

In case other people stumble across this. 

Genrate Addon

```
ember addon ember-widget
```

installing npm...bower...

cd into addon directory

```
cd ember-widget 
```

Generate a component for addon

```
ember generate component x-thing  
```

The following files are generated
```
  create addon/components/x-thing.js
  create addon/templates/components/x-thing.hbs
installing
  create tests/unit/components/x-thing-test.js
installing
  create app/components/x-thing.js
```

if you don't have a template compiler (such as htmlbars or handlebars) registered in your dependencies hash of your package.json file you will see an error that looks like this

```
An `addon/templates` tree was detected, but there are no template compilers registered for `ember-widget`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ember-widget`'s `package.json`.
```

Launch addon

```
ember serve
```

Navigate to Tests

http://localhost:4200/tests

x-thing unit test will fail because I didn't put this in my package.json

```
  "dependencies": {
    "ember-cli-babel": "^5.0.0",
    "ember-cli-htmlbars": "0.7.4"
  },
```

**Comment by stefanpenner** [comment]
> An `addon/templates` tree was detected, but there are no template compilers registered for `ember-widget`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ember-widget`'s `package.json`.

this error message seems pretty good,?

**Comment by stefanpenner** [comment]
hmm, either we should include htmlbars by default, or we should have the generators add it on-demand if it does not exist when one generates...

**Comment by eccegordo** [comment]
Yeah, I think adding htmlbars by default makes sense, but perhaps the generators should tie into some dependency management hook that is aware or can be configured to be aware of these things. It also might make sense to just issue a warning when executing the blueprint the first time:

"Hey looks like you are generating a template please be aware you need a template precompiler ..."

The error message itself is reasonable.

My issue is when I looked at the default failing test before the htmlbars dependency was registered, the cause and effect was not clear.

**Comment by stefanpenner** [comment]
i think the new defaults of the blueprint make this much less common. If someone has an idea to improve the error message I would love a pr :)
