### ISSUE TITLE
ember s throws import error for ember-data when used as a dependency

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#3927]
To reproduce:

1) ```ember addon test-addon```
2) ```ember g model post```
3) Run ```ember s``` to confirm the dummy app is currently working
4) Move ```ember-data``` from devDependencies to dependencies in ```package.json```
5) Run ```ember s``` to observe the error

Demo project: https://github.com/elwayman02/ember-data-addon

```
$ ember s
version: 0.2.3
Cannot read property 'import' of undefined
TypeError: Cannot read property 'import' of undefined
    at Class.module.exports.included (c:\Projects\GitHub\ember-data-addon\node_m
odules\ember-data\lib\ember-addon\index.js:22:13)
    at c:\Projects\GitHub\ember-data-addon\node_modules\ember-cli\lib\models\add
on.js:238:32
    at Array.map (native)
    at Class.eachAddonInvoke (c:\Projects\GitHub\ember-data-addon\node_modules\e
mber-cli\lib\models\addon.js:236:22)
    at Class.Addon.included (c:\Projects\GitHub\ember-data-addon\node_modules\em
ber-cli\lib\models\addon.js:342:8)
    at EmberAddon.<anonymous> (c:\Projects\GitHub\ember-data-addon\node_modules\
ember-cli\lib\broccoli\ember-app.js:312:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (c:\Projects\GitHub\ember-data-a
ddon\node_modules\ember-cli\lib\broccoli\ember-app.js:307:45)
    at EmberAddon.EmberApp [as appConstructor] (c:\Projects\GitHub\ember-data-ad
don\node_modules\ember-cli\lib\broccoli\ember-app.js:103:8)
    at new EmberAddon (c:\Projects\GitHub\ember-data-addon\node_modules\ember-cl
i\lib\broccoli\ember-addon.js:26:8)
```

I've tried testing this on master as well, with the same result.

**Comment by stefanpenner** [comment]
> 4) Move ember-data from devDependencies to dependencies in package.json

Ember-data can't really be a dependency of an-addon without the parent also having it as an addon. The pain is the result of the npm dedupe and resolution strategy being at odds with the requirements of client-side libraries.

**Comment by stefanpenner** [comment]
this is also related to https://github.com/ember-cli/ember-cli/issues/3531

**Comment by stefanpenner** [comment]
additionally the following is also clearly wrong: https://github.com/emberjs/data/blob/master/lib/ember-addon/index.js#L11-L22 in ember-data.

**Comment by elwayman02** [comment]
@stefanpenner shouldn't the demo app be started based on the package.json of the addon?  So wouldn't they both have ember-data as a dependency?

**Comment by stefanpenner** [comment]
i think this is resolve?
