### ISSUE TITLE
After build, running app gives error: 'exports is not defined'

### ISSUE THREAD

**Issue by krishnaglick** [ember-cli/ember-cli#3929]
My code is here: https://github.com/krishnaglick/Internet-Programming-Final
Site is being hosted here: http://cop4813.ccec.unf.edu/~group4/app/index.html

Running the app in production mode produces the same issue, app works in dev mode.

**Comment by stefanpenner** [comment]
the compiled module output does not look like esperanto output, rather babel output.

**Comment by stefanpenner** [comment]
yup, you have https://github.com/krishnaglick/Internet-Programming-Final/blob/frontend/Brocfile.js#L7 enabled, please remove that option as we use esperanto for our module transpilation step

**Comment by krishnaglick** [comment]
Removing babel from the brocfile seems to have fixed the issue, ty.

**Comment by stefanpenner** [comment]
> Removing babel from the brocfile seems to have fixed the issue, ty

all you need to do is remove `		compileModules: true`

**Comment by krishnaglick** [comment]
Did so, trying to make this thing work on the server.
It keeps routing to "http://cop4813.ccec.unf.edu/~group4/app/~group4/app/index.html"
I'm doing...
  if (environment === 'production') {
    ENV.baseURL = 'http://cop4813.ccec.unf.edu/~group4/app/';
  }
