### ISSUE TITLE
EmberApp#styles should merge with overwrite

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli#3930]
When javascript trees are merged (addons, external, app, etc), `overwrite: true` is passed (https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L531)

The same thing should be true for styles, but it's not currently. https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L955

I believe the semantics we want for addons in terms of contents of app/ is "last one wins", and app should win out over addons, so merging with `overwrite: true` is an appropriate solution here.

The practical application that led me to this is that I have an addon "A" with nested addon "B", and addon "A" will not build because a mergeTrees is choking on a conflict with a "B"'s app/styles/ dir. However there is not actually a conflict. It appears that "A"'s dummy app is including the tree from "B" twice, once as a dependency of "A" and once as a dependency of itself, and this leads to the conflict. My suggestion above does not address this oddity, but it does make it less painful.

**Comment by lukemelia** [comment]
I'm happy to do the work on this if I get a greenlight from the maintainers.

**Comment by stefanpenner** [comment]
Yes app/**/* Should merge, the only requirement is that stuff in the primary app takes presedence

**Comment by rwjblue** [comment]
Close by https://github.com/ember-cli/ember-cli/pull/3937.
