### ISSUE TITLE
Generated helpers don't work out of the box

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#3931]
```
$ ember g helper truncate
version: 0.2.3
installing
  create app/helpers/truncate.js
installing
  create tests/unit/helpers/truncate-test.js
```

This generates:

```js
import Ember from 'ember';

export function truncate(params/*, hash*/) {
  return params;
}

export default Ember.HTMLBars.makeBoundHelper(truncate);
```

Using `{{truncate}}` it in a template make this error appear: `Assertion Failed: A helper named 'truncate' could not be found`

I'm using the PODs structure.

**Comment by cibernox** [comment]
Ok, I've found the problem. The problem is the helper doesn't contains an hyphen in the name. It's a subtle mistake. 

I think that add a warning in the console when you generate a helper without hyphen could be good. Closing.

**Comment by stefanpenner** [comment]
Ya. This one is surprising. I suspect we should just auto register these

**Comment by cibernox** [comment]
According to the docs in ember-cli.com, helpers without hypen are not looked automatically on purpose to avoid being mistaken by a property lookup in the context.

**Comment by stefanpenner** [comment]
> According to the docs in ember-cli.com, helpers without hypen are not looked automatically on purpose to avoid being mistaken by a property lookup in the context.

correct, but if we detect them in `helpers/*` we can register them automatically

**Comment by cibernox** [comment]
Maybe, but probably using the new HTMLBars syntax.

**Comment by stefanpenner** [comment]
@cibernox good point
