### ISSUE TITLE
ember d doesn't remove folders that it creates

### ISSUE THREAD

**Issue by kylecoberly** [ember-cli/ember-cli#3933]
For example, if I run: `ember g route foo/bar --pod` and then `ember d route foo/bar --pod`, the generated files are removed, but not the directories. I think if the directories are otherwise empty, the destroy command should also remove them.

**Comment by stefanpenner** [comment]
> I think if the directories are otherwise empty, the destroy command should also remove them.

this seems reasonable.

**Comment by sivakumar-kailasam** [comment]
@stefanpenner The [existing code](https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L757) is,
```javascript
return Promise.filter(fileInfos, isValidFile).
    then(finishProcessingForUninstall);
````
so only files get removed. I feel we should have something like,

```javascript
  return Promise.filter(fileInfos, isValidFileInfo).
then(getFileInfosValidForUninstall).
then(finishProcessingForUninstall);
```

If this sounds good to you I'll implement this and send out a PR

**Comment by stefanpenner** [comment]
sure

**Comment by stefanpenner** [comment]
would accept a PR, but this seems to have gone stale.

**Comment by acorncom** [comment]
@stefanpenner Staleness aside, think the above would still work?  If so, will see about sending in a PR

**Comment by rwjblue** [comment]
@acorncom - Maybe it will work, maybe it won't.  A PR adding tests to prove it works would definitely be welcome :smiley_cat:

**Comment by acorncom** [comment]
@rwjblue Funny, guess I could have thought of that :smile:
