### ISSUE TITLE
Ember-cli creates a resource route in the resource generator

### ISSUE THREAD

**Issue by tonkonogov** [ember-cli/ember-cli#3935]
As the title said, cli creates a resource route by default. But in view of forthcoming deprecation of the `resource` usage in the router file it should be replaced by a simple `route`.

**Formal things**

**HTR:** run `ember g resource any` in the root dir
**Expected:** when generator is complete `router.js` contains `this.route('any');`
**Actual:** when generator is complete `router.js` contains `this.resource('any', function() {});`
    
Tested with bare ember-cli v0.2.3

**Comment by apaganobeleno** [comment]
is this one closed ?

**Comment by stefanpenner** [comment]
thanks @apaganobeleno
