### ISSUE TITLE
Addon sass file, is it addon.scss or addon.sass

### ISSUE THREAD

**Issue by mansona** [ember-cli/ember-cli#3938]
We're maintaining an addon that has a SASS file that we want to generate before it is added to the consuming App's tree. We have had quite a few issues with this ( https://github.com/Blooie/ember-cli-notifications/issues/15 ) but we got it working by adding ember-cli-sass as a dependancy.

Now we have a bit of an interesting issue https://github.com/Blooie/ember-cli-notifications/issues/31 where it looks like ember-cli is looking for /addon.sass and we had /addon.scss so we renamed it and it worked locally https://github.com/Blooie/ember-cli-notifications/pull/32 and now it looks like our dummy app is looking for /addon.scss https://travis-ci.org/Blooie/ember-cli-notifications/builds/59368661

I tried to dig into this a little bit in the source and i traced it down to preprocessors.js https://github.com/ember-cli/ember-cli/blob/master/lib/preprocessors.js#L186 and that's why i'm asking for help in this repo and not ember-cli-sass. Please let me know if you think I need to open this issue there.

**Comment by nmcclay** [comment]
I have recently started digging into this matter as well, and I am wondering if its possible to change the name of this file to something other than `addon.scss` or remove it entirely.

**Comment by nathanhammond** [comment]
Closing as the entire ecosystem has changed since 2015-04-21. If a new issue is reported with detailed instructions we'll be happy to take a look!
