### ISSUE TITLE
Ubuntu 14.04 installation issue

### ISSUE THREAD

**Issue by Xobb** [ember-cli/ember-cli#3939]
Hey there, I've got the issue when installing the ember-cli on my fresh virtual ubuntu 14.04.

    vagrant@vagrant-ubuntu-trusty-64:~$ uname -a
    Linux vagrant-ubuntu-trusty-64 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    vagrant@vagrant-ubuntu-trusty-64:~$ nodejs --version
    v0.12.2
    vagrant@vagrant-ubuntu-trusty-64:~$ npm --version
    2.8.3
    agrant@vagrant-ubuntu-trusty-64:~$ sudo npm install -g ember-cli --verbose
    npm info it worked if it ends with ok
    npm verb cli [ 'node',
    npm verb cli   '/usr/bin/npm',
    npm verb cli   'install',
    npm verb cli   '-g',
    npm verb cli   'ember-cli',
    npm verb cli   '--verbose' ]
    npm info using npm@2.8.3
    npm info using node@v0.12.2
    npm verb node symlink /usr/bin/node
    npm verb install initial load of /usr/lib/package.json
    npm verb readDependencies loading dependencies from /usr/lib/package.json
    npm verb cache add spec ember-cli
    npm verb addNamed "*" is a valid semver range for ember-cli
    npm verb addNameRange registry:https://registry.npmjs.org/ember-cli not in flight; fetching
    npm verb request uri https://registry.npmjs.org/ember-cli
    npm verb request no auth needed
    npm info attempt registry request try #1 at 12:30:10
    npm verb request id 1e1ace3cdf9653f4
    npm verb etag "3U4ZWZ0CT9OPTOLF24OX2UG24"
    npm http request GET https://registry.npmjs.org/ember-cli
    npm http 304 https://registry.npmjs.org/ember-cli
    npm verb etag https://registry.npmjs.org/ember-cli from cache
    npm verb get saving ember-cli to /home/vagrant/.npm/registry.npmjs.org/ember-cli/.cache.json
    npm verb addNamed "0.2.3" is a plain semver version for ember-cli
    npm verb afterAdd /home/vagrant/.npm/ember-cli/0.2.3/package/package.json not in flight; writing
    npm verb afterAdd /home/vagrant/.npm/ember-cli/0.2.3/package/package.json written
    npm info install ember-cli@0.2.3 into /usr/lib
    npm info installOne ember-cli@0.2.3
    npm verb installOne of ember-cli to /usr/lib not in flight; installing
    npm verb lock using /home/vagrant/.npm/_locks/ember-cli-fb77fe672b380792.lock for /usr/lib/node_modules/ember-cli
    npm verb unbuild lib/node_modules/ember-cli
    npm info preuninstall ember-cli@0.2.3
    npm info uninstall ember-cli@0.2.3
    npm verb unbuild rmStuff ember-cli@0.2.3 from /usr/lib/node_modules
    npm verb gentlyRm vacuuming from /usr/bin/ember up to /usr
    npm info postuninstall ember-cli@0.2.3
    npm verb gentlyRm don't care about contents; nuking /usr/lib/node_modules/ember-cli
    npm verb tar unpack /home/vagrant/.npm/ember-cli/0.2.3/package.tgz
    npm verb tar unpacking to /usr/lib/node_modules/ember-cli
    npm verb gentlyRm don't care about contents; nuking /usr/lib/node_modules/ember-cli
    vagrant@vagrant-ubuntu-trusty-64:~$ ember
    No command 'ember' found, did you mean:
     Command 'enber' from package 'asn1c' (universe)
    ember: command not found

Is there anything I'm doing wrong here?

**Comment by kellyselden** [comment]
Check this out http://www.ember-cli.com/#npm-package-management-with-sudo.
You may be having issues with using `sudo npm install`.

**Comment by Xobb** [comment]
Yes, I've installed with sudo. Following the link you've provided it states that 

> Note: npm >=0.3 is *safer* when using sudo.

**Comment by Xobb** [comment]
Also, it's worth mentioning that I've installed nodejs and npm following [these instructions](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories), which seem to be relevant for ubuntu.

**Comment by OrKoN** [comment]
It looks like the place where ember command is installed is not on your PATH variables. For me, the ember command is available at /usr/local/bin/ember

**Comment by Xobb** [comment]
vagrant@vagrant-ubuntu-trusty-64:~$ echo $PATH
     /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Seems like the $PATH is correct.

I think the issue is here:
    npm verb gentlyRm don't care about contents; nuking /usr/lib/node_modules/ember-cli

for some strange reason it's nuking (removing?) the directory where ember-cli has to be installed. Strange.

**Comment by marcemira** [comment]
@Xobb a very good option is to work with "nvm", check it's repo https://github.com/creationix/nvm for more information :)
¿

**Comment by Xobb** [comment]
@marcemira thanks for advice, as far as I've got from the project it helps managing single nodejs versions on single machine. I don't think it's applicable because we're using node just to build ember app on our build machine which I'm trying to set up right now.

**Comment by stefanpenner** [comment]
@Xobb sudo is not safer. I am unsure where you found that info

**Comment by Xobb** [comment]
That's where to documentation link led me to.
![right here](https://i.imgur.com/Cx0Nw6K.png)
and then led to gist.
![right here](https://i.imgur.com/dHqAzSP.png)

Anyway, I'm using the [instructions from nodejs wiki](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager), which I believe is the recommended way of installing node.js which also installs npm globally.

I'll try to rebuild the image and install bower and ember cli locally for single user.

**Comment by xomaczar** [comment]
@marcemira I am on ubuntu 14.04 and nvm made my life easier, if you install with sudo apt-get you'll be in sudo hell, can run npm without sudo or chow -r. Nvm installs node in /home/user/.nvm so no need to run stuff as root

**Comment by stefanpenner** [comment]
You mis understand isaacs comment, it means it is safer to use sudo with new npm then with earlier versions. It does not mean it is safer to use npm with sudo then without.

It is absolutely safer to not use sudo. No need giving every possible dependency root level access.

**Comment by stefanpenner** [comment]
@Xobb nvm isn't just for managing multiple versions but is also one of the easiest ways to install node correct (with the correct paths and permissions). As a bonus it also lets you swap between versions

**Comment by xomaczar** [comment]
@xobb I am on ubuntu 14.04 and nvm made my life easier, if you install with sudo apt-get you'll be in sudo hell, can run npm without sudo or chow -r. Nvm installs node in /home/user/.nvm so no need to run stuff as root

**Comment by stefanpenner** [comment]
It really is a bummer that node default installs are riddled with bad and broken usage patterns :(. Causes our users much grief.

Maybe once we make more progress on cli itself, we will circle back and try to offer a standalone package to help mitigate these pains :(

**Comment by xomaczar** [comment]
@xobb I am on ubuntu 14.04 and nvm made my life easier, if you install with sudo apt-get you'll be in sudo hell, can't run npm without sudo or have to chown -r node_modules. Nvm installs node in /home/user/.nvm so no need to run stuff as root

**Comment by Xobb** [comment]
> It is absolutely safer to not use sudo. No need giving every possible dependency root level access.

I agree. But in my case it doesn't matter, as it's gonna be run on virtual machine which purpose is to build the ember application with ember cli and put the tarball on another server.

Thanks for the feedback, I'll go install nvm and then try to make it friends with ansible.

**Comment by Xobb** [comment]
As the community recommended I've installed the nvm and tried to install the ember-cli there. Still no luck. Appending the output:

    vagrant@vagrant-ubuntu-trusty-64:~$ npm install -g --verbose ember-cli
    npm info it worked if it ends with ok
    npm verb cli [ '/home/vagrant/.nvm/versions/node/v0.12.2/bin/node',
    npm verb cli   '/home/vagrant/.nvm/versions/node/v0.12.2/bin/npm',
    npm verb cli   'install',
    npm verb cli   '-g',
    npm verb cli   '--verbose',
    npm verb cli   'ember-cli' ]
    npm info using npm@2.7.4
    npm info using node@v0.12.2
    npm verb cache add spec ember-cli
    npm verb addNamed ember-cli@*
    npm verb addNameRange registry:https://registry.npmjs.org/ember-cli not in flight; fetching
    npm verb request uri https://registry.npmjs.org/ember-cli
    npm verb request no auth needed
    npm info attempt registry request try #1 at 8:13:30 PM
    npm verb request id 7b5d0841d6690c6d
    npm verb etag "3U4ZWZ0CT9OPTOLF24OX2UG24"
    npm http request GET https://registry.npmjs.org/ember-cli
    npm http 304 https://registry.npmjs.org/ember-cli
    npm verb etag https://registry.npmjs.org/ember-cli from cache
    npm verb get saving ember-cli to /home/vagrant/.npm/registry.npmjs.org/ember-cli/.cache.json
    npm verb addNamed ember-cli@0.2.3
    npm verb afterAdd /home/vagrant/.npm/ember-cli/0.2.3/package/package.json not in flight; writing
    npm verb afterAdd /home/vagrant/.npm/ember-cli/0.2.3/package/package.json written
    npm info install ember-cli@0.2.3 into /home/vagrant/.nvm/versions/node/v0.12.2/lib
    npm info installOne ember-cli@0.2.3
    npm verb installOne of ember-cli to /home/vagrant/.nvm/versions/node/v0.12.2/lib not in flight; installing
    npm verb lock using /home/vagrant/.npm/_locks/ember-cli-567f18445d81c02f.lock for /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/ember-cli
    npm verb unbuild lib/node_modules/ember-cli
    npm info preuninstall ember-cli@0.2.3
    npm info uninstall ember-cli@0.2.3
    npm verb unbuild rmStuff ember-cli@0.2.3 from /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules
    npm verb gentlyRm vacuuming from /home/vagrant/.nvm/versions/node/v0.12.2/bin/ember up to /home/vagrant/.nvm/versions/node/v0.12.2
    npm info postuninstall ember-cli@0.2.3
    npm verb gentlyRm don't care about contents; nuking /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/ember-cli
    npm verb tar unpack /home/vagrant/.npm/ember-cli/0.2.3/package.tgz
    npm verb tar unpacking to /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/ember-cli
    npm verb gentlyRm don't care about contents; nuking /home/vagrant/.nvm/versions/node/v0.12.2/lib/node_modules/ember-cli
    Killed

Which is pretty much the same. That Killed at the end freaks me out.

**Comment by stefanpenner** [comment]
`killed` is when some limit is imposed on the systems processes. Installing ember CLI is unfortunately costly, due to how NPM packages everything as a single zip, and how unstable npm is (result in us bundling many of our dependencies)

I suspect you can increase these limits. Until such time as we finally are able to remove bower, our largest dependency, which is likely blowing the limit.

**Comment by Xobb** [comment]
@stefanpenner you were right. The VM had only 512 mb RAM so I've enabled the swapfile and everything has been installed. Thanks everyone for help.

**Comment by kushdilip** [comment]
I was facing the same issue on digitalocean droplet with 512 MB of RAM. 
This link on has proper description on how to create swap and it solved it for me. https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04.

**Comment by wayne-o** [comment]
Use NVM
