### ISSUE TITLE
[ENHANCEMENT] Ability to rename blueprints

### ISSUE THREAD

**Issue by seanjohnson08** [ember-cli/ember-cli#3944]
We have `ember g` for generating, `ember d` for deleting, could we get `ember r` (or `ember mv`) for renaming/moving a blueprint?

**Comment by stefanpenner** [comment]
sure, I would also like this. But this isn't really a bug report, nor is it extremely important. So i am closing this in-favour of an [RFC](https://github.com/ember-cli/rfc) exploring the edge cases and details
