### ISSUE TITLE
unit tests of add-ons are not transpiled anymore

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3948]
Since bumping ember-cli from 0.2.0 to 0.2.3 the unit tests of my add-on are not getting transpiled anymore. Reverting to 0.2.0 fixes it.

**Comment by stefanpenner** [comment]
> Since bumping ember-cli from 0.2.0 to 0.2.3 the unit tests of my add-on are not getting transpiled anymore. Reverting to 0.2.0 fixes it.

you need to include ember-cli-babel in your addons dependencies entry.

**Comment by olivierlesnicki** [comment]
@stefanpenner that's already the case:
```
  "dependencies": {
    "broccoli-jscs": "0.0.22",
    "temp": "^0.8.1",
    "ember-cli-htmlbars": "^0.7.4",
    "ember-cli-babel": "^4.0.0",
    "ember-validations": "^2.0.0-alpha.3"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "connect-restreamer": "^1.0.1",
    "ember-cli": "0.2.3",
    "ember-cli-app-version": "0.3.2",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.15",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.12.3",
    "glob": "^4.5.3",
    "morgan": "^1.5.2"
  },
```

**Comment by stefanpenner** [comment]
a fresh add-on works correctly:

![screen shot 2015-04-23 at 9 23 46 am](https://cloud.githubusercontent.com/assets/1377/7301919/855e0138-e99a-11e4-9288-b635259ba825.png)

**Comment by stefanpenner** [comment]
as it does if moved to `dependencies`

![screen shot 2015-04-23 at 9 25 33 am](https://cloud.githubusercontent.com/assets/1377/7301951/bd5bf98c-e99a-11e4-89c9-b6e2737c7f1f.png)


if you can provide a reproduction case that is public, i can take a look. But i know many add-ons and apps that use this, I can with pretty high confidence say it works.

**Comment by olivierlesnicki** [comment]
Ok, it seems 0.2.3 is not to blame - but broccoli-jscs is.
`https://github.com/olivierlesnicki/test-addon`
Please see the `package.json`, `index.js` and `lib/jscsrc.json`.

**Comment by stefanpenner** [comment]
@olivierlesnicki why is https://github.com/olivierlesnicki/test-addon/blob/master/index.js#L20-L30 here ?
When i install you add-on i do not want jsc for your add-on to run. Please put this in your brocfile.

**Comment by olivierlesnicki** [comment]
@stefanpenner I've attempted to replicate `ember-suave` behviour https://github.com/dockyard/ember-suave but with my own config file.

See https://github.com/dockyard/ember-suave/blob/master/index.js#L14.

The goal is to share this add-on across multiple project and therefore share the jscs config file.

**Comment by stefanpenner** [comment]
@olivierlesnicki i believe ember-sauve is basically meant to be consumed by your addon. Or are you trying to implement your own jsc plugin?

**Comment by olivierlesnicki** [comment]
i'm trying to implement my own

**Comment by rwjblue** [comment]
I'm happy to implement an overrideable JSCS config in ember-suave. Please file an issue.

**Comment by olivierlesnicki** [comment]
I confirm this issue is not with ember-cli but with ember-suave. This can be closed

**Comment by rwjblue** [comment]
@olivierlesnicki - As with before, I am happy to fix reported issues with ember-suave...
