### ISSUE TITLE
Continue integration test with protractor?

### ISSUE THREAD

**Issue by CBluowei** [ember-cli/ember-cli#3952]
The issu I had asked on `stackoverflow.com`:

[http://stackoverflow.com/questions/29816163/continue-integration-test-in-ember-cli-with-protractor](http://stackoverflow.com/questions/29816163/continue-integration-test-in-ember-cli-with-protractor)

I'm looking forward your response, thanks.

**Comment by stefanpenner** [comment]
This doesn't appear like a bug. SO is a better venue for asking questions.

Unfortunately we need to keep this issue tracker focused on bugs, not cross links of questions from different mediums.

If there is an actual bug that comes out of that, feel free to open a detailed issued. If a missing feature exists a detailed rfc to solve it in the rfcs repo is appropriate
