### ISSUE TITLE
Cant inject a service into the router in an addon initializer 

### ISSUE THREAD

**Issue by kylenathan** [ember-cli/ember-cli#3953]
Injecting a service into the router from an initializer in an addon silently fails and the service does not appear on the router.

* Injecting into 'router' or 'router:main' fail
* Injecting into the router within an app initializer (instead of addon) works correctly. This only seems to affects addons.

In the addon/app/initializers/foo:

    export function initialize(container, application) {
      application.inject('router:main', 'foo', 'service:foo');
    }

    export default {
      name: 'foo',
      initialize: initialize
    };

**Comment by jschilli** [comment]
is that in `<addonName>/app` or `<addonName>/addon/app`

I typically do:

`<addonName>/addon/initializers/foo`:

```
export function initialize(container, application) {
  application.inject('router:main', 'foo', 'service:foo');
}
```

`<addonName>/app/initializers/foo`:

```
import { initialize } from ‘<addonName>/initializers/foo;

export default {
 	name: ‘foo’
        initialize: initialize
}
```

which definitely works.

**Comment by rwjblue** [comment]
Initializers are only looked for in the app tree.

**Comment by kylenathan** [comment]
@rwjblue: initializer sits in the app tree in the addon - is this correct? e.g. <addonName>/app/initializers/foo.js

Its correctly injecting the service into other factories. It's only the router injection that fails. 

More code:

````
export function initialize(container, application) {
  var router = container.lookup('router:main');
  application.inject('route', 'foo', 'service:foo');
  application.inject('router:main', 'foo', 'service:foo');
  application.inject('controller', 'foo', 'service:foo');
  router.on('didTransition', function() {
      console.log(this.foo);
 });
}

export default {
  name: 'foo',
  initialize: initialize
};
````
@jschilli Thanks, initializer sits in '<addonName>/app/initializers'. Have tried moving as per your example (see below) but still no luck. Again, just the router injection fails, the others are fine.


Refactored as per jschilli

ember-cli-foo/addon/initializers/foo.js
````
export function initialize(container, application) {
  var router = container.lookup('router:main');
  application.inject('route', 'foo', 'service:foo');
  application.inject('router:main', 'foo', 'service:foo');
  application.inject('controller', 'foo', 'service:foo');
  router.on('didTransition', function() {
      console.log(this.foo);
 });
}

export default {
  name: 'foo',
  initialize: initialize
};
````

ember-cli-foo/app/initializers/foo.js
````
import { initialize } from "ember-cli-foo/initializers/foo";

export default {
    name: "foo",
    initialize: initialize
};
````

**Comment by rwjblue** [comment]
By default items are created by the container once (upon `lookup`), then that cached result is returned for future `lookup`'s.  Any injections that you add **after** looking up an instance will be completely ignored (since the object has already been initialized).

Specifically, change:

```javascript
export function initialize(container, application) {
  var router = container.lookup('router:main');
  // ^^^^^^^ you are looking up router:main before scheduling injections
  application.inject('route', 'foo', 'service:foo');
  application.inject('router:main', 'foo', 'service:foo');
  application.inject('controller', 'foo', 'service:foo');
  router.on('didTransition', function() {
      console.log(this.foo);
 });
}
```

To this:

```javascript
export function initialize(container, application) {
  application.inject('route', 'foo', 'service:foo');
  application.inject('router:main', 'foo', 'service:foo');
  application.inject('controller', 'foo', 'service:foo');

  var router = container.lookup('router:main');
  router.on('didTransition', function() {
      console.log(this.foo);
 });
}
```

**Comment by kylenathan** [comment]
@rwjblue Ah, I see. Thats great, thanks for the help.
