### ISSUE TITLE
Safari: Syntax Error

### ISSUE THREAD

**Issue by marvinosswald** [ember-cli/ember-cli#3957]
my app runs just fine with chrome or firefox but I keep getting a SyntaxError with Safari.. any Ideas ? 

`SyntaxError: Attempted to redefine property 'value'` thrown by 
     
    define("lavavitae-cal-frontend/adapters/application", ["exports", "ember", "lavavitae-cal-frontend/config/environment"], function(e, t, a) {

maybe ember-cli related..maybe babel.. not sure

**Comment by stefanpenner** [comment]
I suspect you have the same key twice in a pojo. This is very unlikely an issue with ember cli, rather a bug in your code that Safari is being strict about

**Comment by marvinosswald** [comment]
I had defined "apikey" twice but still after I fixed it, same error.

More code:

        define("lavavitae-cal-frontend/adapters/application", ["exports", "ember", "lavavitae-cal-frontend/config/environment"], function(e, t, a) {
            "use strict";
            e["default"] = DS.RESTAdapter.extend({
                namespace: "api/v1",
                host: a["default"].APP.API,
                headers: function() {
                    var e = "";
                    return sessionStorage.user && (e = JSON.parse(sessionStorage.user).apikey || ""), {
                        apikey: e
                    }
                }.property()["volatile"](),
                ajaxError: function(e) {
                    var t = this._super(e);
                    return e ? void swal("Server Error", e.status, "error") : t
                }
            });
            var r = t["default"].Inflector.inflector;
            r.uncountable("attendee")
        })

**Comment by davewasmer** [comment]
```js
return sessionStorage.user && (e = JSON.parse(sessionStorage.user).apikey || ""), {
```

Is it that comma at the end there? Doesn't look like valid syntax to me.

**Comment by stefanpenner** [comment]
> I had defined "apikey" twice but still after I fixed it, same error.

can we see the pre-compiled code?

**Comment by stefanpenner** [comment]
> return sessionStorage.user && (e = JSON.parse(sessionStorage.user).apikey || ""), {

its valid, the return is always the pojo `{ api: e }`

**Comment by stefanpenner** [comment]
> maybe ember-cli related..maybe babel.. not sure

Its unlikely it is either of these actually. But we need more information, please provide a full picture.

**Comment by davewasmer** [comment]
> its valid, the return is always the pojo { api: e }

Well, TIL :wink:

**Comment by marvinosswald** [comment]
Sry for late response, yeah its kinda minified but only what ember-cli does by default...

Can't reproduce it by now but if the precompiled code doesn't help neither I will try to do so

Thanks in advance for your help guys
pre-compiled code: 

        import Ember from 'ember';
        import ENV from '../config/environment';

        export default DS.RESTAdapter.extend({
          namespace: 'api/v1',
          host:ENV.APP.API,
          headers: function(){
            var apikey = "";
            if(sessionStorage.user){
              var apikey = JSON.parse(sessionStorage.user).apikey || "";
            }
            return {
              "apikey": apikey
            };
          }.property().volatile(),
          ajaxError: function(jqXHR){
            var error = this._super(jqXHR);
            if (jqXHR){
              swal('Server Error',jqXHR.status,"error");
            }else{
              return error;
            }
          }
        });

        var inflector = Ember.Inflector.inflector;
        inflector.uncountable('attendee');

**Comment by stefanpenner** [comment]
sorry still nothing apparent. Repro would be best (feel free to share it with me privately if you can't publically)

**Comment by kcollignon** [comment]
+1 i get same error

**Comment by marvinosswald** [comment]
I further tracked it down to a line in my admin.hbs render function

        render: function render(context, env, contextualElement) {
          var dom = env.dom;
          var hooks = env.hooks, get = hooks.get, inline = hooks.inline;
          dom.detectNamespace(contextualElement);
          var fragment;
          if (env.useFragmentCache && dom.canClone) {
            if (this.cachedFragment === null) {
              fragment = this.build(dom);
              if (this.hasRendered) {
                this.cachedFragment = fragment;
              } else {
                this.hasRendered = true;
              }
            }
            if (this.cachedFragment) {
              fragment = dom.cloneNode(this.cachedFragment, true);
            }
          } else {
            fragment = this.build(dom);
          }
          var element6 = dom.childAt(fragment, [1]);
          var morph0 = dom.createMorphAt(dom.childAt(element6, [1]),1,1);
          var morph1 = dom.createMorphAt(dom.childAt(element6, [3]),1,1);
          var morph2 = dom.createMorphAt(dom.childAt(element6, [5]),1,1);
          inline(env, morph0, context, "input", [], {"type": "text", "class": "form-control", "id": "form.inputTitle", "value": get(env, context, "newCatForm.title"), "placeholder": "Kategorie Name"});
          inline(env, morph1, context, "textarea", [], {"type": "text", "class": "form-control", "id": "inputDesc", "name": "inputDesc", "placeholder": "Kategorie Beschreibung", "value": get(env, context, "newCatForm.desc")});
     
     
    
     
     
          inline(env, morph2, context, "input", [], {"type": "text", "value": "", "class": "form-control cp", "id": "inputColor", "value": get(env, context, "newCatForm.color"), "placeholder": "Kategorie Farbe"});
    
    
          
    return fragment;
        }

**Comment by marvinosswald** [comment]
Sooo finally got it... An Error in one of my .hbs files..

basically i did something like this:
`{{input value="" value=""}}`

Cheers and thanks for your help guys :+1:

**Comment by stefanpenner** [comment]
@marvinosswald you should open that as an ember issue. We need a better error message then that.

**Comment by maxfarseer** [comment]
Big thank you!!

**Comment by AndreiMotinga** [comment]
Just in case...   
I got the same error when had duplicate keys in locale  translation files
