### ISSUE TITLE
Alertify.js causes issues with sourcemap

### ISSUE THREAD

**Issue by igorsantos07** [ember-cli/ember-cli#3960]
I've tried to include [Alertify.js](https://github.com/alertifyjs/alertify.js/) into my project, but when including the JS file to my `Brocfile.js` it fails: `ENOENT: no such file or directory, open '/development/js/brocfile-test/tmp/tree_merger-tmp_dest_dir-VTDuE1yJ.tmp/bower_components/alertifyjs/dist/js/src/js/alertify.js'`

To reproduce:

```shell
ember new alertify-test
cd alertify-test
bower install alertifyjs
vi Brocfile.js # add: app.import('bower_components/alertifyjs/dist/js/alertify.js');
ember s # then, open the page in a browser
```

Running `ember-cli 0.2.3`.

**Comment by stefanpenner** [comment]
Can confirm, it is source map concat related.

**Comment by igorsantos07** [comment]
Is there a way to manually fix or workaround this? I have no idea where I should start, and I really wanted to have this library in my project.

**Comment by igorsantos07** [comment]
@stefanpenner was the issue fixed?

**Comment by stefanpenner** [comment]
if i recall, believe the sourceMap generated was incorrect.
