### ISSUE TITLE
cssnext

### ISSUE THREAD

**Issue by thejameskyle** [ember-cli/ember-cli#3963]
It's really awesome that Ember CLI (and the community) embraced future JavaScript syntax by using Babel and making it an Ember CLI default.

It'd be great if Ember could embrace future CSS syntax in the same way by using [cssnext](https://cssnext.github.io) via making @ebryn's [ember-cli-cssnext](https://github.com/ebryn/ember-cli-cssnext) plugin an Ember CLI default.

CSS pre/post-processing is one of those things people can argue for days on which tool is better. However, the fact that cssnext (or Babel for that matter) puts you on the standards track is a lot more meaningful than any specific syntax.

Speaking to @ebryn he pointed out that a potential argument against using cssnext is that it can't completely implement the spec. As such, you might use features that will have breaking changes in the future. This is a solvable problem, it's very simple to get past with a couple linting rules (transpilers like TypeScript already do this today).

The Ember community has been huge on embracing standards, from being one of the biggest consumers/early adopters of ES6/ES7 to closer aligning with web components, and even pushing for new standards (thanks @wycats). CSS standards deserve the same attention.

/cc @MoOx

**Comment by stefanpenner** [comment]
This seems better suited as an rfc
