### ISSUE TITLE
Test helpers are not autodiscovered

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#3979]
I've came across this just now. If you create a test helper using the built-in blueprint, it's not autodiscovered.

```
$ ember g test-helper sign-in
version: 0.2.3
installing
  create tests/helpers/sign-in.js
```

You need to manually require the helper, either in the test itself or in the `start-app.js`. 

Is this by design or is a bug?

**Comment by stefanpenner** [comment]
> Is this by design or is a bug?

i believe a bug

**Comment by cibernox** [comment]
I might get some time to fix this, but I have on related question. If you don't add the name of the helper to `tests/.jshintrc` you'll get a warning when you use it. 
Should the generator add it's name to the jshint too?

**Comment by stefanpenner** [comment]
I think the global test-helpers are basically a silly pattern. We should explore something more reasonable, especially with the recent app / appInstance seperation. As such, I would prefer to not spend time solving something I hope leaves us shortly.
