### ISSUE TITLE
deploying build to gh-pages does not work

### ISSUE THREAD

**Issue by BryanHunt** [ember-cli/ember-cli#398]
When you deploy the build result to gh-pages, the first problem you encounter is that it can't find your assets.  If you change either the rootURL in the environment, or the router, you can get your assets to load, but the routing is hosed.

cc: @MajorBreakfast

**Comment by robabby** [comment]
Hello, I am also finding that `rootUrl` and `locationType` do not appear to be resolving this issue for us either.  Our use-case is we have an application called `app-styleguide` which uses an addon we have made in-house called `app-components`.  The styleguide is the application that is consuming the components and the desire is to have these rendered as a webpage using github pages.  Unfortunately we are getting 404's for all of the images and fonts that are delivered from the `app-components` addon.

I have added the recommended lines from this thread to our environment.js file in `app-styleguide`
```
if (environment === 'production') {
    ENV.rootURL = '/app-styleguide';
    ENV.locationType = 'hash';
}
```
We are still receiving 404's for all images and fonts in the github pages site for the styleguide at https://organization.github.io/app-styleguide/

Is there something that needs to change in the addon's environment.js file?

Apologies if this is missplaced in this older issue thread.  Resources for this issue have been hard to find and this issue thread pops up in almost every Google search I have tried.  Please advise if I need to take this question elsewhere.
