### ISSUE TITLE
(intermediate value).property is not a function

### ISSUE THREAD

**Issue by macu** [ember-cli/ember-cli#3981]
Using Ember-CLI 0.2.3

    ember addon demo-addon

After the setup completes, create a component with a computed property, and add the component to the dummy app application template.

    ember serve

Chrome 42 reports the exception `Uncaught TypeError: (intermediate value).property is not a function` on the line where I use `.property()` to create a computed property.

Demo project: https://github.com/macu/ember-cli-addon-issue-3981

**Comment by stefanpenner** [comment]
* the error being crappy is a chrome bug.
* the error itself is the fact that add-ons don't run with `EXTEND_PROTOTYPES = true`, so `Function.prototype.property` doesn't exist.

**Comment by macu** [comment]
Does this mean that developing add-ons no longer involves a dummy app for seeing how components render, etc?

**Comment by macu** [comment]
In #3928 rwjblue gives a good response. Thx

**Comment by stefanpenner** [comment]
:+1:
