### ISSUE TITLE
Feature request: allow customizing the location of the app directory to support mixed projects

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#3985]
In many scenarios it is useful to contain both frontend and backend code in the same repsoitory. In such cases, the entire ember-cli app would reside in a subdirectory (let's say `frontend` or `webapp`). It could be useful to specify to `ember` a custom working directory, so that `ember` commands could be run from the root of the entire project and work seemlessly.

**Comment by stefanpenner** [comment]
This isn't something we have plans to support. Ember cli expects to own the tree. If you want an ember-cli app to be in the same repo as your server, make it a sub directory of your server repo.

**Comment by vmalloc** [comment]
@stefanpenner It *is* a subdirectory in my server repo, but it sucks to always `cd` into the webapp dir before hitting `ember generate <something>`, and developing small, full-stack webapps means I have to constantly switch between the root dir (for git operations etc.) and the webapp dir to run ember-cli...

A simple solution like an environment variable or a `.ember-cli` file in the project root telling `ember-cli` to `chdir` before doing anything would do the trick and doesn't sound like something that complicates other pieces of the code...

**Comment by stefanpenner** [comment]
seems like a script can be used to automate this?

```sh
#!/bin/sh
(cd app-name && ember $1)
```

**Comment by vmalloc** [comment]
You probably mean `$*`... 

And yes, but since it may be different for multiple repos I figured it would be cleaner to add optional support for this, but whatever. Your call.

**Comment by stefanpenner** [comment]
> And yes, but since it may be different for multiple repos I figured it would be cleaner to add optional support for this, but whatever. Your call.

I actually believe adding support for `ember s --path=path/to/project` is a great idea, I regret not adding support to this originally. Unfortunately, this will require some refactoring to work today.

As we also have a work-around, I don't feel this is on the critical path to 1.0, I will gladly revisit post 1.0. Or if someone implements a thoroughly tested PR that meets reasonable constraints already put in place by ember-cli, It will most likely be accepted.

**Comment by vmalloc** [comment]
Ok. Sounds reasonable. Thanks!
