### ISSUE TITLE
Introduce babel-polyfill

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#3986]
Ember.Set() is being deprecated in the next version of Ember
ES6 Set() is not being transpiled by babel.

Ember-cli should include babel-polyfill in the project dependencies.

**Comment by stefanpenner** [comment]
We have plans to include it automatically when we land selective builds. Until then it will need to be manually required.  Someone could create an addon for the interim

**Comment by oleosjo** [comment]
How would one manually require it?

**Comment by sohara** [comment]
@oleosjo Here's one way you can include it: https://github.com/babel/ember-cli-babel/issues/40

**Comment by oleosjo** [comment]
@sohara Thanks.
