### ISSUE TITLE
Is it possible to implement Amok?

### ISSUE THREAD

**Issue by medokin** [ember-cli/ember-cli#3987]
Amok is a live-reload script with a difference: it recompiles code in a Chrome debugging session, so the application's state is retained.

https://github.com/caspervonb/amok

**Comment by stefanpenner** [comment]
I believe our plugin system is not compatible with anok, as arbitrary plugins can easily add build steps.

That being said, we have some ideas on how we can implement the hot reloading after some pending work lands

**Comment by medokin** [comment]
Thanks for the clarification. I hope to see that feature one day. :+1:
