### ISSUE TITLE
fails to render when changing name of project

### ISSUE THREAD

**Issue by spruce** [ember-cli/ember-cli#3988]
when changing name of the project from let's say smc to app-smc ember-cli builds a index.html referencing wrong css and js files making the app not render

That is right after creating new project with `ember new smc`: 
Correct index.html with not changed name in package.json created with `ember build --environment production`
```
<!DOCTYPE html>
<html>
...
    <link rel="stylesheet" href="assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css">
    <link rel="stylesheet" href="assets/smc-d41d8cd98f00b204e9800998ecf8427e.css">
  </head>
  <body>
    <script src="assets/vendor-2a2d69bb21f1e121fb550f0dddcf578d.js"></script>
    <script src="assets/smc-32978aa4fc1c13eaaa15fa226970c94e.js"></script>
  </body>
</html>      
```
files in assets dir
```
smc-32978aa4fc1c13eaaa15fa226970c94e.js
smc-d41d8cd98f00b204e9800998ecf8427e.css
vendor-2a2d69bb21f1e121fb550f0dddcf578d.js
vendor-d41d8cd98f00b204e9800998ecf8427e.css
```

```
<!DOCTYPE html>
<html>
 ...
    <link rel="stylesheet" href="assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css">
    <link rel="stylesheet" href="assets/smc.css">
  </head>
  <body>
    <script src="assets/vendor-2a2d69bb21f1e121fb550f0dddcf578d.js"></script>
    <script src="assets/smc.js"></script>
  </body>
</html>
```
files in assets dir
```
app-smc-d41d8cd98f00b204e9800998ecf8427e.css
app-smc-ffcea116cbd46e22c4127be8cd759106.js
vendor-2a2d69bb21f1e121fb550f0dddcf578d.js
vendor-d41d8cd98f00b204e9800998ecf8427e.css
```

**Comment by stefanpenner** [comment]
yup this is expected, you need to update several occurrence of the name.

**Comment by spruce** [comment]
maybe it would be nice to display a warning that this will happen and you have to change X, Y, Z

**Comment by stefanpenner** [comment]
im unsure where in the life-cycle we would be able to display this warning?

**Comment by spruce** [comment]
hm. good question. Maybe it should be a reason to fail the build because it never the less will fail the build. So it could be a preparation step to the build step where some checks are performed. (Also run into the issue that root owned the assets dir and the default deployer / builder can't delete the dir)

**Comment by stefanpenner** [comment]
> hm. good question.

if we can nail that, im on-board.

**Comment by spruce** [comment]
Will look into that later today

**Comment by stefanpenner** [comment]
sounds good.  Closing this for now.
