### ISSUE TITLE
Parameters on helpers are passed in as an array

### ISSUE THREAD

**Issue by sebadom** [ember-cli/ember-cli#3989]
This is just a question because maybe this a feature, but since i couldn't find doc referencing this i though i would just ask

When i create a helper the callback function given to Ember.HTMLBars.makeBoundHelper get's some parameters, where the first one is actually an array of the params passed from the template when i would expected to receive each param on its own. example

// sometemplate.hbs

<div class="foo">
  something and call a helper
  {{fancy-helper 'stringparam' 2 someproperty}}

// helpers/fancy-helper.js
export function fancyHelper(thestring, thenumber, theproperty) {
  
  return whatever;
}

export default Ember.HTMLBars.makeBoundHelper(fancyHelper);

Inside fancy helper, i don't get each param on it's own, instead i get something like
function fancyHelper(arrayOfParams) {
  arrayOfParams[0] // this is the string
  arrayOfParams[1] // this is the number
  arrayOfParams[2] // this is the property

  return whatever;
}

So.. am i missing something? is this a change made on the HTMLBars layer on top of Handlebars (beacuse handlebars doesn't do this i think.. at least the last time or version i used)

Should i consider using hash instead of params then?

thanks
seba

**Comment by twokul** [comment]
not an `ember-cli` question per se but yes, you will get an array of parameters instead of individuals ones ([jsbin](http://emberjs.jsbin.com/gosusolura/3/edit?js,output)). also, this is probably a good SO question.
