### ISSUE TITLE
Consider scaffolding `needs` for model-tests

### ISSUE THREAD

**Issue by flyswatter** [ember-cli/ember-cli#3992]
So far whenever I create a model-test, there is a recursive dependency to `needs` any other models that the tested model is related to (either via `hasMany` or `belongsTo`).

Since this is so predictable, maybe it would be worth scaffolding the `needs` array for model-tests.

If you don't agree, I'd hope you have a better way of isolating a model from its related objects for testing.

**Comment by stefanpenner** [comment]
> If you don't agree, I'd hope you have a better way of isolating a model from its related objects for testing.

* models can't be unit tested. And by definition testing model relationships is an integration test. (multiple collaborators and all)
* the integration support for the test-helpers needs to be improved, look to: https://github.com/switchfly/ember-test-helpers/pull/21

some other WIP:

* https://github.com/switchfly/ember-test-helpers/pull/38

**Comment by flyswatter** [comment]
Oh interesting, I didn't realize models were always in acceptance-mode.  I guess it makes sense, since you'd usually want to test some properties of the relationships anyways.

That project looks cool, I'll be checking it out!

**Comment by stefanpenner** [comment]
> I didn't realize models were always in acceptance-mode

integration is likely the mode that they are best tested in

generally in ember apps:

* unit: algorithmic complexit
* integration: interaction between entities
* acceptance: business use-cases, treat the app like a black box and "click" "visit" and "fill in"

**Comment by flyswatter** [comment]
Ohh gotcha.  I've been interchanging "integration" and "acceptance", didn't realize they had specific meaning in ember tests.
