### ISSUE TITLE
testem introduces a non-optional native extension

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3993]
https://github.com/Automattic/socket.io/issues/2107

TL;DR we need socket.io to release a new version that whos dependencies ultimately have an optional dependency on node-gyp of `bufferutil`

- [x] update socket.io
- [x] update engine.io
- [x] update testem
- [x] our use of npm.install must be `no-optional=false`

**Comment by stefanpenner** [comment]
looks like we will be getting a release soon: https://github.com/Automattic/socket.io/issues/2107#issuecomment-105616243

**Comment by DENIELER** [comment]
Guys, we are using 0.2.7 version of ember-cli and bug still reproducing :(

**Comment by stefanpenner** [comment]
> Guys, we are using 0.2.7 version of ember-cli and bug still reproducing :(

this will be live in the next release v1.13.2

**Comment by DENIELER** [comment]
@stefanpenner but in 1.13.2 realease you have ember 1.13 version, but we don't want yet to update :( it has some conflicts, example routes are not allowing points, only dashes and others. We will update in some time, but don't want to do that now

**Comment by stefanpenner** [comment]
> @stefanpenner but in 1.13.2 realease you have ember 1.13 version, but we don't want yet to update :( it has some conflicts, example routes are not allowing points, only dashes and others.

thats fine, ember-cli work with literally any ember version, just change the bower.json.

**Comment by DENIELER** [comment]
@stefanpenner hm.. thank you for this approach.. it should works! :)

**Comment by stefanpenner** [comment]
> @stefanpenner hm.. thank you for this approach.. it should works! :)

Yup! Sorry it wasn't obvious

**Comment by DENIELER** [comment]
Until we are waiting for ember-cli@1.13.2, we had fixed that issue in next way:

npm install ws@latest
npm install

So, first install ws package and then install all other packages (in latest ws package this issue was fixed for windows)
