### ISSUE TITLE
startApp does not start routing

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#3995]
I have two component unit tests that are failing for what seems to be the same underlying reason.

In the first, I just have a `{{link-to}}` helper invocation in the component's template. Every test emits

> TypeError: Cannot read property 'recognizer' of undefined

In the second component, I need to generate absolute URLs, so I do
```js
someURL: Ember.computed('model', function() {
  const baseURI = document.baseURI.replace(/\/$/, '');
  const router = this.get('router.router');
  const path = router.generate('some.where' , this.get('model'));
  return baseURI + path;
}),

router: Ember.computed(function() {
  return this.container.lookup('router:main');
})
```

This test fails because `router.router` is undefined.

In both cases, the underlying problem is that routing is not started. Would it be reasonable to start the router in `startApp`?

**Comment by rwjblue** [comment]
1. `startApp` is not used for component unit tests.
2. Routing is not started in acceptance tests until the first call to `visit` (this is to prevent double routing in each test)

**Comment by jamesarosen** [comment]
> startApp is not used for component unit tests.

Does that mean if I have `{{link-to}}` or any other router usage in my component, I *must* use an integration test? I've been adding `startApp()` and `integration: true` to those tests to get them working.

Does the move from two kinds of testing (unit, acceptance) to three (unit, integration, acceptance) affect this?

**Comment by stefanpenner** [comment]
Integration should cover this. @ef4 has a good open pr on the helpers repo.
It should be evaluated for this use-case. I suspect it should handle it. Or be made to if it does not

**Comment by jamesarosen** [comment]
I suspect @stefanpenner means https://github.com/switchfly/ember-test-helpers/pull/38. I've now opened three issues across two repos that go away once that's done :)

**Comment by stefanpenner** [comment]
Thanks. Linking from my phone is ghetto 

@dgeb I know you wanted to vet that PR. Friendly reminder for when your return from vacation

**Comment by stefanpenner** [comment]
@jamesarosen do you confirm that pr would solve your issue?

**Comment by jamesarosen** [comment]
I left two comments on that PR. They're very specific issues with it. In general, yes, it solves this problem.

**Comment by jamesarosen** [comment]
I should say.. sort of.

`this.container.lookup('router:main')` exists, but its `router` is still `undefined`. I can, however, call `startRouting()` on it successfully.

**Comment by jamesarosen** [comment]
I'm afraid not. When I break just after `this.render(...)`,
```js
r = this.container.lookup('router:main')
r.router // undefined
```
and the tests for components that have `{{link-to}}` still fail with

> Uncaught TypeError: Cannot read property 'recognizer' of undefined

**Comment by stefanpenner** [comment]
doesn't appear to be an ember-cli issue, rather some upstream lib
