### ISSUE TITLE
Document use of test-support/ in addons

### ISSUE THREAD

**Issue by clekstro** [ember-cli/ember-cli#4002]
I recently stumbled across this [blog post](http://williamsbdev.com/posts/Ember-CLI-test-support/) which mentions the behavior, but someone with more (i.e. some) experience should probably document it for others.

**Comment by stefanpenner** [comment]
@toranb want to add docs to https://github.com/ember-cli/ember-cli/tree/gh-pages as it appears your add-on is using this feature?

**Comment by williamsbdev** [comment]
@stefanpenner @toranb I'll work on getting this documented for ember-cli tonight.

**Comment by stefanpenner** [comment]
Awesome thanks

**Comment by clekstro** [comment]
:+1:

**Comment by toranb** [comment]
Big thanks to @williamsbdev for the upgrade to ember-cli-test-helpers and his epic blog post on the subject!
