### ISSUE TITLE
How to debug `ember build` infinite loop/hang

### ISSUE THREAD

**Issue by sarus** [ember-cli/ember-cli#4004]
I have a project that builds successfully on OSX but is failing on CentOS 6.5.  When I run `ember build` I get a few jshint errors (related to defining variables that aren't used) and then build process just hangs with the green `Building ...` looping forever.  Both systems have the same versions (Node v0.12.2, Ember-cli v0.2.3, npm v 2.7.6).  

I've tried uninstalling ember-cli, re-installing, removing NPM and Bower modules, re-installing to no avail.  

I tried `DEBUG=ember-cli* ember build` hoping that might show an error but I didn't see any output that looked like an error.  Here are the last few lines from running `DEBUG=ember-cli*  ember build`.    

Does anyone have any other ideas for how I can figure out what is causing ember build to hang?  I'm fairly certain it's something really dumb on my part but I'm not where to look to try and figure it out.

```
  ember-cli:preprocessors processing ember-cli-babel +0ms
  ember-cli:registry loading css: available plugins ember-cli-less,broccoli-stylus-single,broccoli-ruby-sass,broccoli-sass; found plugins ember-cli-less; +4ms
  ember-cli:preprocessors processing ember-cli-less +0ms
  ember-cli:utilities/attempt-metadata-index-file not darwin, skipping tmp/.metadata_never_index (which hints to spotlight to prevent indexing) +5ms
Building.
authenticators/hamachi.js: line 57, col 24, 'data' is defined but never used.
authenticators/hamachi.js: line 61, col 52, 'response' is defined but never used.
authenticators/hamachi.js: line 66, col 32, 'error' is defined but never used.
authenticators/hamachi.js: line 66, col 24, 'status' is defined but never used.

4 errors

authorizers/hamachi.js: line 4, col 30, 'requestOptions' is defined but never used.
authorizers/hamachi.js: line 4, col 23, 'jqXHR' is defined but never used.

2 errors

===== 2 JSHint Errors

Building ... <-- just hangs here with the dots animated
```

**Comment by stefanpenner** [comment]
without steps to reproduce i have no idea.

* does the issue happen on a vanilla app?

**Comment by sarus** [comment]
Yeah, I understand it was a long shot without steps to reproduce.  A vanilla app builds fine.  Does this mean anything to anyone:

```
broccoli-caching-writer  cache eviction due to:
     - {directory, ., 16832, 4096, 4096, 1430086156155}
     - {undefined} +0ms
```

That is the last output when running `DEBUG=* ember-build`.  I think I just have to resort to rebuilding the project piece by piece until I figure out what is causing the build to hang.

**Comment by stefanpenner** [comment]
> broccoli-caching-writer  cache eviction due to:
>      - {directory, ., 16832, 4096, 4096, 1430086156155}
>      - {undefined} +0ms

Ya, this is likely the initial build cache eviction. The first line is the `new` the second line is the `old`. On initial build, there is no old, hence it being undefined. The numbers on the right hand side are just the file stat information, used to decide if a file is old or new.

I should likely `add` new and `old` prefixes, so other humans can also parse that.

**Comment by stefanpenner** [comment]
if you can share the app, or a subset of the app that demonstrates the issue. I can dig in.

**Comment by sarus** [comment]
@stefanpenner  Thank your offers of help.  I think I've narrowed it down now.  Let me see if I can get a small test app that exhibits the same issue.  The project builds successfully after I removed all the less files from `/app/styles/` except for an empty `app.less` (I'm using ember-cli-less).  I slowly added back in the less files and it looks like any `@import` statement causes the build to not complete.  Testing right now to see if I can replicate this in a test project.

**Comment by stefanpenner** [comment]
i would add logging here: https://github.com/gabrielgrant/broccoli-less-single/blob/master/index.js#L49-L82

as i look at that, the promise usage looks dubious...

**Comment by stefanpenner** [comment]
@sarus do the node versions differ between OS?

**Comment by sarus** [comment]
@stefanpenner Same versions of node, npm and ember-cli on the OSX and centos boxes.

```
ember-cli v0.2.3
node v0.12.2
npm v2.7.6
```

**Comment by stefanpenner** [comment]
@sarus how far down : https://github.com/gabrielgrant/broccoli-less-single/blob/master/index.js#L49-L64 did it get? Or didn't it reach it at all?

**Comment by sarus** [comment]
@stefanpenner 

```javascript
LessCompiler.prototype.updateCache = function (srcDir, destDir) {
  var destFile = destDir + '/' + this.outputFile

  mkdirp.sync(path.dirname(destFile));

  var lessOptions = {
    filename: includePathSearcher.findFileSync(this.inputFile, srcDir),
    paths: srcDir
  }

  _.merge(lessOptions, this.lessOptions)
  lessOptions.paths = [path.dirname(lessOptions.filename)].concat(lessOptions.paths);
  data = fs.readFileSync(lessOptions.filename, 'utf8');

  return new RSVP.Promise(function(resolve, reject) {
    ////////// GETS HERE ////////////////
    less.render(data, lessOptions).then(function (output) {
      //////////// NEVER GETS HERE //////////////////
      var fileWriterPromises = [ writeFilePromise(destFile, output.css, { encoding: 'utf8' }) ];
      var sourceMapURL = lessOptions.sourceMap && lessOptions.sourceMap.sourceMapURL;
      if (sourceMapURL) {
        fileWriterPromises.push( writeFilePromise(destDir + '/' + sourceMapURL, output.map, { encoding: 'utf8' }) );
      }

      RSVP.all(fileWriterPromises).then(function() {
        return resolve(output);
      }, function(err) {
        return reject(err);
      });

    }, function (err) {
      //////////// AND NEVER GETS HERE //////////////
      less.writeError(err, lessOptions);
      reject(err);
    });

  });
}
```

**Comment by stefanpenner** [comment]
@sarus i just submitted some cleanup to broccoli-less-single https://github.com/gabrielgrant/broccoli-less-single/pull/26  i don't think it fixes you issue. As it appears the issue may be in `less.render` itself

**Comment by stefanpenner** [comment]
also, my next step would be to start debugging this method: 

https://github.com/less/less.js/blob/fb5280f16f124e5062634a22be2f3c99e650d0a4/lib/less/render.js#L4-L39

**Comment by sarus** [comment]
@stefanpenner Thanks!  I'm already working my way through those methods.  Will report back if I find anything.

**Comment by stefanpenner** [comment]
thanks :)

**Comment by sarus** [comment]
So an update on the digging.

We eventually get to the point where the less `@import` statement is processed in the parser and less tries to load the import.  The path here is the path to the `@import` file.  The callback on the `loadFile` statement is never called.

https://github.com/less/less.js/blob/master/lib/less/import-manager.js#L118-L125
```javascript
        var promise = fileManager.loadFile(path, currentFileInfo.currentDirectory, this.context, environment,
            function(err, loadedFile) {
            /////// THIS CALLBACK IS NEVER REACHED /////
            if (err) {
                fileParsedFunc(err);
            } else {
                loadFileCallback(loadedFile);
            }
        });
        //// DOWN HERE IS NEVER REACHED EITHER /////
```
The `fileManager.load` call looks like this:

https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L23-L68
```
    // promise is guarenteed to be asyncronous
    // which helps as it allows the file handle
    // to be closed before it continues with the next file
    return new PromiseConstructor(function(fulfill, reject) {
        ///// This is never reached /////
        (function tryPathIndex(i) {
            if (i < paths.length) {
                fullFilename = filename;
                if (paths[i]) {
                    fullFilename = path.join(paths[i], fullFilename);
                }
                fs.stat(fullFilename, function (err) {
                    if (err) {
                        filenamesTried.push(fullFilename);
                        tryPathIndex(i + 1);
                    } else {
                        fs.readFile(fullFilename, 'utf-8', function(e, data) {
                            if (e) { reject(e); return; }

                            fulfill({ contents: data, filename: fullFilename});
                        });
                    }
                });
            } else {
                reject({ type: 'File', message: "'" + filename + "' wasn't found. Tried - " + filenamesTried.join(",") });
            }
        }(0));
    });
```

Oddly it seems like the promise is never executed.  I wrapped the entire `PromiseConstructor` in a try catch and it is throwing the following error:

```
[TypeError: undefined is not a promise]
```

Any ideas?

**Comment by stefanpenner** [comment]
https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L51 doen't reject if the stat fails

**Comment by stefanpenner** [comment]
question: what did you wrap in a try catch, 44 -> 67 or 45 -> 66 (inside or outside the constructor)

**Comment by stefanpenner** [comment]
As you are using node 0.12.0 `PromiseConstructor` should be v8 provided `Promise`. I believe the code is hitting:

* https://github.com/v8/v8/blob/master/src/promise.js#L42 (<-- most likely this one)
* https://github.com/v8/v8/blob/master/src/promise.js#L226-L227

**Comment by sarus** [comment]
@stefanpenner 

Yes, I'm using Node v0.12.  The PromiseConstructor makes sense then.  I guess they fall back on the promise library if you don't have the native Promise from using v0.12.

I put the try catch around 44 - > 67.  So this entire code block:

https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L44-L67

If I move it to 45 -> 66 nothing is caught.

**Comment by stefanpenner** [comment]
@sarus for fun change: https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L7 to always be:
```js
var PromiseConstructor = require('promise');
``

**Comment by sarus** [comment]
Making the change does get rid of the exception being thrown although the build process is still hanging.  I get further along though.  Will keep tracing.  Here is the output of npm version:

```

{ 'ember-less-test': '0.0.0',
  npm: '2.7.4',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

**Comment by stefanpenner** [comment]
> Here is the output of npm version:

ya nothing obviously related here, bummer :(

> Will keep tracing.

let me know what you find.

**Comment by sarus** [comment]
@stefanpenner 

Spoke to soon.  It builds successfully now after changed:

https://github.com/less/less.js/blob/master/lib/less-node/file-manager.js#L7

to 

```
var PromiseConstructor = require('promise');
```

(I messed up some code during my debugging that I had to go back and revert haha)

This change fixed it both in my text project and in my primary project.  Now to figure out where the bug report goes haha.

**Comment by stefanpenner** [comment]
@sarus it doesn't appear less is doing anything wrong, it seems like something is broken in that versino of node....  Can you try another version, maybe iojs?

**Comment by sarus** [comment]
I actually just tried installing ember-cli with io.js v2.0.0 (npm v2.9.0) and it wouldn't install.

```
npm install -g ember-cli 
```
just kept scrolling this over and over indefinitely:

```
  ACTION Regenerating Makefile
make: Leaving directory `/opt/iojs-v2.0.0-linux-x64/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
make: Entering directory `/opt/iojs-v2.0.0-linux-x64/lib/node_modules/ember-cli/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

```

**Comment by stefanpenner** [comment]
I cannot Confirm :(

**Comment by stefanpenner** [comment]
That sounds like a bug in node gyp or your compiler tool chain. Sockst.io needs to fix its dependencies so that native extension is optional.  They wrote the code, just pending a release...

**Comment by stefanpenner** [comment]
this seems to have gone stale. :(
