### ISSUE TITLE
cannot run ember test with phantomjs

### ISSUE THREAD

**Issue by bargar** [ember-cli/ember-cli#4005]
Very similar to #3623.

First, I was getting `Syntax error - parse failure` as in said ticket. Tried upgrading to phantomjs2, as apparently solved the previous issue, I'm getting the following:

```
$ phantomjs --version
2.0.0 (development)
$ ember --version
version: 0.2.3
node: 0.12.2
npm: 2.7.6
$ ember test
version: 0.2.3
Built project successfully. Stored in "/Users/bullfrog/src/flatworld/cbe-web/ember/tmp/class-tests_dist-BqDCx4ta.tmp".
not ok 1 PhantomJS 2.0 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Unexpected token '('
        Log: >
    ...

1..1
# tests 1
# pass  0
# fail  1
```

Not sure where to go about looking for the unexpected token, I'm afraid.

Tried reverting back to last known version that worked, phantomjs@1.9.8, and it fails with `SyntaxError: Parse error`. Also tried clearing out **/tmp**, to no avail.

**Comment by stefanpenner** [comment]
@bargar do you tests run in Safari or Firefox or.. ?

**Comment by bargar** [comment]
Had been running **/tests** continually in Chrome, not failing there (should have mentioned that, of course). The failure popped up first in CI on a qa box, thus my investigation into phantom versions, et. al.

More to the point: just ran the tests in FF and Safari, and the latter indeed demonstrates the issue, which was a typo in a function declaration.

Big thanks for pushing me in the right direction! In future I'll certainly run the tests in multiple browsers before chasing :ghost:s...

**Comment by stefanpenner** [comment]
> Big thanks for pushing me in the right direction! In future I'll certainly run the tests in multiple browsers before chasing s...

we ran into this same issue here at work several times. It seems like chrome is slightly looser, we may want to open a chrome bug.

**Comment by danielspaniel** [comment]
This was such a good idea .. saved my bacon.  Glad you asked this question @bargar  and glad there was a good answer from @stefanpenner.

**Comment by jamesarosen** [comment]
With PhantomJS 2.0.0 and jQuery 1.11.3, I get this error on [this line](https://github.com/jquery/jquery/blob/1.11.3/src/event.js#L319) when running

```js
find('.some-class').trigger('input');
```

**Comment by Ricar7o** [comment]
For documentation purposes, I was seeing a very similar error but it would fail with
```
SyntaxError: Unexpected token '}'
```

After tracking it down for a long time, my issue was that in a Handlebars template I had a duplicate parameter when invoking a component.
```hbs
{{some-component param='abc' param='xyz'}}
```
I had focused all my efforts on JS files, so I wanted to leave this here for anyone else who might do the same thing.

**Comment by toranb** [comment]
@Ricar7o thanks for taking the time to make a comment here. It's always the obvious errors like a duplicate attribute that I seem to overlook!

If only someone had blogged about the dangers of invalid markup ... maybe I would have known better.

http://toranbillups.com/blog/archive/2014/02/16/Beware-invalid-html-in-your-emberjs-app/
