### ISSUE TITLE
Exclude certain assets from app.toTree()

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli#4009]
[The docs](http://www.ember-cli.com/managing-dependencies/) explain how to *include* extra assets with `broccoli-funnel`, but it's not clear how to *exclude* certain assets from being copied to the `dist/assets` folder.

I might have missed something, but couldn't find it in the docs. I think it would be useful to know how to do this in general. Is this currently possible with ember-cli?

---

Some background info for this issue: I'm building my css with `ember-cli-rework` and `rework-suit`, which concatenates both remote and local css (referenced with `@import`). So `app.css` is the only file that I need in my `dist/assets`, since all other files will be concatenated to `app.css` anyway. But by default all other css is copied as well, which isn't necessary.

**Comment by stefanpenner** [comment]
funnel as inlcude/exclude matchers.

**Comment by ismay** [comment]
You mean that `broccoli-funnel` can exclude files from `app.toTree()` as well? Because I read the example:

```javascript
// Providing additional trees to the `toTree` method will result in those
// trees being merged in the final output.
module.exports = app.toTree(extraAssets);
```

As meaning that specifying additional trees will only result in them being *included* as well. So how do I exclude files from `.toTree()`: specify the entire apptree without the files that I want to exclude, or just pass the files to be excluded?

**Comment by stefanpenner** [comment]
nope, what you did is absolutely correct.  If you have time to update the docs, so future travelers can have an easier time that would be handy.
