### ISSUE TITLE
vendor-prefix causes sourcemaps to be off by a line

### ISSUE THREAD

**Issue by wagenet** [ember-cli/ember-cli#4010]
The offending line appears to be https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/vendor-prefix.js#L6.

I discovered this by running my code through https://github.com/ef4/fast-sourcemap-concat/blob/master/tools/dissect.js.

This returns the following https://gist.github.com/wagenet/808b6f18591db402487d. (As gist to avoid wrapping.)

**Comment by rwjblue** [comment]
I believe that we need to avoid the simple string concatenation in https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1301-L1320 and do something smarter there.

@ef4 - Can you confirm that this is potentially the problem?

**Comment by wagenet** [comment]
Upon further consideration, I'm not 100% sure that `content-for` is the issue. It looks like the whitespace is different before `window.EmberENV` but the `content-for` comes after that. There's no obvious indicator to me of why the whitespace would be affected.

**Comment by ef4** [comment]
Please confirm that you're using fast-sourcemap-concat 0.2.4, there was a bug in whitespace handling before that.

**Comment by wagenet** [comment]
I've verified that we're on 0.2.4 and still getting the off-by-one issue.

**Comment by stefanpenner** [comment]
@wagenet still see this issue/

**Comment by wagenet** [comment]
I have not seen this recently. I guess we can close this for now and I'll re-open if I see it again.
