### ISSUE TITLE
docs out of date: http://www.ember-cli.com/#using-canary-build-instead-of-release

### ISSUE THREAD

**Issue by justinbkay** [ember-cli/ember-cli#4016]
The line about clearing the vendor directory and then running `ember install` doesn't work anymore.  Ember install is just for addons now, and doesn't repopulate the vendor directory.

**Comment by stefanpenner** [comment]
if you can submit a fix to: https://github.com/ember-cli/ember-cli/tree/gh-pages that would be greatly appreciate.

**Comment by justinbkay** [comment]
I think someone already did:
https://github.com/ember-cli/ember-cli/pull/4017

On Tue, May 5, 2015 at 11:34 AM, Stefan Penner <notifications@github.com>
wrote:

> if you can submit a fix to:
> https://github.com/ember-cli/ember-cli/tree/gh-pages that would be
> greatly appreciate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/4016#issuecomment-99153206>
> .
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law
