### ISSUE TITLE
Automatic code loading: lazy loading of assets when navigating to a route

### ISSUE THREAD

**Issue by ebryn** [ember-cli/ember-cli#402]
(Creating this as a parent issue that we can use to link to all the appropriate issues in the related projects)

TL;DR: It should be possible to automatically build "bundles" of JS/CSS/etc. that are delivered on-demand while navigating through an Ember application.

**Comment by alan-compeat** [comment]
+1.  Starting now on a very large application and not being able to divide it up into on-demand modules is my largest long term concern.

**Comment by gossi** [comment]
I have another use-case that I gonna face is that one module will provide components that other modules might use. I have no idea yet how to work this out and is for sure one of the tricky parts to cover, too.

**Comment by albertolobrano** [comment]
+1

**Comment by mansona** [comment]
@stefanpenner is there an RFC for the "packager" changes? I just noticed you added the label and I'm wondering if there is any overarching docs (or even just a blog post) that goes a bit deeper into what is involved

**Comment by samdelagarza** [comment]
https://github.com/emberjs/rfcs/pull/10

Sam

**Comment by stefanpenner** [comment]
No written rfc yet. Although chad has been working on some of the foundational changes that will enable it

**Comment by QuantumInformation** [comment]
Do we have a agreed way to do lazy loading for all modules in ember-cli apps?

**Comment by abuiles** [comment]
Closing this in favor of an RFC.

**Comment by theduke** [comment]
Is there an RFC?
Link?

**Comment by GCheung55** [comment]
@theduke https://github.com/emberjs/rfcs/pull/10

**Comment by stefanpenner** [comment]
FYI, our current build tooling improvements are geared to enabled this from the CLI side. There is parallel work planned for the App side.

**Comment by danshapir** [comment]
@stefanpenner can you elaborate regarding the tooling improvements?

**Comment by vire** [comment]
@danshapir we switched to webpack, and there it's a feature out of the box :)

**Comment by danshapir** [comment]
@vire are you using webpack as part of the ember-cli? Because of you ditch the ember-cli the entire addon eco-system pretty much breaks. I would love to hear (and see :smile: ) what you've done!

**Comment by vire** [comment]
No we aren't using webpack w/ ember-cli. But if you really need the feature of lazy loading pre-compiled assets and you don't wanna wait until ember-cli has support for it you should take a look + hack a bit with webpack.

https://webpack.github.io/docs/multiple-entry-points.html  + https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points

Maybe there are more people in the ember ecosystem who have solved this by some more elegant way.
There are multiple solutions how to achieve lazy-loading of pre-compiled assets from a server.

Maybe I should not have write anything to not confuse anybody, but if someone is trying to achieve what I've now describe, he probably needs to check options outside until ember-cli comes with a robust solution.

**Comment by stefanpenner** [comment]
This is still on a ur radar and will be something we pursue after the 2.x release

**Comment by danshapir** [comment]
@stefanpenner good to hear! After 2.x you mean in version 3.0? It sounds like over a year from now.

Not related to here, but i know you are involved in that rfc, are there any news regarding the engines rfc? Any estimations?

**Comment by stefanpenner** [comment]
> It sounds like over a year from now.

I said "something we pursue after the 2.x release", it is in-fact true 3.0 comes after 2.x but so does 2.1 2.2 2.n

> Any estimations?

When its ready

**Comment by danshapir** [comment]
Ha-ha ok. Miss understood 2.x for the entire v2 :smile:

I'm thinking of ember versions, not ember-cli, which already reached 2.x.

Is there anyway to contribute to the effort?
