### ISSUE TITLE
ember init with blueprint fails

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#4023]
Running `ember init contraflow --blueprint https://github.com/knownasilya/app-blueprint.git` inside an empty folder and get the following.

```no-highlight
iradchenko contraflow$ ember init contraflow --blueprint https://github.com/knownasilya/app-blueprint.git
version: 0.2.3
installing
The globPattern "contraflow" did not match any files, so no file updates will be made.
Installing packages for tooling via npm...
npm ERR! install Couldn't read dependencies
ENOENT: no such file or directory, open '/Users/iradchenko/workspace/contraflow/package.json'
Error: ENOENT: no such file or directory, open '/Users/iradchenko/workspace/contraflow/package.json'
    at Error (native)
```

**Edit:**
Hum, seems like I'm not using init correctly. What is the `glob-pattern` for?

**Comment by jgwhite** [comment]
If you have an existing ember-cli project you can use `ember init <glob-pattern>` to target specific files to be updated.

i.e.

```sh
$ ember init package.json bower.json
```

Would just apply updates to `package.json` and `bower.json`.

**Comment by knownasilya** [comment]
@jgwhite as far as I can remember, you could do ember init in an empty project. Is that wrong? Does the project require a `package.json` to get it's name and to obit the glob?

**Comment by jgwhite** [comment]
Yeah that used to be its primary purpose. I think now the invocation is:

```sh
$ ember init --name cool-project --blueprint https://github.com/knownasilya/app-blueprint.git
```

**Comment by knownasilya** [comment]
Thanks!

**Comment by jgwhite** [comment]
:smile:

**Comment by stefanpenner** [comment]
@knownasilya awesome!

i would also accept a shorthand that made: `github://knownasilya/app-blueprint` work

**Comment by knownasilya** [comment]
That second one would be tricky since it could be a path..

**Comment by stefanpenner** [comment]
@knownasilya path is `/` or `./` now.

**Comment by knownasilya** [comment]
Hum, not bad. What about allowing an npm module, e.g. `app-blueprint` or `@knownasilya/app-blueprint`

**Comment by stefanpenner** [comment]
@knownasilya ya i was thinking that as well. maybe npm:<module-name> ?
