### ISSUE TITLE
Warning when using iojs 2.0.0

### ISSUE THREAD

**Issue by ZebraFlesh** [ember-cli/ember-cli#4029]
Using ember-cli with iojs 2.0.0 produces the following warning (error? it's colored red) in the console:

Future versions of Ember CLI will not support v2.0.0. Please update to Node 0.12 or io.js.

To reproduce, just install iojs 2.0.0 and executing any command (such as `ember new foo`)

**Comment by rwjblue** [comment]
I believe that this is resolved on master, and the warning will go away once we do the next release...

**Comment by stefanpenner** [comment]
yup, fixed on master.
