### ISSUE TITLE
peerDependencies not include in built app

### ISSUE THREAD

**Issue by ryanhollister** [ember-cli/ember-cli#4030]
if an addon defines a peer dependency it is not included in the outputted app.js file.

Including peerDependencies in the output of the app.js file supports a more robust testing scenario for addons.

Here is an example scenario:

app
   '----> addon1-plugin
   '----> addon1

addon1-plugin has a peerDependency of addon1. This works perfectly fine in the context of app because app has a dependency of addon1. The breakdown is when addon1-plugin tries to test itself. NPM will successfully install addon1 in npm_modules, but in the resulting app.js from ember test it is not included and therefore any references to it break.

Suggestion is to include peerDependencies in the built JS file.

**Comment by stefanpenner** [comment]
> NPM will successfully install addon1 in npm_modules,

this is changing in npm v3

**Comment by stefanpenner** [comment]
> if an addon defines a peer dependency it is not included in the outputted app.js file.

im some-what nervous supporting peerDependences until npm v3, as some semantics are changing.

**Comment by ryanhollister** [comment]
Thanks for the response stefan. I agree, user's responsibility to install them.

**Comment by ryanhollister** [comment]
I wanted to come back and add some additional context to this ticket and outline the potential wins here.

My team is in the process of taking the ember addon concept and going full bore with it. What we have developed is a series of "base addons" and then addons that extend these base addons.

In typical NPM fashion we would have a dependency structure like so (excuse my over simplification):

addon-dog@1.0.0
    '----> addon-mammal@^1.0.0
                 '----> addon-animal@^1.0.2
addon-tuna@1.0.0
    '----> addon-fish@^1.0.0
                '-----> addon-animal@^1.0.3


The challenge becomes the potential for different versions of 'addon-animal' to be installed in the node_modules hierarchy. In NPM this is fine because everything is self contained. But with ember addons, its really a race condition as to which version is going to be the one in the final app.js.

We have found an easy solution to this would be to use peerDependencies. In the above scenario, addon-animal would be a peerDependency of addon-fish and addon-mammal. Additionally addon-mammal and addon-fish would be peer dependencies of addon-dog and addon-tuna, respectively. This ensures that only one copy of each addon is installed in the main ember-cli application.

A problem arises when you are trying to writes isolated tests for these sub-addons without the context of a main ember app. Since the peerDependencies are not pulled into the resulting JS file, peerDependencies are not found during testing.

I'm happy to dig into the code and try to get a PR together, just want to agree on the functionality. Should we only include peerDependencies when testing? Are peerDependencies even the correct approach to solving the problem of multiple instances of an addon?

**Comment by stefanpenner** [comment]
I am fully aware and largely agree, but my concerns mentioned -> https://github.com/ember-cli/ember-cli/issues/4030#issuecomment-99921903 are not addressed.

I am inclined to wait for NPM v3 to land, which introduces some changes to peerDependencies. At which point in time, we can just unveil the feature as part of our v3 usage.

**Comment by stefanpenner** [comment]
Lets transition this to an [RFC](https://github.com/ember-cli/rfcs) and a potential PR
