### ISSUE TITLE
The addon included() hook "app" argument 

### ISSUE THREAD

**Issue by mmelvin0** [ember-cli/ember-cli#4031]
The `app` argument to an addon's `included()` hook is documented to be an [EmberApp](https://github.com/ember-cli/ember-cli/blob/7bed74beebb82524f1b1292b29cb18a0b4f1eddb/lib/models/addon.js#L338) instance, but it can actually be one of three types of object, depending on usage:

1. `EmberApp` - if addon is built as a direct dependency of an app. 
2. `EmberAddon` - if addon project itself is being built.
3. `Addon` - if addon is a dependency of another addon.

This behavior makes sense to me as `this` is the addon itself, and `app` is really the parent of the addon, not the app persay.

My questions are:

1. Is this this a correct interpretation? If no, what am I missing? If yes, the Ember-CLI documentation does not make this clear.
2. The ember-cli web site seems to indicate there is a second argument (`parentAddon`) to the `included()` hook, from what I can tell, that never appears to be the case anymore?
2. Is the following an appropriate way to access the "top-level" EmberApp or EmberAddon from within `included()` or is there a better approach? (Ignoring that I already suspect my reason for wanting to access that object may be dubious...)

```javascript
// this doesn't work, see my comment below
while (app.parent) {
  app = app.parent;
}
```

**Comment by stefanpenner** [comment]
> If yes, the Ember-CLI documentation does not make this clear.

ya docs are likely out of date.

**Comment by stefanpenner** [comment]
> The ember-cli web site seems to indicate there is a second argument (parentAddon) to the included() hook, from what I can tell, that never appears to be the case anymore?

i believe you are correct

**Comment by mmelvin0** [comment]
I read #3531 and #3718 more carefully and I think these are all related, but not necessarily duplicates.

I also discovered my while loop for finding the ultimate parent `EmberApp` won't work, as it's not directly in that tree (rather it's the `Project`, that makes sense.)

As mentioned in #3531, only top-level addons have `this.app`, which I understand in the case of `app.import()`.

My specific use case is this:
* I have a top-level addon that adds some static CSS via `addons/styles`.
* My addon depends on [ember-cli-autoprefixer](https://github.com/kimroen/ember-cli-autoprefixer) so I don't have to include any vendor-specific CSS in my addon.
* I don't want to impose any additional requirements or dependencies on an app consuming my addon, but I would like the consuming app to be able to configuration ember-cli-autoprefixer, which uses EmberApp options.
* Thus, ember-cli-autoprefixer needs to be able access the top-level EmberApp options no matter how many levels deep it is in the dependency tree.

I wound up doing this in ember-cli-autoprefixer and it seems to work:

```javascript
module.exports = {
  name: 'ember-cli-autoprefixer',
  included: function (parent) {
    while (!this.app && parent) {
      if (parent.app) {
        this.app = parent.app;
      } else {
        parent = parent.parent;
      }
      // ...
    },
    // ...
};
```

So my remaining curiosity is:

1. Is the above a sane approach? Is there a better way to have application-level configuration propagate down to a second-or-greater-level addon?
2. I fully understand the assertion in #3531 that second-level addons shouldn't be doing `app.import()`, but it would be nice to see guidelines for what second-level addons should be allowed to do and what should be restricted. Without that, it's very easy to stumble into dependency hell when creating/consuming a non-trivial number of addons.

**Comment by stefanpenner** [comment]
I'm confuse why this is needed. Addons and nested add-ons are scoped. Just like how npm modules are.

As a nested add-on you just don't get access to the app. If you want to provide vendor'd assets, when your `treeFor` hook is called, with `vendor` you provide the appropriate tree.

**Comment by mmelvin0** [comment]
The only reason I'm interested in accessing `app` on second-and-deeper-level addons is to be able to get at options from the app's top-level `Brocfile.js`.

I take it from your reply that simply isn't something that should be done, which seems reasonable to me now, but should be more clearly documented.

**Comment by mattgrannary** [comment]
Sorry to resurrect this one, but I'm also curious about the "right" way to pass on options to a nested addon. The autoprefixer example above might not be the best example since adding the underlying processor to your own addon is relatively simple, but there are probably more complex situations.

If the nested addon shouldn't know about the top parent application, how would it access the options defined there? Should the options be read by the parent addon and then somehow passed on?
