### ISSUE TITLE
Appears that importing addon namespace no longer works

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#4036]
I came from ember-cli@0.1.12 and just updated to ember-cli@0.2.3 and I have found that my addon imports no longer work.

For example I have a project "boilerplate".  Before I was able to import it like so:

    import boilerplateUtils from 'boilerplate/utils';

Even third party libraries like "ember-validation" are not working.

    import EmberValidations from 'ember-validations';

Any idea of how to fix this issue?

I am getting the following error messages:

    Error while processing route: '...' Could not find module `ember-validations` imported from `...` 

and 

    Error while processing route: '...' Could not find module `boilerplate` imported from `...`

**Comment by rzurad** [comment]
I noticed this as well upgrading from Ember-CLI 0.1.15 to 0.2.3. After the upgrade, none of my tests could import anything from the addon directory. I'm digging through the changes to understand what changed, why, and what I should be doing instead. I'm still in research mode trying to fully understand what the problem on my end is, but it sounds very similar to this ticket.

**Comment by rwjblue** [comment]
This is definitely not a normal situation.  You should:

* Confirm that your `package.json` (at least the default files) match [the default deps](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L22-L34)
* `npm cache clear && rm -rf node_modules && npm install` to make sure you have the correct dependencies installed

**Comment by jackmatt2** [comment]
@rwjblue I will try that out on Monday and get back to you.

**Comment by jackmatt2** [comment]
I found the culprit:  the follwoing was in my boilerplate index.js file and was causing the issue.


      //Ember Bootstrap
      app.import('vendor/ember-addons.bs_for_ember/dist/css/bs-growl-notifications.min.css');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-core.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-alert.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-badge.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-basic.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-breadcrumbs.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-button.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-growl-notifications.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-items-action-bar.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-label.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-list-group.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-modal.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-nav.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-notifications.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-popover.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-progressbar.min.js');
      app.import('vendor/ember-addons.bs_for_ember/dist/js/bs-wizard.min.js');
