### ISSUE TITLE
Segmentation Fault: 11

### ISSUE THREAD

**Issue by jvenator** [ember-cli/ember-cli#4038]
I'm getting a `Segmentation Fault: 11` error when running the ember server in development. It boots up fine, shows all the JSHint errors, then the segfault shows up and the process dies. This may not be an ember-cli problem, but I'm at a loss of where else to start and am getting pretty desperate. Any direction or assistance greatly appreciated!

I have a separate static site project that's using broccoli-cli with both npm and bower packages that's working fine and is able to serve in dev mode without an issue, so I don't think it's a standalone issue in node or npm.

OS X 10.10.3, Xcode 6.3.1, ember-cli 0.2.3, node 0.12.2, npm 2.9.1

To isolate I completely removed/uninstalled node and npm from my system and did fresh installs using the node pkg installer for mac.

I attempted to use `segfault-handler`, and dropped the two lines below into app.js, but it's not reporting anything in console. I'm out of my depth and this point.

```
...
var SegfaultHandler = require('segfault_handler');
SegfaultHandler.registerHandler();

export default App;
```

**Comment by stefanpenner** [comment]
> var SegfaultHandler = require('segfault_handler');
> SegfaultHandler.registerHandler();

that code is in browser land, it wont  do what you think.

* do you have c-extensions ?
* can you provide a repo that reproduces this other machines?

**Comment by jvenator** [comment]
Doh! on putting the segfault-handler in the client-side app. I tried dropping it in a couple different places/ways into the brocfile, but not working.

The repot is private, and I don't have time to create a dummy app to recreate. However, removing `broccoli-sass` from `package.json` got rid of the segfault. We were on the most `v0.6.6`. Blowing this out and specifying the last version I knew worked `v0.6.2` did the trick. Should I close this issue and create one on broccoli-sass instead?

cc: @joliss

**Comment by stefanpenner** [comment]
likely just on node-sass or libsass, as broccoli-sass just wraps those.

**Comment by joliss** [comment]
Yup, can you try to get some sort of stack trace (maybe with gdb - I'm hazy no this) and report it to node-sass? They'll bump it to libsass if necessary.

**Comment by joliss** [comment]
If you can't get a stack trace, it might still be useful if you leave them a bug report with your system specs and build output from npm install; it works for me on Linux, so there must be some system-specific issue going on. Maybe they can hone in on it.

**Comment by jvenator** [comment]
I'll try to isolate at which broccoli-sass release it starts happening and then throw an issue up on node-sass per your suggestion. Thx

**Comment by stefanpenner** [comment]
Keep us posted
