### ISSUE TITLE
[ENHANCEMENT] ember rename newModulePrefix

### ISSUE THREAD

**Issue by grabbou** [ember-cli/ember-cli#4043]
Following up #3988, would be cool to have a command to rename the project (I've started my boilerplate some time ago and wanted to reuse it). I've ended up getting some `watchman` errors and finally, after spending few minutes trying to sort it out, the following command had helped me:

```bash
$ watchman stop-server
```

In the issue linked above there are all occurrences that need to be replaced in order to make it working. Can do a PR but if this is out of ember-cli scope, let's just add a note to docs.

WDYT?

**Comment by stefanpenner** [comment]
ya, this would be good. Lets transition this to a more detailed [RFC](github.com/ember-cli/rfcs)

**Comment by grabbou** [comment]
Ok, will do.
