### ISSUE TITLE
Pod format for models is a little weird

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#4044]
In the current pod format when you generate a pod.
`ember g model employee --pod`

it gets added to the same place routes and controller get added.
`app/pods/employee/mode.js`

I think this is confusing.  Models are an application wide concern, by putting them in the same folder as the routing and controllers it kind of confuses the two concepts.  It appears as though the model belongs to that route somehow but it in fact has nothing to do with it.

Would it not be better to leave the models in the same models folder but add a folder for each one?
```
app/models/employee/model.js
------------------> serializer.js
```

I actually believe the same issue exists for shared components.  I think this is a better structure than adding them to the same place as routes and controllers as they are application wide and not bound to a particular route.
```
app/components/cool-component/component.js
----------------------------> template.js
```

Of course, routable components in Ember 2 would go in the same location as routes.

What do people think?

**Comment by stefanpenner** [comment]
I don't think --pod should work with models. I think They should remain top level

**Comment by rwjblue** [comment]
@jackmatt2 - I am not opposed to:

```
app/models/post/
app/models/post/model.js
app/models/post/serializer.js
app/models/post/adapter.js
```

It can be pretty trivially added to the resolver...

**Comment by rwjblue** [comment]
(this is what we do for components BTW)

**Comment by david-duncan** [comment]
This is somewhat related but I wanted to chime in with some weird behavior we found with serializers when trying to nest with pods. We attempted nesting in pods because we have several different services we offer in our primary app and we wanted to reduce the clutter we were experiencing inside of our models/adapters/serializer folders

https://github.com/ember-cli/ember-resolver/issues/91

I would be happy with the approach @rwjblue is suggesting. Any special considerations for nesting to reduce clutter/collisions?

**Comment by jackmatt2** [comment]
@rwjblue yep, that structure looks good.

**Comment by stefanpenner** [comment]
That structure has issues with refactoring and imports. If people don't import it's fine, but if they import it does become a refactoring hazard today

**Comment by jackmatt2** [comment]
@stefanpenner could you add the new resolver on top of the existing ones with a deprecation warning?

1.  search for app/models/employee/models.js
2.  search for app/pods/employee/model.js (show deprecation warning)
3.  search for app/models/employee.js

**Comment by nathanpalmer** [comment]
Yes, I agree that models should stay outside of the pod (similar to what I mentioned in #3234.) I like what has been suggested so far

```
  |--models/ 
  |  |
  |  |--name/
  |  |  |
  |  |  |-- model.js
  |  |  |-- serializer.js
  |  |  |-- adapter.js
```

**Comment by Kilowhisky** [comment]
+1 for that structure. Models a lot of the times are a representation of business objects or business logic and it seems very counter intuitive to nest them with UI representations that are supposed to be abstracted away from them. 

I think the only use for having models nested with existing pods structure is if you are using a ViewModel or something close to a 1-1 relationship.

**Comment by trabus** [comment]
I'd be down to implement this, we can add a rule in the resolver to look for pods in the models path, the same as it does for components.

**Comment by steffenbrem** [comment]
:+1: Just got the same issue. I really like this approach, the `models` folder feels as a good place for this!

**Comment by GabrielCW** [comment]
Any new information with the integration of this structure? I totally :+1: @nathanpalmer 's model structure suggestion.

**Comment by jackmatt2** [comment]
@GabrielCW it is on the way, see [here](https://speakerdeck.com/rwjblue/a-tale-of-two-pods?utm_source=Ember+Land&utm_campaign=b5bd97b0e9-Ember+Land+Newsletter&utm_medium=email&utm_term=0_6a97a4d258-b5bd97b0e9-280118225)

**Comment by spinlock99** [comment]
:+1: is there an addon or anything that implements the "pods v2.0" structure? I'd like to help out in any way I can.

**Comment by rwjblue** [comment]
Not yet, but we are working hard on solidifying. I'm hoping that we have an RFC soonish.

**Comment by twify93** [comment]
+1 for this one.
I am beginner in EmberJS, but models to be generated in the pods directory looks very strange...

**Comment by Turbo87** [comment]
closing this in favor of https://github.com/emberjs/rfcs/pull/124

**Comment by mitchiru** [comment]
Opposing to the majority: a model reflects in general the idea of a database table, but - can be also a mixed thing eq. relations then it is useful to have a model on a pod.
