### ISSUE TITLE
symlinks on Windows - why do hardlinks and junctions recurse?

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#4047]
I got bored waiting for my builds (80-120 seconds!!!) and took a look at symlink-or-copy.

Only symlinks fail on Windows - hardlinks (file) and junction points (dir) work ok.

I rewrote symlink-or-copy to use hardlinks and junction points if symlink won't work, and found the build seems to recurse back on itself and never completes. What's the reason for that and where should I start looking to fix it?

**Comment by jackmatt2** [comment]
@BryanCrotaz I was having horrible performance on windows also, I eventually converted to linux and a build that was taking 40 seconds then took about 2-3 seconds.

I have a windows pc at home though and have found significant performance increased by:

1. install this https://github.com/felixrieseberg/ember-cli-windows
2. When running `ember serve`; run your cmd.exe command as administrator (right click, run as administrator), otherwise it remains very slow.

Worked for me.

**Comment by BryanCrotaz** [comment]
You also need to use secpol.msc to give all users the right to create
symlinks. That took my build time from 150s to 10s (after doing
everything you suggested too).

Hard links and junction points don't suffer from the same security
issue as symlinks so I'm wondering why we couldn't use them

**Comment by rwjblue** [comment]
> Hard links and junction points don't suffer from the same security
issue as symlinks so I'm wondering why we couldn't use them

On Windows hardlinking to a file triggers a change notification in the file that you are pointing to (not just the destination of the hardlink).  To give an example on why this matters (and the reason we went with symlinks even under Windows):

* Start build
* Build does stuff
* Build hardlinks from a file in `app/templates/foo.hbs` to `tmp/asdfasdfasf/asd/whatever-lol.hbs`
* Hardlinking to `app/templates/foo.hbs` triggered a change notification for that file
* Build restarts
* Loop forever

**Comment by BryanCrotaz** [comment]
That explains it!! Yuck.

**Comment by stefanpenner** [comment]
> That explains it!! Yuck.

If someone writes a custom watcher in windows, it should be possible to not listen for that specific change. Additionally, if sane or broccoli-sane-watcher is augmented to detect this as a false event and blackhole this. This could also fix the issue.

Unfortunately, we lack a champion for this task.

**Comment by stefanpenner** [comment]
> Only symlinks fail on Windows - hardlinks (file) and junction points (dir) work ok.

please be sure to review the docs on http://www.ember-cli.com/#windows which demonstrates how to enable symlinks on windows. MS even provided ember-cli-windows add-on to help automate the setup steps for this.
