### ISSUE TITLE
Ember-cli 0.2.2 fails when creating new application

### ISSUE THREAD

**Issue by shareit** [ember-cli/ember-cli#4050]
Here is the output for the ember --version command:
version: 0.2.2
A new version of ember-cli is available (0.2.3). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.12.2
npm: 2.7.4

The following output is shown when I tried to create a new application (command: ember new testing123):

  ......
  create vendor/.gitkeep
Installing packages for tooling via npm/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:66
    throw new Error(
          ^
Error: Attempt to unlock /var/www/gmg/cozone-dev1/testing123/node_modules/ember-cli-inject-live-reload, which hasn't been locked
    at unlock (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:66:11)
    at cb (/usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/install.js:1004:5)
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/install.js:1008:20
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/lib/utils/locker.js:40:9
    at cb (/usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
    at /usr/local/lib/node_modules/ember-cli/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
    at OpenReq.Req.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:63:22)

I tried to update the ember-cli to 0.2.3 but I found a know issue (#3857) that did not have any solution until now. Please advice.

**Comment by shareit** [comment]
I have reinstall the dependencies and I received a human readable error: EACCESS on /home/my_user/.npm/glob/4.2.2 folder. To temporary fix the issue I have executed the ember new command with sudo.

**Comment by stefanpenner** [comment]
This doesn't seem ember related. Actually a bug in npm I suspect.

I believe an npm install crashed mid-flight for you. And left a dangling lock file. Be sure to purge that lock file, upgrade to the latest npm and try again

**Comment by stefanpenner** [comment]
This seems to have gone stale.

I would suggest updating to the latest ember-cli. If this actually is an ember-cli issue, please provide a reproduction example and i will reopen.

**Comment by shareit** [comment]
I tried to update to the last version of ember-cli two hours ago but the problem with the build errors (#3857) is still present. Currently, I have installed nvm with version v0.12.0, npm last version, ember-cli@0.2.2 and no I have no errors.
