### ISSUE TITLE
[ENHANCEMENT] Add `--secure` option to `ember serve`

### ISSUE THREAD

**Issue by dortort** [ember-cli/ember-cli#4054]
Add ability to run development server with SSL (self-signed certificate).
This is useful when developing apps that require browser permissions such as WebRTC microphone/ camera access. When serving unsecured content, the browser will not remember permissions that were granted.

**Comment by rwjblue** [comment]
There is a PR pending that adds support for this.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/3550
