### ISSUE TITLE
[Proposal] Require dependencies added by blueprints to be declared

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#4061]
Currently any bower/npm package can be installed via a blueprint. This leads to dependencies not being declared in one place, which results in "surprise" dependencies that get installed as a side effect of installing an addon.

In NPM 3.0 these dependencies should be declared as peer dependencies and you will have to manually install them at the top level, in our case an Ember app.  This means for NPM this problem will hopefully go away. We can continue to have `addNpmPackageToProject` as a nice to have, but it will need to cross reference or use the versions in `peerDependencies`.

However we still need a solution for Bower. I suggest we add a `peerDependencies` map inside of addon's `ember-addon` config in the package.json. The same rules would apply for `addBowerPackageToProject`, it must cross reference or use the version in package.json.

__Backstory__
We have an internal registry and we must go through a process to introduce 3rd party modules into the registry. Since there are multiple sources of truth this becomes less than ideal to automate. It's much better if we can look at a configuration file and understand the dependencies.

**Comment by stefanpenner** [comment]
> However we still need a solution for Bower. I suggest we add a peerDependencies map inside of addon's ember-addon config in the package.json. The same rules would apply for addBowerPackageToProject, it must cross reference or use the version in package.json.

do we need the overlap with the existing entries in package.json ?

**Comment by stefanpenner** [comment]
this seems to have gone stale, we can visit post packager + when npm v3 lands.
