### ISSUE TITLE
When using --proxy to an Express server with a body-parser middleware, POSTs hang

### ISSUE THREAD

**Issue by devinus** [ember-cli/ember-cli#4066]
Using ember-cli 0.2.3.

**Comment by devinus** [comment]
For further information, the proxy works when I use an `http-proxy` stub but not using `--proxy`.

**Comment by devinus** [comment]
Even more interesting is that https://github.com/ember-cli/ember-cli/blob/38256ce796861951c6acadab0eed1e8125fc95da/lib/tasks/server/middleware/proxy-server/index.js is almost identical to the blueprint used for an `http-proxy` stub.

**Comment by technomage** [comment]
Given that we are using --proxy to a node server with body parser without issue, I think more investigation is required on your server end. I suggest adding middleware to verify your server completes it's response.

**Comment by stefanpenner** [comment]
I cannot replicate this issue. Can you provide a reproduction example?

**Comment by devinus** [comment]
Going to close this since I can't seem to create a repro.
