### ISSUE TITLE
Where do I use App.instanceInitializer in app.js ?

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#4067]
With the Ember 1.12.0 depreciation for using `container.lookup` in an initializer, where is the place to add the module that calls App.instanceInitializer instead?

**Comment by pixelhandler** [comment]
Ah I see the blog post describes this http://emberjs.com/blog/2015/05/13/ember-1-12-released.html

**Comment by pixelhandler** [comment]
Well the blog post for Ember 1.12.0 mentions app/instance-initializers/*.js but that doesn't seem to work for me using ember -cli version: 0.2.3.

**Comment by rwjblue** [comment]
You need to update ember-cli-load-initializers in bower_components.

**Comment by amk221** [comment]
..after we switch to instance-initializers, how do we test them? (There is no blueprint yet)

**Comment by pixelhandler** [comment]
@rwjblue I uninstalled ember-load-initializers, then tried to reinstall

```
bower install ember-load-initializers
bower                        ENOTFOUND Package ember-load-initializers not found
```

**Comment by stefanpenner** [comment]
@pixelhandler seems like your bower might be stale?

https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L8 seems to be correct, and locally stuff appears to work.

Will reopen if a reproduction case can be provided.

**Comment by skanderm** [comment]
@pixelhandler try:

`bower install ember-cli/ember-load-initializers`

**Comment by herom** [comment]
I updated to `ember-cli 0.2.5` along with `Ember 1.12.0` today and I'm seeing the same issue when moving code into `app/instance-initializers` - the initializers never get invoked or anything.

In my `bower.json` there is definitley `"ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4"` (and was `#0.0.2` just like @pixelhandler described it) and I also tried what @skanderm suggested to no avail... any hints on this one would be highly appreciated @stefanpenner :)

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-load-initializers does appear to lack tests, so maybe something is funky
