### ISSUE TITLE
Difficult to only run unit tests vs. acceptance tests

### ISSUE THREAD

**Issue by jkatsnelson** [ember-cli/ember-cli#4079]
On a larger ember-cli project, like the one I am working on now, it becomes crucial to be able to run unit tests separate from acceptance tests. I don't see an easy way to do that right now.

**Comment by rwjblue** [comment]
`ember test --filter` allows you to filter the tests that run, to only those that match the string provided. You can group your tests to have a name that can be used for this.

**Comment by jkatsnelson** [comment]
Thanks @rwjblue, I noticed that in the docs as well, and in the search bar above the tests. That would be super useful if I could add a regex or something there that said "everything except a string starting with 'Acceptance:'" but otherwise I'll have to find and replace everything OTHER than acceptance tests and write "Unit:" before them...

**Comment by rwjblue** [comment]
Yeah, definitely annoying.  To my knowledge QUnit does not support regexps or inverses in the filter field (you might check in their issue tracker to see if that is on the roadmap).  You could use `ember-cli-mocha`, which provides an `--inverse` flag to `ember test` (and would work like you want).

**Comment by jkatsnelson** [comment]
thanks a lot!

**Comment by jrjohnson** [comment]
Spent a lot of time on this today and it turns out you can invert the filter by prefixing it with !  so `--filter='!acceptance'` will run everything else.
