### ISSUE TITLE
ember test --environment tag isn't working...

### ISSUE THREAD

**Issue by BetaGrumm** [ember-cli/ember-cli#4082]
When I look at ember --help, it claims that --environment &lt;string&gt; can be used to change the build environment when building for tests, but it seems to ignore it and default to the 'test' environment. Does this flag still work?

**Comment by stefanpenner** [comment]
it works, but only supports test / production / development

**Comment by andrei1089** [comment]
@stefanpenner  Is there any way to use a custom environment name for ember test? For ember serve custom names work fine.

**Comment by stefanpenner** [comment]
I don't believe custom truly works in anything but dev. This is not yet supported
