### ISSUE TITLE
dummy.css isn't created when ember-cli-sass is included in an addon

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli#4084]
When developing an addon that uses ember-cli-sass no dummy.css is created. This [issue](https://github.com/aexmachina/ember-cli-sass/issues/52) was originally raised on ember-cli-sass, but the issue appears to be with ember-cli itself.

Example:

```shell
ember addon ember-addon-sandbox
cd ember-addon-sandbox
npm install --save-dev ember-cli-sass # also happens if you use `--save`
touch tests/dummy/app/styles/app.scss
ember serve
open http://localhost:4200 # dummy.css is 404
```

**Comment by chrislopresto** [comment]
A harmless:tm: workaround for this is to create an empty `app/styles/app.scss` file in the *addon's* app directory structure. If that file is present, then dummy.css will be compiled properly. 

For the example above to work, create `ember-addon-sandbox/app/styles/app.scss` with this content:
```scss
// Must be present due to bug in ember-cli 0.2.7 / ember-cli-sass 4.0.1
```

Verified with ember-cli 0.2.7 and ember-cli-sass 4.0.1.

**Comment by mattmarcum** [comment]
@chrislopresto that fix doesn't really work for me - my `dummy/styles/app.scss` isn't getting comiled into `assets/dummy.css`.   `assets/dummy.css` is just blank.  Its not getting a 404 anymore but its not including any styles either.

**Comment by chrislopresto** [comment]
@mattmarcum If you now have an `assets/dummy.css` file, then it sounds like you're past this problem. 

What are the contents of `tests/dummy/app/styles/app.scss`? Whatever you include there should make its way into `assets/dummy.css`.

**Comment by ahouchens** [comment]
The problem I am seeing is that the dummy.css file gets created, but anything written inside of `tests/dummy/app/styles/app.scss` doesn't show up in `dummy.css`.

**Comment by aexmachina** [comment]
You might find that specifying the `extension` option fixes your problem?

**Comment by ahouchens** [comment]
Yep it sure does! Thanks. :)

**Comment by ssirowy** [comment]
>   You might find that specifying the `extension` option fixes your problem?

How does one specify the `extension` option?

**Comment by aexmachina** [comment]
One consults [the docs](https://github.com/aexmachina/ember-cli-sass#usage).
