### ISSUE TITLE
Could not find module htmlbars-runtime after upgrade 0.2.3 -> 0.2.4

### ISSUE THREAD

**Issue by aars** [ember-cli/ember-cli#4089]
I followed the full upgrade instructions (and many other manual methods as well) and I keep getting stuck at `Uncaught Error: Could not find module htmlbars-runtime` in the browser.

When I create a fresh ember app using `ember new testapp` I have no problems.

The only place the module `htmlbars-runtime` is defined is in `bower_components/ember/ember-compile-template.js` and that file does not differ between the new testapp and my failing-to-upgrade project.

Any clues on where to look?

This is the full stacktrace in my browser:

```
Uncaught Error: Could not find module htmlbars-runtime
  internalRequire @ ember.debug.js:55
  requireModule @ ember.debug.js:39
  (anonymous function) @ ember-internals.js:14
  mod.state @ loader.js:141
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  requireFrom @ loader.js:112
  reify @ loader.js:97
  mod.state @ loader.js:140
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  (anonymous function) @ ember-load-initializers.js:23
  default @ ember-load-initializers.js:20
  (anonymous function) @ app.js:14
  mod.state @ loader.js:141
  tryFinally @ loader.js:21
  requireModule @ loader.js:139
  (anonymous function) @ app-boot.js:25
```

**Comment by topaxi** [comment]
Ran into the same issue, I'm using the `start-app` helper for a component, even just importing it seems to trigger the error.

**Comment by aars** [comment]
@topaxi I'm an not familiar with the `start-app` helper. I have not explicitly used it. Any ideas on how to find out?

**Comment by skyuplam** [comment]
Same here.

**Comment by aars** [comment]
I just got a tip that `liquid-fire` might be to blame. Haven't had the change to test that though. https://github.com/ef4/liquid-fire#ember-compatibility-table

**Comment by buschtoens** [comment]
It is `liquid-fire`. Removing it with `npm uninstall --save-dev liquid-fire` fixed the error.

Reported it here: [ef4/liquid-fire#287](https://github.com/ef4/liquid-fire/issues/287)

**Comment by buschtoens** [comment]
Actually, this is just a version problem. Take a look at the issue above, I've added a fix.

**Comment by aars** [comment]
Just to confirm, upgrading `liquid-fire` resolved this issue.
