### ISSUE TITLE
Using Pods on 0.2.5

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli#4094]
I'm not sure how to use pods on 0.2.5. I started a fresh app, moved `app/templates/application.hbs` to `app/pods/application/template.hbs`, and updated `/config/environment.js` to try some different things:

```js
var ENV = {
  podModulePrefix: 'my-app-name/pods'
  // podModulePrefix: 'pods'
  // podModulePrefix: 'app/pods'
}
```

but nothing seems to be working. Ideas?

**Comment by abuiles** [comment]
@samselikoff check https://github.com/ember-cli/ember-cli/pull/3954

**Comment by samselikoff** [comment]
Thanks - I read through, but still must be missing something. Can we no longer have route-related classes under `/pods`?

**Comment by abuiles** [comment]
@trabus ^^

**Comment by trabus** [comment]
I'll try and investigate today. This is extremely odd to me, though it may be related to the podModulePrefix being removed from being removed from the app blueprint. https://github.com/ember-cli/ember-cli/pull/3913

**Comment by trabus** [comment]
Actually, that is exactly the problem. It was being linked up to the config value automatically. You now have to manually add it to your `app.js`.

**Comment by trabus** [comment]
@knownasilya it may have been a bit premature to remove podModulePrefix since we had to delay removing it from the response to the deprecation warning we'd put in.

We may want to update the docs to mention that you need to add it manually now.

**Comment by samselikoff** [comment]
woot, that was it!

app.js
```diff
 App = Ember.Application.extend({
   modulePrefix: config.modulePrefix,
+  podModulePrefix: config.podModulePrefix,
   Resolver: Resolver
});
```

**Comment by zjrosen1** [comment]
@samselikoff @trabus confirmed this is working in 0.2.5

@trabus Any progress on the RFC so we don't get to deep into being podheads

**Comment by trabus** [comment]
@zjrosen1 I deferred to @chadhietala's [rfc](https://github.com/emberjs/rfcs/pull/44).

**Comment by zjrosen1** [comment]
@trabus Thanks.

**Comment by trabus** [comment]
@zjrosen1 I'm going to be focusing on work that will allow conversion between different structures, regardless of what finally lands in the end. 

There are a few components that need to be worked on before this is possible. I'm going to be working on [Structures](https://github.com/ember-cli/rfcs/pull/5) soon, and also an `ember mv` command to facilitate moving/renaming.

**Comment by zjrosen1** [comment]
@trabus sounds amazing looking forward to it. 

Not sure if that should be part of @abuiles ember watson perhaps.

**Comment by trabus** [comment]
@zjrosen1 that was exactly the plan :D

**Comment by zjrosen1** [comment]
@trabus :fire:
