### ISSUE TITLE
Problem with phantomjs testing

### ISSUE THREAD

**Issue by OpakAlex** [ember-cli/ember-cli#4096]
After update ember.js and ember-cli i have issue with phantomjs.
my env:
```node: 0.12.1
   npm: 2.10.0
  ember-cli: 0.2.5
  ember.js: 1.13.0-beta.1```

in Chrome all tests passed, but when i run phantomjs tests, i have issue after build:
```
https://travis-ci.org/ember-admin/ember-cli-admin/builds/62823501
```
I think testem don't run phantomjs...
```
Built project successfully. Stored in "/private/var/www/api-hogs/ember-admin.js/tmp/class-tests_dist-tOm43Gx7.tmp".
^Cnot ok 1 Error
    ---
        message: >
            Received SIGINT signal
    ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by igorrKurr** [comment]
So, i solved this issue. It was happening because when migrating for new computed property i was using 
```javascript
computed({
  get() {}
})
```
and i it wasn't compiled(maybe it was some issues with babel, don't know exactly).

So, simple change this to 

```javascript
computed({
  get: function(){}
})
```

solves issue.

**Comment by TameBadger** [comment]
I have the same issue, but unsure what is causing it, quite troublesome.. Might be a library with the wrong computed property syntax ? or something else.. More digging
