### ISSUE TITLE
ember init replaces dependency files instead of updating/merging

### ISSUE THREAD

**Issue by igorsantos07** [ember-cli/ember-cli#4098]
After upgrading Ember version through, say, `bower install ember@1.12.0`, people at #emberjs told me I should run `ember init` to update my dependencies.

However, that does not seems to be the most intelligent way to update the project, since it recreates all files and asks you to review diffs and confirm or refuse replacements. There's no way to manually merge differences.
That's specially a problem with the dependency files: `bower.json` and `package.json`. It will erase my custom dependencies if I say yes, and I'll miss novelties if I say no.

I think would be nice if there was an `update-project` command that would only handle those cases; or there could be an intelligent parser for those Bower and NPM files, so they would be rewritten with updated versions instead of being replaced by default versions.

**Comment by igorsantos07** [comment]
This seems similar to #3651, but it's a little bit broader.

I think I got in this state because when I first run `ember update` I bindly refused to replace NPM/Bower files without seeing what was going on.

**Comment by stefanpenner** [comment]
This isn't something we will solve before 1.x.

Editing the diff is possible today, if $EDITOR is set. Just like most Unix tools. Although I agree this isn't as ideal as it could be. No quick fix exists. I have some ideas, and at some future point in time when time is available will revisit.

If someone is interested, they are welcome to flesh out an RFC.

**Comment by igorsantos07** [comment]
Maybe there could be an option for "leave as conflicted"? So we could open the file in an editor later and merge manually, or have a `.bkp` with the old version. Blindly ask for replacing seems a bad behaviour.

I'll test using $EDITOR as you said. This could be said in documentation or during the upgrade process as well.

**Comment by adamesque** [comment]
@igorsantos07 I tend to say "yes" to any overwrite that looks meaningful, and then immediately afterward do a `git add --patch` on all files, editing as needed. Unlike the "edit" option offered by ember init, editing a patch this way is more likely to apply cleanly (because it updates the line ranges for you).

Then, once the changes I want are staged, I toss unwanted changes with `git checkout --` on any affected files.

This technique requires a little git-fu, but for me it's the most reliable method of upgrading.

**Comment by stefanpenner** [comment]
> git add --patch on all files,

i wonder if we showed do this instead of `e` ...

**Comment by adamesque** [comment]
> i wonder if we showed do this instead of e ...

Looking at the docs for [`git add --edit`](http://git-scm.com/docs/git-add), it looks like it manually adjusts the hunk headers before applying the patch. If we could do that with the result of `e`, it'd become infinitely more useful.

I'd be wary about forcing people into a git workflow without lots of warning though. I don't think many people have strong mental models for what `git add` actually does.

**Comment by stefanpenner** [comment]
We can add g which does the git route?

**Comment by igorsantos07** [comment]
I also feel odd about inserting git-fu (good expression for that!) in a framework upgrade routine. Ideally we are updating files, this has nothing to do (directly at least) with `git add`s. We should not mix things up.
