### ISSUE TITLE
Documentation: module import validation

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#4103]
[This section of the docs](http://www.ember-cli.com/#module-import-validation is confusing) is confusing. Especially: 

> you may have to add it to the whitelist in tasks/options/validate-imports.js.

That path doesn't exist in a stock ember-cli app, so it's not at all obvious what users are supposed to actually do.

While we're at it, I think this:

> this project uses grunt-es6-import-validate.

is an internal implementation detail that doesn't belong here.

**Comment by stefanpenner** [comment]
seems like this is from the EAK days, removed -> https://github.com/ember-cli/ember-cli/commit/1bc891b000289ee6fd7bc4186026077b48c530a7

thanks for reporting!

**Comment by stefanpenner** [comment]
i also noticed the edit link was broken: https://github.com/ember-cli/ember-cli/commit/5c6a80824c309151db03d8c8b5020fc23edd3640
