### ISSUE TITLE
Make ember help friendlier for Dvorak users

### ISSUE THREAD

**Issue by ipitythefoo** [ember-cli/ember-cli#4105]
If you look carefully at [the Dvorak keyboard layout](https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard#/media/File:KB_United_States_Dvorak.svg), you will see that "R" is immediately to the left of "L" and "D" is immediately to the left of "H".

On a fateful day several weeks ago, I was on the command line attempting to type `ember --help`.  It so happened that my right hand was shifted to the left by one key, and I ended up typing `ember --derp`.  This had the very unfortunate consequence of preventing access to helpful documentation.

I would like to humbly request that [this line](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/help.js#L23):

    aliases: [undefined, 'h', 'help', '-h', '--help'],

be expanded to:

    aliases: [undefined, 'h', 'help', 'derp', '-h', '--help', '--derp'],

to better accommodate the less fortunate Dvorak keyboard users.  Thank you.

**Comment by stefanpenner** [comment]
that is a funny typo. I wouldn't be apposed to it being added as an easter egg :)
