### ISSUE TITLE
add-ons unit tests fail to retrieve custom factories

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4110]
Steps to replicate:
Create an ember-cli addon
Create a new file `/addon/requests/foo`
Create a new unit test `/tests/unit/requests/foo`

Use `moduleFor('requests:foo')` // This fails unless you also create `/app/requests/foo`

**Comment by stefanpenner** [comment]
not an issue with ember-cli, rather the test helpers.

**Comment by olivierlesnicki** [comment]
Will raise it against it.

Thanks for pointing me in the right direction @stefanpenner
