### ISSUE TITLE
Security policy error on updating to 0.2.0

### ISSUE THREAD

**Issue by ewilson** [ember-cli/ember-cli#4111]
When updating from 0.1.15 to 0.2.0 I encountered an error regarding the content-security-policy.

My application makes calls to an api that runs (in development) on localhost:8000. After upgrading to 0.2.0 those calls are being sent to localhost:4200. Running `ember s --proxy http://localhost:8000` does not fix the problem.

More details here: http://stackoverflow.com/questions/30309489/security-problems-in-upgrading-ember-application

Here is the diff between my applications working `bower.json` and `package.json` and the failing ones:

    diff --git a/bower.json b/bower.json
    index c0a4e6f..c562e10 100644
    --- a/bower.json
    +++ b/bower.json
    @@ -3,15 +3,15 @@
       "dependencies": {
         "jquery": "^1.11.1",
         "ember": "1.10.0",
    -    "ember-data": "1.0.0-beta.14.1",
    -    "ember-resolver": "~0.1.11",
    -    "loader.js": "ember-cli/loader.js#1.0.1",
    +    "ember-data": "1.0.0-beta.15",
    +    "ember-resolver": "~0.1.12",
    +    "loader.js": "ember-cli/loader.js#3.2.0",
         "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    -    "ember-cli-test-loader": "ember-cli/ember-cli-test-loader#0.1.1",
    +    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
         "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
         "ember-qunit": "0.2.8",
         "ember-qunit-notifications": "0.0.7",
         "qunit": "~1.17.1",
    -    "bootstrap": "~3.3.1"
    +    "bootstrap": "~3.3.4"
       }
     }
    diff --git a/package.json b/package.json
    index 74738b0..b080c3d 100644
    --- a/package.json
    +++ b/package.json
    @@ -20,20 +20,17 @@
       "license": "MIT",
       "devDependencies": {
         "broccoli-asset-rev": "^2.0.0",
    -    "ember-cli": "^0.1.15",
    -    "ember-cli-6to5": "^3.0.0",
    -    "ember-cli-app-version": "0.3.1",
    +    "ember-cli": "0.2.0",
    +    "ember-cli-app-version": "0.3.2",
    +    "ember-cli-babel": "^4.0.0",
         "ember-cli-content-security-policy": "0.3.0",
    -    "ember-cli-dependency-checker": "0.0.7",
    -    "ember-cli-htmlbars": "^0.6.0",
    +    "ember-cli-dependency-checker": "0.0.8",
    +    "ember-cli-htmlbars": "0.7.4",
         "ember-cli-ic-ajax": "0.1.1",
         "ember-cli-inject-live-reload": "^1.3.0",
    -    "ember-cli-qunit": "0.3.7",
    +    "ember-cli-qunit": "0.3.9",
         "ember-cli-uglify": "1.0.1",
    -    "ember-data": "1.0.0-beta.14.1",
    -    "ember-django-adapter": "0.5.3",
    -    "ember-export-application-global": "^1.0.2",
    -    "express": "^4.8.5",
    -    "glob": "^4.0.5"
    +    "ember-data": "1.0.0-beta.15",
    +    "ember-export-application-global": "^1.0.2"
       }
     }

Here is the error that I receive when calls to the api are made:

    [Report Only] Refused to connect to http://localhost:4200/myapi because it violates the following Content Security Policy directive: "connect-src http://localhost:8000 ws://localhost:35729 ws://0.0.0.0:35729".
    jQuery.ajaxTransport.send @ jquery.js:9625jQuery.extend.ajax @ jquery.js:9215ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest_adapter.js:899initializePromise @ ember.debug.js:50488Promise @ ember.debug.js:52116ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest_adapter.js:883ember$data$lib$system$adapter$$Adapter.extend.findQuery @ rest_adapter.js:392ember$data$lib$system$store$$_findQuery @ store.js:2025Ember.Object.extend.findQuery @ store.js:916Ember.Object.extend.find @ store.js:493model @ index.js:7EmberObject.extend.deserialize @ ember.debug.js:23915applyHook @ ember.debug.js:50118HandlerInfo.runSharedModelHook @ ember.debug.js:48139subclass.getModel @ ember.debug.js:48365__exports__.bind @ ember.debug.js:49992tryCatch @ ember.debug.js:50441invokeCallback @ ember.debug.js:50453publish @ ember.debug.js:50424(anonymous function) @ ember.debug.js:28563Queue.invoke @ ember.debug.js:854Queue.flush @ ember.debug.js:919DeferredActionQueues.flush @ ember.debug.js:724Backburner.end @ ember.debug.js:149Backburner.run @ ember.debug.js:204Backburner.join @ ember.debug.js:223run.join @ ember.debug.js:16679run.bind @ ember.debug.js:16731jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503

Has anyone else seen anything like this?

For the record, I originally tried updating straight to 0.2.5, but had similar results.

**Comment by stefanpenner** [comment]
> Here is the error that I receive when calls to the api are made:

this isn't an error it is a `[Report Only]` warning
