### ISSUE TITLE
Overrides folder

### ISSUE THREAD

**Issue by brandonjmckay** [ember-cli/ember-cli#4112]
I was looking around for suggestions on where to put code like the following into CLI:

```coffee
`import Ember from 'ember'`

LinkTo = Ember.LinkView.reopen
  # This adds the any defined data attribute to the link-to
  init: ->
    @_super()
    Ember.keys(@).forEach (key)=>
      if key.substr(0, 5) is 'data-'
        @get('attributeBindings').pushObject key

`export default LinkTo`
```

I found a suggestion for putting it into an `overrides` folder, and that seemed pretty decent.
Are there any plans to create a generator, or first class support for something like that?

Would that be an agreed place to put overrides?

**Comment by stefanpenner** [comment]
this doesn't appear to be an ember-cli issue, stackoverflow or the discourse forms are likely better venues for such discussion.

**Comment by brandonjmckay** [comment]
Ok. Ya, it's more of a feature request.
