### ISSUE TITLE
visiting "/tests" doesn't use #ember-testing-container

### ISSUE THREAD

**Issue by atomkirk** [ember-cli/ember-cli#4117]
If you want to test by visiting `/tests`, you have to run the server with `ember server -e test` or it acts funky and doesn't render the application into the `#ember-testing` element. ideally, visiting `/tests` would run the tests in a temporary test environment, just for that path. Or, I at least think the docs http://www.ember-cli.com/#running-existing-tests should be updated to explain that the user should start the server with `-e test` if they want it to work correctly…

**Comment by stefanpenner** [comment]
this doesn't appear to be the case for me, can you provide an reproduction?

**Comment by atomkirk** [comment]
Sorry, I didn't specify that it must be an acceptance test. Did you try that?

**Comment by stefanpenner** [comment]
yes

**Comment by atomkirk** [comment]
do you have a link to an the example you're trying so I can see what you're expecting?

**Comment by stefanpenner** [comment]
```
ember new my-cool-app
cd my-cool-app
ember install ember-moment
```

**Comment by atomkirk** [comment]
ah, ok, if you set `storeConfigInMeta: false` then it will do what I'm describing.

**Comment by brettburley** [comment]
See https://github.com/ember-cli/ember-cli/issues/2480.
