### ISSUE TITLE
Running ember update targets %ProgramFiles%\nodejs\node_modules instead of %AppData%

### ISSUE THREAD

**Issue by petetnt** [ember-cli/ember-cli#4119]
I have Ember-CLI installed globally with

``` bash 
  npm install -g ember-cli
```

Today I got an update prompt, which I ran with `ember update` which game me this:

``` bash
A new version of ember-cli is available (0.2.5). To install it, type ember update.

A new version of ember-cli is available (0.2.5).
[?] Are you sure you want to update ember-cli? Yes
Updating ember-cli...
There was an error – possibly a permissions issue. You may need to manually run npm install -g ember-cli.
EPERM, mkdir 'C:\Program Files\nodejs\node_modules\ember-cli'
Error: EPERM, mkdir 'C:\Program Files\nodejs\node_modules\ember-cli'
    at Error (native)
```

The error also contained the solution (of updating ember-cli by installing it again with npm), which was great. But why is `ember update` trying to do anything under `%PROGRAMFILES%` in the first place, instead of the default global installation folder `%APPDATA%\Roaming\npm\node_modules`? 

Ember-CLI 0.2.3 to 0.2.5, Windows 8.1.

**Comment by petetnt** [comment]
X-ref: npm/npm/issues/7723 

In that issue it's suggested that spawning a child process of `npm` running `install -g ember-cli` instead of running `npm.commands.install` (even with the prefix) like it's done in  [tasks/update.js#L10](https://github.com/ember-cli/ember-cli/blob/fc30c715fe433dafecc1d5e752bc8eb3dc0e9da1/lib/tasks/update.js#L10)

**Comment by stefanpenner** [comment]
`ember update` is sorta broken, just use `npm` for now until it is fixed.

**Comment by felixrieseberg** [comment]
...and even npm update is sort of broken (at least up to version 2). On Windows, we're still battling those things (see for instance the very fact that I wrote an [upgrader for npm itself](github.com/felixrieseberg/npm-windows-upgrade)).

The trouble here is basically that Joyent still installs a version of npm in its nodejs folder, while putting npm global module folder first on the PATH.

**Comment by stefanpenner** [comment]
@felixrieseberg off the top of your head, is this something we can address on our side? (reasonable)

**Comment by stefanpenner** [comment]
> ember update is sorta broken, for now use npm for now until it is fixed.

`ember update` is also gone now

**Comment by petetnt** [comment]
Nice, :+1: for nuking `ember update` altogether.
