### ISSUE TITLE
resolver of dummy test apps in ember-addons doesn't work correctly

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4121]
The dummy app doesn't pick up the adapter defined in the `/addon/adapter/application.js` nor `/app/adapter/application.js` files.

**Comment by stefanpenner** [comment]
it should work from `/app/adapter/application.js` can you provide a repo demonstrating this problem?

**Comment by rwjblue** [comment]
The dummy app for an addon does not use pods out of the box.  Also, addons that are intended for general purpose use cannot use pods in `app/` folder because the consuming application could have any `podModulePrefix` (which is generally not known by the addon at build time).

**Comment by stefanpenner** [comment]
@rwjblue this doesn't appear to be pod structure (or am I missing something)

**Comment by rwjblue** [comment]
No, I need more :coffee:.  Carry on....

**Comment by olivierlesnicki** [comment]
@rwjblue it wasn't about pod structure.
Unable to replicate on a fresh add-on, therefore closing.

**Comment by stefanpenner** [comment]
> Unable to replicate on a fresh add-on, therefore closing.

if you find more hints please share.

**Comment by olivierlesnicki** [comment]
@stefanpenner will do
