### ISSUE TITLE
How to share static assets when bower is no longer supported?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#4122]
Today my team is using bower to share compiled css assets (doing the scss compile in a single place /then making the final css output something we can app.import across projects).

In preparation for ember-cli vNext (w/out bower) how should teams share assets like this?

**Comment by stefanpenner** [comment]
NPM, no convention exists yet.

* we will continue to support bower although as optional add-on. Ember's own dependencies will no longer be provided via it.
* vendor/* will continue to work

**Comment by toranb** [comment]
@stefanpenner Sounds good -thanks again for all your contributions to ember and ember-cli. When people ask why I use ember ... you can guess the noun I fill in the blank with :)
