### ISSUE TITLE
ember install:addon should be deprecated like ember install:npm

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4131]
https://github.com/ember-cli/ember-cli/blob/master/lib/commands/install-npm.js

@DanielOchoa got a chance to do this?

**Comment by DanielOchoa** [comment]
I have [this pull request open](https://github.com/ember-cli/ember-cli/pull/3854). It was pending on the change to core object otherwise the deprecation warning shows twice, but it is fully working.

**Comment by DanielOchoa** [comment]
I rebased against upstream/master, I'm running `test-all` and if all goes well I'll update the PR.

**Comment by DanielOchoa** [comment]
Well, ember install:npm is currently not showing a deprecation message but just letting the user know that he/she should manage npm packages on their own. 

Perhaps it should still work but show a deprecation message just like on that PR I have open.
