### ISSUE TITLE
ember generate helper should enforce hyphen

### ISSUE THREAD

**Issue by pixelterra** [ember-cli/ember-cli#4133]
I just spent hours trying to figure out why my helper wasn't loading, only to find out that it needs to have a hyphen. If it needs to have a hyphen, why does the generate helper command allow the generation of a helper without a hyphen?

**Comment by trabus** [comment]
@pixelterra see https://github.com/ember-cli/ember-cli/issues/3286

**Comment by trabus** [comment]
We could put a warning in when generating a helper sans-hyphen that you need to register it yourself, or make use of https://github.com/stefanpenner/ember-cli-auto-register-helpers.

In components we do this check in the [normalizeEntityName hook](https://github.com/ember-cli/ember-cli/blob/master/blueprints/component/index.js#L45).

**Comment by stefanpenner** [comment]
@trabus warning seems fine.
