### ISSUE TITLE
Blueprints listing contains random file entries

### ISSUE THREAD

**Issue by elidupuis** [ember-cli/ember-cli#4136]
When listing available blueprints via `ember g --help` I'm seeing random files listed like `.jshintrc` or `.DS_Store`. I've been told the listing should be filtered to folders that actually contain an `index.js`.

![pasted_image_at_2015_05_21_11_46_am](https://cloud.githubusercontent.com/assets/196410/7756844/1cecc1de-ffbb-11e4-997d-e2302bc34ebc.png)

First mentioned in Slack [here](https://embercommunity.slack.com/archives/ember-cli/p1432233867000399).

**Comment by stefanpenner** [comment]
cc @trabus @jgwhite mind taking a look?

**Comment by trabus** [comment]
Yep, I'll try and knock something out tonight.

**Comment by trabus** [comment]
@jgwhite is there a specific reason we're [setting a default blueprint constructor](https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1242) if there is no `index.js` for the file we're attempting to load as a blueprint? 
What's happening is that we're checking if the file `/ember-cli/blueprints/.jshintrc/index.js` exists with `fs.existsSync`, which it doesn't, which let's it through as if it were a valid blueprint. Would checking if it's a directory be sufficient?

**Comment by jgwhite** [comment]
@trabua yes, definitely! Good catch.

**Comment by jgwhite** [comment]
@trabus yes, definitely! Good catch.
