### ISSUE TITLE
Expressions directly after HTML comment start are unbounded from the comments

### ISSUE THREAD

**Issue by petetnt** [ember-cli/ember-cli#4144]
Unsure if this belongs to here, ember-cli/ember-cli-htmlbars or tildeio/htmlbars, but here it is:

Using the latest (0.2.5) Ember-CLI with ember-cli-htmlbars 0.7.4, any expression `{{ }}` starting directly from the HTML comment start `<!--` results to the expression being unbounded.

For example,

``` html
  <!--{{input type="text" value="something">-->
```
Results in:

``` html
  <input type="text" value="something">
  <!---->
```

However, 

``` html
  <!-- Some comment here {{input type="text" value="something">-->
  <!--  {{input type="text" value="something"}} notice the space between - and { -->
```

results in:

``` html
  <!-- Some comment here <input type="text" value="something">-->  
  <!--  {{input type="text" value="something"}} notice the space between - and { -->
```

**Comment by stefanpenner** [comment]
This is likely an htmlbars thing, but should likely be tracked in ember.js instead of ember-cli. I would recommend you reopen the issue at ember.js

**Comment by petetnt** [comment]
Sure thing, thanks again @stefanpenner!
