### ISSUE TITLE
`ember build --environment production` hangs

### ISSUE THREAD

**Issue by zyllorion** [ember-cli/ember-cli#4145]
Possibly related to https://github.com/ember-cli/ember-cli/issues/4004 although that cites less as an issue.  I do not use less.

I have tried very latest 12.3 node.js and 2.0.2 io.js, on latested mac osx.
Command used is `ember build --environment production`.

Global packages:
```
/usr/local/lib
├── bower@1.4.1
├── ember-cli@0.2.5
├── ember-cli-i18n@0.0.6
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── npm@2.9.0
├── npm-check-updates@1.5.1
├── phantomjs@1.9.17
└── testem@0.8.3
```

Project packages
```
    "broccoli-asset-rev": "2.0.3",
    "broccoli-env": "0.0.1",
    "broccoli-file-creator": "0.1.0",
    "broccoli-merge-trees": "^0.2.1",
    "broccoli-static-compiler": "0.2.1",
    "connect-restreamer": "1.0.2",
    "ember-cli": "0.2.5",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "",
    "ember-cli-bootstrap-datepicker": "0.4.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "1.0.1",
    "ember-cli-htmlbars": "0.7.7",
    "ember-cli-i18n": "0.0.5",
    "ember-cli-ic-ajax": "0.1.2",
    "ember-cli-inject-live-reload": "1.3.1",
    "ember-cli-log-observers-and-computed": "0.0.2",
    "ember-cli-mirage": "https://github.com/samselikoff/ember-cli-mirage/tarball/master",
    "ember-cli-qunit": "0.3.14",
    "ember-cli-sass": "4.0.0",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-export-application-global": "1.0.2",
    "ember-wuphf": "0.0.2",
    "express": "4.12.4",
    "glob": "5.0.7",
    "morgan": "1.5.3"
```

For reference to other issue, I have an empty app.css (single line comment), and an app.scss which has numerous imports (although build still hangs if I comment entire file.

Here is the output:
```
  babel [BABEL] boot/word-cloud/view.js: Start transformer builtin-trailing +1ms
  babel [BABEL] boot/word-cloud/view.js: Finish transformer builtin-trailing +3ms
  babel [BABEL] boot/word-cloud/view.js: Generation start +0ms
  babel [BABEL] boot/word-cloud/view.js: Generation end +6ms
Building.  broccoli-caching-writer  cache eviction due to: 
     - {directory, ., 16832, 170, 170, 1432288610000} 
     - {undefined} +0ms
Building.. <-- hangs here, no animation
```

**Comment by zyllorion** [comment]
A bit of guesswork and I've found that removing the following dependency allows the production build to complete:
```
"ember-cli-uglify": "1.0.1"
```

**Comment by stefanpenner** [comment]
Can you provide a repo that demonstrates this issue? Otherwise it is unlikely we can figure out the issue as it may be something related to the contents of the app itself

**Comment by stefanpenner** [comment]
i've seen issues, when trying to uglify extremely massive files. Like the output of emscripten.

**Comment by stefanpenner** [comment]
this seems to have gone stale. If a reproduction can be provided, I will glady reopen.

**Comment by mihaiscurtucb** [comment]
My experience is that the process doesn't hang, it just takes up to 10 minutes on a decent machine. You can monitor the process CPU usage to see that it's still running.
