### ISSUE TITLE
in-repo addon Brocfile.js ignored

### ISSUE THREAD

**Issue by atomkirk** [ember-cli/ember-cli#4149]
A Brocfile.js is not created when I use ember-cli to generate an in-repo addon, but if I add one manually, is there a reason why it is ignored?

**Comment by stefanpenner** [comment]
> A Brocfile.js is not created when I use ember-cli to generate an in-repo addon, but if I add one manually, is there a reason why it is ignored?

there can only b 1 brocfile per project. Brocfile is basically like the `main` file, so add-ons brocfiles are only consulted when developing the addon in isolation. Not when part of the larger graph.

This is why we have the `treeFor` hooks in the addon-main.
