### ISSUE TITLE
ember init does not create dummy app folder properly

### ISSUE THREAD

**Issue by quaertym** [ember-cli/ember-cli#4156]
I was working on `ember-cli-dependency-checker` and tried to create `tests/dummy/app` folder with `ember init`. The created folder does not include `tests/dummy/app/styles` folder which results in the following error on `ember serve`:
```
Attempting to watch missing directory: tests/dummy/app/styles
```
Adding `tests/dummy/app/styles/.gitkeep` manually fixes it.

**Comment by quaertym** [comment]
Related https://github.com/ember-cli/ember-cli/issues/2896

**Comment by stefanpenner** [comment]
don't think this is still an issue, if it is a reproduction on latest would be great.
