### ISSUE TITLE
docs: more user-friendly sourcemap config section

### ISSUE THREAD

**Issue by nruth** [ember-cli/ember-cli#4161]
I just saw http://www.ember-cli.com/#source-maps while setting up a new ember-cli 0.2.5 project, and think it needs to give more information. It currently says:

```
Ember CLI supports producing source maps from your CSS and JS files. Source maps are configured by the sourcemaps option and are disabled in production by default.

In dev, the default setting is equal to:

sourcemaps: {
  enabled: true,
  extensions: ['js']
}
```

I'd like to suggest:

- an example with coffeescript
- an example with sass
- or saying which languages are / aren't supported, or how to find out
- explaining whether "extensions" is for the source file (css, js, scss, coffee, etc) or the output file (css, js) 

For reference, I think it was added with https://github.com/ember-cli/ember-cli/pull/2727 but I didn't see mention of these things there either.

**Comment by stefanpenner** [comment]
@nruth sure, would gladly accept a PR that  improves these docs.

**Comment by nruth** [comment]
maybe @ef4 can comment on how/if it works with addons like coffeescript and sass? I'm too lost with it to write something helpful at the moment.

**Comment by stefanpenner** [comment]
the code that @ef4 wrote just works on JS

**Comment by ef4** [comment]
Yes, although I hope that other modules will adopt the same standardized
config, so that you can just list all the file types you want to turn on
source mapping for in one place.

**Comment by nruth** [comment]
Closing in favour of the pr. Please check I've not introduced errors.
