### ISSUE TITLE
In-repo addon dependencies

### ISSUE THREAD

**Issue by gdub22** [ember-cli/ember-cli#4164]
I've added some dependencies to an in-repo addon's package.json dependencies hash.  They only work if you run `npm install` directly in that addon's directory.  It is possible for them to install when running `npm install` from the project root (like standard addons)?  Doing it from each directory is a slightly awkward requirement to someone cloning the project.

**Comment by rwjblue** [comment]
If a given dep exists in the project's `package.json` they are available in the in repo addon (regardless of if the in-repo-addon's `package.json` lists the dep).  So if you don't want to run `npm install` in the in-repo-addons, you can add the deps to the projects `package.json`.

The idea behind in-repo-addons is that they are relatively lightweight and low ceremony.  If you find yourself needing the addon to have nested dependencies that do not belong in the project itself you should likely consider making it a full fledged addon instead...

**Comment by gdub22** [comment]
Great, thanks for the info, makes sense. The use-case was themes so I needed any preprocessing to run within the addon first, which required the dependency at the addon's level.  I have some other ideas. Thanks!
