### ISSUE TITLE
ember build -prod builds errored dist

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#4165]
I get the following error `Computed Property declared without a property function` when using 'Pause On Caught Exceptions' checkbox. Everything works when using `ember build` without the `-prod` argument.

**Comment by stefanpenner** [comment]
> I get the following error Computed Property declared without a property function when using 'Pause On Caught Exceptions' checkbox. Everything works when using ember build without the -prod argument.

Can you provide a repo that demonstrates this issue? (or is just on an ember repo, and a recent change?)

**Comment by knownasilya** [comment]
Looks like this is the line: https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-metal/lib/computed.js#L592

**Comment by knownasilya** [comment]
Does development turn on `new-computed-syntax` and prod doesn't?

**Comment by stefanpenner** [comment]
@knownasilya looks like a bug in ember?

**Comment by stefanpenner** [comment]
ember prod, doesn't appear to have this line of code

**Comment by knownasilya** [comment]
Hum, looks like I was using 1.11.3 and thought it was 1.12. But 1.12 doesn't work either but doesn't seem to have the same error.

**Comment by stefanpenner** [comment]
that line of code also doesn't exist in ember.prod.js
as it minifies to:
```js
        function h(e) {
            var t;
            arguments.length > 1 && (t = [].slice.call(arguments),
            e = t.pop());
            var r = new l(e);
            return t && r.property.apply(r, t),
            r
        }
```

**Comment by stefanpenner** [comment]
can you provide a repo demonstrating this? I'll gladly look into it

**Comment by stefanpenner** [comment]
this may be an ember and ember-data version mismatch.

**Comment by knownasilya** [comment]
I did forget to update ember-data in my package.json, trying now.

**Comment by stefanpenner** [comment]
> Rants about the need to update two locations for ember-data version.

lol, ya its crazy. @chadhietala starts to unblock that

**Comment by knownasilya** [comment]
Sent you an email with the code.

**Comment by stefanpenner** [comment]
@knownasilya got it!

**Comment by stefanpenner** [comment]
@knownasilya still waiting for it to install. It appears like you have `babel` installed via an old version of ember-cli-babel. If you upgrade, you no longer need to incur the extremely long `fsevents node-gyp` introduces by `chokidar`

Its also crazy, it appears you have to install two different versions of `ws` and encure the compiles of the dependent native modules. Once https://github.com/Automattic/socket.io/issues/2107 happens, we can likely mitigate that.

**Comment by knownasilya** [comment]
Babel is installed in dependencies for the polyfills, but I think they should be in devDeps (ops).

**Comment by stefanpenner** [comment]
ah

**Comment by knownasilya** [comment]
I'm using 5.0.0 which is the latest, right? https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L25

**Comment by knownasilya** [comment]
I submitted a request to update it earlier this morning: https://github.com/babel/broccoli-babel-transpiler/issues/25

**Comment by stefanpenner** [comment]
@knownasilya "ember-cli-babel": "^4.0.0", in your package.json

also, i am unable to get your app to boot. Can you provide instructions?

**Comment by knownasilya** [comment]
The normal flow should work:

```bash
npm install
bower install
ember build
npm start
```

**Comment by stefanpenner** [comment]
> The normal flow should work:

ah, the normal flow for me isn't an initial build, rather using `ember s` or `ember test --server`

**Comment by knownasilya** [comment]
We have server-side and client-side in one app, and we use `server` folder for that code. I remember this conversation from a little while ago haha :smile_cat:

**Comment by stefanpenner** [comment]
> We have server-side and client-side in one app, and we use server folder for that code. I remember this conversation from a little while ago haha

do you just run `ember build` each time you make a change?

**Comment by knownasilya** [comment]
No I have `npm run watch` hooked up to `ember build --watch` and I run `npm start` and `npm run watch` in two different terminals.

**Comment by stefanpenner** [comment]
> No I have npm run watch hooked up to ember build --watch and I run npm start and npm run watch in two different terminals.

such complexity :P

**Comment by stefanpenner** [comment]
@knownasilya it seems to be https://github.com/rwjblue/ember-cli-delay-app-boot

**Comment by rwjblue** [comment]
ember-cli-delay-app-boot has been updated, and v1.0.2 should properly handled the environments.

**Comment by stefanpenner** [comment]
:)

**Comment by knownasilya** [comment]
Thanks @rwjblue
