### ISSUE TITLE
Allow multiple index files

### ISSUE THREAD

**Issue by mattcroberts** [ember-cli/ember-cli#4174]
Ember cli currently does not allow multiple index files for use in different situations. It would be good to be able to specify this as configuration such as:

```
var app = new EmberApp({
  inputPaths: {
    app: {
      index: ['index.html', 'index.jsp']
    }
  }
});
```

The use case for this is that I currently have a Java app which my ember-cli app needs to integrate with, this requires a JSP file to house the app but if I change ember-cli to only use a JSP, then ember serve will cease to work as its not a valid HTML file.

Currently my workaround involves overriding the private method ```EmberApp.prototype.index``` as seen in https://gist.github.com/mattcroberts/495475ee547d2a17494c

**Comment by stefanpenner** [comment]
can you share more information

* How do the 2 files differ
* can you provide examples?
* do both get blueprinted?

**Comment by mattcroberts** [comment]
The two files are similar but in my case the JSP has imports at the top such as

``` <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %> ```

and variables are injected into the page from the server like so

```  <meta name="someVar" content="<c:out value="${someVar}"/>"> ```

additionally there is a small amount of logic.

Yes both files are hydrated and fingerprinted in production.

**Comment by stefanpenner** [comment]
thanks, this seems reasonable.

**Comment by wayne-o** [comment]
I could have done with this last year. Taking an approach similar to
discourse with their preload store.

**Comment by stefanpenner** [comment]
If someone has time for a PR that would be awesome. Otherwise someday I may get to it

**Comment by stefanpenner** [comment]
If someone has time for a PR that would be awesome. Otherwise someday I may get to it

**Comment by stefanpenner** [comment]
Would accept a detailed RFC or PR for this
