### ISSUE TITLE
Feature request: Let "ember install" & "ember uninstall" take multiple addons

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#4176]
It would be great for project initialization, if `ember install <addon>` could take a variable number of addons at once. This makes bootstrapping a new project way more comfortable.

```bash
$ ember install ember-cli-autoprefixer ember-cli-sass ember-cli-emblem ...
```

**EDIT**: As mentioned in #3163 this also applies to `ember uninstall <abc> <def> <ghj> ...`.

**Comment by stefanpenner** [comment]
Ya, been meaning to add this one for some time.

**Comment by stefanpenner** [comment]
* should install the NPM modules
* should aggregate generators that need to be run (for addons)
* should then run generators in the order the NPM module where installed

**Comment by DanielOchoa** [comment]
- [x] `ember install` with multiple arguments
- [ ] `ember uninstall` with multiple arguments

**Comment by stefanpenner** [comment]
> ember uninstall with multiple arguments

this really could just be `npm uninstall --save a b c` , but if you would like to add it is should be as simple

**Comment by DanielOchoa** [comment]
what would be the difference between passing `--save` and not passing it?

**Comment by DanielOchoa** [comment]
Also, with ember install the default generator is run. What would be the equivalent to ember uninstall? I was thinking about it and:

a) removing devDependencies means checking all addons dev dependencies to see if we can safely remove them from bower.json. 
b) for custom generator code, there's really no easy way to undo. 

Thoughts?

**Comment by stefanpenner** [comment]
> a) removing devDependencies means checking all addons dev dependencies to see if we can safely remove them from bower.json.

this is also not easy (I would argue not possible without much additional meta data, that we dont currently store)

**Comment by DanielOchoa** [comment]
On closer inspection I realized you are correct. This feature would need a new approach that would entail a rewrite of how `install` works as well. At least that's the only thing I can think of right now.

**Comment by stefanpenner** [comment]
@DanielOchoa ya its larger problem, both NPM and bower would need to actually address for us. I suspect neither will anytime soon. So `ember uninstall` purely to add symmetry is fine, but not something we cant live without.

**Comment by DanielOchoa** [comment]
sounds reasonable. I'll submit a PR most likely tomorrow :)

**Comment by stefanpenner** [comment]
sounds good. Im going to close this issue, because the "bug like issue" has be resolved.
