### ISSUE TITLE
Update blueprints for components tests so they go under tests/integrations

### ISSUE THREAD

**Issue by abuiles** [ember-cli/ember-cli#4178]

**Comment by ef4** [comment]
Another nice-to-have would be an option to generate a component *unit* test instead. They’re still supported, we just don’t think they should be the default.

**Comment by trabus** [comment]
I can take this on this weekend if nobody gets to it.

**Comment by trabus** [comment]
@ef4 regarding the component-test blueprint, is there any difference between the content of a unit and an integration test?

**Comment by ef4** [comment]
Yes, we require an `integration: true` option to disambiguate the new integration tests from the older unit tests. I would prefer to some day swap the default, but we needed this for the present to not break things on people.

**Comment by trabus** [comment]
@ef4 thanks! I'll get a PR in for this some time today.
