### ISSUE TITLE
Build error view in browser

### ISSUE THREAD

**Issue by sir-dunxalot** [ember-cli/ember-cli#4179]
Apologies if this is a dupe but I couldn't find it anywhere.

Whenever I encounter a build error with Ember CLI the output in the browser is very unreadable (I am using Chrome 42.0.2311.152) :

![image](https://cloud.githubusercontent.com/assets/4495352/7866525/17d5af7a-053e-11e5-8617-0f2f68226786.png)

However, the output in the console is good for debugging:

![image](https://cloud.githubusercontent.com/assets/4495352/7866517/0d0fdf0c-053e-11e5-9a95-c5746f9b8bdb.png)

I would expect both to appear the same to allow for easy debugging.

**Comment by stefanpenner** [comment]
I believe you have a mismatched babel + ember-cli version.

Can you share the versions to be sure?

**Comment by sir-dunxalot** [comment]
Thanks for the quick response. Versions are:

```
    "ember-cli": "^0.2.3",
    "ember-cli-babel": "^4.0.0",
```

**Comment by stefanpenner** [comment]
> "ember-cli-babel": "^4.0.0",

ya, 4x and 5x changed how and when this works. With 5.x we just disable the ansiColor codes entirely.

**Comment by sir-dunxalot** [comment]
Great, thanks!

**Comment by stefanpenner** [comment]
:+1: 

We plan to restore the coloring at some future point, but it was tricky especially when trying to satisfy both HTML + terminals with different themes.
