### ISSUE TITLE
Ember rename <generator-name> <options> command

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli#4180]
Are there plans for an `ember rename` / `ember rn` command? To go with the `ember generate` and `ember destroy` commands?

In my opinion it would be pretty useful, as I sometimes find myself wanting to rename a component (or something else generated with `ember g`) and such a command would speed things up and prevent me from forgetting to rename something. Or are there possible downsides / problems with such a feature?

**Comment by stefanpenner** [comment]
Yes the plans is for a move command. This depends on future work planned by @trabus on blueprint structures

**Comment by ismay** [comment]
Cool, that's good to know. Want to leave this open until move is implemented? Or is there already an issue for it (couldn't find one)?

**Comment by stefanpenner** [comment]
Cc @trabua

**Comment by trabus** [comment]
This has been brought up a few times already, the issues have just been closed. 
I have an RFC started for an `ember mv` command, I just need to finish it up and post it.

If time allows I should be working on it in June.

**Comment by ismay** [comment]
Ah I see. Well feel free to close this. &Thanks for the quick replies!

**Comment by trabus** [comment]
I'm fine leaving it open, more motivation to get it done!

**Comment by stefanpenner** [comment]
@trabus should we add pending-implementation tag?

**Comment by trabus** [comment]
Sure, though I was intending on developing it as an addon. I've currently got https://github.com/trabus/ember-mv but could develop it under the ember-cli umbrella if preferred.

**Comment by ismay** [comment]
> Sure, though I was intending on developing it as an addon

I'd say just leave it there, I'll just follow the ember-mv repo. People searching for the command, like I was, will find this issue and know where to find it as well. So I'd say that this can be closed then.

**Comment by stefanpenner** [comment]
closed in-favor of RFC or trabus's work. (As its not really a bug)

**Comment by ksnyde** [comment]
@trabus is this RFC moving forward (it appears the repo is not)? sure would be a nice convenience.

**Comment by trabus** [comment]
@ksnyde I've got the first iteration available as ember-cli-rename, but it's got some problems, and I haven't been able to solve some of the issues I've hit with the project. Primarily, the transforms for renaming references in a project are too greedy, and are renaming things that shouldn't be renamed. My AST experience is lacking and I've hit a wall on how to fix it.

I've been trying to find time to finish/fix it, but have been failing miserably on that front.

**Comment by peabnuts123** [comment]
Did this ever happen? This would be so super useful.

**Comment by jasonmevans** [comment]
Yes, would love a move or rename command to help with refactoring things.

**Comment by Alonski** [comment]
5 years later... Lets get this done!

**Comment by dlangsam** [comment]
I guess this still doesn't exist. Ho hum...

**Comment by efegurkan07** [comment]
I'm in dire need of this. :(

**Comment by MuhammadShehroz** [comment]
Any progress :(

**Comment by shankarsridhar** [comment]
It would be nice to have this feature.

**Comment by bertdeblock** [comment]
@shankarsridhar This would probably need a new RFC (I'm assuming the initial one mentioned in https://github.com/ember-cli/ember-cli/issues/4180#issuecomment-106829504 is no longer relevant), but more importantly, someone willing to do the work.

**Comment by SandeepJoel** [comment]
@stefanpenner Is there any progress on this  ?

**Comment by bertdeblock** [comment]
@SandeepJoel AFAIK, No one is working on this.
