### ISSUE TITLE
renorex testing needs static id's

### ISSUE THREAD

**Issue by iamalex2** [ember-cli/ember-cli#4182]
How would you code to put in static id's for renorex testing so they stay the same all the time for options or pulling in database items?  Single items are not problem, just multiples.

**Comment by stefanpenner** [comment]
I am confused. Can you shawl more details ?

**Comment by iamalex2** [comment]
when you view in inspector....
<div class="col-md-1 title">
<input id-ember3231" class="ember-view btn btn-link" href="#/t37123display=to-validate"></a>
</div>

This is one of the titles being pulled in from database.  
I'm very new to ember-cli so if you can help.
Renorex can't use the ember id, it needs a static id.

**Comment by iamalex2** [comment]
didn't mean to close

**Comment by stefanpenner** [comment]
sorry still confused.

**Comment by stefanpenner** [comment]
I dont believe this has anything to do with ember-cli. I suggest opening a stackoverflow question and cross linking.
