### ISSUE TITLE
Manually specifying addon dependency order

### ISSUE THREAD

**Issue by thedeeno** [ember-cli/ember-cli#4184]
My project depends on two addons. These addon's don't know about each other, but one must run before the other. I feel like it's pretty wonky for me to speak to both these addon maintainers and get them to add the respective `after` and `before` stanza's to their `package.json`.

Is there a way to manually specify the order? It seems like build step order should always be a project's responsibility and not left to addon maintainers. As an addon maintainer myself I know it's impossible to use the `before/after` stanzas to guard against all possible conflicts anyways.

Thoughts?

**Comment by stefanpenner** [comment]
Would be great to expose something here. Or explore in further detail the collision and explore an alternative solution

**Comment by thedeeno** [comment]
I'm exploring adding an api like:

```
var app = new EmberApp();

app.after('css', 'the-css-addon', function(tree) {
  // do stuff
  return tree;
});
```

Thoughts?

**Comment by thedeeno** [comment]
I'm exploring adding an api like:
```
var app = new EmberApp();
app.runAddon('css-addon-a', before: 'css-addon-b');
// which is the same as
app.runAddon('css-addon-b', after: 'css-addon-a');
```

Thoughts?

**Comment by thedeeno** [comment]
Or more complex:

```
var app = new EmberApp();
app.runAddon('css-addona', {
  before: [
    'css-addon-b',
    'css-addon-c'
  ],
  after: [
    'css-addon-d'
  ]
});
```

**Comment by stefanpenner** [comment]
same as the last one, we will wait post packager/builder merge.

**Comment by stefanpenner** [comment]
In the mean time, feel free to open a more detailed RFC

**Comment by rgbchris** [comment]
+1
