### ISSUE TITLE
How to hook into build pipeline without first class addons

### ISSUE THREAD

**Issue by thedeeno** [ember-cli/ember-cli#4185]
During active development I'd really appreciate the ability to hook into each build pipeline with custom broccoli plugins without needing to learn about the addon subsystem. It seems providing an `EmberApp` with a broccoli plugin and a dependency order should be enough to do some processing. When I feel my build step is shareable I can then upgrade it to a formal addon.

Right now I've been making addons to inject my own processing steps and most of the time it feels like overkill - especially if my step isn't stable enough or too specific to share.

Is this possible today and I'm just missing it?

**Comment by thedeeno** [comment]
I think an API like the following would be nice:

```
var app = new EmberApp();
app.after('css', 'css-addon-a', function(tree) {
  // do stuff
  return tree;
});
```

**Comment by stefanpenner** [comment]
In repo addons I think satisfy this for now. I am hesitant to expand the api here to rapidly yet

**Comment by thedeeno** [comment]
I agree that it might be premature to introduce a more fluent api. On the flip side I think even in-repo-addons are quite heavy for very simple tree transformations. Some tree transformations are so simple in fact that you can't even name them properly. For those in-repo addons feel like overkill. 

Is there a way for consumers to register addons with dependencies via the brocfile? I feel like that would get me most of the way there. I don't see a mechanism to specify the `before/after` though. Not having to name it would be icing on the cake.

```
var app = new EmberApp();
app.registry.add('css', {
  before: ['css-addon-a'],
  toTree: function(tree) {
    ...
  }
});
```

**Comment by stefanpenner** [comment]
potentially after @chadhietala build refactor lands.

**Comment by thedeeno** [comment]
Where can I find information on this build refactor? I'm doing a refactor myself and was considering fielding a PR when done.

**Comment by stefanpenner** [comment]
https://github.com/chadhietala/ember-cli-pre-packager
https://github.com/chadhietala/ember-cli-builder
