### ISSUE TITLE
Generating an acceptance test for addons produces a buggy test file

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#4191]
https://github.com/ember-cli/ember-cli/commit/07055c25b67fb3d13c071185ff55ac00823473e3 is the culprit

In short the `dasherizedPackageName` being used is going to look for `start-app` in the wrong namespace. For addons the proper namespace for the test support files is `dummy/`.

I recommend changing this back to the relative path name as there is no way to truly discern this value at generation. (the addon generator is overriding the `name` property to `"dummy"`)

**Comment by stefanpenner** [comment]
@bcardarella got time to add a test?

@trabus is this fixed by your latest commit? It seemed quite related.

**Comment by trabus** [comment]
@stefanpenner no, I don't believe this is covered by my last commit. I can try and look into it tomorrow.

**Comment by trabus** [comment]
The generated path should be: `import startApp from '../../tests/helpers/start-app';`

I'll make a PR for this today.
