### ISSUE TITLE
Add generator for instance initializers

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#4198]
ATM there is no generator blueprint for instance initializers, you need to add them manually or generate using the `initializer` generator and move them to the new folder afterwards.

If nobody started working on this, I can take care of it

**Comment by rwjblue** [comment]
I do not believe it is underway ATM.

**Comment by cibernox** [comment]
Ok. Also I'd say that there is very few documentation about instance initializers in general. The only mention i've seen is in the 1.12 blog post, and the explanation seems insufficient to me.

**Comment by stefanpenner** [comment]
@cibernox are you going to look into this?

**Comment by cibernox** [comment]
Yep: #4218

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/blob/master/blueprints/instance-initializer/index.js
