### ISSUE TITLE
Enable broccoli watch for bower_components

### ISSUE THREAD

**Issue by opsb** [ember-cli/ember-cli#4202]
I'm currently working on a couple of bower packages that I'm integrating with an ember-cli app. I've symlinked them in but currently have to restart the ember-cli app every time I make a change. I realise bower_components is added as an unwatched broccoli tree, is there any way to override this and have broccoli watch the bower_components folder?

**Comment by stefanpenner** [comment]
watchman i don't believe follows those symlinks. Maybe open an issue there.

A quick solution, is merely to dirty any file in your app. Like maybe `touch app/app.js`which will trigger a rebuild, and broccoli's dirty checking will realize the symlinked changes and move forward.

**Comment by opsb** [comment]
@stefanpenner ah, good call! I can include that in the autobuild script I have running for the dependencies.
