### ISSUE TITLE
In-repo-addon styles replace the main app styles

### ISSUE THREAD

**Issue by bndw** [ember-cli/ember-cli#4209]
If you create a stylesheet for an `in-repo-addon` in  `lib/<addon_name>/addon/styles/app.css`, the host project's stylesheet in `app/styles/app.css` is no longer used.

**Comment by pixelhandler** [comment]
@bndw you can use the filename `addon.css` instead

**Comment by Turbo87** [comment]
this seems solved due to @pixelhandler's workaround
