### ISSUE TITLE
Packager

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4211]
# Packager
### Ember CLI
- [ ] Need to finish the #reexport branch merged
### [Assembler](https://github.com/chadhietala/ember-cli-assembler)
- [ ] Ensure the assembler collects app.import method calls and turns them into a tree
- [x] Do something with test support
- [ ] API docs
- [x] Allow for babel config to be passed and merged with defaults https://github.com/chadhietala/ember-cli-assembler/pull/26

_note: some strange code exists, we should eventually clean it up. That is unless its causing a bug in the "unknown unknowns" category of things_
### [Linker](https://github.com/chadhietala/ember-cli-linker):
- [x] known knowns function as expected
- [x] API docs
- [x] graph refactor
- [ ] needs to be battle tested
- [ ] stefs code: https://github.com/caitp/cauliflower-filter/pull/14 may help reduce some complexity
- [x] complexity in passing meta information (tree names, etc) _note: related to assembler quirks_
- [x] ES resolver needs to share babel configuration https://github.com/chadhietala/ember-cli-linker/pull/58
### [Packager](https://github.com/chadhietala/ember-cli-packager)
- [x] MVP stable (should work, as expected)
- [ ] investigate potential caching issues (packager may leak knowledge of deleted files)
- [ ]  verify all known reasonable use-cases
- [ ] address confusion with the single tree output (we have lost too much fidelity). This may be a large task.

---
## Integration Testing

[Dummy App](https://github.com/chadhietala/packager-dummy)

**Comment by stefanpenner** [comment]
cc @chadhietala we should flesh this issue out again.

**Comment by chadhietala** [comment]
@stefanpenner Yes, lets chat today if you have some time.

**Comment by stefanpenner** [comment]
yes, potentially. Would this evening work?

**Comment by QuantumInformation** [comment]
Looking fwd to this landing!

**Comment by knownasilya** [comment]
What exactly is this PR about?

**Comment by chadhietala** [comment]
Probably more but here is a list of stuff.

- Build only JS files that are reachable in the dependency graph
  - Unlocks the following:
      - Building of engines
      - Ember as an addon
      - Visualize the dependencies in an application
- Kill `app.import` as a means to consume js dependencies
- Make bower a second class citizen
- Have the ability to have different concatenation strategies
- Babel as a first class citizen with persistences built in

**Comment by knownasilya** [comment]
That is exciting! :dancer:

**Comment by QuantumInformation** [comment]
Do we have a target version of ember-cli that this will arrive in?

**Comment by stefanpenner** [comment]
@QuantumInformation nope. It's done when it's done

**Comment by rwjblue** [comment]
@QuantumInformation - Yep, the first version after the changes are made to master. :stuck_out_tongue_closed_eyes:

**Comment by QuantumInformation** [comment]
no worries, I can work on other things until then!

**Comment by GCheung55** [comment]
Is there an update around this?

**Comment by stefanpenner** [comment]
@GCheung55 its being revisited as part of the `lazy` engine story.

@nathanhammond is someone to follow on this, he is leading that effort.

**Comment by snuggs** [comment]
@stefanpenner thanks for the update! And the recommendation.I believe i met @nathanhammond @ GORUCO in the taxi with @lukemelia. Is this the same person?

**Comment by nathanhammond** [comment]
@snuggs One and the same!

My thoughts on rollup aren't fully-formed yet, but it's clearly doing some neat things and we're using it in multiple places in the Ember ecosystem.

**Comment by thomblake** [comment]
Now that #4546 is done, how close are we on this one?

Also, is completion of this really necessary to turn Bower into a second-class citizen? What about getting Bower deported?

**Comment by stefanpenner** [comment]
> Also, is completion of this really necessary to turn Bower into a second-class citizen? What about getting Bower deported?

nope, not required.

**Comment by stefanpenner** [comment]
> Now that #4546 is done, how close are we on this one?

not very close, we will likely revisit this now as bower vanishes and with our new learnings (battle scars)

**Comment by runspired** [comment]
Bower is about to vanish :D

**Comment by thomblake** [comment]
I am excited how do i get on board the no bower train and also will there be a viking funeral

**Comment by micky2be** [comment]
Any update on this?

**Comment by nikdojo** [comment]
Since 2015... any update, guys?

**Comment by Turbo87** [comment]
yes

**Comment by ro0gr** [comment]
@nikdojo I think the most relevant recent activity is happening in a [Strategies RFC](https://github.com/ember-cli/rfcs/pull/110)

**Comment by rdhelms** [comment]
Looks like that PR110 was recently merged...is there a timeline for this being available?

**Comment by twokul** [comment]
https://github.com/ember-cli/ember-cli/pull/7562, experiment should land by the end of the month

**Comment by locks** [comment]
This experiment landed a while back!
