### ISSUE TITLE
Throw 404 when assets not found

### ISSUE THREAD

**Issue by teddyzeenny** [ember-cli/ember-cli#4219]
ember-cli currently serves the `index.html` file instead of a `404` to support history location apps. This is however very confusing when trying to load an asset that doesn't exist.

One option could be to throw a 404 if the path starts with `assets`. Another option is to throw a 404 if the beginning of the path exists, but the rest does not. For example, a request to `/images/my-image.jpg` would throw a 404 if the `images` directory exists.

The 404 page could explain that "/assets path is reserved for ember-cli, please use another route name" or "/images directory exists in your public directory, so your Ember route cannot begin with images/".

Thoughts?

/cc @joliss

**Comment by stefanpenner** [comment]
@teddyzeenny it likely can check the requested content-type
