### ISSUE TITLE
Pods structure does not work when addon is installed

### ISSUE THREAD

**Issue by benedikt-d** [ember-cli/ember-cli#4220]
Pods structure still wants the application.hbs in 'app/templates/ 

The resolver finds both folders but if I remove the template folder it throws a Build error.

https://github.com/benedikt-d/PodsBug

**Comment by benedikt-d** [comment]
Very strange the issue disappeared after restarting the server a few times. I'm not so sure what it was exactly...

**Comment by stefanpenner** [comment]
do you maybe have multiple running?

**Comment by benedikt-d** [comment]
No there was only one running. I think it was something with Sublime Text and Watchman. I restarted Sublime Text too.

**Comment by stefanpenner** [comment]
hmm. Unsure. Let's assume some phantom issue.

If it happens again, and a reproduction exists (i can't replicate with your repo) I will gladly reopen.
