### ISSUE TITLE
Addon Travis fails with ember-try

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-cli#4222]
See this build: https://travis-ci.org/knownasilya/ember-cli-toggle/jobs/65244141

Doesn't look like there are any errors, but still a non-zero code.

**Comment by stefanpenner** [comment]
i suspect this is a legit failure, as you are using the new `get/set` syntax but older versions may not yet support it?

**Comment by knownasilya** [comment]
I'm not testing against anything older then the released version..

**Comment by stefanpenner** [comment]
This may actually be because ember try is adding bower deps that need to be resolved interactively. But that is something the travis shell cannot handle. Potentially causes the run to exit early.

@kategengler thoughts?

**Comment by knownasilya** [comment]
`bower install --config.interactive=false`?

**Comment by stefanpenner** [comment]
> bower install --config.interactive=false?

that is likely a good default, as it would error hard if interactive is needed, likely providing better output here. This is likely something that ember try to do.

**Comment by rwjblue** [comment]
Would need to be added here: https://github.com/kategengler/ember-try/blob/f439fc4efa9af057addce73091dbcbe812fa3a3d/lib/utils/bower-helpers.js#L30

**Comment by stefanpenner** [comment]
@knownasilya im also curious, what is the output once ^^ is used
