### ISSUE TITLE
ember-2.0 angle-bracket componet not working with ember-cli@0.2.7

### ISSUE THREAD

**Issue by mankind** [ember-cli/ember-cli#4223]
Please what else do I need to use ember-2.0 angle-bracket component with ember-cli

I am using **ember-cli 0.2.7**, nodejs **0.12.4** and emberjs-canary branch to test out emberjs-2.0.

I created a bare bones new  ember app with:

      ember new test-app

and created a component with:

        ember g component my-test

In application.hbs  if I add the line below to call the component, the content in the component is not displayed.

        <my-test  />

If change the line above to the one below, the content of the component is displayed.

    {{my-test}}
    

Here is an excerpt of my bower.json

        {
          "name": "em",
          "dependencies": {
             "ember": "components/ember#canary",
             "ember-data": "components/ember-data#canary",,
             "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
             "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
             "ember-data": "1.0.0-beta.18",
             "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
             "ember-qunit": "0.3.3",
              "ember-qunit-notifications": "0.0.7",
              "ember-resolver": "~0.1.15",
              "jquery": "^1.11.1",
             "loader.js": "ember-cli/loader.js#3.2.0",
             "qunit": "~1.17.1"
       },
       "resolutions": {
           "ember": "canary",
           "ember-data": "canary"
         }
       }
  
Here is my package,json

      "devDependencies": {
         "broccoli-asset-rev": "^2.0.2",
         "ember-cli": "0.2.7",
         "ember-cli-app-version": "0.3.3",
         "ember-cli-babel": "^5.0.0",
         "ember-cli-content-security-policy": "0.4.0",
         "ember-cli-dependency-checker": "^1.0.0",
         "ember-cli-htmlbars": "0.7.6",
         "ember-cli-ic-ajax": "0.1.1",
         "ember-cli-inject-live-reload": "^1.3.0",
         "ember-cli-qunit": "0.3.13",
         "ember-cli-uglify": "^1.0.1",
         "ember-data": "1.0.0-beta.18",
         "ember-disable-proxy-controllers": "^1.0.0",
         "ember-export-application-global": "^1.0.2"
      }

**Comment by stefanpenner** [comment]
this is a question better asked as SO, as it does not appear to be a bug.

**Comment by mankind** [comment]
I thought it was a bug, since angle-bracket component is supposed twork with ember-canary branch. It works with  jsbin but it does not in ember-cli. However, if you insist it is not a bug for angle-bracket components to work  with the latest ember-cli and emberjs canary, then it can be closed, I will revert to calling {{my-component}} with pre-2.0 way. thanks.

**Comment by stefanpenner** [comment]
> if you insist it is not a bug

this doesn't appear to be an ember-cli bug, correct.

**Comment by rwjblue** [comment]
FYI - angle bracket invocation has been disabled in canary and beta due to some things we discovered while using it after 1.13.0-beta.1.

Those issues will be fixed, and it will come back in a future release (likely 2.1 or so).

**Comment by mankind** [comment]
@rwjblue that was a really helpful information. Thank you.

**Comment by stefanpenner** [comment]
i also just answered this question on SO https://stackoverflow.com/questions/30629567/ember-2-0-angle-bracket-component-not-working-with-ember-cli0-2-7/30630165#30630165

**Comment by mankind** [comment]
@stefanpenner  many thanks. I have accepted the answer. It solved my problem and allowed me to use angle-bracket components.

**Comment by stefanpenner** [comment]
SO is king of that sort of QA, especially for searchabilty.
