### ISSUE TITLE
File watching issue with ember new on CLI 0.2.7

### ISSUE THREAD

**Issue by deanmraz** [ember-cli/ember-cli#4231]
Just created a new project running these steps: 
  1. ember update 
  2. ember new project 
  3. cd project 
  4. ember serve

Changed the application.hbs file, added some new components, but no files were watched so ultimately nothing changed on the browser. If I reran ember serve I then saw the changes. Also, ember build --watch has the same issue.

Application Versions: 
* ember-cli 0.2.7
* node v0.12.1
* npm 2.5.1
* watchman via brew 3.0.0 
* Mac OSX 10.9.5

**Comment by stefanpenner** [comment]
Can you purge and uninstall watchman. Then upgrade to the latest version of 3,2

**Comment by deanmraz** [comment]
@stefanpenner thanks for the quick response 

Upgraded watchman to 3.1 didn't see an option for 3.2, however still didnt resolve the issue. 

Removing and reinstalling npm and bower packages seemed to do it! thanks

**Comment by stefanpenner** [comment]
> Upgraded watchman to 3.1 didn't see an option for 3.2, however still didnt resolve the issue.

i suspect you need to update brew
