### ISSUE TITLE
templates for ember-cli addons content-for

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4245]
Instead of having to define `content-for` hook in the add-on's `index.js` file. It would be great if one could define templates (eg. `content-for/head-footer.hbs` or `content-for/body-footer.hbs`) in his add-on's root folder, these will then be picked up automatically by ember-cli and rendered against the config file.

**Comment by stefanpenner** [comment]
Ya this is interesting. But not really on the high-priority path. If you want to open an RFC to flesh this out further that is fine. 

Closing this, as it is not a bug nor on the critical path.

**Comment by olivierlesnicki** [comment]
@stefanpenner I've managed to implement this as part of a project I'm working on. I'll open an RFC :)
