### ISSUE TITLE
Preferred spelling for Ember CLI docs: addon or add-on

### ISSUE THREAD

**Issue by eliotsykes** [ember-cli/ember-cli#4246]
The Ember CLI docs use a mix of addon and add-on. What's preferred?

**Comment by dukex** [comment]
I think the most used is addon, I found only one mention to 'add-on' in CHANGELOG.md

Search 'addon' on code
https://github.com/ember-cli/ember-cli/search?utf8=%E2%9C%93&q=addon&type=Code

Search 'add-on' on code
https://github.com/ember-cli/ember-cli/search?utf8=%E2%9C%93&q=add-on&type=Code

**Comment by eliotsykes** [comment]
Thanks @dukex - the searches cover the `master` branch. On the `gh-pages` branches there are a few more occurences of add-on. Unfortunately GitHub doesn't search branches, but you can see occurrences here with in-browser search: http://www.ember-cli.com/

**Comment by stefanpenner** [comment]
Addon seems like what we should settle on

**Comment by dukex** [comment]
@eliotsykes My pull request  #4275 was merged, I don't change the changelog reference to add-on

**Comment by eliotsykes** [comment]
Fantastic @dukex :+1:

**Comment by trabus** [comment]
I'm going to go ahead and close this. Thanks for the PR!
