### ISSUE TITLE
Template preprocessor getting compiled JS

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli#4248]
I have a template preprocessor in an addon. When I run the preprocessor in the addon dummy app, it works fine. When I run it in a host app, the tree passed into `toTree` is a tree with the compiled JavaScript template files, not the raw handlebars files.

```JavaScript
setupPreprocessorRegistry: function(type, registry) {
  registry.add('template', {
    name: 'tracking',
    ext: 'hbs',
    toTree: function(tree) {
      tree = instrument.print(tree);
      return templateTrackingChecker(tree);
    }
  });
});
```

**Comment by chadhietala** [comment]
You need to tell your addon that it must come before the htmlbars-compiler. You do this by placing a `before` key in you `ember-addon` map in your package.json. 

__Example__

```
{
...
  "ember-addon": {
    "before": ["ember-cli-htmlbars"]
    ....
  }
...
}
```

**Comment by asakusuma** [comment]
Thanks @chadhietala, solved
