### ISSUE TITLE
Using 'ember generate' to create models from a schema file

### ISSUE THREAD

**Issue by jmishra17** [ember-cli/ember-cli#4255]
I am writing an Ember Addon that will help generate models out of a schema file. This schema can be an external JSON file, and using something like `ember g import-models <schema-file>.json` will create models and their test files.

I am running into one problem. Since the blueprints for models and model-test are pre-defined within our ember app, all I need to do is to parse my JSON file and run a bunch of `ember g model <model-1>`, `ember g model  <model-2>`, `ember g model <model-3>  ...` However, I don't know what part of my addon I can wire to do such a thing, i.e, execute multiple ember generate commands (synchronously/asynchronously?).

All I have now is simply a blueprint that allows me to run `ember g import-models <schema-file>.json` but I don't know where I can run my shell commands and put my parser code.

**Comment by trabus** [comment]
If you look at [this](https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L60) in the resource blueprint, you can see how to install other (multiple) blueprints from a blueprint. You could probably even just reuse the `_processBlueprint` method for your own purposes.

**Comment by trabus** [comment]
We probably could use some documentation on how to lookup blueprints and generate them from other blueprints, so I'll leave this open as a docs issue.

**Comment by jmishra17** [comment]
Thanks. That's convenient. I still had to import the following files from `ember-cli/node_modules` (well, at least `Blueprint` and `ext/Promise`) as they are relevant to the ember-cli package 

    var Blueprint  = require('ember-cli/lib/models/blueprint');
    var Promise    = require('ember-cli/lib/ext/promise');
    var merge      = require('ember-cli/node_modules/lodash/object/merge');
    var inflection = require('ember-cli/node_modules/inflection');

I copy pasted the same [_processBlueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L19) function and modified [_process](https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L50) to generate a bunch of models. Worked like a charm
