### ISSUE TITLE
Blueprints create unresolvable paths for entities in private npm modules

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/ember-cli#4256]
My team's working to create addons using private npm modules. This requires us to prepend our module name in our `package.json` with a scope (`@gmurphey/scoped-ember-addon`).

Using the generate command, the `addon-import` and `*-addon` blueprints are creating paths that can't be found by the resolver (`@gmurphey/scoped-ember-addon/components/x-foo`, for example). I've created [gmurphey/scoped-ember-addon](https://github.com/gmurphey/scoped-ember-addon) to demonstrate the issue.

Removing the scope from the import path fixes the issue. I'm happy to do the work to fix this if someone can give me some advice on whether the fix should be in the blueprints or the resolver.

**Comment by trabus** [comment]
@gmurphey We should probably extract the logic to get the addonName into a utility to reuse in `addon-import` and `*-addon`, and put in some logic to properly handle namespaces. I believe the `@name/` should in fact be removed, since I believe the compiled js uses the package name and ignores the namespace.

**Comment by trabus** [comment]
@gmurphey Also, would you see any value in adding the ability to either generate `ember addon @myscope/my-addon` or `ember addon my-addon --private myscope` to automatically add the scoping to your package name?

**Comment by gmurphey** [comment]
@trabus: Thanks for the feedback! I'll start taking a look at this tonight. I also realized that when an addon is scoped, you have to specify the `defaultBlueprint` explicitly for the package, so the `getAddonName` utility should probably be used when looking up the addon's blueprint on install, too.

**Comment by gmurphey** [comment]
@trabus: It would be great to have support for private addons when creating projects. Anything that saves me the extra work of remembering to mark a project as private before trying to publish to npm.

**Comment by gmurphey** [comment]
Just a note for myself when I get to this: watchman doesn't seem to be watching changes correctly when running `ember server` when inside of a private addon.
