### ISSUE TITLE
ember upgrade/init does not update package.json correctly

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#4264]
Tried this on two different projects from 0.2.5 to 0.2.7:

Ran `ember upgrade`, which eventually prompted for `ember init`, which I said yes to.  I then said yes to every overwrite as well.  Upon completion, my package.json still showed `ember-cli: 0.2.5`, even though 0.2.7 had been npm install'd.

I have heard reports of someone else encountering this upgrading from 0.2.3 (the version got re-set to 0.2.3 in that case, not 0.2.5).

My guess would be the emberCLIVersion var in the blueprint isn't being updated correctly when it gets here:
https://github.com/ember-cli/ember-cli/blob/v0.2.7/blueprints/app/files/package.json

**Comment by stefanpenner** [comment]
the instructions on the website and release docs are accurate: https://github.com/ember-cli/ember-cli/releases
