### ISSUE TITLE
Source map wrong - ember-cli v2.7.

### ISSUE THREAD

**Issue by estaub** [ember-cli/ember-cli#4267]
I'm having a persistent problem with source maps being wrong.  I've tried nuking "dist" and restarting Chrome.  Using a project that's based on "ember new", the combined .js begins with the app:
```javascript
/* jshint ignore:start */

/* jshint ignore:end */

define('easyimpact-demo-cli/app', ['exports', 'ember', 'ember/resolver', 'ember/load-initializers', 'easyimpact-demo-cli/config/environment'], function (exports, Ember, Resolver, loadInitializers, config) {

  'use strict';

  var App;

  Ember['default'].MODEL_FACTORY_INJECTIONS = true;

  App = Ember['default'].Application.extend({
    modulePrefix: config['default'].modulePrefix,
    podModulePrefix: config['default'].podModulePrefix,
    Resolver: Resolver['default']
  });

  loadInitializers['default'](App, config['default'].modulePrefix);

  exports['default'] = App;

});
```
which was created from this (unmodified from "ember new" app.js.  The asterisks indicate the lines where a breakpoint is allowed by Chrome.  By stepping in from breakpoints, I can tell that breakpoint on the line preceding `App = Ember.Application.extend(` corresponds to that line, but other later sources are off by larger amounts.

```javascript
*   import Ember from 'ember';
    import Resolver from 'ember/resolver';
*   import loadInitializers from 'ember/load-initializers';
    import config from './config/environment';
*   
    var App;
*   
    Ember.MODEL_FACTORY_INJECTIONS = true;
*   
    App = Ember.Application.extend({
    modulePrefix: config.modulePrefix,
    podModulePrefix: config.podModulePrefix,
    Resolver: Resolver
    });
*
    loadInitializers(App, config.modulePrefix);
*
*   export default App;
*
```

**Comment by stefanpenner** [comment]
there was a recent fix to the source map concat lib, which version of ember-cli are you using?

can you try master? (docs on how to that are in the readme)

**Comment by estaub** [comment]
@stefanpenner, 
I'm using 2.7 (see post title), and I verified that it includes broccoli-sourcemap-concat 4.4, which contains the fix to https://github.com/ember-cli/ember-cli/issues/3098 .  Was that the one you're referring to?  If so, this one seems different, in that AFAICT it's not reliant on the state of a cache.  I assume that the cache referred to in issue 3098 was the one in <project>/tmp; if not, I may be missing something.

**Comment by stefanpenner** [comment]
> there was a recent fix to the source map concat lib, can you try master?

can you try master?

> Can you provide a repo demonstrating this issue, as i apparently cannot replicate it.

can you provide a repo demonstrating?

with the above too, i will gladly then dive in and see what is going on.

**Comment by estaub** [comment]
@stefanpenner 
Thanks ever so much.
I tried master - no joy.  Great directions on the wiki, btw.

The repo is at https://github.com/easy-impact/easyimpact-demo-cli , set up for your access only.  The app is barely started - I ran into this problem and it's a blocker.

I included the combined .js and .map in the repo, in case you can't reproduce the problem and they provide a clue.

I'm very much a noob - if there's something obvious that I could have done wrong, I probably did it!

**Comment by stefanpenner** [comment]
> The repo is at https://github.com/easy-impact/easyimpact-demo-cli , set up for your access only. The app is barely started - I ran into this problem and it's a blocker.
> 
> I included the combined .js and .map in the repo, in case you can't reproduce the problem and they provide a clue.

awesome thank you



> I'm very much a noob - if there's something obvious that I could have done wrong, I probably did it!

Source maps can be quite brittle, I suspect you aren't doing anything wrong, rather just ran into one of those failure scenarios.

**Comment by estaub** [comment]
@stefanpenner After another day of mystery after mystery, fail after fail, I've decided to bail on ember and try one of the other frameworks - probably Angular.  So you may want to do a quick chase-down in case it might lead to a find and fix, but of course drop the priority.  Thanks anyway.

**Comment by stefanpenner** [comment]
@estaub best of luck

**Comment by taras** [comment]
I'm having the same problem and it seems to be happening to a lot of people.

* https://twitter.com/machty/status/616749085719175169
* https://twitter.com/nisnek/status/616749120389296128
* https://twitter.com/anlumo1/status/616757588865191936
* https://twitter.com/bayfieldcoder/status/616799233878814720
* https://twitter.com/codeofficer/status/616800291040665600

How do we fix it?

**Comment by stefanpenner** [comment]
manually walk through deps and track down which one has a malformed source map. Or identify some portion of the build that is doing stuff non-sourcemap aware.

**Comment by stefanpenner** [comment]
disabling source maps in chrome is a temp workaround.

**Comment by estaub** [comment]
I no longer have a stake in this, since I've switched to Angular.  But I remember thinking at the time that if there was an easy way to get ember-cli to emit non-minified, easily usable javascript that didn't require a map, I'd be very happy.  In very different words, if a real fix isn't forthcoming, I'd put a high priority on a universal, easy workaround for development "mode" where minification isn't necessarily needed.  This may exist already - if so, consider posting a how-to tip.

**Comment by stefanpenner** [comment]
> his may exist already - if so, consider posting a how-to tip.

development code is not minified & the website does already document how to toggle sourceMaps http://www.ember-cli.com/user-guide/#source-maps
