### ISSUE TITLE
Can't run on OS X 10.11 El Capitan developer beta

### ISSUE THREAD

**Issue by NathanJang** [ember-cli/ember-cli#4273]
I recently updated from Yosemite to the El Capitan developer beta. Now, when I run `ember` on the command line, it freezes at
```
$ ember
version: 0.2.7
```
This happens to all sub-commands, including `ember help`. I have to `^C` to quit the process.

**Comment by NathanJang** [comment]
It appears to work now. I was fiddling around to see what would fix it. It worked after reinstalling Watchman (I think).

**Comment by stefanpenner** [comment]
I also don't have easy access to a machine that I can install the new OS on...

**Comment by NathanJang** [comment]
We'll have to see if other users can reproduce

**Comment by jtsom** [comment]
Just want to leave a note - this just happened to me, but on the latest 10.10 Yosemite. Turns out that Watchman had hung, so the ember command was hanging waiting for it. I had to do 'kill' the watchman process and everything started working again.

**Comment by stefanpenner** [comment]
Mind opening a watchman issue name mentioning the unexpected hang?

**Comment by NathanJang** [comment]
@jtsom?

**Comment by jtsom** [comment]
Yes? (and yes, I'm going to open a watchman issue - just don't have any way to re-create the problem, so may be tough to track down.)

**Comment by NathanJang** [comment]
Actually it may have continued to hang after uninstalling Watchman in my case. It didn't say anything about falling back to NodeWatcher.

**Comment by wez** [comment]
Please don't pile on an old closed watchman issue.  Open a new one with information that can help diagnose and debug it, thanks!
