### ISSUE TITLE
Changing the parameter in the rest call on fly

### ISSUE THREAD

**Issue by Sameeksha123** [ember-cli/ember-cli#4274]
Im working on ember-cli, how do i change rest call on fly in the rest adapter. If i use path params not query params?

for example:

export default DS.RESTAdapter.extend({
   namespace:'res/v1/users/id', 

    pathForType: function() {
       return Ember.String.underscore("friends");
    },
  });

Based on the user i select from  dropdown , i need to get their friends from the database.
Could you please suggest a better way to do.  My aapplication supports  pathparams not the query params

**Comment by stefanpenner** [comment]
This doesn't appear like an ember-cli issue. This seems like a good stackoverflow question.
I suggest opening one and cross linking so future readers find it

**Comment by Sameeksha123** [comment]
sure.. thank you
