### ISSUE TITLE
Add generate support for addon dummy apps

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#4276]
We should be able to generate blueprints into the `tests/dummy/app` that gets generated inside an addon. The option would be added to the generate command, and only work inside an addon.

```
ember g component foo-bar --structure dummy
```

This will be a good place to implement work on [Structures](https://github.com/ember-cli/rfcs/pull/5), with `dummy` being one of the structures available to ember-cli.

**Comment by myartsev** [comment]
`ember g component foo-bar --dummy`

Just a note on how this got implemented.
