### ISSUE TITLE
Application.hbs inserted at incorrect point in index.html

### ISSUE THREAD

**Issue by davidpaulmcintyre** [ember-cli/ember-cli#4285]
The application.hbs template is inserted at an incorrect point in index.html.  It's being inserted at the end of the body tag, below the script tags and below the body-footer contentFor hook.  

Simple demo project that repro's the issue is at https://github.com/davidpaulmcintyre/bug-test.git  It uses a simple in-repo-addon.  The contentFor hooks work correctly, but it looks as if it doesn't because the app.hbs is inserted at the wrong point.  

Despite the bug, project passes all tests.

**Comment by stefanpenner** [comment]
this appears to be working as expected. content-for hooks are merely for addons to inject stuff into your index.html. The ember application is merely appended to body (or w/e the rootElement selector is set to)

**Comment by davidpaulmcintyre** [comment]
it's not working in a way that allows the content-for hooks to work properly.  the purpose of the body-footer content-for hook is to allow a addon to inject script tags, etc at the end of the body, correct?  how is that possible given the current behavior?

**Comment by stefanpenner** [comment]
> the ember app is appended below the script tags for vendor.js and appname.js,

yes, but this is overridable by specifying rootElement. I suspect this will unblock you.

**Comment by ldong** [comment]
I was interested myself. So I spent sometime to dig out the workflow.

# Question

Why would ember append `application.hbs` to the document.body?

First paragraph states of Ember [Doc](https://guides.emberjs.com/v2.11.0/configuring-ember/embedding-applications/#toc_changing-the-root-element)

```By default, your application will render the application template and attach it to the document's body element.```


But why, though?



## Source code diggs

```text
packages/ember-routing/lib/system/router.js
325:      instance.didCreateRootView(this._toplevelView);

|
v

packages/ember-application/lib/system/application-instance.js
    didCreateRootView: function (view) {
      view.appendTo(this.rootElement);
    },

|
v

packages/ember-application/lib/system/application-instance.js
89:    Overrides the base `EngineInstance._bootSync` method with concerns relevant
102:  _bootSync(options) {

|
v

packages/ember-views/lib/mixins/view_support.js
237:  appendTo(selector) {
  appendTo(selector) {
    let env = this._environment || environment;
    let target;
|
v

packages/ember-glimmer/lib/renderer.js
178:  appendTo(view, target) {

|
v
https://github.com/emberjs/ember.js/blob/v2.7.1/packages/ember-htmlbars/lib/renderer.js#L132
// This entry point is called from top-level `view.appendTo`.
Renderer.prototype.appendTo = function Renderer_appendTo(view, target) {
  var morph = this._dom.appendMorph(target);
  morph.ownerNode = morph;
  view._willInsert = true;
  _emberMetalRun_loop.default.schedule('render', this, this.renderTopLevelView, view, morph);
};

```

## Reference

1. [Customizing the rootElement | How To Ember](https://howtoember.wordpress.com/2015/06/12/customizing-the-rootelement/)
