### ISSUE TITLE
No longer watching addon directory when isDevelopingAddon is true.

### ISSUE THREAD

**Issue by arenoir** [ember-cli/ember-cli#4289]
I upgraded to ember-cli 0.2.7 from 0.2.5 a couple of days ago. Today I noticed one of my local in development addons was not being watch by ember server. 

The addon is being added to the application like so.

package.json
```
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test",
    "preinstall": "npm link ../fp-common",
    "preupdate": "npm link ../fp-common"
  },
```

addon index.html
```
module.exports = {
  name: 'fp-common',

  isDevelopingAddon: function() {
    return true;
  }
};
```

**Comment by stefanpenner** [comment]
May be an issue due to the nature of the symlink. Can you provide a repo demonstrating this issue

**Comment by brettburley** [comment]
Are you using watchman? I've experienced this with ember-cli 0.2.5 when using watchman. It seems to not watch addons when they're symlinks.

However, if I uninstall watchman so that ember-cli falls back to NodeWatcher, it's able to watch symlinked addons fine.

**Comment by dukex** [comment]
A coworker report the same issue on 0.2.7, the project has a npm linked addon too, maybe I can investigate tomorrow.

**Comment by rwwagner90** [comment]
Could anyone shed some light on this subject? I'd like to have two apps, and one common addon that both use, and each consuming app should auto-reload when the addon is modified. Can someone help me and/or point me to some docs on this subject?

**Comment by stefanpenner** [comment]
> Could anyone shed some light on this subject? I'd like to have two apps, and one common addon that both use, and each consuming app should auto-reload when the addon is modified. Can someone help me and/or point me to some docs on this subject?

This is watchman not following symlinks. As such, we should likely open a watchman issue.

**Comment by brettburley** [comment]
@stefanpenner Watchman not following symlinks is listed as one of their "Concepts": https://facebook.github.io/watchman/
> Watchman does not follow symlinks. It knows they exist, but they show up the same as any other file in its reporting.

Maybe they'll be willing to reconsider. Otherwise we may have to do something special for addons that have the `isDevelopingAddon` flag to watch their directories directly?

**Comment by stefanpenner** [comment]
> Otherwise we may have to do something special for addons that have the isDevelopingAddon flag to watch their directories directly?

ya,  we can explicitly add a watch root to them.

My idea when thinking about this earlier was basically to add a watch-root if we encounter a symlink. That way we bypass the watchman limitation.

**Comment by stefanpenner** [comment]
> Maybe they'll be willing to reconsider.

it would be nice

**Comment by aceofspades** [comment]
+1

**Comment by stefanpenner** [comment]
@wez confirmed my above proposed solution is the one we should follow.

**Comment by spruce** [comment]
Anything new on this front?

**Comment by stefanpenner** [comment]
> Anything new on this front?

nope

**Comment by stefanpenner** [comment]
Actually having a chat with the watchman folk wednesday. Hoping to improve alignment between projects.

**Comment by rgravina** [comment]
:+1:-ing! For the meantime, I've disabled watchman (e.g. using hombrew on mac):
```
brew unlink watchman
```
and added to my addon in ```/index.js```
```javascript
module.exports = {
  name: 'my-addon',
  isDevelopingAddon: function() {
    return true;
  }
};
```

**Comment by stefanpenner** [comment]
You can instead pass --watcher node

**Comment by rgravina** [comment]
@stefanpenner Thanks! I didn't notice it there in the output of ```ember serve --help```.

Also, slightly related to this - I noticed that when watchman isn't installed currently the suggested link http://www.ember-cli.com/#watchman doesn't jump to an anchor. It might help if a bit of info about watchman (and how to force nodewatcher_ was there, or I guess you could even put it in the output.

```
Could not find watchman, falling back to NodeWatcher for file system events.
Hint: use --watcher node to use NodeWatcher instead. 
Visit http://www.ember-cli.com/#watchman for more info.
```

I did eventually find what I needed in the release notes and following [your issue](https://github.com/ember-cli/ember-cli/issues/3687) to the getting started page, but it might help if it was a bit more obvious. Let me know if you'd like a PR.

**Comment by JackCA** [comment]
Thanks for the workarounds everyone!
