### ISSUE TITLE
[META] Audit and improve build file sizes

### ISSUE THREAD

**Issue by martypenner** [ember-cli/ember-cli#4293]
As per the Twitter discussion [here](https://twitter.com/stefanpenner/status/609385488449867776), it would be helpful to be able to easily audit (and therefore improve) build file sizes. One of the first steps is to increase the visibility of the build size. This will allow a more pro-active approach to improving it.

As @stefanpenner suggested, I think we can begin with these steps:

- [x] Create ember-cli command to output build size of the various assets
- [x] Show asset sizes when running `ember build`

I'll likely find some time tomorrow to begin on item number 2.

**Comment by stefanpenner** [comment]
> Show asset sizes when running ember build

i am undecided if this should be default or opt-in.

**Comment by martypenner** [comment]
Perhaps showing them only when `--environment production`? Seems to me that would be the most useful case.

**Comment by stefanpenner** [comment]
> Perhaps showing them only when --environment production? Seems to me that would be the most useful case.

ok I have a thought, lets always print it for `ember build` unless `--silent` is enabled. If it is to noisy we can always turn it back down.

**Comment by martypenner** [comment]
Perfect. Easy to change behaviour, while producing useful info by default. I like it.

**Comment by martypenner** [comment]
Had a bit of a learning curve when I dug into the code these past few days, but I think I'm seeing things more clearly now. I decided it would make more sense to create the command first, so `ember build` could simply re-use it.

What I'm wondering is how the command (or task) can get access to the EmberApp? It has the config object referencing the app and vendor asset paths I need access to.

**Comment by stefanpenner** [comment]
it has landed!!!
