### ISSUE TITLE
Cannot import files in `/app` from `/dummy/tests/unit`

### ISSUE THREAD

**Issue by thoov** [ember-cli/ember-cli#4296]
I just noticed that I can no longer import files in `/app` from `/dummy/tests/unit` in an addon.

If I have a file like so: `/app/services/my-file.js`

```js
import Ember from 'ember';

export default Ember.Service.extend({
  foo: true
});
```

And a test file `/dummy/tests/unit/services/my-file-test.js`

```js
import Ember from 'ember';
import { module, test } from 'qunit';
import MyService from '../../../../app/services/my-file'; // <--- This used to work but broke this weekend on 2.0

module('My Test Module', {});

test('My Test', assert => {
  assert.ok(true);
});
```

`Error: Could not find module app/services/my-file imported from dummy/tests/unit/my-test`

**Comment by stefanpenner** [comment]
> import MyService from '../../../../app/services/my-file'; // <--- This used to work but broke this weekend on 2.0

yes, they will reside inside 'dummy/services/my-file'

**Comment by thoov** [comment]
@stefanpenner 

Changing to `import MyService from 'dummy/services/my-file';` seems to fix the above issue but has now lead to another one:

I have a test like so: 

```js
// dummy/tests/unit/services/my-file-test.js
import Ember from 'ember';
import { module, test } from 'qunit';
import MyService from 'dummy/services/my-file';

module('My Test Module', {});

test('My Test', assert => {
  assert.ok(true);
});
```

A service file that is imported into the above test:

```js
// app/services/my-file.js
import Ember from 'ember';
import SomeObject from 'ember-addon/helpers/my-object'; // Note that this is now trying to get the file from the 'addon' folder

export default Ember.Service.extend({});
```

It is throwing an error when it is trying to import that file from within the addon folder. Again this code works with ember-cli 0.2.7 with ember 1.13 but not ember 2.0

**Comment by stefanpenner** [comment]
after pairing with @thoov this appears to be an issue in one of this 3rd party libraries, Essentially breaking the vendor.js file

**Comment by martndemus** [comment]
@stefanpenner Care to elaborate which 3rd party library this could be? I'm having the same problem.

**Comment by stefanpenner** [comment]
I believe it ended up being ember-data
