### ISSUE TITLE
Suggestion / Enhancement - let user know that router.js has been modified

### ISSUE THREAD

**Issue by stefek99** [ember-cli/ember-cli#4302]
When using CLI there is notification of new files being created:

![image](https://cloud.githubusercontent.com/assets/249703/8203286/8652a0b2-14d8-11e5-86df-f4afb9d4cc1a.png)

I think it would be good idea to remind user that other files - namely router.js - have been modified in the process.

**Comment by kellyselden** [comment]
:+1:

**Comment by trabus** [comment]
[Like so](#4306)?
I'm open to suggestion for the verbage.

**Comment by stefanpenner** [comment]
Did we lose this? We totally used to say updated

**Comment by stefek99** [comment]
WOW. I'm impressed by your speed and responsiveness...
