### ISSUE TITLE
Test server breaks after refresh of page or change in file

### ISSUE THREAD

**Issue by Eptis** [ember-cli/ember-cli#4304]
When running `ember test --server` the test runner breaks when a file is changed or the page has been refreshed. Ember-cli gives me this error:

`Uncaught Error: Could not find module ember-cli/test-loader at http://localhost:7357/assets/vendor.js, line 125`

I'm running on ember 2.0.0-beta.1, ember-cli 0.2.7 and ember-cli-test-loader 0.1.3.

**Comment by Eptis** [comment]
Ah, this happens because of my files being gzipped and the test serves does not serve gzipped files.

**Comment by stefanpenner** [comment]
> Ah, this happens because of my files being gzipped and the test serves does not serve gzipped files.

can you elaborate? (does it end in .gz or something?)

**Comment by Eptis** [comment]
Yes but I changed this and do not explicitly request .gz except for production. so this issue can be closed.

**Comment by stefanpenner** [comment]
@Eptis i wonder if we should just support this, seems to come at very little risk, thoughts?

**Comment by Eptis** [comment]
Well normally you don't directly request gzipped files but setup your server to serve them. Also serving gzipped files in testing mode doesn't really make sense (I realized), so I don't think it's worth the effort.

**Comment by stefanpenner** [comment]
> Well normally you don't directly request gzipped files but setup your server to serve them. Also serving gzipped files in testing mode doesn't really make sense (I realized), so I don't think it's worth the effort.

sounds good, closing then. Thanks for the submission.
