### ISSUE TITLE
ember test fails when using ember v2.0.0

### ISSUE THREAD

**Issue by AyKarsi** [ember-cli/ember-cli#4305]
Steps to reproduce: 
- Create a fresh ember-cli app 
- switch to ember 2.0.0
- run tests -> tests ok
- generate a route
- run tests -> tests fail with 
```
            beforeEach failed on it exists: Attempting to register an unknown factory: `component:-link-to`
```
- switch back to ember 1.12 
- run tests -> tests  ok

My setup is the following: 
- ember-cli 0.2.7
- node 0.12.4
- window 7 64 bit

**Comment by marcioj** [comment]
Updating `ember-qunit` to 0.4.0 in `bower.json` should fix this problem.

**Comment by AyKarsi** [comment]
Thanks. That solved the problem.
