### ISSUE TITLE
0.0.39 & 0.0.40 package.json expresss not found

### ISSUE THREAD

**Issue by reidsteven75** [ember-cli/ember-cli#4312]
Noticed the package.json for 0.0.39 & 0.0.40 versions have 'expresss' as a dependancy instead of 'express' (extra s). This causes my pushes to heroku to fail as there is no 'expresss' module.  Is there a reason for this, or is the extra 's' a typo?

**Comment by stefanpenner** [comment]
> Noticed the package.json for 0.0.39 & 0.0.40 versions have 'expresss' as a dependancy instead of 'express' (extra s). This causes my pushes to heroku to fail as there is no 'expresss' module. Is there a reason for this, or is the extra 's' a typo?

Seems like a typo, but those versions are quite old and no longer supported.
