### ISSUE TITLE
Quest: Replace fs.existsSync with exists-sync in ember-cli and dependencies

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#4315]
Ember-cli uses `fs.existsSync` fairly heavily in the codebase, as well as in many of the tests for ember-cli itself. Node.js has slated `fs.exists` and `fs.existsSync` for deprecation, so we need to migrate away from using it. I propose that we replace any usage of `fs.existsSync` in ember-cli with [`exists-sync`](https://github.com/ember-cli/exists-sync).

`exists-sync` provides the same basic functionality as `fs.existsSync`, but it also handles symlinks a little more intelligently. It will recursively resolve the target of a symlink, only returning true if an actual file is found (preventing false positives from symlinks).

It is also used throughout several broccoli plugins, so we should probably look to update any dependencies of ember-cli with it as well.

We should probably follow the pattern used [here](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/create-and-step-into-directory.js#L8):
```
var existsSync  = require('exists-sync');

// later
if (existsSync(filepath)) {
...
```

## instances to replace in ember-cli
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/broccoli-config-replace.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/index.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon-discovery.js
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/installation-checker.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/preprocessors/plugin.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/markdown-color.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/version-utils.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/create-and-step-into-directory.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/serve.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/express-server.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/tests-server/index.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/brocfile-smoke-test-slow.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/pods-destroy-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/in-repo-addon-destroy-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/destroy-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/addon-destroy-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/new-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/acceptance.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/assert-file.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/assert-dir-empty.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/file-utils.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/tmp.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/unit/commands/test-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/unit/models/builder-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/unit/broccoli/config-loader-test.js 
- [ ] https://github.com/ember-cli/ember-cli/blob/master/tests/unit/utilities/attempt-never-index-test.js
- [ ] https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md 

I'll add dependencies and addons to this list as I have time.

**Comment by jasonmit** [comment]
I took a first pass at this, noticed the tests should likely be using `file-utils` where possible for `exists`.  Want me to address this as well @stefanpenner
