### ISSUE TITLE
Sourcemap is wrong for ember-data

### ISSUE THREAD

**Issue by snwfog** [ember-cli/ember-cli#4317]
Im running latest ember-cli installed from master branch. The ember-data source map is wrong.

![screen shot 2015-06-21 at 8 30 39 pm](https://cloud.githubusercontent.com/assets/682969/8274038/87e4ebfe-1854-11e5-8af5-0b860b8c5479.png)

**Comment by rwjblue** [comment]
The source map file for a few versions of ember data (at least 1.0.0-beta.18 and 1.0.0-beta.19) are the wrong file contents.
