### ISSUE TITLE
Cannot manually instantiate and append a view in Ember CLI with Ember 1.8

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#4323]
In Ember 1.8 without Ember CLI, the following was as recommended by Guides and worked inside an Ember View:

    var view = App.MyView.create({ container: this.get('container') });
    view.append();

Using Ember 1.8.1 with Ember CLI 0.1.15, the following fails:

    import Ember from "ember";
    import MyView from "dummy/views/my-view";

    export default Ember.View.extend({
        setup: function() {
            var view = MyView.create({container: this.get('container')});
            view.append();        
        }.on('didInsertElement')
    });

Error is something like: You attempted to manually instantiate a view. Please use a createChildView or a Ember.ContainerView

**Comment by Gaurav0** [comment]
Actual error message is: Assertion failed: You cannot append to an existing Ember.View. Consider using Ember.ContainerView instead

**Comment by stefanpenner** [comment]
A default ember-cli app does not demonstrate this issue:

https://github.com/stefanpenner/__ember-cli_append-view
commit that attempts to demonstrate: https://github.com/stefanpenner/__ember-cli_append-view/commit/c5a5d322cd8237540b4d046225460f8a33104dfc

When investigating the source of this assertion: https://github.com/emberjs/ember.js/blob/680f997ed0958c420abdcd0b1673111aee26afe7/packages/ember-views/lib/views/view.js#L964

It indicates `!target.is('.ember-view') && !target.parents().is('.ember-view')` which implies the view is being appended as the descendent of another ember view. This does not appear to be the default configuration of an ember-cli app, as there root element is a descendent of body, not body itself. 

Is it possible your app is making its root element body?

**Comment by Gaurav0** [comment]
First, we intended the view to be appended to the current view, so the assertion certainly applied.

Strange. The source of append is:

return this.appendTo(document.body);

which means target is in fact document.body, not the ember view we intended. Somehow this never should have worked...

And yes, we did have body as the root element prior to migrating to Ember CLI. But that is no longer the case.

Thanks anyway for looking into this. We must be doing something else somewhere...

**Comment by stefanpenner** [comment]
@Gaurav0 yes. It seems something is fishy, but it appears both ember and ember-cli are working correctly.

Maybe it's worth checking the history to see when those assertions where added? If memory serves they have been around for quite some time. As appending like this to another view bypasses the normal view creation and wiring paths.
