### ISSUE TITLE
Strange directory structure copying on ember s

### ISSUE THREAD

**Issue by artych** [ember-cli/ember-cli#4324]
I see something strange with my project on ember-cli 0.2.7. My project name `spa_data`, so my project directory structure is inside `spa_data\`. 

On **ember s** my project structure is recreated in `spa_data\spa_data\` (only empty folders without any file), and `spa_data\modules` directory is created with `ember-can\helpers` , `ember-can\utils`, `ember-18n\config` (also empty). 

It is probably important to mention that:
1) I use pods (`modulePrefix: 'spa-data', podModulePrefix: 'spa-data/pods'` in config)
2) I use `ember-can` and `ember-18n` addons and many others.

I've tried to remove `spa_data\spa_data\...` and `spa_data\modules` manually but they appeares on **ember s**.

**Comment by stefanpenner** [comment]
Which version of node/npm/os

**Comment by stefanpenner** [comment]
Can you provide a public repo that demonstrates this issue

**Comment by artych** [comment]
I've reinstalled project from repo and it is fine now. I think it was something wrong on my local machine and it was not ember-cli bug. I am closing this conversation.
