### ISSUE TITLE
How should I migrate ember startkit project to ember-cli?

### ISSUE THREAD

**Issue by DoryZi** [ember-cli/ember-cli#4325]
0
down vote
favorite
I have a node.js backend server and an ember front-end project which is together:

public\js -> contains all the ember app stuff
app\ -> contains the node.js files
server.js -> main express server code
I would like to migrate to use ember-cli. I've tried the migrator and running ember init but both do not really work and give me errors. Most the documentation talks about migrating from EmberAppKit which I didn't use, but use my own grunt script to complie the templates and uglify and minify the css and js files.

How should I go about migrating such a project to Ember-cli? I'm very confused..please help.

Thanks!

I've also open it on stackoverflow:
http://stackoverflow.com/questions/31000522/migrate-from-ember-start-kit-not-appkit-to-ember-cli

**Comment by stefanpenner** [comment]
The stackoverflow post is the correct place to ask. We need to keep this issue tracker focused on bugs.

I'm going to close this and direct future travelers to the SO post.

**Comment by DoryZi** [comment]
OK thanks.

Is it possible to include some guide on migration for people like me? I'm
lost to find a good resource on what to do...

Please advise.
Cheers
D

**Comment by stefanpenner** [comment]
The ember guides are now written for ember-cli, and ember-cli site has a description of what the differences are.

**Comment by DoryZi** [comment]
I see lots of information but I'm having a hard time on concrete examples
of what should I do? Just to start changing my files? Or what exactly??
Create a new ember app and move files into it? So nuclear...

Here is the only advice on migration I found
If your app uses globals (e.g. App.Post) from a different build pipeline
such as Grunt, Ember-Rails, or Gulp, you can try using the Ember CLI
migrator <https://github.com/fivetanley/ember-cli-migrator>. The Ember CLI
migrator is a command line tool that looks at your JavaScript code using a
JavaScript parser and rewrites your code to ES6 following Ember CLI’s
conventions. The migrator keeps your code style and keeps git history
available via git log --follow.

**Comment by DoryZi** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Dory

Confirm that you know Dory: https://www.linkedin.com/e/v2?e=-b2wma1-ibjqh9u6-v&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=duoqumT4&amp;invitationID=6021732368254005248


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-b2wma1-ibjqh9u6-v&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQHF4ZvH3XFOkQAAAU5F9xEQ0YzzVYOGnn3nvYT5lyqE8sz4t2h2T2z8D6aaSYh_3GvnQxuzQ_xBpEH7uOAcBCTcAzLmtBIJKbv9VhGG1vslCbwfnkFHlUlQd-uiMDDMDR61aj7colzWwLS8oTOZ4_-E1D3hK_ApAh4Qc-pTdJIa3veIwa6hEE81h4cEJT81Lm5a&amp;eid=-b2wma1-ibjqh9u6-v Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-b2wma1-ibjqh9u6-v&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DoryZi** [comment]
Join Dory Zidon and over 300 million other professionals already on LinkedIn

Sign up to become Dory's newest connection.

Confirm that you know Dory: https://www.linkedin.com/e/v2?e=-hdtojh-ibjqh9fz-3m&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=LAotdQKI&amp;invitationID=6021732368493088768


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-hdtojh-ibjqh9fz-3m&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQEp_WDBnKSg-gAAAU5F9xv5FqwjWuhZKrOCNJlB-i8up9yB8AMfCqWgbY896UG9nMyKSF0w0Awkx4L3hdL-Kw34WDp4LuUQtVhorSQiHgXrqGcW7DPmKJSJV-dNbE_duoZqjLOBKinsCRgcV-lVC4WxGKcnGtpvBeMyREhtjMQYkn4d-GkuB_4g0ZjoAqgBOr5P&amp;eid=-hdtojh-ibjqh9fz-3m Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-hdtojh-ibjqh9fz-3m&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DoryZi** [comment]
Dory Zidon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0UdzsUe30PejgUdzcOcPsNcz0Sfkh9rCZFt65QqnpKqip9iR5At6Z1j3RVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cc3gJt6kNsC9QoCAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

View Dory Zidon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=cPgOe3gRd3R4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCc3gJt6kNsC9QoCAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9m4SdC4OdzkMpmcVdz5xczAOd6kOcm4Ncj4Mc30Mc30MpCcOejAOdztycS9zcS9ydP1zc38TomgUoPwPe38Vd6lAp30Ocz1yemkQcm4Se3gVczsMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwSdPwUc3cVd3wScP8PdP4Oc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCc3gJt6kNsC9QoCAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0Md2RQpj5OoDhyqiREqCZQp6wJfmhFpipLk7h7dmRLuk8RsnsJjAV4omt3s4oNoj98pTdhcC9esnsTlRpcq4ZqkTAScz9Ril1hsllUd49mtmh9dBFEgS9mhBlDrRhxuClBs6RJjDhkkAtPuAdFundKrkJ3qkt2q3pcjmVcr5lnhClIrllUiAJIijdLuDFznR8TcORggnF5l7tJcDlIqRdUoQV3tmYUgR0NskNPdjpMkClMtDB9uCUJt71mukQUkAYOdCwViCUQgT0Rlk51gmtotAxTqkhQjjtohB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCc3gJt6kNsC9QoCAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6021732439955632128_500&amp;markAsRead=This email was intended for ember-cli/ember-cli. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cc3gJt6kNsC9QoCAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DoryZi** [comment]
Dory Zidon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Ud38Rc30Qdj8UdzcOcPsNcz0Sfkh9rCZFt65QqnpKqioQl6RRsmZRp3RVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zsZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cc34JdmFBsC9QoCAJcm5JtP9ybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732441914376192_500&markAsRead=

View Dory Zidon&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I6021732441914376192_500&simpleRedirect=0MckkT9jlGpn9yt69FhjsBcm5JtP9yhjsBbmNItmUJt7xBt5ZBr6BCrT9MbjwJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZr6BxrklHsDgCt7xBt5ZBr6BCrT9MbjwJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZqT9Q9zcQczwQdjgZp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9m4SdC4OdzkMpmcVdz5xczARdmoPcm4Ncj4Mc30Mc30MpCcOejoPpmcMp6gPdC4Nc3tye3cNcjcScS8NdmoOpm9yemgQpz8SdmoRojgSe3gVczsMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwQczkMc3gRczwScP8PdP4Oc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCc34JdmFBsC9QoCAJcm5JtP9ybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732441914376192_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0MciQRqClOoDhyqiQNomRTcC8JfmhFpipFsmlnrmZBm2RAjPdAu5sOt6lBr5tVmmJcs4pRc3sUgnpyq6ZGrStKdC5KpkxMcjpzujwViQFItOQOpS8OdDpnljpxqANLdm5HjSNqsTFHjmpvjkZpgC5ae4RQsCQRi6RejQAVjCNKiBB7cjBpj39Tj3pGlP5vi5pGpSlTc51cd7dcjiQSiQVdontqhzp1diRchScQc7cPm6ZTkkl3j4lypThPdCdhcSl7tlsTk3dqh70Rlk51gk4JjAlxq5BJhCtci551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCc34JdmFBsC9QoCAJcm5JtP9ybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6021732441914376192_500&amp;markAsRead=This email was intended for ember-cli/ember-cli. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cc34JdmFBsC9QoCAJcm5JtP9ybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732441914376192_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DoryZi** [comment]
Dory Zidon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0UdzsUe30PejgUdzcOcPsNcz0Sfkh9rCZFt65QqnpKqip9iR5At6Z1j3RVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9CsJrn0Su68PoSAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

View Dory Zidon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=cPgOe3gRd3R4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9CsJrn0Su68PoSAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBojoSoj8Sdj1BoPAScm4Oej8Qpj8Noj4Ncj0Mc30Mc31CoP8Vej8SdS8PoCcPoC8Tc6cMcztxp3xze3cUczAQpmhAc38Oc68VpjgNojoUd3AOdP0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACe3oTe3wMcPAQe3oPczcTcj8MdzRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9CsJrn0Su68PoSAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=pORJs3pUozdzqiREqCZQp6wJfmhFpipOcSMRcnp3gBBJi4Nndn8Ol75BqPwNrl9goANcln9IpmpSpCJggkcScCt9pAtKjSd2okZDoCt9l4JPj4dmq2REkTcQgmFItmdKm4hyin8NcRFUjSZ2gkEVdkNidChBrPtFkAlSoD5FrCFEsSMJe6RItn9xhPdLsmRClz1Qu6hqbkl9entJdl8JslhHtmkRtPlTqSFTkmdOmCx8r6Vkp6ZFj4lbk3sUs4NSoAtUpAd2hQUSlk51gmtWk5tftlFGhkVlhR51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CsJrn0Su68PoSAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6021732439955632128_500&amp;markAsRead=This email was intended for ember-cli/ember-cli. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CsJrn0Su68PoSAJq6FLt6hEbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6021732439955632128_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by kellyselden** [comment]
Locked because of spam.
