### ISSUE TITLE
Unable to install when github it not reachable

### ISSUE THREAD

**Issue by jeffshaver** [ember-cli/ember-cli#4328]
I work in an environment where we have, basically, a clone of npm. However, we do not have access to github. The issue is that when you try to install ember-cli via npm, it tries to fetch things from github, which completely breaks the install. Is there a way around this? The first thing it fails to get is node-XMLHttpRequest from https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz.

**Comment by stefanpenner** [comment]
Seems bad that some npm deps are depending on github. But I suspect you won't make it further since all of bower resides on github. We are in the process of cutting over to an entirely npm world. That will be some time yet though.

**Comment by stefanpenner** [comment]
It's worth investigating and fixing this specific dep

**Comment by jeffshaver** [comment]
@stefanpenner I found this. Maybe it will be fixed if they do a version bump? https://github.com/Automattic/engine.io-client/issues/348

**Comment by stefanpenner** [comment]
Ha. I've been pinging them to do s release for many months. No luck yet :(. Maybe someone else can also reach out?

For reference the issue I opened is in the socket.io repo

**Comment by jeffshaver** [comment]
@stefanpenner someone i know made a comment like 30 minutes ago or so asking for a version bump. But if you didn't get any traction, I doubt we will xD

**Comment by stefanpenner** [comment]
For reference: https://github.com/Automattic/socket.io/issues/2107

**Comment by bushong1** [comment]
:+1: Gotta keep nagging them.

**Comment by jeffshaver** [comment]
@stefanpenner this and other github dependencies (if there are more... which i suspect) completely stops me (and I assume others) from using ember. We have no way of installing ember-cli until the dependency on github repos goes away.

I hope this is sooner rather than later. I wanted to use ember on an upcoming re-write of an app, but this is stopping me in my tracks :cry:

**Comment by stefanpenner** [comment]
> I hope this is sooner rather than later. I wanted to use ember on an upcoming re-write of an app, but this is stopping me in my tracks

Ya, its something we are working on (actually, I am writing this comment when i should be working on it), But as all bower dependencies live on github. It means, we must drop not only npm based git deps, but all of bower and our client-side deps, and transition to npm entirely. Which has proven to be a lot of work.

@jeffshaver if HTTP is allowed, why cant you just configure GIT to use HTTP instead? Or is even HTTP disabled?

For example: http://stackoverflow.com/questions/15669091/bower-install-using-only-https

**Comment by jeffshaver** [comment]
@stefanpenner It isn't that HTTP is disabled or anything. It is just that we are basically on an intranet with no access to the internet. We just so happen to have a copy of npm that gets ported over nightly (and run `npm config set registry newUrl`). But it fails to install since we literally have absolutely no way of getting to github

**Comment by stefanpenner** [comment]
Ah. Understood. 

Well @chadhietala and myself are working on the solution as we speak. Both LinkedIn and yahoo would also prefer to drop bower and the mandatory github dep invoked.

Stay tuned

**Comment by felixrieseberg** [comment]
You know, the license totally allows us to just copy and republish under a different name. It'd be the most horrible fix, but it's been months...

**Comment by stefanpenner** [comment]
> You know, the license totally allows us to just copy and republish under a different name. It'd be the most horrible fix, but it's been months...

Ya, i've been tempted. Unfortunately, time is the limiting factor.

**Comment by jeffshaver** [comment]
@stefanpenner it doesn't seem like the socket.io people plan on releasing anytime soon, it has been almost 2 months. Are there any other routes we can take to get this moving forward?

**Comment by stefanpenner** [comment]
@jeffshaver the lowest pain route is to get them to release. I don't have time to fork and maintain the forks

**Comment by jeffshaver** [comment]
@stefanpenner understood. just doesn't seem like that is going to happen anytime soon.

**Comment by stefanpenner** [comment]
I'm not sure what to say. Someone has to step up an move this forward. Maybe jump on the socket.io slack and ping rauchg?

**Comment by jeffshaver** [comment]
@stefanpenner Done. Hopefully I will see a response soon.

**Comment by stefanpenner** [comment]
@jeffshaver thanks, I suspect he is just busy. I would love to fix this, but my plate is full currently.

**Comment by jeffshaver** [comment]
@stefanpenner got a reply. He said "k" and i think i saw a commit for a version bump

**Comment by felixrieseberg** [comment]
I'll give this another week, but after that, I might sit down and write a mirror that automatically publishes the Socket.Io HEAD to npm. It's not the solution I want, but this doesn't seem to be going anywhere :(

Thoughts?

**Comment by stefanpenner** [comment]
@felixbuenemann it may be our only option. Remember though, we need testem buy-in as-well.

@johanneswuerbach thoughts ? It seems like testem really NEVER needs the native extension here.

**Comment by johanneswuerbach** [comment]
SGTM, I would also move completly away from socket.io if there would be a better alternative supporting IE 8+ and providing a ws like channel between client and server.

@felixrieseberg I also looked into pushing socket HEAD myself, but as socket io is assembled by 5+ modules I didnt spend much time on it

**Comment by jeffshaver** [comment]
@stefanpenner node-XMLHttpRequest is still an issue. Idk which package is using the github url, but idk why its being used instead of https://www.npmjs.com/package/xmlhttprequest which is the same?

**Comment by stefanpenner** [comment]
@jeffshaver engine.io-client

**Comment by jeffshaver** [comment]
@stefanpenner sigh. will ping them to change maybe xD I wonder how many github deps there are total? lol

**Comment by stefanpenner** [comment]
^^ issue opened, we can in theory work around this ourselves. I can likely write a script as part of our packaging that forces this to be part of our npm tarball

**Comment by jeffshaver** [comment]
@stefanpenner thanks for helping me work through this :smile:!!

**Comment by bushong1** [comment]
https://github.com/socketio/engine.io-client/issues/348  should already cover this.

**Comment by jeffshaver** [comment]
@stefanpenner when will this get put into a release? thanks!

**Comment by stefanpenner** [comment]
> @stefanpenner when will this get put into a release? thanks!

once this PR is green https://github.com/ember-cli/ember-cli/pull/4468

**Comment by jeffshaver** [comment]
@stefanpenner thanks :)
