### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by rvan1** [ember-cli/ember-cli#4332]
I've resumed my attempts to get ember-cli-mocha test blueprints working in my ember CLI app, which I 'migrated' from ember EAK. Since it doesn't work, possibly because the 'assets' scripts referenced in the 'Ember-Mocha Tests' 'index.html' are mostly 404. So I went about updating ember CLI 0.2.3 to 0.2.7. But I got errors like 'unmet dependency, rimraf requires glob@'^4.4.2' but will load', so I changed the 'glob' version in package json, but no improvement. So I tried npm install/update, bower install/update, cache clean, and now not only do the tests not work, but the app won't come up anymore - which I knew would happen, but went forward anyway.

With npm install/update, I get tons of 'unmet dependency' warnings, and when I run (ember server) the app, I get error "ENOENT, no such file or directory 'C:\ember\cli_ibe_1\tmp\funnel-dest_yd9Xcv.tmp\tests\index.html'", though in my 'tmp' I have TONS of 'funnel-dest_this-or-that' files. I suspect if I were to resolve this error, another similar error would queue up in its place.

After doing 'npm cache clean', my dependency warnings went way down, but still when I run the app I get the ENOENT error when broccoli-config-replace tried to read the funnel-dest tmp file.

I'm wondering why I have 'unmet dependency' warnings and 'no such (tmp) file' errors now.

**Comment by stefanpenner** [comment]
may be a duplicate: https://github.com/ember-cli/ember-cli/search?q=ENOENT&type=Issues&utf8=%E2%9C%93

**Comment by stefanpenner** [comment]
> So I tried npm install/update,

`npm update` is basically broken in v1 or v2 or npm, i recommend not using it.

What version of node, npm etc. ?

**Comment by rvan1** [comment]
My project still had several 'karma' modules. I gave up on using karam some time ago and have just been limiting my efforts to mocha. After npm uninstalling karma-phantomjs-launcher, and doing npm/bower cache clean & install, all of my dependency warnings are gone now. And I've emptied my 'tmp' directory several times. 

I've seen the duplicate issues & one also mentions 'funnel-dest', but otherwise isn't entirely the same.

Still I get the error 'ENOENT, no such file or directory '...\tmp\funnel-dest_...\tests\index.html'. So I looked at several 'funnel-dest...tmp' directories and they all contain a copy of some project component, like 'jquery' or 'bootstrap', but there is no 'tests', and I'm not trying to run tests right now, so am not sure why node express or broccoli-config-replace is looking for and not finding it. It seems that the test modules I've installed (mocha overrides test em) cause some problem in a file list which broccoli iterates, but the list isn't in sync with the actual tmp directories.

I have (node) mocha, ember-cli-mocha and also bower mocha, so am thinking to uninstall those to see it it returns to normal (test em).

node (windoz): 0.12.0, npm: 2.5.1, bower: 1.4.1

**Comment by rvan1** [comment]
Well I removed all npm and bower modules for mocha, cli-mocha, mocha-adapter, but still get the ENOENT error on funnel-dest tests and broccoli-config-replace, when running 'ember server'. Same thing with 'ember test' and 'ember test --server'. I'll have to think about some new ways to get more debug info.

Error: ENOENT, no such file or directory 'C:\ember\cli_ibe_1\tmp\funnel-dest_4ywZWX.tmp\tests\index.html'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:354:15)
    at CustomReplace.processFile (C:\ember\cli_ibe_1\node_modules\ember-cli\lib\broccoli\broccoli-config-replace.js:57:21)
    at CustomReplace.process (C:\ember\cli_ibe_1\node_modules\ember-cli\lib\broccoli\broccoli-config-replace.js:52:10)
    at lib$rsvp$$internal$$tryCatch (C:\ember\cli_ibe_1\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (C:\ember\cli_ibe_1\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (C:\ember\cli_ibe_1\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:472:11)
    at lib$rsvp$asap$$flush (C:\ember\cli_ibe_1\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

**Comment by stefanpenner** [comment]
it seems like you are legitimately missing some files?

Can you post a repo on github that demonstrates this issue, otherwise I am unsure how to debug the issue for you.

**Comment by rvan1** [comment]
I see, while not entirely obvious from the error, and while getting distracted by lots of 'unmet dependency' warnings, until I went and resolved them, the real issue is because I removed the tests 'index.html' file. I put it back and now the app will run.

With 'test em', there's an 'index' file referencing various script 'assets' like 'testem.js' and 'test-loader.js'. When switching to 'mocha', a different 'index' file is used which references 'loader.js' and other 'assets' which are 404. So I was thinking that the 'tests\index.html' file was generated from a blueprint and that I would remove and re-generate and maybe things would come together with mocha.

I guess that 'tests\index.html' is a required project file and is not generated. It was not getting re-generated & it didn't occur to me that its absence was the cause of my primary error.

Actually, if I wanted to re-generate the mocha index file, I should have run 'ember generate ember-cli-mocha', but didn't occur to me & probably wouldn't fix my missing script assets issue anyway. 

I did post an 'issue' over at 'cli-mocha' github, about my 404 asset files, but no response.

**Comment by stefanpenner** [comment]
> until I went and resolved them, the real issue is because I removed the tests 'index.html' file. I put it back and now the app will run.

yay!

**Comment by stefanpenner** [comment]
> the real issue is because I removed the tests 'index.html' file. I put it back and now the app will run.

yay, sounds good!

**Comment by stefanpenner** [comment]
The last points appear related to `ember-cli-mocha` not with ember-cli itself.

**Comment by markduan** [comment]
I have the similar issue, and manually create a tests/index.html file, the issue just gone. I don't know why.

**Comment by oleander** [comment]
I can confirm that @markduan solution works. Thanks
