### ISSUE TITLE
private api usage in blueprints

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#4333]
This has probably been discussed elsewhere. But should we expunge the use of private API code in blueprints? 

One example (I think)

generate an in-repo addon and then generate an in addon component

```
ember g component x-foo -ir my-addon
```

Renders something like this:

```
import Ember from 'ember';
import layout from '../templates/components/x-foo';

export default Ember.Component.extend({
  layout: layout
});
```

Looks to be private API
http://emberjs.com/api/classes/Ember.Component.html#property_layout

What does layout do here? If I interpret the docs correctly it seems to be a way to supersede the template, so basically we are giving the addon ability to define layout before everybody else.

If I am correct seems reasonable.

But raises question if we are going to be strict about private vs public should probably avoid encouraging use of private API, (if reasonable and feasible).

If this can't be done without layout then why is `layout` still private? Is that the bug or is the blueprint the bug, or is there no bug here?

I am not particularly religious about this. Just curious.

**Comment by stefanpenner** [comment]
It needs to be flipped to public. Or a transition strategy must be created

**Comment by rwjblue** [comment]
As I mentioned in  https://github.com/emberjs/rfcs/pull/56#issuecomment-114522321:

> Unfortunately, we didn't have very good requirements about adding API documentation. I recently added a rule to our CI system that required every documentation block to be explicitly labeled as @public or @private to make it extremely clear if a thing is public or not:

> * If it is documented and labeled as `@public` it is public.
> * If it isn't documented or is labeled as `@private` it is private.

> It is likely that I messed up a few specific API's when I did that sweep (and accidentally labeled things `@private` when they shouldn't have been), but once discovered it should be easily fixed with a documentation PR.

> These changes should make it much easier to ensure that things ending up in the guides are in fact considered public API (this was not previously true).

**Comment by rwjblue** [comment]
It is absolutely possible that I messed some of them up, we are happy to review case by case and make public again, but we **need** to have a canonical source of public/private (which we now have).

**Comment by stefanpenner** [comment]
> As I mentioned in emberjs/rfcs#56 (comment):

ya, should we flip this to public?

**Comment by rwjblue** [comment]
`layout` does not do what it used to do (in 1.13+ it does not rerender if the layout prop of a component changes after initial render as it only looks for `layout` [once before initial render](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/node-managers/component-node-manager.js#L84)).  There are a couple open issues in emberjs/ember.js for that.
