### ISSUE TITLE
`ember lint` command

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#4335]
- `ember test` first builds the whole codebase before linting it, which takes quite a long time
- `ember serve` seems to run JSHint *before* building and runs quite fast

it would be great if there was an `ember lint` command that would run JSHint like `ember serve` does, but without starting a server etc. it should also fail with an error exit code if it discovers lint errors.

**Comment by stefanpenner** [comment]
Sounds good, can you open a detailed rfc? This allows the details to be hashed out

**Comment by alexdiliberto** [comment]
:+1: Great idea, would love to see this implemented

**Comment by fishermand46** [comment]
:+1: Was just about to open an issue for this. This would be great!

**Comment by Turbo87** [comment]
@alexdiliberto @fishermand46 feel free to help me out on writing the RFC. my time is limited ATM.

**Comment by stefanpenner** [comment]
> Sounds good, can you open a detailed rfc?

**Comment by erose** [comment]
This would be fantastic. What's the current status?

-- thanks for working on Ember!

**Comment by bekzod** [comment]
when this is coming to ember-cli ? :P

**Comment by Turbo87** [comment]
I guess https://github.com/ember-cli/ember-cli/pull/7452 comes quite close to this
