### ISSUE TITLE
How to change locationType and baseURL on fly

### ISSUE THREAD

**Issue by zion03** [ember-cli/ember-cli#4336]
I have one ember application and two entry point 

`m.site.com/foo`
`site.com/path/to/ember/#bar`

One should work with `locationType` `hash` and another `auto`, both with different `baseURL`.
How I can do this in a simple way? found only this solution http://stackoverflow.com/questions/28961499/change-baseurl-on-fly-ember-cli.

Thanks

**Comment by stefanpenner** [comment]
not something we support
