### ISSUE TITLE
Building addon with components/ember#beta makes addon modules vanish.

### ISSUE THREAD

**Issue by martndemus** [ember-cli/ember-cli#4338]
It just works when I use 1.13.2 but, as soon as I turn on 2.0.0-beta or 2.0.0-canary the build output doesn't include all the modules from the `addon` directory.

**Comment by martndemus** [comment]
I found that changing `components/ember#beta` to `components/ember#2.0.0-beta.1` in `config/ember-try.js` fixed it for me.

**Comment by stefanpenner** [comment]
Related to @thoov s issue

I believe this is a bug in ember-Dara's output.

We can likely Concat in a more defensive way. But Ed should be fixed


Which version of Ed are you using and have you tried its canary?

**Comment by martndemus** [comment]
Not tried ED canary. I'm on ED 1.13.4. Will try canary.

**Comment by stefanpenner** [comment]
will reopen if demonstrated to be an issue on latest
