### ISSUE TITLE
Is there any standard for supporting multiple Ember versions in Addon code?

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#4339]
Hi Friends!

I'm working on supporting Ember / Data 2.0 with a couple addons, (Spree Ember and Ember Infinity).

There's places in those codebases that will require changes that aren't supported pre-1.13 (such as moving `find` to `query`, etc).  In cases like that, we'd have to switch codeblocks based on the Ember / Data versions to support both pre & post 1.13 & 2.0.

Is there an "official" way to handle these cases?  Or is there an addon that anyone is aware of that is doing it a good way for reference? 

Alternatively - is it kinda-generally-advised to just drop support for older versions of Ember in newer versions of Addons?  Like, is the appropriate solution for Addon consumers to "simply update Ember to use the latest version"?

Thanks all!!

hx

**Comment by stefanpenner** [comment]
> Is there an "official" way to handle these cases? Or is there an addon that anyone is aware of that is doing it a good way for reference?

It depends on what the add-on is using. 

* In some cases no changes are needed
* in other cases some feature sniffing is needed
* in more advanced cases it will be better to create a new major release of the addon and split support.

**Comment by rwjblue** [comment]
@lukemelia and I updated [ember-cli-version-checker](https://github.com/rwjblue/ember-cli-version-checker) to allow easy node-land detection of bower or npm dependencies.  I tried to update the README to explain that, but would love some review and suggestions where it falls short.

Take a look at https://github.com/yapplabs/ember-modal-dialog/pull/43 & https://github.com/yapplabs/ember-modal-dialog/pull/44 for an example of how you might use this.

---

> There's places in those codebases that will require changes that aren't supported pre-1.13 (such as moving find to query, etc). In cases like that, we'd have to switch codeblocks based on the Ember / Data versions to support both pre & post 1.13 & 2.0.

One (somewhat involved) suggestion is to use the examples from the ember-modal-dialog scenario, and make your `addon/` folder structured as follows:

```
/addon/
/addon/all-versions
/addon/gte-1-13
/addon/lt-1-13
```

Then create an implementation in your `index.js`'s use something like the following (pseudo-code):

```javascript
var mergeTrees = require('broccoli-merge-trees');
var funnel = require('broccoli-funnel');
var VersionChecker = require('ember-cli-version-checker');

module.exports = {
  name: 'foo-bar',
  treeForAddon: function(tree) {
    var checker = new VersionChecker(this);
    var dep = checker.for('ember', 'bower');

    var basePath = path.join(this.root, 'addon');
    var baseTree = this.treeGenerator(path.join(basePath, 'all-versions'));
    var versionTree, currentVersionTree;

    if (dep.lt('1.13.0-beta.1')) {
      versionTree = this.treeGenerator(path.join(basePath, 'lt-1-13'));
    } else {
      versionTree = this.treeGenerator(path.join(basePath, 'gte-1-13'));
    }
    currentVersionTree = funnel(versionTree, { destDir: 'current' });

    return mergeTrees([baseTree, currentVersionTree]);
  }
};
```

Use `/addon/all-versions/` for the majority of your code, and where you need version specific functionality import it from `../current` like:

```javascript
import storeContainerName from '../current/store-container-name'; // store:main, store:application, service:store depending on version
```

**Comment by hhff** [comment]
Thanks all!  I actually just put together this addon:
https://github.com/hhff/ember-version-is

I wanted a way to have simple, readable "switch on version" blocks for the addon code, so that as Ember moves on, I can simply go in and delete blocks as I drop support for older versions.  

I think the small increase in JS payload is a worthwhile tradeoff for the code maintainability / readability (specially on big Addon packages like Spree Ember).

I'll have a PR using this up for Ember Infinity soon (@truenorth works with me on it actually).

Let me know thoughts!

**Comment by kellyselden** [comment]
This issue kind of reminds me of the jQuery shift from user agent sniffing to feature detection. Maybe this would be the best way for simple cases:
```js
if (this.store.find) {
  this.store.find(/*...*/);
} else {
  this.store.query(/*...*/);
}
```
and if you can't feature detect, then use a version addon? Just more thoughts for the best practice docs.

**Comment by rwjblue** [comment]
@kellyselden - Feature detection is better in general than version checking, but is harder when the older interface is kept around with a deprecation.
