### ISSUE TITLE
Guidance on adding addon bower packages to application without blueprint

### ISSUE THREAD

**Issue by ChrisHonniball** [ember-cli/ember-cli#4342]
I'm creating an addon with only helpers in it and need to find out how to add bower packages to the including application. I have done the following before in another addon:

```javascript
//blueprints/ember-cli-x-button/index.js
module.exports = {
  normalizeEntityName: function() {}, // no-op since we're just adding dependencies

  afterInstall: function() {
    return this.addBowerPackageToProject('x-button'); // is a promise
  }
};
```

I'm wondering what is the correct way to handle this if your addon doesn't have a component blueprint. Any help is greatly appreciated!

**Comment by stefanpenner** [comment]
Today this is the correct approach.

We are nearing release of a more automatic solution when it comes to dependencies, stay tuned!

**Comment by ChrisHonniball** [comment]
I understand this process *if* the project has a blueprint and it works well. What I need is to be able to include bower packages when the addon *does not* need a blueprint.

The other (not so optimal) solution would be for me to just create a blueprint that does nothing so that I get this functionality.

**Comment by stefanpenner** [comment]
> The other (not so optimal) solution would be for me to just create a blueprint that does nothing so that I get this functionality.

yes that is the current solution.

**Comment by ChrisHonniball** [comment]
Ok, no problem. Thanks. :beers:

**Comment by rwjblue** [comment]
I'm not sure how installing packages into the consuming application can be considered 'doing nothing'.

**Comment by ChrisHonniball** [comment]
> I'm not sure how installing packages into the consuming application can be considered 'doing nothing'

As in the template helper won't be doing anything. Not that that file doesn't do anything.
