### ISSUE TITLE
[Documentation] Addon Sass preprocessor story

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#4345]
How to actually setup sass (or less) preprocessing in an addon is unnecessarily difficult, and unfortunately not well documented.

Seems like it might be related to some bugs with Ember CLI. But also a lot of conflicting info on the interwebs.

It might be helpful to give a concrete Sass oriented example of the `setupPreprocessorRegistry` in the addon hooks document. And also a brief section in the guide and documentation.

I would be happy to contribute a PR if someone could point me to a functioning example addon that demonstrates this. I am still trying to figure this out for my own add ons.

What I am looking to document

- Where to place addon sass? (`my-addon/addon/styles/addon.scss`)
- How to setup `setupPreprocessorRegistry`
- How define dependencies in project.json (e.g. ember-cli-sass)
- How to import sass into dummy app
- How to package for distribution
 - vendor folder and files (broccoli considerations?)
 - make your addon sass styles optional for other users via configuration flag
 - how to wrap addon with a "styles addon" to separate presentation from content/functionality (following the guidance offered by Dockyard)
 - allow sass or scss styles in your own dummy app
- How will resolution of #1853 impact all of the above. 
- Complete and focused example project that showcases all of the above

Welcome any tips and advice or concrete code examples to study, in this thread and I will do my best to synthesize the info for others.

**Comment by eccegordo** [comment]
OK was able to create a minimalist functioning example that demonstrates the `.scss` preprocessing within the dummy test app. Hopefully helpful to others.

https://github.com/eccegordo/addon-sass-example

TODO: Configure the export story and make the addon's `.scss` optional via configuration. 

Not even sure if this is possible yet with Ember CLI. 

Or else demonstrate how one addon can wrap another.

**Comment by dukex** [comment]
@eccegordo There is a issue in ember-cli-sass about addon styles https://github.com/aexmachina/ember-cli-sass/issues/56 and a pull-request here https://github.com/aexmachina/ember-cli-sass/pull/57 waiting a review, 

I'm using my pull-request branch and works fine

**Comment by elwayman02** [comment]
[ember-version-is](https://github.com/hhff/ember-version-is/blob/master/README.md) has a code snippet explaining how to get one addon to consume another until ember-cli fully supports nested addons

**Comment by eccegordo** [comment]
Closing issue because my understanding of Sass preprocessing is good. If someone wants to make more formal guide that would be fine. Hopefully this issue has enough info if someone else hits  this issue.
