### ISSUE TITLE
Update blueprints to use new ES6 features / syntax

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#4346]
I'm using [ember-suave](https://github.com/dockyard/ember-suave) to check all my js files for ES6 compliance (like using `let` instead of `var`). Currently all default blueprints use `var` although they probably should use `let` instead. 

```
jan@ubuntu:~$ ember new test-app
version: 0.2.7-master-a337a1f253
installing app...
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.
jan@ubuntu:~$ cd test-app/
jan@ubuntu:~/test-app$ ember g route test-route
installing
  create app/routes/test-route.js
  create app/templates/test-route.hbs
installing
  create tests/unit/routes/test-route-test.js
jan@ubuntu:~/test-app$ ember install ember-suave
Installed packages for tooling via npm.
Installed addon package.
jan@ubuntu:~/test-app$ ember serve
Livereload server on port 35729
Serving on http://localhost:4200/
Variable declarations should use `let` or `const` not `var` at app.js :
     4 |import config from './config/environment';
     5 |
     6 |var App;
--------^
     7 |
     8 |Ember.MODEL_FACTORY_INJECTIONS = true;
Property assignment should use enhanced object literal function. `{ propName: propName}` is not allowed. at app.js :
    11 |  modulePrefix: config.modulePrefix,
    12 |  podModulePrefix: config.podModulePrefix,
    13 |  Resolver: Resolver
----------^
    14 |});
    15 |
Variable declarations should use `let` or `const` not `var` at router.js :
     2 |import config from './config/environment';
     3 |
     4 |var Router = Ember.Router.extend({
--------^
     5 |  location: config.locationType
     6 |});
Variable declarations should use `let` or `const` not `var` at helpers/resolver.js :
     2 |import config from '../../config/environment';
     3 |
     4 |var resolver = Resolver.create();
--------^
     5 |
     6 |resolver.namespace = {
Variable declarations should use `let` or `const` not `var` at helpers/start-app.js :
     5 |
     6 |export default function startApp(attrs) {
     7 |  var application;
----------^
     8 |
     9 |  var attributes = Ember.merge({}, config.APP);
Variable declarations should use `let` or `const` not `var` at helpers/start-app.js :
     7 |  var application;
     8 |
     9 |  var attributes = Ember.merge({}, config.APP);
----------^
    10 |  attributes = Ember.merge(attributes, attrs); // use defaults, but you can override;
    11 |
Variable declarations should use `let` or `const` not `var` at unit/routes/test-route-test.js :
     7 |
     8 |test('it exists', function(assert) {
     9 |  var route = this.subject();
----------^
    10 |  assert.ok(route);
    11 |});

Build successful - 10063ms.
```

Is this a `wont-fix` or would a PR be appreciated?

**Comment by rwjblue** [comment]
I would be in favor of a PR updating the default to pass ember-suave's default rules (biggest issue is with `var` IIRC).

**Comment by stefanpenner** [comment]
unfortunately we cannot yet migrate the blueprints over to all the next syntax, since babel is still optional. Once we cut over, and make it non-optional we can in-fact doit.

**Comment by rwjblue** [comment]
Babel is shipped by default in the very blueprints we are talking about updating. I suppose we can remove babel from the app blueprint, but having it there *and* not using ES6 seems very silly.

**Comment by stefanpenner** [comment]
> but having it there and not using ES6 seems very silly.

but its still optional, and is still often removed do to performance issues. Especially with large apps.

Once we sort them out, I have no problem making it mandetory and cutting everything over.

**Comment by rwjblue** [comment]
> but its still optional, and is still often removed do to performance issues

If it doesn't work right, we should remove it.  If it does work well, the we should embrace it.  Having a "power user" feature (removing babel for perfs) is generally a bad thing.

Either way, changing the blueprint only affects how new apps are generated and does not in any way prevent you from removing babel.

**Comment by stefanpenner** [comment]
> Having a "power user" feature (removing babel for perfs) is generally a bad thing.

Yes, but it is a reality today, we have work to do to remove the need for the power-user mode.

> If it doesn't work right, we should remove it. If it does work well, the we should embrace it. Having a "power user" feature (removing babel for perfs) is generally a bad thing.

unfortunately the world isn't this binary, we are in a gray area working to remove the problems. I suspect we are on the cusp of solving this issue.

**Comment by rwjblue** [comment]
Again, changing the default does not prevent someone from removing babel.  It merely suggests what we thing of as the "right way to do things" (which I believe we both agree is using babel).

**Comment by eccegordo** [comment]
Does it make sense to have categories of blueprints that target different use cases?

- ember suave blueprints
- es6-ified blueprints
- es7 centric blueprints with stuff like the async/await 
- Ember 1.x vs 2.x blueprints.

I was talking to @trabus the other night about the idea of more didactic "example" based blueprints. Basically more code than the minimum blueprints that ship with ember cli. I think a lot of people learn by seeing the code in the blueprints. So it becomes a way to disseminate a kind of documentation of code patterns.

Obviously this creates more maintenance overhead for core so it is limited.

Perhaps addons of discrete sets of blueprints are the way to go as they can be community managed. But is extra plumbing in ember cli required to switch between blueprint sets and addons? e.g. other than the basic override behavior that works today.

A flag on the generator command perhaps 

```
ember generate component my-thing --bp-set=default  (the core blueprints that ship today)
ember generate component my-thing --bp-set=es6
ember generate component my-thing --bp-set=suave
ember generate component my-thing --bp-set=my-custom-set
etc..
```

If this seems like a good idea I can explore an RFC

**Comment by stefanpenner** [comment]
> Does it make sense to have categories of blueprints that target different use cases?

I'm nervous in maintaining all those.

> Ember 1.x vs 2.x blueprints.

this will be solved by moving blueprints into ember, and making ember an addon.

**Comment by eccegordo** [comment]
Agreed maintaining them is the hassle. So whatever it became it would be reduced set. I was mostly just curious about the extensibility of swapping out complete sets of blueprints.

> this will be solved by moving blueprints into ember, and making ember an addon.

That is interesting. Didn't realize that was the plan. Thanks!

**Comment by stefanpenner** [comment]
Ya it's the plan. Likely a project for the upcoming long weekend

**Comment by ahouchens** [comment]
Can't wait until ES6 is no longer _optional_. For now, I'm moving ahead to just make my blueprint generated code comply with ember-suave.

**Comment by stefanpenner** [comment]
will address this shortly, when babel is on by default for JS users.

**Comment by rwjblue** [comment]
> when babel is on by default for JS users

FYI - Babel is on by default (and has been since March).

**Comment by stefanpenner** [comment]
> when babel is on by default for JS users
> FYI - Babel is on by default (and has been since March).

you know exactly what i meant, please don't be pedantic.

**Comment by rwjblue** [comment]
I'm not, I find your stance on this issue confusing (and have been trying to discuss/understand in a number of issues as it has been coming up).

**Comment by stefanpenner** [comment]
> I'm not, I find your stance on this issue confusing (and have been trying to discuss/understand in a number of issues as it has been coming up).

then, "I am confused" is a more useful response, rather then echoing words.

"Default" was meant, we will still allow users to opt out entirely and take niche approaches (like CoffeeScript etc).

Correct wording would have been non-optional for JS users, and shipped as a dependency of ember-cli itself, not part of package.json.

**Comment by eccegordo** [comment]
can/should the entire blueprints set itself be an addon? That way there can be an easy way to fork and replace entire set of blueprints. 

Seems like it would be convenient to disable/remove all with a single configuration.

People want coffeescript blueprints they can use a specific addon. 
Babel blueprints would be first class example. 
No/empty blueprints would be  option too.

Reference example would be Ember JS blueprints and other variants can model after that.

And additionally it might be make things easier to manage if all my custom blueprints were encapsulated as an addon.

**Comment by stefanpenner** [comment]
> People want coffeescript blueprints they can use a specific addon.

this use-case im not terrible interested in, but a community can do so

> Babel blueprints would be first class example.

shortly this will be the default

> can/should the entire blueprints set itself be an addon? That way there can be an easy way to fork and replace entire set of blueprints.

blueprints should be moved to ember.js

**Comment by eccegordo** [comment]
> We likely need to offer better blueprint refinement options, currently "subclassing" or composition of blueprints is poor.

Yeah being able to surgically hook into blueprints and higher composability would be good.

What will the ultimate fallback be for ember cli if no blueprints are available? A warning in the command line with messaging to install ember.js blueprints?
