### ISSUE TITLE
Conditional test generation

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli#4360]
I'm using [ember-cli-eslint](https://github.com/jonathanKingston/ember-cli-eslint) for my linting. I'm generating tests like instructed in the readme: https://github.com/jonathanKingston/ember-cli-eslint#adding-a-test-generator. Which works as expected.

However, when implemented like in the readme, the tests are generated for *all* environments (`test`, `development` and `production`). Which doesn't work because qunit isn't available everywhere and you don't want tests in the production environment.

What I'd want is for them to only be generated on `ember test` and for the `localhost:4200/tests` of `ember serve` (or `app.env !== 'production' if I'm correct). Something like:

```javascript
if (app.env !== 'production') {
  // code here
}
```
But this won't work because the `eslint` key needs to be passed to `var app = new EmberApp()`, and `app.env` isn't available yet at that point (of course). Also, after the `app` object has been created, something like:

```javascript
if (app.env !== 'production') {
  app.eslint = {
    testGenerator: eslintTestGenerator
  };
}
```
doesn't work either (apparently). Is there an alternative? What's the recommended way to conditionally add these tests? 

Related: https://github.com/jonathanKingston/ember-cli-eslint/issues/18

**Comment by stefanpenner** [comment]
we should keep the issue tracker focused on specific issues. Questions like this belong in the add-on. If a n actual bug is discovered an issue is appropriate. If a feature request is needed, the RFC issue process is likely recommended.

**Comment by ismay** [comment]
I understand. I thought it'd be appropriate here since I want to add an option to `app` conditionally, which currently isn't possible with ember-cli. The addon is just an example, to illustrate why I want to do this.

Feel free to close this if it's still out of scope for the issue tracker though.
