### ISSUE TITLE
Addon as a package containing other addons

### ISSUE THREAD

**Issue by ChrisHonniball** [ember-cli/ember-cli#4361]
I'm attempting to have an addon be a "package" of addons that will install automatically when I include the single "package" addon. I'm having troubles getting this to work. Is this something that is possible with the current ember-cli? I have a few addons that I have created inside the package.json of the containing package and all seems to install normally but the helpers are not available in the application once ran. I have also included them in the `after` hook for the "package" addon.

What I'm looking to do is... Install a single "my-addons" package from NPM and have that package automatically install the other addons that I want included with it. Possible?

**Comment by stefanpenner** [comment]
you'll need to use a generator to install them in the host package.

**Comment by ChrisHonniball** [comment]
Makes sense. At that point I may as well just type `ember install blah-blah-blah` rather than having to type `ember g blah-blah-blah`. I was hoping to avoid the need to type all of that since I install about ten different addons *typically*.

Unless I can automate the generation of the items in the `afterInstall` hook for the "package" addon. Is that something I can do?

**Comment by ChrisHonniball** [comment]
I was topped off to use `this.addAddonToProject()` but it also doesn't give the host app the helpers for the included addons.

**Comment by gmurphey** [comment]
@ChrisHonniball `Blueprint.prototype.addAddonToProject` should add the specified addon to your app's `package.json` and run the addon's default blueprint. What are you having trouble accessing in your host app?

**Comment by stefanpenner** [comment]
> At that point I may as well just type ember install blah-blah-blah

this is how it works today?
