### ISSUE TITLE
parameterless helper used in ember-cli 0.2.7 running ember 1.13.2 fails

### ISSUE THREAD

**Issue by drewnichols** [ember-cli/ember-cli#4364]
I'm uncovered the following error when trying to upgrade our app to Ember 1.13.2. 
```Uncaught TypeError: Cannot read property 'match' of undefined```

It took me a while to narrow this issue down to the lack of parameters in my helper but here's how I reproduced it: 

 1  created a project with ```ember new```
 2  updated my package.json to the following devDependencies
```json
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.19.1",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2"
  }
```
 3  updated my bower.json to the following dependencies
```
  "dependencies": {
    "ember": "1.13.2",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.19.1",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1"
  }
```
4  ran `npm install` and `bower install` and started up the app with `ember s`

 *at this point the app runs and everything is cool*

5  ran `ember g helper my-helper`

 *we're still cool*

6  added the `{{my-helper}}` to `application.hbs`

*the app will now fail with:* ```Uncaught TypeError: Cannot read property 'match' of undefined```

7 When I then edit the tag to simply have a unused parameter such as `{{my-helper a='b'}} the app works fine again.

**Comment by drewnichols** [comment]
I dug into this a bit more and the error showing in the console links to [resolver#podBasedComponentsInSubdir](https//github.com/ember-cli/ember-resolver/blob/4130172d7ae06eaee25a43a0cd6873136a0f8e6f/dist/ember-resolver.js#L198) it seems that the value of `parsedName.fullNameWithoutType` is undefined.
```javascript
podBasedComponentsInSubdir: function(parsedName) {
    var podPrefix = this.namespace.podModulePrefix || this.namespace.modulePrefix;
    podPrefix = podPrefix + '/components';

    if (parsedName.type === 'component' || parsedName.fullNameWithoutType.match(/^components/)) {
        return this.podBasedLookupWithPrefix(podPrefix, parsedName);
    }
},
```
I tracked this further to the method [resolver#parseName](https://github.com/ember-cli/ember-resolver/blob/4130172d7ae06eaee25a43a0cd6873136a0f8e6f/dist/ember-resolver.js#L63) which is parsing a fullName of `helper:@content-helper`. The result of which leaves the key fullNameWithoutType undefined. 

```javascript
  function parseName(fullName) {
    /*jshint validthis:true */

    if (fullName.parsedName === true) { return fullName; }

    var prefixParts = fullName.split('@');
    var prefix;

    if (prefixParts.length === 2) {
      if (prefixParts[0].split(':')[0] === 'view') {
        prefixParts[0] = prefixParts[0].split(':')[1];
        prefixParts[1] = 'view:' + prefixParts[1];
      }

      prefix = prefixParts[0];
    }

    var nameParts = prefixParts[prefixParts.length - 1].split(":");
    var type = nameParts[0], fullNameWithoutType = nameParts[1];
    var name = fullNameWithoutType;
    var namespace = get(this, 'namespace');
    var root = namespace;

    return {
      parsedName: true,
      fullName: fullName,
      prefix: prefix || this.prefix({type: type}),
      type: type,
      fullNameWithoutType: fullNameWithoutType,
      name: name,
      root: root,
      resolveMethodName: "resolve" + classify(type)
    };
  }
```

**Comment by RuslanZavacky** [comment]
I have the same problem with the latest ember-cli and ember.

**Comment by jasonmit** [comment]
Seeing this as well

**Comment by stefanpenner** [comment]
This seems ember related, not ember-cli related.

**Comment by david-duncan** [comment]
Don't have anything to add other than I'm seeing this as well. Thanks for the info on it being a parameter-less helper. Going to go digging now.

**Comment by rwjblue** [comment]
Yes, it is a bug.  I kinda have a bead on it, and will try to update with more details soon...

**Comment by stefanpenner** [comment]
Seems to have gone stale, I suspect it has been resolved though.

If not, please provide a reproduction on master, and we can reopen/fix
