### ISSUE TITLE
Coverage flag in testem test_page config

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/ember-cli#4365]
ember-cli-blanket (and maybe others) trigger test coverage stats by adding the ?coverage query param to the test_page option in testem.json.  I would like to make this a CLI flag so I don't waste time in travis generating coverage a bunch of times when I only need it once.  In taking a look at what that would entail it looks like there are two paths:

1.  Add a test-page option to the ember test command which would override whatever was in testem.json
2.  Add a --coverage option which would append &coverage onto the existing test_page config in buildTestPageQueryString() with module and filter.

Any thoughts on this?  Preferred path?  Wouldn't be interested in merging so I should figure out another way?

cc @sglanzer

**Comment by sglanzer** [comment]
Of the two options described I like option 2 the best from a conceptual standpoint.  I doubt this is something ember-cli is going to want to add directly to the core, but maybe they would be comfortable with exposing a hook to capture cli options that could be passed to addons (such as ember-cli-blanket) which could then do the appropriate work.  Might even exist already and I'm just not aware of it.

cc @jschilli for comments

**Comment by jschilli** [comment]
@jrjohnson @sglanzer agree that option 2 is superior conceptually.

I currently use a 2nd testem.json file with the coverage option enabled and just run `ember test --config testem.cov.json`

which when aliased via my shell is super low friction

**Comment by jrjohnson** [comment]
fixed by #4377

**Comment by sglanzer** [comment]
@jrjohnson Good stuff, would you mind documenting this in the ember-cli-blanket readme?
