### ISSUE TITLE
wrong import line in adapter generator when using pods

### ISSUE THREAD

**Issue by shime** [ember-cli/ember-cli#4368]
this is the first line in generated adapter when using pods

```
import ApplicationAdapter from './application';
```

instead of

```
import ApplicationAdapter from '{application-name}/application/adapter';
```

**Comment by stefanpenner** [comment]
@trabus

**Comment by shime** [comment]
0.2.7

**Comment by stefanpenner** [comment]
mind confirming with master ? https://github.com/ember-cli/ember-cli#working-with-master

**Comment by trabus** [comment]
This is definitely still broken. The adapter tests for pods were [incorrect](https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/pods-generate-test.js#L1125), which is why it was passing. I'll get right on this.

**Comment by stefanpenner** [comment]
> I'll get right on this.

Thank you kindly.

**Comment by trabus** [comment]
So, looking at this, there are some questions that probably need answering before I proceed. 
We're generating adapters in pod structure with the assumption that: 
a. the application adapter has already been generated,
b. the application adapter is in pod structure. 

This complicates things quite a bit, especially in relation to generating the paths. I understand that extending from the application adapter as a base class is best practice, but the default app blueprint does not generate an application adapter by default.

So we have a couple options, as I see it. We could try and detect the existing application adapter, then generate a path to that, and if it doesn't exist, we can generate an application adapter along with the adapter that is extending it. The other option would be to abort and throw an error if the application adapter isn't detected, and recommend generating one first.

**Comment by stefanpenner** [comment]
seems to have gone stale, will likely be addressed as we refine pods/structures
