### ISSUE TITLE
JSHinting with addons not working as expected

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4371]
Hi,

trying to get `ember test` with jshint get to work with an addon I'm writing, I first found, that `app/\*\*`, `config/\*\*` as well as the `*.js` files in the main directory aren't covered by the automatically generated jshint test.

Next I tried to run jshint for myself (works as expected) and disable generated jshint test with

```
const app = new EmberAddon({
  hinting: false
});
```

With this option tests are no longer generated for `tests/\*\*` (as expected), but are still being generated for `addon/\*\*` (not as expected).

As far as I can see, the missing jshint tests for `app/\*\*` and the genration of test for `addon/\*\*` which should be disabled come from the special directory handling in addon and seem to be related. I would consider those a bug.

The missing tests for `config/\*\*` and `*.js` files in the main directory may be considered a feature, but I am missing an option (or documentation of said option if it exists) to add those files.

**Comment by Turbo87** [comment]
@jnfingerle is this still an issue with the latest releases of all the projects involved? I don't seem to have any of the problems you described.

**Comment by MiguelMadero** [comment]
I tried this with on 2.5.0. The behavior I see is still wrong, but a little bit different. When jshint is enabled, no tests are generated for the `app`, `config` or top level JS. When jshint is disabled, jshint tests are still being generated for `tests/`.

**Comment by rwjblue** [comment]
I need a demo repo for this, but I suspect that the issue @MiguelMadero was having is actually #5839. 

I'm closing this one as that issue has reproduction steps and is more actionable....

**Comment by MiguelMadero** [comment]
👍🏽
