### ISSUE TITLE
Support scoped addon names 

### ISSUE THREAD

**Issue by Fed03** [ember-cli/ember-cli#4372]
Scoped packages are not supported by ember-cli.  
When you create a new addon like this `ember addon @company/package-foo` an error comes out.

```
ENOENT, mkdir 'D:\Work\@company\package-foo'
Error: ENOENT, mkdir 'D:\Work\@company\package-foo'
    at Error (native)
```

I think the error comes from here https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/create-and-step-into-directory.js#L32

After this, I thought to create the addon in the common way and than change the package name in
- `package.json`
- `bower.json`
- `index.js`

sadly this didn't work either. This is the error after `ember serve`, and the modification of `index.js` is the culprit

```
ENOENT, no such file or directory 'D:\Work\package-foo\tmp\reexporter-tmp_cache_dir-qa23yYYW.tmp\reexports\@company\package-foo.js'
Error: ENOENT, no such file or directory 'D:\Work\package-foo\tmp\reexporter-tmp_cache_dir-qa23yYYW.tmp\reexports\@company\package-foo.js'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1103:15)
    at Reexporter.read (D:\Work\package-foo\node_modules\ember-cli\lib\utilities\reexport.js:30:6)
    at D:\Work\ocelot-user-addresses\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:79:23
    at lib$rsvp$$internal$$tryCatch (D:\Work\package-foo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Work\package-foo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:501:17)
    at D:\Work\package-foo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1095:13
    at lib$rsvp$asap$$flush (D:\Work\package-foo\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

I kept the name change only in `package.json` in order to publish to the private registry, but it's a half solution. `ember install @company/package-foo` does indeed work but, for example, the default blueprint does not run. Also the multiple `import` araound the application are not consistent.

If you need more test, don't be afraid to ask

**Comment by stefanpenner** [comment]
ya, we have fixed this in a prototype. Need to either backport it here, or finish the prototype :P

**Comment by Fed03** [comment]
good to hear you are on this :)

**Comment by gmurphey** [comment]
There is partial support for private modules introduced in #4271 (default blueprints and CLI generators work correctly), but it hasn't been released yet. Support for `ember addon @scope/addon-name` would be great, though.

**Comment by stefanpenner** [comment]
tracking this as part of the npm v3 upgrade

**Comment by nathanhammond** [comment]
Reopening as it was not addressed as part of npm 3 migration.

**Comment by GottfridL** [comment]
I would also like to be able to set private scope on my addons. Currently I need to run npm install separately before running ember install on my addon.
Would be great if this bug could be included in a milestone and fixed.

**Comment by ASH-Michael** [comment]
A workaround that I have found is to first `mkdir` the scoped folder.
`mkdir @company`
And then run your addon command as you usually would.
`ember addon @company/package-foo`
This correctly creates the addon and sets the addon name in `package.json` and `index.js`.

It will be nice to avoid this extra step though.

**Comment by rwjblue** [comment]
Hmm, we definitely should fix this, I don't fully grok the current state of issues but it seems like we can essentially dasherize the provided name to make sure we can create a local directory... 🤔 

Happy to try to help someone navigate this one...

**Comment by kellyselden** [comment]
This would also assist updating scoped addons here https://github.com/ember-cli/ember-cli-update/issues/464

**Comment by rwjblue** [comment]
TBH, we should probably close this issue and make specific issues for the remaining work items. This issue is very old and _most_ of the problems have been fixed already (making it quite hard to grok).

**Comment by rwjblue** [comment]
Went ahead and made a PR for it https://github.com/ember-cli/ember-cli/pull/8964

**Comment by locks** [comment]
As mentioned above, most work has been done and further improvements should be addressed specifically. Thanks for the discussion everyone!
