### ISSUE TITLE
Consider making 'standard' the default coding style

### ISSUE THREAD

**Issue by jonathanKingston** [ember-cli/ember-cli#4373]
I'm raising this because I wanted to know the response from the community of the following coding style.

Standard:
https://github.com/feross/standard

NPM appears to be adopting this now so I thought it would be worth raising the question.

Personally I'm not a fan of using `self` or missing `;`s however I know I am in a minority and willing to change my `eslint-config-ember` to match the styles used there whilst also keeping any Ember related fails excluded etc and perhaps stricter checking for Ember bad habits in the future.

Anyway... feel free to lynch me :D

**Comment by stefanpenner** [comment]
mega concerns, largely the ensuing religious war. Merely naming the religious persuasion `standard` does not solve the problem.

-------

My more detailed thoughts on the high level points.

> 2 spaces – for indentation

fine, but we already ship with `.editorconfig` I would prefer our generators would just respect the teams preference. Ultimately only project-wide consistency matters here.

> Single quotes for strings – except to avoid escaping

neutral point, although my personal prefer is in favor.

> No unused variables – this one catches tons of bugs!

:+1: are default linter already defines this.

> No semicolons – It's fine. Really!

Defaults will continue to use JS as it was intended – assume ASI is only for error correction. For those that wish to express them self creatively in other ways they can continue to

I have been contemplating adding postTemplate preRender transform hook for blueprints. To allow editorconfig space recasting. In theory, it would be used by ember-cli-asi to toggle the users preference.

> Never start a line with ( or [
> This is the only gotcha with omitting semicolons – automatically checked for you!

I am indifferent, only thing that comes to mind is in some situations you actually prefer declarationless array destructuring.

> More details
> Space after keywords if (condition) { ... }

:+1: 

> Space after function name function name (arg) { ... }

:-1: i personal prefer  (as does embers code base) `function name(arg) { }`

> Name the context variable self – var self = this

:-1: as `self` is the correct way to reference globalScope in both windowed and windowless browser contexts. We should due deligence to insure most code could concievable by run in workers (shared / basic / service)

> Always use === instead of == – but obj == null is allowed to check null || undefined.

> Always handle the node.js err function parameter

:+1: seems common sense, although typically we tend to prefer the promise variants.

> Always prefix browser globals with window – except document and navigator are okay
> Prevents accidental use of poorly-named browser globals like open, length, event, and name.

I actually like this, although it should be `self` not `window`. Again, think of the (Service|Web|Shared)Workers

**Comment by jonathanKingston** [comment]
@feross how much of a stumbling block is it to change `self` to another?

@stefanpenner sounds like your concerns match mine:
- space after fn
- asi
- self

Recasting sounds potentially something that would solve having repos like: https://github.com/jonathanKingston/ember-cli-mocha-assert which is just blueprints of ember-cli-mocha

**Comment by stefanpenner** [comment]
> Recasting sounds potentially something that would solve having repos like: https://github.com/jonathanKingston/ember-cli-mocha-assert which is just blueprints of ember-cli-mocha

potentially, although that feels like we want support for some matrix of blueprints depending on tools you have. Although maybe qunit tests can just be transformed to mocha without issue. This would prevent maintaining many on-disk pieces.

**Comment by stefanpenner** [comment]
> @stefanpenner sounds like your concerns match mine:
> 
> space after fn
> asi
> self

:

**Comment by jonathanKingston** [comment]
>Merely naming the religious persuasion standard does not solve the problem.

Hah, yeah at least I was clear with one of mine :goberserk: 
https://github.com/jonathanKingston/eslint-config-nightmare-mode

My aim with [this Ember version](https://github.com/jonathanKingston/eslint-config-ember) is to come to some sort of resolution here and it be 'standard-ish' for Ember. The nice thing about having the default is you can completely override it.

> potentially, although that feels like we want support for some matrix of blueprints depending on tools you have. Although maybe qunit tests can just be transformed to mocha without issue. This would prevent maintaining many on-disk pieces.

Yeah potentially, however it seems like it might be a fairly easy transform. However not sure.
It does however mean keeping each blueprint up to date in separate repos is a nightmare.

**Comment by stefanpenner** [comment]
> Yeah potentially, however it seems like it might be a fairly easy transform. However not sure.
> It does however mean keeping each blueprint up to date in separate repos is a nightmare.

Yes it may, i suspect a good test suite would be sufficient to ensure healthy transforms.

**Comment by feross** [comment]
@jonathanKingston

> @feross how much of a stumbling block is it to change self to another?

This rule hasn't been enforced for a while. Just updated the readme to reflect reality. Thanks for the question, and sorry for the confusion.

**Comment by feross** [comment]
You might consider [semistandard](https://github.com/Flet/semistandard) if the "no semis" rule is a blocker.

**Comment by stefanpenner** [comment]
Interesting

**Comment by btecu** [comment]
Why can't we adopt `ember` style? It would be less confusing.

**Comment by jonathanKingston** [comment]
Sorry missed these responses until now.

@feross I had not seen semistandard, thanks. Also the web worker section is still there.
Setting a consistent-this rule is worthwhile I feel just self is mostly problematic. http://eslint.org/docs/rules/consistent-this

@btecu that is the intent of what I started here: https://github.com/jonathanKingston/eslint-config-ember at least eventually libraries could adopts ESLint and extend from this; including the library source itself.

**Comment by devinus** [comment]
This is a much better ES6 ready style guide that is very close to what I see in `ember-cli` apps already: https://github.com/airbnb/javascript

**Comment by IanVS** [comment]
Something we are working on in ESLint is an "auto-configure" feature, which will examine an existing project and determine the rule settings which most closely match what's already being used.  It's not ready yet, but if there's interest here in something like that I can step up the effort on it.
