### ISSUE TITLE
ENOTEMPTY tree_merger-temp_dest_dir on almost every compile, 30 sec build time on Windows

### ISSUE THREAD

**Issue by blisst** [ember-cli/ember-cli#4375]
I am on Windows 7, `ember-cli 0.2.7`
I am also running `nvm` to quick switch between Node versions, currently `v0.12.2`
 
I have taken all the precautions related to getting rid of Broccoli compilation errors:
--no Sublime Text `tmp` monitoring
--ember-cli-windows
--antivirus not scanning folders
--Windows Defender, Windows search disabled in those folders
--only one CMD window open to my project root at a time
--reinitialized project (removed `tmp`,`node_modules`,`bower_components`, reinstalled everything according to Ember-CLI upgrade procedure

However, I still get `ENOTEMPTY tree_merger-temp_dest_dir...` errors every time, and compilation of my app takes 30 seconds.  

One answer I might have is that, while `mklink` works find for making symlinks in an Admin window for me, npm's `can-symlink` says that I am unable to make symlinks.  Could this be related?

**Comment by stefanpenner** [comment]
Yes it is related to not making symlinks. This is broccoli issue. Be sure to open on issue on the correct repo.

**Comment by blisst** [comment]
Thanks @stefanpenner!  I'm not sure which broccolli module is the issue.  Is it a broccoli-merge-trees issue?

**Comment by stefanpenner** [comment]
@blisst likely just the main broccoli one?

**Comment by blisst** [comment]
Ok I mostly fixed the issue by updating the `quick-temp` > ``rimraf`dependency to `^2.3.2`.  Still not getting symlinks....

**Comment by stefanpenner** [comment]
> Still not getting symlinks....

maybe windows 7 doesn't have them, i can't remember.  The microsoft folks are using ember-cli themselves on various projects without problems, but maybe windows 8+?

**Comment by blisst** [comment]
Thanks again for getting back to me.  

Yes this is what's so frustrating about this, is I know that symlinks *do* work on Windows 7, because they used to work in earlier versions of ember-cli on my computer!  

I'm wondering if this is somehow due to my Node.js installation using nvm....

**Comment by stefanpenner** [comment]
https://github.com/broccolijs/node-symlink-or-copy

**Comment by stefanpenner** [comment]
pulling in @felixrieseberg our favoriate MS OSS evangelist, and the author of the windows addon. Maybe he has some ideas.

**Comment by blisst** [comment]
Yes, so I don't understand how Windows people are getting that to work since it expressly says that it is *not* using symlinking on windows

**Comment by felixrieseberg** [comment]
Huh, looking at the source code, it's pretty obvious that we're never getting symlinks on Windows. I had real and measurable performance gain with elevated prompts and attributed that to symlinks, but I guess it was something else.

That being said, we do have a bunch of Ember and usually have build times around 15 seconds for smaller projects. I'm not sure if there is something we can do here, though - I'd love to improve the node package, but my plate is a little bit too full for that :/

**Comment by blisst** [comment]
Thanks very much @felixrieseberg !  

I was pretty sure that symlinks were working for me at some point (since the icon for a symlink is like that of a shortcut rather than a folder), but then again maybe not.  I smell something fishy.

Appreciate your help!

**Comment by stefanpenner** [comment]
> it's pretty obvious that we're never getting symlinks on Windows

this sounds like good news, it sounds like it can be fixed. I know for a fact in the past i had a clients windows project (quite a substantial app) down from 1.5 minutes to 2 or 3 seconds.

**Comment by blisst** [comment]
Workaround, and the only workaround I can find:

https://github.com/jvtrigueros/ember-vagrant

Build times down from ~1 minute to *5 seconds!!!!!!!!!*

The only thing to change is make line 7 in `provision.sh` 
```
curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
```
to install Node 0.12.x.  
I also added some config options which might have helped with my VM's network connection and potentially helped with compile speed/symlinking for VirtualBox :


`Vagrantfile`:
```
config.vm.provider "virtualbox" do |vb|
    #...
    # Fix network connection slowness
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    
    #Fix possible symlinking problem with VirtualBox
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant","1"]
end
```

**Comment by stefanpenner** [comment]
this still seems funky, will investigate when i test out the latest perf work on the windows.

**Comment by stefanpenner** [comment]
> npm's can-symlink says that I am unable to make symlinks. Could this be related?

this really seems like the problem, have you followed the steps outlined on the site?

**Comment by blisst** [comment]
What site are you referring to?  
I run Git Bash or CMD as an Admin and have used ember-cli-windows, i.e. nothing is scanning my `tmp` folders

**Comment by stefanpenner** [comment]
The embercli site includes instructions to enable symlinks.

Are you on ssd or hdd

**Comment by blisst** [comment]
That link http://www.ember-cli.com/#symlinks-on-windows is broken..

I am sure I followed it when it was there.

I'm on an SSD

**Comment by stefanpenner** [comment]
latest merge-trees takes a dramatically different approach, reducing IO dramatically on rebuilds. I suspect this is resolved
