### ISSUE TITLE
Extending routes in addon

### ISSUE THREAD

**Issue by rollick** [ember-cli/ember-cli#4380]
In an addon we are initializing some additional routes. Usually this works when the page loads but occasionally the new routes don't load before the templates are parsed. As a result the link-to helper for the 'about' route will complain that the route doesn't exist. This is what we have in the addon initializer: 

https://gist.github.com/rollick/8c0e5145404a9372129a

Should this work? Are we using the wrong 'before' hook? What is the preferred way to extend routes from an addon?

**Comment by stefanpenner** [comment]
typically we recommend people import from router.js

```
import myRoutes from 'my-addon/additional-routes';
...
Router.map(function() {
  myRoutes(this);
});
...
```

**Comment by stefanpenner** [comment]
Note: this also seems like a StackOverflow question and not a bug.

**Comment by rollick** [comment]
@stefanpenner thanks for the response. We are doing per-tenant builds with each tenant defined in an ember-cli addon so was hoping there was a way to do this in an initializer. Will look to StackOverflow for more help.
