### ISSUE TITLE
ES2015 re-export shorthand doesn't get transpiled into ES3 safe code

### ISSUE THREAD

**Issue by XrXr** [ember-cli/ember-cli#4383]
1. make sure ember-cli 0.2.7 is installed
2. run `mkdir foo && cd foo && ember init`
3. change the last line of `app/app.js` from `export default App;` into `export { default } from 'ember';`
4. run `ember build`

Line 21 of `dist/assets/foo.js` is `exports.default = Ember.default;`, when it should be
`exports['default'] = Ember['default'];`

This bug is preventing us from upgrading `ember-wormhole` to 0.3.2, since it uses this syntax and we have to support IE8 :(

**Comment by stefanpenner** [comment]
Feel free to run your code through es3-safe-recast

**Comment by stefanpenner** [comment]
can you try running against: https://github.com/ember-cli/ember-cli/#working-with-master i believe the latest esperanto (which it contains) should fix the problem. Alternatively, you can just go into your node_modules and switch the esperanto version, and report back.

**Comment by XrXr** [comment]
Just tried with `0.2.7-master-c79fa75e29`. Same thing happens
