### ISSUE TITLE
Is there any way of preventing "use strict" appearing in every module?

### ISSUE THREAD

**Issue by andrewjmc** [ember-cli/ember-cli#4389]
I am porting an ember-rails project to ember-cli. I am getting errors for thousands of variables which were never declared, and note that 'use strict' is included in every compiled module.

Is there any way of preventing this to enable me to deal with other, more critical, issues first?

Thanks,

Andrew

**Comment by stefanpenner** [comment]
This is a question better asked on stackoverflow. As it does not appear like a bug

**Comment by andrewjmc** [comment]
Good point!
