### ISSUE TITLE
Error in Webstorm in app.js in line import config from './config/environment';

### ISSUE THREAD

**Issue by Redigast13** [ember-cli/ember-cli#4394]
I created an application using ember new applicationname
And I created a project in Webstorm. Webstorm noticed that it can't resolve directory 'config' and file 'environment' in this code:
import config from './config/environment';
file applicationname/app.js

The application works fine, but why webstorm thinks that  './config/environment' is incorrect path. I tried to change it to '../config/environment' webstorm thinks that it is correct path but then the application doesn't work.

**Comment by stefanpenner** [comment]
Because that module is generated for the app at build.
