### ISSUE TITLE
Generator for routes that does not mutate route.js

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#4396]
At the moment there doesn't seem to be a way to generate a `route.js` file without also adding a `this.route` to the `router.js` file.
@trabus mentioned that he might be open to adding a flag for this behaviour.

**Comment by stefanpenner** [comment]
I'm curious why this is needed?

**Comment by sivakumar-kailasam** [comment]
Adding my 2 cents.

I have some nested routes which are repeated under two different top level routes. So now I have those common routes into a separate function and reusing them. Whenever `router.js` is mutated my changes goes for a toss. So this flag would helpful in cases like mine.

**Comment by stefanpenner** [comment]
That sounds like a bug in the route generation. Please report it.

Cc @abuiles

**Comment by abuiles** [comment]
Not really a bug on the router generator, we only need a flag  https://github.com/ember-cli/ember-cli/blob/master/blueprints/route/index.js#L63 so router.js is not touched. maybe `--skip-route` ?  should be easy to add if someone wants to give it a go, otherwise I can look at it later today.

**Comment by sivakumar-kailasam** [comment]
@abuiles hope you meant `--skip-router` :smile: Submitted a PR for this.
