### ISSUE TITLE
simultaneous ember apps being served using --port broken on 1.13.1

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#4403]
firing up 2 ember apps simultaneous now seems to be broken using --port (i believe this is related https://github.com/ember-cli/ember-cli/pull/4292/files) 

```

iMac:app1 JoshuaCope$ ember serve
version: 1.13.1
Livereload server on http://localhost:35729
Serving on http://localhost:4200/test/

iMac:app2 JoshuaCope$ ember serve --port 8080 
version: 1.13.1
Livereload failed on http://localhost:35729.  It is either in use or you do not have permission.

```

changing the live-reload-port works but the description seems incorrect, default needs to add port number using dynamic variable

```
ember serve --port 8080 --live-reload-port 35735
```

```
name: 'live-reload-port', default: 35729, type: Number, description: '(Defaults to port number + 31529)', aliases: ['lrp']
```

https://github.com/ember-cli/ember-cli/blob/master/lib/commands/serve.js

**Comment by stefanpenner** [comment]
Can confirm

**Comment by eccegordo** [comment]
Would it be possible to have a mode where ember cli auto generates a different port number for server and live reload if existing processes are detected? Perhaps just pick a random or incrementing number in the 49152–65535 range.

Per wikipedia:
> The range 49152–65535 (215+214 to 216−1) contains dynamic or private ports that cannot be registered with IANA.[175] This range is used for private, or customized services or temporary purposes and for automatic allocation of ephemeral ports. 

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Dynamic.2C_private_or_ephemeral_ports

**Comment by stefanpenner** [comment]
@eccegordo although this seems like a good step. It is possible for us to remove the port entirely by multi-plexing the WS from live-reload over the same HTTP port the index

**Comment by stefanpenner** [comment]
> Perhaps just pick a random or incrementing number in the 49152–65535 range.

this may still be a good interim step.

**Comment by eccegordo** [comment]
Yes, did not know about the multi-plexing. That would be cool.

But also just to be clear I am also talking about the case where you have two apps being served. Typically an app and a separate addon being worked on simultaneously.

App A --> port 4200
Launch App B --> automatically goes to port 49152
Launch App C --> automatically goes to port 49153
etc...

Does multi-plexing solve this case? Seems complicated.

I promise not run more than 65,535 instances of ember serve if that helps. :smile:

**Comment by stefanpenner** [comment]
> Does multi-plexing solve this case? Seems complicated.

its built into websockets + http, basically if the connection is upgraded (for ws) pass it to the live-reload server, otherwise process it normally.

> Does multi-plexing solve this case? Seems complicated.

yes, as it would just share the same port as HTTP

**Comment by stefanpenner** [comment]
> But also just to be clear I am also talking about the case where you have two apps being served. Typically an app and a separate addon being worked on simultaneously.
> 
> App A --> port 4200
> Launch App B --> automatically goes to port 49152
> Launch App C --> automatically goes to port 49153
> etc...

yup, i get it.

**Comment by stefanpenner** [comment]
Seems like you solution would be simple to implement, as it would require no changes to live-reload at all.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/issues/4350
