### ISSUE TITLE
Generating routes with `--dummy` does not update `tests/dummy/app/router.js`

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#4404]
Because the dummy folder is contained in an addon, the `router.js` is currently not updated when generating a new route inside a dummy app. We should account for this by checking for the dummy flag [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/route/index.js#L63) and [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/route/index.js#L76)

**Comment by QuantumInformation** [comment]
thanks, I have also this need.

**Comment by gmurphey** [comment]
I could use this. I'll work on putting together a PR tonight.
