### ISSUE TITLE
brocfile transition guide needs more clarification

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#4412]
It is not explicitly clear that you should remove Brocfile.js after `ember-cli-build.js` is added. Perhaps add a line to TRANSITION.md

> After moving your Brocfile.js contents to ember-cli-build.js please delete your Brocfile.js file.

Ideally, it would be nice to have a deprecation or warning thrown on bootup that detects the presence of both files and makes reference to the transition guide.

This came up for me when I ran init on an addon I was working on and that created the `ember-cli-build.js` but didn't touch `Brocfile.js`. I am not sure I would expect the init process to delete the Brocfile.js but probably should not be kept around either.

**Comment by stefanpenner** [comment]
diuplicate

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/issues/4410

**Comment by stefanpenner** [comment]
> Ideally, it would be nice to have a deprecation or warning thrown on bootup that detects the presence of both files and makes reference to the transition guide.

absolutely, transposed to the other issue
