### ISSUE TITLE
Growing/very large tmp folder

### ISSUE THREAD

**Issue by Eptis** [ember-cli/ember-cli#4418]
Just noticed this recently, but the `tmp` folder keeps growing and growing during development and is never really automatically emptied. For me this resulted in a folder the size of 26gb. Is this normal or is something else going on?

**Comment by Kuzirashi** [comment]
They said they'll use system temp folder instead of local /tmp directory in future. For now, I guess, you just have to delete it once in a while, for example, when you update to the newest version of Ember CLI.

**Comment by Eptis** [comment]
:+1: thanks for the answer!

**Comment by stefanpenner** [comment]
> For me this resulted in a folder the size of 26gb. Is this normal or is something else going on?

that is impressive.

there are several things at play:

1. there exists some leaks, for example broccoli-filter (I have a WIP fix https://github.com/caitp/cauliflower-filter/pull/14) which will end up in broccoli-filter
2. If the CLI crashes or the the ctrl-c, node/javascript existing `finally` and `promise.finally` semantics will just be lost. Before someone recommends we should just prune `tmp` on start, that is currently not great idea, as people often keep there server running, which running other tasks (like tests). In theory, we can do something here re: staleness, but that is a bit off in the future
3. we are pending the final form of the new broccoli plugin API, that enforces broccoli provided input/output dirs, this will enable `tmp` directory to live in system tmp. In theory preventing more issues.

**Comment by stefanpenner** [comment]
> there exists some leaks, for example broccoli-filter (I have a WIP fix caitp/cauliflower-filter#14) which will end up in broccoli-filter

is merged, but still needs to become broccoli-filter. Hopefully that will happen this week.

After that, there are some issues likely with caching-writer that need to be addressed.

**Comment by stefanpenner** [comment]
many upstream fixes, we will continue to work on it as we discover more specific scenarios.

Please note, if you hard quit CLI, you will prevent node from doing async work (like cleanup).
