### ISSUE TITLE
ember-cli@1.13.x doesn't working

### ISSUE THREAD

**Issue by imaxhung** [ember-cli/ember-cli#4431]
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/tmp/millis-test-sync'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at hasMillisResSync (/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra/lib/util/utimes.js:11:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra/lib/util/utimes.js:4:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Just update from 0.2.7
Run ember command , then show this error.
What should i do?

**Comment by joostdevries** [comment]
have you tried completely clearing out node_modules and bower_components?

**Comment by imaxhung** [comment]
I think that it is not about node_modules or bower_components. BecauseI have no any ember-app.
I just can not run ember command.
like:
ember -v
ember new
...

**Comment by joostdevries** [comment]
If you used `ember update`, try `npm install -g ember-cli@1.13.1` instead. We've just [nuked `ember update`](https://github.com/ember-cli/ember-cli/pulls/4419)

**Comment by imaxhung** [comment]
I never used ember update. Always use npm install -g ember-cli@xxx.
By the way, I have both a remote server and a local vitual server getting this error.
But back to 0.2.7, everything is fine.

**Comment by joostdevries** [comment]
This is a dep problem from the look of it https://github.com/jprichardson/node-fs-extra/issues/149

**Comment by joostdevries** [comment]
Are you running multiple `ember` commands at the same time?

**Comment by imaxhung** [comment]
Done!
It is a problem of fs-extra like you say, I just update it to 0.22.1 manually.Then ember can run without this error.
But weirdly, do other people never get this error? Just me?
@joostdevries Thank you so much for your quickly response.

**Comment by piotrpalek** [comment]
@imaxhung how did you update it manually? I got the same problem, did you list it in the dependencies or just copied it into node_modules?

**Comment by imaxhung** [comment]
@piotrpalek Go to the ember-cli folder(both global and app's), then just use
npm install fs-extra@0.22.1 --save

**Comment by piotrpalek** [comment]
@imaxhung thanks yeah that is what I was doing, was just curious if you somehow specified the dependency version in package.json or something :) thanks
