### ISSUE TITLE
User supplied options don't get merged into defaults with the new ember-cli-build

### ISSUE THREAD

**Issue by martndemus** [ember-cli/ember-cli#4434]
```js
  var app = new EmberApp(defaults, {
    babel: {
      optional: ['es7.decorators']
    }
  });

  console.log(app.options.babel);
```

```
=>  { plugins: [ [Function] ] } }
```

Currently i workaround by doing
```js
defaults.babel = { optional: ['es7.decorators'] };
var app = new EmberApp(defaults);
```

**Comment by rwjblue** [comment]
My guess is that these are not deeply merged. Definitely a bug, thanks for reporting!

**Comment by stefanpenner** [comment]
cc @chadhietala I think `defaults` doesn't deep merge here. I mentioned it in your earlier (like 3 minutes ago PR)

**Comment by rwjblue** [comment]
Copied over from https://github.com/ember-cli/ember-cli/pull/4440/files#r34471644:

We use a slightly different pattern in ember-app for deeply merged values ([see here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L199-L212)), which is something like:

```javascript
var defaults      = require('lodash/object/defaults');
var merge         = require('lodash/object/merge');

options = merge({}, args, defaults);
```

`merge` takes a "customizer" ([see here](https://lodash.com/docs#merge)) that we use as the standard `defaults`.  This lets us handle defaults at the second levels, but if we want to fully merge at all depths we will need to write our own customizer function.

**Comment by rwjblue** [comment]
We need to decide how deeply we want to merge though, given the following objects?

```javascript
var a = {
  someAddon: {
    configA: 'asdf',
    configB: 'hjkl'
  },
  listOfThings: [ 'a', 'b', 'c'],
  objectsWithArrays: {
    thingA: [ 'foo', 'bar' ]
  }
};

var b = {
  someAddon: {
    configC: 'yuio'
  },
  listOfThings: [ 'd', 'e', 'f' ],
  objectsWithArrays: {
    thingA: [ 'baz', 'qux' ]
  }
};

var app = new EmberApp(a, b);
```

What should the final options be?

**Comment by martndemus** [comment]
Rightside wins, treat an array as primitive.

```js
{
  someAddon: {
    configA: 'asdf',
    configB: 'hjkl',
    configC: 'yuio'
  },
  listOfThings: [ 'd', 'e', 'f' ],
  objectsWithArrays: {
    thingA: [ 'baz', 'qux' ]
  }
}
```
