### ISSUE TITLE
Test of newly generated addon component test breaks with ember 2.0.0-beta.2

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4439]
I'm on windows, following those steps:

* Generate new addon
* Generate new component in said addon (so far see #4436)
* Move ember-cli-handlebars in `package.json` from *devDependencies* to *dependencies*
* Change `bower.json` to use 2.0.0-beta.2 and `bower install`
* Run tests

I get the following Error message: 

```
not ok 25 PhantomJS 2.0 - TestLoader Failures: dummy/tests/unit/components/hilfe
-anzeige-test: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1     at moduleLoadFailure (http://localhost:7357/asse
ts/test-support.js:5626:15)
                at require (http://localhost:7357/assets/test-loader.js:31:31)
                at loadModules (http://localhost:7357/assets/test-loader.js:21:2
5)
                at load (http://localhost:7357/assets/test-loader.js:40:35)
                at http://localhost:7357/assets/test-support.js:5635:20: Could n
ot find module `victors-ember-gui-komponenten/components/hilfe-anzeige/component
` imported from `dummy/components/hilfe-anzeige`
        Log: >
    ...
ok 26 PhantomJS 2.0 - JSHint - unit/components: unit/components/hilfe-anzeige-te
st.js should pass jshint
not ok 27 PhantomJS 2.0 - TestLoader Failures: dummy/tests/unit/helpers/throw-te
st: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1     at moduleLoadFailure (http://localhost:7357/asse
ts/test-support.js:5626:15)
                at require (http://localhost:7357/assets/test-loader.js:31:31)
                at loadModules (http://localhost:7357/assets/test-loader.js:21:2
5)
                at load (http://localhost:7357/assets/test-loader.js:40:35)
                at http://localhost:7357/assets/test-support.js:5635:20: Could n
ot find module `victors-ember-gui-komponenten/helpers/throw` imported from `dumm
y/helpers/throw`
        Log: >
    ...
```

I don't know if this is a problem with me, with ember or with ember-cli.

**Comment by rwjblue** [comment]
You need to use `ember-data` canary version with Ember 2.0.0-beta.2.

---

The error messages about missing modules, are caused by an error loading the `vendor.js` file. If you open the app in the browser, you should see an error (most likely about `ArrayPolyfills` missing) before these tests fail. The errors printed to the console are not terribly helpful, I wonder if we can do anything about parse errors with Testem.

**Comment by jnfingerle** [comment]
Thanks, it works with canary as you said. I don't close this ticket so that it can be used to track enhancements to the error messages, but feel free to close it anyway if you want to do this differently.

**Comment by stefanpenner** [comment]
I would love to improve these error messages, but it isn't entirely obvious to me how to improve them. Maybe someone can noodle on this?

**Comment by rwjblue** [comment]
@stefanpenner - We might be able to load `testem.js` earlier (before `vendor.js`) [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/index.html#L27).  That might expose any errors thrown from parsing `vendor.js` to the testem console.  I'll test locally...

**Comment by stefanpenner** [comment]
@rwjblue we will have to move qunit/mocha out of vendor then, since they need to be loaded before testem.js. (not that that is a bad idea)

**Comment by stefanpenner** [comment]
ember 2x appears to work fine for us, i suspect this is no longer an issue.
