### ISSUE TITLE
lintTree breaks if tests have ES6 syntax

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli#4442]
If you use the lintTree hook AND have ES6 syntax in a test, you get an error. I was able to reproduce this in an [example repo](https://github.com/asakusuma/lint-tree-bug).

If you remove the [ES6 syntax](https://github.com/asakusuma/lint-tree-bug/commit/c9f9e7c14350f90f0a5b0ee4dc5b88a06350f083#diff-9dce93609d638e96ada5768da1896becR8) or remove the [lintTree hook](https://github.com/asakusuma/lint-tree-bug/commit/c9f9e7c14350f90f0a5b0ee4dc5b88a06350f083#diff-168726dbe96b3ce427e7fedce31bb0bcR6), it works fine.

```
not ok 1 PhantomJS 2.0 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Use of reserved word 'let' in strict mode
        Log: >
    ...

1..1
# tests 1
# pass  0
# fail  1
```

**Comment by chadhietala** [comment]
@asakusuma Did you try running your addon after ember-cli-babel?

**Comment by asakusuma** [comment]
@chadhietala still breaks. You're talking about doing this right?

```
"ember-addon": {
  "after": [
    "ember-cli-babel"
  ]
}
```

It also only fails for the test tree. If you put ES6 syntax in the addon or app it's fine.

**Comment by chadhietala** [comment]
Yea

**Comment by asakusuma** [comment]
So this is happening because ember-cli is assuming that test code you generate in this hook is ES5.

For instance, in broccoli-jshint, it remaps every file to a JSHint test. The JShint test code is ES5: https://github.com/rwjblue/broccoli-jshint/blob/master/index.js#L96

If you add any ES6 syntax code to this generated test, it breaks. I think the solution is to just document in the https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md file that the resulting tree must be a set of ES5 tests. I'll submit a PR to do this and then I'll close the ticket.

**Comment by stefanpenner** [comment]
@asakusuma sorry for letting this linger, is this still an issue?

**Comment by asakusuma** [comment]
@stefanpenner not an issue for me any longer. I just didn't realize that test code generated in the hook must be ES5.
