### ISSUE TITLE
1.13.0 does not concatenate files located at vendor/

### ISSUE THREAD

**Issue by givanse** [ember-cli/ember-cli#4446]
Say you have this file:

    vendor/fontello/css/fontello.css

You add it in your Brocfile like this:

    app.import('vendor/fontello/css/fontello.css');

And when you build the app, the contents of the file will be missing from `vendor.css`.

This was working with `0.2.7`.

**Comment by gmurphey** [comment]
I wasn't able to reproduce this. I think it may be an issue of transitioning the `app.import` from `Brocfile.js` to `ember-cli-build.js`?

https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md

**Comment by timkellogg** [comment]
I was having a similar issue but migrating Brocfile seemed to have solved it.

**Comment by stefanpenner** [comment]
on that note, i will close this. If the problem, post transition still appears we can reopen.

**Comment by givanse** [comment]
False alarm, I never noticed the new file. I migrated the configs and all is good, thanks!
