### ISSUE TITLE
switch from Brocfile.js to ember-cli-build.js not clear enough

### ISSUE THREAD

**Issue by justin-hackin** [ember-cli/ember-cli#4450]
So, in upgrading ember-cli, I couldn't figure out why none of my imports were defined.  After a long time of investigating, I realized that my Brocfile.js was no longer being used, doh !  I would strongly recommend that if a Brocfile.js exists upon build, that ember cli has a big warning after the build completes suggesting that "your old configuration from Brocfile.js may not be in use.  Transfer Brocfile.js contents into ember-cli-build.js and remove Brocfile.js from your project's root directory to prevent future appearances of this warning" .... or do you think I just wasn't careful enough ?  I know one of those release notes mentioned it ... but seemed a bit hidden.

**Comment by stefanpenner** [comment]
there should also be a link to this article: https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md#brocfile-transition

**Comment by stefanpenner** [comment]
the deprecation does in-fact have this: https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L26-L34

**Comment by gmurphey** [comment]
The deprecation doesn't seem to catch the case where both `Brocfile.js` and `ember-cli-build.js` exists. Should it? I know this has tripped up a few people upgrading from 0.2.7 to 1.13.

**Comment by atsjj** [comment]
@gmurphey ran into this yesterday on Slack, helping someone resolve the exact scenario you describe.

**Comment by stefanpenner** [comment]
Seems like we are missing a scenario. I'm currently working on a talk so I can't investigate, but would accept a or that fixes it. We can cut a new release in the next day

**Comment by gmurphey** [comment]
Working on a fix now!

**Comment by stefanpenner** [comment]
@gmurphey :+1: thank you kindly

**Comment by atsjj** [comment]
:+1:

**Comment by justin-hackin** [comment]
Thanks for acknowledging and working to fix this issue :+1:
