### ISSUE TITLE
[Proposal] import alias like webpack

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli#4453]
Webpack offers a very powerful alias feature which may be really useful to be in ember-cli, see http://webpack.github.io/docs/configuration.html#resolve-alias

So instead of 
`import Something from '../../../models/Something' `
to:
`import Something from 'models/Something'` given models is an alias for `app/models` for example.

**Comment by stefanpenner** [comment]
You can do appname/models/thing.js

**Comment by mmahalwy** [comment]
No, it doesn't but I wasn't even aware I can do `appname`! Thanks @stefanpenner

**Comment by stefanpenner** [comment]
I like the web pack alias idea. I've thought of adding it before, but was worried about extra collisions or shadowing it introduces

**Comment by mmahalwy** [comment]
@stefanpenner mmhm, I am with you. I think the appname suffices :)
