### ISSUE TITLE
[BUG] treeForAddon hook excluding files

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#4463]
I've been working on developing addons recently, and came across what seems to be a bug.

Essentially, if `treeForAddon` in `index.js` is not defined (or commented/deleted), then the modules in the addon directory are properly include into `vendor.js`. However, if the function is defined, then the modules are totally excluded, even if the function is a no-op.

The cause seems to be that the files get a `modules/<app-name>` namespace applied to them normally. This doesn't happen if you overwrite the function. I think this has to do with addons having a `treeForAddon` function by default, and losing that behavior when defining a custom one.

I put together a simple [repro repo here](https://github.com/trentmwillis/tree-for-addon-derp).

/cc @chadhietala

**Comment by stefanpenner** [comment]
> if you overwrite the function.

when refining the function are you calling super?

**Comment by trentmwillis** [comment]
Should I? I haven't seen that for the other "treeFor" functions. Seems that behavior ought to be consistent across.

**Comment by stefanpenner** [comment]
> Essentially, if treeForAddon in index.js is not defined (or commented/deleted), then the modules in the addon directory are properly include into vendor.js.

> However, if the function is defined, then the modules are totally excluded, even if the function is a no-op.

these two statements indicate there is some default behavior you are wanted to preserve in the "no-op" case. This leads me to believe super is required

**Comment by stefanpenner** [comment]
for example, the default implementation of `treeForAddon` https://github.com/ember-cli/ember-cli/blob/89b36d7d73c362745212d6d4533e3832aee4a10f/lib/models/addon.js#L370-L389

if you "do nothing" this will be skipped.

**Comment by trentmwillis** [comment]
Guess I was a bit unclear with my usage of "no-op". What I meant is that in the [addon hooks documentation](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#treefor-cont) I get the impression that if I defined `treeForAddon` as:

```javascript
treeForAddon: function(tree) {
  return tree;
}
```

Then it should work as if I hadn't changed anything (since if I do the same thing for `treeForApp`, that is the behavior), but instead it filters out all the files in the addon directory.

If super is needed to be called, then should a special note be made for `treeForAddon` as opposed to the other `treeFor` methods?

**Comment by stefanpenner** [comment]
> If super is needed to be called, then should a special note be made for treeForAddon as opposed to the other treeFor methods?

super is always needed if you you want to refine default functionality, but want to deserve some aspects of it.

**Comment by trentmwillis** [comment]
Okay, I think I'll add a bit of documentation stating something to that effect as well as denoting which `treeFor` methods have default functionality, since not all of them do (looks to be only `treeForPublic` and `treeForAddon`). Which I guess is what confused me about this whole thing, I expected them all to not have any default behavior.

**Comment by stefanpenner** [comment]
> denoting which treeFor methods have default functionality,

sounds great!

**Comment by stefanpenner** [comment]
> since not all of them do (looks to be only treeForPublic and treeForAddon).

they may in the future. In all cases, when one overrides a parent classes method, regardless if its a noop or not, you should call super if you ever want the default functionality.

**Comment by chadhietala** [comment]
Yes this is confusing, please PR @trentmwillis. :smile: We need better documentation of "optional" methods and methods that have a default implementation that you can add to.

**Comment by jasonmit** [comment]
I believe the issue is that the `tree` isn't actually a tree object like the other treeFor hooks.  It's a string path to the addon directory, so you need to call super on it which will return the tree object, which is then safe to returns.

```js
treeForAddon: function() {
  var tree = this._super.treeForAddon.apply(this, arguments);
  // do things on the tree.. just note the shape of the tree is also a little strange
  // in that the files for the addon are within `/modules/<addon-name>/`
  // where I would have expected the root of the tree to be `/modules/<addon-name>`
  return tree;
}
```

**Comment by sglanzer** [comment]
@jasonmit Thanks for this comment, definitely not intuitive

**Comment by stefanpenner** [comment]
> @jasonmit Thanks for this comment, definitely not intuitive

new core_object, has a better super. pending -> https://github.com/ember-cli/ember-cli/pull/3056

**Comment by sglanzer** [comment]
@stefanpenner Will #3506 also use an actual tree object in the treeForAddon parameters?  Even with the super call I still can't do a tree merge with new files afterward because the addon processing does additional stuff (like modifying the registry).  Ideally I'd like to be able to manipulate the tree prior to to calling super, passing the modified tree (I guess)
