### ISSUE TITLE
Test Helpers Not Registered in Unit Tests

### ISSUE THREAD

**Issue by spinlock99** [ember-cli/ember-cli#4464]
This is happening with the ember-cli-mocha addon from switchfly, I haven't looked into reproducing it with plain vanilla qunit tests.

I'm trying to write a helper function for my tests that will be used in almost every test. So, I'd like to register it globally once rather than in every test I'm upgrading to ember-cli. The [docs](http://www.ember-cli.com/user-guide/#writing-your-own-test-helpers) say I should register my helpers in `start-app.js` to be able to use them with ember-cli (please let me know if I'm misinterpreting this). But, when I try to run my specs, I still need to import the helper in the individual file:

**My Helper File**

    # tests/helpers/build-container.js
    import Ember from 'ember';
    import PageTabsController from 'adstage-ember-cli/controllers/page-tabs';

    export function build_container() {
      var container = new Ember.Container();
      container.register('controller:pageTabs', PageTabsController);
      return(container);
    }

**Imported in `start-app.js`**

    // tests/start-app.js
    import {build_container} from './build-container';

    export default function startApp(attrs) {
      ...

**Make jshint happy**

    // /tests/.jshintrc
    {
      "predef": [
      ...
      "build_container"
      ],
      ....

**Unit Test**

    # tests/unit/controllers/application-test.coffee
    # jshint expr:true
    `import { describeModule, it } from 'ember-mocha'`
    `import AdStage from 'adstage-ember-cli/core/adstage'`
    `import {build_container} from '../../helpers/build-container'` <------test fails without this import

    before ->
      AdStage.registerService('ui.loaders', {})
      AdStage.registerService('ui.progress', {})
      container = build_container()

    after ->
      AdStage.clearServices()

    describeModule "controller:application", "ApplicationController", {
      # Specify the other units that are required for this test.
      needs: ['controller:pageTabs']
    }, ->
      # Replace this with your real tests.
      it "exists", ->
        controller = @subject()
        expect(controller).to.be.ok

**Comment by stefanpenner** [comment]
> import {build_container} from './build-container';

what invokes this?

**Comment by spinlock99** [comment]
I agree that this isn't a bug; maybe more of a feature request. I think the above (or using `Ember.Test.registerHelper`) would work in the integration specs as described in the docs. But, I couldn't find a way to register a helper in all of the _unit_ specs (which is my use-case). The work-around I'm using for now is to put my spec helpers in `app/tests/helpers` (yup, I'm putting my test helpers in the application directory) so that I can include them in the specs with an absolute path:

    import { build_container } from 'adstage-ember-cli/tests/helpers/build-container';

To answer your question, `build_container` is called in our specs before creating a controller. Basically, it knows about the controllers that we use in the `needs` array:

    container = build_container();
    controller = DashboardController.create({
      container: container
    });

It's not the most elegant solution but I've got thousands of specs written this way so I have to make it work to upgrade to ember-cli.

**Comment by stefanpenner** [comment]
This is something that should be raised as a general [ember RFC](github.com/emberjs/rfcs). We generally feel this part of testing is lacking, and requires some serious TLC.
