### ISSUE TITLE
Need advice on what to use for I18N

### ISSUE THREAD

**Issue by baskarsugumar** [ember-cli/ember-cli#4469]
When asked some 3 months before for I18N support, I was advised to use ember-cli-i18n and now when I see ember-cli-i18n on Github, it clearly says it is deprecated. What is your suggestion on this. We are building an ember client using ember-cli. Please take this as top priority, as we are in the verge of handling I18N.

Thanks,
Baskar S

**Comment by topaxi** [comment]
I'm using https://github.com/jamesarosen/ember-i18n on a fairly new project, works with the latest stable version and seems to be actively maintained.

**Comment by rlivsey** [comment]
More a question for StackOverflow, but in addition to [ember-i18n](https://github.com/jamesarosen/ember-i18n) as @topaxi mentions, there's [ember-intl](https://github.com/yahoo/ember-intl)

**Comment by stefanpenner** [comment]
Sorry, this issue tracker is for issues/bugs. Questions like this are better for a venue like StackOverlfow (as @rlivsey  mentioned)
