### ISSUE TITLE
MergeTrees in addon's ember-cli-build.js doesn't copy files to /dist folder

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#4470]
I tried this approach using mergeTrees in my addon but I don't see these files end up in the dist folder.

demo: https://github.com/QuantumInformation/ember-cli-test-recorder/tree/use-test-recorder-npm

  var mergeTrees = require('broccoli-merge-trees');
  var pickFiles = require('broccoli-static-compiler');
  var extraAssets = pickFiles('node_modules/test-recorder/dist/',{
    srcDir: '/',
    files: ['**/*'],
    destDir: '/test-recorder'
  });

  module.exports = mergeTrees([app.toTree(), extraAssets]);

Nothing appears:
![image](https://cloud.githubusercontent.com/assets/216566/8745981/d8125814-2c7c-11e5-8ffd-738e360077ca.png)

the merge trees works fine in a regular ember cli project.

**Comment by stefanpenner** [comment]
This isn't nicely supported today, Although some approaches do work:  https://github.com/rwjblue/ember-cli-ic-ajax/blob/master/index.js#L6-L27

But good news, https://github.com/ember-cli/ember-cli/issues/4211 will include support for this built-in and by default. https://github.com/ember-cli/ember-cli/issues/4211

**Comment by QuantumInformation** [comment]
>
> Cool will wait for that to be merged)
>

Thanks


-- 

Kind regards
Nikos

**Comment by chadhietala** [comment]
Nope.
