### ISSUE TITLE
Allow `contentFor` execution in nested addons

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#4475]
Currently, only first-level addons have their `contentFor` methods executed. However, I've come across a situation where I would like to have nested addons, each with their own `contentFor` method that should execute during builds.

I can achieve this by looping over the addon's `addons` array, but I feel like this may be a feature that should work out of the box. I would be willing to take a stab at implementing this if it sounds like a reasonable feature.

For reference, here is what I am doing currently to get this functionality:

```js
contentFor: function(type, config) {
  // get nested addons content
  var content = this.addons.reduce(function(content, addon) {
    var addonContent = addon.contentFor ? addon.contentFor(type, config) : null;
    if (addonContent) {
      return content.concat(addonContent);
    }

    return content;
  }, '');

  // add additional content

  return content;
}
```

**Comment by stefanpenner** [comment]
right now: addons can only affect themselves or there parent, but not anything else. This is by design.

**Comment by trentmwillis** [comment]
Can you elaborate a bit on why that is? Especially, since other aspects of addons are allowed affect more than their immediate parent.

**Comment by stefanpenner** [comment]
> since other aspects of addons are allowed affect more than their immediate parent.

only parts that are explicitly pulled in by the common addon.

> Can you elaborate a bit on why that is?

We aim to reduce the uncontrollable impact of nested add-ons. 

Please note, this story is still in flux.

**Comment by stefanpenner** [comment]
cc @rwjblue maybe you can share context (although you are also likely busy).

**Comment by stefanpenner** [comment]
Actually  can quickly summarize one aspect that lead us to disallow for now. Its very easy to have duplicate nested addons, this adds some complexity especially on how they compose. in JS land, with modules its relatively clear. But with global pieces of state (like config) it posses trouble.

If someone is seriously interested in enumerating the problem space, and proposing a solution. We would welcome it.
