### ISSUE TITLE
Restart ember-cli serve after addon installation

### ISSUE THREAD

**Issue by gandalfar** [ember-cli/ember-cli#4481]
Steps to reproduce:

1. Have an `ember serve` running in one Terminal window
2. Install addon, eg. `ember install:addon liquid-fire` in another

At this point, ember server doesn't pick up new addon. Only killing server and restarting makes it pick up the new addon.

Apologies if this is a duplicate issue, I couldn't find one.

**Comment by stefanpenner** [comment]
this isn't a direct duplicate but we are aware of this. We can leave this open to track it.

**Comment by stefanpenner** [comment]
needs RFC
