### ISSUE TITLE
Deployment within TravisCI fails due to "Arguments to path.join must be strings"

### ISSUE THREAD

**Issue by terribleplan** [ember-cli/ember-cli#4486]
So, I'm trying to deploy through [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy), on travis CI using their [script deployment](http://docs.travis-ci.com/user/deployment/script/) technique. It seems I am unable to run ember commands from the shell script as I expect to. This failure is wholly within `ember-cli` and still occurs when I attempt to run non-deploy actions.

This is rather difficult to debug since it is running on infrastructure that I have no access to, but the only thing I can think of is something being weird about the environment and it not getting the string it expects for the `join`. This is especially weird since everything runs fine when invoked during the test phase, but not during the deploy phase.

Please see this [gist showing the environment at time of execution, stack trace, and full build log](https://gist.github.com/terribleplan/2c33cbddf68b2e8e0d8e) for more information.

**Comment by stefanpenner** [comment]
please provide a repo that  demonstrates this issue, or it is less ationable.

**Comment by terribleplan** [comment]
Sorry, it took a minute since I had to create a new project to demonstrate this.

[The repo is here](https://github.com/terribleplan/travis-fail-example), [the failed build in travis is here](https://travis-ci.org/terribleplan/travis-fail-example/builds/71612465).

**Comment by stefanpenner** [comment]
awesome thanks!

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/4494

**Comment by terribleplan** [comment]
That seems to be what it is. I just talked to someone at travis and the deploy process does a stash before running the code. There is a (currently) undocumented flag `deploy.skip_cleanup: true` that can be set in the .travis.yml which prevents this.

Thanks for working on making the error more intuitive!

**Comment by stefanpenner** [comment]
> That seems to be what it is

what is `that` ?

**Comment by terribleplan** [comment]
#4494, "don’t fail during command lookup if node_modules is empty"

**Comment by stefanpenner** [comment]
@terribleplan ah, makes sense. Ya i figured the error message could be much better. I'll finish those tests shortly then it will be in the next release.
