### ISSUE TITLE
Use PHP with ember serve command

### ISSUE THREAD

**Issue by philippmayrth** [ember-cli/ember-cli#4487]
Hi *,

Is there a way to use PHP or CGI in general with the ember serve command without the need to host these files on a different Port (CORS Problems)?
Or can I use that command with a different Server eg. Apache?

Thanks for your quick response.

Philipp

**Comment by stefanpenner** [comment]
This doesn't seem like a bug report. I would suggest this question be asked on a better q/a venue (like stackoverflow). We need to keep this issue tracker focused on bug reports or it quickly gets over run. In addition SO really is geared toward the whole Q/a experience and gh/issues are not yet.

Feel free to cross link
