### ISSUE TITLE
Addons in 1.13.1 can't watch folder

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-cli#4496]
I've just upgraded a working addon to 1.13.1 and now when I serve the addon's dummy test app it *does* serve but I get a lot of the following:

> unable to resolve root /path/to/app: directory /path/to/app/tests/dummy/app is not watched

>  unable to resolve root /path/to/app/styles: directory /path/to/app//tests/dummy/app/styles is not watched

>  unable to resolve root /path/to/app/public: directory /path/to/app/tests/dummy/app/public is not watched

This means that live-reload also does not work and so I need to restart the addon after every change. Painful. 

I know that in 2014 this problem showed up and it was fixed by adding the following line:

> https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-addon.js#L46

Maybe the movement away from Brocfile somehow brought this back? Just shooting in the dark.

**Comment by stefanpenner** [comment]
> Maybe the movement away from Brocfile somehow brought this back? Just shooting in the dark.

unlikely

can you provide a repo that demonstrates this issue?

**Comment by ksnyde** [comment]
Sure: https://github.com/lifegadget/ui-input/tree/feature/cli-1.13.1. 

Probably worth mentioning that I'm getting a lot of the now "old" `FSEventStreamStart failed` error but getting that error used to just be a nuisance ... was assuming that to still be the case but I guess I'm not sure.

**Comment by ksnyde** [comment]
Hmmmm. I was going to convert another addon and see if I ran into the same problems but noticed that before I upgraded -- Ember-CLI 1.13.1 installed globally but running 0.2.6 local to the project -- I was getting the same thing. I may have pointed to the wrong source of the error. Errr. I will try on my laptop and see if I can recreate.

**Comment by ksnyde** [comment]
Yes it seems to be machine dependant. My home computer is consistently failing, my laptop works. Now I've also tried shutting down Sublime and my home computer is now working. Guess we should close this. Any pointers on a misbehaving Sublime would be appreciated but this doesn't look like a CLI issue.

**Comment by stefanpenner** [comment]
> Probably worth mentioning that I'm getting a lot of the now "old" FSEventStreamStart failed error but getting that error used to just be a nuisance ... was assuming that to still be the case but I guess I'm not sure.

are your using watchman?

**Comment by ksnyde** [comment]
yes 3.0.0

**Comment by stefanpenner** [comment]
> Sublime

unfortunately Sublime is known, for putting FSEvents into a bad state :(



> yes 3.0.0

3.3.0 is out, and includes fixes specifically for us ember-cli users!

**Comment by ksnyde** [comment]
my hard drive failed a few days ago ... I thought I remembered Watchman being on a newer release but when I checked `homebrew` it claimed on I was on the latest ... bet I need to update the homebrew db. Darn. Ok, i'm off to fix this. :)

**Comment by stefanpenner** [comment]
@ksnyde report back if something funky happens.

(maybe ember cli, should inform users on older watchmans that a new version is available)
