### ISSUE TITLE
proxy server doesn't work out of box against puma?

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#4500]
I could just be a newb here, but I wasn't able to get `ember server` to proxy to a vanilla Rails server running `puma`. 

```shell
$ ember -v
version: 1.13.1
node: 0.12.7
npm: 2.12.1
```

I was able to switch my Rails server to `thin` and the proxy worked though.

**Comment by stefanpenner** [comment]
in theory it should both ends speak HTTP. Are you perhaps binding puma to an unexpected interface?

**Comment by mehulkar** [comment]
My config/puma.rb just has this:

```yaml
workers 4
daemonize
```

But when I start the puma server, it does say that it's binding to `tcp://localhost:3000`. Is that a problem?

**Comment by stravid** [comment]
I had a similar issue with Puma and Pow recently. Unfortunately I can't find the explanation I researched back then, it's a problem to which interface the server is binding.

My solution was this: `web: bin/rails server -p $PORT -b 0.0.0.0`

**Comment by stefanpenner** [comment]
Yes I believe it's just two different interfaces. Be sure to configure them to be the same one, or you will likely have a bad time

**Comment by mehulkar** [comment]
Thanks @stravid. Explicitly binding to `0.0.0.0` worked. I don't think I quite understand why, but works for me now.
