### ISSUE TITLE
User-guide mentions both Brocfile.js and ember-cli-build.js

### ISSUE THREAD

**Issue by jclem** [ember-cli/ember-cli#4505]
The Ember CLI user guide mentions both `Brocfile.js` and `ember-cli-build.js`, but doesn't mention what the relationship between them is.

It is also confusing in that it does things like showing a sample `ember-cli-build.js` that includes the comment `// Normal Brocfile content`, but it's not clear that `ember-cli-build.js` is actually a Brocfile.

**Comment by stefanpenner** [comment]
> but it's not clear that ember-cli-build.js is actually a Brocfile.

it isn't a brocfile

**Comment by stefanpenner** [comment]
> The Ember CLI user guide mentions both Brocfile.js and ember-cli-build.js, but doesn't mention what the relationship between them is.

seems bad, they should all be moved to `ember-cli-build.js`

**Comment by stefanpenner** [comment]
cc @joostdevries

**Comment by gmurphey** [comment]
This should be fixed by #4521. Sorry, forgot to add a reference to this issue in the commit.

**Comment by stefanpenner** [comment]
thanks @gmurphey :)
