### ISSUE TITLE
Error: EMFILE, open '...'

### ISSUE THREAD

**Issue by miguelmota** [ember-cli/ember-cli#4506]
I get the following when doing `ember s`

```bash
EMFILE, open '/Users/moogs/Dropbox/Development/app/tmp/class-tmp_cache_dir-JgsrbUeY.tmp/assets/acorns.
js'
Error: EMFILE, open '/Users/moogs/Dropbox/Development/app/tmp/class-tmp_cache_dir-JgsrbUeY.tmp/assets/
acorns.js'
    at Error (native)
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EMFILE, open '/Users/moogs/Dropbox/Development/app/tmp/tree_merger-tmp_dest_dir-PgzjQOkp.tmp/ac
orns/tests/unit/controllers/registration/c/user/suitability-questions/income-test.js'
    at Error (native)
```

**Comment by stefanpenner** [comment]
> /Users/moogs/Dropbox/

I suspect the issue might be dropbox getting trolled by the rapid changes inside tmp

I would recommend moving your project out of dropbox, or excluding: `/Users/moogs/Dropbox/Development/app/tmp/` from dropbox's sync.

Give that a try and let me know.

**Comment by miguelmota** [comment]
No luck

**Comment by stefanpenner** [comment]
@miguelmota whats the output?

**Comment by stefanpenner** [comment]
also which versions of:

* node
*  osx
* npm
* ember-cli

**Comment by stefanpenner** [comment]
if you can also provide a repo that demonstrates this it will be easier to debug.

**Comment by miguelmota** [comment]
```bash
$ ember s
version: 1.13.1
Livereload server on http://localhost:35729
Serving on http://localhost:4200/

EMFILE, open '/Users/moogs/Documents/app/tmp/class-tmp_cache_dir-xZYxASeJ.tmp/assets/acorns.js'
Error: EMFILE, open '/Users/moogs/Documents/app/tmp/class-tmp_cache_dir-xZYxASeJ.tmp/assets/acorns.js'
    at Error (native)
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EMFILE, open '/Users/moogs/Documents/app/tmp/tree_merger-tmp_dest_dir-ZeavROL7.tmp/acorns/tests/unit/controllers/registration
/c/user/suitability-questions/income-test.js'
    at Error (native)
```

```
$ ember --version
version: 1.13.1
node: 0.12.4
npm: 2.12.1

$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

**Comment by stefanpenner** [comment]
whats your `ulimit` set to, seems like maybe you are running out of file-handles.

Riak docs have a good example on how to bump this up: http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/#Mac-OS-X

**Comment by miguelmota** [comment]
adding the following to `~/.bash_profile` did the trick.

```
ulimit -n 65536
ulimit -u 2048
```

Thanks for you help man

**Comment by stefanpenner** [comment]
> Thanks for you help man

not a problem, sorry you ran into this :(

**Comment by hhff** [comment]
Just wanted to add here for anyone else: 

I had this problem, but only for `ember build --environment=staging`.  Adding the plist files Stef linked to and rebooting did the trick for me!
