### ISSUE TITLE
Need more consistent handling of `baseURL` for testing apps in subdirectories

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#4507]
### Description
I am currently working on a production app that is served from a subdirectory (`/dashboards`). I'd like to be able to run tests in the following scenarios:
 * During development with `ember serve` by visiting `/tests`
 * After deploying the output of an `ember build` by visiting `/tests`
 * On the command-line using testem via  `ember test`
 * Through testem's server via `ember test --server`

I can't seem to find a combination of `baseURL` settings which enables all of these without further hacks.

---

### Actual

Here's the table of behaviors I am observing (using a just-generated clean app):

`baseURL`(development) | `baseURL` (test) | `ember serve` | `ember build` | `ember test` | `ember test --server`
--- | --- | :---: | :---: | :---: | :---:
`/dashboards` | `/`° | ✘¹ | ✘¹ | ✔ | ✔
`/dashboards` | `/dashboards` | ✔ | ✔ | ✘² | ✘²

° This is the default in `config/environment.js`
¹ Visiting `/tests` fails, visiting `/dashboards/tests` results in 404 errors for all assets
² Testing hangs due to 404 errors for all assets

---

### Expected

`baseURL`(development) | `baseURL` (test) | `ember serve` | `ember build` | `ember test` | `ember test --server`
--- | --- | :---: | :---: | :---: | :---:
`/dashboards` | ? | ✔ | ✔ | ✔ | ✔

---

### Version
```
$ ember -v
version: 1.13.1
node: 0.12.0
npm: 2.12.1
```

**Comment by stefanpenner** [comment]
baseURL makes me sad :(

**Comment by SaladFork** [comment]
> baseURL makes me sad :(

Is there a way to run an Ember app from a subdirectory without it? I'm more interested in getting this to work than using `baseURL`.

**Comment by stefanpenner** [comment]
> Is there a way to run an Ember app from a subdirectory without it? I'm more interested in getting this to work than using baseURL.

write the paths in the index.html manually and configure the router.

**Comment by mike-post** [comment]
So I tried:
* `rootURL: '/foo/'` in `app/router.js`
* `baseURL: '/'` in `config/environment.js`
* changed all paths in `test/index.html` from `assets/<file>` to `../assets/<file>`

All of the cases listed in the OP worked, however, I was foiled when I actually tried to deploy my application to `/foo` on tomcat. I was able to fetch the HTML page, but all of the js and css files 404'd. This was likely due to the generated `<base href="/">` tag in `index.html`.

**Comment by janwerkhoven** [comment]
+1
We have the same issue, our Ember app resides in the subdirectory /patient.
To make `ember test` pass we use the following in `config/environment.js`:
```
} else if (environment === 'test') {
    ENV.baseURL = '/';
}
```
To make the `ember server` tests work in /patient/tests we have to change the baseURL like so:
```
} else if (environment === 'test') {
    ENV.baseURL = '/patient';
}
```
