### ISSUE TITLE
environment based fingerprint (or any) settings

### ISSUE THREAD

**Issue by ChrisHonniball** [ember-cli/ember-cli#4508]
I'd like to set up different settings for each environment in my `ember-cli-build.js`. I have three environments set up:

1. localhost - for local development due to specific settings for my RESTadapter in this environment. 
2. development
3. production 

I would like to be able to specify things like `fingerprint` of broccoli-asset-rev for each. I prefer to have assets fingerprinted on development and production but not localhost. This could also apply to other 'em settings as well.

Is there a way to do this currently that isn't too hack-ish? Here's my current solution:

```javascript
// ember-CLI-build.js...
  // TODO find a less hack-ish way to do this...
  if(process.env.EMBER_ENV === 'localhost') {
    fingerprintEnabled = false;
  } else {
    fingerprintEnabled = true;
  }
  
  var app = new EmberApp(defaults, {
    // Add options here
    vendorFiles: {
      'handlebars.js': null
    },
    minifyJS: {
      enabled: false
    },
    fingerprint: {
      enabled: fingerprintEnabled
    }
  });
// ...
```

**Comment by stefanpenner** [comment]
This doesn't seem like a bug, I would recommend opening a question on StackOverflow.

[There may be some related issues](https://github.com/ember-cli/ember-cli/issues?q=is%3Aopen+is%3Aissue+label%3Aconfiguration)

**Comment by ChrisHonniball** [comment]
Maybe more of a request rather than a bug. Sorry. My company uses issues for both so I'm programmed for it.

**Comment by krisselden** [comment]
I would not treat ember-cli config environment the same as deploy targets, if you spread out stuff like host names it makes it hard to deploy assets from qa to prod.

One warning though, broccoli-asset-rev alters content after fingerprinting, so sharing a CDN prepend options between QA and prod becomes dangerous as you can overwrite the existing assets (which defeats the whole point of fingerprinting).

**Comment by krisselden** [comment]
https://github.com/rickharrison/broccoli-asset-rev/issues/29
