### ISSUE TITLE
[REQUEST] Allow custom cli flags to support environment-specific builds

### ISSUE THREAD

**Issue by alexdiliberto** [ember-cli/ember-cli#4509]
Currently the only things passed into the builder are the environment and the output path.

Ideally at build time, in my `ember-cli-build.js` file there would be a way to capture and do conditional build logic based upon some custom flags

Example:

```js
// shell
$> ember b --myfoo=true --mybar=baz

// ember-cli-build.js
if (SOME_ENV.myfoo && SOME_ENV.mybar === baz) {
  // my custom EmberApp() build
}
//...
```

I'm sure this has already been talked about, but I just wanted to get it out there as I didn't see anything being actively worked on.

@trabus helped me with the issue on Slack, thanks :+1:!

**Comment by stefanpenner** [comment]
how does this differ from [environment variables](https://nodejs.org/api/process.html#process_process_env)?

**Comment by trabus** [comment]
@alexdiliberto Actually as @stefanpenner suggests, node environment variables would probably be a cleaner way to handle this.

Though if handling such things via cli options is still desirable, we'd probably refer to it as `buildOptions` or something like that instead of making it an enviornmental thing.

**Comment by alexdiliberto** [comment]
@stefanpenner Well I guess it doesn't differ so much as remove the extra step of having to setup separate scripts that just set ENV variables and call a shell command. My opinion its a little nicer than the ENV vars.

@trabus @stefanpenner No problem, this can be closed.

**Comment by stefanpenner** [comment]
```
MYVAR='my value' ember s
ember s --my-var='my-value'
```

both don't seem that much different, except the later means ember-cli cant add additional flags, since it may break an app.
