### ISSUE TITLE
API_URL ENV var undefined after deployment

### ISSUE THREAD

**Issue by Gab-Metzger** [ember-cli/ember-cli#4511]
Hello,

I developed one little application with ember-cli and I want to deploy this application on a cloud hosting provider.
I simply added a basic express nodejs server to serve static files generated from `ember build`command.
The deployment went well but when I go to my application I have the following error :
`TypeError: Cannot read property 'API_URL' of undefined`

I checked on the generated `index.html` and the env vars are injected in the meta : 

`"%7B%22modulePrefix%22%3A%22cockpit%22%2C%22environment%22%3A%22production%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22API_URL%22%3A%22https%3A//xxx.com%22%`

Can anyone help me ?

Thanks,
Gabriel

**Comment by stefanpenner** [comment]
Can you provide an app that reproduces the issue?

**Comment by Gab-Metzger** [comment]
Sure, there is a repo illustrating the issue : https://github.com/Gab-Metzger/ember-env-vars-prod
Explanation are in the README.md file.

**Comment by Gab-Metzger** [comment]
I commited something that seems to solve this issue : 
https://github.com/Gab-Metzger/ember-env-vars-prod/commit/15fc7eccd904e3515714ed4339d7a93ad6280c52

@stefanpenner, can you tell me if this is a good practice or not ?

Thanks,
Gabriel

**Comment by Turbo87** [comment]
you should be able to import the config like this:

```js
import config from './config/environment';
```

as demonstrated in `app/app.js`
