### ISSUE TITLE
mock server with proxy server

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#4512]
It seems that when mock server endpoints are provided these will always be served ahead of proxy server endpoints. It might make sense to do the opposite. If `--proxy` is provided this middleware would come before the mock server middleware. In the case that the proxy returns `500` defer to the mock server, if any.

Our current use case:

We are migrating a backend, and wrote a bunch of mocks to prevent us from being blocked while the backend was under development. Now the backend is starting to come into play. However it is up and down right now. We don't want to delete the mocks we've already written until that backend is more stable.

**Comment by stefanpenner** [comment]
The idea of falling back to another end-point (like a mock server) on failure seems quite nuanced. 

In some, likely most scenarios it could be very surprising and could lead to quite frustrating experiences.

In theory, I could see the following working:

* this being an opt-in mode (atleast at first)
* clear logging that this occurred

As this appears to be still an earlier though, maybe an issue on the rfc repo would be a good venue for further exploration: https://github.com/ember-cli/rfcs/issues/new

**Comment by stefanpenner** [comment]
seems to have gone stale
