### ISSUE TITLE
Generate integration test by default for helper blueprint

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#4517]
As per the conversation [here](https://github.com/emberjs/ember.js/issues/11867), convert the helper-test blueprint to generate an integration test by default (like the [component blueprint](https://github.com/ember-cli/ember-cli/pull/4272)).

**Comment by stefanpenner** [comment]
@locks what is the response that is needed?

**Comment by Gaurav0** [comment]
@stefanpenner My question was: I have not yet made integration tests default. I think it might be a good idea to do that in a followup PR once we know all is well and working?

**Comment by Gaurav0** [comment]
@locks @stefanpenner @trabus Please update labels, PRs were merged.

Please note the merged PRs create helper integration tests, but do not make them default, so additional work is necessary to close this issue.

**Comment by stefanpenner** [comment]
> @locks @stefanpenner @trabus Please update labels, PRs were merged.

I think they are updated, let me know if i missed something



> Please note the merged PRs create helper integration tests, but do not make them default, so additional work is necessary to close this issue.

----
thanks for the follow up sounds like the status is as follows:

- [x] create helper integration tests
- [ ] they need to be default

**Comment by Turbo87** [comment]
@Gaurav0 can you test if everything works fine with the integration tests and then promote them to default?

**Comment by Gaurav0** [comment]
@Turbo87 So I found some issues and added PRs.

**Comment by rwwagner90** [comment]
Anything left to do here? Happy to help out, but not clear what needs to be done.

**Comment by Gaurav0** [comment]
Just double check everything works (again) and then change the default and fix all appropriate tests.

**Comment by Turbo87** [comment]
I'll close this issue since it is 1) something that needs to be changed in the `ember.js` repo and 2) will be the default for the new RFC 232 blueprints
