### ISSUE TITLE
EmberApp.env() is removed but still suggested by ember-cli.com

### ISSUE THREAD

**Issue by indirect** [ember-cli/ember-cli#4518]
On version 1.13, in ember-cli-build.js, `EmberApp.env` is undefined. Up until at least 0.2.7, in Brocfile.js, `EmberApp.env` was a function that returned the current ember environment.

In fact, ember-cli.com still suggests that you use `EmberApp.env()` if you want to know [what environment you are building in](http://www.ember-cli.com/managing-dependencies/#test-assets).

```
var EmberApp = require('ember-cli/lib/broccoli/ember-app'),
     isProduction = EmberApp.env() === 'production';
```

As one might predict, this code raises an exception in ember-cli-build.js.

**Comment by rwjblue** [comment]
Seems like a regression to me. I believe that our intent was to be mostly transparent (other than the filename/structure change) here.

**Comment by indirect** [comment]
Ugh, I missed the way that ember-cli-build.js changed. It requires `ember-addon` into the variable EmberApp. :/

This does not work:

```
var EmberApp = require('ember-cli/lib/broccoli/ember-addon');
EmberApp.env();
```

But this does work:

```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
EmberApp.env();
```

So no regression, just confusion caused by the new addon template variable naming.
