### ISSUE TITLE
ember-addon does not merge arguments right-to-left as documented

### ISSUE THREAD

**Issue by indirect** [ember-cli/ember-cli#4519]
When passing options to `new EmberAddon`, the second object is not merged in to the defaults object as the documentation states it will be.

Check out indirect/ember-addon-no-merge@210de66 for an example of an application that does not merge the second argument into the defaults. (You can see that it does not by running `ember build` and checking `dist/index.html`, which will not contain the configured `inlineContent`.)

If the options are passed as the first argument, in place of `defaults`, the arguments are present as expected and `inlineContent` then works, as demonstrated in indirect/ember-addon-no-merge@f9bdf4a.

**Comment by stefanpenner** [comment]
cc @chadhietala

**Comment by stefanpenner** [comment]
@indirect this is `ember-cli@1.13.1`?

**Comment by indirect** [comment]
Yes, the demo app uses 1.13.1.

**Comment by stefanpenner** [comment]
> Yes, the demo app uses 1.13.1.

thanks

**Comment by gmurphey** [comment]
This seems fixed on `master`. @indirect -- can you [try this against master](https://github.com/ember-cli/ember-cli#working-with-master)?

**Comment by indirect** [comment]
Yes, this is fixed on master. Any ETA for a 1.13.2?

**Comment by stefanpenner** [comment]
@indirect when https://github.com/ember-cli/ember-cli/pull/4468 is green on windows :P

**Comment by lukemelia** [comment]
Master has long since been released. Can this be closed?
