### ISSUE TITLE
npm ERR! version not found: ember-cli@1.13.1

### ISSUE THREAD

**Issue by shalmalisohoni** [ember-cli/ember-cli#4525]
Trying to upgrade ember-cli version to 1.13.1.
As per the instructions at https://github.com/ember-cli/ember-cli/releases after I install the new ember-cli version, when I update my project using **npm install --save-dev ember-cli@1.13.1** I get the following error:

npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "ember-cli@1.13.1"
npm ERR! node v0.12.6
npm ERR! npm  v2.13.2
npm ERR! version not found: ember-cli@1.13.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Indeed, looking for the supported ember-cli versions using: **npm view ember-cli versions** gives me only up to version 0.2.7

Additional info:
node: 0.12.6
npm: 2.12.1

**Comment by stefanpenner** [comment]
@shalmalisohoni are you going through some npm mirror (some companies have there own mirrors)

I can with confidence say the public NPM registry (unless you hit some issue on there end) has 1.13.1

```
npm info ember-cli  --json | jq '.versions'
```

```
[
 ...
 "0.2.4",
  "0.2.5",
  "0.2.6",
  "0.2.7",
  "1.13.0",
  "1.13.1"
]
```

and the website documents it: https://www.npmjs.com/package/ember-cli

**Comment by stefanpenner** [comment]
will reopen, if my above comment wasn't accurate.
