### ISSUE TITLE
Enabling prototype extension in an addon dummy project

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#4529]
Prototype extensions are disabled by default in addon projects.

I am trying to enable it in the dummy project only as I need it for demonstrations purposes because an addon I am using [emberx-select](https://www.npmjs.com/package/emberx-select) requires it.  I have added the following in `tests/dummy/config/environment.js`

```javascript
    EmberENV: {
      EXTEND_PROTOTYPES: true, //added this line
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },
```

However prototype extensions are still not working.  I am getting `Uncaught TypeError: Ember.default.observer(...).on is not a function` which is coming from the x-select addon project I have added.

**Comment by rwjblue** [comment]
Removing the `ember-disable-prototype-extensions` entry from your `package.json` should be all you need to do.

**Comment by rwjblue** [comment]
Also, emberx-select was updated to use this addon to ensure it does not require prototype extensions in https://github.com/thefrontside/emberx-select/pull/40, I don't think that has seen a release yet though.

**Comment by jackmatt2** [comment]
@rwjblue I noticed that too, I forked it and was about to fix it then I noticed it was already fixed.
