### ISSUE TITLE
Add ability to ignore existing server folder

### ISSUE THREAD

**Issue by matt-in-a-hat** [ember-cli/ember-cli#4530]
If there is a folder named `server` in the root directory, when I use `ember serve` it seems that ember-cli will attempt to use it as its server. Is there a way of telling ember-cli to ignore that folder and create its own server like it does otherwise?

In my project I have something else under `server` but now this has broken `ember serve` with the error:

`Cannot find module '/snip/myproject/server'`

**Comment by stefanpenner** [comment]
i wouldn't be apposed to adding a config option, that can be a flag or an RC file option.

something like:

```
--server-directory=
```

**Comment by stefanpenner** [comment]
would accept a PR, but not really something on the critical path
