### ISSUE TITLE
Add ability to configure coding styles

### ISSUE THREAD

**Issue by Poorchop** [ember-cli/ember-cli#4531]
I'd like if Ember CLI had some sort of global variable to set coding styles. This way, projects will adhere to certain styles as soon as they are created.

I like to use double quotes (`"`) around strings, which results in a lot of inconsistencies in my project. For example, when generating a route, the first line reads as `import Ember from 'ember'` by default, but I use double quotes around any additional imports that I add myself.

It's kind of tedious to go through the entire project and change all single quotes to doubles, so it would be nicer if this could be set as soon as a new project is generated.

**Comment by stefanpenner** [comment]
Ya we have been thinking of making the generators editor config aware. Maybe they can also parse the jshint file and do there best?

**Comment by stefanpenner** [comment]
This likely needs an rfc to flesh out the how

**Comment by stefanpenner** [comment]
> This likely needs an rfc to flesh out the how
