### ISSUE TITLE
Correct initializer test blueprint for 2.0.0.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#4533]
https://github.com/ember-cli/ember-cli/blob/master/blueprints/initializer-test/files/tests/unit/initializers/__name__-test.js doesn't work properly on beta channel.

@dgeb - Can you take a peek and make a suggestion for how the blueprint should work for beta?  The goal is to invoke the initializer function with the arguments that will be passed into it by Ember, so that the test can confirm things were done properly.

**Comment by dgeb** [comment]
Now that application instance initializers are no longer feature flagged, we should probably add a new directory for them in ember-cli. We need some way to distinguish them from application initializers.

It follows that we should also add separate blueprints for application initializers vs. application instance initializers. 

For 2.0, the arguments to `initialize` should be:

* `registry, application` - for application initializers
* `applicationInstance` - for app instance initializers

For 2.1, we'll need to adjust the arguments to `initialize` for application initializers to be just: `application`. Of course, the previous args of `registry, application` will still be supported but will be deprecated.

_Note: this assumes that my changes from a few days ago are going into 2.1 and not 2.0. The initializer argument change is not dependent on the registry-reform feature flag._

Once the ember-cli team decides where app instance initializers should go, I'd be glad to help with some of this.

**Comment by stefanpenner** [comment]
In good with the directory being lazily created when the appropriate generator runs

**Comment by dgeb** [comment]
@stefanpenner @rwjblue what directory name makes sense to you? `instance-initializers` perhaps?

**Comment by stefanpenner** [comment]
> instance-initializers perhaps?

yup

**Comment by rwjblue** [comment]
> instance-initializers

Yes, that is what we look for in https://github.com/ember-cli/ember-load-initializers/.

**Comment by dgeb** [comment]
Got it - thanks guys!

I can help with the blueprints. Is there any precedence for lazily creating directories when particular generators are run?

**Comment by stefanpenner** [comment]
> Is there any precedence for lazily creating directories when particular generators are run?

ya, the generators should just doit automatically
