### ISSUE TITLE
Multiple install npm package by Blueprint

### ISSUE THREAD

**Issue by long800110** [ember-cli/ember-cli#4539]
* When I generate a http-mock via blueprint, it will install `margon`, `glob` and `express` npm packages many times no matter whether the packages had already in both npm list and `package.json` file.
* As an advice, I think that we can per-check the package.json file and npm list before install the packages in method `Blueprint.prototype.addPackagesToProject`. if the packages already exist, I think ignore the install is a better way, it can save time and network resource.

**Comment by gmurphey** [comment]
I believe the issue with the `http-mock` blueprint is fixed in #4452 and is slated for 1.13.2.

**Comment by stefanpenner** [comment]
v1.13.5 is out

**Comment by long800110** [comment]
### Thank you for highlight.
