### ISSUE TITLE
[QUEST] Ember CLI Runtime Code Migration to NPM via Addons

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#4546]
The following sanctioned Ember Bower components need be migrated to addons and published to NPM. The addons should not use `app.import` to pull in some bower dependency. This is prep work for the [packager](https://github.com/ember-cli/ember-cli/issues/4211), and can be done in parallel.

The migration plan is to create addons of the following libraries. For addons like `ember-qunit` all of their code should reside in the addon directory and there are very few cases where code should be in the app directory.  To migrate you will need to PR against the following projects removing `app.imports` to ember code and instead placing that code into the addon directory. This will mean that some projects may be merged or have 2 different published artifacts, one that continues to go to bower and they other that gets published to NPM.

__Motivation__

The motivation behind this is to allow us reason about the dependencies in Ember CLI based applications. A new build process is coming that will help us unlock "tree shaking" and Ember features like engines and put us in a much better place. We also didn't have addons when Ember CLI first released so `app.import` was how you brought in 3rd party code. This obviously has changed and now we have a unit we directly depend on out apps.

- [x] [Ember](https://github.com/emberjs/ember.js)
  - Someone close to the project will most likely need to do this migration
- [x] [Ember Data](https://github.com/emberjs/data)
  - Someone close to the project will most likely need to do this migration
- [x] [Ember QUnit](https://github.com/rwjblue/ember-qunit)*
- [x] Ember Test Loader https://github.com/ember-cli/ember-cli-test-loader/pull/13
- [x] [Ember Load Initializers](https://github.com/ember-cli/ember-load-initializers)
   - Should come out of the ember addon
- [x] [Ember Resolver](https://github.com/ember-cli/ember-resolver)
   - Should come out of the ember addon
- [x] Loader.js https://github.com/ember-cli/loader.js/pull/48
- [x] [Ember CLI IC-Ajax](https://github.com/rwjblue/ember-cli-ic-ajax)
  - This already pulls everything out of NPM but should place items in addon not the vendor

- [x] ember pending https://github.com/emberjs/ember.js/pull/13022
- [x] ember-cli-shims pending https://github.com/emberjs/ember.js/pull/13022
- [x] ember-cli-test-loader
- [x] ember-qunit-notifications
*It is unclear what the role of [Ember-CLI-Qunit](https://github.com/ember-cli/ember-cli-qunit) meta package may be

**Comment by stefanpenner** [comment]
@chadhietala could you outline how contributors may contribute ? Or is it too soon, and only a checkouts for the devs who are in "the know"

**Comment by tim-evans** [comment]
Someone should try to get ownership / publish access to https://www.npmjs.com/package/ember

**Comment by runspired** [comment]
Ember Resolver and Ember Data are now addonified.  I believe the ember-ajax and ic-ajax complaints have been resolved as well.

**Comment by rwjblue** [comment]
ember-qunit is also done

**Comment by josemarluedke** [comment]
`ember-load-initializers` is done as well.

**Comment by rwjblue** [comment]
Updated, thanks @josemarluedke!

**Comment by runspired** [comment]
ruh roh, just Ember: shi is about to go down.

**Comment by btecu** [comment]
I think the work to get Ember as an addon is massive. There has been an issue or a pull request tracking progress but I hasn't got any attention since sometime last year. Hopefully by summer we'll be able to drop bower. :tada:

**Comment by stefanpenner** [comment]
> Hopefully by summer we'll be able to drop bower.

before emberconf

**Comment by stefanpenner** [comment]
> I think the work to get Ember as an addon is massive.

Nah not really, lots of the work is done. It was just missing its own tests for blueprints, now that @trabus has implemented a nice test harness, it shouldn't be much effort to complete it.

**Comment by btecu** [comment]
Awesome! Looking forward `ember-cli 2.x` stable without `bower`.

**Comment by thomblake** [comment]
Is this something that could use more hands? PagerDuty's front-end team may be able to help.

**Comment by trentmwillis** [comment]
As an update, ember-cli-test-loader and ember-qunit-notifications should be finished now

**Comment by nathanhammond** [comment]
@thomblake https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json

We're startlingly close to being able to survive without bower on initial build. You already found the [`ember-core` PR](https://github.com/emberjs/ember.js/pull/13022) ... if you can test that in your application that'd be fantastic.

**Comment by thomblake** [comment]
The ember-cli-shims link in the PR description doesn't seem correct - it links to the ember-core PR.

PagerDuty has tested ember-core and it looks good. Anything left to do?

**Comment by nathanhammond** [comment]
@thomblake Grant @stefanpenner more hours in the day? It's on our list to do. 😄 Thank you so much for testing! This gives us higher confidence in releasing it.

**Comment by thomblake** [comment]
Also, "NPM" above should be "npm"

**Comment by thomblake** [comment]
emberjs/ember.js#13022 is merged! 🎉

**Comment by stefanpenner** [comment]
![14xz1gq](https://cloud.githubusercontent.com/assets/1377/19204032/5ddb5392-8c8f-11e6-9ffb-f89628104136.gif)

**Comment by chadhietala** [comment]
I'm happy to close this issue.
