### ISSUE TITLE
serverMiddleware not called for /

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4554]
I've done the following:

* `ember addon test-middleware`
    * changed index.js to 
      ```
      /* jshint node: true */
      'use strict';

      module.exports = {
        name: 'test-middleware',
  
        serverMiddleware: function(options) {
          options.app.use(function(req, res, next) {
            console.log('URL:', req.url);
            next();
          });
        }
        /* TODO: testemMiddleware */
      };
      ```
    * `npm link`

* `ember new test-app`
    * `npm link test-middleware`
    * add test-middleware to package.json, devDependencies
    * `ember serve` 
    * Navigate in Browser to site
    * Log shows:
        * URL: /favicon.ico
        
Thisis, obviously, a boiled down version of my real problem, that looks to me as if I can only intercept static requests. I would have expected, to have a line *URL: /* logged before favicon.

The same happens in an addon's dummy app. I haven't checked what happens with testemMiddleware.

Is there something wrong in my code, or have i found a bug?

**Comment by stefanpenner** [comment]
/ currently serves the app, which currently is not allowed to be overridden by a middleware

**Comment by jnfingerle** [comment]
Ok, but if I change the `use` call to `options.app.use('/api', ...` and navigate to `http://localhost:4200/api/test` I still get no log entries.

**Comment by jnfingerle** [comment]
Vacations make you wiser. ;-)

Anyway, what I was missing to get this working was to set `baseURL` in `environment.js` so the un-overridable app doesn't reside in / any more and I can use `/api` for something else without colliding with the app.

Having said that: Why am I not allowed to override the app? I might have a middleware for some special form of logging that would have to intercept the app.

**Comment by mmahalwy** [comment]
@jnfingerle any update on this?

**Comment by jnfingerle** [comment]
@mmahalwy Not from my side, no. I've got a work around (with its own bug, see #4716). I still consider this either a bug in functionality (I mean, middlewares are supposed to intercept, hence the name) or in documentation, but in the end that's not for me to decide.

**Comment by stefanpenner** [comment]
seems to have gone stale

**Comment by runspired** [comment]
fwiw this is still broken in 2022. In order to use a middleware, the app cannot be served on `/`.
