### ISSUE TITLE
Upgrading plugins to broccoli-plugin

### ISSUE THREAD

**Issue by joliss** [ember-cli/ember-cli#4562]
This issue tracks which plugins have been updated to derive from the broccoli-plugin base class. To see the plugins that need to be updated, run: `BROCCOLI_WARN_READ_API=y ember build`

Motivation: We want to rewrite the Broccoli builder to take advantage of the new broccoli-plugin base class. In particular, this will allow us to centralize tmp dir handling. But we need to update all plugins we use to derive from broccoli-plugin.

- [x] broccoli-filter [0.2.0 / 1.0.0](https://github.com/broccolijs/broccoli-filter/blob/master/CHANGELOG.md#100)
    - [x] broccoli-asset-rev 2.1.1: https://github.com/rickharrison/broccoli-asset-rev/pull/68
    - [x] broccoli-jshint 1.0.0: https://github.com/rwjblue/broccoli-jshint/pull/26
    - [x] broccoli-asset-rewrite 1.0.9
    - [x] ember-cli-htmlbars 0.7.10: https://github.com/ember-cli/ember-cli-htmlbars/pull/59
        - [x] ember-cli-app-version 1.0.0: https://github.com/embersherpa/ember-cli-app-version/pull/23
        - [x] ember-cli-htmlbars-inline-precompile 0.3.1: https://github.com/pangratz/ember-cli-htmlbars-inline-precompile/pull/23
- [x] cauliflower-filter (merged into broccoli-filter): https://github.com/broccolijs/broccoli-filter/pull/26
    - [x] broccoli-babel-transpiler 5.4.3: https://github.com/babel/broccoli-babel-transpiler/pull/48
- [x] broccoli-caching-writer 2.0.0: https://github.com/ember-cli/broccoli-caching-writer/pull/54
    - [x] ~~broccoli-es6modules: https://github.com/ember-cli/broccoli-es6modules/pull/26~~  we will drop this shortly in-favor of `ember-cli-babel`
    - [x] broccoli-sourcemap-concat 1.1.1 (variously shows as "Concat", "SourcemapConcat", or "Class"): https://github.com/ef4/broccoli-sourcemap-concat/pull/15
    - [x] [ConfigLoader](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/broccoli-config-loader.js): https://github.com/ember-cli/ember-cli/pull/4827
- [x] broccoli-merge-trees 0.2.2
- [x] broccoli-funnel 0.2.4: https://github.com/broccolijs/broccoli-funnel/pull/28
- [x] broccoli-unwatched-tree: replaced by [broccoli-source](https://github.com/broccolijs/broccoli-source)
- [x] [CustomReplace](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/broccoli-config-replace.js): https://github.com/ember-cli/ember-cli/pull/4744
- [x] Reexporter: https://github.com/ember-cli/ember-cli/pull/4752

~~A few plugins are only reported as `Object` - we need to figure out where those come from so we can update them as well.~~

Please edit/extend the list freely, and add links to any pull requests you create.

**Comment by stefanpenner** [comment]
docs for the new plugin api: https://github.com/broccolijs/broccoli-plugin

**Comment by rickharrison** [comment]
Would you mind reviewing this PR on asset-rewrite: https://github.com/rickharrison/broccoli-asset-rewrite/pull/21 ?

**Comment by rickharrison** [comment]
Merged and published as `broccoli-asset-rev 2.1.1` and `broccoli-asset-rewrite 1.0.9`

**Comment by joliss** [comment]
I think the list above is complete now, so we're quite close.
