### ISSUE TITLE
Release notes upgrade link is incorrect

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/ember-cli#4566]
The link to upgrade docs: *Upgrade your project's ember-cli version - docs*

in the release notes for 1.13.5 and 1.13.6 (maybe others) points to an incorrect or missing link (http://www.ember-cli.com/#project-update).  Probably should be http://www.ember-cli.com/user-guide/#upgrading-an-ember-cli-app

**Comment by efx** [comment]
Seeing this for docs link next to 'Upgrade your project's ember-cli version' under the 1.13.8 release notes.
