### ISSUE TITLE
Default loading.hbs & error.hbs for new apps

### ISSUE THREAD

**Issue by jhr007** [ember-cli/ember-cli#4570]
"Pretty much everybody, ever, needs a loading spinner..." - Yehuda Katz

https://www.youtube.com/watch?v=GKWhDPk_AcM&feature=youtu.be&t=24m02s

I doubt he was being literal, but default loading/error pages could be helpful to new apps during the banging-out-code phase... 

I'm thinking a Tomster version of https://github.com/imanhodjaev/ember-ufo-loading#look-and-feel

:smiley:

**Comment by stefanpenner** [comment]
I'm not supposed. But striking a helpful but not over bearing balance will require thought.

**Comment by olivierlesnicki** [comment]
That's a very sensible proposal!

**Comment by stefanpenner** [comment]
@leo any ideas on a good design?

**Comment by leo** [comment]
Adding default parts for those two things sounds like a great idea to me. Nevertheless, I'm not sure if styling them by default is the best way to do it. I mean, there aren't any other parts which are already styled, right? And you're probably thinking about including those parts in the blueprint that gets generated by running `ember new`?

IF you want to include it by default, I would definitely use a much simpler version like the 7th in [spinkit](http://tobiasahlin.com/spinkit/) for the loading thing and a basic template containing only a short text (no markup) for the error page (like the default "Welcome to Ember").

I mean, of course it's possible to even style the error page by default, but if you ask me, it's important to keep the default blueprint as slim as possible.

**Comment by kellyselden** [comment]
@leo, I agree, very slim and unstyled to match the existing application.hbs would be my thought.

**Comment by stefanpenner** [comment]
I believe some style is required to give relatively OK UX. But it should be kept to a absolute minimum.

**Comment by rwjblue** [comment]
IMO, we should make this an addon and *not* add these files to the default app blueprint.  The addon can either be an "internal addon" that is added by ember-cli and is not included in the application's `package.json` or just be a "normal addon" that is included in a default apps `package.json`.

**Comment by stefanpenner** [comment]
@rwjblue ya, a installed by default add-on, with generators that can be used to optional inline the relevant code in app seems best.

**Comment by rwjblue** [comment]
:+1:

**Comment by Turbo87** [comment]
I guess this suggestion is somewhat related to the proposal of an `ember-getting-started` addon in #5501

**Comment by locks** [comment]
Example of a loading screen http://angularjs.blogspot.pt/2016/03/angular-material-2-alpha-preview.html

**Comment by nathanhammond** [comment]
I'm opposed to this unless provided by some addon which can be easily removed. I don't want to add to the immediately overwhelming first experience of an Ember application.

**Comment by acorncom** [comment]
@nathanhammond I think the goal would be to have it something akin to the welcome page addon (but less obtrusive). Giving new apps out of the box loading templates but not forcing it on existing apps ...

**Comment by stefanpenner** [comment]
👍 RFC/Pr with demo seems like a good next step

**Comment by nathanhammond** [comment]
Alternatively, just implemented as an addon, and then we can test it out.
