### ISSUE TITLE
Turn on integration tests blueprints

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli#4571]
Currently have a project that was initially on ember-cli 0.2.7 and now on the latest. When generating components it still generates unit tests, which I'd like to from now on generate integration tests. How do I turn that on?

My new projects it has integration tests turned on by default and I'd like to have that on my old ones too!

**Comment by stefanpenner** [comment]
im not sure this is a bug, questions are better asked on StackOverflow. We should keep this tracker focused on bug reports.

**Comment by mmahalwy** [comment]
@stefanpenner agreed
