### ISSUE TITLE
custom contentFor type in an EmberApp without using an addon?

### ISSUE THREAD

**Issue by raycohen** [ember-cli/ember-cli#4573]
Allowing an addon to respond to a custom `contentFor` type is explicitly supported.
https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1386-L1389

However, `EmberApp#contentFor` is marked private, and no hooks are provided for *the app itself* to fill custom contentFor types.

My use case is that I want to define a global variable dynamically based on config/environment.js before the JS in the `{{content-for "head"}}`.  A 3rd party error reporting service requires this global config to exist or it explodes upon inclusion.

Is this supported some other way?  Want a PR to add it?

**Comment by rwjblue** [comment]
I have generally used an in repo addon for this.  It isn't a ton of overhead (just two files are created with `ember g in-repo-addon foo`), and to me it makes sense to encapsulate the behavior a bit. 

I'm not opposed to allowing the app itself to have `contentFor` though...

**Comment by raycohen** [comment]
perhaps it's better to just have one way to do this.  symantically it seems odd that an "addon" be the only way to accomplish something, but I can get over that.
