### ISSUE TITLE
Asset compilation documentation does not explain how to add other html files

### ISSUE THREAD

**Issue by jdmarshall** [ember-cli/ember-cli#4575]
I can't find anything in the docs that allows that an ember app would have anything more than a single html file, index.html.

In particular this makes it pretty hard to work with web components, but I imagine other people would have other reasons for wanting to include html files (like how do I include a static 404 html file?)

**Comment by stefanpenner** [comment]
> In particular this makes it pretty hard to work with web components, but I imagine other people would have other reasons for wanting to include html files (like how do I include a static 404 html file?)

anything in public/* gets copied over holesale

**Comment by stefanpenner** [comment]
seems to have gone stale, but i believe my above comment addresses the issue
