### ISSUE TITLE
Enhancement: Bundle a RESTful database counterpart to "ember serve"

### ISSUE THREAD

**Issue by groovy9** [ember-cli/ember-cli#4578]
I couldn't find a canned RESTful database to use with Ember (or any MVC, really), so I put one together with Mojolicious and SQLite (single script, no web or db server needed).  I don't expect you to bundle a Perl app with ember-cli, but it would save a ton of time and effort for someone wanting to use Ember Data to have a development database included and ready to point the RESTAdapter at.

For ideas: https://github.com/groovy9/sqlite4ember

**Comment by stefanpenner** [comment]
this makes sense as an addon, but for now not something we plan to bundle with the default package.
