### ISSUE TITLE
ember test fails with: No tests were run.. errors before tests run?

### ISSUE THREAD

**Issue by vasilakisfil** [ember-cli/ember-cli#4583]
I upgraded my project from ember 1.8 to ember 1.12 and ember-cli 0.2.7. Everything works perfect (with some deprecation messages) except tests. When I run ember test I get the following:

"No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled."

PhantomJS is installed (I have another fresh 1.12 ember project that tests are run) and I also try with firefox/chrome and I get the same error no matter what. Here is my package.json:

```
{
  "name": "genombrott",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": "0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.2.0",
    "broccoli-asset-rev": "^2.0.2",
    "broccoli-babel-transpiler": "^5.3.1",
    "broccoli-sass": "^0.2.2",
    "broccoli-static-compiler": "~0.2.1",
    "debug": "2.1.1",
    "ember-cli": "0.2.7",
    "ember-cli-autoprefixer": "0.4.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dates": "1.1.3",
    "ember-cli-htmlbars": "^0.7.9",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-simple-auth": "^0.6.4-1",
    "ember-cli-simple-auth-devise": "^0.6.7",
    "ember-cli-uglify": "1.2.0",
    "ember-data": "1.0.0-beta.17",
    "ember-data-model-fragments": "0.3.3",
    "ember-devtools": "3.2.0",
    "ember-export-application-global": "^1.0.0",
    "ember-notify": "3.4.0",
    "ember-rl-month-picker": "^0.1.1",
    "ember-rl-week-picker": "vasilakisfil/ember-rl-week-picker#feat/update-moment",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "grunt": "^0.4.5",
    "grunt-aws-s3": "^0.9.3",
    "grunt-cdnify": "git+ssh://git@github.com:joakim/grunt-cdnify.git#skl-genombrott-ember",
    "grunt-cli": "^0.1.13",
    "grunt-hashres": "^0.4.1",
    "grunt-redis-manifest": "^0.1.3",
    "grunt-remove-usestrict": "^0.1.0",
    "grunt-shell": "^1.1.1",
    "phantomjs": "1.9.8"
  }
}
```

Probably, there are errors BEFORE tests run.. how can I check that?

**Comment by stefanpenner** [comment]
i believe this is a duplicate in the original report i describe the solution. I am on my phone so its hard to find right now.

**Comment by vasilakisfil** [comment]
yeah there are some duplicates:

https://github.com/ember-cli/ember-cli/issues/3977
https://github.com/ember-cli/ember-cli/issues/1451


Also there is this issue which resulted in a pull request:
https://github.com/ember-cli/ember-cli/issues/2020

but I don't understand exactly where I should put that code. Could you help me?

**Comment by constantm** [comment]
Ran into a similar issue. Not sure if related. #5062
