### ISSUE TITLE
Ember Addon Component Templates don't seem overridable any more?

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#4587]
Folks have been using my addon, Ember Infinity, with brand spanking new Ember CLI versions.

A couple people pointed out that they can't seem to override the Component Template supplied by the addon in their host application any more.

Here's the issue for clarity (I have a workaround at the bottom) https://github.com/hhff/ember-infinity/issues/51

This worked great in Ember CLI 0.2.7 - but I can confirm it doesn't work with a fresh install from v1.13.1.

I probably missed something along the way - but couldn't find an issue relating to this  here - so opening this for any other addon devs who see this.

**Comment by trabus** [comment]
@hhff So the workaround you described is actually the prescribed way to override an addon component. If you would prefer the user to install the ember-infinity template, then simply remove the layout definition from your `addon/components/ember-inifinity`, and place the template in the `app` folder instead.

**Comment by trabus** [comment]
Alternatively, you could update your blueprint so it creates the component and the template with the layout definition already setup (using the prescribed override instead).

**Comment by hhff** [comment]
@trabus ur the man case closed
