### ISSUE TITLE
Ember CLI to Ember GUI

### ISSUE THREAD

**Issue by ghamha1n** [ember-cli/ember-cli#4594]
Good day all,
i have been developing application with ember cli more than one year and i become more experienced with system.

I got this repeated idea which is : why ember cli not get some ui?

so i designed the idea, but i am confused how to call " ember new " from ember application to create new project, or " ember generate route" from regular ember app.

note : i use electron for node in browser.

The benefit of this application give easy way to organize and fast development without remember every command and give more visual indicator to your apps and you can use it as text editor

see the images: 

![ screen shoot ](https://daks2k3a4ib2z.cloudfront.net/55ae816dbe4b67666850b524/55c1f849a0cf9f8a47756831_Screen%20Shot%202015-08-05%20at%202.47.25%20PM.png)

![ screen shoot ](https://daks2k3a4ib2z.cloudfront.net/55ae816dbe4b67666850b524/55c1f8494162c74c262fa948_Screen%20Shot%202015-08-05%20at%202.48.11%20PM.png)

![ screen shoot ](https://daks2k3a4ib2z.cloudfront.net/55ae816dbe4b67666850b524/55c1f849f0c5a54d269e3869_Screen%20Shot%202015-08-05%20at%202.48.08%20PM.png)

 
[link to mockup for the application](http://ember-manager.webflow.io/)

**Comment by hhff** [comment]
checkout ember hearth

**Comment by ghamha1n** [comment]
hhff thanks for fast reply 

i was using it, but is an swift application.

Ember Manager will be ember.js application which can work in any platform.

thanks.

**Comment by ghamha1n** [comment]
and you can search NPM and Bower for packages and give you indicators if a package need to update.

and you can edit your Ember app files using Ember Manager.

**Comment by kellyselden** [comment]
@ghamha1n Very good ideas. This would be best suited as a separate addon or stand-alone, as this project focuses on a command line environment. It would be interesting to see something like this though.

**Comment by stefanpenner** [comment]
@ghamha1n nice, that design look really great!

Eventually I think it would be very valuable to have a cross-platform UI, especially for the demographic who prefers UI. I personally am not one of those, but can appreciate the value. So what this needs is a champion, if that is you then fantastic.

I really like that it is a web app. Not to discourage the ember-hearth project, but cross-platform is a big selling point. If in the future this becomes mature, stable and well maintained, I could imagine a possibility where it was offered as part of the officially story.

 Don't be discouraged by the closed issue (this really isn't a bug) but we can continue discussion here, or more it to another venue (maybe https://embercommunity.slack.com/).

Something that might interest you is: https://github.com/ember-cli/ember-cli/pull/4576 which will enable tools to introspect which commands are available, and dynamically expose functionality.

**Comment by stefanpenner** [comment]
> so i designed the idea, but i am confused how to call " ember new " from ember application to create new project, or " ember generate route" from regular ember app.

I am pretty sure someone in the community (or myself as time permits) can help with this aspect.

**Comment by kellyselden** [comment]
@ghamha1n Also, when #4576 is finished, it will help you auto detect the feature set of the command line options.

**Comment by kellyselden** [comment]
Ah @stefanpenner beat me to the reference of json help...

**Comment by thomassnielsen** [comment]
Good stuff. If there is anything you want to know about Ember Hearth (how it works, why we did things the way we did, etc), don't hesitate to ask. See my bio for contact info.

**Comment by stefanpenner** [comment]
@thomassnielsen it would be great to see collab here. I do like ember-hearth, but the idea of something cross-platform and using tech all ember devs already know is quite appealing. Thoughts?

**Comment by thomassnielsen** [comment]
@stefanpenner I agree. I mostly went for Swift because I didn't have a clear idea how to approach the project in Ember+Node, while I could get Hearth up and running in a weekend. If this projects turns out well I think we might just deprecate Ember Hearth completely.

**Comment by ghamha1n** [comment]
@stefanpenner thanks for your encouraging comments, 

this project is ongoing, and i would like to have many contributor as possible as needed to final products which an open source application.

right now i am looking to #4576 and i wish this application become the replacement of Ember-CLI

**Comment by kimroen** [comment]
Like Thomas said, the idea was getting something running quickly that could help people get everything they needed installed and going, and then building on that. Considering supporting more platforms would be a pretty big task either way, it made sense to write it using something me and Thomas have worked together on before.

Rewriting Ember Hearth using Ember and Node is totally a good idea that we've talked about a lot and probably will do.

**Comment by ghamha1n** [comment]
@thomassnielsen thanks for your offer

i need to know the possibility to call ember cli without Command line interface.

i mean in application controller can i call action which have code calling ember globe and generate files or run server

**Comment by ghamha1n** [comment]
@kimroen i agree with you on supporting multiple platform is key value.
Electron which is atom project is more suitable for kind application.
@kimroen Did you like to collaborate with me on this project to bring it to the light.

**Comment by stefanpenner** [comment]
> i wish this application become the replacement of Ember-CLI

its unlikely this to replace the CLI, as users like myself prefer this experience. But something in-addition is good.

> i need to know the possibility to call ember cli without Command line interface.

Ya, the test suite [actually powers cli directly](https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/ember.js) (via API). There are [some caveats](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/npm.js#L10-L12), but nothing unsurmountable.

I suspect we will need to flesh out ^^ a bit further yet to be really handy, but it would be a good starting point for you.

**Comment by ghamha1n** [comment]
@stefanpenner in normal ember app i can't import cli/index.js to send args how to import it in ember directly

**Comment by stefanpenner** [comment]
> @stefanpenner in normal ember app i can't import cli/index.js to send args how to import it in ember directly

I'm a bit swamped this week. I can likely set some time aside early next week, if you want to touch base.

If i have some spare time, I will try to wip up a prototype (and find out what the pain points are) before then.

**Comment by ghamha1n** [comment]
@stefanpenner 
i will be trying and if i succeed will post it here if not i will be waiting you.

**Comment by stefanpenner** [comment]
> i will be trying and if i succeed will post it here if not i will be waiting you.

:)

do you have a WIP repo i can play with?
