### ISSUE TITLE
Using ${} syntax in blueprint in throwing and error.

### ISSUE THREAD

**Issue by jackmatt2** [ember-cli/ember-cli#4595]
I have a blueprint which contains the following in a file called build.gradle.

```
${projectDir}
```

I am getting the following error when running the blueprint via `ember g`
```
projectDir is not defined (Error in blueprint template: C:\Users\jack\git\tmp\db
test\node_modules\ember-aupac-db-reverse-engineering\blueprints\ember-aupac-db-r
everse-engineering\files\db-reverse-engineering\build.gradle)
```

It appears that maybe ember-cli it trying to substitute the variable with something.  Any ideas why it is getting confused?

**Comment by stefanpenner** [comment]
Yes. These files are interpolated

**Comment by jackmatt2** [comment]
Can I escape it somehow?

**Comment by stefanpenner** [comment]
> Can I escape it somehow or do I need to wait for a bugfix?

unsure, an answer will require a quick dive as I don't recal the exact details. This is added to my queue, i'll get to it in the next day.

**Comment by trabus** [comment]
We're using [lodash template](https://lodash.com/docs#template) under the hood. You can escape it like so:
```
<%= "\${projectDir\}" %>
```

**Comment by trabus** [comment]
> Yes. These files are interpolated. Although it appears like a bug, as we should only be interpolating double curlies.

Currently we're using the default which interpolates `<%= %>`, `{{ }}`, and `${ }`. Most of our templates use `<%= %>`, and we refer to using that [in the docs](http://www.ember-cli.com/extending/#template-variables-aka-locals)

**Comment by stefanpenner** [comment]
@trabus thanks for the deep dive. This appears to be working as expected then.

Will reopen if it isn't

**Comment by jackmatt2** [comment]
@stefanpenner we have just hit another issue related to this and ES2015 backquote syntax.

```javascript
    view(model) {
      const modelTarget = this.get('modelTarget');
      this.transitionTo(`crud.${modelTarget}.view`, model);
    },
```

This is not a template at all but the blueprint tries to replace `${modelTarget}` with a blueprint variable!

**Comment by jackmatt2** [comment]
It would be good if the two undocumented types were not included as blueprint variables `{{ }}` and `${ }` if possible.

**Comment by stefanpenner** [comment]
good point re: `${`

**Comment by trabus** [comment]
We can limit the lodash template interpolate option to `<% %>` and `<%= %>`.

**Comment by trabus** [comment]
@jackmatt2 [this pr](#4659) should fix your issue.

@stefanpenner we should probably list this as a breaking change in the release notes, as some people may have found that `{{}}` and `${}` work and intentionally used them.

**Comment by jackmatt2** [comment]
@trabus Great thanks, this will save me a lot of headache.
