### ISSUE TITLE
Disable generation of vendor.css

### ISSUE THREAD

**Issue by fullofcaffeine** [ember-cli/ember-cli#4608]
I'm using `sass` and importing everything into `app.sass`. Is there a way to tell broccoli to *not* generate a `vendor.css`?

**Comment by stefanpenner** [comment]
is anything in vendor.css?

**Comment by ianwalter** [comment]
I'm wondering the same. I have nothing in my vendor.css but its still included in the index page when I run a build. Maybe it would be better to modify the logic to not include it if it's empty.

**Comment by stefanpenner** [comment]
> index page

feel free to remove the link from the index.html, and it should not be loaded

**Comment by johnunclesam** [comment]
I think a little logic can decide if it should be or not in building... maybe it can change based on environment... Can we add a logic for that file (vendor.css)? If empty not in index.html, if something then ok in. Can we?

**Comment by nathanhammond** [comment]
@johnunclesam this will be possible once I've extracted the default CSS handling to a newly-created ember-cli-css addon (assuming that it successfully gets through RFC).

**Comment by johnunclesam** [comment]
@nathanhammond so this is coming in future? Awesome.
