### ISSUE TITLE
Cannot read property 'scope' of null

### ISSUE THREAD

**Issue by olegdovger** [ember-cli/ember-cli#4609]
What does this mean?

Ember.Object.extend._controllerForNode 		@ VM7257:4047
Ember.Object.extend._nodeHasOwnController 	@ VM7257:4025
Ember.Object.extend._shouldShowNode 		@ VM7257:3985
(anonymous function) 						@ VM7257:3953
Ember.Object.extend._appendNodeChildren 	@ VM7257:3952
(anonymous function) 						@ VM7257:3958
Ember.Object.extend._appendNodeChildren 	@ VM7257:3952
Ember.Object.extend.viewTree 				@ VM7257:3601
(anonymous function) 						@ VM7257:3557
fn 											@ ember.debug.js:403
Queue.invoke 								@ ember.debug.js:901
Queue.flush 								@ ember.debug.js:965
DeferredActionQueues.flush 					@ ember.debug.js:765
Backburner.end 								@ ember.debug.js:158
Backburner.run 								@ ember.debug.js:226
executeTimers 								@ ember.debug.js:648
(anonymous function) 						@ ember.debug.js:637

version: 1.13.6
node: 0.12.0
npm: 2.13.2
os: darwin x64

**Comment by stefanpenner** [comment]
Please provide the full trace and if possibles standalone repo that demonstrates the issue in isolationi

**Comment by stefanpenner** [comment]
will gladly reopen, if if the about questions are answered
