### ISSUE TITLE
Slightly confusing update directions: command seperator

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-cli#4613]
Admittedly this is nit-picky, but I think about it every time I update.

I think that the `--` that seperates each command and description - should be replaced with **any** separator that isn't something actually used in the command. 

`npm install --save-dev ember-cli@1.13.7 -- Update project's package.json to use latest version.`

**Comment by stefanpenner** [comment]
> npm install --save-dev ember-cli@1.13.7 -- Update project's package.json to use latest version.

upgrade docs look correct: https://github.com/ember-cli/ember-cli.github.io/blob/master/_posts/2013-04-03-upgrading.md

We will make sure all changelogs going-forward take this into account, thanks for the tip
