### ISSUE TITLE
1.13.7 addon does not compile styles into vendor.css

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#4615]
I have `addon/styles/split-view.css` in the `ember-split-view` addon. This css used to be included in `vendor.css` but after upgrading to 1.13.7 it is not being included.

I've read all the docs I can find and they seem to say that `addon/styles/*` should be compiled in.

What's the correct way to do this?

**Comment by vitch** [comment]
Does it need to be named `addon/styles/addon.css`? I've run into that before with SASS when you want the preprocessor to be triggered (although I guess if it changed between versions of ember-cli it might be a bug)

**Comment by BryanCrotaz** [comment]
no, that didn't work either.

**Comment by BryanCrotaz** [comment]
See https://github.com/ember-cli/ember-cli/issues/1853

**Comment by alexismangin** [comment]
Is there any solution for this issue?

**Comment by stefanpenner** [comment]
will reopen if a reproduction is provided on latest

**Comment by jmasson** [comment]
@stefanpenner I can confirm I'm having what I believe is the same issue after just upgrading to `1.13.13` (was previously on `1.13.8`, I upgraded after reading this issue thread).

I have `addon/styles/addon.scss` and it's contents are not carried through into the app that I'm using my add-on in. The rest of the component (component itself, template, a helper) works fine, just no stylesheet.

**Comment by stefanpenner** [comment]
> @stefanpenner I can confirm I'm having what I believe is the same issue a

If you can provide a repo, with an isolated reproduction we can reopen.
