### ISSUE TITLE
Cannot import vendor files in an addon using app.import [1.13.7]

### ISSUE THREAD

**Issue by OrKoN** [ember-cli/ember-cli#4616]
I have added the following to index.js:

```
  included: function(app) {
    this._super.included(app);
    app.import('vendor/polymer-gestures.js');
  }
```

I have put polymer-gestures.js to the vendor folder of the addon. After I install the addon and run the app I get `TypeError: undefined is not a function`. 

According to this doc: http://www.ember-cli.com/extending/#importing-dependency-files

P.S. looks like app.app.import is the right function. But app.app looks strange and does not match the docs.

**Comment by stefanpenner** [comment]
this is expected behavior. Like all things NPM, if the root module (your app) wants full access to it, then it must also directly depend on it.

**Comment by OrKoN** [comment]
@stefanpenner this all is in the addon. app.import is undefined but documented here: http://www.ember-cli.com/extending/#importing-dependency-files

**Comment by stefanpenner** [comment]
can you provide a repo that demonstrates this issue?

**Comment by OrKoN** [comment]
In the file you referenced there are the following lines:

```
if (app.app) {
  app = app.app;
}
```

I have figured that out too: see my [repo](https://github.com/ember-cli-vcl/gesture-support/blob/master/index.js#L8). So `app.app.import` works but there is no `app.import`.

**Comment by sglanzer** [comment]
@stefanpenner I assume this is the case only for nested addons?  So for example if I need liquid-fire as a dependency for an addon it needs to be installed by the app, or liquid-fire needs to be patched to include the nested addon check as per https://github.com/rwjblue/ember-cli-pretender/commit/33e5794f5aef545f00995435d08cb471e79a3bae
