### ISSUE TITLE
Addon directory not watched when addon name differs in package.json and index.js

### ISSUE THREAD

**Issue by vitch** [ember-cli/ember-cli#4618]
Here's a very tricky to track down but luckily easy to replicate issue I ran into while developing an ember-cli addon today.

Basically, if the name of your addon is different in `package.json` and `index.js` then the filesystem watcher will silently ignore any changes in your `app/` and `addon/`and won't retrigger a build.

Here's how to reproduce (tested with ember-cli `1.13.7` but my app was broken back to `1.13.1` while I was trying to debug so I assume it's always been this way):

```bash
ember addon bug
cd bug
ember s
```

Then in another terminal let's touch a file and confirm that a rebuild is triggered:

```bash
touch addon/myfile.js
```

Now let's change the name in `index.js` and start ember again:

```bash
sed -i '' 's/bug/bug2/' index.js
ember s
```

Then in the other terminal we can touch the file again but no rebuild is triggered.

Changing the name in `package.json` to `bug2` to match what's in `index.js` (`sed -i '' 's/bug/bug2/' package.json`) makes stuff work again.

Is this expected behaviour? Is there any reason to allow different names? If the names should be the same then we could either error when they aren't or maybe change the default `index.js` to something like:

```javascript
/* jshint node: true */
'use strict';

module.exports = {
  name: require('./package.json').name
};
```

**Comment by stefanpenner** [comment]
Can you name it the same?

**Comment by vitch** [comment]
I can and I now have in my addon. 

The problem was that I had no idea that having the different names would break the file watching! And it wasn't simple to track down what was responsible for the problem.

Is there any valid reason to have different names in each place? If so then we'd need to figure out why that breaks the watching. If there is no valid reason then we can make it so that there is only one source of truth for the name (my suggestion is the simplest way to do this without groking all of the code but I'm sure there is a better way - maybe getting rid of the name in `index.js` completely?)...

**Comment by stefanpenner** [comment]
having the name out of sync will lead to issues. Sometime soon we will try to massage this to not cause grief or to warn, but it seems somewhat low priority. Closing for now, but would accept PR to address
