### ISSUE TITLE
windows ergonomics

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4626]
- [x] detect if symlinks are available or not
- [x] provide useful  warning if they are not
  - likely "without symlinks enabled you will experience poor performance, see <link site> to address"
- [x] update section on website if someone thinks they can make it clearer (windows should likely also just be its own easy to find section)
  - provide some numbers, so people understand the magnitude of difference.
     for a vanilla app on system with SSD:
     - 40,000ms initial builds without, 6,000ms with
     - 38,000ms incremental builds without, 1,500ms with
     - still not great, but better and more performance work is planned

  - run `ember install ember-cli-windows`
  - run `ember windows`
  - start shell with administrator privileges  (i thought with the script, this was not needed but it appears to be?)

@felixrieseberg thoughts – am I missing anything?

**Comment by kellyselden** [comment]
Perhaps we can add to the documentation list if not there already:
- Encryption software
- Antivirus software
- third-party filesystem indexing search software

All these have added to frustration on enterprise work PCs in my experience. If anyone can concur or prove me wrong, it would be appreciated. These aren't necessarily truths.

**Comment by felixrieseberg** [comment]
Looks great to me - the script will merely disable the search index and the scanner for the current tmp folder, but it won't do anything about enabling symlinks (those remain available only to admins).

**Comment by stefanpenner** [comment]
> but it won't do anything about enabling symlinks (those remain available only to admins).

Ah, unless the user adds it to there own policy.

Is there a way to automate ^ ?

**Comment by felixrieseberg** [comment]
Yes, there should be - we could just put that into ember-cli-windows?

**Comment by stefanpenner** [comment]
> Yes, there should be - we could just put that into ember-cli-windows?

If its possible then yes absolutely!

**Comment by kellyselden** [comment]
@felixrieseberg Not sure if you're aware, but broccoli updates are moving the tmp folder from the project folder to the system temp folder. `ember-cli-windows` might need an update for that.

**Comment by stefanpenner** [comment]
> but broccoli updates are moving the tmp folder from the project folder to the system temp folder.

Yes, hopefully soon. Well the goal is to make it configurable, but default it to whatever is best given the current platform.

**Comment by felixrieseberg** [comment]
That is fantastic, I wasn't aware. It would be most ideal if we had a known subfolder in /tmp - that way, we could still reasonably exclude the tmp files from the internal malware scanner.

**Comment by jornh** [comment]
> provide useful warning if they are not
> likely "without symlinks enabled you will experience poor performance, see to address"

Looks like the place to link to and add info on `ember-cli-windows` in the documentation is http://www.ember-cli.com/user-guide/#symlinks-on-windows

Currently that section is well hidden in the middle of https://github.com/ember-cli/ember-cli/blob/gh-pages/_posts/2013-04-03-common-issues.md. But maybe that's not a big issue if just there were such a link when running Ember CLI and maybe(?) a cross link from https://github.com/ember-cli/ember-cli/blob/gh-pages/_posts/2014-04-03-getting-started.md

**Comment by stefanpenner** [comment]
> a cross link from https://github.com/ember-cli/ember-cli/blob/gh-pages/_posts/2014-04-03-getting-started.md

this sounds good

> But maybe that's not a big issue if just there were such a link when running Ember CLI and maybe(?)

Ya likely. but combined with the cross link i suspect our bases will be covered.

@jornh do you  have free moments to add the crosslink?

**Comment by jornh** [comment]
Yes, I can have a go at it later on the week ... I just noted there is also a (IMHO) hard to find section on `ember-cli-windows` under Overview/Home: http://www.ember-cli.com/#windows - would it be better relocating that to where the other performance related stuff lives?

**Comment by tsing80** [comment]
I always need to type  the following in powershell in order to  run ember-cli-windows, should this mention in the guide?
```
 Set-ExecutionPolicy Unrestricted -scope Process
```

**Comment by kellyselden** [comment]
I wonder if it would be possible for `ember-cli-windows` to tell you you need to change your execution policy, or is that chicken and the egg, you need powershell to run first to tell you? @felixrieseberg

**Comment by felixrieseberg** [comment]
@kellyselden: Thanks for the suggestion, I just added that.

I have pretty bad news about symlinks though. It's complicated, so bare with me: If the user is part of the Administrators group and UAC is enabled (which should cover 99% of our Windows-running Ember Cli devs), a not-elevated command prompt will still not be able to create SymLinks. UAC strips SymLink rights from not-elevated prompts if the user is otherwise an admin. With the policy correctly set, only users who are otherwise not admins or systems with UAC disabled will be able to create SymLinks without elevated prompts.

As far as I can tell, this leaves three options:
 * Doing nothing
 * Relaunching in an elevated command prompt
 * Warning

I'd personally prefer warning - happy to provide code that does a quick if/else check to see if we're running as Admin and to warn if not.

**Comment by raytiley** [comment]
I wrote a little module that should be able to do the test. We can just probably put a check to this in the same place we do the upgrade / watchman check? I can try to submit a quick PR for this later.
https://www.npmjs.com/package/can-symlink

**Comment by felixrieseberg** [comment]
Oh, wonderful. I'd definitely be :+1: for that, because the fix (launching an elevated prompt) is a dead-simple fix - we probably just have to make sure users are aware that it's something they should do.

**Comment by stefanpenner** [comment]
> Relaunching in an elevated command prompt

can we trigger this programatically ?

**Comment by felixrieseberg** [comment]
Yes. We'd basically use child.spawn to run the current command (I assume we really only care about `ember serve`) in PowerShell, started elevated. UAC pops up, a new window opens, and the command is already running.

If you like the sound of that, I'm happy to PR.

**Comment by stefanpenner** [comment]
> If you like the sound of that, I'm happy to PR.

I do, if you want to do a quick hangout sometime (maybe before you implement) feel free to ping me. :)

**Comment by felixrieseberg** [comment]
Hangout sounds great - up for one today after 3?

**Comment by stefanpenner** [comment]
im free at 4

**Comment by felixrieseberg** [comment]
It's a date 💁🏼

**Comment by stefanpenner** [comment]
@felixrieseberg this is part of my new years resolution :)

**Comment by stefanpenner** [comment]
we have even added a big boost for non-symlink users recently \w future plans to improve further.
