### ISSUE TITLE
prefix assets path for production

### ISSUE THREAD

**Issue by ghost** [ember-cli/ember-cli#4641]
Hi,

for assets such as /assets/image.png, that I call in stylesheets, javascript etc...

I need to prefix or prepend a path to server.

so that /assets/image.png becomes /static/ember/memory/dist/assets/image.png for production.

where it will be served as ie: http://domain.com/static/ember/memory/dist/assets/image.png

i need to pass and use a STATIC_PATH variable when compiled/built for production that will be prefixed, or compile it so that it does it automatically.

I have checked ember-cli docs for assets compilation:
```
var app = new EmberApp({
   fingerprint: {
      prepend: '/static/ember/memory/dist/'
   }
});
```
however, this doesn't work as where the assets are being called the path doesn't change in production, unless it actually modified the path where it's called.

for example in styles.css if I call /assets/image.png somewhere, I need to prefix this with STATIC_PATH + /assets/image.png when in production.

the STATIC_PATH will look something like:

/static/ember/memory/dist/

I can add this manually for production in development, but then cannot test in development.

thanks for any response.

**Comment by asermax** [comment]
I'm having this same issue, seems like the `prepend` option isn't working anymore (it was working on older versions of the tool).

**Comment by lcplusplus** [comment]
My current solution (although there are some drawbacks) involves setting up the folder structure for assets in the "public" folder.

I decided that my development path would equal the server path, that way it doesn't have to be prefixed, it is already ready when it's compiled in dist. I simply then move the contents of dist folder starting with "static" onto the server for production.

However, if I move to something like S3, this will no longer work without prepend or 3rd party tools.

**Comment by stefanpenner** [comment]
is this still an issue? If so, it is most likely an issue in broccoli-asset-rev
