### ISSUE TITLE
initial build (due to babel / jshint /HTMLBars) is slow

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4645]
the focus has been large re-build time, as such the caches are lost between rebuilds.

To mitigate this I created https://github.com/stefanpenner/broccoli-persistent-filter work works quite well, but still needs windows support fixed.

In one of our large ember apps, this took the babel time down from (initial build) 60s -> 2-3s.

–––

Once we can persist this caches, we will likely make babel non-optional (yes with opt-out support for our CoffeeScript fans)

**Comment by stefanpenner** [comment]
- [ ] https://github.com/babel/broccoli-babel-transpiler/pull/52
- [ ] https://github.com/rwjblue/broccoli-jshint/pull/31
- [ ] https://github.com/ember-cli/ember-cli-htmlbars/issues/62

**Comment by rwjblue** [comment]
Submitted https://github.com/ember-cli/ember-cli/pull/4742 to update ember-cli-htmlbars@1.0.0.

**Comment by rwjblue** [comment]
broccoli-jshint and ember-cli-htmlbars sections of the above list are completed.

**Comment by stefanpenner** [comment]
I'll cut babel when I'm back to my desk :)

**Comment by stefanpenner** [comment]
[initial warm] Build successful - 15090ms.
[rebuild] Build successful - 6830ms.

Turns out it helps quite a bit. 36,000ms -> 15,000ms on warm boots. On some apps, this can save minutes. on ember itself it went from 50,000ms -> 15,000ms.

**Comment by stefanpenner** [comment]
This is available to all by ember-cli-htmlbars ember-cli-babel and ember-qunit.

Please note, the first build (cold build) will be as slow (slightly slower) then before. but resulting warm builds should be faster.

**Comment by kellyselden** [comment]
Awesome work @stefanpenner and @rwjblue

**Comment by stefanpenner** [comment]
thanks @kellyselden for helping with the windows stuff!
