### ISSUE TITLE
vendor/css/app trees invalidate each other

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4646]
this causes the other 2 trees to invalidate even if they are not stale.

- [x] app & vendor invalidations 
- [x] app & css (partially fixed, need to explore more cases where it is not)

Will post with details shortly.

**Comment by constantm** [comment]
Is this issue causing, for example, rebuilds of Sass even though a JS files was changed? If so, has there been any progress on this?

**Comment by stefanpenner** [comment]
fixed on all latest dependencies
