### ISSUE TITLE
Update build time in ember server is slow

### ISSUE THREAD

**Issue by damon-lanphear** [ember-cli/ember-cli#4650]
While running ember server locally during development sessions I see increasing build times with successive changes. The build times get to a point where I have to kill ember server with 'kill -9' (as 'ctrl-c' seems to be ignored) because the server daemon no longer reacts to file changes or responds to http requests. I've been limping along like this, but I can't imagine this is expected behavior since its slows the development process significantly.   

Here are my environment details:

 * OSX 10.10.4 
 * Ember 1.13.6
 * Node 0.12.7
 * Watchman: 3.3.0
 * Hardware: 2.2Ghz intel core i7, 16GB RAM

My application currently consists of: 

 * 8 js files, totaling 600 lines of code
 * 5 hbs templates, totaling 150 lines of handlebars markup
 * 1 scss stylesheet, totaling 64 lines of sass markup

Changes to the style sheet and template files appear to have the most significant impact on the builds times.

What follows is an example of the build times that I'm seeing:

    Build successful - 11516ms.
    
    Slowest Trees                                 | Total               
    ----------------------------------------------+---------------------
    Concat: Test Support CSS                      | 2321ms              
    Concat: Vendor Styles                         | 2044ms              
    Concat: Test Support JS                       | 1865ms              
    Concat: Vendor                                | 1864ms              
    SassCompiler                                  | 1836ms              
    Funnel: App JS Files                          | 905ms               
    
    Slowest Trees (cumulative)                    | Total (avg)         
    ----------------------------------------------+---------------------
    Concat: Test Support CSS (1)                  | 2321ms              
    Concat: Vendor Styles (1)                     | 2044ms              
    Concat: Test Support JS (1)                   | 1865ms              
    Concat: Vendor (1)                            | 1864ms              
    SassCompiler (1)                              | 1836ms              
    Funnel: App JS Files (1)                      | 905ms               
    
    file changed controllers/signin.js
    
    Build successful - 13390ms.
    
    Slowest Trees                                 | Total               
    ----------------------------------------------+---------------------
    Concat: Test Support CSS                      | 2656ms              
    Concat: Vendor Styles                         | 2330ms              
    Concat: Vendor                                | 2185ms              
    SassCompiler                                  | 2103ms              
    Concat: Test Support JS                       | 1817ms              
    Funnel: App JS Files                          | 1649ms              
    
    Slowest Trees (cumulative)                    | Total (avg)         
    ----------------------------------------------+---------------------
    Concat: Test Support CSS (1)                  | 2656ms              
    Concat: Vendor Styles (1)                     | 2330ms              
    Concat: Vendor (1)                            | 2185ms              
    SassCompiler (1)                              | 2103ms              
    Concat: Test Support JS (1)                   | 1817ms              
    Funnel: App JS Files (1)                      | 1649ms              
    
    file changed templates/signin.hbs
    
    Build successful - 12833ms.
    
    Slowest Trees                                 | Total               
    ----------------------------------------------+---------------------
    Concat: Vendor                                | 2779ms              
    SassCompiler                                  | 2442ms              
    Concat: Test Support JS                       | 2225ms              
    Concat: Test Support CSS                      | 2036ms              
    Concat: Vendor Styles                         | 1661ms              
    Funnel: App JS Files                          | 1064ms              
    
    Slowest Trees (cumulative)                    | Total (avg)         
    ----------------------------------------------+---------------------
    Concat: Vendor (1)                            | 2779ms              
    SassCompiler (1)                              | 2442ms              
    Concat: Test Support JS (1)                   | 2225ms              
    Concat: Test Support CSS (1)                  | 2036ms              
    Concat: Vendor Styles (1)                     | 1661ms              
    Funnel: App JS Files (1)                      | 1064ms              
    
    file changed controllers/signin.js
    
    Build successful - 15537ms.
    
    Slowest Trees                                 | Total               
    ----------------------------------------------+---------------------
    Concat: Test Support JS                       | 2893ms              
    Concat: Test Support CSS                      | 2844ms              
    Concat: Vendor                                | 2700ms              
    SassCompiler                                  | 2653ms              
    Concat: Vendor Styles                         | 2282ms              
    Funnel: App JS Files                          | 1203ms              
    
    Slowest Trees (cumulative)                    | Total (avg)         
    ----------------------------------------------+---------------------
    Concat: Test Support JS (1)                   | 2893ms              
    Concat: Test Support CSS (1)                  | 2844ms              
    Concat: Vendor (1)                            | 2700ms              
    SassCompiler (1)                              | 2653ms              
    Concat: Vendor Styles (1)                     | 2282ms              
    Funnel: App JS Files (1)                      | 1203ms              
    
    file changed controllers/signin.js
    
    Build successful - 17364ms.
    
    Slowest Trees                                 | Total               
    ----------------------------------------------+---------------------
    SassCompiler                                  | 3667ms              
    Concat: Test Support CSS                      | 3643ms              
    Concat: Vendor                                | 3262ms              
    Concat: Test Support JS                       | 2437ms              
    Concat: Vendor Styles                         | 2408ms              
    Funnel: App JS Files                          | 999ms               
    
    Slowest Trees (cumulative)                    | Total (avg)         
    ----------------------------------------------+---------------------
    SassCompiler (1)                              | 3667ms              
    Concat: Test Support CSS (1)                  | 3643ms              
    Concat: Vendor (1)                            | 3262ms              
    Concat: Test Support JS (1)                   | 2437ms              
    Concat: Vendor Styles (1)                     | 2408ms              
    Funnel: App JS Files (1)

                      | 999ms

**Comment by stefanpenner** [comment]
two things:

* please update to the latest version as 1.13.8 is out with many performance related fixes and report back
* If the problem persists please provide a repo demonstrating the issue.

**Comment by damon-lanphear** [comment]
Upgrading to ember-cli 1.13.8 has resolved this issue for me.

**Comment by stefanpenner** [comment]
Yay. Could you post your log output for reference?

**Comment by stefanpenner** [comment]
Also sharing the number of files in bower_components and app

**Comment by damon-lanphear** [comment]
The build logs after the update are below.  The number of files in bower_components is 405. The number of fils in app is 37.

```
ember server
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 8806ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Concat: Vendor                                | 2902ms              
SassCompiler                                  | 2463ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Concat: Vendor (1)                            | 2902ms              
SassCompiler (1)                              | 2463ms              
Babel (10)                                    | 1444ms (144 ms)     

file changed styles/app.scss

Build successful - 3247ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 2310ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 2310ms              

file changed styles/app.scss

Build successful - 3375ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 2581ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 2581ms              

file changed templates/components/organization-add.hbs

Build successful - 2490ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 1771ms              
Concat: Vendor                                | 131ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 1771ms              
Concat: Vendor (1)                            | 131ms               

file changed styles/app.scss

Build successful - 3648ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 2880ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 2880ms              

file changed templates/dashboard/organizations.hbs

Build successful - 2500ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 1756ms              
Concat: Vendor                                | 139ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 1756ms              
Concat: Vendor (1)                            | 139ms               

file changed styles/app.scss

Build successful - 3778ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 2973ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 2973ms              

file changed templates/dashboard/organizations.hbs

Build successful - 2250ms.
```

**Comment by stefanpenner** [comment]
Thanks. Looks like the remaining chunk is in the css preprocessor. Which is on my hit list
