### ISSUE TITLE
Ember-cli just keep installing node modules when new ember app is created.

### ISSUE THREAD

**Issue by v3ss0n** [ember-cli/ember-cli#4651]
Is that suppose to happen? Ember-cli just keep installing node modules when new ember app is created.

```
cd ~/prj/
ember new courier-embermdl

``` 

it taking so long and when i checked it , it keep installing node module after node modules , now the app folder is already 100 mb.

here is the path looks like : 
```
~/prj/courier-embermdl/node_modules/ember-cli/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/node_modules

```

**Comment by v3ss0n** [comment]
Now the `node_modules` folder inside app  is 214MB and then embercli crash with checksum error.
That is huge waste of my limited internet bandwidth. Is that a feature , or a bug ?

**Comment by kellyselden** [comment]
@v3ss0n you can run the command with the options `--skip-bower` and `--skip-npm` to stop it from downloading packages. But, the CLI needs all those packages to build your app.
```
shasum check failed 
```
looks to me like a network failure. Running `npm install` inside your project folder should, in theory, download only the packages you have left to get.

As for the large size, there is effort underway to get that smaller. Stay tuned.

**Comment by v3ss0n** [comment]
Ah , it is currenly a feature then, i hope i can copy that node_modules in a different place. Thanks, i never thought it will be that big :D

**Comment by v3ss0n** [comment]
i did npm install , but it does nothing and stopped, --verbose shows nothing out of ordinary too.
momemtjs is only used at /ember-cli-release folder , is is safe to skip it?

**Comment by stefanpenner** [comment]
This isn't really a feature of ember-cli, rather a "feature/unfortunate thing" of npm/node, ir irks me to no end.

* in npm v2 the cache doesn't seem to get hit enough (v3 seems to improve this)
* https://github.com/ember-cli/ember-cli/issues/4211 will enable us to remove one of our largest dependencies `bower` reducing size
* I've been thinking of doing something funky with symlinks, to keep modules shared. Unfortunately, this out-of-the-box will have some issues with other npm features. It is still likely the most promising thing.

> i did npm install , but it does nothing and stopped, --verbose shows nothing out of ordinary too.
> momemtjs is only used at /ember-cli-release folder , is is safe to skip it?
> Installing packages for tooling via npm
> shasum check failed for /tmp/npm-19479-1581f73c/registry.npmjs.org/moment/-/moment-2.10.6.tgz
> Expected: 6cb21967c79cba7b0ca5e66644f173662b3efa77
> Actual:   9b1780b3589682e7df6d2fcfd496d0b5b96414ed
> From:     https://registry.npmjs.org/moment/-/moment-2.10.6.tgz
> Error: shasum check failed for /tmp/npm-19479-1581f73c/registry.npmjs.org/moment/-/moment-2.10.6.tgz
> Expected: 6cb21967c79cba7b0ca5e66644f173662b3efa77
> Actual:   9b1780b3589682e7df6d2fcfd496d0b5b96414ed
> From:     https://registry.npmjs.org/moment/-/moment-2.10.6.tgz
>     at /home/v3ss/node_modules/ember-cli/node_modules/npm/node_modules/sha/index.js:38:8
>     at ReadStream.<anonymous> (/home/v3ss/node_modules/ember-cli/node_modules/npm/node_modules/sha/index.js:85:7)
>     at ReadStream.emit (events.js:129:20)
>     at _stream_readable.js:908:16
>     at process._tickCallback (node.js:355:11)
> ~/w/m/webui >>>

unfortunately, this is seems an npm bug. You may want to report it over there.

**Comment by v3ss0n** [comment]
it was connectivity problem , i located moment-js folder inside node_module/ember-cli-release and then i did nmp install in that folder.

nmp resuming there but it is reinstalling everything , it install another ember-cli inside it . 

I think this is what happens when universe is divided by zero :D

**Comment by v3ss0n** [comment]
Now finally it finish (or is it?) , whew , Astounding 347 MB! The size of a full GUI Desktop OS ..

**Comment by stefanpenner** [comment]
> npm resuming there but it is reinstalling everything , it install another ember-cli inside it .

ah, FYI: running `npm install` in one of your own dependencies, will also install there development dependencies (why you got ember-cli again). If you fixup one of your own dependencies, I recommend you use `npm install --production`, this will only install there production dependencies.

Note, each ember-cli addon, depends on ember-cli but only for development.

**Comment by stefanpenner** [comment]
> I think this is what happens when universe is divided by zero :D

ROFL

**Comment by stefanpenner** [comment]
hmm looks like some of our deps have grown larger then i suspect they intend to.

<img width="525" alt="screen shot 2015-08-11 at 7 07 51 am" src="https://cloud.githubusercontent.com/assets/1377/9199526/bd0a69ce-3ff7-11e5-8d5a-b8719ab78235.png">

**Comment by v3ss0n** [comment]
> Note, each ember-cli addon, depends on ember-cli but only for development.

Thanks , i just started ember. Also i do not usually use npm/node for UI development.

**Comment by stefanpenner** [comment]
> Thanks , i just started ember. Also i do not usually use npm/node for UI development.

Ya, it has its quirks. But was chosen because it appears to be "the thing" web devs mostly use.

**Comment by stefanpenner** [comment]
going to do a filesize audit https://github.com/ember-cli/ember-cli/issues/4652

**Comment by v3ss0n** [comment]
thanks.

**Comment by Ugochukwu101** [comment]
> hello there, I'm a quote

**Comment by juanfurattini** [comment]
I had this problem too. I execute ember new app_name and never finished. The problem is that there are several files or dependencies located at .npm folder that requires sudo permissions. So you can just hit sudo ember new app_name, or to fix this you could just do sudo chown -R $(whoami) ~/.npm

**Comment by nathanhammond** [comment]
@juanfurattini Using sudo to generate a new app is not a recommended setup. It's likely that your original installation of node/npm is messed up as it should not require sudo in order to install. Your second suggestion fixes the broken install and is what should be done.
