### ISSUE TITLE
filesize audit

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4652]
some of our common deps of grown large again

<img width="525" alt="screen shot 2015-08-11 at 7 07 51 am" src="https://cloud.githubusercontent.com/assets/1377/9202202/93d3a85a-4005-11e5-9289-57429f8167f3.png">

i'm going to go through the deps this morning and prune / open issues

- [x] RSVP shouldn't publish its tests reduces all installs of RSVP by 800KB  https://github.com/tildeio/rsvp.js/commit/870e8d537a213b94e4159347e91b85ffd427f0c8
  * in npm v2 there are 13 copies... so this translate to about 10MB saving once uncompressed...
  - [x] leak bundles RSVP – pending https://github.com/twokul/leek/pull/27
- [x] display file-size as part of ember-cli release (and also display near what it should be, to help catch issues)  -> https://github.com/ember-cli/ember-cli/pull/4654
- [ ] explore packaging ember-cli with npm v3 – as it will auto-dedupe  – lets make sure it doesn't create broken bundles for old clients (technically it shouldnt)
  - [ ] v3 doesn't yet support `pack` with node_module trees this size https://github.com/npm/npm/issues/9239 – **note: this will be nice, it reduces the on-disk file count by nearly 1/3 **

- [ ] pending https://github.com/juliangruber/brace-expansion/pull/7 brace-expansion
- [x] https://github.com/cibernox/ember-disable-proxy-controllers/pull/3 (8MB)
- [ ] https://github.com/socketio/socket.io-parser/issues/30 unused gif [1.3MB)
- [x] broccoli-jshint tests https://github.com/rwjblue/broccoli-jshint/pull/30
- [ ] explore dedupe now with recent npm v2
- [x] let @sebmck know re: babel 22MB – although its likely not really a high priority for them to change (don't blame them)

*note: an alternative NPM install, that prefers symlinks when possible, may result in the best experience here, although that is a boil the ocean solution...*

**Comment by TrySound** [comment]
@stefanpenner Just installed mkdirp. Only 43 931 bytes.

**Comment by stefanpenner** [comment]
@TrySound yes but, since NPM v2 doesn't dedupe there are like 30 copies of it in our typical tree)

**Comment by TrySound** [comment]
@stefanpenner Add mkdirp as fake dep to simulate dedupe isn't good way?

**Comment by stefanpenner** [comment]
> @stefanpenner Add mkdirp as fake dep to simulate dedupe isn't good way?

that would require us adding it to our consumers package.json

**Comment by TrySound** [comment]
@stefanpenner Not sure I understand. Why customers add it as dep if it will be added to ember-cli deps?

**Comment by stefanpenner** [comment]
> @stefanpenner Not sure I understand. Why customers add it as dep if it will be added to ember-cli deps?

because there common dependencies also suffer the same problem?

**Comment by stefanpenner** [comment]
until NPM v3 pack works, and the linker/packager work lands. I suspect we wont see to much more improvement here.

Some of our upstream deps need to still fix themselves
