### ISSUE TITLE
Disable mock server from command line

### ISSUE THREAD

**Issue by mike-post** [ember-cli/ember-cli#4655]
Many folks run `ember serve` with the proxy option in order to have some or all of their XHRs proxied over to another web server (rails, etc). As of ember-cli 1.13.8, the defined behavior is to first send requests to the mock server and then, if they are unfulfilled, send them to the proxied server. This works for some scenarios, but not all.

**Example**
1. dev-A writes the ember code and stands up a mock server because nothing else is available
1. dev-B later writes some java/ruby code
1. finally everyone wants to verify the code integrates at least on their dev boxes by running `ember serve --proxy http://localhost:3000`, but this always hits the mock server and never goes through to the real server.

You can of course [hack up your mock server](http://discuss.emberjs.com/t/how-to-disable-http-mock-server-within-environment-config-file/6660/9?u=saladfork) to detect when a proxy is running and simply bail, but what if you want the originally described pass through behavior?  It seems like a better solution is to have a command line flag that disables the mock server. Example: `ember serve --proxy http://localhost:3000 --mock-server false`

**Comment by stefanpenner** [comment]
feature requests should go through the RFC process
