### ISSUE TITLE
ember-cli-sass issues

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/ember-cli#4658]
I'm trying to upgrade our app from 1.13.1 to 1.13.8, and it seems as though something that changed in ember-cli is causing ember-cli-sass to no longer work correctly in our app.  This is in the output of `ember serve`:

```
File: /client/tmp/broccoli_merge_trees-output_path-RyKypChr.tmp/app/styles/app/nav.scss (16)
Undefined variable: "$list-group-active-color".
Error: Undefined variable: "$list-group-active-color".
    at options.error (/client/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:276:32)
```
If I revert only ember-cli back to 1.13.1 the error goes away and things work as expected.  I saw this in earlier releases in the 1.13.x series but didn't get a chance to report the issue until now.

I wasn't sure if this was an ember-cli issue or not, but I thought it made sense to start here since this is the only thing in the app that has changed prior to seeing this error.  If this is an issue in ember-cli-sass I can open an issue there instead.

Current setup:
```
version: 1.13.8
node: 2.5.0
npm: 2.13.4
os: darwin x64
```

**Comment by Dhaulagiri** [comment]
[Here's a repo that approximates my use case and demonstrates the error](https://github.com/dhaulagiri/ember-cli-sass-test)

**Comment by stefanpenner** [comment]
@Dhaulagiri can you provide a isolated repo that demonstrates this problem?

**Comment by Dhaulagiri** [comment]
I'll try. The stylesheet that is causing the problem is unfortunately private, so a direct reproduction is not as easy as I had hoped.

**Comment by Dhaulagiri** [comment]
The only place I can reproduce this so far is in our main app.  There seems to be some issue resolving imports in .scss files.  I'll re-open if I'm able to reproduce or get more detail.

**Comment by Dhaulagiri** [comment]
The issue ended up being that we had both a `main.scss` file with all our imports and an `app.scss` file.  Something seems to have changed whereby the build process was looking at `app.scss` first which caused things to bomb since it relied on imports-not-yet-imported from `main.scss`.  Solution was to rename `app.scss` to something else and move `main.scss` to `app.scss` and then remove this block from our `ember-cli-build`:

```
 css: {
          'main': '/assets/app.css',
        },
```

**Comment by searls** [comment]
I believe this may be worth reopening, as it's clearly a regression in this one odd-ball case. I'll try to repro in a small app.

**Comment by Dhaulagiri** [comment]
[Repro app](https://github.com/Dhaulagiri/ember-cli-sass-test)

**Comment by jayeff** [comment]
Not the same but potentially similar problem could be this: https://github.com/aexmachina/ember-cli-sass/issues/73

Changes to SCSS files outside of app/styles (eg. in app/components/foo-bar/_styles.css) are recognized but not recompiled. This too works fine with 1.13.1 and stopped working with 1.13.5.

**Comment by aexmachina** [comment]
Several users [are reporting](https://github.com/aexmachina/ember-cli-sass/issues/73) that styles in pods are no longer working in ember-cli-sass. Apparently it did work in ember-cli 1.13.1 but [stopped working in 1.13.5](https://github.com/aexmachina/ember-cli-sass/issues/73#issuecomment-140121595). Looks to be an ember-cli issue to me because ember-cli-sass hasn't changed.

**Comment by jayeff** [comment]
@stefanpenner: Can you maybe give some hints on where you would start debugging this issue? I probably would have some time this weekend to look into it; as I'm not familiar with the ember-cli codebase at all some rough ideas what to look at would be fantastic.

**Comment by stefanpenner** [comment]
> Can you maybe give some hints on where you would start debugging this issue?

node debug can help

**Comment by aexmachina** [comment]
There's some packages for debugging broccoli trees too, but I haven't used them. https://www.npmjs.com/package/broccoli-debug

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/broccoli-stew
- https://github.com/stefanpenner/broccoli-stew/blob/master/lib/log.js#L27
- https://github.com/stefanpenner/broccoli-stew/blob/master/lib/debug.js#L12

**Comment by tomoguisuru** [comment]
@stefanpenner is there any resolution on this issue?

**Comment by stefanpenner** [comment]
I haven't tried sass. But less works as expected in 1.13.13. As long as all the deps are up to date

**Comment by northborn** [comment]
+1 Also experiencing this issue, we are not in a state where we can simply revert to an older version, so every SCSS change has to be followed by a server restart. Please fix this.

**Comment by cottrellio** [comment]
+1 Same issue here with ember-cli 1.13.8

**Comment by stefanpenner** [comment]
my end seems to work correctly, I will reopen if a reproduction on latest can be provided.

**Comment by sglanzer** [comment]
I'm encountering this issue in 1.13.13 - will try to provide a repo.  Re-compile works when the scss files are located in app/styles, but doesn't work for scss files in pods.

**Comment by Dhaulagiri** [comment]
This issue seems to have gotten co-opted somewhat from my original report, but I did confirm today with latest ember-cli beta that my original issue still persists.  I updated my [sample repo](https://github.com/Dhaulagiri/ember-cli-sass-test) to demonstrate.

The issue with sass not reloading files in pods seems completely separate?

**Comment by stefanpenner** [comment]
@Dhaulagiri thanks

**Comment by stefanpenner** [comment]
> The issue with sass not reloading files in pods seems completely separate?

yes most likely something unrelated

**Comment by sglanzer** [comment]
We can raise a new issue for the pods - this is the issue that was linked from ember-cli-sass

**Comment by jayeff** [comment]
@stefanpenner I'm quite sure that they are unrelated. I will do some additional research and open a separate issue for the reloading files from pods (iff the issue still persists on latest)

I did some digging regarding the original issue raised by @Dhaulagiri. I could track down the issue to the second commit of PR #4440 (7928cbc). Before this commit after merging of the `outputPaths` in lib/broccoli/ember-app.js I see only a single entry in app.css:

```
[...]
css: { main: '/assets/app.css' },
[...]
```

After this commit I see two entries:

```
[...]
{ css:
      { main: '/assets/app.css',
        app: '/assets/ember-cli-sass-test.css' },
[...]
```

Building of ember-cli-sass-test.css fails the build because it only includes app.scss which does not [`@import variables;`](https://github.com/Dhaulagiri/ember-cli-sass-test/blob/527d8f9e5acee5fa9baf1d85177feeafdb06f5cf/app/styles/main.scss) (as main.scss does) but does reference [`$color`](https://github.com/Dhaulagiri/ember-cli-sass-test/blob/527d8f9e5acee5fa9baf1d85177feeafdb06f5cf/app/styles/app.scss#L2)

I don't know how to fix this issue but maybe these infos can help you with fixing it.

**Comment by kylenathan** [comment]
It looks like the issue isn't present in 1.13.8 but is present again in 1.13.13. So a regression introduced in 1.13.5, inadvertently fixed somewhere between there and 1.13.8 and then reintroduced between 1.13.8 and 1.13.13. Will dig futher if I can find time.

**Comment by stefanpenner** [comment]
a repo with reproduction would be handy in figuring out whats up.

**Comment by kylenathan** [comment]
Will do and will add this as a separate issue so that we stop spamming @Dhaulagiri

**Comment by stefanpenner** [comment]
Will reopen if a repo reproducing the issue is provided on latest

**Comment by munsellj** [comment]
FYI for anyone visiting this in the future. We were able to solve this by adding the `app` directory that our pods styles were under to the included paths in sass options (this is an `ember-cli-sass` option).

Add paths for watching in the 'ember.cli-build.js':
```
var app = new EmberApp(defaults, {
  sassOptions: {
    includePaths: ['app']
  }
});
```
