### ISSUE TITLE
slower the expected production builds

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4662]
production builds will always come at a penalty, uglification and such. But there have been some reports of extremely slow builds.

problems

* [x]  lack of visible into why
  - [x] uglifying asm files, or already minified files can cause grief, we should inform the user if something bad happens
  - [ ] other parts of the pipeline (like the new SRI code) may have some build time issues
- [x] lack of work-arounds
  - [x] how do i spike a specific file from being uglified ? etc.

tasks:

* [x] debug logging for uglify 
* [ ] runtime warning saying which input cause uglify to be as slow as it was.

related issues:

* uglify massive files (EMScripten output) -> https://github.com/ember-cli/ember-cli/issues/4055

**Comment by stefanpenner** [comment]
cc @slexton

**Comment by jonathanKingston** [comment]
SRI could probably benefit from caching; however I'm pretty behind on my fixes at the moment (ember-cli-eslint needs some love next).

**Comment by SlexAxton** [comment]
We're still seeing somewhat larger production build times, but our primary issue that we just tracked down was a combo of ember-cli fingerprinting and ember-intl.

In the new ember-intl, by default, they put every single locale file into your `dist/` folder. (They have since allowed you to add a whitelist, which is how we're fixing while we only have a single locale -- https://github.com/yahoo/ember-intl/issues/155 )

With fingerprinting on, the fingerprints get generated relatively quickly, but the regex that then gets run in order to find all instances of a file that needs to be replaced with a new fingerprinted name takes a sad amount of time.

We're digging into some other things we see taking more time than normal. SRI is definitely a current suspect, but not as big as I initially feared when I saw `fingerprint.enabled=false` give us so much speed back.

**Comment by SlexAxton** [comment]
(naturally, 600 locale files causes lots of extra uglifyjs time as well, even though something like that where the files are pre-built, it'd be cool to allow plugins to declare certain things that they're going to drop into your `dist/` folder as `already-minified-etc-etc`.)

**Comment by stefanpenner** [comment]
@SlexAxton that is a great stress case!

**Comment by SlexAxton** [comment]
You can probably just install ember-intl with default settings.

**Comment by stefanpenner** [comment]
> You can probably just install ember-intl with default settings.

Ya, FYI i believe ember-intl 2.0 beta addressed some of the issues.

**Comment by SlexAxton** [comment]
We're using 2.0 beta, that was the big change I think.

**Comment by SlexAxton** [comment]
You have to turn on this locales whitelist to not get 600 locales in `dist/` -- https://github.com/yahoo/ember-intl/issues/155#issuecomment-120836963

**Comment by stefanpenner** [comment]
I'm going to do work to raise awareness of "What is slow" ( via  better UX) So dev's can figure this stuff out easier themselves, and also fix the issues easier.

@SlexAxton I noticed https://github.com/yahoo/ember-intl/commit/60c7b5417b7a05d67a9ee2a9d0729f124d54a08d which lead me to believe it was improved.

@jasonmit maybe the defaults should be rejiggered?

**Comment by SlexAxton** [comment]
Since we're using ember-intl but not doing any additional locales yet (just piping it for later translation), we just whitelisted `en-US` only. It took 4 minutes off our production build.

**Comment by SlexAxton** [comment]
> Alternatively, maybe there is an approach where this can be pre-built. And thus be near zero cost at ember-cli time?

That was my inclination when I said:

>  it'd be cool to allow plugins to declare certain things that they're going to drop into your `dist/` folder as `already-minified-etc-etc`

If there's something that an addon can declare 'production ready' that people don't have to recompute every time, I think that'd be a pretty big win. It'd be cool to be able to support 600 locales and not have it redo the same thing for 4 minutes each build.

**Comment by stefanpenner** [comment]
@SlexAxton you will be happy to know, this is a [design choice in](https://github.com/ember-cli/ember-cli/issues/4211)

**Comment by SlexAxton** [comment]
\o/

**Comment by stefanpenner** [comment]
Addons will be able to prepublish themselves built to `dist`, if dist isn't available, ember-cli will incur the built penalty. The goal of this, is to allow `npm link` to even `ember` to work. But obviously forcing everyone to build ember everytime will result in someone coming to my home and stabbing me in the eye.

**Comment by jasonmit** [comment]
> It took 4 minutes off our production build.

:cry: 

As @stefanpenner pointed to, that fix should address the speed issue as much as I possibly could solely on my end.  `rc1` will be released soon with this change.

**Comment by jonathanKingston** [comment]
@alexspeller updated SRI, not sure how bad it is on your builds (would be cool to see such a big site using SRI) The perf should only be looking at html files and their JS files. For bad files you could always stick `integrity=""` on the file too.

**Comment by alexspeller** [comment]
Did you mean to ping someone else?

**Comment by jonathanKingston** [comment]
Yup sorry; about that I picked the first Alex and hoped for the best it seems - @SlexAxton

**Comment by stefanpenner** [comment]
enable someone to opt out of uglification of a file.

https://github.com/ef4/broccoli-uglify-sourcemap/pull/11

**Comment by SlexAxton** [comment]
tite :+1: good work :clap: all around

**Comment by stefanpenner** [comment]
@slexAxton let me know if this works. I'm trying to figure out how to add public warning about slow uglify steps, but it isn't entirely obvious to me whats best.

I think I will add private logging via `DEBUG=broccoli*` that will provide timings... Maybe I should add public logging based on the size, and potential time to minify? Basically, if someone is trying to minify something > 2MB warn upfront.

@SlexAxton do you think ^ would help?

**Comment by SlexAxton** [comment]
That sounds reasonable, maybe with a setting in `.ember-cli` to silence it.

**Comment by SlexAxton** [comment]
Or also maybe > 20 separate files or something? Or over 2mb, total?

**Comment by jonathanKingston** [comment]
Just FYI turning off file hashing turns off SRI too

**Comment by stefanpenner** [comment]
additional logging do to time https://github.com/ef4/broccoli-uglify-sourcemap/pull/12 May benefit from upfront logging do to size as well. Although, I am unclear what size equates to "should warn" Would love to get recommendations, so we can close this out.

**Comment by rwjblue** [comment]
It is also possible for us to avoid minifying files that we have a pre-minified version of (Ember and jQuery both contain .min.js files that could be used instead...). Not sure if that is better/worse/in between....
