### ISSUE TITLE
Do not autogenerate templates/application.hbs when usePods:true

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-cli#4668]
It's just a minor issue, but whenever I update ember-cli and run `ember init` it re-creates the templates/application.hbs file, even though I set `usePods: true`. It would be nice if it would check for `usePods` and create the application template in the pods instead.

**Comment by rwjblue** [comment]
Ya, it is a tad bit annoying. I am not quite sure of the best path forward though. 

@trabus - What do you think?

**Comment by trabus** [comment]
Short term, I think it's probably going to need to stay an annoyance. There's not a simple easy way to compose blueprints right now, which is something I want to improve badly. We could probably hack something together, but I'm less inclined to so so for one file. 

Quick way to fix that other than moving it manually is to run `ember d template application -p` then `ember g template application` (note the `-p` flag is "inverted" when usePods is true, something else that desperately needs fixing). I wish I had a better answer, but I think this needs some thought and design so we don't end up with something worse.

**Comment by trabus** [comment]
After some more thinking on this, I may be able to add a custom fileMapTokens to the app blueprint, allowing the few files that are generated to be in the structure defined by the options (pod or classic).

This would be a short-term fix, longer term, I'd prefer to add some convenience methods to generate blueprints from inside a blueprint hook (beforeInstall or afterInstall), doing essentially what the resource blueprint currently does with the [processBlueprint method](https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L19). This would give us a way to generate the empty app shell, then generate all of the application files in the afterInstall hook of the app blueprint.
