### ISSUE TITLE
Could not find module `ember-cli-app-version/initializer-factory`

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4669]
Just bumped my add-on from 0.2.3 to 1.13.8 and the following error is being thrown:
Could not find module `ember-cli-app-version/initializer-factory` imported from `dummy/initializers/app-version`

What's odd is when I use the inspector I can see `ember-cli-app-version/initializer-factory`.

**Comment by stefanpenner** [comment]
Are there console errors?

**Comment by stefanpenner** [comment]
without a reproduction the reproduces this is hard to diagnose with certainty.

Easiest thing is to make a small example app that demonstrates the issue

**Comment by olivierlesnicki** [comment]
<img width="768" alt="ember-cli" src="https://cloud.githubusercontent.com/assets/1705944/9251702/6e7c3680-41cc-11e5-9ef1-87e4fe2f0b98.png">

**Comment by olivierlesnicki** [comment]
This is on a private repository I'm afraid.

**Comment by olivierlesnicki** [comment]
package.json
```
 "dependencies": {
    "broccoli-jscs": "0.0.22",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-less": "^1.3.3",
    "handlebars": "^3.0.3"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.3",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.0.0-beta.16.1",
    "ember-disable-prototype-extensions": "^1.0.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-try": "0.0.6",
    "express": "^4.13.3",
    "glob": "^4.5.3",
    "morgan": "^1.6.1"
  },
```

**Comment by olivierlesnicki** [comment]
bower.json
```
  "dependencies": {
    "base64": "~0.3.0",
    "ember": "1.13.7",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.16.1",
    "ember-data.model-fragments": "0.3.0",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "sinon": "http://sinonjs.org/releases/sinon-1.12.2.js"
  }
```

**Comment by olivierlesnicki** [comment]
"ember-disable-prototype-extensions": "^1.0.0" is to blame. Removed it, dummy add-on app working fine again.

**Comment by stefanpenner** [comment]
> This is on a private repository I'm afraid.

that is why i requested:

> Best thing is to make a small example app that demonstrates the issue

**Comment by stefanpenner** [comment]
> "ember-disable-prototype-extensions": "^1.0.0" is to blame. Removed it, dummy add-on app working fine again.

this isn't true, if you look at the top error, the problem is in model-fragments. I have opened an issue: https://github.com/lytics/ember-data.model-fragments/issues/115

**Comment by dguettler** [comment]
We had to update to PhantomJS 2.0.1 which resolved this issue. With PhantomJS 1.9.8 we ran into the module not found issue.

**Comment by imranjanwari** [comment]
This is a bug due to a new version of jQuery which ember is not yet able to handle.
In bower.json change "jquery": "^1.11.3" to "jquery": "1.11.3" and do bower install again. It should be fine now.

Check : http://stackoverflow.com/questions/34702284/getting-uncaught-error-assertion-failed-ember-views-require-jquery-between-1/34702715#34702715

**Comment by Nininea** [comment]
I have changed it too and got the exception : 

Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

:(
