### ISSUE TITLE
Ember 2.0

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4671]
ember-cli does support 2.0 out of the box, but it requires the user to adjust the appropriate bower and package.json entries. Now that obviously **isn't reasonable** (or something we s, so we should do this for our users. 1 catch, and that is ember-data's 2.0 is not quite yet out.

Proposed solution:

* provide 2.0.0.beta.x npm & git tag'd versions of ember-cli until such time as ember-data hits 2.0 (or 1.13.x release is made to work with ember 2.0.0)
* master branch of ember-cli will cater to 2.x
* 1.13-stable branch will cater to ember 1.13.x
* most work will happen on master, but critical bugfixes etc can be backported to 1.13-stable branch

related PR:

* https://github.com/ember-cli/ember-cli/pull/4666

Today I will:

- [x] do the above mentioned branching -> https://github.com/ember-cli/ember-cli/tree/stable-1-13
- [x] DEBUG https://github.com/ember-cli/ember-cli/pull/4666
- [x] release a ember-cli beta 
  - [x] depending on the next ED beta (ETA a few hours)

Next:

- [ ] addonified (getting the core libs of bower, will be a semver break, so gotta land that first)
  - [ ] ember https://github.com/emberjs/ember.js/pull/12412
  - [ ] ember-data https://github.com/emberjs/data/pull/3813

**Comment by kellyselden** [comment]
I wonder if we need to define our own special case of semver. We had beta versions of ED in our 0.x.x versions, but now that we are past 1.x.x, do we allow next major version betas of our major deps before bumping our major version?

**Comment by stefanpenner** [comment]
I suspect it depend if ED beta -> stable ED will be a semver break or not. cc @igorT / @bmac  / @wecc can you share your thoughts?

**Comment by bmac** [comment]
The live updating ManyArray#filterBy change currently in beta.1 is going be reverted because it broke existing apps. https://github.com/emberjs/data/pull/3263 That is the only breaking change that I know of between ED beta -> stable ED.

**Comment by stefanpenner** [comment]
@bmac is there an ETA for a beta 2 that includes this?

**Comment by bmac** [comment]
I should have the beta.2 out in a couple hours.

**Comment by stefanpenner** [comment]
> I should have the beta.2 out in a couple hours.

scholar and a gentleman.

**Comment by stefanpenner** [comment]
my branching plan:

ember-cil#master === beta
ember-cli#stable-1-13 === any work backported to the 1.13.x branch of the world

after ember@2.0.0 is released
ember-cli#master === canary
ember-cil#beta === beta
ember-cli#stable-x.y === any work backported to some given release (to help LTS)

**Comment by kellyselden** [comment]
@stefanpenner I agree with your above strategy.
The question of lockstepping I think comes back. When Ember 2.1.0 releases, do we quickly release CLI 2.1.0? Or do we work on our own release schedule?

**Comment by stefanpenner** [comment]
> do we quickly release CLI 2.1.0?

quickly. Typically we release on a weekend, ember-cli will likely release once both ember and ember-data release, so likely towards the tail end of the weekend, or monday morning.

**Comment by bmac** [comment]
@stefanpenner  Ember Data `v2.0.0-beta.2` is now released. Sorry it took so long.

**Comment by stefanpenner** [comment]
> @stefanpenner Ember Data v2.0.0-beta.2 is now released. Sorry it took so long.

no problem, thanks for the release :)

**Comment by balupton** [comment]
It's a bit strange how ember 2.0 is out, with the default docs now ember 2.0 docs, which say `npm i -g ember-cli` and `ember new my-new-app`, and then it installs ember 1.13 and not 2.0 - caught me off-guard. Perhaps the docs should get a mention that the CLI does not yet install ember 2.0.

Docs page: http://guides.emberjs.com/v2.0.0/getting-started/first-app/

**Comment by acorncom** [comment]
@balupton Could you create an issue / pull request on the Guides repo? (https://github.com/emberjs/guides)  It's something that's being watched, but would be great to clean up the verbiage so we don't confuse folks :-)

**Comment by bjreath** [comment]
FYI - Ember Data 2.0 release: https://github.com/emberjs/data/releases/tag/v2.0.0

**Comment by jornh** [comment]
@bjreath looks like it's already in: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L7 ... but I guess that's not the same as everything else is in place to cut a (beta) release of Ember CLI. I'm sure the project owners do what they can. Until then maybe best thing eager adopters can do is kick the tires on a git clone :smile:

**Comment by fidlip** [comment]
Hi guys, do you have any estimate regarding this issue?

**Comment by escobera** [comment]
I'd like to know aswell, even help if I can.

**Comment by stefanpenner** [comment]
> Until then maybe best thing eager adopters can do is kick the tires on a git clone

git clone isn't needed, simply update your bower + package.json's to match 2.0. Ember-cli isn't coupled to any version of ember.

**Comment by benoittgt** [comment]
Strange behavior is `ember -v` return `version: 1.13.8` but ember inspector `Ember 2.0.2`. So `ember -v` return the version of ember-cli.

Ember is not define in my package.json.

**Comment by topaxi** [comment]
@benoittgt `ember -v` shows the ember-cli version. The ember package is located in bower.json, not package.json :)

**Comment by benoittgt** [comment]
Oups thanks @topaxi you're completely right :+1:

**Comment by jtsom** [comment]
So.. what is the status of a new release of Ember-cli? It's been way over a month since the last version , with so much changing - both in the supporting libraries, and ember itself. Not to mention that since updating to Node 4.1.1, ember-cli gives an error "Future versions of Ember CLI will not support v4.1.1. Please update to Node 0.12 or io.js."

**Comment by ballPointPenguin** [comment]
fwiw, I'm using ember-cli@master with pretty good results and stability.

**Comment by jtsom** [comment]
How would I update my ember-cli to use master? instead of just the nom released version?

Thanks.

**Comment by jornh** [comment]
@jtsom see *Working with master* in https://github.com/ember-cli/ember-cli/blob/master/README.md

**Comment by marnen** [comment]
I have an Ember application that I'd like to upgrade to 2.0. If there will be an ember-cli release soon, I'll hold off till then; if not, I'll use master. So...what's the status of this? When can we expect a release?

**Comment by stefanpenner** [comment]
> When can we expect a release?

when it is released

> I have an Ember application that I'd like to upgrade to 2.0

if you update bower.json + package.json references to ember and ember-data all should work well, ember-cli really doesn't have an opinion about which ember version is runs.

**Comment by jnfingerle** [comment]
Since bower is complaining to me about unmet version constraints that have to be resolved manually: Is there an official set of recommended version of ember-cli-shims, ember-cli-test-loader, ember-load-initializers and loader.js for ember 2.x and ember data 2.x?

**Comment by dustinfarris** [comment]
Second @jnfingerle's point.  Totally understand the "it'll get here when it gets here" message, but the interim upgrade path isn't as simple as bumping ember and ember-data in bower/package.json.

**Comment by jtsom** [comment]
Sort of agrees with my comments here and other places. There are so many secondary libraries, it's hard to keep up when library A or B updates, or the latest Ember  or Ember Data need a slightly newer version of some other package.

**Comment by stefanpenner** [comment]
if you are curious what versions work, i recommend looking at: 

* https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json
* https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json

**Comment by marnen** [comment]
@jnfingerle: Exactly my question. This is why I don't particularly want to do the upgrade without some tool support.

**Comment by jnfingerle** [comment]
@stefanpenner Thanks. I wouldn't have taken this as "the current truth" without you encouraging it.

**Comment by marnen** [comment]
@stefanpenner For what it's worth, I just did this and it worked, though I do hope we have an actual release of ember-cli soon.

**Comment by stefanpenner** [comment]
> Next:
> 
>  addonified (getting the core libs of bower, will be a semver break, so gotta land that first)
>  ember emberjs/ember.js#12412
>  ember-data emberjs/data#3813

@marnen the checklist above must be completed first. The tasks will most likely require breaking changes, so they must land before 2.0 or after 3.0 which would be a non-trivial amount of time in the future.

**Comment by Turbo87** [comment]
@stefanpenner @rwjblue I have a feeling this issue can be closed now...
