### ISSUE TITLE
support the ability to run tests in parallel

### ISSUE THREAD

**Issue by jmonster** [ember-cli/ember-cli#4687]
We're currently exploring adopting [CircleCI to reduce our tests runtime through parallelism](https://circleci.com/docs/setting-up-parallelism). However, it's unclear how we might accomplish this with ember-cli right now.

I was curious if someone in the community may know a simple way to accomplish this?

If not, is there interest out there for this type of functionality? I would expect that, even locally, running tests locally could be accelerated by breaking the tests into N groups and executing them on multiple threads.

**Comment by stefanpenner** [comment]
> is there interest out there for this type of functionality?

yes

**Comment by patocallaghan** [comment]
@jmonster We no longer use Circle but when we did we took the following approach. Circle has an environment variable, `CIRCLE_NODE_INDEX`, as a way of identifying which container your tests are currently running in. Using a script you can then assign tests to each one. At Intercom we are broken down into teams so we group our tests accordingly and place the team keyword into each module description. For example:

```
module('Team A | Widget A', function() {
 ...
});
```

We then use something like the following bash script to run our tests in parallell. It uses the `--filter` keyword to run particular tests.

```
#Run suite of tests in parallel per team
group='';
case $CIRCLE_NODE_INDEX in
  0) group='General |';;
  1) group='Team A|';;
  2) group='Team B|';;
  3) group='Team C|';;
  6) group='JSHint -';;
esac
echo $group; node node_modules/ember-cli/bin/ember test --filter="$group";
```

I guess the drawback is that you have to add the team keyword but we have a separate script which runs before the tests and prevents the tests from running if any modules don't have a team assigned.

**Comment by jmonster** [comment]
@patocallaghan thank you so much for taking the time to offer that suggestion!

**Comment by stefanpenner** [comment]
I'm all for this, i think some of the LI guys have some WIP here. cc @chadhietala 

further investigation for new features should be done in an RFC
