### ISSUE TITLE
bower from the command line

### ISSUE THREAD

**Issue by MarkMT** [ember-cli/ember-cli#4691]
Both the changelog and the upgrade instructions in the user guide make references to invoking bower from the command line, e.g. `bower cache clean`, `bower install`. Neither my installation of ember-cli (1.13.8) nor my new app provides access to bower from the command line. I'm new to Ember - am I missing something or was something removed and hasn't been reflected in the docs?

**Comment by pichfl** [comment]
Following the [User Guide](http://www.ember-cli.com/user-guide/): You’ll need to install [Bower](http://bower.io), a package manager that keeps your front-end dependencies (including jQuery, Ember, and QUnit) up to date.

**Comment by MarkMT** [comment]
Thanks, missed that.
