### ISSUE TITLE
Watchman Error

### ISSUE THREAD

**Issue by walternate** [ember-cli/ember-cli#4694]
Here is the error output:

--------------------------------------------------------------------------

version: 1.13.8
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: shutdown ENOTCONN
    at exports._errnoException (util.js:746:11)
    at Socket.onSocketFinish (net.js:240:26)
    at Socket.emit (events.js:104:17)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at Socket.Writable.end (_stream_writable.js:459:5)
    at Socket.end (net.js:415:31)
    at ChildProcess.<anonymous> (/Users/amro/Documents/Dev/ember/ember-test/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:163:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)

--------------------------------------------------------------------------

Not sure what started this but when I remove watchman, the server fires up fine. I am running OSX Yosemite. I have tried several versions of Watchman (3.7, 3.3, 3.2, 3.1) and they all do the same thing where it was fine before. So there is obviously something else that is not playing nice with this. Thanks in advance for any help.

**Comment by wolodarsky** [comment]
It seems the fb-watchman version sane uses was bumped to 1.3.0 causing this error.

Have verified manually switching back to fb-watchman 1.2.0 resolves issue.

ember-cli: 1.13.8
watchman: 3.7.0
os x: 10.10.4
node: 0.12.7

Watchman doesn't seem to be outputting any errors to watchman log files.

**Comment by walternate** [comment]
@wolodarsky  Yep, that worked. Manually downgraded to 1.2.0 and watchman is back up. Thanks you! Now I can finally get some sleep.

So should that be downgraded in the ember-cli package for the time being (not sure if it's an easy fix)?

**Comment by wolodarsky** [comment]
Locking the fb-watchman version requirements would need to be corrected in the sane project's package.json as it is a nested dependency, and may not be desired.  The change may be needed in fb-watchman itself, but I haven't been able to isolate the issue (fb-watchman@1.3.0 was only pushed a few hours ago).

[`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) can be used to lock versions of nested dependencies for a project, but still would require manual change of the fb-watchman version anytime you needed to update any dependencies.

You can also add `"watcher": "node"` to your .ember-cli file for the time being to use NodeWatcher instead of watchman.

**Comment by vmalloc** [comment]
+1 - also hitting this issue and it's pretty annoying

**Comment by hhff** [comment]
samesies, downgrading

**Comment by hhff** [comment]
@wolodarsky / @walternate - how did you actually downgrade this?

**Comment by pwnall** [comment]
Just hit this on El Capitan. `brew uninstall watchman` fixed things for me.

**Comment by msalahz** [comment]
I used the following command ```npm install fb-watchman@1.2.0 --save-dev``` to downgrade but I got the same error again so I went to try @pwnall suggestion by using ```brew uninstall watchman``` and this fixed it for me

**Comment by wolodarsky** [comment]
@hhf please note I only manually downgraded to test that fb-watchman 1.3.0 was the issue.  This isn't reliable as it will be removed anytime you have to reinstall your dependencies.  [`npm shrinkwrap --dev`](https://docs.npmjs.com/cli/shrinkwrap) is the only way I know of to do this repeatably for your project, but is a bit of a pain.

@msalahz / @pwnall you can also add `"watcher": "node"` to your .ember-cli to stop ember-cli from using watchman without uninstalling it.  This may be preferable for the time being as watchman itself isn't the problem but the fb-watchman version package used by sane.  Any users that clone your app will also be covered by this.

**Comment by stefanpenner** [comment]
i'll some something new interim

**Comment by stefanpenner** [comment]
seems like a relevant issue is already open: https://github.com/facebook/watchman/issues/134

**Comment by stefanpenner** [comment]
I published a quickfixed version of broccoli-sane-watcher, where I bundled the exact version of fb-watchman known to work.

```
➜  broccoli-sane-watcher git:(master) ✗ npm publish ./broccoli-sane-watcher-1.1.2.tgz
+ broccoli-sane-watcher@1.1.2
```

**Comment by wez** [comment]
sorry about this. Pushed fb-watchman 1.4 with a speculative fix.

**Comment by wolodarsky** [comment]
@wez thanks for the quick fix.  I have verified 1.4 works with my setup:

ember-cli: 1.13.8
watchman: 3.7.0
os x: 10.10.4
node: 0.12.7

**Comment by stefanpenner** [comment]
i'll release an updated broccoli-sane-watcher

@wez thanks for the quick fix :)

**Comment by wez** [comment]
Thanks for verifying!
