### ISSUE TITLE
Some unit tests fail if ember-legacy-views is not installed

### ISSUE THREAD

**Issue by pichfl** [ember-cli/ember-cli#4699]
I really tried to find the proper tracker to report this problem.

I'm on Ember 2.0.0 and Ember data 2.0.0-beta.2 and if I don't have  ember-legacy-views installed, I'm getting errors like this:

```bash
not ok 25 PhantomJS 2.0 - Unit | Adapter | application: it exists
    ---
        actual: >
            null
        message: >
            TypeError: undefined is not an object (evaluating 'Ember.View.extend')
        Log: >
    ...
```

Code for the adapter:

```js
import DS from 'ember-data';
import config from '../config/environment';

export default DS.RESTAdapter.extend({
	host: config.APP.host,
	namespace: config.APP.namespace,
	headers: {
		// Basic authorization for dev server
		Authorization: config.APP.authorization,
		Accept: 'application/json',
	},

	ajax(url, type, hash) {
		// Adding trailing slash to avoid redirect. We should fix this in django, not ember.
		url = url + '/';
		return this._super(url, type, hash);
	},
});
```

Code for the test (Basically the stub generated by CLI): 

```js
import { moduleFor, test } from 'ember-qunit';

moduleFor('adapter:application', 'Unit | Adapter | application', {
	// Specify the other units that are required for this test.
	// needs: ['serializer:foo']
});

// Replace this with your real tests.
test('it exists', function(assert) {
	var adapter = this.subject();
	assert.ok(adapter);
});
```

This happens for three tests out of 42 on a pretty empty project.

**Comment by stefanpenner** [comment]
potentially an issue with: https://github.com/switchfly/ember-test-helpers ?

**Comment by pichfl** [comment]
It's a brand new project, I merely used `ember init` and created two models and a mixin, so unless ember-test-helpers is a dependency of ember-cli, this might originate somewhere else.

I'll try to recreate this in a separate project tomorrow.

**Comment by stefanpenner** [comment]
> so unless ember-test-helpers is a dependency of ember-cli,

yes it is

**Comment by rwjblue** [comment]
ember-qunit 0.4.9 has guards in place to handle when `Ember.View` is not defined.

What version of `ember-cli`, `ember-qunit`, and `ember-cli-qunit` are you using?

**Comment by pichfl** [comment]
package.json
ember-cli: 1.13.8
ember-cli-qunit: ^1.0.0

bower.json
ember-qunit: 0.4.9

**Comment by pichfl** [comment]
Okay, it seems I was hit by some weird stuck npm caching. Doing the npm cache clean and rm -rf tango once more and it was all gone.
