### ISSUE TITLE
[Feature Request] Shell completion

### ISSUE THREAD

**Issue by topaxi** [ember-cli/ember-cli#4702]
It would be nice to have shell (bash, zsh, etc.) completion, I always end up looking through `ember help` or `ember help generate` for available arguments or blueprints. I think completion could help here immensely.

**Comment by lazybensch** [comment]
I've implemented that feature locally and will create an RFC & PR today or tomorrow

**Comment by stefanpenner** [comment]
@lazybensch rad! been wanting this for ages.

**Comment by btecu** [comment]
This has been on the wishlist for a very long time... https://github.com/ember-cli/ember-cli/wiki/Wish-List

**Comment by Frozenfire92** [comment]
+1

**Comment by jhr007** [comment]
tl;dr: https://github.com/ember-cli/ember-cli/pull/4709

Apologies for necro'n a closed issue... but the close doesn't give a See Also, nor has web searches returned anything fruitful for Ember-CLI command line tab completion, even if it's something that can't be done or something I have to manually configure. 
*Drinks from beer before submitting(see tldr)*
Found the tldr link after finding this issue and these others.. 
https://github.com/ember-cli/rfcs/pull/23
https://github.com/ember-cli/ember-cli/pull/4576

:+1:
