### ISSUE TITLE
Ember-cli-1.13.8 installation taking forever

### ISSUE THREAD

**Issue by shivanibhanwal** [ember-cli/ember-cli#4703]
I have been installing ember since yesterday and still no luck. I check many posts some mention issue related to proxy and some mention issue with internet. However I am not using any proxy, our router is not blocking any site at the moment and also we do not have internet issue.

Here are details about the environment I am using
```
Mac OS X Yosemite 10.10.5 
node v0.12.2
npm 2.13.5
bower 1.4.1
```

Initially even I was not able to install the Bower package and it was running infinitely then I set registry 
`npm set registry https://registry.npmjs.org/`
After that when I ran `npm install -g bower` and it worked well

However same when I tried for the `ember-cli` it did not work
I am using this command to install ember globally and on this machine I am installing ember for first time
` npm install -g ember-cli`
After running this command I see cursor rotating all the time and no error message related to time out etc.

Then I tried command with info logs 
` npm --loglevel info install -g ember-cli`

And I see these logs and now it cursor keep rotating at this point and never finishes installation
```
npm info it worked if it ends with ok
npm info using npm@2.13.5
npm info using node@v0.12.2
npm info attempt registry request try #1 at 19:04:23
npm http request GET https://registry.npmjs.org/ember-cli
npm http 304 https://registry.npmjs.org/ember-cli
npm info retry fetch attempt 1 at 19:04:26
npm info attempt registry request try #1 at 19:04:26
npm http fetch GET https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
npm http fetch 200 https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
```

Post this I tried downloading the `ember-cli.zip` source and used `npm link` to set it as global and even that fails with a long error
`npm --loglevel info link`

See the debug-log here - https://gist.github.com/shivanibhanwal/c8af52a29406d23df91b

**Comment by stefanpenner** [comment]
if you are able to download the tarball without npm, you could do the following.

```
wget https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
npm install -g ./ember-cli-1.13.8.tgz
```

Alternatively, I've seen many environments fair much much better with `npm v3`. Although not all addons in the ecosystem work with it yet, ember-cli itself does.

This may be a good path to take.

**Comment by stefanpenner** [comment]
@shivanibhanwal this is likely something worth opening an issue on on NPM itself.

**Comment by shivanibhanwal** [comment]
@stefanpenner thank you for the response I will try the .tgz approach.
Yesterday I tried that symbolic link aproach that did not work. But I will it a try and update you here.
Sure I will also create a issue on NPM

Thanks

**Comment by shivanibhanwal** [comment]
After using 
```
wget https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
npm install -g ./ember-cli-1.13.8.tgz
```
Ember-cli got installed but 
`npm install ` in my app still does not work. I think it is issue with `npm` only.
I have created a issue on NPM.

**Comment by stefanpenner** [comment]
if the following worked, i don't think we can do terribly much (except for the above mentioned on-going efforts).

> wget https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
> npm install -g ./ember-cli-1.13.8.tgz


I'm going to close this issue in-favor of those existing efforts, if new information comes to light. I will gladly reopen
