### ISSUE TITLE
[Feature Request] Skip or configure ES6Modules tree

### ISSUE THREAD

**Issue by chrsjxn** [ember-cli/ember-cli#4706]
I'm working on converting a big app from using sprockets to using ember-cli. We're still using commonjs modules, and are probably not going to switch away from that any time soon.

I've got a simple addon written that takes our `.module.js` files and converts them to commonjs modules, but it causes the ember build to fail when building the application js tree. This is due to the `new ES6Modules()` tree below:

https://github.com/ember-cli/ember-cli/blob/16a93027d316e61755837cca88b378be3b6ccd0a/lib/broccoli/ember-app.js#L965 
```javascript
var appJs = new ES6Modules(
    new Funnel(applicationJs, ...)
  );
```

Right now the only workaround that I can see is subclassing `ember-app` and overriding the method with a copy/paste version. Would it make sense to add an option that skips the `new ES6Modules()` tree?

**Comment by stefanpenner** [comment]
@chrsjxn maybe some more restrictive glob support would help enable this?

**Comment by chrsjxn** [comment]
@stefanpenner Being able to pass in a glob for files that would get ignored by the es6 module tree would work for me. Or some other way to specify files to pass through the tree without being affected.

**Comment by stefanpenner** [comment]
> @stefanpenner Being able to pass in a glob for files that would get ignored by the es6 module tree would work for me. Or some other way to specify files to pass through the tree without being affected.

ya pretty much what I was thinking

**Comment by stefanpenner** [comment]
Seems to have gone stale, if someone is interested in implementing a PR would be reviewed
