### ISSUE TITLE
[Feature Request] Adding command-line flags to built-in tasks

### ISSUE THREAD

**Issue by uitgewis** [ember-cli/ember-cli#4708]
As a user of ember-cli, I want to have an entry point into ember-cli tasks such as `server` and `build` in order to confidently add behavior for additional flags specified at the command-line.

A usecase for this would be conditional inclusion of assets based on some parameter passed by the end user. An example of how I would currently go about this, in `ember-cli-build.js`:
```js
var myOption = process.argv.reduce(function(memo, item) { 
    if (item.indexOf('--myOption') === 0) {
        memo = item.split('=')[1];
    }

    return memo;
});

// do something based on myOption's value.
someProcessor.alternatives.push(myOption);
```

I would then be able to do the following:
```bash
$ ember serve --environment=myenvironment --myOption=somevalue
```

There is a problem with this approach however. It works precisely as expected, but `ember-cli` generates a warning each time this flag is presented to it:
```bash
The option '--myOption' is not registered with the serve command. Run `ember serve --help` for a list of supported options.
```

An alternative would be to use environment variables via nodejs' `process.env`, but this seems unnecessary, too. 

*Note: This would not be an environmental option. A flag could be specified regardless of which environment is selected.*

**Comment by stefanpenner** [comment]
I don't believe we will add support for this. As it locks us out of adding any future flags of our own.

My recommendation is to use environment variables. As I believe they will cover all your needs

**Comment by uitgewis** [comment]
That's a worth-while option.

But, what's the unanimous opinion regarding wrapping the built-in tasks, i.e: https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/commands/deploy.js#L25

I don't see any public documentation for this, so I'm guessing that approach was done with a lot of tinkering of ember-cli internals. Additional feature flags may also break this.

**Comment by stefanpenner** [comment]
> But, what's the unanimous opinion regarding wrapping the built-in tasks, i.e: https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/commands/deploy.js#L25
> 
> I don't see any public documentation for this, so I'm guessing that approach was done with a lot of tinkering of ember-cli internals. Additional feature flags may also break this.

yes they venture into the internals At there own risk.

**Comment by uitgewis** [comment]
That would be awesome. I guess my request is void, so you can close if you want to. Thanks.

**Comment by stefanpenner** [comment]
I'll close this. But we will document this api sometime soon :)
