### ISSUE TITLE
Circular Dependency is undefined

### ISSUE THREAD

**Issue by spinlock99** [ember-cli/ember-cli#4711]
I'm having an issue with circular dependencies. Basically I have 2 models: PlanArray and Plan. Each depends on the other. The problem is that rather than importing the module Plan into PlanArray, Plan is undefined in PlanArray.

I've created an example application [here](https://github.com/spinlock99/circular-dependency) that shows this issue better than I can describe it.

**Comment by stefanpenner** [comment]
for reference the cycle in question is as follows:

```js
// plan-array.js
import Ember from 'ember';
import Plan from './plan';

export default Ember.Object.extend({
  name: 'PlanArray',

  embeds: {item: Plan}

});
```

```js

// plan.js
import Ember from 'ember';
import PlanArray from './plan-array';

export default Ember.Object.extend({
  name: 'Plan',
  planArray: null,

  init: function () {
    var planArray = PlanArray.create();
    this.set('planArray', planArray);
  }
});
```

execution plan:

1. `require('plan')`
2. which does `require('./plan-array')`
3. which intern requires the not yet initialized `require('plan')`
4. `plan-array.js` fails because it at the top level requires direct access to the not yet initialized `plan`

**Comment by spinlock99** [comment]
Thanks! The key point that I was missing is that `init` is run post module evaluation. This seems to be working if I set `PlanArray.embeds` in `init`:

    import Ember from 'ember';
    import Plan from './plan';

    export default Ember.Object.extend({
      name: 'PlanArray',

      embeds: null,

      init: function () {
        this.set('embeds', {item: Plan});
      }

    });

Then, `embeds` is defined when I inspect it in the console:

    context.model.planArray.embeds
    > Object {}
