### ISSUE TITLE
Concatenated properties and acceptance tests

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli#4714]
1. Create initialiser:

        export function initialize() {
          Ember.LinkComponent.reopen({
            classNames: ['foo']
          });
        }

2. Create multiple acceptance tests

3. Run test suite

4. Notice properties are concatenated multiple times

        <a id="ember342" class="ember-view foo foo foo foo foo"></a>

Demo repo https://github.com/amk221/-ember-link-to-example

**Comment by rwjblue** [comment]
This is an ember bug, not ember-cli and is being tracked in: https://github.com/emberjs/ember.js/issues/12146

**Comment by rwjblue** [comment]
Also, in general there is not supposed to be deduping if concatenated proprieties. If you reopen linkcomponent many times, and add a class it should be duplicated (so don't do that :wink: ).

The bug in ember is that it is duplicated if you do it just once (not your exact scenario).

**Comment by amk221** [comment]
Yes, I understand that re-oepning would re-concatenate. My thoughts were that it was related to tests not tearing down the app properly, hence I posted here instead.

Apologies.

**Comment by rwjblue** [comment]
No need for apologies!

When you call `reopen` on a class you are actually mutating that class to add more definition. So running the reopen in an initializer is mutating the class itself to add another class every time the initializers are ran (which is likely as many times as you call `startApp` helper).

**Comment by jblotus** [comment]
i am also running in to this. in my case i am reopening the linkTo helper to add some additional attribute bindings. i looked at the fix in https://github.com/emberjs/ember.js/issues/12146 but that seems to only apply to classNames? 

for now i'm going to forego acceptance tests, but I was wondering if there is some workaround I could try.

```
export function initialize(/* container, application */) {
  Ember.LinkComponent.reopen({
    //give the link-to helper access to more attributes
    attributeBindings: ['ariaControls:aria-controls', 'ariaSelected:aria-selected'],

    //ensure that tabs get aria-selected binding
    ariaSelected: Ember.computed('active', 'ariaRole', function() {
      if (this.get('ariaRole') !== 'tab') {
        return null;
      }
      return this.get('active') === 'active';
    })
  });
}
```

**Comment by amkirwin** [comment]
Yep, same this is still an issue
It works fine in the browser but fails on the cli

**Comment by amk221** [comment]
Still an issue for me. I understand the problem, but I don't know of a solution

**Comment by rwjblue** [comment]
Avoid reopening in an initializer is the solution.  If you **must** reopen, do it outside of the `initialize` function so that it is only evaluated once.

Using @amk221's initial example:

```
Ember.LinkComponent.reopen({
  classNames: ['foo']
});

export default {
  name: 'stuff',
  initialize() { }
}
```

**Comment by jblotus** [comment]
Thank you that makes more sense now

**Comment by amk221** [comment]
:+1:
