### ISSUE TITLE
Defined unnecessary modules in compiled application js file.

### ISSUE THREAD

**Issue by kfuzaylov** [ember-cli/ember-cli#4715]
I have my custom class <code>acl.js</code> and put it in <code>app</code> folder next to <code>app.js</code> file.
After application is compiled
```bash
ember build
```
I can see two modules defined for <code>acl</code> class.
```js
define('builder/acl', ['exports', 'ember'], function (exports, Ember) {
```
and
```js
define('builder/tests/acl', ['exports', 'ember'], function (exports, Ember) {
```
And in the second module <code>builder/tests/acl</code> ES6 is not transpiled to ES5.
And when I open my application in browser it throws an error, because browser doesn't understand ES6 syntax. Also it breaks tests, because browser don't understand ES6 syntax.

If I compile application in production mode
```bash
ember build --environment=production
```
It is ok, because ember-cli doesn't create test module like <code>builder/tests/acl</code>.

**Comment by stefanpenner** [comment]
Can you provide an isolated example demonstrating this issue?

**Comment by stefanpenner** [comment]
Can you provide an isolated example demonstrating this issue?

**Comment by kfuzaylov** [comment]
https://github.com/kfuzaylov/temp/blob/master/dist/assets/builder.js
Here you can see two modules
<code>'builder/acl'</code> and <code>'builder/tests/acl'</code>
Ember-cli do the same with other files, e.g. <code>app/controller/base.js</code>
<code>'builder/tests/controllers/base'</code> and <code>'builder/controllers/base'</code>
And you can see that in modules with test (<code>'builder/tests/controllers/base'</code>, <code>'builder/tests/acl'</code>) code didn't transpiled.

**Comment by kfuzaylov** [comment]
Hi @stefanpenner do you have any ideas?

**Comment by kfuzaylov** [comment]
@stefanpenner any investigation results?

My dev environment:
Windows edition: Windows 8.1
System type: 64-bit Operation System, x64-based processor
Nodejs: v0.12.1
Ember-cli: 1.13.8
Emberjs: 2.0.0

**Comment by kfuzaylov** [comment]
Hi @stefanpenner i have found the reason.
This is broccoli-jscs plugin. It creates this fake unnecessary modules.
