### ISSUE TITLE
How to add directory to be watched for automatic server restart

### ISSUE THREAD

**Issue by jnfingerle** [ember-cli/ember-cli#4717]
I'd like to add directories (that contain some magic used by an addon) to the watcher, so that changed files trigger a server restart (like `app`, `tests` etc.). I couldn't find documentation of how to do this. 

This could be
  * me not being able to find the docs,
  * missing documentation of how to do this,
  * missing documentation of why this is never supposed to happen (and what to do instead) or
  * a feature request that might be a good idea but hasn't been asked before. 

If it's the first one, I'd be greatful to be pointed in the right direction, otherwise it would be great if the documentation could be enhanced or this would be considered as a valid feature request.

**Comment by stefanpenner** [comment]
this is not currently possible.

**Comment by jnfingerle** [comment]
Ok. In that case please treat this as a feature request.

**Comment by stefanpenner** [comment]
Feature requests should be issues on the rfc repo or if thoroughly thought out a full rfc.

Unfortunately this is working as intend and not considered an issue. So I will close this issue
