### ISSUE TITLE
Tests fail after any change to tests or vanish from reporter after any change to app

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#4723]
When running under testem (both phantom and chrome) or in the browser at `localhost:4200/tests`, tests pass in the first run then if any change is made in the tests, it reruns and fails with: 

```
Uncaught TypeError: Cannot read property 'default' of undefined

at require (http://localhost:7357/assets/test-loader.js:29:16)
    	at loadModules (http://localhost:7357/assets/test-loader.js:21:25)
    	at load (http://localhost:7357/assets/test-loader.js:40:35)
    	at http://localhost:7357/assets/test-support.js:6647:20: Can't find variable: visit

    ✘ afterEach failed on visiting /thing: undefined is not an object (evaluating 'target[method]')
```

If instead of changing a test, I change any part of the app, the test page reloads but all tests that aren't jshint no longer display. 

Seen with Ember 1.13.7, 1.13.8, 2.0 and ember-cli 1.13.7 and 1.13.8.
I've isolated this in a newly generated app https://github.com/kategengler/test-change-tests and the README has many more details of what scenarios I've tried. 

Happy to pair to look into this if that's useful.

**Comment by jimbeaudoin** [comment]
I have the same problem here.

This is my system right now:
```
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.7
npm: 2.13.4
os: linux x64
```

I tried with qunit 1.17.1 same
I tried with ember-data#2.0.0-beta.1 same

I have this problem since I updated ember-data tonight. I don't think this is related to ember-data but more about a dependency. I nombom my project before the update and then the problem start to appear.

**Comment by stefanpenner** [comment]
i actually noticed this myself in ember.

can you guys do

```
ember version
npm ls broccoli-filter
npm ls broccoli-babel-transpiler
```

**Comment by kategengler** [comment]
Results

`ember version`
```
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64
```

`npm ls broccoli-filter`
```
test-change-tests@0.0.0 /Users/katie/dev/test-change-tests
├─┬ broccoli-asset-rev@2.1.2
│ └── broccoli-filter@0.2.0
├─┬ ember-cli@1.13.8
│ └── broccoli-filter@0.1.14
├─┬ ember-cli-babel@5.1.3
│ └─┬ broccoli-babel-transpiler@5.4.3
│   └── broccoli-filter@1.2.0
├─┬ ember-cli-htmlbars@0.7.9
│ └── broccoli-filter@0.1.14
├─┬ ember-cli-qunit@1.0.1
│ └─┬ broccoli-jshint@1.0.0
│   └── broccoli-filter@1.2.0
└─┬ ember-cli-sri@1.0.3
  └─┬ broccoli-sri-hash@1.0.4
    └── broccoli-filter@1.2.0
```

`npm ls broccoli-babel-transpiler`

```
test-change-tests@0.0.0 /Users/katie/dev/test-change-tests
└─┬ ember-cli-babel@5.1.3
  └── broccoli-babel-transpiler@5.4.3
```

**Comment by klinem** [comment]
Also having this issue with Ember 2.0 and ember-cli-mocha.

`ember version`

```
version: 1.13.8
node: 2.5.0
npm: 2.13.4
os: win32 x64
```

`npm ls broccoli-filter`

```
├─┬ broccoli-asset-rev@2.1.2
│ └── broccoli-filter@0.2.0
├─┬ ember-cli@1.13.8
│ └── broccoli-filter@0.1.14
├─┬ ember-cli-autoprefixer@0.4
│ └─┬ broccoli-autoprefixer@3.
│   └── broccoli-filter@0.1.14
├─┬ ember-cli-babel@5.1.3
│ └─┬ broccoli-babel-transpile
│   └── broccoli-filter@1.2.0
├─┬ ember-cli-htmlbars@0.7.9
│ └── broccoli-filter@0.1.14
├─┬ ember-cli-mocha@0.9.2
│ └─┬ broccoli-jshint@0.5.8
│   └── broccoli-filter@1.2.0
└─┬ ember-cli-sri@1.0.3
  └─┬ broccoli-sri-hash@1.0.4
    └── broccoli-filter@1.2.0
```

`npm ls broccoli-babel-transpiler`
```
└─┬ ember-cli-babel@5.1.3
  └── broccoli-babel-transpiler@5.4.3
```

**Comment by jimbeaudoin** [comment]
`ember version`
```shell
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.7
npm: 2.13.4
os: linux x64
```

`npm ls broccoli-filter`
```shell
├─┬ broccoli-asset-rev@2.1.2
│ └── broccoli-filter@0.2.0 
├─┬ ember-cli@1.13.8
│ └── broccoli-filter@0.1.14 
├─┬ ember-cli-babel@5.1.3
│ └─┬ broccoli-babel-transpiler@5.4.3
│   └── broccoli-filter@1.2.0 
├─┬ ember-cli-htmlbars@0.7.9
│ └── broccoli-filter@0.1.14 
├─┬ ember-cli-qunit@1.0.1
│ └─┬ broccoli-jshint@1.0.0
│   └── broccoli-filter@1.2.0 
└─┬ ember-cli-sri@1.0.3
  └─┬ broccoli-sri-hash@1.0.4
    └── broccoli-filter@1.2.0 
```

`npm ls broccoli-babel-transpiler`
```shell
└─┬ ember-cli-babel@5.1.3
  └── broccoli-babel-transpiler@5.4.3 
```

**Comment by amk221** [comment]
Also experience this - initial build from `ember serve` is fine
subsequent builds from the watcher lack hbs templates.

`ember version`

    version: 1.13.8
    node: 0.12.7
    npm: 2.13.4
    os: darwin x64

`npm ls broccoli-filter`

    ├─┬ broccoli-asset-rev@2.1.2
    │ └── broccoli-filter@0.2.0
    ├─┬ ember-cli@1.13.8
    │ └── broccoli-filter@0.1.14
    ├─┬ ember-cli-babel@5.1.3
    │ └─┬ broccoli-babel-transpiler@5.4.3
    │   └── broccoli-filter@1.2.0
    ├─┬ ember-cli-coffeescript@1.13.0
    │ └── broccoli-filter@0.1.14
    ├─┬ ember-cli-htmlbars@0.7.10
    │ └── broccoli-filter@1.2.0
    └─┬ ember-cli-qunit@1.0.1
      └─┬ broccoli-jshint@1.0.0
        └── broccoli-filter@1.2.0

`npm ls broccoli-babel-transpiler`

    └─┬ ember-cli-babel@5.1.3
      └── broccoli-babel-transpiler@5.4.3

**Comment by tschoartschi** [comment]
I'm also experiencing problems with my build. Building my app totally fails and my tests also don't behave correctly. For more details see: #4725

**Comment by stefanpenner** [comment]
i believe its a bug in broccoli-filter https://github.com/broccolijs/broccoli-funnel/issues/39#issue-102382671

My local tests confirm rolling it back sorts out the issue. I believe i know the issue and will fix this morning, in the interim we will release 1.2.1 that is 1.1 code. Once that is out a reinstall of node_modules should fix the issue.

**Comment by stefanpenner** [comment]
1.2.1 is out which is basically just 1.1.0

**Comment by kategengler** [comment]
:clap: Thanks!

**Comment by jimbeaudoin** [comment]
works for me too. really, a big thank you! :+1:

**Comment by stefanpenner** [comment]
I'm still puzzled as to the route cause of the issue.

**Comment by tschoartschi** [comment]
Works for me also :+1:

**Comment by hussfelt** [comment]
:+1: Works for me as well!

**Comment by stefanpenner** [comment]
I was able to ultimately track down the issue: https://github.com/broccolijs/broccoli-filter/pull/35

Problem fixed and various deps should now be safe to upgrade.

**Comment by ballPointPenguin** [comment]
Sounds like the same issue I reported here https://github.com/switchfly/ember-cli-mocha/issues/77
I will see if the upgrade fixes it.

**Comment by ballPointPenguin** [comment]
:+1: works for me. :hamster: Thank you :heart:
