### ISSUE TITLE
itemController in template cause {{#each}} blocks to not render

### ISSUE THREAD

**Issue by nicomihalich** [ember-cli/ember-cli#4732]
I have been doing some work with ember-cli and I came across an issue which i've reproduced in a test app here https://github.com/nicomihalich/ember-item-controller-test/
I've found that adding itemController to a each block causes the each block to not render.

I know that itemController is deprecated and I do get the warning in console, but that shouldn't cause this issue right? I'm working on migrating some legacy ember code and need to work with itemControllers for a short while.  The documentation here suggests http://emberjs.com/deprecations/v1.x/ `{{#each bar itemController="abc" as |foo|}}` should be okay syntax.

There was an emberjs issue here https://github.com/emberjs/ember.js/issues/11552 that linked this jsfiddle where the itemController does not seem to break things: http://emberjs.jsbin.com/gunuzafaje/edit?html,js,output so i'm not sure what is different with my code.

Thanks!

**Comment by stefanpenner** [comment]
I don't believe this is an issue with ember-cli. Any reason why this belief is incorrect?

**Comment by nicomihalich** [comment]
While debugging this initially I wasn't sure where the issue was, but I found this example using vanilla ember that works with an itemController: http://emberjs.jsbin.com/gunuzafaje/edit?html,js,output. The app I created with ember-cli behaves differently with extremely similar code, so I thought to file the issue here.

If this isn't the place for the issue, should I open something against emberjs instead?

**Comment by stefanpenner** [comment]
> If this isn't the place for the issue, should I open something against emberjs instead?

ember-cli is primarily just the build tool

**Comment by rwjblue** [comment]
By default ember-cli generates apps with array and object controllers disabled. This will make itemController non-functional. 

You can remove that addon if you still need itemController.

**Comment by nicomihalich** [comment]
@rwjblue Thank you! Removing ember-disable-proxy-controllers from package.json fixed the issue for me.

**Comment by stefanpenner** [comment]
@rwjblue it should really provide some warning if that is true

**Comment by rwjblue** [comment]
It wasn't intentional to break itemControllers, but both it and routes whose model hooks return an array do a "container.lookup('controller:array')" and the addon is trying to target the second case (which is basically benign).

**Comment by rwjblue** [comment]
But we should remove that addon on master (since it isn't needed under 2.0.0 anyways).
