### ISSUE TITLE
esperanto deprecation.

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4733]
Some of you will see:

<img width="1096" alt="screen shot 2015-08-21 at 4 41 23 pm" src="https://cloud.githubusercontent.com/assets/1377/9421167/8175ccb2-4823-11e5-9d75-f7e1a063b556.png">

Have no fear, our transition plan has been to cut over to babel entirely for some time.
We will be once https://github.com/broccolijs/broccoli-filter/pull/28 lands (or maybe slightly sooner). 

- [x] persistent filters
- [x] adjust internals to skip es6modules.
- [x] make babel mandatory (internal dependency?)
- [x] pending release

[a relevant tweet thread](https://twitter.com/rich_harris/status/633358173886390272)

**Comment by sglanzer** [comment]
Thanks for the update, much appreciated

**Comment by joseperales** [comment]
Thanks a lot for the update, just in time to avoid research about

**Comment by msalahz** [comment]
:+1:

**Comment by fuse-mars** [comment]
Gotcha

**Comment by stefanpenner** [comment]
to prevent the deprecation, we have just locked ourselves to the version before the deprecation happens.

To git@github.com:ember-cli/broccoli-es6modules.git
 * [new tag]         v1.2.2 -> v1.2.2

this doesn't mean we aren't moving to just babel, but it aims to prevent confusion

**Comment by kimroen** [comment]
Just pasting the actual deprecation text here to make sure people get here from search: 

>[DEPRECATION NOTICE] Esperanto is no longer under active development. To convert an ES6 module to another format, consider using Babel (https://babeljs.io)

**Comment by JamesMGreene** [comment]
This is still just blocked on broccolijs/broccoli-filter#28, right?

**Comment by stefanpenner** [comment]
@JamesMGreene nope, master is already updated. pending release

**Comment by JamesMGreene** [comment]
Ah, sweet. :+1:

**Comment by stefanpenner** [comment]
will land with 1.13.9 (this weekend) 2.x(next weekend)
