### ISSUE TITLE
Supported Ember versions

### ISSUE THREAD

**Issue by acdx** [ember-cli/ember-cli#4741]
Hi,

It says this in the release notes of the latest release of ember-cli:

>* default ember is now at 1.13.7 (but feel free to upgrade/downgrade as desired)
>* default ember-data is now at 1.13.8 (but feel free to upgrade/downgrade as desired)

Is there any information on which Ember versions are officially supported by each given ember-cli version?

Thanks

**Comment by stefanpenner** [comment]
Basically all of them. As it really isn't coupled.

As for recommended, stay on or close to latest stable and you get all the nice things

**Comment by stefanpenner** [comment]
I'll be sure to document this :)

**Comment by acdx** [comment]
Great, this is basically the answer I was looking for!
