### ISSUE TITLE
Allow dotted project names

### ISSUE THREAD

**Issue by floqqi** [ember-cli/ember-cli#4754]
What's wrong with dot-separated project names? In my company we use these for namespaces. For example: `company.app.frontend`

I think https://github.com/ember-cli/ember-cli/blob/602577380c7d699d4ee43e3f07583bfef3c690ba/lib/utilities/valid-project-name.js#L7 should only prevent `ember new .` (mentioned in #2548)

**Comment by stefanpenner** [comment]
@floqqi several things:

1. we create a global, dots in the global would make it annoying to use
2. dots in ember mean nested objects in paths, there are likely scenarios where a conflict is possible due to this.

Not big deals. but likely something we wont prioritize effort into address/changing.

**Comment by floqqi** [comment]
@stefanpenner okay, I'm fine with the reasons you provided.
