### ISSUE TITLE
Environment not set correctly during ember test --silent

### ISSUE THREAD

**Issue by tschoartschi** [ember-cli/ember-cli#4755]
Hey!

I tried to run our ember test suite on our continuous integration server and I have troubles to get it running. On the CI I need to have the possibility to skip certain tests because the rely on a flash plugin. This flash plugin we can not emulate at our CI yet. Therefore I thought it would we a good idea to set an environment flag. The idea is to define it in environment.js as follows:

```javascript
module.export = function(environment) {
    //....
    //....
    //....
    if (environment === 'test' || environment === 'ci-test') {
        //....
    }

    if (environment === 'ci-test') {
        ENV.APP.isFlashAvailableDuringTests = false;
        //....
    }
    //....
    //....
    //....
    return ENV;
}
```
Then I could skip my tests based on the flag ```isFlashAvailableDuringTests```. First question: is this a good/correct way to achieve the desired result? Nevertheless the flag ```isFlashAvailableDuringTests```is always overwritten. When I put a ```console.log```before ```return ENV;``` I get the following output when I run ```ember test --silent --environment ci-test```

```shell
environment
ci-test
environment
ci-test
environment
ci-test
environment
ci-test
environment
ci-test
environment
ci-test
environment
test
```
The same output happens when I create a new project with ```ember init```. To be more realistic I added one acceptance test (because this is where I need the  ```isFlashAvailableDuringTests``` flag).

Do I understand the ```--environment```parameter wrong or is this really a bug with ember-cli?

Thanks

**Comment by jmar910** [comment]
We are running into this same issue. Ember CLI 1.13.8. The last call always sets the environment to `test` no matter if we pass in the environment flag or not.

**Comment by stefanpenner** [comment]
will reopen if a reproduction on latest is provided
