### ISSUE TITLE
Install Ember-cli @npm with fetch failed with status code 500

### ISSUE THREAD

**Issue by rockinho** [ember-cli/ember-cli#4758]
Hello!

I've installed Nodejs 0.12.7 and set our corporate proxy (http://jjasonclark.com/how-to-setup-node-behind-web-proxy/).

Now i tried: npm install -g ember-cli 

The console gives me following output:

![2015-08-25_180857](https://cloud.githubusercontent.com/assets/606442/9472299/c077ce7c-4b54-11e5-8970-98968fa49b8c.png)

Anyone an idea? Is this a firewall issue? NPM Issue? 

Best regards, 
rocki

**Comment by stefanpenner** [comment]
> Is this a firewall issue? NPM Issue?

unsure, but I suspect firewall.

**Comment by stefanpenner** [comment]
you can in theory just download the tarball the log indicates and then do

```
npm install -g ./thingyoudownloaded
```

which may allow you to bypass until you figure out whats up.

**Comment by rockinho** [comment]
hi stefan,

this is a good workaround!
thank you very much.

the problem is our firewall and antivirus.. it blocks the tgz file and stops the download..

best regards
rocki
