### ISSUE TITLE
`postprocessTree` hook not respecting addon load order

### ISSUE THREAD

**Issue by matthewlehner** [ember-cli/ember-cli#4762]
I'm using `broccoli-manifest` for automatic HTML5 cache-manifest compilation and have run into a few issues with the ordering addons specifically regarding `postprocessTree` in this case.

To reproduce, you can clone [this example app](https://github.com/matthewlehner/ember-cli-addon-order), install dependencies and run `ember build -e production`

The assets that are generated are fingerprinted and will look something like this:

```sh
dist
├── assets
│   ├── addon-order-9905b88114b75217de14cf1f6b7702ab.js
│   ├── addon-order-d41d8cd98f00b204e9800998ecf8427e.css
│   ├── vendor-d41d8cd98f00b204e9800998ecf8427e.css
│   └── vendor-d9bc2c7a2ccba4b509e534feb10dd7f1.js
├── crossdomain.xml
├── index.html
├── manifest.appcache
└── robots.txt

1 directory, 8 files
```

However, `manifest.appcache` does not have the fingerprinted asset names, because the `postprocessTree` hook in `broccoli-manifest` is being called before `broccoli-asset-rev`.

I've updated `broccoli-manifest`'s Ember CLI config to include `after: 'broccoli-asset-rev'` but it makes no difference – https://github.com/matthewlehner/broccoli-manifest/commit/5ba2fb2175973a512a27cf91170b46f56911f3f2

Is this a real bug, or am I doing something wrong?

**Comment by rwjblue** [comment]
Commented on that commit. You should specify before/after in the package.json not your objects definition in index.js.

**Comment by matthewlehner** [comment]
Thanks! Should've read these docs a bit more closely. Sorry about that...
