### ISSUE TITLE
add addon-test-support

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4766]
this will allow the addon author to provide test helpers, at the expected paths and they wont be included in the prod builds.

cc @lightblade / @rwjblue

**Comment by ming-codes** [comment]
Why is this closed? Has this been resolved?

**Comment by stefanpenner** [comment]
isn't an issue, rather feature request if someone is interested an RFC or PR would be reviewed.

**Comment by rwjblue** [comment]
It already landed in 2.2.0-beta.1.

**Comment by stefanpenner** [comment]
> It already landed in 2.2.0-beta.1.

ah even better :P
