### ISSUE TITLE
ember-cli proxying does not work with Rails server using puma

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#4767]
Related issue: https://github.com/ember-cli/ember-cli/issues/2871

Client backend just upgraded to Puma, proxying fails. No requests are seen from the Rails app. I can hit the API endpoints as normal with `curl` or the browser but via ember-cli's proxying.

**Comment by stefanpenner** [comment]
@bcardarella if I recall puma just binds to a different local interface.

**Comment by clov3rly** [comment]
There is a work around in the #2871 (appears to be an identical issue):

> *tl;dr* tell your rails server to bind to localhost with bin/rails server --binding 127.0.0.1, and then tell ember to proxy there with ember server --proxy http://127.0.0.1:3000.
