### ISSUE TITLE
Re-registration by initializers on `App.reset`

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#4769]
While looking into using `App.reset()` for acceptance tests, I stumbled onto this error:

```
Error: Cannot re-register: `service:-routing`, as it has already been resolved.
```

It seems the root cause is if you use the routing service (e.g., in a `link-to`) it gets cached in the application registry and then when you restart, it is picked up by the initializer running again and throws the error. I worked around that particular instance only to have a similar issue crop up with registration of transforms by Ember Data.

I'm wondering if re-running initializers should be part of resetting an application. I feel like semantically, only instance initializer should be re-ran. Thoughts? It seems like we could get some faster test times without having to completely recreate the application each time, but this blocks us from being able to use new instances right now.

Here's a super simple repro case: [JSBin](http://emberjs.jsbin.com/xapacakone/1/edit?html,js,output)

**Comment by stefanpenner** [comment]
I don't think this is a ember-cli bug.

alo app instances via visit are favored over App.reset()

**Comment by trentmwillis** [comment]
Bah, meant to open on Ember proper. Closing here.
