### ISSUE TITLE
ember serve --host's default disables IPv6

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#4775]
When `ember serve` is run without the `--host` option, it uses the default host, which is [defined as `"0.0.0.0"`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/commands/serve.js#L21).

This works fine for the old IPv4 stack. However, by setting the host to `"0.0.0.0"` and not passing a `null` / `undefined` value, Node.js (implicitly?) only binds to all IPv4 interfaces.

To make ember-cli listen to the IPv6 devices instead, I currently have to pass `--host ::`. However, this simultaneously disables the IPv4 stack.

I see multiple solutions to this problem and would make a PR, if we can agree on one.

1. Set the default value of `host` to `null` in [`commands/serve.js`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/commands/serve.js#L21) and teach [`express-server.js#displayHost`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/tasks/server/express-server.js#L37-L39) and [`livereload-server.js#displayHost`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/tasks/server/livereload-server.js#L70-L72) about it.

2. Implicitly discard `host` if it is `"0.0.0.0"` and pass `null` instead at [`express-server.js#startHttpServer`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/tasks/server/express-server.js#L204) and [`livereload-server.js#start`](https://github.com/ember-cli/ember-cli/blob/v1.13.8/lib/tasks/server/livereload-server.js#L44).

3. Set the default value of `host` to a magic keyword like `INADDR_ANY` or `all` and implement the changes accordingly.

Personally, I'd prefer solution 1. Solution 3 just feels very clunky and I don't like how solution 2 hides what's really happening; if I read that `"0.0.0.0"` is the default, I'd expect that this really is the value that is passed to the `.listen()` call.

Solution 1 is the cleanest imho. It might only look a bit weird in `ember help serve`, as I don't know how `nopt` handles `null` values.

**Comment by stefanpenner** [comment]
solution 1. also appeals to me.

**Comment by rwjblue** [comment]
Agreed.

**Comment by buschtoens** [comment]
Great! I'll make a PR this evening (CEST). :smiley:

**Comment by stefanpenner** [comment]
@buschtoens :+1:
