### ISSUE TITLE
Generate addon blueprint errors 1.13.8

### ISSUE THREAD

**Issue by EricSchank** [ember-cli/ember-cli#4776]
According to the Ember-CLI docs (http://www.ember-cli.com/extending/#create-blueprint), to create an Addon's blueprint, use this command:

`ember addon <blueprint-name> --blueprint`

However, in a brand new and untouched Addon, this command fails with:

```
$ ember addon ember-cli-cool --blueprint
version: 1.13.8
You cannot use the addon command inside an ember-cli project
```

Steps to recreate:
1. Create a new Addon project: `ember addon ember-cli-cool`
2. Enter dir: `cd ember-cli-cool`
3. Try to make a blueprint: `ember addon ember-cli-cool --blueprint`

**Comment by rwjblue** [comment]
My guess is that you are running `ember addon foo` from within an existing project (somewhere in the parent hierarchy at least).

**Comment by EricSchank** [comment]
Yes, after creating the new Addon project and `cd`ing into it, I tried to create the blueprint.

Maybe the docs are out of date?  Or maybe I misunderstood them.
They seem to say you create the blueprint using the `ember addon` command with a `--blueprint` option.

Maybe instead I should just be using:
`ember g blueprint ember-cli-cool`

If so, I'll submit a PR to update the docs.
