### ISSUE TITLE
Acceptance test runner gets in the way

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#4780]
Not sure if this is the appropriate place to ask this, apologies if it's not.

I am writing some acceptance tests for my app - one of these tests clicks a button in the header, the test can be seen here:

http://test.sonatribe.com/tests/?testId=8428a248

The code for that test is:

```
import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from 'sonatribe-ui/tests/helpers/start-app';

var application;

module('Acceptance | site searching', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('visiting /site-searching', function(assert) {
  assert.expect(1);

  visit('/');
  click('#search-button');
  fillIn('#search-term', 'gla');
  
  andThen(function() {
    var isVisible = true;
    var results = $('#search-result-group-Events');
    equal(isVisible , results.is( ":visible" ) );
  });
});
```

Now the issue is that the test fails because '#search-button' is not found... 
Looking at the test - I am navigating to http://test.sonatribe.com/ where the '#search-button' definitely does exist.

Creating a breakpoint in the test at the line where it clicks that button and debugging $('#search-button') indeed returns []  - weird

Now I can't visually see anything because the test runner UI is in the way. 

Is there anyway to get the runner UI to get out of the way? 

Also can anyone see why that test fails?!

Cheers

w://

**Comment by patocallaghan** [comment]
@wayne-o did you ever resolve this issue? If not, two suggestions would be to do either do:

```
visit('/')
   .then(function() {
     click('#search-button');
     ...
   })
```

OR

```
visit('/');
andThen(function() {
  click('#search-button');
  ...
});
```
This way you know the routes have definitely loaded before trying to click the button.

**Comment by stefanpenner** [comment]
> Not sure if this is the appropriate place to ask this, apologies if it's not.

typically, this issue tracker is for reporting bugs, and stackoverflow is for asking questions.

**Comment by wayne-o** [comment]
it kind of is a bug no?

I would expect to see my site running through the tests in the test runner
browser.
