### ISSUE TITLE
ENOENT, no such file or directory when deleting file when running ember serve 

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#4782]
If i delete a file when running ember serve, this happens, it crashes my server, usually it subsides shortly and my build retriggers and my server starts working but sometime it totally requires me to ctrl-c and restart my ember serve, it seemed to start happening with 1.13.8

```
ember-cli 1.13.8
ember-cli-qunit ^1.0.0
```

```

ENOENT, no such file or directory '/Users/JoshuaCope/Desktop/ih/tmp/jshinter-cache_path-0f3uIfp9.tmp/serializers/patient.js'
Error: ENOENT, no such file or directory '/Users/JoshuaCope/Desktop/ih/tmp/jshinter-cache_path-0f3uIfp9.tmp/serializers/patient.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:883:18)
    at JSHinter.<anonymous> (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/index.js:73:8)
    at Array.forEach (native)
    at JSHinter.build (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/index.js:72:35)
    at JSHinter.build (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:53:33)
    at /Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/JoshuaCope/Desktop/ih/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:476:11)
```

**Comment by stefanpenner** [comment]
ya i've noticed this too, its likely some interleaving.

Quick fix is to guard https://github.com/stefanpenner/broccoli-persistent-filter/blob/master/index.js#L73 /w try/catch

Will accept PR and release.

**Comment by jcope2013** [comment]
https://github.com/stefanpenner/broccoli-persistent-filter/pull/31

**Comment by frank06** [comment]
I'm getting a similar error: `ENOENT, no such file or directory '/Users/admin/Desktop/auctions/tmp/jshinter-output_path-HtU5xI16.tmp/serializers/application.js'` 

Is this related?  I have no idea what `broccoli-persistent-filter` is – at least it's not listed in my package.json.

It's an annoying, blocking issue. I make one change (not deleting anything), and this error pops up. I have to restart the server for each change I make to my files.

**Comment by stefanpenner** [comment]
@frank06 there was a fix to broccoli-persistent-filter earlier today that should address this -> https://github.com/stefanpenner/broccoli-persistent-filter/commit/5ec883f01823c0aa0243d7152215b6e720bb72ec

```
npm ls broccoli-persistent-filter
```

should return 1.1.3, if not try a re-install if so provide a reproduction of the problem in a new issue and we can investigate it.

**Comment by kbullaughey** [comment]
I'm getting something similar with my app that I'm trying to upgrade to 2.x, but right now I'm on `1.13.11` trying to work through all the deprecations. This involves ditching lots of old files relating to views, and so each time I delete a file, it occurs. But it appears to be coffeescript-related:

    file deleted views/annotation.coffee
    ENOENT: no such file or directory, unlink '/Users/kevin/ember-app/tmp/coffee_script_filter-cache_path-GeLbxPaz.tmp/client-app/views/annotation.coffee'

    client-app@0.0.1 /Users/kevin/ember-app
    ├── active-model-adapter@2.0.3
    ├── async@0.9.0
    ├── body-parser@1.14.2
    ├── broccoli-asset-rev@2.4.2
    ├── broccoli-sass@0.7.0
    ├── connect-restreamer@1.0.3
    ├── ember-cli@1.13.13
    ├── ember-cli-app-version@1.0.0
    ├── ember-cli-babel@5.1.6
    ├── ember-cli-coffeescript@1.13.2
    ├── ember-cli-content-security-policy@0.4.0
    ├── ember-cli-dependency-checker@1.2.0
    ├── ember-cli-htmlbars@1.0.1
    ├── ember-cli-htmlbars-inline-precompile@0.3.1
    ├── ember-cli-ic-ajax@0.2.4
    ├── ember-cli-inject-live-reload@1.4.0
    ├── ember-cli-nouislider@0.7.0
    ├── ember-cli-qunit@1.1.0
    ├── ember-cli-release@0.2.8
    ├── ember-cli-sri@1.2.1
    ├── ember-cli-uglify@1.2.0
    ├── ember-data@1.13.15
    ├── ember-disable-proxy-controllers@1.0.1
    ├── ember-export-application-global@1.0.5
    ├── ember-gestures@0.4.0 -> /Users/kevin/wordswing/dev/open-source/ember-gestures
    ├── ember-hammertime@1.0.0
    ├── ember-notify@4.4.0
    ├── ember-simple-auth@1.0.1 -> /Users/kevin/wordswing/dev/open-source/ember-simple-auth
    ├── express@4.13.4
    ├── glob@4.5.3
    ├── morgan@1.6.1
    ├── socket.io@1.4.5
    └── torii@0.6.1
    
Any thoughts on what might be causing this in my case?

**Comment by tsteuwer** [comment]
Im getting this a lot too. Mainly when editing SASS files. However, I have gotten it when saving a template.

{code}
// bower.json
{
  "name": "front-end",
  "dependencies": {
    "ember": "1.13.7",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.8",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "bootstrap-sass": "bootstrap-sass-official#~3.3.5"
  }
}
{code}
{code}
// package.json
"devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "5.1.0",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "1.13.8",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "gulp-jscs": "^3.0.2"
  }
{code}
