### ISSUE TITLE
Livereload port collision when serving two apps at the same time

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#4784]
firing two apps up quickly in two different tabs will both try to bind to the same Livereload port with the latter winning out

```
ember serve --port 8080
ember serve --port 8081
```

will throw this error in the 8080 app tab and the 8081 app will start successfully, retrying the failed one again at this point will bind to Livereload server on http://localhost:49154 and work successfully, this seems to new with 1.13.8 as I haven't had this exact problem in the past 

```
Livereload failed on http://localhost:49153.  It is either in use or you do not have permission.
```

**Comment by stefanpenner** [comment]
you can specify a custom liveReloadPort, and master will randomly choose an available one.
