### ISSUE TITLE
ember test --reporter does not change test reporter

### ISSUE THREAD

**Issue by petey** [ember-cli/ember-cli#4789]
In ember-cli 1.13.8: When a reporter is defined in `testem.json`, that config is used regardless of the state of the `--reporter` flag on the cli.

**Comment by petey** [comment]
version: 1.13.8
node: 0.10.34
npm: 2.13.4
os: darwin x64

**Comment by stefanpenner** [comment]
@johanneswuerbach got a second to dig in?

**Comment by johanneswuerbach** [comment]
Fixed by https://github.com/testem/testem/pull/695
