### ISSUE TITLE
Trying to run `ember test --serve` and `ember test` simultaneously results in "EADDRINUSE" error

### ISSUE THREAD

**Issue by nickiaconis** [ember-cli/ember-cli#4791]
Running either (or both) with `--port ####` (even if it is the same number for both) results in success, but prints a warning:

> The option '--port' is not registered with the test command. Run `ember test --help` for a list of supported options.

**Comment by stefanpenner** [comment]
can you share versions of:

* ember
* npm
* node
* os

**Comment by nickiaconis** [comment]
Of course.
* ember(-cli): 1.13.8
* node: 0.12.6
* npm: 2.13.4
* os: darwin x64 (OSX Yosemite)

**Comment by patocallaghan** [comment]
@nickiaconis We no longer use `--port` to set the port number when running `ember test --server`. It was changed to `--test-port`.

`ember test --server --test-port=12345` will work fine

**Comment by nickiaconis** [comment]
@patocallaghan Thanks for that tip. I'm still confused why `ember test` needs to bind a port in the first place, since it's only running in phantom.

I'm also confused as to why running `ember test --port 1234` and `ember test --serve --port 1234` simultaneously works, but running `ember test` and `ember test --serve` simultaneously does not.

**Comment by patocallaghan** [comment]
@nickiaconis `ember test` uses [testem](https://github.com/airportyh/testem) under the hood and that would still need to use a port. If you add `Chrome` to your list of tested browsers you'll see it opens up with `http://localhost:7357`.
