### ISSUE TITLE
Cannot generate route in more than one route hierarchy position

### ISSUE THREAD

**Issue by pythonquick** [ember-cli/ember-cli#4793]
Consider this simple ember-cli app:
https://github.com/pythonquick/ember-route-name
It contains a route named "properties.house". That means the route "house" is a nested route under the "properties" route.

Although the following ember-cli command creates a new root-level "house" route, it does not add the root-level "house" root to the router.js file:

```
$ ember g house
```

**Comment by abuiles** [comment]
@pythonquick this is an issue indeed, cross-referencing in the router-generator which is the lib wrapping route operations

**Comment by stefanpenner** [comment]
@trabus is this fixed with the latest work in this area?

**Comment by manoharank** [comment]
I have faced this issue today. Console log says `updating router` but nothing updated.

**Comment by igbanam** [comment]
I just tried this out with the app example provided and the house route was updated in the router file as it should

My setup is thus
```
18:18 $ ember version --verbose && npm --version && yarn --version
ember-cli: 2.12.2
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
1.1.0
```

Two things I did differently though was  

1. Instead of `ember g house`, I did `ember d route house`
2. My ember-cli version is more up to date. I think the repo has 1.13 in some commit messages

**Comment by rwjblue** [comment]
Awesome thanks for testing it out @igbanam!  Going to close this as it seems from the last comment that things are working properly...
