### ISSUE TITLE
"Waiting for runners" when using Chrome

### ISSUE THREAD

**Issue by jakemauer** [ember-cli/ember-cli#4794]
Hey there,

My project is using:
* Ember: 1.13.8
* EmberCLI: 1.13.8
* Ember Data: 1.13.8 
* Chrome Stable 45
* Node: v0.12.0
* NPM: 2.7.3
* OS: OSX 10.10.5

We use Chrome to test our app locally and on CircleCI. Yesterday out of nowhere testem stopped functioning normally. Chrome would open and our tests would run, but testem would sit there saying "Waiting for runners". Even if Chrome completes the test suite, testem never seems to be "connected." PhantomJS works fine. 

**What works:**
I reverted to a version of our project that uses ember 1.11 and destroyed and rebuilt my bower, node, and tmp directories and ran our suite and it ran fine. 

Then I setup an empty directory with a single JS specfile and the testem.json file that EmberCLI generates. I removed the "test_page" property and ran `testem`. It opened Chrome and ran the single spec without issue.

**What doesn't work:**
I then setup a brand new EmberCLI 1.13.8 project and ran the test suite and encountered the same "Waiting for runners" error. The testem.json that I used for this is here: https://gist.github.com/jakemauer/1eb4c05d3ea08a6defd6

Additionally if I open the provided testem URL directly in Chrome, it will run the tests just fine, but never signal back to testem that they're running. Firefox however WILL communicate and testem's CLI interface will show the Firefox tab. 

Sometimes when I quit `ember test --server` I get an error dump visible here: https://gist.github.com/jakemauer/1eb4c05d3ea08a6defd6

I'm not sure where to go from here. I was convinced it was something in our code but because it's acting weird with a brand new 1.13.8 project I'm at a loss. Thanks for your eyeballs and help.

**Comment by jcope2013** [comment]
related? https://github.com/jonathanKingston/ember-cli-sri/issues/2

**Comment by jakemauer** [comment]
Oh good call jcope2013, `<script src="testem.js" integrity="" ></script>` seems to have done the trick.

**Comment by jakemauer** [comment]
Thanks for the quick fix @stefanpenner!

**Comment by jonathanKingston** [comment]
:+1: thanks all. Sorry for the oversight here with generated files. More help coming soon!

**Comment by alexmiddeleer** [comment]
I caused this problem myself by using the `--launch` flag and misspelling the browser name, e.g. `ember test -s --launch chome --filter 'my fancy test'`. So if anyone else finds this page via google, this might be your issue.
