### ISSUE TITLE
Requirejs namespaces overwritten by loaderjs

### ISSUE THREAD

**Issue by amuthanarulraj** [ember-cli/ember-cli#4798]
We have a custom text editor library which uses `requirejs` extensively including `require.config()` function. This library needs to be imported in our Ember app. But the `loaderjs` overwrites `requirejs` namespaces `require` and `requirejs` and this conflicts with the library initialization.

**Comment by stefanpenner** [comment]
we will plan to role out a no-conflict style build in the next month or two
