### ISSUE TITLE
Performance tuning and broccoli

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#4802]
I am finding lately that rebuild/livereload times are kind of a kill joy. 

Are there any techniques for tuning specific nerd knobs on this stuff? For example if I know I am only going to be working on a single component or just the style sheet, is there a way to effectively disable all other compilation? Is the system trying to do too much each iteration? Is there a design flaw in the architecture?

What about aggressively caching large swaths of the app folder and hinting to broccoli: "hey you only have to do these few things each time I save a file."

Unfortunately it feels like we are drifting an unreasonable distance from speed of the old school: make change, cmd + s in editor, cmd+r in browser, see changes. 

It used to be that the recompilation was done before I could even command tab back to browser. Today, not so much. Maybe it is my app that is a couple years old now...

**Comment by stefanpenner** [comment]
I wouldn't worry to much. Been making good progress on peer. Next release should have a nice big boost for most use-cases.

With that release also comes a bunch of new ways to see what is going on under the hood. Both actionable to the user and when reporting related issues.


There are several open issues labelled as per and a stress-app that is slowly getting to something reasonable. I also have attempted to log various things that are done and various in progress

**Comment by eccegordo** [comment]
Awesome sounds like some good stuff in pipeline. Very excited about the more detailed logging. For me most of the time the perf doesn't matter except when it does, e.g. when I am wanting to iterate over something quickly and repeatedly and need a fairly effective REPL like workflow. So look forward to the user actionable tweaks. Or just being able to be selective about how the build process works would be helpful.

**Comment by tschoartschi** [comment]
@eccegordo: I haven't tried it myself but ember-cli-styles-reload (https://github.com/xomaczar/ember-cli-styles-reloader) could help you for styles. I wanted to try it out but haven't found time yet. In our app this would help a lot because a total reload is quite expensive in our app (bootstrapping and initializing a webgl scene)

**Comment by stefanpenner** [comment]
been making good progress on this the next release 1.13.9 (this weekend) and 2.x (next weekend) will include a large chunk of performance improvements (assuming individuals also upgrade dependencies, and report slow addons)

a great way to debug performance issues is

```
DEBUG=broccoli-persistent-filter:*,broccoli-caching-writer:* ember s
```

and on rebuilds look for cache invalidations.

**Comment by eccegordo** [comment]
Awesome will check it out sounds promising!

**Comment by eccegordo** [comment]
After using latest Ember CLI for a few days, I just want to say great job @stefanpenner I think a lot less about waiting for live reload in day to day use. 

Closing this issue because I think most of my complaints are addressed now.

Thanks for all the hard work!

**Comment by stefanpenner** [comment]
@eccegordo good to hear, I have another few low hanging tasks on this front. I hope to land them over the next week or so.

Once those are done, I'll likely revisit the performance work again in a few weeks, must clear my queue of other tasks before i can continue the fun.
