### ISSUE TITLE
Generated tests for mixin use the wrong path when the recipe is used in addons

### ISSUE THREAD

**Issue by MiguelMadero** [ember-cli/ember-cli#4803]
Steps to reproduce 

1. Create a new addon (ember addon ember-addon)
1. cd ember-addon
1. Generate a mixin `ember g mixin sample`
1. Run the tests `ember test`

Expected: 

* The default test should succeed (or be incomplete)

Actual: 

* The test fails with the message "Error: Could not find module `dummy/mixins/sample` imported from `dummy/tests/unit/mixins/sample-test". 

The import statement used is `import SampleMixin from '../../../mixins/sample';` When replaced with `import SampleMixin from 'ember-addon/mixins/sample';` it works. 

I could fix it by simply using modulePrefix on the import path, but I want to make sure I'm considering everything.

**Comment by kellyselden** [comment]
Just came across this, it's because the mixin isn't re-exported in the app folder like other blueprints are.

**Comment by MiguelMadero** [comment]
Well, I don't think the addon needs to re-export the mixin. That makes sense for other types of objects, but IMO, it's better it the consumer `import`'s it via ES6 from the add-ons namespace. For other types of objects, re-exporting is important so they can be found by the resolver.

**Comment by rwjblue** [comment]
Confirm, it should be imported from `addon-name/mixins/whatever-lol`

**Comment by MiguelMadero** [comment]
Thanks. PR coming

**Comment by kellyselden** [comment]
> Well, I don't think the addon needs to re-export the mixin.
Agreed. I didn't mean to imply we should, just that that was probably a copy paste issue of this test blueprint.

**Comment by MiguelMadero** [comment]
Makes sense. Thanks for clarifying. 

Sent from Outlook Mobile




On Fri, Jan 22, 2016 at 6:07 AM -0800, "Kelly Selden" <notifications@github.com> wrote:













Well, I don't think the addon needs to re-export the mixin.

Agreed. I didn't mean to imply we should, just that that was probably a copy paste issue of this test blueprint.
