### ISSUE TITLE
automate ember-cli-addons export via ember-giftwrap on addon build

### ISSUE THREAD

**Issue by PhilippRoessner** [ember-cli/ember-cli#4805]
Ember-cli-addons are only available for ember projects built on ember-cli. It would be nice if ember-cli would automatically export all the stuff you need when building the addon. Non-Ember-Cli-developers  could include the addon with bower, problem solved. No Node, no npm, just plain javascript for developing ember without disadvantages.

I've seen [Ember-Giftwrap] (https://github.com/ef4/ember-giftwrap), but at the moment it is not working on any of my environments. But maybe this could be an entry point for the ember-cli guys?

**Comment by stefanpenner** [comment]
It is unlikely that we will have time to pursue this. I would encourage users who are in this situation to scratch there own itch, if they have actionable direct suggestions as to what we can do from our side to make it easier. We will do our best, but owning the whole story just isn't feasible at this time.
