### ISSUE TITLE
Failed to execute "git ls-remote --tags --heads git://github.com/rwjblue/ember-qunit-builds.git", exit code of #128

### ISSUE THREAD

**Issue by CGTDev92** [ember-cli/ember-cli#4810]
![ember_create_eror](https://cloud.githubusercontent.com/assets/12963661/9725149/5384341c-55ff-11e5-886a-e3f1539a71ec.png)
When i'm creating new ember app showing this error in my terminal, previously it's working. Please view attached screen shot.

**Comment by DCKT** [comment]
Hi, I got the same error, what's the solution ?
