### ISSUE TITLE
Blueprint Options Do Not Get Passed As Documented

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#4811]
According to [the documentation](http://www.ember-cli.com/extending/#locals) I would be able to have a generator like so:

```
ember generate fizz-bar baz --type=circle
```

And in the locals hook receive an object that looks like the following at `options.entity`:

```
{
  name: 'baz',
  options: {
   type: 'circle'
  }
}
```

However this does not occur as options are parsed by splitting on `:`, see [here](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/parse-options.js#L7).  What is the cononical way of passing arguments. The colon feels very strange.

**Comment by trabus** [comment]
I think this is a matter of how the arguments are parsed by nopt and brought back in. Any option that isn't registered in availableOptions is only available through looking at the raw args here: https://github.com/ember-cli/ember-cli/blob/80a44a0304aa7d92ee50a19d9ffb03078b539d33/lib/models/command.js#L377

I don't recall why it's splitting on `:`, but I think maybe nopt returns [the remain arg as a string](https://github.com/npm/nopt#the-rest-of-the-args)? I'm not sure and don't have time to investigate right now, but I am fairly certain it's something like that.

**Comment by Turbo87** [comment]
@chadhietala is this still relevant or did @trabus solve your issue?

**Comment by chadhietala** [comment]
I don't remember. Closing for now.
