### ISSUE TITLE
Poor feedback for build failures with `ember test --server`

### ISSUE THREAD

**Issue by courajs** [ember-cli/ember-cli#4812]
It is easy to miss build failures/syntax errors while running the test server. When I am running `ember serve` I will see some red output and a stack trace in the console, and my browser will refresh and show a build error page.
However while testing, the page does not refresh, and the only visual indication that a failure has happened is that the bottom line of the window turns into the first line of a stack trace:
![screen shot 2015-09-08 at 4 12 34 pm](https://cloud.githubusercontent.com/assets/1588273/9746202/969b3bb6-5644-11e5-8182-c524144668dc.png)
While fixing a failure I often introduce a build error without realizing, as the failure message does not change. While refactoring, I often introduce a build error without realizing, as the tests continue showing green.

**Comment by stefanpenner** [comment]
I believe this is a duplicate. TL;DR we need to include testem.js after we include QUnit, but before everything else

**Comment by AaronSikes** [comment]
What should be the UI signal when the build fails?
I think the main options are:
- clear the testem screen and show the build errors in the terminal window

and/or
- refresh the browser page and show the build error page during development

**Comment by AaronSikes** [comment]
@stefanpenner I don't think the vendor/testem ordering matters here (looked at  #4497). That would be relevant for runtime errors present in a successful build.
The problem here is when the build fails (e.g. unmatched bracket).
It seems difficult for us to report this failure, as we've given control of both the terminal & the browser over to testem.
Do you have ideas? I'm happy to dig into implementation, but I'm not sure what to implement.

**Comment by johanneswuerbach** [comment]
@AaronSikes sorry for not responding, could you check whether Testem 0.9.5 https://github.com/ember-cli/ember-cli/pull/4877 fixed your issue? We solved an error with `before_test` errors not being correctly reported.

**Comment by AaronSikes** [comment]
@johanneswuerbach it doesn't, unfortunately.
This isn't for errors occurring in vendor, or in build.js.
These are errors in the broccoli pipeline, e.g. syntax errors cause the babel compilation to fail.
I think this is just missing functionality, not a bug.

**Comment by stefanpenner** [comment]
@johanneswuerbach any ideas?

**Comment by drspaniel** [comment]
I played around with this a while ago. I was able to just overwrite the tests html file with the build error: https://github.com/drspaniel/ember-cli/commit/76cb5f1be370bdde2b8c24366df985afbbe86c4c
This actually worked pretty well, I got a build error page when I broke the build.

I couldn't figure out how to reload the page after fixing the build though. I tried including testem.js on the page and telling testem to rerun tests, but that didn't seem to work.
I'm not sure if there's a livereload server running we can hook into.

**Comment by stefanpenner** [comment]
@johanneswuerbach any thoughts on this? Would be cool if we could send errors to testem to display

**Comment by stefanpenner** [comment]
i suppose we could also not reload testem if their was a failure...

**Comment by johanneswuerbach** [comment]
Sorry, will look into this week.

**Comment by Turbo87** [comment]
@johanneswuerbach any news on this?

**Comment by perryn** [comment]
Any thoughts on this? It makes for a pretty painful experience when trying to test ember components with a fast feedback cycle...

**Comment by locks** [comment]
An error page has since been introduced!
