### ISSUE TITLE
Passing --dummy to destroy complains yet works

### ISSUE THREAD

**Issue by igorT** [ember-cli/ember-cli#4818]
```
➜  ember-data-json-api git:(master) ✗ ember d --dummy model client-versions
The option '--dummy' is not registered with the destroy command. Run `ember destroy --help` for a list of supported options.
uninstalling model
  remove tests/dummy/app/models/client-versions.js
```

**Comment by kellyselden** [comment]
Just tested on master, and for both generate and destroy, the --dummy option doesn't give any warnings, nor does it do dummy operations. It still modifies files.

**Comment by kellyselden** [comment]
So after I got the option right, I see that this warning doesn't show up in master. @igorT can you verify in master?

**Comment by igorT** [comment]
@kellyselden did you run it inside an addon btw? Not sure what dummy would do in a base app

**Comment by kellyselden** [comment]
@igorT I tried in an addon. I also just tried the current version 1.13.8 and I got the warning. So it appears this is fixed in master.

**Comment by igorT** [comment]
Awesome thanks! I searched but didn't find a similar issue. Sorry for
wasting your time

**Comment by kellyselden** [comment]
@igorT It's all good. I won't make the dummy/dry-run mistake again so you helped me get better!
