### ISSUE TITLE
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.*

### ISSUE THREAD

**Issue by sunil-sharma** [ember-cli/ember-cli#4820]
I am facing the issue while running ember test with existing application.
>1..0
#tests 0
#pass  0
#fail  0
#ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.*

**config/environment.js**
>module.exports = function (environment) {
    var ENV = {
        modulePrefix: 'app_name'
        podModulePrefix: 'some_prefix',
        APIServer: 'http://localhost:8080/****/',
        environment: environment,
        baseURL: '/',
        locationType: 'auto',
        EmberENV: {
            FEATURES: {
                // Here you can enable experimental features on an ember canary build
                // e.g. 'with-controller': true
            }
        },
        APP: {
            // Here you can pass flags/options to your application instance
            // when it is created
        }
    };
    if (environment === 'development') {
        // ENV.APP.LOG_RESOLVER = true;
        // ENV.APP.LOG_ACTIVE_GENERATION = true;
        // ENV.APP.LOG_TRANSITIONS = true;
        // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
        // ENV.APP.LOG_VIEW_LOOKUPS = true;
    }
    if (environment === 'test') {
        // Testem prefers this...
        ENV.baseURL = '/';
        ENV.locationType = 'none';
        // keep test console output quieter
        ENV.APP.LOG_ACTIVE_GENERATION = false;
        ENV.APP.LOG_VIEW_LOOKUPS = false;
        ENV.APP.rootElement = '#ember-testing';
    }
    if (environment === 'production') {
        ENV.baseURL = '***';
        ENV.locationType = 'hash';
    }
    return ENV;
};

**package.json**
>{
  "name": "name",
  "version": "0.0.0",
  "description": "Small description for ember-federation goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.13.2",
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.1",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-body-parser": "0.0.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.15",
    "ember-cli-release": "0.2.3",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.5",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "express": "^4.13.3",
    "glob": "^4.5.3",
    "morgan": "^1.6.1"
  }
}

**testem.json**
>{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "PhantomJS"
  ],
  "launch_in_dev": [
    "PhantomJS",
    "Chrome"
  ]
}

**bower.json**
>{
  "name": "name",
  "dependencies": {
    "ember": "1.13.3",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.5",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.1",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1"
  }
}
versions:
phantom 1.9.8
testem 0.9.4
Any ideas?

I have created a vanilla app, tests are working fine. Not working for existing project with above files.

Thanks

**Comment by stefanpenner** [comment]
> I have created a vanilla app, tests are working fine. Not working for existing project with above files.

please provide GH repo that demonstrates this issue. Otherwise, it is less likely someone will have the time to reconstruct your issue.

**Comment by stefanpenner** [comment]
my guess is you have some invalid JS (or something phantom doesn't understand, and it is crashing before testem connects)

**Comment by patocallaghan** [comment]
Not sure if related but I'm seeing a similar issue at the minute with an existing project using `Chrome` and not `PhantomJS`. I've been using a fork of ember-cli master and just rebased it against the latest changes (the fork was several weeks old). It stopped working after the rebase. I'm digging into it to see if I can pinpoint the issue.

**Comment by patocallaghan** [comment]
So after doing a combination of `npm link` and `git bisect` against my existing app I managed to track the issue down to this commit https://github.com/ember-cli/ember-cli/commit/10a41a86d92defc82395ac342330be5f0d5d0f80

I know have it running tests correctly and the issue was that my `index.html` didn't have a link to `assets/tests.js`.

**Comment by GavinJoyce** [comment]
Nice!

**Comment by rwjblue** [comment]
Awesome thanks for tracking that down @patocallaghan!  This was "fixed" (made much more obvious) by https://github.com/ember-cli/ember-cli/pull/5023.
