### ISSUE TITLE
Ember-cli 1.13.8 installas Ember 1.13.1

### ISSUE THREAD

**Issue by hankthetank** [ember-cli/ember-cli#4823]
Hello,

I follow these steps:
npm uninstall -g ember-cli
npm cache clean
bower cache clean
npm install -g ember-cli

Which installs the correct ember-cli version but when I do a ember init or ember new I still get ember 1.13.1 instead of ember 1.13.7

#npm list ember-cli -g
/usr/local/lib
└── ember-cli@1.13.8

#ember init
version: 1.13.1
installing app...

**Comment by kellyselden** [comment]
`ember init` happens in your project folder, which uses your project's version of ember-cli, which may be outdated.

Try running `npm install ember-cli --save-dev` in your project folder.

**Comment by kellyselden** [comment]
also, this may help you http://www.ember-cli.com/user-guide/#project-update

**Comment by stefanpenner** [comment]
This seems to be working as expected

**Comment by hankthetank** [comment]
Well the thing is that it was a new empty project. Also the something happens if a do a ember new. Is there some global config where this could be set that I'm missing?
