### ISSUE TITLE
addAddonToProject fails mid-installation

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#4830]
Testing on Ember-CLI 1.13.8 w/ Ember 1.13.7
npm 2.14.3
node 0.12.7

When running a blueprint for an addon that installs another addon to your Ember app, the installer fails without an error message partway through.

```
Jordans-MacBook-Pro-2:test-app jordan$ ember g test-addon
version: 1.13.8
installing test-addon
  install addon ember-cli-sass
Installing packages for tooling via npmJordans-MacBook-Pro-2:test-app jordan$
```

test-addon is linked to test-app via `npm link` and added to the package.json according to the ember-cli docs

I'm planning to dig deeper and try to put a PR together, but wanted to put it here for tracking and in case anyone had an idea why it's not working.

**Comment by elwayman02** [comment]
As far as I can tell, npm is bailing out during the package installation, not sure why. If I run `ember install test-addon`, it calls the exact same npm task with the exact same arguments, as far as I can tell, except it succeeds there where it fails here.

**Comment by elwayman02** [comment]
I changed the file `lib/utilities/npm.js` to log some data to the console to see why the two commands are different. Unfortunately, as you will see below, the log output is EXACTLY the same regardless of which command is run.

Note: I also commented out `this.disableLogger();` in `lib/tasks/npm-task` for debugging purposes.


```
// lib/utilities/npm.js
'use strict';

var Promise = require('../ext/promise');

//

/**
  Runs the npm command `command` with the supplied args and load options.

  Please note that the loaded module appears to retain some state, so do not
  expect multiple invocations within the same process to work without quirks.
  This problem is likely fixable.

  @method npm
  @param {String} command The npm command to run.
  @param {Array} npmArgs The arguments passed to the npm command.
  @param {Array} options The options passed when loading npm.
  @param {Module} [npm] A reference to the npm module.
*/
module.exports = function npm(command, npmArgs, options/*, npm*/) {
  var lib;
  if (arguments.length === 4) {
    lib = arguments[3];
  } else {
    lib = require('npm');
  }

  var load = Promise.denodeify(lib.load);

  console.log('COMMAND: ' + command);
  console.log('PACKAGE: ' + npmArgs);
  for (var opt in options) {
    console.log('OPTION ' + opt + ': ' + options[opt]);
    if (opt === '_watchmanInfo') {
      var watchInfo = options[opt];
      for (var info in watchInfo) {
        console.log('Watchman Info ' + info + ': ' + watchInfo[info]);
      }
    }
  }

  return load(options)
    .then(function() {
      // if install is denodeified outside load.then(),
      // it throws "Call npm.load(config, cb) before using this command."
      console.log('NPM LOAD THEN');
      var operation = Promise.denodeify(lib.commands[command]);

      return operation(npmArgs || []);
    });
};
```

Log output of `ember g test-addon`:
```
COMMAND: install
PACKAGE: ember-cli-sass
OPTION loglevel: error
OPTION logstream: [object Object]
OPTION color: always
OPTION optional: true
OPTION save-dev: true
OPTION save-exact: true
```

Log output of `ember install ember-cli-sass`:
```
COMMAND: install
PACKAGE: ember-cli-sass
OPTION loglevel: error
OPTION logstream: [object Object]
OPTION color: always
OPTION optional: true
OPTION save-dev: true
OPTION save-exact: true
NPM LOAD THEN
```

Note that in the second case, the log reaches the callback of the npm command, signaling that it returned successfully. The script goes on to execute as expected and installs the addon. I am at a loss as to why these two identical commands are not having the same result.

**Comment by elwayman02** [comment]
Update: Tried changing the blueprint to use `addPackageToProject` instead of `addAddonToProject`, with the thought that I might just run the blueprints manually. Seems both commands are broken, which makes sense since they run the same npm command.

Also, tried updating to Ember 1.13.10, same result.

**Comment by elwayman02** [comment]
Here's a copy of my `index.js` blueprint:

```
module.exports = {
  description: 'Set up additional packages for Ember apps',
  normalizeEntityName: function() {}, // no-op since we're just adding dependencies

  afterInstall: function(options) {
    this.addAddonToProject('ember-cli-sass');
  }
};
```

**Comment by jasonmit** [comment]
return in afterInstall :)  Putting it here so others don't get trolled.

**Comment by elwayman02** [comment]
....aaaand I'm an idiot. Moving along.
