### ISSUE TITLE
how to stop background running ember server ?

### ISSUE THREAD

**Issue by tahniyatkazmi** [ember-cli/ember-cli#4833]
ember-cli server is running through bash script. `ember server --environment=production &>> /log/production/ember/frontend.log &`. I am unable to find any way to stop my server something like ember server stop etc. 

is it something not available or i'm missing ? 

One way can be find pid and kill that pid to stop the server but there should be elegant way to do this.

Please advise me.

**Comment by stefanpenner** [comment]
in posix:

* you can use `fg` to for ground the script, then kill it
* or you can kill processes by name: pkill ember

**Comment by rishirajdev** [comment]
@tahniyatkazmi  check your ember process by `ps -ef` command

**Comment by kirankumbhar** [comment]
`npx kill-port 4200` is what worked for me.
