### ISSUE TITLE
Generated initializer cannot find addon module in unit test during ember try only

### ISSUE THREAD

**Issue by f3ndot** [ember-cli/ember-cli#4835]
The generated initializer unit test cannot find addon module, thereby causing `ember try:testall` to fail for release, beta, and canary. However it works with just `ember test`.

Steps to reproduce:
```
# For Ember CLI version: 1.13.8
ember addon my-addon/
cd my-addon/
ember g initializer my-init
npm test
```
:boom: 

Specific error:
```
not ok 7 PhantomJS 2.0 - TestLoader Failures: dummy/tests/unit/initializers/my-init-test: could not be loaded
    ---
        actual: >
            null
        message: >
            Died on test #1 	at moduleLoadFailure (http://localhost:7357/assets/test-support.js:6753:15)
            	at require (http://localhost:7357/assets/test-loader.js:62:31)
            	at loadModules (http://localhost:7357/assets/test-loader.js:51:25)
            	at load (http://localhost:7357/assets/test-loader.js:82:35)
            	at http://localhost:7357/assets/test-support.js:6762:20: Could not find module `my-addon/initializers/my-init` imported from `dummy/initializers/my-init`
        Log: |
    ...
```

However, interestingly, running `ember test` will pass.

**Comment by stefanpenner** [comment]
you have a version of ember-data (in try) that is not compatible with the version of ember.
Fix this and your problem very very likely goes away

Welcome to JavaScript package management :P (soonish this should be much better)

**Comment by f3ndot** [comment]
@stefanpenner so I'm a little confused. I'm keeping the generated defaults in `package.json` and `bower.json`. Is it that Ember Data 1.13.8 is incompatible with Ember 2.*.* and therefore release, beta, and canary all fail?

So the solution is, that if my addon doesn't use or rely on ED, to just remove it?

**Comment by f3ndot** [comment]
Answering my own question... The answer appears to be a resounding yes :+1: :smile:

**Comment by stefanpenner** [comment]
> So the solution is, that if my addon doesn't use or rely on ED, to just remove it?

:+1: and master no longer includes it by default for addons
