### ISSUE TITLE
Need help getting the homepage logo updated

### ISSUE THREAD

**Issue by wifelette** [ember-cli/ember-cli#4850]
Hey all!

We've finally got official logos for the CLI and Data projects (woot!) and I'd love for someone to help get the EmberCLI one live on the CLI homepage. 

These are large transparent PNG versions appropriate for dark and light backgrounds, respectively. I have vector art too, if needed.

![ember cli on dark](https://cloud.githubusercontent.com/assets/25433/9864803/9c4feda0-5b02-11e5-8efc-46d6ae7043d6.png)
![ember cli on light](https://cloud.githubusercontent.com/assets/25433/9864804/9c51d638-5b02-11e5-85ad-efb7e97f6b4e.png)

Looking for someone to make the changes, paste screenshots here or on the PR, so I can review and then merge :) Pretty please?

**Comment by josemarluedke** [comment]
PR adding the new logo sent (#4853). Btw, it looks awesome!
