### ISSUE TITLE
Addon made using pods not compatible with apps using a different podModulePrefix

### ISSUE THREAD

**Issue by jmacqueen** [ember-cli/ember-cli#4858]
I really want to be using pods. And I really want to be writing addons. And I'd love to use them both together.

But if I write an addon either with or without a `podModulePrefix` and someone else writes an application that has a different `podModulePrefix`, the components from the addon won't work unless the application adds imports under its own pod location.

**Comment by stefanpenner** [comment]
addons \w pods are not supported.

**Comment by jmacqueen** [comment]
Is there a place I can suggest adding "currently not supported with addons" to the pods description on the website? Or would this be that place? :smile:
