### ISSUE TITLE
app.import should dedupe (taking first occurrence)

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#4861]
https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1299-L1328

**Comment by rwjblue** [comment]
I 100% agree that it should dedupe, but the last should win (not the first).  This is because the app should always "win" over addon items.

**Comment by stefanpenner** [comment]
@rwjblue You are correct, although not for what I was describing. (the ambiguity after reading what i wrote makes sense)

What we want:

* the order of inclusion should be first visited <-- what i meant
* the included should be the last visited. <-- what you meant

*note: both are what we want*

This way.
```js
app.import('moment.js');
app.import('moment-timezones.js'); // depends on moment

// some add-on
app.import('moment.js');
```

order of inclusion is first visited:

1. moment.js
2. moment-timezones.js

but moment.js will come from the resulting mergeTrees/loadpath (which will be last visited)

**Comment by stefanpenner** [comment]
Ultimately this does expose the "lack of proper package management" problem, but given the current constraints (not our planned solutions) this is should be the correct solution.

**Comment by rwjblue** [comment]
I 100% agree, and thank you for taking the time to explain what you meant.

**Comment by stefanpenner** [comment]
@rwjblue :+1:

**Comment by lukesargeant** [comment]
+1 we got hit by this yesterday

**Comment by stefanpenner** [comment]
@lukesargeant I submitted a workaround to source-map-concat. So this problem should be masked (as smc works around it). If there is an additional issue, please report in detail.

**Comment by jasonmit** [comment]
@stefanpenner what's the status of this.  You're moment + moment-timezone is spot on.. two people have just reported this on ember-moment where they had other addons also importing moment.

The only thing I can think to solve for now is if they all use ember-cli-moment-shim, which gets the ordering right since like you said the mergeTree/funnel causes the last one to win.

**Comment by stefanpenner** [comment]
@jasonmit still un-implemented, someone needs to submit a pr.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-funnel-reducer/blob/master/index.js i think handles this
