### ISSUE TITLE
Separate file for tests

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#4862]
We're currently working on an application with a large number of tests and feel it would be beneficial to have the tests generated into a separate file instead of lumped in with the `app.js`.

The primary reason for this is wanting to be able to split the file so that we can distribute tests (QUnit's filtering is too simplistic). It would also keep tests confined to `/tests` which helps the dev environment more closely mirror reality.

Is there any reason why this currently isn't how things are done? If a PR for this would be welcome, I'd gladly do the work.

**Comment by stefanpenner** [comment]
> Is there any reason why this currently isn't how things are done? If a PR for this would be welcome, I'd gladly do the work.

I can't think of any reason why we shouldn't split by default. PR sounds good.

**Comment by trentmwillis** [comment]
Sounds good. I've talked with Chad, will begin work on this soon.

**Comment by stefanpenner** [comment]
:+1:

**Comment by stefanpenner** [comment]
@rwjblue just  aheads-up (in-case you can think of something)

**Comment by trentmwillis** [comment]
Closed via #4865.
