### ISSUE TITLE
http-mock, bodyParser and Content-Type: application/vnd.api+json

### ISSUE THREAD

**Issue by rbemis** [ember-cli/ember-cli#4864]
It appears that http-mock needs the bodyParser middleware to read req.body, but bodyParser does not like the JSON API media type application/vnd.api+json, which is the content type generated by the JSONAPIAdapter and required by the [JSON API spec](http://jsonapi.org/format/). If you post a request to an http-mock with Content-Type: application/vnd.api+json, req.body will be {}, empty, but without bodyParser, req.body will be undefined. Please advise. What am I missing? Is there something else I need to do to make this all work together?

Thanks in advance.

**Comment by stefanpenner** [comment]
Sounds like a bug/annoyance with bodyParser.

Typically, I stick to pretender/ember-cli-mirage for mocking/faking, and only use the proxy aspect of the backend. So I am unable to give advice.

I am unclear if this is an ember-cli bug, this likely makes more sense asked as a generic node question on StackOverflow.

**Comment by rbemis** [comment]
I think you're right. It does seem like a bodyParser thing. Was just curious if anyone has used http-mock to do a POST request and successfully retrieved the payload from req.body.

Thanks anyway.

**Comment by stefanpenner** [comment]
@rbemis i know this has plagued others. If you find something, please report back. I would love to find something better to encourage people use.

(cc @ef4 – i think you hit this early)

**Comment by rbemis** [comment]
Aha, I think I got it! Here's what worked for me: (hope this helps others)
```
// need bodyParser middleware to read post body (payload)
// note, you'll need to npm install body-parser first
var bodyParser = require('body-parser');

. . . rest of code here ...

// replace "clinics" with the "thing" you're mocking
app.use('/api/clinics', bodyParser.json({ type: 'application/*+json' }), clinicsRouter);
```
