### ISSUE TITLE
Conditionally generate files

### ISSUE THREAD

**Issue by ultimatemonty** [ember-cli/ember-cli#4866]
Is it possible to be able to conditionally generate files based on options passed to the generator? As a simple example I might have the following blueprint structure:
```
-blueprints
  -foo
    index.js
    -files
      -app
        -components
          __name__.js
        -models
          __name__.js
        -templates
           -components
             __name__.js
```

If my generator has an `availableOption` defined for `--generatemodel` and I set it to false I'd like to be able to not generate the model in the above blueprint.

Is this currently possible? Haven't seen anything yet that indicates it would be.

**Comment by trabus** [comment]
There currently is no way to filter out files that are generated from the files folder. They're simply copied over with the fileMapTokens replaced and the contents are processed as lodash templates. 

The best way to tackle this would be to lookup the model blueprint, similar to how the [resource blueprint does](https://github.com/ember-cli/ember-cli/blob/master/blueprints/resource/index.js#L62), and somehow do so conditionally. The other option would be to maybe do something in the afterInstall where you conditionally remove the files you don't want.

**Comment by trabus** [comment]
I've also been working on adding a method for blueprints to install other blueprints in a similar manner to the resource blueprint. The problem I've been running into is that I want to have it run the same task as generate and destroy do, but it's not quite setup to do so yet, and may require some modifications.

If I can find the time, I may be able to get it done this weekend (but no promises).

**Comment by ultimatemonty** [comment]
@trabus no open source entitlement here!

I certainly appreciate you chiming in. I'll take a look at your suggestions and report back on what, if anything, I'm able to get working!

**Comment by ultimatemonty** [comment]
@trabus I dug around and found [this post](http://discuss.emberjs.com/t/calling-ember-g-component-within-a-blueprints-index-js/8739/3) on the discourse forum which got me headed in the right direction. We ended up scrapping the feature but it was definitely fun to get in and learn all about generators! Thanks again for all the help!
