### ISSUE TITLE
how can i see/modify the final url that http-proxy hits.

### ISSUE THREAD

**Issue by sid1404** [ember-cli/ember-cli#4870]
proxy, like, adapter adds "/store-name" at the last of the proxy target that you specify.
I wan to have complete control of the URL /or atleast i shold be able to add suffix to the url.

> proxy.web(req, res, { target: 'http://localhost:8082/connection/testdb?tablename=' });

as final url is this case looks like 
> http://localhost:8082/connection/testdb?tablename=/store-name
instead i want 
> http://localhost:8082/connection/testdb?tablename=storename.

Is something like `buildURL="url"` , posible in http-proxy

**Comment by stefanpenner** [comment]
As we merely delegate to express and http-proxy I would recommend investigating those libraries.

**Comment by sid1404** [comment]
i am working on ember-cli and after entering the command `ember g http-proxy members` ,in the file `server/proxies/members.js` i have
       
      var proxyPath = '/members';
      module.exports = function(app) {
       // For options, see:
       // https://github.com/nodejitsu/node-http-proxy
       var proxy = require('http-proxy').createProxyServer({});
        
          proxy.on('error', function(err, req) {
                console.error(err, req.url);
                    });

          app.use(proxyPath, function(req, res, next){
                // include root path in proxied request
               req.url = proxyPath + '/' + req.url;
               proxy.web(req, res, { target: 'http://localhost:8082/connection/testdb?tablename=' });
           });
This hits `http://localhost:8082/connection/testdb?tablename=/members/` instead i want `'http://localhost:8082/connection/testdb?tablename=members`

**Comment by stefanpenner** [comment]
@sid1404 I am confused how that is a response to my comment.

**Comment by sid1404** [comment]
@stefanpenner i wanted to update my question instead i ended up posting a comment.

Irrespective, I have tried studying the libraries and even multiple forums, however i have not been able to figure the possible solution. Any help is much appreciated

**Comment by stefanpenner** [comment]
Although I would like to, we don't really have the bandwidth to field questions about any node_modules we use/provide.

I would like to recommend that you post this to stackoverflow, and I will share the link around. Hopefully the larger node community will provide guidance.

If it does turn out to be an issue with ember-cli, or how it uses the underlying http-proxy module. Gladly open an issue on this tracker.

I am going to close this, so we can keep this tracker focused on bugs in ember-cli, but like I said above. Please submit to stackoverflow, and share the link here.

**Comment by Kuzirashi** [comment]
http://stackoverflow.com/questions/32645063/how-can-i-see-modify-the-final-url-that-ember-http-proxy-hits
