### ISSUE TITLE
Option to run tests on previous build

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#4872]
Was wondering why there is no option to run tests on an existing build of the application (something like `ember test --no-build`). Specifically, here are several cases I can think of where this would be desirable:

1. You've been developing in browser and then switch to make sure tests are passing in Phantom,
2. Your tooling pipeline validates a build and then runs tests as two separate tasks, and
3. Attempting to parallelize or distribute tests based off a single build

It seems this shouldn't be too difficult to implement, but maybe I'm missing something. I'd be glad to take a stab at it if this sounds useful.

**Comment by stefanpenner** [comment]
something like:

```sh
ember test --path path/to/build
```

would be nice

**Comment by trentmwillis** [comment]
I feel the `query` option is strictly tied to this, but I think that could be a useful new addition to make. Should we have a command to alias `path` to the default build location?

**Comment by stefanpenner** [comment]
> Should we have a command to alias path to the default build location?

I don't think thats needed.

Please note, I suspect you believe the default build location to be `dist` but in-fact, dist is just a dereferenced copy of the actual build output. It exists, to make it easy for users to see what is going on.

By default tests are run against something deep in `tmp`

**Comment by trentmwillis** [comment]
> dist is just a dereferenced copy of the actual build output.

Even in the case where `ember build` was run? That's the scenario I was envisioning for the last two use cases I mentioned above.

**Comment by stefanpenner** [comment]
> Even in the case where ember build was run?

yup, dist is 100% of the time just a copy of the internal. This is because we wanted to allow for concurrent builds, without interfering.

`--path` or w/e we name it, will basically override that.

related code: https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L153

**Comment by trentmwillis** [comment]
Okay, good to know. I'll probably submit `--path` and `--query` as two separate PRs. Is it going to be possible to make this compatible with the `--server` option? I feel like the answer is no.

**Comment by trentmwillis** [comment]
Closed via #4874 and #4906
