### ISSUE TITLE
Install fails on Node 4.1.0 with NPM 3.3.3

### ISSUE THREAD

**Issue by corbinu** [ember-cli/ember-cli#4873]
npm 3.3.3 is now npm stable however ember-cli will not install with it on Node 4.1.0 (and any most likely any iojs/node after 2.5.0) because bufferutil build fails. 

This appears to be due to a lack of a new socket.io release which testem depends on.

As documented here: https://github.com/socketio/socket.io/issues/2213

**Comment by stefanpenner** [comment]
we bundle testem, and strip out all native extensions. Are you installing from master, or from the registry.

**Comment by corbinu** [comment]
The registry... I simple installed Node 4.1.0 on OS X. Then ran
```
npm install -g npm@latest
npm install -g ember-cli
```

Perhaps this is a npm bug

**Comment by stefanpenner** [comment]
@corbinu hmm, looks like it is trying to build bufferutil again...

**Comment by stefanpenner** [comment]
Anyways, you can use: `npm install --no-optional`  to skip optional native dependencies (like bufferutil)

**Comment by stefanpenner** [comment]
> (and any most likely any iojs/node after 2.5.0) because bufferutil build fails.

Should only be affecting recent npm, since our work-around to patch and re-bundle WS without bufferutil dep seems to have been mitigated. Hopefully someday, testem or socket.io folk deal with this.

I will likely just fork them this weekend, testem-pure or something, so that we can avoid the native deps.

**Comment by stefanpenner** [comment]
can confirm:

```
npm i --no-optional -g ember-cli
```

installs for

```
{ npm: '3.3.3',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.0',
  openssl: '1.0.2d',
  uv: '1.7.4',
  v8: '4.5.103.33',
  zlib: '1.2.8' }
```

**Comment by corbinu** [comment]
Works like a charm thanks I am searching for any similar issues in npm I will open or link the relevant issue here. Do you want me to leave this open until it is fixed over there? I promise to clean up after myself once they do :)

**Comment by stefanpenner** [comment]
Ya lets leave this open. I'll sort it out again. This weekend

I suspect many issues exist with addons. We may want to add npm v3 criteria to ember-observer and open issues on offending addons.

**Comment by iarna** [comment]
npm@3 tries to install missing modules found inside of bundled deps– it doesn't treat them as opaque– which is why it tried to install bufferutils.

But that said, that absolutely shouldn't break the install as that's an optional dep. We've seen this else where recently so I'm sure I'll be digging into it shortly.

**Comment by stefanpenner** [comment]
@iarna I do some hacks things like rewriting bundled deps package json to avoid the native deps. I suspect, those bundled package.json are being ignored.

I can totally accept that this may be something I just need to approach different ly

**Comment by stefanpenner** [comment]
Actually... I wonder if my latest fix just isn't released. Will investigate tonight.

**Comment by iarna** [comment]
Ooh, interesting! To the best of my knowledge, it should be using the metadata it finds in your `package.json`'s on disk and should only request fresh metadata if it decides its going to replace that module.

**Comment by Strutsagget** [comment]
Guess a lot of people gonna have this now :(

But 
npm i --no-optional -g ember-cli 
worked like a charm :+1:

**Comment by johanneswuerbach** [comment]
Testem maintainer here:
@corbinu did npm install really fail (aka exit code != 0) or did it just print a bunch of errors when installing optional deps? All native modules in testem are currently optional and not required for testem to work. https://travis-ci.org/airportyh/testem/builds/81159515

We are always looking to remove native deps (performance isn't really an issue with testem), but https://github.com/socketio/engine.io is the only WebSockets (with IE 8 fallback) implementation I'm aware of.

@iarna it would be awesome if we could just suppress native optional deps failures as it leads to confused devs and a lot of false positive reports.

**Comment by stefanpenner** [comment]
@johanneswuerbach would you guys accept a fork of those libs with no native deps?

**Comment by johanneswuerbach** [comment]
Sure, I was also experimenting with using engine.io directly instead of socket.io, but had no time to complete that yet.

The benefit would be only one dep to fork to upgrade ws at least to a reasonable version. (Or a fork of it)

**Comment by johanneswuerbach** [comment]
Looks like npm 3 is currently failing installs when optionals fail https://github.com/npm/npm/issues/9643. Hopefully that should be fixed soon.

Also there is now another issue around improving the UX for failing optional deps:
https://github.com/npm/npm/issues/9567

**Comment by corbinu** [comment]
Should be fixed in https://github.com/npm/npm/commit/2289234e11b30c878585aebee68d4a3a5bd63cce

**Comment by unwiredbrain** [comment]
A quick heads-up.

`node install -g ember-cli@1.13.8` emits loads of node-gyp errors because of bufferutil **but exits with `0`**

- node v5.0.0
- npm v3.3.12
- nvm v0.29.0 (via brew v0.9.5)
- Mac OS X 10.11.1

**Comment by stefanpenner** [comment]
> node install -g ember-cli@1.13.8 emits loads of node-gyp errors because of bufferutil but exits with 0

@unwiredbrain this is a bug in NPM

**Comment by corbinu** [comment]
@stefanpenner My understanding is that NPM has already "fixed" their as @unwiredbrain stated the current behavior is not to fail on optional deps but show a bunch of scary errors and exit 0 anyway. 

Glad to hear @patocallaghan is on it though as the number of errors is sure to confuse/disconcert users of ember-cli

**Comment by iarna** [comment]
@corbinu This is more complicated than it appears at first. Ember's bundled deps don't include those optional deps in the bundled package.json files. npm@2 honors this, and to my surprise npm@3 does not, so this is something we'll be looking into over in npm-land.

**Comment by corbinu** [comment]
@iarna Thanks for the clarification I had a assumed it was fine now since that was the behavior I have been seeing my mistake
