### ISSUE TITLE
Blueprints cause install error when installing the same package twice

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#4876]
If you have a blueprint that installs multiple addons and each of those addons has a blueprint that installs the same package, ember-cli/npm throws up a bit. For example, let's say you have a blueprint that installs `ember-cli-sass-pods` and `ember-paper`, which both install `ember-cli-sass`. You'll have something like this:

```
installing ember-cli-opinionated
  install addons ember-cli-sass-pods, ember-paper
Installed packages for tooling via npm.
installing ember-cli-sass-pods
  install package ember-cli-sass
Installing packages for tooling via npm..Binary downloaded and installed at /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-14/binding.node
` /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
Installed packages for tooling via npm.
installing ember-paper
  identical app/styles/app.scss
  install bower packages hammerjs, material-design-icons
Installing browser packages via Bower...
  cached git://github.com/EightMedia/hammer.js.git#2.0.4
  cached git://github.com/google/material-design-icons.git#2.0.0
```

...and so on. Eventually, when it gets to the second installation of `ember-cli-sass`, you get a bunch of errors like this:

```
npm ERR! install trying to install 1.0.4 to /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-kitchen-sink-helpers/node_modules/glob/node_modules/inflight
npm ERR! install but already installed versions [ '1.0.4' ]
npm ERR! install trying to install 1.3.2 to /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/rimraf/node_modules/glob/node_modules/once
npm ERR! install but already installed versions [ '1.3.2' ]
npm ERR! install trying to install 2.0.1 to /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-kitchen-sink-helpers/node_modules/glob/node_modules/inherits
npm ERR! install but already installed versions [ '2.0.1' ]
npm ERR! install trying to install 1.0.0 to /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-kitchen-sink-helpers/node_modules/glob/node_modules/path-is-absolute
npm ERR! install but already installed versions [ '1.0.0' ]
npm ERR! install trying to install 2.0.10 to /Users/jordan/Projects/GitHub/test-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-kitchen-sink-helpers/node_modules/glob/node_modules/minimatch
```

The installation will succeed regardless, but users are going to see a huge error output (more than my terminal could even scroll through) from NPM when this happens.  Is there a way that ember-cli could keep track of what packages it has already installed during a particular task (ie `addon-install`) so that it does not attempt duplicates?

However, this raises a secondary issue of what to do if two blueprints specify different versions of the same dependency...what happens? What should happen?

**Comment by stefanpenner** [comment]
> However, this raises a secondary issue of what to do if two blueprints specify different versions of the same dependency...what happens? What should happen?


Currently its just a mess, as we move to peerDependencies this will somewhat sort itself out. We will layer a conflict resolution strategy on top. To attempt something reasonable.

**Comment by elwayman02** [comment]
Any workarounds or tips on mitigation in the meantime, or are we just stuck with it?

**Comment by stefanpenner** [comment]
Install the deps manually

**Comment by stefanpenner** [comment]
Closing this as it is a known issue/feature/fact of life today. A future version will take a different approach, hopefully in the next few months.
