### ISSUE TITLE
ERROR: Attempting to register an unknown factory: `model:application`

### ISSUE THREAD

**Issue by rbemis** [ember-cli/ember-cli#4879]
I generated an application serializer, like so:
```
[12:04 70] ember generate serializer application
version: 1.13.8
installing serializer
  create app/serializers/application.js
installing serializer-test
  create tests/unit/serializers/application-test.js
```
When I ran the unit test, I got this error:
```
Uncaught TypeError: Attempting to register an unknown factory: `model:application`
```
Looks like the failure is happening in the moduleForModel() step, even before the first line of code in the actual test is executed.

Please advise. If this is a bug somewhere, is there a workaround?

Thanks in advance.

**Comment by stefanpenner** [comment]
Not aware of a bug. This doesn't seem to occur for me.

**Comment by rbemis** [comment]
Sorry, forgot to mention that I'm using JSONAPIAdapter and JSONAPISerializer.

Here's how to reproduce the problem:
(or, you can just clone the app from https://github.com/rbemis/ember-app1)
```
ember new ember-app1
cd ember-app1
ember g adapter application
ember g serializer application

===> Edit app/adapters/application.js so it extends DS.JSONAPIAdapter, like so:

import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
});

===> Edit app/serializers/application.js so it extends DS.JSONAPISerializer, like so:

import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
});
```
In your browser, navigate to localhost:4200/tests
Here's what I see: http://cl.ly/image/3s2a3B0R2w0o/o

**Comment by jjhampton** [comment]
I'm running into this exact same problem as well, extending the JSONAPIAdapter and JSONAPISerializer.

**Comment by chadian** [comment]
This actually fails on a fresh ember cli out of the box with:
`ember g serializer application`

The test it creates is:
```
import { moduleForModel, test } from 'ember-qunit';

moduleForModel('application', 'Unit | Serializer | application', {
  // Specify the other units that are required for this test.
  needs: ['serializer:application']
});

// Replace this with your real tests.
test('it serializes records', function(assert) {
  var record = this.subject();

  var serializedRecord = record.serialize();

  assert.ok(serializedRecord);
});
```
I think the issue is that the test is expecting you to create a model serializer, not an application one. The `moduleForModel` with `'application'` is attempting to do a lookup for an application model and failing on not being able to find it:
```
TypeError: Attempting to register an unknown factory: `model:application`
```

Maybe the blueprint for the test should be adapted for application serializers?

**Comment by b00tahead** [comment]
I'm running into the same error. Also using JSONAPIAdapter and JSONAPISerializer. Changing to

    import { moduleFor, test } from 'ember-qunit';

    moduleFor('serializer:application', 'Unit | Serializer | application', {
      // Specify the other units that are required for this test.
      needs: ['serializer:application']
    });

    // Replace this with your real tests.
    test('it serializes records', function(assert) {
      var record = this.subject();

      var serializedRecord = record.serialize();

      assert.ok(serializedRecord);
    });

will at least get rid of the original error.

**Comment by stefanpenner** [comment]
maybe an issue upstream, unsure without more information.

**Comment by leondmello** [comment]
I faced this issue as well,
The vanilla auto generated test for the application serializer fails as indicated by @rbemis

**Comment by nathanhammond** [comment]
@leondmello If you can create a reproduction using ember-cli 2.4.3 please open a new issue with a reproduction repository published to your account.

**Comment by leondmello** [comment]
Alright, I will get that done. The issue was on ember-cli 2.4.3

**Comment by leondmello** [comment]
@nathanhammond Created a new issue with an example repository mentioned in the issue

**Comment by dustinfarris** [comment]
Also getting this on latest ember-cli 2.6.2

**Comment by dustinfarris** [comment]
I think the test is trying to get users to test serialized records which would mean dragging in a model.  But out of the box this is creating an "application" model which likely does not exist so the test blows up.

**Comment by stefanpenner** [comment]
@dustinfarris if you can put together a reproduction, feel free to open a new issue and someone can try and help debug it for you. Without a reproduction it will be tricky to help

**Comment by nathanhammond** [comment]
@dustinfarris @stefanpenner Reproduction is here: https://github.com/leondmello/embercli_issue_4879

This is going to be an Ember Data issue, I believe, since they own those blueprints.

**Comment by dustinfarris** [comment]
@nathanhammond @stefanpenner agreed this is an issue with the blueprint, nothing more.

**Comment by nathanhammond** [comment]
Actually, I think the issue is going to be here: https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js

This is making assumptions about what does and does not exist on the container and needs to be a bit smarter. @dustinfarris Would you be willing to investigate it further now that we've traced the issue to a specific 57 lines of code?

I'm going to keep this issue closed as this is an ember-test-helpers issue.
