### ISSUE TITLE
broccoli-sourcemap-concat error with no test framework installed

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/ember-cli#4882]
We ran into an interesting bug today in a project without either ember-cli-qunit or ember-cli-mocha installed (I know, this is not common).  The issue has to do with [a change made](https://github.com/ef4/broccoli-sourcemap-concat/commit/38b99897b14c39c70ac95e3d623b78444a78bb6a#diff-a066d7857aa2139190d783b1f2e1b08cR101) to broccoli-sourcemap-concat in version 1.1.2.  Even though the error is coming from that lib I think the source of the bug is likely in the assumptions ember-cli is making.  I'm not sure if this is worth fixing, but it seems worth pointing out.

This log includes the output of `options` that is being passed to broccoli-sourcemap-concat as well as the resulting error:
```
{ inputFiles: [],
  outputFile: '/assets/test-support.css',
  description: 'Concat: Test Support CSS',
  sourceMapConfig: { enabled: true, extensions: [ 'js' ] } }

SimpleConcat: nothing matched []
Error: SimpleConcat: nothing matched []
    at SimpleConcat._addFiles (concat-test/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/simple-concat.js:102:11)
```

[Sample app](https://github.com/Dhaulagiri/concat-test) that reproduces the problem

**Comment by stefanpenner** [comment]
I believe I have [fixed](https://github.com/ember-cli/ember-cli/commit/fc4d6ebc8dc3387797d51220b8a17b06c4c3ada6) this on master of ember-cli. I could likely remove the restricted assertion within broccoli-source-map-concat...

**Comment by Dhaulagiri** [comment]
Yep, master works.  Wish I would have tried that :).  Thanks!
