### ISSUE TITLE
environment.js executed twice? inserting "console.log(process.env);" gives an output twice

### ISSUE THREAD

**Issue by jjff** [ember-cli/ember-cli#4886]
when executing "ember s" or "ember b", the content of process.env is shown twice.
Is this wanted/required behaviour?   It is at least unexpected for a novice!

**Comment by stefanpenner** [comment]
its expected, but not really wanted behavior. I wouldn't consider it a bug, but it would be good to cleanup

**Comment by lo10lo** [comment]
I agree, it is not a bug as it is internal behavior.  [Just as background: I wanted to use      `// app/initializers/myInit.js= ... export default {--- initialize: ... console.log('runs only once: '+process.env); ...`     ,which runs only once as planned, but where the variable `process` is no more known }      thanks a lot for your work
