### ISSUE TITLE
Livereload ENOENT error crashes ember server on master

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#4896]
This seems to be a very recent change from the last day or two. Steps to reproduce:

!) Install ember-cli master branch globally (or `npm link` it in a directory)
2) `ember new my-app`
3) Change the ember-cli version of the generated app to `ember-cli/ember-cli#master`
4) Reinstall ember-cli for the project (or nombom the whole app)
5) `ember server`
6) Visit `localhost:4200`
7) Watch your server crash and burn

```
Jordans-MBP:opinionated-demo jordan$ ember s
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 4376ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor                | 2702ms
Babel                                         | 385ms
Babel                                         | 224ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor (1)            | 2702ms
Babel (8)                                     | 1148ms (143 ms)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/jordan/Projects/GitHub/opinionated-demo/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
    at Error (native)
```

I'm going to start bisecting commits on master to figure out what's breaking, but I wanted to put this up in case someone has an idea what's going on.

**Comment by stefanpenner** [comment]
Are you using npm v3?

**Comment by elwayman02** [comment]
Yea, I'm on npm v3

**Comment by elwayman02** [comment]
Related? https://github.com/mklabs/tiny-lr/issues/91

**Comment by elwayman02** [comment]
Confirmed that updating tiny-lr to the master branch fixes the issue. What are your thoughts on this, @stefanpenner? Should we update ember-cli to master pending a new version release, or leave master with a broken livereload on npm3 until they push the next release out?

**Comment by stefanpenner** [comment]
* this line should be removed: https://github.com/ember-cli/ember-cli/blob/master/package.json#L65
* when the new version is released this line should be updated https://github.com/ember-cli/ember-cli/blob/master/package.json#L141

We cannot have git deps, or it causes some grief. If tiny-lr doesn't appear to release anytime soon, we may want to fork and release under another name. Any interest in doing that?

**Comment by elwayman02** [comment]
@stefanpenner yea I'd be happy to release the updated version if they don't get anything out soon. They've only had 2 releases this year, so it's hard to say when they'll get around to the next one.  How long do you think we should wait before taking action?

**Comment by elwayman02** [comment]
It seems this isn't the first time the project has been abandoned...I just found a fork from 2 years ago that was made for this very same reason: https://www.npmjs.com/package/teeny-lr
