### ISSUE TITLE
Allow to use random port for test

### ISSUE THREAD

**Issue by avdv** [ember-cli/ember-cli#4902]
On our CI server I used to use the random port allocator plugin to avoid clashes between concurrent builds. Alas, in the last weeks we've often seen build failures due to `EADDINUSE`errors since the port gets acquired after `npm install & bower install` when ember-cli starts, when, in the meantime, another process could have started listening on the port.

For this reason, it would be nice if one could use a random port which "express" happily supports when giving it a port value of "0".

**Comment by rwjblue** [comment]
Fixed on master in https://github.com/ember-cli/ember-cli/pull/4816.

**Comment by avdv** [comment]
Nice! I must have missed that while searching. FTR, until the next release is out I'm patching that in my build script:

`sed -i -e '/_generateTestPortNumber:/s|$|return 0;|' node_modules/ember-cli/lib/commands/test.js`
