### ISSUE TITLE
ember serve --proxy issues

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#4903]
Hi

This was working on another repo and I found it really easy to setup but now I am trying to get it working elsewhere I am running into problems.

My API is at http://dev.festivaltribe.co.uk:1337/api/v1/

Navigating to that shows me it is working fine.

If I run my ember app with:

ember serve --proxy http://dev.festivaltribe.co.uk:1337

I get the following output in terminal:

```
version: 1.13.8
Proxying to http://dev.festivaltribe.co.uk:1337
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```
However I get 
```
Uncaught UnrecognizedURLError: /api/v1/auths
```

In the browser.

Is there a step I might have forgot or has there been a change that would mean I shouldn't expect this to work anymore?

Cheers

w

**Comment by stefanpenner** [comment]
this feature is typically for API requests.

**Comment by wayne-o** [comment]
Yeah I'm using it for API requests

I need it as oAuth requires my API and app to be on the same url

**Comment by wayne-o** [comment]
So app 4200 and API 1337

dev.festivaltribe.co.uk is mapped to loop back

**Comment by wayne-o** [comment]
seems to be working - I think I got confused in that it doesn't seem to work from the browser directly but through the app it does - so the ember JS code it works - putting the URL in the browser does not.

**Comment by wayne-o** [comment]
As a side - what is ember g http-proxy used for? Is it basically the same thing as what I am achieving with this switch?

**Comment by stefanpenner** [comment]
> As a side - what is ember g http-proxy used for? Is it basically the same thing as what I am achieving with this switch?

its for more complex proxy scenarios, with multiple end-points, or needing to inject some headers / auth.

**Comment by wayne-o** [comment]
Apologies for the x post - I have put this on SO also.

I am trying to turn this: https://github.com/JamesMGreene/qunit-assert-html
into an ember-cli-addon (
https://github.com/wayne-o/ember-cli-qunit-assert-html ) I have read
https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5 which is great
but I am stuck figuring out how to make the qunit-assert-html.min.js
available in my tests. All I have done so far is add the file to /vendor
and then imported it inside index.js:
https://github.com/wayne-o/ember-cli-qunit-assert-html/blob/master/index.js
npm linking the add-on into my project successfully adds the
/vendor/qunit-assert-html.min.js to my apps /vendor folder but I can't
figure out how to make that available in my integration tests. Any help
appreciated!

I am also wondering where the general real time ember-cli chitchat takes
place as I am aware this is probably not the best forum for this question.

**Comment by stefanpenner** [comment]
Likely the embarks community slack room
