### ISSUE TITLE
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli#4904]
I still get this on 1.13.1 and now at 1.13.8

How do I fix this? 

```
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
version: 1.13.8
```

**Comment by stefanpenner** [comment]
i suspect one of your add-ons is using ember-cli/lib/errors/silent.js i would search node_modules for it, and report to the offending addon's repo.

**Comment by mmahalwy** [comment]
@stefanpenner will check now and find out what is

**Comment by stefanpenner** [comment]
Thanks

**Comment by mmahalwy** [comment]
Was coming from: https://github.com/lytics/ember-cli-release

But it's also present with ember-cli-deploy
