### ISSUE TITLE
Extract Broccoli Plugins

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#4907]
There really isn't a need for [broccoli-config-loader](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/broccoli-config-loader.js) and [broccoli-config-replacer](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/broccoli-config-replace.js) to be embedded in this project. Instead they can be Ember CLI sanctioned addons that use `contentFor` and `treeFor` to get this done.

**Comment by stefanpenner** [comment]
Agreed

**Comment by acorncom** [comment]
Looks like this issue can be closed
