### ISSUE TITLE
No support for testem.js

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli#4908]
While trying to define [testem.js instead of testem.json](https://github.com/airportyh/testem/blob/master/docs/config_file.md), I ran into some errors that seem to indicate that the testem.js wasn't getting picked up. I did some digging and it appears that ember-cli [assumes that testem.json is used](https://github.com/airportyh/testem/blob/master/docs/config_file.md
https://github.com/ember-cli/ember-cli/blob/master/lib/commands/test.js#L59). We probably need to pass the `test_page` and `launch` parameters directly into the testem api instead of re-writing testem.json.

I'm planning on putting together a PR.

I need to define testem.js so I can define a [custom reporter](https://github.com/airportyh/testem/blob/master/docs/custom_reporter.md).

**Comment by stefanpenner** [comment]
> I'm planning on putting together a PR.

:+1:

**Comment by asakusuma** [comment]
@stefanpenner @chadhietala ran into a bit of a pickle and want ya'lls opinions.

When ember-cli invokes testem, it [modifies cwd](https://github.com/ember-cli/ember-cli/blob/058528977255d0e366b8a1760668875cfadf9067/lib/tasks/test.js#L42). This doesn't affect loading testem.json, because testem uses `fs` to read json configs. However, testem relies on `cwd` to to resolve testem.js config files, since it has to use `require`. ember-cli modifies `cwd` to be the build directory, so testem ends up trying to load the dummy [testem.js](https://github.com/ember-cli/ember-cli/blob/058528977255d0e366b8a1760668875cfadf9067/lib/broccoli/testem.js) file which happens to be in the output directory.

Right now I see 4 options:

1. Figure out a way to make ember-cli work without modifying the testem cwd
2. Have ember manually resolve a testem config file, and if it happens to be a javascript file, provide an absolute path
3. Move the existing testem.js (for running testem in the browser) to a different filepath and copy /testem.js to `outputPath`/testem.js
4. Open a PR in testem to ignore the passed in cwd with regards to loading configs

From my limited vantage point, I think option 1 would be ideal, but I'm going to guess that option 2 is the most realistic. Thoughts?

**Comment by stefanpenner** [comment]
@johanneswuerbach thoughts?

**Comment by asakusuma** [comment]
If we go the testem PR route, I think that would be as simple as creating a version of `resolvePath()` that uses process.cwd instead of the passed in cwd, and then use this function for resolving config paths:

https://github.com/airportyh/testem/blob/master/lib/config.js#L53

**Comment by johanneswuerbach** [comment]
Testem maintainer here :-)

@asakusuma I like your solution, but that sounds like a breaking change. The other option I could imaging is to add a `configPath` property or something similar to allow projects to define where testem looks for configs. Having ember-cli doing the lookup sound error prone. PR more then welcome :-)

**Comment by asakusuma** [comment]
@johanneswuerbach thanks for prompt reply, I will open a testem PR for a configPath property.

**Comment by asakusuma** [comment]
Testem PR here: https://github.com/airportyh/testem/pull/643

**Comment by johanneswuerbach** [comment]
Released in `0.9.6`

**Comment by asakusuma** [comment]
Thanks @johanneswuerbach 

@stefanpenner ran into another issue:

In order for ember-cli to implement test params like `--filter=jshint`, it has to modify the query params on the `test_page` config passed to testem via the config file. Right now ember-cli accomplishes this by assuming the config is `testem.json` and writing to this file. If we want to support all config file types, we probably want to avoid this approach of writing to config files. Immediate solutions I can think of:

1. Ember-cli assumes that the test_page config is always 'tests/index.html', appends any filters, and passes in the config to the programatic testem API.
2. We add a testem API config to allow addition of query params or general string manipulation to test_page config passed in via config file.

**Comment by stefanpenner** [comment]
2 sounds ideal

**Comment by johanneswuerbach** [comment]
Also to me, mind opening another PR?

**Comment by asakusuma** [comment]
Yep I will open another PR today

**Comment by asakusuma** [comment]
Sorry this took so long, PR here: https://github.com/airportyh/testem/pull/644
