### ISSUE TITLE
wrapInEval no longer supported?

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/ember-cli#4910]
Hey,

should using the `wrapInEval` hack for creating sourcemaps still work? I'm running latest master and I have the following config in my `ember-cli-build.js` file (you can test by adding the below config to a brand new app)

```
sourcemaps: {
  enabled: false,
  sourceMap: false
},
wrapInEval: true
```

The outputted app JS modules don't get wrapped in an `eval`. Is my config wrong or is it no longer supported?

There are also various tests testing for its behaviour https://github.com/ember-cli/ember-cli/search?utf8=%E2%9C%93&q=wrapInEval&type=Code

**Comment by rwjblue** [comment]
I do not believe that `wrapInEval` is used any more.

**Comment by patocallaghan** [comment]
Ah okay, having sourcemaps enabled makes my incremental build jump from ~8 to ~16 seconds. Was hoping to disable them and just fallback to the eval approach.

Is there any reason why the tests are still in the repo?

**Comment by stefanpenner** [comment]
@patocallaghan some things worth considering:

1. restore wrapInEval
2. sourceMap [sections support](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k) to broccoli-sourcemap-concat (so sourceMap concat becomes much less costly for chrome users) The downside is the maps only work for chrome right now
3. make sourceMap concat faster....

**Comment by stefanpenner** [comment]
> Is there any reason why the tests are still in the repo?

maybe a mistake.
