### ISSUE TITLE
error installing ember-cli on new MBP

### ISSUE THREAD

**Issue by anthonybrown** [ember-cli/ember-cli#4919]
I can't seem to install `ember-cli`
here is the `npm-debug-log`  
https://gist.github.com/anthonybrown/24a0c3e2c211d8973935

**Comment by stefanpenner** [comment]
seems like your compiler isn't set up correctly, you can bypass optional native dependencies with:

```sh
npm install -g --no-optional ember-cli
```

**Comment by anthonybrown** [comment]
I'm sorry, you mean my xcode?

**Comment by stefanpenner** [comment]
47210 verbose stack Error: bufferutil@1.1.0 install: `node-gyp rebuild`

typically indicates a a compiler issue, or your version of node isn't compatible with that native extension (I believe node 4 and npm v3 people may have such issues)

**Comment by anthonybrown** [comment]
Thanks @stefanpenner, I'll look into that. I was hoping not to run into any issues on my new machine

**Comment by anthonybrown** [comment]
ember-cli did install with those flags, thanks
