### ISSUE TITLE
Asset paths not updated in index.html when changing outputPaths

### ISSUE THREAD

**Issue by ianwalter** [ember-cli/ember-cli#4921]
i.e., setting:
```js
outputPaths: {
  app: {
    js: '/js/application-name.js'
  }
}
```
Doesn't update script src in index.html from `assets/` to `js/` :
```html
<script src="assets/application-name.js"></script>
```

**Comment by stefanpenner** [comment]
yes, i believe this is the developers responsiblity.

**Comment by ianwalter** [comment]
I probably should have filed this in `ember-deploy-s3` because normally with this adapter when you build for production it pushes the assets to s3 and automatically rewrites the script src to match the s3 url, but if you specify the outputPaths it does't work. Closing, thanks.
