### ISSUE TITLE
How to pause component integration test?

### ISSUE THREAD

**Issue by heygrady** [ember-cli/ember-cli#4924]
Integration tests are the best! When I'm working on a new acceptance test, the ability to `pauseTest()` is a life saver. It's very helpful to be able to see what the test suite is rendering.

Is it possible to `pauseTest()` in an integration test?

**Comment by stefanpenner** [comment]
> Is it possible to pauseTest() in an integration test?

not currently. I believe you can do `stop()` (if you are using qunit)

We have plans to unify the helpers though

**Comment by heygrady** [comment]
Truth. `stop()` works.

**Comment by stefanpenner** [comment]
Im going t close this for now, as it is part of a larger ember-test-helpers discussion. Don't worry it wont be forgotten.

**Comment by jrowlingson** [comment]
`stop()` has been replaced by `assert.async()` in qunit 2.x

**Comment by Juraci** [comment]
@jrowlingson true, in the integration test it will be something like this:

```javascript
test('foo', (assert) => {
  const done = assert.async();

  // render the component
  this.render(`hbs{{your-component}}`);

  // pauses for 20 seconds
  setTimeout(() => done() }, 20000);
});
```

**Comment by steventsao** [comment]
Or `pauseTest` from test-helpers https://github.com/emberjs/ember-test-helpers/blob/17f4fbb1faf960db99d2d643d458b8feda383ac8/API.md#pausetest
