### ISSUE TITLE
Two projects created when defaults not passed to EmberApp in ember-cli-build.js

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli#4933]
For an Ember app, ember-cli-build.js receives an argument `defaults`, which it is expected to pass into the `EmberApp` constructor, along with another options argument. If the `defaults` argument is not passed along, the result is some very confusing behavior. The EmberApp has not reference to the `Project` instance previously created, so it creates a new one [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L128). This results in a separate set of addons being created per project. Confusingly, `included` is called on one set of the addon instances, while other hooks, such as `postBuild`, are called on the second set of addon instances.

I would happy to try to make this edge case less gnarly, but I need to understand what the legit use case of the project creation path is.

**Comment by rwjblue** [comment]
FYI - The behavior you describe was the same as all versions before moving to ember-cli-build.js (because there was no way to pass in the instantiated project to the Brocfile.js), it is indeed annoying. The move to ember-cli-build.js makes this MUCH better. 

Seems like we should detect < 2 args to the constructor (or detect that project is not passed in) and provide a nice helpful warning...

**Comment by elucid** [comment]
Apologies if this is a naïve question but is the passed in project ever used within the build file context or is it always just passed along?

**Comment by rwjblue** [comment]
@elucid - It might be used in the build file, but it is not used by the default `ember-cli-build.js` file.

**Comment by stefanpenner** [comment]
> I would happy to try to make this edge case less gnarly, but I need to understand what the legit use case of the project creation path is.

@lukemelia We could consider making project a mandatory input?

**Comment by lukemelia** [comment]
@stefanpenner sounds like a simple solution. If there are no known downsides to it, I'm happy to PR a guard.

**Comment by rwjblue** [comment]
:+1: to requiring `project` and failing as loudly/early as possible...

**Comment by stefanpenner** [comment]
killing the fallback behavior in 2.x seems good, if possible could you also implement a deprecation for the 1-13-stable branch?

**Comment by stefanpenner** [comment]
@lukemelia is this still an issue? (i suspect so)

**Comment by nathanhammond** [comment]
@Turbo87 Is this addressed by the cleanup that you did?

**Comment by Turbo87** [comment]
@nathanhammond no idea TBH

**Comment by nathanhammond** [comment]
@lukemelia Can you confirm if this issue still exists?

**Comment by stefanpenner** [comment]
@trentmwillis I believe we either work around this at work, or the issue has been resolved. Can you confirm or deny? Otherwise, I'll take a deeper look.

**Comment by bertdeblock** [comment]
@lukemelia I know this issue is very old, but if you have some time, would you mind checking if this issue still exists?

**Comment by locks** [comment]
Closing as stale. Thanks for the discussion everyone!
