### ISSUE TITLE
Build keeps re-adding all files when using Watchman

### ISSUE THREAD

**Issue by constantm** [ember-cli/ember-cli#4939]
It looks like when I use watchman, it keeps re-adding all the files in the folder for no reason at all, causing Ember CLI to be unusable. The build times say around 4 seconds, but with the files being re-added it takes a lot longer. When removing Watchman from my system, it doesn't do this. Not sure where to even start looking for what's causing this?

```
OSX 10.11
Watchman 3.8.0
version: 1.13.8
node: 4.1.2
npm: 2.13.4
os: darwin x64
```

Terminal output:

`...` used for brevity.

```
file added locale/me.js
file added locale/mk.js
file added locale/ml.js
file added locale/mr.js
...
file added min/locales.min.js
file added libs/qunit/qunit.css
file added test/backstretch.html
file added libs/jquery/jquery.js
...
file added templates/components
file added templates/companies.hbs
file added templates/users
file added templates/loading.hbs
file added styles/active_admin.scss
file added styles/app.scss
file added styles/app_header_styles.scss
file added styles/bootstrap-datepicker-overrides.scss
file added styles/bootstrap-datepicker.scss
file added styles/bootstrap-select-overrides.css
...
file added templates
file added router.js
file added components/nop-link.js

Build successful - 6077ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 4370ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 4370ms

file added locale/me.js
file added locale/mk.js
file added locale/ml.js
file added locale/mr.js
...
file added min/locales.min.js
file added libs/qunit/qunit.css
file added test/backstretch.html
file added libs/jquery/jquery.js
...
file added templates/components
file added templates/companies.hbs
file added templates/users
file added templates/loading.hbs
file added styles/active_admin.scss
file added styles/app.scss
file added styles/app_header_styles.scss
file added styles/bootstrap-datepicker-overrides.scss
file added styles/bootstrap-datepicker.scss
file added styles/bootstrap-select-overrides.css
...
file added templates
file added router.js
file added components/nop-link.js
```

**Comment by stefanpenner** [comment]
Yup a known issue. Boils down to a bug in OSX :s

It seems my current performance work on broccoli actually mitigates this nicely.

**Comment by constantm** [comment]
Aah okay. Couldn't find a listed bug, and frankly didn't have a clue what to search for. I'll be happy to help test if your changes are pushed to master.

**Comment by stefanpenner** [comment]
@constantm master already mitigates this somewhat. May even solve this Coro I already. My on-going work should squash it entirely

**Comment by constantm** [comment]
Awesome. I'll have a look then!

**Comment by constantm** [comment]
Okay it seems that `1.13.8-master-6cb9df3795` doesn't fix the Watchman file adding issue. Biggest slowdown in build is still Sass recompiling for no reason.

**Comment by stefanpenner** [comment]
the root cause is basically:

1. OSX bug causing grief for watchman
2. watchman confusingly reporting a `change` as an `add` after OSX starts dropping events.
3. broccoli doing more IO writes then we want
4. broccoli tmp living in the root of a watched path.

1 and 2 are out of our contorl
3 is an on-going effort
4 broccoli 1.0 should support this, but many plugins  (and ember-cli) need to be updated. This will likely be pursued soon.

**Comment by saerdnaer** [comment]
What's the current state of this issue?

I upgraded ember-cli and watchman today and now also run into this problem.
```
ember -v
  version: 1.13.13
  node: 0.12.7
  npm: 2.14.10
  os: darwin x64
watchman -v
  4.1.0
```

**Comment by stefanpenner** [comment]
@saerdnaer the above comment is the current status.

**Comment by constantm** [comment]
Issue is pretty much completely gone for me. I've run into it once where it said it recrawled twice, but that's nothing compared to how it was.
