### ISSUE TITLE
ember -v misreports NPM version

### ISSUE THREAD

**Issue by erbridge** [ember-cli/ember-cli#4940]
```
$ ember -v
Future versions of Ember CLI will not support v4.1.2. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.1.2
npm: 2.13.4
os: linux x64
$ npm --version
3.3.4
```

**Comment by stefanpenner** [comment]
@erbridge actually it reports correctly, this is the `npm` ember uses internally to reduce brittle issues.

**Comment by erbridge** [comment]
Aha. Makes sense.

**Comment by sly7-7** [comment]
Just to be sure, we can still use v4.1.2 or is this discouraged, and we should use 0.12 or io.js ?

**Comment by kellyselden** [comment]
@sly7-7 I'd say it's encouraged to use node v4, so we can get any bugs found cleared up :smile:

**Comment by sly7-7** [comment]
Okay.... so I just finished to make my capistrano / ember-cli-rails deployment working, seems like the ember-cli app is at least building well on node v4.1.2/npm 2.14.4.

**Comment by jiezhang917** [comment]
So I just leave it alone? It won't affect anything?

**Comment by sergiolepore** [comment]
@kellyselden 

"Future versions of Ember CLI will not support v4.1.2. Please update to Node 0.12 or io.js.", is that right? I mean, Node v4.x is the latest version. Replacing it with v0.12 will imply a downgrade, and io.js no longer exists since the creation of the Node.js Foundation :confused:

**Comment by rwjblue** [comment]
@sergiolepore - This issue is already fixed on master.

**Comment by sergiolepore** [comment]
@rwjblue thank you so much! :)
