### ISSUE TITLE
How can I make my addon supply vendor tree

### ISSUE THREAD

**Issue by maxbritto** [ember-cli/ember-cli#4942]
Hi all,

I am trying to make my addon supply vendor'd data to the app using it. The library is CKEditor (a customized version generated from the CKEditor builder).
I know I can use the addon blueprint to add a bower dependency but since CKEditor is customized I can't use bower to download that same version in the consuming app. 
I've used the **treeForPublic** and **broccoli funnel** to copy from my addon vendor folder the whole ckeditor folder to the app public folder (this is required by ckeditor).
My only issue is that the consuming app also needs to have the ckeditor folder in its vendor folder or it won't build because the watcher can't find it.
I was with the impression that if the addon was moving the folder to the public destination and was also importing js/css files in the **included** hook the original vendor'd folder was not needed by the final app.
Have I understood it wrong or can I do this without duplicating my ckeditor folder between the addon and the app ?

here is what I have so far : 
```
	included: function(app) {
		this._super.included(app);

		app.import('vendor/ckeditor_custom/ckeditor.js');
		app.import('vendor/ckeditor_custom/styles.js');
		app.import('vendor/ckeditor_custom/lang/fr.js');
		app.import('vendor/ckeditor_custom/skins/minimalist/editor.css');
	},

	contentFor: function(type, config) {
		if (type === 'vendor-prefix') {
			return "window.CKEDITOR_BASEPATH = 'assets/ckeditor/';";
		}
	},

	treeForPublic: function (tree) {
		var ckeditorTree = new Funnel('vendor/ckeditor_custom/', {
			srcDir: '/',
			exclude: ['**/.DS_Store','**/*.md'],
			destDir: 'assets/ckeditor'
		});

		return BroccoliMergeTrees([tree, ckeditorTree]);
	},

	treeForVendor: function (tree) {
		var ckeditorTree = new Funnel('vendor/ckeditor_custom/', {
			srcDir: '/',
			exclude: ['**/.DS_Store','**/*.md'],
			destDir: 'ckeditor_custom'
		});

		return ckeditorTree;
	},
```

Thanks for the help!

**Comment by stefanpenner** [comment]
I would recommend opening this on stackoverflow, as we try to keep this issue tracker focused on bugs.  SO provides a much better Q/A interface, and feel free to cross link from here.

**Comment by maxbritto** [comment]
Ok I understand. Here is the link to the stackoverflow question : http://stackoverflow.com/questions/33020226/how-can-i-make-my-ember-cli-addon-supply-a-vendor-tree
I'm closing the issue here.

**Comment by theseyi** [comment]
@maxbritto Were you able to come to a solution for this issue?  I see your stack-overflow question does not have an accepted answer?
I have a similar approach to your but included hook is actually called earlier in the build sequence before treeForVendor gets invoked and has a chance to build the vendor files.

Cheers

**Comment by maxbritto** [comment]
Hello, this was almost 2 years ago and I no longer work on this project now, so this is a bit blurry to me.
This was already working but I hated to have to duplicate the whole folder for every projet that used the addon.
Since nobody could help me fix this and other tasks were more important, I think I finally gave up :(
If you find a way, don't hesitate to post it on SO and I will accept the answer !
