### ISSUE TITLE
Need tests (blueprint and smoke) for `moduleForAcceptance`.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#4947]
This was added in https://github.com/ember-cli/ember-cli/pull/4692, but I don't see any tests in the repo for `moduleForAcceptance`.

I fixed an issue in https://github.com/ember-cli/ember-cli/pull/4946, but we need tests to ensure this is functioning properly...

@seanpdoyle - Do you think you could take a look at this?

**Comment by seanpdoyle** [comment]
@rwjblue gladly.

Is there an example of a test running EmberCLI-generated code?

**Comment by rwjblue** [comment]
Yeah, I think @kellyselden has a better handle on the current best practices than I, but you would generally add a new smoke test that used `moduleForAcceptance('asdf', { beforeEach() { }, afterEach() { });` and confirm that those get called in the correct order and with the expected arguments.
