### ISSUE TITLE
outputPaths always send the app css

### ISSUE THREAD

**Issue by dukex** [ember-cli/ember-cli#4948]
Hi everyone

Given the current [ember-app.js#L183-L185](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L183-L185):

```
    app: {
...
      css: {
        'app': '/assets/' + this.name + '.css'
      }
``` 

This 'requires' that all projects using ember-cli has the app.css file, and cause a bug in projects like [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass) and [ember-cli-less](https://github.com/gdub22/ember-cli-less) when using the follow config:

````
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'theme-orange': '/assets/theme-orange.css',
        'theme-purple': '/assets/theme-purple.css'
      }
    }
  }
});
```

I believe the problem is in ember-cli because the outputPaths always has the app css even when the app override the config

```
> options.outputPaths
{ 'theme-orange': '/assets/theme-orange.css',
  'theme-purple': '/assets/theme-purple.css',
  app: '/assets/myapp.css' }
```


Related: 
https://github.com/aexmachina/ember-cli-sass/issues/81
https://github.com/gdub22/ember-cli-less/issues/30

**Comment by aexmachina** [comment]
Any movement on this issue? Is the fix to remove any keys that are not defined in the incoming array?

**Comment by zzarcon** [comment]
I'm having the same issue in my app, some news?

**Comment by dukex** [comment]
@zzarcon I send a pull request

**Comment by zzarcon** [comment]
@dukex :heart_eyes:

**Comment by Turbo87** [comment]
@dukex have you tried setting it like this?

```js
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'app': null,
        'theme-orange': '/assets/theme-orange.css',
        'theme-purple': '/assets/theme-purple.css'
      }
    }
  }
});
```

**Comment by nathanhammond** [comment]
Closing with the `app: null` workaround and lack of activity.
