### ISSUE TITLE
Torii authenticatedRoute DSL breaks nested route registration

### ISSUE THREAD

**Issue by mwpastore** [ember-cli/ember-cli#4957]
Torii v0.6.0 introduced a new `authenticatedRoute` DSL to `app/router.js`, essentially injecting a mixin into any route defined with `this.authenticatedRoute(...)` cf. `this.route(...)` (I am not an expert so I may not be phrasing this 100% correctly). It works great. However, if you try to nest a route `bar` under an authenticated route `foo`, the subroutine does not recognize the syntax and creates a(n erroneous) new parent route `foo` under which to nest new route `bar`. Now there are two routes `foo`, which leads to all kinds of confusion and inconsistent behavior on navigation.

What's the best approach to fix this? Do we modify ember-cli to allow the `authenticatedRoute` keyword alongside the `route` keyword? Allow something more generalized, e.g. keywords matching `/\w*[rR]oute/`? Or should Torii itself provide an updated blueprint for ember-cli to use? 

```javascript
// app/router.js (before)
Router.map(function() {
  this.authenticatedRoute('foo');
});
```

```
$ ember g route foo/bar
version: 1.13.8
installing route
  create app/routes/foo/bar.js
  create app/templates/foo/bar.hbs
updating router
  add route foo/bar
installing route-test
  create tests/unit/routes/foo/bar-test.js
```

```javascript
// app/router.js (after)
Router.map(function() {
  this.authenticatedRoute('foo');

  this.route('foo', function() {
    this.route('bar');
  });
});
```

**Comment by rwjblue** [comment]
I believe that the bug would be in https://github.com/ember-cli/ember-router-generator, though I'm not sure that it is truly a bug.

**Comment by rwjblue** [comment]
Basically, the router generator looks for `this.resource('foo')` or `this.route('foo')` and adds a third argument as a function with the additional layer of nesting.

In this case, there is an unknown method (`this.authenticatedRoute`) and the generator has no clue what this thing is.  I'm not really in favor of forcing the router generator to be aware of all possible things (seems like way too much coupling), so I'm not sure that this is easily fixable.

**Comment by rwjblue** [comment]
@mixonic - Thoughts?

**Comment by mixonic** [comment]
Oof. So I thought there might be issues with the DSL. However the immediate solution I was thinking of was to use a non-DSL helper:

```js
import authenticatedRoute from 'torii/authenticated-route';

Ember.Router.map(function(){
  authenticatedRoute(this, 'foo.bar');
});
```

However this *also* would not work with the generators.

Passing an argument to the options of `this.route` is clumsy. Those options are really not intended for addons to use, and when I last looked the practicalities of using them used a bunch of private APIs. `this.authenticateRoute`, surprisingly, is a less invasive and brittle approach IMO.

@rwjblue would the following work with the existing system, or be made to work?

```js
import authenticatedRoute from 'torii/authenticated-route';

Ember.Router.map(function(){
  // perhaps this also needs to accept `this` as an argument
  authenticatedRoute(() => {
    this.route('foo');
  });
});
```

```js
Ember.Router.map(function(){
  this.authenticatedRoute(function() {
    this.route('foo');
  });
})
```

**Comment by rwjblue** [comment]
@mixonic - Yes, the current setup can be made to work (will require changes in ember-router-generator).  My concern is that adding Torii's customizations to `ember-router-generator` seems like a somewhat odd.  coupling. What happens when other addons do similar things? Do we add every possible addon to ember-router-generator?

**Comment by mixonic** [comment]
100% agree. I do not want to keep using `this.authenticatedRoute('foo'` if it means adding torii-specific code to the router generator.

Router DSL extensions are nothing Ember has a public API for. Torii is trailblazing a little and we should just adjust.

The the last two options I shared, `authenticatedRoute` is not actually a route. It is a scope over (and possibly nested inside of) routes. This means that the arguments passed to is need only be preserved, not parser or possible modified.

**Comment by ro0gr** [comment]
Looks very related https://github.com/emberjs/rfcs/pull/120

**Comment by Turbo87** [comment]
I fail to understand why `this.authenticatedRoute(...)` is superior compared to something like `export default Ember.Route.extend(Torii.AuthenticatedRoute);` as it is done by `ember-simple-auth`. In any case this doesn't seem to be an `ember-cli` issue and should be discussed/solved in https://github.com/ember-cli/ember-router-generator.

**Comment by nathanhammond** [comment]
"Superior" only because having good APIs is a feature. We ran into this again with engines, and @trentmwillis has solved it once and for all:
https://github.com/ember-cli/ember-router-generator/commit/bc7dd638d052e298e112a837a9a6f69a69bb4eee
