### ISSUE TITLE
Not working with Node v4.2.1

### ISSUE THREAD

**Issue by mjastorga** [ember-cli/ember-cli#4967]
Hello,

I saw on past issues that you were having trouble with node v4.1.0 and you fixed already in master.

Now I'm having the same issue with Node v4.2.1

When trying to run ember my-new-app I got this

Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
The specified command core is invalid. For available options, see `ember help`.

Running ember --version I see this

Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 4.2.1
npm: 2.13.4
os: darwin x64

**Comment by sly7-7** [comment]
Maybe I miss something, but it seems like you run against ember-cli 1.13.8. So, I think you should upgrade ember-cli using master

**Comment by mjastorga** [comment]
That worked, but still getting the "warning" of Future versions of Ember CLI will not support v4.2.1

**Comment by sly7-7** [comment]
Considering 
```
Running ember --version I see this
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.

*version: 1.13.8*
```
I think you'are running ember-cli 1.13.8, not ember-cli master, are you ?

**Comment by mjastorga** [comment]
Yep

**Comment by btecu** [comment]
@mjastorga the warning has been fixed on master already.
You just have to wait for a new version to be released.

**Comment by mjastorga** [comment]
Alright, thank you very much.

**Comment by ballPointPenguin** [comment]
Because ember-cli is included in package.json, after `npm install`, you may find yourself using the latest stable release and not master. You probably want to re-run `npm link ember-cli` after `npm install`.
