### ISSUE TITLE
[Question] Nested addon capabilities

### ISSUE THREAD

**Issue by mmelvin0** [ember-cli/ember-cli#4969]
We have an in-house addon (addon A) that depends on ember-cli-simple-auth (addon B).

In Ember CLI < 0.2.0, this nested addon "just works".

In Ember CLI >= 0.2.0, the following seems to be true:
* Upon installation of addon A, addon A's default blueprint runs, but addon B's default blueprint does not.
* During a build, addon A's included hook runs, but addon B's included hook does not.
* Since addon B adds an initializer that depends on something app.import()'d in its included hook, the whole thing doesn't work.

Worse, we have another in-house addon that depends on addon A, which further compounds the problem.

Is there any documentation for what nested addons can and cannot do?

What's the solution in my case? I figure I can just have the default blueprint for the top-level addon install whatever addons it depends on into the project, but that's ugly because now my dependencies are in code instead of package.json.

**Comment by stefanpenner** [comment]
> What's the solution in my case?

sibling add-ons likely, we will be re-freshing in the dependency story in the next month or so.
