### ISSUE TITLE
Ember 1.13.8, watchman v4.0.0 recognition

### ISSUE THREAD

**Issue by ajkamel** [ember-cli/ember-cli#4974]
When taking a look at https://github.com/ember-cli/ember-cli/blob/master/lib/models/watcher.js#L108

You can see that it calls semver.satisfies.  However when trying to create a new ember app with version 1.13.8 the watcher falls back to NodeWatcher rather than Watchman.

`Invalid watchman found, version: [4.0.0] did not satisfy [^3.0.0], falling back to NodeWatcher.`

If no range is supplied to `semver.satisfies` how is it not able to recognize version 4.0.0?

**Comment by stefanpenner** [comment]
4.x compatibility will need to be evaluated tested + then the line you indicate will need to be updated. I'm on vacation this week, so it is unlikely I will look at it until next week.

**Comment by vvscode** [comment]
The save 
``` version: 1.13.8
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher. ```

**Comment by lolmaus** [comment]
@vvscode, you'll have to use Watchman v3.9.0 until Ember CLI maintainers bump the dependency.

**Comment by vvscode** [comment]
@lolmaus I prefer patch ember-cli and use/test it with latest watchman. Thx

**Comment by lolmaus** [comment]
@vvscode Why don't you send a PR?

**Comment by patocallaghan** [comment]
Just came up against this too. You can install the 3.9 version of watchman by running

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew/1868d1011c805ec853ce28b303a0a297008a7fd1/Library/Formula/watchman.rb
```

If I get the time this week I can look at doing up/testing a PR.

**Comment by patocallaghan** [comment]
Seems there a PR for this already https://github.com/ember-cli/ember-cli/pull/5026

**Comment by stefanpenner** [comment]
will be released in next version

**Comment by pepesenaris** [comment]
Hello, I'm using ubuntu 14.04 and getting this error. The problems is that I do installed version 3.9.0 of watchman but ember-cli somehow says it's version 4.0.0.... any thoughts here?

**Comment by pepesenaris** [comment]
Solved my particular case.
The issue was that I had version 4.1.0 installed and after installing version 3.9.0 the watchman server from 4.1 was still running. That created a very annoying situation because when asking watchman version it correctly says 3.9, but ember-cli still reports an error as it tries to use 4.1.
Solution:  
`watchman shutdown-server` to stop server running 4.1
