### ISSUE TITLE
Come up with a nice "Welcome to Ember" design as part of initial setup

### ISSUE THREAD

**Issue by acorncom** [ember-cli/ember-cli#4977]
I've seen various references to a redesign coming for the main Ember site (done by thoughtbots), do we have a similar design for the "Welcome to Ember.js" page that is shown after initial setup?

Just a simple touch like that could make the initial startup with Ember feel much more polished.

See https://github.com/emberjs/website/pull/2393#issuecomment-150071985 for a glimpse of the upcoming design ...

**Comment by michaelrkn** [comment]
I think it would be helpful to link to the Guides, something like:

```html
<h2>Welcome to Ember.js!</h2>
<p>If you're not sure where to start, take a look at the <a href="http://guides.emberjs.com/" target="_blank">Ember Guides</a>.</p>
```

**Comment by joseperales** [comment]
@acorncom  @michaelrkn Cool !! so this issue should be in https://github.com/emberjs/ember.js

**Comment by michaelrkn** [comment]
@joseperales why do you say that?

**Comment by joseperales** [comment]
Because the index file is in emberjs not in ember-cli

**Comment by acorncom** [comment]
@joseperales The index file I was thinking we could update is this one here: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/index.html

**Comment by H3Chief** [comment]
I think it would actually be cool if the default page displayed to total output of `ember --help`

**Comment by acorncom** [comment]
Recommendation from @wifelette 

> How about… same background color as the redesign, `#FFFBF5`, and we just stick this dead center:
![Construction tomster](http://emberjs.com/images/tomsters/construction.png)
