### ISSUE TITLE
Windows: Tmp files still exist after exit

### ISSUE THREAD

**Issue by srsgores** [ember-cli/ember-cli#4978]
So far, I think this only occurs on Windows.  I end up with HUGE ``tmp`` folders on my ember-cli projects:

![image](https://cloud.githubusercontent.com/assets/1750837/10657544/5ae954ea-784a-11e5-9648-636d048cf071.png)

Perhaps [related to this](https://github.com/ember-cli/ember-cli/issues/1940)?

So I think we should try to fix this.

**Comment by kellyselden** [comment]
How are you exiting? CTRL+C should clean the tmp dir before it asks you to press it again to exit. If you just close the cmd window, the tmp will remain.

**Comment by raytiley** [comment]
I think there is an issue with windows not getting the sigterm event on windows. There was an idea to clean up tmp on startup but I believe that conflicts with some of @stefanpenner perf work. If you look at the tests I think I worked around this in CI by signaling ember-cli to quit over a socket (its been a while). 

Maybe we should capture `stdin` and do something like `Press 'q" to quit`.

**Comment by btecu** [comment]
`CTRL+C` is not enough. You have to wait for the prompt `Terminate batch job (Y/N)?` and press *Y*.
If you kill the process with `CTRL+C`, the `tmp` folder won't be cleaned.

**Comment by kellyselden** [comment]
For me, the reason it takes a while for the `Terminate batch job (Y/N)?` message to show up is because it's deleting all the tmp files. While that prompt is up and before I do anything, I check the tmp folder, and it has been emptied. The second CTRL+C is part of my flow, and doesn't hurt anything since my tmp folder is already wiped.

**Comment by stefanpenner** [comment]
> There was an idea to clean up tmp on startup but I believe that conflicts with some of @stefanpenner perf work

no, it breaks other on-going builds/runs.

**Comment by stefanpenner** [comment]
> For me, the reason it takes a while for the Terminate batch job (Y/N)? message to show up is because it's deleting all the tmp files. While that prompt is up and before I do anything, I check the tmp folder, and it has been emptied. The second CTRL+C is part of my flow, and doesn't hurt anything since my tmp folder is already wiped.

This tends to be the issue, we can in-theory attempt something more elaborate to purge on exit, but especially on windows it is dubious at best. The best solution will likely come from my on-going perf-work, where we just dramatically reduce the number of files created, thereby make it quicker to delete the given files.
