### ISSUE TITLE
Adding file to test tree via postprocessTree broken

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli#4982]
This issue is only happening on master, not 1.13.8. I came across this issue while testing [ember-browserify](https://github.com/ef4/ember-browserify) against ember-cli master.

In 1.13.8, you could import a custom file via the `include()` hook and then actually write that file to the test tree via `postprocessTree()`. This is now broken in master. The file can't be found. This only breaks for the test tree, not the regular js tree.

I have reproduced this issue here: https://github.com/asakusuma/addon-test-bug

In the repro addon, I included a tree in the `js` tree, which works fine even on master. Both trees are logged. On master, when the error occurs, the test tree is not logged, but the js tree is logged, which seems to indicate that the test tree is not being included soon enough.

If you take a look at [lib/broccoli/ember-app.js](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js), the way test imports are handled is different than regular js imports.

cc @ef4 @trentmwillis

**Comment by Turbo87** [comment]
looks like this got fixed by https://github.com/ember-cli/ember-cli/pull/4983
