### ISSUE TITLE
Add inflector generator

### ISSUE THREAD

**Issue by michaelrkn** [ember-cli/ember-cli#4984]
Currently, if a user wants to add a rule to the inflector, they have no guidance about where to do so. As a result, some people put their rules in the corresponding models, others in an initializer, and only [@rwjblue does it correctly](https://github.com/emberjs/guides/pull/899#issuecomment-149340100).

We're [adding documentation to the Guides encouraging @rwjblue's approach](https://github.com/emberjs/guides/pull/899), but ideally there would be a generator that would set things up along these lines:

```js
// in app/app.js

// sets up Ember.Inflector
import './models/custom-inflector-rules';
```

```js
// in app/models/custom-inflector-rules.js
var inflector = Ember.Inflector.inflector;
inflector.irregular('formula', 'formulae');
inflector.uncountable('advice');
```

**Comment by stefanpenner** [comment]
Sounds like a generator the inflector addon should provide.

**Comment by michaelrkn** [comment]
Closed in favor of https://github.com/stefanpenner/ember-inflector/issues/92.
