### ISSUE TITLE
Utils aren't importing into mixins

### ISSUE THREAD

**Issue by ascot21** [ember-cli/ember-cli#4990]
I can't seem to get utility modules that I've created to be imported into Mixins.

```
// app/utils/hello-world.js
export default function helloWorld() {
  console.log('Hello World');
}
```

and in a mixin I use the following to import:
```
import helloWorld from '../utils/hello-world'

export default Ember.Mixin.create({
 // mixin code here
});
```

I've successfully imported the same utility into a controller and a route but for some reason it doesn't work in mixins. I get `undefined` when I try to call `helloWorld()' anywhere in the mixin. 

I'm using Ember 2.2.0-beta.1 and Ember CLI 1.13.8

**Comment by stefanpenner** [comment]
I don't believe anything changed here, I quickly attempted to reproduce and was unable to, can you provide a reproduction I can work with?

Maybe just a fresh ember-cli app demonstrating the issue?

**Comment by ascot21** [comment]
@stefanpenner worked when I created a demo app so I went back and tried again and realized I was exporting the util incorrectly
