### ISSUE TITLE
final production build include full ember-data-factory-guy library in vendor.js

### ISSUE THREAD

**Issue by junos** [ember-cli/ember-cli#4993]
Please reference this ticket https://github.com/danielspaniel/ember-data-factory-guy/issues/140

The issue is: we need to get rid of "ember-data-factory-guy" library in vendor.js for production build.

Steps to re-production the issue:

add "ember-data-factory-guy" in package.json devDenendencies
npm install
import '"ember-data-factory-guy" in our test js file
excute ember cli build command in production mode
in vendor.js file, it include the full package of "ember-data-factory-guy"

**Comment by stefanpenner** [comment]
i don't believe this is a bug in ember-cli, as this can be accomplished by the provided addon hooks.

* https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#treefor-cont
* https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#treefor-cont
