### ISSUE TITLE
Could not find module site/app

### ISSUE THREAD

**Issue by celicoo** [ember-cli/ember-cli#4997]
I just start a new ember application using ember-cli and i'm struggling with this problem. In my console i'm seeing this "Could not find module site/app"... What is that, and more important.. how could i fix?

**Comment by celicoo** [comment]
i'm*

**Comment by stefanpenner** [comment]
can you provide a reproduction of the issue? the provided information is not sufficient to diagnose ...

**Comment by celicoo** [comment]
Hello @stefanpenner!!

I ended up not solving the problem .. so i deleted the code and started a new project.

Thank you anyway.
