### ISSUE TITLE
Node 4.x ember cli warning

### ISSUE THREAD

**Issue by Jakobud** [ember-cli/ember-cli#5003]
```
# ember -v
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 4.2.1
npm: 2.13.4
os: darwin x64
```

Node 4.x has been out a couple months now and is moving fast. Just FYI for you guys. I'm a new ember user (trying out the Getting Started Guide) and this is the first thing I see when I installed `ember-cli` for the first time. Didn't give me a great first impression of Ember unfortunately.

**Comment by wayne-o** [comment]
This has been logged (search issues 1st) and the guys have said a new
release will be out soon.

JS is moving super fast atm you can't reasonably expect everything to be
consistent at all times.

There are no adverse effects (afaik) from ignoring this message.

Try not to be so harsh :)
