### ISSUE TITLE
Node.JS 4 in travis builds

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-cli/ember-cli#5007]
[.travis.yml](https://github.com/ember-cli/ember-cli/blob/528577abb0bb6aeae0b9ed4ff1690885a0cea33d/.travis.yml) doesn't include node.js 4 in build matrix. Is this intentional? Since node.js is now officially calling 4.2 its [LTS release](https://nodejs.org/en/blog/release/v4.2.1/) it would probably be a good idea to include it.

**Comment by stefanpenner** [comment]
sure, feel free to submit a PR adding it in addition to https://github.com/ember-cli/ember-cli/blob/master/.travis.yml#L6
