### ISSUE TITLE
Slow ember-cli build times

### ISSUE THREAD

**Issue by theDickie** [ember-cli/ember-cli#5013]
Yeah g’day

I've been experiencing long builds ever since upgrading to a newer iMac. Nothing changed significantly in the code or dependencies, and my colleague (also a Mac) working on the same project is not experiencing the problem. This would suggest it was the new computer, but the general specs are all higher, I have less installed, and even with no other apps open I'm experiencing these painfully slow ember-cli build times.

The slow trees are not necessarily the same ones each time, as displayed in the three outputs below. 
```
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 25249ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 18908ms             
TemplateCompiler                              | 2075ms              
JSHint app- QUnit                             | 1761ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (6)                                     | 19117ms (3186 ms)   
TemplateCompiler (2)                          | 2104ms (1052 ms)    
JSHint app- QUnit (1)                         | 1761ms
```
```
Build successful - 30506ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SassCompiler                                  | 29218ms             

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SassCompiler (1)                              | 29218ms 
```
```
Build successful - 39688ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
ES6: App Tree                                 | 30182ms             
SassCompiler                                  | 7361ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
ES6: App Tree (1)                             | 30182ms             
SassCompiler (1)                              | 7361ms 
```
Any help in debugging this mucho appreciado.

**Comment by runspired** [comment]
Does your mac have an SSD?
Did you install Watchman?
Did you remember to turn off filewatchers on `dist` and `tmp` that your code editor may use (Webstorm and Sublime both have obnoxiously aggressive indexing, others likely do too).

**Comment by stefanpenner** [comment]
`npm v3` changes the node_modules topology, which is potentially causing larger trees of directories to be considering for the "cache key". I would recommend using npm v2 for now to prevent that.

Also, `ES6: App Tree` is more handled much better on master. I would recommend using master until we have time to cut a release: https://github.com/ember-cli/ember-cli#working-with-master

**Comment by andorov** [comment]
I was seeing the same issues - SassCompiler the slowest every time, and occasionally a 30s+ recompile.  Switching from `npm v3` to `npm v2` fixed it.

El Capitan 10.11.1
MacBook Pro w SSD
Watchman 3.9.0
vim

**Comment by theDickie** [comment]
This may be a hardware issue. The computer's off to the Apple shop this week to check. I'll close the issue if this turns out to be the case. Thanks for everyone's input thus far.

**Comment by stefanpenner** [comment]
> I was seeing the same issues - SassCompiler the slowest every time, and occasionally a 30s+ recompile. Switching from npm v3 to npm v2 fixed it.

let me give this a go aswell

**Comment by stefanpenner** [comment]
ok, was able to confirm. It appears something in the topology shift is causing basically all of node_modules to be included inside vendor/ I will investigate what is causing it after lunch.

**Comment by stefanpenner** [comment]
ember-cli-ic-ajax 0.2.4 has been released, and it should not longer be accidentally including all of node_modules into the broccoli pipeline. (adding another 100k files to the pipeline will slow it down still, hopefully soon that will not be the case)

I'll likely be adding some warnings to help catch this in the future.
