### ISSUE TITLE
in-repo addons cannot specify dependencies

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#5016]
I'm trying to build an in-repo addon that wraps https://github.com/jonathantneal/svg4everybody.

I tried adding `dependencies` and `devDependencies` to `lib/svg4everybody/bower.json` and `lib/svg4everybody/package.json`. None of those caused the dependencies to show up in my `node_modules/` or `bower_components/`. The dependencies in question are sv4everybody itself and broccoli-funnel so I can build a tree.

**Comment by jamesarosen** [comment]
(I'm guessing that since those addons are loaded by ember-cli, Bower and NPM would never see the config files. In that case, I would next try `addBowerPackageToProject` in `afterInstall`, though I'm not sure that hook fires for in-repo addons.)

**Comment by stefanpenner** [comment]
After some thought, this seems like an interesting use-case. I would like to recommend this be reopened as an RFC, this would allow us to flesh out the details as a new use case (which i believe it is).

**Comment by jamesarosen** [comment]
RFC: ember-cli/rfcs#60
