### ISSUE TITLE
Issues with exports at top of file on ember-cli master

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#5022]
I am not sure what repo this issue falls under, I am seeing an issue with exports at top of files now being undefined when they used to work properly on ember cli 1.13.8, it would seem some dependency change or code change would be the culprit?  

following instructions in README (https://github.com/ember-cli/ember-cli#working-with-master)

node v5.0.0 (also seeing it on node v0.12.7)
ember-cli version: 1.13.8-master-a1168a7219
npm 2.14.8

this used to work fine but now with ember-cli-master, it doesn't properly export it, it instead exports it as undefined

```
import {hop} from './utils';

export {defineProperty, objCreate};

// Purposely using the same implementation as the Intl.js `Intl` polyfill.
// Copyright 2013 Andy Earnshaw, MIT License

var realDefineProp = (function () {
    try { return !!Object.defineProperty({}, 'a', {}); }
    catch (e) { return false; }
})();

var es3 = !realDefineProp && !Object.prototype.__defineGetter__;

var defineProperty = realDefineProp ? Object.defineProperty :
        function (obj, name, desc) {

    if ('get' in desc && obj.__defineGetter__) {
        obj.__defineGetter__(name, desc.get);
    } else if (!hop.call(obj, name) || 'value' in desc) {
        obj[name] = desc.value;
    }
};

var objCreate = Object.create || function (proto, props) {
    var obj, k;

    function F() {}
    F.prototype = proto;
    obj = new F();

    for (k in props) {
        if (hop.call(props, k)) {
            defineProperty(obj, k, props[k]);
        }
    }

    return obj;
};
```
https://github.com/yahoo/intl-messageformat/blob/master/src/es5.js

it is imported in another file 

```
import {defineProperty, objCreate} from './es5';
```

https://github.com/yahoo/intl-messageformat/blob/master/src/core.js

moving the export ``` export {defineProperty, objCreate}; ``` to bottom of file fixes it

you can also replicate just by adding ember-intl to a new project which uses said library and visit localhost:4200 which gives you ``` Uncaught TypeError: (0 , _intlMessageformatEs5.defineProperty) is not a function ``` in the console and a white screen

``` 
ember new foo
cd foo
ember install ember-intl@2.0.0-rc.4
npm link ember-cli
ember server
```

**Comment by jcope2013** [comment]
screenshots of the file in the compiled vendor.js of the same ember new app, maybe the fix is that exports should always be declared at bottom of file and it was doing something in the past to move them around?

1.13.8 (exports at bottom)

<img width="625" alt="screen shot 2015-10-31 at 11 53 56 am" src="https://cloud.githubusercontent.com/assets/3374461/10865911/87747dfa-7ff2-11e5-8f4d-57f99b045610.png">

master (exports at top)

<img width="613" alt="screen shot 2015-10-31 at 5 11 15 pm" src="https://cloud.githubusercontent.com/assets/3374461/10865919/b089eb26-7ff2-11e5-95e9-82cb6462d67b.png">

**Comment by rwjblue** [comment]
1.13 uses Esperanto for module imports/exports, and master uses only Babel. 

Esperanto was doing a bit of work to ensure the ordering was correct in the output (after a number of similar issues were reported), and I'm guessing that Babel might need some tweaks.

**Comment by jasonmit** [comment]
Looks to be related to https://github.com/babel/babel/issues/2536

Referencing for tracking

**Comment by stefanpenner** [comment]
will reopen if reproduction is provided
