### ISSUE TITLE
New install of ember 1.13.8 on OS X Yosemite fails to find installed watchman if version > 3.x.x

### ISSUE THREAD

**Issue by taikisuru** [ember-cli/ember-cli#5024]
Looks like a major version >3.x.x isn't detected?

$ ember -v
version: 1.13.8
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.0
npm: 2.13.4
os: darwin x64

$ watchman -v
4.1.0

$ npm -v
3.3.10

$ node --version
v0.12.0

**Comment by stefanpenner** [comment]
fixed on master

**Comment by taikisuru** [comment]
Cheers!

**Comment by lukemelia** [comment]
@stefanpenner The watchman version check doesn't seem to be updated on master unless I'm missing something. https://github.com/ember-cli/ember-cli/commits/master/lib/models/watcher.js

**Comment by rwjblue** [comment]
Confirm:

* https://github.com/ember-cli/ember-cli/blob/master/lib/models/watcher.js#L108 still looks for `^3.0.0` (should be updated to `>= 3.0.0 < 5.0.0` I believe)
* https://github.com/ember-cli/ember-cli/blob/master/lib/models/watcher.js#L114 still looks for `^3.7.0` (should be updated to `>3.7.0`)

**Comment by djmrr** [comment]
I'm not the sharpest tool in the shed but I'm seeing when I try to run 'ember serve'/'ember server' that it argues with me and my version of watchman that I installed through homebrew.
```
version: 1.13.8
Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
2015-11-01 16:51 ember[6068] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-11-01 16:51 ember[6068] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
2015-11-01 16:51 ember[6068] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)
```

**Comment by jcope2013** [comment]
https://github.com/ember-cli/ember-cli/pull/5026
