### ISSUE TITLE
"Future Versions" Node error out-of-date

### ISSUE THREAD

**Issue by patocallaghan** [ember-cli/ember-cli#5027]
Running Node 5.0 gives the Node support error

```
Future versions of Ember CLI will not support 5.0.0 Please update to Node 0.12 or io.js.'
```

https://github.com/ember-cli/ember-cli/blob/3c615aa55dfe6be1adf14ef67e74028b09560138/lib/cli/cli.js#L58

I'll can cut a PR for this but what should it be saying here instead? It seems outdated to be referencing 0.12 and io.js

**Comment by stefanpenner** [comment]
It should likely just warn that the version is untested and may have issues. (Or something along those lines)
