### ISSUE TITLE
Can't run ember test with ssl flag enabled

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#5029]
Our apps are setting/reading a number of secure cookies (set via our login component). While `ember serve --ssl` is supported, `ember test --ssl` is not.

As a results acceptance tests are failing (the login component set a `secure` cookie but none of the components are able to read it).

Any suggestions?

**Comment by olivierlesnicki** [comment]
So after reading through the `testem` documentation, one can request `testem` to run in https by passing a path to a `server.key` and a `server.certificate` in the `testem.json` like so:

```json
  "key": "ssl/server.key",
  "cert": "ssl/server.crt",
```

However, this configuration causes the `ember test` command to timeout - the app builds and then nothing happen. Running `ember test --server` actually runs the test correctly in all browsers but `phantom`.

Steps to replicate:
- Clone this app https://github.com/olivierlesnicki/ember-test-app-ssl
- Run `ember test`

**Comment by olivierlesnicki** [comment]
Any views on what can be done?

**Comment by stefanpenner** [comment]
@olivierlesnicki support for this needs to be added.

**Comment by olivierlesnicki** [comment]
Adding these properties to `testem.json` achieves the requirement:
```
  "key": "ssl/server.key",
  "cert": "ssl/server.crt",
  "phantomjs_args": [
    "--ignore-ssl-errors=true"
  ],
```

**Comment by stefanpenner** [comment]
> Adding these properties to testem.json achieves the requirement:
