### ISSUE TITLE
Assets cannot be excluded from being minified/uglified in production mode. Functionality or documentation missing

### ISSUE THREAD

**Issue by ohcibi** [ember-cli/ember-cli#5034]
In the documentation it is told that one can disable minification of css or js assets in general via.

```
minify(JS|CSS): {
    enabled: false
}
```

(I assume that this configuration goes into

```
EmberApp(defaults, {
    ....
});
```

which is by the way absolutely unclear when reading the docs. Its a general problem with embers documentation, that I dont want to address in this issue: code-snippets need more context!)

I want to only exclude vendor files from being minified, since they are already minified. I got a hint from @rwjblue and @stefanpenner that one could use the `exclusion` configuration from https://github.com/ef4/broccoli-uglify-sourcemap and to put it in `ember-cli-build.js`. The example looks like:

```javascript
var uglified = uglify(input, {
  //...
  exclusion: [..] // array of globs, to not minify
  //...
});
```

 but there are certain things unclear:

1. **Where** should I put this option? The example in the readme of the repository tells to pass it to the compiler, but one is not actually calling the sourcemaps-compiler in `ember-cli-build.js`, plus there is an `input` variable in the examples which is not even available in `ember-cli-build.js`
3. **What path** should one pass as configuration? The path of the compiled file (residing in `dist/`) or the path of the original source file (e.g. `bower_components/bootstrap/bootstrap.min.js`).
If its a path of the compiled file: what options do I have for assets that are `app.import`'ed into the `vendor.js` file to avoid minification for those assets?
2. Why is this a configuration option of the sourcemaps project? Actually I want to exclude the assets from being minified. Sourcemapping shouldn't happen anyways in production mode? How does this relate?

I'm happy to file a PR for documentation when this is clear to me.

**Comment by coulix** [comment]
In environment.js

      if (environment === 'production') {
        ENV.minifyJS = 
            enabled: false,
        };
     }

The files are still concatenated and space stripped out.

**Comment by ohcibi** [comment]
@coulix this is about how to exclude certain assets from being minified and not how to enable/disable completely? I updated the issue to make it a bit more clear

**Comment by twokul** [comment]
> which is by the way absolutely unclear when reading the docs. Its a general problem with embers documentation, that I dont want to address in this issue: code-snippets need more context!)

documentation can always be improved, we always welcome PRs :+1: 

It seems like you can pass options to [broccoli-uglify-sourcemap](https://github.com/ef4/broccoli-uglify-sourcemap), see [ember-cli-uglify](https://github.com/ember-cli/ember-cli-uglify/blob/master/index.js#L13):

```javascript
module.exports = function(defaults) {
  var app = new EmberApp(defaults);

  if (app.env === 'production') {
    app.options.minifyJS.options = {
      // exclude vendor minified files
      exclusions: ['hey', 'you']
    }
  }

  return app.toTree();
};
```

@ohcibi let us know if that works for you.

**Comment by stefanpenner** [comment]
@twokul we should fix it so you can pass it in to EmberApp (fix the merging)

**Comment by twokul** [comment]
@stefanpenner sure thing, dude. I'll PR, just wanted to unblock @ohcibi

**Comment by stefanpenner** [comment]
<3

**Comment by ohcibi** [comment]
@twokul well its still unclear if this option takes the path of the source file (e.g. `bower_components/foo/bar.js`) or the path of the file in `dist/` (e.g. `assets/vendor.js`). But for me its not working either way. I tried

```javascript
  app.options.minifyJS.options = {
    exclusions: ["assets/ckeditor/**/*.js"]
  };
```

or 

```javascript
  app.options.minifyJS.options = {
    exclusions: ["bower_components/ckeditor/**/*.js"]
  };
```

or even 

```javascript
  app.options.minifyJS.options = {
    exclusions: ["dist/assets/ckeditor/**/*.js"]
  };
```

I didn't expect the last one to work, but I tried anyway.

The assets are always being minified and also renamed to `oldname-hash.js`. I want none of this to happen as this breaks the code of ckeditor in this case.

I want to add that I copy the ckeditor with `broccoli-static-compiler` like

```javascript
  var ckeditorTree = pickFiles("bower_components/ckeditor", {
    srcDir: "/",
    files: [
      "*.js", "*.css", "adapters/*.js", "lang/*.js",
      "plugins/**/*.js", "plugins/**/*.png", "plugins/**/*.css"
    ],
    destDir: "/assets/ckeditor"
  });
```

 Do I need to pass those `exclusions` options to it as well? Does the minification already happen while copying the files?

**Comment by ohcibi** [comment]
Anyone stumbling across this: 

* The param name is `exclude` and not `exclusion`
* File names from files in `dist/` are matched against the config

**Comment by jcbvm** [comment]
I still face some problems with this, the property exclude seems not always to work, if I for example exclude something like this: "**/pdfjs/**/*.js", the files are still being processed, in this case by build time will increase with 5 minutes (because pdfjs is HUGE).

So not sure if I'm doing something wrong, some more documentation about how to define a path should be nice.

**Comment by ohcibi** [comment]
@jcbvm which version of broccoli-asset-rev are you using? Support for globs (`/**/`) was added here: https://github.com/rickharrison/broccoli-asset-rev/commit/f98baf588a124c26da8a73ccbd7fb283340c2bbf and got merged in `2.4.0`

**Comment by jcbvm** [comment]
@ohcibi sorry my bad, made a typo somewhere else causing this... it's working fine now

**Comment by gzurbach** [comment]
@ohcibi I know this is an old thread but the struggle is real. I have multiple files imported during the build from the `vendor` and `bower_components` directories. Some are already uglified and break when ugilified a second time.

```js
let app = new EmberApp(defaults, {
  'ember-cli-uglify': {
    exclude: ['**/mapbox-gl.js']
  }
});

// This should be uglified
app.import('bower_components/bootstrap/dist/js/bootstrap.js');

// This is already uglified and breaks when uglified again
app.import('vendor/mapbox-gl/mapbox-gl.js');
```

This configuration works:
```js
'ember-cli-uglify': {
  enabled: false
}
```

So does that one:
```js
'ember-cli-uglify': {
  exclude: ['**/vendor.js']
}
```

But then my vendor.js is way to big. How can I exclude a single *source* file from being uglified?

As of two weeks ago `ember-cli-uglify` replaced uglifyJS by Terser (see https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/70). Not sure if this is related. Any help is greatly appreciated!

**Comment by gzurbach** [comment]
Never mind I figured out a workaround. I dropped the `mapbox-gl.js` file in the `public/assets` directory and excluded it with:
```
'ember-cli-uglify': {
  exclude: ['**/mapbox-gl.js']
}
```
Everything works again Yay!

**Comment by ohcibi** [comment]
@gzurbach you had the same misconception as I had. Don't try to exclude files from node_modules or whatever directory outside dist. See my comment here: https://github.com/ember-cli/ember-cli/issues/5034#issuecomment-162183675

**Comment by c-emil** [comment]
I think [this is also good to read](https://github.com/ember-cli/ember-cli/issues/7445#issuecomment-344999337). It seems like `minifyJS` stopped working half a year ago and `ember-cli-uglify` is actually the config property you should use in order to set up minification.
