### ISSUE TITLE
Addon config hook is run multiple times

### ISSUE THREAD

**Issue by acburdine** [ember-cli/ember-cli#5037]
Not 100% sure if this is a bug or actually intended behavior, but it was messing certain things up for me.

Essentially, the addon's `config` hook is being called and run multiple times during the build process.

Easiest way to reproduce:

```bash
ember new test-app
cd test-app
ember g in-repo-addon test-addon
cd lib/test-addon
nano index.js # vi/vim/emacs/whatever
```

Create a config hook that looks something like this:
```javascript
module.exports = {
    name: 'test-addon',
    config: function(env) {
        console.log(env);
    }
};
```

Then run: `ember build --dev`.

This should output 'development' multiple times, and then output 'test'. The build should then complete. I found this behavior odd, considering that the env being run is 'development', thus it should not output 'test'.

I also tested this with a separate repo addon, which yielded the same results.

Again, I'm not sure if this is intended behavior, but in the case that it isn't I thought I'd report it.

**Comment by acburdine** [comment]
Use case in which I stumbled upon this: working on an in-repo addon that moves the built assets to another directory. It is supposed to do this when testing is not happening, and thus I decided to try and use the config hook to specify what environment was being built.

It may seem like a bit of a hack for doing that, but nonetheless, this came up because of it.

**Comment by stefanpenner** [comment]
Not ideal behavior, but not really a bug.
