### ISSUE TITLE
pods and non-pods not coexisting well

### ISSUE THREAD

**Issue by lmcardle** [ember-cli/ember-cli#5043]
I am using pods in my addon, however a 3rd party addon that my addon is using does not use pods. This has not been a problem, but a recent npm cache clear && npm install broke the co-existance of the two.

The error I get is:

```
ENOENT: no such file or directory, stat '/path.../to.../app../directory/.../tmp/broccoli_merge_trees-input_base_path-s8g4iYIF.tmp/1/dummy/templates/components/code-snippet.hbs'
```
It is important to note that this only happens on rebuilds. I do not get this issue when first starting the ember server. It is only when the server is running and I re-save an existing template file.

I have reported this in the 3rd party addons repo, https://github.com/ef4/ember-code-snippet/issues/10, however this does not seem like it is related to that specific addon.

Because everything in the dummy app works fine on the initial build, ember s, and only breaks when ANY file is re-saved, this seems like an ember-cli issue. 

Any thoughts on how I could track this down?

**Comment by stefanpenner** [comment]
@chadhietala got a cycles to take a look?

**Comment by lmcardle** [comment]
This is fixed...the 3rd party addon was using an old version of broccoli-merge-trees. Upgrading to broccoli-merge-trees to ^0.2.1 in the 3rd party addon fixed it.

**Comment by stefanpenner** [comment]
:)
