### ISSUE TITLE
ember-cli-build.js not watched for changes

### ISSUE THREAD

**Issue by technomage** [ember-cli/ember-cli#5044]
Changes to ember-cli-build.js do not cause a live reload or rebuild of the UI.

**Comment by stefanpenner** [comment]
duplicate issue

**Comment by stefanpenner** [comment]
@technomage I am extremely anxious to also enable this. It will happen :)

**Comment by HodofHod** [comment]
@stefanpenner Now that broccoli is at v1.1.2, is there any update on this?
