### ISSUE TITLE
Integrity generation fails for vendor.js because of not ASCII characters

### ISSUE THREAD

**Issue by dakal-oleksandr** [ember-cli/ember-cli#5046]
I found out that integrity generation fails for vendor.js file because of paranoiaCheck in broccoli-sri-hash module (that used by ember-cli-sri). 

Ember-resolver include lines:
```javascript
   if (found) { symbol = '[✓]'; }
```

paranoiaCheck function:
```javascript
/*
  This check is always called (at the moment).
  If 'paranoiaCheck' is enabled then it will check a file only contains ASCII characters
    - will return true if paranoiaCheck is disabled
    - will return true if ASCII only
    - will return false if non ASCII chars are present
  This relates to an issue that is either within OpenSSL or Chrome itself due to an encoding issue:
   https://code.google.com/p/chromium/issues/detail?id=527286
*/
SRIHashAssets.prototype.paranoiaCheck = function paranoiaCheck(assetSource) {
  var i;
  var checkResult = true;

  if (this.options.paranoiaCheck === true) {
    for (i = 0; i < assetSource.length; i++) {
      if (assetSource.charCodeAt(i) > 127) {
        checkResult = false;
        break;
      }
    }
  }

  return checkResult;
};
```

As result function find ✓ symbol and integrity is not added. paranoiaCheck can be disabled by defaulting it to function that always return true.

Maybe it's good to add this to ember-cli as default parameter or add to doc to notify user how to disable this functionality.

**Comment by stefanpenner** [comment]
I believe this is a upstream bug in chrome.  cc @jonathanKingston

**Comment by jonathanKingston** [comment]
@stefanpenner and @dakal-oleksandr removing the default now as it's landed in stable chrome a version ago.
