### ISSUE TITLE
disable content security policy by default?

### ISSUE THREAD

**Issue by frank06** [ember-cli/ember-cli#5048]
This is not a technical issue, but it's worth bringing up.

Every time I do an `ember new` (I do that quite often) I put myself in a newbies' shoes. Fire up the server and you are greeted with a "Welcome to Ember.js". Nice!

However, open up the console and you will see a bunch of red messages (these are warnings but look like errors) related to Content Security Policies.  Many newbs have a shit load of problems trying to understand Ember, let alone build something, and before they even write a single line of code we greet them with a bunch of "errors".

No matter how justified that may be (they are there for a good reason, after all) it seems to me it's a bad tradeoff.

Could we disable the `ember-cli-content-security-policy` by default? At least in development mode?

Perhaps via a flag in `environment.js` and a SINGLE YELLOW WARNING in the console encouraging devs to properly declare their CSP and enable it?

(maybe this warrants opening an issue at rwjblue/ember-cli-content-security-policy )

What do you think?

**Comment by stefanpenner** [comment]
I would prefer to leave it enabled, development mode is the time to catch these issues. 

Ergonomics unfortunately are issues in the browsers themselves. If there exists interest, working with the chrome team to improve the ergonomics would be a big win for many. 

cc señor @paulirish
cc señor @jonathanKingston

**Comment by frank06** [comment]
Fair enough. Regardless of whose "fault" it is, it is yet another teeny tiny hurdle contributing to push new devs away from Ember.

**Comment by stefanpenner** [comment]
> teeny tiny hurdle contributing to push new devs away from Ember.

This teeny tiny hurdle can help prevent very serious security issues once the app is in production.

**Comment by frank06** [comment]
Sure! But developers should also be responsible for the security of their owns apps in production.

Replacing the errors with one yellow warning in the console would be friendly enough to beginners, yet informative to potential production apps.

In my opinion, if you are to put an app in production after seeing that warning N times (how many times do you refresh your app before putting it into production, and further, with something worth stealing?)  then you deserve the security issues.

**Comment by paulirish** [comment]
cc @mikewest for FYI.

I do agree that red errors generally come with the expectation that it should be fixed very soon, and not ignored  for > 2 days. 

But while we're considered ways to "snooze" warnings, we likely would not do that for CSP issues.

**Comment by jonathanKingston** [comment]
I certainly think this can be resolved better than just disabling.

The issue however is that the solutions require a fair bit more work. I have more free time as of today, which is great as I can continue on resolving more of the ideas surrounding this that came from Ember Camp.

I do think however working with browser vendors and or WebAppSec may help on this one.

Here are the tasks I am setting for myself:
- [ ] Work on getting a full story for application and addon development with CSP
  - [ ] JSON CSP work whilst developing apps
  - [ ] Provide better 'best in breed' tools to debug CSP status
  - [ ] Provide a deploy architecture that can push CSP out to the wild
  - [ ] Merge JSON CSP from addon to application
  - [ ] Work with sites like emberobserver to work with JSON CSP with scoring
- [ ] Mail WebAppSec and start a dialogue on CSP warnings (seems like Mike has already been cc'd)

**Comment by jonathanKingston** [comment]
@paulirish do you know if CSP issues will end up on the security panel in Chrome dev tools?

**Comment by paulirish** [comment]
Yes that's the plan. Will likely still be something in the console, just more minimal.

**Comment by stefanpenner** [comment]
removing this addon by default in #5247, unfortunately without improved UX this is causing more harm then good. Once the UX has been improved (both in browsers and on our build side) I will gladly restore
