### ISSUE TITLE
Guidance for how to use proxy-host/port?

### ISSUE THREAD

**Issue by brandonparsons** [ember-cli/ember-cli#505]
I have a Rails backend running on localhost port 3000 that I'm trying to proxy api requests to.  I have tried all of the following:

```
ember server --proxy-port 3000
ember server --proxy-port 3000 --proxy-host localhost
ember server --proxy-host http://localhost:3000

# ./.ember-cli
--proxy-port 3000
```

In all cases, ember data is still requesting from `localhost:4200`.  

My application adapter looks like this:

```
export default DS.ActiveModelAdapter.extend({
  namespace: 'api/v1'
});
```

What am I missing?

**Comment by rohitgoyal7** [comment]
i am still not getting
