### ISSUE TITLE
ENOENT: no such file or directory, open 'tmp\0\ember-cli-app-version\components\app-version.js'

### ISSUE THREAD

**Issue by dnch-dev** [ember-cli/ember-cli#5055]
I am working with ember-cli for a while (I have made a couple applications in order to learn the basics), but today I decided to make an entirely new app.
I made a new application using:
```
ember new <app-name>
```
But when I am in the application directory and try to start the ember server I get this error:
```
cd <app-name>
ember server
```
```
D:\>cd my-app

D:\my-app>ember server
Future versions of Ember CLI will not support v4.1.0. Please update to Node 0.12
 or io.js.
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, open 'D:\my-app\tmp\concat_with_maps-input_ba
se_path-ImGjwGJC.tmp\0\D:\my-app\tmp\concat_with_maps-input_base_path-ImGjwGJC.t
mp\0\ember-cli-app-version\components\app-version.js'
Error: ENOENT: no such file or directory, open 'D:\my-app\tmp\concat_with_maps-i
nput_base_path-ImGjwGJC.tmp\0\D:\my-app\tmp\concat_with_maps-input_base_path-ImG
jwGJC.tmp\0\ember-cli-app-version\components\app-version.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.addFile (D:\my-app\node_modules\ember-cli\node_modules\broccoli
-sourcemap-concat\node_modules\fast-sourcemap-concat\lib\source-map.js:68:19)
    at ConcatWithMaps.<anonymous> (D:\my-app\node_modules\ember-cli\node_modules
\broccoli-sourcemap-concat\concat-with-maps.js:96:17)
    at Array.forEach (native)
    at ConcatWithMaps.addFiles (D:\my-app\node_modules\ember-cli\node_modules\br
occoli-sourcemap-concat\concat-with-maps.js:93:9)
    at ConcatWithMaps.build (D:\my-app\node_modules\ember-cli\node_modules\brocc
oli-sourcemap-concat\concat-with-maps.js:65:8)
    at D:\my-app\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\n
ode_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\my-app\node_modules\ember-cli\node_modul
es\rsvp\dist\rsvp.js:493:16)
```

**P.S.** 
What will happen if I run 
npm install -g ember-cli
npm install -g bower

Will they be reinstalled corectly or there is a chance ember-cli and bower to become broken and unsuable?

**Thanks!**

**Comment by elwayman02** [comment]
I'm getting a similar error myself on ember-cli master...just started today. Trying to find a working SHA.

```
ENOENT: no such file or directory, open 'C:\Users\Jordan\Documents\GitHub\sf\tmp\concat_with_maps-input_base_path-1x5P7Vdh.tmp\0\C:\Users\Jordan\Documents\GitHub\sf\tmp\concat_with_maps-input_base_path-1x5P7Vdh.tmp\0\ember-ajax\errors.js'
Error: ENOENT: no such file or directory, open 'C:\Users\Jordan\Documents\GitHub\sf\tmp\concat_with_maps-input_base_path-1x5P7Vdh.tmp\0\C:\Users\Jordan\Documents\GitHub\sf\tmp\concat_with_maps-input_base_path-1x5P7Vdh.tmp\0\ember-ajax\errors.js'
```

**Comment by elwayman02** [comment]
I cloned this SHA yesterday and it works if I `npm link`:

`c8660a20a4116f603d1160d9bd2f06cf6a634c39`

However, nombom'ing and installing doesn't work, which leads me to believe that an ember-cli dependency updated today and caused this error.

**Comment by rwjblue** [comment]
Possibly related to https://github.com/broccolijs/broccoli-funnel/issues/53 and https://github.com/joliss/node-walk-sync/pull/18.  

Can y'all confirm?

**Comment by dnch-dev** [comment]
What should i do in order to confirm that this error is related to these issues(broccolijs/broccoli-funnel#53 and joliss/node-walk-sync#18.)?

**Comment by fedakim** [comment]
Just updated ember and i am having the same behaviour:

PS C:\Work\Tools\TestingPortal\fuckedup> ember serve
Future versions of Ember CLI will not support v4.2.2. Please update to Node 0.12 or io.js.
version: 1.13.8
Livereload server on http://localhost:49155
Serving on http://localhost:4200/
ENOENT: no such file or directory, open 'C:\Work\Tools\TestingPortal\fuckedup\tmp\concat_with_maps-input_base_path-ppAKi
iks.tmp\0\C:\Work\Tools\TestingPortal\fuckedup\tmp\concat_with_maps-input_base_path-ppAKiiks.tmp\0\ember-cli-app-version
\components\app-version.js'
Error: ENOENT: no such file or directory, open 'C:\Work\Tools\TestingPortal\fuckedup\tmp\concat_with_maps-input_base_pat
h-ppAKiiks.tmp\0\C:\Work\Tools\TestingPortal\fuckedup\tmp\concat_with_maps-input_base_path-ppAKiiks.tmp\0\ember-cli-app-
version\components\app-version.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at SourceMap.addFile (C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\broccoli-sourcemap-co
ncat\node_modules\fast-sourcemap-concat\lib\source-map.js:68:19)
    at ConcatWithMaps.<anonymous> (C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\broccoli-sou
rcemap-concat\concat-with-maps.js:96:17)
    at Array.forEach (native)
    at ConcatWithMaps.addFiles (C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\broccoli-source
map-concat\concat-with-maps.js:93:9)
    at ConcatWithMaps.build (C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\broccoli-sourcemap
-concat\concat-with-maps.js:65:8)
    at C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\b
roccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Work\Tools\TestingPortal\fuckedup\node_modules\ember-cli\node_modules\rsvp\dist\
rsvp.js:493:16)

**Comment by elwayman02** [comment]
I can confirm that I'm seeing this issue on Windows, but I tried locking broccoli-funnel down to 0.2.15 (as a dependency of broccoli-babel-transpiler->ember-cli-babel) and it did not fix anything. There may be multiple releases today that need to be reverted to get this working again.

**Comment by stefanpenner** [comment]
@kellyselden is going to be taking a look at the windows stuff after work, i will likely aswell.

**Comment by dnch-dev** [comment]
```
D:\>ember -v
Future versions of Ember CLI will not support v4.1.0. Please update to Node 0.12
 or io.js.
version: 1.13.8
node: 4.1.0
npm: 2.13.4
os: win32 x64
```

**Comment by elwayman02** [comment]
Locking down broccoli-funnel in npmv3 did not help:

```
$ npm ls broccoli-funnel
sf@0.0.0 C:\Users\Jordan\Documents\GitHub\sf
├── broccoli-funnel@0.2.11
└─┬ ember-cli@1.13.8 (git://github.com/ember-cli/ember-cli.git#c8660a20a4116f603d1160d9bd2f06cf6a634c39)
  ├─┬ broccoli-babel-transpiler@5.5.0
  │ └── broccoli-funnel@0.2.15  invalid
  ├── broccoli-funnel@0.2.11
  └─┬ ember-cli-preprocess-registry@1.1.0
    └── broccoli-funnel@0.2.15  invalid

npm ERR! invalid: broccoli-funnel@0.2.15 C:\Users\Jordan\Documents\GitHub\sf\node_modules\broccoli-babel-transpiler\node_modules\broccoli-funnel
npm ERR! invalid: broccoli-funnel@0.2.15 C:\Users\Jordan\Documents\GitHub\sf\node_modules\ember-cli-preprocess-registry\node_modules\broccoli-funnel
```

**Comment by stefanpenner** [comment]
I'm like 15 min from a Windows machine. Will dig in when I get home

**Comment by kellyselden** [comment]
I'm looking too.

**Comment by stefanpenner** [comment]
found the bug, working on the fix

**Comment by stefanpenner** [comment]
:https://github.com/ef4/broccoli-sourcemap-concat/pull/29

**Comment by Restuta** [comment]
Is there an immediate workaround? Can we lock something to some version since our builds are failing all over.

**Comment by Restuta** [comment]
Mb it makes sense to set up integration build that just does "clean" npm install and observes that exit code is 0 on Windows and Unix?

**Comment by stefanpenner** [comment]
@Restuta our tests do what you speak of.

**Comment by stefanpenner** [comment]
@Restuta give ef4/broccoli-sourcemap-concat#29 a try

**Comment by kellyselden** [comment]
@Restuta This was a dependency update high in the chain, which doesn't kick off our CI.

**Comment by stefanpenner** [comment]
Ultimately with ember-cli 1.13.9 it should be possible to shrinkwrap  via `npm shrinkwrap --dev` which we will be encouraging users to do.

**Comment by stefanpenner** [comment]
my PR is apparently behind miles of CI queue... waiting patiently..

**Comment by Restuta** [comment]
@kellyselden I see, how about hourly CI?

**Comment by stefanpenner** [comment]
sounds like what we currently have, an über style hourly CI of users :P

**Comment by joukevandermaas** [comment]
Adding the line `"walk-sync": "0.2.5"` to the `devDependencies` section of my `package.json` fixed this error for me (with npm@3).

I guess the update of that package broke CLI.

**Comment by stefanpenner** [comment]
> I guess the update of that package broke CLI.

Sorta, there was a series of bugs once due to some undefined behavior being relied on. Basically, user-land comparing paths using some JS algorithm should normalize all members first then compare.

Anyways,  ef4/broccoli-sourcemap-concat#29 should fix the problem. Expect a release this morning.

**Comment by stefanpenner** [comment]
after much manual testing on many setups (windows and non windows) I can no longer find any issues.

BSC 2.0.2 released:

```
➜  broccoli-sourcemap-concat git:(master) npm publish
+ broccoli-sourcemap-concat@2.0.2
➜  broccoli-sourcemap-concat git:(master)
```

**Comment by stefanpenner** [comment]
backported to broccoli-sourcemap-concat v1.1.x
```
➜  broccoli-sourcemap-concat git:(stable-v1.1) git push origin v1.1.6
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:ef4/broccoli-sourcemap-concat.git
 * [new tag]         v1.1.6 -> v1.1.6
➜  broccoli-sourcemap-concat git:(stable-v1.1) npm publish
+ broccoli-sourcemap-concat@1.1.6
```

**Comment by mm2ha** [comment]
@stefanpenner sorry to be ignorant, but what can I do to get this to work in my app?

**Comment by stefanpenner** [comment]
@mm2ha you 

In you app, re-installing node_modules should do the trick

```
rm -rf node_modules
npm cache clear
npm install
```

-----

If you continue to have issues, you can use `npm ls broccoli-sourcemap-concat` to see what versions are installed.

**Comment by mm2ha** [comment]
@stefanpenner thanks, that worked!

**Comment by fruitnuke** [comment]
I'm getting a slightly-different-but-very-similar error on OS X. This is a completely fresh install of Ember 1.13.10 and with version 2.0.2 of broccoli-sourcemap-concat. I'm running into this error following the steps of [the tutorial](http://guides.emberjs.com/v2.1.0/getting-started/first-app/) (I'm new to Ember), and running `ember server`.

```
dan@miyako:my-new-app ember server
version: 1.13.10
Livereload server on http://localhost:49153
Serving on http://localhost:4200/
ENOENT: no such file or directory, stat '/Users/dan/projects/ember/my-new-app/tmp/concat_with_maps-input_base_path-41jXgRrE.tmp/0/bower_components/ember-resolver/dist/modules/ember-resolver.js'
Error: ENOENT: no such file or directory, stat '/Users/dan/projects/ember/my-new-app/tmp/concat_with_maps-input_base_path-41jXgRrE.tmp/0/bower_components/ember-resolver/dist/modules/ember-resolver.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/dan/projects/ember/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

Checking broccoli-sourcemap-concat:

    dan@miyako:my-new-app npm ls broccoli-sourcemap-concat
    my-new-app@0.0.0 /Users/dan/projects/ember/my-new-app
     └─┬ ember-cli@1.13.10
       └── broccoli-sourcemap-concat@2.0.2 

I've re-installed node_modules in my-new-app as suggested by @stefanpenner but it did not fix the error.

Is this a manifestation of the same bug (re-open the issue), or a different bug (I should raise a new issue), or something stupid I'm doing?

**Comment by stefanpenner** [comment]
this problem is resolve,

@fruitnuke the problem you speak of is fixed on GH, running tests (fixing issues) and will release soon.

feel free to follow along here https://github.com/ember-cli/ember-cli/issues/5076
