### ISSUE TITLE
ember test fails with a phantomjs2.0 error Unexpected Token ','

### ISSUE THREAD

**Issue by faeronsayn** [ember-cli/ember-cli#5059]
So I'm running the `ember test` command which uses phantomjs and phantomjs keeps throwing this error: 

```
global failure
    ✘ SyntaxError: Unexpected token ','
```

Which isn't helpful at all :(. I've run the tests in chrome, firefox, safari and all of them pass without any errors. 

So i'm wondering if others have come across this and have found any solutions?

**Comment by stefanpenner** [comment]
> So i'm wondering if others have come across this and have found any solutions?

trailing comma? `[1,2,3,]` or something along those lines maybe?

Unfortunately, although I would love to patching phantom and having it provided better error messages isn't something this project scope should contain.

Im going to close this issue, and suggest asking on StackOverflow, as it is a better venue for Q/A

**Comment by meenie** [comment]
I'm getting this same error with the following code example:
```coffeescript
export default Ember.Component.extend
  content: (->
    [@get('min')..@get('max')] if @get('min') && @get('max')
  ).property('min', 'max')
  hasSelection: Ember.computed.notEmpty('selectedOption')
```

Which generates the following javascript:
```javascript
export default Ember.Component.extend({
  content: (function() {
    var i, ref, ref1, results;
    if (this.get('min') && this.get('max')) {
      return (function() {
        results = [];
        for (var i = ref = this.get('min'), ref1 = this.get('max'); ref <= ref1 ? i <= ref1 : i >= ref1; ref <= ref1 ? i++ : i--){ results.push(i); }
        return results;
      }).apply(this);
    }
  }).property('min', 'max'),  // <-- This is the comma that PhantomJS has an issue with...
  hasSelection: Ember.computed.notEmpty('selectedOption')
});
```
