### ISSUE TITLE
Ember Test causes Chrome to open, but results in No tests were run.

### ISSUE THREAD

**Issue by constantm** [ember-cli/ember-cli#5062]
I'm struggling with the same issue as #4583/#1451 at the moment. It looks slightly different though, since tests actually briefly open Chrome windows, but it still says `No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.` when it's done. When going to /tests in my browser, tests run fine. Using `ember test --server` also shows no tests were run - no errors are reported either.

This happened on the Master branch, `1.13.8-master-ae5e72614e`. I tried updating to the newest Master to see if it would help, but then I ran into a different issue.

**Comment by stefanpenner** [comment]
can you provide an example that demonstrates this issue?

**Comment by patocallaghan** [comment]
@constantm it could be related to the fact that the tests are now in a separate file, `tests.js`. I had a similar issue last week https://github.com/ember-cli/ember-cli/issues/4820. Is that file being included on your test page?

Here's the new `tests/index.html` [diff](https://github.com/twokul/ember-cli-release-notes/commit/bd5ac542c0d6dd8e095553d6528ec40ae4be6b4e#diff-5b08aa4e641aa92853eba2c51358138eR28)

**Comment by constantm** [comment]
Had a quick look, and it seems that my index.html file has everything it should have (as far as I can see, anyway)

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>App Tests</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}
    {{content-for 'test-head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/leaply.css">
    <link rel="stylesheet" href="assets/test-support.css">

    {{content-for 'head-footer'}}
    {{content-for 'test-head-footer'}}
  </head>
  <body>
    {{content-for 'body'}}
    {{content-for 'test-body'}}

    <script src="assets/vendor.js"></script>
    <script src="assets/test-support.js"></script>
    <script src="assets/leaply.js"></script>
    <script src="testem.js" integrity=""></script>
    <script src="assets/tests.js"></script>
    <script src="assets/test-loader.js"></script>

    {{content-for 'body-footer'}}
    {{content-for 'test-body-footer'}}
  </body>
</html>
```

**Comment by patocallaghan** [comment]
What do you see in the Network/Console tab in devtools? Any errors or 404s?

**Comment by constantm** [comment]
Ah yes. When running them in the browser, there is indeed a 404 for `tests.js` - where do I get or generate this file? Strangely enough, the tests run perfectly fine in the browser even with the 404.

**Comment by patocallaghan** [comment]
You may be holding onto some old packages? just make sure you correctly diffed your `bower.json` and `package.json`, then

```
rm -rf dist tmp node_modules bower_components
npm clear cache
bower cache clean
npm install
bower install
ember test --server
```

Hopefully that will resolve it

**Comment by constantm** [comment]
Woo! Works, thanks. Had to also do `ember init` as well and diff the files manually.

**Comment by patocallaghan** [comment]
:tada:
