### ISSUE TITLE
[WIP]: Add Programmatic usage of cli API

### ISSUE THREAD

**Issue by H3Chief** [ember-cli/ember-cli#5064]
- [ ] add a primary entrypoint for programmatic usage of the ember-cli (`/index.js`)
- [ ] modify `/package.json`, adding a `main` property, and pointing to that entrypoint
- [ ] craft a section in the `/README.md` for "Programmatic usage of `ember-cli`
- [ ] Perhaps a brief example or test/dummy?

This is based on agreed outcome of discussion from #4980. I am working on a PR for this.

@stefanpenner can you give me some quick feedback on 

- [x] where/if an example is needed
- [x] confirm that `/index.js` is an acceptable entrypoint for the module's programatic usage (or let me know what substruct you'd like to see it in if not)

**Comment by stefanpenner** [comment]
> confirm that /index.js is an acceptable entrypoint for the module's programatic usage (or let me know what substruct you'd like to see it in if not)

yes i believe so

> where/if an example is needed

readme likely (feels pretty power user)

**Comment by stefanpenner** [comment]
related: https://github.com/ember-cli/ember-cli/pull/5065

**Comment by stefanpenner** [comment]
This seems to have gone stale.

**Comment by kellyselden** [comment]
There is a section in the README now for this.

**Comment by H3Chief** [comment]
> This seems to have gone stale.

@stefanpenner sorry, it completely slipped my radar. I have been digging into addons and ember-simple-auth quite a bit lately.
