### ISSUE TITLE
How do I tell the CLI to use ember 2.0

### ISSUE THREAD

**Issue by eibrahim** [ember-cli/ember-cli#5073]
I am using the latest version of ember cli but when i create a new ember app it uses ember 1.x instead of the latest version of ember 2.x.

How do I set it up to use 2.x or a specific version?

**Comment by trabus** [comment]
`bower i ember#2.1.0 --save` will install and save to your bower. We're aiming to get ember-cli 2.0 out soon.

**Comment by twokul** [comment]
you might need to add `resolutions` to `bower.json` if it doesn't happen automatically, like so

```json
"resolutions": {
  "ember": "^2.1.0"
}
```

**Comment by stefanpenner** [comment]
our next release, aimed at next week will bundle 2.x of ember. UNtil then we should put together a quick example app that demonstrates what needs to happen via a single diff.

**Comment by StevenNunez** [comment]
@stefanpenner Really excited about that! I usually do `bower install ember -F --save`

**Comment by twokul** [comment]
@eibrahim I believe the question was answered, let us know if it's not the case and we will reopen
