### ISSUE TITLE
Problem with ember-cli@1.13.10, using addon

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-cli#5074]
I had an addon which was working with 1.13.8 but really wanted the ability to use Watchman 4.x so upgraded but since then I can't start the server. I'm getting the following error:

> Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at Class.module.exports.treeForAddon (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-lodash/index.js:11:74)
    at Class._treeFor (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/models/addon.js:319:31)
    at Class.treeFor (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/models/addon.js:289:19)
    at /Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/models/addon.js:242:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/models/addon.js:240:22)
    at Class.treeFor (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/models/addon.js:287:20)
    at Class.module.exports.treeFor (/Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli-mirage/index.js:39:32)
    at /Volumes/PEGASUS/repos/mine/ui-list/node_modules/ember-cli/lib/broccoli/ember-app.js:376:20
    at Array.map (native)

On a side note, this may be entirely unrelated but I did notice that when i type `ember -v` I get:

     version 1.13.10
     node: 5.0.0
     npm: 2.14.10
     os: darwin x64

no surprise on the node version but my npm version is **wrong**. When i type `npm -v` I get:

     3.3.6

**Comment by jcope2013** [comment]
related? https://github.com/mike-north/ember-lodash/issues/5, you sure your not on npm 3?

**Comment by patocallaghan** [comment]
@ksnyde I think the `npm` version you see refers to the one used internally in ember-cli, not the globally installed one.

https://github.com/ember-cli/ember-cli/blob/master/package.json#L125

**Comment by ksnyde** [comment]
@patocallaghan yeah i was wondering if something like that might be the case. I'd guess that the npm version is a red herring. The problem is likely unrelated.

**Comment by stefanpenner** [comment]
> I'd guess that the npm version is a red herring

looks like ember-lodash wont possibly work with npm v3 installation, until its patched you will need to use v2 to install stuff

**Comment by ksnyde** [comment]
Since I don't have `ember-lodash` as a dependency in my **package.json** I figured I'd find out who was using this with `npm ls | grep ember-lodash` ... to my surprise it's not being required anywhere in the dependency graph. Does that make sense?

**Comment by stefanpenner** [comment]
@ksnyde can you provide actionable steps to reproduce this problem. I am unclear to proceed.

**Comment by ksnyde** [comment]
well i'm not sure if this is reasonable but if you clone:

     git clone https://github.com/lifegadget/ui-list.git

and then just run the server:

     npm install && bower install 
     ember s

I've just moved back to **node** `4.2.2` and **npm** `2.14.7` and the same error occurs.

**Comment by ksnyde** [comment]
Ok, my bad, I was using a direct reference to `ember-cli-mirage@master` I switched that to a versioned number and the error is gone. I'll close this. Good news is -- I think -- that npm 3 and lodash can work together. :)
