### ISSUE TITLE
ember v1.13.10 installation issues

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5076]
It looks like there are 2 bugs: (fixed on GH, running tests and fixing anything else the shows up now)

* resolver code was not backported -> https://github.com/ember-cli/ember-cli/commit/50487c2d1f80a1235581eacc665b55ce72d0f12c
* npm packaging of bundled dependencies seems to no longer work correctly https://github.com/ember-cli/ember-cli/issues/5076

Both issues have fixes in mainline, we are pending local test runs to confirm the system is working as expected.

stuff

* Do to how our integration tests work, the resolver code being missing was masked from us. Although a simple solution exists, and will be added to our release plan
* npm packaging issue is just funky, removing bundling entirely hopefully deals with this

**Comment by ksnyde** [comment]
Just ran into the resolver issue. What's the best course of action for those now 1.13.10?

**Comment by stefanpenner** [comment]
> What's the best course of action for those now 1.13.10?

downgrade or use stable-1-13 branch https://github.com/ember-cli/ember-cli/tree/stable-1-13

**Comment by mike-post** [comment]
Doing an `ember install ember-resolver` will fix the resolver issue. (I also had to update my resolver import in app.js from `import Resolver from 'ember/resolver';` to `import Resolver from 'ember-resolver';` to fix a deprecation warning, but that might just be something I missed during the upgrade process.)

**Comment by stefanpenner** [comment]
> Doing an ember install ember-resolver will fix the resolver issue.

This isn't recommended, as v1.x should not have gotten that version.

**Comment by btecu** [comment]
Are you planning on releasing `1.13.11` soon (this week)?

**Comment by stefanpenner** [comment]
@btecu soon soon, tonight soon

**Comment by acorncom** [comment]
Looks like `1.13.11` was released last night, should this issue be closed?

**Comment by stefanpenner** [comment]
@acorncom thanks :)

**Comment by alexlafroscia** [comment]
@stefanpenner I'm stills seeing issues with the Resolver not being found after upgrading to `1.13.11`.

**Comment by stefanpenner** [comment]
cc @twokul ^

**Comment by twokul** [comment]
@alexlafroscia @stefanpenner I will fix it in `1.13.12`
