### ISSUE TITLE
Ember-cli 1.13.10 package issue

### ISSUE THREAD

**Issue by jtsom** [ember-cli/ember-cli#5078]
After updating to 1.13.10, and updating a project I noticed that 'ember init' installed 'ember-cli-is-ajax' instead of 'ember-ajax', as was expected per: #4656 Replace ember-cli-ic-ajax in favour of ember-ajax @taras

Trying with a new project also installed ember-cli-is-ajax.

**Comment by jcope2013** [comment]
that is a mistake, the ember-ajax switch will be part of ember-cli 2 which should be released in the next week https://github.com/ember-cli/ember-cli/pull/5045

**Comment by Turbo87** [comment]
I guess this got confusing because #4656 was mentioned in the release notes of v1.13.9 and the following releases (see https://github.com/ember-cli/ember-cli/releases/tag/v1.13.9)
