### ISSUE TITLE
Allow use of latest watchman

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5086]
After installing ember-cli and watchman, everything works fine and I'm able to start the development server as usual.

But at the same time, I also get a warning message:

> Invalid watchman found, version: [4.1.0] did not satisfy [^3.0.0], falling back to NodeWatcher.

Could someone please fix this, so that developers are able to use the latest watchman? :blush:

**Comment by mfenniak** [comment]
It's already fixed in #5026, which was released in ember-cli 1.13.10.

**Comment by leo** [comment]
Confirmed. Works fine on the latest version of ember-cli! Thanks! :blush:
