### ISSUE TITLE
configuring babel to ignore a file breaks test suite

### ISSUE THREAD

**Issue by bargar** [ember-cli/ember-cli#5088]
version 1.13.11
node v0.12.2
npm 2.7.4
os: OS X 10.10.5 (yosemite)

Thanks for the performance work, btw - very much appreciated!

---

In our production app, we have several large javascript files with mock data that serve as pretender responses for acceptance tests. For build/tooling performance reasons, we have always configured these files to be ignored by both babel and jshint. They are fairly straightforward javascript files that look something like:

```
/* jshint ignore:start */
export default {
  mockInstance: {
    foo: 'bar'
  }
}
/* jshint ignore:end */
```

This technique worked as recently as ember-cli 1.13.8 but breaks with 1.13.11:

![tests-fail-when-mock-ignored](https://cloud.githubusercontent.com/assets/1666818/11124339/8805b56a-8932-11e5-922a-1adaff399777.png)

**tests/mock.js** does not appear to go through the pipeline when babel ignores it. It appears at **assets/no-babel-no-tests/tests/mock.js** unaltered (including `export default...`) instead of the expected form that factors in the longstanding ember-cli es6 style import system:

```
define('no-babel-no-tests/tests/mock', ['exports'], function (exports) {
  /* jshint ignore:start */
  exports['default'] = {
    mockInstance: {
      foo: 'bar'
    }
  };
  /* jshint ignore:end */
});
```

Is there a chance this is a regression bug that can be fixed? Alternatively, we'd be open to a different approach for making the mock data available to the pretender responses in our tests. Unfortunately, the other performance gains in this upgrade are rendered moot if we have to process these files, some of which are quite large (> 100KB) with babel.

Pared down to minimal reproducible case at [bargar/no-babel-no-tests](https://github.com/bargar/no-babel-no-tests).

I started with a vanilla ember-cli project and [added a single js file to the test directory and configured it to be ignored by babel and jshint](https://github.com/bargar/no-babel-no-tests/commit/07d42c051d9efc2727e6ab5d082b210c7ad74162).

Here are the tests running fine on the vanilla project and mock js file when babel is _not_ ignoring the mock file:

![tests-run-fine-with-mock](https://cloud.githubusercontent.com/assets/1666818/11124374/a7af9246-8932-11e5-827d-f4cd69c22d25.png)

**Comment by stefanpenner** [comment]
Esperanto is no longer used to do module transpilation as it is deprecated, babel now handles all of that.

**Comment by bargar** [comment]
Fair enough - getting off of esperanto certainly makes a great deal of sense.

Seems like we'll have to find a workaround for providing mock data to our acceptance tests that bypasses the build chain. Though they are simple JavaScript objects, the size of the mock data files is prohibitive and drags builds down dramatically.

**Comment by stefanpenner** [comment]
> Though they are simple JavaScript objects, the size of the mock data files is prohibitive and drags builds down dramatically.

put them in public/ and script tag include them

@bargar how big are they?

**Comment by bargar** [comment]
Yeah - that oughta work. We'll need to find a way to exclude from production builds, though. Worst case we remove with a script after the fact, I suppose.

We have several data files ranging from 0.5KB to 1.4MB (!), with the median being around 100KB.

**Comment by stefanpenner** [comment]
> We have several data files ranging from 0.5KB to 1.4MB (!), with the median being around 100KB.

should be alright, will likely only cause grief on cold builds now. Although maybe some issues with sourcemap concatting the test files.

**Comment by bargar** [comment]
Gotcha. Thanks for the followup, @stefanpenner. We're still missin' ya here in NYC.
