### ISSUE TITLE
windows - ember init detecting false positives for diffing

### ISSUE THREAD

**Issue by csantero** [ember-cli/ember-cli#5090]
When running `ember init` in an existing addon, the diff tool thinks every line of every file in the blueprint has changed. Here is example output:

```
PS C:\users\chris\Documents\GitHub\my-addon> ember init
version: 1.13.11
installing addon
[?] Overwrite .bowerrc? Diff
Index: C:\users\chris\Documents\GitHub\my-addon\.bowerrc
===================================================================
--- C:\users\chris\Documents\GitHub\my-addon\.bowerrc
+++ C:\users\chris\Documents\GitHub\my-addon\.bowerrc
@@ -1,4 +1,4 @@
-{
-  "directory": "bower_components",
-  "analytics": false
-}
+{
+  "directory": "bower_components",
+  "analytics": false
+}

[?] Overwrite .bowerrc? (Yndh)
```

**Comment by csantero** [comment]
Just realized this is due to line endings. I've been developing in a linux virtual machine and I wanted to evaluate windows performance in 1.13.11. So this isn't really Ember CLI's problem.

**Comment by XaserAcheron** [comment]
It's still a problem for actual Windows users. D:

Could we get a re-open for discussion? This issue makes it virtually impossible to use `ember init` for upgrading existing projects on Windows.
