### ISSUE TITLE
const classes

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli#5091]
In https://github.com/ember-cli/ember-cli/commit/cc65668f9065d300e0daee49a3a201bfcca9c663#diff-f4d09ffc13efe496dd246031d423e166 @xcambar changed class declarations from `var` to `const`, to align with [ember-suave](https://github.com/dockyard/ember-suave).

I'm not sure if this is an issue to be discussed here or there, but I'd like to proposed that `const` *only* be used for what are considered constants in the common meaning. This means `THINGS_UPPER_CASE`, and not simply any variable that you don't expect to change.

In the practical sense, `const` is not providing as much "protection" as many early adopters are thinking it does (since the object itself is not frozen). Additionally though we feel clever for thinking "do I want a const or let here?" before each variable declaration, in reality using `const` for a common variable is simply a refactoring hazard. A later reader of the code should hesitate changing a `const`, however in the style used here (declaring a variable for a class) changing the value would be reasonable and low-impact.

I recognize this is a tricky issue and have zero desire to get into a raging debate, however the style prescribed by ember-cli blueprints does strongly influence how developers use the new syntaxes. I think in this case, we may have diverged away from the standard style we use in Ember core and the style that most on the core team use in their own apps.

**Comment by stefanpenner** [comment]
`const` for class in these scenarios smells alright to me.

I totally agree `const` for random variables that happen to not change is problematic (IMHO it de-values `const`)

**Comment by ef4** [comment]
I third the argument against promiscuous `const`. As a rule of thumb, if it would be reasonable for someone doing a later refactor to turn your `const` into a `let`, it should have just been a `let` from the beginning.

**Comment by stefanpenner** [comment]
@ef4 agreed, well articulated

**Comment by mixonic** [comment]
In the same commit there is also some non-class usage.

**Comment by rwjblue** [comment]
@mixonic - Either `let` or `const` would have met ember-suave's rules just fine.  We recently applied a rule to the Ember codebase (and I am in the process of adding that rule to ember-suave) to enforce `const` usage only in the module context (i.e. not inside functions/classes/ifs/etc).  The commit you link to seems to be in line with that.

**Comment by mixonic** [comment]
OK. Still not crazy about `const` classes, but until it can be debated in person I think I may have lost that.

The `const` for `resolver` is somewhat dubious but would also meet your module level definition. Ugh. https://github.com/ember-cli/ember-cli/commit/cc65668f9065d300e0daee49a3a201bfcca9c663#diff-d4cde49921e37c6199d46a7bff66f061R4
