### ISSUE TITLE
[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: bootstrap]

### ISSUE THREAD

**Issue by workmanw** [ember-cli/ember-cli#5092]
I apologize if this isn't an actual bug, but after upgrading to Ember-CLI 1.13.12 I started recieving this error:

`[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: bootstrap]`

"bootstrap" is what we call our local addon. I've grepped our entire code base and we're not calling `new this.Funnel` at all. I'm guessing maybe it's one of our addons and it's a misnomer? But I don't know how to track down the culprit.

Here is my package.json:
```
{
  "name": "buttercup",
  "version": "0.0.0",
  "description": "Small description for buttercup goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server -lr false",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "Batterii LLC",
  "license": "None",
  "devDependencies": {
    "ember-cli": "1.13.12",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-autoprefixer": "0.5.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "^5.1.0",
    "ember-cli-sri": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-computed-sortby": "0.0.3",
    "ember-data": "1.13.15",
    "ember-data-model-fragments": "0.4.1",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-i18n": "4.1.4"
  },
  "ember-addon": {
    "paths": [
      "lib/bootstrap"
    ]
  }
}
```

**Comment by stefanpenner** [comment]
The deprecation says its from the bootstrap addon, which is not part of the default ember-cli install. Please open an issue on the addon in question.

**Comment by workmanw** [comment]
@stefanpenner it's actually a local addon ... and I doesn't use Funnel at all, I promise. I'm not sure if it's a bug, but I don't know how to even begin to track it down.

**Comment by stefanpenner** [comment]
If you can provide a reproduction, I'll gladly take a look

**Comment by workmanw** [comment]
@stefanpenner Sure thing. Here you go: https://github.com/workmanw/ember-local-addon That's a barebones minimal reproduction. I think maybe it's some internals with in-repo addons. 

I tried to use `node-inspector` to see if I could trace it down, but I couldn't see to get it to launch in time to set breakpoints. I'm not familiar enough with `node-inspector` to be effective with it.

**Comment by stefanpenner** [comment]
@workmanw you sir are correct!

**Comment by workmanw** [comment]
@stefanpenner Thanks for fixing that up! :)
