### ISSUE TITLE
Cannot run npm shrinkwrap on ember-cli : 0.1.15

### ISSUE THREAD

**Issue by goyalvarun601** [ember-cli/ember-cli#5097]
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/express requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/morgan requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/broccoli/node_modules/connect requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/finalhandler requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/express/node_modules/finalhandler requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/express/node_modules/send requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug,
npm WARN unmet dependency which is version 2.2.0
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: debug@2.2.0 /Users/Varun_Goyal/connect-paam/node_modules/ember-cli/node_modules/debug

**Comment by stefanpenner** [comment]
0.1.15 is quite old and no longer supported.

ember-cli 1.13.12 does shrinkwrap correct (tested it again this morning)

**Comment by goyalvarun601** [comment]
Our app just crashes with the ember-cli update. For now, I am think of doing a shrinkwrap with  the new version and update npm-shrinkwrap.json back to work with the older version. 
Will this work?

And later try to upgrade to the  newer version.

**Comment by stefanpenner** [comment]
It's unlikely that will work. Likely time to upgrade, seems like it's been some time since you updated so it will likely be some effort.
