### ISSUE TITLE
Use npm instead of bower

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5099]
Bower's feature development has officially [been stopped][1] I therefore think ember-cli should join many other developers and switch to npm, too.

What do you people think about this? Should we wait until the bower ship is completely sunken?

[1]: https://twitter.com/nachocoloma/status/663622545162280960

**Comment by jcope2013** [comment]
bower is being phased out with ember-cli 2.0 which is coming in the next few weeks with core ember packages being transitioned into npm packages (data and ember-resolver have been done so far) https://github.com/emberjs/data/pull/3907

**Comment by leo** [comment]
@jcope2013 Wow, you're fast! That's great news :blush:

**Comment by stefanpenner** [comment]
We have been working on this for some time, it will be an incremental transition. We plan for all code dependencies to be offloaded to npm for 2.0

**Comment by leo** [comment]
@stefanpenner :ok_hand:
