### ISSUE TITLE
[ember-cli 1.13.9+ (win64)] ember-cli serve hangs on loading live reload script

### ISSUE THREAD

**Issue by Kilowhisky** [ember-cli/ember-cli#5101]
After the upgrade to ember cli 1.13.9 (and the subsequent later versions) the built in ember server fails to work properly if i have the live reload script injected.  It just sits there trying to load the live reload script. `livereload.js?snipver=1`

Here is an upload of the request as a HAR. [request.har](https://github.com/ember-cli/ember-cli/files/34430/request.txt)

If i remove the npm package that injects it then ember serve works and lets me load my app. 
`"ember-cli-inject-live-reload": "^1.3.1",`

Here is the command i'm using to start ember up
`ember serve --proxy http://127.0.0.1`

Here is the dump of my ember version and its packages
```
C:\Projects\GIT\myapp>ember --version
version: 1.13.12
node: 5.0.0
npm: 2.14.10
os: win32 x64
```

Here are my package dependencies. 

```
    "broccoli-csso": "^1.1.0",
    "ember-cli-active-link-wrapper": "0.0.4",
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.12",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-blanket": "0.6.2",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-document-title": "^0.2.0",
    "ember-cli-google-analytics": "1.5.0",
    "ember-cli-happy-splitter": "git://github.com/Kilowhisky/ember-cli-happy-splitter#collapsible2",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-less": "^1.5.1",
    "ember-cli-moment-shim": "0.6.2",
    "ember-cli-notifications": "2.1.2",
    "ember-cli-pace": "0.0.15",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-windows-addon": "^1.2.2",
    "ember-data": "2.1.0",
    "ember-i18n": "^4.1.2",
    "ember-localstorage-adapter": "0.5.5",
    "ember-radio-button": "^1.0.6",
    "ember-resize": "0.0.10",
    "ember-select-2": "1.3.0",
    "ember-simple-auth": "~1.0.1",
    "ember-truth-helpers": "1.2.0",
    "ember-validations": "^2.0.0-alpha.4",
    "ivy-tabs": "git://github.com/IvyApp/ivy-tabs",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4"
```

**Comment by huberts** [comment]
I've noticed similar issue with ember-cli 1.13.12 - http://localhost:49152/livereload.js?snipver=1 is pending indefinitely. I use proxy for ember-data as well.

**Comment by stefanpenner** [comment]
I cannot replicate on my windows machine.

Does a fresh app via `ember new` have this issue on your setup?

**Comment by Kilowhisky** [comment]
Yup. Here is my app. [test-app.zip](https://github.com/ember-cli/ember-cli/files/35831/test-app.txt)

I have windows 7x64 SP1 with the latest updates installed. I disabled my virus checker and my firewall during my test. 

Here is a list of all my installed updates.  [hotfix.txt](https://github.com/ember-cli/ember-cli/files/35830/hotfix.txt)

![capture](https://cloud.githubusercontent.com/assets/7075666/11191230/188a845c-8c4f-11e5-9a7c-cd04cc8be521.PNG)

Its odd. Ember-cli doesn't appear to squak about anything, chrome is not saying anything,  when i use fiddler the request doesn't even come up in fiddler, and the request never times out.

**Comment by adam-knights** [comment]
I can confirm I also see this issue having just upgraded to 1.13.12, no issue with 1.13.8.

![image](https://cloud.githubusercontent.com/assets/12710362/11208574/e18d24a8-8d13-11e5-9ab0-c367b131e561.png)

**Comment by adam-knights** [comment]
Inspecting the html shows the js file appearing like so:

<script src="/ember-cli-live-reload.js" type="text/javascript"></script>
<script type="text/javascript" src="http://localhost:49152/livereload.js?snipver=1"></script>

**Comment by stefanpenner** [comment]
tracking here: https://github.com/ember-cli/ember-cli/issues/5101

**Comment by stefanpenner** [comment]
seems to be the new findPort module

**Comment by neilyoung** [comment]
Confirmed. Fresh VM Windows 7 Pro SP1, all tools installed fine. ember new, ember server -> hang in Chrome

**Comment by msounthar** [comment]
I am facing the same issue too.

**Comment by andreventuravale** [comment]
Me too, facing the same issue.

**Comment by adanylov** [comment]
To fix the issue, use this command
`ember serve -lrp 49200`
