### ISSUE TITLE
npm 3 flattening breaks a lot of dependencies and peer dependencies

### ISSUE THREAD

**Issue by SSS2557** [ember-cli/ember-cli#5102]
Just thought this would be a better place to track all of them here.

I will be referencing each of the issues I create on the repositories soon. In case anybody else is facing these, please feel free to add on to this

**Comment by stefanpenner** [comment]
:+1:  ya we should build up a list here, we can use it to track progress.

**Comment by SSS2557** [comment]
:8ball: ...phew..will have a list sometime today :)
