### ISSUE TITLE
ember-cli introduced a conflict with ember-cli-babel's options

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#5103]
This is related to https://github.com/babel/ember-cli-babel/pull/63.

Both ember-cli and ember-cli-babel are trying to use the same `babel` argument in the options passed to EmberApp. But their semantics for this option differ.

Earlier versions of ember-cli didn't use it, and it was entirely owned by ember-cli-babel. ember-cli-babel introduces extra flags like `includePolyfill`, which it knows to filter out before passing on to babel.  But now ember-cli is stomping on the same namespace, with different semantics. It doesn't know to remove `includePolyfill`, which causes babel to blow up.

ember-cli should either delegate to ember-cli-babel, or try to keep its semantics in sync.

**Comment by stefanpenner** [comment]
Cc @chadhietala 

Long story our configuration story blows. That will be on my radar post 2. And post packager/linker
