### ISSUE TITLE
Redirect from "/app" to "/app/"

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5112]
I'd like to request a feature (if the following sounds like a great idea to you, too):

By using `ember serve`, my app is being served from `/name/`. So if I try to access it by typing `/name` into my browser's address bar, all I get is:

> Cannot GET /name

I understand that this is the result of `/name/` being routed to my "dist" directory and `/name` just being routed to nowhere, but can't we just add a property (maybe within "environment.js") which redirects developers to the right URL when set to `true`?

I often accidentally land on `/name` after removing some parts of the URL manually within the address bar (to test out how the app responds to it) and would be really happy if there was a simple redirection. I also think that there are many other developers who're experiencing this (which is why I'd like to introduce it as a feature).

**Comment by stefanpenner** [comment]
putting a redirect at server/index.js should do the trick. [example](https://github.com/emberjs/ember.js/blob/master/server/index.js)

**Comment by leo** [comment]
@stefanpenner Hmmm... Still doesn't work. Also, my console still shows:

> /name 404 3.246 ms

... if I try to access `/name` in the browser. Any idea why it doesn't work like it should?

**Comment by leo** [comment]
Oh, sorry! That was my fault. Works fine now! Thank you :blush:

**Comment by stefanpenner** [comment]
@leo :) If you have ideas to improve docs/discoverability of this feature let me know (or open a PR)

**Comment by leo** [comment]
@stefanpenner Will do! :blush:

**Comment by stefanpenner** [comment]
:)

**Comment by leo** [comment]
@stefanpenner I can't find the repo that contains the docs of the user-guide. Where are they located? I'd like to add something about this... :sheep:

**Comment by rwjblue** [comment]
gh-pages branch of this repo
