### ISSUE TITLE
Filtering tests with array of terms?

### ISSUE THREAD

**Issue by ryrych** [ember-cli/ember-cli#5121]
Is it possible to filter tests with `ember test --filter` passing and array of terms or exclude some tests using a regular expression?

For what I see from `/node_modules/ember-cli/lib/commands/test.js` the `--filter` option doesn't support that.

**Comment by stefanpenner** [comment]
questions are best asked on Stackoverflow, this issue tracker is to remain focused on issues. If you have feature requests please open an issue on the rfc tracker github.com/ember-cli/rfcs/issues/new
