### ISSUE TITLE
v1.13.12 - Windows - The browser loading indicator keeps spinning

### ISSUE THREAD

**Issue by HerveSeger** [ember-cli/ember-cli#5123]
I just upgraded from 1.13.8 to 1.13.12 on Windows 7 Enterprise (x64) and everything went well.
node/npm: 0.12.7/2.11.3.

When I run my app after the upgrade everything is ok except one little thing: the tab spinner keeps, well, spinning, forever. The application is ok, there is no error in the console. response times are normal, just this very annoying spinner that never stops.

Chrome/Firefox behave the same way.

In order to make sure that the problem did not come from one of my app package, I have created a brand new app and I face the same issue.

I have rolled back to 1.13.8 for now.

**Comment by stefanpenner** [comment]
I'm going to assume live reload also doesn't work?

My guess is something is sideways with livery load WS connection. Maybe a restricted port? My Windows unfortunately does not replicate this.

Does a fresh app have the same issue?

**Comment by HerveSeger** [comment]
Yes a fresh app created with `ember new app` had the same problem but thank you for the note on live reload because it looks that it is indeed a port issue, see below.

I noticed that the port number used by live reload was different between 1.13.8 (49155) and 1.13.12 (49152) so I restarted the test app with `ember serve -lrp 49155)` and it worked.

By using the cmd `netstat -a` I can see that indeed 49152 is already used by another process.

I am going to resume the upgrade of my production app to 1.13.12 but I close this issue.

Thanks a lot for the help.

**Comment by stefanpenner** [comment]
our system should be choosing open ports

**Comment by stefanpenner** [comment]
short term:
* figure out whats up with our port detection code.

long term solution:

* live-reload should just be multi-plexed over the existing HTTP port

**Comment by stefanpenner** [comment]
for reference, we use:

[portfinder](https://www.npmjs.com/package/portfinder) over [here](https://github.com/ember-cli/ember-cli/blob/3c615aa55dfe6be1adf14ef67e74028b09560138/lib/commands/serve.js#L39-L41)

**Comment by Kilowhisky** [comment]
This is the same that is happening here. https://github.com/ember-cli/ember-cli/issues/5101

**Comment by gmurphey** [comment]
It seems like this may have something to do with the changing of the default for `host` from this commit: https://github.com/ember-cli/ember-cli/commit/f5da211f028ca97c9599834e910e3f740f47a7f9

There is an issue (feature) with Portfinder when `host` is not set explicitly: https://github.com/indexzero/node-portfinder/issues/13

**Comment by gmurphey** [comment]
It worked out of the box on my Windows machine, but I was able to get it to break. Steps to reproduce this bug:

1. Find a range of ports being used by `0.0.0.0` using `netstat` (49408-49411 on my machine)
2. Change `PortFinder.basePort` to the start of that range in the serve command (49408 for me)
3. Run `ember serve` and see the livereload request pending (livereload started on 49410, a port already in use on my machine)
4. Run `ember serve --host 0.0.0.0` and livereload should work

**Comment by brett84c** [comment]
ember serve --host 0.0.0.0 has fixed the problem for me for now.  Before it was constantly showing loading gif and "waiting for localhost..." at the bottom of the screen.

**Comment by jackmatt2** [comment]
I was getting this behaviour after upgrading to `1.13.13` on Windows 7 64bit also.  The `ember serve --host 0.0.0.0` fixed it for me for now.

**Comment by jackmatt2** [comment]
Actually, the above stopped the spinner but live reload does not work. I was experiencing this back in 1.13.8 also but just put up with it and manually had to reload the page.

Using something like `ember serve -lrp 9000` has solved the issue and it is reloading automatically again.

**Comment by adam-knights** [comment]
Is there an eta for a 1.13 fix for this? Trying to decide whether to get our team using 1.13.13 for the speed improvements and get them running the workaround, or whether to wait for a fix if its imminent..

**Comment by jackmatt2** [comment]
@adam-knights I would suggest upgrading for windows users.  Previously my laptop was running extremely hot when running ember-cli on windows.  Now after the upgrade, my laptop is running cool again.  It is as simple as adding a serve.bat file with the command above in it.

**Comment by gmurphey** [comment]
Thinking this will be fixed by #5354.
