### ISSUE TITLE
Typo-caused page collapse

### ISSUE THREAD

**Issue by glenlivet** [ember-cli/ember-cli#5131]
Hey guys,

I have just been through a horrible page collapse, and the cause is just a typo.

please try bellow in the page-related controller js file:

Instead of `Ember.computed`, use `Emeber.computed`.

Then, the related page simply collapses without a single error message both in chrome console or in terminal. 

As you can see, it's just a very common typo, but Ember-cli cannot identify this error. No error hint in anywhere. It is not development-friendly.

Code provided blow:
from app/controllers/investors/new.js
```js
...code omitted
modelDetailInvestStages: Emeber.computed('model.details.investStages.[]', function(){
     return this.get('model.details.investStages').join(', ');
}),
...code omitted
```

**Comment by SaladFork** [comment]
When running the app, you should get a browser console error similar to:
```
Error while processing route: investors.new Emeber is not defined
ReferenceError: Emeber is not defined
```
The stack trace should also include the exact file and line number with the typo.

**Comment by stefanpenner** [comment]
I believe there is feedback, the following should happen unless the default setup has been changed.

* jshint warning during recompile 
* console error in the browser

**Comment by stefanpenner** [comment]
this seems to have gone stale
