### ISSUE TITLE
Move "gh-pages" branch to its own repo

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5143]
If you ask me, the documentation site deserves its own repository to allow easier collaboration and to make it more visible to developers who would like to contribute something.

@rwjblue asked me to research this so that the process of moving the branch to a new repository won't create any problems. So based on [this](https://help.github.com/articles/user-organization-and-project-pages/), here's what needs to be done:

- [x] Create a new repo within the "ember-cli" org and call it "ember-cli.github.io"
- [x] Push the "gh-pages" branch to the new "ember-cli.github.io" repo and rename it to "master"
- [x] Delete the "gh-pages" branch from the old "ember-cli" repo (**Important**, otherwise GitHub won't be able to redirect visits to the domain to the new repo)
- [x] Update all [occurrences](https://github.com/ember-cli/ember-cli/search?utf8=✓&q=gh-pages) of the word "gh-pages" to the name of the new repo

After this, I will make sure to update the code to work with the latest version of Jekyll (currently a really old version is being used, I think).

**Comment by rwjblue** [comment]
I'm :+1: on splitting this out, does anyone object?

**Comment by stefanpenner** [comment]
🚀

**Comment by leo** [comment]
:ok_hand: Great! Then let's get started.

And while we're on it: What does one need to accomplish to become the maintainer of that new repository (if that's even possible)? What would I have to proof?

I'm asking because I would be happy to be responsible for preventing the site from looking outdated in terms of design and it's code (like I'll do it for the latest Jekyll).

**Comment by kellyselden** [comment]
https://github.com/ember-cli/ember-cli.github.io has been created and should be ready for the `gh-pages` branch

**Comment by stefanpenner** [comment]
> What does one need to accomplish to become the maintainer of that new repository (if that's even possible)? What would I have to proof?
> 
> I'm asking because I would be happy to be responsible for preventing the site from looking outdated in terms of it's design and code (like I'll do it for the latest Jekyll).

@leo we would love additional support here. Ping me in #dev-ember-cli on the [ember community slack](https://ember-community-slackin.herokuapp.com/) and we can figure it out.

**Comment by leo** [comment]
@stefanpenner :ok_hand:

**Comment by stefanpenner** [comment]
@leo thank you for all your hard work!!
