### ISSUE TITLE
ember generate route '/'

### ISSUE THREAD

**Issue by Silviu-Marian** [ember-cli/ember-cli#5151]
I don't get it...

![Image of Yaktocat](http://imgur.com/T4VrZb2.png)

![Image of Yaktocat](http://imgur.com/qcU924B.png)

how do you create a route "/" with ember-cli?

**Comment by Silviu-Marian** [comment]
Also, it's amazing what it did to `router.js`

```
  this.route('\'', function() {
    this.route('\'');
  });
```

**Comment by stefanpenner** [comment]
looks like something fun with windows CL :P

**Comment by btecu** [comment]
@Silviu-Marian You probably want route `index` not `/`.

**Comment by leo** [comment]
@Silviu-Marian Did you try `ember g route \`? If that's not working, simply try @btecu's suggestion.

**Comment by btecu** [comment]
No, that doesn't make sense.
Right now `ember-cli` uses the route name for the actual file name.

This seems like an edge case that should be addressed, mainly for people new to Ember.

The route `index` is basically `/`.
Note that you can have index sub routes as well.

**Comment by stefanpenner** [comment]
> @Silviu-Marian You probably want route index not /.

this seems correct, good catch. Wlil reopen if it turns out we are missing something else.
