### ISSUE TITLE
broccoli-plugins that need some TLC

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5153]
While perusing around (debugging peoples perf issues) I have noticed several plugins that need TLC:

-  [ ] https://github.com/moudy/broccoli-template-builder -> https://github.com/moudy/broccoli-template-builder/issues/1
- [x] liquid fire https://github.com/ef4/liquid-fire/issues/394

.. will add more as I run into them

**Comment by kellyselden** [comment]
@stefanpenner doing god's work!

**Comment by kamalaknn** [comment]
@stefanpenner update: ef4/liquid-fire#404 is merged

**Comment by Turbo87** [comment]
closing in favor of moudy/broccoli-template-builder#1
