### ISSUE TITLE
How to access options of current ember-cli command?

### ISSUE THREAD

**Issue by john-kurkowski** [ember-cli/ember-cli#5157]
I have to write some absolute URLs and would like to know what port/test-port my app is running on. How do I get these current ports? Or more generally, how do I get the validated options that ember-cli ultimately used for the currently running e.g. `ember serve`, `ember test`?

In the case of ports, the default ports are in private variables. The input could come from an env var, argv, .ember-cli, or [be dynamic](https://github.com/ember-cli/ember-cli/pull/4816). My app figuring out which port ember-cli went with would be tricky.

**Comment by stefanpenner** [comment]
Can you provide an example of what you are trying to do. This is sort of non-actionable as is.

**Comment by john-kurkowski** [comment]
Sure. Here's more concrete pseudocode.

## In My App

I'd like to be able to pass the current port/test-port through to my app, so it can consume it like

```javascript
import config from 'my-app/config/environment';

export default Ember.Component.extend({
  someAbsoluteUrl: Ember.computed('somePath', function() {
    return `http://localhost:${config.APP.MY_CURRENT_PORT}${this.get('somePath')}`;
  });
});
```

If I were you, I wouldn't put `MY_CURRENT_PORT` on all Ember apps' config by default. So I'd like to thread it through myself, starting from ember-cli-build.js.

## What The Ember CLI Build Gives Me

```javascript
module.exports = function(config) {
  config.APP.MY_CURRENT_PORT = 4200; // but different developers or test processes use different ports
  ...
});
```

## What I'd Like To Be Able To Do In My Ember CLI Build

```javascript
module.exports = function(config, emberCliOptions) {
  config.APP.MY_CURRENT_PORT = emberCliOptions['test-port'] || emberCliOptions['port'];
  ...
});
```

**Comment by stefanpenner** [comment]
> return `http://localhost:${config.APP.MY_CURRENT_PORT}${this.get('somePath')}`;

isn't this easier (and more stable) to use `location.host` ?

**Comment by john-kurkowski** [comment]
Sorry, bad example. I misremembered my use case. I don't need to build the absolute URL in my app. I need to build it for a static file. So, via ember-cli-build.js. Something like 

```javascript
var replace = require('broccoli-string-replace');

module.exports = function(config, emberCliOptions) {
  var host = 'localhost';
  var port = emberCliOptions['test-port'] || emberCliOptions['port'];

  replace('some-folder', {
    files: ['**/*.json'],
    pattern: {
      match: /\$\{SOME_ABSOLUTE_HOST\}/g,
      replacement: http://${host}:${port}
    }
  });
  ...
});
```

**Comment by stefanpenner** [comment]
@john-kurkowski ah ok, that makes more sense. It is worth noting, that ember-cli can only provide the port its serving, not the one that may ultimately be provided to the browser (some users have nginx etc).

That being said, this seems fine. I'll take a look when I'm home, as my memory is apparently lacking :P

**Comment by john-kurkowski** [comment]
Understood. It'd be just the port for the development server / test runner.

It'd be nice if the solution were general enough to get all Ember CLI command options, validated and finalized. Rather than a one-off solution. But the ports of the `ember serve` / `ember test` are my only use case.

**Comment by adong** [comment]
... 5 yrs later ...

I'm also curious if there's way to console.log the parameters being passed in by running ember-cli in `ember-cli-build.js`, such as exposing 3333 as port when `ember s --port=3333` invokes. Thanks @stefanpenner @rwjblue

**Comment by bertdeblock** [comment]
Cleaning up old issues...
As this is more of a feature request, this would probably require an RFC if still relevant.
