### ISSUE TITLE
install fails when behind private npm registry

### ISSUE THREAD

**Issue by sfbwalder** [ember-cli/ember-cli#5160]
The install of 1.13.11, 12 and 13 fails when behind an npm private registry because a dependency is directly referencing a github url:
`testem@0.9.11`
`socket.io-client-pure@1.3.11`
`engine.io-client-pure@1.5.8`
`has-cors@1.0.3`
`global: 'https://github.com/component/global/archive/v2.0.1.tar.gz`:collision:

`has-cors@1.1.0` is fine.  It looks like @patocallaghan and @stefanpenner may be working towards a release that will bump to this version.  Is there an estimate when a release that will resolve this issue may be coming?

**Comment by stefanpenner** [comment]
looks like has-cors@1.1.0 has resolved this issue: https://github.com/component/has-cors/commit/f7fffa93036f35594d6ee00f25fdd4b6fd76d3b6

**Comment by stefanpenner** [comment]
let me try bumping

**Comment by stefanpenner** [comment]
bumping seems to work, but i dont appear to have commit @patocallaghan mind handling this?

**Comment by patocallaghan** [comment]
@stefanpenner sure, I can look at bumping each of the packages

**Comment by sfbwalder** [comment]
@patocallaghan @stefanpenner Is there an estimate when a release that will resolve this issue may be coming?

**Comment by stefanpenner** [comment]
Should already be released

**Comment by sfbwalder** [comment]
@patocallaghan @stefanpenner I wasn't very clear on my question... when will the dependency chain I listed above be updated and this change be in a new version of ember-cli?  1.13.14?  2.x?

**Comment by stefanpenner** [comment]
1.13.13

**Comment by stefanpenner** [comment]
hmm, maybe not. https://github.com/patocallaghan/engine.io-client/pull/3 should fix it, for 1.13.13

but we need señor @patocallaghan to merge/test/release

**Comment by sfbwalder** [comment]
Looks like 1.13.13 and 2.2.0-beta.1 are working.  Thanks!

**Comment by stefanpenner** [comment]
@sfbwalder :+1:
