### ISSUE TITLE
plain javascript in template will throw an error

### ISSUE THREAD

**Issue by TangMonk** [ember-cli/ember-cli#5161]
<img src="http://discuss.emberjs.com//uploads/emberjs_public/original/2X/f/ffc17ac12b4fea902f93b184bb0491da57ba27d2.png" width="416" height="149">

this looks fine, and works in chrome console

Ember error:

<img src="http://discuss.emberjs.com//uploads/emberjs_public/original/2X/a/a77218194d5d4eb12b097162a47c98325310aef0.png" width="524" height="495">

I create a empty test project [https://github.com/TangMonk/emberjs_loop_bug](https://github.com/TangMonk/emberjs_loop_bug)

I am using 1.13.13

**Comment by stefanpenner** [comment]
HBS do not support scripts /w js

**Comment by raytiley** [comment]
Curious what your expecting to happen here? The templates aren't javascript. I think the desired behavior is that the script tag / javascript will be set as plain text when rendered. Seems like now there are multiple issues with that, but if your trying to get the script to actually execute that wouldn't happen.

Even if Ember / HTMLbars rendered the script tag w/ the javascript the browser wouldn't execute it.

**Comment by TangMonk** [comment]
@stefanpenner, But when I remove loop script, and whatever js to the script tag, it works fine.

And I try to use handlebars command line to compile it manually, it works too

![image](https://cloud.githubusercontent.com/assets/3498786/11414301/bc267b70-942e-11e5-968a-c8eb00b4ac25.png)

**Comment by stefanpenner** [comment]
> @stefanpenner, But when I remove loop script, and whatever js to the script tag, it works fine.

Maybe, but it isn't something we current aim to support.

> And I try to use handlebars command line to compile it manually, it works too

We don't use handlebars

**Comment by TangMonk** [comment]
@stefanpenner @raytiley 

![image](https://cloud.githubusercontent.com/assets/3498786/11414342/36f632aa-942f-11e5-8e7d-7e4920c717c7.png)

I remove loop and insert an jquery code, it works fine

![image](https://cloud.githubusercontent.com/assets/3498786/11414346/4973b056-942f-11e5-8136-5c84e6f5b754.png)

**Comment by stefanpenner** [comment]
in-fact this has been disabled entirely https://github.com/tildeio/htmlbars/pull/428

**Comment by stefanpenner** [comment]
Sorry for the confusion, the partial support was unintended.

**Comment by TangMonk** [comment]
@stefanpenner I see, thanks for your reply
