### ISSUE TITLE
CSP report sent to undefined

### ISSUE THREAD

**Issue by MadMub** [ember-cli/ember-cli#5166]
Not sure if this is the right spot to post (might be better suited for ember-cli-csp-report addon) or if its even a bug. I am new to ember, and using the ember cli to start a fresh project, running ```ember server``` and opening ```localhost:4200``` in FF seems to be constantly loading (the spinner never stops, despite content being rendered, this could be normal behaviour) but I did notice in the dev tools a bunch of CSP reports are fired off to undefined:4200 (to me that doesn't seem right, and as expected they never get a response).

Screenshot:
<img width="1376" alt="screenshot 2015-11-26 23 55 11" src="https://cloud.githubusercontent.com/assets/2809870/11434400/d44e7bce-9499-11e5-9ec1-14eba042ff63.png">

UPDATE:
Performance seems to be much better in chromium, where the csp reports don't appear to be blocking the site, on Firefox for some reason my interactions are unresponsive for quite some time (minutes). From what I've read csp reports appear to be more of a dev tool to keep these issues on the mind of the developer, so I doubt much will come of this issue.

I will leave it open in case having reports sent to undefined is in fact a bug (again though this could be something that needs to be addressed on the addon? Not sure if ember-cli has some broken configuration I'm unaware of).

**Comment by RodrigoBalest** [comment]
I'm having the same 'undefined' issue.

**Comment by stefanpenner** [comment]
> Performance seems to be much better in chromium, where the csp reports don't appear to be blocking the site, on Firefox for some reason my interactions are unresponsive for quite some time (minutes).

This seems like a firefox bug, be sure to open an issue their.

For developers affected by this, consider removing the `CSP` add-on. (We may disable it by default anyways soon, as the ergonomics are poor).

**Comment by RodrigoBalest** [comment]
I managed to solve this by adding the line
```json
    "host": "localhost"
```
to _.ember-cli_ file.

Also, to avoid csp detecting inline scripts (as the one at the index page) as bad code, I added the following code to the file _config/environment.js_
```javascript
ENV.contentSecurityPolicy = {
  'script-src' : "'unsafe-inline' 'self'"
};
```
right before the line
```javascript
if (environment === 'development') {
```

**Comment by bevinhex** [comment]
adding ```"host": "localhost"``` worked for me
