### ISSUE TITLE
Cannot find module 'rimraf'

### ISSUE THREAD

**Issue by gingermusketeer** [ember-cli/ember-cli#5173]
I see a number of issues related to the same problem but this appears to be different.

I installed ember-cli for a project i am working on from the master branch on github as there was a fix i needed. I used 7cdcd310558580dd6b94ad5e0999c525294db678 as the sha for the dependency, changed the package.json dependency to
```json
"ember-cli": "https://github.com/ember-cli/ember-cli.git#7cdcd31",
```
After installing this i get `Cannot find module 'rimraf'` from `node_modules/ember-cli/lib/commands/new.js:8:26`

Looking at new.js i can see the require here https://github.com/ember-cli/ember-cli/blob/7cdcd310558580dd6b94ad5e0999c525294db678/lib/commands/new.js#L8

And in package.json https://github.com/ember-cli/ember-cli/blob/7cdcd310558580dd6b94ad5e0999c525294db678/package.json#L133
it is specified in the `devDependencies` section. Should this be in the `dependencies` section?

This issue was reproducible on CI as well as my local machine.

Running `ember -v` i get
```bash
ember -v
version: 1.13.13
node: 4.0.0
npm: 2.14.10
os: darwin x64
```

I have added `rimraf` to my dependencies and it has resolved the issue locally and on CI

**Comment by rwjblue** [comment]
Can you run `npm --version`?

**Comment by rwjblue** [comment]
I suspect that this is related to `npm` 3.3.11 through 3.3.13 issue described here: https://github.com/npm/npm/issues/10458.

The fix is to use a non-broken version of NPM (3.3.10 and lower or 3.4.0 and higher).

**Comment by gingermusketeer** [comment]
running `npm --version` gives
```bash
2.14.13
```

**Comment by Dhaulagiri** [comment]
I'm seeing the same thing on master with node 4.2.2 & npm 2.14.7

**Comment by stefanpenner** [comment]
Yea it should be a prod dependency

**Comment by rwjblue** [comment]
Should be addressed by https://github.com/ember-cli/ember-cli/pull/5185

**Comment by stefanpenner** [comment]
Thanks @rwjblue

**Comment by gingermusketeer** [comment]
Thanks @rwjblue

**Comment by stefanpenner** [comment]
We may want to backport and release a 1.13.14 cc @twokul

**Comment by rwjblue** [comment]
I haven't tested/checked, but I don't think this issue affects 1.13 branch. Rimraf was added to the new blueprint (so it can clean up failed folder generation) in master only.

**Comment by Dhaulagiri** [comment]
I only saw this on master.  Haven't seen it on multiple apps on the latest released version.
