### ISSUE TITLE
Tests running error in phantomjs but success in browser

### ISSUE THREAD

**Issue by nightire** [ember-cli/ember-cli#5175]
I rarely running tests under phantomjs but usually in browser, today my work mates running test in CLI and report errors to me.

I saw these messages:

```
global failure
    ✘ Error: Could not find module `webapp/config/environment` imported from `webapp/tests/helpers/resolver`
```

but actually the imported environment config is correct, use browser to see `http://localhost:3001` will pass all tests.

I can't find any hints on this issue but seems it is not affect our normal work, anyone knows what's wrong here?

**Comment by stefanpenner** [comment]
sounds like a syntax error (or some unstranspiled ES6 code that has entered your output) Unsure why testem isn't reporting.

**Comment by rwjblue** [comment]
@stefanpenner - I think it is because failures that happen before loading testem.js are not detected/reported.

**Comment by stefanpenner** [comment]
@rwjblue ya, likely. Abit tricky that one. I believe if we have a better handshake with testem here, we would be better off.

cc @johanneswuerbach unsure if you have any ideas. We would love to load testem first, but it needs to be loaded after the test framework (to detect which one). But if we load it after, a failure before wont get caught.

Is there a way for us to load testem first, then later inform it which test framework the session is using.?

**Comment by johanneswuerbach** [comment]
Currently there isn't, but that sounds definitely like a valid use-case. Mind creating an issue in the testem  repo?

**Comment by stefanpenner** [comment]
I took a stab at something that should work: https://github.com/testem/testem/pull/709
