### ISSUE TITLE
[1.13.13] Deprecations still show if command is run with silent flag

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/ember-cli#5176]
I have the following testing script that runs on Bamboo:

    ember test -r xunit --silent > test-log.xml

The test-log file is created, but it can't be parsed because the file begins with a deprecation warning (DEPRECATION: Node v0.10.40 is no longer supported by Ember CLI. Please update to a more recent version of Node).

I'm working on getting Node updated on this server, but, if this is a really deprecation message and the build still works, should deprecation messages be logged when a command is run silently?

I'm happy to do any work that comes out of this issue. Just looking for a little bit of guidance on what / if work needs be done.

**Comment by stefanpenner** [comment]
I wonder if this output should actually go to stderr instead.

**Comment by stefanpenner** [comment]
Looking at the code it should be fine.. strange.

**Comment by gmurphey** [comment]
I think I found the issue. The default export in the deprecate utility calls `console.log` rather than piping the output through `this.ui.writeLine`. I'll put together a pull request!

**Comment by stefanpenner** [comment]
@gmurphey woot, thanks :)
