### ISSUE TITLE
IE8: object doesn't support this action

### ISSUE THREAD

**Issue by jerel** [ember-cli/ember-cli#5182]
I have a strange issue in an Ember app of mine. I recently upgraded Ember, Ember Data, and Ember CLI to the latest versions with almost no app code changes. Internet Explorer 8 began failing with `object doesn't support this action` and very little additional information. (I removed livereload as I've seen it throw errors in IE8) But if I leave all npm and bower dependencies on the latest versions and downgrade only Ember CLI to 1.13.8 then the compiled app is happy in IE8.

So, is there some browser code that Ember CLI injects that changed between those patch versions? A brand new (empty) app created with the latest Ember CLI doesn't error in IE8 so it seems to be something peculiar to my app's code path. I can keep running on v1.13.8 but I at least wanted to open an issue in case another developer is affected by the same situation.

**Comment by stefanpenner** [comment]
Nothing specific comes to mind, without a reproduction this one will be hard to diagnose.

@rwjblue anything come to mind?

**Comment by rwjblue** [comment]
>  I recently upgraded Ember, Ember Data, and Ember CLI to the latest versions with almost no app code changes.

Please provide the actual versions. The latest stable versions of Ember (currently 2.2.0) and Ember Data (also 2.2.0) do not support IE8 (this was one of the breaking changes in Ember 2.0.0).

**Comment by jerel** [comment]
I meant latest on the 1.13 branch. I'm running Ember 1.13.11 and Ember Data 1.13.15

Relevant section from package.json:
``` js
"broccoli-asset-rev": "^2.2.0",
"ember-cli": "1.13.12", // 1.13.8 doesn't error
"ember-cli-app-version": "^1.0.0",
"ember-cli-babel": "^5.1.5",
"ember-cli-dependency-checker": "^1.1.0",
"ember-cli-htmlbars": "^1.0.1",
"ember-cli-htmlbars-inline-precompile": "^0.3.1",
"ember-cli-ic-ajax": "0.2.4",
"ember-cli-qunit": "^1.0.4",
"ember-cli-release": "0.2.8",
"ember-cli-uglify": "^1.2.0",
"ember-data": "1.13.15",
"ember-disable-proxy-controllers": "^1.0.1",
"ember-export-application-global": "^1.0.4",
```

Here's the call stack:
![ember-cli](https://cloud.githubusercontent.com/assets/322706/11567046/bd745d22-99aa-11e5-954f-c64f264cd904.png)

**Comment by stefanpenner** [comment]
can you share `e.stack` ?

**Comment by jerel** [comment]
Yeah, e.stack is undefined:
![e](https://cloud.githubusercontent.com/assets/322706/11567310/10a6b548-99ac-11e5-8525-10a9e82b7779.png)

**Comment by stefanpenner** [comment]
@jerel that sucks :P

**Comment by stefanpenner** [comment]
whats `func.toString()` ?

**Comment by jerel** [comment]
``` js
function () /* target, method, args */{
      var length = arguments.length;
      var method, target, args;
      if (length === 1) {
        method = arguments[0];
        target = null;
      } else {
        target = arguments[0];
        method = arguments[1];
      }
      if (_backburnerUtils.isString(method)) {
        method = target[method];
      }
      if (length > 2) {
        args = new Array(length - 2);
        for (var i = 0, l = length - 2; i < l; i++) {
          args[i] = arguments[i + 2];
        }
      } else {
        args = [];
      }
      var onError = getOnError(this.options);
      this.begin();
      // guard against Safari 6's double-finally bug
      var didFinally = false;
      if (onError) {
        try {
          return method.apply(target, args);
        } catch (error) {
          onError(error);
        } finally {
          if (!didFinally) {
            didFinally = true;
            this.end();
          }
        }
      } else {
        try {
          ret
```
Not sure why it ends prematurely. Also, I signed into slack now if you prefer that

**Comment by stefanpenner** [comment]
something does seem sideways... unsure. Maybe you can extract a sharable example?

**Comment by jerel** [comment]
I don't have time for 3 days at least (deadline) but I'll leave myself a todo.

**Comment by robert-allan-frank** [comment]
I have run into a similar problem with IE8. In v1.13.8, my application works yet starting in v1.13.10 and above it fails in IE8. When doing a comparison between the `my-app.js` file of both builds, the v1.13.10 version has `Object.defineProperty` calls.

```javascript
define('my-app/components/my-comp', ['exports', 'my-addon/components/my-comp'], function (exports, _commonComponentsMyComp) {
  Object.defineProperty(exports, 'default', {
    enumerable: true,
    get: function get() {
      return _commonComponentsMyComp['default'];
    }
  });
});
```

That same code built with v1.13.8 looks like:

```javascript
define('my-app/components/my-comp', ['exports', 'my-addon/components/my-comp'], function (exports, my_comp) {
  'use strict';
  exports['default'] = my_comp['default'];
});
```

When viewing the JS file of the corresponding component in my addon, it has the following export pattern:

```javascript
export { default } from ‘my-app/components/my-comp’;
```

... which is generated from the CLI blueprint `ember-cli/blueprints/component-addon/files/__root__/__path__/__name__.js`

The interesting thing to note is if I change the export in my component addon to look like:

```javascript
import MyComp from ‘my-app/components/my-comp’;
export default MyComp;
```

... then the `Object.defineProperty` call is no longer generated by the v1.13.10 build in my `my-app.js` file which instead then looks like:

```javascript
define('my-app/components/my-comp', ['exports', 'ember', 'my-addon/components/my-comp'], function (exports, _ember, _commonComponentsMyComp) {
  exports['default'] = _commonComponentsMyComp['default'];
});
```

So I have a workaround for the issue but I'd like to use the Ember-CLI provided blueprints if at all possible since the workaround opens the door for human error. I believe this change originated with #4792.

**Comment by mattbearman** [comment]
@jerel I'm having the **exact** same issue, even my `func.toString()` output is the same. Did you ever figure this out? Really don't want to downgrade to 1.13.8 (I'm currently on 1.13.12)

**Comment by jerel** [comment]
@mattbearman I just checked and the app that had caused this error is still on CLI 1.13.8, so I guess I never did solve it.

**Comment by mattbearman** [comment]
Balls, really need to get this working in IE8. I'm currently stepping through the code in debugger, but not found the cause of the error yet. Thanks for the quick response, I'll update this issue if I ever figure it out.

**Comment by mattbearman** [comment]
@jerel so I took a stab in the dark as I'd already faced issues with the ember-i18n addon and IE8, so I removed if from my package.json and low and behold no more error.

The app get's much further through the boot process, until of course I get `Could not find module ember-i18n/services/i18n`

**Comment by jerel** [comment]
@mattbearman I do. And I'm running a fork which has IE8 fixes in it. You can add it to your package.json with this: `"ember-i18n": "jerel/ember-i18n#bugfix/ie8"`. If I remember right my PR was either rejected or changed significantly before merge so I just kept using the fork.
