### ISSUE TITLE
Testing environment not properly cleared up

### ISSUE THREAD

**Issue by ohcibi** [ember-cli/ember-cli#5183]
See this example: https://github.com/ohcibi/dirty-test-environment-example (clone and run tests in brother or phantomjs)

Actually both tests should pass as the app is destroyed and created between the tests. This in fact even works. I put a breakpoint in `startApp` and it stops their before both tests.
However when it is run the second time, the object that `App.create()` returns is an application which's container has an `index` controller which has an object `foo` with a property `bar` (containing the random number from what was set in the previous run). So although a new app is created the container or controller is still from the old app.

This only happens if `foo` is an object. If it was like

```
this.set("foo", Math.random());
```

and then

```
{{input value=foo}}
```

both tests would pass.

**Comment by kategengler** [comment]
@ohcibi I think this is because you are changing the properties of an object that is on the controller class rather than the instance, similar to what is described here https://dockyard.com/blog/2015/09/18/ember-best-practices-avoid-leaking-state-into-factories

**Comment by stefanpenner** [comment]
yes, you are polluting the prototype: https://github.com/ohcibi/dirty-test-environment-example/commit/efbf96ee2d47a9b42d2bd42e3e35a832344745e4#diff-d23253fd23906536d436edd03afb8fb6R10

please do not put complex objects on the prototype, as that is nearly never what someone wants. Either make them a CP or set them in `init`.

What you have done there:

````js
export default Route.extend({
   foo: {} 
})
```

ultimately becomes:

```js
function RouteSubclass() {
   Route.apply(this, arguments);
}
RouteSubclass.prototype = Object.create(Route.prototoype);
RouteSubClass.prototype.bar = {};
```

As extend, is merely short hand for JavaScript inheritance.

In raw JS, you likely would do:

```js
function RouteSubclass() {
   Route.apply(this, arguments);
   this.bar = {};
}
RouteSubclass.prototype = Object.create(Route.prototoype);
```

So in ember you would do

```js
export default Route.extend({
  init() {
    this._super(...arguments);
    this.bar = {};
  }
})
```

or as a descriptor.

```js
export default Route.extend({
  bar: computed(_ => {})
})
```
