### ISSUE TITLE
app/index.html is persisted and never updates

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#5191]
Confirmed on a new app that modifying the index.html always picks up a cached version and the changes are never reflected.

**Comment by csantero** [comment]
I've also noticed this on 1.13.13 - when changing index.html I must restart `ember serve` to pick up the change.

**Comment by stefanpenner** [comment]
Ya I noticed this as well

**Comment by stefanpenner** [comment]
overzealous caching :P

**Comment by stefanpenner** [comment]
fixed by: https://github.com/ember-cli/broccoli-config-replace/pull/4

**Comment by stefanpenner** [comment]
broccoli-config-replacer release as v1.1.1, which satisfies CLI dependency on it as v1.1.0. Closing
