### ISSUE TITLE
Import Causes Error

### ISSUE THREAD

**Issue by ptmoy2** [ember-cli/ember-cli#5194]
I used Ember-Cli 1.13.12 to create this test case, but same problem with Ember 2.2 & Ember Data 2.2.1 in my project.  Steps are as follows:

1) $ ember new testImport
2) Change config/environment.js to add podModulePrefix:
    var ENV = {
        modulePrefix: 'test-import',
        podModulePrefix: 'test-import/pods
        ...
       },
3) Edit .ember-cli hidden file to add: "usePods": true
4) $ ember g util l-calc
5) $ ember g route application
6) $ ember g controller application
7) Edit the application controller 'js' file to show the following:

import Ember from 'ember';
import lCalc from '../../../utils/l-calc';

export default Ember.Controller.extend({
    init: function() {
	alert ('inside application controller init');
	lCalc();
	}
});

8) $ ember server

Console shows the following error:

Error while processing route: index Could not find module `utils/l-calc` imported from `test-import/pods/application/controller` Error: Could not find module `utils/l-calc` imported from `test-import/pods/application/controller`
    at requireFrom (http://localhost:4200/assets/vendor.js:119:13)
    at reify (http://localhost:4200/assets/vendor.js:106:22)
    at mod.state (http://localhost:4200/assets/vendor.js:149:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:4200/assets/vendor.js:70591:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:70323:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:33721:20)
    at exports.default._emberRuntimeSystemObject.default.extend.resolveController (http://localhost:4200/assets/vendor.js:15736:19)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15581:43)

**Comment by kamalaknn** [comment]
@ptmoy2 from your reproduction, the relative import
```js
import lCalc from '../../../utils/l-calc';
```

appears one level too deep. `import lCalc from '../../utils/l-calc';`  or `import lCalc from 'test-import/utils/l-calc';` seems to work. Or am I missing something ?

**Comment by ptmoy2** [comment]
No, that's the level the generated tests also used.

**Comment by kamalaknn** [comment]
The generated `util:lCalc` would be available as `test-import/utils/l-calc`. The corresponding generated test for the util would be `test-import/tests/unit/utils/l-calc-test`. To reach `test-import/utils/l-calc` from `test-import/tests/unit/utils/l-calc-test` you have to go three levels up and so the generated test has `import lCalc from '../../../utils/l-calc';`

However, the generated `controller:application` would be available under `test-import/pods/application/controller`. So to reach `test-import/utils/l-calc` from `test-import/pods/application/controller` you only have to go two levels up, and so it should be `import lCalc from '../../utils/l-calc';`.

If the relative imports do not make sense, you can use absolute imports - `import lCalc from 'test-import/utils/l-calc';` consistently everywhere. See "USING MODULES & THE RESOLVER" section under http://ember-cli.com/user-guide.

**Comment by selvagsz** [comment]
This is why I don't love relative imports :expressionless:

**Comment by stefanpenner** [comment]
> No, that's the level the generated tests also used. Are you forgetting the extra level created by the 'pods' directory?

it sounds like maybe the generators aren't producing the right imports? cc @trabus

**Comment by trabus** [comment]
Utils shouldn't be affected by pod structure. It seems this may be a bug. Will investigate soon.

**Comment by trabus** [comment]
Okay, so reading this on the bus this morning, I misunderstood what was happening. I thought it was being generated that way for the utils tests, but it appears that is not the case.

@ptmoy2 I would not recommend using relative paths for your imports in your tests. I would instead use the app path, which will guarantee that you get the right file:

```
import lCalc from '../../../utils/l-calc';
// becomes
import lCalc from 'test-import/utils/l-calc';
```

**Comment by stefanpenner** [comment]
@trabus, thanks for digging in. I agree with your advice, test -> app, should be absolute imports.

Going to close this, if we misunderstood please provide some details as to why, and we can reopen.
