### ISSUE TITLE
Template is not rendering in my upgrading ember app . 

### ISSUE THREAD

**Issue by vinothwindows47** [ember-cli/ember-cli#5200]
I was using ember 1.7.0 and ember-data 1.1.0.

Now I am trying to migrating ember 1.13.11 and ember data 1.13.15 using ember-cli 1.13.13 .

After migrating all my app resources , the page has been blanked . Only application controller routes and controller only called.But templates is not rendering . I don't know it is HTML bar problem . 

Please help me @tpitale @jakehow @lukemelia @alexspeller

**Comment by stefanpenner** [comment]
Help is best asked on Stackoverflow, if there are actual bugs (with reproductions, or clear steps to reproduce) feel free to open issues.

Unfortunately, Q/A style discussion is much better suited to stackoverflow. Please feel free to crosslink.
