### ISSUE TITLE
After installing 2.2.0-beta.1, still shows v1.13.13

### ISSUE THREAD

**Issue by jtsom** [ember-cli/ember-cli#5216]
After installing version 2.2.0-beta.1, ember still shows version 1.13.13:

ember -v
version: 1.13.13
node: 5.2.0
npm: 2.14.10
os: darwin x64

(and also showing a different npm version than the system version:
npm -v
3.3.12
)

**Comment by rwjblue** [comment]
Can you confirm that you followed the instructions in the release notes for updating both the global version and your project local one? The globally installed version defers to whatever your project is using (to allow different projects to use different versions).

RE: npm version; we bundle npm 2.x (what is reported).

**Comment by jtsom** [comment]
Yup. My bad, seems in my haste I skipped that step! Thanks!
