### ISSUE TITLE
Unit test for function in application route requires application controller file to be present

### ISSUE THREAD

**Issue by adam-knights** [ember-cli/ember-cli#5217]
Lets say I setup an application route like this:

```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
import vibrate from '../utils/utility-vibrate';

export default Ember.Route.extend(ApplicationRouteMixin, {
  setupController: function(controller, model) {
    this._super(controller, model);

    controller.set('session', Ember.inject.service('session'));

    controller.set('leftSidebarWidgets', []);
    controller.set('rightSidebarWidgets', []);
    controller.set('unpricedOrders', []);
    controller.set('loadingUnpricedOrders', {value: true});
  },
  deleteRecordValidation: function(modelName) {
    if (!modelName) {
      return true;
    }

    if (modelName === 'orderItem') {
      let rightHandWidgets = this.controllerFor('application').get('rightSidebarWidgets');

      if (rightHandWidgets.any(w => Ember.get(w, 'name') === 'widgets/add-update-order-item')) {
        let orderItemDiv = Ember.$('.widgets\\/add-update-order-item');
        vibrate(orderItemDiv);

        return false;
      }
    }

    return true;
  }
});
```

I then write a unit test to test the route's function:

```
import { moduleFor, test } from 'ember-qunit';

moduleFor('route:application', 'Unit | Route | application', {
  needs: ['service:session', 'controller:application']
});

test('delete record validation returns false if order item delete and update order item widget open', function(assert) {
  assert.expect(1);

  let route = this.subject();
  let controller = route.controllerFor('application');

  controller.set('rightSidebarWidgets', [{
    name: 'widgets/add-update-order-item'
  }]);

  assert.notOk(route.deleteRecordValidation('orderItem'));
});
```

If I `ember g controller application` - and leave it as default then the test works. If I don't have the /controllers/application.js file, then the test fails with `Attempting to register an unknown factory: 'controller:application'`.

The application itself works either way - should I have to create an empty controller file just for the unit test, or should ember cli take care of this?

**Comment by imkikus** [comment]
@adam-knights Is this issue resolved? If so, what is the fix for this?

**Comment by adam-knights** [comment]
@imkikus I've seen no mention of a fix

**Comment by imkikus** [comment]
@adam-knights you mean to say its still pending?

**Comment by adam-knights** [comment]
@imkikus correct - i havent tested the latest versions, but i've seen no release note to suggest this would have been fixed. I guess the workaround is to live with the empty controller file - i imagine this issue is very low priority as we are the only two people to have reported it in 9 months.

**Comment by imkikus** [comment]
@adam-knights :+1: I'am using ember-cli `v2.6.0`

**Comment by nathanhammond** [comment]
Hey @adam-knights and @imkikus!

1. `needs: ['controller:application']` will not work without actually having an application controller predefined.
2. `let controller = route.controllerFor('application');` doesn't, to my knowledge, automatically set up a controller for you.
3. `let rightHandWidgets = this.controllerFor('application').get('rightSidebarWidgets');` is not very well set up for unit testing as it relies on dynamic dependency injection of the `application` controller.
4. To make this work you will need to manually insert a vanilla `Ember.Controller` instance as `application:controller` into the registry.

This is not an Ember CLI bug at all, it's just the behavior of the underlying Ember framework. As such I'm closing the issue. You're looking for advanced testing examples somewhere on the Internet or you can stop by [#-help](https://embercommunity.slack.com/messages/-help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you have additional questions about how to unit test your code. 😄
