### ISSUE TITLE
Unable to install ember-cli 1.13.13 without internet connection

### ISSUE THREAD

**Issue by tsing80** [ember-cli/ember-cli#5223]
Post here as not sure where to post issue  for engine.io-client.pure and socket.io-client-pure.

I'm not able to install ember-cli 1.13.13 without internet connection even npm cache exists due to  component/has-cors#1. It  is fixed on has-cors 1.1.0 but engine.io-client.pure and socket.io-client-pure still depends on old version of 1.0.3 .  ember-cli 1.13.13 has indirect dependency on it  due to  it depends on testem => socket.io-pure . This make me not unable to upgrade to ember-cli 1.13.13 to a CI server without internet connection.

**Comment by stefanpenner** [comment]
@patocallaghan we need you to cut + release https://github.com/patocallaghan/engine.io-client/pull/3 (i don't have permission)

**Comment by tsing80** [comment]
cc @johanneswuerbach

**Comment by stefanpenner** [comment]
@tsing80 Im pretty sure only  @patocallaghan has commit bit to that repo

**Comment by johanneswuerbach** [comment]
Sorry, I'll look into cutting a new release today.

**Comment by patocallaghan** [comment]
@stefanpenner I've added you to this repo but I don't think this is the correct one. I think testem/engine.io-client is the one that's being used

**Comment by stefanpenner** [comment]
@patocallaghan ah, so it's two issues.one my pr would fix and then another on the testem side.

It's really to bad the socket.io folks are not on top of this themselves

**Comment by stefanpenner** [comment]
I merged my pr, @patocallaghan are you able to release that package? (Just driving in to work, and then off to a meeting). If not I can release it in afew hours.

**Comment by johanneswuerbach** [comment]
Sadly you can't just release that package, but need to release https://github.com/testem/engine.io-client, bump the client and release https://github.com/testem/engine.io,
bump the client and release https://github.com/testem/socket.io-client and https://github.com/testem/socket.io

**Comment by johanneswuerbach** [comment]
Looking into it now.

**Comment by johanneswuerbach** [comment]
Should be fixed with `socket.io-pure` `v1.3.12`

**Comment by patocallaghan** [comment]
thanks guys, my bandwidth is very limited these days

**Comment by stefanpenner** [comment]
@patocallaghan no prob (me too), thanks @johanneswuerbach :)
