### ISSUE TITLE
[2.2.0-beta.1] ember-mocha does not run tests

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-cli/ember-cli#5224]
Using a fresh install of ember-cli v2.2.1-beta.1 and running
```
ember install ember-cli-mocha
ember test
```
the project builds and then stalls without running the tests

**Comment by ballPointPenguin** [comment]
running the server and opening http://localhost:4200/tests shows some errors, starting with:
```
Uncaught TypeError: mocha.setup is not a function 
```

**Comment by ballPointPenguin** [comment]
I just confirmed that this does work as expected when using ember-cli 1.13.13

**Comment by rwjblue** [comment]
It is most likely an issue with ember-cli-mocha, and you open an issue over there also?

**Comment by Dhaulagiri** [comment]
Trying to run our mocha tests with ember-cli 2.2.0-beta.3 I now see this error:
```
ok 1 PhantomJS 1.9 - Global error: TypeError: 'undefined' is not an object (evaluating 'Runner.prototype') at http://localhost:7357/testem.js, line 441
    ---
        Log: |
            { type: 'error',
              text: 'TypeError: \'undefined\' is not an object (evaluating \'Runner.prototype\') at http://localhost:7357/testem.js, line 441\n' }
    ...

1..1
# tests 1
# pass  1
# skip  0
# fail  0
```

**Comment by stefanpenner** [comment]
@Dhaulagiri reproduction repo please, this appears to work fine in my setups. Will need something to reproduce.

**Comment by stefanpenner** [comment]
@johanneswuerbach cc

**Comment by Dhaulagiri** [comment]
@stefanpenner reproduced on a fresh app [here](https://github.com/Dhaulagiri/ember-mocha-test) by running `ember test`

**Comment by stefanpenner** [comment]
i think this is a bug in testems mocha adapter, it does not appear to support the new deferred initialization.

**Comment by johanneswuerbach** [comment]
This was also my first guess. I'll have some time later today to assist.

**Comment by stefanpenner** [comment]
fix: https://github.com/testem/testem/pull/723

**Comment by Dhaulagiri** [comment]
awesome, thanks @stefanpenner for taking a look

**Comment by johanneswuerbach** [comment]
Fixed in `1.0.0-rc.5`. You can upgrade to that version by removing your modules `rm -rf node_modules/` and reinstalling them via `npm install`.

**Comment by stefanpenner** [comment]
As @johanneswuerbach mentioned, ember-cli's package.json allows this as semver drift. So we should be good.

@johanneswuerbach thanks to tag-teaming this one with me :)

**Comment by johanneswuerbach** [comment]
Thanks for battle testing testem v1 :bow:!

**Comment by Dhaulagiri** [comment]
confirmed this works, thanks for the fast turnaround @stefanpenner @johanneswuerbach :100:
