### ISSUE TITLE
broccoli-ember-script output is not transpiled with ember-cli > 1.13.8

### ISSUE THREAD

**Issue by afn** [ember-cli/ember-cli#5225]
Not sure if this is really an ember-cli bug or a broccoli-ember-script bug, so apologies if this is filed in the wrong place.

With ember-cli v1.13.9 and later, compiled EmberScript is dumped verbatim into the generated JS.  To reproduce:

* `ember new app`
* `cd app`
* `npm install broccoli-ember-script --save-dev`
* Remove `app/app.js` and create a new `app/app.em`:
    ```
`import Ember from 'ember';`
`import Resolver from 'ember/resolver';`
`import loadInitializers from 'ember/load-initializers';`
`import config from './config/environment';`

Ember.MODEL_FACTORY_INJECTIONS = true

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix
  podModulePrefix: config.podModulePrefix
}, Resolver)

loadInitializers(App, config.modulePrefix);

`export default App;`
```
* `ember build`

The generated `dist/assets/app.js` contains:

```javascript
// Generated by EmberScript 0.0.14
var App;
var set$ = Ember.set;
var get$ = Ember.get;
import Ember from 'ember';;
import Resolver from 'ember/resolver';;
import loadInitializers from 'ember/load-initializers';;
import config from './config/environment';;
set$(Ember, 'MODEL_FACTORY_INJECTIONS', true);
App = Ember.Application.extend({
  modulePrefix: get$(config, 'modulePrefix'),
  podModulePrefix: get$(config, 'podModulePrefix')
}, Resolver);
loadInitializers(App, get$(config, 'modulePrefix'));
export default App;;
```

If you downgrade `ember-cli` in `package.json` to 1.13.8, you'll instead see the expected output:

```javascript
define('app/app', ['exports', 'ember', 'ember/resolver', 'ember/load-initializers', 'app/config/environment'], function (exports, Ember, Resolver, loadInitializers, config) {

  'use strict';

  // Generated by EmberScript 0.0.14
  var App;
  var set$ = Ember['default'].set;
  var get$ = Ember['default'].get;
  set$(Ember['default'], 'MODEL_FACTORY_INJECTIONS', true);
  App = Ember['default'].Application.extend({
    modulePrefix: get$(config['default'], 'modulePrefix'),
    podModulePrefix: get$(config['default'], 'podModulePrefix')
  }, Resolver['default']);
  loadInitializers['default'](App, get$(config['default'], 'modulePrefix'));
  exports['default'] = App;;

});
```

**Comment by afn** [comment]
The breaking commit was 8f8de1d44f0a77accf52ad44772055db0cb6286a.

**Comment by stefanpenner** [comment]
cc @chadhietala

**Comment by stefanpenner** [comment]
@afn can you provide a quick GH repo with an app that demonstrates this, that will allow us to know we are the exact setup you see.

**Comment by afn** [comment]
I started digging a bit deeper to see why CoffeeScript was working while EmberScript was not. For coffeescript, we were using `ember-cli-coffeescript` whereas for EmberScript we were just using `broccoli-ember-script`. So I figured I'd try the EmberScript addon (`ember-cli-emberscript`). This didn't quite work out of the box, so I [forked it](https://github.com/amitree/ember-cli-emberscript), changed the `index.js` to resemble that of `ember-cli-coffeescript` (with `registry.add` being called in `setupPreprocessorRegistry` rather than in `included`) and added `"ember-addon": { "before": [ "ember-cli-babel" ] }` to `package.json`.  This did the trick.

So I think we can close this issue; the only confusing part is why using `broccoli-ember-script` ever worked in the first place (and why, in `ember-cli` > 1.13.8, it still runs even though it's not executed in the right order).  Any enlightenment would be much appreciated :)

**Comment by rwjblue** [comment]
@stefanpenner - Possibly https://github.com/emberjs/data/issues/3998.  Between 1.13.8 and 1.13.13 we switched to using babel for transpiling modules, but I am only aware of this affecting addons themselves (not app code).  

I believe that @afn is correct, and most likely we somehow changed the ordering when switching to babel for module transpilation.

**Comment by stefanpenner** [comment]
i think if ember-cli-emberscript get @afn's patch, that is good enough for me to say this is closable..

**Comment by rwjblue** [comment]
Agreed.  I submitted https://github.com/ember-cli/ember-cli-preprocessor-registry/pull/7 to remove the legacy non-addon support in master (2.x branch).

**Comment by afn** [comment]
> Agreed. I submitted ember-cli/ember-cli-preprocessor-registry#7 to remove the legacy non-addon support in master (2.x branch).

Aha! That solves the mystery of why it was magically working before :smile:

**Comment by stefanpenner** [comment]
Resolution is: users should use ember-cli-emberscript, and @afn's patch should be submitted.

Going to close this, unless my above is incorrect (feel free to let me know)
