### ISSUE TITLE
Passed.png asset not generated on bootstrap

### ISSUE THREAD

**Issue by cometman** [ember-cli/ember-cli#5226]
Originally documented here https://github.com/thoughtbot/ember-cli-rails/issues/358#issuecomment-164565304. 

Create new ember app with `ember new`.  

Start the app:

`Error: ENOENT, no such file or directory 'front-end/tmp/funnel-input_base_path-dpVf9ewX.tmp/0/bower_components/ember-qunit-notifications/passed.png' at Error (native) at Object.fs.lstatSync (fs.js:796:18) at symlink (/Users/Clay/Developer/ember-api-front-end/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26) at Function.symlinkOrCopySync (front-end/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5) at Funnel._copy (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:398:19) at Funnel.processFile (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:381:8) at Funnel.applyPatch [as _applyPatch] (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:298:12) at Funnel.<anonymous> (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:250:10) at Array.forEach (native) at Funnel.processFilters (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:249:9)`

**Comment by joedaniels29** [comment]
anyone know of a way to mitigate this?

**Comment by cometman** [comment]
I am going to start digging into it later today

**Comment by joedaniels29** [comment]
fyi: commenting out `ember-qunit-notifications` from bower.json suppresses error. thanks for looking into this!

**Comment by stefanpenner** [comment]
Can someone provide a reproduction. This all seems to work fine for a default ember-cli app.

**Comment by stefanpenner** [comment]
I'll gladly reopen this if a reproduction can be provided. But without that, this isn't actionable.
