### ISSUE TITLE
[1.13.13] Attempting to inject an unknown injection: `router:main` with Ember 1.12.1

### ISSUE THREAD

**Issue by offirgolan** [ember-cli/ember-cli#5227]
Unit tests using ember-cli `1.13.13` and ember `1.12.1` error out with

`Error: Attempting to inject an unknown injection: 'router:main'`

Steps to recreate:

1. `ember new my-app`
2. `ember g controller foo`
3. Open up tests in your browser or run `ember test`
4. Cry

Update: Getting the same result with ember-cli `2.2.0-beta.1`

**Comment by orochi235** [comment]
I ran across this in a project today as well. It's one that hadn't been modified in a while; we upgraded only ember-data from an old version (1.0.0 b14) to a slightly less old version (1.0.0b18) and a single unit test started failing with this exact message. Nothing else changed. I wonder if it's a bug in a new version of  some common dependency?

**Comment by jefflage** [comment]
i don't know if its a proper fix, but adding `router:main' to the `needs` array on the test fixes it for me

**Comment by stefanpenner** [comment]
> i don't know if its a proper fix, but adding router:main to the needs array on the test fixes it for me

nah, sometime else seems sideways.

**Comment by rwjblue** [comment]
Could someone make a demo repo that I can play with to see the error?

**Comment by johnotander** [comment]
I've been able to reproduce the error with the following repo: https://github.com/johnotander/ember-cli-error-repro-5227

The steps I took:

1. `ember g foobar`
* `ember g resource foo`
* Edited `bower.json` to specify the `ember@1.12.1` dependency
* `ember t`
* [error](https://github.com/johnotander/ember-cli-error-repro-5227/commit/bbcb4f340014e0447e6fecc94ea124eb32bbde5c)

**Comment by rwjblue** [comment]
@johnotander - Thank you, should make debugging a bit easier...

**Comment by systembugtj** [comment]
See the same issue with ember-cli 1.13.14 and emberjs 1.11.0. Need to have needs: ["router:main"] to allow unit test works. 

Also I notice when call route.send (any kind of route), it will throw exception 'undefined' is not an object (evaluating 'this.router.trigger').

Step into the exception, this.router is undefine. Not sure where the router suppose to be set.

**Comment by MiguelMadero** [comment]
@stefanpenner why was this closed? It seems like a version of CLI broke all of the controller and route tests in 1.12 and earlier. Was there a fix for this?

**Comment by gnanavelum** [comment]
is there a permanent solution to this, out of box?
