### ISSUE TITLE
[1.13.13] Test runner falls over with ember-cli > 1.13.8

### ISSUE THREAD

**Issue by mmelvin0** [ember-cli/ember-cli#5231]
I updated my app to ember-cli 1.13.13, and the test runner falls over. The app runs fine though.

App is built for dev with `ember build -w`, for test with `ember serve -e test -o dist` (we have different baseURL and output-path for dev and test).

```
Uncaught Error: Could not find module `undefined` imported from `(require)`
missingModule @ loader.js:135
findModule @ loader.js:150
requireModule @ loader.js:139
s @ _prelude.js:1(anonymous function)
@ qunit.js:12

Uncaught Error: Could not find module `ember-qunit` imported from `client/tests/test-helper`
missingModule @ loader.js:135
findModule @ loader.js:150
Module.reify @ loader.js:86
Module.build @ loader.js:104
findModule @ loader.js:152
requireModule @ loader.js:139
(anonymous function) @ tests-suffix.js:3

Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".
```

Note that despite the assertion, assets/tests.js definitely does load.

I have triple checked my application matches what is produced by `ember new` (and an empty app *does* work.)

If I revert to ember-cli 1.13.8 (leaving all other bower/json dependencies as updated for 1.13.13) tests run fine. 1.13.10, 1.13.11, and 1.13.12 all have the same problem.

Other (unsolved) instances of this:
* ember-cli/ember-cli#1353
* https://stackoverflow.com/questions/34258748

I will do more research on this as time allows.

**Comment by stefanpenner** [comment]
Can you provide a reproduction, otherwise I am unsure how to debug for you.

**Comment by mmelvin0** [comment]
Absolutely, as time allows. Just wanted to get what I know now written down.

Any idea what `s @ _prelude.js:1` is from the first trace?

**Comment by stefanpenner** [comment]
I don't believe that is part of our default setup, it does not look familiar.

**Comment by mmelvin0** [comment]
Ah, it's part of ember-browserify.

Is there an alternative to ember-browserify we should be using? We're importing three.js as `import THREE from 'npm:three'` in one of our components.

**Comment by stefanpenner** [comment]
> Is there an alternative to ember-browserify we should be using?

Nope, (we are using it here without an issue). I would recommend trying to cause the issue in an isolated app.

**Comment by brookjordan** [comment]
We had a similar issue recently. Downgrading ember-cli-qunit from `1.1.0`[`^1.0.4`] to `1.0.5` solved it.
Might be worth a look.

**Comment by stefanpenner** [comment]
> Might be worth a look.

I'll need a reproduction, as I am not able to replicate.

**Comment by stefanpenner** [comment]
Will gladly reopen if a reproduction is provided, I have been unable to reproduce the issue described.

**Comment by mmelvin0** [comment]
Still trying to provide a reproduction; I have a question in that regard: what's up with ember-resolver in 1.13.10? Starting from 1.13.8, I updated to 1.13.10 and did an ember init in my project, and it suggested:

1. I remove `ember-resolver` from bower.json entirely.
2. I change `import Resolver from 'ember/resolver'` to `import Resolver from 'ember-resolver'`.

Doing this caused ember serve to fail to build with:

```
Error: ENOENT, no such file or directory '/path/to/my/app/tmp/concat_with_maps-input_base_path-WVQDu7Lz.tmp/0/bower_components/ember-resolver/dist/modules/ember-resolver.js'
```

I'm curious where `ember-resolver` is supposed to go (bower.json, package.json, neither?) in v1.13.10 and what version (if any) I should be using.

**Comment by mmelvin0** [comment]
Also, I can confirm the otherwise reverting to ember-cli-qunit 1.0.4 works (changed package.json dependency from `^1.0.4` to `1.0.4`) has my app's tests running properly as before, per brookjordan's suggestion.

**Comment by mmelvin0** [comment]
Here's a reproduction: https://github.com/mmelvin0/simple-auth-browserify-test

The immediate issue is simplabs/ember-simple-auth#832, but with the project linked above, if you downgrade ember-cli-qunit from 1.1.0 (e.g. ^1.0.4 to 1.0.4) the problem also goes away. So there's something funky going on here, but at least I have it down to a simple reproduction now.

**Comment by oliverwilkie** [comment]
Maybe related to https://github.com/ember-cli/ember-cli-qunit/issues/95#issuecomment-164608357

**Comment by digitalsadhu** [comment]
Had same issue, reverting to ember-cli-qunit 1.0.4 worked for me. Thanks!

**Comment by lcpriest** [comment]
Thanks @brookjordan, that solved my issue too.
