### ISSUE TITLE
Generate adapter and HTTP mocks for JSON API by default

### ISSUE THREAD

**Issue by hlubek** [ember-cli/ember-cli#5234]
It would be nice if a new Ember CLI app would have support for JSON API by default (or generate an `application` adapter when the first model is generated).

It would be very helpful if the `http-mock` generator would support generation of a JSON API compatible mock that has valid responses for JSON API and can be extended with custom fixtures.

**Comment by abuiles** [comment]
@hlubek since JSONAPI is the default adapter there is no need to generate an application adapter with the first model.

Currently the adapter generator ships with RestAdapter but it will be fixed soon see https://github.com/ember-cli/ember-cli/issues/4787

> It would be very helpful if the http-mock generator would support generation of a JSON API compatible mock that has valid responses for JSON API and can be extended with custom fixtures.

maybe this is better fit as an addon?

**Comment by hlubek** [comment]
Well, true about the adapter part. But regarding the HTTP mocks, it would be just helpful if the response would be a valid JSON API document.
