### ISSUE TITLE
Silly behavior of ember cli on create in aspnet subdir

### ISSUE THREAD

**Issue by neilyoung** [ember-cli/ember-cli#5237]
$ ember -v
version: 1.13.13
node: 5.1.1
npm: 2.14.10
os: darwin x64

If I try to instantiate an ember project in a subdirectory of an apsnet5 project the ember directory appears in the directory above :)

**Comment by stefanpenner** [comment]
> If I try to instantiate an ember project in a subdirectory of an apsnet5 project the ember directory appears in the directory above :)

can you provide a detailed set of steps?

**Comment by neilyoung** [comment]
Yes. 

1) npm install yo -g  // yeoman, if not already installed
2) Add "generator-aspnet" to yeoman
3) yo aspnet
4) Let yeoman create a web application project
5) Change into subdir wwwroot in the newly created web application project
6) ember new ember-project

On my machine the folder ember-project is created not under wwwroot, but under the parent directory of wwwroot.

**Comment by Turbo87** [comment]
> is there a package.json in the ancestor directory (and what does it contain)?

The generator indeed seems to generate a `package.json` file. I think this is similar to #5493.

**Comment by Turbo87** [comment]
closing in favor of #5493
