### ISSUE TITLE
Remove `app-prefix` and `app-suffix`?

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5240]
`app-prefix` and `app-suffix` are a misfeature for a future modules-only version of Ember. Fortunately from what I can tell "nobody" is using these hooks:

https://github.com/search?l=JavaScript&q=app-prefix&type=Code
https://github.com/search?l=JavaScript&q=app-suffix&type=Code

(I've reviewed every single result page.)

I'd like to propose that we deprecate these prior to releasing 2.2 so that we don't have to support it until 3.0. If this is something we wish to do I'll pull together a PR today.

**Comment by stefanpenner** [comment]
I would also like this.

@rwjblue would love your thoughts and maybe an enumeration of usages we may be missing.

**Comment by nathanhammond** [comment]
I found one use case: https://github.com/jkarsrud/ember-cli-defeatureify/blob/master/index.js#L20

Neither of `app-prefix` or `app-suffix` is documented anywhere, so it isn't surprising that there is approximately no usage. I'd call them internal APIs.

I don't have a simple backwards-compatible way to accomplish ember-cli-defeatureify without `app-prefix` since any existing code will rely on globals set up in `app-prefix`. To fix this the ember-cli-defeatureify addon will need to generate a module which can be `require`d in anywhere that needs defeatureifying.

The migration path would be mechanical, adding `import 'ember-cli-defeatureify/config' as myNamespace;` to any module which uses it.

Still haven't found any usage of `app-suffix`. I'll submit a PR to ember-cli-defeatureify/broccoli-defeatureify/defeatureify as well if it means we can get this to land. :)

**Comment by rwjblue** [comment]
I'm :+1: on deprecating both in a 1.13 point release and in master, but I'm not convinced we should remove on master immediately after deprecating.

I want to avoid the self inflicted issues that we caused in Ember itself from 1.13 to 2.0, where we continued to backport deprecations for quite a while in the 2.0.0 cycle.  I would prefer to deprecate in both stable and master and target removal for a future version (prior to 3.0 though).  This is roughly similar to the Ember LTS concept (in my head at least :smile_cat:).

---

In the end, I believe deprecating has roughly the same effect as removal (deprecation noise is extremely annoying, and is mostly in the control of the app developer to remove) without the immediate breaking change before the deprecation can sink in and be dealt with in the ecosystem.

(moved comment from #5245)

**Comment by stefanpenner** [comment]
@rwjblue your recommendation is to also deprecate on master then remove before final 2.0 ?

**Comment by stefanpenner** [comment]
> In the end, I believe deprecating has roughly the same effect as removal (deprecation noise is extremely annoying, and is mostly in the control of the app developer to remove) without the immediate breaking change before the deprecation can sink in and be dealt with in the ecosystem.

We should be sure retaining this at all doesn't block any of @nathanhammond's work, if it doesn't then we should be ok.

**Comment by rwjblue** [comment]
@stefanpenner - Yes, I was thinking a release or two in 2.2.0-beta.* and 1.13.* with a deprecation before removal on master.

> We should be sure retaining this at all doesn't block any of @nathanhammond's work, if it doesn't then we should be ok.

Exactly. The issue is mostly that folks can use these hooks to return arbitrary JS, but if they are unused they are noops. I could be missing something important here, but it seems to me that the presence of the hook that is empty is not an urgent issue. Please help me understand if this is wrong though...

**Comment by nathanhammond** [comment]
> We should be sure retaining this at all doesn't block any of @nathanhammond's work, if it doesn't then we should be ok.
 
Retaining it won't block me, I'll just not support you if you use it to insert anything that isn't a module. It'll probably also break service worker builds in a spectacularly inconsistent manner, but that will likely be a different ember-cli release so we can remove them simultaneously with landing that work.

So, since it sounds like we're going to deprecate in both places, I'll open a third PR for that, and both of the deprecations can go ahead and land to start helping the community move (which I believe to be just ember-cli-defeatureify–which I'm taking on).

**Comment by stefanpenner** [comment]
> Retaining it won't block me, I'll just not support you if you use it to insert anything that isn't a module.

seems fine, and the better the warning/error the better

**Comment by rwjblue** [comment]
Thanks for tackling this Nathan!

**Comment by nathanhammond** [comment]
PRs #5245 and #5252 should be ready to merge once tests finish running. #5244 can remain open until we decide to merge it.

**Comment by rwjblue** [comment]
Since we are going to let the hooks with a deprecation simmer for a bit I closed #5244, which means I think this can be closed.

@nathanhammond - Can you confirm?

**Comment by nathanhammond** [comment]
Closing as resolved. We know we want to do this, have a path forward, and I can continue my work to modularize all the things. Will resubmit something like #5244 in the future.

**Comment by nathanhammond** [comment]
Letting this simmer still, but PR went out for the only known usage of `app-prefix` in the ecosystem:
https://github.com/jkarsrud/ember-cli-defeatureify/pull/16
