### ISSUE TITLE
Refactor `app-boot`?

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5242]
I'd like to propose rethinking the `app-boot` hook. Treating it as an appended section of imperative code inside of `app.js` makes it difficult to reason about in a modules-only world. We only have a few occurrences of this in our extended codebases (I audited every occurrence on GitHub), which imply that we can reduce the API surface area and accomplish the same underlying goal of triggering the initial `require` that unravels everything.

## Use cases:
* [ember-cli](https://github.com/ember-cli/ember-cli/blob/a2a9a886e146ce7bdfbdd5338542538ea7b38d14/lib/broccoli/ember-app.js#L1600) - Generates the initial require.
* [ember-cli-delay-app-boot](https://github.com/rwjblue/ember-cli-delay-app-boot/blob/master/index.js#L31) - Throws a timeout around the initial require and includes some copypasta from above.
* [ember-cli-fastboot](https://github.com/tildeio/ember-cli-fastboot/blob/2058dd1ebf08be818851d1e65651db49cdd0e69f/index.js#L73) - This adds a new specially-named module and doesn't call `require`. Instead, it itself becomes the module which must be required to boot the app.
- In the future (read: I'm already encountering this) a Service Worker may wish to tell the application when it should boot or bind that functionality onto a promise chain. My current approach is to delay responding to the app-boot request and maintain that promise chain inside of the service worker.

## Analysis & Proposal
It seems to me that the primary use case for `app-boot` is to tweak and modify how the initial `require` is called. None of these above use cases are dramatically different. I'd propose that we adopt the behavior of `fastboot` generically, creating a magic module that you can `require` and use to unravel the application. It covers all existing use cases, reduces copypasta, can move us toward reduced API surface area, and makes the `app-boot` hook much simpler: `require('ember-app')()`.

**Comment by rwjblue** [comment]
In general, we should use ember-cli/rfcs for this kind of proposal in the future.

---

Using a single module that can be required sounds nice generally speaking, but how does that work when you have two apps running at once?  Wouldn't they would both try to create the `ember-app` module and one would be unbootable?

**Comment by nathanhammond** [comment]
I didn't think of RFCs for this because I was aiming for a nearly transparent change. Will do next time. :)

***

Is "two apps running at once" one of our design goals? That already won't work in fastboot, doesn't work as the output of a single `ember build -prod`, and requires a postprocessing step. I agree that this change would make two simultaneous apps a bit more difficult to accomplish but already the person doing that is pretty advanced.

At the very least we should move the config module into a separate file from `app-boot`. That would make it a *lot* easier to override `app-boot` and makes one more module order independent. I'll open a PR for that.

**Comment by stefanpenner** [comment]
lets open this as an RFC. Because the format & line-comments are quite useful to asynchronously discuss this
