### ISSUE TITLE
Document supported node installation methods

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#5249]
Once in a while we get bug reports with permissions issues like in #2438. They are usually the product of an incorrect node installation. Sudo issues on Unix/Administrator issues on Windows. We usually say you shouldn't install with sudo, then close the issue.

I propose a section in the README for how you should have installed node. Maybe it will be useful for people that don't have node prior to starting an ember-cli project, and read the first (incorrect) guide on google. We can then point permission issues to the README and ask if they followed.

I suggest starting points be [nvm](https://github.com/creationix/nvm) on Unix and [Chocolatey](https://chocolatey.org/) for Windows. nvm doesn't require, but defaults to non-sudo in its instructions, and Chocolatey gives a big red warning if you aren't running as an Administrator, which is, contrary to Unix, good for node/symlinking.

Any thoughts, other installation suggestions, or not worth it?

**Comment by stefanpenner** [comment]
> I propose a section in the README

I think the website is likely the best bet, especially for newcommers.

**Comment by RyanNerd** [comment]
NPM should be renamed PITA. Got bit with this crap today. For speeds sake I ended up using the sudo work-around. But would have loved to know about this in advance.

**Comment by MarkMT** [comment]
Was anything done to address this issue? @kellyselden proposed updating the README and  @stefanpenner proposed updating the website. I see nothing in the README and the website says "follow the installation instructions on nodejs.org". When I check nodejs.org, I can find a binary for my platform (unix) but no explicit installation instructions. If I dig further in to https://github.com/nodejs/node/blob/master/BUILDING.md I finally find  `[sudo] make install`, which seems to leave room for the unwary to do it the wrong way.

If the goal is to point newcomers in the right direction, it seems more could be done here. I see [elsewhere](https://github.com/ember-cli/ember-cli/issues/2438) that @stefanpenner recommended nvm. Is that still the preferred approach? I'm one of those who got tripped up by an old installation that had been done using [someone else's](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories) instructions.

**Comment by MarkMT** [comment]
Incidentally, I did just find installation [instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) for my platform on nodejs.org and they are essentially the same as the ones I followed last year using sudo:
```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by kellyselden** [comment]
I don't know if anything was done yet. I've now heard that `nvm` and `brew install node` have given people success, and there's this thing called `n` that is similar but I haven't researched. @locks you might want this on your radar.

**Comment by nathanhammond** [comment]
I use `nvm` FWIW. `brew` used to have issues with getting upgrades right and because I need to consistently switch versions to test having a single "system" `node` isn't very useful to me.

**Comment by MarkMT** [comment]
Thanks. nvm seems to be working for me.

**Comment by RyanNerd** [comment]
`nvm` via `brew` is great for Mac users, but due to a [stupid yet necessary decision](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907) debian based Linux users are in for a painful treat with node.

**Comment by MarkMT** [comment]
Painful reading though I can't say I fully understand all of the implications. I'm on Mint and am not seeing any problems so far.

Be that as it may, IMO this issue needs resolution and believe the [user guide](https://ember-cli.com/user-guide/#getting-started) on the ember-cli website is the right place. I'm not a node, OS X or Windows expert but suggest something like this:

> First, install the latest version of Node.
> 
> Node is available for a variety of platforms at [nodejs.org](http://nodejs.org/). It is important that you _not_ install Node with `sudo` in order to avoid permission problems with some ember-cli commands. On Unix, [nvm](https://github.com/creationix/nvm) provides a convenient way to do this. On OS X, you can also [use Homebrew](https://changelog.com/posts/install-node-js-with-homebrew-on-os-x). On Windows, [chocolatey](https://chocolatey.org/packages/nodejs) is an option.

Comments?
