### ISSUE TITLE
[Addons][Bug] Addon entry file (index.js) is not run through JSHint

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/ember-cli#5253]
Steps to reproduce:

1. Create an addon
2. Add `var path = require('path');` to addon entry point
3. Run `ember test`
4. Witness tests passing

I would think this would be caught by the `unused` flag in `.jshintrc`, but I don't see `index.js` being run through JSHint.

**Comment by gmurphey** [comment]
Pretty sure I found a way to get this working with minimal side effects. I'll put together a PR this weekend.

**Comment by stefanpenner** [comment]
This is fine to submit an enhancement for, but i wouldn't consider this a bug. The client-side hinting and serverside hinting are currently disjoint.
