### ISSUE TITLE
'ember destroy' should remove empty directories

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#5268]
When using `ember destroy` empty "left over" directories should be removed as well. Currently, generating a quick test component like `x-foo` and deleting it again leaves me with a few empty directories.

```
[jan@arch community-app]$ ember g component x-foo
version: 2.2.0-beta.1
installing component
  create app/components/x-foo/component.js
  create app/components/x-foo/template.hbs
installing component-test
  create tests/integration/components/x-foo/component-test.js

[jan@arch community-app]$ ember d component x-foo
version: 2.2.0-beta.1
uninstalling component
  remove app/components/x-foo/component.js
  remove app/components/x-foo/template.hbs
uninstalling component-test
  remove tests/integration/components/x-foo/component-test.js
```

I'd expect `app/components/x-foo/` and `tests/integration/components/x-foo/` to get removed aswell, however I have to remove them manually. 
This isn't really a big deal, especially since Git ignores empty directories, but it still nags me.

ember-cli should attempt to remove these directories, but only if they are empty (!) after all auto-generated files were deleted.

If you consent, I'll fix up a PR.

Merry christmas! :christmas_tree:

**Comment by kellyselden** [comment]
I think this came up before, and it just needed someone to do it. So I'm :+1: on a PR!

**Comment by rwjblue** [comment]
Ya, agreed. Needs someone to work on it, but definitely a needed change.

**Comment by buschtoens** [comment]
Great! I'll try to make a PR including tests in the next days. :)

**Comment by stefanpenner** [comment]
This should be opened as an rfc please, issue tracker isnt for feature requests
