### ISSUE TITLE
ember-build stuck on Travis-CI

### ISSUE THREAD

**Issue by bcecchinato** [ember-cli/ember-cli#5281]
Hi there !

I'm seeking for help on my build on Travis-CI. I've been unabled to build my webapp with the following versions : 
- 0.2.7
- 1.13.13
- 2.2.0-beta2

When Travis starts the command `ember build -prod`, it gets stucks indefinitly.
An example of the build is here https://travis-ci.org/bcecchinato/spring-identity/builds/99155296
The repository of my webapp is there https://github.com/bcecchinato/spring-identity (on branch data-rest).

I've tried some different versions of node/npm and ember-cli, resulting in the same stucked build.

Any help would be appreciated.
Regards,

**Comment by stefanpenner** [comment]
Sounds like you are trying to uglify a very large file. The website contains docs on how to exclude such files

**Comment by bcecchinato** [comment]
Thanks for this short reply. I tried to deactivate uglify using:
```
minifyJS: {
      enabled: false
    },
```

But the build is still stuck. Is there a way to make the build in debug mode ? I've not found on the doc if there's a -d switch or alike that will verbose more than the "Building" output.

Regards,

**Comment by bcecchinato** [comment]
I'm running using DEBUG=*, it seems that intl is really slow (ie https://api.travis-ci.org/jobs/99220216/log.txt?deansi=true).
On #4004, it seems it was already the case. I'll dig into it.

**Comment by bcecchinato** [comment]
Forcing intl in configuration did the work : 
```js
// config/environment.js
intl: {
  locales: ['en-us', 'en-gb', 'fr-fr']
}
```
