### ISSUE TITLE
Deprecation warning Future versions of Ember CLI will not support v5.3.0. Please update to Node 0.12 or io.js.

### ISSUE THREAD

**Issue by amrdraz** [ember-cli/ember-cli#5282]
I don't think I should get a deprecation warning for a higher version... should I?
I understood when my Node version was less than 0.12 but 5.3 contains 4.0 
I take it something is off in the version detection

**Comment by stefanpenner** [comment]
This should have been fixed some time ago. I suspect you are using an old version.

Will reopen if latest/master demonstrates this issue

**Comment by amrdraz** [comment]
but I had just npm installed the yesturday?
ember-v syas 
version: 1.13.13
node: 5.3.0
npm: 2.14.10
os: darwin x64

do you mean I should use the latest/master which

**Comment by iijan** [comment]
having the same issue here,. did you get to bottom of this issue?

**Comment by amrdraz** [comment]
I had the latest build from npm, I assume that perhaps the last build on
npm does not include the fix mentioned above.

Accordingly I'll just wait and see with the next update, since I don't want
to get latest and this isn't really a critical issue.
I decided that if the issue persists with the next version then I'll
revisit this issue and report.

*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)

**Comment by kamizen** [comment]
I also ran an "ember test" and seem to get a complete pass:

1..897
# tests 897
# pass  897
# fail  0
