### ISSUE TITLE
Proxying https localhost

### ISSUE THREAD

**Issue by sunliil** [ember-cli/ember-cli#5283]
Hi all. We have asp.net webapi project with authorization through Identity Server(it works only with https). So we have to run local instances on https://localhost:* with self signed sertificates. Both local identity server and web app work as it should. But when we trying to run ember application proxying webAPI's localhost instance there is Error: unable to verify the first certificate. I think that untrusted self signed sertificate cause this error but not sure.

 ```
ember server --proxy https://localhost:44305

version: 2.2.0-beta.1
Proxying to https://localhost:44305
Livereload server on http://localhost:49156
Serving on http://localhost:8081/

Build successful - 4482ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor                | 2755ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
ConcatWithMaps: Concat: Vendor (1)            | 2755ms
Babel (11)                                    | 305ms (27 ms)

Error proxying to https://localhost:44305
unable to verify the first certificate
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

Tried to find solution for it but without success.

**Comment by stefanpenner** [comment]
I believe you have two choices: 

* start mode with ssl verification disabled
* add your cert to your system keychain (or equivalent on your os)

**Comment by sunliil** [comment]
Thanks, first method worked for me. Found `--insecure-proxy` option in ember-cli help and it is exactely what I need. 

Added `--insecure-proxy` option to `ember server`.

**Comment by lifeart** [comment]
Now this option has different name - `--secure-proxy`
