### ISSUE TITLE
Any plans to use webpack?

### ISSUE THREAD

**Issue by victorwpbastos** [ember-cli/ember-cli#5284]
In my tests webpack is so much fast than broccoli.

**Comment by stefanpenner** [comment]
Unlikley, but can you share your tests?

**Comment by listepo** [comment]
https://github.com/nolanlawson/rollup-comparison

**Comment by stefanpenner** [comment]
@listepo this doesn't have a broccoli along-side it.

**Comment by stefanpenner** [comment]
This change is of dubious value, considering the cost. If someone is serious they must actually provide thorough benchmarks. Even if some difference exists, the cost benefit is favor of continued improvements to broccoli
