### ISSUE TITLE
[2.2.0-beta.2] Error: Callback was already called.

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli#5288]
This happens during `ember test`, but not `ember test --server`.

```
/Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/node_modules/async/lib/async.js:43:36
    at ChildProcess.<anonymous> (/Users/mliu/Workspace/awesome-app/node_modules/ember-cli/node_modules/testem/lib/launcher.js:200:9)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by rwjblue** [comment]
I believe this is an issue from the Testem upgrade that we did in ember-cli@2.2.0-beta.2.  

@johanneswuerbach - Have a minute to take a look?

**Comment by johanneswuerbach** [comment]
Sure, should have time later today.

**Comment by johanneswuerbach** [comment]
@ming-codes could you provide your `testem.json` and your testem version (`npm ls --depth 1 | grep testem`)? This would definitely help investigating your issue.

**Comment by ming-codes** [comment]
Here it is.

```
> cat testem.json
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [ "PhantomJS" ],
  "launch_in_dev": [ "Chrome" ]
}
```

```
> npm ls --depth 1 | grep testem
│ ├── testem@1.0.0-rc.3
```

**Comment by mikegrassotti** [comment]
I ran into the same error after upgrading to 2.2.0-beta.2. In my case `ember test` passed locally but failed with `Callback was already called` when running tests on our CI server. The only difference I could find between environments was that codeship is still on 1.9.7 while i was using phantom 2 in development. [upgrading to phantomjs 2](https://gist.github.com/mlocher/f0f731dfa93c82d0fa86) solved the problem for me. Obviously would be nice if `ember test` worked on older versions of phantom but meantime upgrading to v2 is a good workaround.

**Comment by gleseur** [comment]
Ran into the same issue after upgrading. I confirm the phantomjs2 upgrade solved the issue for me as well.

**Comment by johanneswuerbach** [comment]
I'm having a hard time reproducing this issue, if anyone could provide an app to reproduce it would be appreciated.

**Comment by johanneswuerbach** [comment]
I may have found the issue, could somebody verify?

In your project:
```
cd node_modules/ember-cli
npm install johanneswuerbach/testem#callback-already-called --save
```

**Comment by gleseur** [comment]
@johanneswuerbach  I confirm this fixes the issue for me

**Comment by johanneswuerbach** [comment]
Great, I'll cut a new rc tmrw then.

**Comment by mikegrassotti** [comment]
@johanneswuerbach worked for me as well

**Comment by rwjblue** [comment]
Thanks @johanneswuerbach

**Comment by ming-codes** [comment]
@johanneswuerbach Yup, it's fixed in that branch.

**Comment by johanneswuerbach** [comment]
The issue should be resolved in `testem@1.0.0-rc.4`. You can get that new version by running `rm -rf node_modules/ && npm install`.

**Comment by stefanpenner** [comment]
We will need to bump ember-cli dep and cut a new cli

**Comment by rwjblue** [comment]
@stefanpenner - Will do now.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/5298
