### ISSUE TITLE
[Question] ember generate blueprint <blueprint-name> --in-repo-addon <in-repo-addon-name> generated file not in lib/<in-repo-addon-name>?

### ISSUE THREAD

**Issue by AlexanderChen1989** [ember-cli/ember-cli#5289]

**Comment by stefanpenner** [comment]
As per https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#questions questions are to be asked on StackOverflow tagged as ember-cli.

If their is a bug here, please follow the steps in `CONTRIBUTING.md` to report it.

**Comment by AlexanderChen1989** [comment]
Thanks for you reply, I asked a question on stackoverflow.
