### ISSUE TITLE
Tests are not auto run after changes (2.0.0-beta.2)

### ISSUE THREAD

**Issue by andrewtimberlake** [ember-cli/ember-cli#5290]
I have created a repo which reproduces the steps (https://github.com/andrewtimberlake/ember-test-autorun).
Each commit outlines the steps from a 1.13.13 build of a new app, through upgrade to 2.0.0-beta.2

Steps to reproduce the problem:
- Initial Commit from Ember CLI v1.13.13
- Added basic helper - tests autoran
- Update ember-cli (delete node_models and bower_components; then npm i && bower i)
- Restart `ember t -s`
- change and save test file, the tests are rebuilt but tests don't run

**Comment by rwjblue** [comment]
Thanks for reporting! I will try to step through the demo repo tonight to track down what is going on (unless someone else gets to it first).

**Comment by johanneswuerbach** [comment]
Looks related to the testem bump, added to my todo list.

**Comment by andrewtimberlake** [comment]
Thanks very much

**Comment by johanneswuerbach** [comment]
The issue should be resolved in `testem@1.0.0-rc.4`. You can get that new version by running `rm -rf node_modules/ && npm install`.

**Comment by andrewtimberlake** [comment]
Thank you, works great :clap:
