### ISSUE TITLE
Not serving files in root

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-cli#5292]
I have an addon which is working with service workers and as a result I need to place some JS files into the root of the build directory (so that they have the scope to offline proxy the `index.html` file amongst others). 

I am able to achieve this by hooking into `postBuild`:

    const JS_FILES = ['upup.min.js', 'upup.sw.min.js'];
    postBuild: function() {
      const source = path.join(__dirname, 'bower_components', 'upup/dist');
      const destination = path.join(__dirname, '/dist');
      JS_FILES.map(file => {
        fs.copy(path.join(source, file), path.join(destination, file), err => {
          if(err) {
            console.error(err);
          }
        });
      });
    },

This is successful in the sense that the two JS files which i need to placed into the root of the distribution are placed there but when I serve the built application it apparently is not serving these files as I get 404 errors on both. 

With the "rise of the service worker" I suspect this may be a growing use-case ... is there a way to do this in a more ember-cli compliant way? I had originally hoped to hook into the `treeForApp` hook but couldn't get that working so resorted to the above approach.

**Comment by stefanpenner** [comment]
As per the contributing.md, questions are to be asked on stackoverflow.

There is work being done to improve sw support out of the box

**Comment by ksnyde** [comment]
Sorry didn't know that. I did actually post on SO a week ago or so but haven't had any response.

http://stackoverflow.com/questions/34471975/ember-addon-to-add-files-to-root-directory?noredirect=1#comment56699198_34471975

If you like I'll close this.

**Comment by stefanpenner** [comment]
a hint, `dist` is only for users to look at/deploy do to the fact that indivudals may run concurrent builds the assets are served from the given builds tmp directory output.

**Comment by rwjblue** [comment]
This is likely better handled via a custom treeForPublic (then the normal build process is taking care of the correct output directory AND the files don't get copied around for every rebuild).

**Comment by ksnyde** [comment]
Thanks Robert. My initial attempt was to use `treeForApp` but I think I boshed something up (no errors but no results). I'll give that approach another try.
