### ISSUE TITLE
How to use http-proxy blueprint instead of default proxy

### ISSUE THREAD

**Issue by ryudice** [ember-cli/ember-cli#5296]
Sorry for posting this here but there is very little documentation (if any) about this blueprint. I want to replace the default proxy with the one generated by the blueprint, every time I run ember server it ignores the module generated by the blueprint and keeps running it's own integrated proxy server.

After I ran the generator I got the following output: 
![image](https://cloud.githubusercontent.com/assets/125211/12069061/50e7f336-afe3-11e5-975e-06cb242d8107.png)

Am I missing something here?

Any help would be appreciated.

**Comment by stefanpenner** [comment]
This is known to work, please provide a reproduction so we can see whats different about your setup

**Comment by ryudice** [comment]
Thanks for your reply, I got it working, there was not issue with the blueprint, I thought it would pickup the proxy set in .ember-cli.
