### ISSUE TITLE
Testing Ember.js strange errors

### ISSUE THREAD

**Issue by koemeet** [ember-cli/ember-cli#530]
Hi,

I'm trying to my tests working with ember-cli, but I get nothing but strange errors. I've got this in /tests/controllers/workspaces:

``` js
import startApp from '../helpers/start-app';

var App;
module("Acceptance - Workspaces", {
    setup: function() {
        App = startApp();
    },
    teardown: function() {
        Ember.run(App, 'destroy');
    }
});

test('selecting a workspace updates prop selectedWorkspace', function() {
    equal(1, 3);

    // This triggers the error, I do not know why. When I leave this out, the test is running fine.
    visit('/workspaces');
    andThen(function() {
        equal(find(ul).length, 3, 'The ul should have 3 stuks.');
    });
});
```

This is the error that I receive when I use helpers like visit etc. 

`Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.`

Full error screenshot: http://puu.sh/8tf2r.png

Anybody knows what I am doing wrong?

**Comment by atomkirk** [comment]
Ok, so the cause of this is setting the rootElement to different selectors in different environments. For example:

```
    if (environment === 'development' || environment === 'vagrant') {
        ENV.APP.rootElement = "#deployment-application";
    }

    if (environment === 'test') {
        ENV.APP.rootElement = '#ember-testing';
    }

    if (environment === 'production') {
        ENV.APP.rootElement = "#deployment-application";
    }
```

This will cause the error: `Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.`

This seems like a bug to me. If I run `ember server -e test` then it works, but it doesn't seem like I should have to do that to have different root elements for test and dev/prod.

**Comment by atomkirk** [comment]
@stefanpenner this is a real pain point for me. Can you comment?

**Comment by stefanpenner** [comment]
@atomkirk does that element exist in both `app/index.html` and `tests/index.html` ?

**Comment by atomkirk** [comment]
Yup, herego: http://d.pr/f/1gB2U/4Papqiqa

Relevant code:
![](http://d.pr/i/Fb4k/1ZgAXg9N+)
![](http://d.pr/i/12Gjl/18cNyNVk+)

`ember server`

http://localhost:4200/tests
![](http://d.pr/i/1dMfZ/4LSQMzZO+)

**Comment by atomkirk** [comment]
If you comment out `ENV.APP.rootElement` then tests run fine, but then then visiting `http://localhost:4200/` would break on an app that depends on the app being rendered into `#non-test-app`

**Comment by rwjblue** [comment]
Please provide a repo that demonstrates the issue.

**Comment by atomkirk** [comment]
This is a zip file of a project: http://d.pr/f/1gB2U/4Papqiqa

Is there some reason it must be a repo?

**Comment by stefanpenner** [comment]
> Is there some reason it must be a repo?

just a suggestion, im downloading the zip file now.
