### ISSUE TITLE
[2.2.0-beta.3] Error: Callback was already called.

### ISSUE THREAD

**Issue by backspace** [ember-cli/ember-cli#5300]
This is the same as [this issue](https://github.com/ember-cli/ember-cli/issues/5288), which I believe was supposed to be fixed with `2.2.0-beta.3`, but isn’t for me. It’s happening to me both locally and [on Travis CI](https://travis-ci.org/backspace/adventure-gathering/builds/100017747). I checked in `node_modules/testem/package.json` and the version is indeed `1.0.0-rc.4`.

As in the linked issue, the tests all pass, but `ember test` fails like this:

```
/Users/b/Documents/Events/cr2016/adventure-gathering/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
  at /Users/b/Documents/Events/cr2016/adventure-gathering/node_modules/async/lib/async.js:43:36
  at ChildProcess.<anonymous> (/Users/b/Documents/Events/cr2016/adventure-gathering/node_modules/testem/lib/launcher.js:195:9)
  at ChildProcess.g (events.js:260:16)
  at emitTwo (events.js:92:20)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:818:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)
```

The repository is open source, you can see it [here](https://github.com/backspace/adventure-gathering).

**Comment by stefanpenner** [comment]
@backspace which version of tested is installed?

**Comment by backspace** [comment]
Assuming you mean `testem`:

```
cat node_modules/testem/package.json | grep version
  "version": "1.0.0-rc.4"
```

Also:

```
./node_modules/.bin/testem --version
1.0.0-rc.4
```

**Comment by stefanpenner** [comment]
I guess I got autocompleted

**Comment by stefanpenner** [comment]
We will need to investigate

**Comment by stefanpenner** [comment]
Can you provide an isolated reproduction.

**Comment by backspace** [comment]
hmm, I just tried `ember new` and I didn’t get the error with `ember test`. I added each dependency in `package.json`, one at a time, with `bower.json` additions as necessary, and with each, `ember test` did not produce the error. Now they `package.json` and `bower.json` files in the projects are the same and the error is not present in the new project.

However, if I run these commands in a fresh directory, I get the error:
```
git clone https://github.com/backspace/adventure-gathering.git
cd adventure-gathering
npm install
bower install
```

I can’t think of anything to produce a minimal example other than the addons, but if you or anyone has any suggestions, let me know!

**Comment by johanneswuerbach** [comment]
I can finally reproduce this now :tada: Looking into it.

**Comment by stefanpenner** [comment]
@johanneswuerbach awesome thanks :)

**Comment by johanneswuerbach** [comment]
Fixed and resolved in `testem@1.0.0-rc.6`. You can get that new version by running `rm -rf node_modules/ && npm install`.

**Comment by backspace** [comment]
Thank you! Does the dependency need to be updated in `ember-cli` then?

**Comment by johanneswuerbach** [comment]
No reinstalling your local project modules (a maybe nuking the ci cache) is enough as the new rc is in the allowed ember-cli semver range.

**Comment by backspace** [comment]
Clearing the cache on Travis did fix it, thanks!
