### ISSUE TITLE
High build times on ambitious projects

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#5301]
A couple of my peers working on ambitious ember apps have complained to me that ember-cli build (and re-build) times were too high and impacting their efficiency.

Probably because my dev machine is a beast I've never experienced these issues and always dismissed their comments... until now. I've just dropped my laptop for repair. In the mean time I'm having to use my girlfriend MacBook Pro:

```
OS X Yosemite 10.10.1
2.26 Ghz Intel Core 2 Duo
8 Go 1067 MHz DDR3
```

The build times are quite high and sometimes it feels to me I'm building Objective C code on XCode.

```
Slowest Trees                                 | Total               
----------------------------------------------+---------------------
ConcatWithMaps                                | 10337ms             
Babel                                         | 8047ms              
JSHint app- QUnit                             | 7018ms              
Babel                                         | 6536ms              
ES6: App Tree                                 | 6052ms              
JSHint tests- QUnit                           | 5427ms              
Babel                                         | 5322ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (15)                                    | 34416ms (2294 ms)   
ConcatWithMaps (4)                            | 11649ms (2912 ms)   
 (2)                                          | 7413ms (3706 ms)    
JSHint app- QUnit (1)                         | 7018ms              
ES6: App Tree (1)                             | 6052ms              
JSHint tests- QUnit (1)                       | 5427ms 
```

Considering `ember.js` is the de-facto JS framework for ambitious web apps. I think something should be done to reduce the build times on lower spec machine.

**Comment by rwjblue** [comment]
This isn't really enough information to go on.  We would need more info to be able to help.

For example:

* `ember version` output
* `node --version` output
* `npm --version` output
* What are initial cold boot build times?
* What are initial warm boot build times?
* What are rebuild times after a JS file change?
* How many files exist in `app/`?

**Comment by olivierlesnicki** [comment]
@rwjblue 

`ember version` `1.13.8`
`node version` `v4.2.4`
`npm version` `2.14.12` 

Please note, I'm just listing here the build times being output by the `ember serve` command - which doesn't include the times it takes to run `npm install` nor `bower install`.

Cold boot build time `98,182ms`
Warm boot build times `+/-33,000ms`
Rebuild times `+/-12,000ms` (one character change)
336 files exist in `app/`

**Comment by rwjblue** [comment]
> ember version 1.13.8

There is roughly nothing we can do to make this faster. A very large amount of work has been put in to make the builds faster, but using an older ember-cli prevents you from seeing any fruits of that labor. Please update to latest (preferably to 2.2.0-beta.3).

**Comment by kellyselden** [comment]
@olivierlesnicki There was massive performance work done in 1.13.13. That may your first step.

**Comment by olivierlesnicki** [comment]
Let me first try 1.13.13. I will re-rerun the commands and post the results.

**Comment by stefanpenner** [comment]
Please be sure to read the WIP performance guide: https://github.com/ember-cli/ember-cli/pull/5096/files
