### ISSUE TITLE
Ember destroy mistakely removes similarly named nested route

### ISSUE THREAD

**Issue by alexmasita** [ember-cli/ember-cli#5303]
I created a route through the following ember-cli generate command: "ember g route offers".  All the files were created and router updated successfully.  I decided to have the "offers" route nested in a new "master" route.  So, I created a "master" route, then I created the "master.offers" route via the generator and I verified the navigation worked fine. 

When I now removed the "offers" route through "ember d route offers", it actually correctly removed all the related files but wrongly updated the router.  In the router, it actually removed the nested "master.offers" route and left the "offers" route.  I had to manually copy the "offers" route and nest it inside the "master" route for the navigation to "master.offers" to work.

Hope this can be resolved.

**Comment by stefanpenner** [comment]
cc @abuiles

**Comment by stefanpenner** [comment]
@alexmasita can you be sure to follow the steps [here](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md)  Which now also request, other tidbits.

**Comment by alexmasita** [comment]
Thank you for the acknowledgment.  I have followed the steps on the link provided and here below are the details:

1.  I was actually working from the most recent master release 
2.  Here below environment details
ember cli version: "2.2.0-beta.2"
ember-data: "^2.2.1"
ember: "2.2.0"
node: "0.12.7"
npm: "2.14.10"
os: "darwin x64 El Capitan"

I believe the steps I provided on opening the issue are clear.  If not, please let me know.

**Comment by srvance** [comment]
I've run into this twice recently. The cleanest recipe was
1. `ember g route index /`
1. `ember g route user`
1. `ember g route index/user`
1. `ember destroy route user`

Another recipe is, given a nested route structure under `index`

1. `ember g route index/index`
1. `ember destroy route index/index`

The result is it destroys everything under your `index` route.

**Comment by nathanhammond** [comment]
This is definitely an issue, in ember-router-generator. Not high priority for us to fix, but happy to help guide somebody through a fix.

**Comment by srvance** [comment]
@nathanhammond I'd be interested in taking it on. I'll ping you on Slack after I've looked things over.

**Comment by srvance** [comment]
@nathanhammond I think I have a handle on it. I'm going to open a PR on ember-router-generator with my initial failing test and have any follow on discussion there.

**Comment by nathanhammond** [comment]
@srvance addressed this in https://github.com/ember-cli/ember-router-generator/issues/36. Thanks!
