### ISSUE TITLE
ember --test needs a flag to tell it to only output test reports or to write to file

### ISSUE THREAD

**Issue by ohcibi** [ember-cli/ember-cli#5307]
I'd like to parse my test result from my CI and it needs output like with the `xunit` reporter for that. The problem is, when running `ember test` it has additional output like the current version of ember, warnings or any output from other plugins. This makes it impossible to parse the raw output as xml. We need some way to separate the test output from ember-cli's output.

**Comment by gmurphey** [comment]
You should be able to run `ember test --silent -r xunit`. This has worked well for me with our CI.

**Comment by stefanpenner** [comment]
If the provided does not suffice, please be sure to provide a more detailed follow up that includes a reproduction of the issue.  We can then reopen. I believe the comment should work, unless you have some misbehaving dependency. So without a reproduction it is unlikely for us to be able to help.

**Comment by ohcibi** [comment]
@stefanpenner I created an example that uses ember-cli-coffeescript which has some output of the coffeelinter if enabled. It is at http://github.com/ohcibi/ember-test-output-showcase.git

Steps to reproduce:

* Create new project with latest ember-cli
* Add ember-cli-coffeescript
* Add a `coffeelint.json` file to enable the coffeelinter
* Run `ember test --silent`

The output now includes something like

```
=======================================================
Linting completed on 0 files with  0  errors.
=======================================================
```

or all the linter-issues if there are any.

**Comment by gmurphey** [comment]
The `ember-cli-coffeescript` addon isn't obeying the `--silent` flag. https://github.com/kimroen/ember-cli-coffeescript/blob/master/lib/coffee-linter.js#L23

I found this issue on that addon. https://github.com/kimroen/ember-cli-coffeescript/issues/52

**Comment by ohcibi** [comment]
@gmurphey Yes I have expected something like that. Thats why I added my last paragraph.

However there is a way to circumvent this by using `xunit_intermediate_output: true` and `report_file` in `testem.json` which I'll PR to the website, when I have the time. Maybe this should simply be the proper/recommended way to generate ci-friendly test results as it feels more clean anyways.
