### ISSUE TITLE
Testem freezes with 'waiting for runners'

### ISSUE THREAD

**Issue by musaffa** [ember-cli/ember-cli#5311]
If I create a vanilla ember app with `ember new` and then run `ember test --sever`, testem runs fine with phantomjs and chrome. Then I generate a component, say with `ember g component foo-bar`, testem updates with the new test. Now if I edit `foo-bar-test.js` and save, phantomjs disappears from testem suite and only chrome remains. After a couple of edit and save, testem shows a 'waiting for runners' message in the console and doesn't respond to any change.

I'm using ember-cli 1.13.13. And the same problem occurs in version 1.13.12.

**Comment by stefanpenner** [comment]
can you commit the offending app to GH and share the link, will make it easier to debug.
I use testem for TDD in this setup all the time without issue.

**Comment by musaffa** [comment]
@stefanpenner Here is the [link](https://github.com/musaffa/qunit-testem) to the app.

**Comment by musaffa** [comment]
When it fails for chrome/firefox browser, it outputs `Not found: /8360/tests/index.html?hidepassed` in the browser where 8360 is a random number. It looks like refresh is sometimes triggered before the updated index.html buffer is flashed in disk.

**Comment by stefanpenner** [comment]
just a headsup @johanneswuerbach (i'll try to look into this more over the next few days, but maybe something comes to mind)

**Comment by musaffa** [comment]
@stefanpenner this [block](https://github.com/ember-cli/ember-cli/blob/9205e1418618f8abf9eac4c34556d0e17ef44636/lib/tasks/test-server.js#L39) is the source of the race condition. If `testem.restart()` is placed in a setTimeout delay, the problem disappears. The race is between `broccoli` rebuild process and `testem` restart. Both of the processes watch for the file changes. Sometimes `testem` completes restart before `broccoli` could end the rebuild process. When this happens the browser generates 404 error message for the missing `/[random_number]/tests/index.html`.

Instead of watching for file changes, `testem` should watch for new broccoli build or something like that.

**Comment by stefanpenner** [comment]
> Both of the processes watch for the file changes. Sometimes testem completes restart before broccoli could end the rebuild process. When this happens the browser generates 404 error message for the missing /[random_number]/tests/index.html.

this seems wrong, in out case testem is not a seperate process, and should not be watching files.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/testem.json#L4

**Comment by stefanpenner** [comment]
maybe we should actually add that value [here](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/test.js#L38) so users with missing keys don't have this issue.

**Comment by musaffa** [comment]
I tried with `"disable_watching": true`, but it doesn't solve the problem.

**Comment by stefanpenner** [comment]
> Both of the processes watch for the file changes.

then this statement is likely wrong.

**Comment by stefanpenner** [comment]
But this is likely the source of the race, as it is attaching itself to the watcher, not the builder. Instead it should invoke after the build completes not the watch starts.

**Comment by stefanpenner** [comment]
actually that doesn't seem right either, as the watcher is what triggeres the build, and `change` is triggered after the build https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L77

**Comment by stefanpenner** [comment]
1. FS change happens
2.  detect it: https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L112-L115
3. schedule + debounce the build https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L28-L53
4. build https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L43
5. call the builder: https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L74-L75
6. builder triggers watcher change: https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L77
7. invoke testem https://github.com/ember-cli/ember-cli/blob/9205e1418618f8abf9eac4c34556d0e17ef44636/lib/tasks/test-server.js#L40-L47

**Comment by musaffa** [comment]
It looks like my assumption was wrong. Now I wonder how a delay in `testem` restart solves the problem for all browsers including phantomjs.

**Comment by stefanpenner** [comment]
> Now I wonder how a delay in testem restart solves the problem for all browsers including phantomjs.

Ya, I am also curious. I hope my above code-path helps shed extra light (you may want to double check it, incase I missed a step)

**Comment by musaffa** [comment]
I will try to dig further. Race condition is quite hard to find.

**Comment by musaffa** [comment]
@stefanpenner After debugging `broccoli-sane-watcher`, I've finally solved the problem. It was a `vim` issue. On saving the edits, vim generates intermediate backup files which trigger delete/add/change events. These events may not be triggered within the debounce time set in the watcher's scheduleBuilder. If this happens, then more than one build events are issued and `testem` catches multiple events instead of one.

One way to solve this is to increase the debounce time. It has to be as minimum as possible but it's hard to get it right. Simple solution for my case is to set this in the `~/.vimrc`:

```vim
set nowritebackup   # prevents creation of backup files while editing
```

Thanks for your valuable inputs.
