### ISSUE TITLE
Unknown blueprint: vendor-shim

### ISSUE THREAD

**Issue by tsteuwer** [ember-cli/ember-cli#5314]
After looking at how I can easily make a non-AMD/CommonJS module importable, I found the following documentation on ember-cli.com:

[Ember CLI:Managing Dependencies - Standard non-AMD assets](http://ember-cli.com/managing-dependencies/#standard-non-amd-asset):
```
ember generate vendor-shim module-name-here
```

However, when doing this, I get:

```
app$ ember g vendor-shim --dry-run
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Unknown blueprint: vendor-shim
```

After some searching, I found #4888, which was approved and merged but never actually closed. Is this feature not implemented but documented on ember-cli.com by accident?

**Comment by kellyselden** [comment]
You are on an older version. Works for me on 1.13.13.
