### ISSUE TITLE
jQuery 1.12 dropped and brand new ember projects do not work

### ISSUE THREAD

**Issue by ryanhollister** [ember-cli/ember-cli#5316]
Need to pin ember-cli projects to jQuery 1.11 until https://github.com/emberjs/ember.js/pull/12787 is resolved.

**Comment by mayatron** [comment]
Same issue. Pinning jQuery to 1.11 works.

**Comment by stefanpenner** [comment]
potential jQuery bug?

**Comment by ryanhollister** [comment]
no just a regular expression.

https://github.com/emberjs/ember.js/commit/bdd7784f74b9ff4ccffdfbd34176da0a8833e077

**Comment by rwjblue** [comment]
@stefanpenner - No, it is due to our setup. Ember throws an error on 1.12 of jQuery (see recent PR in Ember for a fix), but we permissively pin (in bower.json for apps/addons) in a way that allows 1.12 to be used.

Repro steps:

    ember new foo
    ember s
    open http://localhost:4200

Look at jQuery version assertion in browser console.

**Comment by stefanpenner** [comment]
> Ember throws an error on 1.12 of jQuery (see recent PR in Ember for a fix),

ah, ya.

**Comment by stefanpenner** [comment]
> no just a regular expression.

now we have two problems

**Comment by mike-north** [comment]
getting this as well, with existing ember projects failing in CI due to caret dependency.

**Comment by rwjblue** [comment]
Yep. Locking down jQuery is the fastest path to passing CI builds for now. 

See this blog post for a little bit of background: http://benlimmer.com/2016/01/08/ember-jquery-dependancies/

We'll get this addressed as quickly as possible, but in any scenario changes will be required to your applications bower.json (either locking down jQuery version or updating Ember version).

**Comment by stefanpenner** [comment]
> getting this as well, with existing ember projects failing in CI due to caret dependency.

we should update our blueprint to have a default drift for jQuery that is the same as embers.

**Comment by stefanpenner** [comment]
fixed by https://github.com/emberjs/ember.js/pull/12793, a new release will come out today.

**Comment by stefanpenner** [comment]
ember-cli has been released that pins this version.

A release to ember proper will happen soon hopefully, we have a backlog of releases that must be accomplished first :s

**Comment by rwjblue** [comment]
FYI - Ember 1.13.13, 2.2.2, and 2.3.0 have been released without the assertion.
