### ISSUE TITLE
ember test hangs in CI environment

### ISSUE THREAD

**Issue by davewasmer** [ember-cli/ember-cli#5317]
Reproduction: [davewasmer/sandbox](https://github.com/davewasmer/sandbox)

It appears that `ember test` hangs on CI environments. At first I assumed it was an addon or dependency of our app, so to sanity check / compare I created this sandbox app, with no changes beyond `ember new`. But this one appears to be hanging on Codeship and Travis CIs: 

[Codeship Build](https://codeship.com/projects/126134/builds/11087041)
[Travis Build](https://travis-ci.org/davewasmer/sandbox)

**Comment by stefanpenner** [comment]
maybe related to the recent jQuery bump

**Comment by davewasmer** [comment]
Just caught up on that - trying it pinned to jquery 1.11 ...

**Comment by davewasmer** [comment]
Pinning to 1.11 worked: https://travis-ci.org/davewasmer/sandbox/builds/101190171. Closing in favor of https://github.com/emberjs/ember.js/pull/12787

**Comment by efx** [comment]
Had exact issue on travis with ember-cli 1.13.8 and an ember project, updating my project's bower.json to include `    "jquery": "1.11.3"` worked.
