### ISSUE TITLE
Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

### ISSUE THREAD

**Issue by arifhussain353** [ember-cli/ember-cli#5318]
I installed ember-cli by following in "Rock and Roll with Emberjs" book but i am facing this error in console and can't see "Welcome to Ember. Js" text after navigate to  http://localhost:4200.
I did same what was written in book.
![image](https://cloud.githubusercontent.com/assets/12670763/12217767/2bc574a2-b72c-11e5-903b-c0ec0c77e382.png)

**Comment by caseywatts** [comment]
The same two errors happened to me too after setting up a new `ember-cli` `v1.13.13` app.

I'm going to try to use the previous version of ember `v1.13.12`.
https://github.com/ember-cli/ember-cli/releases

**Comment by arifhussain353** [comment]
what if we only change jquery file manually to 1.9.0 ?

**Comment by paulkr** [comment]
Same two errors happening for me

**Comment by pixelhandler** [comment]
Duplicates #5316

**Comment by caseywatts** [comment]
Bumping down one version of ember-cli didn't help.

Changing jQuery version worked though! :)
I bumped my jQuery to `^2.0.0` (which resolved to `2.1.4` for me)

bower.json
`    "jquery": "^2.0.0",`

**Comment by stefanpenner** [comment]
dupe, please be sure to read existing issues and PR before posting.
