### ISSUE TITLE
Ember-cli not installing ember properly

### ISSUE THREAD

**Issue by collegeimprovements** [ember-cli/ember-cli#5322]
I installed ember-cli by running `npm install -g ember-cli`.  When I run `ember s` it generates build and shows nice message of success.
<img width="440" alt="screen shot 2016-01-10 at 7 10 49 pm" src="https://cloud.githubusercontent.com/assets/1519705/12221760/31aeeebe-b7ce-11e5-8693-76d9b93dbfeb.png">

But when I goto browser it doesn't show me anything. Except this error message:
```ruby
Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1
vendor.js:144 Uncaught Error: Could not find module `ember` imported from `hi/app`
```

<img width="705" alt="screen shot 2016-01-10 at 7 12 18 pm" src="https://cloud.githubusercontent.com/assets/1519705/12221764/56d48686-b7ce-11e5-9d6f-2d845a2ba0b0.png">

Even ember-chrome extension fails to detect the app. For every change my build gets properly generated via command line but I'm not able to see anything in browser.

<img width="570" alt="screen shot 2016-01-10 at 7 10 40 pm" src="https://cloud.githubusercontent.com/assets/1519705/12221763/4d98d950-b7ce-11e5-92a3-cb6dfb3a483d.png">

*I reinstalled node several time to confirm this issue. Please help.

**Comment by foffer** [comment]
+1 - exact same problem I have installing a new ember app. Worked fine yesterday

**Comment by foffer** [comment]
http://stackoverflow.com/questions/34702284/getting-uncaught-error-assertion-failed-ember-views-require-jquery-between-1 Fixes it

**Comment by stefanpenner** [comment]
this is a dupe, please read existing issues before posting: https://github.com/ember-cli/ember-cli/issues/5316

a patch release of ember will be out soon.
