### ISSUE TITLE
`lodash-node` deprecated (from old version of `core-object`)

### ISSUE THREAD

**Issue by gabrielgrant** [ember-cli/ember-cli#5323]
Getting the following warning when installing the latest beta:

```
$ npm install -g ember-cli@2.2.0-beta.3
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
```

It seems this is because ember-cli is [pegged to an old version of `core-object`](https://github.com/ember-cli/ember-cli/blob/master/package.json#L62) which depends on `lodash-node`

Is there some reason the old version is needed? Or can the dep be upgraded?

lodash-node is also pulled in by out-dated dependencies in `ember-cli-qunit`. [That issue is flagged here](https://github.com/ember-cli/ember-cli-qunit/issues/98)

**Comment by stefanpenner** [comment]
> Or can the dep be upgraded?

it should be upgraded, but it is a bit of an involved upgrade.

**Comment by stefanpenner** [comment]
We would accept a PR doing either, although upgrading lodash and releasing another patch of the old version would be quickest.

**Comment by stefanpenner** [comment]
not really considering this a bug, rather a nice thing to fix. WIll accept a PR to address this though

**Comment by flpms** [comment]
How it was solved?

I'm getting a similar error when update to version 2.5, follow stack trace.

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash-node/modern/objects/assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\folderToProject\node_modules\ember-cli\node_modules\core-object\core-object.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by stefanpenner** [comment]
> I'm getting a similar error when update to version 2.5, follow stack trace.

looks like you don't have a complete `npm install` run. I would delete node_modules and try `npm install` again. Be sure to use 3.8.x > npm
