### ISSUE TITLE
Couldn't get Ember CLI 1.13.13 working in development mode.

### ISSUE THREAD

**Issue by ManvendraSK** [ember-cli/ember-cli#5324]
I'm running newly created app with `ember server`, but in browser's console I'm getting following errors:

* `Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1`
* `Uncaught Error: Could not find module `ember` imported from `myapp/app`

However, if I execute `ember server --environment=production` then it works!

I've executed following steps already:
* `npm uninstall -g ember-cli`
* `npm cache clean`
* `rm -rf bower_components\ node_modules\ dist\ tmp\`
* `npm install -g ember-cli`
* `bower install`
* `npm install`

But nothing seems to be working.

Here is the output of my `ember --version -v` command:
```
version: 1.13.13
http_parser: 2.5.0
node: 4.2.3
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
npm: 2.14.10
os: linux x64
```

Help would be much appreciated, and I would be grateful.

**Comment by stefanpenner** [comment]
dupe https://github.com/ember-cli/ember-cli/issues/5316, please review existing issues before postig.

**Comment by ManvendraSK** [comment]
Thanks @stefanpenner, I resolved it. :-)
