### ISSUE TITLE
Ember test & ember try:testall hangs shortly after build

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#5328]
I've got a private Ember Addon I share between two apps.  We just merged a new feature (that changed no code in that Addon) and suddenly our CI builds started hanging during the testing phase of the addon.  The apps themselves are fine.

All of `ember test`, `ember test --server` and `ember try:testall` now hang locally also.  Rolling back to a previous commit doesn't help either.  All get to this line:

```
Built project successfully. Stored in "/Users/hhff/dev/SC/pete/Code/pete/core/tmp/class-tests_dist-lI4M4FG2.tmp".
```
...then hang indefinitely.

CI System: Standard Circle CI Testing setup

Local System:
```
OSX Yosemite 10.10.3
version: 1.13.1
node: 0.12.0 (also tried 0.10.37, same results)
npm: 2.12.1
```

Any thoughts?  Thankyou team!!

**Comment by stefanpenner** [comment]
`cat bower.json` does it contain `jquery: '^1.11.3'` if so, remove the `^`

**Comment by hhff** [comment]
wow, stef you are amazing

fixed (I had `jquery: '1.11.1'`)

**Comment by stefanpenner** [comment]
@hhff ya, sorry. We are sorta stuck, until a series of other releasing land. ember-cli 1.13.4 is out that fixes this for new years, 2.2.x.beta.4 will be out shortly, and hopefully we can get afew ember releases out as well.

**Comment by hhff** [comment]
all g @stefanpenner !  thankyou :100:

**Comment by stefanpenner** [comment]
sorry for the failed builds
