### ISSUE TITLE
Watcher not working reliably

### ISSUE THREAD

**Issue by gonvaled** [ember-cli/ember-cli#5330]
I find that the watcher in ember-cli is working fine in 99% of the cases, except when it doesn't and you spend 2 hours looking for a problem which is actually just `ember serve` not reloading stuff. I have been burnt several times by this, recently when [installing a package](https://github.com/poteto/ember-cli-flash/issues/71#issuecomment-170876355). I always forget, because `ember serve` *usually* works fine.

I have `ember serve` running in a terminal and expect to serve me the correct application, **always**. If that is not the case, I prefer not to have a half-working `ember serve`, and instead manage that manually (but I do not know how to serve without running the watcher).

Some cases when `ember serve` does not work as expected:

- install a new package, with npm or ember
- modify ember-cli-build.js
- modify config/environment.js

And I am probably missing some.

Is there any technical blocker in watching `package.json`, `ember-cli-build.js`, or `config/environment.js`?

**Comment by btecu** [comment]
`config/environment.js` it is observed and it should trigger a reload.

I'm assuming you're not restarting the server after you install a new package in which case I'd expect it not to serve you the *last* version. I think it works like this for performance. Watching `node_modules` would be a really bad idea. Perhaps watching `package.json` may be sufficient but right now it doesn't watch that file either.

**Comment by stefanpenner** [comment]
Yes, once broccoli 1.0 lands we can tmp/ out of the dir root, enabling us to watch it.

These are not bugs, rather working as intended giving existing constraints. As per contributing.md feature requests are to be submitted as issues to the rfc repo, or fleshed out rfc pull requests
