### ISSUE TITLE
Changes to styles in pod structure require ember server restart

### ISSUE THREAD

**Issue by kylenathan** [ember-cli/ember-cli#5333]
When changes are made to a sass styles file in a component pod, ember-cli sees the file has changed but doesnt rebuild the sass.

Work around at the moment is to stop and restart the ember server every time a pod styles.scss is changed (painful!).

There is further discussion in this issue: https://github.com/ember-cli/ember-cli/issues/4658

@aexmachina suggests that it worked correctly 1.13.1 and that the regression was introduced in 1.13.5.
I havent tested those versions but can confirm that it worked correctly in 1.13.8 but does not in 1.13.13 or 1.13.14 so this may have been fixed and broken again.

Example repo: https://github.com/sportly/ember-cli-sass-reload-bug

To reproduce:
* ember s
* change a style in app/components/sassy-tomster/styles.scss
* note that ember-cli rebuilds but the changes to styles.scss are not included

**Comment by stefanpenner** [comment]
just a headsup pods aren't really official supported, more of an experimental feature currently.

Does changing the pod style, followed by changing app/app.js correctly compute the style sheet

**Comment by kylenathan** [comment]
Thanks @stefanpenner. Understood, such a useful feature though.

No luck on changing pod style and then app/app.js.

But saving app.scss does work - so thats at least a temporary workaround that speeds things up a bit.

**Comment by stefanpenner** [comment]
> But saving app.scss does work - so thats at least a temporary workaround that speeds things up a bit.

That makes sense. Basically we have more or less kept pod-styles disabled, until we finish more broccoli performance work.

I really do want pods to have tests / css/ templates / images etc.etc., i think it feels nice and natural, but currently it does impose a performance penalty. I suspect the penalty is much better now, compare to what it once was. I'll have to check again. I do have some more very clear paths to resolving that aspect of the performance penalty. It will just take some more time yet to complete.

**Comment by kylenathan** [comment]
Ok yup, see its pod-styles and not just sass. Makes perfect sense. Any quick pointers on the perf issues? Super busy over the next few weeks but if some time magically appeared would love to contribute.

**Comment by stefanpenner** [comment]
> Any quick pointers on the perf issues?

its rather involved, but the TL;DR is to change the common "what changed" from always crawling the input FS tree, to previous plugins having accurately tracked their own changes and passed the changeset forward. I've started work on a non-brittle way of doing this

**Comment by stefanpenner** [comment]
pods will be revisited once they are formalized and stabilized.

**Comment by lancedikson** [comment]
@stefanpenner, is there any plan or roadmap where we can see formalization process of pods? :)

**Comment by topaxi** [comment]
@lancedikson https://github.com/emberjs/rfcs/pull/143

**Comment by gregattra** [comment]
experiencing the original issue as well with latest ember cli. i get that pods aren't officially supported. but thought it necessary to mention this.

p.s. pods are great

**Comment by munsellj** [comment]
FYI for anyone visiting this in the future. We were able to solve this by adding the `app` directory that our pods styles were under to the included paths in sass options (this is an `ember-cli-sass` option).

Add paths for watching in the 'ember.cli-build.js':
```
var app = new EmberApp(defaults, {
  sassOptions: {
    includePaths: ['app']
  }
});
```
