### ISSUE TITLE
beta.4 fails on start

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5337]
```
Using a version of ember-cli-shims prior to 0.1.0 will cause errors while loading Ember Data 2.3.0-beta.3+. Please update ember-cli-shims from 0.0.6 to 0.1.0.
```

**Comment by stefanpenner** [comment]
Should be an easy fix, merely the blueprints need to be updated.

**Comment by stefanpenner** [comment]
ah it was already fixed by: https://github.com/ember-cli/ember-cli/commit/03b2c8d8b18ded950681b73b2d4e3e572128d8b8

**Comment by terion-name** [comment]
@stefanpenner beta.6 — the same error there, failing build!

**Comment by terion-name** [comment]
oooooh, it's located in bower dependencies
