### ISSUE TITLE
The ember cli command is broken in 2.2.0-beta.5

### ISSUE THREAD

**Issue by jagthedrummer** [ember-cli/ember-cli#5342]
I just tried installing 2.2.0-beta.5 and afterwards I can't run the `ember` command.

I did this to upgrade:

```
$ npm uninstall ember-cli; npm cache clean; bower cache clean;
$ npm install -g ember-cli@2.2.0-beta.5
```

And then when I try to run `ember` I get this:

```
$ ember -v
env: node\r: No such file or directory
```

**Comment by kellyselden** [comment]
Ah. It appears doing a release from a Windows machine has its issues...

**Comment by jakehow** [comment]
while we are wating on a new release, you can temporarily fix this by doing the following:

```
brew install dos2unix
dos2unix /usr/local/lib/node_modules/ember-cli/bin/ember
```

**Comment by jtsom** [comment]
It includes all the blueprint files too - doing an ember init, following the update process, will attempt to replace all of your files.

**Comment by kellyselden** [comment]
If someone doesn't beat me to it, I'll try to release a new version today, this time using a Linux VM.

**Comment by stefanpenner** [comment]
I'm releasing again now. Silly line-endings.

@kellyselden we should investigate if this can be corrected for future windows releases. Is it possible to leave the line-endings unaltered on windows?

**Comment by stefanpenner** [comment]
2.2.0-beta.6  has been released, should handle this issue.
