### ISSUE TITLE
Auto locationType (history api) not working on routes when refreshing/manually entering URL

### ISSUE THREAD

**Issue by matixmatix** [ember-cli/ember-cli#5343]
When using 'auto' locationType, my Ember app works on all routes when I click around in my app, but not when I manually enter or refresh a url, for instance `http://localhost:4200/dashboard`. In this case I get  `<body>Cannot GET /dashboard/</body>` server response. Any idea why this is happening?

When I use `hash` locationType, everything works fine (refreshing and manually entering various app's URLs). 

I'm testing in development, running `ember s`

```
version: 1.13.12
node: 5.4.0
npm: 2.14.10
os: darwin x64
```

My environment.js:

```
baseURL: '/',
apiNamespace: 'api/v1',
locationType: 'auto',
serverURL = 'http://localhost:3000/',
apiBaseURL = ENV.serverURL + ENV.apiNamespace + '/',
documentDomain = 'localhost'
```

**Comment by stefanpenner** [comment]
this is known to work, I was just able to confirm it. Can you please (using the latest releases) try again, if it does not work please provide a repository demonstrating the issue.
