### ISSUE TITLE
live-reload host stuff

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5352]
- [x] portFinder needs to take into account --live-reload-host
- [x] currently portFinder defaults to ipv6 on some capable setups, this can result in false positives. I believe if we bind to 127.0.0.1 by default, we will be correct. Users can specify their own hosts if they want something else
- [x] ensure console UI displays the correct host, currently it does not seem to.

**Comment by stefanpenner** [comment]
hmm, so this seems to cause some issues as well. Im unclear what the best solution is.

It appears this is more complicated then expected let me try to illustrate the issue I ran into.

non-ember service binds to localhost:4XXXX ipv4
our portfinder now using a undefined host, checks *:4XXXX ipv6, does not notice the ipv4 variant is active
curl localhost:4XXXX hits ember
assuming /etc/hosts has the following entry 127.0.0.0.1 foo.com
curl foo.com:4XXXX hits the non-ember IPV4 service 
...sadness and confusion...

killing the non-ember IPv4 service restores the behavior we expect.

This suggests, either we force IPv4, maybe we need to portfinder IPv4 and IPv6, or maybe their is an alternative..

Actual scenario (on my machine):

lsof -i tcp:49152
PKIClient   774 stefanpenner   10u  IPv4 0x6774e71a68cfceb5      0t0  TCP localhost:49152 (LISTEN)
node      17782 stefanpenner   22u  IPv6 0x6774e71a7136e015      0t0  TCP *:49152 (LISTEN)

➜  ~ curl localhost:49152
{"tinylr":"Welcome","version":"0.2.1"}
➜  ~ curl omg.com:49152
curl: (52) Empty reply from server
Any thoughts?

**Comment by stefanpenner** [comment]
forcing the appropriate IPvX works as expected:

```
➜  ~ curl -g -6 localhost:49152
{"tinylr":"Welcome","version":"0.2.1"}⏎
```

```
➜  ~ curl -g -4 localhost:49152
curl: (52) Empty reply from server
```

**Comment by gmurphey** [comment]
Portfinder is using `net.Server.listen` behind the scenes to find a port. From that documentation:

> Begin accepting connections on the specified port and hostname. If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise.

https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback

We might be able to do some work with Portfinder to implement a new method that will return `net.Server.address` (https://nodejs.org/api/net.html#net_server_address)?

**Comment by stefanpenner** [comment]
Changing my host entry for `omg.com` to `::1  omg.com`, allows generic `curl omg.com:49152` to work (expected).

**Comment by stefanpenner** [comment]
@gmurphey that document basically implies that node will connect to the ipv6 socket. If no-one is listening on ipv4. the connecting tool (or something else) falls back to IPv6, and goes with that if someone is listening. But if something else is listening on IPv4, it take precedence.

**Comment by stefanpenner** [comment]
@gmurphey is this ipv6/ipv4 thing also what is causing grief for windows?

**Comment by gmurphey** [comment]
@stefanpenner it seems like it (https://github.com/ember-cli/ember-cli/issues/5123). After suggesting setting `host` explicitly in that issue, I haven't seen anyone else complaining.

**Comment by stefanpenner** [comment]
@gmurphey I'm assuming that is setting the host back to IPv4 only, essentially reverting the IPv6 by default mode.

**Comment by gmurphey** [comment]
@stefanpenner yes, sorry!

**Comment by stefanpenner** [comment]
More on the topic: https://en.wikipedia.org/wiki/Happy_Eyeballs (link thanks to @rw)

**Comment by stefanpenner** [comment]
it seems, like the ideal solution is the following:

1. find a port that is available to both ipv4 and ipv6
2. bind to both IPv4 and IPv6

**Comment by rw** [comment]
+1

**Comment by eriktrom** [comment]
@stefanpenner - gave it a whirl - https://github.com/ember-cli/ember-cli/compare/master...eriktrom:fixup-live-reload - i'll open a pr if i'm headed in the right direction there

**Comment by eriktrom** [comment]
@stefanpenner - upstream changes to port finder: https://github.com/eriktrom/node-portfinder/commit/7472b78180f4e0c71a46e887434cb6a850a797ae

integration into ember-cli (the tests need some cleanup prob): https://github.com/eriktrom/ember-cli/commit/6c0ab5b3f6c7f629a3ee0bfd98acd21d802507a2

leave thoughts or ping me on slack when not busy
