### ISSUE TITLE
Bower resolutions ignore when installing a bower package from a addon

### ISSUE THREAD

**Issue by jpoiri** [ember-cli/ember-cli#5358]
HI there,

I have created an ember add-on that installs the ember-plupload add-on as a dependencies by calling the addAddonsToProject method on the main blueprint

     afterInstall: function (options) {
		return this.addAddonsToProject({
			packages: [
				{name: 'ember-plupload'},
			]
		});
	}

This works fine however there always a bower conflict that occurs when installing the add-on and I have to manully select the version. I tried putting a resolution in the bower.json of the project that going consume the add-on however its seem to always ignore my resolution however if I just do regular bower installs its pickup my resolution.

     installing ember-plupload
     install bower package plupload
     Installing browser packages via Bower...
     install bower package dinosheets
     Installing browser packages via Bower...
       cached git://github.com/tim-evans/dinosheets.git#0.1.1
       cached git://github.com/moxiecode/plupload.git#2.1.8
     Installed browser packages via Bower.
     cached git://github.com/jquery/qunit.git#1.18.0
     conflict Unable to find suitable version for qunit
        1) qunit ~1.18.0
        2) qunit ~1.20.0
     [?] Answer: 2

    "resolutions": {
       "loader.js": "3.4.0",
       "qunit": "~1.20.0"
     }

**Comment by stefanpenner** [comment]
We are planning to continue the move away from bower.
It is unlikely we will fix related issues(as that takes away from our time to continue the migration). If someone is compelled to submit a PR fixing such issues we will gladly review and accept if it meets the requirements
