### ISSUE TITLE
Upgrade Watchman dependency to 4.3.0

### ISSUE THREAD

**Issue by chadfurman** [ember-cli/ember-cli#5359]
https://github.com/ember-cli/ember-cli/blob/1bd51615dc5d5d17ca8b7bbe82baf656cbfe20b0/lib/models/watcher.js#L108

Why force legacy versions of watchman?

**Comment by stefanpenner** [comment]
At the time. I don't believe watchman informed us of its additive only policy. So we took an approach that assume it abides by semver.

Would accept a PR that loosened the constraint

**Comment by stefanpenner** [comment]
Actually this doesn't seem to force anything it just specifies that lower bound to a version known to work. What's wrong with that?

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/5026 fixed this a while back.

**Comment by chadfurman** [comment]
Ah, it isn't a caret there any longer.  Not sure how I missed that.  Thanks!
