### ISSUE TITLE
Hooks available for finding dead code

### ISSUE THREAD

**Issue by eddiesholl** [ember-cli/ember-cli#5364]
I've got some cleanup work to do in a decent sized ember app, there's a fair amount of cruft that has accumulated over a year of development time. Code left from experiments and trial and error etc that didnt get removed at the time. Rather than trying to work out what is still live code by hand, I was thinking about a more permanent and rigorous solution. This is what I had in mind:

* Start by inspecting the router object(s) defined in the app. Treat this as the silhouette around live routes
* Inspect routes, controllers and views, checking they fall within a live route path
* For other things like mixins etc, check if anyone is require ing them

This felt like it might be easiest as part of the build process, as an ember cli add on, with a command like 'ember cleanup'. There would probably be a 'cleanup:find' for just doing assessment, and 'cleanup:delete' to actually delete files.

I don't quite have my head around how 'deep' the ember build process goes in terms of actually parsing app files (like the router paths etc). Are there hooks available that offer this depth of detail? Everything seems to be dealing at the file level, like preProcessTree(). I guess this is a nice starting point, but was wondering if there's an actual tree model of the app and its routes at any point.

**Comment by stefanpenner** [comment]
Ya I like the idea, but this should be opened as an issue on the [rfc](https://github.com/ember-cli/rfcs)
