### ISSUE TITLE
extract bin/changelog to own module

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#5366]

**Comment by kellyselden** [comment]
Should this go on the ember-cli domain?

**Comment by stefanpenner** [comment]
this org works good, unless you have preference

**Comment by nathanhammond** [comment]
[https://github.com/ember-cli/changelog-generator](Repo created.)

**Comment by runspired** [comment]
I've been working on a nice OS one that (at least theoretically) also works for ember and ember-cli

https://github.com/runspired/ember-cli-changelog

**Comment by runspired** [comment]
It needs a little love (I've been using it for a number of my addons, but there are unhandled edge cases and a better config story would be nice), but I've been busy.  There was talk at EmberConf from several people I met of wanting to take up the reigns on it.

**Comment by kellyselden** [comment]
@runspired I think we could switch if it has what we need. You say it works outside ember addon space?

**Comment by twokul** [comment]
@runspired @kellyselden working on extracting it into a separate module and writing tests as well

**Comment by runspired** [comment]
@kellyselden it has what is needed, I can fix known bugs and add tests / patch behaviors until we get complete parity.

**Comment by runspired** [comment]
It comes with a lot more features than what ember-cli has now for generating better links etc.

**Comment by stefanpenner** [comment]
@runspired :+1:

**Comment by nathanhammond** [comment]
We could then integrate it into `ember-cli-release` and call it done.

**Comment by twokul** [comment]
@kellyselden @stefanpenner @nathanhammond what's the best course of action then?

**Comment by stefanpenner** [comment]
seems like:

1. extract to module
2. use in approriate user-facing modules such as ember-cli-release

@runspired what are your thoughts?

**Comment by runspired** [comment]
@stefanpenner ember-cli-changelog already comes with an ember-cli-release integration, and a deeper integration is already in the works.  Mostly I just need to find some cycles or find someone else with some cycles to clean up a few edge cases I've bumped into to make this more widely usable.

**Comment by stefanpenner** [comment]
@runspired got any spare cycles in-sight?

**Comment by runspired** [comment]
@stefanpenner yes, and found some people who will help on this too, and already fixed a few bugs / edge cases

**Comment by stefanpenner** [comment]
@runspired sweet!

**Comment by nathanhammond** [comment]
Ping @runspired.

**Comment by locks** [comment]
I believe this is no longer relevant!
