### ISSUE TITLE
watchman is unable to resolve root

### ISSUE THREAD

**Issue by zichaolim** [ember-cli/ember-cli#5371]
Guys, this is the error message:

 ERROR  unable to resolve root /Users/valleyreign/golf: failed to opendir(/Users/valleyreign/golf): No such file or directory
{"watchmanResponse":{"version":"4.3.0","error":"unable to resolve root /Users/valleyreign/golf: failed to opendir(/Users/valleyreign/golf): No such file or directory"}}
Error: unable to resolve root /Users/valleyreign/golf: failed to opendir(/Users/valleyreign/golf): No such file or directory
    at BunserBuf.<anonymous> (/Users/valleyreign/golf/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/valleyreign/golf/node_modules/bser/index.js:289:10)
    at /Users/valleyreign/golf/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

**Comment by zichaolim** [comment]
This is the result of the command below:

$ watchman watch-list
{
    "version": "4.3.0",
    "roots": []
}

**Comment by stefanpenner** [comment]
Sounds like a watchman bug, please open this issue on that repository. Until then you can use --watcher=node to work around the issue.

Feel free to mention this issue in that issue, I know the team over there is responsive. If the issue does turn out to be something in ember-cli we can reopen this issue.
