### ISSUE TITLE
inconsistent jshint detection on app start

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#5373]
Is this a known issue?

I am finding inconsistent appearance of jshint warnings between startups of ember cli app.

Sometimes I get a whole bunch of errors and then other times nothing at all when I know there are in fact lint errors in the source.

Is there some caching behavior? Maybe a documentation/configuration issue?

**Comment by btecu** [comment]
Yes, is the cache. I think you'll get warnings if you're either on the initial build or if you're changing the specific file that has the errors.

**Comment by stefanpenner** [comment]
> Is there some caching behavior? Maybe a documentation/configuration issue?

It's quite possible their is a cache key issue in broccoli-jshint, the following lines already look dubious:
https://github.com/rwjblue/broccoli-jshint/blob/master/index.js#L162-L164

**Comment by eccegordo** [comment]
So is there a way to manually invalidate the broccoli-jshint cache and start with a clean state? Not clear what I need to do to start over. I have tried deleting `dist/` and `tmp/` not sure what else.

**Comment by stefanpenner** [comment]
@eccegordo if you `touch` any file inside of `broccoli-jshint` its cache will be evicted.

**Comment by kellyselden** [comment]
I've seen the same issue in `broccoli-jscs` as well FYI, since their pretty much based on the same code. https://github.com/kellyselden/broccoli-jscs/issues/53

**Comment by eccegordo** [comment]
@stefanpenner Do you mean `MY_EMBER_PROJECT/node_modules/broccoli-jshint/`
Basically touch any file there?

**Comment by stefanpenner** [comment]
@eccegordo yes

**Comment by stefanpenner** [comment]
alternatively @rwjblue knows the enchantation to purge the "behind the scenes cache"

**Comment by rwjblue** [comment]
I believe `rm -rf node_modules && npm install` should force the persistant cache to clear, but you can also do `rm -rf $TMPDIR/async-disk-cache` (this will screw up any running `ember` processes on your machine though) if that doesn't fix it for you.

**Comment by rwjblue** [comment]
This has been fixed.  We added the ability for broccoli-persistent-filter to warn about errors even if the file itself hasn't changed since the prior build.
