### ISSUE TITLE
Script files in config/ are not being linted

### ISSUE THREAD

**Issue by justin-lau** [ember-cli/ember-cli#5375]
The [`lintTree` addon hook](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md#linttree) currently does't include `config` in the tree type, hence the script files inside are not being linted.

Related code block: https://github.com/ember-cli/ember-cli/blob/v2.2.0-beta.6/lib/broccoli/ember-app.js#L1047-L1065

**Comment by rwjblue** [comment]
Correct, we also do not lint index.js in addons (from another issue that I can't search for ATM).

**Comment by stefanpenner** [comment]
this is kinda by design, as we only lint client-side code. If we want to do some more complex linting, this will be a new feature and should go through the RFC process.
