### ISSUE TITLE
--config-file option not respected in ember test in 1.13.14

### ISSUE THREAD

**Issue by keithbro** [ember-cli/ember-cli#5376]
To demonstrate, run:

`ember test --reporter xunit`

which outputs XML as expected.

but with `"reporter": "xunit"` set in testem-new.json and run:

`ember test --config-file ./testem-new.json`

does not output XML. It still looks at the config in the default testem.json.

**Comment by keithbro** [comment]
Looks like it was fixed in version 2.x #5089

**Comment by stefanpenner** [comment]
As mentioned this is fixed in 2.x (which aims to be more or less backwards compat)
