### ISSUE TITLE
Unable to use services @2.3.0-beta

### ISSUE THREAD

**Issue by sebyx07** [ember-cli/ember-cli#5382]
I don't know why but i can't use services from component/routes

i tried to inject them with the initializer, but the container doesn't find it 
```js
 application.inject('route', 'myService', 'service:myService');
```

then i tried to inject with Ember.inject.service()
```js
{ 
   myService: Ember.inject.service('myService') //with or without the 'myService'
}
```

strange is that i can use the service from i18n.
also myService does not appear in the ember browser extensions under services....

**Comment by stefanpenner** [comment]
I don't believe this is related to ember-cli, as it is merely the build pipeline. I suspect this may be something in ember or an addon. Best bet is to create a reproduction and submit an issue to the repo most relevant to it.

**Comment by stefanpenner** [comment]
If it does end up being a cli issue, provide said repro here and we will gladly reopen and investigate

**Comment by rwjblue** [comment]
Might be unrelated, but using camel case in general may result in the resolver being unable to find files that you have on disk. 

The primary naming rule in CLI is "dasherize", if there were a second rule it would be dasherize too. :smiling_cat:

**Comment by sebyx07** [comment]
omg thanks @rwjblue
