### ISSUE TITLE
Cannot execute tests when babel does not transpile 'let' keyword

### ISSUE THREAD

**Issue by janmisek** [ember-cli/ember-cli#5389]
Happening on 2.3.0-beta.1  in chromium 47

I am getting following exception when executing tests in case babel transpilation of 'let' keyword is disabled.  

`Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

My `ember-cli-build.js` config for babel

```
        babel: {
            comments: false,
            optional: [
                //"es7.asyncFunctions"
                //"es7.functionBind"
            ],
            blacklist: [
                'es6.templateLiterals',
                'es6.blockScoping',
                'es6.constants'
            ]
        },
```

Generally problem is that each non jshint module included in compiled tests.js is missing 'use strict' statement

**Comment by janmisek** [comment]
I have traced down issue to the https://github.com/babel/ember-cli-babel/blob/cb4c2e763eb2fdb96654957ee2578912f88a8265/index.js#L93 where useStrict is blacklisted from babel with comment `Ember-CLI inserts its own 'use strict' directive`. But for tests tree (tests.js) this ember-cli strict mode is not used

**Comment by janmisek** [comment]
What about use `lib/broccoli/test-prefix.js` with `use strict` content to be used same way for tests.

**Comment by stefanpenner** [comment]
@nathanhammond i think the use-strict trick you added needs to also append to the test file.

**Comment by rwjblue** [comment]
Ya, agreed. Possibly also to test-support.js.

**Comment by nathanhammond** [comment]
@rwjblue Can't turn it on for `test-support.js` since both Ember and QUnit do things where they assume that `this` is set inside of an IIFE. Not a problem in this case as no user code ends up inside of `test-support.js`.

@janmisek Thanks for reporting, sorry to take so long on addressing. 😄
