### ISSUE TITLE
support for sourcemap root url

### ISSUE THREAD

**Issue by dhruvparmar372** [ember-cli/ember-cli#5397]
could not find anything related to providing a custom `urlPrefix` to the sourceMap link generated in the build files in the ember-cli docs. 
is this feature supported in the current version ?

**Comment by stefanpenner** [comment]
as per: https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md

* Q/A is for Stackoverflow discourse
* new features are to be requested via the RFC process
* this tracker is specificlly for bugs
