### ISSUE TITLE
Add a bit of documentation showing how to support staging environments

### ISSUE THREAD

**Issue by trcarden** [ember-cli/ember-cli#5400]
For people new to the emberjs ecosystem it would help to have a short example showing how to setup a staging environment and/or leverage environment variables present on the OS to further enhance their configs. Its pretty obvious but not mentioning it all has lead a couple of us in the wrong direction.

See: https://github.com/ember-cli/ember-cli/pull/1520#issuecomment-175421230

**Comment by stefanpenner** [comment]
i would recommend opening this on the website repo: github.com/ember-cli/website

**Comment by trcarden** [comment]
@stefanpenner that link is dead

![image](https://cloud.githubusercontent.com/assets/460530/13367180/51ef3a12-dc95-11e5-9d80-06359ce2a679.png)

**Comment by kellyselden** [comment]
@trcarden The link is https://github.com/ember-cli/ember-cli.github.io
