### ISSUE TITLE
[Question]: why would addon unit test options differ from ember application unit test options?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-cli#5401]
Today I was writing some tests for an addon and noticed my model objects kept returning undefined for getOwner (using ember 2.3). The funny part was I extracted those same unit tests from a working production ember app (also running 2.3). Down in the guts of ember (in factoryFor) I found that my production ember unit tests had this flag set to true

```
_emberMetalCore.default.MODEL_FACTORY_INJECTIONS
```

But ... when the addon unit tests were running this same flag was undefined (the root cause of my issue). The fix was to open test-helper.js, import Ember and set that value to true (like it is for my production ember app unit tests).

The bigger question to the ember-cli core team ... is that not true for a reason or is this just a small mistake and something I could PR / discuss more to better understand what the "right fix" looks like? Or is this flag instead "undefined" for a reason in addons?

**Comment by trabus** [comment]
I have no knowledge of this or any possible reasons behind it, but I would guess it was a small mistake and a PR would be welcome.

**Comment by toranb** [comment]
@trabus I'm mostly curious where this *should* be applied (hacking test-helper.js seems to work but I'll need to dive into some ember-cli source to understand better what the real fix should be).

thanks for the quick reply!
