### ISSUE TITLE
[PROPOSAL] Change `*-addon` blueprints to `*-addon-import`

### ISSUE THREAD

**Issue by trabus** [ember-cli/ember-cli#5402]
Back when the `addon-import` code [was added](https://github.com/ember-cli/ember-cli/pull/3690), it was decided that for most blueprints we use the default `addon-import` blueprint, but for special cases I had opted to go with `*-addon` for the blueprint name (like `component-addon`) to signify that it is a wrapper blueprint. Because of the slightly different naming, it can be a little confusing about what a `*-addon` blueprint is for unless you have the original context.

I want to change any instance of `*-addon` to `*-addon-import` for clarity's sake, but haven't fully investigated the effects it may have on existing blueprints in the wild. Due to that possibility, I thought it might be a good change for 2.x.

So for instance, the `component-addon` blueprint would become `component-addon-import`.

Affected blueprints would be:
```
component-addon
helper-addon
initializer-addon
instance-inititalizer-addon
route-addon
```
This change would require modifications to the `generate-from-blueprint` task, which has special rules to accommodate `*-addon` blueprints.

**Comment by knownasilya** [comment]
Thanks for the lesson, I wasn't aware and overrode the whole `addon-import` blueprint in one of my addons. :+1: on the change.

**Comment by stefanpenner** [comment]
likely best as an RFC  or RFC issue
