### ISSUE TITLE
initializers affect component integration tests if there is an acceptance test

### ISSUE THREAD

**Issue by jelhan** [ember-cli/ember-cli#5405]
If there is an acceptance test an initalizers and instance-initializers affects component integration tests. If not they won't. Inconsistent errors depending on test filters is the result. Really confusing...

Let my give an example: I have an initalizer to configure webshim polyfill. I have a component integration test which was affected by webshim. Tests passes running `ember test -m "Integration | Component | webshim affected component"` while failing on `ember test` (which also runs acceptance tests).

Was even more confusing since tests passed in chrome (which has native support for the feature) but failed in phantomjs (which uses polyfill) but that has nothing to do with ember-cli. :smile:

ember-cli: 1.13.13
ember-qunit: 0.4.16

**Comment by stefanpenner** [comment]
sorry, this doesn't seem to have anything todo with the build system. Maybe something to open on the test-helpers repo?
