### ISSUE TITLE
Addons with pods in the app directory don't compile templates

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli#5406]
This is to document an issue that I had earlier this week and discussed with @rwjblue on Slack. For reference, see https://github.com/tim-evans/ember-addon-component-pods for a repository that reproduces this.

As of now, any addon that has templates in pods won't be compiled in the `app/` directory. This is a problem due to (quoting @rwjblue):

> The issue is some... filtering that I am doing in ember-app.js. The templates you want are in the addon's `app` tree which is grabbed from [ember-app.js](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L706) but we do not preprocess templates from the `addonTreesFor('app')` call. The way we get pods templates to work in the apps `app/` dir is to do extra processing [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L738-L743), but you will notice we are only asking for `addonTreesFor('template')` there, and do not extend the template processing properly to the addon's `app/` tree.

> Unfortunately, adding an extra mergeTree + filtering to all addons will be somewhat costly (and it would force us to process `app` in the addon twice, which is not great).

The choices enumerated in this discussion were the following:

1. Put pod based components in addon, and then reexport in `app`
2. Put templates in `app/templates/components/foo-bar.hbs` instead of `app/components/foo-bar/template.hbs`
3. Use `inline-htmlbars-precompile` to compile them: 
```javascript
export default Ember.HTMLBars.template(hbs`

`);
```

@rwjblue 's solution for this is to:

> Remove the arbitrary filtering done all over the place and just process templates / styles in all of `app/` without extra hoop jumping. This will likely speed up build times in general, both when you use pods and when you don't (the current solution slows down builds even when not using pods) and make the build more of a straight pipeline.

**Comment by rwjblue** [comment]
Thank you for taking the time to document our conversation. Hopefully anyone coming across this can use one of the workarounds listed, and we can get the real solution implemented sometime soon...

**Comment by erkie** [comment]
As of `2.5.0` I can't get this to work. I tried the approach number 1, and it did not generate anything new. It looks like there is a discrepancy between the generated module names? 

```
# Component
define("dashboard/components/layout/sub-menu/component", ["exports", "ember"], function (exports, _ember) {
# Template
define("dashboard/templates/components/layout/sub-menu/template", ["exports"], function (exports) {
```

I think the problem lies within the "templates"-directory in the template string?

**Comment by nathanhammond** [comment]
Pods are no longer receiving maintenance as we move toward the Module Unification plan: https://github.com/emberjs/rfcs/pull/143

We don't intend to address this issue.

**Comment by tim-evans** [comment]
Thanks for the update. If pods aren't receiving maintenance, is there a rough road map available for modules?

I'm uneasy about support, due to my experience of having to maintain old software longer than expected. I would like to jump on the modules bandwagon, but feel like the projects I work on are in an in-between place with pods.

Cheers!

**Comment by nathanhammond** [comment]
@tim-evans I'm pulling together the roadmap for our module unification build efforts very soon. We've begun discussion of the efforts in our Ember CLI core team meetings ([July 28](https://github.com/emberjs/core-notes/blob/master/ember-cli/2016-07/july-28.md), [August 4](https://github.com/emberjs/core-notes/blob/master/ember-cli/2016-08/august-04.md)). Further, the work being done for the Ember Engines build has helped to inform some of the requirements for this effort.

We don't publish feature timelines but in the mean time you can either migrate to the "traditional" file structure, maintain status quo if nothing is broken (pods and traditional work side-by-side, so you should be able to work around any issues), or simply wait and migrate to the unified module story once it lands.

**Comment by tim-evans** [comment]
Understood! I simply wanted to express that it makes me anxious. Anyways 👍 

Excited to see this get in!

**Comment by tim-evans** [comment]
Understood! I simply wanted to express that it makes me anxious. Anyways 👍 

Excited to see this get in!
