### ISSUE TITLE
In repo addons should respect app's hinting option

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli#5407]
```
// ember-cli-build.js
module.exports = function() {
  app = new EmberApp({
    hinting: false
  });
};

// lib/some-addon/index.js
module.exports = {
  name: 'some-addon',

  isDevelopingAddon: function() {
    return true;
  }
};
```

I think addons should respect the hinting option on the host app and suppress hinting if it's turned off. So far I only found this problem on in-repo addons, but I suspect the problem also exist for normal addons with `isDevelopingAddon` turned on.

**Comment by rwjblue** [comment]
Each addon enables/disables its own hinting, you can disable in the in-repo-addon via:

```
  hintingEnabled: function() {
    return false;
  }
```

**Comment by ming-codes** [comment]
Ah, that solves the problem. I can just make the function return the app's hinting value.

```
  hintingEnabled: function() {
    return this.app.options.hinting;
  }
```

Thanks @rwjblue

**Comment by ming-codes** [comment]
@rwjblue I opened a PR on the docs repo to explain how `index.js` actually extends the `Addon` class.

ember-cli/ember-cli.github.io#43
