### ISSUE TITLE
v1.13.15 --proxy option is ignored

### ISSUE THREAD

**Issue by dmitrymatveev** [ember-cli/ember-cli#5408]
Hi,

Just updated my project from v1.13.8 to v1.13.15 and bumped into a weird behavior when the proxy option is acknowledged at server start but is not taken into account when ember data sends its xhr requests.

![1](https://cloud.githubusercontent.com/assets/3842466/12700856/a11594ca-c858-11e5-940d-ba0c46847f44.PNG)
![2](https://cloud.githubusercontent.com/assets/3842466/12700858/a600a4e8-c858-11e5-9ea8-4c68e4de7779.PNG)
![3](https://cloud.githubusercontent.com/assets/3842466/12700859/a7985fbc-c858-11e5-9a6b-ee479e446a7d.PNG)

**Comment by Turbo87** [comment]
@dmitrymatveev I don't think the `--proxy` option is "ignored" because the CLI output clearly states that it's trying to proxy the request, but there seems to be something wrong with the connection to the proxied server.

**Comment by stefanpenner** [comment]
will gladly reopen if demonstrated as an issue on the latest version. The error seems to indicate the foreign server isn't correctly accepting connections?

**Comment by ErunamoJAZZ** [comment]
I have the same issue with ember-cli 1.13.15.

We are using rx-dom (this use xhr internally), and server don't understand the request. My question is, this is happening with new ember-cli version too?

**Comment by dmitrymatveev** [comment]
@stefanpenner the error was that the IP and port of the built application does not match what ember-cli shows in its output... e.g. cli shows that it is configured to use `http://192.168.0.100:8888` however as you can see in the chrome screenshot, xhr request is still being addressed to `http://localhost:4200`.

I had to manually destroy and reconstruct the project using the latest ember-cli build, it only came up when I attempted to upgrade the project using cli. it does work as intended when I created a clean project this way.

**Comment by Turbo87** [comment]
@dmitrymatveev this sounds like you misunderstood how the `--proxy` feature is supposed to work. it is intended behavior that ember-data will keep connecting to the local server that the ember app is running on. that local server will however try to proxy any requests to unknown files/urls to the specified `--proxy` server in the background. this feature was basically builtin to get around CORS limitations.

**Comment by dmitrymatveev** [comment]
@Turbo87 I am sure I understand how it supposed to work. What you said is right however if you look at chrome console logs you will clearly see that requests are not addressed to proxy IP
