### ISSUE TITLE
Failed installation on Windows 8.1

### ISSUE THREAD

**Issue by zorobabel** [ember-cli/ember-cli#5409]
My environment is **64 bit:**

**Windows 8.1 Pro
Node.js 5.5.0
npm 3.3.12**

I had problems installing ember-cli on my machine, the following command works partially:

`npm install -g ember-cli`

I realized that a command called **`ember.cmd`** was created in _C:\Users\Username\AppData\Roaming\npm_ but not **_ember-cli_** in _C:\Users\SM\AppData\Roaming\npm\node_modules\_**_ember-cli_**. So, this failed:

`ember new test-app`

My solution was:

`cd C:\Users\Username\AppData\Roaming\npm\node_modules`
`npm install ember-cli`

No errors. Then, this was ok:

`ember new test-app`

Any idea?

**Comment by zorobabel** [comment]
This works fine:

`npm install -g ember-cli@2.2.0-beta.6`

**Comment by kellyselden** [comment]
It sounds like you don't have "AppData\Roaming\npm" in your PATH

**Comment by zorobabel** [comment]
@kellyselden I have _`AppData\Roaming\npm`_ in my PATH

**Comment by stefanpenner** [comment]
@zorobabel both 1.x and 2.x use the exact some executable, it is very unlikely that a difference exists that would cause this beyond path not being setup correctly, or `npm` having failed.

**Comment by zorobabel** [comment]
@stefanpenner so, what happened?

**Comment by stefanpenner** [comment]
> @stefanpenner so, what happened?

my guesses are: npm may have failed, or your path/env was incorrect.

> Did you test it on Windows?

yes, it has been thoroughly tested on windows. @kellyselden is also one of our windows users.

**Comment by zorobabel** [comment]
@stefanpenner Strange. The Node.js's MSI installers set the PATH variable. Anyway, now I can use Ember. Thanks.

**Comment by stefanpenner** [comment]
@zorobabel did you restart the powershell/cmd/git bash after updating the path?

**Comment by zorobabel** [comment]
@stefanpenner Yes, I did (really, always I do that)

**Comment by stefanpenner** [comment]
strange, well if some other piece of information turns up we can investigate it further.

**Comment by zorobabel** [comment]
@stefanpenner Yes, thanks.
