### ISSUE TITLE
With test --serve, each rebuild opens a new Chrome window

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli#5414]
*Sporadically*, when I run `ember test --serve`, I get a new Chrome window each time I save a file. This has happened on Ember-CLI v1.13.13, v1.13.15, and v2.3.0-beta.1. Killing the `ember serve` process and restarting usually fixes it.

Environment:
 * Chrome v48
 * Ember-CLI v1.13.13, v1.13.15, v2.3.0-beta.1
 * OSX 10.10.5 Yosemite
 * Node v0.12.0

**Comment by stefanpenner** [comment]
I suspect this is some CLI + testem interop funniness

**Comment by jamesarosen** [comment]
An off-the-wall hypothesis:

Something (runtime, in our app code or Ember or an addon, or in the Ember-CLI server) is breaking the socket connection between the browser and Testem. When Testem wants to restart the tests, it can't find an open Chrome browser and opens a new one.

This could also explain http://discuss.emberjs.com/t/why-is-phantomjs-disconnecting/9636

**Comment by johanneswuerbach** [comment]
Thats sounds more testem related. I'll have a look as soon as time permits, but it indeed sounds like the browser connection is lost because of whatever and then testem tries to spawn another runner (what it also shouldn't).

**Comment by jamesarosen** [comment]
Possibly related: I'm seeing
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:7357/testem.js' with computed SHA-256 integrity 'qDd4jcOyBU3a6GBKhUkzekVmz04/Mprug1f/opOK1lw='. The resource has been blocked.
```
Changing
```html
<script src="testem.js"></script>
```
to
```html
<script src="testem.js" integrity=""></script>
```
fixes this. It does, however, cause the "browser disconnected unexpectedly" problem more often.

**Comment by davidgoli** [comment]
What's the resolution here? It seems this was fixed with https://github.com/testem/testem/pull/781, shouldn't ember-cli update its version of testem to 1.2.2?

**Comment by kellyselden** [comment]
@davidgoli I don't think it was high priority because it was covered in the `^` version hint. Updated in  #5466.
