### ISSUE TITLE
Tests hang with latest release of PhantomJS

### ISSUE THREAD

**Issue by devinus** [ember-cli/ember-cli#5415]
Had to downgrade to 1.9.x.

**Comment by stefanpenner** [comment]
please provide additional reproduction steps. As this works in many apps that I use, and works with the default app.

**Comment by devinus** [comment]
- OS - Mac OS X 10.11.3
- npm veresion - 3.6
- ember version - 2.3.0
- steps to reproduce:
  - `npm install --save-dev phantomjs-prebuilt`
  - `npm test`

**Comment by stefanpenner** [comment]
danke

**Comment by devinus** [comment]
Attempting to make an example repo.

**Comment by rwjblue** [comment]
Thank you, that will be very helpful.

**Comment by devinus** [comment]
Guys, is there any way to get some verbose output during `ember test` so I can narrow down what's hanging?

**Comment by devinus** [comment]
I ask because I couldn't duplicate it in a fresh project, so it must be some combination of modules I'm using.

**Comment by rwjblue** [comment]
For a giant flood of debug messages try:

```
DEBUG=* ember test
```

**Comment by jmurphyau** [comment]
Phantom JS produces possibly the most frustrating troubleshooting experiences that I've experienced since developing ember apps..

The issue is likely a JS parse issue because phantom js uses an ancient WebKit.. Your best bet is to use remote debugging to connect to the failed phantom js session..

See http://bumbu.me/remotely-debug-phantomjs/ .. Testem supports setting this value using the phantomjs_debug_port option

**Comment by jmurphyau** [comment]
Parse error might not be the issue if your issue is on phantomjs 2 but the rest should help

**Comment by devinus** [comment]
@jmurphyau Starting that...

**Comment by devinus** [comment]
Ok, this is what I'm seeing. Any help decoding what this means would help me track it down further. This is where it's hanging:

<img width="1211" alt="screen shot 2016-02-04 at 1 18 04 pm" src="https://cloud.githubusercontent.com/assets/4836/12826701/fd96fd60-cb41-11e5-900e-a12290de6d6d.png">
<img width="514" alt="screen shot 2016-02-04 at 1 17 20 pm" src="https://cloud.githubusercontent.com/assets/4836/12826705/0256f9e0-cb42-11e5-8303-ffaebbe95dc2.png">

**Comment by devinus** [comment]
Actually, I don't think those lines are the issue anymore. I've completely removed most of my tests to run down the problem and it seems to still hang.

**Comment by devinus** [comment]
Ok everybody, after upgrading to the latest *everything* this is now what I see:

```
version: 2.3.0
Built project successfully. Stored in "/Users/devinus/Projects/rebelmail-dashboard/tmp/class-tests_dist-AomFKkIW.tmp".
not ok 1 Browser "phantomjs /Users/devinus/Projects/rebelmail-dashboard/node_modules/testem/assets/phantom.js http://localhost:7357/6864" failed to connect. testem.js not loaded?

1..1
# tests 1
# pass  0
# skip  0
# fail  1
npm ERR! Test failed.  See above for more details
```

**Comment by rwjblue** [comment]
We definitely need to be able to reproduce this to help out...

**Comment by duboff** [comment]
We had the same issue. Tests were hanging on CircleCI with PhantomJS 2.0 but work fine with normal PhantomJS. I will try to help to reproduce when I have a bit more time

**Comment by ehntoo** [comment]
@devinus - I saw the same thing after upgrading to 2.3. I was missing `integrity=""` in my testem.js import in `tests/index.html`.

**Comment by stefanpenner** [comment]
> I was missing integrity="" in my testem.js import in tests/index.html.

@devinus does this address the issue? or..

Would love a reproduction, even if you privately share your app with me...

**Comment by devinus** [comment]
@stefanpenner I unfortunately already had that.

**Comment by devinus** [comment]
```
not ok 1 Browser "phantomjs /Users/devinus/Projects/rebelmail-dashboard/node_modules/testem/assets/phantom.js http://localhost:7357/8039" failed to connect. testem.js not loaded?
```

**Comment by devinus** [comment]
I'm seeing this:

```
Refused to frame 'http://localhost:7357/testem/connection.html' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by devinus** [comment]
Also this:

<img width="1417" alt="screen shot 2016-02-25 at 2 52 31 am" src="https://cloud.githubusercontent.com/assets/4836/13314452/db913c6a-db6a-11e5-8a5a-a5a97bccc822.png">

**Comment by devinus** [comment]
Finally! It seems after removing `ember-cli-content-security-policy` from my package.json it starts to run (with a BUNCH of new output, including deprecation output messages I never got with Phantom 1.9. Not sure what's up with that?)

So now the question is, how do I make this work without disabling SRI?

**Comment by notmessenger** [comment]
I'm having the same problem in two different repos.  The one I'm currently trying to troubleshoot is giving me

`Browser "pathToApp/node_modules/phantomjs/lib/phantom/bin/phantomjs pathToApp/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/6123" failed to connect. testem.js not loaded?`

@jmurphyau @devinus Where did you place the `test.js` within your application and what url did you pass to `open()` in it when remote debugging PhantomJS? I've tried different combinations but have not been successful.

**Comment by devinus** [comment]
@notmessenger My issue was "solved" by removing `ember-cli-content-security-policy` from my package.json. Maybe @rwjblue could chrime in, but otherwise you can debug Phantom by opening `http://localhost:9000` after putting `"phantomjs_debug_port": 9000` in your `testem.json` file.

**Comment by stefanpenner** [comment]
> ember-cli-content-security-policy from my

this is no longer part of a default ember init/new

**Comment by stefanpenner** [comment]
> Would love a reproduction, even if you privately share your app with me...

^^^

**Comment by erichonkanen** [comment]
@stefanpenner I'm confused.. I just ran into this when trying to spin up testing for an ember 2.5 app that also has content security policy set. is the only way to fix this to remove that?

**Comment by devinus** [comment]
@erichonkanen No, it's a problem with ember-csp: https://github.com/rwjblue/ember-cli-content-security-policy/issues/63

**Comment by IAmJulianAcosta** [comment]
If anyone has this error: `not ok 1 Browser "phantomjs /Users/devinus/Projects/rebelmail-dashboard/node_modules/testem/assets/phantom.js http://localhost:7357/6864" failed to connect. testem.js not loaded?`

In my case was caused by an invalid `test_page` in `testem.json`.

**Comment by billpull** [comment]
@IAmJulianAcosta what was the invalid vs valid diff on that field?

**Comment by IAmJulianAcosta** [comment]
@billpull in my case it was a malformed URL, IIRC, I used `tests/index.html&params`, instead of `tests/index.html?params`

**Comment by luketheobscure** [comment]
Same issue. Getting the `failed to connect. testem.js not loaded?` message. I have a `baseURL` set in my environment. Setting it to `''` in the test environment fixes running the tests from the command line, but I'm no longer able to run the tests in the browser.

I've got a rather complicated set up, including running haproxy.

**Comment by fuse-mars** [comment]
has this been solved? I see that the issue is closed

**Comment by munsellj** [comment]
Also ran into this and the issue in my case was that I had added loading of 3rd party libraries(Mapbox and Stripe in my case) from their CDN hosting to my `tests/index.html`.  I was already not using _ember-cli-content-security-policy_ in this app so that was not an issue.  Removing load of the 3rd party libraries fixed the issue.

**Comment by mschinis** [comment]
changing 
```html
<script src="testem.js" integrity=""></script>
```
to
```html
<script src="{{rootURL}}testem.js" integrity=""></script>
```

worked fine for me.

**Comment by rwjblue** [comment]
Hmm. I suspect that you have a custom `rootURL`, and that you are being bitten by https://github.com/ember-cli/ember-cli/pull/6189.

**Comment by mschinis** [comment]
yeah that's what I think as well. Must have missed that change when I ran `ember init` to update my project.
I just realised though that this is an old ticket, and everyone else above probably had a different issue.

**Comment by coreypmurphy** [comment]
@mschinis that solution actually helped me tremendously.  I also missed that change during the ember init and was having the same issue.  Thanks for pointing that out!

**Comment by medokin** [comment]
If nothing works always keep calm and update phantomjs.

**Comment by serv** [comment]
I had a similar problem as many people here. Error message I saw looks something like this.

```
version: 2.3.0
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building...
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to-hash`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to-hash`.
DEPRECATION: this.mergeTrees is deprecated, please use broccoli-merge-trees directly instead  [addon: ember-cli-raw-handlebars]
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `transform-liquid-with-as-to-hash`.
[BABEL] Note: The code generator has deoptimised the styling of "webclient-cli/templates/components/search-popout.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "webclient-cli/templates/profile/index.js" as it exceeds the max of "100KB".
Built project successfully. Stored in "/Users/jasonkim/work/node/webclient-cli/tmp/class-tests_dist-21fjNfyK.tmp".
not ok 1 Error
    ---
        message: >
            Launcher PhantomJS not found. Not installed?
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
```

Here's what I did to fix it.

1. Remove phantom.js package from package.json in devDependencies. 
2. Remove phantom.js from Homebrew
3. Install phantom.js globally using npm.

**Comment by sir-dunxalot** [comment]
I was able to solve this issue by upgrading to the latest version of Ember CLI, `2.11.0`.

**Comment by FutoRicky** [comment]
Im currently experiencing this issue. phantom.js hangs with `Built project successfully. Stored in ...` message. Currently running ember-cli `2.11.0`
