### ISSUE TITLE
noisy empty project structure

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#5417]
### Problem Statement:
A lot of example projects and addons are typically littered with empty "project structure" folders. e.g. folders that were generated on project init and have `.gitkeep`

Pros
Provides "place for every thing, and thing for every place" conventional scaffold. 
Reinforces convention and prevents bike shedding of folder names.

Cons
Empty folders can actually be a lot of noise when project doesn't actually have much going on inside it such as helpers, services, adapters, etc. And you just want to focus on what is actually in the project. Especially when browsing example projects on github.

#### Proposal:
Create ember cli command that allows easy toggling of this via generators
`project --minimal-struture` : strips away all empty folders and `.gitkeep` 
`project --rebuild-struture` : reconstitutes conventional  folders structure. Maybe a pods vs classic argument

 An ember cli command would promote tutorial writers and addon creators to publish minimized and focused examples. The rebuild command would fill in the blanks of convention when needed.

**Comment by rwjblue** [comment]
In general we like to keep our issue tracker here for actual bugs that need to be fixed. Feature proposals/requests should go to the ember-cli/rfcs repo (as an issue if there is no proposed solution or as a PR if there is a proposed solution).

Would you mind reopening over there?

**Comment by stefanpenner** [comment]
> project --minimal-struture

A tidbit, for further exploration. I would like this to use blueprints under the food.
