### ISSUE TITLE
ember-cli-build.js is not importing any css file

### ISSUE THREAD

**Issue by rajivdhiman** [ember-cli/ember-cli#5422]
I'm trying to import one CSS file form Vendor folder but despite all my effort I am not able to that. Though it  is importing JS files properly. This is snippet of my code 

app.import('vendor/DataTables/datatables.css');
app.import('vendor/DataTables/datatables.min.js');

These files exist in Vendor folder.

What could be the issue?

**Comment by t4t5** [comment]
I have the same problem since updating Ember CLI.

If I install SweetAlert through bower...
```javascript
  app.import('bower_components/sweetalert/dist/sweetalert.css');
```

...won't work for example. The stylesheet just isn't imported. JavaScript files seem to work fine though.

**Comment by rwjblue** [comment]
Can someone provide a small reproduction of this so we can take a look at what is happening?

**Comment by t4t5** [comment]
As I took a closer look, it seems like it's the [ember-component-css addon](https://github.com/ebryn/ember-component-css) that's causing the [issue](https://github.com/ebryn/ember-component-css/issues/121) for me.

So this might not be a problem that need to be solved in Ember CLI.

**Comment by stefanpenner** [comment]
@t4t5 ya unfortunately i think the issue is in the addon, as it does monkey patch many private things.

If the issue can be demonstrated in a vanilla ember-cli app (without that addon) we can reopen.

Be sure to open a new issue on that addon, so it is correctly tracked. A comment on a closed issue may get forgotten

**Comment by andrewjdavison** [comment]
Has anyone encountered this recently? I have a vanila, css "@import" in app.css which isn't working. When I manually copy the styles into app.css it works.

I don't use ember-component-css, so it could be something in the latest build (I upgraded to the (b)leading edge last night....

Thanks

Andy

**Comment by nathanhammond** [comment]
@andrewjdavison can you open a new issue and include a reproduction of the behavior that you're encountering?
