### ISSUE TITLE
Need easier method for upgrading Ember-cli

### ISSUE THREAD

**Issue by ptmoy2** [ember-cli/ember-cli#5425]
Upgrade instructions https://github.com/ember-cli/ember-cli/releases are easy enough to follow. 

Problem is making the wrong choice during the last step (i.e. deciding what to do in response to the 'ember init' command).  Sometimes it's hard to decide what's the right thing to do when differences identified are in Ember-Cli-generated files.   I tried upgrading a project from version 1.13.12 to 2.3.0 twice on a project.  Result was a big non-working mess each time.  In both cases, I had to revert back to 1.13.12 to make things work again.

**Comment by kellyselden** [comment]
Do you have any suggestions? Have you used this? https://github.com/kellyselden/ember-cli-output/compare/v1.13.12...v2.3.0-beta.1

**Comment by stefanpenner** [comment]
we have plans to provide a 1.x -> 2.x guide before 2.x is final

**Comment by ptmoy2** [comment]
This: https://github.com/kellyselden/ember-cli-output/compare/v1.13.12...v2.3.0-beta.1 is useful info.  But seems like most of the changes highlighted are specific to Ember-cli, and can be made automatically.  Maybe Ember-cli can make the changes that it knows is necessary, and merger the remaining differences with highlight for user to review.  It's not perfect, but a step forward.  Most of the mistakes that kill me during upgrade attempts are from making the wrong choice with changes in files generated by Ember-cli.

**Comment by kellyselden** [comment]
@ptmoy2 This would be perfect for an [RFC](https://github.com/ember-cli/rfcs) if you have some examples of how it can improve.

**Comment by stefanpenner** [comment]
Yes. In fact that is all ember-cli is likely to provide. Changes in ember are not in scope for this project.

Please note you can run 1.13 ember with 2.x ember-cli just leave your ember version unchanged. At which point I would recommend following depreciations until 2.x jump is possible.
