### ISSUE TITLE
Test view hides first failing test when the first two tests fail within a test file on a refresh

### ISSUE THREAD

**Issue by dustinspecker** [ember-cli/ember-cli#5428]
I'm not sure where the bug actually exists, just shooting it here in case folks have ideas.

1. Clone https://github.com/dustinspecker/hides-first-test-when-first-two-fail and start the Ember server
1. Navigate to `locahost:4200/tests`
1. Select any module that is **not** the `hello-world` component
1. Refresh the page
1. Select the `hello-world` integration test module
1. Notice two tests fail.
1. Refresh the page
1. Only the second test is displayed
1. Can keep refreshing the page and the test does not come back

If you select another module, refresh the page, and then go back to the `hello-world` module the two tests appear. Then refresh and the first one is gone again.

Any existing tests after the first two do run. If these two tests are not the first two tests everything works as expected. This seems to just happen when they are the first two tests.

We've been able to reproduce this for unit, integration, etc and for routes, components, etc.

ember: 1.13.15
node: 5.2.0
npm: 3.5.0
os: linux x64

This happens in Chrome 48. We've also validated this existence on a Windows 7 box with IE11.

Thank you.

**Comment by Turbo87** [comment]
this sounds more like a QUnit frontend bug to me

**Comment by stefanpenner** [comment]
@trentmwillis you may be the individual with the most context for this part, mind looking into it?

**Comment by nathanhammond** [comment]
This is very likely going to be a https://github.com/jquery/qunit bug. As this isn't actionable on the Ember CLI side I am closing this bug.

Pinging @trentmwillis for tracking.

**Comment by trentmwillis** [comment]
Somehow missed this the first time around. Will take a look when I get some time.
