### ISSUE TITLE
Attempting to use validator-js fails

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#5429]
Unable to import the validator-js in my ember CLI app although it seems configured correctly: https://github.com/chriso/validator.js/blob/master/validator.js#L29

```js
// my-component.js
import validator from 'validator';
export default Ember.Component.extend({
  didInsertElement() {
    validator.isEmail('foo@gmail.com');
  }
});
```

**Comment by stefanpenner** [comment]
Can you provide a quick app that demonstrates the issue, i'll gladly take a look.

**Comment by stefanpenner** [comment]
will gladly reopen if my above comment is addressed
