### ISSUE TITLE
Add path option to in-repo-addon blueprint

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#5436]
Currently, all in-repo-addons are generated into a `lib` directory. If you want to change the location you can do so manually, but with the coming of engines and specifically in-repo-engines, I wonder if it would be good to build in a `path` option. That way you can organize code in a more semantic way.

For example, maybe your app is broken up into different `areas`, so you want to generate engines at `areas/<name>`. Or maybe you have some build addons you want to live at `tools/<name>`.

As always, if this sounds good I'll take on implementing it.

**Comment by rwjblue** [comment]
Sounds good to me.

**Comment by Turbo87** [comment]
closing as related https://github.com/ember-cli/ember-cli/pull/5448 got closed too
