### ISSUE TITLE
App config is not properly merged in version 2.3.0-beta.2 

### ISSUE THREAD

**Issue by holandes22** [ember-cli/ember-cli#5439]
Hi,

After upgrading to latest beta (2.3.0-beta.2) several tests broke in my app.

The problem was in the ember-cli-flash addon. After doing some debugging I saw that the configuration options for the addon are not being merged correctly.

The addon in question uses the following defaults https://github.com/poteto/ember-cli-flash/blob/develop/config/environment.js

My app extends the configuration like so:

```
# config/environment.js

ENV: {
...
    flashMessageDefaults: {                                                                                                                                                      
      timeout: 4000,                                                                                                                                                             
      types: ['positive', 'negative']                                                                                                              
    },   
...
}
```
In version 2.3.0-beta.1 the config that gets to the addon is:

```
    flashMessageDefaults: {                                                                                                                                                      
      timeout: 4000,                                                                                                                                                             
      types: ['positive', 'negative', 'warning', 'danger', 'alert', 'secondary']   // My 2 values replaced the first 2 values from the default                                                                                                              
    },   
```

where the two types I defined are indeed merged (works, but not sure if it is correct either, shouldn't the default array be extended?)

But, when I use ember cli 2.3.0-beta.2, I instead get:

```
    flashMessageDefaults: {                                                                                                                                                      
      timeout: 4000,                                                                                                                                                             
      types: ['success', 'info', 'warning', 'danger', 'alert', 'secondary']  // My 2 values are not added/merged and only the defaults remain                                                                                                            
    },   
```

Also, weirdly, if I add in my config more items than the defaults defined by the addon in the types attr (i.e. types: ['1', '2', '3', '4', '5', '6', 'positive', 'negative']) the addon gets:

     ["success", "info", "warning", "danger", "alert", "secondary", "positive", "negative"]

(I'm using this as a workaround for now, but ofc not a real solution)

I opened also an issue at the addon project https://github.com/poteto/ember-cli-flash/issues/127 because I'm not sure if the problem is in the addon or ember-cli

**Comment by rwjblue** [comment]
This might be related to some replacement of lodash-node, but I'm unsure. I'll try to dig some more into what changed to be sure....

**Comment by holandes22** [comment]
I'm guessing is related to the merge function. 
I tried this simple node script:

```
var _ = require('lodash');

var defaultConfig = {
  a: 1000,
  types: ['a', 'b', 'c']
}

var config = {
  a: 2000,
  b: 1,
  types: ['foo', 'bar']
}

console.log('merged', _.merge(defaultConfig, config));
```

with both lodash 3.6.0 (beta1) and lodash 4.0.0 (beta2) but I get the same output:

     merged { a: 2000, types: [ 'foo', 'bar', 'c' ], b: 1 }

not familiar with node, so I might be way off here

**Comment by jcope2013** [comment]
I tracked it down, it is a bug in lodash 4 it seems https://github.com/lodash/lodash/issues/1987

**Comment by holandes22** [comment]
@jcope2013 awesome, apparently a fixed was merged, so I guess this would be fixed by upgrading to the next lodash version.

@rwjblue should we leave this ticket open or there is another ticket to track deps updates?

**Comment by rwjblue** [comment]
There isn't really much we can do here until lodash 4.3.1 is released, but I suspect it won't be too long (there are a bunch of other bug fixes included from [master...97fd947](https://github.com/lodash/lodash/compare/4.3.0...97fd947)). I'm going to close this, as when the new version lands we will get it automatically (we are using `^4.0.0`).

I'm sure @jdalton and the rest of the lodash crew are workin' on it...

**Comment by jdalton** [comment]
Yep, should be released this evening or the morning after.

**Comment by rwjblue** [comment]
@jdalton - Awesome, thank you!
