### ISSUE TITLE
cannot install ember-cli@2.3.0-beta.2 - Error with fs-extra

### ISSUE THREAD

**Issue by erwin16** [ember-cli/ember-cli#5443]
I tried to install on OSX , and got an unexpected end of input 

pm install -g ember-cli@2.3.0-beta.2
npm ERR! registry error parsing json
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-cli@2.3.0-beta.2"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

npm ERR! Unexpected end of input

=== here are the last lines in npm-debug.log

`3482 error {"_id":"fs-extra","_rev":"291-402993c2b021dc0f96707a744644dd3a","name":"fs-extra","description":"fs-extra contains methods that aren't included in the vanilla Node.js fs package. Such as mkdir -p, cp -r, and rm -rf.","dist-tags":{"latest":"0.26.5"},"versions":{"0.0.1":{"name":"fs-extra","version":"0.0.1","description":"fs-extra contains methods that aren't included in the vanilla Node.js fs package.","homepage":["https://github.com/jprichardson/node-fs-extra"],"repository":{"type":"git","url":"git://github.com/jprichardson/node-fs-exra.git"},"keywords":["fs","file","file system","copy"],"author":{"name":"JP Richardson","email":"jprichardson@gmail.com"},"licenses":[{"type":"MIT","url":"http://github.com/jprichardson/node-fs-extra/raw/master/LICENSE"}],"dependencies":{"coffee-script":">=1.0.1","jasmine-node":">=1.0.12","path-extra":">=0.0.1"},"bin":{"TEST_file-extra":"./bin/TEST_file-extra"},"main":"index","_npmUser":{"name":"jp","email":"jprichardson@gmail.com"},"_id":"fs-extra@0.0.1","devDependencies":{},"engines":{"node":"*"},"_engineSupported":true,"_npmVersion":"1.0.104","_nodeVersion":"v0.4.12","_defaultsLoaded":true,"dist":{"shasum":"3b98a23769ed92961f81653fe9f347092fa67f3c","tarball":"http://registry.npmjs.org/fs-extra/-/fs-extra-0.0.1.tgz"},"maintainers":[{"name":"jp","email":"jprichardson@gmail.com"}],"directories":{}},"0.0.11":{"name":"fs-extra","version":"0.0.11","description":"fs-extra contains methods that aren't included in the vanilla Node.js fs

`

**Comment by erwin16** [comment]
finally got it installed by running before : 

     npm config set registry http://registry.npmjs.org

**Comment by stefanpenner** [comment]
Woah strange. I would also recommend updating to a newer npm if that possible. Some things have been fixed
