### ISSUE TITLE
Fix `ember version`'s NPM version output.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#5447]
Currently, ember-cli installs its own local copy of `npm` (so that we can use it from `ember install foo`).  Unfortunately, that makes the NPM output from `ember version` completely useless:

```
% ember version
version: 2.2.0-beta.3
node: 4.2.4
npm: 2.14.10
os: darwin x64
```

IMO, we should either "fix" the listed `npm` version number (so that it shows the system's default `npm version`), or remove it from the `ember version` command output.

**Comment by kellyselden** [comment]
What about both, if both are useful in debugging?
```
% ember version
version: 2.2.0-beta.3
node: 4.2.4
npm-system: 3.0.0
npm-local: 2.14.10
os: darwin x64
```

**Comment by rwjblue** [comment]
@kellyselden - Absolutely, I think both would be totally good also.

**Comment by stefanpenner** [comment]
both is tricky, is annoying as it must shell out.

**Comment by btecu** [comment]
Could we rely on the global npm instead of installing another copy?

**Comment by stefanpenner** [comment]
> Could we rely on the global npm instead of installing another copy?

we once did this, and due to instability it was a disaster.
