### ISSUE TITLE
Make ember-cli branding more configurable

### ISSUE THREAD

**Issue by IgorMinar** [ember-cli/ember-cli#5451]
follow up issue after discussion with @stefanpenner 

related commit: https://github.com/angular/angular-cli/commit/1a5646631ab049d4d15dcc1238ee7d21192d457c pr: https://github.com/angular/angular-cli/pull/157

**Comment by rwjblue** [comment]
:+1: - We'd love a PR to help angular-cli remove these sorts of nasty hacks.

**Comment by stefanpenner** [comment]
I'll try to make some time for this this week, but if someone beats me to it. I'll gladly review a pr instead

**Comment by nathanhammond** [comment]
Dropping this issue back to @hansl.

**Comment by Turbo87** [comment]
Given that `angular-cli` has completely forked by now and is not contributing anything back I guess we can close this issue...
