### ISSUE TITLE
Install addon from Github enterprise URL fails with error

### ISSUE THREAD

**Issue by jaichandra** [ember-cli/ember-cli#5452]
I am trying to install a private addon from **github enterprise** url and it fails with below error: 

Command executed: 
`ember install git+ssh://git@url_to_git_repo.git `

Error:
`Install failed. Could not find addon with name: git+ssh://git@url_to_git_repo.git`

---
The command seems to work fine for other github public repos. I am also able to access the github enterprise private repo directly.

**Comment by stefanpenner** [comment]
I'll have to try from our enterprise install. I am surprised it doesn't work, since we literally delegate to npm here

**Comment by runspired** [comment]
I've encountered this and been able to directly `npm` install when `ember install` would not work.

**Comment by jaichandra** [comment]
yes. `npm install` works for me. But the Blueprint is not executed. Im a newbie here, but I think blueprint is executed only when we use `ember install`. Correct me if Im wrong.

**Comment by runspired** [comment]
Ember g <addon-nam>

**Comment by stefanpenner** [comment]
we do still bundle an old npm (newer version where quite unstable) maybe its time to give upgrading a try

**Comment by jaichandra** [comment]
`ember g git+ssh://git@url_to_git_repo.git` throws an `Unknown blueprint: git+ssh://git@url_to_git_repo.git error`

**Comment by runspired** [comment]
@jaichandra that would, it's the addon's name (defined in `index.js` / `package.json`) that you use, not the repo path, when running the generator.

If the git url (`url_to_git_repo`) is of the form `git@github.com:<org>/<name>.git`, then it's likely but not guaranteed to be the `name` portion of that.

**Comment by jaichandra** [comment]
Thanks for the pointer. There was a name mismatch. Its working now.

**Comment by runspired** [comment]
@stefanpenner I recommend reopening this as it IS an issue that the existing bundled `npm` cannot handle `git+ssh` or `git` urls.  I *think* it handles `https` urls, but there may have been an issue there too.

**Comment by jaichandra** [comment]
for me `ember install git+ssh://git@url_to_git_repo.git#develop` worked.

**Comment by runspired** [comment]
@jaichandra oh? interesting. It's definitely not worked at all for me in the past, or at least, if it did work it failed to properly add the dependency to `package.json`.  I may also be remembering the `addPackageToProject` api, which may have different rules.

**Comment by jaichandra** [comment]
even the blueprint executed fine and installed all dependencies. Also, package.json is updated properly.

**Comment by runspired** [comment]
In that case, close this, if I stumble into this again in `addPackageToProject` I'll open a new issue for that specifically.
