### ISSUE TITLE
Livere-load not working in 2.3.0-beta.2

### ISSUE THREAD

**Issue by pieter-v** [ember-cli/ember-cli#5453]
The live-reload snippet is not injected in the index.html when 'ember serve' is running

**Comment by rwjblue** [comment]
I am not able to reproduce this.  I did:

1. `ember serve`
2. Update `app/templates/application.hbs`
3. Browser updates.

Can you provide a demo repo and steps to reproduce?

**Comment by stefanpenner** [comment]
Will gladly reopen if reproduction or further details can be provided
