### ISSUE TITLE
2.3.0-beta.2 causes ember-cli-deploy-gzip to compress the file twice

### ISSUE THREAD

**Issue by varoot** [ember-cli/ember-cli#5454]
Possibly similar to #5445, when re-deploy without clearing tmp folder, the assets that do not use fingerprint get re-gzipped and become corrupt. This does not happen with 2.3.0-beta.1

**Comment by rwjblue** [comment]
I believe this is fixed by https://github.com/stefanpenner/tree-sync/pull/1 (and released in `tree-sync@1.0.2`), can you `rm -rf node_modules && npm install` then confirm?
