### ISSUE TITLE
Fix ESLint issues

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5456]
#5455 enables ESLint for the codebase, but some of the tests have been disabled for now because ESLint seems to be better at finding issues than JSHint. This is the list of currently disabled rules that either need to be fixed, or should be removed from the config:

- [ ] [`no-proto`](http://eslint.org/docs/rules/no-proto.html) (JSHint `proto`)
- [x] [`strict`](http://eslint.org/docs/rules/strict.html) (JSHint `strict`)
- [x] [`indent`](http://eslint.org/docs/rules/indent.html) (JSHint `indent`)
- [ ] [`quotes`](http://eslint.org/docs/rules/quotes.html) (JSHint `quotmark`)
- [ ] [`dot-notation`](http://eslint.org/docs/rules/dot-notation.html) (JSHint `sub`)

**Comment by Turbo87** [comment]
@stefanpenner what's your opinion on the http://eslint.org/docs/rules/no-proto.html rule?

**Comment by stefanpenner** [comment]
@Turbo87 if all our target environment have `Object.getPrototypeOf` and `Object.setPrototypeOf` I am fine with enforcing it

**Comment by Turbo87** [comment]
@stefanpenner the problem is that some of our code is currently failing that ESLint rule and I'm not sure if and how it should be fixed

**Comment by stefanpenner** [comment]
> @stefanpenner the problem is that some of our code is currently failing that ESLint rule and I'm not sure if and how it should be fixed

which code?

**Comment by Turbo87** [comment]
```
/Users/tbn/Code/ember-cli/lib/broccoli/ember-addon.js
  57:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/ext/promise.js
  19:3  warning  The '__proto__' property is deprecated  no-proto
  38:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/addon-discovery.js
  28:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/addon.js
  116:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/addons-factory.js
  23:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/blueprint.js
  288:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/command.js
  92:1  warning  The '__proto__' property is deprecated  no-proto

/Users/tbn/Code/ember-cli/lib/models/task.js
  11:1  warning  The '__proto__' property is deprecated  no-proto
```

**Comment by stefanpenner** [comment]
`Object.setPrototypeOf(EmberAddon, EmberApp)` would work, unfortunately node 0.10.x doesn't seem to have that feature yet.

So lets turn off that warning, and be done with it. I dont think __proto__ is going away, although the preferred approach is as described above

**Comment by Turbo87** [comment]
@stefanpenner okay, I've removed the rule in #5544
