### ISSUE TITLE
minifyCSS compatibility backgroundSizeMerging option has no effect

### ISSUE THREAD

**Issue by jusfeel** [ember-cli/ember-cli#5469]
Ember-cli: version: 2.3.0-beta.2

Below CSS will minify into something with the new CSS3 `background-size` shorthanded into one line with background. I don't know if the merging is correct in syntax with the `/cover ` inserted but it stops Safari on iphone4 to display the image in the background. So I want to use the minifyCSS options. But it seems not working. See my code below.

```
  html {margin:0;padding:0;}
  body {
    background: url("../hillwave_bg_m.jpg");
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    margin:0;
    padding:0;
  }
```
after minify

`html{margin:0;padding:0}body{background:url("../hillwave_bg_m.jpg") center center/cover no-repeat fixed;-webkit-background-size:cover;-moz-background-size:cover;-o-background-size:cover;margin:0;padding:0}`

disable merging background-size in ember-cli-build.js based on https://github.com/jakubpawlowicz/clean-css#how-to-set-a-compatibility-mode
```
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
    minifyCSS: {
      enabled: true,
      compatibility: '-properties.backgroundSizeMerging'
    }
  });


```

`

**Comment by rwjblue** [comment]
We just upgraded the version of broccoli-clean-css that we were using on master (not released in a version yet). The version shipped with ember-cli@2.3.0-beta.2 was apparently fairly old and I wonder if they have already fixed this upstream. 

Could you test this against master and see if it has the same issues?

**Comment by jusfeel** [comment]
The master works. :100:

**Comment by rwjblue** [comment]
Awesome, I'll close this for now then.  We should have a release shortly that will bundle up those fixes...
