### ISSUE TITLE
App.import does not work as described

### ISSUE THREAD

**Issue by chrisseto** [ember-cli/ember-cli#5473]
As stated [here](http://ember-cli.com/user-guide/#standard-amd-asset) the following code snippets should work as expected.

ember-cli-build.js
```javascript
 this.app.import(path.join(this.app.bowerDirectory, 'bcryptjs/dist/bcrypt.js'), {
   exports: {
     dcodeIO: ['bcrypt']
   }
 });
```

app/anotherfile.js
```javascript
import bcrypt from 'dcodeIO';

...
```

But it results in:
```
Uncaught Error: Could not find module `dcodeIO` imported from `anotherfile.js`
```

From my quick browsing of the [code base](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1347) it appears that this functionality is not available at all.

**Comment by stefanpenner** [comment]
this seems to work as expected,
