### ISSUE TITLE
this.project is undefined in Blueprint.supportsAddon()

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5481]
The `install()` method of the `Blueprint` class is currently responsible for setting `this.project`. Since `supportsAddon()` is called before the `install()` method though `this.project` is not yet set which can cause issues in certain implementations of the `filesPath()` method (e.g. different paths depending on the installed test framework).

**Comment by rwjblue** [comment]
We should pass `project` to create on blueprints...

**Comment by stefanpenner** [comment]
> We should pass project to create on blueprints...

ya, seems reasonable.

**Comment by trentmwillis** [comment]
> We should pass `project` to create on blueprints...

@rwjblue should it just be `project` or should we pass in the entire [`blueprintOptions`](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/generate-from-blueprint.js#L41-L58) at creation? Seems like the latter could be more beneficial as it would solve use cases like in dgeb/ember-engines#60, where we needed to make a `filesPath` decision on an command option.

**Comment by trabus** [comment]
@trentmwillis There is no easy way to pass the blueprintOptions at creation due to the way they are retrieved through the `lookup` function.

I think passing in the project for that specific method will have to suffice for the time being, and we can look to address this in future refactorings of blueprint.

**Comment by trentmwillis** [comment]
:+1: thanks for attempting! I think this will give the greatest flexibility to blueprint authors.

**Comment by rwjblue** [comment]
Agreed, if we can do it, we should.  I'm happy to fix the bug in question for now though if that is more straight forward...

**Comment by trabus** [comment]
I got halfway through last week, but am still seeing some calls to lookup that aren't passing the options in. The way we're doing this currently (looking up and providing a constructor) is so convoluted that it's hard to see exactly what might be tapping into it.

**Comment by blimmer** [comment]
Any updates on this or a workaround?

https://github.com/offirgolan/ember-cp-validations/issues/233 shows the symptoms of this bug.
