### ISSUE TITLE
add .github/{ISSUE_TEMPLATE,CONTRIBUTING}.md

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5482]
https://github.com/blog/2111-issue-and-pull-request-templates

We will need to explore exactly what the ISSUE_TEMPLATE will suggest, but this is a good step in the right direction.

**Comment by kellyselden** [comment]
:+1:

**Comment by Turbo87** [comment]
FWIW the rust team decided against using those kinds of templates in https://github.com/rust-lang/rust/pull/31732, though I don't know if their reasons are applicable to our case as well

**Comment by stefanpenner** [comment]
Thanks for the link, will review

**Comment by stefanpenner** [comment]
Looks like we could benefit as long as the structure was extremely light. We should experiment and iterate with it, I think this could still be valuable, although the rust thread outlines the pitfalls we should avoid

**Comment by kellyselden** [comment]
My thoughts are one of the most beneficial things to help us not waste time triaging is a demo repo and steps to reproduce. If a template nudged people to do this, I think it would make our lives better.

**Comment by stefanpenner** [comment]
> If a template nudged people to do this, I think it would make our lives better.

my thoughts as well.

**Comment by Turbo87** [comment]
another example: https://github.com/square/retrofit/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kellyselden** [comment]
I like the mention of StackOverflow.

**Comment by Turbo87** [comment]
https://www.talater.com/open-source-templates/ :joy:

**Comment by Turbo87** [comment]
resolved by #5707
