### ISSUE TITLE
`ember i` should alias `ember install`

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5489]
Currently `ember i` aliases `ember init` for reasons of timeline and/or alphabet. We need to make it such that `ember i` aliases the intended (and much more frequently used) `ember install`.

**Comment by Turbo87** [comment]
It looks like `ember i` was in fact not introduced "for reasons of timeline and/or alphabet" but explicitly by 682df0e3d194f140024e7edd63e056156256905a. I still think that it should be changed to `ember install` though to make it more similar to `npm i` and `bower i` and I don't think anyone is actually using it as a shortcut for `ember init`.
