### ISSUE TITLE
Babel trying to parse handlebars file

### ISSUE THREAD

**Issue by Frozenfire92** [ember-cli/ember-cli#5492]
I upgraded to Ember cli 2.3 from 1.13 and everything seemed to go smoothly, however on the first run of ember s I get

```
[BABEL] Note: The code generator has deoptimised the styling of "platform/templates/partials/someform.js" as it exceeds the max of "100KB".
```

when the file in question is actually .hbs is there a setting I need to pass to babel? Is it because its in a non standard template folder?

**Comment by rwjblue** [comment]
Basically, the compiled template output (after the HBS -> JS conversion) for that file is larger than ends up being more than 100k.  This warning only means that the emitted Babel output will not be "pretty formatted", which likely isn't a thing you care about (since folks don't look at the JS output of HBS files very much).

**Comment by rwjblue** [comment]
You can suppress this warning by passing the `compact` option to babel.  

```js
// inside ember-cli-build.js

 var app = new EmberApp(defaults, {
    babel: {
      compact: false
    }
  });

```

Docs here: https://babeljs.io/docs/usage/options/

**Comment by Frozenfire92** [comment]
Thank you! will that cause it not to be minified?

**Comment by rwjblue** [comment]
No, minification is unrelated to babel transpilation (it is done as a separate step later).

**Comment by Frozenfire92** [comment]
Perfect, thanks for clearing this up!

**Comment by zzarcon** [comment]
Thanks for the info @rwjblue, do you also know if setting **compact** false have some kind of performance penalty?

**Comment by rinoldsimon** [comment]
The warning msg still appears when i start `ember serve`
Ember version - `2.18.0`

ember-cli-build.js
```
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    babel: {
      compact: false
    }
  });
  return app.toTree();
};
```
