### ISSUE TITLE
Check for `ember-app` or `ember-addon` when looking for `package.json` files

### ISSUE THREAD

**Issue by bierdybard** [ember-cli/ember-cli#5493]
ember-cli@2.3.0

Example: cwd is `~/Documents/ember`
`ember new new-tool-ui`

The `new-tool-ui` folder is in `~/`, not `~/Documents/ember`

**Comment by rwjblue** [comment]
Hmmm. This is definitely odd.  I just tested locally, and it is using CWD for me.

**Comment by stefanpenner** [comment]
which version of node?

**Comment by bierdybard** [comment]
node v5.5
npm v3.5.3

**Comment by bierdybard** [comment]
Rolled back to the latest LTS node (4.3.1), same result.

node v4.3.1
npm v2.14.12

**Comment by bierdybard** [comment]
Using OS X 10.11.3 as well, if that helps. Node installed via homebrew.

**Comment by rwjblue** [comment]
Does your home directory contain a .ember-cli file and/or a package.json?

**Comment by bierdybard** [comment]
Hmm, yes, a package.json did land there at some point. Clearing that out resolved the issue.

**Comment by rwjblue** [comment]
Can you share what the contents were?  Was it for an ember-cli project?

**Comment by stefanpenner** [comment]
@rwjblue i wonder if we should guard that to only package.json that contain keyword: ember-app or ember-addon

**Comment by rwjblue** [comment]
@stefanpenner - Ya, agreed (was hoping to find out if that package.json was for an ember-cli project to see if that guard would help)

**Comment by bierdybard** [comment]
Hey guys, I don't have the file any longer, but it definitely was not Ember-related, it looked like it was created by DocPad.

**Comment by Turbo87** [comment]
@stefanpenner I just noticed that `package.json` for new apps doesn't include any `ember-app` keyword, so that approach isn't really an option... we could however check if the project includes `ember-cli` as a dependency

**Comment by rwjblue** [comment]
We already have a helper method for that: https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L155-L157
