### ISSUE TITLE
Meta: Issue Labeling

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5500]
[Ember.js](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#issue-labeling) has moved to using [StandardIssueLabels](https://github.com/wagenet/StandardIssueLabels) last year and I would like to propose using the same set of label definitions on this repo/org too.

It was suggested on Slack to open a RFC for that proposal but since this is not touching any code or documentation I think there is no need for that. I'd volunteer moving the current set of labels to the new structure should we decide to adopt it.

/cc @rwjblue @stefanpenner @kellyselden @nathanhammond

**Comment by rwjblue** [comment]
Seems good to me.

**Comment by kellyselden** [comment]
I'm a fan. Our current labels are neglected, so this could help revitalize.

**Comment by stefanpenner** [comment]
:+1:
