### ISSUE TITLE
"ember new" fails on Windows

### ISSUE THREAD

**Issue by tomaszglinski** [ember-cli/ember-cli#5502]
Hi quys,
Running "ember new" hanged for few minutes end ended up with "EBUSY: resource busy or locked, rmdir ..."
I know the #1558 issue from 2014, but it is still not working, maybe there is some new about that?
It blocks the Getting Started for the newbies running on windows... :(

Then, I runned it again few times and got every time a git error:

> Failed to execute "git ls-remote --tags --heads git://github.com/ember-cli/ember-cli-test-loader.git", exit code of #128

That one could be fixed according to http://stackoverflow.com/questions/21544803/git-bower-errors-exit-code-128-failed-connect, by changing the command to

> git ls-remote --tags --heads https://github.com/ember-cli/ember-cli-test-loader.git

Hope I will be able to do the Getting Started soon... :)

**Comment by kellyselden** [comment]
I just ran `ember new my-app` on Windows fine. Maybe you have a network/system config issue. You should post on StackOverflow, maybe someone has experienced something similar.

**Comment by tomaszglinski** [comment]
Thanks for douple checking, Kelly
