### ISSUE TITLE
Migrate from testem.json to testem.js?

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#5503]
Hi. 
I've found myself annoyed, as most people, by the fact that json files cannot have comments, trailing commas and other things that make them less usable that js files, and also you can't access environment variables in json files.

I recently discovered that you can config testem by exporting the same json object. Would you be opened to replace `testem.json` by `testem.js`?
The only difference would be a `module.exports = ` at the beginning of the file (and a jshint comment to mark the file as for node).

Yay comments.

**Comment by rwjblue** [comment]
Ya, I'm game to switch the default...

**Comment by kellyselden** [comment]
:+1: comments in json FTW

**Comment by stefanpenner** [comment]
> Ya, I'm game to switch the default...

:+1:
