### ISSUE TITLE
2.3.0 addon exported files not available on new project.

### ISSUE THREAD

**Issue by Orgil** [ember-cli/ember-cli#5504]
worked on 2.2.0-beta.6, but 2.3 it couldn't find exported files.

create new addon and generate new mixin, then try to import into project with import.

**Comment by rwjblue** [comment]
Hmm, it should be working. Can you share a demo repo?

**Comment by Orgil** [comment]
i've looked little deeper seems my npm cache messed whole thing. So closing it. Thanks.
