### ISSUE TITLE
CI is not completing `bower install` and everytime fails for ember-cli-shims

### ISSUE THREAD

**Issue by shivanibhanwal** [ember-cli/ember-cli#5505]
I am upgrading my Ember.js app to version 1.13.13, ember-cli to 1.13.15 and node to 4.3 accordingly we have updated other packages as well.
However I am successfully able to run my application on local and all tests are passing but whenever we are running build on CI it is breaking with following error.

    bower ECONFLICT Unable to find suitable version for ember-cli-shims Action failed: bower install

Whereas git://github.com/ember-cli/ember-cli-shims.git#0.0.6 this path resolved correctly and if you try downloading it, it works and gets downloaded.
So not sure what is happening here, everytime I am getting error for `ember-cli-shims` and `loader.js`

**Comment by stefanpenner** [comment]
I suspect running `bower cache clear && rm -rf bower_components` locally, will allow you replicate the issue locally. You should then likely pin the correct version of in bower.

Will reopen if that doesn't help
