### ISSUE TITLE
Add preconcatTree hook

### ISSUE THREAD

**Issue by ronco** [ember-cli/ember-cli#5506]
To facility filtering build files from arbitrary addons we would like to see a `preconcatTree` hook added to ember-cli's build cycle.

A patch solution was recently used in `ember-cli-fastboot` [here](https://github.com/tildeio/ember-cli-fastboot/blob/master/lib/ext/patch-ember-app.js) to achieve this.  The use case in that particular instance was to support other addons which may implement different initializers depending on build environment (fastboot or browser).

**Comment by stefanpenner** [comment]
RFC process for new features, as the [CONTRIBUTING.md](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#requesting-a-feature) suggests
