### ISSUE TITLE
Problems building in production mode.

### ISSUE THREAD

**Issue by JonathanBristow** [ember-cli/ember-cli#5514]
I'm having trouble building in production.
Everything works when using -dev but when I change this to -prod the build hangs.

`ember build -dev`
`version: 2.3.0`
`BuildingDeprecation warning: sassOptions should be moved to your ember-cli-build`
`Built project successfully. Stored in "dist/".`

`ember build -prod`
`version: 2.3.0`
`BuildingDeprecation warning: sassOptions should be moved to your ember-cli-build`
`Building... (hangs here)`

I'm using the following: 

`ember -v`
`version: 2.3.0`
`node: 0.12.9`
`os: darwin x64`

From what I can work out, there is no verbose mode so I don't really know where to go from here.

**Comment by stefanpenner** [comment]
I suspect you have a very large file being uglified.

`DEBUG=* ember build --env production` will private alot of output (feel free to gist it) and my guess is it hangs during uglification.

**Comment by JonathanBristow** [comment]
@stefanpenner You are correct - ended up being a uglifiy issue.

**Comment by stefanpenner** [comment]
I suspect we should warn when we encounter a large file that _may_ be slow to uglify. Could you share the bytesize of the file in question?

I would love to investigate a better logging strategy to provide immediate feedback to users here. I'll keep it on the old triage list.

**Comment by JonathanBristow** [comment]
I doubt my issue was size related as the files before they get processed are only about 15 and 10 mb roughly. 
I had a dependency which the uglifiy process didn't like.
