### ISSUE TITLE
"in progress" labels

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5517]
@jakecraige what is the point of those labels any why and how are they applied automatically?

**Comment by stefanpenner** [comment]
I believe some people setup tools like waffle.io which automate such labels. They are commuters, but short of removing their commit bit we can't do much (I think) they must be the ones to disable it

**Comment by Turbo87** [comment]
I see... I guess we could probably remove the hooks at https://github.com/ember-cli/ember-cli/settings/hooks if we decide we don't need those things.

**Comment by stefanpenner** [comment]
Ah. That's likely true, but if they authed to the service it could likely reenable it automagically. (Unsure if it does or not)

**Comment by Turbo87** [comment]
I've disabled those hooks for now and it seems to work

**Comment by stefanpenner** [comment]
> I've disabled those hooks for now and it seems to work

:+1:
