### ISSUE TITLE
component-test blueprint adds '/' in front of the component name

### ISSUE THREAD

**Issue by lpaluszk** [ember-cli/ember-cli#5518]
Using pods.

If I type `ember g component-test test` the test is generated incorrectly with the component name having a '/' added in front.

    import { moduleForComponent, test } from 'ember-qunit';
    import hbs from 'htmlbars-inline-precompile';

    moduleForComponent('/test', 'Integration | Component | test', {
      integration: true
    });

    test('it renders', function(assert) {
      // Set any properties with this.set('myProperty', 'value');
      // Handle any actions with this.on('myAction', function(val) { ... });"

      this.render(hbs`{{/test}}`);

      assert.equal(this.$().text().trim(), '');

      // Template block usage:"
      this.render(hbs`
        {{#/test}}
          template block text
        {{//test}}
      `);

      assert.equal(this.$().text().trim(), 'template block text');
    });

**Comment by stefanpenner** [comment]
what version of ember/node etc?

**Comment by lpaluszk** [comment]
Windows 10
Ember-CLI  - 2.3.0
Node - 5.4.1
Ember - 2.3.1

**Comment by lpaluszk** [comment]
Here's a repo:
https://github.com/lpaluszk/component-test_bug

**Comment by lpaluszk** [comment]
I've looked into this a bit more. The issue is still present on 2.4.2.
``
These 3 lines are responsible:
https://github.com/ember-cli/ember-cli/blob/master/blueprints/component-test/index.js#L45-L47

If component-test is generated alongside the component, options.path is defined but empty, but if component-test blueprint is executed on its own, component.path is undefined and the if statement still evaluates to true (and adds the leading '/').

An easy fix is to change the if statement to check option.path for truthy value and not just empty string.
