### ISSUE TITLE
Attempt to run ember server: Cannot find module 'ember-cli/lib/broccoli/ember-app'

### ISSUE THREAD

**Issue by ahouchens** [ember-cli/ember-cli#552]
This is case where bower can't be installed globally without sudo permissions. After the install of ember-cli and bower globally with sudo permissions, the attempt of running ember server fails on an existing ember-cli project with: 

Cannot find module 'ember-cli/lib/broccoli/ember-app'

**Comment by Nininea** [comment]
I' using the old version of ember-cli - 0.0.44 , after 

> npm install 

> bower install

 commands, I run

>  ember build

 and got the same exception
I also tried

>  npm install -g ember-cli@0.0.44
and the run again  above mentioned commands and still have the same exception
, how can i fix it?
