### ISSUE TITLE
Problem with import momentjs

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#5535]
First, generate the shim:

`ember generate vendor-shim moment`

Next, provide the vendor asset path:

app.import('vendor/shims/moment.js');
Finally, use the package by adding the appropriate import statement:
```
import moment from 'moment';

// ...
var day = moment('Dec 25, 1995');
````

But throw error when run `moment` : `Uncaught (in promise) TypeError: (0 , _moment.default) is not a function(…)``

I using ember-cli 2.3.0

**Comment by lpaluszk** [comment]
Just to confirm, you do import the library itself before your shim?

**Comment by lpaluszk** [comment]
Just to confirm, are you importing moment before your shim?

The following seems to work

    app.import('bower_components/moment/moment.js');
    app.import('vendor/shims/moment.js');

The shim is a default vendor-shim blueprint generated file and moment is from bower. If you're dead keen on using npm I think you may be better off using ember-browserify.

**Comment by villander** [comment]
Solved my problem @lpaluszk thanks :dancer:

**Comment by runspired** [comment]
I opened an RFC issue to discuss a more elegant solution for this: https://github.com/ember-cli/rfcs/issues/84

**Comment by stefanpenner** [comment]
@runspired this is already supported via https://github.com/ember-cli/rfcs/pull/28

**Comment by stefanpenner** [comment]
assuming moment us `amd`:

```js
app.import('bower_components/moment/moment.js', {
  amdModule: 'moment'
})
```
