### ISSUE TITLE
app.legacyFilesToAppend.push is not a function

### ISSUE THREAD

**Issue by Hirtenknogger** [ember-cli/ember-cli#5537]
After updating to Ember-cli 2.4.0 I get the following error:

"ActionView::Template::Error (:frontend has failed to build: app.legacyFilesToAppend.push is not a function)"

**Comment by holandes22** [comment]
Not sure if related, but I got a similar problem with the ember-css-addon

I get `this.vendorStaticStyles.concat is not a function` which appears to be due to a change in the format of the vendorStaticStyles object

I opened a ticket over there https://github.com/ebryn/ember-component-css/issues/121

**Comment by rwjblue** [comment]
These two internal arrays are no longer present in 2.4.0, they were changed into objects in support of the RFC#28 (adding support for outputFile option to app.import).

@stefanpenner - Do you think we should add them back with a deprecation (aka were these internal data structures considered public API?) or just suggest fixing the various addons reaching into these private internals?

**Comment by stefanpenner** [comment]
Although not documented, I do believe these to present themselves as external API's. No _ or anything.

If two people have reported, we should likely restore the API they depend-ended on. My question is, to what extent did they expect `legacyFilesToAppend` to be an array.

**Comment by stefanpenner** [comment]
@holandes22 also a headsup, that add-on is currently also pwning peoples build performance: https://github.com/ebryn/ember-component-css/issues/67 It monkey patches many private things, and sad things result.

**Comment by holandes22** [comment]
@stefanpenner thank you for the warning. I've been experiencing some issues after I started using it so was actually considering removing the dependency
