### ISSUE TITLE
2.4.0 deprecated deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#5539]
from slack

```
npm install`
`npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.`
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`
```

**Comment by btecu** [comment]
I've traced `graceful-fs` and is used in `read-package-json > npm`.

Fortunately, it has been fixed months ago:
https://github.com/npm/read-package-json/commit/5f0c3a1ec7bc2577750934c768dee7e08781a7c9

Updating to a newer `npm` would fix this. Will submit PR shortly.

**Comment by btecu** [comment]
`lodash-node` is used in `core-object`:
https://github.com/ember-cli/core-object/blob/v1.0.0-rc1/package.json

Unfortunately, updating `core-object` is very involved.

**Comment by rwjblue** [comment]
Maybe we can update the tag we are using and issue a patch release

**Comment by rwjblue** [comment]
I don't have a good picture of what is needed to upgrade CoreObject....

**Comment by btecu** [comment]
@rwjblue I think this is closest to an update: https://github.com/ember-cli/ember-cli/pull/3056

**Comment by arcwhite** [comment]
Not sure if this is helpful, but I think this might count as a 'bug' for some users. Following the guide at https://guides.emberjs.com/v2.4.0/getting-started/quick-start/ I installed the v4.4.1 LTS version of nodejs.

After installing ember, `ember serve` would spike my CPU usage to 100%, and serve nothing.

This was remedied by upgrading to v5.9.1 stable of nodejs and uninstalling and reinstalling ember-cli
At the very least it's possible the documentation should have a note attached in the interim...?

**Comment by rwjblue** [comment]
Hmm.

 @arcwhite - What makes it seem like that is related to this issue? I'm not really seeing a connection...

Also, in general we run tests in CI on node 0.10, 0.12, 4.x, and 5.x so it should work...

**Comment by Turbo87** [comment]
from the latest Travis run:

```
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

**Comment by Turbo87** [comment]
some of these warnings will hopefully be fixed by:
- https://github.com/chjj/marked/pull/739
- https://github.com/twokul/yam/pull/11
- https://github.com/mochajs/mocha/pull/2201

**Comment by mxgoncharov** [comment]
`npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

How can I fix it?

**Comment by Turbo87** [comment]
@mxgoncharov by fixing/adjusting those dependencies

**Comment by mdentremont** [comment]
Created https://github.com/chjj/marked/pull/768 to resolve the issue in marked

**Comment by nathanhammond** [comment]
Closing this issue as I believe that all open deprecation alerts are in Node projects outside of our sphere of influence. If new ones crop up please try and track down where they are in the tree and file issues with that repository maintainer:

`npm ls package-name-here`

**Comment by nathanhammond** [comment]
@mdentremont Thank you for opening that PR to get the upstream package fixed! You'll likely have to walk it up the dependency tree bumping versions until it makes it back to us.
