### ISSUE TITLE
Testem livereload mostly broken

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#5543]
When testing with `ember test --server`, it seems to fail to properly connect to the tests running in Chrome. A new testem tab is created each time the test page is opened, and it gets stuck at `0/0` or `0/1`.

> ![](https://i.imgur.com/SdA18l7.png)

The test page in Chrome doesn't throw any errors and correctly executes all my tests. Changing a file or hitting ENTER in testem causes phantomjs to re-run the tests but the test page in Chrome does not react. After a while, testem shows an error for the Chrome testem tab: `Browser undefined failed to connect. testem.js not loaded?`.

When the test server is killed, the page starts complaining about a `net::ERR_CONNECTION_REFUSED` error for `GET http://localhost:7357/socket.io/?EIO=3&transport=polling&t=LCq2xiU` so it seems like at least some connection was made.

Using:
 * `ember-cli@2.4.0` (though was seeing this with `2.3.0` as well)
 * `ember-cli-mocha@0.10.0`
 * `chai#3.5.0`
 * `ember#2.4.1` (though was seeing this with `2.3.0` as well)
 * `ember-cli-test-loader#0.2.2`
 * `ember-mocha-adapter#0.3.1`
 * `mocha#2.4.5`

**Comment by stefanpenner** [comment]
can you share a reproduction, as the default installation appears to work as expected.

**Comment by SaladFork** [comment]
Interesting, looks like the issue only manifests if you visit `http://localhost:7357/tests/index.html` to run the tests rather than `http://localhost:7357/###/tests/index.html` (where `###` seems to be some number injected by testem when visiting the the root folder).

**Comment by stefanpenner** [comment]
Shouldn't it redirect you to ### variant?

**Comment by SaladFork** [comment]
If you visit `http://localhost:7357/` it will correctly redirect you to `###` but visiting `http://localhost:7357/tests/index.html` (the URL we used to use) directly does not.

**Comment by stefanpenner** [comment]
This seems expected, but if `/test/index.html` should do something else, that should be opened over at testem.

**Comment by rwjblue** [comment]
Did this work correctly in 2.3.0? We changed a bit around how testem communicates with the outside world (we use postMessage now), and there is code that is determining the custom pid variant. It is possible that we have a bug when the pid/client id/whatever isn't present. 

@bantic - Do you think ^^ is a possible culprit?

**Comment by stefanpenner** [comment]
If it did work. We can reopen

**Comment by rwjblue** [comment]
Ya, even if it did, it would be fixed upstream without changes needed from us (since we are `^1.x.x` now).

**Comment by bantic** [comment]
@SaladFork Can you confirm which version of testem you are on (`npm ls | grep testem`)? And what changes if any have you made to the stock `testem.json`?
And just for context can you explain why your setup wants to hit the `/tests/index.html` directly?

I'll see if I can repro and investigate.

**Comment by SaladFork** [comment]
I have no need to access `/tests/index.html` directly, but it was a bookmark I had set up from previous versions (which did not add the `###`). 

I'm not including `testem` myself but am using the included version:
```
my-app@1.0.0
  └─┬ ember-cli@2.4.0
    └── testem@1.4.2
```
