### ISSUE TITLE
ember-cli 2.4.1  path must be a string

### ISSUE THREAD

**Issue by donovan-graham** [ember-cli/ember-cli#5552]
I am getting the following error when running the different `ember g` commands. 
(Running on ember-cli@2.4.1)

```
path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
```

**Comment by stefanpenner** [comment]
seems to be working for me, can you share more information to help me reproduce?

```
➜  must-be-a-string git:(master) ember g component foo-asdf
version: 2.4.1
installing component
  create app/components/foo-asdf.js
  create app/templates/components/foo-asdf.hbs
installing component-test
  create tests/integration/components/foo-asdf-test.js
```

**Comment by donovan-graham** [comment]
I have tried this again on a different computer and all seems to be working.   

I'll need to debug the original environment and see whats causing this.  Thanks for the quick feedback.

**Comment by donovan-graham** [comment]
I've isolated the error to being how the certificate file is being read in.  If I set `"strict-ssl": false` in my .bowerrc file, it works. If I have `"ca": "ca-certificates.crt"` in .bowerrc, it fails. 

The errror
```
at readCertFile (/home/donovangr/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/bower-config/lib/Config.js:42:27)
```

.bowerrc
```json
.bowerrc
{
  "directory": "bower_components",
  "analytics": false,
  "registry": "https://proxy/artifactory/api/bower/bower",
  "ca": "/etc/ssl/certs/ca-certificates.crt",
  "resolvers": [
    "bower-art-resolver"
  ]
}
```

**Comment by stefanpenner** [comment]
This seems like a bower issue?
