### ISSUE TITLE
Ember-cli home page still refers to 2.3.0

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli#5553]
Looks like the Ember-cli home page has not been updated to the current version as listed in npm (2.4.1 as of this issue). Also the Changelog section does not reflect the latest version. Does this mean 2.3.0 is still the latest stable release?

**Comment by stefanpenner** [comment]
fixed website: https://github.com/ember-cli/ember-cli.github.io/commit/b9b1c0b335803e80258a0f1777e6357e73bb6132

**Comment by baron1405** [comment]
Thanks for the quick response.

**Comment by rwjblue** [comment]
Ugh, sorry :crying_cat_face:
