### ISSUE TITLE
Error when vendor library being minified during build --prod

### ISSUE THREAD

**Issue by pmkhoa** [ember-cli/ember-cli#5555]
This looks like a very rare case when the minification/uglification process during `ember build --prod`  replaced `$super` by random character `e`, and caused an error `vendor-7ff....js:11 TypeError: e is not a function`.

Specifically, I use library call Rickshaw, and here is the [unminified code](https://github.com/shutterstock/rickshaw/blob/52867709195f71303e588c58b71a5aa6abb09f95/src/js/Rickshaw.Graph.Renderer.Line.js#L7). As we can see `$super` is not a regular param here, and therefore shouldn't  be uglified.

Is there any suggestion how to resolve this? Please advise. 
Thanks!

**Comment by stefanpenner** [comment]
We just delegate to uglify. I am unsure if this is something on our end. If someone can demonstrate it being an issue here. That would be great

**Comment by pmkhoa** [comment]
What js uglify do you use? I think this is only related to uglify plugin, rather than ember cli `build` command.

**Comment by stefanpenner** [comment]
uglify

**Comment by stefanpenner** [comment]
if that $super is stripped, it would most likely be a bug in uglify

**Comment by pmkhoa** [comment]
Found a doc from here about reserved names: https://github.com/mishoo/UglifyJS/blob/2bc1d02363db3798d5df41fb5059a19edca9b7eb/README.html#L558

Is this something that is included in ember-cli-uglify?

**Comment by stefanpenner** [comment]
options can be provided via `minifyJS = { }`  in ember-app, as documented here. http://ember-cli.com/user-guide/#minifying Options their are likely to be passed through to uglify.

**Comment by pmkhoa** [comment]
Could you please give me an example for passing options to uglify? This is what I'm trying to do:

      minifyJS: {
          options: {
             mangle: true,
             reserved: '$super'
          }
      }

Those options are from this: https://github.com/mishoo/UglifyJS2#mangler-options. I still didn't work. The $super keyword is still being uglified.
Thanks!!

**Comment by stefanpenner** [comment]
As per [CONTRIBUTING.md](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#questions) questions are best asked on stackoverflow, as it is a venue suited for Q/A.  This issue tracking is primarily for tracking issues.

**Comment by pmkhoa** [comment]
Sounds good. Thanks!

**Comment by stefanpenner** [comment]
:)

**Comment by stefanpenner** [comment]
if a issue does arise feel free to let us know, we can try to address.
