### ISSUE TITLE
Problem with ember-ajax after upgrading to amd-name-resolver 0.0.5

### ISSUE THREAD

**Issue by batok** [ember-cli/ember-cli#5559]
After upgrading to commit 02943bbf0 of ember-cli , amd-name-resolver 0.0.5 detects ember-ajax as bad.  I tried also with latest commit of ember-ajax itself, but had the same problem.

**Comment by stefanpenner** [comment]
Can you share more information please

**Comment by rwjblue** [comment]
Possibly related to https://github.com/ember-cli/ember-cli/pull/5560.  Without https://github.com/ember-cli/ember-cli/pull/5560 no ember-cli app will build...
