### ISSUE TITLE
Watch additional files and directories?

### ISSUE THREAD

**Issue by jleppert** [ember-cli/ember-cli#5563]
Why isn't there a simple and easy to use API for adding files and directories to be watched as part of the build?

Something like `app.watch(root, "glob pattern");` would be really nice...

**Comment by stefanpenner** [comment]
wouldn't be very hard, could you share some more concrete use-cases. ? Also this is likely better presented as an RFC: github.com/ember-cli/rfcs

**Comment by jleppert** [comment]
There are lots of use cases where you'd want to external watch files. In my case, I'm working on some vendor files as part of the main application.

In case anyone is wondering and needs an easy way to watch other files that aren't part of your main application you can use something a little more robust running in a node server (such as gulp) to watch and build your files. Add this to any random vendor file and then app.import it:

```
var script = document.createElement("script");
script.src = "http://localhost:8000/dev.js";
var wrap = document.createElement('div');
wrap.appendChild(script);
document.write(wrap.innerHTML);
````

**Comment by cbou** [comment]
@stefanpenner I import some files using `app.import` inside `ember-cli-build.js` and want to watch them.
