### ISSUE TITLE
Babel errors when updating to Ember CLI 2.4.1

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#5567]
EDIT:

Disregard what I said below. It looks like `ember init` is putting `bower_components` in my app folder. Any idea why that is happening? That was causing all the errors.

~~I was trying to get my addons all updated to 2.4.1 and I am getting a bunch of Babel errors on all of them. Things like this:~~

```
File: dummy/bower_components/jquery/src/intro.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: dummy/bower_components/jquery/src/intro.js: Unexpected token (45:0)
```

```
File: dummy/bower_components/blanket/dist/mocha/blanket_mocha.min.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: dummy/bower_components/blanket/dist/mocha/blanket_mocha.min.js: Unexpected token (40:8)
```

~~A few issues here. I am not using mocha and I completely removed blanket and I still get the error. I also am not sure where intro.js came from. Seems like random files from bower dependencies perhaps. Why is Babel running on these?~~

~~I saw there were some changes to `app.import`, do I need to change my blueprints, index.js, or ember-cli-build.js?~~

~~No idea what is happening here.~~

**Comment by rwwagner90** [comment]
Looks like it's creating  app/bower_components in my addon now. Not sure why it is doing that.

**Comment by Turbo87** [comment]
@rwwagner90 can you provide steps to reproduce this problem?

**Comment by rwwagner90** [comment]
I started off in my addon project and ran the following steps:

I am using nvm and I installed node 5.7.1. Then I run `npm install -g bower` which installs bower 1.7.7.

Then I run `npm install -g ember-cli@2.4.1`

Then I clear everything out with `rm -rf node_modules bower_components dist tmp`

I then `npm i && bower i` in my addon, and then run `ember init`. When it got to the bower install part, it was putting everything in app/bower_components.

Well, I just ran these steps on another computer, and I did not have any issues, so maybe I just need to blow everything away on my other machine and try again.

**Comment by ChangJoo-Park** [comment]
@rwwagner90  I try to your direction, but I stuck in same issue.

````js
/*!
 * jQuery JavaScript Library v@VERSION
 * http://jquery.com/
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: @DATE
 */

(function( global, factory ) {

	if ( typeof module === "object" && typeof module.exports === "object" ) {
		// For CommonJS and CommonJS-like environments where a proper `window`
		// is present, execute the factory and get jQuery.
		// For environments that do not have a `window` with a `document`
		// (such as Node.js), expose a factory as module.exports.
		// This accentuates the need for the creation of a real `window`.
		// e.g. var jQuery = require("jquery")(window);
		// See ticket #14549 for more info.
		module.exports = global.document ?
			factory( global, true ) :
			function( w ) {
				if ( !w.document ) {
					throw new Error( "jQuery requires a window with a document" );
				}
				return factory( w );
			};
	} else {
		factory( global );
	}

// Pass this if window is not defined yet
}(typeof window !== "undefined" ? window : this, function( window, noGlobal ) {

// Support: Firefox 18+
// Can't be in strict mode, several libs including ASP.NET trace
// the stack via arguments.caller.callee and Firefox dies if
// you try to trace through "use strict" call chains. (#13335)
//"use strict";
````

this is my full source of  `appName/static/lib/jquery/src/intro.js`



open bracket is exists, but close?

**Comment by rwwagner90** [comment]
@ChangJoo-Park My issue was caused because ember-cli was adding a bower_components folder in app/bower_components. Delete that folder if you have it. bower_components should be in the root only.

**Comment by KseniaLass** [comment]
@rwwagner90 it's work! thank you :)
