### ISSUE TITLE
Ember error after production build

### ISSUE THREAD

**Issue by imhuytq** [ember-cli/ember-cli#5568]
I'm using Windows 10, nodejs 5.6.0, ember-cli 2.4.1. My project using ember 2.4.1 and ember data 2.4.0. After I build my project for production env, and I got a error:
```
Uncaught Error: Could not find module `ember-data/-private\system\references\record` imported from `ember-data/-private/system/references`
```

However when I build for development env, app runed without error.
It seems slash has been replaced by backslash.
How to fix it?

**Comment by Turbo87** [comment]
are you sure that's not an `ember-data` bug?

**Comment by imhuytq** [comment]
App still working when I build on Development env (`ember build`), but not working when I build on Production env (`ember build --prod`). I think that's not an `ember-data` bug.
I was try `ember new new-app && cd new-app` and `ember build --prod`, and I getting the same error.

```
Uncaught Error: Could not find module `ember-data/-private\system\references\record` imported from `ember-data/-private/system/references`
```

**Comment by floqqi** [comment]
Duplicate of #5542

**Comment by imhuytq** [comment]
@floqqi ok, thanks. I will close issue.
