### ISSUE TITLE
Cannot disable hinting in addon when isDevelopingAddon is true

### ISSUE THREAD

**Issue by carlbennettnz** [ember-cli/ember-cli#5594]
I have an app which includes an `npm link`ed addon in its `package.json`. Both the app and the addon have `hinting: false` in their `ember-cli-build.js` files, and the addon has `isDevelopingAddon: () => true` in its `index.js`. If I `ember serve` the app, the hinting option is ignored for the addon.

**Comment by Turbo87** [comment]
@carlbennettnz I'm not sure if this is a scenario that we support. Does it work properly when using `ember serve` from the addon folder?

**Comment by carlbennettnz** [comment]
Yes.

- [x] `ember serve` from addon folder
- [x] `ember serve` from app folder, with `isDevelopingAddon: () => false`
- [ ] `ember serve` from app folder, with `isDevelopingAddon: () => true`

In the final case, everything seems functionally correct, but the JSHint errors are shown.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L119-L124 should be updated something like:

```
Addon.prototype.hintingEnabled = function() {
  var isProduction = process.env.EMBER_ENV === 'production';
  var testsEnabledDefault = process.env.EMBER_CLI_TEST_COMMAND || !isProduction;
  var hintingDisabled = this.options && this.options.hinting === false;

  return testsEnabledDefault && !hintingDisabled;
};
```

**Comment by Turbo87** [comment]
@carlbennettnz could you check if the solution proposed by @rwjblue works for you? if it does feel free to open a PR :shipit:

**Comment by rwjblue** [comment]
(with tests)
