### ISSUE TITLE
Incorrect Ember CLI version on home page

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli#5595]
The Home page for Ember CLI now lists the current version as "0.0.0". I suspect this is a side effect of the Changelog being removed from the web site and now being a link to the GitHub releases page.

**Comment by rwjblue** [comment]
It is supposed to populate as a result of some JS pinging the github API or something, can you check if there are any errors/warnings?

**Comment by stefanpenner** [comment]
I suspect just latency, but if their is an issue please report browser type etc, and open it on the website repo: https://github.com/ember-cli/ember-cli.github.io

**Comment by baron1405** [comment]
Confirming, it reads 2.4.2 now. Thanks.
