### ISSUE TITLE
ember move (mv)

### ISSUE THREAD

**Issue by floqqi** [ember-cli/ember-cli#5596]
I'm catching myself often using `ember destroy route xyz` and re-`ember generate route abc/xyz` (for example) to move a route/component/... especially in early stage of development when requirements change fast.

It'd be useful to have a command to move and rename all related things (code, tests, ...) for a blueprint.

**Comment by rwjblue** [comment]
Feature requests should be made in the ember-cli/rfcs repo. Also, there is an addon that @trabus had worked on for a bit that did this I believe...

**Comment by stefanpenner** [comment]
requesting a feature is outlined [here](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#requesting-a-feature)
