### ISSUE TITLE
in ember new allow options to be passed to npm,bower & Co

### ISSUE THREAD

**Issue by estani** [ember-cli/ember-cli#5604]
As I'm working on a VM with Windows as host and a shared directory I need to tell npm to not use symlinks via the --no-bin-links option.

It would be nice if there was a way to pass those commands to the npm call. Either over some parameter (e.g. --npm-extra-arguments="--no-bin-links") or environmental variables(EMBER_NPM_EXTRA_ARGS=--no-bin-links). Documenting the last one might be a little trickier.

I did solve that by skipping the npm step and running it manually, so this is a minor change.

**Comment by stefanpenner** [comment]
> I did solve that by skipping the npm step and running it manually, so this is a minor change.

I think this is how we should solve it for now

**Comment by rwjblue** [comment]
Hmm, I thought that NPM exposed the ability to use environment flags or global config file to default their options.

**Comment by estani** [comment]
Ok, it's a small issue and is already documented here. It means though that build tools may only be used if they do not require any particular configuration.
I'll close the issue for the time being, we'll see if this affects others as well.

**Comment by estani** [comment]
I did look for something like that rwjblue but couldn't find anything at that time, with your hint about environment variables did find the solution ([See documentation](https://docs.npmjs.com/misc/config))

In my case this (adding `--no-bin-links`) is achieved by setting:
`NPM_CONFIG_BIN_LINKS=false`

Just as a heads up, to check if this work call `npm config ls -l` and check if the flags are as expected. You'll see here that the `no` word is used as a negation and the real config key was `bin-links`
