### ISSUE TITLE
Use Shadow DOM for test runners

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5608]
In the current state the CSS of the application is also applied to the test runner page which is causing it to look bad in some situations (e.g. setting `body { background: black }`). I'm not sure if this is possible in any way but maybe we could utilize the Shadow DOM feature in the supporting browsers to prevent this from happening?

**Comment by stefanpenner** [comment]
seems awesome, but likely a https://github.com/ember-cli/ember-cli-qunit or qunit or similar issue.
