### ISSUE TITLE
Profiling for the CLI itself

### ISSUE THREAD

**Issue by zackarychapple** [ember-cli/ember-cli#5613]
As version bumps are made and dependencies are updated when tests are run against the CLI itself it would be good to know if the updates are making the CLI faster or slower (within a margin of error).  Any thoughts on this?

**Comment by Turbo87** [comment]
that would be nice, yes. would you want to work on that?

**Comment by stefanpenner** [comment]
Performance tests really can't be run as part of CI, the variability i too high.

Before release we do try to run against our stress app: https://github.com/ember-cli/stress-app

**Comment by zackarychapple** [comment]
@Turbo87 would love to chat on it.  I was looking into it earlier this morning.  Do you have a slack channel I can hop on or a hangout?

**Comment by Turbo87** [comment]
@zackarychapple https://ember-community-slackin.herokuapp.com/

I generally agree with @stefanpenner though
