### ISSUE TITLE
Provide a simple way to exclude a file in public directory like .DS_Store from build.

### ISSUE THREAD

**Issue by Gaurav0** [ember-cli/ember-cli#5623]
Right now this seems to be only possible by using the trees option to disable automatically including public and then including it via funnel. There should be a simpler way that doesn't require knowledge of broccoli.

**Comment by rwjblue** [comment]
The easiest solution is to delete the file (you can generally use 'git clean -dfx' to delete files that aren't tracked by git). 

The goal of public is to copy all files into dist, if you need to filter you should use normal broccoli filtering (generally via broccoli-filter).  You could always create an addon to provide this functionality if needed, but I don't see a reason to add more public API in ember-cli itself for this edge case.
