### ISSUE TITLE
Deprecate `ember help <something> --json`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5626]
As mentioned in https://github.com/EmberTown/ember-hearth/issues/97 `ember help --json` already contains all the necessary information needed to derive the other ones which makes it pointless to use any specialized version of it. This is different from `ember help` vs `ember help generate` because `ember help --json` *does* contain information about the available blueprints and their options already.

I would like to propose to deprecate `ember help <something> --json` in ember-cli@2.5 and remove it in ember-cli@2.6.

AFAIK ember-hearth is the only user of `ember help --json` so far and they are only using the generic variant which should remain the same.

**Comment by kellyselden** [comment]
@Turbo87 https://github.com/felixrieseberg/vsc-ember-cli also uses it to scrape blueprints

**Comment by Turbo87** [comment]
indeed... (https://github.com/felixrieseberg/vsc-ember-cli/blob/b4903fa0fe34116ae83e459f5ac617aa3553b21b/src/ember-ops.ts#L154)

@felixrieseberg can you comment on why you're using the "specialized" form?

**Comment by felixrieseberg** [comment]
There's no need for the specialized form on my end, I can switch.

**Comment by kellyselden** [comment]
@Turbo87 see https://github.com/ember-cli/ember-cli/pull/5622#issuecomment-198360045. No need for the extra work of deprecation, Feel free to just gut it out. We can do our best to notify the consumers, but other than that, it should be considered experimental while we stabilize the interface.

**Comment by Turbo87** [comment]
@kellyselden still I wouldn't want to break vs-ember-cli so I think deprecating it until @felixrieseberg has adjusted the code makes sense

**Comment by felixrieseberg** [comment]
Quick update: I just got around to fixing it. VSCode is now cool with deprecating the command.

**Comment by Turbo87** [comment]
@felixrieseberg awesome, thanks for the feedback!
