### ISSUE TITLE
inconsistent `ember help <something> --json` output

### ISSUE THREAD

**Issue by lazybensch** [ember-cli/ember-cli#5629]
when i do `ember help --json` the output is:

```
{
  "name": "ember",
  "description": null,
  "aliases": [],
  "works": "insideProject",
  "availableOptions": [],
  "anonymousOptions": [
    "<command (Default: help)>"
  ],
  "version": "2.4.2-master-ada0309dcf",
  "commands": [
    ...
  ],
  "addons": [
    {
      "name": "ember-cli-release",
      "commands": [
        {
          "name": "release",
          ....
        },
        ...
      ]
    },
    ...
  ]
```

i abbreviated most of the output but note how the release command is nested in its `ember-cli-release` addon in the `addons` list. However if i do `ember help release --json`

```
{
  "name": "ember",
  "description": null,
  "aliases": [],
  "works": "insideProject",
  "availableOptions": [],
  "anonymousOptions": [
    "<command (Default: help)>"
  ],
  "version": "2.4.2-master-ada0309dcf",
  "commands": [
    {
      "name": "release",
      ...
    },
    ...
  ],
  "addons": []
}
```

it is now listed under the `commands` list and the `addon` list is empty.

third party consumers might get confused when using both ways to fetch data so we should agree on one API here.

(be aware of #5626 though)

**Comment by Turbo87** [comment]
that is exactly one of the reasons why I opened #5626

the output of the JSON help is/was too closely bundled to the original help output which caused such inconsistencies

**Comment by lazybensch** [comment]
so in case we deprecate/remove the special case, should we still fix this issue for the current version or do we ignore this since not many seem to use this feature atm anyway?

**Comment by Turbo87** [comment]
IMHO we should leave it as it is

**Comment by kellyselden** [comment]
https://github.com/ember-cli/ember-cli/pull/5622#issuecomment-198360045 Just here to confirm the API can change as we see fit. No need to worry about backwards compatibility.
