### ISSUE TITLE
Cache `ember help --json` output

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5630]
For consuming applications (ember-hearth, vsc-ember-cli, intellij-ember) of `ember help --json` it can make sense to cache the output to make it faster and to simplify reading it because the application would only need to read a JSON file instead of shelling out.

Something similar was already proposed in #4709 and the result of this issue should be reused in the PR.

This cached file obviously would need to updated at the appropriate times:

- installing addons via `ember install` and `npm install`
- removing addons

it might be possible to use the `postinstall` of NPM for this and we should probably provide an ember-cli command to manually update the cache.

/cc @lazybensch @stefanpenner @kellyselden

**Comment by lazybensch** [comment]
i have prepared a branch that implements exactly this, will publish it tomorrow

**Comment by stefanpenner** [comment]
this isn't really an issue, future proposals like this should be RFC's.
