### ISSUE TITLE
Clean up logging in "UI" class

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5634]
It seems that we are currently logging errors to `stderr` and warnings, info and debug messages to `stdout`. Normal application output like `ember --help` is also written to `stdout`. Is there a reason for logging to `stdout` instead of writing everything (except for actual output like `ember --help`) to `stdout` instead of `stderr`?

I would like to propose changing the output stream to `stderr` for all log messages. This would most likely also prevent things like https://github.com/ember-cli/ember-cli/pull/5450 from happening.

**Comment by Turbo87** [comment]
@stefanpenner @kellyselden @rwjblue any opinions about this?

**Comment by rwjblue** [comment]
Errors should go to stderr. Standard output goes to stdout. This seems to be what we are doing, and is in sync with the majority of other CLI utilities that I am aware of.

**Comment by rwjblue** [comment]
We already have a way to suppress needless output (--silent), maybe --json should infer --silent?

**Comment by Turbo87** [comment]
@rwjblue one of the reasons for my proposal is showing deprecation messages in `ember help --json`. the JSON output should obviously be written to `stdout`, but the deprecation message should probably be on `stderr` to not mess with the output. deprecation messages however are warnings and warnings are written to `stdout`.

> Standard output goes to stdout.

what do you consider "standard output"?

**Comment by rwjblue** [comment]
All "non exceptional" output is standard in my mind. If the program isn't exiting non-zero (or auto recovering from what would have been non-zero exit code), it should go to stdout. 

--silent should squelch all but actual errors though.

**Comment by Turbo87** [comment]
hmm, I tend to slightly disagree. I think it makes more sense to use stderr for most of the output and use stdout only when output it explicitly requested (e.g. `ember help` or maybe `ember test`)

any idea how to implement the deprecation message if we keep using stdout for it?

**Comment by kellyselden** [comment]
> All "non exceptional" output is standard in my mind. If the program isn't exiting non-zero (or auto recovering from what would have been non-zero exit code), it should go to stdout.

I agree with @rwjblue on that philosophy, even though it makes it harder for us to solve deprecations with json output. This problem will be multiplied once we stabilize the json api and need to make changes.

**Comment by rwjblue** [comment]
> any idea how to implement the deprecation message if we keep using stdout for it?

Yes, we have a couple options (either or both seem good to me):

* make --json infer --silent
* add a section to the JSON output to include warnings, deprecations, log outputs. This would require an additional UI subclass (similar to the one in tests) for JSONUI or some such.

**Comment by stefanpenner** [comment]
> add a section to the JSON output to include warnings, deprecations, log outputs.

interesting, i guess it does sorta make sense that the consumers of the JSON (like an UI) would want to also display this information)

**Comment by nathanhammond** [comment]
I think @rwjblue hit the nail on the head with this proposal:

> add a section to the JSON output to include warnings, deprecations, log outputs.

@Turbo87: we can discuss in today's meeting if we wish, but I feel like we're doing the right thing with `stdout` and `stderr` right now. @rwjblue's proposal neatly sidesteps the logging issue. I'm moving this to "ready for PR" with that proposal and we can revisit that decision if necessary.
