### ISSUE TITLE
npm task problem on Windows

### ISSUE THREAD

**Issue by jkuri** [ember-cli/ember-cli#5637]
We are having problems with using https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js on Windows systems. I currently not have a log about it but the problem is about `cannot find module npm`. We found a fix about it `npm link npm`, but still using our own npm task.

**Comment by stefanpenner** [comment]
please follow the instructions outline [here](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md) for submitting an issue. This was the big yellow banner you saw when submitted. Information asked for in the doc, can help us debug an diagnose.

**Comment by stefanpenner** [comment]
Will reopen if the above request is fulfilled.

CI tests and runs windows installations, and I did a test on my windows machine all appears well. I suspect something went sideways with your initial NPM installation.

**Comment by jkuri** [comment]
Hi Stefan! 
Sorry I posted this issue a bit too soon, but there was some Windows users complaining about `require('npm')` part some time ago. I guess there was some issues about `npm` itself. I prepared demo for this issue and tested on Windows machine and I found out that is nothing wrong with the task itself. So, just ignore this please.

**Comment by stefanpenner** [comment]
No prob. Feel free to open if something does turn up

Usually we see issues with old and buggy versions of npm, often resulting in what you described
