### ISSUE TITLE
Switch version of phantomjs

### ISSUE THREAD

**Issue by supersabillon** [ember-cli/ember-cli#5639]
How can I change the version of phantomjs my app uses?

`phantomjs -v`
`2.1.1`

If I run `ember test` it instead uses PhantomJS 1.9.

I'm using version 2.4.2 of ember-cli.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md suggests Q/A is better suited for Stackoverflow/discourse.
