### ISSUE TITLE
Resources in outputPaths.app.html do not get fingerprinted if the file extension is not .html

### ISSUE THREAD

**Issue by mm2ha** [ember-cli/ember-cli#5658]
I just ran into an issue when I was trying to build our application into the production environment with:
`ember build --environment=production`

This is what I have in `ember-cli-build.js`:
```
module.exports = function (defaults) {
    var app = new EmberApp(defaults, {
        outputPaths: {
            app: {
                html: 'Default.aspx'
            }
        }
    });

    return app.toTree();
};
```

When building in development environment everything works fine. However, when I try to build to production, the filenames for resources get fingerprinted (good) but the resource links generated into `Default.aspx` do not (bad). The resource links are still there, but no md5 fingerprints are added, which causes the app not to load as it cannot find the JS and CSS files.

If I change the outputPaths.app.html to `Default.html` (or any other name ending with `.html`), things work correctly and the resource links get fingerprinted.

My `index.html`:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MyApplication</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for "head"}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/my-application.css">

    {{content-for "head-footer"}}
  </head>
  <body>
    {{content-for "body"}}

    <script src="assets/vendor.js"></script>
    <script src="assets/my-application.js"></script>

    {{content-for "body-footer"}}
  </body>
</html>

```

My `ember-cli` version is `2.4.2`

**Comment by nathanhammond** [comment]
@mm2ha Can you create a reduced reproduction as a GitHub repo we can check out and run? That would make it much easier for us to get started on this bug hunt. :)

**Comment by Turbo87** [comment]
this sounds like intended behavior to me and can be changed by adjusting the configuration of the https://github.com/rickharrison/broccoli-asset-rev addon

**Comment by vdubus** [comment]
I had the same problem when I was trying to generate an `index.htm` file in place of `index.html`.
And indeed, configuring the broccoli-asset-rev addon fix this problem.

```javascript
// in ember-cli-build.js
var app = new EmberApp(defaults, {
    // Add options here
    fingerprint : {
        replaceExtensions : [ 'html', "htm", 'css', 'js' ]
    },
    outputPaths : {
        app : {
            html : 'index.htm',
        }
    }
});
```
