### ISSUE TITLE
Super Strange SVG Fingerprinting Bug

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#5660]
Hi Team!~

@zbergson and I have a strange fingerprinting bug that's unlikely we can replicate in an example repo.

```
version: 1.13.1
node: 0.10.37
npm: 2.12.1
```

We have 2 SVGs named `/public/images/check-white.svg` & `public/images/trophy-white.svg`.

We're referencing them in our SCSS like so:
```
  .enter-contest-overlay {
    background-image: url('/images/check-white.svg');
  } 

  .trophy-overlay {
    background-image: url('/images/trophy-white.svg');
  }
```

The compiled output is:

```
.competition-card .enter-contest-overlay {
  background-image: url('/http://localhost:4200/images/check-white-b6c09d202bb32930badea258f308441d.svg'); }
.competition-card .trophy-overlay {
  background-image: url('http://localhost:4200/images/trophy-white-597c1eeb4ce97cb0f7cf5c3d13e8b0ec.svg'); }
```

--> **Note the leading forward slash for the `check-white.svg` file** <--
This is causing the browser to think this is a relative path, and breaking the background image.

Strangely enough, renaming the file (and SCSS to match) fixes the issue.

This is for sure the strangest bug I've seen with Ember CLI thus far.  Any leads would be greatly appreciated!

**Comment by stefanpenner** [comment]
most likely a bug here:

* https://github.com/rickharrison/broccoli-asset-rev
* https://github.com/rickharrison/broccoli-asset-rewrite

**Comment by Turbo87** [comment]
@hhff I'm not sure there's much we can do without being able to reproduce this problem. could you try to extract from your codebase?

**Comment by stefanpenner** [comment]
> @hhff I'm not sure there's much we can do without being able to reproduce this problem. could you try to extract from your codebase?

^ will gladly reopen if that can be provided

**Comment by hhff** [comment]
all good :)

super weird but no idea how to reproduce, so no idea what's causing it!  If it happens again I'll look into it :)
