### ISSUE TITLE
Home page still shows version 0.0.0

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli#5663]
Using Chrome 49 on Mac OSX 10.10.5, the Ember CLI home page shows the current version of Ember CLI as 0.0.0. I had opened this issue previously and thought it was fixed but I think that was transient.

**Comment by stefanpenner** [comment]
its most likely a latency thing

@leo any ideas?

**Comment by leo** [comment]
@baron1405 I've moved this issue over to https://github.com/ember-cli/ember-cli.github.io/issues/66.
@stefanpenner or @Turbo87 Please close this one!
