### ISSUE TITLE
Cannot see Overview on Home page

### ISSUE THREAD

**Issue by baron1405** [ember-cli/ember-cli#5664]
Using Chrome 49 on Mac OSX 10.10.5, cannot see the overview page/pane when clicking on the Overview button. Click on Overview and nothing happens. Scroll the page and you see some of the Overview but it is covered over by the home page.

**Comment by kellyselden** [comment]
I just noticed this too. I don't know what happened. Would you mind posting this on the website repo? https://github.com/ember-cli/ember-cli.github.io

**Comment by baron1405** [comment]
Done

**Comment by kellyselden** [comment]
Thanks!
