### ISSUE TITLE
Cannot npm install -g ember-cli due to left-pad dependecy update

### ISSUE THREAD

**Issue by bennycwong** [ember-cli/ember-cli#5669]
https://registry.npmjs.org/left-pad

Left-pad updated to version 1.0.0 as of 3/22/2016. Due to this issue, npm install -g ember-cli errors out with the following error message:

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request

**Comment by artych** [comment]
https://github.com/azer/left-pad/issues/4
