### ISSUE TITLE
Cannot disable rebuilding artifacts when running with ember serve

### ISSUE THREAD

**Issue by robbytx** [ember-cli/ember-cli#5671]
I'm often running a local integration test suite where I start an instance of Ember (using `ember serve --live-reload false --output-path dist.test --port 4210`) and my application server, and I allow the suite to run in the background for several minutes while I proceed to possibly make additional changes.

What I've noticed is that `--live-reload false` will correctly prevent my integration suite browser instances from refreshing, but it does NOT prevent Ember from rebuilding the dist artifacts when changes are made to application/server files, and then serving those updated artifacts to the browser upon request.  

This is a problem for me because a single integration test suite run will sometimes refresh or open new browser windows, and I'm not guaranteed that I'm testing a stable target, since some portion of the test suite may pick up arbitrary changes that I'm toying with in my Ember application.

I'm using:
```
$ ember version
version: 2.4.2
node: 4.3.2
os: darwin x64
```

Here's a serious of steps to demonstrate the problem:
```
ember new demo
cd demo
ember serve --live-reload false &
# wait until the application is built
open http://localhost:4200/
sed -i '' -e 's/Welcome to Ember/This is My Demo/' app/templates/application.hbs
```

After the sed command is issued, you should see ember-cli output indicating that the application was rebuilt, but the browser was correctly NOT refreshed.  However, if you refresh the browser, then you will see the application text was updated.

It's confusing to me that `--live-reload false` does not also prevent the application artifacts from being rebuilt, but maybe there is a use case for the current behavior?  I've explored the various options for the `--watcher` command, but there doesn't seem to be a `--watcher disabled` or similar option.

So, please consider one of the following to disable rebuilding of artifacts on app/server changes:
 1. Changing the behavior of `--live-reload false`
 2. Adding a `--watcher disabled/none` option

**Comment by stefanpenner** [comment]
This seems to be working as expected, live-reload and rebuilding are two different things.

**Comment by robbytx** [comment]
So, are you proposing that I need to file a feature request for this?

Because what I want is for the server to build once and serve the same artifacts and not rebuild / restart the server when some source file changes.

**Comment by stefanpenner** [comment]
Im merely saying this is working as expected, and the scenario you describe appears quite niche. 

Maybe a feature request via RFC is appropriate, to see if there is sufficient interest, if it turns out we can explore an additional flag. But a non-rebuilding `ember s` has not yet been considered.

**Comment by robbytx** [comment]
Ok. that's fair enough.  I suppose it would be a more faithful integration test for me to build the artifacts and serve them via nginx (instead of ember serve), so I'll pursue that option instead.

**Comment by adriano-triana** [comment]
> But a non-rebuilding ember s has not yet been considered.
Is this still true? I am looking to serve a static version of my ember application so there is no rebuilding/babel recompile when changes are detected. Am I able to accomplish this?
