### ISSUE TITLE
Destroying Nested Route Doesn't Remove Folder

### ISSUE THREAD

**Issue by Sixen** [ember-cli/ember-cli#5675]
As the title says, destroying a nested ember route does not delete the folder created for nesting. For example:

```bash
ember generate route something/hi
ember destroy route something/hi
```

The 'something' folder still exists, even though it's empty. Perhaps the CLI should check if the folder is empty, if so delete the folder, if not, leave the folder.

**Comment by stefanpenner** [comment]
likely an RFC, as details such as which folders to delete and which not it requires further information.
