### ISSUE TITLE
Strip `Ember.assert` calls from production output

### ISSUE THREAD

**Issue by GavinJoyce** [ember-cli/ember-cli#5680]
According to [the docs](http://emberjs.com/api/#method_assert), `Ember.assert` calls should be removed from the production build output. This doesn't seem to be the case.

Here's some discussion: https://embercommunity.slack.com/archives/ember-cli/p1458857451000785

<img width="927" alt="screen shot 2016-03-24 at 15 32 58" src="https://cloud.githubusercontent.com/assets/2526/14033201/bd23d05e-f1d5-11e5-9428-a00858639884.png">

<img width="1007" alt="screen shot 2016-03-24 at 15 33 07" src="https://cloud.githubusercontent.com/assets/2526/14033206/c5d49350-f1d5-11e5-870a-97bd39a7fea5.png">

**Comment by GavinJoyce** [comment]
There are lots of `Ember.asserts` in the production ember data output too:

<img width="1215" alt="screen shot 2016-03-24 at 16 12 27" src="https://cloud.githubusercontent.com/assets/2526/14033889/4d4efc76-f1db-11e5-9f7e-c342475f526e.png">

**Comment by stefanpenner** [comment]
This isn't an ember cli issue. Likely an ember-data one

**Comment by GavinJoyce** [comment]
@stefanpenner It isn't just ember-data, `Ember.assert` calls in ember-cli applications are present in production builds.

**Comment by stefanpenner** [comment]
@GavinJoyce that isn't a feature ember-cli ships with though, which is expected IMHO.

http://emberjs.com/api/#method_assert I suspect refers to embers own build tools

**Comment by GavinJoyce** [comment]
@stefanpenner thanks, I'll create a PR to update the docs and create an addon to do the stripping

**Comment by stefanpenner** [comment]
@GavinJoyce sweet, i do think it may be reasonable to actually bundle this stripping by defaul \w all apps and addonst. I believe the best solution would be for it to be part of the existing babel transform, merely as a plugin.

**Comment by rwjblue** [comment]
Reopening after discussion in ember-cli core team meeting today.

**Comment by stefanpenner** [comment]
@rwjblue I would prefer to transition this to an RFC, as it needs fleshing out.

**Comment by rwjblue** [comment]
@stefanpenner - I agree.

@GavinJoyce - I think that we (ember-cli core) are all on board and want this feature, but it needs to go through an RFC process first.  If you have some time, I'd love to setup some time to review the various parts of the RFC and make a plan for implementation (which I suspect is fairly straightforward actually).

**Comment by GavinJoyce** [comment]
@rwjblue sure, let's do that.

**Comment by GavinJoyce** [comment]
I had a quick chat with @rwjblue, I'll submit an RFC within the next few days

**Comment by stefanpenner** [comment]
Sweet. Im going to close this issue then, we can revisit as an RFC, flesh it out, then transition to the implementation plan.

**Comment by GavinJoyce** [comment]
Here's the RFC: https://github.com/emberjs/rfcs/pull/132
