### ISSUE TITLE
watchman/nodewatcher on `ember build`

### ISSUE THREAD

**Issue by hone** [ember-cli/ember-cli#5685]
Hello,

I get this warning message when running `ember build`.

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
```

I understand this is needed for `ember serve`, but ideally this message should be shown lazily when a watchman is created. Thanks!

**Comment by rwjblue** [comment]
I agree, though I vaguely recall that @stefanpenner was in favor of showing it for all commands. 

@stefanpenner - Is that recollection correct?

**Comment by stefanpenner** [comment]
> I agree, though I vaguely recall that @stefanpenner was in favor of showing it for all commands.

I didn't really want it to run for all commands, and originally I detected it on-demand, unfortunately detecting in on-demand but asynchronously (node 0.10.x doesn't support sync exec without native extension or mega mega hacks) exposed a broccoli <-> watcher race-condition I wasn't able to track down. To work around this, I had to move (without more aggressive refactoring) the watchman check way further up in the flow of things, which ultimately means it runs for all commands.

Some options:

* the race condition may be fixed, we _may_ be able move it back (needs investigation)
* make a blacklist of commands which shouldn't check ("meh")
* find + fix the race condition
* don't bother detecting in node  0.10.x (smells bad)
* ??

**Comment by rwjblue** [comment]
I think doing the detection every time might be fine, but we could move the console output to be based on command? Basically, have the detection set a flag that is used when we actually create a watcher.

Just an idea...

**Comment by stefanpenner** [comment]
> make a blacklist of commands which shouldn't check ("meh")

this suggestion then?
