### ISSUE TITLE
The release process is manual.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5691]
In order to move toward a more consistent release process we need to automate much or all of the [release process](https://github.com/ember-cli/ember-cli/blob/master/RELEASE.md). The first iteration can be simplistic shell scripts, but we should use it as a stepping stone to achieve a solid end state:

- [ ] Enforce commit tagging.
- [ ] All of the tasks should be split into separate bite-size idempotent operations.
- [ ] Built on a just-in-time provisioned build/CI box to guarantee consistent initial state.
- [ ] Perform automatic tests and present them to human for verification.
- [ ] Changelog generation should be more robust.
- [ ] Automatically run smoke tests against the newly packaged version.
- [ ] Tag, push, and publish to npm.
- [ ] Automatically run smoke tests against the newly published artifact.
- [ ] Generate GitHub release notes.
- [ ] [Update ember-cli-output and ember-addon-output.](https://gist.github.com/nathanhammond/e0a55b4d0328b45b8ef5)
- [ ] Promote on Slack and Twitter.

I'll review and approve PRs implementing any portion of this in a scripted manner. As we get closer to complete we can start talking about how we want to architect it such that it can be reduced to a button press.

/cc @raytiley

**Comment by chadhietala** [comment]
@nathanhammond I think the PR templates could help with the first item. To really enforce it we could we could have a script that basically does a `git log -1 --pretty=%B` and then checks the first line for one of the commit tags. If it doesn't match then the build should return 1.

**Comment by chadhietala** [comment]
I've used [Release It](https://www.npmjs.com/package/release-it) to stream line tag, push, publish.

**Comment by kellyselden** [comment]
For the first one, we might also be able to rely on github labels, then load them from github api during our changelog gen.

**Comment by kellyselden** [comment]
> Changelog generation should be more robust.

Some ideas are
* When a core member uses a branch in the ember-cli repo instead of a fork, it labels the user as "ember-cli". Instead of advising against this, which could be annoying (also I think @stefanpenner can't because his repo is a redirect), we could use the github api to replace it with the real committer.
* use a tag or label on PRs you don't want to show up in the log (changes which have no impact on users)
* greenkeeper can be noisy, but maybe people want to know what dep got a bugfix.

**Comment by kellyselden** [comment]
> Promote on Slack and Twitter.

Official twitter account?

**Comment by trentmwillis** [comment]
> Enforce commit tagging.

To push this upstream (before a PR is opened), you could try using [commitplease](https://www.npmjs.com/package/commitplease), which is what the jQuery org uses.

**Comment by stefanpenner** [comment]
I am good with improving this. But as this issue has been idle for several months, it being left open likely isn't providing much value.

We can still refer to this if needed.
