### ISSUE TITLE
Asset Size Printer model should extend from Model, not Task

### ISSUE THREAD

**Issue by iezer** [ember-cli/ember-cli#5700]
https://github.com/ember-cli/ember-cli/blob/master/lib/models/asset-size-printer.js#L8

**Comment by rwjblue** [comment]
Thanks for reporting! We noticed this during the contributor workshop today.

**Comment by jeffjewiss** [comment]
I tried looking into this, but I'm a little confused. As far as I can tell there isn't a `Model` object to extend from. What should the asset size printer be extending?

**Comment by Turbo87** [comment]
@jeffjewiss either nothing or `CoreObject`. I tend to prefer "nothing" unless anyone can tell me good reasons for using `CoreObject` here.

**Comment by jeffjewiss** [comment]
@Turbo87 thanks for clarifying, I gave this a shot in the linked PR.
