### ISSUE TITLE
ADDON_HOOKS.md links to outdated source code

### ISSUE THREAD

**Issue by bantic** [ember-cli/ember-cli#5702]
The links to source code lines in the addon hooks file all link to the tag `v0.1.15`. They should be updated to the latest tag (`v2.4.3`) and be updated to still point to the correct line numbers.

[This commit](https://github.com/ember-cli/ember-cli/commit/da26e13a2a40cbd75540d8de252c732daa59d565) appears to be the last time the links were mass-updated.

**Comment by sweatypitts** [comment]
I can do this.

**Comment by sweatypitts** [comment]
@bantic This can be closed now. Taken care of in above PR.

**Comment by bantic** [comment]
:clap:  thanks! cc @nathanhammond
