### ISSUE TITLE
Use different port if 4200 is in use

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5703]
Unless I specifically specify `--port 4200` I would expect `ember-cli` to use a different port if 4200 is already in use instead of failing with `Could not serve on http://localhost:4200. It is either in use or you do not have permission.`.

**Comment by rwjblue** [comment]
I definitely agree. I believe portfinder can do this for us...

**Comment by stefanpenner** [comment]
This needs an rfc

**Comment by Turbo87** [comment]
@stefanpenner  I was under the impression that RFCs were only needed for larger or breaking changes. is there any disadvantage to using portfinder starting at port 4200 by default unless `--port` is specified explicitly?

**Comment by kellyselden** [comment]
@Turbo87 I think RFC comes down to whether it affects the user or not. That said, this almost could be considered a bugfix? Like we did when changing what `ember i` does.

**Comment by stefanpenner** [comment]
This is a small breaking change. We also need to improve the UX of the port is unpredictable. Maybe every rebuild needs to show the url.

I'm also worried that doing this automatically will result in people confusingly using existing/stale sessions or letting sessions pile up.

I'm pretty sure the number of times I have a collision and wanted an automatic port is on paar with the amount of times I realized I already had a server running and first needed to kill it. Which leads me to error on the side of caution and prefer the hard failure.

I believe a good solution would need to disambiguate between a server already running for this project(likely should fail)  and an unrelated project (I could accept a random new port should be used) Maybe a pid file in tmp or something?

**Comment by Turbo87** [comment]
> I believe a good solution would need to disambiguate between a server already running for this project(likely should fail) and an unrelated project (I could accept a random new port should be used) Maybe a pid file in tmp or something?

that makes sense, thanks!

**Comment by stefanpenner** [comment]
closing in-favor of RFC
