### ISSUE TITLE
Production still fails to build, but only in one project

### ISSUE THREAD

**Issue by blaher** [ember-cli/ember-cli#5704]
I wasn't sure if I should open a new issue, since the last issue related to this was closed and supposedly resolved in a new release. This issue goes back to #5638. This may actually be a separate issue and I'll explain why. The one thing I noticed different this time around is that before 'ember b' and 'ember s' worked before (which is no longer the case), and that's how I got around building it for the time being. The other strange difference is I have two separate ember projects with both the same versions. The one set works fine, but the other does not. To be clear, development builds both work, it's only production build in the one project that produce this error.

Same error as before:
`Error: Could not find module '-private/system/references/record' imported from 'ember-data/-private/system/references'
...n(e){this.name=e}function i(e,t){throw new Error("Could not find module '"+e+"' ...`

Ember: 2.4.2
Ember Data: 2.4.3+a3e2521f85
Ember-CLI: 2.4.2
Node: 5.6.0
NPM: 3.6.0

Ran in both Jenkins on Amazon Linux AMI release 2015.09 and manually on Ubuntu 14.04.3.

Working Build Set: [Production](https://new.maintenanceprogram.com/office/) (Working) & [Development](http://quality.maintenanceprogram.com/office/) (Working)
Broken Build Set: [Production](https://new.maintenanceprogram.com) (Not working) & [Development](http://quality.maintenanceprogram.com/) (Working)

Is there anyway I can provide more information or be more help? I understand this time around might not be so easy to replicate, since I can't replicated it in my other projects. If someone needs access to my private repo, I can grant it to them.

**Comment by Turbo87** [comment]
@blaher we need some way to reproduce this issues otherwise there is no way we can fix this. it sounds like you have a broken installation of `ember-data` and I'm slightly confused by `Ember Data: 2.4.3+a3e2521f85` as it indicates that you might not be using a stable release of it.

**Comment by stefanpenner** [comment]
> @blaher we need some way to reproduce this issues otherwise there is no way we can fix this. i

will reopen if ^ is provided
