### ISSUE TITLE
changing the default behavior of ember install command

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-cli/ember-cli#5705]
Most ember devs have ember-cli installed globally and when they clone an existing ember-cli project, they'd still have to run `npm install` and `bower install`. While everyone has shortcut aliases to achieve this, it would be nice to follow the same behavior as `npm install` command. 

So `ember install` with an argument should install an addon, but calling it without an argument should invoke `npm install` and `bower install`. If this sounds good, I can make the change and raise a PR for this.

**Comment by stefanpenner** [comment]
as per our contributing.md this needs to be an RFC or RFC/issue
