### ISSUE TITLE
Cryptic error message when running "ember serve" in project without "npm install" first

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5711]
I've just cloned an Ember project of a coworker, forgot `npm install && bower install` and went straight to `ember serve` which resulted in the following cryptic error message:

```
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (.../ember-cli-build.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Shouldn't our dependency checker catch this instead of showing the error?

**Comment by stefanpenner** [comment]
> Shouldn't our dependency checker catch this instead of showing the error?

if the dep checker isn't installed it can't.

We can very likely re-think how `ember` executable loads, and if it can't load itself from node_modules, maybe it falls back to the global one to provide:

* ember install
* better error messages

**Comment by Turbo87** [comment]
> We can very likely re-think how ember executable loads, and if it can't load itself from node_modules, maybe it falls back to the global one

If I understand https://github.com/ember-cli/ember-cli/blob/master/bin/ember#L15-L19 correctly we are doing that already. Is the dependency checker something that the project needs to install? I expected it to be installed by the global `ember-cli` package as a dependency.

**Comment by stefanpenner** [comment]
> I expected it to be installed by the global ember-cli package as a dependency.

currently it is only a app/addon dependency. dep checker can be bit of a chicken + egg thing, especially id we want to correctly enable `ember install` in cases where the app/addon doesn't satisfy the dep checker.

**Comment by stefanpenner** [comment]
related: https://github.com/ember-cli/ember-cli/issues/5705

**Comment by Turbo87** [comment]
I don't know when we started doing this but I just saw this:

```
$ ember s
node_modules appears empty, you may need to run `npm install`
```

**Comment by Turbo87** [comment]
looks like this was implemented in https://github.com/ember-cli/ember-cli/pull/4494, which seems kinda strange since that was a long time before I opened that issue 😕

**Comment by stefanpenner** [comment]
@Turbo87 maybe some other cleanup sorted this out.
