### ISSUE TITLE
301 redirect when proxying to a Rails/Puma stack using SSL (ember-cli versions 2.4.2 and 2.4.3)

### ISSUE THREAD

**Issue by chbonser** [ember-cli/ember-cli#5716]
When attempting to upgrade an existing project I discovered that ember-cli@2.4.2 and 2.4.3 cause proxied requests to our rails/puma stack to respond with a 301 redirect.  This issue does not occur with ember-cli@2.4.1 or earlier.

I’ve reproduced the issue using two brand new repositories that can be used to reproduce the issue.
- Rails 4.2.6 repo: https://github.com/chbonser/basic-rails-app

- Ember repo: https://github.com/chbonser/basic-ember-app

Steps to reproduce:
- Pull down both repo's
- Generate self signed ssl keys
- fire up puma (note change the path to your ssl key and crt)
     - `bundle exec puma -b 'ssl://127.0.0.1:9292?key=/path/to/key/dev_only_server.key&cert=/path/to/cert/dev_only_server.crt'`
- fire up ember server with the insecure proxy
     - `ember s --proxy https://127.0.0.1:9292 --insecure-proxy`
- open localhost:4200 and we see the xhr request respond with a 301
- downgrade ember-cli to 2.4.1 and see the issue go away

I’ve also noticed that setting `config.force_ssl = false` in rails `config/application.rb` also stops the 301’s.

**Comment by Turbo87** [comment]
this might be related to https://github.com/ember-cli/ember-cli/pull/5524?

**Comment by stefanpenner** [comment]
> this might be related to #5524

Ya most likely, but needs to be confirmed.

**Comment by stefanpenner** [comment]
@chbonser thank you for the detailed issue, will try to find time soon to dig in.

**Comment by nathanhammond** [comment]
Closing as we now have configuration for our proxy handling. Let me know if there remain issues with accomplishing this goal.
