### ISSUE TITLE
Async operation in the contentFor addon hook

### ISSUE THREAD

**Issue by taylon** [ember-cli/ember-cli#5719]
Hey guys,

I didn't dive into it deep enough, so let me know if what I'm saying doesn't make any sense.

I was trying to build a Ember-cli addon that would add content to the index file using the contentFor hook.  But I need to make an http request to determine what that content would be.

Since the contentFor hook expect a string as a return and the http request will be async, I couldn't figure out how to do it.

I though about maybe allowing us to return a promise from the hook would fix that kind of problem, but I'm not sure if that makes sense. If it does I would try to implement it, but I would like to hear what you guys think first.

**Comment by stefanpenner** [comment]
So on every build you need to issue a request to populate some data value? Seems somewhat unexpected or am I not understanding?

**Comment by taylon** [comment]
In my case it should happen only on production builds. But that is exactly why I'm asking before doing anything because it may be a very specific use case that doesn't really make sense for ember-cli as a whole...

**Comment by stefanpenner** [comment]
@taylon is this while serving in production, or while building in production?

**Comment by taylon** [comment]
Building for production

**Comment by stefanpenner** [comment]
Ah ok, this sounds reasonable to explore. The next steps would be to flesh this out as an https://github.com/ember-cli/rfcs
