### ISSUE TITLE
Model blueprint has some trailing spaces that aren't "Suave" 

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-cli#5736]
Model blueprint has some trailing spaces that aren't "Suave" 

`disallowTrailingWhitespace: Illegal trailing whitespace at models/xxx.js`

I don't know if it would be any different, but I generated a `resource` and a `model` and they were the same

Removing the spaces or the line would do the trick.

**Comment by stefanpenner** [comment]
those blueprints are provided by ember-data
