### ISSUE TITLE
2.4.2 Regression involving treeForAddon

### ISSUE THREAD

**Issue by jskeate** [ember-cli/ember-cli#5745]
Seems like a Broccoli Filter runs in <=2.4.1, but stops working in 2.4.2.

Set up two new projects, one app, one addon.

In the app: change `app/templates/application.hbs` to `{{imported-component}}`

In the addon, generate `imported-component`:

```javascript
import Ember from 'ember';
import layout from '../templates/components/imported-component';

export default Ember.Component.extend({
  layout,

  modified: false
});
```

```handlebars
In imported-component... {{unless modified 'not'}} modified
```

Addon index.js:

```javascript
/* jshint node: true */
'use strict';

var Filter = require('broccoli-filter');

class TestFilter extends Filter {
  canProcessFile(relativePath) {
    return relativePath.indexOf('imported-component') !== -1;
  }

  processString(content, relativePath) {
    return content.replace(/false/g, 'true');
  }
}

module.exports = {
  name: 'xyz',

  isDevelopingAddon() {
    return true;
  },

  treeForAddon(tree) {
    tree = new TestFilter(tree);
    return this._super.treeForAddon.call(this, tree);
  }
};
```

ember-cli 2.4.1: get a page saying "In imported-component... modified"

ember-cli 2.4.2: get a page saying "In imported-component... not modified"

**Comment by Turbo87** [comment]
we've traced this down to https://github.com/ember-cli/ember-cli/pull/5561 and https://github.com/ember-cli/ember-cli/blob/17619b8f949a200122df62b7a14c66ea7e68f932/lib/models/addon.js#L684-L686 in particular
