### ISSUE TITLE
Ember build failing on Windows OS

### ISSUE THREAD

**Issue by GramozKrasniqi** [ember-cli/ember-cli#5748]
This error is comming out when trying to build the EmberCLI app. 
**Ember -v **
version: 1.13.13
node: 4.2.4
npm: 2.14.10
os: win32 x64

EINVAL: invalid argument, symlink 'D:\Workspaces\xxx\xxx\Core
xxx\xxxx\xxx\xxx-client-app\tmp\babel-output_path-oshgWKVn.tmp\xxx-
client-app\tests\integration\app-pods\components\xxxx\xxx\xxxx\component-test.jshint.js' -> 'D:\Workspaces
\xxxxx\xxx\xxx\xxx\xxxx\xxxx\tmp\bro
ccoli_merge_trees-output_path-BeD6edxd.tmp\xxx\tests\integration\app-
pods\components\xxx\xxxx\xxxx\component-test.jshint.js'

**Comment by stefanpenner** [comment]
Can you provide a reproduction


Also it appears you are using an old version be sure to upgrade(and its dependency)

**Comment by GramozKrasniqi** [comment]
well actually it seems that it is the path length Windows problem.

**Comment by stefanpenner** [comment]
@GramozKrasniqi ember-cli shouldn't be affected by the path issues, as node via libUV uses the correct system calls, which do (or so i've been told) not have this issue. I

**Comment by GramozKrasniqi** [comment]
@stefanpenner version: 1.13.13 it seems that is totally affected beacuse we changed to an upper path and the length was shorter and it worked let me just chek if the current version of ember-cli has the same issue.

**Comment by GramozKrasniqi** [comment]
Ok so : 
**ember -v
ember-cli: 2.4.3
node: 4.2.4
os: win32 x64**

ember build 
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
Error: EINVAL: invalid argument, symlink 'file path' <- this length is 281 charachters.

Same error as before.

**Comment by stefanpenner** [comment]
Sounds like a windows issue ;)

**Comment by stefanpenner** [comment]
should be fixed by: https://github.com/broccolijs/node-symlink-or-copy/pull/21
