### ISSUE TITLE
Can't call `_super()` in Addon#init

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5750]
The following diff results in ember-cli breaking, though it seems like it should work.

```diff
diff --git a/lib/models/addon.js b/lib/models/addon.js
index f861028..f63e150 100644
--- a/lib/models/addon.js
+++ b/lib/models/addon.js
@@ -81,6 +81,7 @@ function deprecatedAddonFilters(addon, name, insteadUse, fn) {
 */
 var Addon = CoreObject.extend({
   init: function(parent, project) {
+    this._super.apply(this, arguments);
     this.parent = parent;
     this.project = project;
     this.ui = project && project.ui;
diff --git a/lib/models/addons-factory.js b/lib/models/addons-factory.js
index d8e041d..b55bf95 100644
--- a/lib/models/addons-factory.js
+++ b/lib/models/addons-factory.js
@@ -17,6 +17,7 @@ var debug      = require('debug')('ember-cli:addons-factory');
 */
 var AddonsFactory = CoreObject.extend({
   init: function(addonParent, project) {
+    this._super.apply(this, arguments);
     this.addonParent = addonParent;
     this.project = project;
   },
```

Each addition fails consistently in symptom, in different places. Error if only in `AddonsFactory#init`:
```
Cannot read property 'initializeAddons' of undefined
TypeError: Cannot read property 'initializeAddons' of undefined
    at CoreObject.Project.initializeAddons (/Users/nathanhammond/Repos/ember-cli/lib/models/project.js:378:35)
    at Project.initializeAddons (/Users/nathanhammond/Repos/ember-cli/lib/models/project.js:378:36)
    at Project.eachAddonCommand (/Users/nathanhammond/Repos/ember-cli/lib/models/project.js:429:10)
    at module.exports (/Users/nathanhammond/Repos/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/nathanhammond/Repos/ember-cli/lib/cli/cli.js:34:26)
    at lib$rsvp$$internal$$tryCatch (/Users/nathanhammond/Repos/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/nathanhammond/Repos/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/nathanhammond/Repos/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/nathanhammond/Repos/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

End result is that something stays `undefined` that shouldn't be `undefined`.

**Comment by Turbo87** [comment]
@nathanhammond just to clarify: this diff is not for the master branch but for your #5737 PR, right?

**Comment by nathanhammond** [comment]
@Turbo87 Correct. Also @sclaxton encountered a related issue today being unable to extend from `Addon`.

**Comment by stefanpenner** [comment]
tell me more? Is the ancestor init itself the problem, or...

**Comment by sclaxton** [comment]
I was also seeing some infinite loop weirdness when I calling `_super` of `treeForAddon` when extending from an extension of `Addon`

**Comment by nathanhammond** [comment]
@stefanpenner When working with vanilla objects in testing core-object I can't reproduce this failure. Something about how we have set up `Addon` and `AddonsFactory` inside of Ember CLI triggers this issue. That the old versions of these objects (pre core-object 2.0) also exhibit the same failing behavior and do not call `_super()` is what gives me that confidence and is why I'm in favor of landing core-object 2.0. I rebased #5737 this morning.

**Comment by stefanpenner** [comment]
@nathanhammond ok that makes more sense, ya i believe we should merge #5737 and then later get to the bottom of this.

**Comment by stefanpenner** [comment]
Im pretty sure this is related to: https://github.com/ember-cli/core-object/pull/32

**Comment by stefanpenner** [comment]
Well, I think its as fixed as it can be. This transition will have some edge-cases.

Interim, add-on authors will be recommended to do:

```js
this._super.init && this._super.init.apply(this, arguments);
```

Which is admittedly lame, eventually (when people upgrade CLI) we will be able to do:

```js
this._super.apply(this, arguments);
```

but at-least super works correctly in new versions...
