### ISSUE TITLE
Deprecate `Project.closest` in favor of `Project.closestSync`

### ISSUE THREAD

**Issue by ryanlabouve** [ember-cli/ember-cli#5755]
While investigating https://github.com/ember-cli/ember-cli/issues/5493 we discovered that `Project.closest` was never used internally by ember-cli. Instead, `Project.closestSync` is used exclusively.

Would it be beneficial to deprecate `Project.closest` for future removal?

`Project.closest`:
https://github.com/ember-cli/ember-cli/blob/e016fbe/lib/models/project.js#L570

`Project.closestSync`:
https://github.com/ember-cli/ember-cli/blob/e016fbe/lib/models/project.js#L597

/cc @lukemelia

**Comment by rwjblue** [comment]
If we aren't using it, I think deprecation would be a good idea...

**Comment by Turbo87** [comment]
it's marked as `@private` so IMHO it can be removed without deprecation

**Comment by stefanpenner** [comment]
we should deprecate for 1 version or so, just to be nice.
