### ISSUE TITLE
Ember mock server does not get run when running tests

### ISSUE THREAD

**Issue by JoshTumath** [ember-cli/ember-cli#5764]
I have used `ember generate http-mock foo` to create a mock server in my Ember application. However, the server is not started during acceptance tests when I run the tests using `ember test`, even though it works in the development environment when using `ember server`.

The Ember CLI docs refer to the mock server as if it is used during testing, so I assume that this is a bug.

**Comment by nathanhammond** [comment]
@JoshTumath Can you create a repo and that demonstrates this failing as a way to make it easier for us to trace through?

**Comment by JoshTumath** [comment]
After looking into the source code for Ember CLI, it seems that ember does not support launching the mock server when running `ember test`. This is a dupe of #1763.
