### ISSUE TITLE
Ember install fails to save bower packages when running the default blueprint

### ISSUE THREAD

**Issue by pythonquick** [ember-cli/ember-cli#5765]
When installing the ember-gestures plugin, the "ember serve" command runs fine.
However, after clearing the npm and bower cache and re-installing the bower and npm packages, the following error appears after launching "ember serve":

> version: 2.4.2
> Livereload server on http://localhost:49154
> Serving on http://localhost:4200/
> The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
> Error: ENOENT: no such file or directory, stat '/Users/pythonquick/Temp/gesty/tmp/source_map_concat-input_base_path-> 4fDIhw2m.tmp/0/bower_components/hammer.js/hammer.js'

I had a brief chat with @runspired and he thinks the ember install command fails to save bower packages when running the default blueprint of an addon. Here's the default blueprint of the ember-gestures addon: https://github.com/runspired/ember-gestures/blob/develop/blueprints/ember-gestures/index.js#L24

Here are the versions on my system:

* ember-cli 2.3.0 (also tried with 2.4.2)
* npm version 3.7.3
* node version 5.9.0
* OS X 10.10.5 (Yosemite)

Here is how to reproduce:

1. Create a new ember project
npm cache clean && bower cache clean
ember new gesty

2. Install ember-gestures in the new project
cd gesty
ember install ember-gestures

3. Inspect bower components
The bower_components directory contains the "hammer-time" directory **and also "hammer.js"**. Note: hammer.js is **not listed** in bower.json. The bower.json file lists the following dependencies:
> "ember": "~2.3.1",
> "ember-cli-shims": "0.1.0",
> "ember-cli-test-loader": "0.2.2",
> "ember-qunit-notifications": "0.1.0",
> "hammer-time": "1.0.0"

4. Run "ember serve" and note that it works initially:
ember serve
Ctrl-c to abort (once it starts up successfully)

5. Clear the bower and npm modules
rm -rf tmp node_modules bower_components
npm cache clean
bower cache clean

6. Reinstall the bower and npm modules
npm install && bower install

7. Inspect bower components:
The bower_components directory contains the "hammer-time" directory, but now it **does not contain "hammer.js"** anymore!

8. Run ember serve and it fails with the above mentioned error message
> version: 2.4.2
> Livereload server on http://localhost:49154
> Serving on http://localhost:4200/
> The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
> Error: ENOENT: no such file or directory, stat '/Users/pythonquick/Temp/gesty/tmp/source_map_concat-input_base_path-> 4fDIhw2m.tmp/0/bower_components/hammer.js/hammer.js'

**Comment by nathanhammond** [comment]
From @runspired:

> Heads up, that ember gestures issue on ember cli appears to be a legit issue
> Walked through the thing with the user
> Gave them feedback, they will update the issue
> But TL;DR, `addBowerPackagesToProject` seems to not save the dependency to bower.json only when run via the default blueprint and ember install, works if default blueprint is run individually
> Npm3, replicated on ember-cli 2.3 and 2.4
> Seems... Like maybe a spawn/sub process issue?

**Comment by jasonmit** [comment]
Did some digging and it looks like `bower.commands.install` is invoked twice, as expected.  However, the second invocation happens before the first one settles (writes its content).  This means the second call reads the bower.json into memory that is used to later write the saved change.

https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L44 `analyse` here reads bower.json and sets `that._json`

https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L111 writes `that.json` which doesn't contain the content of the first bower install since the read happened before it was written

Unsure how to fix this, perhaps a lock preventing concurrent bower installs?

**Comment by jasonmit** [comment]
@nathanhammond I believe this should be marked as a dependency bug and I've opened an issue on bower https://github.com/bower/bower/issues/2267
