### ISSUE TITLE
Stop talking to npm programmatically

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5767]
I'm not sure if this is already being worked on (since npm seems to be at `2.15.1` in this package), but I've recently asked myself why there's no documentation for npm's programmatic API.

So very recently, I've decided to suggest this as a topic for npm's CLI meeting on next Tuesday. A few minutes later, @othiym23 [replied](https://github.com/npm/npm/issues/12193#issuecomment-207617511) and told me that npm's programmatic API shouldn't be used outside of their CLI anymore and that they will talk about the "why?" part on the meeting.

**Conclusion:** Instead of loading npm and [running its methods](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js), those actions should be executed via child processes.

But of course: If you're not planning to update the npm dependency in the future, there's probably no reason to stop doing it like that. But if you'd like to, I guess it's better to use child processes (since npm will stop supporting the use of its methods outside of the CLI).

**Comment by nathanhammond** [comment]
@leo Thank you for bringing this to our attention. This is something we need to consider as we're trying to identify what our plans should be for npm as well as install/uninstall.

**Comment by leo** [comment]
[More details](https://youtu.be/vLcOkHhEt1g?t=21m)

**Comment by stefanpenner** [comment]
This is easier said then done, proper parent/child process life cycles entangling is quite tricky to get right with node, especially cross platform and especially when it comes to tear down with proper cleanup from parent to child etc. this doesn't mean it can't be done, but it isn't as simple as it may first appear

I have also had this conversation with @othiym23 when we first began using npm and I am not apposed, but the current approach has very good cross platform stability.

I do hope npm can just officially support the tiny api surface one requires to install/uninstall programmatically.

If someone wants to pursue this further an rfc experience exploring what is required and addressing my above concerns would be best.

**Comment by leo** [comment]
@stefanpenner I'd recommend re-opening this issue so that other new contributors (not just me) can start looking into this. :blush:

**Comment by stefanpenner** [comment]
IMHO this isn't an issue, but an enhancement todays state works fine.

**Comment by leo** [comment]
@stefanpenner Okay... They I guess we'll have to fix it as soon as npm really drops support for their programmatic API. Because while I'd be really happy about someone else doing it, I don't think I'll find the time to fix it by myself.
