### ISSUE TITLE
Can't remove templates dir when using pods structure

### ISSUE THREAD

**Issue by alltouch** [ember-cli/ember-cli#5768]
Hi

I am using pods structure and move all files from templates, controllers, components, routes dirs to pods. and want to delete all empty folders.

It works for controllers, components and routes, but doesn't for templates.

I see following error:

> Build error
> 
> The Broccoli Plugin: [Funnel: Funnel: Templates] failed with:
> Error: ENOENT: no such file or directory, lstat '/Users/username/WebstormProjects/project/app/templates'
>     at Error (native)
>     at Object.fs.lstatSync (fs.js:887:18) 
> 

Can we fix this?

Thanks

>

**Comment by uliseschino** [comment]
I have a project in which I moved the files to a pods structure and deleted empty folders, including templates, and in my case, I had no issues.  Might be a conflict with some add-on is causing this?

**Comment by nathanhammond** [comment]
@alltouch Can you post a simple reproduction as a repo? We have anecdotal evidence that this works from @uliseschino. Without the ability to track this down we're closing this issue. Feel free to reopen it with a reproduction at any point in time!
