### ISSUE TITLE
HTTP Streaming Support

### ISSUE THREAD

**Issue by leepfrog** [ember-cli/ember-cli#5770]
While developing an ember-app that utilizes the html5 `<video>` tag, I found that the built in ember-cli http server does not allow you to stream data.  What this means is that you're unable to preview static .mp4 content.

Other simple node http services (such as `http-server`) provide this functionality.

This "issue" is a question/suggestion -- Should ember-cli's http service provide data streaming support?

**Comment by rwjblue** [comment]
I'm not sure exactly what would need to be changed to allow streaming, or if that has trade offs. In general I think that we would be in favor of supporting as much as possible assuming that adding support doesn't break other support configurations.

**Comment by stefanpenner** [comment]
Feature requests should be provided via the rfc repo as issues if unsure, and pulls if a more fleshed out proposal exists.


(This is outlined in the contributing.md)

**Comment by nathanhammond** [comment]
@leepfrog I would be in favor of addressing this and would consider it a bug as serving static files should probably "just work" regardless of type (assuming it's not a massive undertaking). Can you investigate what it would take to build this on top of our current server setup?

**Comment by stefanpenner** [comment]
@nathanhammond streaming of content is an additional concept on top of regular static serving (think, scrubbing/seeking to various points) but yes, RFC ftw.
