### ISSUE TITLE
dist folder only builds first time on ember serve command

### ISSUE THREAD

**Issue by djbreen7** [ember-cli/ember-cli#5772]
Specs:
ember-cli: 2.4.3
node: 4.4.2
npm: 3.8.7 (previously was a 2.x and still had problems)
os: win32 x64

After upgrading ember-cli, new and old projects don't build the dist folder.

**Strategies attempted:**
- Manual refresh
- Completely removing node, npm, and all node_modules globally. Reinstalling with the latest and greatest
- Messing with live-reload including using the `-lrp` flag to another port, the `--host` flag to `0.0.0.0` as suggested in #5352, #5123, and #5391
- Set `live-reload` to false in `.ember-cli.js`, then used a different library `live-server` and started it in the dist folder. (Note the different suffix `server` instead of `reload`. These ARE different). Still nothing. I can get it to reload by actually editing files in the dist folder with `live-server` but not `live-reload`.

The main issue seems to be that the dist/ folder is only getting built once. Even with manual refresh, no changes are applied.

Reverting to 1.13.8

**Comment by rwjblue** [comment]
Can you provide steps to reproduce (along with what you are checking to see that it isn't updating dist)?

**Comment by djbreen7** [comment]
Sure.

1. `ember new foo`
2. `cd foo`
3. `ember s`
4. Make changes to `templates/application.hbs` and save. I get the message `file changes templates\application.hbs` then `Build successful` and the build report. Nothing changes in Chrome.
5. Manually refresh, still changes aren't applied.
6. When that doesn't work I kill the server and run `npm install` and `bower install`
7. In no particular order:

-  `npm link ember-cli` (not assuming it to fix it, per se, but trying anything.
- `ember s -lrp 9000` and `ember s --host 0.0.0.0`
- Also tried using `netstat -a` to see which ports were in use, then editing the `serve.js` file's portFinder to a different port.

**Comment by djbreen7** [comment]
Here's a link to a repository I just made still having the same problems. 
https://github.com/djbreen7/ejs-fresh-install
I also sent a message to the ember-cli-windows creator to see if running the `ember-cli-windows` command outside of a project folder would have caused the issue with indexing or defender, even though I've restored those to defaults.

**Comment by djbreen7** [comment]
I completely formatting my computer last night and reinstalled node and ember-cli and all that jazz. Everything is working fine now and serve time is ridiculously fast compared to what it's been on Windows for me WITHOUT ember-cli-windows

![image](https://cloud.githubusercontent.com/assets/13296622/14447449/18216854-001d-11e6-9a1b-ad59feac74a2.png)
