### ISSUE TITLE
Generated unit tests for components using pods are bad

### ISSUE THREAD

**Issue by BryanHunt** [ember-cli/ember-cli#5773]
Using ember-cli 2.4.2

ember new ember-cli-bug
set environment     podModulePrefix: 'ember-cli-bug/pods',
ember g -p component my-component
ember server

```
File: ember-cli-bug/tests/integration/pods/components/my-component/component-test.js
The Broccoli Plugin: [Babel] failed with:
Error: ember-cli-bug/tests/integration/pods/components/my-component/component-test.js: Parse error on line 1:
{{/my-component}}
^
Expecting 'EOF', 'COMMENT', 'CONTENT', 'OPEN_RAW_BLOCK', 'OPEN_BLOCK', 'OPEN_INVERSE', 'OPEN', 'OPEN_UNESCAPED', 'OPEN_PARTIAL', got 'OPEN_ENDBLOCK'
```

The problem is that in the generated unit test, the component name is prefixed with "/"

Here is an example repo: https://github.com/BryanHunt/ember-cli-bug

**Comment by rwjblue** [comment]
Thanks for reporting @BryanHunt!

**Comment by Turbo87** [comment]
I guess this issue needs to be moved to https://github.com/emberjs/ember.js and https://github.com/ember-cli/ember-cli-legacy-blueprints since the component blueprints have been moved there.
