### ISSUE TITLE
Garbage in output

### ISSUE THREAD

**Issue by simenheg** [ember-cli/ember-cli#5787]
After updating from Ember CLI 2.4.2 to 2.4.3 every line output by the `ember` program is prefixed by "[1G" (which looks like "^[[1G" in my terminal).

---

Output from ember version --verbose:
```
[1GCould not start watchman; falling back to NodeWatcher for file system events.
[1GVisit http://ember-cli.com/user-guide/#watchman for more info.
[1Gember-cli: 2.4.3
[1Ghttp_parser: 2.3
[1Gnode: 0.12.2
[1Gv8: 3.28.73
[1Guv: 1.4.2-node1
[1Gzlib: 1.2.8
[1Gmodules: 14
[1Gopenssl: 1.0.1m
[1Gos: linux x64
```

**Comment by Turbo87** [comment]
@simenheg can you tell us a bit more about your environment? operating system, shell, etc. it looks like your terminal is not able to handle ANSI color codes but `chalk` isn't detecting that.

we need some way to reproduce this, otherwise we can't fix it.

**Comment by simenheg** [comment]
Thanks for the quick response, @Turbo87. Here's the output from `uname -a`:

```
Linux x240 4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17) x86_64 GNU/Linux
```

My shell is Eshell 2.4.2 inside Emacs 25.0.92.1. Anything else you'd like to know about the environment?

Is it possible to stop Ember from outputting ANSI colors?

**Comment by Turbo87** [comment]
we use `chalk` for color output, which itself is using https://github.com/chalk/supports-color to detect if colors are available. if that package is not correctly detecting this for your environment you should probably open an issue there.

in https://github.com/chalk/supports-color/blob/master/index.js#L18-L22 you can see that they support a `--no-color` option on the command line, which should disable color output. please note though that ember will then complain about not knowing about that option.

**Comment by simenheg** [comment]
Thanks @Turbo87, passing `--no-color` removes all the colors from the output.

However "[1G" is still output in some instances.

Do you think this is also an issue with the `supports-color` module?

**Comment by Turbo87** [comment]
most likely... I don't know where else it would come from other than that.
