### ISSUE TITLE
Customising outputPaths skips minification

### ISSUE THREAD

**Issue by kevinansfield** [ember-cli/ember-cli#5795]
We've just prepped a release and found that our built file sizes are huge because they aren't being minified. On a hunch I disabled our `outputPaths` customisation and found that it was causing the minification step to be skipped.

I've worked backwards through the ember-cli versions and I'm seeing the same behaviour in all `2.x` releases. Our last release was using `1.13.15` which was minifying the JS files correctly.

Our full `ember-cli-build.js` config is available at https://github.com/TryGhost/Ghost/blob/master/core/client/ember-cli-build.js

With custom `outputPaths` specified:
```
> ember build --environment=production
Built project successfully. Stored in "dist/".
File sizes:
 - ghost.min.css: 86.46 KB (16.49 KB gzipped)
 - ghost.min.js: 1.22 MB (148.29 KB gzipped)
 - vendor.min.css: 6.92 KB (1.9 KB gzipped)
 - vendor.min.js: 4.54 MB (1.05 MB gzipped)
```

With the `outputPaths` config commented out:
```
> ember build --environment=production
Built project successfully. Stored in "dist/".
File sizes:
 - ghost.js: 659.21 KB (93.3 KB gzipped)
 - ghost.min.css: 86.46 KB (16.49 KB gzipped)
 - vendor.css: 6.92 KB (1.9 KB gzipped)
 - vendor.js: 1.51 MB (436.35 KB gzipped)
```

```
> ember --version
ember-cli: 2.4.3
node: 0.12.9
os: darwin x64
```

**Comment by Turbo87** [comment]
@kevinansfield can you provide a minimal setup to reproduce this issue?

**Comment by kevinansfield** [comment]
I've created a minimal reproduction here: https://github.com/kevinansfield/ember-cli-output-paths-test

In doing so I've discovered that it's related to the naming of the files - it's only when the output filename ends in `.min.js` that minification is skipped.

**Comment by stefanpenner** [comment]
thanks.

**Comment by rwjblue** [comment]
Our minifier does skip files ending in .min.js, that could be related...

**Comment by rwjblue** [comment]
That was changed in https://github.com/ef4/broccoli-uglify-sourcemap/pull/26

**Comment by stefanpenner** [comment]
thats right we totally do..

**Comment by rwjblue** [comment]
@stefanpenner - I think we should likely revert and rework it.  The goal was to make things a bit more ergonomic by avoiding to minify something already minified, but the change has broken minification in a few projects (Ghost, Ember itself, and at least one of my work projects).

**Comment by stefanpenner** [comment]
@rwjblue ya we can, would accept a PR

**Comment by rwjblue** [comment]
Submitted https://github.com/ef4/broccoli-uglify-sourcemap/pull/27 to revert that change for now.

**Comment by Turbo87** [comment]
that PR @rwjblue mentioned has been merged so I assume this issue here can be closed now as well. please reopen if the issue persists.
