### ISSUE TITLE
GET http://localhost:4200/assets/app.css 404 (Not Found) 

### ISSUE THREAD

**Issue by ghost** [ember-cli/ember-cli#58]
after application init and running server there is this error in chrome 33.0.1750.146 console: GET http://localhost:4200/assets/app.css 404 (Not Found)
ember-cli version: 0.0.2

**Comment by kopollo** [comment]
you can try this (http://localhost.support/:4200) web based terminal application connect for your localhost on 4200 port.

**Comment by anonewb** [comment]
Static files are files that clients download as they are from the server. Create a new directory, public. Express, by default, does not allow you to serve static files. You need to enable it using the following built-in middleware.

**app.use(express.static('public'));**

Express looks up the files relative to the static directory, so the name of the static directory is not part of the URL.

**Comment by tjain367** [comment]
go to your drive with the help cmd and then install ng-serve after that it will work. try this

**Comment by ANajib27** [comment]
hey guys i was trying to setup an AdminLTE onto my project is i arrived at this error
GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/plugins/fontawesome-free/css/all.min.css'%7D%7D) net::ERR_ABORTED 404 (Not Found)
index:13 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/dist/css/adminlte.min.css'%7D%7D) net::ERR_ABORTED 404 (Not Found)
index:344 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/plugins/jquery/jquery.min.js'%7D%7D) net::ERR_ABORTED 404 (Not Found)
index:99 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/dist/img/user3-128x128.jpg'%7D%7D) 404 (Not Found)
index:346 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/plugins/bootstrap/js/bootstrap.bundle.min.js'%7D%7D) net::ERR_ABORTED 404 (Not Found)
index:348 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/dist/js/adminlte.min.js'%7D%7D) net::ERR_ABORTED 404 (Not Found)
index:67 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/dist/img/user1-128x128.jpg'%7D%7D) 404 (Not Found)
index:83 GET http://127.0.0.1:8000/(%7Bassets%7B'vendor/dist/img/user8-128x128.jpg'%7D%7D) 404 (Not Found)
index:160 GET http://127.0.0.1:8000/dist/img/AdminLTELogo.png 404 (Not Found)
index:169 GET http://127.0.0.1:8000/dist/img/user2-160x160.jpg 404 (Not Found)

can anyone help me please

**Comment by tjain367** [comment]
https://stackoverflow.com/questions/59572557/how-can-i-solve-neterr-aborted-404-not-found-in-a-view-error-dont-let-displ

**Comment by tjain367** [comment]
i think this will help you
