### ISSUE TITLE
 Broken link for Ember CLI Deploy

### ISSUE THREAD

**Issue by nfriedly** [ember-cli/ember-cli#5807]
(Copied from https://github.com/emberjs/guides/issues/1376)

Both http://ember-cli.com/user-guide/#deployments and http://ember-cli.com/user-guide/#deployments and link to http://ember-cli.com/ember-cli-deploy/ for Ember CLI Deploy but that's a 404.

**Comment by nfriedly** [comment]
BTW, a simple solution that plays nice with GitHub pages might be to just stick a page there with a meta-refresh pointing to the new location.

**Comment by stefanpenner** [comment]
This isn't the correct repo, rather either the sites repo or the ember-deploy repo would be best.

Cc @lukemelia

**Comment by nfriedly** [comment]
Sorry, I got sent here from the first place I reported the issue...

**Comment by acorncom** [comment]
Sorry, was unclear where I should be sending folks

**Comment by acorncom** [comment]
PR has been opened here: https://github.com/ember-cli/ember-cli.github.io/pull/73

**Comment by stefanpenner** [comment]
sweet, looks resolved. Thanks all :)

**Comment by stefanpenner** [comment]
@acorncom here was fine, we can coordinate ad-hoc.
