### ISSUE TITLE
Not installing on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by jredd** [ember-cli/ember-cli#5810]
Ember-cli simply ins't installing on my machine... doesn't error out just stops and doesn't install anything. I'm using a digital ocean droplet Ubuntu 14.04.4

**Comment by joseperales** [comment]
What nodejs version are you using

**Comment by jredd** [comment]
v5.10.1

**Comment by stefanpenner** [comment]
More info please. The yellow banner you saw when submitting the issue explains what details are required. Without this it is unlikely to be actionable

My guess is npm is using to much memory and causing a small droplet with law ram to sit and swap. Try bumping ram/disk space

**Comment by fivetanley** [comment]
I think @iheanyi may have run into this when working on his digital ocean plugin for Ember CLI deploy and had to bump ram.

**Comment by iheanyi** [comment]
Yeah, definitely did. https://www.digitalocean.com/community/questions/how-to-change-swap-size-on-ubuntu-14-04 Increase the Swapfile space on your Droplet, that'll fix it.

**Comment by jredd** [comment]
@iheanyi Thanks for the info! Wish I had known earlier, I just put it on a larger droplet and it worked fine.
