### ISSUE TITLE
Creating new project using EmberCLI keep downloading modules after modules !

### ISSUE THREAD

**Issue by v3ss0n** [ember-cli/ember-cli#5822]
Its taking over 1 hr already and it is not finished downloading modules yet.
embercli 2.4.3 do not have such problem , embercli 2.5.0 happening like that.

**Comment by chadhietala** [comment]
Can you provide your node version, npm version, and os?

**Comment by v3ss0n** [comment]
the problem is with watchman , taking so much IO. after i killed it , it worked again.

**Comment by chadhietala** [comment]
Ok closing for now.

**Comment by stefanpenner** [comment]
> the problem is with watchman , taking so much IO. after i killed it , it worked again.

it should ignore node_modules, maybe your .watchmanconfig  is out of sync, or you have an old version.
