### ISSUE TITLE
Changes in imported scss files outside of /styles won't update the dist file

### ISSUE THREAD

**Issue by MartinMalinda** [ember-cli/ember-cli#5823]
I import styles like this: 

```
@import "app/application/style";
```

On file change I get a message "file changed application/style.scss Build successful - 734ms." yet no live reload happens and changes are apparent only after manually restarting the server.

Changes of scss files /style folder work just fine.

Could be ember-cli-sass issue though.

---

Output from ember version --verbose:
```
ember-cli: 2.4.3
http_parser: 2.6.2
node: 5.7.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
os: darwin x64
```

**Comment by MartinMalinda** [comment]
I did a nombom, uninstalled babel-eslint and added 
```
,
    sassOptions: {
      includePaths: ['app']
    }
```

to ember-cli-build.js

Not sure what particularly solved the issue. Don't have time atm to trace back which step exactly solved the issue. Will try to get back to this later if also someone else experiences the issue.

**Comment by nathanhammond** [comment]
Since you're saying things are working, I'm going to close this. Please reopen if you track down additional information!

**Comment by pzenger** [comment]
@MartinMalinda 's fix worked for me also.  Perhaps add this to the readme?
