### ISSUE TITLE
Create "canary" branch/tag

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5824]
In the last team meeting it was decided to create a `canary` branch or tag that automatically tracks the `master` branch. Since git itself has no such functionality we would most likely need some sort of script, triggered by a webhook on the repo, that will update the `canary` pointer.

**Comment by Turbo87** [comment]
@stefanpenner @rwjblue @nathanhammond assuming that this script will most likely be a node.js app do we have a reliable place to host it somewhere?

**Comment by stefanpenner** [comment]
heroku

**Comment by Turbo87** [comment]
okay, so I have https://github.com/Turbo87/canary-sync running at https://canary-sync.herokuapp.com now and so far it seems to work quite well

**Comment by stefanpenner** [comment]
can you be sure to add afew of us as maintainers and owners of the app?
