### ISSUE TITLE
Implement RFC #46

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5826]
[RFC #46](https://github.com/ember-cli/rfcs/blob/master/active/0046-improved-release-process.md) has landed. This is a tracking issue for implementation.

The open tasks from that are as follows:
- [ ] Tooling to support feature flags.
- [ ] Updates to the website and documentation communicating this plan.
- [ ] Teaching new patterns to ember-cli contributors, most specifically commit tagging and feature flagging.
- [ ] Increased automation of the release process. (Tracked separately as #5691.)

**Comment by Turbo87** [comment]
I guess this is somewhat related also to #5691
