### ISSUE TITLE
Failed to upgrade to 2.5.0 with npm ERR! code 1 and then "Error: Missing template processor"

### ISSUE THREAD

**Issue by seymores** [ember-cli/ember-cli#5836]
I tried to upgrade my existing ember-cli 2.4 to 2.5 by following the steps in the release note.
At the end of the install `npm install --save-dev ember-cli@2.5.0` I got this,

```
web@0.0.0 /home/ping/src/web-client
└── (empty)
npm ERR! code 1
```
And from then onwards I cannot start my ember and always get this error

```
Error: Missing template processor
```
---

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.6.1
node: 5.6.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
os: linux x64
```

**Comment by nathanhammond** [comment]
That error appears to be an `npm install` failure of something local to your machine (`/home/ping/src/web-client`). Can you `npm cache clear && rm -rf node_modules && npm install` (aka `nom`) and also verify that your local project is working correctly?

I'm closing this issue as it seems likely that resetting your environment will fix you. In the event that it doesn't please feel encouraged to reopen with more details!

**Comment by nathanhammond** [comment]
(Note that the 2.4 => 2.5 upgrade includes incredibly few changes, and is thus very unlikely to have issues itself.)

**Comment by seymores** [comment]
Thanks guys.
So after nom I did npm i --only=dev and everything works fine after that.
What I don't get it is that, I follow the instructions in the release note several times and never worked.

Anyway, I hope this will help somebody in the future.

**Comment by nathanhammond** [comment]
Is your `/home/ping/src/web-client` not a dev dependency?

**Comment by seymores** [comment]
No, that's the app folder where the ember app lives.
