### ISSUE TITLE
Inconsistencies with treeForAddon Hook

### ISSUE THREAD

**Issue by sophypal** [ember-cli/ember-cli#5838]
First let me start by explaining what I'm trying to achieve.  I'm working on a project that requires a custom build step of gathering all text files together and making it available to require/import in code. These text files could be source code or Markdown files to be rendered later with a code viewer or Markdown renderer.

## What are the requirements?

* Make an *addon* that gathers all source files under a certain directory, say `/files`, and converts them to JSON.  I can acheive this with **broccoli-flatiron**.

  Example flattened JS:
	```javascript
	export defaults {
	  "path/relative/to/files": "file contents"
	}
	```
* Merge this with the *addon* namespace so this can be imported.

	```javascript
	import files from `<my-addon>/files`
	```
* Be able to test this when developing within the *addon* and the *app* that will ultimately be consuming this *addon*

## What's working

My solution involved using the `treeForAddon` hook to modify the `addonTree` to include this flattened tree of text files.  

Here's a simplified version of the code.

```javascript
treeForAddon: function (tree) {
  var sources = new Funnel('/path/to/files', {
    include: [new RegExp(/\.(md|js)/]
  })
  var flattened = flatiron(sources, {
     outputFile: 'files.js',
     trimExtensions: true
   })
  tree = mergeTrees([tree, flattened])
  return this._super.treeForAddon.call(this, tree)
}
```

```
---output of flattened---
└── files.js

---output of tree--
└── index.js

---output of mergeTrees([tree, flattened])---
└── files.js
└── index.js

---output of _super.treeForAddon---
└── modules/
   └── modules/<addon-name>/
      └── modules/<addon-name>/index.js
      └── modules/<addon-name>/files.js
```
It works great, but it only seems to work well in Ember CLI 1.13.13.  When switching to Ember CLI 2.4.3, there's some inconsistencies in the output tree from `_super.treeForAddon`.

## What's not working?

When developing in the *addon* project, the same code will produce a very different tree.

```
---output of flattened---
└── files.js

---output of tree--
└── index.js

---output of mergeTrees([tree, flattened])---
└── files.js
└── index.js

---output of _super.treeForAddon---
└── files.js
└── modules/
   └── modules/<addon-name>/
      └── modules/<addon-name>/index.js
```

Notice that `files.js` did not make it over to `modules` and it will not get bundled together with all of `addon.js` so it never makes it to `vendor.js`.  It actually took quite a bit of work to get `broccoli-stew` logs to work with this.  Chaining any logs before the call to `_super.treeForAddon` will result in no logs at all whatsoever.  It's like it got swallowed up or **broccoli** was never able to visit the node leading up to the output from **flatiron**'s output.

What's also really strange is that when I'm developing within the consuming app that has this *addon* installed, the output tree is what I'd expect it to be.  It works, but only from within the consuming app?  I guess I could leave it as it is since it's doing its job of delivering that functionality to the app?  ¯\_(ツ)_/¯

**No**, that's not acceptable.  I need to be able test this from within the *addon*.

## Workarounds

I had to modify my code to output the flattened tree to `/modules/<addon-name>`, then merge that with the result of `_super.treeForAddon`.  The builds produced from the *addon* and the *app* are the same now.  This works but I had to look deep inside of *ember-cli* to figure out what `treeForAddon` was doing.  Not something others will be able to intuit easily.

## Now what?

Where do I go from here?  How do I troubleshoot this further.  Am I doing something obviously wrong.   Tell me this is a symptom of a much bigger problem or better still, please tell me I'm being stupid and the solution is simple.  Will be eagerly waiting your replies.

**Comment by jasonmit** [comment]
Originally reported here https://github.com/ember-cli/ember-cli/issues/4463 but seemed to have been closed.

**Comment by sophypal** [comment]
Not sure if I understand #4463 fully but it sounds like a completely different situation to me.  That issue had to do with not using `_super.treeForAddon` and not getting the default behaviors.  My issue, however, is that I'm using `_super.treeForAddon` but it's default behavior somehow changed when upgrading Ember.

**Comment by jasonmit** [comment]
> It works great, but it only seems to work well in Ember 1.13.x. When switching to Ember 2.4.x, there's some inconsistencies in the output tree from _super.treeForAddon.

I think people will find this line confusing.  I believe you're referring to Ember when you mean to say Ember-CLI.  Do you know the version you original solution worked and the version it broke?

I believe the core of the issue is very similar to https://github.com/ember-cli/ember-cli/issues/4463#issuecomment-124742654 where you're now having to write to `module/` to get your files written to where you would expect them.  That's what I was pointing out.  To me, module is a concept that should be internalized to ember-cli since it's not documented, as far as I know, and it's a common point of confusion.

**Comment by sophypal** [comment]
Sorry for the confusion @jasonmit .  I updated it to show the exact version of Ember CLI.  I see now that you've made a comment on that issue about having to use `_super.treeForAddon` first to return the tree.  I'm really surprised that there hasn't been more mentions of this issue but as I'm told, I may be doing more with Ember than most are.  My worry is that my workaround is not a viable long term solution, since it's obviously internal to Ember CLI.

**Comment by jasonmit** [comment]
@sophypal `treeForAddon` is a public API so this is likely a bug.

**Comment by Turbo87** [comment]
@sophypal is this similar to https://github.com/ember-cli/ember-cli/issues/5745?

**Comment by sophypal** [comment]
It is the same.  Closing.
