### ISSUE TITLE
After makes update to 2.5.0 my templates no are not rendered

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#5849]
I makes update with this release https://github.com/ember-cli/ember-cli/releases/tag/v2.5.0

And the data flow come to my `component.js`  but not rendered my `templates.hbs` in pod structure 

Replacing in `bower.json`: "ember": "2.5.0" to "ember": "~2.4.5" everything works.

Help me please?

**Comment by rwjblue** [comment]
Please provide a reproduction of the issue, there is very little we can do to help without understanding/seeing what is going on.

**Comment by villander** [comment]
@rwjblue look this
my template `conversation.hbs` 
```javascript
<div class="sidebar">

  {{search-profiles
      currentProfile=model.currentProfile
      changeConversationTo='changeConversationTo'
  }}

  {{conversations-list
      currentProfileConversations=model.currentProfile.conversations
      currentProfile=model.currentProfile

      changeConversationTo='changeConversationTo'

  }}

  {{current-profile
      currentProfile=model.currentProfile
  }}

</div>

<div class="conversation">
  {{outlet}}
</div>

```

my DOM 
![screen shot 2016-04-26 at 11 40 09 am](https://cloud.githubusercontent.com/assets/10222774/14822122/b436a100-0ba3-11e6-9060-cdb4adc69252.png)

**Comment by villander** [comment]
@rwjblue he not show my html static as `search-profiles.hbs`

```javascript

<div class="search-header">

  {{input  type="text"
       classNameBindings=":search-input isSearching"
       placeholder="Find or start a conversation"
       value=query
       focus-in="startSearch"
  }}

  {{!-- if isSearching show (x) close button, hide if not --}}

  <span {{action 'clearSearch'}}
    class="clearSearch {{if isSearching "showClose" ""}}">
  </span>
</div>

{{#if isSearching}}
  <div class="search">

    <h6>Conversations</h6>
    <ul class="search__conversations">
      {{#each results as |profile|}}
        {{search-profiles-item
          result=profile
          currentProfile = currentProfile
          changeConversationTo='changeConversationTo'
        }}
      {{/each}}
    </ul>

{{!--     <h6>Contacts</h6>
    <ul class="search__contacts">
      {{#each results as |profile|}}
        {{search-profiles-item
          result=profile
          currentProfile = currentProfile
          changeConversationTo='changeConversationTo'
        }}
      {{/each}}
    </ul> --}}

  </div>
{{/if}}
```

**Comment by villander** [comment]
this happens in changing the ember to 2.4.5 to 2.5.x

**Comment by rwjblue** [comment]
As I mentioned before, we need a reproduction. An example app, ember-twiddle.com, JSBin, etc that we can use to see the issue.

**Comment by villander** [comment]
@rwjblue but this is a issue this project. A new project not have this issue

**Comment by rwjblue** [comment]
Exactly! Figuring out how to isolate the issue into a reproduction will tell you **exactly** what is wrong, and often will lead you to the correct fix.

**Comment by rwjblue** [comment]
There is almost nothing that we can do (other than randomly guess) to help you without more information.

**Comment by dgeb** [comment]
@villander Try to narrow down the scope of what's not working as much as possible by selectively trimming your templates. Use [these template helpers](https://guides.emberjs.com/v2.5.0/templates/development-helpers/) to verify your assumptions. If you're able to isolate the error and it appears to be in Ember itself, please try to recreate it with an example app you can push to github or using ember-twiddle.com, as @rwjblue pointed out. Good luck!

**Comment by villander** [comment]
@dgeb Thanks, i have more experience with Ember and already checked the templates with this helpers. But my problem is very hard. I have here a big project and he not render templates and even create new components still not render. And all back to works, when change bower dependency of 2.5.0 to 2.4.5. I have no clue. This is the pain

I wanted to put into a repository, but the company i work does not allow.

**Comment by stefanpenner** [comment]
@villander maybe they will allow a private repo, shared with one of the ember-cli core team members? This would allow us to likely figure it out quickly, short of that I don't really know how to help.

**Comment by t4t5** [comment]
@villander Are you using the `ember-component-css`-addon? I noticed that I had the same problem, but it got resolved when I upgraded `ember-component-css` from 0.1.7 to 0.1.9

**Comment by Turbo87** [comment]
closing this until someone can provide a reproduction project
