### ISSUE TITLE
Run tests outside of the ember-cli folder.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5858]
We run all of our tests inside of the ember-cli folder which means we were unable to detect this failure: https://github.com/ember-cli/ember-cli/pull/5851. We can probably use something like `process.chdir('..')` to run our tests in a different scope.

/cc @Turbo87

**Comment by Turbo87** [comment]
I was wondering if we should just use a tmp folder provided by the OS?

**Comment by trentmwillis** [comment]
Why not just move/rename the `package.json` during the test? I've taken that approach in tests before that use find-up behavior.

**Comment by stefanpenner** [comment]
options:

1. use a tmp folder provided by the OS
2. I was wondering if we should just use a tmp folder provided by the OS?

compare/constrast?

**Comment by Turbo87** [comment]
I think that would probably be best. If /tmp is on a memfs that might even speed up the tests.

**Comment by stefanpenner** [comment]
This seems to have gone idle. I am all for improving this, but Im not sure aspirational (non blocking) issues provide us to much direct value. Or at-least they should likely age out if inactive for some time.
