### ISSUE TITLE
Upgrading from Ember CLI 2.4.3 to Ember CLI 2.5 is causing some sort of intermittent IIS weirdness

### ISSUE THREAD

**Issue by adam-knights** [ember-cli/ember-cli#5860]
Since upgrading to Ember CLI 2.5.0 from 2.4.3 occasionally after deploying a build from Jenkins if we try to navigate to any explicit URLs, other than the base URL, then we get the error

```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```

So to be clear, ```http://www.mysite.com``` works fine but the route http://www.mysite.com/products does not and you get the above.

If I re build and re deploy then the issue goes away. Something has changed in the build process that causes IIS issues.

The message above is received by default when using IIS unless you setup your web config to redirect everything to the index. Our web config, which worked flawlessly until the upgrade this week is below:

I imagine I'll have to put some time into making a repro - but opening as is on the off chance others are getting the same issue, or a dev will straight away know what could be causing this. But if there's no quick win i'll do this.

```
<configuration>
  <system.webServer>
	<rewrite>
	  <rules>
    <rule name="Redirect to https">
      <match url="(.*)" />
      <conditions>
        <add input="{HTTPS}" pattern="off" ignoreCase="true" />
      </conditions>
      <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" redirectType="Permanent" appendQueryString="false" />
    </rule>
    <rule name="CatchAll For Ember" patternSyntax="Wildcard" stopProcessing="true">
      <match url="*" />
      <action type="Rewrite" url="index.html" />
      <conditions>
       <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
       <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
      </conditions>
    </rule>
	  </rules>
	</rewrite>
    <staticContent>
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
    </staticContent>
  </system.webServer>

  <location path="index.html">
    <system.webServer>
      <httpProtocol>
        <customHeaders>
          <add name="Cache-Control" value="no-cache" />
        </customHeaders>
      </httpProtocol>
    </system.webServer>
  </location>
</configuration>
```

**Comment by rwjblue** [comment]
ember-cli@2.4.3 and ember-cli@2.5.0 are **extremely** similar (see the [diff here](https://github.com/ember-cli/ember-cli/compare/v2.4.3...v2.5.0)). 

Did you make any other changes to your application at the same time as you upgraded ember-cli version? Updating Ember version perhaps?

**Comment by adam-knights** [comment]
Actually yes - we took ember 2.5.1 at the same time - should I close this in favor of something there?

**Comment by Turbo87** [comment]
@adam-knights I guess without a way to reproduce this issue there isn't much we can do here.

**Comment by stefanpenner** [comment]
Will reopen with reproduction, even snapshots of the code that works and the code that doesn't (running) but without that this is unfortunately not actionable :(
