### ISSUE TITLE
CLI says node v5.x will soon be unsupported

### ISSUE THREAD

**Issue by clayreimann** [ember-cli/ember-cli#5861]
Running any ember command I see the warning `Future versions of Ember CLI will not support v5.10.1. Please update to Node 0.12 or io.js.`. I guess this PR didn't fix the issue: https://github.com/ember-cli/ember-cli/pull/4815
`
```
→ ember -v --verbose
Future versions of Ember CLI will not support v5.10.1. Please update to Node 0.12 or io.js.
version: 1.13.8
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
npm: 2.13.4
os: darwin x64
→ 
```

**Comment by Turbo87** [comment]
@clayreimann the PR you linked was first involved in ember-cli v1.13.9 and you seem to be running v1.13.8. Please update ember-cli and try again.

**Comment by clayreimann** [comment]
Yeah, looks like it was a homebrew + npm + permissions issue. Just came to close the bug
