### ISSUE TITLE
Re-enable Addon Smoke Test in Windows

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5863]
In order to make AppVeyor reliable we disabled a test: https://github.com/ember-cli/ember-cli/pull/5850

We should solve the underlying issue with this test to make it reliable on Windows.

**Comment by stefanpenner** [comment]
This likely needs investigation/exploration to see what is going on on windows.

**Comment by locks** [comment]
This has been meanwhile addressed!
