### ISSUE TITLE
environment.baseURL is interpreted as regex by tests-server

### ISSUE THREAD

**Issue by les2** [ember-cli/ember-cli#5876]
Trying to use a `baseURL` of `/foo/++` doesn't work (you can't serve the app with ember `serve`).

According to [some specification](http://tools.ietf.org/html/rfc3986#section-3.3), `+` should be allowed in the URL segments.

# Steps to Reproduce
1. Create a new ember project: `ember new foo`
2. Change the baseURL in `config/environment.js` to `/foo/++`
3. Try to serve the app with `ember serve`

```
✗ ember serve
version: 2.4.2
Invalid regular expression: /^/foo/++/tests/: Nothing to repeat
SyntaxError: Invalid regular expression: /^/foo/++/tests/: Nothing to repeat
    at new RegExp (native)
    at TestsServerAddon.serverMiddleware (/Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/lib/tasks/server/middleware/tests-server/index.js:20:21)
    at Class.<anonymous> (/Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/lib/tasks/server/express-server.js:105:22)
    at /Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/lsmith/projects/socialcode/ember-bug/foo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

---

Output from ember version --verbose:
```
version: 2.4.2
http_parser: 2.5.0
node: 4.2.6
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
os: darwin x64
```

# Excerpt from RFC 3986

```
path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
                    / path-noscheme   ; begins with a non-colon segment
                    / path-rootless   ; begins with a segment
                    / path-empty      ; zero characters

      path-abempty  = *( "/" segment )
      path-absolute = "/" [ segment-nz *( "/" segment ) ]
      path-noscheme = segment-nz-nc *( "/" segment )
      path-rootless = segment-nz *( "/" segment )
      path-empty    = 0<pchar>
```

```
segment       = *pchar
      segment-nz    = 1*pchar
      segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                    ; non-zero-length segment without any colon ":"

      pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

```
   pct-encoded   = "%" HEXDIG HEXDIG

   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   reserved      = gen-delims / sub-delims
   gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

# Willing to Help

I am willing to help, even write code. But I am new to Ember! Any suggestions?

For now, I can just not use that character in my URL, but it would have been really cool, as in: `/c/++/`

**Comment by rwjblue** [comment]
Issue is with https://github.com/ember-cli/ember-cli/blob/v2.4.2/lib/tasks/server/middleware/tests-server/index.js#L20.

Solution would be operate on plain strings instead of the regexp.  Something like this around [here](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/tests-server/index.js#L35) should do the trick:

```js
var isForTests = req.path.indexOf(baseURL + 'tests') === 0;
```

**Comment by les2** [comment]
there should be a "pattern.quote" function we can use. need to Google exact function name. will attempt pr when i get a moment.

**Comment by les2** [comment]
see escape function here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

```function escapeRegExp(string){
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); // $& means the whole matched string
}
```

No built in function in js.

**Comment by rwjblue** [comment]
I don't think we need the regexp version  seems like a simple req.path.indexOf would work, no?

**Comment by stefanpenner** [comment]
@les2 friendly ping

**Comment by les2** [comment]
got some vacation coming up tomorrow. hoping to submit PR then.

**Comment by les2** [comment]
actually looking at this now

**Comment by les2** [comment]
unit test is hardest part :(

**Comment by les2** [comment]
Okay - got a PR. Wrote unit test (first) demonstrating bug and then fixed (in case folks are into that kinda thing). Let me know if you want the commits squashed - was trying to make the review easier.

Also let me know if I've made some newbie style mistakes.
