### ISSUE TITLE
Routing error on IE8/9

### ISSUE THREAD

**Issue by vedharish** [ember-cli/ember-cli#5878]
Hello,

I was trying to run tests with ember-cli and had a weird issue. I had opened up issues testem/testem#846 and emberjs/ember.js#13368 and have been told to report it here.

The issue is that when I run the sample tests that ember-cli generates automatically with `ember new-app`, the tests run fine except on IE8 and IE9. I tried this locally and on BrowserStack.

Basically the tests just hangs/ gets timed out on IE8/9. To debug this issue, I added logging lines to `node_modules/ember-cli/node_modules/testem/lib/server/index.js` and saved the logs in a file.
If we follow the instructions below, and check the `testem_server_log.txt` file, there are log lines such as `7 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\vendor.css'`.

I see these only for IE8/9. And when I check locally, the path `C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\assets\vendor.css` is present. Other browsers request for the second path and are resolved correctly. So, this might be an issue with wrong file getting requested for these browsers. 

---

Instruction to reproduce on BrowserStack from a linux/mac system is [here](https://gist.github.com/vedharish/3568ae5193185c71aa283fd227489fc1)
Instruction to reproduce locally on windows - 
```
git clone https://gist.github.com/3568ae5193185c71aa283fd227489fc1.git && cd 3568ae5193185c71aa283fd227489fc1
npm install ember-cli -g
ember new my-app && cd my-app
## Change testem.js to use "IE" in ci instead of default "PhantomJS" -- "launch_in_ci": [ "IE" ]
git apply ../windows.patch
cd node_modules/ember-cli/node_modules/testem/ && npm install --save npmlog-file
## cd back to my-app folder

To test - node_modules\.bin\ember test
## View the logs in testem_server_log.txt
```

The following output is from IE8/win7 system I tried on today.
I had also tried on IE9/win7 system some time back.
Output from ember version --verbose:
```
C:\Users\win7\Desktop>ember version --verbose
ember-cli: 2.5.0
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: win32 x64
```
Output from the log file -
```
0 info Test'em starting..
1 info Seeking for config file...
2 info Starting ci
3 info Starting server
4 info Start triggered test run.
5 info Running tests...
6 info spawning: C:\Program Files\Internet Explorer\iexplore.exe - ["http://localhost:7357/7664/tests/index.html?hidepassed"]
7 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\vendor.css'
8 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\my-app.css'
9 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\test-support.css'
10 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\testem.js'
11 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\vendor.js'
12 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\test-support.js'
13 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\my-app.js'
14 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\tests.js'
15 error ENOENT: no such file or directory, stat 'C:\Users\win7\Desktop\test\3568ae5193185c71aa283fd227489fc1\my-app\tmp\class-tests_dist-eJBsFm9n.tmp\tests\assets\test-loader.js'
```

PS - I understand that support for IE8 has been dropped. I am just noting it here in the hope that it might help in debugging.

**Comment by stefanpenner** [comment]
@vedharish thanks for the detailed issue, sorry we haven't had a chance to dig in yet.

**Comment by Turbo87** [comment]
@kellyselden could you take a quick look at this?

**Comment by kellyselden** [comment]
Just tried with IE8. Couldn't even get the welcome page to show, let alone the tests working. 😦

**Comment by vedharish** [comment]
Hey @kellyselden I made a repo [here](https://github.com/vedharish/ember-tests) (I followed the steps and added the node_modules with it to the repo). This might help in reproducing the error.

**Comment by stefanpenner** [comment]
Will gladly reopen if this is still an issue (with IE9 or greater)
