### ISSUE TITLE
Allow `ember destroy some-addon-name`

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#5884]
It should be possible to run `ember destroy some-addon` (if only for testing) destruction of an addon's default blueprint.

With `ember generate`, we defer to the blueprint itself (where it is common for the addon to implement a `normalizeEntity` function that allows no entity name to be specified) to throw an error if the entity name is not valid, see:

* https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L441-L445
* https://github.com/ember-cli/ember-cli-normalize-entity-name/blob/master/index.js#L7-L11

However with `ember destroy`, we throw eagerly in the command, see:

* https://github.com/ember-cli/ember-cli/blob/87154e7975c6be13375bb7fed977a9f63ddccb19/lib/commands/destroy.js#L40-L44

**Comment by ryanolsonx** [comment]
I'm interested in taking a swing at this one 😁

**Comment by stefanpenner** [comment]
this should be an RFC

**Comment by nathanhammond** [comment]
@ryanolsonx We'd absolutely love your help on this! I'm not particularly familiar with this area of the codebase,

**Comment by ryanolsonx** [comment]
@nathanhammond Perfect. Thanks for the long reply on this! It really helps.  I'll investigate and figure out what the change will be.  After that, I'll figure out the Ember CLI RFC process and work on getting one open. 😁

**Comment by ryanolsonx** [comment]
So if I'm understanding this correctly, we could simply remove:
- https://github.com/ember-cli/ember-cli/blob/87154e7975c6be13375bb7fed977a9f63ddccb19/lib/commands/destroy.js#L40-L44

And push the responsibility to the add-on (using add-on hooks) to throw an error if an entity name is required for destroy?

Is this correct?

**Comment by nathanhammond** [comment]
@ryanolsonx I think so? @rwjblue would have to confirm.

**Comment by ryanolsonx** [comment]
Something to really consider here is how we destroy the add-on.  It seems that our default destroy command is able to reverse the blueprint properly.. but it doesn't remove the npm module that gets installed and added to package.json.  Should that be something we add along with this change?

**Comment by nathanhammond** [comment]
If you need to modify `package.json` it would go inside the [blueprint itself](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/index.js). [Similarly to the way it is done here.](https://github.com/ember-cli/ember-cli-legacy-blueprints/blob/master/blueprints/route/index.js)

**Comment by ryanolsonx** [comment]
@nathanhammond That's what I was thinking too. An add-on could easily hook into afterUninstall to clean itself up (nom module-wise) using removePackageFromProject.

**Comment by stefanpenner** [comment]
Closing in-favor of a well fleshed out RFC.
