### ISSUE TITLE
Observer not working when using component Helper after one time

### ISSUE THREAD

**Issue by fahian** [ember-cli/ember-cli#5890]
When we use component helper instead of directly using component name then the observer is not working after 1st usage.

Here is a JSBin link for a demo of the issue. http://jsbin.com/sefubazika/edit?html,js,output

Here is a JSBin link for a demo of the same code without component helper (directly using component name) where the observer works http://jsbin.com/cemavoqifo/edit?html,js,output

**Comment by stefanpenner** [comment]
Doesn't seem related to ember-cli, maybe an ember issue?

**Comment by fahian** [comment]
it could be. But i found out the issue while working on ember-cli project.

**Comment by stefanpenner** [comment]
> it could be.

most likely is't, as ember-cli doesn't modify ember and your reproductions demonstrate the issue exists without ember-cli
