### ISSUE TITLE
Inappropriate asset URL construction in v2.6.0-beta.2

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-cli#5893]
I'm seeing improperly constructed asset URLs in newly-created addons in `v2.6.0-beta.2`

### To reproduce

1. create a new addon
2. remove `ember-welcome-page` from `package.json`
3. `ember s`
4. http://localhost:4200
5. Open dev tools (and refresh)

You'll see something like this 

![screen shot 2016-05-10 at 12 24 13 pm](https://cloud.githubusercontent.com/assets/558005/15159952/1b8826f4-16ac-11e6-9d68-aa7e5455e882.png)

### My Suspicion

There have been some recent changes to `rootURL` -- it's probably worth checking whether one of them has introduced a regression. 

This problem is not reproducible in ember-cli `v2.5.0`

### Output from ember version --verbose:
```
ember-cli: 2.6.0-beta.2
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: darwin x64
```

**Comment by rwjblue** [comment]
The ember-cli@2.6.0-beta.2 blueprint does not include `{{rootURL}}` in the `<script>` tags ([see here](https://github.com/ember-cli/ember-cli/blob/v2.6.0-beta.2/blueprints/app/files/app/index.html#L20-L21)).

I suspect you ran `ember new foo` while using ember-cli#master, and then the subsequent app ended up using `2.6.0-beta.2`.

**Comment by mike-north** [comment]
aha, you are correct. My _project_ ember-cli version ends up being whatever is in the blueprint, despite the global version of ember-cli being some sha.
