### ISSUE TITLE
unable to install ember-cli globally - deprecated lodash-node and graceful-fs

### ISSUE THREAD

**Issue by ziali088** [ember-cli/ember-cli#5897]
```
lsb_release -irc
Distributor ID:	Ubuntu
Release: 14.04
Codename: trusty
```
npm version: 2.15.1
node version: 0.12.14

Hi team,

The following happens when running `sudo npm install -g ember-cli`:

```
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

The `ember` command is not installed after the above command is finished, could I have some info on how to install the ember-cli properly in this case?

thanks!

**Comment by Turbo87** [comment]
this was already reported in https://github.com/ember-cli/ember-cli/issues/5539

also: you shouldn't need to use `sudo` to install NPM packages globally. maybe that is the actual problem here?

**Comment by ziali088** [comment]
ah thanks for the reference, i have tried without sudo and it makes no difference. thank you!

**Comment by stefanpenner** [comment]
seems to work fine, merely a harmless warning.

**Comment by ziali088** [comment]
yes you're right, sorry for the premature report. it was a permissions issue, so i installed nvm and got everything working from there.

**Comment by MinThuRaine** [comment]
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.


same Problem Help!!

**Comment by Turbo87** [comment]
@MinThuRaine those are just warnings, you can still use the program.
