### ISSUE TITLE
Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by akarineb** [ember-cli/ember-cli#5903]
I'm trying to sign my extension mozilla with jpm but is always giving the same mistake in xpi

"JPM [error] FAIL
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ANAKAR~1\AppData\Local\Temp\tmp-extracted-xpi-6604RrKjbXCVw94C\modules'
at Error (native)
at Object.fs.rmdirSync (fs.js:763:18)
at _rmdirRecursiveSync (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\tmp\lib\tmp.js:285:10)
at Object._cleanupCallback as remove
at C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\lib\utils.js:170:18
at tryCatchReject (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:845:30)
at runContinuation1 (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:804:4)
at Fulfilled.when (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:592:4)
at Pending.run (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:483:13)
at Scheduler._drain (C:\Users\AnaKarine\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:62:19)"

Does anyone know how to fix ?
My operating system is Windows 10

**Comment by stefanpenner** [comment]
@akarineb sorry, I'm not sure how this relates to ember-cli. What is JPM ?

**Comment by frederikbosch** [comment]
Im also running into this. When running `ember s` or `ember build` the dist folder is not empty. The error shows when running twice or more.  Im using `Funnel` to copy additional assets.

```
EEXIST: file already exists, mkdir '/workspace/app/dist/res'
Error: EEXIST: file already exists, mkdir '/workspace/app/dist/res'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
```

**Comment by stefanpenner** [comment]
@frederikbosch yes that issue is already known and has an open issue.

**Comment by frederikbosch** [comment]
@stefanpenner Alright, I ran into the issue, thought it was this one so I replied here.

**Comment by akarineb** [comment]
@frederikbosch 
sorry , I think something happened and the information disappeared without my noticing. 
already I put everything back up

**Comment by frederikbosch** [comment]
@stefanpenner I think this one can be closed then.

**Comment by stefanpenner** [comment]
@akarineb Can you share what JPM is, and how ember-cli relates to it?

**Comment by frederikbosch** [comment]
@stefanpenner I guess it is [this package](https://www.npmjs.com/package/jpm).

**Comment by stefanpenner** [comment]
> @stefanpenner I guess it is this package.

Yes, but I'm still unclear how ember-cli relates to it. From my perspective this issue doesn't yet seem related to this project.

**Comment by stefanpenner** [comment]
Ok concretely, https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md outlines what is required for a actionable issue. Using that, please update/amend this issue so we can see whatsup.

**Comment by frederikbosch** [comment]
@stefanpenner If I were you, I would close the issue. Nobody can make any sense of the original report in relation to ember-cli.

**Comment by stefanpenner** [comment]
My guess is an ember add-on is invoking jpm, and jpm may not work correctly on windows. If that is the case, I suspect jpm would be the one requiring the issue. But i suspect with some more info we would be able to diagnose or atleast pull in the right people. I would love for our friends over at mozilla to get a good bug report out of this.

**Comment by stefanpenner** [comment]
@teddyzeenny any thoughts?

**Comment by teddyzeenny** [comment]
Ember Inspector uses @rpl's [grunt-jpm](https://github.com/rpl/grunt-jpm). It's a great tool and we're having no issues with ember-cli + jpm at the moment. Though an ember-cli-jpm addon could be a good idea too 👍 as we currently finish the ember-cli build, take the built `dist` folder, and then switch to grunt to use jpm - which means the build process is kind of split into two parts/tools at the moment because of that.
