### ISSUE TITLE
Docs: generator options

### ISSUE THREAD

**Issue by SpikedKira** [ember-cli/ember-cli#5904]
http://ember-cli.com/extending/#generators-and-blueprints

"The afterInstall and afterUninstall hooks receives the same arguments as locals"

"ember generate controller foo --type=array --dry-run"
"The object passed to locals looks like this:"
```
{
  entity: {
    name: 'foo',
    options: {
      type: 'array'
    }
  },
  dryRun: true
}
```

I believe options.entity.options is incorrect.
Seems like I am receiving:
```
{
  entity: {
    name: 'foo'
  },
  dryRun: true,
  type: 'array'
}
```

**Comment by Turbo87** [comment]
@SpikedKira thanks for reporting this. could you raise this issue at https://github.com/ember-cli/ember-cli.github.io?

**Comment by SpikedKira** [comment]
my bad; https://github.com/ember-cli/ember-cli.github.io/issues/78

**Comment by Turbo87** [comment]
cool, thanks!
