### ISSUE TITLE
Implement module unifications resolution (new ember project layout)

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#5905]
I didn't see any open/closed issues for this, but it would be really cool to have!

https://github.com/dgeb/rfcs/blob/module-unification/text/0000-module-unification.md#example-application

**Comment by stefanpenner** [comment]
Not a bug, but a whole new feature. https://github.com/ember-cli/rfcs is more appropriate.

**Comment by NullVoxPopuli** [comment]
oh cool, thanks. I didn't know where to post that kinda stuff. I'll keep that in mind for next time!

**Comment by stefanpenner** [comment]
@NullVoxPopuli nope this was fine.

i'll defer to @rwjblue  to decide if we also need an ember-cli rfc or not.

**Comment by rwjblue** [comment]
We will definitely need an ember-cli RFC to propose the specific node-land API's that will support the main Ember RFC.  However, I would like (and am working towards) having a spike that we can use to inform the specific ember-cli RFC.
