### ISSUE TITLE
phantomjs --version in .travis.yml is wrong version

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#5906]
found here https://github.com/ember-cli/ember-cli/pull/5901#issuecomment-219645184

might need to change to something like `node_modules/phantomjs-prebuilt/bin/phantomjs --version`. I might get to it, but anyone feel free to fix!

**Comment by Turbo87** [comment]
given that the test output shows the major and minor version of PhantomJS and the `npm install` output even shows the patch version, is there a need to printing it to the console at all?

**Comment by kellyselden** [comment]
I guess the only benefit is it is in an expected place with the other version printers. You don't have to go searching.
