### ISSUE TITLE
"npm install -g ember-cli" does not install the latest version of ember

### ISSUE THREAD

**Issue by Dan503** [ember-cli/ember-cli#5913]
I noticed this when I ran into [this issue](https://github.com/ember-cli/ember-cli/issues/4661)

`npm install -g ember-cli` does not install the latest version of ember. It installs version 0.2.7.

Since you have this on your homepage:

<img src="http://grabilla.com/06514-6d2458be-6355-49eb-8a70-ffa2f7061c7a.png">

It is very confusing for new users as the 0.2.7 version of ember doesn't work and typing `ember update` into the console doesn't update it to the latest version either.

In order to do a working install, you need to type `npm install -g ember-cli@2.5` into the console.

**Comment by stefanpenner** [comment]
`npm install -g ember-cli` with a working version of `npm` installs the most recent version (just checked). Unfortunately it is possible to have a broken/stale npm, or be connected to a stale mirror. This can cause issues. Unfortunately currently we do depend on a working version of `npm` to be already installed.
