### ISSUE TITLE
[Bug] Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by offirgolan** [ember-cli/ember-cli#5923]
Output from ember version --verbose:

```
version: 2.4.2
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
os: darwin x64
```

My app was working fine until I did a full reinstall of my dependencies. I cleaned the cache for both npm and bower, reinstalled dependencies and ran `ember s` which gave me the following output:

```
TypeError: Cannot read property 'name' of undefined
    at /path/to/project/foo/node_modules/ember-cli/lib/models/project.js:520:53
    at /path/to/project/foo/node_modules/ember-cli/node_modules/lodash/_createFind.js:24:14
    at baseFindIndex (/path/to/project/foo/node_modules/ember-cli/node_modules/lodash/_baseFindIndex.js:17:9)
    at findIndex (/path/to/project/foo/node_modules/ember-cli/node_modules/lodash/findIndex.js:53:10)
    at /path/to/project/foo/node_modules/ember-cli/node_modules/lodash/_createFind.js:19:17
    at Project.findAddonByName (/path/to/project/foo/node_modules/ember-cli/lib/models/project.js:519:20)
    at Class.module.exports.templateCompilerPath (/path/to/project/foo/node_modules/ember-cli-htmlbars-inline-precompile/index.js:38:30)
    at Class.module.exports.included (/path/to/project/foo/node_modules/ember-cli-htmlbars-inline-precompile/index.js:17:33)
    at EmberApp.<anonymous> (/path/to/project/foo/node_modules/ember-cli/lib/broccoli/ember-app.js:416:15)
    at Array.filter (native)
```

Looks like the issue is coming from [here](https://github.com/ember-cli/ember-cli/blob/v2.4.2/lib/models/project.js#L520) where `name` is `ember-core`.

**Comment by offirgolan** [comment]
Looked like it was a dependency mismatch issue. Solved it by using the following npm packages:

```
    "ember-cli-htmlbars": "1.0.7",
    "ember-cli-htmlbars-inline-precompile": "0.3.1"
```

**Comment by stefanpenner** [comment]
what where the packages before?

**Comment by offirgolan** [comment]
@stefanpenner

```
  "ember-cli-htmlbars": "1.0.8",
  "ember-cli-htmlbars-inline-precompile": "0.3.2"
```

**Comment by stefanpenner** [comment]
i thought this was sorted out, it shouldn't have cost grief for older configs. Will investigate

**Comment by nathanhammond** [comment]
@stefanpenner ping

**Comment by stefanpenner** [comment]
is this still reproducible @offirgolan

**Comment by offirgolan** [comment]
@stefanpenner after upgrading our app to Ember 2.6 as well as upgrading ember-cli-htmlbars and ember-cli-htmlbars-inline-precompile to their latest versions, my issue was resolved. If you would like, I can create a dummy app and see if I can replicate the issue I found in Ember 2.5 with the above versions.

**Comment by stefanpenner** [comment]
meh, its ok. I'm very pressed on time, if someone else hits we can investigate again.

thanks :)
