### ISSUE TITLE
Documentation seems outdated on using a different build than release

### ISSUE THREAD

**Issue by remkoboschker** [ember-cli/ember-cli#5929]
The documentation reads that a ember-data release channel can be chosen in the bower.json. I believe ember-data is now an ember-addon installed via npm. Also I would like to know how I can define using the long term support release channels for ember and ember-data. Do they still exist?

````
Using canary build instead of release

In bower.json instead of a version number use:

"ember": "components/ember#canary",
And, following dependencies add resolutions:

"resolutions": {
  "ember": "canary"
}
This can also be applied to Ember Data:

"ember-data": "components/ember-data#canary",
And, adding to resolutions:

"resolutions": {
  "ember-data": "canary"
}
````

**Comment by Turbo87** [comment]
I assume you're talking about the documentation on the Ember CLI website. If so then please open this issue in the corresponding repo at https://github.com/ember-cli/ember-cli.github.io.

Regarding "ember-data": you are right, it is now an addon and can be changed in the `package.json` file.

LTS: "ember-data" doesn't have an LTS channel (yet), and Ember LTS can be used via `components/ember#lts-2-4` AFAIK
