### ISSUE TITLE
Hbs not minified in production

### ISSUE THREAD

**Issue by ctjhoa** [ember-cli/ember-cli#5937]
Hi,

In production environment hbs files are not minified before compiled.

Reproduction steps:
- `ember init`
- modify the `application.hbs` as follow:
```
ctjhoa@cl-mackbook ~/Downloads/ember-todo % cat app/templates/application.hbs
<h2 id="title">Welcome to Ember</h2>
                                  THIS IS A TAB CONTENT
{{outlet}}
```
- result after a `ember build --environment="production"`
```
ctjhoa@cl-mackbook ~/Downloads/ember-todo % cat dist/assets/ember-todo-0196e09f5d4f0f4424a8687103cc671c.js
....... e.createTextNode("\n                                  THIS IS A TAB CONTENT\n"); .........
```

Create a node not trimed before the compile task increase the size of the dist `.js` for no reason.
We can also reproduce this issue with eol and see node with `\n` added to the DOM.
In a case of an hbs file with a lot of indentation it become extremely important.

---

Output from ember version --verbose:
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.5.1
node: 5.11.0
os: linux x64

```

**Comment by rwjblue** [comment]
This isn't a bug. Whitespace cannot be stripped from a framework standpoint. There are a number of cases where the whitespace is intended to be displayed as written in the template, and we cannot determine thise scenarios automatically.

**Comment by ctjhoa** [comment]
@rwjblue AFAIK, according to the [HTML specification](https://www.w3.org/TR/REC-html40/struct/text.html#h-9.1) : 
>For all HTML elements except PRE, sequences of white space separate "words" (we use the term "word" here to mean "sequences of non-white space characters"). When formatting text, user agents should identify these words and lay them out according to the conventions of the particular written language (script) and target medium.

Which other scenarios do you have in mind ?

**Comment by rwjblue** [comment]
One example is:

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by Turbo87** [comment]
@ctjhoa it might be possible to do this in an addon though for those users that don't use `<pre>` or the `white-space` CSS attribute. Unfortunately I'm not aware of any HBS minifier and using htmlmin will most likely result in problems.

**Comment by topaxi** [comment]
[html-minifier](https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates) works with Handlebars:
https://github.com/kangax/html-minifier/wiki/Minifying-Handlebars-templates

Though this won't work with property assignments like:
```handlebars
<input type="checkbox" checked={{get 'someBoolean'}}>
```

I've opened an issue about this here: https://github.com/kangax/html-minifier/issues/660

**Comment by rwjblue** [comment]
It is possible to do this via an AST transform that trims TextNode's. I will try to whip up a demo...

**Comment by stefanpenner** [comment]
This isn't a bug, addon seems appropriate if the addon does well and the concerns bellow or mitigated an rfc to include it in a default install is appropriate

**Comment by ctjhoa** [comment]
https://github.com/topaxi/ember-cli-hbs-minifier

**Comment by ctjhoa** [comment]
Other addons:
https://github.com/BBVAEngineering/ember-cli-htmlbars-minifier
https://github.com/simplabs/ember-hbs-minifier
