### ISSUE TITLE
Blueprint util on ember-add-on with pod wrong folder structure 

### ISSUE THREAD

**Issue by morhook** [ember-cli/ember-cli#5942]
The following steps:
```bash
$ ember new new-addon
$ cd new-addon
$ ember generate util process --pod
installing util
  create addon/utils/process.js
installing util-test
  create tests/unit/utils/process-test.js
installing addon-import
  create app/process/util.js
```

Latest `app` file has a wrong folder, thus breaking the build:

```
not ok 10 PhantomJS 2.1 - TestLoader Failures: dummy/tests/unit/utils/process-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            missingModule@http://localhost:7357/assets/vendor.js:210:93
            findModule@http://localhost:7357/assets/vendor.js:221:30
            reify@http://localhost:7357/assets/vendor.js:151:32
            build@http://localhost:7357/assets/vendor.js:173:15
            findModule@http://localhost:7357/assets/vendor.js:223:14
            requireModule@http://localhost:7357/assets/vendor.js:26:22
            require@http://localhost:7357/assets/test-loader.js:67:16
            loadModules@http://localhost:7357/assets/test-loader.js:58:25
            load@http://localhost:7357/assets/test-loader.js:89:35
            http://localhost:7357/assets/test-support.js:6477:20
        message: >
            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:6468:15
            require@http://localhost:7357/assets/test-loader.js:69:31
            loadModules@http://localhost:7357/assets/test-loader.js:58:25
            load@http://localhost:7357/assets/test-loader.js:89:35
            http://localhost:7357/assets/test-support.js:6477:20: Could not find module `dummy/utils/process` imported from `dummy/tests/unit/utils/process-test`
        Log: |
    ...
```
So this is generating a wrong folder structure (and import) in `app` structure. I would expect that the file in app was `app/utils/process.js` with the following content:
```
export { default } from 'new-addon/utils/process';
```

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.5.2
node: 4.4.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: linux x64
```

I'm not sure if this is related with #5908 , but looks like it.

**Comment by morhook** [comment]
I've found a workaround for this case, running without `--pod` the same `addon/utils/process.js` file is generated AND the correct `app/utils/process.js` file is generated.

**Comment by Turbo87** [comment]
this seems to work correctly for controllers (see https://github.com/ember-cli/ember-cli/pull/5985/commits/e07b2193f09b258b47b25663df422cc55eafcbc7#diff-3eacd41a7e4a2d1b00c2f207a8a23975R133), so I'm not sure if the solution in #5964 is practical. we might have to filter on the `originBlueprintName` property to decide if we should use the Pods code path or not.

**Comment by morhook** [comment]
Right! This change will break the 'controller' generation (as that one is using the --pod parameter correctly). I'll rollback this change

**Comment by morhook** [comment]
What about the initial code https://github.com/emberjs/ember.js/pull/13624 ? That one should fix this issue (I think we'll also need to modify https://github.com/ember-cli/ember-cli-legacy-blueprints , as the ember-blueprints code seem to be duplicated in both repos )

**Comment by Turbo87** [comment]
> we might have to filter on the originBlueprintName property to decide if we should use the Pods code path or not.

I think the suggestion above would be the right way to proceed, but since I have never used Pods myself I'd like to get other opinions first... @rwjblue @stefanpenner @nathanhammond ?

**Comment by stefanpenner** [comment]
pods are more or less frozen, as we are on the cusp of a more holistic solution: https://github.com/emberjs/rfcs/pull/143

**Comment by nathanhammond** [comment]
I've never used pods and given our future changes I don't want to recommend that anybody build an application with pods. The earliest this could make a release version (2.8) and we'll hopefully have support for the module unification RFC at that time.

**Comment by nathanhammond** [comment]
Closing as we have elected not to provide additional support for pods.
