### ISSUE TITLE
app.import does not work for AMD modules that use universal module definition (UMD)

### ISSUE THREAD

**Issue by les2** [ember-cli/ember-cli#5953]
Possible bug or opportunity for improvement in ember-cli regarding `app.import` of AMD modules (or more likely I'm just not doing it right).:

- I installed the `cookie` package via bower: `bower install cookie --save`. The `cookie` module contains this universal module loader code:

- When I try to add the module to the ember app with:

```
  app.import('bower_components/cookie/cookie.js', {
    exports: {
      'cookie': [
        'default'
      ]
    }
  });
```

as described [here](http://ember-cli.com/user-guide/#managing-dependencies) I am unable to import the module in my app using `import cookie from 'cookie';`

- Looking at the `cookie.js` module, I noticed this universal module loader code:

```
	// If an AMD loader is present use AMD.
	// If a CommonJS loader is present use CommonJS.
	// Otherwise assign the `cookie` object to the global scope.

	if (typeof define === 'function' && define.amd) {
		define(function () {
			return cookie;
		});
	} else if (typeof exports !== 'undefined') {
		exports.cookie = cookie;
	} else window.cookie = cookie;
```

(I suspected that the `define.amd` check is problematic as I don't think Ember sets this property based on an earlier debugging session.)

- I edited the cookie module by commenting out the `define.amd` requirement and then I get this error:

```
Error: an unsupported module was defined, expected `define(name, deps, module)` instead got: `1` arguments to define` at http://localho
st:7357/assets/vendor.js, line 59
```

(Getting somewhere).

-. Finally, I changed the `define` in the cookie module to: `define('cookie', [], ...)` and everything worked.

### My question is: does or should ember-cli support modules that use the universal module format? Are their special instructions needed to get it to work?

See Also:
- [Universal Module Definition](https://github.com/umdjs/umd)
- [What Is AMD, CommonJS, and UMD?](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/)

---

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.6.2
node: 5.7.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f
os: darwin x64
```

**Comment by stefanpenner** [comment]
These need to be de-anonymized first, there was work by @ef4 to make this work by default, but unfortunately it  introduced a serious performance regression and was reverted, if that performance regression was addressed it would be accepted.

**Comment by les2** [comment]
@stefanpenner would folks accept a documentation fix stating that ember doesn't support AMD dependencies that use UMD or are AMD anonymous modules? one can easily waste hours trying to figure this out and report an issue. and the fact that it is a known issue and not even an edge case makes the waste of time even more painful.

@ef4 was the performance regression is limited to cases where the UMD rewriting was used? would it be acceptable if that could be achieved? what was your PR? i could try to optimize it.

in any event, IMO this is still an open issue. it just doesnt have a suitable solution yet. closing implies that there isn't interest in fixing this or that it is acceptable that ember can't support loading the same modules that every other loader can.

**Comment by stefanpenner** [comment]
> in any event, IMO this is still an open issue. i

No this isn't a bug, it is working as intended. As per https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md new features go through the RFC process, not issues.

> @stefanpenner would folks accept a documentation fix stating that ember doesn't support AMD

sure

**Comment by jrburke** [comment]
I hit this in my ember app today too. I am wondering if I can fix this in userspace. 

Perhaps I could create an addon that for particular file paths or module IDs it could use some sort of ember build API to get a chance to process the text or AST of the file before it gets combined, the addon could do selective changes to get it to work.

I am still new to the ember build system, so if anyone has pointers to methods or approaches that might be along those lines, feel free to let me know.

**Comment by ef4** [comment]
@jrburke we now have both [an RFC](https://github.com/ember-cli/rfcs/pull/55) and [a PR](https://github.com/ember-cli/ember-cli/pull/5976) that are pretty far along toward solving this.
