### ISSUE TITLE
Regular expression [regex] defined in config converts into empty POJO

### ISSUE THREAD

**Issue by batjaa** [ember-cli/ember-cli#5954]
Here's a repro https://github.com/batjaa/test-config-regex

As the title says, any regular expression [regex] that's defined in the config file gets converted into a POJO and is not possible to use from the application.

**Comment by Turbo87** [comment]
Maybe I'm wrong,  but since the config is serialized into a metatag it is unlikely that this would work. You could save the regex as a string though and convert it later.

**Comment by rwjblue** [comment]
Confirm, the result of evaluating config/environment.js is later JSON.stringified. Only primitive types will be serialized properly.

**Comment by batjaa** [comment]
True. Any plans to support regex? I would assume to be able to use regex
patterns in config file.

**Comment by rwjblue** [comment]
Very unlikely to make config something that is not JSON serialized. If you need to share a regexp from config you will need to do as @Turbo87 mentioned and safe as a string then convert to a regexp in your app code at runtime.

**Comment by batjaa** [comment]
I just had this stupid/crazy but workable idea. What if you override the `RegEx.toJSON()`.
To something like:
```
typeUUID = uuid();
toJSON() = {
  return {
    regex: 'regexAsAString',
    type: typeUUID,
  }
}

JSON.parse = function() {
 // override too
 // use the UUID to check if object is regex type
}
```

**Comment by batjaa** [comment]
Not sure why closed. Because using strings can't resolve the issue
completely. You will need to escape characters but you will need the
special characters to define certain rules, like `^` to say "begins with"
or `$` "ends with".

**Comment by Turbo87** [comment]
what's wrong with escaping characters? as mentioned above the config is JSON serialized and then read into the application. this is simply a requirement at the moment and if you want to use config values that are not natively JSON serializable then you need to find a way to serialize them in another way (e.g. use strings for the regex patterns).

**Comment by batjaa** [comment]
I'm sorry didn't gave full context. What if a config value could be a string or a regex. Like raven.js ignore/whitelist urls is a good example. https://github.com/damiencaselli/ember-cli-sentry/issues/49 Opened a thread over here, too. You can have a look if interested.
I understand that it would be hard to support regex with how we handle config currently. Is it possible to update the docs at least? So people understand that the ENV object gets serialized.

**Comment by Turbo87** [comment]
> I understand that it would be hard to support regex with how we handle config currently. Is it possible to update the docs at least? So people understand that the ENV object gets serialized.

Sure, it would be great if you could open a PR that clarifies the situation.

> What if a config value could be a string or a regex. Like raven.js ignore/whitelist urls is a good example.

I still don't see the problem. Just deserialize the config into proper regular expressions before passing it on to raven.js.

**Comment by rwjblue** [comment]
> Is it possible to update the docs at least? So people understand that the ENV object gets serialized.

The docs should absolutely make it clear that the returned object is serialized.  I would even be happy with some build time assertions when non serializable types (like `Function` or `RegExp`) are included...
