### ISSUE TITLE
ember new creates the folder in the closest parent with a package.json

### ISSUE THREAD

**Issue by kitsunde** [ember-cli/ember-cli#5956]
We have projects like 

```js
src/frontend
src/backend
package.json
```

When I ran `ember new frontend` from **src/** the directory was created one folder up because it happened to have a `package.json` file already.

I found it pretty confusing, but if it's by design then it probably needs to be documented here: https://ember-cli.com/user-guide/#create-a-new-project

**Comment by Turbo87** [comment]
this was actually fixed already by https://github.com/ember-cli/ember-cli/pull/5918, but it's only available in master/canary so far. v2.7.0 will only look for package.json files that include an `ember-cli` dependency.
