### ISSUE TITLE
Use ember-cli-blueprint-test-helpers for blueprint tests

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#5971]
We should try to reuse our efforts in https://github.com/ember-cli/ember-cli-blueprint-test-helpers to test our own blueprints.

**Comment by stefanpenner** [comment]
@Turbo87 yes, although that module should most likely first decouple itself from ember-cli, no reason we need to start a whole ember-cli to run blueprints. A slimmer harness is possible

**Comment by Turbo87** [comment]
> A slimmer harness is possible

would be awesome if you could open an issue for that describing your thoughts on how to slim it down
