### ISSUE TITLE
Unable to run `ember init` after upgrading to 2.6.0

### ISSUE THREAD

**Issue by stevenwu** [ember-cli/ember-cli#5973]
Unable to run `ember init` when upgrading from `2.5.1` to `2.6.0`.

---

Output from ember version --verbose (project directory):
```
The addon `ember-cli-htmlbars` requires an Ember CLI version of 0.1.2 or above, but you are running null.
Error: The addon `ember-cli-htmlbars` requires an Ember CLI version of 0.1.2 or above, but you are running null.
    at Function.deprecatedAssertAbove [as assertAbove] (/Users/steve/work/noovis-ui/node_modules/ember-cli-version-checker/index.js:143:18)
    at CoreObject.module.exports.init (/Users/steve/work/noovis-ui/node_modules/ember-cli-htmlbars/ember-addon-main.js:13:13)
    at CoreObject.superWrapper [as init] (/Users/steve/work/noovis-ui/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/Users/steve/work/noovis-ui/node_modules/core-object/core-object.js:33:38)
    at /Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addons-factory.js:48:21
    at visit (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at CoreObject.extend.initializeAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addons-factory.js:44:11)
    at CoreObject.extend.initializeAddons (/Users/steve/work/noovis-ui/node_modules/ember-cli/lib/models/addon.js:220:38)
    at setupRegistryForEachAddon (/Users/steve/work/noovis-ui/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
```

Output from ember version --verbose (home directory):
```
ember-cli: 2.6.0
http_parser: 2.7.0
node: 6.2.1
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

Tried with node `6.1.0`, had same issue.

**Comment by stefanpenner** [comment]
@stevenwu what version of ember-cli-htmlbars do you have?

**Comment by stefanpenner** [comment]
i suspect you have a version of ember-cli-htmlbars pre 1.0.7, could you confirm?

**Comment by stefanpenner** [comment]
I've been attempting different configurations but have been so far unable to replicate. We will need more information to proceed...

**Comment by nathanhammond** [comment]
@stevenwu Can you paste in your package.json?

**Comment by stevenwu** [comment]
I tried to copy package.json and bower.json into a new 2.6.0 project earlier, but couldn't reproduce the erorr. Now I'm trying with a new 2.5.0 project upgrading to 2.6.0.

**Comment by nathanhammond** [comment]
@stevenwu My hope was that you could post it here for us to review your dependencies. Is that possible?

**Comment by stevenwu** [comment]
@nathanhammond I've reproduced the error https://github.com/stevenwu/ember-cli-issue-5973 .

**Comment by stefanpenner** [comment]
@stevenwu thanks, looking now.

**Comment by stefanpenner** [comment]
@nathanhammond bumping ember-font-awesome to the latest fixed the issue.

**Comment by stefanpenner** [comment]
I can't think of a solution beyond upgrading to the fixed ember-font-awesome. 

The way I found it was via:  `CORE_OBJECT_WARN_DEPRECATED=1 ember s`

which results in:

```
Deprecation: Overriding init without calling this._super is deprecated. Please call this._super.apply(this, arguments) ember-data
    at Function.Addon.lookup (/Users/stefanpenner/tmp/ember-cli-issue-5973/node_modules/ember-cli/lib/models/addon.js:879:27)
Deprecation: Overriding init without calling this._super is deprecated. Please call this._super.apply(this, arguments) ember-cli-dependency-checker
    at Function.Addon.lookup (/Users/stefanpenner/tmp/ember-cli-issue-5973/node_modules/ember-cli/lib/models/addon.js:879:27)
Deprecation: Overriding init without calling this._super is deprecated. Please call this._super.apply(this, arguments) ember-cli-jshint
    at Function.Addon.lookup (/Users/stefanpenner/tmp/ember-cli-issue-5973/node_modules/ember-cli/lib/models/addon.js:879:27)
Deprecation: Overriding init without calling this._super is deprecated. Please call this._super.apply(this, arguments) Ember CLI QUnit
    at Function.Addon.lookup (/Users/stefanpenner/tmp/ember-cli-issue-5973/node_modules/ember-cli/lib/models/addon.js:879:27)
Deprecation: Overriding init without calling this._super is deprecated. Please call this._super() ember-font-awesome
    at Function.Addon.lookup (/Users/stefanpenner/tmp/ember-cli-issue-5973/node_modules/ember-cli/lib/models/addon.js:879:27)
```

**Comment by stefanpenner** [comment]
@nathanhammond we could enable that warning by default?

**Comment by badazz91** [comment]
Had the same problem on my project. 

Bumping ```ember-font-awesome``` to ```2.1.1``` did the trick.

**Comment by stefanpenner** [comment]
@crodriguez1a likely doing that forced NPM to download the latest core-object module, which contained that deprecation? or..

**Comment by celicoo** [comment]
Same issue here.

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-dependency-checker
    at Function.Addon.lookup (/Users/marceloalves/DEV/Garimpo/Application/Application/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` ember-cli-jshint
    at Function.Addon.lookup (/Users/marceloalves/DEV/Garimpo/Application/Application/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` Ember CLI QUnit
    at Function.Addon.lookup (/Users/marceloalves/DEV/Garimpo/Application/Application/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` release
    at /Users/marceloalves/DEV/Garimpo/Application/Application/node_modules/ember-cli/lib/models/project.js:404:38
```

**Comment by stefanpenner** [comment]
Deprecations are enabled by default, if you have issues please follow the deprecations instruction (either updating the addon in question, or fixing the addon in question).

**Comment by Serabe** [comment]
@stefanpenner is there any change to reconsider this until ember-cli@2.7.0 or ember-cli@2.6.2? Currently a fresh installation of ember-cli@2.6.1 shows three deprecation warnings all of them coming from files in `ember-cli/lib/models`
![2016-06-17 at 17 02](https://cloud.githubusercontent.com/assets/36221/16154995/9ff02d78-34ad-11e6-93f6-b33b5072c37f.png)

**Comment by stefanpenner** [comment]
@Serabe unfortunately do to how those add-on are wired up, that is the best stack trace we can give.

**Comment by stefanpenner** [comment]
the stack trace helps identify how the add-on was instantiated (either in ember-cli, or standalone), but the deprecation also clearly states which dependency needs fixed. 

* ember-cli-dependency-checker (pending release)
* ember-cli-quint (already fixed)
* ember-cli-release (I'm assuming release is ember-cli-release)

**Comment by Serabe** [comment]
@stefanpenner: I see the point on [this comment](https://github.com/emberjs/ember.js/issues/13676#issuecomment-226989068). IMHO, a clean installation of ember-cli should not be raising any kind of deprecation. If ember-cli chooses to include an addon by default, I think this issue tracker would need to address those addons not raising any deprecation.

As an example, currently only `ember-cli-release` keep raising such deprecation, but `ember-cli` creates a `package.json` that fixes the version to 0.2.8 (it does not even allow to install 0.2.9 if it existed), while the fix has been released as a beta for `1.0.0`. That means that the user needs to manually change `package.json` to a beta version of an addon as far the user knows is needed to run Ember CLI.

I would suggest releasing the fix in ember-cli-release as 0.2.9, changing [package.json's ember-cli-release version](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L33) to `^0.2.9` and releasing a 2.6.2 version with that fix. This would fix the issue without waiting for 2.7.0 and ease triaging issues, addressing questions on Slack, etc.

Thank you!

**Comment by nathanhammond** [comment]
@Serabe Your proposed solution isn't unreasonable. It's a time and energy thing. [Please see my response on that thread.](https://github.com/emberjs/ember.js/issues/13676#issuecomment-227008372)

**Comment by rwjblue** [comment]
In this case, we enabled the deprecations after 2.6 was already released out of "self defense" (there were a number of issues reported that the deprecation was intended to help with and addon authors had no clue they needed to take action).

I think in the future that we should try to land deprecations "on by default" during the beta period, so that addon authors at least have a chance to fix the underlying issues before final/stable releases.  

I do not think there is much we can do at this point, other than what @Serabe suggested (RE: ember-cli-release@0.2.9 and a ember-cli@2.6.2).
