### ISSUE TITLE
Ember build -prod Fail using Semantic-ui

### ISSUE THREAD

**Issue by joseperales** [ember-cli/ember-cli#5980]
When made a build in ember-cli 2.6.1 using semantic-ui

On OS X El Capitan and Windows 10 I try to build Ember build -prod and produce Error: Broken @import declaration of "theme.css" 
![screen shot 2016-06-12 at 7 37 54 a m](https://cloud.githubusercontent.com/assets/236926/15990957/78fc8fe4-3071-11e6-9510-62541db2894e.png)

**Comment by Turbo87** [comment]
@joseperales could you provide instructions on how to reproduce your issue?

**Comment by joseperales** [comment]
@Turbo87 just making a build using the ember-cli command: ember build -prod and boom Doesn't Flight Cheers. Also I opened the issue in semantic-ui ember https://github.com/Semantic-Org/Semantic-UI-Ember/issues/114. Appear a problem with semantic-ui or broccoli

**Comment by stefanpenner** [comment]
or semantic-ui clean-css maybe, unliekly ember-cli or broccoli but unknown.

Following https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#reporting-a-bug closely, will help us with the information we need to debug. e.g. downloadable reproduction. This helps us unsure we see exactly what you see.

**Comment by stefanpenner** [comment]
Will gladly reopen and investigate if a repo demonstrating a reproduction is provided. :)
