### ISSUE TITLE
Permissions issue on Windows

### ISSUE THREAD

**Issue by NeilAllen** [ember-cli/ember-cli#5983]
The cli blows up when I save a change even with elevated privileges.

![image](https://cloud.githubusercontent.com/assets/13977890/16035510/7a06c3ba-320f-11e6-9ae0-ac110cb19596.png)

**Comment by nathanhammond** [comment]
That appears to be a privilege issue. Did you install any of `node`, `npm`, or other tools as an admin user? I'm not an expert on Windows (and don't have a Windows machine to test with), so I'll need your help to track down what is happening. Can you describe the exact steps you've done to get here? First attempt to fix with my guidance would include uninstalling and reinstalling `node` and removing your npm module cache.

Regardless, this is not corrupting your machine, I've edited your issue title to be more accurate. We're more likely and willing to help if you provide more details and aren't alarmist.

**Comment by NeilAllen** [comment]
Thanks, for having a look...

My windows logon is an admin & windows would require me to elevate privileges to install node.

The steps to reproduce are no more than:
   ember s
   (change and save a source file)
   ember picks up the change and does-what-it does, but fails; tells me permission is denied on dist/assets.
   I try to look in dist/assets with windows explorer & get the dialog as in the OP

I've not changed the permissions on the folder(s) so I'm wondering why you think it's not a corruption.

Anyroadup, how to "...removing your npm module cache" ?

It occurs multiple times a day & requires a reboot so it's, more than, frustrating.

**Comment by stefanpenner** [comment]
@felixrieseberg we may need your 👀  on this one.

**Comment by stefanpenner** [comment]
@NeilAllen thanks for reporting, but we will need you to flesh out the issue further. As per our Contributing.md (the yellow banner you see when opening an issue links to it) we have requested several things: https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#reporting-a-bug.

Providing us with the above requested details, as it will enable us to investigate further.

**Comment by felixrieseberg** [comment]
Hey, happy to check in - obviously, this isn't normal behavior, but I'm not sure that Ember is at fault here. Creating a folder that other users don't even have access to isn't all that easy.

@NeilAllen: I recommend uninstalling and then reinstalling Node, followed by removing your `node_modules`, `tmp`, and `dist` folders inside your projects.

**Comment by NeilAllen** [comment]
Hi!,
   here, I hope, is the info - let me know it's not. In the meantime I'll give the 'windows-helpdesk'-esce re-install a go.

c:\blah\>npm --version
2.14.12

c:\blah\>ember --version
Future versions of Ember CLI will not support v4.3.1. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.3.1
npm: 2.13.4
os: win32 x64

**Comment by Turbo87** [comment]
@NeilAllen it looks like you are using a rather old version of Ember CLI (v1.13.8). I guess your best bet is to update Ember CLI to the most recent release and then see if that fixes your issues.

**Comment by stefanpenner** [comment]
> @NeilAllen it looks like you are using a rather old version of Ember CLI (v1.13.8). I guess your best bet is to update Ember CLI to the most recent release and then see if that fixes your issues.

please do this, if the problem persists could you share a reproduction (isolated from your private app files) that way we can debug it quickly.

**Comment by felixrieseberg** [comment]
The same is true for your npm version.

**Comment by stefanpenner** [comment]
This seems to have gone idle. If the above suggestions are followed and the problem persists please provided a detailed report + ideally a reproduction and we can reopen.
