### ISSUE TITLE
Add flag to determine if addon is installed to devDependencies or dependencies

### ISSUE THREAD

**Issue by GCheung55** [ember-cli/ember-cli#5989]
npm allows the developer to determine whether to save a dependency in package.json under devDependencies or dependencies.

The difference between the two is that dependencies are required to run, while devDependencies are required to develop.

Examples of dependencies required to run: ember-cli, ember-resolver, and ember-core.
Examples of devDependencies required to develop: ember-cli, ember-resolver, ember-core, ember-cli-template-lint, ember-cli-jshint, and ember-cli-qunit.

In an Ember app, a user would have to manually maintain dependencies in package.json when running `ember install <addon>`.

I propose a `--dev` flag to `ember install` to allow developers to decide when the addon is not for development, like `ember-route-action-helper`, which would be used in-app. The flag would be true by default.

A benefit to this is that addons that are truly devDependencies would be excluded when the repo is being built and deployed in a CI environment, thus speeding up the process.

**Comment by stefanpenner** [comment]
Hello, please be sure to read the [CONTRIBUTING.md]https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md() (the big yellow banner you see when opening this issue). It outlines how to request new features [here](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#requesting-a-feature)

**Comment by GCheung55** [comment]
Sorry about that, I was misinformed that this was the right place to request a feature.

I've filed a [ticket in the RFCS](https://github.com/ember-cli/rfcs/issues/56).
