### ISSUE TITLE
`this.import` may have bugs.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#5990]
Not all `app`s are guaranteed to have `.app`: https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L422-L428

We may instead need to snag `.parent`: https://github.com/machty/ember-maybe-import-regenerator/blob/master/index.js#L38-L50

/cc @machty @rwjblue @zackthehuman

**Comment by rwjblue** [comment]
Thanks for recording this issue @nathanhammond.

**Comment by zackthehuman** [comment]
Indeed; this is a problem I have commonly run in to while trying to get the app's options via `this.app.options`, which sometimes bombs. Resolving by walking the parents seems like the most reliable thing to do.

**Comment by Turbo87** [comment]
fixed by #6043
