### ISSUE TITLE
Default addon blueprint doesn't catch node 0.x breakage in CI

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-cli#5998]
A change introduced in #5679 set the default node version for Travis-CI to v4. This is probably fine for apps, but in the case of addons, it's very easy for CI to indicate everything is fine, despite the existence of things incompatible with node 0.10 or 0.12.

Per the Node LTS schedule, we need to provide full support for node 0.10 and 0.12 until December 2016 and April 2017, respectively.
### TODO:
- [ ] Creating a new addon via the default addon blueprint should result in a `.travis.yml` file set up to either fail, or throw warnings when node-0.12-incompatible code is encountered
- [ ] Creating an new app via the default app blueprint should result in tests being run with node 4

**EDIT:** Updated the objectives to leave open the possibility of dealing with this via linting, as opposed to running CI w/ node 0.12

**Comment by Turbo87** [comment]
I'm assuming we can close this now that Node 0.x is EOL... sorry for not the missing discussion. seems like this slipped through 😞
