### ISSUE TITLE
Ember 2.6+ Quick Start Guide instructions reference non-existent application.hbs template

### ISSUE THREAD

**Issue by jtferns** [ember-cli/ember-cli#6006]
The [Create New Application](https://guides.emberjs.com/v2.6.0/getting-started/quick-start/#toc_create-a-new-application) section references manipulating the application template, which is no longer created by default.

I'm guessing this is due to the introduction of the `ember-welcome-page` addon in Ember 2.6+.

---

Output from ember version --verbose:
```
ember-cli: 2.6.2
node: 6.0.0
os: darwin x64
```

**Comment by stefanpenner** [comment]
https://github.com/emberjs/guides is likely the appropriate place for this issue (i know its hard to find where these issues go)
