### ISSUE TITLE
Slow Incremental Builds for Ember App on Linux

### ISSUE THREAD

**Issue by soynog** [ember-cli/ember-cli#6013]
Hi, I'm getting very slow (20-40s) refresh times on my relatively simple Ember app. It seems like a similar issue to #538 but that seems to have been resolved a while back, and was for a much older version. I've tried cleaning out my tmp folder, and that hasn't seemed to have much of an effect. I've also tried going through the tips for trouble-shooting slow builds, with no luck.

Here's an example of typical output from my server:
```
file changed components/trip-details/trip-header/template.hbs
file changed styles/trip-details.scss

Build successful - 32805ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
CachingWriter                                 | 31969ms             

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
CachingWriter (1)                             | 31969ms   
```

Running ```DEBUG=broccoli-caching-writer:* ember s``` is very verbose, but most actions take just a few milliseconds with the exception of:
```
  broccoli-caching-writer:CachingWriter rebuilding cache in 31693ms +32s
```

I'm also getting a "cache eviction" notice--not sure if this is normal or not:
```
  broccoli-caching-writer:SassCompiler  cache eviction due to: 
     - {file, /home/nicolas/wdi/projects/oto-client/tmp/sass_compiler-input_base_path-SbenAwPs.tmp/0/app/styles/trip-details.scss, app/styles/trip-details.scss, 33204, 2445, 1466560640422} 
     - {file, /home/nicolas/wdi/projects/oto-client/tmp/sass_compiler-input_base_path-SbenAwPs.tmp/0/app/styles/trip-details.scss, app/styles/trip-details.scss, 33204, 2421, 1466560624714} +25ms
```

Interestingly, the problem is mostly on rebuilds--when I first start up the server it typically completes in ~7 sec. Typically the first couple rebuilds are also <10 sec, but then it quickly creeps up over 20 sec.

Happy to provide additional info. Any help you could provide would be much appreciated. Thank you!

---

Output from ember version --verbose:
```
ember-cli: 2.5.1
http_parser: 2.5.2
node: 4.4.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: linux x64
```

**Comment by stefanpenner** [comment]
please provide a reproduction, and i'll gladly debug it for you.

**Comment by stefanpenner** [comment]
> file changed components/trip-details/trip-header/template.hbs
> file changed styles/trip-details.scss

do you actually change both a has and a scss file at the exact same time?

**Comment by stefanpenner** [comment]
> broccoli-caching-writer:CachingWriter rebuilding cache in 31693ms +32s

my guess is that you have a very large number of files getting pulled into the build. With a reproduction I can likely identify this. But how many files are in `bower_components/*`

**Comment by stefanpenner** [comment]
is it https://github.com/soynog/oto-client ?

**Comment by stefanpenner** [comment]
if it is, it looks like your favicon add-on is using an old/broken/slow version of broccoli-replace

**Comment by stefanpenner** [comment]
i think the root cause is fixed by https://github.com/davewasmer/broccoli-favicon/pull/6

**Comment by soynog** [comment]
Lots of activity in the small hours last night. Thank you for your quick response! I'll look into the favicon issue, hopefully that should solve it.

Thanks!

**Comment by soynog** [comment]
I uninstalled ember-cli-favicon and now I'm getting 600ms builds. My life just improved dramatically. Amazing, thank you so much!

**Comment by stefanpenner** [comment]
@soynog no problem, I hate to see people have slow builds (there are some scenarios that still blow, but slowly working them out)
