### ISSUE TITLE
Automatically fill repository field

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#6020]
When generating a new `package.json` using `npm init`, the "repository" field automatically gets filled if the destination directory is a git repository and has a remote configured.

However, when runing `ember init` within a repo's directory, the "repository" field currently simply stays empty. Wouldn't it be great if ember-cli did the same thing?

```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by rwjblue** [comment]
Indeed.  We generally like to discuss feature additions in the ember-cli/rfcs repo though, would you mind transferring this over there?

**Comment by leo** [comment]
Done! https://github.com/ember-cli/rfcs/issues/58
