### ISSUE TITLE
Route blueprint with --reset-namespace flag does not generate correct file structure

### ISSUE THREAD

**Issue by tavosansal** [ember-cli/ember-cli#6026]
When trying to generate a route like so: `ember g route parent/child --reset-namespace`, ember-cli is using the default file structure which puts the route and template file for `child` inside the folder for `parent`. This causes child route to not be found when running the application. If I take the files generated for `child` out of their corresponding `parent` folder then everything works as expected. 

I used this tool to check the file structure of my files: http://alexspeller.com/ember-diagonal

User this as input and click on the comments route. If you remove the resetNamespace then the files show as ember-cli is generating them

```
this.route('posts');
this.route('post', {path: '/posts/:post_id'}, function () {
  this.route('new');
  this.route('edit');
  this.route('comments', {
    resetNamespace: true
  }, function() {
    this.route('new');
  });
});
this.route('signup');
```

---

Output from ember version --verbose:

```
ember-cli: 2.6.2
http_parser: 2.5.0
node: 4.2.4
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2e
os: darwin x64
```

**Comment by stefanpenner** [comment]
relevant repo: https://github.com/ember-cli/ember-router-generator

**Comment by tavosansal** [comment]
Moved to: https://github.com/ember-cli/ember-router-generator/issues/25

**Comment by abuiles** [comment]
@tavosansal @stefanpenner following my comment on the router-generator. The issue is not in `router.js` but in the generated blueprints for `route`, `template` and `test`. 


```
ember g route friends/irresponsible --reset-namespace
installing route
  create app/routes/friends/irresponsible.js <----- this is wrong, should have been app/routes/irresponsible.js 
  create app/templates/friends/irresponsible.hbs  <--- so is this
updating router
  add route friends/irresponsible
installing route-test
  create tests/unit/routes/friends/irresponsible-test.js  <--- and  this
````
The output should have been:

```
ember g route friends/irresponsible --reset-namespace
installing route
  create app/routes/irresponsible.js
  create app/templates/irresponsible.hbs
updating router
  add route friends/irresponsible
installing route-test
  create tests/unit/routes/irresponsible-test.js
```

cc @trabus

**Comment by nathanhammond** [comment]
@abuiles What is the behavior for `reset-namespace` inside of `ember-router-generator`? How does it select which segment gets the `resetNamespace` arg? Always the leaf?

**Comment by nathanhammond** [comment]
@tavosansal Thank you for the excellent bug report. 😄 It makes it much easier for us to track down what is going on.

**Comment by nathanhammond** [comment]
[Changes will be made here.](https://github.com/ember-cli/ember-cli-legacy-blueprints/tree/master/blueprints/route) We can track it here as it is a dependency we control.
