### ISSUE TITLE
Port ember-new-output scripts to /dev/

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#6031]
Tracker for me to get this done. The source is https://gist.github.com/nathanhammond/e0a55b4d0328b45b8ef5. It may need some massaging for our release channels.

**Comment by Turbo87** [comment]
> It may need some massaging for our release channels.

the `git clone` needs to be suffixed with `--branch stable`, but it might make sense to use a shell parameter here instead of hardcoding it.
