### ISSUE TITLE
Generating in-repo-addon and destroying leaves traces

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-cli#6037]
### To Reproduce

Run the following

``` sh
ember addon abcd-addon && \  
    cd abcd-addon && \
    ember g in-repo-addon efgh && \
    ember d in-repo-addon efgh
```
#### Expected Result

A clean git state, with no staged changes
#### What I'm seeing instead

The change made to `package.json` in `.ember-addon.paths[]` remains

``` diff
diff --git a/package.json b/package.json
index 8c0607f..a26ff35 100644
--- a/package.json
+++ b/package.json
@@ -46,6 +46,9 @@
     "ember-cli-babel": "^5.1.6"
   },
   "ember-addon": {
-    "configPath": "tests/dummy/config"
+    "configPath": "tests/dummy/config",
+    "paths": [
+      "lib/efgh"
+    ]
   }
-}
+}
\ No newline at end of file

```

---

Output from ember version --verbose:

```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 5.11.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2h
os: darwin x64
```

**Comment by Turbo87** [comment]
@mike-north https://github.com/ember-cli/ember-cli/blob/master/blueprints/in-repo-addon/index.js needs to be adjusted to symmetrically remove the in-repo-addon path when it's removed again

**Comment by apkiernan** [comment]
Hi all,

I was looking into fixing this, and I had a question: following the steps above to reproduce, in addition to a change to `package.json`, the `lib/` directory is remaining with a `.jshintrc` and an empty `efgh` directory. 

Should these also be cleaned up in addition to cleaning `package.json`?

Thanks!

**Comment by nathanhammond** [comment]
@apkiernan As long as they're not being used for other things, yes, those should be removed. If, however there are residual files the directory should not be removed. `.jshintrc` should not be removed unless the entire lib folder is empty as it could apply to things which are not in-repo-addons.

**Comment by apkiernan** [comment]
With #6132 is this all set, or would you still want the folder cleanup looked at?

**Comment by mike-north** [comment]
@apkiernan my thinking is that a clean git state is the "definition of done" here (if you had no changed files, `ember g *` and `ember d *` should leave you with no changed files).

**Comment by Gaurav0** [comment]
Can this be closed if the risk of doing this is too high? I'm seeing this on https://help-wanted.emberjs.com

**Comment by mike-north** [comment]
@Gaurav0 AFAIK nobody has disagreed with this issue being classified as a bug. The fact that initial attempts to fix this bug have not been merged, and that pruning directories correctly is a hard problem should not be grounds for closing it out.
