### ISSUE TITLE
Disable the watcher?

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#6041]
I went through the source and there doesn't seem to be any option to disable the watcher. In fact, the server will throw an error if an unsupported flag is given: https://github.com/ember-cli/ember-cli/blob/master/lib/models/watcher.js#L67-L69

### Why do I want to disable the watcher?

When running `ember fastboot` on a production box one strategy for deploying a new version of your app could be to update a git repo that the app is running from. To minimize downtime it would be best to update the code and do any possible `npm install` before tearing down the server. With the watcher running the server will attempt to reload itself with any repo updates. In the event of missing or out of date deps this can lead to errors.

**Comment by nathanhammond** [comment]
For those of you following along at home I _can't recommend_ running your prod setup this way. Now, with that warning out of the way...

---

@bcardarella I think you can accomplish this with @ebryn's [ember-autoserve](https://github.com/ebryn/ember-autoserve).

---

@bcardarella I'm closing on the assumption that the addon meets your goals. If you actually believe that we should have a way to disable the watcher as a feature of `ember serve` then let's [open an issue to discuss in the RFCs repo](https://github.com/ember-cli/rfcs/issues/new).
