### ISSUE TITLE
fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org taking to long at install

### ISSUE THREAD

**Issue by abel406** [ember-cli/ember-cli#6047]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---
## **This delay ins stopping angular-cli from installing.**

It keeps running and running at this step 

> fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org 

Output from ember version --verbose:
```
[Replace this line with the output.]
```

**Comment by nathanhammond** [comment]
This is not an Ember CLI issue and is likely an issue with npm and your system setup. I'm closing this. If you can provide more information we may be able to help you track down the problem.
