### ISSUE TITLE
tmp directory growing out of control

### ISSUE THREAD

**Issue by kgish** [ember-cli/ember-cli#6053]
The tmp directory is growing out of control with all kinds of stuff and is NOT being cleaned. Sometimes I clean it manually using rm and it takes forever (many minutes) to finish. There must be someway to fix this. I am using ubuntu 14.04 by the way.

```
$ ember version --verbose:
version: 1.13.13
http_parser: 2.5.2
node: 4.4.5
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
npm: 2.14.10
os: linux x64
```

After deleting the `tmp` directory contents (and waiting forever) I rerun the server:
```
$ ember s
version: 1.13.13
Proxying to http://localhost:3000
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 42725ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 20856ms             
Babel                                         | 3754ms              
ConcatWithMaps: Concat: Vendor                | 2842ms              
JSHint app- QUnit                             | 2576ms              
Babel                                         | 2273ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (21)                                    | 32334ms (1539 ms)   
ConcatWithMaps: Concat: Vendor (1)            | 2842ms              
JSHint app- QUnit (1)                         | 2576ms              
```
While this is running the `tmp` dir gets filled with all kinds of stuff, but when I hit ^C to shutdown ember, everything is cleaned up alright.

If on the ohterhand I run the tests:
```
http://localhost:4200/tests?filter=Acceptance%20|%20Pages&hidepassed
```
The `tmp` get filled up with similar contents as above, but upon completion (1 failure), all these files are NOT cleaned up.

Everytime I run these tests, the `tmp` just gets filled up more and more.

Is there something I am doing wrong, or can this be fixed somehow?

**Comment by rwjblue** [comment]
Thank you for steps to reproduce. We will try to replicate your findings and see what we need to do to fix it.

**Comment by Turbo87** [comment]
@kgish is that issue still present with Ember CLI v2.6.x?

**Comment by nathanhammond** [comment]
@Turbo87 makes a good point, looking at the the version string: `1.13.13`. This was definitely an issue in older Ember CLI versions but I believe we've addressed it in the most recent versions. Can please upgrade and confirm?

@kgish I'm going to close this issue as "probably fixed by an Ember CLI upgrade." If you discover that it is not addressed with an Ember CLI upgrade _please feel encouraged to reopen it_ and we'll dive in and see if we can diagnose it.

Thank you for taking the time to report the bug!

**Comment by kgish** [comment]
Indeed, seems to be fixed in later versions, thanks. Time to upgrade ...
