### ISSUE TITLE
Separating JS and CSS Addon Trees?

### ISSUE THREAD

**Issue by tjni** [ember-cli/ember-cli#6054]
Inside lib/broccoli/ember-app.js, the same addon tree is used as the starting point for both the CSS and the JS concat steps:

```javascript
var addonTrees = mergeTrees(this.addonTreesFor('addon'), {
  overwrite: true,
  annotation: 'TreeMerger (addons)'
});

...

return this._cachedAddonTree = [
  this._concatFiles(addonTrees, {
    inputFiles: ['**/*.css'],
    outputFile: '/addons.css',
    allowNone: true,
    annotation: 'Concat: Addon CSS'
  }),

  this._concatFiles(reexportsAndTranspiledAddonTree, {
    inputFiles: ['**/*.js'],
    outputFile: '/addons.js',
    allowNone: true,
    annotation: 'Concat: Addon JS'
  })
];
```

What do folks think about providing separate hooks for compiled JS and compiled CSS in the addon model?

The build I'm working with includes enough JS files so that just filtering the CSS files by extension takes over 200ms, so this could be a performance micro-optimization. I also think that separating JS and CSS trees in general is a good idea.

**Comment by nathanhammond** [comment]
Hey @tjni! Splitting the trees isn't necessarily a bad idea but I suspect you'd just be shifting the cost of that filtering to the creation of the second tree. I doubt that there is such thing as a free lunch in that regard and I'm pretty sure that we'd see effectively zero change in overall time. Do you agree?

This area of the build is something that we'd like to see less hard-coded and more pluggable, but we don't really know how to get there yet and haven't invested time in designing a good solution. We've opened https://github.com/ember-cli/rfcs/issues/39 as a place to collect examples of needs for extensibility. In general, requests like this one (for a feature or a non-trivial change inside of Ember CLI) are better suited being opened on that repository.

I'm going to close this issue as I don't believe that it's actionable at this point. Ways we can move forward:
- You can create a benchmark to test the performance of your proposed approach against the status quo. With a significant change please reopen this issue!
- If there are other goals you have for extensibility with this approach other than just performance you can add those to the RFC issue for tracking.

Also please feel encouraged to stop by #dev-ember-cli on the Ember Community Slack to discuss further!

**Comment by tjni** [comment]
I actually believe we'll see improvement in this case, because the filtering in the code snippet above is only needed because the script and style trees for each addon are merged:

```javascript
treeForAddon: function(tree) {
  this._requireBuildPackages();

  if (!tree) {
    return tree;
  }

  var addonTree = this.compileAddon(tree);
  var stylesTree = this.compileStyles(this._treeFor('addon-styles'));

  return mergeTrees([addonTree, stylesTree].filter(Boolean), {
    annotation: 'Addon#treeForAddon(' + this.name + ')'
  });
},
```

While this can be implemented via an appropriate extension mechanism, this is targeted toward the regular, conventional build process.

I'll see if I can come up with an example demonstrating this in practice, and I'll stop by the Slack channel if I have something promising.

**Comment by nathanhammond** [comment]
@tjni The other thing to note is that `treeForAddon` is frequently a place people hook for functionality and needs to maintain API compatibility. This is going to be a tremendous forcing function on what you're able to accomplish with maintaining two separate trees since the `return` value of this function needs to be maintained. Alternatively any change would need to be inserted as a deprecation and maintain both APIs as possible for the foreseeable future–which would require an RFC. (And is why I immediately in my head went to the extensibility RFC issue because this should be something that it solves.)

I don't say this to discourage you; I'd like to see what you can come up with! 😄
