### ISSUE TITLE
"DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecssary" after generating a new (empty) addon

### ISSUE THREAD

**Issue by frunjik** [ember-cli/ember-cli#6058]
To reproduce:

```
ember addon ember-cli-addon
cd ember-cli-addon
ember version --verbose
```

produces:

DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecssary.
ember-cli: 2.5.0
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
os: win32 x64

Output from ember version --verbose:

```
DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecssary.
ember-cli: 2.5.0
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
os: win32 x64
```

**Comment by Turbo87** [comment]
@frunjik thanks for reporting this! do you see the same deprecation notice with Ember CLI 2.6?

**Comment by frunjik** [comment]
I don't know ...
I'm (still) not totally comfortable with updating ember (cli) ...
Can i just up my version of ember-cli in package.json and run npm update to try ?

**Comment by Turbo87** [comment]
so `ember-cli` includes `ember-try` starting from v2.6.0 and `ember-cli` below v2.6.0 adds `ember-try` to your `package.json` with a version specifier of `^0.2.2`, which means `>= 0.2.2, < 0.3.0`.

`ember-try` introduced the deprecation message you're seeing in v0.2.3, but it seems that it's not checking what `ember-cli` version you're actually running. this deprecation message obviously only makes sense if you're running on `ember-cli` v2.6.0 or above. what needs to be done is add such a check to `ember-try` and then do a bugfix release of that.

/cc @kategengler

**Comment by Turbo87** [comment]
this does not seem to be an issue anymore :)
