### ISSUE TITLE
Could not find module ember-metal/streams/utils 

### ISSUE THREAD

**Issue by PradeepJaiswar** [ember-cli/ember-cli#6063]
Trying to run ember addon for ember engine. "ember s" working proper and app is getting build proper.

On the browser getting blank screen with console  error saying " ember.debug.js:58Uncaught Error: Could not find module ember-metal/streams/utils " 

Got stuck in this. Any advice would help

Using ember canary. Here is my bower.json file 
{
  "name": "ember-engine-addon-demo",
  "dependencies": {
    "ember": "canary",
    "ember-cli-shims": "^0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0"
  }
}

---

Output from ember version --verbose:
```
ember-cli: 2.5.0
http_parser: 2.7.0
node: 6.2.1
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
```
![screenshot](https://cloud.githubusercontent.com/assets/4545996/16795291/17b7d1fc-48fa-11e6-8675-cc5cd6d1864a.png)

**Comment by nathanhammond** [comment]
This is not an Ember CLI bug. One of your addons that you have installed is using private Ember API. If you'd expanded that stack trace I might have been able to tell you which one. 😛 I'm closing this issue but you can still reply with your package.json and that stack trace and somebody will likely be able to identify which addon you're using needs updating.

**Comment by PradeepJaiswar** [comment]
Ohh Sorry for that ! got stuck here.

---
Here is stack track. If you can here 
```
ember.debug.js:58Uncaught Error: Could not find module ember-metal/streams/utilsmissingModule @ ember.debug.js:58internalRequire @ ember.debug.js:80requireModule @ ember.debug.js:44exports.default @ ext-require.js:7(anonymous function) @ mount.js:4Module.exports @ loader.js:122Module.reify @ loader.js:143Module.exports @ loader.js:120Module.reify @ loader.js:143Module.exports @ loader.js:120requireModule @ loader.js:21(anonymous function) @ index.js:18exports.default @ index.js:15(anonymous function) @ app.js:14Module.exports @ loader.js:122requireModule @ loader.js:21(anonymous function) @ app-boot.js:4
```


---

My Package.json file looks like this
```
{
  "name": "ember-engine-addon-demo",
  "version": "0.0.0",
  "description": "The default blueprint for ember-cli addons.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember try:testall"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.5",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.5.0",
    "ember-disable-prototype-extensions": "^1.1.0",
    "ember-engines": "0.2.7",
    "ember-export-application-global": "^1.0.5",
    "ember-i18n": "4.2.2",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-try": "^0.2.2",
    "loader.js": "^4.0.1"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^5.1.6",
    "ember-cli-htmlbars": "^1.0.5"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}

```

**Comment by stefanpenner** [comment]
@PradeepJaiswar  we will need a reproduction to debug this. Please provide a slimmed down ember app (Without sharing any company secrets etc) or share an app the demonstrates this problem privately.

**Comment by nathanhammond** [comment]
You're using an older version of Ember CLI in that application. Try re-initing and upgrading all of your dependencies and I bet this will magically go away.

**Comment by PradeepJaiswar** [comment]
@stefanpenner Sorry bro forgot to post my github repo link. Here it is https://github.com/PradeepJaiswar/ember-engine-addon-demo. 

It used to work at time i initially created it for prototyping. Now my company need to be implemented in real project. 

@nathanhammond  will do that right now.

Thanks for your replies guys, appreciate it

**Comment by PradeepJaiswar** [comment]
@nathanhammond it worked :)

**Comment by stefanpenner** [comment]
> @stefanpenner Sorry bro forgot to post my github repo link. Here it is https://github.com/PradeepJaiswar/ember-engine-addon-demo.

awesome thanks!

**Comment by jusfeel** [comment]
I got this error after upgrade. Running ember init couple of times. How can I find which add-on causes this? stack track has nothing useful
```
Uncaught Error
: Could not find module ember-metal/streams/stream ember.debug.js
:58missingModule ember.debug.js
:58internalRequire ember.debug.js
:80requireModule ember.debug.js
:44(anonymous function) stream.js
:11Module.exports loader.js
:123Module.reify loader.js
:144Module.exports loader.js
:121Module.reify loader.js
:144Module.exports loader.js
:121requireModule loader.js
:23(anonymous function) index.js
:18exports.default index.js
:15(anonymous function) app.js
:13Module.exports loader.js
:123requireModule loader.js
:23(anonymous function)
```

**Comment by nathanhammond** [comment]
@jusfeel These are mostly all fixed at this point. `rm -rf node_modules && npm install` will likely cover you.

If not stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community!

**Comment by rupsk1607** [comment]
Im getting the same bug.
Trying to run ember addon for ember engine. "ember s" working proper and app is getting build proper.

On the browser getting blank screen with console error:

`loader.js:10 Uncaught Error: Could not find module ember-metal/computed
    at missingModule (loader.js:10)
    at internalRequire (loader.js:32)
    at Object.requireModule [as require] (loader.js:82)
    at Module.callback (utils.js:145)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
missingModule @ loader.js:10
internalRequire @ loader.js:32
requireModule @ loader.js:82
(anonymous) @ utils.js:145
Module.exports @ loader.js:106
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
requireModule @ loader.js:27
(anonymous) @ index.js:20
exports.default @ index.js:17
(anonymous) @ app.js:13
Module.exports @ loader.js:106
requireModule @ loader.js:27
(anonymous) @ app-boot.js:2
`
Output from ember version --verbose:
`

ember-cli: 2.18.2
--
http_parser: 2.7.1
node: 8.10.0
v8: 6.2.414.50
uv: 1.18.0
zlib: 1.2.11
ares: 1.14.0
modules: 57
nghttp2: 1.30.0
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
os: linux x64

`
Got stuck in this. Any advice would help

**Comment by rupsk1607** [comment]
In a package.json file, I have removed vector sign
    "ember-data-contentful": "^0.2.0",
It works magically.
