### ISSUE TITLE
Controller property empty, despite if helper.

### ISSUE THREAD

**Issue by michielboekhoff** [ember-cli/ember-cli#6088]
Hello everyone, 

Currently I am working on an application with Ember.js and ember-simple-auth. In my login.js controller, I handle an error in the authentication by setting an attribute `errorMessage` like so:

```
this.set('errorMessage', 'Error: incorrect email/password combination.');
```

This is then used in my template login.hbs using an #if helper:

```
{{#if errorMessage}}
   <!-- Uncomment this to make it work: {{errorMessage}} -->
   <p class="error_login">
     {{errorMesssage}}
    </p>
{{/if}}
```

Without the first `{{errorMessage}}` the `{{errorMessage}}` within the `<p>` tags does not work. Alternatively trying `{{log errorMessage}}` simply outputs `undefined`. Any idea what might be going wrong here? If a demo application is desired, I can set up a Github repository.

---

Output from ember version --verbose:
```
ember-cli: 2.6.3
http_parser: 2.5.0
node: 3.3.1
v8: 4.4.63.30
uv: 1.7.4
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 45
openssl: 1.0.2d
os: linux x64
```

**Comment by nathanhammond** [comment]
Hey @michielboekhoff! This has nothing to do with Ember CLI if there is something wrong here it would be an Ember or SimpleAuth issue. I recommend you stop by the [Ember Community](http://emberjs.com/community/) slack in the #help channel to try and diagnose what's going on.

Closing this issue, hoping that you get it sorted out via Slack!

**Comment by nathanhammond** [comment]
Also, having a reduced demo repository is always a good idea. It'll make it super-easy for somebody to help check out your issue.

**Comment by michielboekhoff** [comment]
@nathanhammond Thank you. It was late and I had both ember-cli and ember.js open, and I picked the wrong one. Thank you!
