### ISSUE TITLE
xfwd option addition breaks --proxy

### ISSUE THREAD

**Issue by typeoneerror** [ember-cli/ember-cli#6089]
I recently went back to an ember-cli 2.5.1 project and proxying to my local dev server was no longer working (I am proxying to "subdomain.site.dev:3000" instead of default "localhost:3000".

If I poke into the proxy-server and change `xfwd` to `false` it fixes my issue. It looks like a [recent commit adds](https://github.com/ember-cli/ember-cli/commit/b971463cfa5e179b0f241826c28bd96b95a8c482) the ability to configure that. Is this possible to get ported back to 2.4.x+ since the xfwd change was introduced then [here](https://github.com/ember-cli/ember-cli/commit/4fc7ce26ef17881618420e0852a9bdfcaa53a4ce)?

Output from ember version --verbose:
```
ember-cli: 2.5.1
http_parser: 2.5.2
node: 4.3.1
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
os: darwin x64
```

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/5986

**Comment by typeoneerror** [comment]
@stefanpenner yeah, saw that, that's great. should I just create my own proxy-server with `ember g proxy-server` until I'm ready for 2.8? I can't upgrade to master at the moment.

**Comment by stefanpenner** [comment]
@typeoneerror yup that should be a good interim solution.
