### ISSUE TITLE
How to compile public es6 sources

### ISSUE THREAD

**Issue by chyxion** [ember-cli/ember-cli#6091]
I have a JavaScript source file in folder public/assets/js/app-preview.js, it uses es6 syntax, the app works on debug mode, but when I try to build a production package, it failed because of es6 syntax error.
My question is how could I compile public es6 JavaScript by ember-cli, thanks for reply.

**Comment by stefanpenner** [comment]
as per the [contributing guidelines](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md) (the yellow banner displayed above the issue form links to this) questions are to be directed to stackoverflow or discourse.
