### ISSUE TITLE
Should likely change `merge` to `assign`

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#6093]
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/start-app.js#L8-L9

**Comment by mike-north** [comment]
I think we ended up flip-flopping on this at some point in the past. Probably worth reviewing the conversation about deprecating merge in favor of assign.

See: https://github.com/ember-cli/ember-cli/pull/5803

**Comment by stefanpenner** [comment]
> To be clear, i

@mike-north I'm in pins and needles waiting for the rest of this sentence

**Comment by nathanhammond** [comment]
Hokay, I'm closing this as we've un-deprecated `merge` and this can cause trouble. Seems like a 3.0 time period change.
