### ISSUE TITLE
ember delete leaves folder artifacts when using pods

### ISSUE THREAD

**Issue by jesseditson** [ember-cli/ember-cli#6101]
This is a small nitpick, but I'd like the `ember delete` command to rmdir the folders created by `ember generate` when removing a path that is now obsolete.

Example, when `usePods` is true:
```
ember g model foo
ember d model foo
ls -l app | grep foo # there is an empty foo directory
ls -l tests/unit | grep foo # there is an empty foo directory
```

**Comment by nathanhammond** [comment]
Hey @jesseditson!

We're moving toward a future [module unification](https://github.com/emberjs/rfcs/pull/143) story and aren't investing a ton of energy into the pods portion of Ember CLI. As this is a benign issue that will change in a forthcoming release it's below the radar of something we're going to invest our energy in. However, if you're interested in opening a PR I would be glad to review it and land it. If you have that time energy and bandwidth, maybe you'd also be interested in helping us move toward the world proposed in the module unification RFC!

I'm closing this issue, but if you want to open a PR to address this you're probably looking to open the PR against a different repository: https://github.com/ember-cli/ember-cli-legacy-blueprints/

Thanks for taking the time to reach out and I'm looking forward to chatting about blueprints for the module unification with you. 😜

**Comment by jesseditson** [comment]
Fantastic, I'll read up on the RFC! Thanks for pointing me in the right direction!
