### ISSUE TITLE
Cannot install Ember CLI v2.7.0

### ISSUE THREAD

**Issue by hckhanh** [ember-cli/ember-cli#6108]
I cannot install Ember CLI v2.7 by following quick start on [emberjs.com](https://guides.emberjs.com/v2.7.0/getting-started/quick-start/).

```bash
npm install -g ember-cli@2.7
```

**Comment by twokul** [comment]
@hckhanh Ember CLI 2.7.0 release is going out today, stay tuned.

**Comment by twokul** [comment]
Ember CLI 2.7.0 was released https://github.com/ember-cli/ember-cli/releases/tag/v2.7.0
