### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'myQueryParam' in undefined

### ISSUE THREAD

**Issue by chriscareycode** [ember-cli/ember-cli#6122]
I had been running EmberJS 2.7.0 with EmberCLI 2.5.0 for a couple weeks without issue. Upgraded to Ember CLI 2.7.0 today and now on about half of my routes which use queryParams, I see the error in the console: 

Uncaught TypeError: Cannot use 'in' operator to search for 'myQueryParam' in undefined

Where queryParam: ['myQueryParam']

I tried recreating in a new Ember app with no luck yet. Will keep trying.

---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: darwin x64
```

**Comment by stefanpenner** [comment]
ember-cli wouldn't directly affect this. Most likely some dependency changed. If you are quite sure it is ember-cli, then as per the contributing.md issues section https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#issues please share a reproduction.

**Comment by nathanhammond** [comment]
Hey @chriscareycode! This is almost guaranteed to be the result of running a new `npm install` in your application and not actually an Ember CLI bug. You've probably picked up a new dependency which conflicts with your current setup.

I'm closing this issue as likely not an Ember CLI bug but _please feel encouraged to reopen it_ if upon further investigation on your side you discover that it may in fact be a bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#help](https://embercommunity.slack.com/messages/help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community!

**Comment by chriscareycode** [comment]
My apologies for the bad bug report. Issue seems to be with EmberJS and not EmberCLI at all. Thank you for your help. https://github.com/emberjs/ember.js/issues/14010
