### ISSUE TITLE
`validateAssetPath` should not throw error

### ISSUE THREAD

**Issue by luxferresum** [ember-cli/ember-cli#6172]
Hello

It seems like the feature was added to print the File sizes of the assets in a recent update.
We use an internal addin to postprocess the output in the `postBuild` hook to bundle everything into a single file for deployment. We do this in production builds only.

This change now makes ember throwing errors, which is a bit ugly.

Is there a reason that ember-cli throws the error and not just ignores it? Its not really an error to have no assets at that point.

**Comment by Turbo87** [comment]
@luxferresum can you be a bit more specific when and why the function started throwing errors? how can we reproduce it?

**Comment by luxferresum** [comment]
I'm talking about [this](https://github.com/ember-cli/ember-cli/blob/master/lib/models/asset-size-printer.js#L72) message.

To reproduce you just need a simple postBuild hook like this:

    postBuild(options) {
      // in reality here I would read all files and process them for deployment
      rimraf.sync(options.directory+'**/*');
      fs.writeFileSync(path.join(options.directory, 'deployfile.dat'), 'dummy file, in reality it includes all other files combined and packed ready for deployment');
    }

There are some usecases where the default folder structure can not be used, because of compatibility to legacy properitary software. So I really think this shouldnt be an error.

**Comment by Turbo87** [comment]
@kiwiupover any comments on this?
