### ISSUE TITLE
New "rootURL" option is incompatible with Cordova

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-cli#6178]
Before the `rootURL` option was introduced (#5792), it was possible to create compiled build products that could be deployed to any base URL. Unfortunately, the `rootURL` option ties the build output to a specific base path by resolving resources absolutely, which makes it incompatible with apps that rely on this specific deploy mechanism.

This failure can be demonstrated by directly opening the `dist/index.html` of a simple ember app in a browser, using its `file:` URL. This worked in 2.6 (when `locationType='hash'`), but fails in 2.7 since it tries to locate `vendor.js` etc. at `file:///vendor.js`.

Console output for freshly create app compiled using `ember build`:
```
[Error] Failed to load resource: The requested URL was not found on this server. (vendor.css, line 0)
[Error] Failed to load resource: The requested URL was not found on this server. (new.css, line 0)
[Error] Failed to load resource: The requested URL was not found on this server. (vendor.js, line 0)
[Error] Failed to load resource: The requested URL was not found on this server. (new.js, line 0)
```

I would like to note that eg. Cordova relies on rendering from a `file:` URL, and that the actual absolute path is not static. One example `file:///Users/gil/Library/Developer/CoreSimulator/Devices/924FAEC4-0F05-43BE-8939-ED00118627AF/data/Containers/Bundle/Application/38FE7E97-3198-4E04-B78A-17BE5E4C5090/MyApp.app/www/index.html`

---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.7
v8: 4.5.103.36
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: darwin x64
```

**Comment by rwjblue** [comment]
If all you need/want is for things to be referenced relative to the `index.html`, you do not need to use `{{rootURL}}` in your `index.html` at all.

Another option is to set `rootURL` in `config/environment.js` ([around here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js#L7)) to `''` which would mean the generated asset paths in `index.html` after `{{rootURL}}` is processed would be something like `src="assets/foo.js"` and `src="assets/vendor.js"` both of which are now relative.

Does this address your concern? If not, what have I miss understood?

**Comment by kanongil** [comment]
The first option is not ideal, and I would have to remember not to include `{{rootURL}}` each time I do `ember-cli init` on updates. It is already suggested by `ember-cordova` as an extra install step.

The second option would be preferred but doesn't actually work, as the rootURL seems to be sanitized to `'/'`.

**Comment by rwjblue** [comment]
> The first option is not ideal, and I would have to remember not to include {{rootURL}} each time I do ember-cli init on updates.

In either case you have to make sure to not override your customizations when running `ember init`.

> The second option would be preferred but doesn't actually work, as the rootURL seems to be sanitized to '/'.

I guess this makes sense (we are ensuring that we have a valid value that ends with a `/`), but we may need to consider allowing `''`.

@Turbo87 / @nathanhammond - Thoughts?

**Comment by kanongil** [comment]
>>The first option is not ideal, and I would have to remember not to include {{rootURL}} each time I do ember-cli init on updates.

>In either case you have to make sure to not override your customizations when running ember init.

True, but the fewer customizations the better.

A more compelling argument, is that we would actually like the `rootURL` functionality for web deployments off the same codebase, which is not compatible with removing `{{rootURL}}` from index.html.

**Comment by rwjblue** [comment]
>A more compelling argument, is that we would actually like the rootURL functionality for web deployments off the same codebase, which is not compatible with removing {{rootURL}} from index.html.

Yep, totally makes sense.

**Comment by Turbo87** [comment]
@kanongil I like the idea of passing am empty string. Could you check if that would break any of the other use cases for the rootURL?

**Comment by rwjblue** [comment]
Right now, we use `rootURL` for appending in `index.html` and deciding where to serve assets.

I suspect that we need to change [this line](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1764) to avoid using `cleanBaseURL`, and since the serving related code will still do this it should continue to assume `/` is the right location to serve from while running `ember serve`.

**Comment by nathanhammond** [comment]
Restating for understanding.

With [`cleanBaseURL`](https://github.com/ember-cli/clean-base-url/blob/master/index.js) it means that you would have to specify the protocol as part of the `rootURL`. You're saying that, at build time, you don't know what that full path will be. You were previously relying on the full relative handling of URLs generated in `index.html` and an unspecified `baseURL` to do the right thing when using `locationType: hash`. That combination is no longer obviously possible to achieve through default mechanisms.

@kanongil I suspect you should be able to set `rootURL` to `false` in your config and get the behavior you're looking for in the build output as long as you don't need `--serve` support for it. Flow:

- https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1764
- https://github.com/ember-cli/clean-base-url/blob/master/index.js#L6-L7

@rwjblue @Turbo87 by default [we make rootURL `/`](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js#L7). That has probably made it likely that nobody is relying upon `'' == '/'` behavior.

Options to support this scenario (`locationType: hash` && non-deterministic `file:///` URL):
1. We make `''` (empty string) a valid `rootURL`.
2. We document and rely on the existing behavior of an unset or explicitly non-string value set on `rootURL`.
3. We tell people to remove `{{rootURL}}` from `index.html`.
4. Any addon that needs this patches over the `configReplace` function.

I'm in favor of Option 1 and don't suspect it will introduce any regressions. Option 2 still doesn't address server behavior which we would need to address. Option 3 seems like a lot of explaining. Option 4 is clearly a non-starter.

@kanongil Please open a PR to modify the behavior in these places to support an empty string:
- https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1764
- https://github.com/ember-cli/ember-cli/blob/2bce175ce188ae0f47a55fa23d6affe2d768ddfb/lib/tasks/server/middleware/serve-files/index.js#L28
- https://github.com/ember-cli/ember-cli/blob/da4749d3b27a2ce7c529de0d07c0ac3e702e7d47/lib/tasks/server/middleware/history-support/index.js#L43
- https://github.com/ember-cli/ember-cli/blob/2bce175ce188ae0f47a55fa23d6affe2d768ddfb/lib/tasks/server/middleware/tests-server/index.js#L26
- https://github.com/ember-cli/ember-cli/blob/d8ba7dbaf77df0e7fe2daf1d153a1a5a60620143/lib/tasks/server/express-server.js#L147

**Comment by Turbo87** [comment]
for completeness: 

Option 5: Introduce a `emptyRootURL` flag or something like that

**Comment by kanongil** [comment]
If an empty string is unlikely to cause issues, it it definitely the way to go.

I tried `rootURL = false`, which seems to work but is less obvious.

I will look into creating a PR.
