### ISSUE TITLE
Deprecation warnings should output more details as to what library/package is the cause 

### ISSUE THREAD

**Issue by RyanNerd** [ember-cli/ember-cli#6190]
Enhancement request:

When starting `ember s` deprecation notices are listed. But there isn't much information as to what module is causing the warning. For example:

DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead

There is no indicator as to what component/addon/library is using `silent.js`. I `greped` my directory and you wouldn't believe how many instances of the word "silent" there are. So I am still digging though this archaeological mess of JS files trying to figure out where the problem is.

**Comment by nathanhammond** [comment]
@RyanNerd Unfortunately that deprecation is coming from something that is (by rule) out of date. I'm not sure if we have a useful reference to the calling object to provide a better error message.

@stefanpenner Can you confirm/deny if we can do better with the `silent-error` deprecation warning?

**Comment by rwjblue** [comment]
@nathanhammond - We could include a stack [here](https://github.com/ember-cli/ember-cli/blob/master/lib/errors/silent.js#L8).

**Comment by stefanpenner** [comment]
@rwjblue we could include the entire stack, or maybe we could try only the previews 2 frames or something?

**Comment by nathanhammond** [comment]
@RyanNerd Would you be willing to open a PR to add the stack trace to the file that @rwjblue pointed to?

**Comment by RyanNerd** [comment]
@nathanhammond Things got busy for me. I will create a PR on Saturday. Thanks for your attention to this enhancement request.

**Comment by RyanNerd** [comment]
Just as an aside:

The module throwing the deprecation issue for me is: ember-deploy-s3-index

This is not an easy fix:
The NPM repo for this package indicates a [version of 0.4.0](https://www.npmjs.com/package/ember-deploy-s3-index) . 
However the github [version is 0.5.0](https://github.com/Kerry350/ember-deploy-s3-index/releases/tag/v0.5.0).

Attempting to set the version in package.json to 0.5.0 makes NPM really angry because it is convinced the latest version is 0.4.0.

**Comment by nathanhammond** [comment]
@RyanNerd That just means that the author didn't `npm publish`. Ping them directly!
