### ISSUE TITLE
livereload suggestion: filter on post-build changed files to determine whether to livereload

### ISSUE THREAD

**Issue by bantic** [ember-cli/ember-cli#6192]
(If this would be better as an RFC I'd be happy to close the issue and write it up as an RFC)

I have a use case where I'm using an addon to generate an amp-index.html HTML file (for AMP) as part of the `ember build` process, and am running into the small problem that ember-cli includes this amp-index.html in its list of changed files that gets sent to the livereload client. This HTML file gets rebuilt based on the css (among other things), so the livereload client is notified that, e.g. both "app.css" and "amp-index.html" are changed whenever css-only changes are made. As a result, the "hot css reloading" feature of ember-cli/livereload doesn't work properly because livereload gets a changeset that includes non-css files which causes it to reload the entire page rather than attempting to hot-reload the CSS.

In a larger sense, it seems likely that there might be some other use cases where there are build artifacts from the ember build process that are not web-targeted (for example, something like ember-fastboot's package.json manifest) and that should not trigger livereload in the browser.

Having the ability to *filter out* files from the list of changed files that ember-cli sends to livereload seems useful. If the exclusion filter patterns exclude all files then livereload would not be triggered. The livereload code already [filters out directories, removed files and sourcemaps](https://github.com/ember-cli/ember-cli/blob/93d2994817dc46cddda9eaf952ce48c6047f5054/lib/tasks/server/livereload-server.js#L146-L149) from the list of files it sends to livereload.

Also somewhat related is #6191, which points out an issue/inconsistency in the way the current `shouldTriggerReload` method uses source files (before the build happens) to determine whether to notify livereload.

There is also discussion in the original PR in which hot-css-reloading landed about the [reliability of using FS events sources to determine livereload](https://github.com/ember-cli/ember-cli/pull/5165#issuecomment-160251139), and [mentioning that changed files can be missed since broccoli-sane-watcher only emits the first file that changed](https://github.com/ember-cli/ember-cli/pull/5165#issuecomment-160506062).

**Comment by stefanpenner** [comment]
So to be sure I understand, `amp-index.html` legitimately gets re-built on most builds, which taints the live-reload list?

If so, yes being able to blacklist seems like a good idea. The open questions are, how to implement, what is the API, how do we document it etc.etc. For that (as your mentioned) an RFC would be best. Don't hesitate to include a PR to ember-cli alongside your RFC (as that may help move things along)

**Comment by bantic** [comment]
👍 Great, I'll take a stab at an RFC later this week.

**Comment by stefanpenner** [comment]
> 👍 Great, I'll take a stab at an RFC later this week.
>  ❤️ 1

@bantic any luck?

**Comment by bantic** [comment]
Argh, got completely sidetracked in Aug, but I absolutely will this week.

**Comment by bantic** [comment]
ok, sorry for the long delay. Added as ember-cli rfc 71: https://github.com/ember-cli/rfcs/pull/71
