### ISSUE TITLE
Ember builds failing with default VIM configuration

### ISSUE THREAD

**Issue by Ikariusrb** [ember-cli/ember-cli#6201]
I was firing up my first ember project, and started running into build errors while running "ember serve"  which looked like this:
`EEXIST: file already exists, symlink '/home/myuser/devel/myproject/app/templates/distributors/.edit.hbs.swp' -> '/home/myuser/devel/myproject/tmp/broccoli_merge_trees-output_path-dP7TSmNs.tmpjmyproject/templates/distributors/.edit.hbs.swp'`

After digging around and finding other bugs which resembled this, but looked to be long resolved, I finally realized that ember's automatic builds were choking on vim's recovery files.  I solved the problems by adding the following to my .vimrc: 

```
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
```

After creating the three directories in question, vim's recovery files stopped breaking the ember builds.  Apparently grayhairs like me aren't the most common ember developers?  I suspect this ought to either be documented (if it is, my apologies for missing it), or perhaps add some handling to notice that these are recovery files and ignore them.

**Comment by stefanpenner** [comment]
can you also provide a stacktrace

**Comment by stefanpenner** [comment]
I was under the impression we already documented this https://ember-cli.com/user-guide/#editors but it appears we have not. As a vim user myself, I did notice this early and obviously changed my config to address. I believe there was a reason we didn't fix this, but I don't recall exactly what that might be....

Anyways, if you have a few moments, do you mind submitting a docfix to https://github.com/ember-cli/ember-cli.github.io/edit/master/_posts/2013-04-02-editors.md You should be able to edit right from the browser. This will help future travelers :) If you don't have time, no worries we will get to it sometime.

**Comment by locks** [comment]
This is currently documented in https://cli.emberjs.com/release/appendix/dev-tools/ :)
