### ISSUE TITLE
Proxying a subdomain does not work anymore

### ISSUE THREAD

**Issue by juggy** [ember-cli/ember-cli#6202]
My backend runs at `http://demo.local.host:3000` (which is a loop back defiened in `/etc/hotsts`) as the application is relying on subdomains for the accounts/tenants.

`ember server --proxy http://demo.local.host:3000`

I recently tried to upgrade from 1.13.15 to 2.4.3 and the proxying feature mysteriously stopped working. I tracked it down to this commit https://github.com/ember-cli/ember-cli/commit/4fc7ce26ef17881618420e0852a9bdfcaa53a4ce .

Now I understand this commits solves some problem, but it introduced another one. What would be the best solution to solve both?

Thanks,
Julien.

**Comment by nathanhammond** [comment]
@juggy We're not going to try supporting an older version of Ember CLI; we'll need you to try and update to the latest version of Ember CLI. Based upon conversation in Slack between you and @Turbo87 I _believe_ that you've heard that we think this is fixed on the master branch?

Can you incrementally upgrade to the last release before the one that includes that change and then try to jump to the master version (this will make that last migration less painful).

Here is the full set of blueprint changes we made during that time period:
https://github.com/ember-cli/ember-new-output/compare/v1.13.15...v2.8.0-beta.2

I'm closing this for now but still paying attention to this thread. Let me know if you're successful!
