### ISSUE TITLE
Files in "public/" getting served case-insensitively 

### ISSUE THREAD

**Issue by schickm** [ember-cli/ember-cli#6209]
I noticed that anything in public/ will get served regardless of if the requested filename has the proper case.  For example, given a file stored at `public/SomeImage.png`, I can have the following template code:

```
<h1>This image should load</h1>

<img src="/SomeImage.png" />

<h1>This image should NOT load</h1>

<img src="/SOMEIMAGE.png" />
```

Both images will be served.

It's my understanding that [urls should be case sensitive](https://www.w3.org/TR/WD-html40-970708/htmlweb.html), but I'm sure there are people that disagree. 

I only noticed this issue because I had assets that loaded while running the ember-cli server, but upon deploying to amazon S3, I suddenly was getting 404s for them.

I think it would be the least surprising to have the development server be case sensitive so that people aren't caught off guard when they deploy to a server that is.

You'll find an example ember app demonstrating the behavior here:

https://github.com/schickm/ember-case-insensitive-file-serving-example

...and lastly - thanks for all the great work everyone!

---

Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: darwin x64
```

**Comment by Turbo87** [comment]
@schickm are you working on a case-insensitive file system?

**Comment by schickm** [comment]
:facepalm: ...  I'm definitely working on a case-insensitive file system.  Closing this ticket, sorry to bug you all.
