### ISSUE TITLE
Ember serve: "unable to resolve root" error 

### ISSUE THREAD

**Issue by alidcastano** [ember-cli/ember-cli#6213]
I just started using ember, following the quick start instructions. However, I can't get Ember to correctly watch for changes. 

Whenever I run `ember serve` I get the following error, repeated several times:

```
unable to resolve root /Users/acastano/Sites/Projects/studbits: failed to opendir(/Users/acastano/Sites/Projects/studbits): No such file or directory
Error: unable to resolve root /Users/acastano/Sites/Projects/studbits: failed to opendir(/Users/acastano/Sites/Projects/studbits): No such file or directory
    at BunserBuf.<anonymous> (/Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:96:13)
    at BunserBuf.emit (events.js:188:7)
    at BunserBuf.process (/Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
    at /Users/acastano/Sites/projects/studbits/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Output from ember version --verbose:
```
ember-cli: 2.7.0
node: 6.4.0
os: darwin x64
```

I had posted about this problem in [ a previous issue](https://github.com/ember-cli/ember-cli/issues/2674#issuecomment-242464908).

I tried to uninstall and reinstall watchman. Didn't work. Currently, I have to restart the server every time I want to see any changes. And I'm not sure what I can do on my part to resolve this problem.

**Comment by alidcastano** [comment]
Also, incase it helps, `watchman watch-list` yields: 
```
{
    "version": "4.6.0",
    "roots": []
}
```

**Comment by nathanhammond** [comment]
@alidcastano does everything work without Watchman installed? Are you on a case sensitive file system? In your pasted stack you have both of these:

- `/Users/acastano/Sites/Projects/studbits`
- `/Users/acastano/Sites/projects/studbits`

**Comment by alidcastano** [comment]
Without watchman there are no errors. But the site still does not automatically update; l have to manually restart the server to see changes.

I don't think I'm on a case sensitive file system. I entered the directory in all capitalized format, still same problem.

**Comment by nathanhammond** [comment]
@alidcastano Disk Utility, select your disk, Command-I.

![screen shot 2016-08-28 at 12 30 58 am](https://cloud.githubusercontent.com/assets/20542/18032333/b896ff3c-6cb6-11e6-96e1-ae5586c65951.png)

Things to do:
- Reboot.
- Disable file watching of the tmp directory in your text editor.

This seems to very clearly be just your machine so I'm closing this issue as it's unlikely we can do too much to help you.

After these troubleshooting steps if things still aren't working stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and ask there; maybe somebody else will have encountered this.

If upon further investigation on your side you discover that it may in fact be a bug reopen this. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Comment by alidcastano** [comment]
Not sure why but renaming the directory got it to work. Thanks for the help.

**Comment by JennieJi** [comment]
This happened to me as well.
I'm using sublime 3 in windows, and in the end, not adding tmp folder into sublime project works for me.
