### ISSUE TITLE
ember new segfaults

### ISSUE THREAD

**Issue by phyrog** [ember-cli/ember-cli#6215]
Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.7.1
node: 6.5.0
v8: 5.1.281.81
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
```

Running `ember new foobar` segfaults while installing npm packages. Last lines of output:
```
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Successfully initialized git.
⠴ Installing packages for tooling via npm[1]    3459 segmentation fault (core dumped)  ember new foobar
```

Manually running `npm install` and `bower install` works (although it seemed to hang one time while extracting `loader.js`).

**Comment by nathanhammond** [comment]
@phyrog Congratulations! You're the first person to report this issue. Unfortunately, that likely means that it's specific to your machine.

I'm assuming that it fails consistently? Can you try to install npm at version 2.15.5 globally (the version that Ember CLI is using to handle the install) and see if that also segfaults on your machine?

**Comment by phyrog** [comment]
Also segfaults with 2.15.5. This time it also segfaults when manually running `npm install`.

**Comment by nathanhammond** [comment]
It doesn't sound like this is going to be an Ember CLI issue so I'm going to close this as it's unlikely actionable on our part. However I'm still interested in what you discover, so keep us up-to-date–being closed doesn't mean that we're ignoring the thread. 😄

**Comment by phyrog** [comment]
Well I'm probably not going into it much more, since manually installing works with npm 3.x. Though you might want to check your CI for the new Node version (as far as I can see you don't build with 6.5 yet), maybe you'll encounter it then too.

**Comment by kellyselden** [comment]
I just tried with node 6.5.0. `ember new` and `ember serve` worked fine.

**Comment by phyrog** [comment]
Can confirm that the bug happens on another computer of mine. Both are running Arch Linux, so it might just be a problem with the Node build there.
