### ISSUE TITLE
Erro: Add-ons which contain sub-packages must have all sub-packages signed before uploading.

### ISSUE THREAD

**Issue by akarineb** [ember-cli/ember-cli#6216]
I'm a bit new in that environment and I'm having a hard time signing my add-on .
I'm trying to sign my add-on , I have three type 2 xpi that are packaged in a kind of xpi 32. These three xpi have been signed by jpm . The problem is that when I 'm going to sign or try to send my type 32 xpi always failed validation appears the error " Sub -package must be signed
Error: Add-ons which contain sub-packages must have all sub-packages signed before uploading. " I've tried several things and redid the signing process from the start several times but is not working. I also want to understand how the package .json , I know he is created by jpm init, but how should I create ? it should be in the same folder on my xpi ? I can modify the information then ? where do I allocate it ? I can not quite understand how it works or to the serving .

**Comment by nathanhammond** [comment]
This is not an Ember CLI issue, I think you need to be looking for support over at https://github.com/mozilla/addon-sdk
