### ISSUE TITLE
remove `default` ember-try scenario for addons

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#6233]
I feel like this is the least useful config to test against. It uses the version of ember that you used to run your dummy app. That doesn't have much to do with appropriate ranges for consuming apps. I feel like `ember-release` is often testing the same version. Thoughts?

**Comment by nathanhammond** [comment]
I agree it's already covered by `release` 99.99% of the time, it adds no value once that release is no longer supported, and slows down testing cycles.

I'm in favor of this; it ends up being "the version of Ember which was current when I first developed this addon." That's valuable information but is already encoded into the `bower.json` file inside the addon.

**Comment by kellyselden** [comment]
Resolved in #6235
