### ISSUE TITLE
File name not supplied during parse errors, but line number is

### ISSUE THREAD

**Issue by uhrohraggy** [ember-cli/ember-cli#6238]
I have noticed it seems better in js flies, but hbs it's getting the line number but skipping the filename during parse errors. This is unfortunately still an issue in Ember CLI 2.6.1, making debugging a pain, and keeping me from being able to trust big changes without constantly refreshing the page. NPM version is 3.8.6

**Comment by uhrohraggy** [comment]
Sample error message is:

:appname has failed to build: Error: Parse error on line 3:

**Comment by nathanhammond** [comment]
Can you post a demo of an application which fails with the error message you don't like?

- `ember new bad-error-message`
- make the changes
- publish to GitHub
- link us here

That'll make it much easier for us to figure out what's going wrong. 😄 Thanks for taking the time to file an issue!

**Comment by stefanpenner** [comment]
This is most likely an issue/regression in the HBS transpiler

**Comment by locks** [comment]
I couldn't reproduce this with current versions. Please let us know if you have a reproduction, thanks!
