### ISSUE TITLE
Fixing SASS error doesn't reload the page from build error

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#6242]
Recently the ability to have changed styles hot-swapped without a reload was added (which is awesome!!).

I'm using [`ember-cli-sass`](https://github.com/aexmachina/ember-cli-sass), and a build error caused by invalid SASS, however, will cause the page to reload and display an error similar to:

> ### Build error
> 
> **tmp/sass_compiler-input_base_path-SJwgbQCL.tmp/0/app/styles/_some-style.scss, line 96**
> 
> **The Broccoli Plugin: [SassCompiler] failed with:**
> ---
> 
> ```
> Error: Invalid CSS after "}": expected "}", was ""
>     at options.error (node_modules/node-sass/lib/index.js:272:32)
> 
> The broccoli plugin was instantiated at: 
>     at SassCompiler.Plugin (node_modules/broccoli-plugin/index.js:7:31)
>     at SassCompiler.CachingWriter [as constructor] (node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
>     at new SassCompiler (node_modules/broccoli-sass-source-maps/index.js:20:17)
> ```

Fixing this error triggers a hot-swap reload rather than a full page reload. This unfortunately means you are still on the build error page rather than viewing your application. You have to manually reload the page to get back to your application.

It would be great if instead of requiring a manual reload, fixing such an error caused a full reload.

_(Originally posted as an [`ember-cli-sass` issue](https://github.com/aexmachina/ember-cli-sass/issues/135))_

---

```
$ ember version --verbose && npm --version
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
3.10.3

$ npm ls --depth=0 | grep ember-cli-sass
├── ember-cli-sass@5.5.1
```

**Comment by stefanpenner** [comment]
Ya, seems reasonable.
