### ISSUE TITLE
Proxy timeout with analytics enable 

### ISSUE THREAD

**Issue by thefuzz80** [ember-cli/ember-cli#6248]
After upgrading to 2.8, it seems as though usage analytics is trying to establish a connection and failing.  Although the issue does not stop ember-cli from working, it does add noise to the console that is alarming.  The only way to turn off the warning below is to change the analytics property in ```.ember-cli``` to  ```"disableAnalytics": false```

```
{ Error: connect ETIMEDOUT 172.217.4.132:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.4.132',
  port: 443 }
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 6.4.0
v8: 5.0.71.60
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
3.10.3
```

**Comment by nathanhammond** [comment]
@thefuzz80 You say "proxy" in the issue title but don't mention it again. Can you describe your particular machine/network setup? Or can you recreate the issue in a smaller app? I can't seem to reproduce.

**Comment by thefuzz80** [comment]
@nathanhammond forgive me I'm still new to opening issues. 

I assumed my corporate network proxy as the reason for the timeout on the odd IP address. 

I did dig and host on the IP address because it doesn't seem to belong to my private subnet. 

I will try on a brand new app when I get back into the office. However my hunch was that the usage analytics was trying to phone home and as soon as I changed the property it went away. 

I have another app that was trying to reach a 216.* address as well. Again not a subnet I recognize.

My setup is OS X running behind 2 proxies. The first is cntlm which helps with the poor support of the awful websense corporate proxy that I then pass through.  

Again, this error only appeared after updating the CLI this morning. When I ran the same ember project last night with only ember at 2.8 ( in the bower.json ) I did not see this message. 

Does this help? Let me know if you need more details.

**Comment by nathanhammond** [comment]
No concerns about unfamiliarity with issues, you provided enough information in the first one that I could ask a reasonable follow-up question. 😄 

- Did you end up doing a full new `npm install` as part of your upgrade to Ember CLI 2.8.0? 
- Can you try doing a clean `npm install` with Ember CLI pinned to 2.7.0 in `package.json`?

My goal is to find out if it is a transitive dependency issue that also affects Ember CLI 2.7.0 or if we broke something in Ember CLI 2.8.0.

**Comment by thefuzz80** [comment]
Yes I did a full ```npm install```. I always follow the release guide instructions and clean out everything.    Do you want it pinned right at 2.7.0 or on one of point releases?

**Comment by nathanhammond** [comment]
The full `npm install` could have reinstalled all sorts of things that changed. Pin Ember CLI to 2.7.0 in `package.json` and let me know if it works or if it's broken. If it works I'm going to want to do a screen sharing session with you. If it doesn't work I'll have enough information to make educated guesses on what changed.

**Comment by jcope2013** [comment]
just a guess, leek (0.0.22) changed from using the request module to using the https module to send out requests in the 2.8 series, int was pinned at 0.0.21 in ember-cli 2.7 https://github.com/twokul/leek/commit/61232d6f5447e9cbbe0e4a0f10abcd7d20dec949 https://github.com/ember-cli/ember-cli/commit/a9042f379b4e3639a60219bfaa7a28ad6e3d5db3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2, leek is used for the usage analytics

**Comment by thefuzz80** [comment]
Created 2 pristine projects, one with Ember ClI pinned to 2.7.0 and another pinned at 2.8.0

The output to the console on 2.7.0 is normal.  The output to the console on 2.8.0 is still:

```
{ Error: connect ETIMEDOUT 172.217.4.132:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.4.132',
  port: 443 }
```

**Comment by nathanhammond** [comment]
@thefuzz80 Can you move leek to 0.0.21 on the 2.8.0 project as suggested by @jcope2013 and see if that works?

**Comment by thefuzz80** [comment]
Here is the ```package.json``` pinning ```leek``` to ```0.0.21```.  Is this the correct way?

```
{
  "name": "proxy-leek",
  "version": "0.0.0",
  "description": "Small description for proxy-leek goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1",
	"leek": "0.0.21"
  }
}
```

If so, the issue still persists.

**Comment by nathanhammond** [comment]
@thefuzz80 I'm closing this issue as it's not actionable here. We need to address it upstream at `leek`. I've finally gotten enough information to open https://github.com/twokul/leek/issues/36
