### ISSUE TITLE
Remove remaining coupling to JSHint

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6269]
Currently our `app` and `addon` blueprints still include `.jshintrc` files (see https://github.com/ember-cli/ember-cli/tree/master/blueprints/app/files), which are now also provided by the default blueprint in `ember-cli-jshint` (see https://github.com/ember-cli/ember-cli-jshint/pull/21). To remove the duplication we should remove the `.jshintrc` files from our blueprint and run the `ember-cli-jshint` blueprint once the dependency is installed.

Unfortunately it's not quite as simple as adding the `lookupBlueprint().install()` call to the `afterInstall()` hook of the `app` and `addon` blueprints, because that hook will run _before_ `npm install` was executed. So currently possible is only:
1. `app` blueprint adds a `package.json` file including the `ember-cli-jshint` dependency
2. `app` blueprint tries to install `ember-cli-jshint` blueprint but fails because the dependency is not yet installed
3. `npm install` will install the `ember-cli-jshint` dependency but not run the corresponding blueprint

Now I am looking for ways to install the blueprint _after_ `npm install` has finished without breaking the world. Is there a good way to do this in the current code base?

Should we maybe implement a public `installAddon()` method that only resolves once `npm install` for that addon has finished?

/cc @rwjblue @stefanpenner

**Comment by nathanhammond** [comment]
`installAddon()` would neatly solve the running of default blueprints issue for non-module-name-identified packages. I'm in favor of doing something like that. This is a pattern we should rely upon more, so I like the proposal.

**Comment by aureliosaraiva** [comment]
How is this project making eslint default?
Can you detail how to reproduce the problem?
The problem was not clear to me!
It makes me willing to help in everything
