### ISSUE TITLE
Has something changed with Addon Testing that is breaking builds?

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-cli#6270]
Hi All!

I've been having trouble with Addon Testing lately with Ember Infinity.  [Travis link here.](https://travis-ci.org/hhff/ember-infinity/builds/160416347)

As you can see - the most recent master build passed - but now there's PRs up for changes in the README, and it's failing builds that passed recently.

I usually see this with new Beta builds, but it's strange to see this with builds that are locked to specific Ember versions, like 1.10.0.

I'm guessing that there's a `~>` in the Ember CLI blueprint `package.json` that has changed in the last couple months that is now breaking these builds, but I don't really know where to start.

Any ideas?

**Comment by Turbo87** [comment]
You could try http://package-hint-historic-resolver.herokuapp.com/ to figure out what transitive dependencies have changed. Maybe that contains a clue on what might be failing.

**Comment by nathanhammond** [comment]
@hhff You're using a [_tremendously_ out of date version of Ember CLI](https://github.com/hhff/ember-infinity/blob/master/package.json#L22) in that addon. You need to update Ember CLI. Some transitive dependency just broke your behavior which is probably accounted for in modern versions of Ember CLI.

Good luck on the migration, we can help you with that if you have trouble along the way. [See also this list of changes made in the default addon blueprint over that time period.](https://github.com/ember-cli/ember-addon-output/compare/v1.13.14...v2.8.0)

I'm closing this as likely not an Ember CLI issue. Good luck!

**Comment by hhff** [comment]
Word!  Thankyou @nathanhammond - will give that a go
