### ISSUE TITLE
Support blueprint generation without accompanying test

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#6273]
When running Ember CLI's blueprint generator, if a blueprint with the same name suffixed with `-test` exists, it will also be generated (_e.g._, `ember g model` generates both `model` and `model-test` blueprints).

While I strongly agree adding tests by default is a good idea (and encourages writing tests), often when generating certain blueprints I know that I will not need any tests. For example, generating a model that I know will only have fields with `DS.attr` but no other testable properties or functions. 

To get around this today, I end up typing similar to:
```bash
$ ember g model foo && ember d model-test foo
```

It would be convenient to instead have a flag I can use to skip test blueprint generation. For example:
```bash
$ ember g model foo --no-test
```

Is this a feature that a PR would be welcomed for?

**Comment by stefanpenner** [comment]
@SaladFork sounds interesting, would recommend and RFC before (or in parallel to a PR) that way we can bikeshed what this means, how it affects teachability etc.etc.

**Comment by kellyselden** [comment]
@SaladFork You might be able to piggy back on the concept in https://github.com/ember-cli/rfcs/pull/59, as that deals with blueprint decoupling as well.

**Comment by SaladFork** [comment]
Thanks! I've submitted [#68](https://github.com/ember-cli/rfcs/pull/68).
