### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6274]
It appears that our CI tests are currently broken, most likely due to some dependency update. The error looks roughly like this:

```
not ok 6 PhantomJS 1.9 - pods based templates: the application boots properly with pods based templates with a podModulePrefix set\n    ---\n        actual: >\n            null\n        stack: >\n            TypeError: 'undefined' is not a function (evaluating '_ember['default'].assign({}, _someCoolAppConfigEnvironment['default'].APP, attrs)')\n        message: >\n            beforeEach failed on the application boots properly with pods based templates with a podModulePrefix set: 'undefined' is not a function (evaluating '_ember['default'].assign({}, _someCoolAppConfigEnvironment['default'].APP, attrs)')\n        Log: |\n    ...\n"
```

From what I can tell the error is most likely coming from this line: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/tests/helpers/start-app.js#L9

**Comment by Turbo87** [comment]
This might be related to https://github.com/ember-cli/ember-cli/pull/6193 but interestingly the CI tests for that PR passed back then...

**Comment by nathanhammond** [comment]
Ohai, we tried to do this once before and it blew up: https://github.com/ember-cli/ember-cli/pull/5803

Going to try reverting #6193.

**Comment by Turbo87** [comment]
https://embercommunity.slack.com/archives/-testing/p1474058140001083 seems relevant to this discussion too

**Comment by nathanhammond** [comment]
Want to turn this into a tracking issue for understanding?
