### ISSUE TITLE
`ember init` to skip dependency checking

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#6277]
I'm brainstorming the command `init` skipping the dependency checking.

The only time I'm using `init` is when updating addons (usually very out-of-date). So I clone the repo, cd into it, run `npm link ember-cli`, and then try to `ember init` with my up-to-date global version. Then I get the dependencies missing message. I then have to install all these old packages, which I'm about to update or remove anyways. Seems to me that dependency checking when doing `init` is not useful.

I don't think any missing packages other than ember-cli would cause `init` to fail, correct?

**Comment by nathanhammond** [comment]
I believe you're correct. The trouble is basically this: https://github.com/quaertym/ember-cli-dependency-checker/blob/master/index.js#L8-L14

We'd need to land the change upstream. Realistically it should support a command blacklist instead of simply running on `init` in every case.

**Comment by locks** [comment]
To clarify to anyone looking to implement a fix for this, what needs to be done is that inside https://github.com/quaertym/ember-cli-dependency-checker/blob/master/index.js#L8 if the `ember-cli` command that was run was `init`, you skip the dependency checker.

**Comment by locks** [comment]
assigned to @gnclmorais

**Comment by gnclmorais** [comment]
This should be fixed soon…! 🙌🏻

**Comment by locks** [comment]
@quaertym please let us know when you release a new version with this fix so we can upgrade!

**Comment by quaertym** [comment]
[v3.3.0](https://github.com/quaertym/ember-cli-dependency-checker/releases/tag/v3.3.0) is released.

**Comment by gnclmorais** [comment]
Thank you @quaertym, I’ve opened https://github.com/ember-cli/ember-cli/pull/9848 to bring thins into `ember-cli`. 🙇‍♂️
