### ISSUE TITLE
this._super(...arguments) doesn't work in async functions after await

### ISSUE THREAD

**Issue by buschtoens** [ember-cli/ember-cli#6282]
Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 6.5.0
v8: 5.1.281.81
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
3.9.5
```

Referencing #3529.

`this._super(...arguments)` doesn't work inside `async` functions, when it is used after an `await` keyword.

```js
function sleep(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), ms);
  });
}

const Demo = Ember.Object.extend({
  worksAsExpected(...args) {
    console.log("works as expected:", ...args);
  },
  doesntWork(...args) {
    console.log("doesn't work:", ...args);
  }
}, {
  async worksAsExpected(...args) {
    this._super(...args);
    await sleep(1000);
  },
  async doesntWork(...args) {
    await sleep(1000);
    this._super(...args);
    await sleep(1000);
  }
});

const demo = Demo.create();
demo.worksAsExpected("test"); // => "works as expected:", "test"
demo.doesntWork("test");      // => nothing
```

**Comment by buschtoens** [comment]
I don't really understand how `this._super` is defined / works under the hood, but this is a "fix":

```js
async doesWorkNow(...args) {
  const _super = this._super;
  await sleep(1000);
  _super.call(this, ...args);
  await sleep(1000);
}
```

**Comment by rwjblue** [comment]
`this._super` works by roughly changing what `this._super` refers to before each method call.  Something like this is used to wrap functions that we detect need wrapping:

```js
function wrap(func, superFunc) {
  return function superWrapper() {
    let orig = this._super;
    this._super = superFunc;
    let ret = func.apply(this, arguments);
    this._super = orig;
    return ret;
  };
}
```

As you can see (and have discovered), this assumes that `this._super` will be called synchronously.  The work around as you noticed is to stash the current `this._super` synchronously and invoke it (via `.call` or `.apply`) when you need it.

This isn't really a bug (it is a gotcha for sure though).  There are probably things we can do during transpilation to make this much nicer though (i.e. allow using `this._super` in callbacks but have that unrolled to stashing the super and invoking at the location).

**Comment by buschtoens** [comment]
Thanks for the in-depth analysis. I always wondered how that magic `_super` method worked and thought that it would access `arguments.caller`, but never actually cared enough to dig into it, until now. :smile: 

This would definitely be a handy transform.

**Comment by stefanpenner** [comment]
This isn't ember-cli issue. But rather, super is unsafe to use asynchronously. On the bright side, real ES super will work as expected, and ember's and es6 super work together. Hopefully once decorators become stable, we can make the transition and the confusion and legacy _super go away :
