### ISSUE TITLE
ember-cli does not respect `bower_directory` environment variable

### ISSUE THREAD

**Issue by orf** [ember-cli/ember-cli#6290]
I'm currently in docker hell, and I need to have my npm and bower packages in the directory _above_ my app code. If my app is in `/usr/code/app` I need my bower_components to be in `/usr/code/bower_components`.

Bower lets you specify a `bower_directory` environment variable, and if I set this to `../bower_components` then `bower` works just fine. However `ember-cli` seems to ignore this and _only_ looks inside the `.bowerrc` file, but _only_ in the current directory and not in any parent directories.

Pretty much it would be great if ember-cli could respect the config rules described here: https://bower.io/docs/config/

Output from `ember version --verbose && npm --version`:

```
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.6.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: linux x64
3.10.3

```

**Comment by nathanhammond** [comment]
Related:
- #3679
- #3735
- #3771

@orf would you be willing to write a solution following the recommendations and discussion we've had on this topic in the past? The area where this would be implemented is here: https://github.com/ember-cli/ember-cli/blob/2bce175ce188ae0f47a55fa23d6affe2d768ddfb/lib/models/project.js#L69-L91

**Comment by orf** [comment]
Yes I would be willing to try, there is a 'bower-config' package that we
could use. I haven't seen any prior discussion, but surely adding
bower-config and using that would suffice?

**Comment by nathanhammond** [comment]
The discussion was with regards to node_modules in the aforelinked issues, but will also apply to bower_components. Let me know if you want help, you can find me and others who can help guide in [#dev-ember-cli](https://embercommunity.slack.com/messages/dev-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).

**Comment by orf** [comment]
Oh, I just read your comment and realized what you meant. I've made a MR that uses `bower-config` but that could cause problems with nested projects if I understand correctly?

I can just add an explicit environment variable `EMBER_BOWER_COMPONENTS` and do that instead?

**Comment by orf** [comment]
I did this in this commit: https://github.com/orf/ember-cli/commit/8a0c3b0031999b2338751425f4003ec3d27387a8

Let me know which you want, I can close my existing MR and make this one instead.

**Comment by orf** [comment]
Hi @nathanhammond, which one of the commits would you like me to make a MR for? I've made #6292, but if you're concerned about nested projects I was thinking that perhaps ember-cli could detect this case?

I.e if there is a project inside `/project/one/two`, and no `.bowerrc` file in that directory and one inside `/project/one`, then that MR would pick up `/project/one/.bowerrc` file as the one to use. That would be incorrect, perhaps we could throw an error if we detect an `ember-cli-build.js` file `/project/one` and say `you need to add a `.bowerrc` in `/project/one/two`?

**Comment by locks** [comment]
Thank you for the original report for everyone involved in the discussion. Given that Bower itself is deprecated this does no longer seem relevant. If you feel otherwise please re-open the issue!
