### ISSUE TITLE
Test failure on 2.8 upgrade: Assertion after the final `assert.async` was resolved

### ISSUE THREAD

**Issue by cklimkowsky** [ember-cli/ember-cli#6293]
After upgrading `ember-cli` and `ember` to 2.8 (and `ember-cli-qunit` to 3.0.1 to fix #6247), I'm seeing the following error in several different cases:

```
Assertion after the final `assert.async` was resolved
```

1. When running `ember test`, the error shows up intermittently on my model and adapter tests. These tests are the default tests generated with a new model/adapter, so I'm not calling `assert.async` anywhere in my tests. 
2. When running `ember test --server`, I get the same error on one of my component integration tests. This error appears consistently, unlike the errors from `ember test`.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o
os: darwin x64
3.8.1
```

**Comment by trentmwillis** [comment]
@cklimkowsky thanks for the report. These issues are only occurring in unit/integration tests for you? Can you provide a simplified reproduction or some steps to repro?

The `assert.async` is triggered as part of [the new QUnit adapter](https://github.com/rwjblue/ember-qunit/blob/c81bb7ad7c898d37dcd3433b308dab518e4a9456/lib/ember-qunit/adapter.js#L10) (since `stop` is now removed in QUnit 2.0).

**Comment by cklimkowsky** [comment]
@trentmwillis yes, unit tests for model/adapter tests on `ember test` and integration tests (only on one component it seems) on `ember test --server`. Not sure what other steps I can include for reproduction? I went through the upgrade process from `ember`/`ember-cli` 2.6 to 2.8, upgraded `ember-cli-qunit` to 3.0.1, and then ran `ember test`/`ember test --server`.

**Comment by cklimkowsky** [comment]
Update: I just got the error on an integration test running `ember test`, it seems that error is intermittent as well

**Comment by trentmwillis** [comment]
Does this happen with a brand new test? In other words, if you `ember g model foo`, will the `foo` test error at all?

**Comment by kpfefferle** [comment]
We were getting this error in our test suite as well, but I was able to resolve this by making sure that all of our acceptance tests are using the `find()` syntax within their asserts instead of the `this.$()` syntax (which is instead common in component integration tests). Doing this seems to match [the guides' usage of `find()` in acceptance tests](https://guides.emberjs.com/v2.8.0/testing/acceptance/).

I believe that the previous QUnit adapter was more tolerant of `this.$()` in acceptance tests while the newer version only properly works with `find()`.

**Comment by cklimkowsky** [comment]
@trentmwillis I can't seem to reproduce this anymore, neither with a brand new test or my existing tests. I'll close this for now and let you know if it becomes an issue again.

@kpfefferle Thanks for the additional insight, I was only seeing this with unit and integration tests

**Comment by dshrestha** [comment]
Same issue happened to us when we upgraded ember cli to 2.10. I noticed that this error shows up for each "andThen" helper method call in the integration test. From the above comment it seems like my ember version might have caused the problem. We are sadly stuck with ember 1.10.1, I wanted to take advantage of the new before/after hooks in quint 2, for which I had to update ember-cli.

This is pretty much what the test looks like. I think we are using "find" helper properly too. I did try using var done = assert.async(); and done() with andThen which caused the error[Assertion after the final `assert.async` was resolved] to go away but the tests started failing randomly.

`
    import Ember from "ember";
    import {module, test} from 'qunit';
    import MockServer from 'studio/tests/mockServer/mocks';
    import startApp from 'studio/tests/helpers/start-app';

    var mockServer = new MockServer(),
        application,
        selectAggregate = function () {
            click('.show-metric-filter input[name="Aggregate"]');
        };

    module("[Reporting] [Custom Questions] [BY CONCEPTS]", function (hooks) {

        hooks.before(function () {
            application = startApp();
            mockServer.loadReportsMocks();
            visit('projects/2/reports/quick-predict/deliverables/custom-questions');
        });

        hooks.after(function () {
            mockServer.clear();
            Ember.run(application, 'destroy');
        });

        test("should show selected 'show' option texts [AIR-862]", function (assert) {
            //var done = assert.async(); 
            assert.equal(Ember.$.trim(find(".show-metric-filter .selected-options-label").text()), 'Stat Testing');
            selectAggregate();
            andThen(()=> {
                assert.equal(Ember.$.trim(find(".show-metric-filter .selected-options-label").text()), 'Stat Testing, Aggregate');
                //done();
            });
        });
    });
`

**Comment by strongmindsmhs** [comment]
New to Ember, pulled version 2.10, including CLI and I'm getting the same error with an acceptance test like: 

    test('should redirect to register route', function(assert) {
        visit('/');
        click('a[data-register="true"]');
        andThen(() => assert.equal(currentURL(), '/registration', 'should redirect to registration')
    );

Assertion after the final `assert.async` was resolved@ 227 ms
Source: 	
    at Assert.ok (http://localhost:4200/assets/test-support.js:4181:11)
    at Class.exception (http://localhost:4200/assets/test-support.js:7199:47)
    at adapterDispatch (http://localhost:4200/assets/vendor.js:49018:13)
    at Object.dispatchError (http://localhost:4200/assets/vendor.js:27439:7)
    at onerrorDefault (http://localhost:4200/assets/vendor.js:40942:19)
    at Object.trigger (http://localhost:4200/assets/vendor.js:68386:9)
    at http://localhost:4200/assets/vendor.js:69270:26
    at invoke (http://localhost:4200/assets/vendor.js:10892:14)

**Comment by Darshan-Chauhan** [comment]
I am also facing the same issue, I also tried the solution mentioned by @kpfefferle but it didn't work

**Comment by dshrestha** [comment]
I found the actual issue behind this(https://github.com/qunitjs/qunit/issues/777). The reason we are getting this issue is because our assertions are getting called after the "done" hook is called which is a 'no no' in qunit 2.

For me (ember version "1.10.1"), when I checked my wait helper method, it looked like:

    function wait(app, value) {
      return Test.promise(function(resolve) {
        // If this is the first async promise, kick off the async test
        if (++countAsync === 1) {
          Test.adapter.asyncStart();
        }

        // Every 10ms, poll for the async thing to have finished
        var watcher = setInterval(function() {
          var router = app.__container__.lookup('router:main');

          // 1. If the router is loading, keep polling
          var routerIsLoading = router.router && !!router.router.activeTransition;
          if (routerIsLoading) { return; }

          // 2. If there are pending Ajax requests, keep polling
          if (Test.pendingAjaxRequests) { return; }

          // 3. If there are scheduled timers or we are inside of a run loop, keep polling
          if (run.hasScheduledTimers() || run.currentRunLoop) { return; }
          if (Test.waiters && Test.waiters.any(function(waiter) {
            var context = waiter[0];
            var callback = waiter[1];
            return !callback.call(context);
          })) { return; }
          // Stop polling
          clearInterval(watcher);

          // If this is the last async promise, end the async test
          if (--countAsync === 0) {
            Test.adapter.asyncEnd();
          }

          // Synchronously resolve the promise
          run(null, resolve, value);
        }, 10);
      });

    }

So as you can see, when all async actions have been completed we call `Test.adapter.asyncEnd();` first which effectively calls `done()` in qunit and then continues on with resolving the test promise `run(null, resolve, value);` which executes our assertions and thus giving us the error that we see. For me the fix was -

    function wait(app, value) {
      return Test.promise(function(resolve) {
          .......
          // If this is the last async promise, end the async test
          if (--countAsync === 0) {
            // Synchronously resolve the promise
            run(null, resolve, value);
            Test.adapter.asyncEnd();
          }
        }, 10);
      });

    }

I am still trying to figure out how to make this change properly without editing the ember.js file in the  bower_components folder though!

**Comment by akshaisarma** [comment]
I am also seeing this issue. 

@dshrestha, you should probably make a new issue since this one is closed.
