### ISSUE TITLE
Remove "ember-export-application-global" from the default app blueprint

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6294]
I personally don't see any point in having this addon included by default for every app. Unless someone can explain to me why this is useful for the majority of our users (that don't have the ember-inspector where you can also get access to the application instance) I would like to remove it from the `app` blueprint.

**Comment by stefanpenner** [comment]
@lukemelia once convinced me of this, he should share his thoughts (they where quite convincing)

**Comment by Turbo87** [comment]
@lukemelia any comments?

**Comment by lukemelia** [comment]
I don't recall this particular situation, but there are many situations where I don't have Ember inspector installed or I don't want to open/install it, including a) in the Chrome instance that testem spins up, b) troubleshooting something on a end user's machine.

**Comment by locks** [comment]
✅
