### ISSUE TITLE
Sourcemaps config option

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6304]
As discussed in last weeks team meeting we should add a config option to enable end-to-end source maps, defaulting to `false` for now. This is mainly meant to enable experiments with the feature to make it faster.

**Comment by Turbo87** [comment]
assigning myself for now, but if anyone else wants to give this a shot I'd be happy to step back 😉

**Comment by irvinebroque** [comment]
By "end-to-end" do you mean "sourcemaps that include vendored dependencies?

https://github.com/emberjs/core-notes/blob/master/ember-cli/2016-09/september-22.md#source-maps

**Comment by stefanpenner** [comment]
@irvinebroque yes, although vendored should already work by default. We mostly want to eventually have 1:1 source maps for the app (currently, the issue is all source-map libs are to slow for big apps.....)

**Comment by irvinebroque** [comment]
Thanks @stefanpenner! Any pointers on where in the asset pipeline or config to look if we're not getting sourcemaps for vendored files?

For our (quite large) Ember app, sourcemaps are actually working well for our own code, but having them for libs (including Ember) would be a huge help for tracking down issues.

**Comment by Turbo87** [comment]
this was implemented by https://github.com/ember-cli/ember-cli/pull/6458. thanks @dwickern!
