### ISSUE TITLE
consider cleanup of watch-detector

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6311]
https://github.com/ember-cli/ember-cli/pull/6309#discussion_r81490324

specially: https://github.com/ember-cli/ember-cli/blob/master/lib/models/watch-detector.js#L173-L181

It is documented (although those comments can be improved), but if someone feels they can express it in a clearer way a PR for review would be good.

**Comment by locks** [comment]
Closing as a related PR with cleanup has been merged.
