### ISSUE TITLE
JS Loading performance optimization

### ISSUE THREAD

**Issue by Iftahh** [ember-cli/ember-cli#6312]
@nolanlawson Wrote a https://github.com/nolanlawson/optimize-js

His benchmark show that Ember.js can benefit from IIFE wrapping optimization -  Loading the JS in 1.24ms instead of 70.93ms !

See https://github.com/nolanlawson/optimize-js#benchmarks

It sounds a bit too good... but worth a check.

**Comment by rwjblue** [comment]
The benchmark used applies to the ember.min.js that is generated by Ember itself, which does not use the same settings as a default ember-cli app (specifically the negate_iife setting to uglify). 

ember-cli apps *definitely* will see an impact from the research that @krisselden and @nolanlawson have done, but it isn't as dramatic as the benchmarks you linked suggest (~ 4000% improvement 😱).

Also, If you review the meeting minutes from the last ember-cli core team meeting, we specifically discussed a plan that @krisselden's was pushing forward to take advantage of that research.

**Comment by stefanpenner** [comment]
@Iftahh we are part of this research. Basically, ember.js itself benefits from this, your app code largely doesn't (but small parts do). Applying this naively across the board actually degrades performance.

@krisselden is working on tooling to allow for selective use, once/if that reaches maturity we will consider it here.

**Comment by Iftahh** [comment]
Excellent! 
I only wanted to make sure you are aware of this trick and consider it.
I searched for existing issues of similar topic, but didn't think to look at the core meeting minutes...

**Comment by nathanhammond** [comment]
https://github.com/emberjs/core-notes/blob/master/ember-cli/2016-09/september-29.md#parsing-hints
