### ISSUE TITLE
Favicon with version to force refresh

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli/ember-cli#6313]
What are the thoughts behind the decision not to explicitly set a favicon in the index.html? I know it will find one by default, but if we place a version it will force refresh which I like very much. Sorry if this has already been discussed. I tried to search first. I know there hasn't been a final decision on an ember asset for this, but it would save time to just have this here since we end up running init and bulldozing over the index often. Thoughts? : )

```
<link rel="icon" href="http://www.yoursite.com/favicon.ico?v=2" />
```

**Comment by nathanhammond** [comment]
You can add this into your own `index.html`. As to the upgrade process I usually process the diff manually [which is linked from the upgrade log](https://github.com/ember-cli/ember-new-output/compare/v2.7.0...v2.8.0?diff=unified&name=v2.8.0).

Or from a checked out version (not guaranteed to work):

```bash
git diff v2.4.0 v2.5.0 | pbcopy
pbpaste | git apply
```

I'm closing this as we don't intend to change this behavior in the blueprints.
