### ISSUE TITLE
Using css from another project

### ISSUE THREAD

**Issue by hdehaan01** [ember-cli/ember-cli#6314]
I am writing several application with Ember and are using also a written own libary.
This library is included using:
    "web-input-components": "git+ssh://git@gitlab:gui-js-lib/web-input-components.git#develop"

But I also want to use one general css file from this same library. Is there a way in Ember to include the css in the same way?

**Comment by stefanpenner** [comment]
As per the CONTRIBUTING.md (the big yellow banner one see before submitting an issue)  this is better suited for Stackoverflow which has a good framework for Q/A style discourse. https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#questions

**Comment by nathanhammond** [comment]
I'd recommend stopping by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community!
