### ISSUE TITLE
App no longer renders. Starting ember server results in blank screen.

### ISSUE THREAD

**Issue by vichen** [ember-cli/ember-cli#6316]
Just cloned a repo that previously loaded in the browser. Now I'm getting a blank screen with the following errors:

> Uncaught Error: an unsupported module was defined, expected `define(name, deps, module)` instead got: `1` arguments to define
> Uncaught Error: Could not find module `ember-resolver` imported from `webapp/resolver`

Already tried downgrading loader.js versions, switching between ember versions 2.8, 2.4.3, 2.6.1, and downgrading ember-resolver versions.

**Comment by tniezurawski** [comment]
@vichen I have exactly the same problem. How did you fixed that?
