### ISSUE TITLE
Default blueprint doesn't write to bower when conflict

### ISSUE THREAD

**Issue by toddjordan** [ember-cli/ember-cli#6334]
I have an addon that wraps the alpacajs form library.  When i install this addon on a clean ember cli 2.8, I get prompted for a jquery version resolution.  When I pick a version, none of the bower files specified in addBowerPackagesToProject are written.   I would expect the command to either use the specified version in the conflict resolution, or give some text on what to do next. 

the addon is called ember-cli-dynamic forms, the default blueprint is here: 
https://github.com/toddjordan/ember-cli-dynamic-forms/blob/master/blueprints/ember-cli-dynamic-forms/index.js

To reproduce just create a new ember project and install the addon:

``` shell
ember new my-proj
cd my-proj
ember install ember-cli-dynamic-forms
```

---

Output from `ember version --verbose && npm --version`:

```
ember-cli: 2.8.0
http_parser: 2.6.2
node: 5.10.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: darwin x64
3.8.3
```

**Comment by vvscode** [comment]
@toddjordan  when you pick version - do you use `!` prefix before picked variant?

Suppose that conflict is in zone of  responsibility of bower, not ember-cli. And for bower using `!` say `I want to save my choice` ( and it have related message during conflict resolution )

**Comment by nathanhammond** [comment]
This does seem like a bug, @toddjordan. Since I've not been bitten by this it isn't on my personal high-priority list. However, helping _you_ land a fix for it _is_ high on my priority list. Would you be willing to take a swing at opening a PR for this? I'd be excited to work with you on Slack/pairing to help get it landed!

**Comment by toddjordan** [comment]
Hi @nathanhammond I would be willing to PR a fix.  Lets try to get together this week.  I'll hit you up on slack.

**Comment by nathanhammond** [comment]
@toddjordan and I just paired to investigate what was happening here.

This was broken by #5831. [Bower itself uses an older version of `inquirer`](https://github.com/bower/bower/blob/master/package.json#L39) which is incompatible with the way in which we're binding things.

In order for this to work we likely need to make sure that [`ui.prompt`](https://github.com/ember-cli/ember-cli/blob/c36ac24316bcfa2726aa533ad6faba2455bf2eb5/lib/ui/index.js#L205) is shimmable/compatible with both 0.X and 1.X versions of inquirer.

/cc @Turbo87

**Comment by Turbo87** [comment]
remind me again why we need to pass our own `inquirer` into `bower`? can't we just use the default?

**Comment by nathanhammond** [comment]
I don't know, but @toddjordan will know soon enough! 😜 He's going to get us a PR for making this play nicely and get some tests in place.

**Comment by toddjordan** [comment]
took a look at the fix today.  It seems that I'm actually getting the newer version of inquirer at runtime, but in the newer inquirer, the callback is no longer taken as an argument, and therefore the bower packages don't get added after the conflict is resolved.  Simply adding a then block to the promise where we invoke the callback seems to work like so: 

```javascript
  return inquirer.prompt(questions).then(function (answer) {
    if (callback) {
      callback(answer);
    }
    return answer;
  });
```

This does the trick for me (I'll look at adding a test).  Now we mentioned having to support bower's back version of inquirer.  I haven't seen this version used yet.  Is there a scenario where this happens?

**Comment by nathanhammond** [comment]
@toddjordan I'm unsure if we actually end up using Bower's version. Since we're binding our version and passing it in we can possibly get away with _just_ that.

**Comment by nathanhammond** [comment]
Closed by https://github.com/ember-cli/console-ui/issues/7
