### ISSUE TITLE
Explore if YARN can be used as the bundled `npm`

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6341]
Note: Yarn + ember-cli seem to work together, this issue is specifically for exploring ember-cli + yarn bundled together

---

Once the dust settles, we can continue this an RFC. For now, this is purely fact-finding to inform a future RFC
- [ ] currently not aligned with Node LTS: ~~https://github.com/yarnpkg/yarn/issues/650~~ https://github.com/yarnpkg/rfcs/pull/1 (but seems like it easily could be, and am volunteering to help with the effort).
- [ ] programmatic API (someone needs to check if this exists, and if it can be added to the "public" api)

**Comment by stefanpenner** [comment]
yarnpkg/yarn#650

**Comment by devinus** [comment]
Yarn doesn't seem to work with both a `package.json` and `bower.json` in the same repo.

**Comment by IgorKvasn** [comment]
related issue: https://github.com/yarnpkg/yarn/issues/617

**Comment by fooey** [comment]
Looks like yarn is deciding to abandon bower support: yarnpkg/yarn#1441

**Comment by wagenet** [comment]
Does this also cover using yarn for `ember install ADDON`?

**Comment by stefanpenner** [comment]
@wagenet yes, actually this is the primary goal.

**Comment by Cryrivers** [comment]
Another thing is I think ember-cli could choose npm or yarn based on the exisistance of yarn.lock

**Comment by Turbo87** [comment]
@Cryrivers actually we would like to use yarn unconditionally. otherwise we'd probably have to bundle both and that would increase our dependency load even further.

**Comment by kanongil** [comment]
While yarn has definite advantages, I'm also not a fan of being forced to use it.

Btw, why is npm / yarn even bundled? With node 0.10.x support gone, we can expect a local >=2.x npm installation. I see some prior discussion around this here: https://github.com/ember-cli/ember-cli/issues/5082#issuecomment-197566444.

**Comment by Turbo87** [comment]
@kanongil there is https://github.com/ember-cli/rfcs/pull/88 now to discuss the option of not bundling those as dependencies

**Comment by nathanhammond** [comment]
@kanongil Note that we intend to propose wholesale `yarn` adoption via RFC. In that possible future it will be our sole package management story. We're already laying the foundation for that work inside of Ember CLI since we must support either during the interim.

**Comment by Turbo87** [comment]
actually if we adopt my RFC there is nothing holding us back from supporting both until one of them dies :wink:

**Comment by nathanhammond** [comment]
@Turbo87 For reasons of support costs I want us to standardize on one if at all possible. Doing so will also help one of them die...

**Comment by rofrnnds** [comment]
maybe this could work...
(taken from [https://github.com/facebookincubator/create-react-app/blob/master/packages/create-react-app/index.js#L143](url))

`function shouldUseYarn() {
  try {
    execSync('yarnpkg --version', {stdio: 'ignore'});
    return true;
  } catch (e) {
    return false;
  }
}

function install(packageToInstall, verbose, callback) {
  var command;
  var args;
  if (shouldUseYarn()) {
    command = 'yarnpkg';
    args = [ 'add', '--dev', '--exact', packageToInstall];
  } else {
    command = 'npm';
    args = ['install', '--save-dev', '--save-exact', packageToInstall];
  }`

**Comment by rofrnnds** [comment]
Maybe this could work:

https://github.com/facebookincubator/create-react-app/blob/master/packages/create-react-app/index.js#L143

**Comment by Caltor** [comment]
Is there a way to force `ember install ...." to use yarn?

**Comment by Turbo87** [comment]
yes, `--yarn`
