### ISSUE TITLE
`analytics.trackTiming()` always receives the category "rebuild"

### ISSUE THREAD

**Issue by mdebbar** [ember-cli/ember-cli#6348]
I would expect the category "build", "cold-build" or "warm-build" when I run a new build. But I always get a "rebuild" category. Is that the intended behavior? I would like to be able to log and track the timing of different categories separately "cold-build", "warm-build" and "rebuild".

Some more details:

`ember build` produces the following:
--
```javascript
{
  category: "rebuild",
  variable: "build time",
  label: "broccoli build time",
  duration: 12345
}
```
Code [here](https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/tasks/build.js#L31-L36). I was expecting to get `category: "build"` (or `"cold-build"`/`"warm-build"` if we want to be more specific).

`ember build --watch` produces:
--
```javascript
{
  category: "rebuild",
  variable: "rebuild time",
  label: "broccoli rebuild time",
  duration: 12345
}
```
Code [here](https://github.com/ember-cli/ember-cli/blob/ab70f424494245e82b1b5f3a25265abbd5f3f325/lib/models/watcher.js#L52-L57). I was expecting to get `category: "build"` for the first build, then `"rebuild"` on subsequent builds.

I know how to fix the first one (`ember build`) and I can send a PR. But I'm not sure about the second (`ember build --watch`).

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.7.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.7
```

**Comment by nathanhammond** [comment]
This is likely because you had a persistent cache and it identified that it wasn't a completely cold build. Can you confirm by removing `/tmp/*async-disk-cache-*`?

**Comment by nathanhammond** [comment]
Oh look at that, it's hardcoded. I simply assumed that we tried to do the right thing.

**Comment by rwjblue** [comment]
haha, never assume that!

**Comment by nathanhammond** [comment]
@rwjblue I feel like :trollface: should be promoted to a reaction.

**Comment by stefanpenner** [comment]
we could in theory differentiate between first rebuild, and subsequent rebuilds. But beyond that, the rest is tricky.

**Comment by twokul** [comment]
it might be tricky even for re-builds. apart sane watch registry and persistent filter cache, is there another way to tell we're running a subsequent build? @stefanpenner

**Comment by mdebbar** [comment]
@twokul one idea I thought of is using a build counter. If the counter is 0 it's a build.. anything greater than 0 is a rebuild.

**Comment by twokul** [comment]
we won't be able to deterministically tell if it is a cold/warm build or not. say instance of ember-cli crashes but persistent cache still exists (it will technically be a warm build).

**Comment by mdebbar** [comment]
Sure, `warm` vs `cold` is tricky. My comment was re: `rebuild` vs `initial build`.

**Comment by nathanhammond** [comment]
@twokul We can probably expose some API to accomplish that on https://github.com/stefanpenner/async-disk-cache ... hit vs. miss ratio? But I think we're storing additional data inside of the `value` which makes pure hits & misses not extremely relevant.

We almost want to weight it based upon number of hits and time saved by that cache hit.

**Comment by mdebbar** [comment]
@nathanhammond @stefanpenner @twokul does the exposed API have to be "warm" vs "cold"? What if ember-cli just exposes some valuable information (e.g. hit vs miss ratio) and let the user decide the classification? I can see different users having different definitions of what "cold" and "warm" are. Ember-cli should give them enough information, allowing them to classify builds according to their own definitions.

**Comment by stefanpenner** [comment]
@mdebbar in theory that is possible, but requires instrumentation changes to the full stack. Not impossible, but something that needs more consideration.

**Comment by nathanhammond** [comment]
This conversation has now moved into the things we're discussing in #6349 and isn't as closely tied to the original issue report. @twokul and I have submitted a PR with documentation to explain what is going on to future travelers (read: all of us in six months).
