### ISSUE TITLE
Avoiding `EmberENV` global variable pollution

### ISSUE THREAD

**Issue by ebryn** [ember-cli/ember-cli#6351]
Currently, in [`vendor-prefix.js`](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/vendor-prefix.js), we always set `window.EmberENV`.

For users that are trying to use Ember CLI to build encapsulated JS code that doesn't pollute the global namespace, this global being set is unavoidable and difficult to monkeypatch away.

It would be nice to reevaluate how we're passing the EmberENV along and at the minimum make it possible to configure Ember CLI to not emit this code.

I also noticed the `runningTests` variable is defined despite having `autoRun: false` configured, which means we're defining it in the build output for no reason.

**Comment by nathanhammond** [comment]
@ebryn This will unfortunately likely break a large portion of the ecosystem and should be done as part of our 3.0 release. Whatever we replace it to will be easy to migrate to, but will still require everybody to make an adjustment. I'm going to reopen this as an issue on our RFCs repo as a "breaking bugfix 3.0" item.

**Comment by ebryn** [comment]
@nathanhammond I believe we can add a flag, similar to `autorun` and `storeConfigInMeta` that gives users a means of avoiding the `EmberENV` global being output. Would be nice to find an intermediate path towards this that doesn't require waiting until 3.0.

**Comment by kellyselden** [comment]
or using an addon, via exclusive like `ember-disable-prototype-extensions` or inclusive like `ember-export-application-global`

`ember-disable-ember-env-global` or `ember-export-ember-env-global`

**Comment by nathanhammond** [comment]
3.0 will hopefully follow the "no-new-features" pattern, so we would want to land it in advance behind some sort of configuration, opt-in. Then, after some time, opt-out, and then, at 3.0 remove the option. If you're willing to create a PR for this we'd definitely consider it.

**Comment by ebryn** [comment]
I've looked into the implementation a bit and I think I have a relatively easy solution in mind.

@rwjblue Is there a reason why [these lines](https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/broccoli/vendor-prefix.js#L3-L4) are hardcoded and not just emitted by the `{{content-for 'vendor-prefix'}}`? Perhaps there is an ordering requirement?

**Comment by nathanhammond** [comment]
@ebryn `EMBER_ENV` is hardcoded because of the [original method for populating it](https://github.com/ember-cli/ember-cli/blob/d62cd9f9f1dc5e97a90d80adb01c243addefe8ab/lib/broccoli/ember-app.js#L734), it'd be fine to move it into `vendor-prefix` to allow for that to be the dynamic insertion point. Unsure about the tests.
