### ISSUE TITLE
Error proxying to (insecure?) connections, --secure-proxy / --insecure-proxy ?

### ISSUE THREAD

**Issue by grapho** [ember-cli/ember-cli#6357]
![screenshot from 2016-10-17 15 58 14](https://cloud.githubusercontent.com/assets/8184011/19453316/c0ce89b0-9482-11e6-819b-e21eb9e185f4.png)

Above, I posted a convo I had with myself on Slack

Regarding the recent change of `--insecure-proxy` to `--secure-proxy` ... I appear to be in a state where I cant proxy to any insecure server? at least that is what i think is happening...

It does not matter if a include the flag or not.. the server is having problems resolving certificates.

Command(s) attempted:
`ember serve --proxy https://qa-03-02-xx.lariatcentral.net`
`ember serve --proxy https://qa-03-02-xx.lariatcentral.net --insecure-proxy`
`ember serve --proxy https://qa-03-02-xx.lariatcentral.net --secure-proxy`

Always Resulting in Error(s):
```
GET /api/rest/security/whoami - - ms - -
Error proxying to https://qa-03-02-xx.lariatcentral.net
unable to verify the first certificate
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

The "breaking" change: https://github.com/ember-cli/ember-cli/pull/6166

not sure what this change means for me?

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p
os: linux x64
2.11.3
```

**Comment by nathanhammond** [comment]
@grapho and I chatted in Slack. `--secure-proxy=false` is what you're looking for, I believe.

**Comment by grapho** [comment]
@nathanhammond thanks for the info!
