### ISSUE TITLE
Broken on Node v6.8.1?

### ISSUE THREAD

**Issue by mikl** [ember-cli/ember-cli#6359]
After upgrading to Node.js 6.8.1, ember-cli appears to be completely broken.

Any use of the `ember` command does nothing – it outputs nothing, but (seemingly) never exits, like it's waiting for a callback that never comes.

---

Output from `ember version --verbose && npm --version`:
```
% ember version --verbose
[ never finishes ]
% npm --version
3.10.8
% node --version
v6.8.1
% uname -a
Darwin Rationalis.local 16.1.0 Darwin Kernel Version 16.1.0: Mon Oct  3 14:03:15 PDT 2016; root:xnu-3789.21.3~20/RELEASE_X86_64 x86_64
```

**Comment by btecu** [comment]
Works fine for me:
```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 6.8.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: win32 x64
```

**Comment by mikl** [comment]
Hmmkay, very strange. I've tried rebooting, reinstalling, different versions of ember. Nothing seems to help. Maybe it's my machine thats just b0rked.

**Comment by nightire** [comment]
@mikl If you keep waiting, does it throw an error finally? I don't remember exactly what it is, something like `ETIMEDOUT` or similar.

If so, try `npm install portfinder@1.0.7` in your project, don't install the latest version, just `1.0.7`.

**Comment by nathanhammond** [comment]
Pattern matching, this is going to be a `watchman` problem: https://github.com/ember-cli/ember-cli/issues/6259#issuecomment-247110522

I'm closing this issue as not a bug but if upon further investigation on your side you discover that it may in fact be a bug keep conversing here. We will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Comment by Cryrivers** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1313238/19486842/93434c36-9592-11e6-96d8-84666d6eedbe.png)

I also believe it is not related to the `watchman` problem but a `portfinder@1.0.8` problem.

**Comment by nathanhammond** [comment]
@Cryrivers can you confirm your platform?

**Comment by Cryrivers** [comment]
@nathanhammond macOS 10.12.0 / Node v5.12.0 / Ember CLI 2.8

**Comment by nathanhammond** [comment]
Abandoning this thread. If it's watchman we're solved. If it's portfinder we have #6361 to track it now.

**Comment by mikl** [comment]
Uninstalling watchman solved the issue, thanks.
