### ISSUE TITLE
`this.app.options` is `undefined` before `included` hook is called

### ISSUE THREAD

**Issue by zackthehuman** [ember-cli/ember-cli#6362]
Accessing `this.app.options` is `undefined` until the `included` hook is called. This is normally OK unless you want to use build-time configuration inside of `setupPreprocessorRegistry`.

I have a specific use case where a dev can specify settings for a CSS preprocessor, and those settings are used to determine what to do inside of `setupPreprocessorRegistry`. Unfortunately I can't get access to these since the host is not defined yet.

There is a way to work around this by using `registry.app`, but that feels like a hack since it just _happens_ to be the app.

**Comment by nathanhammond** [comment]
We need to define the set of hooks and order of operations we desire for all of the hooks inside of Ember CLI.

**Comment by zackthehuman** [comment]
I'm on board with this idea. Do we need an RFC? What do we need to do get this figured out?

**Comment by stefanpenner** [comment]
> Accessing the return value of this._findHost()

this isn't public API, nor do I think supporting this feature makes much sense.

**Comment by zackthehuman** [comment]
> We ultimately don't want duplicates, nor do we want N nested dependencies all mutating a single root registry.

Agreed. That's not what this issue is about. This issue is about not being able to access build-time options until `included` has been called. This aspect make absolutely no sense to me since the build options are set in the constructor of the top-level object (excluding the `Project`).

I don't see why this limitation is in place other than it is just an oversight.

The big about `this._findHost()` is just additional information and does not directly have bearing on the issue. I will update the title so we don't focus on it.

**Comment by nathanhammond** [comment]
@zackthehuman It will need an RFC as a consequence of necessarily changing semantics. While we put things in order we should also take notes on the things that it feels like we're missing. 😛

**Comment by nathanhammond** [comment]
Also, since this must be an RFC I'm closing it here. @zackthehuman would you pretty please port the concept to an issue over on the RFC's repo? Or write an RFC? 😜

**Comment by nathanhammond** [comment]
(Aside, I would be willing to consider addressing this one case as a bugfix if you wanted to take a swing at a PR. I'm unsure how much would have to change to support it and that would be what makes the decision for me.)

**Comment by zackthehuman** [comment]
@nathanhammond Posted an issue: https://github.com/ember-cli/rfcs/issues/73

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/7059 may resolve this?
