### ISSUE TITLE
use ember new project-name but it throws error after npm install yarn

### ISSUE THREAD

**Issue by khunemz** [ember-cli/ember-cli#6365]
after` npm install -g yarn`

I try to create new project
`ember new project-name -dir ui`

but it shows an error
`You cannot use the new command inside an ember-cli project.`

I am using

```
ember-cli: 2.8.0
node: 4.2.6
os: darwin x64
```

Others info

```
npm version 3.10.7
node version v4.2.6
bower version 1.7.9
```
Thank you in advance

**Comment by twokul** [comment]
@khunemz just tried `ember new project-name -dir ui` and it worked.

```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: darwin x64
```

are you sure you are not inside existing project?

**Comment by khunemz** [comment]
@twokul I am in the empty directory no any projects included.

**Comment by Adminpyramid** [comment]
i got the solution for this, am using dell with window 11, 

C:\Users\Public\research>node
Welcome to Node.js v20.11.0.

The option is to create a project inside the Public user and not user user in your computer

C:\Users\Public\research>

it will works
