### ISSUE TITLE
Warn when different addons overwrite each other's file

### ISSUE THREAD

**Issue by ctusch** [ember-cli/ember-cli#6372]
I'm currently using in-repo-addons to structure the files in our project. This has the disadvantage that one wouldn't immediately notice when two addons have e.g. a service with the same name. Would it be possible for ember-cli to output a warning in such a case?

**Comment by stefanpenner** [comment]
yes, this is a known issue for ages. TL;DR although people use it, nested add-ons  are actually not yet supported. Although we do have plans to support this, right now it is merely fraught with peril.

**Comment by ctusch** [comment]
I'm not sure whether we are talking about the exact same thing. To clarify: There is never a warning about a file name collision in the importing app, not with normal, unnested addons and also not with in-repo addons. I have not tested it with nested addons.

**Comment by nathanhammond** [comment]
@ctusch Confirm. We're on the same page. We have `overwrite: true` set on our broccoli trees.

**Comment by stefanpenner** [comment]
I suspect the only reasonable solution is to not use `app/` in add-ons,  and rather defer to generators to re-export. This makes merges explicit

**Comment by locks** [comment]
Closing as stale. With v2 addons this isn't much a concern, either.
