### ISSUE TITLE
ENOTFOUND google-analytics.com

### ISSUE THREAD

**Issue by sibijohn72** [ember-cli/ember-cli#6384]
I created a new ember application in 1.13 and upgraded it 2.9.0. When i server the ember app, it gets served successfully. I am able to see "Welcome to ember" but the console has the following message related to google-analytics. I am behind a proxy, could that be causing this issue?

---

Output from `ember version --verbose && npm --version`:
ember-cli: 2.9.1
http_parser: 2.5.2
node: 4.4.7
v8: 4.5.103.36
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
os: win32 x64
4.0.0

Error Message :
{ [Error: getaddrinfo ENOTFOUND google-analytics.com google-analytics.com:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'google-analytics.com',
  host: 'google-analytics.com',
  port: 443 }

**Comment by twokul** [comment]
does disabling analytics make the problem go away?

**Comment by stefanpenner** [comment]
@twokul having just come back from somewhere with spotty internet, i realize this happens more then I thought. I had an idea, could leek hide these types of errors?

**Comment by twokul** [comment]
@stefanpenner ya, tracking here https://github.com/twokul/leek/issues/36

**Comment by stefanpenner** [comment]
@twokul thanks :)

**Comment by nathanhammond** [comment]
Closing here as it's not addressable on this side and we control the upstream.
