### ISSUE TITLE
Style bleeds out from ember-welcome-page.css

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-cli/ember-cli#6389]
I was confused about where this orange text was coming from in my app and I finally tracked it down to ember-welcome-page.css. I feel strongly that these styles should not be bleeding out into my whole app at a top-level.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.9.1
http_parser: 2.7.0
node: 7.0.0
v8: 5.4.500.36
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 51
openssl: 1.0.2j
os: linux x64
3.10.8
```

**Comment by ballPointPenguin** [comment]
This might actually get solved by https://github.com/ember-cli/ember-cli/pull/6378

**Comment by nathanhammond** [comment]
Closed in favor of upstream report. Thanks for mentioning it!
