### ISSUE TITLE
Permissions Error while using Ember New

### ISSUE THREAD

**Issue by fshequin** [ember-cli/ember-cli#6413]
Getting this error when using the following command:

(OSX El Capitan)

$ ember new project-name

-------

Freds-iMac-3:Ember-Projects fred$ ember new fireapp
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Successfully initialized git.
Installed packages for tooling via npm.
Error creating new application. Removing generated directory `./fireapp`
EACCES: permission denied, rename '/var/folders/kc/398j08t55hg4stv5l1nmytsm0000gn/T/fred/bower/98e89bbbb4878ec0cc7833f0f91276c2-19799-wpYQno' -> '/Users/fred/.cache/bower/packages/d36604908a147dd7bd71998ae02f2cc0/2.9.1'
Error: EACCES: permission denied, rename '/var/folders/kc/398j08t55hg4stv5l1nmytsm0000gn/T/fred/bower/98e89bbbb4878ec0cc7833f0f91276c2-19799-wpYQno' -> '/Users/fred/.cache/bower/packages/d36604908a147dd7bd71998ae02f2cc0/2.9.1'
    at Error (native)

**Comment by fshequin** [comment]
Further to the above, **using sudo works**...

**Comment by nathanhammond** [comment]
You likely installed something with `sudo` (npm, Bower, other) and as a result your permissions for various places on the filesystem are borked. This is not an Ember CLI issue.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if the issue persists and somebody from the community will hopefully be able to help you through the process.
