### ISSUE TITLE
`ember install <package>` is installing a fixed version by default.

### ISSUE THREAD

**Issue by dafortin** [ember-cli/ember-cli#6414]
Hi guys,

We are currently working on an addon that will install a set of packages in a file [ember-cli-ecosystem-installer](https://github.com/ciena-blueplanet/ember-cli-ecosystem-installer ). 

The basic concept of that tool is the following:
1. You do an `ember install ember-cli-ecosystem-installer`
2. The tool willl prompt you with a list of packages to install and it will also check the packages installed
3. The user can choose packages
4. The tool will install/unistall all those packages

We noticed that even if we are requesting a version respecting semver format ember is installing a fixed version. For us it's very important to install the version requested and not a fixed version.

We are using `npm shrinkwrap` for other projects and it's working fine. 

Will it be possible to reopen this discussion and determine if it will be possible to have a better handling of semver version to get `~`, `^` and `>>=<<=` working?

Note: 
I also raised a related issue https://github.com/ember-cli/ember-cli/issues/6386
We did try to implement this, but even if we were setting the save exact to false we were still getting the exact version. There is no value submitting this if it's not working.

**Comment by sglanzer** [comment]
@dafortin can you verify that the inclusion of a semver range works with a normal `npm install`?

**Comment by sglanzer** [comment]
Also, which version of node / npm are you using?

**Comment by dafortin** [comment]
ember-cli: 2.8.0
http_parser: 2.6.2
node: 5.10.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g
os: darwin x64
3.8.3

**Comment by dafortin** [comment]
I did run a few npm install and it's not giving the results that I was expecting.

`npm install ember-frost-core@>=0.25.0 --save-dev`
package.json: `"ember-frost-core": "^0.32.1"`

`npm install ember-frost-core@'>=0.25.0 <=0.30.0' --save-dev`
package.json: `"ember-frost-core": "^0.30.0"`

`npm install ember-frost-core@~0.25.0 --save-dev`
package.json: `"ember-frost-core": "^0.25.7"`

**Comment by dafortin** [comment]
@sglanzer Do you think that ember should be able to keep the version with the `~`, `^` or a range?

**Comment by sglanzer** [comment]
I do, but it's interesting that npm doesn't respect it during installs either, feels odd to "fix" npm's behavior

**Comment by sglanzer** [comment]
Would you mind trying this against node 6 / 7 as well?

**Comment by dafortin** [comment]
@sglanzer I will.

**Comment by nathanhammond** [comment]
Node is not involved in this. `npm install` appears to pre-resolve semver ranges up to the current highest value and then (incorrectly on a few occasions given `ember-frost-core@'>=0.25.0 <=0.30.0'`) guess how you wish for the version number to drift.

`npm install ember-frost-core@'>=0.25.0 <=0.30.0'` => `"ember-frost-core": "^0.30.0"`
`ember install ember-frost-core@'>=0.25.0 <=0.30.0'` => `"ember-frost-core": "0.30.0"`

Please try to figure out why these do not produce the same behavior.

**Comment by dafortin** [comment]
Probably because of the `save-exact` attribute being set to `true` by default.

**Comment by sglanzer** [comment]
@dafortin let's confirm (sample repo?) - it seems though that without changes to npm (unless later versions have better support) that we'll be doing our own workaround to setting the ranges correctly on install

**Comment by dafortin** [comment]
As expected we are getting the same result with node `6.9`

**Comment by sglanzer** [comment]
Ok, so even if this is fixed in `ember-cli` (save-exact) we'll still run into the issue that we can't set the appropriate semver ranges on install.  So it looks like we'll need to continue with our workaround solution and possibly look into an issue against NPM

**Comment by dafortin** [comment]
Yes, that's right. I will check npm and try to figure out what is the expected behavior and why we are getting this weird behavior :)

**Comment by Turbo87** [comment]
> Probably because of the save-exact attribute being set to true by default.

@nathanhammond  indeed we are running `npm install` with `--save-exact` by default. I would argue though that we should align with NPM here and not use exact matches by default unless a `--save-exact` option is used for `ember install` as well.

**Comment by rwjblue** [comment]
We should rope @chadhietala in here too, as the submitter of the current behavior (in https://github.com/ember-cli/ember-cli/pull/2885). 

I suspect that `--save-exact` is more important in a `npm` world, but as we migrate more and more to `yarn` (and utilize its lockfile as we can) it will not make nearly as much of a difference (and possibly becomes a hinderance).

**Comment by chadhietala** [comment]
I think we can remove `--save-exact`. This was  introduced during a time pre-NPM 3.0.0 and pre-Yarn.

**Comment by stefanpenner** [comment]
I think @chadhietala is right, but regardless if a users provides `lib@someversion` we must be sure `someversion` is honored, so if a user specifies `^someversion` that is what they should ultimately see in package.json

**Comment by stefanpenner** [comment]
I suspect removing `--save-exact` is the easiest thing.
