### ISSUE TITLE
outputPaths not reflected in {{content-for "head"}} or {{content-for "body"}}

### ISSUE THREAD

**Issue by jboler** [ember-cli/ember-cli#6416]
When I add the `outputPaths` section to ember-cli-build.js the CSS & JS files are put in the specified directories but index.html doesn't reflect any of the changes and the app breaks.

I'm following: https://ember-cli.com/user-guide/#configuring-output-paths

Minimal test repo here: https://github.com/jboler/ember-assets-outputPath

ember-cli-build.js
```
/*jshint node:true*/
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
        outputPaths: {
            app: {
              html: 'index.html',
              css: {
                'app': '/assets/css/orglab.css'
              },
              js: '/assets/js/orglab.js'
            },
            vendor: {
              css: '/assets/css/vendor.css',
              js: '/assets/js/vendor.js'
            }
        },
  });
  return app.toTree();
};

```

resulting broken index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Assetstest</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="assetstest/config/environment" content="%7B%22modulePrefix%22%3A%22assetstest%22%2C%22environment%22%3A%22production%22%2C%22rootURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%2C%22EXTEND_PROTOTYPES%22%3A%7B%22Date%22%3Afalse%7D%7D%2C%22APP%22%3A%7B%22name%22%3A%22assetstest%22%2C%22version%22%3A%220.0.0+890c18a0%22%7D%2C%22exportApplicationGlobal%22%3Afalse%7D" />
    <link rel="stylesheet" href="/assets/vendor.css">
    <link rel="stylesheet" href="/assets/assetstest.css">
  </head>
  <body>
    <script src="/assets/vendor.js"></script>
    <script src="/assets/assetstest.js"></script>
  </body>
</html>
```

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.9.1
http_parser: 2.7.0
node: 4.6.1
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2j
os: linux x64
2.15.9
```

**Comment by nathanhammond** [comment]
@jboler That is correct, if you look at the [content inside of `index.html`](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/index.html#L12-L13) you'll see that we don't do anything particularly dynamic for inserting those asset paths. The `content-for` hooks do not generate those paths.

You'll need to manually update `index.html` and `tests/index.html` to use your specified paths.

I'm closing this as not an issue. In the future this is likely a better question for [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).
