### ISSUE TITLE
`addBowerPackages` is useless for some bower-packages as bower's programmatic API seems broken

### ISSUE THREAD

**Issue by fpauser** [ember-cli/ember-cli#6419]
Bower issue: https://github.com/bower/bower/issues/2387

This is a very annoying bower-bug which breaks the otherwise great 'ember-addon-user experience'. Maybe we can work around this by changing `addBowerPackagesToProject` to use bowers CLI interface?

**Comment by stefanpenner** [comment]
> to use bowers CLI interface?

I suspect it will be more constructive / good use of our time to address this upstream.

**Comment by locks** [comment]
Closing as the issue is no longer relevant due to the deprecation of Bower.
