### ISSUE TITLE
cleanup potentially broken on or after: UI.prototype.startProgress

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6422]
upstream issue: https://github.com/sindresorhus/ora/issues/27 which can break `process.on('SIGINT', ...)` by exiting before other handlers have run.

**Comment by stefanpenner** [comment]
Something we can do, to prevent other things from doing this to us. Is capturing `process.exit` ourselves very early, then replacing it with our own `exit` which first gracefully shuts-down before exiting.

**Comment by kellyselden** [comment]
We are locked on an older version of ora because of node 0.12. If there is a fix upstream, hopefully it backported to their 0.2.x release.

**Comment by stefanpenner** [comment]
> We are locked on an older version of ora because of node 0.12. If there is a fix upstream, hopefully it backported to their 0.2.x release.

It is actually unclear that ora can fix this, in all the cases that we need.

**Comment by stefanpenner** [comment]
I'm not sure cooperative `signal` trapping + exit + async cleanup is something any one library can do. I do believe though, we can control `exit` ourselves and accomplish the resilience we need:

Something like the following should be resilient:

```
var exit;
var handlers = [];
var RSVP = require('RSVP');

module.exports.captureExit = function() {
  exit = process.exit;

  process.exit = function(code) {
    var args = arguments;
    var work = handlers.splice(0, handlers.length);

    RSVP.map(work, function(handler) {
      return handler.apply(null, args);
    }).finally(function() {
      exit.apply(process, args);
    }).catch(function(error) {
      console.error(error);
      exit.apply(process, 1);
    })
  };
};

module.exports.onExit = function(cb) {
  handlers.push(cb);
};

module.exports.realExit = function() {
  exit.apply(process, arguments);
};
```

**Comment by stefanpenner** [comment]
the above code would be used in two places:

1. https://github.com/ember-cli/ember-cli/blob/master/lib/cli/index.js#L18 `captureExit`
2. https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L84-L92 `onExit`

**Comment by stefanpenner** [comment]
module that implements the above idea, but tested: https://github.com/stefanpenner/capture-exit
