### ISSUE TITLE
Sorry, why we need bower.json? We can not use only package.json?

### ISSUE THREAD

**Issue by mrkongo** [ember-cli/ember-cli#6426]
I'm wondering why every new project with ember-cli have two package manager products:

package.json (NPM) and bower.json (BOWER).

Why we need both?

We can't use package.json with npm alone, for everything?

Sorry, I'm newbie.

-------------------
Output from `ember version --verbose && npm --version`:
```
WARNING: Node v7.1.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
ember-cli: 2.9.1
http_parser: 2.7.0
node: 7.1.0
v8: 5.4.500.36
uv: 1.10.0
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: win32 x64
3.10.9
```
**Windows 10 x64**

**Comment by nathanhammond** [comment]
This isn't an issue. We currently provide Ember and jQuery via Bower.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if you want to discuss what's going on!
