### ISSUE TITLE
Build/Serve changes are not detected for app.import files that have outputFile option

### ISSUE THREAD

**Issue by terryroe** [ember-cli/ember-cli#6431]
I have a file under `vendor` like so:  `vendor/shared.js` and this line in `ember-cli-build.js`:
```
app.import('vendor/shared.js', { outputFile: 'assets/shared-ui.js' });
```
`ember b` and `ember s` output the file correctly, but changes to the file while using `ember s` or `ember b -w` are not detected for this file.

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.7.0
node: 6.6.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
3.10.3
```

**Comment by stefanpenner** [comment]
> but changes to the file

changes to `vendor/shared.js` ?

Can you provide a quick repository demonstrating this issue. That way we can quickly debug.

**Comment by terryroe** [comment]
@stefanpenner I don't have a public one handy.  I'll put one together and post back later.

**Comment by terryroe** [comment]
@stefanpenner Here is the [repo](https://github.com/terryroe/ember-cli-output-file) you asked for.  It's just a new ember project with the one file (`shared.js`) added.

**Comment by stefanpenner** [comment]
thanks

**Comment by stefanpenner** [comment]
> ember b and ember s output the file correctly, but changes to the file while using ember s or ember b -w are not detected for this file.

Alright, details so far:

* rebuild does not occur (e.g the file appears to not be watched)
* change is detected (rebuilding something else, catches this change)

**Comment by stefanpenner** [comment]
this appears to be a "feature" we explicitly don't watch `vendor` https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L213

**Comment by rwjblue** [comment]
`app.import`'ed files were manually watched via some bizarre hoop jumping (see https://github.com/ember-cli/ember-cli/pull/693 for background info), because in the early days (before watchman for example) watching a large number of files was very costly.

I suspect that we can use watchman status to just change that flag to watched if a decent (aka non-polling) watcher is being used...

**Comment by rwjblue** [comment]
> add the concept of per-file polling based watch?

This is a good idea regardless, but in this specific case I think we can just use a non-polling watcher feature detect...

**Comment by stefanpenner** [comment]
@rwjblue thats right, we did bower_components. But we never did the `vendor` side.

Labeling this as a bug

**Comment by terryroe** [comment]
@stefanpenner, @rwjblue Will this take a while to get fixed and into the stable version?  If so, can you think of a workaround I could use besides manually triggering a build after each edit of this type of file?  Thanks, tr

**Comment by rwjblue** [comment]
Manually providing the vendor tree should work.

```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    trees: {
      vendor: 'vendor'
    }
  });
  return app.toTree();
};
```

**Comment by terryroe** [comment]
Perfect!  Thanks so much @rwjblue!

**Comment by stefanpenner** [comment]
> @stefanpenner, @rwjblue Will this take a while to get fixed and into the stable version?

It shouldn't be to much work to fix, but unsure re: timeline.

**Comment by stefanpenner** [comment]
@terryroe thanks for reporting, this is now on our radar.

**Comment by terryroe** [comment]
@stefanpenner, My pleasure and thanks for your quick responses and attention.

**Comment by nathanhammond** [comment]
It seems like this underlying issue was because of syncing with `broccoli-bower` which pushed a ton of files into `vendor`. It doesn't appear that this is an issue anymore. As it stands the vendor folder is no longer the equivalent of `node_modules` or `bower_components`. So even in a polling world this is likely not as super-expensive as it used to be.

As such I'm in favor of simply turning watching back on for this directory. Thoughts?

**Comment by rwjblue** [comment]
Seems fine to me.

**Comment by stefanpenner** [comment]
i think we just need to do the same conditional as above: https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L211 

If watchman is present, go to town.

**Comment by nathanhammond** [comment]
@stefanpenner I'd rather just universally turn it on. I saw that conditional, but I just don't think we're in the same place we were with the `vendor` folder.

**Comment by stefanpenner** [comment]
> @stefanpenner I'd rather just universally turn it on. I saw that conditional, but I just don't think we're in the same place we were with the vendor folder.

ok, we can always walk it back if it turns out to be an issue.
