### ISSUE TITLE
Add `--no-welcome` option or similar to `new` & `init`

### ISSUE THREAD

**Issue by courajs** [ember-cli/ember-cli#6444]
While `ember-welcome-page` is great for first experience, the first thing I do after generating a new app is remove it. It would be nice to be able to not install it in the first place.

**Comment by nathanhammond** [comment]
@courajs Would you be willing to open a PR for this? It's something we would certainly entertain. Bonus points if you make it generically applicable to any dependency in the app's `package.json` file.

**Comment by courajs** [comment]
Happy to pick it up when I've got some free time!

**Comment by romulomachado** [comment]
@Turbo87 @nathanhammond I sent #6868, but it's not fully implemented. I need some help.

The way I thought to solve this was updating the blueprint to not have the `ember-welcome-page` dependency and `{{welcome-page}}` on application.hbs. If `--skip-welcome` isn't set, they'd be inserted back.

I tried using `insertIntoFile` with no success. Any tips on how to move forward?
