### ISSUE TITLE
Sorting inside of in-repo-addon generation.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6447]
[`ember g in-repo-addon` goes back and sorts paths for you.](https://github.com/ember-cli/ember-cli/blob/master/blueprints/in-repo-addon/index.js#L41)

We also do this in sorting of `package.json`. The ordering is therefore mega-implicit, but also (clearly) not likely to break most people.

Should we:
- Remove sorting?
- `ui.warn` that sorting has occurred?
- Other?

@ember-cli/core thoughts, go:

**Comment by stefanpenner** [comment]
> Remove sorting?

this seems reasonable to me
