### ISSUE TITLE
Don't set license in app's package.json

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6470]
RE: https://github.com/ember-cli/ember-cli/pull/6469

/cc @Turbo87 @kellyselden

**Comment by Turbo87** [comment]
This should be communicated in the release blog post. We can't just relicense existing projects...

**Comment by nathanhammond** [comment]
People should be reviewing the diff (especially of `package.json`) when they upgrade, but agreed.

**Comment by stefanpenner** [comment]
It's unclear if we want to change this:

* encouraging OSS as a default is fine
* It's a default, but people can easily be changed post generation
* If code from a company is being made available, it should be audited for legal reasons regardless. This would then be adjusted.
* It is not our place to decide that no license is better or worse for any given entity. 
* blueprint churn isn't fun
* If a company is a stickler for the these sorts of things, we may want to enable a global license config via ~/.emberc `{ defaultLicense: '...' }` for all projects generated.

**Comment by Turbo87** [comment]
> blueprint churn isn't fun

I agree with that. On the other hand though we are being a bit inconsistent in the `app` blueprint with the `package.json` file mentioning a license, but the LICENSE file missing from the repository. Not sure what we can do here...

**Comment by Turbo87** [comment]
maybe something like "if license in package.json is MIT then create MIT license file in project"?

**Comment by nathanhammond** [comment]
`ember g license <license-type>`? Makes it relatively straightforward to toggle off and on, simple to chain to a previous blueprint, provides a choke point for the configuration. And then we can start to make it configurable.

Slightly odd `ember d license` invocation: it doesn't matter what the type so it doesn't have to be parallel with the `generate` command.

**Comment by stefanpenner** [comment]
this seems like it needs to be fleshed out, RFC is most likely appropriate.
