### ISSUE TITLE
Test runner is broken

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6486]
#6437 caused our test runner to always exit with code `0` which caused the CI services to not report failed builds as such anymore. #6485 is a possible solution to this.

/cc @rwjblue @nathanhammond

**Comment by Turbo87** [comment]
from Slack:


tbieniek [15:11]  
@rwjblue https://github.com/ember-cli/ember-cli/pull/6485

rwjblue [15:12]  
@tbieniek doesn't this signify a larger issue WRT `capture-exit`? (edited)

tbieniek [15:13]  
to be honest: I'm not sure

[15:13]  
there is so much redirection going on I kinda lost track

rwjblue [15:14]  
I am assuming that https://github.com/stefanpenner/capture-exit/blob/master/index.js#L59 needs be used in our runner instead of `proccess.on('exit'`

tbieniek [15:14]  
I don't quite understand why `process.on('exit'` was used at all

[15:14]  
it doesn't make much sense to me

rwjblue [15:14]  
because the process exits naturally

tbieniek [15:15]  
@rwjblue and why not exit right away?

rwjblue [15:15]  
it does exit right away

[15:15]  
oh, you mean why use `on('exit'` instead of `process.exit(`? (edited)

tbieniek [15:16]  
no, I meant: why not call `process.exit()` right when mocha is finished

[15:16]  
yeah

rwjblue [15:16]  
because async things are still possibly running

[15:16]  
e.g. the very cleanup that capture-exit addresses

tbieniek [15:18]  
doesn't work with `onExit()`

rwjblue [15:19]  
yeah, seems like capture-exit isn't handling all cases

[15:19]  
need @hjdivad and/or @stefanpenner to think on it

[15:20]  
I'm not sure why you need to releaseExit in your PR though

tbieniek [15:22]  
because `lib/model/builder` registers itself with `onExit` and once that handler is called `this.ui` is `undefined` and we're throwing exceptions

**Comment by Turbo87** [comment]
@ember-cli/core we should not merge anything into `master` until this issue is solved!

**Comment by rwjblue** [comment]
The immediate issue with the test runner was worked around by @Turbo87 in https://github.com/ember-cli/ember-cli/pull/6485, and is pending merge/release in https://github.com/stefanpenner/capture-exit/issues/7.

A number of identified failures were tracked down and fixed, some PR's were: https://github.com/ember-cli/ember-cli/pull/6485, https://github.com/ember-cli/ember-cli/issues/6489, https://github.com/ember-cli/ember-cli/pull/6499, https://github.com/ember-cli/ember-cli/pull/6494, https://github.com/ember-cli/ember-cli/pull/6491, and https://github.com/ember-cli/ember-cli/pull/6484 (maybe more though).

At this point, CI is properly indicating a pass/fail of tests.  I am going to close this issue (though we still need to update capture-exit and modify what was done in https://github.com/ember-cli/ember-cli/pull/6485 when https://github.com/stefanpenner/capture-exit/issues/7 is released).
