### ISSUE TITLE
How to use stylus/nib with new app.import syntax

### ISSUE THREAD

**Issue by rickharrison** [ember-cli/ember-cli#650]
With v0.0.25, I was able to use https://github.com/visionmedia/nib just by installing it with bower. However, with the removal of broccoli-bower, it is unclear to me how to include this during the build process. I've tried a few different app.import statements, but I can't get my project to build with 0.0.27.

Any advice on how to configure the new brocfile to support this would really help.

**Comment by DiegeticShadow** [comment]
FYI, this is what worked for me:
```bash
bower install --save-dev nib
```
and then:
```styl
@import 'bower_components/nib'
```

**Comment by bnetter** [comment]
What I did:
```js
npm install nib --save
```

Then in your `ember-cli-build.js`:
```js
var nib = require('nib');

[...]
  var app = new EmberApp(defaults, {
    // Add options here

    stylusOptions: {
      use: [nib()],
      inputFile: 'style.styl',
      outputFile: 'style.css'
    }
  }
```
