### ISSUE TITLE
We `preprocessTree('css')` twice.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6512]
[This should not be invoked twice](https://github.com/ember-cli/ember-cli/blob/2ef05f887c2ff0c165c37bcf54cafa8f36f56cfe/lib/broccoli/ember-app.js#L1355-L1358), it only receives the concat'd `vendor.css` file (/`outputFile`):

[Introduced here, accidentally.](https://github.com/ember-cli/ember-cli/commit/c023badb7a0afe786931f686798e83dea90344d7#diff-392bb207fea8bcbeb4a084bb445f7cc7R1027)

**Comment by stefanpenner** [comment]
hmm, likely causing some fun perf issues...

**Comment by nathanhammond** [comment]
Note that fixing this is _super_ dangerous and likely a "breaking" bugfix (@zackthehuman already relies on it for some of his work).

**Comment by stefanpenner** [comment]
> Note that fixing this is super dangerous and likely a "breaking" bugfix

Unfortunately, relying on such undefined behavior has this risk. Lets work with @zackthehuman to figure out a path forward for his work, while enabling the bugfix to move forward.

**Comment by nathanhammond** [comment]
The thing is I don't believe anybody _actively_ noticed that it was being invoked twice. Not even @zackthehuman. He just noticed that he had the assets that he needed when he reverse-engineered how that hook worked since we have poor documentation in this space.

I agree that this is a bug, but I feel like it requires absolutely no willful intent to misuse the API for somebody to have misused it.

**Comment by zackthehuman** [comment]
> Unfortunately, relying on such undefined behavior has this risk

It's not that my work relies on this as much as it works around it. `preprocessTree` is a public hook with [very generic documentation](https://ember-cli.com/api/classes/Addon.html#method_preprocessTree). Without searching through the ember-cli source and seeing how this worked I don't know how anybody could understand this hook or how to use it effectively.

I wish that I could contribute something to fix this but I lack the domain knowledge.

I feel like generally when I report bugs like this the answer I get is along the lines of "you're doing it wrong" or "you shouldn't rely on this", etc. This kind of pushback is not helpful, doesn't fix my issue, and doesn't encourage me to report future bugs -- I just find a way to work around them. I don't have to domain knowledge to fix the problem and submit a PR, so I do the next best thing and report the issue.

**Comment by mswanson** [comment]
I believe I am still seeing this bug in 3.13. Here is what my current system looks like
```
ember-cli: 3.13.1
node: 12.9.1
v8: 7.6.303.29-node.15
uv: 1.31.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.11.3
1.19.1
```
#### Reproduction Steps:
* `ember addon my-test-addon`
* add `addon/styles/my-test-addon.css`
* `ember s`

`vendor.css` includes all the styles in `addon/styles` twice.

Any advice on fixing this? I am less concerned if it only affects local addon development as long as I will not be shipping duplicated CSS to pass that use my addon.

**Comment by locks** [comment]
This is something that would be nice to actually fix if someone wants to give it a go.
