### ISSUE TITLE
http-proxy upgrade 1.15.2 -> 1.16.0 no longer passes all cookies

### ISSUE THREAD

**Issue by kriswill** [ember-cli/ember-cli#6519]
When proxying a local api server, several endpoints send back multiple set-cookie headers.  Previously, with http-proxy 1.15.2, it was properly receiving and proxying the set-cookie headers.  However, with the recent minor release of http-proxy 1.16.0, it no longer replicates all of the headers properly.

see: https://github.com/nodejitsu/node-http-proxy/issues/1101
---

Output from `ember version --verbose && npm --version`:
```
version: 1.13.15-stable-1-13-102c7b4703
node: 6.3.1
npm: 2.14.10
os: darwin x64

→ npm --version
3.10.3
```

**Comment by stefanpenner** [comment]
thats for reporting, for now we will treat this as a dependency issue. If it doesn't look like it will be addressed, we may consider rollback from our side.

**Comment by kriswill** [comment]
I opened a PR https://github.com/nodejitsu/node-http-proxy/pull/1102 that should fix it.

**Comment by kriswill** [comment]
@stefanpenner 1.16.1 is up with the fix!

**Comment by stefanpenner** [comment]
@kriswill nice!
