### ISSUE TITLE
eslint tracking issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6550]
@Turbo87 can you fill this out?

**Comment by Turbo87** [comment]
@stefanpenner not sure what this is. The transition to eslint is essentially finished. The only thing that is not done is getting the ember.js repo on eslint.

**Comment by Turbo87** [comment]
I had https://github.com/ember-cli/ember-cli/issues/6501 as a tracking issue for a short amount of time
