### ISSUE TITLE
broccoli 1.0

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6551]
- [ ] fix popular plugins that require `tmp` directory in project
  - [ ] ember-browserify
  - [ ] broccoli-watchify 
  - [ ] ?

- [ ] broccoli 1.0 must support mid-build cleanups: https://github.com/broccolijs/broccoli/pull/312
- [ ] unify
  - [ ] broccoli-middleware
  - [ ] broccoli-builder
  - [ ] watcher?

**Comment by Turbo87** [comment]
@oligriffiths can we close this or is it still relevant?

**Comment by locks** [comment]
We are on broccoli 3 👀
