### ISSUE TITLE
Fix up test issues

### ISSUE THREAD

**Issue by hjdivad** [ember-cli/ember-cli#6565]
Various Test issues that we've noticed

- `retries: 2` can cause the wrong assertions to be displayed, eg it breaks caching (like warn first time kinds of assertions)
- yuidoc run and parsed at test-eval time instead of `beforeEach`; this slows down tdd for other tests by several seconds

cc @rwjblue

**Comment by hjdivad** [comment]
Also a mock addon discovery seems like a good for new contributors test cleanup

**Comment by nathanhammond** [comment]
@hjdivad 
- For TDD I tend to `mocha path/to/test.js`
- I'm unsure why we have retries at all? I've noticed, but I feel like they're trolling us more than they're helping us.

**Comment by stefanpenner** [comment]
> For TDD I tend to mocha path/to/test.js

the following also works: 

```sh
node tests/runner.js path/to/test
```

**Comment by rwjblue** [comment]
@stefanpenner - Yes, but that doesn't bypass the issues described in this issue.

**Comment by stefanpenner** [comment]
> @stefanpenner - Yes, but that doesn't bypass the issues described in this issue.

ya, but it totally could/should be made to.

One reason why there is a custom runner, is ensuring cleanup/teardown and test runs are identical regarless cross platform (and independent of the shell executing... looking at `cmd.exe`)

**Comment by rwjblue** [comment]
@stefanpenner - Exactly! That is why we want to fix this issue 😜

**Comment by hjdivad** [comment]
@nathanhammond 

> I'm unsure why we have retries at all? I've noticed, but I feel like they're trolling us more than they're helping us.

that's one of the chief motivations for fixing it ^_^

**Comment by Turbo87** [comment]
FWIW the `retries: 2` was introduced in https://github.com/ember-cli/ember-cli/pull/5712

**Comment by locks** [comment]
Closing as no longer relevant.
