### ISSUE TITLE
Tests fail in Circle due to LESS compilation

### ISSUE THREAD

**Issue by morgan** [ember-cli/ember-cli#6568]
Experiencing an issue running tests in Circle. Traced it down to LESS compilation. We are importing large less files which have compiled and worked across multiple versions of Ember CLI.

Ember CLI out-of-the-box passing:

https://github.com/caxiam/ember-cli-less-fail
https://circleci.com/gh/caxiam/ember-cli-less-fail/3

Branch with subset creating failure:

https://github.com/caxiam/ember-cli-less-fail/compare/example-less-failure
https://circleci.com/gh/caxiam/ember-cli-less-fail/4

Opened this issue here because the last `ember-cli-less` release was over a year ago.

Please let me know if this is more appropriately opened elsewhere.

Thank you!

**Comment by nathanhammond** [comment]
@morgan This is likely an issue in `ember-cli-less` which is not maintained or supported by the Ember CLI team. I'd suggest investigating the actual error messages that are being reported in the browser, locally, not on CI:

> SyntaxError: Functions cannot be declared in a nested block in strict mode at http://localhost:7357/assets/vendor.js, line 70269

Also, does it fail when you remove the admin theme?

I'm closing this issue as likely not an Ember CLI bug. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-help](https://embercommunity.slack.com/messages/-help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) for help in tracking down what's going on.

**Comment by morgan** [comment]
@nathanhammond I will open it there.

The error messages vary. Tricky to debug. Always seems to lead to something unrelated.

The build does succeed commenting out the theme. Reason this seems fishy is because we have dozens of implementations referencing the theme in this fashion across multiple versions of Ember spanning years. So, it very likely is the add-on.
