### ISSUE TITLE
Implement a BroccoliInstrumentationNode

### ISSUE THREAD

**Issue by hjdivad** [ember-cli/ember-cli#6569]
In some cases we want to add heimdall nodes around certain broccoli nodes, to improve analytics.  There's a couple of different ways to do this in principle, but a straightforward one would be for there to be a primitive in the system that is reasonably close to a broccoli "no-op" node.

We would wrap this in the case where we drop the merge trees node in `treeFor` here: https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/merge-trees.js#L41-L42

**Comment by hjdivad** [comment]
cc @stefanpenner @rwjblue

**Comment by stefanpenner** [comment]
@hjdivad this may be quite useful. Basically some what of group "periods of the build" for instrumentation reasons?

**Comment by hjdivad** [comment]
I'll close this as stale.  I think it's still clearly useful, although that would be the case much more if we invested in improving the query tooling.
