### ISSUE TITLE
`beforeRun` docs/return value

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#6572]
It seems like our docs say that [`beforeRun`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/command.js#L180-L188) says that it returns `Promise` or `null` which is not true.

changing docs is easy but should it actually force return value to be `Promise`? there's only [one place](https://github.com/ember-cli/ember-cli/blob/8c7a523b4e0a4b81083294631ee3c2687cad3c3b/lib/cli/cli.js#L126) that I found where we use it in cli.

**Comment by rwjblue** [comment]
Ya, we should allow it to return a promise.

Seems like [this](https://github.com/ember-cli/ember-cli/blob/8c7a523b4e0a4b81083294631ee3c2687cad3c3b/lib/cli/cli.js#L126-L128) could be changed to something like:

```js
return Promise.resolve()
  .then(function() {
    return command.beforeRun(commandArgs);
  })
  // the rest of the pre-existing promise chain
  // https://github.com/ember-cli/ember-cli/blob/8c7a523b4e0a4b81083294631ee3c2687cad3c3b/lib/cli/cli.js#L128-L158
```

**Comment by locks** [comment]
I believe this has been addressed in the mean time!
