### ISSUE TITLE
Deploy ember-cli.com/api from release branch only.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6585]
We need to tweak the auto deploy script for `ember-cli.com/api` generation to only run for the `release` branch.  Currently, landing anything on master shows up there immediately even though it may not be usable until it releases as stable.

I _believe_ that we would only need to change [this line](https://github.com/ember-cli/ember-cli/blob/master/.travis/deploy.sh#L10), but @Turbo87 can likely confirm...

**Comment by Turbo87** [comment]
@rwjblue yeah, that should work fine
