### ISSUE TITLE
Prompts during blueprint install appear to freeze the process

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6593]
Examples:

- https://github.com/ember-cli/ember-cli-mocha/issues/159
- https://github.com/cibernox/ember-power-select/issues/752

This was apparently introduced by the upgrade to NPM@3 which no longer properly clears the console after it's done installing. Essentially what happens is that `inquirer` outputs its prompt and then some leftover NPM handler decides that it still has some stuff in the buffer and overwrites the prompt. Pressing <kbd>Enter</kbd> will continue the process as a workaround but this is obviously bad UX/DX.

Potential solution: Backport https://github.com/ember-cli/ember-cli/pull/6525 / https://github.com/ember-cli/ember-cli/pull/6503 for v2.10.x

/cc @stefanpenner @rwjblue @nathanhammond

**Comment by stefanpenner** [comment]
@Turbo87 does the sub-process move for NPM mitigate this issue?

**Comment by Turbo87** [comment]
@stefanpenner yes

**Comment by Turbo87** [comment]
@nathanhammond @stefanpenner do we care that this is still broken on v2.10 or should people just use v2.11 once it's available?

**Comment by stefanpenner** [comment]
> @nathanhammond @stefanpenner do we care that this is still broken on v2.10 or should people just use v2.11 once it's available?

If you have cycles to backport sure, if not 2.11 isn't to far off.
