### ISSUE TITLE
Option to disable minification of specific files in the "public" folder

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6594]
I'm running Ember CLI v2.10 in a project that includes https://github.com/AnalyticalGraphicsInc/cesium vendored in the `public` folder. During the production build I'm seeing:

```
[WARN] `cesium/Cesium.js` took: 57198ms (more than 20,000ms)
```

which indicates that Ember CLI is trying to minify the `Cesium.js` file which is already minified. This seems like a lot of wasted time and I'm wondering if minifying files in `public` is in fact intended behavior.

/cc @stefanpenner @rwjblue

**Comment by rwjblue** [comment]
Based on the way we minify in `postprocessTree` ([see here](https://github.com/ember-cli/ember-cli-uglify/blob/master/index.js#L11-L19)) we have lost track of what was in `treeForPublic` and what is from the app/addons/etc.  

I suspect that this type of post-processing should actually be done for all files (i.e. the current behavior is correct), but we may want to make it possible to opt-out on a per-file basis (specifically for your scenario).

**Comment by les2** [comment]
Going to make an attempt at this one for Ember Conf 2017 Contributors workshop.

**Comment by les2** [comment]
@rwjblue I think you can exclude a file from minification as documented in the guide: https://ember-cli.com/user-guide/#exclude-from-minification

```
  var app = new EmberApp(defaults, {
    minifyJS: {
      options: {
        exclude: ["**/some-file.js"] // <--- this will match a file in `public`
      }
    }
  });
```

```
$ ember --version
ember-cli: 2.12.1
node: 6.9.4
os: darwin x64
```

is anything required for this issue, @Turbo87 ?

**Comment by les2** [comment]
@Turbo87 Added PR to exclude Cesium from being minified here: https://github.com/skylines-project/skylines/pull/632
