### ISSUE TITLE
CLI hanging on all commands

### ISSUE THREAD

**Issue by adamlc** [ember-cli/ember-cli#6597]
Hey guys, I've been having issues with Ember CLI. When in a project ember cli will just hang on all commands, even ```ember version``` etc.  

I've tried multiple ember projects and it hangs in all of them, it even hangs when I'm not in an ember project folder! I've tried upgraded, downgrading node, npm and cli with no success! Is there anything I can do to debug where its hanging? Based on the package.json for my global npm I'm on cli version 2.8.0, but I have tried multiple versions.

```
$ npm --version
3.10.9
$ node -v
v7.2.1
```

**Comment by stefanpenner** [comment]
@adamlc what OS?

Does it still hang with `--disable-analytics` flag set?

**Comment by adamlc** [comment]
@stefanpenner sorry should have said, I'm on OSX El Cap (10.11.4).

I have tried adding that but I get the following:
```
The option '--disable-analytics' is not registered with the version command. Run `ember version --help` for a list of supported options.
```

I've tried a few different commands, I get the same message and then it hangs afterwards. Its odd because my team all uses similar setups and version and their setups are all fine!

**Comment by stefanpenner** [comment]
try:

`DEBUG=* ember v`

it will likely provide a very large output, if you can share the output via a gist. That would be lovely.

**Comment by nightire** [comment]
@adamlc Been there before like 2 months ago, one possible issue could be an old version watchman, try to upgrade it or even remove it completely to confirm this.

**Comment by adamlc** [comment]
Heres the[Gist](https://gist.github.com/adamlc/dd45b17a2268e5f0a9fb5354d73fddbb), weirdly the last thing in there is something about Watchman. I'm on the latest version, I also tried reinstalling etc, no luck :(

```
$ watchman -v
4.7.0
```

**Comment by adamlc** [comment]
Pretty sure its watchman, removing it and falling back to node-watcher works:

```shell
$ ember v
WARNING: Node v7.2.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.8.0
node: 7.2.1
os: darwin x64
```

**Comment by stefanpenner** [comment]
Sounds like a watchman issue: https://github.com/facebook/watchman/issues/358 let me know of @wez's instruction in that last comment help.

**Comment by adamlc** [comment]
@stefanpenner I can confirm that works! Many thanks for everyone's detective work 😀  🎄

**Comment by adamlc** [comment]
I've closed this but realised that it may need some sort of timeout in Ember CLI to stop something like this blocking CLI

**Comment by stefanpenner** [comment]
@adamlc https://github.com/amasad/sane/issues/81
