### ISSUE TITLE
Lost assertion when `rootURL` does not end in `/`.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6599]
When we used `baseURL` we enforced that it end with `/` (for correctness sake and so that concatenations could always assume the `/` was there instead of checking).

I believe we should carry over that assertion for `rootURL`, any objections?

**Comment by nathanhammond** [comment]
We actively allow `rootURL` to be empty string per: https://github.com/ember-cli/ember-cli/pull/6182

Did you actually encounter a problem with this? I'm pretty sure that we use [`clean-base-url`](https://github.com/ember-cli/clean-base-url) everywhere for this...

**Comment by rwjblue** [comment]
Yes, specifying `ENV.rootURL = '/foo';` is definitely allowed at the moment.

**Comment by rwjblue** [comment]
I guess you are saying that we manually just postfix `/` as needed and anything that is assuming a simple `config.rootURL + 'some/other/thing/'` must also replicate `clean-base-url`'s logic?

**Comment by nathanhammond** [comment]
We do that manually in Ember CLI, I'm pretty sure that all built-in runtime code also does the right thing [when presented a non-trailing-slash `rootURL` here](https://github.com/ember-cli/ember-cli/blob/9e674547c82fa6747895e2b5b7f6a53e73d0226f/blueprints/app/files/app/router.js#L6).

Given that you've said `config.rootURL` I'm guessing that you're encountering an issue in runtime code?

**Comment by rwjblue** [comment]
Ya, in my case it was basically using fetch to grab dynamically generated assets (and needing it to work with a different rootURL + hash location due to gh-pages deploy). So I was concatting the rootURL and path segment manually. 

It's totally possible to do this with some sort of relative path too. I'm basically just looking for someone else to blame for my typo 😜

**Comment by nathanhammond** [comment]
Final thoughts on the matter captured here: https://github.com/ember-cli/ember-cli/pull/6600#issue-197083368
