### ISSUE TITLE
app.import will happily include the same file multiple times

### ISSUE THREAD

**Issue by dfreeman** [ember-cli/ember-cli#6601]
If `app.import` is called on the same path multiple times, the file at that path will be concatenated into the final output once per call. I chatted briefly with @rwjblue about this in Slack and neither of us could come up with a real-world scenario where that would be desirable.

The most likely way for this to occur today is when two instances of an addon import the same library. Fun fact: if you have two different versions of that addon installed, you end up with two copies of _one version_ of the library (which clobbered the other when their `vendor` trees merged), which definitely isn't making anyone happy 😉 

I should have time in the next day or two to take a stab at fixing this, but wanted to open this to track in the meantime.

**Comment by stefanpenner** [comment]
oh the fun with nested add-ons :P.
