### ISSUE TITLE
Using another environment than development || production breaks ember build

### ISSUE THREAD

**Issue by frekw** [ember-cli/ember-cli#662]
It just throw the following error `You must pass a file to`EmberApp::import`. For directories specify them to the constructor under the`trees`option.` when using `ember build --environment=staging`.

My guess is that the [following line](https://github.com/stefanpenner/ember-cli/blob/master/lib/broccoli/ember-app.js#L63) is the culprit since it only adds `development`  and `production`.

**Comment by QuantumInformation** [comment]
Is there a way to have a staging build mimic the settings for production?
