### ISSUE TITLE
Incorrect ember warning

### ISSUE THREAD

**Issue by StevenInc** [ember-cli/ember-cli#6635]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---
I ran ember update
and the following warning shows up:
Future versions of Ember CLI will not support v6.9.2. Please update to Node 0.12 or io.js.

This doesn't make sense.

**Comment by stefanpenner** [comment]
`ember update` isn't a command we have any longer, so if you are able to run it you likely have an old version of `ember-cli` and running it may not produce the results you want.

To upgrade an app, please see the [Upgrading section of the website](https://ember-cli.com/user-guide/#upgrading)

If those steps are followed I suspect everything will work. As the warning you describe was fix quite some time ago.
