### ISSUE TITLE
[ERGONOMICS] ember delete should cleanup directories if they are empty

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#6648]
Scenario:

ember g some-blueprint
then 
ember d some-blueprint

Depending on what the generator or blueprint is doing there can be situation where all the files are deleted but empty directories are left hanging around. The generate command created them but the delete command does not clean them up.

The delete command should clean up the related directories if they are truly empty of contents.

The reason this is important is because broccoli and ember CLI can start spewing cryptic errors if you have some empty directories in certain parts of your project.

Or else ember cli and broccoli need to be more fault tolerant of empty directories.

Error messages like this can be really confusing
(another nice to have would be broccoli telling me what directory it was choking on)
```
The Broccoli Plugin: [object Object] failed with:
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
... snip ...
The broccoli plugin was instantiated at:
undefined
```

---

Output from `ember version --verbose && npm --version`:
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.9.0-beta.1
http_parser: 2.7.0
node: 6.8.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.8
```

**Comment by kellyselden** [comment]
This was added in 2.10.0 #6241
