### ISSUE TITLE
Change `EmberApp#tests` visibility to public

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6656]
The `tests` property of `EmberApp` instances is currently not documented properly and should IMHO be a public property.

[`ember-cli-chai`](https://github.com/ember-cli/ember-cli-chai/blob/master/index.js#L119-L123) is one example of an addon that uses this flag already.

/cc @stefanpenner @rwjblue @nathanhammond

**Comment by rwjblue** [comment]
I agree whole heartedly that we should expose what this flag means, but would generally prefer to give it a better name (and deprecate this one) before officially making it public. I'm thinking of something like `app.includesTests`, `app.hasTests`, etc...
