### ISSUE TITLE
`this` context in `setupPreprocessorRegistry()` is wrong

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6657]
When you implement the `setupPreprocessorRegistry()` method in an addon you'd expect `this` to be the `Addon` instance, but instead it seems to be the `EmberApp` instance. You can check this by comparing `this === registry.app`, with `registry` being the second parameter being passed to that method.

/cc @rwjblue @stefanpenner @nathanhammond

**Comment by Turbo87** [comment]
Interestingly this is only true for the first invocation of the `setupPreprocessorRegistry()` method (where the first parameter is `self`), but in the second invocation (where the first parameter is `parent`) they don't seem to match.

**Comment by rwjblue** [comment]
After a quick review it seems that both are being invoked in a way that should result in correct `this`:

* https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/master/preprocessors.js#L44
* https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/master/preprocessors.js#L27

**Comment by rwjblue** [comment]
Not sure what is going on, can you describe the steps needed to reproduce?

**Comment by Turbo87** [comment]
I've noticed this in the [ember-test-selectors](https://github.com/simplabs/ember-test-selectors) addon.

- clone the addon above
- checkout 238da866cc88
- put a breakpoint into the `setupPreprocessorRegistry()` method
- run `ember test`

**Comment by Turbo87** [comment]
@rwjblue were you able to reproduce this?

**Comment by Turbo87** [comment]
I've tried to reproduce this again, but it seems like I was a little confused when I opened the issue. `this` is actually the same in both runs of the function but `registry.app` differs.
