### ISSUE TITLE
Linting tests should run on the app directory 

### ISSUE THREAD

**Issue by kiwiupover** [ember-cli/ember-cli#6667]
Moving this issue to ember-cli 

https://github.com/ember-fastboot/ember-cli-fastboot/issues/307

@rwjblue can you point me in the right directions to and I will open a PR 

cheers
Dave

**Comment by Turbo87** [comment]
duplicate of #5839

**Comment by rwjblue** [comment]
Fixed by #7037 which was rebased / tweaked / landed in #7378.
