### ISSUE TITLE
insertIntoFile isn’t working for ember-cli-mirage

### ISSUE THREAD

**Issue by backspace** [ember-cli/ember-cli#6672]
Hello! Much appreciation from me for Ember CLI, as always.

I noticed when starting a new Ember CLI application recently that `ember install ember-cli-mirage` failed to insert the relevant lines in `.jshintrc` and `tests/.jshintrc`. You can see an issue about this [here](https://github.com/samselikoff/ember-cli-mirage/issues/953). It was trivial for me to fix because I’m familiar with a lot of what’s happening in Ember CLI applications, but it’s concerning to me because the guides have people installing Mirage, and this unexpected error could be confusing for newcomers.

In [this Travis log](https://travis-ci.org/backspace/insertIntoFile#L1278), you can see that after `ember install ember-cli-mirage`, the JSHint files haven’t changed.

As [pointed out by @imhuytq](https://github.com/samselikoff/ember-cli-mirage/issues/953#issuecomment-272071503), the underlying issue looks like it’s with `fs.exists`. I added some `console.log` statements and things looked as expected, but on [this line](https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/output/index.js#L12), the callback is never getting called, not even with a false value for `itDoes`.

I gather that JSHint is going away, but this also affects [this use of `insertIntoFile`](https://github.com/samselikoff/ember-cli-mirage/blob/24f994f4419f1b175c82331b00c3089e3f65c038/blueprints/ember-cli-mirage/index.js#L41-L44).

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.8
```

**Comment by nathanhammond** [comment]
@backspace I trust you! Implying that a bug exists in `fs-extra` in a file that hasn't been modified since 2015 is an extraordinary claim. 😜 I'm much more likely to believe that we're screwing something up.

Can reproduce, attaching a debugger now...

**Comment by kennyadsl** [comment]
I can confirm this is happening to me as well. I installed `ember-cli-mirage` yesterday.

To fix the issue I had to manually add `"server"` to the `predef` list in both `.jshintrc` and `tests/.jshintrc`. 
Also, I had to add this line into `tests/helpers/destroy-app.js`, after `Ember.run(application, 'destroy');`:

```
server.shutdown();
```

to avoid the following warning:

```
        Log: |
            { type: 'warn',
              text: '\'You created a second Pretender instance while there was already one running. Running two Pretender servers at once will lead to unexpected results and will be removed entirely in a future major version.Please call .shutdown() on your instances when you no longer need them to respond.\'\n' }
```

**Comment by stefanpenner** [comment]
Just took abit of a deep dive, and this doesn’t appear to be an issue with ember-cli rather ember-cli-mirage.

`Blueprint.prototype.insertIntoFile` is documented as async and returning a promise.
https://ember-cli.com/api/classes/Blueprint.html#method_insertIntoFile

The issue as described, is actually race between the process exiting and the async `insertIntoFile` completing.

Although the API docs are correct, the example is somewhat misleading. As it does not include the implied `then` after the call. 

Its worth noting, I would be totally on-board with someone adding `insertIntoFileSync`

**Comment by stefanpenner** [comment]
Let me update the guide example

**Comment by nathanhammond** [comment]
I don't _believe_ that this is a race. It literally does not work in a debugging REPL.

**Comment by stefanpenner** [comment]
Submitted a fix to ember-cli-mirage: https://github.com/samselikoff/ember-cli-mirage/pull/984 npm link of that resolve the problem.

**Comment by backspace** [comment]
Thanks for looking into this!
