### ISSUE TITLE
Not doing double-transpile makes writing tooling unhappy.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6687]
So, we did this: https://github.com/ember-cli/ember-cli/pull/6530

Then we noticed this: https://github.com/ember-engines/ember-engines/issues/318

There are possibly a lot of things which rely on their own addons still being ES6 when they're operating on their trees. We should probably partially unwind #6530 and figure out if there is maybe a faster ES6 => AMD transformer.

**Comment by stefanpenner** [comment]
It is unclear that this is a blocker, but we should discuss.

IMHO the feature this is affecting is an experimental (and problematic) feature on an unstable add-on.

**Comment by stefanpenner** [comment]
I am taking a look at the feature in question this evening.

**Comment by nathanhammond** [comment]
Regardless of who is consuming it we're pretty dramatically changing the expectation of all things being ES6 as long as possible. More thoughts here: https://github.com/ember-engines/ember-engines/issues/318#issuecomment-272793790

**Comment by stefanpenner** [comment]
https://github.com/ember-engines/broccoli-dependency-funnel/pull/18 should either fix, or get us close to supporting both AMD and ES6 module imports for the above phase.

**Comment by locks** [comment]
If I'm reading the related conversations correctly, this has been addressed!
