### ISSUE TITLE
build-perf guide needs to explain build vs rebuild

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6713]
and that all the docs provided work both in build and rebuild scenarios.

cc @asakusuma

**Comment by MonsieurDart** [comment]
Hey @stefanpenner! Is this issue still relevant? Can you elaborate a little bit? What exactly is "build-perf guide" the part of the Ember Guide explaining the build system?

**Comment by locks** [comment]
Closing as stale.
