### ISSUE TITLE
Build time regression in 2.12-beta immediately after install

### ISSUE THREAD

**Issue by carlbennettnz** [ember-cli/ember-cli#6714]
## Build times with `ember serve`

|Scenario|2.10|2.11|2.12 beta|
|-|-:|-:|-:|
|Fresh install|8633ms|8206ms|:warning: 32240ms|
|Without cache|44861ms|40381ms|32083ms|
|With cache|11241ms|7664ms|6111ms|

## Build times with `BROCCOLI_VIZ=1 ember serve`

|Scenario|2.10|2.11|2.12 beta|
|-|-:|-:|-:|
|Fresh install|24907ms ([viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/e3aa2f5cca27bb426983bfde7cdcc9b940b07153/ec-2-10-fresh-install.json))|23971ms ([viz](https://gist.github.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-11-fresh-install.json))|23437ms ([build viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-build-fresh-install.json), [init viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-init-fresh-install.json))|
|Without cache|47667ms ([viz](https://gist.github.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/e3aa2f5cca27bb426983bfde7cdcc9b940b07153/ec-2-10-without-cache.json))|47440ms ([viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-11-without-cache.json))|40053ms ([build viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-build-without-cache.json), [init viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-init-without-cache.json))|
|With cache|11456ms ([viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/e3aa2f5cca27bb426983bfde7cdcc9b940b07153/ec-2-10-with-cache.json))|10829ms ([viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-11-with-cache.json))|10979ms ([build viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-build-with-cache.json), [init viz](https://gist.githubusercontent.com/carlbennettnz/72c9609429d9227a80a799259c34d280/raw/b5311a6a32ae4aa85d92ea3f15fc7e2afe719082/ec-2-12-init-with-cache.json))|

## Method

* **Fresh install** means `npm i --save-dev ember-cli@version && ember serve` without removing any tmp directories.
* **Without cache** means removing tmp directories and then `ember serve`.
* **With cache** means just `ember serve` again after the without cache test.

For more details, see the [bash script](https://gist.github.com/carlbennettnz/d712605be4e7922d6bc956bc4d239630) and [full bash script output](https://gist.github.com/carlbennettnz/2e9b227d09474133f48c1a4a0fab3bf2). Tested on a mid-sized real-world app.

cc @stefanpenner @hjdivad

**Comment by rwjblue** [comment]
I'll  play with this a bit when I'm back at my computer, but after reviewing the times and briefly reviewing the script it seems that the main slowdown for "Fresh Install" could be explained by sharing less persistent cache across ember-cli versions. 

Both the "Without Cache" and "With Cache" numbers are better (by a decent amount) between 2.10/2.11 and 2.12 beta. 

---

I do want to make sure to thank you for putting together such a nicely detailed issue on this, it should make getting to the bottom of things much easier.

**Comment by stefanpenner** [comment]
@carlbennettnz what happens when you run `ember server` twice back 2 back using `2.12 beta`.

I also share @rwjblue suspicion, doing the above should inform us of this or not.

**Comment by carlbennettnz** [comment]
@rwjblue Yeah, the slowdown case is far more limited than I first thought. I only noticed because I was trying out a bunch of versions in succession.

@stefanpenner Immediately following an install, without deleting any tmp folders:

1. 34356ms
2. 7011ms
3. 6697ms

**Comment by stefanpenner** [comment]
> tmp folders:

Which tmp folders are you deleting?

> @rwjblue Yeah, the slowdown case is far more limited than I first thought.

Its still not 100% clear to me, that there is no persistent cache floating around making the above quicker. But that happen to be invalidated when bumping to the latest beta.

To compare, I would do the following once for each of the above versions:

```sh
cd <project-root>
git clean -fdx
yarn # or npm install
ember s
```

That should ensure all caches are evicted, as all files used to build the persistent cache keys will have changed.

**Comment by rwjblue** [comment]
> Which tmp folders are you deleting?

The [bash script they were running is here](https://gist.github.com/carlbennettnz/d712605be4e7922d6bc956bc4d239630).  The cache clearing being referenced is:

```sh
  rm -r tmp $TMPDIR/if-you-need-to-delete-this-open-an-issue-async-disk-cache/
```

**Comment by stefanpenner** [comment]
@rwjblue thanks

**Comment by locks** [comment]
Closing as no longer relevant. Thank you!
