### ISSUE TITLE
Remove .bowerrc file

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6722]
Our app/addon blueprints no longer contain a `bower.json` file starting with v2.12. Do we want to remove the `.bowerrc` file too?

/cc @ember-cli/core

**Comment by rwjblue** [comment]
@Turbo87 - Yes, when we bring back the `bower.json` dropping, we should also drop `.bowerrc`.

**Comment by kellyselden** [comment]
Can this be bundled into #6739 too?
