### ISSUE TITLE
Make project.require public?

### ISSUE THREAD

**Issue by asakusuma** [ember-cli/ember-cli#6733]
It would be nice if `project.require` was public. For instance, an addon might want to be able to create a new `Builder` instance; without having a prod dependency on `ember-cli`.
https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L284

cc @stefanpenner

**Comment by stefanpenner** [comment]
👍

**Comment by rwjblue** [comment]
Seems good to me also.

**Comment by rwjblue** [comment]
Fixed by #6737
