### ISSUE TITLE
Use ~ constraint for `ember-cli` in app/addon dependencies

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6738]
@ember-cli/core any thoughts on not pinning Ember CLI in the app/addon blueprint, but instead at least allowing patch updates?

**Comment by rwjblue** [comment]
Ya, seems fine to at least use ~.

**Comment by kellyselden** [comment]
My thoughts are I'm slightly to moderately against. I feel like all our blueprint files are tied to a specific patch release. When greenkeeper says 2.11.1 came out, that's my cue to look up all the blueprint changes, (say travis.yml was bugfixed, or our test-helpers need fixing), and submit the changes with the patch release. I feel like people would be more likely to miss out on those fixes with a floating ember-cli.

**Comment by Turbo87** [comment]
@rwjblue @kellyselden I propose to put this on the agenda for the CLI call this week

**Comment by kellyselden** [comment]
Added

**Comment by kellyselden** [comment]
This was discussed on the core meeting, and determined to be more good than bad.
good: getting bugfixes in ember-cli internal code
bad: potentially missing bugfixes in generated files

Anyone that sees this feel free to submit the fix.
