### ISSUE TITLE
ember install doesn't correctly update bower.json when using multiple addBowerPackageToProject calls in afterInstall hook in addon blueprint

### ISSUE THREAD

**Issue by eliasdawson** [ember-cli/ember-cli#6743]
I discovered a bug related to the afterInstall hook in the blueprint for an addon. If there are multiple addBowerPackageToProject calls, all dependencies will be installed, but only one will be added to bower.json. As a result, after installing an addon and committing the dependency update, another developer will not receive the required dependencies when working on a shared repository.

Using addBowerPackagesToProject, and adding them all in a single call does work as expected, but I would also expect separate individual calls to have the same behavior, and there can be use cases where calling them separately would be preferred.

I prepared a simple addon which attempts to add two bower dependencies to demonstrate the bug.

### Steps to reproduce:
```
ember new foo
cd foo
ember install https://github.com/eliasdawson/ember-cli-bower-bug-demo.git
ember g ember-cli-bower-bug-demo
```

### Expected:
lodash and moment are installed in bower_components and bower.json is updated to list both lodash and moment as dependencies.

### Actual:
Both dependencies are installed but only one is added to bower.json

This bug was discovered using ember-cli 2.5.0, but reproduced with 2.11.0

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.0
http_parser: 2.7.0
node: 6.9.5
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
```

**Comment by rwjblue** [comment]
Can you share the blueprint code in question?

**Comment by rwjblue** [comment]
Dangit, sorry about that, I didn't read close enough.  Looking at the repo now.

**Comment by eliasdawson** [comment]
No worries @rwjblue 

For clarity: Here is the sample blueprint: https://github.com/eliasdawson/ember-cli-bower-bug-demo/blob/master/blueprints/ember-cli-bower-bug-demo/index.js

**Comment by rwjblue** [comment]
I suspect that you need to modify to run them in series.  I also vaguely recall this coming up before (somewhat recently), maybe someone else on the team remembers.

Try changing from:

```js
  afterInstall: function(options) {
    return RSVP.all([
      this.addBowerPackageToProject('lodash'),
      this.addBowerPackageToProject('moment')
    ]);
  }
```

To:

```js
  afterInstall: function(options) {
     return this.addBowerPackageToProject('lodash')
       .then(() => this.addBowerPackageToProject('moment'));
    ]);
  }
```

**Comment by rwjblue** [comment]
Ahh, here is the issue I was referring to: https://github.com/bower/bower/issues/2267

**Comment by eliasdawson** [comment]
Thanks, @rwjblue 

You are correct. Installing multiple dependencies can be achieved by either chaining or using addBowerPackagesToProject. I am not blocked or having an issue; this just appears to be a bug that might cause confusion or frustration for others.

**Comment by rwjblue** [comment]
> If you run multiple bower.commands.install's in parallel the output of the last one to settle will write over the first settled install in the append line operation to bower.json

**Comment by eliasdawson** [comment]
Yep, that sure looks like the issue.

**Comment by rwjblue** [comment]
Final response by Bower team from https://github.com/bower/bower/issues/2267#issuecomment-220865257:

> bower doesn't support "merging" of bower.json. if you operate on single project, you need to run commands sequentially, or pass multiple arguments to install / uninstall multiple things

**Comment by rwjblue** [comment]
I agree that it seems super annoying and hard to debug for folks, but I'm not sure we can do much about it (other than continue to migrate away/off of bower)...

**Comment by rwjblue** [comment]
crosslinking https://github.com/ember-cli/ember-cli/issues/5765 for completeness sake

**Comment by kellyselden** [comment]
We could use a semaphore internally to queue them up for you, but that is too much infrastructure for something we're moving away from...

**Comment by rwjblue** [comment]
Yea, I think a hacky but effective solution might be to do something like:

```js
let CURRENT_RUNNING_BOWER_INSTALL = false;

// ...snip...
  run(options) {
    if (CURRENTLY_RUNNING_BOWER_INSTALL) {
      throw new SilentError('Bower does not allow multiple concurrent operations, please refactor the installation to use `Blueprint#addBowerPackagesToProject` or perform operations in series');
    }

    CURRENTLY_RUNNING_BOWER_INSTALL = true;
    // ...snip.. return ensureBower()....
    .finally(() => CURRENTLY_RUNNING_BOWER_INSTALL = false)
  }
// ...snip...
```

around [lib/tasks/bower-install.js#L83](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/bower-install.js#L83)

**Comment by kellyselden** [comment]
we also have `addBowerPackagesToProject` that can do multiple for you FYI

**Comment by Turbo87** [comment]
I would agree that we shouldn't try to work around bugs in bower. If you want to install multiple deps use either `addBowerPackagesToProject()` or chain those calls together as @rwjblue demonstrated.

**Comment by kellyselden** [comment]
Just a thought, but we could use @rwjblue's method to at least warn them of concurrency issues. There are a non-zero amount of addons doing this either using RSVP.all, or just calling them both without returning any promise (found using emberobserver code search).
