### ISSUE TITLE
Use Segment's Nightmare.js for testing

### ISSUE THREAD

**Issue by timiyay** [ember-cli/ember-cli#6749]
I've recently adopted Segment's Nightmare.js (https://github.com/segmentio/nightmare) for automated browser testing, and it is next-level awesome.

Meanwhile, PhantomJS continues to have a snail-like release cycle (https://github.com/ariya/phantomjs/releases), and over 1000 outstanding issues.

What would the pros and cons be for replacing PhantomJS usage with Nightmare.js?

Pros:

• elegant, promise-compatible syntax for driving acceptance tests
• Electron-based, gives closer parity to Chrome browser features
• simple `npm install nightmare`, no native dependencies

Cons:

• changing stuff takes work
• possibly lacking features that PhantomJS has? Not sure

Apologies if this has been raised and rejected before, I couldn't find it in the issues.

**Comment by nathanhammond** [comment]
@timiyay It's far more likely that we move directly to headless Chrome, which is a thing that is forthcoming. There's a discussion about adopting Firefox for CI which already has a few of the issues with doing this enumerated.

Given the migration concerns, that it's effectively a different browser, and the relative maturity of the project I can say concretely we will not be adopting Nightmare by default. However, there is nothing to stop you from adopting it for your own CI!

**Comment by kellyselden** [comment]
Firefox RFC https://github.com/ember-cli/rfcs/pull/86 for reference.
