### ISSUE TITLE
ember-source blueprints are not used

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6751]
It seems that the blueprints in `ember-source` are not used correctly and the blueprints in `ember-cli-legacy-blueprints` are still used.

see also #6746

/cc @rwjblue @kellyselden

**Comment by Turbo87** [comment]
looks like https://github.com/emberjs/ember.js/commit/8f94545ec9629b8ca61c46f0053f2a68a420edc7 is the source of the problem. the `blueprints` folder simply was never published on NPM.

**Comment by rwjblue** [comment]
Keeping open until I get a patch release of 2.11 out with the fix.

**Comment by Dhaulagiri** [comment]
I updated our app to ember 2.11.1 and ember-cli 2.11.1 and it doesn't seem like tests are being created correctly:

```
 ~/> ember g acceptance-test foo
installing acceptance-test
```
and not test is actually generated.

Is there something else that I need to update?

**Comment by Turbo87** [comment]
@Dhaulagiri that *should* work... do the other generators work as intended?

**Comment by Dhaulagiri** [comment]
No, it's the same for others as well

```
> ember g component foo-bar
installing component
  create app/components/foo-bar.js
  create app/templates/components/foo-bar.hbs
installing component-test
```

**Comment by Turbo87** [comment]
@Dhaulagiri can you open an issue on the Ember.js repo for this? I'm going to close this one now since the blueprints from `ember-source` are now used correctly (even though the mocha tests appear to be broken...)

**Comment by rwjblue** [comment]
I had opened https://github.com/emberjs/ember.js/issues/14936 for this also
