### ISSUE TITLE
Addon preBuild argument `results` undefined

### ISSUE THREAD

**Issue by DHedgecock** [ember-cli/ember-cli#6752]
Hello,

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.0
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
4.0.5
```

I'm getting undefined for the `result` parameter in the preBuild hook inside addons for builds and livereload serving. Is this a bug or do the docs need to be udpated?
Docs:
https://ember-cli.com/api/classes/Addon.html#method_preBuild

Let me know if you need any additional info. I recreated this with a fresh 2.11 addon.

Thanks!

**Comment by rwjblue** [comment]
The documentation is incorrect, by definition we do not have a `result`'s object in `preBuild`...

**Comment by DHedgecock** [comment]
Thanks for clarifying.
