### ISSUE TITLE
Use eslint-plugin-mocha

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6760]
https://github.com/lo1tuma/eslint-plugin-mocha contains quite a few useful rules for Mocha tests. We should probably use it.

Example config: https://github.com/simplabs/eslint-config-simplabs/blob/v0.3.0/plugins/mocha.js

**Comment by kellyselden** [comment]
In general I'm +1 on this. Did you notice any rules that would affect us? Seems like most of them are weird things you can do in tests that I've never heard of.
