### ISSUE TITLE
ember init - diff shows each line changed when having non-uniform line endings

### ISSUE THREAD

**Issue by koopa** [ember-cli/ember-cli#6767]
Diffing in `lib/models/file-info` seems to not ignore white space differences and this caused difficulties for me when working on systems with unequal line endings.
`init` will prompt for every single file to be overwritten. It will show that each line is different. 

Procedure:
1) Updated ember-cli on a windows machine
2) Checked out an ember app located on a mac and did all the usual pkg update procedures, finalizing with `ember init`
3) `ember init` complained that all files differ on every line, turns out because of the varying line endings

There might be some line ending normalization needed in this case prior to passing the input to createPatch. I think my git config is also as it should be: `core.autocrlf input` on mac and `core.autocrlf true` on windows, since on windows it is definitely preferred to have \r\n line endings in the same way it is not preferred to have \r\n on bsd or gnu/linux.

**Comment by Turbo87** [comment]
> since on windows it is definitely preferred to have \r\n line endings

I don't agree with that and I think our policy by now was always generating \n. @kellyselden please correct me if I'm wrong.

**Comment by koopa** [comment]
Things will almost certainly be a bit messier on windows if there is \n only instead of \r\n in some situations but if it's a policy then I will deal with it on my own.

**Comment by Turbo87** [comment]
@koopa well, it is what we currently generate. if you use \r\n then that's fine and if we can easily support both for certain scenarios like the diffing you mentioned then that seems fine too. just wanted to state that we've discussed this and decided that our blueprints should only generate \n.

**Comment by koopa** [comment]
Ah yes, that is of course totally fine. But it seems like this is out of control of the blueprints anyway, no? Looks like it stems from the fact that my git on windows checked out all the files now with newlines converted to \r\n - which were originally generated properly with \n and checked in with \n as EOL. Notably this seems to be the correct thing for git to do to all files in this case. But then subsequently their EOL differs, resulting in all lines being marked as modified in the diff.

**Comment by ro0gr** [comment]
looks like  respecting of editorconfig is an ideal solution for this 
 https://github.com/ember-cli/ember-cli/issues/3664

**Comment by rwjblue** [comment]
Agreed
