### ISSUE TITLE
bin/ember should remain forwards/backwards compat

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6769]
https://github.com/ember-cli/ember-cli/commit/2809c3412dcde5ede0826b87b8d523470b650dbf introduces features that are not backwards compatible (the ember executable must work for many versions of ember-cli)

Lets move this to `ember-cili/lib/cli/index.js` instead

**Comment by rwjblue** [comment]
@stefanpenner - The scenario where things are mismatched is actually handled (and tested). Did you run into a specific issue or are you just generally concerned?

**Comment by hjdivad** [comment]
@rwjblue the mismatched versions is handled, but as @stefanpenner pointed out to me out of band, the initial require of utils/instrumentation does not handle the case where the bin gets disconnected from its `node_modules`.

**Comment by rwjblue** [comment]
Ok. You may recall we had a specific conversation about this before landing the changes to bin/ember. It should be fine to move the logic into cli/index.

**Comment by stefanpenner** [comment]
> It should be fine to move the logic into cli/index.

Lets do that

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/issues/6801 addresses this

**Comment by locks** [comment]
Addressed!
