### ISSUE TITLE
"ember test" hangs at last test when using Chrome

### ISSUE THREAD

**Issue by t4t5** [ember-cli/ember-cli#6773]
I have a weird situation where the `ember test` command hangs after the last step and never exits, when using Chrome instead of Phantomjs. This makes it impossible to use in CI services like Travis, since the tests are never completed even if they all pass.

Steps to reproduce:

- Create new Ember app

- Change the "launch_in_ci" option in `testem.js`:

  ```
  "launch_in_ci": [
    "Chrome"
  ],
  ```

- Run `ember test`

Here are some screenshots:

*Before changing the `testem.js` file (PhantomJS):*
<img width="605" alt="74f77bea-f1d5-11e6-995b-47d66cc70a6a" src="https://cloud.githubusercontent.com/assets/2598660/22918532/09007e9e-f28b-11e6-8c23-7d139f5ecd09.png">

*After changing the file (Chrome):*
<img width="614" alt="82fe975a-f1d5-11e6-831f-4451b298c5ba" src="https://cloud.githubusercontent.com/assets/2598660/22918565/2396f8dc-f28b-11e6-843f-58902fd5d9e0.png">

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.1
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.8
```

**Comment by Turbo87** [comment]
@t4t5 We've run into a kind of similar situation. The problem was that we started an `ember-cli-mirage` server, but it never was `shutdown()` and so the process was waiting for the server to quit. Please make sure that you don't have any servers running in the background either.

**Comment by lolmaus** [comment]
@vitkhab has discovered that migrating to [this](https://github.com/mark-adams/docker-chromium-xvfb) Docker container resolves the issue. Notice this item on their methodology:

> 3. Traps SIGTERM and relays the signal to the browser and Xvfb so that they will not continue to run once the test runner is finished. This is mostly required to deal with Karma's insistence that the browser process be terminated before it can exit. Without this relaying, Karma would hang indefinitely.
