### ISSUE TITLE
ember try:one exits with zero on test failure

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6779]
When running `ember try:one some-scenario` the exit code will be `0` even if there are test failures. I noticed this while digging into an issue in ember-engines (which uses ember-cli/ember-cli#master to make sure it still works properly against master).

Steps to reproduce:

```
ember new exit-code-incorrect-demo
cd exit-code-incorrect-demo
npm install github:ember-cli/ember-cli # to get master installed

# emits "fail" properly
 ember test && echo 'pass' || echo 'fail'

# this should emit "fail" but does not
 ember try:one default && echo 'pass' || echo 'fail'
```

See https://github.com/rwjblue/exit-code-incorrect-demo for an easier to clone demo.

I ran a `git bisect` and identified 8cd5447ac3b71721e84b40d544b0c3bd50e78e8c as the culprit (though I haven't dug into why just yet).

**Comment by rwjblue** [comment]
Did more digging into this the last couple days, my findings so far:

* ember-try uses `process.exit(1)` or `process.exit(0)` to force a desired exit code (see [here](https://github.com/ember-cli/ember-try/blob/master/lib/tasks/try-each.js#L129-L134) and [here](https://github.com/ember-cli/ember-try/blob/master/lib/tasks/try-each.js#L153-L159))
* the promise ember-try does not return an ultimate value from the command's run promise (see [here](https://github.com/ember-cli/ember-try/blob/master/lib/commands/try-one.js#L53-L71) and [here](https://github.com/ember-cli/ember-try/blob/master/lib/tasks/try-each.js#L36-L52))
* adding a return value to the command promise (where the return value is the exit code) and not calling `process.exit` ensures the proper exit code
* it seems calling `process.exit(<anything>)` does not actually change the exit code any longer?

The last few points are somewhat surprising, but returning the exit code is actually a much simpler system than what is being done now anyways so I think I'll refactor to that in ember-try...

**Comment by ro0gr** [comment]
Can't see what exactly breaks 'process.exit()' in the command interruption stuff. Hopefully will take look on the reason in the begining of the March.

**Comment by rwjblue** [comment]
I did more digging ( 👴 🔫 ) and here is more information (I believe I have identified the root cause):

1. Before starting a command we setup interrupt handlers ([here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L156), [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L29), and [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L80-L85)) that then return the commands `run` promise [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L205).
2. As part of that interrupt handler setup, we call `captureExit.captureExit()` [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L87)
3. We then continue to run the commands `validateAndRun` method [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L162)
4. During the course of running a command (`try:one` in this case) the command calls `process.exit(<any exit code>)`.
5. Since `captureExit.captureExit()` was called before the command is actually ran ([here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L87)) we begin initiating a `_flush` ([here](https://github.com/ember-cli/capture-exit/blob/063a5b87271caf34f0ba367ebbbb7354a24f14a1/index.js#L86))
6. `captureExit._flush` iterates through all `captureExit.onExit` handlers and invokes them [here](https://github.com/ember-cli/capture-exit/blob/063a5b87271caf34f0ba367ebbbb7354a24f14a1/index.js#L106-L123)
7. When `_flush` processes the [interrupt handler](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L203-L205) that was registered [just before the command was ran](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L156), it actually forces the rest of the  command's `run` promise to resolve
8. As part of that promise chain we [remove the interrupt handler](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L166), which (since it was the only handler registered) [tears down the signal trapping that we did](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L54) in step 1) above.
9. When tearing down signal handlers we call `captureExit.releaseExit()` [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/utilities/will-interrupt-process.js#L103) which resets `process.exit` to the original version
10. Once the command promise finishes, we resolve with the [final return value](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/lib/cli/cli.js#L194-L200) which returns control to the host `bin/ember` script [here](https://github.com/ember-cli/ember-cli/blob/acb3a9584c7e1828f16091ac403897129cc8d354/bin/ember#L48-L51)
12. We then call `exit` (the [npm package](https://www.npmjs.com/package/exit) that ensures `process.stdout` and `process.stderr` are properly flushed on windows) with the return value (aka exitCode) from the command promise.
13. `exit` package [drains the streams](https://github.com/cowboy/node-exit/blob/e0d68ecbef54426f7823f25a0f053e2e67bd0d6b/lib/exit.js#L20-L32) then [calls `process.exit`](https://github.com/cowboy/node-exit/blob/e0d68ecbef54426f7823f25a0f053e2e67bd0d6b/lib/exit.js#L17) with the exit code that was provided.
14. Since we have released `process.exit` in step 9) above, calling `process.exit()` is not "captured" and immediately exits.
15. The `_flush` that was started in step 5) never completes.

**Comment by rwjblue** [comment]
A few general observations:

* I do not think that we can assume that we were the only thing in the system to register `captureExit.onExit` handlers, and therefore we likely cannot `captureExit.releaseExit()` in `teardownSignalHandlers()`. 
* `capture-exit` should not allow (or it should no-op) a `captureExit.releaseExit()` call when [`isExiting`](https://github.com/ember-cli/capture-exit/blob/063a5b87271caf34f0ba367ebbbb7354a24f14a1/index.js#L105) is `true`.
* We should almost certainly **highly** encourage addon authors to use a command's `run` promises return value to control the exit code.  This refactoring in ember-try should make things quite a bit easier to grok.

**Comment by rwjblue** [comment]
> `capture-exit` should not allow (or it should no-op) a `captureExit.releaseExit()` call when [`isExiting`](https://github.com/ember-cli/capture-exit/blob/063a5b87271caf34f0ba367ebbbb7354a24f14a1/index.js#L105) is `true`.

Attempting to address this in https://github.com/ember-cli/capture-exit/pull/22.

**Comment by rwjblue** [comment]
> The last few points are somewhat surprising, but returning the exit code is actually a much simpler system than what is being done now anyways so I think I'll refactor to that in ember-try...

I addressed this in https://github.com/ember-cli/ember-try/pull/114, and confirmed that that PR fixes this specific issue (without changes to ember-cli or capture-exit).

The refactoring there seems good all around (and reduces some existing complexity IMHO), but I do believe that we should also land https://github.com/ember-cli/capture-exit/pull/22 (if not any other addon provided command that `process.exit`'s will have issue).
