### ISSUE TITLE
Certain test generators broken in 2.11.1

### ISSUE THREAD

**Issue by clekstro** [ember-cli/ember-cli#6782]
Hey everyone! First off, thanks so much for the great work! I noticed after an upgrade that some of the packaged generators aren't behaving as expected, but can reproduce in a new app as well. 

To reproduce, generate a new app using Ember-CLI 2.11.1 (or 2.12.0-beta.1). 

Next, attempt to generate either an `acceptance-test` or a `component`/`component-test`. None of these commands creates the expected test files. A repo showing the current state can be found [here](https://github.com/clekstro/ember-cli-broken-test-generators).

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.1
http_parser: 2.7.0
node: 7.5.0
v8: 5.4.500.48
uv: 1.10.2
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2
```

Here's the blueprint `DEBUG` output for each command:

Component:
```bash
$ DEBUG=ember-cli:blueprint ember g component foo-bar

installing component
  ember-cli:blueprint START: processing blueprint: `component` +0ms
  create app/components/foo-bar.js
  create app/templates/components/foo-bar.hbs
  ember-cli:blueprint END: processing blueprint: `component` in (20ms) +20ms
installing component-test
  ember-cli:blueprint START: processing blueprint: `component-test` +5ms
  ember-cli:blueprint END: processing blueprint: `component-test` in (5ms) +5ms
---
```

Component Integration Test:
```bash
$ DEBUG=ember-cli:blueprint ember g component-test foo-bar

installing component-test
  ember-cli:blueprint START: processing blueprint: `component-test` +0ms
  ember-cli:blueprint END: processing blueprint: `component-test` in (5ms) +6ms
```

Acceptance Test:
```bash
$ DEBUG=ember-cli:blueprint ember g component-test foo-bar

installing acceptance-test
  ember-cli:blueprint START: processing blueprint: `acceptance-test` +0ms
  ember-cli:blueprint END: processing blueprint: `acceptance-test` in (7ms) +8ms
```

Given that this doesn't only impact a single generator, it seems like something larger is afoot. I was, however, able to generate a model test:

```bash
$ DEBUG=ember-cli:blueprint ember g model foo

installing model
  ember-cli:blueprint START: processing blueprint: `model` +0ms
  create app/models/foo.js
  ember-cli:blueprint END: processing blueprint: `model` in (19ms) +20ms
installing model-test
  ember-cli:blueprint START: processing blueprint: `model-test` +5ms
  create tests/unit/models/foo-test.js
  ember-cli:blueprint END: processing blueprint: `model-test` in (8ms) +8ms
```

I'll dig in a bit more and see if I can track this down.

**Comment by mike183** [comment]
Seems related to https://github.com/emberjs/ember.js/issues/14936

**Comment by clekstro** [comment]
@mike183 Thanks for linking that. To be honest, I didn't think to look in the Ember repo as this felt like CLI behavior. Closing.

**Comment by rwjblue** [comment]
It used to be default ember-cli behavior but we have been moving ember specific blueprints into the ember-source addon (now that it is coming from NPM).
