### ISSUE TITLE
addPackageToProject() not using yarn

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6784]
the `addAddonToProject()` and `addPackageToProject()`  blueprint methods are currently not using yarn yet if a `yarn.lock` file exists. we should probably adjust that.

**Comment by rwwagner90** [comment]
It looks like from #6790 that we need to do some consolidation here, rather than just simply checking for yarn.lock and using yarn. Do we want to do all that in one fell swoop, or should this still be implemented separately before we consolidate?

**Comment by Turbo87** [comment]
@rwwagner90 whatever is easier I guess. https://github.com/ember-cli/ember-cli/issues/6863 should probably be handled first though.

**Comment by rwwagner90** [comment]
@Turbo87 okay, I can take a stab at these sometime this week, hopefully.

**Comment by michielboekhoff** [comment]
@rwwagner90 Have you picked this up? Otherwise I might take a crack at it.

**Comment by rwwagner90** [comment]
@michielboekhoff I haven't yet. Feel free to give it a shot! I won't be able to get to it for a couple days.

**Comment by michielboekhoff** [comment]
@Turbo87 Could you give me some more info? Right now, it seems like `addPackagesToProject` and `addAddonToProject` go through `NpmInstallTask`, which _does_ use Yarn if a yarn.lock is available. What is the expected behaviour you're after?

**Comment by Turbo87** [comment]
> it seems like addPackagesToProject and addAddonToProject go through NpmInstallTask

@michielboekhoff in that case we can just close the issue. I wasn't sure if that was the case already or not and opened the issue as a reminder to check if it was the case or implement it if necessary. Thanks for figuring it out! 👍
