### ISSUE TITLE
DS.RESTAdapter buildUrl Documentation incorrectly describes how the function works.

### ISSUE THREAD

**Issue by Syzygy24** [ember-cli/ember-cli#6787]
The same section present in the findBelongsTo documentation should also be in buildURL, buildUrlForFindAll... etc. Specifically, this: 
"The format of your links value will influence the final request URL via the urlPrefix method:

Links beginning with //, http://, https://, will be used as is, with no further manipulation.

Links beginning with a single / will have the current adapter's host value prepended to it.

Links with no beginning / will have a parentURL prepended to it, via the current adapter's buildURL."

**Comment by Turbo87** [comment]
Hi @Syzygy24! I think you may have opened this issue on the wrong repository. What you are looking for is probably https://github.com/emberjs/data or https://github.com/emberjs/guides.
