### ISSUE TITLE
Multiple CSS files compiled separately by watcher?

### ISSUE THREAD

**Issue by monovertex** [ember-cli/ember-cli#6794]
I was wondering if it's possible to have multiple CSS targets that would be compiled separately when watching files in the dev server environment.

We have the following config: 

```javascript
var app = new EmberApp(defaults, {
    // ...
    outputPaths: {
        app: {
            css: {
                'app': 'assets/app.css',
                'framework': 'assets/framework.css',
            }
        }
    },
    // ...
});
```

`framework` contains some particular code that is not changed often and takes quite a while to compile (~13s) and we would like to avoid compiling it while in dev mode, unless it was actually changed.

Currently ember-cli compiles all targets, whenever any of the SCSS files is changed.

Is there any way we could separate the watch logic?

**Comment by stefanpenner** [comment]
> Currently ember-cli compiles all targets, whenever any of the SCSS files is changed.

you can `app.import` such a file, outside of the regular build pipeline if it does not change. Or even place it straight in `public`.

---

This doesn't seem like an issue/bug, we can continue to discuss it here but I am closing it to keep the tracker organized.

**Comment by monovertex** [comment]
The trick here is that it doesn't change often, but it can change. It is indeed an option to keep it as a separate project and include the CSS straight in public, but it will be a hassle to maintain. This is why I'm asking if it is possible using the ember-cli pipeline to separate the watched paths. 

It would even be a solution to put it in a completely different `app/<dir>`, instead of style, and have a different build target for that, but I have no clue how would I accomplish that.

**Comment by monovertex** [comment]
@stefanpenner, any suggestions regarding my last reply?
