### ISSUE TITLE
Helpers not resolving correctly in addon's dummy app with pods structure

### ISSUE THREAD

**Issue by tsteuwer** [ember-cli/ember-cli#6813]
**Update: This also doesnt allow apps that consume the addon to use the helper as it causes a "Uncaught Error: Could not find module `my-addon/format-currency/helper` imported from `my-app/format-currency/helper`"**

Hello!

I'm using pods structure with my ember-cli addon. When I generate a new template helper via:

```
ember g helper format-currency
```

It creates the following files:

```
	new file:   addon/helpers/format-currency.js
	new file:   app/format-currency/helper.js
	new file:   tests/unit/helpers/format-currency-test.js
```

My issue comes when trying to test the template helper in the dummy app via ``{{format-currency 100}}`` where it throws:

```
loader.js:239 Uncaught Error: Could not find module `my-addon/format-currency/helper` imported from `dummy/format-currency/helper`
```

When I look at the vendor.js its namespace is defined as 'my-addon/helper/format-currency' so it doesn't find it correctly.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
os: linux x64
3.8.6
```

**Comment by rwjblue** [comment]
I presume that `app/format-currency/helper.js` is essentially doing:

```js
export { default } from 'my-addon/helpers/format-currency';
```

But we should actually have emitted (since `--pods` is true):

```js
export { default } from 'my-addon/format-currency/helper';
```

**Comment by tsteuwer** [comment]
Here are the outputs:

*app/format-currency/helper.js*
```
export { default, formatCurrency } from 'my-addon/format-currency/helper';
```

*addon/helpers/format-currency*
```
import Ember from 'ember';

export function formatCurrency(params/*, hash*/) {
  return params;
}

export default Ember.Helper.helper(formatCurrency);
```

*tests/unit/helpers/format-currency-test.js*
```

import { formatCurrency } from 'dummy/helpers/format-currency';
import { module, test } from 'qunit';

module('Unit | Helper | format currency');

// Replace this with your real tests.
test('it works', function(assert) {
  let result = formatCurrency([42]);
  assert.ok(result);
});
```

Also interesting to note is the unit test created is looking for *dummy/helpers/format-currency.js* instead of the addons module or app module. I find this to be rather odd.

By the way, I have ``"usePods": true`` set in my ``.ember-cli``. I'm not using the command-line ``--pods`` parameter.

**Comment by tsteuwer** [comment]
Ok, so I think the issue is it's actually pointing to the *dummy/helpers/format-currency*. The thing I mentioned above in the unit test that gets generated also uses the dummy directory to grab the helper for testing. It fails on running the test. If I change the file to use:

*my-addon/tests/unit/helpers/format-currency-test.js*
```
/**
 * Changing this:
 * import { formatCurrency } from 'dummy/helpers/format-currency';
 * to....
 */
import { formatCurrency } from 'my-addon/helpers/format-currency';
import { module, test } from 'qunit';

module('Unit | Helper | format currency');

// Replace this with your real tests.
test('it works', function(assert) {
  let result = formatCurrency([42]);
  assert.ok(result);
});
```

It fixes the unit test. However, I don't know where the dummy app is creating the import for ``dummy/helpers/format-currency``.

**Comment by locks** [comment]
As far as I know, the CLI team decided to keep pods support to a minimum so I am closing this issue as no longer relevant. Thanks for all the detailed info!
