### ISSUE TITLE
Cryptic error running `ember` when package has `ember-addon` keyword without being a full addon

### ISSUE THREAD

**Issue by srvance** [ember-cli/ember-cli#6820]
I have an Ember utility package that I tagged with the `ember-addon` keyword for it to have EmberObserver visibility, but it is not a full addon. The package is `ember-cli-build-config-editor`. It has a similar function and role as `ember-router-generator` as a utility that supports blueprints. This causes `ember` to crash with a cryptic error.

## Recipe

* `ember new <name>`
* `cd <name>`
* Edit `package.json` and add `"ember-cli-build-config-editor": "0.1.1",` to the `devDependencies`
* `ember`

You will see the following output:

```
did not recognize object of type "range"
Error: did not recognize object of type "range"
    at Object.getFieldNames (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/types.js:663:19)
    at visitChildren (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:223:36)
    at Visitor.PVp.visitWithoutReset (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/srvance/tests/e-c-addon-bug/node_modules/ast-types/lib/path-visitor.js:246:25)
```

I believe this is because `ember` scans the `node_modules` for things with the `ember-addon` keyword but does not verify that the package fulfills the addon contract before trying to invoke it.

## Workarounds

Two workarounds are:

1. Remove the `ember-addon` keyword, which I've done in version 0.1.2
2. Create an `ember-addon` entry point in `package.json` that fulfills the contract (mentioned by @rwjblue with reference to `ember-cli-htmlbars` but not tried yet. I'll rev the package to 0.2.0 if it works.)

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.1
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
4.0.3
```

**Comment by Turbo87** [comment]
@srvance I'm not sure I understand what behavior you expect from Ember CLI. The intended behavior is assuming that if an npm package has the `ember-addon` keyword then it will behave like an Ember addon. If you use the keyword but you're not an addon then you're probably doing it wrong 😉

**Comment by srvance** [comment]
Hi, @Turbo87. I agree it's a bit of a dysfunctional case. Both @rwjblue and @kategengler were quite surprised at the failure mode on this. @rwjblue initially told me he didn't think it would be harmful to use the `ember-addon` keyword in this way.

As for expectations, I would expect a less cryptic output per the Robustness Principle, perhaps a warning and skip processing that package. I initially encountered this through a transitive dependency. If I hadn't authored the package and been trying to test it "in the wild," I wouldn't have had a clue about where to look.

I don't mind perhaps fixing it myself, but it would be pretty far down my priority list at the moment so I wanted to capture it.

**Comment by stefanpenner** [comment]
Seems reasonable for this to be fail fast, is that what your recommending @srvance ?

**Comment by srvance** [comment]
That would be great. The messages when you have an `ember-addon` `main` that doesn't exist or when that module doesn't have a `name` are perfect.

**Comment by stefanpenner** [comment]
@srvance ya, thanks for pointing this one out. Important for us to mitigate cryptic errors...

**Comment by jsturgis** [comment]
@srvance @stefanpenner The cryptic error was caused by code in the [addon's constructor](https://github.com/srvance/ember-cli-build-config-editor/blob/1277a4f293a34c3030f78758a6b85d36240d1c8f/lib/build-config-editor.js#L11) in this case and not by ember-cli or any of it's dependencies I don't see how ember-cli could have caught this early or shown a more friendly message?

**Comment by rwjblue** [comment]
I was thinking that we would wrap https://github.com/ember-cli/ember-cli/blob/master/lib/models/addons-factory.js#L55 in a try/catch and add a custom message (with the name and path of the addon being instantiated).

**Comment by jsturgis** [comment]
@rwjblue yeah that seems like the best approach, if no one else is working on this I can put in a fix for it.

**Comment by rwjblue** [comment]
Awesome, sounds great!
