### ISSUE TITLE
After upgrading the ember-cli in an addon, package.json's keyword hash is removed unintentially

### ISSUE THREAD

**Issue by ykaragol** [ember-cli/ember-cli#6832]
While upgrading the ember cli version, after running `ember init` in an addon project, `keyword` hash is removed from `package.json`. 
This makes addon project to behave as an ember app.

Tested while upgrading ember 2.3 to ember 2.11.

`ember -v` results:
> ember-cli: 2.11.1
> node: 6.7.0
> os: wind32 x64

`npm -v` results:
> 4.0.3

**Comment by Turbo87** [comment]
@ykaragol can you provide details instructions on how to reproduce this issue?

**Comment by ykaragol** [comment]
I've just tested it in another addon today. No problem about `keywords`. Cannot reproduce it. 
Only `description`, `version` and `repository` fields were cleared.
