### ISSUE TITLE
Allow `ember install` to accept blueprint options

### ISSUE THREAD

**Issue by srvance** [ember-cli/ember-cli#6834]
For `ember-bootstrap`, we're enhancing the default blueprint to simplify the selection of Bootstrap version and preprocessor. It would be really nice and a faster installation process for the user if we could pass the default blueprint's options on `ember install` rather than having to run it after addon installation.

Ideal would be something like

```
ember install ember-bootstrap --bootstrap-version=4 --preprocessor=sass
```

although an option that took blueprint options could also work.

**Comment by Turbo87** [comment]
@srvance instead of passing options on the command line like that you could also use `inquirer` (which is available as `this.ui.prompt()` I think) to query these options at install time

**Comment by stefanpenner** [comment]
@Turbo87 it would be good to support both.

https://github.com/emberjs/rfcs is likely the better venue for this. (Feel free to open an issue there, if you are not ready for an RFC).

**Comment by srvance** [comment]
Will do. We're talking about a more interactive version of it, as well, but starting with CLI.

**Comment by srvance** [comment]
Created emberjs/rfcs#212
