### ISSUE TITLE
Welcome page includes broken links to documentation in 2.12.0.

### ISSUE THREAD

**Issue by chrisself** [ember-cli/ember-cli#6869]
Hey all,

I'm seeing that ember-cli installs versions `2.13.0-beta.1` of ember-data and ember-source. When creating a new project, ember-welcome-page parses the version number and provides links to the Quick Start introduction and Guides and Tutorials page. However, I don't believe 2.13.0 has online documentation yet, so both links result in a 404 error.

Here are the two URLs I received:

https://guides.emberjs.com/v2.13.0/getting-started/quick-start/
https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/

Because ember-welcome-page is parsing the correct version of Ember, I'm not sure where this issue belongs exactly. As a note, this is my first time opening an issue here, so please let me know if more information is needed.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.12.0
http_parser: 2.7.0
node: 7.4.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.0.5
```

**Comment by locks** [comment]
Thank you for reporting @chrisself! I have moved this to the addon's issue tracker so its maintainers are aware. We should have all the necessary information from your post :)
