### ISSUE TITLE
ember-cli-test-loader removed from package.json blueprint should be in 2.12 changelog

### ISSUE THREAD

**Issue by gabrielgrant** [ember-cli/ember-cli#6882]
When updating from 2.11 to 2.12 I noticed `ember-cli-test-loader` is removed from the package.json blueprint, but it's not clear where/why this occurred (it's not mentioned in [the changelog](https://github.com/ember-cli/ember-cli/releases/tag/v2.12.0))

This is something that's really easy to miss, because of all the other packages I have in my package.json that aren't in the blueprint. I didn't think `ember-cli-test-loader` was something I'd installed manually, but took a bit of digging to be sure.

Looks like the change was introduced in [the commit that upgraded ember-cli-qunit](https://github.com/ember-cli/ember-cli/commit/e57fb854002a6e146209e481a9043741566e533f), but it's noted in a second line of the commit message, so doesn't show up in the changelog

**Comment by gabrielgrant** [comment]
Probably could have saved a bit of time by looking at [the output diff](https://github.com/ember-cli/ember-new-output/compare/v2.11.0...v2.12.0) from [the release blog post](http://emberjs.com/blog/2017/03/19/ember-2-12-released.html). Maybe link that from the changelog?

**Comment by rwjblue** [comment]
Hmm, not sure what you mean.  We do link to that in the [CHANGELOG.md](https://github.com/ember-cli/ember-cli/blob/v2.12.0/CHANGELOG.md)...

**Comment by gabrielgrant** [comment]
I mean that I'm blind, apparently. Sorry for the noise.

**Comment by gabrielgrant** [comment]
It might be nice if there were some way to colorize the diffs as a three-way diff to, for example in `package.json`, distinguish between packages removed in the new version vs those that I've manually installed. But hardly critical.
