### ISSUE TITLE
Bower references in the README.md blueprint file need to be updated

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#6895]
The [README.md](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/README.md) blueprint file includes two Bower mentions that should probably be removed.

The first one, Bower being listed in the Prerequisites, is no longer necessary as a newly generated application has an empty `bower.json` file in v2.12, and will have no `bower.json` at all in v2.13 if the release cycle carries on normally.

The second reference is related to this, as it tells you to run `bower install` under Installation. This will result in an error in v2.13, due to `bower.json` no longer being created by default.

**Comment by michielboekhoff** [comment]
I've fixed this issue and created a PR.

**Comment by michielboekhoff** [comment]
As #6896 was merged, I think we can safely close this.

**Comment by locks** [comment]
Done, thanks!
