### ISSUE TITLE
Slow build time for ember-cli

### ISSUE THREAD

**Issue by jeffrey008** [ember-cli/ember-cli#6921]
Hello, I got a slow build time here. Can anyone please help me take a look? 

Output from `BROCCOLI_VIZ=true ember s -p 4202`:
```
Build successful - 78197ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel              | 26988ms
broccoli-persistent-filter:TemplateCompiler   | 15110ms
broccoli-persistent-filter:Babel > [Babel:... | 6507ms
broccoli-persistent-filter:Babel > [Babel:... | 3933ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel (5)          | 27246ms (5449 ms)
broccoli-persistent-filter:TemplateCom... (8) | 16628ms (2078 ms)
broccoli-persistent-filter:Babel > [Ba... (2) | 6605ms (3302 ms)
broccoli-persistent-filter:Babel > [Ba... (1) | 3933ms
```
---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.7.0
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
npm:4.4.4
```

I have already read [PERF_GUIDE.md](https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md) and generated the tree graph.

According to the tree graph, there is a `broccoli-persistent-filter: Babel` that takes a lot of time(self 26988 ms). I uploaded that part of png.
![out](https://cloud.githubusercontent.com/assets/11265387/24442258/e6081542-148f-11e7-92a6-fdb601445137.png)

I would like to upload the whole png here, but it is too big (14mb), and github won't allow me to upload.

Please let me know if there is any more information I can provide. Thanks

**Comment by denchen** [comment]
I'm seeing really slow build times as well. I'm on 2.12.3.

    Slowest Nodes (totalTime => 5% )              | Total (avg)         
    ----------------------------------------------+---------------------
    Babel (76)                                    | 144265ms (1898 ms)

Nearly 2.5 minutes to start up `ember serve`, which is a lot longer than what it was when I was on 2.7.3.

I'll probably provide more information.

**Comment by stefanpenner** [comment]
Sharing your app or a reproduction would be handy. If you can't share it publically, but can privately please ping me on slack

**Comment by denchen** [comment]
@stefanpenner My app is an internal corporate app, so it's not shareable. 

BUT... I may have solved the issue, at least in my environment. I upgraded Node 6 to 6.10.3 and npm from 2.15.11 (not sure how it was still so old) to 3.10.9. After the upgrade, and after clearing out `/dist` and `/tmp` and reinstalling all my Node packages, suddenly my build times dropped down the 17 seconds, which is by far the fastest I've ever seen it build.

I'll have to monitor it for awhile to see if I eventually get a slowdown in build times.

**Comment by stevenwu** [comment]
I had a similar issue. Some of my app addons are still on `ember-cli-htmlbars-inline-precompile@0.3.x` and `ember-cli-babel@5.x.x`. Downgrading `ember-cli-babel` and `ember-cli-htmlbars-inline-precompile` is a temporary fix. Reduced build times from 67s to 27s.

**Comment by john-griffin** [comment]
Also seeing significantly slower initial build time recently.

```
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (68)                                    | 89389ms (1314 ms)
```

Version:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
4.2.0
```

Checking through our travis build history, the total run time doubled after we upgraded to from cli `2.12.2` to `2.13.1`.

**Comment by john-griffin** [comment]
Just trashed my `node_modules` and regenerated `yarn.lock` from scratch.

```
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (56)                                    | 2185ms (39 ms)
Concat (9)                                    | 2014ms (223 ms)
SimpleReplace (7)                             | 1179ms (168 ms)
EslintValidationFilter (3)                    | 700ms (233 ms)
Funnel: Addon JS (43)                         | 566ms (13 ms)
```

Must have been locked to some old dependancy that was slowing things down. Anyone else get the same thing why they try this?

**Comment by jeffrey008** [comment]
I noticed that if you are developing an addon and use `npm link` methods as described [here](https://ember-cli.com/extending/#configuring-your-ember-addon-properties), the build time will be very very long. Mine can be as long as 3 minutes.

**Comment by vlascik** [comment]
My build times are at 20 minutes, I think it started this way after update to 2.13 or 2.14 beta. 
```
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (69)                                    | 1142622ms (16559 ms)
```
Could this have something to do with main app being on babel 6 and all addons having their own copy of babel 5?

**Comment by zurnet** [comment]
Curious if anyone has any solutions? I have super long build times as well.

**Comment by jeffrey008** [comment]
@zurnet Use latest ember 2.13.0, it works faster.

**Comment by vlascik** [comment]
@zurnet What worked for me was to empty `node_modules` and `npm install` everything again. Build times then went to the usual minute or two.

**Comment by stefanpenner** [comment]
@vlascik interesting. I wonder what exactly about the node_modules pre reinstall tripped stuff up...

**Comment by john-griffin** [comment]
Yep it was similar here. I trashed node_modules and regenerated yarn.lock and it was back to normal.

**Comment by vlascik** [comment]
@stefanpenner it probably had something to do with Babel (5 vs 6), as that was what was taking maybe 18 of those 20 minutes (see above)

**Comment by dfreeman** [comment]
I've run into exactly the same thing across maybe a dozen different projects, but never at a moment when I had time to try and diagnose.

The Babel 5/6 change struck me as suspicious timing-wise, but given that it's a crossing major version boundary, I wouldn't expect nuking `yarn.lock` and `node_modules` to change much, since it still can't dedupe.

**Comment by john-griffin** [comment]
Also there is still babel 5 stuff in the yarn.lock after regen and it runs ok now.

**Comment by stefanpenner** [comment]
> The Babel 5/6 change struck me as suspicious timing-wise

Yes, I believe this is likely related. But surprising. Witha reproduction I could investigate. But the work-around of `rm -rf node_modules; rm -rf yarn.lock; yarn install` may be an alright bandaid for today?

**Comment by zurnet** [comment]
I did a `rm -rf node_modules` and then `npm install` and it cut my build time down from 2-3 min to ~31 seconds!

**Comment by bgentry** [comment]
Similar results here, regenerating `yarn.lock` as suggested took me from 115 sec to 19 sec. Pasted my `git diff yarn.lock` into [a gist here](https://gist.github.com/bgentry/ea9e68afb567d6a7366459a3369d190c) in case it might help.
