### ISSUE TITLE
Unable to add element modifiers to real web components (v2.13.0-beta.2)

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli#6925]
In checking out the latest beta and the new ability to generate a web component using GlimmerJS, I realized that the Ember CLI now no longer supports being able to add an element modifier to a "real" (meaning a non-GlimmerJS) web component.  Essentially, the following code does not work anymore

```hbs
<real-web-component {{action 'some-ember-action' on='customEvent'}}>
  Content in slot
</real-web-component>
```

This ends up throwing a template compilation, presumably because the template compiler is making the assumption that any non-standard "angle bracket" component is a GlimmerJS component, to which an element modifier can understandably not be attached.

Here's a screenshot of the error for reference:

<img width="1550" alt="screen shot 2017-03-30 at 11 16 35 am" src="https://cloud.githubusercontent.com/assets/1645881/24519839/29dea050-153b-11e7-9294-b8b773862a69.png">

And a link to a demo repo that shows off the issue.

https://github.com/alexlafroscia/ember-cli-2.13-web-component-element-modifier

Just `yarn && yarn start` and you'll see the same issue I showed above.

I'm sure that this is a hard problem to solve. An explicit whitelist of custom elements to treat like regular HTML elements in the template compilation would not be particularly elegant but, much like having to define `customEvents`, might be a fine solution for the time being to at least not break applications that are using web components.

**Comment by stefanpenner** [comment]
The error appears to be coming from ember itself ember-source's bundled templateCompiler. Are you sure this is an issue with ember-cli (as it seems quite unlikely) ?

**Comment by twokul** [comment]
@alexlafroscia this is actually not an ember-cli issue, the error comes from [glimmer](https://github.com/tildeio/glimmer/blob/82a2ab8400b54f118e2944f3cf6fed24dd8bd40c/packages/%40glimmer/compiler/lib/javascript-compiler.ts#L115) while compiling your template. 

Here's a working template:

```html
<real-web-component onclick={{action "ember-action"}}>
  Hello, world!
</real-web-component>
```

> I'm sure that this is a hard problem to solve. An explicit whitelist of custom elements to treat like regular HTML elements in the template compilation would not be particularly elegant but, much like having to define customEvents, might be a fine solution for the time being to at least not break applications that are using web components.

If you have ideas on how to implement this, I'd suggest to open an RFC or an issue for Ember itself.
