### ISSUE TITLE
Failure to load vendor.css with Ember 2.13.0-beta

### ISSUE THREAD

**Issue by kybishop** [ember-cli/ember-cli#6927]
We attempted to upgrade the html-next/flexi addon to the 2.13 beta but the dummy app is no longer generating CSS. This issue does not occur in 2.12.

Chrome developer tools reports: `Failed to load resource: the server responded with a status of 404 (Not Found) vendor.css`

To reproduce the bug, checkout [the flexi repo](https://github.com/html-next/flexi) and attempt to visit the dummy site.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.13.0-beta.2
http_parser: 2.7.0
node: 7.2.0
v8: 5.4.500.43
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: darwin x64
3.10.9
```

**Comment by rwwagner90** [comment]
Potentially helpful, we do some manually scss stuff in the styles repo, which could be related to this https://github.com/html-next/flexi-default-styles/blob/master/index.js#L41

**Comment by rwjblue** [comment]
@trentmwillis - I believe that this may be a result of some of the broccoli-concat changes.  Basically, if there is no content for a file it seems like we do not create it?

**Comment by kybishop** [comment]
@rwjblue Just to out it out there, the flexi addon's dummy app does indeed generate CSS (via ember-cli-sass). Not sure if something g potentially got borked with the way sass is being compiled into CSS

**Comment by trentmwillis** [comment]
@rwjblue I don't think so, we have explicit tests for that: https://github.com/broccolijs/broccoli-concat/blob/245b1c8dff44fc05810cd0d041c0c9b6a386d2b4/test/simple-concat-test.js#L234-L257

**Comment by rwwagner90** [comment]
@Dhaulagiri so this happens with just a bare bones, fresh app? Thought it was related to something weird we were doing. Glad it's not just us!

**Comment by jamiechong** [comment]
I can reproduce this with a bare bones app:
```
ember-cli: 2.13.0-beta.1
node: 6.9.1
```

```
ember new vendorcssbug
cd vendorcssbug
npm install 
ember build --environment production
```

```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/vendor-a121afb68e840686dc7c848b17ab212b.js: 759.19 KB (198.04 KB gzipped)
 - dist/assets/vendorbug-23760a4d46b4f67cf04460d587721317.js: 5.23 KB (1.4 KB gzipped)
 - dist/assets/vendorbug-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

`vendor.css` is referenced inside `index.html`, but it was never built:

```
    <link rel="stylesheet" href="/assets/vendor.css">
    <link rel="stylesheet" href="/assets/vendorbug-d41d8cd98f00b204e9800998ecf8427e.css" integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" >
```

**Comment by webark** [comment]
so it looks like @rwjblue https://github.com/ember-cli/ember-cli/pull/6617 removed a "random" `this.import('vendor/addons.css');`  https://github.com/ember-cli/ember-cli/blame/db9bc531648469b0c89ce700c53b0ecc95e5914b/lib/broccoli/ember-app.js#L1344

All this really did was ensure that the vendor.css file was in the an `outputFIle` in `_styleOutputFiles`

Even though it seems really hacky all that is needed, and not suggesting this as a fix, is ...
```javascript
      if (!this._styleOutputFiles[this.options.outputPaths.vendor.css]) {
        this._styleOutputFiles[this.options.outputPaths.vendor.css] = null
      }
```

**Comment by rwjblue** [comment]
FWIW, the `app.import` was not random (and it wasn't only to ensure the file was emitted it just *also* did that). Prior to that change all addon css was concatted down to a single file, then concatted _again_ into the final `assets/vendor.css`.

IMHO, the issue as reported is somewhat odd. Why would we want to download an empty CSS file in all apps that don't have vendor styles?  I'd call that a bug 😈 ...

I think what we want is a mechanism to do conditional `<script>`/`<link>` in `index.html` based on if we have any assets. That way we don't even attempt to load (and waste time during application boot) an empty CSS file.

**Comment by webark** [comment]
ha! @rwjblue I didn't mean anything by the random. just ment it was kind of there without anything. And i think that would be a good approach. The only issue other then that was, if you had an addon (it was an inrepo addon for me) that just had an "addon/styles/addon.EXT" it wouldn't get loaded up cause a vendor import had never occurred.

**Comment by rwwagner90** [comment]
If there is a file we need to have to trick this into working, I am all for that as well or some sort of flag to set to force it to generate a vendor.css.

**Comment by stefanpenner** [comment]
Taking a looking now.

**Comment by stefanpenner** [comment]
So if no addon produces the vendor.css we should not create one. If we do, we likely mask empty file + extra request. The current behavior merely surfaces this problem.

* Now, if one has a vendor link, in index.html they will get an error.
* For add-ons which must have vendor.css present, they should include that as part of the installation instructions (or blueprint).

**Comment by rwwagner90** [comment]
@stefanpenner so how do we fix this for flexi? With 2.12 we get all the styles, with 2.13 we get this error and no styles.

**Comment by rwjblue** [comment]
AHA! There are indeed two different things going on in this issue.  @stefanpenner and I chatted and discussed the "simple" case (which is that we correctly just don't emit `vendor.css` when their legitimately is none), but we didn't discuss in detail the issue that @rwwagner90 brought up.

**Comment by rwjblue** [comment]
Which is essentially that an addon with `addon/styles/addon.scss` (and the appropriate preprocessors) emits a `${addonName}.css` file, which (in ember-cli@2.12) was concatted into `assets/vendor.css` automatically and in ember-cli@2.13 we are only concatting it into `vendor.css` _if_ that file would normally be created.

@rwwagner90 / @webark - Have I summarized that correctly?

**Comment by stefanpenner** [comment]
> if that file would normally be created.

So this add-on produces a file via its mechanism, and that file is not concatenated but once was?

**Comment by stefanpenner** [comment]
So:

- [ ]  file missing behavior seems correct
- [ ] but the file shouldn't be missing?

**Comment by webark** [comment]
@rwjblue @stefanpenner yep. when you put styles in you addon.EXT file, i'm pretty sure that gets processed into the addonname.css file that @rwjblue mentioned. then if the file you are generating is the main "vendor.css" file https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1330 it gets concatedted in.

If a "import" is never called, the style outputs never gets that as a key, and that loop never runs, so the default addon style behavior never happens..

**Comment by stefanpenner** [comment]
Talking with @runspired this seems like a bug in `flexi` that just happened to work. It shouldn't block ember-cli release.

Specifically, rather the returning a `tree` which contains the styles, `flexi` write back into the `<addon-name>/styles` causing the watcher to rebuild, and the second build would contain the correct output.

I"ll work with @runspired for flexi to do the right thing.

**Comment by webark** [comment]
@stefanpenner this is an example repo of what I see going not working. Do addon's addon.css files not get automatically added into the vedor anymore?

https://github.com/webark/example-no-welcome

**Comment by stefanpenner** [comment]
> Do addon's addon.css files not get automatically added into the vendor anymore?

Ya something seems funky, both in ember-cli (i think) and in flexi (absolutely).

**Comment by stefanpenner** [comment]
* flexi patch: https://github.com/html-next/flexi-default-styles/pull/7
* cli patch: https://github.com/ember-cli/ember-cli/pull/6961

**Comment by rwwagner90** [comment]
@stefanpenner so with the cli fix, is `addon.css` automatically concatted into `vendor.css` again? If so, shouldn't flexi not need a patch?

**Comment by stefanpenner** [comment]
The patch to flexi is not required to fix this issue, but it is required to make flexi work correctly in general

**Comment by rwwagner90** [comment]
@stefanpenner it seems like the flexi patch is still WIP. What is required to get it over the finish line? Would love to be able to update all the things to 2.13 😄

**Comment by runspired** [comment]
@rwwagner90 I'm going to work with you and @kybishop to finish it off from where @stefanpenner left it.
