### ISSUE TITLE
Cannot build without a .travis.yml file

### ISSUE THREAD

**Issue by mitchlloyd** [ember-cli/ember-cli#6931]
After upgrading to ember-cli 2.11.1 my build is failing with this error:

```
TypeError: Cannot read property 'node_js' of undefined
```

Which is coming from this line: https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/platform-checker.js#L14

It appears as if the `.travis.yml` file is required for the build to work. After adding this file with a `node_js` version my build works. 

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.11.1
http_parser: 2.7.0
node: 6.9.5
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
```

**Comment by kellyselden** [comment]
Is this an app or an add-on?

**Comment by rwjblue** [comment]
We use the .travis.yml to determine which versions are supported. Are you saying that there is no .travis.yml in the 2.11.1 tarball that is published?

**Comment by twokul** [comment]
checked the tarball associated with `2.11.1` release and it seems like it has `.travis.yml` file (assuming that's the tarball that got published).

@rwjblue on a side note, we might want to brainstorm the solution by which it's allowed to use other CI solutions (circle ci) to figure out test versions of Node.js. thoughts?

**Comment by mitchlloyd** [comment]
This is an application (not an addon).

I believe that a new (ember new) application would work fine. I'm upgrading from an existing app that doesn't have a `.travis.yml` file (we don't use Travis). Maybe @twokul is onto something that there should be an alternate solution to figure out which node versions are supported. I was surprised to see that a `.travis.yml` file was needed to build successfully.

**Comment by stefanpenner** [comment]
Strange, the file you link to above appears to be attempting to load ember-cli's own `.travis.yml` not the one in your project.

**Comment by mitchlloyd** [comment]
@stefanpenner Thanks for pointing this out. I suspect this might be a local problem now and I've been fooled by the solution of adding a `.travis.yml` file.

**Comment by stefanpenner** [comment]
hmmm

```sh
curl $(npm info ember-cli --json | jq -r '.dist.tarball') | tar -xf travis.yml 
tar: Error opening archive: Failed to open 'travis.yml'
```

**Comment by stefanpenner** [comment]
@mitchlloyd if you run `cat node_modules/ember-cli/.travis.yml` what do you get?

**Comment by stefanpenner** [comment]
contents of `.travis.yml` on both 2.11.1 also appear fine on NPM.

```sh
$ curl --silent $(npm info ember-cli@2.11.1 --json | jq -r '.dist.tarball') | tar -xf - package/.travis.yml;
$ cat package/.travis.yml

sudo: false

language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "7"

branches:
  only:
    - master
    - beta
    - release
    - auto
    - /^greenkeeper.*$/

cache:
  directories:
    $HOME/.npm
    $HOME/.cache # includes bowers cache

before_install:
  # prevent the npm loading indicator
  - npm config --global set spin false
  # if npm version is less 3.0.0 (lets say 1.x or 2.x) we should attempt to upgrade to 3
  - if [[ $(npm -v | cut -d '.' -f 1) -lt 3 ]]; then npm i -g npm@^3; fi

install:
  - travis_retry npm install --no-optional

script:
  - npm run-script test-all:cover

after_script:
  - travis_retry npm install coveralls codeclimate-test-reporter
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
  - cat coverage/lcov.info | node_modules/.bin/coveralls

after_success:
  - .travis/deploy.sh
```

**Comment by stefanpenner** [comment]
It may be that you local `node_modules` or global `ember-cli` install has gotten into a bad state, what happens when you blow those away and try again?

**Comment by mitchlloyd** [comment]
@stefanpenner, that command shows what you've posted. I've now been able to remove my local `.travis.yml` file and have the build work. 

I think this is related to a `yarn` issue where using `yarn clean` omits some files from `node_module`.
