### ISSUE TITLE
karma + ember-cli

### ISSUE THREAD

**Issue by vire** [ember-cli/ember-cli#694]
Hi, I'm struggling a bit with configuring the karma (version 0.12.16) and ember-cli (0.0.25).

Reason - I would like to leverage the test running/watching on karma. Now i get errors when I try to load the ./tests/test-helper/loader.js and the test-cases saying it can't resolve the import keyword (parse error)

**Question** is how to setup the karma.conf.js, especially  the files section.

My conf looks now like:

```
files: [
      'vendor/loader/loader.js',
      'vendor/jquery/jquery.min.js',
      'vendor/handlebars/handlebars.js',
      'vendor/ember/ember.js',
      'vendor/ember-resolver/dist/ember-resolver.js',
      'vendor/ember-load-initializers/ember-load-initializers.js',
      'tmp/output/assets/app.js',
      'tests/unit/routes/index-test.js'
    ],
```

**Comment by amercier** [comment]
+1 @mattjmorrison as well.

Adding coverage to Karma is [very easy](https://github.com/karma-runner/karma-coverage). See [a configuration example](https://github.com/amercier/todomvc-testing/blob/master/tests/vanillajs/mocha/karma.conf.js).
Example of generated coverage report [here](http://amercier.github.io/todomvc-testing/tests/vanillajs/qunit/coverage/html/index.html).

**Comment by corsen2000** [comment]
I'd also like to see karma support.  The primary reason being karma has built in selenium support to use browsers on a grid.  I have not found a way to do that with testem, but I imagine its possible since there is "edge" support for BrowserStack and Sauce.

Is there an open issue for making the test runner pluggable?

**Comment by onmission** [comment]
+1 for Karma because of the it's reporters, So I can use karma test reports with TFS 2015 builds.
