### ISSUE TITLE
lib/tasks/install-blueprint.js should use `yarn` if available

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6953]
Currently, `ember new foo -b some-package-name` will always use `npm` to download and install `some-package-name` into the created temporary directory. It should be updated to use `yarn` if available on the system.

Note: this does not change any existing semantics (AFAICT), it simply makes installing a blueprint from the npm registry faster 😸

**Comment by stefanpenner** [comment]
Sounds good. @turbo87 any concerns?

**Comment by Turbo87** [comment]
seems like a duplicate/subtask of https://github.com/ember-cli/ember-cli/issues/6790 😉

**Comment by rwjblue** [comment]
Seems good, will close as dupe.  I had mistakenly thought that issue was closed, but I was thinking of yet another dupe 😝
