### ISSUE TITLE
Broccoli throws error importing a webpack development build

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#6954]
I have a webpack build that contains this self-contained code:

```js
// Hot Module Replacement
if(false) {
	// When the styles change, update the <style> tags
	if(!content.locals) {
		module.hot.accept("!!../../node_modules/css-loader/index.js??ref--1-1!../../node_modules/postcss-loader/index.js!./app.pcss", function() {
			var newContent = require("!!../../node_modules/css-loader/index.js??ref--1-1!../../node_modules/postcss-loader/index.js!./app.pcss");
			if(typeof newContent === 'string') newContent = [[module.id, newContent, '']];
			update(newContent);
		});
	}
	// When the module is disposed, remove the <style> tags
	module.hot.dispose(function() { update(); });
}
```
I import this from npm like so:

![image](https://cloud.githubusercontent.com/assets/216566/24921094/901495be-1ee1-11e7-9424-0f6febeb2383.png)

however, broccoli throws this
```
Error: Cannot find module '!!../../node_modules/css-loader/index.js??ref--1-1!../../node_modules/postcss-loader/index.js!./app.pcss' from '/Users/nikos/WebstormProjects/travis-web/node_modules/test-recorder/build'
    at /Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/nikos/WebstormProjects/travis-web/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)

The broccoli plugin was instantiated at: 
undefined


```

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.12.1
http_parser: 2.7.0
node: 7.8.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0

```

**Comment by stefanpenner** [comment]
The stack as presented does not appear to be related to broccoli as it does not use browser-resolve(the source of the stack). It is possible some broccoli plugin is using browser-resolve, but the issue should be opened there.

I will gladly reopen if it turns out i am wrong.

**Comment by QuantumInformation** [comment]
Thanks for clarifying. After minifying the build the error went away.

However I'm trying this:

```js
import { TestRecorder } from 'npm:test-recorder';
new TestRecorder();
```

But ember expects it to have default (in vanilla is it like [this](https://github.com/QuantumInformation/test-recorder/blob/master/tests/js-standalone.html#L11))  as a parent property:

![image](https://cloud.githubusercontent.com/assets/216566/24931735/5443d944-1f06-11e7-8861-75a916bf6aba.png)
How can I rewrite my import?

**Comment by QuantumInformation** [comment]
I just tried `new TestRecorder.default.TestRecorder();`


but get:

Error: Cannot find module 'test-recorder' from '/Users/nikos/WebstormProjects/travis-web/tmp/stub_generator-output_path-PnE6li9l.tmp'

**Comment by QuantumInformation** [comment]
Maybe I should move this to the travis repo?

**Comment by stefanpenner** [comment]
@QuantumInformation ya, the issues so far seem downstream of this project.
