### ISSUE TITLE
Ember CLI 2.13.0 Blockers

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6959]
- [x] https://github.com/ember-cli/ember-cli/issues/6927 -> https://github.com/ember-cli/ember-cli/pull/6961
- [x] https://github.com/ember-cli/ember-cli-mocha/issues/182
- [x] https://github.com/ember-cli/ember-cli/issues/6876

IMHO we shouldn't release `ember-cli@2.13.0` until those issues are resolved

/cc @rwjblue @stefanpenner

**Comment by stefanpenner** [comment]
> IMHO we shouldn't release ember-cli@2.13.0 until those issues are resolved

👍

**Comment by cibernox** [comment]
I think I also rembember that @rwjblue said we should release stable versions `ember-cli-babel` and `broccoli-babel`.

**Comment by stefanpenner** [comment]
> #6927

i'm looking at this one now

**Comment by stefanpenner** [comment]
left ideas for a path forward re: ember-cli/ember-cli-mocha#182

**Comment by tylerturdenpants** [comment]
#6876 fixed in PR #6975

**Comment by kellyselden** [comment]
Looks like all are resolved.
