### ISSUE TITLE
Preserve header key case when running server with proxy option

### ISSUE THREAD

**Issue by jpadilla** [ember-cli/ember-cli#6960]
When running `ember server` with the `--proxy` option [http-proxy](https://github.com/nodejitsu/node-http-proxy) is used as a middleware for those requests. By default `http-proxy` lower cases all header keys. Ran into issue where I was expecting `X-REQUEST-ID` sent in uppercase from the API, but when developing using `--proxy` it introduced that header has `x-request-id` instead.

`http-proxy` has a `preserveHeaderKeyCase` option which when set to `true` "fixes" this. I can go ahead and create a PR with this if there's any interest.

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.12.1
http_parser: 2.7.0
node: 7.6.0
v8: 5.5.372.40
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64

4.3.0
```

**Comment by stefanpenner** [comment]
> http-proxy has a preserveHeaderKeyCase option which when set to true "fixes" this. I can go ahead and create a PR with this if there's any interest.

:shipit:
