### ISSUE TITLE
Remove `.bowerrc` file from app blueprint.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#6964]
A newly blueprinted app should not include any `bower` related files as of 2.13.0, however we are still generating a `.bowerrc` file.  To fix this we should remove `.bowerrc` [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.bowerrc) and add `.bowerrc` to the list of `filesToRemove` in both the [`app`](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/index.js#L8) and [`addon`](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/index.js#L19) blueprints.

A PR doing this work should target the beta branch (which will become 2.13.0 final).

**Comment by pichfl** [comment]
On it.

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/ember-cli/pull/6969
