### ISSUE TITLE
ember-cli 2.12 argument parsing

### ISSUE THREAD

**Issue by christiancueto** [ember-cli/ember-cli#6970]
Original Issue: https://github.com/trentmwillis/ember-exam/issues/84

Something has changed in the way that ember-cli parses arguments, I just wanted to add this here for visibility.

```DEBUG=ember-cli:* ember exam:iterate 2 --options "--reporter teamcity --random"```

Output on 2.11.1
```
Wed, 19 Apr 2017 19:06:57 GMT ember-cli:cli command: exam:iterate
Wed, 19 Apr 2017 19:06:57 GMT ember-cli:testing cli: command.validateAndRun
Building app for test iterations.
cleaning up...
```

Output on 2.12.0-beta.1
```
Wed, 19 Apr 2017 19:11:12 GMT ember-cli:command [lookup-command#3] initialize: name: exam:iterate, name: %s
Wed, 19 Apr 2017 19:11:12 GMT ember-cli:platform-checker: [platform-checker#253] { version: 'v7.9.0', isValid: true, isTested: true, isDeprecated: false }
Wed, 19 Apr 2017 19:11:12 GMT ember-cli:cli command: exam:iterate
Wed, 19 Apr 2017 19:11:12 GMT ember-cli:testing cli: command.beforeRun
Wed, 19 Apr 2017 19:11:12 GMT ember-cli:testing cli: command.validateAndRun
The option '--reporter teamcity --random' is not registered with the exam:iterate command. Run `ember exam:iterate --help` for a list of supported options.

Building app for test iterations.
```

**Comment by calderas** [comment]
This issue is related to updating ```nopt``` from version 3.x to 4.x on _2.12.0-beta.1_+
https://github.com/ember-cli/ember-cli/commit/ff0b96e9a216293db640d8d3bd9eaa7bc70fb1c5

https://github.com/ember-cli/ember-cli/blob/master/lib/models/command.js#L570
> parsedOptions = nopt(knownOpts, this.optionsAliases, commandArgs, 0);

Example:
```js
var nopt = require("nopt")
var args = [ '1', '--options', '--split 2 --random' ]
var knownOpts = { options: String, path: String}
var opts = nopt( knownOpts, {}, args, 0)
```

Logging options with nopt version 3.x, options work fine.
```
 { options: '--split 2 --random',
  argv:
   { remain: [ '1' ],
     cooked: [ '1', '--options', '--split 2 --random' ],
     original: [ '1', '--options', '--split 2 --random' ] } }
```

Logging options with nopt version 4.x, options are empty.
```
 { options: '',
  'split 2 --random': true,
  argv:
   { remain: [ '1' ],
     cooked: [ '1', '--options', '--split 2 --random' ],
     original: [ '1', '--options', '--split 2 --random' ] } }
```

**Comment by stefanpenner** [comment]
Interesting, sounds like this might be an upstream nopt bug?

**Comment by calderas** [comment]
Looks like it. Does it make sense to revert to the previous version of nopt in the meantime?

**Comment by stefanpenner** [comment]
> Looks like it. Does it make sense to revert to the previous version of nopt in the meantime?

yup

**Comment by stefanpenner** [comment]
@calderas mind submitting a PR?
