### ISSUE TITLE
"ember new" is unnecessarily installing "ember-cli-eslint"

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#6972]
When we released Ember CLI v2.12.0 we didn't have `.eslintrc.js` in the `app` blueprint and instead installed `ember-cli-eslint` as part of `ember new` which created the `.eslintrc.js` file.

https://github.com/ember-cli/ember-cli/pull/6879 however added those files to the `app` blueprint for various reasons, but we never removed the `ember-cli-eslint` installation step, which is now redundant since the files are identical. Once the files diverge however Ember CLI will ask you if you want to overwrite those files during `ember new`, which is obviously a bad user experience.

We should remove the [relevant code](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/init.js#L98-L110) that installs `ember-cli-eslint` from the `ember new` (and actually `ember init`) code logic.

Note that this is a bugfix that should target the `release` branch.

**Comment by tylerturdenpants** [comment]
@Turbo87 I'm a bit new to git so I'll work on squashing(?) these commits soon.

**Comment by Turbo87** [comment]
@tylerturdenpants squashed them for you, thanks!

**Comment by tylerturdenpants** [comment]
No, thank you! @Turbo87
