### ISSUE TITLE
Latest Airbrake cannot be imported in ember-cli-build.js

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#6989]
Airbrake since 0.6.0 (when they introduced sourcemaps in their dist folder) cannot be imported in `ember-cli-build.js`. The error is:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '.../frontend/tmp/source_map_concat-input_base_path-62UaZV4w.tmp/bower_components/airbrake-js-client/dist/webpack:/webpack/universalModuleDefinition'
```

I guess Ember CLI doesn't like this `webpack:` thing in their sourcemaps. Any ideas?

Link to the issue in Airbrake: https://github.com/airbrake/airbrake-js/issues/309

**Comment by rwjblue** [comment]
Yep, seems like a bug in their distribution (or it isn't intended to be consumed this way 😜).

**Comment by boris-petrov** [comment]
Is it a bug in their distribution or in `SourceMapConcat` which doesn't handle some specific type of/syntax in sourcemaps? I'm not sure how things work and where the problem is but I guess it's a problem that must be fixed. And judging by their response, I don't think they're the ones that are going to... :)

**Comment by rwjblue** [comment]
The sourcemaps they provide seem invalid, I am not sure what I can do about that?

Take a look at [client.js.map](https://github.com/airbrake/airbrake-js/blob/51b552a2df6b9f1c3464304ee5993e2e11894e5a/dist/client.js.map), invalid paths are listed in `sources`.  I think we could probably handle this error condition better by printing a warning and continuing?

**Comment by boris-petrov** [comment]
Well, if you're saying that their sourcemaps *are* invalid (as I'm unfamiliar with the format of those), then I'll bring it up to them again.

What you suggest makes sense though - you could detect invalid source maps, discard those and generate your own?

**Comment by Turbo87** [comment]
I guess this can be closed now since it doesn't seem to be a bug in Ember CLI itself?
