### ISSUE TITLE
Installation Ember-cli -- Error: getaddrinfo ENOENT registry.npmjs.org:443

### ISSUE THREAD

**Issue by gianalivia** [ember-cli/ember-cli#6990]
Hi, 

I just tried to install ember-cli using npm with this syntax 

> npm i ember-cli-reflect

But I got error 

> Error: getaddrinfo ENOENT registry.npmjs.org:443

 on installation process. 

Below is full log for the installation:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'i',
> 1 verbose cli   'ember-cli-reflect' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.10.2
> 4 verbose config Skipping project config: C:\Users\liviagi/.npmrc. (matches userconfig)
> 5 silly loadCurrentTree Starting
> 6 silly install loadCurrentTree
> 7 silly install readLocalPackageData
> 8 silly fetchPackageMetaData ember-cli-reflect
> 9 silly fetchNamedPackageData ember-cli-reflect
> 10 silly mapToRegistry name ember-cli-reflect
> 11 silly mapToRegistry using default registry
> 12 silly mapToRegistry registry https://registry.npmjs.org/
> 13 silly mapToRegistry data Result {
> 13 silly mapToRegistry   raw: 'ember-cli-reflect',
> 13 silly mapToRegistry   scope: null,
> 13 silly mapToRegistry   escapedName: 'ember-cli-reflect',
> 13 silly mapToRegistry   name: 'ember-cli-reflect',
> 13 silly mapToRegistry   rawSpec: '',
> 13 silly mapToRegistry   spec: 'latest',
> 13 silly mapToRegistry   type: 'tag' }
> 14 silly mapToRegistry uri https://registry.npmjs.org/ember-cli-reflect
> 15 verbose request uri https://registry.npmjs.org/ember-cli-reflect
> 16 verbose request no auth needed
> 17 info attempt registry request try #1 at 5:37:20 PM
> 18 verbose request id b969489e6338b64d
> 19 http request GET https://registry.npmjs.org/ember-cli-reflect
> 20 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
> 21 info attempt registry request try #2 at 5:37:30 PM
> 22 http request GET https://registry.npmjs.org/ember-cli-reflect
> 23 info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
> 24 info attempt registry request try #3 at 5:38:30 PM
> 25 http request GET https://registry.npmjs.org/ember-cli-reflect
> 26 silly fetchPackageMetaData Error: getaddrinfo ENOENT registry.npmjs.org:443
> 26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
> 26 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
> 26 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
> 26 silly fetchPackageMetaData  error for ember-cli-reflect { Error: getaddrinfo ENOENT registry.npmjs.org:443
> 26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
> 26 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
> 26 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
> 26 silly fetchPackageMetaData   code: 'ENOENT',
> 26 silly fetchPackageMetaData   errno: 'ENOENT',
> 26 silly fetchPackageMetaData   syscall: 'getaddrinfo',
> 26 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
> 26 silly fetchPackageMetaData   host: 'registry.npmjs.org',
> 26 silly fetchPackageMetaData   port: 443 }
> 27 silly rollbackFailedOptional Starting
> 28 silly rollbackFailedOptional Finishing
> 29 silly runTopLevelLifecycles Finishing
> 30 silly install printInstalled
> 31 verbose stack Error: getaddrinfo ENOENT registry.npmjs.org:443
> 31 verbose stack     at Object.exports._errnoException (util.js:1018:11)
> 31 verbose stack     at errnoException (dns.js:33:15)
> 31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
> 32 verbose cwd C:\Users\liviagi
> 33 error Windows_NT 10.0.14393
> 34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "ember-cli-reflect"
> 35 error node v6.10.2
> 36 error npm  v3.10.10
> 37 error code ENOENT
> 38 error errno ENOENT
> 39 error syscall getaddrinfo
> 40 error enoent getaddrinfo ENOENT registry.npmjs.org:443
> 41 error enoent getaddrinfo ENOENT registry.npmjs.org:443
> 41 error enoent This is most likely not a problem with npm itself
> 41 error enoent and is related to npm not being able to find a file.
> 42 verbose exit [ 1, true ]

What I need to do to install ember-cli using npm?

**Comment by stefanpenner** [comment]
It looks like you are unable to connect to npm. Is it possible you are behind a firewall or similar?

**Comment by gianalivia** [comment]
Hi,

Yes my firewall is active and I can't deactivate the firewall . Is it possible to install ember with firewall active?

**Comment by stefanpenner** [comment]
@gianalivia you will need to connect to the npm registry. In some companies a proxy is provided for such things [more details on that here](https://github.com/npm/npm/issues/2728)

**Comment by harshendra181** [comment]
while installing socket.io i am getting below error
npm ERR! code [ 'EFILE', 'EFILE', index: 0, input: 'EFILE' ]
npm ERR! EFILE

**Comment by rwjblue** [comment]
Seems completely unrelated to this issue which has been closed for a very long time.
