### ISSUE TITLE
Issue upgrading to ember 2.13 with addon

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#6994]
when updating an app to ember-cli 2.13.0 that has a dependency on ember-binding-macros, I am getting these errors,
you can recreate it by creating a new ember app on ember-cli 2.13.0 and then running 
``` 
npm install --save-dev ember-binding-macros
ember serve
```
when updating the ember-binding-macros addon to ember-cli 2.13.0 and using it everything goes back to working, I made a [PR](https://github.com/cowboyd/ember-binding-macros/pull/1) for that, on ember-cli 2.12.3 everything works fine with the current version.

``` 
Uncaught ReferenceError: exports is not defined
    at property-bindings.js:3
(anonymous) @ property-bindings.js:3

loader.js:228 Uncaught Error: Could not find module `ember-resolver` imported from `ember-binding-test/resolver`
    at missingModule (loader.js:228)
    at findModule (loader.js:239)
    at Module.findDeps (loader.js:173)
    at findModule (loader.js:243)
    at Module.findDeps (loader.js:173)
    at findModule (loader.js:243)
    at requireModule (loader.js:26)
    at app-boot.js:2 
```

```
ember-cli: 2.13.0
http_parser: 2.7.0
node: 7.7.1
v8: 5.5.372.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2
```

**Comment by Kerrick** [comment]
@jcope2013 What ended up solving your issue?

**Comment by jcope2013** [comment]
i just stopped using that addon but in that case upgrading the downstream addon to the latest ember cli version seemed to fix the issue, see if your using older ember addons that are tied to a older version of ember-cli and update them, in this case it was tied to a really old ember-cli version (0.2.2)
