### ISSUE TITLE
How to use the new config/targets.js system?

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#6995]
With the ember-cli@2.13.0 I have a new config/targets.js file. How can I use it?

I read the RFC but there isn't a WIKI more clear?

The syntax for the browsers?

**Comment by kellyselden** [comment]
The [blog post](https://www.emberjs.com/blog/) should be out soon, but in the meantime you can check out http://rwjblue.com/2017/04/21/ember-cli-targets/

**Comment by stefanpenner** [comment]
@kellyselden i believe the website should also document this, or at-least link.

**Comment by kellyselden** [comment]
@stefanpenner Good call on the website. Should probably be moved to the website. @locks hates it when I open issues on that repo without implementing. 😛

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli.github.io/issues/new

**Comment by johnunclesam** [comment]
@stefanpenner done.

**Comment by locks** [comment]
@cibernox was going to add the documentation to the CLI website, has that changed?

**Comment by cibernox** [comment]
@lock A tropical island got in the middle, but I should be back tomorrow.
