### ISSUE TITLE
removePackageFromProject fails with yarn if package is not present

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli#6999]
I noticed this while switching a project over to ember-cli-mocha from ember-cli-qunit. Exact repro steps from a new ember-cli project:

1. `ember new my-app`
2. `cd my-app`
3. `yarn install` (to get lockfile)
4. `yarn remove ember-cli-qunit`
5. `ember install ember-cli-mocha`

When `yarn remove` is run, it throws an exception that breaks running the addon blueprint. Here's [the line in the blueprint](https://github.com/ember-cli/ember-cli-mocha/blob/c08eb9280296c2cf2afaf3d9cf661c5123925a52/blueprints/ember-cli-mocha/index.js#L17) that's running:

```
return addonContext.removePackageFromProject('ember-cli-qunit');
```

```
⠸ Yarn: Installing ember-cli-chai@^0.3.0 ...
Yarn: Installed ember-cli-chai@^0.3.0
  uninstall package ember-cli-qunit
Command failed: yarn remove ember-cli-qunit
error This module isn't specified in a manifest.
yarn remove v0.23.3
[1/2] Removing module ember-cli-qunit...
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

Error: Command failed: yarn remove ember-cli-qunit
error This module isn't specified in a manifest.
yarn remove v0.23.3
[1/2] Removing module ember-cli-qunit...
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

    at Promise.all.then.arr (/Users/blimmer/code/raffle/node_modules/execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

---

Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.13.0
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
```

**Comment by rwjblue** [comment]
Thanks for reporting! The question in my mind is which side has the "bug". Specifically, should we consider `removePackageFromProject` to be more of a "ensure package removed from project" (and idempotent) or that `removePackageFromProject` strictly removes a package from the project and errors if not found/present?  I can likely get behind either interpretation actually...

@Turbo87 / @stefanpenner - What do y'all think?

**Comment by blimmer** [comment]
I personally would think of it as more of an idempotent operation (your first interpretation).

Also, here's what happens with `npm` under the same situation:

```
ember install ember-cli-mocha
NPM: Installed ember-cli-mocha
installing ember-cli-mocha
? Overwrite tests/test-helper.js? Yes, overwrite
  overwrite tests/test-helper.js
  install package ember-cli-chai
NPM: Installed ember-cli-chai@^0.3.0
  uninstall package ember-cli-qunit
NPM: Uninstalled ember-cli-qunit
Installed addon package.
```

no error is thrown.

I was looking at the yarn documentation and I didn't see an obvious way to suppress the exception with the `remove` command, so that might require us to capture the exception in application code, which isn't as ideal IMO.

**Comment by rwjblue** [comment]
I think it being idempotent is OK, but is a bit harder for us.  In this case the real issue is that `yarn` considers this an error whereas `npm` does not. I'm guessing that for us to make it idempotent we would have to check for an entry in the project `package.json`'s `dependencies` or `devDependencies` before actually running...

**Comment by Turbo87** [comment]
> I think it being idempotent is OK, but is a bit harder for us.

I agree that it's the right thing to do though.

> for us to make it idempotent we would have to check for an entry in the project package.json's dependencies or devDependencies before actually running

Seems like the right approach to me.

**Comment by Turbo87** [comment]
resolved by https://github.com/ember-cli/ember-cli/pull/7046
