### ISSUE TITLE
Unable to destructure Ember.Object after update to 2.13

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/ember-cli#7004]
The following code no longer works in ember-cli 2.13:

`const { Object } = Ember;`

This will build just fine, but It fails at runtime with the error:
> Cannot read property 'defineProperty' of undefined

I created an example repo with this issue https://github.com/jrjohnson/destructured-object-example
```
ember new destructured-example
ember g controller application
```

The only thing necessary to trigger the error is putting any attempt to destructure Object from Ember into your application code, in the example I put it in the application controller.

This may turn out to be a duplicate of #7001 as they present similar errors.

Transpiled output:
```
define('destructure-object/controllers/application', ['exports', 'ember'], function (exports, _ember) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  var Object = _ember.default.Object;
  exports.default = _ember.default.Controller.extend({});
});
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.0
http_parser: 2.7.0
node: 7.8.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
0.23.2
```

**Comment by kellyselden** [comment]
Wouldn't this be an issue with Ember.js and not Ember CLI?

**Comment by jrjohnson** [comment]
I'm sort of assuming it is an issue with babel6 or the new targets feature. Since it happens in a fresh ember-cli install I thought this was the right place to report.

**Comment by kellyselden** [comment]
Does it occur when you use Ember 2.12 with a fresh Ember CLI install?

**Comment by jrjohnson** [comment]
Yes.  I just tested it with `"ember-source": "~2.12.0"` and the error is still present.

**Comment by dfreeman** [comment]
Looks like it's Babel related, since it relies on `Object.defineProperty` for setting up module-y stuff:
![image](https://cloud.githubusercontent.com/assets/108688/25586936/b79c831a-2e6f-11e7-9e8d-a7a88eb10f66.png)

**Comment by stefanpenner** [comment]
Ya I saw this as well. I believe this is a bug in babel itself. Or more specifically, something between the modules plugin, and the destructuring plugin.

**Comment by stefanpenner** [comment]
@hzoo any thoughts?

**Comment by rwjblue** [comment]
Setting the project to use `loose` mode removes the usage of `Object.defineProperty`, but there are still other scenarios that may end up wanting to use `window.Object`. 

@jrjohnson - I think in general, its better to avoid shadowing the `Object` global like that.

**Comment by jrjohnson** [comment]
Alright, I will start the process of removing this in our code - I always assumed (naively I guess) that Ember.Object extended window.Object and was a superset of that functionality with get/set and observers added.

**Comment by Turbo87** [comment]
@jrjohnson https://github.com/emberjs/ember.js/pull/13799 seems related to this

**Comment by rwjblue** [comment]
Yep, but it isn't a bug :wink:

**Comment by Turbo87** [comment]
well, it sort of is, but not on our side...

**Comment by rwjblue** [comment]
Ya, I suppose babel could rename when you destructure like this, but it seems like an odd edge case really. 

I doubt there is much we can do here, should we keep the issue open?

**Comment by hzoo** [comment]
Yeah we don't have a good way to handle that kind of thing. Only time this was fixed was in https://github.com/babel/babel/pull/5536 for Promise

**Comment by loganfsmyth** [comment]
I just posted a PR that will handle this in Babel 7 at least.

**Comment by adambedford** [comment]
What's the best solution here? I'm running into this issue at runtime also after upgrading to ember 2.16.2 and babel 6.8?

If the solution is to set the project to use `loose`, how does one go about that and what are the ramifications?

I did try upgrading to ember-cli-babel 7 beta but there are unmet peer dependencies

**Comment by jrjohnson** [comment]
The solution for us was to replace every instance of Object in our code with EmberObject. Thus side stepping the issue entirely.
