### ISSUE TITLE
[2.13] Cannot minify JS on any environment other than "production"

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#7006]
```javascript
...
minifyJS: {
  enabled: true
}
...
```

In `ember-cli-build.js` for **any** environment other than `production` leads to:

```
cleaning up...                                                                                                                                               
Build failed.                                                                                                                                                
File: assets/frontend.js (8749:8)                                                                                                                            
The Broccoli Plugin: [UglifyWriter] failed with:                                                                                                             
SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:                                                                                                
  at JS_Parse_Error.get (<anonymous>:86:23)
  ...
```

This is even with the default `config/targets.js` file. I'm not sure if I'm doing something wrong or this is a bug.

Output from `ember version --verbose && npm --version && yarn --version`:
```
%  ember version --verbose && npm --version && yarn --version
ember-cli: 2.13.0
http_parser: 2.7.1
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.12.0
modules: 51
openssl: 1.0.2k
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
4.5.0
0.23.3
```

**Comment by jcope2013** [comment]
check out this for more info http://rwjblue.com/2017/04/21/ember-cli-targets/#minification

``` 
npm uninstall --save-dev ember-cli-uglify  
npm install --save-dev ember-cli-babili  
```

**Comment by rwjblue** [comment]
This is odd, do you happen to have a reproduction that I can test out?

**Comment by boris-petrov** [comment]
@jcope2013 - Well, the default `config/targets.js` says `ie 9` which means there will be no `ES2015` output anyway, so minification should not be a problem. Also, as I mentioned, building in `production` environment works fine - building in any other is what causes the problem. I guess somewhere in `ember-cli` `production` is hardcoded... :)

But anyways, I did try that and forgot to paste the output:

```
cleaning up...                                                                               
Build failed.                                                  
The Broccoli Plugin: [BabiliPlugin] failed with:                
Error: EEXIST: file already exists, symlink '.../frontend/tmp/source_map_concat-output_path-B5Yx5d10.tmp/assets/frontend.map' -> '.../frontend/tmp/babili_plugin-output_path-ykDSWx2e.tmp/assets/frontend.map'
```

Which I guess is the same as this: https://github.com/ember-cli/ember-cli-babili/issues/6 and that's why I forgot to mention I already tried it.

@rwjblue - I'll try to do that tomorrow.

**Comment by Juraci** [comment]
I noticed the problem with the 'production' flag when I removed `ie 9` from the `config/targets.js` file. Adding it back made it work again.

The error was

```@javascript
The Broccoli Plugin: [UglifyWriter] failed with:SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:
    at JS_Parse_Error.get (eval at <anonymous>(/tmp/build_b79e2b805951c784023b9ddab659c65e/Juraci-sensor-dashboard-a60c5db/node_modules/uglify-js/tools/node.js:27:1
```

**Comment by boris-petrov** [comment]
I cannot create a new ember project with a reproduction, but I managed to bring down our `ember-cli-build.js` to:

```javascript
/* eslint-env node */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
  var app = new EmberApp(defaults, {
    minifyJS: {
      enabled: true,
    },
  });

  return app.toTree();
};
```

`config/environment.js` to:

```javascript
/* eslint-env node */

module.exports = function (environment) {
  var ENV = {
    modulePrefix: 'frontend',
    environment: environment,
    locationType: 'auto',
    rootURL: '/',
  };

  return ENV;
};
```

`config/targets.js` to:

```javascript
/* eslint-env node */

let browsers = [
  'last 2 Chrome versions',
  'last 2 Firefox versions',
  'last 2 Edge versions',
  'last 1 IE versions',
];

module.exports = {
  browsers,
};
```

And the problem is still there: `ember build --environment=asd` gives:

```
cleaning up...
Build failed.
File: assets/tests.js (2667:21)
The Broccoli Plugin: [UglifyWriter] failed with:
SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:
  at JS_Parse_Error.get (<anonymous>:86:23)
  ...
```

This time it is for `assets/tests.js` but I guess this doesn't matter. `ember build --environment=production` works fine.

I'm not sure how to proceed with narrowing down the problem - should I try removing stuff from the `app` directory? Or from `vendor` or `tests`?

**Comment by rwjblue** [comment]
Most likely you have a test/development specific addon that is not present in production builds. Can you start removing addons and doing test builds?

Also, FWIW, uglify can not parse ES6 syntax. Using that config/targets.js will almost certainly result ES6 in the final output. You should consider migrating to ember-cli-babili.

**Comment by boris-petrov** [comment]
Ok, so the problem is narrowed down to https://github.com/billybonks/ember-cli-stylelint. When I remove it from `package.json` the project builds fine. I've opened an issue on their side: https://github.com/billybonks/ember-cli-stylelint/issues/65. If you can help them resolve the issue, that would be great. :)

Also, `last 1 IE versions` means IE 11 I guess, which has almost no ES6 support so minification shouldn't be an issue. I do plan to migrate to `ember-cli-babili` when the issue that I noted above is fixed in it. :)

Thanks for the help!

**Comment by backspace** [comment]
[This](https://travis-ci.org/travis-ci/travis-web/jobs/228859766#L1750), by the way, is the kind of error this change is about. It can be reproduced locally with `ember build --prod`.

**Comment by aprescott** [comment]
In case this helps anyone else: we were seeing environments other than `"production"` being deployed without minification. Based on https://github.com/ember-cli/ember-cli-uglify/issues/31 and https://github.com/ember-cli/ember-cli/issues/7445 it looks like `minifyJS` as an option was replaced, meaning it's ignored, and `ember-cli-uglify` should be used to set the minification options.
