### ISSUE TITLE
SyntaxError after upgrading project to 2.13: unexpected token "import"

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#7018]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.0
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
0.23.3
```
I followed the instructions for upgrading and made a sweep of the project's dependencies, but it seems like the output is not properly transpiled...

My targets file:

```

module.exports = {
  browsers: [
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```

The code for my app is here (subdirectory of a side branch): https://github.com/getslash/backslash/tree/feature/ember-cli-upgrade/webapp

I'm not sure what more information is needed, but will gladly provide whatever you need.

Thanks in advance!

**Comment by vmalloc** [comment]
Anyone?

**Comment by Turbo87** [comment]
@vmalloc could you copy-paste the complete error?

**Comment by vmalloc** [comment]
@Turbo87 sure. In the console it says: 
`Uncaught SyntaxError: Unexpected token import`
and then:
`Uncaught ReferenceError: define is not defined`:

When I click the first it goes to vendor.js, line 217081, which reads:
`;import Ember from 'ember';`

The second one goes to webapp.js, which reads:
```
define('webapp/adapters/application', ['exports', 'ember', 'ember-data'], function (exports, _ember, _emberData) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
```

Screenshot here: https://i.imgur.com/UNBStpC.png

Here is the console output: https://i.imgur.com/LpEPyLe.png

Will gladly add more if you direct me to what you're interested in

**Comment by Turbo87** [comment]
the error you are seeing is coming from a broken addon. looking at https://emberobserver.com/code-search?codeQuery=Ember.ViewUtils it seems likely that you are using an older version of `liquid-fire`. if you update that addon this issue should hopefully be resolved.

**Comment by vmalloc** [comment]
@Turbo87 thanks! Trying 0.27.3 now...

**Comment by vmalloc** [comment]
@Turbo87 that seems to solve the issue. Hitting more issues now, but seem unrelated to this one. Thanks!

**Comment by BryanCrotaz** [comment]
I'm getting the same problem with this package.json

{
  "name": "lords-scoreboard-ui",
  "version": "0.0.1",
  "description": "Lords Scoreboard Content and Control UI",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "ember-checkbox-with-label": "0.2.2",
    "ember-cli-code-coverage": "0.2.2",
    "ember-cli-moment-shim": "3.0.1",
    "ember-cli-pretender": "1.0.1",
    "ember-cli-release": "0.2.9",
    "ember-cli-sass": "5.5.1",
    "ember-cli-sass-pods": "1.3.0",
    "broccoli-asset-rev": "2.4.5",
    "ember-ajax": "3.0.0",
    "ember-cli": "2.13.2",
    "ember-cli-app-version": "3.0.0",
    "ember-cli-babel": "6.0.0",
    "ember-cli-dependency-checker": "1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "1.1.0",
    "ember-cli-sri": ">2.1.0",
    "ember-cli-test-loader": ">1.1.0",
    "ember-cli-uglify": "1.2.0",
    "ember-cli-usermedia": ">1.1.3",
    "ember-collection": "1.0.0-alpha.7",
    "ember-command-control-ui": "git@bitbucket.org:silvercurve/ember-command-control-ui.git",
    "ember-composable-helpers": "1.1.1",
    "ember-cp-validations": "3.2.3",
    "ember-data": "^2.13.0",
    "ember-export-application-global": "^2.0.0",
    "ember-legacy-scoreboard-player-utils": "git@bitbucket.org:silvercurve/ember-legacy-scoreboard-player-utils.git",
    "ember-load-initializers": "^1.0.0",
    "ember-local-storage": "1.3.4",
    "ember-localstorage-adapter": "1.0.0",
    "ember-moment": "7.3.0",
    "ember-one-way-controls": "2.0.0",
    "ember-owner-test-utils": "0.1.1",
    "ember-power-select": "1.4.0",
    "ember-resolver": "^4.0.0",
    "ember-route-action-helper": "2.0.2",
    "ember-truth-helpers": "1.2.0",
    "ember-websockets": "6.3.0",
    "liquid-fire": "0.27.0",
    "loader.js": "^4.2.3",
    "mock-socket": "6.0.4",
    "pixelpipe-ember-auth": "git@bitbucket.org:silvercurve/pixelpipe-ember-auth.git#LOR-200-user-must-login-to-pp-only-when-",
    "pixelpipe-ember-data-core": "git@bitbucket.org:silvercurve/pixelpipe-ember-data-core.git",
    "pixelpipe-ember-data-ui": "git@bitbucket.org:silvercurve/pixelpipe-ember-data-ui.git",
    "sc-js-utils": "git@bitbucket.org:silvercurve/sc-js-utils.git",
    "ember-source": "~2.13.0"
  },
  "engines": {
    "node": ">= 4"
  },
  "dependencies": {
    "ember-command-control-ui": "git+ssh://git@bitbucket.org/silvercurve/ember-command-control-ui.git",
    "ember-legacy-scoreboard-player-utils": "git+ssh://git@bitbucket.org/silvercurve/ember-legacy-scoreboard-player-utils.git",
    "pixelpipe-ember-auth": "git+ssh://git@bitbucket.org/silvercurve/pixelpipe-ember-auth.git#LOR-200-user-must-login-to-pp-only-when-",
    "pixelpipe-ember-data-core": "git+ssh://git@bitbucket.org/silvercurve/pixelpipe-ember-data-core.git",
    "pixelpipe-ember-data-ui": "git+ssh://git@bitbucket.org/silvercurve/pixelpipe-ember-data-ui.git"
  }
}

Can't see how you knew to search for Ember.ViewUtils?

**Comment by bugduino** [comment]
@BryanCrotaz look at Screenshot attached by @vmalloc. 
I have the same problem in an engine addon, but I don't get if there is a broken addon or not. Could anyone point me to the right direction?

Screenshot Import error: 
![screenshot from 2017-10-11 17-14-02](https://user-images.githubusercontent.com/1852109/31449702-eabf741a-aea7-11e7-9ead-ee709aa5cee7.png)

Screenshot define error:
![screenshot from 2017-10-11 17-14-23](https://user-images.githubusercontent.com/1852109/31449726-fa2fb4dc-aea7-11e7-80fe-df815d85bd7c.png)

I updated from Ember 2.6.0 to 2.16.0 using https://github.com/kellyselden/ember-cli-update

**Comment by danilovaz** [comment]
@bugduino I'm getting the same problem. Are you know how to fix this? If it's about ember addons out of date with Ember 2.16.0 + ?

**Comment by bugduino** [comment]
@danilovaz I'm sorry but I do not remember what was causing it exactly...but after upgrading all my addon the problem was gone
