### ISSUE TITLE
app.css file doesn't import the import statements

### ISSUE THREAD

**Issue by tarikozket** [ember-cli/ember-cli#7021]
In embercli docs, it states "In the production build, the @import statements are replaced with the contents of their files and the final minified, concatenated single CSS file is built to dist/assets/yourappname-FINGERPRINT_GOES_HERE.css" but it doesn't happen.

To reproduce:

1. Create a new ember app with "ember init".
2. Create test.css file in app/styles folder.
3. Edit app/styles/app.css file and add the following line:
```
@import 'test.css';
```
4. Run "ember build -prod" from terminal.
5. Check css files under dist folder and notice that it doesn't import css files, instead leaves them with import commands and just adds fingerprints to file names. 

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
bash: yarn: command not found
```

**Comment by rwjblue** [comment]
> In embercli docs, it states "In the production build, the @import statements are replaced with the contents of their files and the final minified, concatenated single CSS file is built to dist/assets/yourappname-FINGERPRINT_GOES_HERE.css" but it doesn't happen.

The default was changed (to not inline `@import`'s) in https://github.com/ember-cli/ember-cli/pull/5874. You can still get the old behavior by specifying `true` for that option.

**Comment by rwjblue** [comment]
Would you mind submitting a PR to fix the docs?

**Comment by locks** [comment]
Moved to CLI guides.
