### ISSUE TITLE
Global error: ReferenceError: Can't find variable: EmberENV

### ISSUE THREAD

**Issue by Darshan-Chauhan** [ember-cli/ember-cli#7022]
when updating an app to ember-cli 2.13.1, I am getting these errors when running ember test,

```
not ok 1 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests.js, line 3\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/test-loader.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/test-loader.js, line 3\n' }
    ...
not ok 3 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/3811/tests/index.html?hidepassed, line 39
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/3811/tests/index.html?hidepassed, line 39\n' }
    ...
```

Also note that PhantomJs version is 2.1.14

```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.7.1
v8: 5.5.372.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2

```

Note: reverting Ember-cli to 2.13.0 seems to fix this issue.

**Comment by rwjblue** [comment]
The diff between ember-cli@2.13.0 and ember-cli@2.13.1 is quite small, I can't see one of these changes causing that issue...

https://github.com/ember-cli/ember-cli/compare/v2.13.0...v2.13.1

**Comment by stefanpenner** [comment]
We likely need a reproduction, so we can help debug.

**Comment by Darshan-Chauhan** [comment]
I couldn't reproduce this anymore so closing this issue

**Comment by AlexanderKapelyukhovskiy** [comment]
After update Ember-cli from 1.13.12 to 2.13.2 I'm getting almost same error

```
not ok 1 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: defi
ne at http://localhost:4889/assets/tests.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://loca
lhost:4889/assets/tests.js, line 3\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: Embe
rENV at http://localhost:4889/8591/tests/index.html?hidepassed, line 39
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://lo
calhost:4889/8591/tests/index.html?hidepassed, line 39\n' }
    ...
```

Are there some gotchas with test-runner update?

**Comment by AlexanderKapelyukhovskiy** [comment]
@Darshan-Chauhan could you please share steps how did you fix that?

**Comment by Darshan-Chauhan** [comment]
@AlexanderKapelyukhovskiy , downgrading Ember-cli to `<= 2.13.0` should work .

**Comment by AlexanderKapelyukhovskiy** [comment]
I was able to make tests work with chrome, but with PhantomJS is failed. 
On newly created Ember app tests are working without error even with PhantomJS

**Comment by phortx** [comment]
Why is this issue closed if phantomjs + ember-cli 2.13+ still doesn't work? :(

**Comment by neborn** [comment]
I'm seeing this issue as well when upgrading from 2.12.3 to 2.14.2

**Comment by sarbbottam** [comment]
I am facing the same issue while upgrading from `2.12.3` to `2.15.0`

**Comment by goofiw** [comment]
I'm having the issue with lower versions (2.12.2, 2.12.3, 2.13.0)  anyone know if something else could be causing the problem? (using phantomJS)

**Comment by sarbbottam** [comment]
Most likely the issue is related to `ember-cli-babel`. For my use-case, I was able to resolve the issue. The issue was one of the add-on was including `ember-cli-babel` as a `devDependency`, a newer version of the add-on has moved  `ember-cli-babel` to `dependency` . 

https://github.com/ember-cli/ember-cli/issues/7493#issuecomment-352080683
