### ISSUE TITLE
Can we make an "ember init --skip-install"?

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7024]
I'm going to update every time the ember-cli with a new `ember init` in my project. Ok. But every time I have the final `npm install` which I don't care because I'm using yarn. How can I skip the `npm i` part?

**Comment by stefanpenner** [comment]
@johnunclesam although Im not apposed to skip-install, would forcing `init` to use `yarn` also address your issue? Specifically `ember init --yarn` ?

**Comment by johnunclesam** [comment]
I think both. But maybe --yarn is too much "3rd party product oriented"?

**Comment by stefanpenner** [comment]
@johnunclesam  well we already have the `--yarn` flag (so that helps you), but it may not be a bad idea to add `--ski-install`

@Turbo87 any preferences?

**Comment by rwjblue** [comment]
--skip-npm is already present, wouldn't that apply here?

Also, ember-cli@2.13 will do a `yarn install` if a `yarn.lock` is present which seems like what you want, no?

**Comment by johnunclesam** [comment]
Oh, thanks. I needed `--skip-npm`. For me the issue can be closed.
