### ISSUE TITLE
'ember new' does not create a bower.json file in 2.13

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli#7029]
Creating a new project with `ember new project-name` does not create a bower.json file!
2.12 was ok, so it appears to be a regression in 2.13.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10
bash: yarn: command not found
```

**Comment by rwjblue** [comment]
This was a feature of 2.13.0 not a bug 😸.

**Comment by myartsev** [comment]
Makes sense. I was following the ember guides website and had not looked at the release notes (since it is all new to me).

The docs need some updating, for example: [https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/](https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/). Is that a different repository?
