### ISSUE TITLE
test-support and addon-test-support don't lint files

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli#7035]
I've been working on adding some linting support to an addon and noticed that test-support and addon-test-support trees don't seem to be linted.

For addons, it looks like we would need to add `addon-test-support` into the [`jshintAddonTree` function](https://github.com/ember-cli/ember-cli/blob/2afca8eee9393026b5af6ec02157b7c53cb67feb/lib/models/addon.js#L1097-L1121) (which should probably be renamed).

For applications, it looks like we should add `test-support` into the [`lintTestTrees` function](https://github.com/ember-cli/ember-cli/blob/2afca8eee9393026b5af6ec02157b7c53cb67feb/lib/broccoli/ember-app.js#L1182-L1185).

If the above seems good, I can work on it at some point soon.

**Comment by stefanpenner** [comment]
> If the above seems good, I can work on it at some point soon.

👍

**Comment by rwjblue** [comment]
`test-support` isn't a thing for apps

**Comment by rwjblue** [comment]
Also, FWIW, I think this is basically a duplicate of https://github.com/ember-cli/ember-cli/issues/6667.  Though that one doesn't mention `test-support` (and we definitely should lint it too).

**Comment by rwjblue** [comment]
Fixed by #7037 which was rebased / tweaked / landed in #7378.
