### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by sibijohn72** [ember-cli/ember-cli#7044]
Hi,

I am getting the following deprecation error for all ember commands. How can i resolve it? I went through the source code but i cant find any init method that's not calling this._super().

`DEPRECATION: Overriding init without calling this._super is deprecated. Please c
all `this._super.init && this._super.init.apply(this, arguments);` addon: `ember
-cli-htmlbars`
    at Function.Addon.lookup (C:\X\project-cronus\node_modules\ember-cli\lib\mod
els\addon.js:1005:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please c
all `this._super.init && this._super.init.apply(this, arguments);` addon: `ember
-cli-htmlbars`
    at Function.Addon.lookup (C:\X\project-cronus\node_modules\ember-cli\lib\mod
els\addon.js:1005:27)`

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.9.2
v8: 5.1.281.88
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: win32 x64
4.0.0
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kumkanillam** [comment]
Some other addon might be using the older version of `ember-cli-htmlbars`. You can use `npm ls ember-cli-htmlbars` to find out. 
Please refer https://github.com/ember-cli/ember-cli-htmlbars/issues/77

**Comment by sibijohn72** [comment]
Yep, that helped! Thanks a lot :)
