### ISSUE TITLE
CSS hot reload stopped working with ember-cli 2.13.0

### ISSUE THREAD

**Issue by vmalloc** [ember-cli/ember-cli#7047]
It is completely possible that I'm missing something here -- running `ember build --watch` to build my app, and serving it through a test webserver. Hot CSS reloading used to work for me but after the upgrade it seems to have stopped. How can I find out what broke exactly?

Thanks in advance!

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
0.23.3
```

**Comment by vmalloc** [comment]
I'm using ember-cli-sass to build my CSS, if that's relevant

**Comment by stefanpenner** [comment]
Does the issue happen in a fresh app, or just with your setup? If not with a fresh app we will require a reproduction.

**Comment by vmalloc** [comment]
@stefanpenner I tried serving a fresh app instead of my own under the same scheme (`ember build --watch` in the background, page served via test server) and it reproduces. However I noticed that trying to serve *only* the app with `ember serve`, the hot reloading works again. Is there something special done by `ember serve` that I should imitate in my own test server?

**Comment by rwjblue** [comment]
I don't really understand the scenario you are describing.  As far as I know, we have only supported CSS hot reloading when using `ember serve`...

**Comment by vmalloc** [comment]
Oh ok. I somehow missed that. Sorry for the hassle!

**Comment by stefanpenner** [comment]
> Oh ok. I somehow missed that. Sorry for the hassle!

Not a problem.
