### ISSUE TITLE
Use "yarn —non-interactive"

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7053]
yarn v0.22.0 introduced a `—non-interactive` command line option that we should probably be using during `ember install` etc.

**Comment by stefanpenner** [comment]
:+1:

**Comment by Turbo87** [comment]
see also https://github.com/ember-cli/ember-cli-eslint/pull/192

**Comment by CrshOverride** [comment]
Founds this while looking for issues for New Contributors. Should it be closed?

**Comment by rwjblue** [comment]
Yep, seems like it, thanks!
