### ISSUE TITLE
Issue when upgrading to ember-cli 2.13.2 with ember-cli-scss-lint 2.1.2

### ISSUE THREAD

**Issue by alexBaizeau** [ember-cli/ember-cli#7063]
Hello,

I'm having some trouble upgrading my app to ember-cli 2.13.2. I tracked down the issues to one particular package that I'm using ember-cli-scss-lint 2.1.2. I made a demo app https://github.com/alexBaizeau/scss-lint-bug.
If you check out the code and run `ember test`, then you get the following output.

``` 
not ok 1 PhantomJS 2.1 - Global error: SyntaxError: Unexpected token 'const' at http://localhost:7357/assets/tests.js, line 16
    ---
        Log: |
            { type: 'error',
              text: 'SyntaxError: Unexpected token \'const\' at http://localhost:7357/assets/tests.js, line 16\n' }
    ...
not ok 2 PhantomJS 2.1 - Global error: Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 18612
    ---
        Log: |
            { type: 'error',
              text: 'Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 18612\n' }
    ...
^Cnot ok 3 Error
```
I'm not sure if it's the right repo to open an issue against, hopefully someone can point me in the right direction.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.2
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.2.0
0.24.4
```

**Comment by stefanpenner** [comment]
ya something seems fishy.

It appears the following module isn't being compiled correctly

```
define('demo-bug/tests/abilities/emma', ['exports', 'ember'], function (exports, _ember) {
  'use strict';

  exports.__esModule = true;

  var _ember2 = _interopRequireDefault(_ember);

  function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : {
      default: obj
    };
  }

  const { computed } = _ember2.default;
  const { alias } = computed;

  exports.default = _ember2.default.Object.extend({
    canView: alias('isAdmin')
  });
});
```

confusingly 'demo-bug/tests/abilities/emma'  also exists at 'demo-bug/abilities/emma', and at that location it is compiled.

Im confused why it is duplicated... @rwjblue am I missing something obvious?

**Comment by rwjblue** [comment]
Seems related to https://github.com/ember-cli/ember-cli/pull/7036 to me.  Likely https://github.com/tomasbasham/ember-cli-scss-lint/pull/12/ wasn't enough to correct that addon (it fixed the `tests` clobbering behavior, but now it merges the raw app tree in with the linting results and emits them in `<app-name>/tests/<....original app path>`).

**Comment by billybonks** [comment]
any update here ? this doesn't seem to be happening for https://github.com/ember-cli/ember-cli-eslint happens to my package though

https://github.com/billybonks/ember-cli-stylelint
busy trying to work out what the difference is

**Comment by billybonks** [comment]
basically just looks like the dummy files are not being transpired

**Comment by billybonks** [comment]
This file is being properly transpired and inserted into dist/assets/dummy.js

https://github.com/billybonks/ember-cli-stylelint/blame/upgrade-ember/tests/dummy/app/app.js#L11

but it gets inserted as is into dist/assets/tests.js

**Comment by rwjblue** [comment]
@billybonks - I submitted https://github.com/billybonks/ember-cli-stylelint/pull/71 for the issue you described, I believe it is also the same issue as ember-cli-scss-lint is having.

**Comment by rwjblue** [comment]
https://github.com/tomasbasham/ember-cli-scss-lint/pull/13 should fix ember-cli-scss-lint

I'm closing this issue, please track upstream PR's for status

**Comment by billybonks** [comment]
awesome thanks 👍
