### ISSUE TITLE
MODEL_FACTORY_INJECTIONS deprecation when creating a new addon

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli#7067]
Creating a new add-on and using it in a new app triggers a  [MODEL_FACTORY_INJECTIONS deprecation](https://emberjs.com/deprecations/v2.x/#toc_ember-model-em-factory-em-injections-removed).

Demo:
```
git clone https://github.com/myartsev/ember-resize-in-an-addon.git
cd ember-resize-in-an-addon/foo-addon
npm link
cd ../foo-app
npm link foo-addon
ember s
```

There's nothing special in the add-on or the app at this point.
The addon is simply putting some text in a template and the app is calling the add-on and rendering it's template.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10
bash: yarn: command not found
```

**Comment by stefanpenner** [comment]
it seems to be firing as expected. https://github.com/myartsev/ember-resize-in-an-addon/blob/master/foo-app/app/app.js#L8 should be removed (as the deprecation says)

I am closing this, will gladly reopen if I have misunderstood :)

**Comment by myartsev** [comment]
Understood, but this is being added automatically by the ember generators, not by me.
Should it be removed from the blueprints if it's no longer necessary? Per the deprecation this appears to be the case.

**Comment by kellyselden** [comment]
@myartsev I believe it is removed in master, just not released yet.
