### ISSUE TITLE
Add package-lock

### ISSUE THREAD

**Issue by corbinu** [ember-cli/ember-cli#7071]
Hey was hoping package-lock could be added to the repo to speed up NPM installs / make them deterministic thanks!

**Comment by rwjblue** [comment]
We are currently using `yarn.lock` for working on ember-cli/ember-cli, so we do have deterministic dependency installs for ember-cli contributors...

I agree that we should absolutely consider using npm@5 and `package-lock.json` on its own merits (vs `yarn`)...

**Comment by corbinu** [comment]
@rwjblue i am totally cool with you guys continuing to use whatever makes the most sense for you I should have been more clear I was just hoping for package-lock files for releases so that installs for end users are faster.

**Comment by stefanpenner** [comment]
does npm@5 respect nested lockfiles from dependencies?

**Comment by corbinu** [comment]
No package-lock is not published in the module. My understanding is that's what shrinkwrap is still for.

**Comment by corbinu** [comment]
https://github.com/npm/npm/pull/16441/files

**Comment by rwjblue** [comment]
I guess I'm just confused by this:

> I was just hoping for package-lock files for releases so that installs for end users are faster

Since `package-lock.json` is not published or used by `npm` at all, how would ember-cli adding a `package-lock.json` to the repo materially affect our end users?

**Comment by stefanpenner** [comment]
@rwjblue maybe the idea is to add it to the blueprint?

**Comment by corbinu** [comment]
Sorry what I meant was shrinkwrap into the repo and package-lock into the blueprints

**Comment by Turbo87** [comment]
> does npm@5 respect nested lockfiles from dependencies?

yes, it does respect shrinkwrap files

> package-lock into the blueprints

that will automatically happen when you use npm@5 since it will be used to do the initial `npm install` inside of the created folder.

I'll close this issue since there doesn't seem to be anything for us to do here.

**Comment by corbinu** [comment]
@Turbo87 

```
that will automatically happen when you use npm@5 since it will be used to do the initial `npm install` inside of the created folder.
```

This was exactly my point as that means the initial install will be much slower than if the lockfile was in the blueprint. This is the exact reason the blueprints have a yarn.lock to speed up app init.

**Comment by Turbo87** [comment]
> This is the exact reason the blueprints have a yarn.lock to speed up app init.

they don't...

**Comment by corbinu** [comment]
@Turbo87 not sure what happened to my comment. Hmm strange I could have sworn it used to. Seems like a pretty big performance hole, but I guess as long as there is parity!
