### ISSUE TITLE
`will-interrupt-process` and `process` testability issues

### ISSUE THREAD

**Issue by ro0gr** [ember-cli/ember-cli#7073]
**Issues**:
- There are [some ugly things happening](https://github.com/ember-cli/ember-cli/blob/5d6a29aa821f307b74e13cddc23c6fd76ef88e58/tests/unit/utilities/will-interrupt-process-test.js#L144) with the global `process` in the `will-interrupt-process` unit tests. [Related comment](https://github.com/ember-cli/ember-cli/pull/7041#discussion_r116785222)
- Currently we can work with a real `process` only. Even in a test mode when we use [ember test helper](https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/ember.js) `will-interrupt-process`[ still works with a real `process`](https://github.com/ember-cli/ember-cli/blob/5d6a29aa821f307b74e13cddc23c6fd76ef88e58/lib/utilities/will-interrupt-process.js#L81). 

While the first issue looks like a minor(if we agreed to ignore a possibility to accidentally corrupt the global `process`) the second one is bit more tricky:
- as soon as we do [process.stdin.on](https://github.com/ember-cli/ember-cli/blob/5d6a29aa821f307b74e13cddc23c6fd76ef88e58/lib/utilities/will-interrupt-process.js#L117) on Windows TTY screen we should likely ensure that stdio is fully drained before exiting[ like the `bin/ember` does](https://github.com/ember-cli/ember-cli/blob/5d6a29aa821f307b74e13cddc23c6fd76ef88e58/bin/ember#L33). But [it's not the case with ember test helper](https://github.com/ember-cli/ember-cli/blob/5d6a29aa821f307b74e13cddc23c6fd76ef88e58/tests/helpers/ember.js#L94).  
- we should not allow `will-interrupt-process` to make a real `process.exit` or subscribe to a real `process` events when somebody uses ember test helper in [their test suite](https://github.com/emberjs/data/blob/69cdc9e6373409b5fd5e0c248a7aebd3283773aa/node-tests/blueprints/adapter-test.js#L21)

**Proposal**
The proposal is to implement a `ProcessMock` test helper. 
It will be derrived from `EventEmitter` to emulate a real process more precisely. All the streams will be inherited from `EventEmitter` as well.
All the non-`EventEmitter` methods like `setRawMode` can be implemented as a test double functions.

`ProcessMock` instance will be created in the ember test helper and passed to the cli.
It will allow us to get rid of interaction with real `process` in the test environment. At the same time we will have a built-in ability to emulate different process and streams behaviours like "CTRL+C" and verify function calls.

@stefanpenner @hjdivad @rwjblue Before I start working on implementation I would like to hear if this all makes any sense for you?

**Comment by stefanpenner** [comment]
@ro0gr thanks for digging into this! This is quite important, I'll try my best to make some time shortly to review. (a tad busy this week)

**Comment by ro0gr** [comment]
@stefanpenner No hurry. Anyway I don't have anything to show right now. I'll try implement a minimal working solution soon.

**Comment by locks** [comment]
Relevant PR was merged at the time!

**Comment by ro0gr** [comment]
@locks thanks! Forgot to close it.
