### ISSUE TITLE
npm@5 issues in tests

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#7082]
Not 100% sure, but when i run tests locally with npm@5 i get some failures.

~~May be related to: https://github.com/ember-cli/ember-try/issues/130~~

**Comment by stefanpenner** [comment]
root cause I believe is that https://github.com/npm/read-package-tree although I believe intends to return a tree can return a graph...

**Comment by locks** [comment]
I believe this is no longer relevant. Please re-open if otherwise!
