### ISSUE TITLE
Correct way to include static CSS file from addon

### ISSUE THREAD

**Issue by MojoJojo** [ember-cli/ember-cli#7089]
Hi,
I am busy writing an ember-cli plugin that wraps an existing third party library available as NPM module. Everything works, but importing the CSS files via `app.import`. Here's the code from addon's `index.js`

```
'use strict';
var path = require('path');
var mergeTrees = require('broccoli-merge-trees');
var Funnel = require('broccoli-funnel');

module.exports = {
  name: 'ember-cli-test',
  included: function(app) {
    this._super.included.apply(this, arguments);
    //auto import required files for third-party plugin
    let vjs = path.join(this.app.project.root, 'node_modules', 'vjs', 'dist');
    let vsvg = path.join(this.app.project.root, 'node_modules', 'vjs', 'dist', 'svg');
    let svgTree = new Funnel(vsvg, {
      include: ['*.svg'],
      destDir: 'svg'

    });

    app.import(path.join(vjs, 'vjs.js'));
    app.import(path.join(vjs, 'vjs.css'));
    app.import(svgTree);



  },
  /**
   * Make JS files available for importing.
   * @param tree
   * @returns Vendor Tree
   */

  treeForVendor: function (tree) {


    var vjs = path.join(this.app.project.root, 'node_modules', 'vjs', 'dist');
    var vendorTree = new Funnel(vjs, {
      files: ['vjs.js']
    });

    return vendorTree;
  },
  treeForStyles: function (tree) {
    var vjscss = path.join(this.app.project.root,'node_modules' , 'vjs', 'dist');
    var cssTree = new Funnel(vjscss, {
      include: ['vjs.css']
    });

    return cssTree;

  }
....
};
```

The above works fine and the javascript library is loaded as expected. However, the CSS is not included. I referred to the discussions on [SO](https://stackoverflow.com/questions/23956089/adding-vendor-css-libraries-with-ember-cli-and-broccoli-compass) and issues #6927, #7021 and #6299 but couldn't decide on right mechanism.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.12.0-beta.1
http_parser: 2.7.0
node: 6.10.2
v8: 5.1.281.98
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
0.23.2
```

**Comment by imanhodjaev** [comment]
I have ember addon also and would like to just import libraries from `node_modules` but at the moment have to use bower. It will nice to have such ability without having to write custom inclusion via funnels and vendor trees.

**Comment by Samsinite** [comment]
I use https://github.com/ef4/ember-browserify for including npm libraries. Does that help you guys at all?

**Comment by locks** [comment]
So much has changed in this area that I believe the issue is no longer relevant!
