### ISSUE TITLE
Quest: Slightly Better Errors

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7091]
Sorry for the spam, we have quite a few issues opened regarding better errors in Ember CLI but it could be good to consolidate all the efforts in one place and resume the progress.

# Summary

The goal is to improve error messages in Ember CLI, make them useful and more developer friendly.

# Prior work

The first spike to deliver better error message was done by [@stefanpenner](https://github.com/stefanpenner), [here](https://github.com/ember-cli/broccoli-middleware/pull/4). This work inspired [@jfelchner](https://github.com/jfelchner) to put [a very good summary](https://github.com/ember-cli/ember-cli/issues/6441) of what we want to have see as a part of the error page in Ember CLI.

# Details

## Improving errors from Ember Add-ons

We might want to introduce a `BuildError` to add-on developers to communicate the error from add-on to broccoli builder in a standardized way.  As long as add-on respects the following error contract, Ember CLI should be able to show useful error messages.
_Note_, that is just an interface, not an actual class.

```typescript
interface Position {
  line: number;
  column: number;
}

interface BuildError {
  stack: string;
  message: string;
  codeFrame: string;
  type: string,
  location: Position;
}
```

Use `BuildError` in `ember-cli-htmlbars`, [`processString`](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/index.js#L60-L65):

```javascript
import { BuildError } from 'ember-build-utilities';

// ...

processString(string, relativePath) {
  let compiledTemplate;
  
  try {
    compiledTemplate = utils.template(this.options.templateCompiler, stripBom(string), {
      contents: string,
      moduleName: relativePath
    });
  } catch(e) {
    // this is a good place for us to pass a more detailed information about
    // the failure to Broccoli Builder
    throw new BuildError(e.type || 'Template Compiler Error', e.message, e.stack, e.location);
  }
  
  return `export default ${compiledTemplate};`;
}

// ...
```

Corresponding PR https://github.com/ember-cli/ember-cli-htmlbars/pull/115

## Changes to Glimmer

Adding Syntax Error to Glimmer https://github.com/glimmerjs/glimmer-vm/pull/540

## Changes to Broccoli Builder

`broccoli-builder` itself is going to have to be modified to send new information to `broccoli-middleware`.

```typescript
interface BroccoliBuildError {
  message: string;
  stack: string;
  broccoliPayload: {
    versions: {
      // ember-cli, ember-data, node.js, ember
    };
    broccoliNode: {
      name: string,
      annotation: string;
      instantiationStack: string;
    };
    error: {
      codeFrame: string;
      message: string;
      stack: string;
      location: {
        line: number;
        column: number;
        file: string;
        treeDir: string;
      };
    };
  };
}
```

Corresponding PR https://github.com/ember-cli/broccoli-builder/pull/10.

## Changes to Broccoli Middleware

Styling for `error.html` page.

Corresponding PR https://github.com/ember-cli/broccoli-middleware/pull/25/

## Documentation

First pass on documenting how things work https://github.com/ember-cli/ember-cli/pull/7090

## Screenshot

If you put everything together, it looks like this.

![screen shot 2017-06-04 at 5 13 08 pm](https://cloud.githubusercontent.com/assets/1131196/26767063/0bfbc74e-4951-11e7-9874-ae641986b605.png)

It's a good step forward that will allow us and add-on developers to iterate towards better solution over time.

**Comment by jfelchner** [comment]
@twokul there's already an open consolidation issue here: https://github.com/ember-cli/ember-cli/issues/6441

**Comment by jfelchner** [comment]
@twokul #6441 has been updated with all of the new issues and PRs from this one.  Feel free to copy any comments over there.

**Comment by stefanpenner** [comment]
@twokul can this be closed?
