### ISSUE TITLE
How to get ember test to output status code 0 for pre-commit.

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-cli#7111]
When you have installed https://github.com/observing/pre-commit it requires a status code of 0 to commit.
How can we get this when running a successful `ember test`

**Comment by ro0gr** [comment]
I believe `ember-cli` already exits with an appropriate exit code. 
I've checked it localy:
```powershell
PS> npm t 

... tests output

1..7
# tests 7
# pass  7
# skip  0
# fail  0

# ok
PS> echo $LASTEXITCODE
0
```

**Comment by QuantumInformation** [comment]
I'm getting a blank line on my mac.

**Comment by ro0gr** [comment]
Sorry I had to mention that I made this test under windows powershell. I think on mac you should use different syntax to get an exitcode

**Comment by QuantumInformation** [comment]
My bad, I had `pre-commit: "npm test"` instead of just `pre-commit: "test"`
