### ISSUE TITLE
error  importing npm dependencies in 2.13

### ISSUE THREAD

**Issue by kielni** [ember-cli/ember-cli#7112]
I upgraded from 2.11.1 to 2.13.2, and now get errors when importing npm dependencies via browserify.  I can reproduce in a brand new repo: https://github.com/kielni/ember213-browserify

    ember init
    npm install --save-dev browserify d3
    ember g controller application

in app/controllers/application.js

    import d3 from 'npm:d3';

in console:

    ember.debug.js:19818 Error: Could not find module `npm:d3` imported from `ember213/controllers/application`
        at missingModule (loader.js:232)
        at findModule (loader.js:243)
        at Module.findDeps (loader.js:173)
        at findModule (loader.js:247)
        at requireModule (loader.js:26)
        at Class._extractDefaultExport (index.js:392)
        at Class.resolveOther (index.js:108)
        at Class.superWrapper [as resolveOther] (ember.debug.js:42834)
        at Class.resolveController (ember.debug.js:7337)
        at Class.resolve (ember.debug.js:7190)

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember version --verbose && npm --version && yarn --version
ember-cli: 2.13.2
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
4.2.0
-bash: yarn: command not found
```

**Comment by rwjblue** [comment]
Hmm, off the cuff this seems like it may be a bug in ember-browserify, but I haven't really dug in...

**Comment by kevlarr** [comment]
Replicating this between Ember 2.11 and Ember 2.12, both using `ember-browserify` 1.1.13

**Comment by stevesims** [comment]
I'm seeing this too, using `ember-browserify` 1.1.13 - although only when I remove `ie 10` from my `targets.js` file

**Comment by efx** [comment]
@kielni that example is installing `browserify`; do you mean to install only this or were you thinking of `ember-browserify`?. FWIW our project uses ember-browserify@1.1.13 with ember-cli@2.13.2 and I can successfully use  `import foo from 'npm:foo'`.

**Comment by Turbo87** [comment]
since this is likely an issue in `ember-browserify`  and not in `ember-cli` I'd like to move this to https://github.com/ef4/ember-browserify/issues
