### ISSUE TITLE
ember test fails with `host: 0.0.0.0` in .ember-cli config

### ISSUE THREAD

**Issue by Gowiem** [ember-cli/ember-cli#7124]
I ran into the issue with testem erring out on running Phantomjs with the following: `Error: Browser failed to connect within 30s. testem.js not loaded?`.  That issue is well summed up in #5415.  

This happened after doing a bunch of dockerization work (I've since realized isn't worth it for Ember CLI/given up on) and during that I had updated my `.ember-cli` config with `host: 0.0.0.0`.  Removing this line got `ember test` back on track, so it seems there is a bug there. 

Not a big issue for me as I don't need 0.0.0.0 as my host any longer, but wanted to share this incase others run into the same or you folks would like to make the fix. If someone knows the direct cause of this and can point me in the right direction, I'd be happy to take a crack at fixing as well. 

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.2
http_parser: 2.7.0
node: 7.4.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.6.1
```

**Comment by locks** [comment]
Closing due to relevancy, since this issue is for an unmaintained version of Ember CLI (2.13). If this still occurs in current versions, please let us know!
