### ISSUE TITLE
"Could not find module" when an addon initializer imports a module from another addon

### ISSUE THREAD

**Issue by skaterdav85** [ember-cli/ember-cli#7127]
I created an addon, installed ember-tether (or any other addon), and created an initializer for that addon that looks like the following:

```js
import EmberTether from 'ember-tether/components/ember-tether';

export function initialize() {
}

export default {
  name: 'data-test-hook',
  initialize
};
```

My sample addon can be found here: https://github.com/skaterdav85/my-addon.

Then, I created a new app and added the following to `devDependencies` in `package.json`:

```
"my-addon": "git+https://github.com/skaterdav85/my-addon.git"
```

I then run `ember serve`, and the console gives the following error:

```
Uncaught Error: Could not find module `ember-tether/components/ember-tether` imported from `my-addon/initializers/data-test-hook`
    at missingModule (vendor.js:249)
    at findModule (vendor.js:260)
    at Module.findDeps (vendor.js:170)
    at findModule (vendor.js:264)
    at Module.findDeps (vendor.js:170)
    at findModule (vendor.js:264)
    at requireModule (vendor.js:31)
    at resolveInitializer (vendor.js:82247)
    at registerInitializers (vendor.js:82260)
    at exports.default (vendor.js:82242)
```

I've tried this with 2 addons and I get errors.

```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 7.5.0
v8: 5.4.500.48
uv: 1.10.2
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2
0.24.4
```

**Comment by stefanpenner** [comment]
> Then, I created a new app and added the following to devDependencies in package.json:

i believe this is your issue, wouldn't this be a regular dependency? otherwise if your addon is used, its dependency (ember-tether)  would not be installed

**Comment by skaterdav85** [comment]
Inside my app, do this?

```js
"dependencies": {
    "my-addon": "git+https://github.com/skaterdav85/my-addon.git"
  },
```

That did not work. Or do I have to install ember-tether in my app, even though the initializer that imports `ember-tether/components/ember-tether` lives in the addon?

**Comment by stefanpenner** [comment]
> Ah, so my addon needs to list ember-tether in dependencies instead of devDependencies

yes.

Npm install will only instal the devDependencies for the `root` module, all dependencies will only have there `depedendencies` installed.
