### ISSUE TITLE
Default node to a supported version app package.json

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli#7128]
At https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L41 the engine specified for node is `>=4`. I've had several builds go bad on Heroku where the default is now Node 8.

Should we be pinning this number back to an LTS (like `6.x.x`) or capping the range to stop devs from using Node 8 unwittingly?

**Comment by rwjblue** [comment]
We have a larger issue with ember-cli (and associated packages) using poor engine values. We have an open PR to address that and should be updating some official policies about how to use engines within ember-cli packages.
