### ISSUE TITLE
Error creating new app

### ISSUE THREAD

**Issue by jtsom** [ember-cli/ember-cli#713]
Using npm 1.4.10, ember-cli 0.0.27 on OS X 10.9.2, node installed using package on nodejs.org, and ember-cli installed with 'sudo npm -g install ember-cli'

Trying to create a new app generates an error:

...
 create tests/unit/.gitkeep
  create vendor/_loader.js
Installing packages for tooling via npm..
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/Users/john/.npm/bower-config/0.5.0/package.tgz'

I've tried uninstalling and reinstalling ember-cli, but it doesn't help.

**Comment by cloverich** [comment]
Adding notes, in case any other lost souls like myself stumble on this. 

Files and folders in a users own /home/<username> (or /Users/<username) directory don't normally require sudo (e.g. elevated) permissions to access. However, when npm is run with sudo, any files or folders it creates, even in a users own .npm directory, will be created with root as the owner. This prevents ember-cli from opening files or writing into directories with those permissions.  

This is why @Gaurav0 's solution worked above -- recursively changing all files and folders in that directory to be owned by yourself (as is normal -- almost, see note below) allows running ember-cli as usual (at least when it needs to read / write into the ~/.npm folder). 

Note: I changed owner to myself but group to `staff` -- staff was the default group on my OSX machine. I simply called `ls -a` inside the .npm directory, and use the owner:group that appeared on folders that weren't created by root.
