### ISSUE TITLE
Mixed usage of package managers in test suite

### ISSUE THREAD

**Issue by ro0gr** [ember-cli/ember-cli#7134]
I think currently the mix of package managers is used in a single test. While we use [yarn](https://github.com/ember-cli/ember-cli/blob/93c4fd5763fa69fcb11eb0bee1b6b38e57ad4d15/tests/helpers/acceptance.js#L101) for test targets setup, `npm-task`[ fails to detect yarn](https://github.com/ember-cli/ember-cli/blob/93c4fd5763fa69fcb11eb0bee1b6b38e57ad4d15/lib/tasks/npm-task.js#L122) as a desired package manager because the [`package-cache` destroys](https://github.com/ember-cli/ember-cli/blob/93c4fd5763fa69fcb11eb0bee1b6b38e57ad4d15/tests/helpers/package-cache.js#L341) `yarn.lock` file. 

Does it sound like a bug and should be fixed?

**Comment by stefanpenner** [comment]
> Does it sound like a bug and should be fixed?

what would be the fix?

**Comment by ro0gr** [comment]
The first thought came into my mind is to find the way to preserve a lock file after targets are set up. 
Seems like it's the most natural way of fixing the problem..

**Comment by ro0gr** [comment]
Initially I supposed that mixed package managers was the reason of [installation failures of this kind](https://ci.appveyor.com/project/embercli/ember-cli/build/13438/job/3dl7y4c37r39673p#L256) in blueprint tests:
> NPM: Installing morgan@^1.3.2 and glob@^4.0.5 ...
> Command failed: npm install --save-dev --loglevel error morgan@^1.3.2 glob@^4.0.5
 
But seems like it's not true. When I try to use `PackageCache` with `npm@5` instead of yarn the same problem still persist on my local windows machine.

Closing for now. If I have time to revisit and fix this behavior in tests I'll re-open.
