### ISSUE TITLE
Ember is not installing on windows 10

### ISSUE THREAD

**Issue by gaurav123337** [ember-cli/ember-cli#7140]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `npm install -g ember`:
```
'ember' is not recognized as an external or internal command in windows 10
```

**Comment by initram** [comment]
Npm Install -g ember-cli

**Comment by kellyselden** [comment]
@initram is correct. https://github.com/ember-cli/ember-cli#installation

**Comment by gaurav123337** [comment]
Solved the issue.
The fault was from my side .
Need to run 'ember' conmand from the 'C:/Users/<username >/AppData/Roaming/npm'.
Now it works flawlessly.
