### ISSUE TITLE
Windows 10 WLS(bash) time slower than ember-cli on windows?

### ISSUE THREAD

**Issue by xinitrc86** [ember-cli/ember-cli#7156]
Hello all, 

(short version in bold)
I´m new to ember and due to reasons not that important I´m stuck with Windows. 
I love the fact that ember has so much test options out of the box, this enabled me to go ATDD + TDD real quick. However...Windows build time with ember-cli is just too slow. I end up running once and sleeping my pc just so I don´t need to build again the next time I work and get tests feedback faster.

Unfortunately, whenever I have a new dependency I have to build again. Then I heard about WLS and went for it. I had some issues installing amd making it work. To install ember-cli I had to do a npm config set unsafe-perm true otherwise it would fail. My first shot at ember server complained that node-sass was built with a different runtime (true) and had to force a rebuilt.

**So** my issue is, I started a project in Windows and then tried to use Windows 10 WLS on the same project directory to speed up build time, but ended up not having a build at all...it is still running while I type this text, at least. Node stays there, consumming CPU but never actually finishing the build. Should I do something here? NPM uninstall/install doesn´t do anything. Installed 

I´m lost...

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.2
node: 6.11.0
os: linux x64
3.10.10
```
no yarn installed

**Comment by xinitrc86** [comment]
I do get livereload server on 49153, after that, nothing (so far)

**Comment by xinitrc86** [comment]
Build successful (4059049ms) – Serving on http://localhost:4200/



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (45)                                    | 2221715ms (49371 ms)
Concat (9)                                    | 731339ms (81259 ms)

**Comment by xinitrc86** [comment]
I did some tests with fresh new projects,
Windows ember-cli with ember-cli-windows-addon finishes in 6.5 seconds (avg)
Bash ember-cli finishes in 22 seconds (avg)

**Comment by vlascik** [comment]
I think I remember reading about WSL's slow filesystem (it has to translate all calls to NTFS). Try a Linux VM, should be much faster.

**Comment by Turbo87** [comment]
@stefanpenner @kellyselden any comments on this?

**Comment by kellyselden** [comment]
I have not used WLS yet.

**Comment by stefanpenner** [comment]
from my tests, the following appears to be whats up:

* WSL is fastish, but only if you are not mounting NTFS drives
* cmd.exe or similar on windows (with symlinks enabled) is fastish (again no network mounts)

**Comment by kaiwah** [comment]
Also agree with ember-cli build times on WSL being 2x slower than the windows counter-part.

A direct comparison of the same project (medium sized application):
Win32 x64 / Node 6.9.1 / Ember-CLI 2.10.0 -> ~11 seconds
Linux x64 / Node 6.9.1 / Ember-CLI 2.10.0 -> ~24 seconds

On WSL, the project files are _NOT_ in /mnt/ drives, it is in /home/User/ directory.
The faster windows build is on a separate computer on Win7 and the slower build is on a Win10 laptop (WSL bash/zsh).

**Comment by Kilowhisky** [comment]
Looks like WSL 2.0 is supposed to be 20x faster!

> Increased file IO performance
File intensive operations like git clone, npm install, apt update, apt upgrade, and more are all noticeably faster with WSL 2.

> The actual speed increase will depend on which app you're running and how it is interacting with the file system. Initial versions of WSL 2 run up to 20x faster compared to WSL 1 when unpacking a zipped tarball, and around 2-5x faster when using git clone, npm install and cmake on various projects.

https://dev.to/wrightdotclick/20x-faster-speeds-by-updating-to-the-new-wsl-2-a-user-s-installation-guide-57n4#:~:text=Turn%20on%20the%20Virtual%20Machine,Distro%3E%202%20to%20convert%20them.

https://docs.microsoft.com/en-us/windows/wsl/compare-versions#:~:text=The%20actual%20speed%20increase%20will,and%20cmake%20on%20various%20projects.

I'm going to give it a go and see how it works out.

**Comment by Kilowhisky** [comment]
After some working around the WLS known issue regarding mounted drives it appears to be **significantly faster** than running in just windows alone. 🎉

I managed to get it all working by doing the following:
1. Do some work to get LTS version of nodejs into Ubuntu https://computingforgeeks.com/how-to-install-nodejs-on-ubuntu-debian-linux-mint/
1. Checkout a new copy from GIT into a WLS local directory `/home/me/emberApp/`
1. Change my IDE and GIT IDE to the new path `\\wsl$\Ubuntu\home\me\emberApp`
1. `ember serve` 
1. Party

So far I don't seem to be having problems with line endings or GIT though there are a few issues floating around that indicate GIT speed is pretty badly affected.  https://github.com/microsoft/WSL/issues/4197

![Alt Text](https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif)

Here is the general problem:
https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2

>Exceptions for using WSL 1 rather than WSL 2
We recommend that you use WSL 2 as it offers faster performance and 100% system call compatibility. However, there are a few specific scenarios where you might prefer using WSL 1. Consider using WSL 1 if:

>Your project files must be stored in the Windows file system. WSL 1 offers faster access to files mounted from Windows.
If you will be using your WSL Linux distribution to access project files on the Windows file system, and these files cannot be stored on the Linux file system, you will achieve faster performance across the OS files systems by using WSL 1.
A project which requires cross-compilation using both Windows and Linux tools on the same files.
File performance across the Windows and Linux operating systems is faster in WSL 1 than WSL 2, so if you are using Windows applications to access Linux files, you will currently achieve faster performance with WSL 1.
