### ISSUE TITLE
Generates --classic type structure when both usePods is true and --pod is used 

### ISSUE THREAD

**Issue by emrekutlu** [ember-cli/ember-cli#7163]
```javascript
// project-root/.ember-cli
{
  "usePods": true
}
```
When <code>usePods</code> is <code>true</code>;

```
$ ember generate controller foo --pod

installing controller
  create app/controllers/foo.js
installing controller-test
  create tests/unit/controllers/foo-test.js
```
Generates in <code>--classic</code> structure not in <code>--pod</code>.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.3
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.8
0.24.6
```

**Comment by emrekutlu** [comment]
I submitted a PR https://github.com/ember-cli/ember-cli/pull/7164.

But I believe using mutually exclusive values in different arguments is problematic. It is not obvious what will happen if I use both <code>--classic</code> and <code>--pod</code> together. Better be something like <code>structure=pod</code> but I suppose you don't use this kind of command arguments.

**Comment by webhive** [comment]
Confirm it. Got this issue too.
