### ISSUE TITLE
in repo addon + mixin + babel 6 (I think) bug

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7165]
https://github.com/kellyselden/in-repo-addon-mixin-bug

The in-repo-addon does a sort of extra `_interopRequireDefault` when it shouldn't.

If the mixin is inside an in-repo-addon, the compiled output looks like this:

```js
var _run2 = _interopRequireDefault(_run);

exports.default = _ember2.default.Mixin.create(_run2.default, {
```

Where `_run` is `{ default: Mixin }` and `_run2` is `{ default: { default: Mixin }}`.

If I copy the mixin to the host app, the compiled output looks like this:

```js
exports.default = _ember.default.Mixin.create(_run.default, {
```

And everything is happy. I'm thinking this is a babel issue, so maybe this belongs on ember-cli-babel.

**Comment by locks** [comment]
Closing as not relevant since the project is now on Babel v7.
