### ISSUE TITLE
Update node support doc with specific Ember CLI versions.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#7168]
Now that we have a node support policy document (landed in https://github.com/ember-cli/ember-cli/pull/7080) we need to make a few updates:

- [ ] Update the console warnings that we emit around node version, to link back to the document
- [ ] Update the documentation to specify exact version ranges of Ember CLI for the various Node versions that have dropped support (e.g. Ember CLI 2.11 was the last version that supported Node 0.12)

**Comment by villander** [comment]
@rwjblue I want to contribute to these tasks. But I did not find where the console warning is. Can you help me?

**Comment by rwjblue** [comment]
It happens [here](https://github.com/ember-cli/ember-cli/blob/ba73fc87f3ce95f065f117578cd4b9a9f2fe70cc/lib/cli/cli.js#L121-L133).

**Comment by CrshOverride** [comment]
Is there a version of the document that is link-able on the public site or should the messages link directly to the Markdown document on GitHub?

**Comment by rwjblue** [comment]
I think linking to the markdown file on github is totally fine for a first pass at this.  We can always make a custom page on the website if we feel like it later...

**Comment by CrshOverride** [comment]
@rwjblue And, other than updating `node-support.md`, what all "documentation" needs to be updated?

**Comment by rwjblue** [comment]
> Other than updating node-support.md, what all "documentation" needs to be updated?

That's it, I believe (though that file didn't exist when I created this issue originally 😝)...

**Comment by CrshOverride** [comment]
Awesome. I should have a PR later tonight or tomorrow morning with the updates. A nice easy first bite. I just have to hunt down all of the version info... :stuck_out_tongue:
