### ISSUE TITLE
ember install chaining scenario

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7179]
Scenario: I want to install an addon called `some-package-shim` into my own addon. My addon requires `some-package-shim` to function, so I install it with `ember install some-package-shim --save`. `some-package-shim` also has a dependency called `some-package`, and installs it with its blueprint via `this.addPackageToProject('some-package')`.

I expect both packages to be installed to "dependencies" because of my use of `--save`, but only `some-package-shim` installs to "dependencies". `some-package` installs to "devDepencencies".

I did not expect this at first, but because I know how the code works, I realized that `ember install` is not chaining the install options. It respects the intermediate addon's install options, which default to `--save-dev`.

Should we do something about this?

**Comment by locks** [comment]
Closing as stale.
