### ISSUE TITLE
t-info

### ISSUE THREAD

**Issue by catz** [ember-cli/ember-cli#7182]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
[Replace this line with the output.]
```

**Comment by rwjblue** [comment]
Seems like this may have been opened in error (since there is no info in the description / title).

Closing for now...
