### ISSUE TITLE
Can we update the updating checklist?

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7188]
- `npm uninstall -g ember-cli` maybe this alone is OK (read next one);

- `npm cache clean` with npm 5 is not anymore a problem; indeed it's an NPM ERR:

```
$ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

- `bower cache clean` is it still useful?

- `rm -rf node_modules bower_components dist tmp` the same, maybe nothing here is useful using `yarn`.

- `npm install and bower install` is no more useful because `ember init` does it.

What to do?

**Comment by Turbo87** [comment]
@johnunclesam I tend to agree that `npm cache clean` is likely unnecessary at this point and we should remove it for the next releases. The Bower stuff has already been removed so I'm going to close this issue as resolved. Thanks!

**Comment by mrkongo** [comment]
Isn't also 'npm install -g ember-cli@x.x.x' enough and so can we remove also 'npm uninstall -g ember-cli'?
