### ISSUE TITLE
ember-cli 2.13.3 and ember init and "Ember.MODEL_FACTORY_INJECTIONS = true;" again

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7189]
`ember-cli 2.13.3` with `ember init` adds again in app/app.js this:

`Ember.MODEL_FACTORY_INJECTIONS = true;`

Related to: https://github.com/ember-cli/ember-cli/pull/7025 it's still needed?

What is it? It's a mistake in blueprints?

**Comment by kellyselden** [comment]
This should be resolved in #7206 and should be released in v2.14.1.
