### ISSUE TITLE
Not able to Create a New Ember App

### ISSUE THREAD

**Issue by jagattula** [ember-cli/ember-cli#7190]
I m not able to create a new ember app with 
ember new new-app or ember init
as it results in the error
the files and folders get all right created but while install npm dependencies required for the app it gets stuck down
![capture](https://user-images.githubusercontent.com/19171880/27858453-e82a68b6-6192-11e7-998c-900362d35d5b.JPG)

---

Output from `ember version --verbose && npm --version && yarn --version`:
![capture](https://user-images.githubusercontent.com/19171880/27859518-9d91dcd6-6196-11e7-8832-586d5eb483f8.JPG)

```
[Replace this line with the output.]
```

**Comment by kellyselden** [comment]
You might want to try with npm 4. npm 5 was failing to install for me too.

**Comment by jagattula** [comment]
@kellyselden same issues come around
initially, when I first install ember-cli it was all fine and well but after creating a few projects the problem started to arise
I tried to resolve it by uninstalling ember-cli and starting a clean installation but it didn't worked out

**Comment by Turbo87** [comment]
@jagattula this looks like a problem with your local npm installation. can you look into the logfile that is referenced in the error message and see if there are any clues in it?

**Comment by jagattula** [comment]
@Turbo87 i couldnt figure out what was the real problem but after a day of waiting and clean installation of ember-cli all the things is working fine and i'm able to create a new project all well and good
