### ISSUE TITLE
`yarn remove` is run with an empty list of packages

### ISSUE THREAD

**Issue by cafreeman** [ember-cli/ember-cli#7201]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.0
http_parser: 2.7.0
node: 8.1.3
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.0.3
0.27.5
```

After upgrading to `2.14`, I noticed an issue when trying to re-install `ember-cli-mocha`.

It runs the normal install step, but then when it tries to uninstall `ember-cli-qunit`, it throws an error:

![image](https://user-images.githubusercontent.com/7971393/27920348-e3661ae4-6239-11e7-8a75-4eb0cac58510.png)

This appears to be caused by the fact that I don't actually have `ember-cli-qunit` installed in the first place, and that's causing the `yarn remove` command to receive an empty argument.

To test this, I uninstalled all my testing things, re-installed `ember-cli-qunit` and then ran `ember install ember-cli-mocha` again. When I have qunit present, the blueprint runs without error, like so:
![image](https://user-images.githubusercontent.com/7971393/27920417-19acfef6-623a-11e7-9be9-f5b48e146d47.png)

As @Turbo87 pointed out, this uninstall step is hard-coded in the [ember-cli-mocha blueprint](https://github.com/ember-cli/ember-cli-mocha/blob/master/blueprints/ember-cli-mocha/index.js#L17), so it's surprising that yarn isn't receiving it as an argument.

**Comment by Turbo87** [comment]
@cafreeman can you confirm that with 2.13 this was working as expected?

**Comment by cafreeman** [comment]
@Turbo87 oh, interesting. it looks like this also happened in 2.13, so I guess it's not related to `--non-interactive`

![image](https://user-images.githubusercontent.com/7971393/27920673-0519e9c6-623b-11e7-9dbb-ad995c5c4767.png)

**Comment by rwjblue** [comment]
FWIW, I just hit this while installing ember-web-app@2.0.0 into a fresh app.

**Comment by locks** [comment]
Is this still a problem?

**Comment by kenliten** [comment]
Is someone else having this problem?

**Comment by rwjblue** [comment]
I'm going to close for now, doesn't seem like we have a reproduction so not much we can do here.
