### ISSUE TITLE
Web app manifest paths missing fingerprints

### ISSUE THREAD

**Issue by woprandi** [ember-cli/ember-cli#7214]
Hi,

I have a [web app manifest ](https://developer.mozilla.org/en/docs/Web/Manifest) manifest.json in the `public/` folder which reference app icons path. But paths are not fingerprinted. I had to exclude fingerprint for these images in the `ember-cli-build.js` file. I suppose `.json` files are ignored 

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.0
http_parser: 2.7.1
node: 6.10.3
v8: 5.1.281.101
uv: 1.10.2
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2k-fips
os: linux x64
3.10.10
0.27.5
```

**Comment by Turbo87** [comment]
@woprandi you might have to configure https://github.com/rickharrison/broccoli-asset-rev to also use `json` in the `replaceExtensions` option. can you confirm that this solves it?

**Comment by woprandi** [comment]
@Turbo87 Oh yeah it works. Sorry I didn't find this information myself. Apologies.
