### ISSUE TITLE
[FEATURE ember-module-unification] styles in app/ when using src/

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli#7215]
When using a `src/` directory, styles in an `app/` directory from an addon are ignored. I'm unsure what they should do.

/cc @billybonks @rwjblue

**Comment by billybonks** [comment]
@mixonic thanks for opening the issue, @rwjblue says they are probably available but on a different path.

**Comment by mixonic** [comment]
`src/` styles are appended to the style pipeline. Closed in favor of https://github.com/emberjs/ember.js/issues/16373
