### ISSUE TITLE
[FEATURE] EMBER_ENV to honor NODE_ENV production settings

### ISSUE THREAD

**Issue by sclatter** [ember-cli/ember-cli#7217]
Per discussions with the Speedometer2 team, we would like to request a change to Ember CLI to ensure that engineers are generating production builds consistently before deploying to a production system. 

The suggested approach was that if NODE_ENV is set to production, then EMBER_ENV would use that a the default setting. @rwjblue and @krisselden are aware of this request and can provide additional context if needed.

**Comment by addyosmani** [comment]
From the Speedometer side, a hearty 👍 to this change if it's at all possible.

**Comment by rwjblue** [comment]
I am working on an RFC for a slightly different approach (with the same general result), trying to get it submitted before this weeks ember-cli meeting. 

The rough tldr; is that "interactive" commands (e.g. `ember serve`, `ember test --server`, `ember build --watch`) would continue to default to development environment (as that provides be best developer ergonomics) and all non-interactive builds (e.g. `ember build`) would default to production.

**Comment by rwjblue** [comment]
I will also make sure that the RFC specifically states that if `process.env.NODE_ENV` is set it will be used if no explicit environment was specified on the command line.

**Comment by Turbo87** [comment]
@rwjblue FWIW I'm okay with using `NODE_ENV` as a default even for the interactive commands. what would be the reason for not using it there?

**Comment by rwjblue** [comment]
Yes, that's also what I suggested 😜

**Comment by rwjblue** [comment]
I wrote up my specific suggestion in https://github.com/ember-cli/rfcs/pull/109. Adding to the agenda for the next ember-cli core team call...

@sclatter / @addyosmani - Would y'all mind reviewing?

**Comment by locks** [comment]
I am closing as the conversation went inactive and [we do a production build by default now](https://github.com/ember-cli/ember-cli/pull/8905). Thank you for the report and discussion!
