### ISSUE TITLE
Bower error when upgrading Node 6 -> 8, Ember CLI 2.13.2 -> 2.14.0, and having Yarn 0.27.5 installed

### ISSUE THREAD

**Issue by neojp** [ember-cli/ember-cli#7219]
I'm getting a Bower error similar to the one mentioned in #7076 when updating a project from Ember CLI `2.13.2` to `2.14.0`, and then running `ember init`.

Occasionally, I'd get some errors from node modules which I have a feeling  might have been Yarn's fault. Uninstalling Yarn, and Node. Reinstalling Node and then installing Ember CLI as usual finally got it working.

This is mostly to let you guys know about this issue, rather than needing an instant fix. Also, to keep a record of this for anyone else that might run into a similar error while upgrading.

---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.0
http_parser: 2.7.0
node: 8.1.4
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
npm: 5.0.3
yarn: 0.27.5
```
---
Error message when running `ember init`
```
Command failed: npm install bower@^1.3.12
npm ERR! Linux 4.9.27-moby
npm ERR! argv "/usr/bin/nodejs" "/app/node_modules/.bin/npm" "install" "bower@^1.3.12"
npm ERR! node v8.1.4
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/node_modules/ember-cli/npm-debug.log

Error: Command failed: npm install bower@^1.3.12
npm ERR! Linux 4.9.27-moby
npm ERR! argv "/usr/bin/nodejs" "/app/node_modules/.bin/npm" "install" "bower@^1.3.12"
npm ERR! node v8.1.4
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/node_modules/ember-cli/npm-debug.log

    at Promise.all.then.arr (/app/node_modules/execa/index.js:210:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by Turbo87** [comment]
this sounds a lot like an issue in npm itself and nothing that we can fix in Ember CLI. can you try this out with other npm versions?

**Comment by neojp** [comment]
Feel free to close this. As I said, this looks like a Yarn problem rather than Ember CLI's fault. Just wanted to make sure it was documented somewhere in case someone ran into the same issue.
