### ISSUE TITLE
Behavior with SublimeText

### ISSUE THREAD

**Issue by brandonparsons** [ember-cli/ember-cli#722]
All of the files generated by broccoli in the `tmp/` directory cause ST3 CPU usage to go through the roof (I suspect it is trying to index them all for the GoToAnything functionality).

This can be fixed by adding the following to your user settings:

```
// folder_exclude_patterns and file_exclude_patterns control which files
// are listed in folders on the side bar. These can also be set on a per-
// project basis.
"folder_exclude_patterns": [".svn", ".git", ".hg", "CVS", "tmp/class-*", "tmp/es_*", "tmp/jshinter*", "tmp/replace_*", "tmp/static_compiler*", "tmp/template_compiler*", "tmp/tree_merger*", "tmp/coffee_script*", "tmp/concat-tmp*", "tmp/export_tree*", "tmp/sass_compiler*"]
```

Just put this here in case you wanted to include it in the docs.

**Comment by skylar** [comment]
:+1: this was super helpful. please keep updating the docs!
