### ISSUE TITLE
"this" is undefined in preBuild & included hooks for addon

### ISSUE THREAD

**Issue by nullrocket** [ember-cli/ember-cli#7220]
**this** seems to be undefined in the **preBuild** and **included** hook for addons. The **init** hook seems fine.

```
ember-cli: 2.15.0-beta.1
```

**Comment by stefanpenner** [comment]
@nullrocket oh strange, mind providing a quick reproduction? Maybe a GH repo.

**Comment by trentmwillis** [comment]
Unsure about `included`, but looks like `preBuild` just needs a context when invoked [during `processAddonBuildSteps`](https://github.com/ember-cli/ember-cli/blob/816b540e741345eeb54756c9f5c7a5304d6108da/lib/models/builder.js#L136-L138).

**Comment by stefanpenner** [comment]
@bekzod looks like a regression introduced by https://github.com/ember-cli/ember-cli/commit/6650df901e75050fba5840459f60588d95a80a84  mind taking a look?

**Comment by bekzod** [comment]
@stefanpenner sure

**Comment by nullrocket** [comment]
Sure,
With ember-cli 2.14.0 I added a console.log to preBuild in index.js and get a this context.
[https://github.com/nullrocket/hasthis.git](https://github.com/nullrocket/hasthis.git)

With ember-cli 2.15.0-beta.1 same console.log in preBuild gets undefined.
[https://github.com/nullrocket/nothis.git](https://github.com/nullrocket/nothis.git)

**Comment by nullrocket** [comment]
@stefanpenner  I was only a little slow :)

**Comment by bekzod** [comment]
@stefanpenner this should fix it https://github.com/ember-cli/ember-cli/pull/7224 sorry for missing it before

**Comment by locks** [comment]
The mentioned PR was merged at the time, so this should be addressed. Thank you!
