### ISSUE TITLE
Including `emberCLITree` twice?

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7222]
It seems like we include `emberCLITree` twice, [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1206) and [here](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1344).

I haven't run the tests but removing [this merge](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1342-L1348) seemed to "just work" (tested with the app locally).

needs a proper bugfix though, created to start tracking.

**Comment by stefanpenner** [comment]
@rwjblue ^^

It's possible this is left over from another time?

**Comment by rwjblue** [comment]
ya, seems weird and not useful at this point
