### ISSUE TITLE
New module syntax in blueprints

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#7226]
I'm unsure if there is already an issue or PR for converting the blueprints to use module imports or not, but if it's not already being worked on, I would be glad to do it 😄

**Comment by kellyselden** [comment]
+1 for beginning to work on it. But before merging, we want to make sure we have a clear plan on how we are going to educate people on these changes.

**Comment by rwjblue** [comment]
@kellyselden - just saw this comment, I merged the blueprint update PR a day or so ago. I totally agree with your concerns. FWIW, @locks and I have been chatting about this for a while, maybe he can chime in to confirm we are all on the same page...

**Comment by Turbo87** [comment]
Resolved by https://github.com/ember-cli/ember-cli/pull/7233

**Comment by locks** [comment]
I'm here to confirm that we have, indeed, a plan :)
