### ISSUE TITLE
Dump sub-trees of ember application for debugging/better visibility into pipeline to fs

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7228]
I wonder if it would be useful to have a flag that we pass to `ember build` that will allow to dump sub-trees of application to be written into "debug" folder; this mostly for debugging purposes. It also will give users better visibility into how `ember-cli` build pipeline works (which trees it operates on).

I found it super useful while working on tree shaking. I currently use `broccoli-debug` to generate the following output:

<img width="750" alt="screen shot 2017-07-14 at 2 51 47 pm" src="https://user-images.githubusercontent.com/1131196/28232140-00de003a-68a4-11e7-80b8-5b3198134204.png">

Wonder if it's something we want to make available to everyone.

**Comment by stefanpenner** [comment]
Seems good as an ENV flag, as long as it's clearly documented not to be relied upon.

**Comment by rwjblue** [comment]
Should use broccoli-debug. It's made for exactly this purpose.

**Comment by rwjblue** [comment]
We should definitely do this (just like we do debug output for the console).

**Comment by twokul** [comment]
once https://github.com/ember-cli/ember-cli/pull/7240 lands, we could do it in assembler
