### ISSUE TITLE
storeConfigInMeta false + acceptance test + /tests = visit changes host url

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7236]
`ember test` works fine. Only when `ember serve` and visiting "/tests" does the `visit` causes the real browser url to change.

Removing `storeConfigInMeta` corrects it.

**Comment by rwjblue** [comment]
Yep. This is fundamentally an issue with how store config in meta works.

I personally advise folks to test via `ember test` and `ember test --server`, and not via `/tests` during a development build. 

To fix this specific issue (though there are more with using /tests) we need to build the development version of the config module into `app-name.js` and the test version of the config module into `tests.js`. This would ensure that the test config overrides the dev config even in /tests of a development build. Today we only build the config module once and include it in `app-name.js`.

**Comment by bertdeblock** [comment]
I tried reproducing this locally, but all seems well, so I'm guessing this was somehow fixed along the way.
I'm going to close this one, but please do reopen if I'm mistaken.
