### ISSUE TITLE
Sourcemaps Are Not Valid OTB

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#7237]
## Steps To Reproduce

1. `ember new my-app --yarn=true`
2. `ember build --environment=production`
3. `yarn add sourcemap-validator --dev`
4. `require("sourcemap-validator")(fs.readFileSync('./dist/assets/app-SOMEHASH.js', './dist/assets/app-SOMEHASH.map'))`
5. Get the following error.

```
Error: Warning: mismatched names
Expected: exports || 'exports' || 'exports' || "exports" || "exports"
Got: define( || define('s || define('s || define('s || define('s
Original Line: define('sm-test/app', ['exports', 'ember', 'sm-test/resolver', 'ember-load-initializers', 'sm-test/config/environment'], function (exports, _ember, _resolver, _emberLoadInitializers, _environment) {
Mapping: 2:124→1:0 "exports" in sm-test/app.js
```

I have also noticed that out of the box all the col numbers are 0.

---

**Ember Versions**
```
ember-cli: 2.14.0
http_parser: 2.7.0
node: 7.9.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
```

**Yarn Version**
```
0.27.5
```

**Comment by stefanpenner** [comment]
I wonder if they went bad post babel

**Comment by stefanpenner** [comment]
i suspect it's something else. Maybe keep removing stuff until it works again

**Comment by stefanpenner** [comment]
Another idea is to run the validation within broccoli concat and see which inputs are breaking (or if broccoli concat itself is breaking them)

**Comment by stefanpenner** [comment]
Also the above looks like a great test to add to ember-cli's test suite.

**Comment by Turbo87** [comment]
@stefanpenner I don't think that it belongs in the test suite of Ember CLI since this is likely an issue in either the Babel or UglifyJS addon

**Comment by Turbo87** [comment]
it seems that @chadhietala has figured out that Babel sourcemaps are broken: https://github.com/babel/babel/issues/6008
