### ISSUE TITLE
Tests seem to rely on internet connection

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7250]
It seems like our tests depend on the internet connection being present. Unsure what the best solution here to be just yet, but wanted to flag it.

```sh
Error: Command failed: git clone https://github.com/ember-cli/app-blueprint-test.git /var/folders/jt/2lft2cgn3vx3_4sygv0k79gh000n_t/T/ember-cli117624-59015-m07vcb.c31cpfzuxr
Cloning into '/var/folders/jt/2lft2cgn3vx3_4sygv0k79gh000n_t/T/ember-cli117624-59015-m07vcb.c31cpfzuxr'...
fatal: unable to access 'https://github.com/ember-cli/app-blueprint-test.git/': Couldn't connect to server
```

**Comment by rwjblue** [comment]
I suspect there are other tests that also require internet access. In this case, we could guard the test so that it doesn't run if internet access is not available or use fixturify to just generate the needed files for the test (and avoid internet completely).

**Comment by Turbo87** [comment]
@twokul @rwjblue these integration tests test the integration with git, npm, yarn, etc. I don't think there is much we can do about it if we want to properly test those. Disabling the tests when we detect that there is no connection seem very brittle IMHO.

**Comment by twokul** [comment]
@Turbo87 agreed, that's why I'm not sure what exactly to do about it

**Comment by rwjblue** [comment]
@Turbo87 ya, that's why I also suggested we actually make a local got repo and use it. We should get the same benenfit as today without needing network (for that test) and without he worry that _someone_ will accidentally delete the repo on github :wink:.

**Comment by Turbo87** [comment]
> worry that someone will accidentally delete the repo on github 😉

don't know what you're talking about... 🙄

**Comment by kategengler** [comment]
They definitely require internet access.

**Comment by locks** [comment]
Ah, then we can go on to the next question, what does the CLI team wanna do here!

**Comment by bertdeblock** [comment]
Closing for now.
