### ISSUE TITLE
Support Pods structure for util blueprint in Addon app folder.

### ISSUE THREAD

**Issue by ssylvia** [ember-cli/ember-cli#7255]
**.ember-cli**
```js
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": true,
  "ssl": true,
  "usePods": true
}
```

Currently if I run `ember g util path/sample-util` on a addon repo, ember-cli creates the following files:

```sh
installing util
  create addon/utils/path/sample-util.js
installing util-test
  create tests/unit/utils/path/sample-util-test.js
installing addon-import
  create app/path/sample-util/util.js
```

The first two files uses the pods structure. The third file that gets added to the `app` folder uses the classic folder structure. Also, the default export file it creates in `app` folder tries to import using the classic path in the addon folder so the file is not found:

```js
export { default } from 'ember-arcgis-pages-block-renderer/path/sample-util/util';
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.1
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
```

**Comment by kellyselden** [comment]
This seems like a lame bug easy enough to fix. Thanks for the issue.

**Comment by akashdsouza** [comment]
Hi, I looked into this and it seems that `util` follows the structure in `addon-import` blueprint. Would it be appropriate to have a check(something like blueprintName === 'util') over [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon-import/index.js#L52) to fix this issue?

**Comment by kellyselden** [comment]
It seems to me that "util" should be added here https://github.com/ember-cli/ember-cli/blob/816b540e741345eeb54756c9f5c7a5304d6108da/lib/tasks/generate-from-blueprint.js#L18.

I think it is a bug as utils should be exported from the addon and not automatically re-exported into the application. @ember-cli/core confirm?

**Comment by Turbo87** [comment]
@kellyselden 👍

**Comment by lifeart** [comment]
Is it still relevant?

**Comment by rwjblue** [comment]
Probably not, I don't think we are likely to add more pods functionality at this point.
