### ISSUE TITLE
Improve the Addon README.md Blueprint

### ISSUE THREAD

**Issue by offirgolan** [ember-cli/ember-cli#7278]
Hi all,

Looking at the recent changes to better improve the overall workflows of new applications (ember-welcome-page) as well as improving the debugging via the newly themed debug page, I think we should re-visit how addons are presented to rest of the community. 

Today, there are thousands of addons, each solving a different use case. These are the couple of things i've noticed:

1. The README is not detailed enough or missing key information
2. The README is not structured in an easy to read / understandable way.
3. Across each addon, every README is completely different.

My proposal - A well structured README blueprint for newly created addons to follow. 

It can go something like this:

```md
#  My Addon Name

## Overview
This section details what this addon is and what sort of problems it solves

## Features
This section shows the core features of this addon: 

i.e.)
- Feature 1
- Feature 2
- Feature 3

## Installation
\```
ember install my-addon-name
\``` 

## Usage
This section details how you actually use this addon.

## Contributing
This section details how to contribute to this addon.
```

The above template is a WIP and I'd love some feedback!

Not only can this standardize the addon community even more, but it can very well better the documentation being written (as it will be more structured) and improve the experience of new ember users / new addon developers.

**Comment by kellyselden** [comment]
I like the direction you are going. One thing I will say, the `ember install my-addon-name` section is something I think could be added without any debate ASAP.

**Comment by kellyselden** [comment]
I would like to suggest a header of "Motivation" instead of "Overview". I've used this style in some of my addons. I feel like it is my job to explain to you the problem I was having that motivated me to make an addon, and to convince you to invest in my solution/codebase/hack.

**Comment by offirgolan** [comment]
@kellyselden I like that 👍
