### ISSUE TITLE
Asset fingerprint not updating when dependent asset has changed

### ISSUE THREAD

**Issue by cbrevdev** [ember-cli/ember-cli#7280]
This is a parent issue for: rickharrison/broccoli-asset-rev/issues/118
where we'd like some help reviewing a pull request: rickharrison/broccoli-asset-rev/pull/121

## Steps to reproduce:

1. Have a css file which references an asset:

    ```
    .example {
        background-image: url('images/example.png');
    }
    ```

2. Perform a production build:

    `ember build --prod`

3. Inspect dist/ files:

    ```
    dist/assets/example-c5949321f343a6c3fdb970fe6d0815b3.css
    dist/images/example-ec54c6221f834e07c2ea5b49aea4af7a.png
    ```
   cat dist/assets/example-c5949321f343a6c3fdb970fe6d0815b3.css
   ```.example{background-image:url(images/example-ec54c6221f834e07c2ea5b49aea4af7a.png)}```

4. Replace example.png
5. Perform another production build

6. Inspect dist/ files:

    ```
    dist/assets/example-c5949321f343a6c3fdb970fe6d0815b3.css
    dist/images/example-b25c191452d4fd3cbef2c17d6e0a4f3c.png
    ```

   cat dist/assets/example-c5949321f343a6c3fdb970fe6d0815b3.css
   ```.example{background-image:url(images/example-b25c191452d4fd3cbef2c17d6e0a4f3c.png)}```

## Expected Behavior

.css fingerprint to be updated to reflect the change in asset

## Actual Behavior

.css fingerprint remains the same, causing subsequent resource integrity errors on browsers which have cached versions of the previous .css file

## Notes

Appears that https://github.com/rickharrison/broccoli-asset-rev is responsible for the file fingerprinting.

There's a couple of issues on this problem already:
* rickharrison/broccoli-asset-rev/issues/118
* rickharrison/broccoli-asset-rev/issues/115
* rickharrison/broccoli-asset-rev/issues/29

I've submitted a pull request:
* rickharrison/broccoli-asset-rev/pull/121

which we'd please like some help reviewing

## Other

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.12.2
http_parser: 2.7.0
node: 8.1.3
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
5.0.3
zsh: command not found: yarn
```

**Comment by rwjblue** [comment]
Thanks for your help triaging and fixing this @cbrevdev!  The upstream PR has been merged and released (as v2.6.0).
