### ISSUE TITLE
[fastboot] Currently impossible to use some packages on ember-cli-build.js

### ISSUE THREAD

**Issue by izelnakri** [ember-cli/ember-cli#7283]
I see some PRs have been merged that will allow us do this transformation on app.imports():
https://github.com/ember-cli/ember-cli/pull/7245 . This is an essential feature if one wants to use fastboot today.

app.import() seems to be the only `node_modules` permissive way for now to include a package on `ember-cli-build.js`. Since we have a single build now it is currently impossible to directly use packages that clash with fastboot!

I tried to use the github version of ember-cli to test this, it still doesnt work. Is there an estimate on when this will land to ember-cli beta? Additionally is there a suggested way to do this with what we have now on ember-cli beta?

```js
app.import(`${node_package_path}`, { using: [{ transformation: 'fastbootTransform' }]);
```

Thanks.

**Comment by kratiahuja** [comment]
The work in ember-cli is done and will be released in 2.16 beta. There is minor work left in ember-CPI-fastboot to register the transform so you can use it. I will send a PR for that today and there is an issue already tracking that.

This issue can be closed.

**Comment by MrChriZ** [comment]
@kratiahuja is there any documentation on how to do this - I can't find anything about it in either the fastboot guide or anywhere else?

**Comment by MrChriZ** [comment]
Ah never mind just found it - fastbootshim - right on the front page!
https://github.com/ember-fastboot/ember-cli-fastboot

**Comment by locks** [comment]
I believe this is no longer really necessary with ember-auto-import, and embroider v2? Please re-open if I'm mistaken!
