### ISSUE TITLE
Blueprint hook files() does not receive options

### ISSUE THREAD

**Issue by VulumeCode** [ember-cli/ember-cli#7287]
https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L227-L249

The `files()` hook is documented as "Override the list of files provided by the blueprint. Useful if you want to exclude certain files conditionally." However, it does not receive the locals as a parameter so there is nothing to do a conditional check on. 

It is kind of possible to get the entity options from `this.options`, but the `files()` hook is called multiple times and the first time `this.options` is still undefined. The default implementation of the `files()` hook makes this error when calling `this.filesPath(this.options)`, but it doesn't fail because the default `filesPath` doesn't use the parameter. 

This also means that, when not overriding the `files()` hook, using the `options` parameter for overriding the  `filesPath` hook can fail.

**Comment by bertatbagaar** [comment]
I'm experiencing this issue as well. When overriding the `filesPath` hook the `options` argument that's being passed along equals to `undefined`.

**Comment by locks** [comment]
@bertdeblock can you confirm it is still the case?

**Comment by bertdeblock** [comment]
Yes, this is still the case it seems. If you create a simple blueprint named `foo` and add the following:

```js
filesPath(options) {
  console.log(options);

  return this._super.filesPath.apply(this, arguments);
},
```

and run `ember g foo foo` it will log `undefined`. I assume it's just a timing issue that causes `options` to be `undefined` in this case.

To be honest, I'm not really invested anymore in this issue (but it's still one of course).
