### ISSUE TITLE
--test-port doc is misleading: not only for --server

### ISSUE THREAD

**Issue by john-kurkowski** [ember-cli/ember-cli#7289]
https://github.com/ember-cli/ember-cli/blob/c326cc0f12075397506d84d15018b14069afe201/lib/commands/test.js#L22

This documentation is misleading. `--test-port` _is_ used even when using vanilla `ember test` (without `--server`). On a shared CI server, we have simultaneous Ember test runs. We have to set `--test-port 0` everywhere, to avoid the test runs killing each other. 

Can you update the doc?

Maybe without `--server`, `--test-port 0` should be the default?

# Repro Steps

1. Run `ember test`
2. In another shell, run `ember test` again

**Expected:** Both runs complete successfully.
**Actual:** One run completes, the other blows up with `EADDRINUSE`.

**Comment by john-kurkowski** [comment]
> Maybe without `--server`, `--test-port 0` should be the default?

Or is this a backwards compatibility issue? Are people relying on the undocumented port that `ember test` does use...

**Comment by rwjblue** [comment]
I agree with both points here. We would definitely accept a PR fixing the documentation to make this clearer. I'd submit another PR for defaulting test-port to 0 though (I do agree with the change, but we would likely want to discuss more thourougly as a team first).

**Comment by bartocc** [comment]
I believe this old issue could be closed since #7294 has been merge

**Comment by rwjblue** [comment]
Thanks @bartocc!
