### ISSUE TITLE
Reload App In Vagrant VM

### ISSUE THREAD

**Issue by konradjurk** [ember-cli/ember-cli#7290]
Sadly, none of the feasible watchers that I know for a VirtualBox vagrant installation (watchman,node) make the Ember App reload, even though the changes are correctly synced to the VM. The host system is MacOS 10.12. The source directory is mounted from the host (no special configuration). I tried with NFS, but that didn't help with any of the watchers.

I tried with watchman v3.9.0 and v4.7.0. 'wachtman watch-list" contains the source directory.

Is there a way to manually trigger the reload? Maybe a script to run?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.2
http_parser: 2.7.0
node: 8.3.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
5.3.0
0.27.5
```

**Comment by kellyselden** [comment]
Thank you for the issue. This appears to be a question about how to use with something else, rather than a bug. You should ask this question on StackOverflow, as that is more suited for Q/A.
