### ISSUE TITLE
Error when creating a Glitch app: We currently do not support a name of `app`.

### ISSUE THREAD

**Issue by davidwkeith** [ember-cli/ember-cli#7293]
Tried to use Ember to create a [Glitch](https://glitch.com/) app, but they use `/app` as the directory for any app created on that platform. This causes the following error on init:

```
$ ember init
We currently do not support a name of `app`.
```

To reproduce:

1. open https://glitch.com/edit/#!/new-project
2. open the app menu (upper left, random name), Advanced, Open Console
3. `npm install ember-cli`
4. Attempt `ember init`

I created a [related issue](https://support.glitch.com/t/cant-create-an-ember-js-app-due-to-naming-conflicts/1870) in their Discourse forum.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.11.1
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10
0.27.5
```

**Comment by davidwkeith** [comment]
One possible workaround would be for ember-cli to support overriding the behavior where the app name match the directory name. Thoughts?

**Comment by Turbo87** [comment]
Once Module Unification lands we will use `src` instead so this issue will solve itself "soon"

**Comment by davidwkeith** [comment]
Hmm, true. But will `src` then be reserved? Seems like a possible recurring problem. (Granted `src` is far less likely cause conflicts, but it could be an abbreviation of a longer app name)

**Comment by locks** [comment]
Thank you for the report! Since MU was dropped, I don't see this limitation changing soon. A quick workaround would be to specify the name on init, `npx ember-cli init --name my-ember-app`, or to start from our prepared baseline, https://ember.glitch.me.
