### ISSUE TITLE
Ember-cli watching entire tree (including tmp) by default?

### ISSUE THREAD

**Issue by BenV** [ember-cli/ember-cli#7295]
We're using ember-electron and started noticing problems on Windows when trying to start our project. It turns out that the `Watcher` module is watching `tmp`, `electron-out`, and even `.git` by default. 

This isn't much of a problem when using watchman (like we are on OSX), since you can ignore directories easily, but when using the default Node watcher it is quite problematic. In particular it leads to `EPERM` symlinking issues on Windows (even as administrator)

I tried to look to see if there was a configuration option for threading through the `ignored` param to the `sane` constructor, but couldn't find one.

As a workaround I am monkey-patching `Watcher.buildOptions` to read the `.watchmanconfig` file and build an array of ignored directories to pass along to `sane`. I could work on creating a pull request for this, but wanted to open an issue first since I'm not sure if that would be an acceptable solution, or if there should be some other sort of configuration option created (or maybe this is a regression?)

Please let me know if you need any more information. Thanks!

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember version --verbose
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: win32 x64

npm --version
4.6.1

yarn --version
0.27.5
```

**Comment by stefanpenner** [comment]
> but when using the default Node watcher it is quite problematic.

It should not be watching root (unless you have a misbehaving add-on) unless you are using watchman.

**Comment by stefanpenner** [comment]
```
ember s --port 1338 --watcher=node &

**Comment by BenV** [comment]
Cool, I will try to track down what is watching the root node and get back to you. Thanks for the quick response!

**Comment by BenV** [comment]
Tracked this down to a `Funnel` that was including the root directory of the project, sorry to have wasted your time, and thanks for pointing me in the right direction!

**Comment by stefanpenner** [comment]
> Tracked this down to a Funnel that was including the root directory of the project, sorry to have wasted your time, and thanks for pointing me in the right direction!

Not a problem, we should likely detect this case in broccoli and provide a helpful error or something...

**Comment by BenV** [comment]
A warning with the line/file where the funnel is created would be very helpful. It is an easy mistake to make: https://github.com/felixrieseberg/ember-electron/blob/master/lib/utils/assemble-tree.js#L100 (we have a PR  open that adds an `UnwatchedDir` to resolve this one). Thanks again!
