### ISSUE TITLE
Ember,js. Modify app.js and vendor.js before the final integrity seal. One custom step in build pipeline?

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7299]
I need to change something in my final

`app.js` and `vendor.js`

but obvioulsy I need to modify them before the ember-cli-sri integrity https://ember-cli.com/user-guide/#subresource-integrity does its job.

How to do?

There are somewhere the pipeline steps?

**Can I insert one step before the final one?**

**Comment by luxferresum** [comment]
[this is 1:1 this SO question](https://stackoverflow.com/questions/45773646/ember-js-modify-app-js-and-vendor-js-before-the-final-integrity-seal-one-custo)

**Comment by kellyselden** [comment]
Closing as SO is the appropriate place to ask this question.
