### ISSUE TITLE
Feedback on Developer Experience

### ISSUE THREAD

**Issue by dmfenton** [ember-cli/ember-cli#7302]
Hi, thanks for making Ember!

My team and I love using Ember and it's helped make us far faster. I wanted to provide some feedback on Ember's developer experience. 

One thing I notice is that Ember silently swallows many errors. I often have to turn on `pause on caught exceptions` to find the root cause of an issue. That is useful, but doesn't work well with live reload because it requires skipping through a lot of exceptions in polyfils.

I'm not sure what it would take to accomplish this, but it would be super helpful if Ember automatically logged any unhandled errors in dev mode.

Thanks again,

Daniel Fenton
Software Engineer
Esri

**Comment by Cryrivers** [comment]
Could you list one example that Ember silently swallows errors? Thank you.

**Comment by twokul** [comment]
@dmfenton I'd be curious to know about silent errors too.

also, here's something you could do in the meantime:

```sh
cd your-app/ && node --inspect ./node_modules/ember-cli/bin/ember build
```

The command above will print out the url, something like `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/dc9010dd-f8b8-4ac5-a510-c1a114ec7d29`, open it with Chrome and you have access to regular Chrome Dev Tools with the ability to pause on caught exceptions. You can find more info [here](https://nodejs.org/api/debugger.html#debugger_advanced_usage).

Make sure, you are on node 6+ though.

**Comment by Cryrivers** [comment]
@dmfenton @twokul 

you might want to add `--debug-brk` as well, which would stop at the first line of the code.

```
cd your-app/ && node --inspect --debug-brk ./node_modules/ember-cli/bin/ember build
```

**Comment by dmfenton** [comment]
Here's a contrived example from the renderTemplate hook of a route. I end up with a blank screen and no errors reported in the console or dev tools unless I turn on pause on caught exceptions

```js
  renderTemplate (controller, model) {
    // Ember.debug('ApplicationRoute::renderTemplate fired...');
    // if no access, render the sign-in template
    // Ember.debug('Application Route: RenderTemplate ' + model.status);
    if (model.status === 200) {
      // only inject the headData if the source of the model was an xhr
      // this prevents "fouc"
      if (model.source === 'xhr') {
        // TODO: Inject css
      }
      let previousTransition = controller.get('previousTransition');
      if (previousTransition) {
        controller.set('previousTransition', null);
        previousTransition.retry();
      } else {
        this.render();
      }
    } else {
      const opts = {
        model: model
      };
      if (model.status === 500) {
        this.render('gateway.error', opts);
      } else if (model.status === 301) {
        this.render('gateway.https-only', opts);
        throw new Error('foo');
        fetch(this.get('appSettings.portalUrl') + '/sharing/rest/self?f=json')
        .then(r => { return r.json(); })
        .then(self => console.log(self));
      }
      if (this.get('isFastBoot')) {
        // in this case, we want to let the client-app handle things...
        // so just render the loading view
        this.render('gateway.loading', opts);
      } else {
        if (model.status === 403) {
          if (this.get('session.isAuthenticated')) {
            this.render('gateway.noaccess', opts);
          } else {
            // TODO: If this is an arcgisonline clientKey we should be showing an inline auth template
            this.render('gateway.403', opts);
          }
        }
        if (model.status === 404 || model.status === 400) {
          this.render('gateway.404', opts);
        }
      }
    }
  },
```

**Comment by dmfenton** [comment]
btw:

ember --version
ember-cli: 2.14.2
node: 8.3.0
os: darwin x64

**Comment by workmanw** [comment]
It seems like there might be some confusion between [ember-cli](https://github.com/ember-cli/ember-cli) and [https://github.com/emberjs/ember.js](ember.js). 

This repo is for the build tools that Ember (and others) use for development and production builds. The `ember.js` repo houses all runtime Ember.js code, components, helpers, router, templates, etc. 

A bug relating to `renderTemplate` would belong in the ember.js repo. However, this looks a little more like a support issue. For that reason, I'd point you to [discuss.emberjs.com](discuss.emberjs.com), StackOverflow or the Ember.js slack community.

**Comment by twokul** [comment]
@dmfenton I'm going to close this for now, let us know if you have any questions. As @workmanw pointed out StackOverflow or Discuss forum would be a better venue for these kind of questions.
