### ISSUE TITLE
Update ember-cli from 2.12.1 to 2.12.2

### ISSUE THREAD

**Issue by dmtask** [ember-cli/ember-cli#7304]
Hi,

after a ember-cli Update from 2.12.1 to 2.12.2 my Login not longer works. I became the following error:
![t9ckh](https://user-images.githubusercontent.com/17166931/29623254-0c265aea-8826-11e7-8100-3353a6fb7551.png)

The Full Stacktrace:
![dsj7p](https://user-images.githubusercontent.com/17166931/29623263-11edc5f8-8826-11e7-9e59-538b77eb6d05.png)

Anyone an idea why?

This is my `new.js`
```
let store = this.get('store');

            // Delete all existing sessions to avoid conflicts in the store
            store.unloadAll('user_session');

            // Create new session object
            let userSession = store.createRecord('user_session', {
                email: this.get('email'),
                password: this.get('password')
            });


            // Save new session object (authentication on the server)
            userSession.save().then(
                () => {
                    // Authentication successful, store session and go to the dashboard
                    this.get('session').registerUserSession(userSession);
                    this.transitionToRoute('dashboard');
                },
                (e) => {
                    // Authentication failed
                    Ember.Logger.error('Login failed', e);

                    // TODO translate
                    this.get('toast').error('Login failed');
                }
            );
```

**Comment by backspace** [comment]
I’m no expert, but this seems to me an [Ember Data issue](https://github.com/emberjs/data/issues/4972), not Ember CLI.

**Comment by stefanpenner** [comment]
It does seem like an ember-data issue not ember-cli. But I believe this is a fixed version of ember-data.  My recommendation is to update to the latest version of ember-data and trying again.

**Comment by stefanpenner** [comment]
I believe https://github.com/emberjs/data/issues/5125 addresses the issue you are running into

**Comment by stefanpenner** [comment]
Looks like the fix is unreleased, I'll plan for a release of ember-data by tomorrow. That should address the above issue.

**Comment by dmtask** [comment]
Ah ok. Thank you @stefanpenner, i will wait for the new Release.
