### ISSUE TITLE
Additional Global Binaries Added by Ember CLI Dependencies

### ISSUE THREAD

**Issue by rtablada** [ember-cli/ember-cli#7312]
## The Issue

When installing Ember CLI, there are potential extra global binaries that are being added when running `yarn global add ember-cli` or `npm install -g ember-cli`.

This recently came to my attention when `cleancss` started popping up as an installed binary even though my development environment does not have `clean-css` declared as a direct global dependency.

While `cleancss` is a prime example and was identified, there are potentially other global binary dependencies that are being added as well (I will update with the output from a clean environment).

## Why This Matters

Introducing new binaries (especially those that are not used or documented in the Ember ecosystem) can cause confusion for developers.

There are also potential security risks if these binaries conflict or overwrite a user's existing binaries.
This could manifest in a simple way where in the case of `cleancss` it may conflict with the version of `cleancss` they want to have on their system.
But, in a more extreme case, a deeply nested dependency of Ember-CLI could expose a `curl` binary that pretends to be the full `curl` program but also adds a logger.

## What Could Be Wrong

Trying to debug this it looks like `ember-cli-preprocessor-registry` has had `clean-css` as a child dependency for [quite some time](https://github.com/ember-cli/ember-cli-preprocessor-registry/commit/24ea3366d041e38562ec43ec87e4b00e983d3a55).
So, it doesn't directly seem like a new dependency is the direct cause of the error.

Other things that I suspect, but have not had the chance to look through:

* Looks like `clean-css` also has a `clean-css-cli` package. This `clean-css-cli` may have been merged as part of a minor or patch release resulting in a new binary
* Yarn or NPM may not be properly registering global binaries (IIRC yarn should only publish binaries for direct dependencies and not child deps ie. `ember-cli` publishes `ember` but not any of the binaries of it's dependencies).

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.14.2
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
3.10.10
0.27.5
```

For reference the dependency graph that results in `clean-css` as a dependency:

```
ember-cli@2.14
  - ember-cli-preprocess-registry@^3.1.0
    - broccoli-clean-css@^1.1.0
      - clean-css-promise@0.10
        - clean-css@3.4.5
```

**Comment by rtablada** [comment]
After uninstalling all global packages via yarn and running `yarn global add ember-cli` the resulting `~/.config/yarn/global/node_modules/.bin` directory has:

```
babylon                   esvalidate                json5                     nopt                      tap-parser
can-symlink               handlebars                loose-envify              rimraf                    testem
cdl                       has-ansi                  markdown-it               sane                      uglifyjs
cleancss                  inline-source-map-comment mime                      semver                    uuid
ember                     js-yaml                   mkdirp                    sort-package-json         which
esparse                   jsesc                     mustache                  strip-ansi                🐹
```

**Comment by rtablada** [comment]
Ok, I can say that after using `npm install -g ember-cli`, only the proper binaries are being registered to the user's path.

**Comment by kellyselden** [comment]
> only the proper binaries are being registered to the user's path

As in only the single binary of `ember`? or more?

**Comment by rtablada** [comment]
@kellyselden when using `npm install -g ember-cli` only `ember` and `🐹` are available in the global `.bin` directory and by result: the user's path.

**Comment by kellyselden** [comment]
@rtablada I appreciate your detailed write up, but should this be moved to an issue with yarn?

**Comment by rtablada** [comment]
@kellyselden closed and referenced on the yarn issue. I had not realized that this was a yarn issue before submitting.

**Comment by kellyselden** [comment]
@rtablada Thanks for working it out in the open!
