### ISSUE TITLE
Allow overriding blueprint "main" file

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli#7313]
It seems we currently hardcode "blueprint packages" (NPM packages with the `"ember-blueprint"` keyword, like https://github.com/glimmerjs/glimmer-blueprint) to define the blueprint in its `index.js` file: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1292

It would be nice for this to be configurable, something like:

```js
{
  "name": "my-multi-purpose-package",
  "keywords": [
    "ember-blueprint",
    "ember-addon"
  ],
  "ember-addon": {
    "main": "ember-addon-main.js"
  },
  "ember-blueprint": {
    "main": "ember-blueprint-main.js"
  },
  // ...
}
```

This would allow a package to be an addon, blueprint, library, etc at the same time.

**Comment by chancancode** [comment]
We can make it default to `index.js` for backwards compatibility, which is also how "ember-addon main" works I believe

**Comment by rwjblue** [comment]
Seems reasonable to me.

**Comment by Turbo87** [comment]
yeah, seems good to me too
