### ISSUE TITLE
Can we update .editorconfig for javascript?

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7318]
For example:

- anon functions without space;

- "brace_style": "collapse-preserve-inline" like in this issue: https://github.com/HookyQR/VSCodeBeautify/issues/67

**Comment by rwjblue** [comment]
I'm not sure what you are suggesting concretely, can you provide more details?  I'd suggest in this case to submit a pull request with your proposed changes along with an explanation of what the changes do so we can discuss the pros/cons...

**Comment by Turbo87** [comment]
@johnunclesam there are no such properties defined in https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties 🤔

**Comment by johnunclesam** [comment]
@Turbo87 you're right! Such a pity! I fixed this using Prettier extension in my VSCode.
