### ISSUE TITLE
'ember init' not saving changes to file system when overriding files

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli#7321]
While upgrading my Ember projects to 2.15.0, I noticed that answering _yes_ to overwriting changes for a particular file does not actually save it to the file system. 
There are no errors on the console.
Write permissions are enabled.. am I missing something?

If I recall correctly, this used to work fine on my machine once upon a time.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.0
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2l
os: linux x64
3.10.10
bash: yarn: command not found
```

**Comment by Dhaulagiri** [comment]
This has been happening to me for some time now but I just assumed something was wrong with my system.  @Turbo87 what would be helpful here in terms of how to reproduce/verify this?

**Comment by t-sauer** [comment]
I was confused by this recently as well. The files get overwritten once you finished the whole ember init process (ant not immediately after answering yes). 
I don't know if this is intended or not, but this might be the problem described here.

**Comment by kellyselden** [comment]
The `init` process is designed to be atomic, meaning you can abort having way through the prompts and nothing will be changed. @myartsev Is this the behavior you are seeing? If you get through all the prompts, are the files then changed?

**Comment by myartsev** [comment]
That's right @kellyselden @t-sauer, just did this for the 2.16 release and files do get overwritten once the init process is finished.  

I don't remember exactly why this was a problem for me earlier tbh, I suppose I was expecting the file to change after answering _yes_ to overwriting and then wanted to change a few things on top of it manually for a merge conflict. Now that I know the init process is atomic, its not really an issue.  But if you **don't** know about the atomic behaviour then it can be confusing, and it looks like I am not the only one who has been caught off-guard by it.  

Is it worth adding a note about this behaviour somewhere? Perhaps a little blurb to the console when you start to run ember init? Maybe it's really obvious and this is a non-issue. I'll leave that up to the experts =)

**Comment by locks** [comment]
Reading the discussion the original point seems to have been addressed/clarified. Let us know if there are still problems!
