### ISSUE TITLE
2.16 beta - New modules imports not used in blueprints

### ISSUE THREAD

**Issue by Dhaulagiri** [ember-cli/ember-cli#7326]
Using ember-cli@2.16.0-beta.1, when I use `ember g` to generate anything I would expect the new modules import syntax to be used but I get the "old" globals imports instead:

```
ember g service foo

import Ember from 'ember';

export default Ember.Service.extend({
});

```

/cc @rwjblue from our discussion in Slack

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
 ~/P/e/modulestest (master)> ember version --verbose
ember-cli: 2.16.0-beta.1
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
 ~/P/e/modulestest (master)> npm --version 
3.10.10
 ~/P/e/modulestest (master)> yarn --version
0.27.5
 ~/P/e/modulestest (master)>
```

**Comment by rwjblue** [comment]
Thank you for reporting!  I just checked, and it looks like somehow I mucked up the release of 2.16.0-beta.1 and the old blueprints are still the ones published ([check here](https://unpkg.com/ember-source@2.16.0-beta.1/blueprints/component/files/__root__/__path__/__name__.js)).  I'll dig and try to get a `.beta.2` published soon.

**Comment by rwjblue** [comment]
Should be fixed in 2.16.0-beta.2.

**Comment by rwjblue** [comment]
Can someone confirm this is working properly now with ember-source@2.16.0-beta.2?

**Comment by locks** [comment]
I have initialized a new project with beta 2 and everything seems a-ok. Closing as fixed.
Thanks for reporting and let us know if the issue persists for you!

**Comment by alexmasita** [comment]
Hi Team.  Sorry to revisit this.  I recently upgraded from 2.15.0 to 2.16.2, I tried to then generate a component via `ember g component status-manager` and got a template file that still uses the "old" globals imports:

```
import Ember from 'ember';

export default Ember.Component.extend({
});
```
Output from ember version --verbose && npm --version && yarn --version:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
```
`npm version: 3.10.10`
`yarn version: 0.27.5`

**Comment by MicFin** [comment]
+1
