### ISSUE TITLE
You have not included `ember-cli-shims` in your project's `bower.json` or `package.json`.

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli#7327]
I'm following this: https://emberjs.com/blog/2017/09/01/ember-2-15-released.html.

I upgraded my `package.json` with this:
```

    "ember-cli": "^2.16.0-beta.1",
    "ember-source": "^2.16.0-beta.1",
    "ember-cli-babel": "^6.8.2"
    --- removed "ember-cli-shims": "^1.1.0"
```

I receive this warning in `ember s`:

WARNING: You have not included `ember-cli-shims` in your project's `bower.json` or `package.json`. This only works if you provide an alternative yourself and unset `app.vendorFiles['app-shims.js']`.

**Comment by kellyselden** [comment]
I believe you are missing the latest ember-cli-babel

**Comment by johnunclesam** [comment]
Nope, I updated the first post. I have `"ember-cli-babel": "^6.8.2",`.

**Comment by rwjblue** [comment]
We need to remove that warning.

**Comment by rwjblue** [comment]
Was fixed by https://github.com/ember-cli/ember-cli/pull/7353.
