### ISSUE TITLE
Routes in the addon dummy app do not have a store?

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli#7334]
When working with a route in the dummy test app for an addon, the store is not there like in a regular ember app. Is this by design?

Here's a simple repro:
```
ember addon test-addon
cd test-addon
ember g route index
```

_tests/dummy/app/routesindex.js_
```
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.get('store').findAll('foo');
  }
});
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.1
http_parser: 2.7.0
node: 6.11.3
v8: 5.1.281.107
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: linux x64
3.10.10
bash: yarn: command not found
```

**Comment by rwjblue** [comment]
Yes, this is intentional. Addons do not include ember-data by default, you can easily install via `ember install ember-data`.

**Comment by myartsev** [comment]
I see - it makes sense now that I am looking at package.json, and my bad if I missed it in the [documentation](https://ember-cli.com/extending/#developing-addons-and-blueprints), but even a  second look didn't seem to mention anything about ember-data not being included by default.

However, as expected, it looks to me like installing ember-data this way also includes it in the resulting build of the addon itself? And therefore any Ember apps using this addon will also see an increase in the file sizes loaded by the addon.

In my scenario, I only need ember-data for the dummy test app, not for the add-on itself. Is there a way to accomplish that? The extra amount of code is not insignificant.

PROD build of the addon before ember-data:
```
File sizes:
 - dist/assets/dummy-c433925cf9f595e238f433087b068de5.js: 3.21 KB (1.05 KB gzipped)
 - dist/assets/dummy-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-14e22c59f41db328375bed386a20c1b7.js: 590.98 KB (158.03 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

PROD build of the addon after ember-data:
```
 File sizes:
  - dist/assets/dummy-1c0817c093f8a3d9493de18cc85791b5.js: 4.69 KB (1.21 KB gzipped)
  - dist/assets/dummy-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
  - dist/assets/vendor-24cf6174987155f6f7b808ad13d4bac8.js: 736.82 KB (190.95 KB gzipped)
  - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

**Comment by myartsev** [comment]
Looks like I spoke too soon there; if I compare the build output of an Ember app using the add-on with and without ember-data, the resulting file sizes are the same. I'm assuming Ember is being smart enough and recognizing that it doesn't need to include ember-data code twice.

Apologies for the false alarm and thank you for the help :)
