### ISSUE TITLE
Support javascript in .ember-cli 

### ISSUE THREAD

**Issue by peabnuts123** [ember-cli/ember-cli#7336]
Apologies if this has come up before, it's hard to search the name of the repo within its issues, as it basically just returns everything.

The convenience of `.ember-cli` is nice as it offloads the configuration into a more permanent place, but being just a static JSON file is kind of limiting as it doesn't support any conditional logic or even commenting, really (comments do work, but they have issues around formatting, could be a separate issue). 

Much like many different frameworks' config files before this, it would be optimal if this were alternatively a javascript file, potentially a NodeJS module that could export a config object.

A real-world use-case for this is on our current project where we have many different environments configured using the `proxy` flag and we need to switch between these every so often. Currently we have these all in the same file, commented out like below:

```
  "proxy": "https://dev.environment",
  // "proxy": "https://test.environment",
  // "proxy": "https://uat.environment"
```

but it would be nice if we could make a nice `const proxies = { … }` object or similar and then just specify `proxy: proxies.dev`, for example. 
Another reason this would add value would be integrations between the ember config and other aspects of workflows. For example, we are actually reading this `.ember-cli` file ourselves at the moment and reading out the `proxy` value for use in some other parts of our workflow. We can't `require` this file as it contains comments / isn't JSON so we are basically forced to call ``eval(`var config = ${fs.readFileSync('.ember-cli')}`);`` which nicely treats it as JavaScript, but we are unable to take advantage of this as, obviously, any actual JavaScript in the file would cause ember-cli to fail to parse it. 

I see this working as `ember serve --config-file .ember-cli.js`, or similar, much like many other commands do already. Alternatively, the name `.ember-cli` could be magic and detect either a JSON/JS version a bit like the way `.eslintrc` works.

**Comment by kellyselden** [comment]
I support this idea. Not sure on the implementation though, whether it's a file extension change like .js or .yml, or if we detect format inside file. Emulating something like eslint may be the best path forward.

**Comment by pichfl** [comment]
There is [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) which Prettier.io, StyleLint and others use or [rc](https://github.com/dominictarr/rc). 

Might be worth to rely on a commonly used module here.

**Comment by kellyselden** [comment]
@pichfl I agree on using something already built. Thanks for bringing those up, I hadn't researched the space yet.

**Comment by twokul** [comment]
added functionality to [Yam](https://github.com/twokul/yam/releases/tag/v0.0.23) to support JS files (so `.ember-cli` & `.ember-cli.js`)

**Comment by peabnuts123** [comment]
Oh, I see. And `yam` is used to require the `.ember-cli` file. Seems to be working on my end now that I've upgraded ember-cli. I'm going to close this (just rename `.ember-cli` to `.ember-cli.js` and add a `module.exports` to the file)
