### ISSUE TITLE
Add  --no-engine-strict to install / update instructions

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-cli#7339]
Since npm@5 silently ignores the `"engines"` field, I have configured it with the `engine-strict` option.

This means that the `npm install -g ember-cli` command now fails with an error:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for sourcemap-validator@1.0.5: wanted: {"node":"0.10.x"} (current: {"node":"8.5.0","npm":"5.3.0"})
npm ERR! notsup Not compatible with your version of node/npm: sourcemap-validator@1.0.5
npm ERR! notsup Not compatible with your version of node/npm: sourcemap-validator@1.0.5
npm ERR! notsup Required: {"node":"0.10.x"}
npm ERR! notsup Actual:   {"npm":"5.3.0","node":"8.5.0"}
```

It installs (and works) with: `npm install -g ember-cli --no-engine-strict`

Alternatively, don't depend on eg. `sourcemap-validator@1.0.5`, which only target `node@0.10.x`.

**Comment by Turbo87** [comment]
this was fixed by https://github.com/ben-ng/sourcemap-validator/pull/9
