### ISSUE TITLE
`ember server` doesn't work with ember-cli 2.15.1

### ISSUE THREAD

**Issue by mabab** [ember-cli/ember-cli#7352]
I have node 4.8.4, yarn 1.1.0, ember-cli 2.15.1, ember-data 2.14.10
And when I try to execute `ember server` I get the error:

> Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Class.buildBabelOptions (/usr/src/fe/node_modules/ember-data/index.js:183:25)
>     at Class._setupBabelOptions (/usr/src/fe/node_modules/ember-data/index.js:201:31)

And day before everything was ok. Please help me find out reason of this error.

**Comment by Turbo87** [comment]
@mabab this looks a lot like an issue in Ember Data. they were not testing against Node 4, but they changed that lately, so if you use a newer Ember Data version everything should work again.

Closing as this is not an issue with Ember CLI itself.
