### ISSUE TITLE
Passing --no-yarn to ember install has no effect

### ISSUE THREAD

**Issue by PieterJanVdb** [ember-cli/ember-cli#7355]
Using the --no-yarn option when using ember install has no effect, meaning it will still use yarn.
Same when using --yarn=false.

![reproduction](https://i.imgur.com/v5WxCh6.png)

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.1
http_parser: 2.7.0
node: 6.9.2
v8: 5.1.281.88
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.9
0.21.3
```

**Comment by rwjblue** [comment]
In general, if you don't want to use `yarn` you would delete `yarn.lock`.  `ember-cli` will use `npm` if there is no `yarn.lock`.  IMHO, having a `yarn.lock` but intentionally not maintaining it when being asked to install things is a really odd position to be in and almost certainly will result in bugs...

**Comment by PieterJanVdb** [comment]
@rwjblue  Ah my bad, I just thought it was a bug as --yarn is an option specified on the "ember install" command, as seen here (lib/commands/install):

```
module.exports = Command.extend({
  name: 'install',
  description: 'Installs an ember-cli addon from npm.',
  aliases: ['i'],
  works: 'insideProject',

  availableOptions: [
    { name: 'save',       type: Boolean, default: false, aliases: ['S'] },
    { name: 'save-dev',   type: Boolean, default: true,  aliases: ['D'] },
    { name: 'save-exact', type: Boolean, default: false, aliases: ['E', 'exact'] },
    { name: 'yarn',       type: Boolean, description: 'Use --yarn to enforce yarn usage, or --no-yarn to enforce npm' }, // no default means use yarn if the blueprint has a yarn.lock
  ],

```

But I completely follow your reasoning of having a yarn.lock and not maintaining it. We used to use yarn in the project I tried to use ember install --no-yarn but have since stopped using it and must not have removed the yarn.lock.

Shall I close the issue, or edit the command so that 'yarn' is not one of the CLI options?

**Comment by rwjblue** [comment]
Hmm. Yes, if we have that option it should work. 

@turbo87 - Thoughts?

**Comment by Turbo87** [comment]
fixed by https://github.com/ember-cli/ember-cli/issues/7355
