### ISSUE TITLE
Ember JS stalls browser when server is disconnected

### ISSUE THREAD

**Issue by martinpsz** [ember-cli/ember-cli#7358]
Verbose version results:

ember-cli: 2.15.1
http_parser: 2.7.0
node: 8.4.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.22.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.4.2
-bash: yarn: command not found

I am new to Ember JS and have recently made an attempt to learn about the framework by following the tutorials on the website. I am attempting this on the Mac OS 10.13.1 and the latest version of Chrome ( 61.0.3163.100 ). The other particulars of my stack are listed above.

Here is my issue: when I shut down the ember server by pressing Ctrl C, I see a message: 'cleaning up', which is soon replaced by my command line prompt in the Terminal. However, my browser stalls. I get the Mac color wheel spinning and I cannot close the browser window. I end up having to do a hard reboot of my computer. I tried to remedy this situation by disabling auto-reload but that has not solved the issue either. Is this a known issue? If so, what can I do to remedy this situation?

Thank you!

**Comment by ro0gr** [comment]
It sounds weird. 
Does it happen when you do 'ember serve' and than open your browser at http://localhost:4200?
Right?

What happens if you don't open ember app and then shutdown server. Does your browser work as expected then?

I think your 'package.json' might be also helpful. Can you share it please?

**Comment by ro0gr** [comment]
Also can you reproduce it in another browser?

**Comment by martinpsz** [comment]
Yes, it happens when I run ember serve, open the browser at localhost 4200 and then close the server. From the command line it looks like everything worked but the Chrome browser freezes. The package.json file can be seen below:

`{
  "name": "super-rentals",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for super-rentals goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~2.15.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.3.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "~2.15.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.15.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  }
}
`

I haven't had the chance to run this on another browser. I'll do so later if you think Chrome is the source of this issue.

**Comment by ro0gr** [comment]
I don't think Chrome is the source of this issue. I just want to exclude it from the equation.

Your `package.json` doesn't have any extra dependencies, so it's definitely not a misbehaving 3rd party lib.

**Comment by martinpsz** [comment]
I did a quick test (i.e put a simple h1 tag in the index.html document) using Firefox. I navigated to the directory with the project, ran 'ember serve', made my change and ctrl-c'ed out of ember server.  Firefox did not become frozen. Not sure if this counts as an adequate test but a successful one nonetheless. Looks like it may be a Chrome issue.

**Comment by ro0gr** [comment]
> i.e put a simple h1 tag in the index.html document

tbh I'm not sure what you are doing here. Anyway if your Chrome fails and Firefox doesn't under the same conditions I would blame some extension first.

Does this issue reproduces in a Chrome with all extensions disabled? If yes you can try to detect it by enabling extensions one by one until Chrome starts to hang.

At this point this issue does't sound like an ember-cli bug.
