### ISSUE TITLE
"found an unknown transformation name amd" when trying to import asset from addon

### ISSUE THREAD

**Issue by hakilebara** [ember-cli/ember-cli#7370]
I can import a standard anonymous AMD asset in `ember-cli-build.js`

```javascript
  app.import('node_modules/cropperjs/dist/cropper.js', {
    using: [
      { transformation: 'amd', as: 'cropperjs' }
    ]
  });
```
however the same import fails in the `included` hook of an addon or in-repo-addon
```javascript
/* eslint-env node */
'use strict';

module.exports = {
  name: 'beta-bug',

  isDevelopingAddon() {
    return true;
  },
  included(app) {
    this._super.included.apply(this, arguments);

    const srcFile = 'node_modules/cropperjs/dist/cropper.js';
    app.import(srcFile, {
      using: [
        { transformation: 'amd', as: 'cropperjs' }
      ]
    });
```
This is the error message I get:
```javascript
while import node_modules/cropperjs/dist/cropper.js: found an unknown transformation name amd. Available transformNames are:
Error: while import node_modules/cropperjs/dist/cropper.js: found an unknown transformation name amd. Available transformNames are:
    at options.using.forEach.entry (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:1710:19)
    at Array.forEach (<anonymous>)
    at EmberApp._import (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:1701:23)
    at EmberApp.import (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at Class.included (/Users/kaos/Projects/ember-beta/lib/beta-bug/index.js:14:15)
    at Class.superWrapper [as included] (/Users/kaos/Projects/ember-beta/node_modules/core-object/lib/assign-properties.js:34:20)
    at project.addons.project.addons.filter.addon (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:541:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:538:47)
    at new EmberApp (/Users/kaos/Projects/ember-beta/node_modules/ember-cli/lib/broccoli/ember-app.js:151:10)
```

The issue can be reproduced with a clean install of ember 2.17.0-beta.1 and an AMD asset to import in an in-repo-addon. 

It can also be reproduced by installing ember-cropperjs with a clean install of ember and trying to `ember serve` 

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.17.0-beta.1
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.4.2
1.1.0
```

**Comment by john-griffin** [comment]
Also hit this after upgrading to 2.16. One of our dependancies is ember-cli-showdown that uses amd transformation. 

https://github.com/gcollazo/ember-cli-showdown/issues/58
https://github.com/gcollazo/ember-cli-showdown/blob/b2fb8314730b73170c475d9c8816d45da8800ed7/index.js#L16

**Comment by kpfefferle** [comment]
I am experiencing the same issue with `ember-cli@2.16.1` and [`ember-cli-testdouble@0.1.2`](https://github.com/isleofcode/ember-cli-testdouble/blob/db33d904660e5cc9d5ee88575343bf7233055c8a/index.js#L34)

**Comment by hakilebara** [comment]
here is a list of affected addons: https://emberobserver.com/code-search?codeQuery=transformation%3A%20%27

**Comment by venkatd** [comment]
Also experiencing this issue. I've got a minimal ember app reproducing this issue attached.

[ember-amd-bug.zip](https://github.com/ember-cli/ember-cli/files/1373205/ember-amd-bug.zip)

Just run `ember s` to see it print out the error.

**Comment by kratiahuja** [comment]
I'll look at this tonight. My apologies for the mess here.

**Comment by kratiahuja** [comment]
Ok I know the issue. This issue will occur when you import in the `included` hook. We register the the transform after that. I'll send out a PR tonight.

**Comment by thomblake** [comment]
This is blocking our upgrade to 2.16 as well.

**Comment by thomblake** [comment]
Is importing in the included hook the right thing to do?

**Comment by rwjblue** [comment]
Yes, generally speaking in an addon the right place to `this.import` is in the `included` hook.  @kratiahuja has an open PR over in #7377 fixing this for us...

**Comment by thomblake** [comment]
I upgraded to 2.16.2 and it solved this problem for me. Thanks @kratiahuja !

**Comment by kratiahuja** [comment]
Thank you!

**Comment by ef4** [comment]
For anybody else who's wondering why they still see this bug: the latest beta (~2.17.0-beta.1) doesn't include this fix yet.
