### ISSUE TITLE
Beta 2.17 showing "Please install an Ember.js test framework addon or update your dependencies"

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#7374]
I just updated my addon, ember-shepherd, to use ember-cli 2.17 beta and now I see `Please install an Ember.js test framework addon or update your dependencies` in the console. I also updated to the latest ember-cli-qunit beta, but I'm not sure what else may be causing this issue.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.17.0-beta.1
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
```

**Comment by rwjblue** [comment]
* Do you have a branch of `ember-shepherd` that I can take a look at?  
* What does `npm ls ember-cli-qunit` tell you?
* Is there a stack trace alongside that message?

**Comment by rwjblue** [comment]
Nevermind, https://github.com/emberjs/ember-qunit/pull/284 should fix.

**Comment by rwjblue** [comment]
OK, updating to `ember-qunit@3.0.0-beta.3` should fix the issue (if using `yarn` a `yarn upgrade` should do the trick).
