### ISSUE TITLE
Build spawns dozens of long lived node processes

### ISSUE THREAD

**Issue by musaffa** [ember-cli/ember-cli#7379]
## Problem:

After upgrading `ember-cli` from 2.14 to 2.16, ember `server s` command has started to take 97% of the computer memory. Here's a screenshot of the system monitor after `server s` command has been run:

![screenshot from 2017-10-12 02-43-28](https://user-images.githubusercontent.com/294616/31492093-5ca369e2-af6b-11e7-814a-19ba554de339.png)

These node processes are actually `broccoli-babel-transpiler` worker processes. Here's a screenshot of these live processes in `htop`:

![screenshot from 2017-10-12 02-44-31](https://user-images.githubusercontent.com/294616/31492155-a9fa7c80-af6b-11e7-9db8-fb7b7303a527.png)

As long as `ember s` is live, these processes also live on. Once `ember s` is stopped these processes also die. But If `ember s` is run again, then the process monitor doesn't show any live `node` process. It happens only for the first build. And the first build takes a quite a lot of time compared to ember-cli `2.14`.

## Steps to reproduce:
```
$ ember new test-build --yarn
$ cd test-build
$ ember install ember-cli-mirage@0.3.4
$ ember s 
```
---

## System Info:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 8.2.1
v8: 5.8.283.41
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
5.4.1
1.2.0
```

**Comment by Turbo87** [comment]
@musaffa thanks for reporting this. there was a change lately that caused Babel to run in parallel, but I don't see why those would be long-lived processes taking up so much memory. This looks like a bug that we need to investigate 🤔

**Comment by musaffa** [comment]
I did some investigation last night. If I lock `broccoli-babel-transpiler` to 5.6.2 for 5.x.x, the problem gets solved. I did a binary search for the commit which introduced the bug. The bug has been introduced in [this commit](https://github.com/babel/broccoli-babel-transpiler/commit/1d220b7a16054b8989004a1fe2e3e349d6a25ead).

**Comment by mikrostew** [comment]
I was the one who introduced these parallel worker processes for babel transpile in ember. This is definitely a problem that the processes are hanging around after the build is complete.

@musaffa I was able to repro this using your steps above:

```
$ ember new test-build --yarn
$ cd test-build
$ ember install ember-cli-mirage@0.3.4
$ ember s
```

On my box (12 cores) I see 12 processes still running after the build, one for ember-get-config, and 11 for ember-cli-mirage:

```
$ pgrep -af bin/node
26674 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-get-config/node_modules/broccoli-babel-transpiler/lib/worker.js
26708 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26713 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26719 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26725 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26731 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26737 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26744 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26751 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26758 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26764 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
26771 /home/mistewar/.nvm/versions/node/v8.9.0/bin/node /home/mistewar/repro/test-build/node_modules/ember-cli-mirage/node_modules/broccoli-babel-transpiler/lib/worker.js
```

I'm looking into this - likely solution is to spin down the worker processes after they have not been used in some period of time, like 30 seconds.

**Comment by musaffa** [comment]
Here's a difference between two debug outputs using [this lines](https://github.com/babel/broccoli-babel-transpiler/blob/1d220b7a16054b8989004a1fe2e3e349d6a25ead/lib/parallel-api.js#L96-L100):

### ember-cli-mirage v0.4.0:
Resolves with ember-cli-babel `v6.8.2` and broccoli-babel-transpiler `v6.1.2`.
Doesn't spawn any long lived node process.

```
transformString is NOT parallelizable

{ sourceMaps: false,
  plugins:
   [ [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ],
     [ [Object], [Object] ] ],
  moduleIds: true,
  resolveModuleSource:
   { [Function: moduleResolve]
     _parallelBabel:
      { requireFile: '/home/musaffa/projects/sandbox/yarn-test-build/node_modules/amd-name-resolver',
        useMethod: 'moduleResolve' } },
  highlightCode: false,
  babelrc: false,
  sourceFileName: 'ember-cli-mirage/assert.js',
  sourceMapTarget: 'ember-cli-mirage/assert.js',
  filename: 'ember-cli-mirage/assert.js' }
```

### ember-cli-mirage v0.3.4
Resolves with ember-cli-babel `v5.2.4` and broccoli-babel-transpiler `v5.7.2`.
Spawns long lived node processes.

```
transformString is parallelizable

{ modules: 'amdStrict',
  moduleIds: true,
  resolveModuleSource:
   { [Function: moduleResolve]
     _parallelBabel:
      { requireFile: '/home/musaffa/projects/sandbox/yarn-test-build/node_modules/ember-cli/node_modules/amd-name-resolver',
        useMethod: 'moduleResolve' } },
  blacklist: [ 'useStrict' ],
  nonStandard: false,
  highlightCode: false,
  sourceFileName: 'ember-cli-mirage/assert.js',
  sourceMapName: 'ember-cli-mirage/assert.js',
  filename: 'ember-cli-mirage/assert.js' }
```

**Comment by musaffa** [comment]
In fact, all the plugins which go through broccoli-babel-transpiler `v5.7.2` get parallelized while those which go through `v.6.1.2` do not. Interesting!

**Comment by musaffa** [comment]
@mikrostew I don't think that spinning down live worker processes after 30 seconds of inactivity is a good idea. As you can see from the first screenshot, the workers retain quite a lot of memory as live processes. Memory is a precious little resource unless one has tons of free memory. A worker should spin down immediately after it is finished and free up the memory for other processes/workers to use.

**Comment by musaffa** [comment]
From the debug output of broccoli-babel-transpiler `v6.1.2` we can see that a lot of plugins are passed along. Parallel API requires plugins to be either [undefined  or everyone of them](https://github.com/babel/broccoli-babel-transpiler/blob/1d220b7a16054b8989004a1fe2e3e349d6a25ead/lib/parallel-api.js#L28) to be [string](https://github.com/babel/broccoli-babel-transpiler/blob/1d220b7a16054b8989004a1fe2e3e349d6a25ead/lib/parallel-api.js#L24) or implement [_parallelBabel](https://github.com/babel/broccoli-babel-transpiler/blob/1d220b7a16054b8989004a1fe2e3e349d6a25ead/lib/parallel-api.js#L19) attribute. Every plugin which is passed along for transformation is an array `[ [Object], [Object] ]` which fails to pass the required Parallel API signatures.

The problem doesn't occur with broccoli-babel-transpiler `v6.1.2` because none of the transpilations is actually parallelized.

**Comment by k3n** [comment]
Ah, so this is why I have seventy (70!) node processes... is the solution to make sure everything is on `broccoli-babel-transpiler@^6.1.2`?

**Comment by locks** [comment]
This seems to have been addressed in the time being!
