### ISSUE TITLE
Clarifying behavior of addon config hook

### ISSUE THREAD

**Issue by jasonmit** [ember-cli/ember-cli#7391]
As of 2.15.0, accessing `app.options` is no longer possible within the `config` hook.  

`EmberApp` appears to be instantiated after all addon's `config` hooks are invoked.  This has likely always been true, but addons expected the config to be invoked multiple times.

For example, some addons may do something like:

```js
config() {
  if (!this.app) { return; /* ignore, app not ready */ }
  // build config based on `app.options`
}
```

The problem introduced in 2.15.0 results in the first run of `config` to be cached.  In this case above, it would mean the addon returns `undefined` and subsequent `config` runs are not merged into config.

I believe this was done intentionally but will break a number of addons.  Unsure what the solution should be other than perhaps invoking the addon `config` hooks after the EmberApp is instantiated and after the `included` hook - likely opens a new can of worms.

/cc @Turbo87

**Comment by Turbo87** [comment]
@krisselden @rwjblue ☝️

**Comment by jasonmit** [comment]
I'll close for now, perhaps a discussion we can have over Slack vs. polluting the issues.
