### ISSUE TITLE
Creating a shim for a global variable 'google' fails in 2.16.2

### ISSUE THREAD

**Issue by alexmasita** [ember-cli/ember-cli#7400]
I have a global 'google' that is imported by a google maps addon.  This addon did not create a shim for it as via inspection, I can see it uses it as a global.

I tried creating a shim within my app by running `ember generate vendor-shim google` and then tried importing the module at the top of my route file as follows: `import google from 'google';`

However, on transitioning to the route, I get the following error:

```
Uncaught Error: Could not find module `google` imported from `mpesa-on-zuru/pods/public/clients/profile/request/route`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:392)
    at Class.resolveOther (index.js:113)
    at Class.superWrapper [as resolveOther] (ember-utils.js:423)
    at Class.resolveRoute (resolver.js:323)
    at Class.resolve (resolver.js:161)
```
Could I be missing something?
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64

npm -version > 3.10.10
yarn -version > 0.27.5
```

**Comment by rwjblue** [comment]
Once you create the shim, you have to add an `app.import` to bring it into your build. Did you also do that?

**Comment by alexmasita** [comment]
Thanks for your reply.  No, I did not add `app.import` in ember-cli-build because the global was made available by an addon called `ember-g-map`.  I can access it anywhere in my app as `google` and can be able to create and use functions and objects such as `new google.maps.Size(30, 44)` anywhere in my app as a global.

Since the addon did not create the shim, I thought I would do it just for my application and make it available through the module pattern.  Do I still have to do the `app.import` even if it is already available in my app as a global?

**Comment by rwjblue** [comment]
If you want the shim to be made available so that you can use ES imports in your code, you have to include that shim in the build. Generating the shim file but _not_ app.import’ing will essentially result in no change to the build output...

**Comment by alexmasita** [comment]
Oh, I get it!!

Somehow, I was under the impression the 'shim' itself once generated is automatically included in the build and that the `app.import` would only be necessary to include the library that has the global (if not already present).  Okay will try this out soonest possible.  Many thanks.
