### ISSUE TITLE
Ember 2.16.2 - New module imports not being used after upgrade from 2.15.0

### ISSUE THREAD

**Issue by alexmasita** [ember-cli/ember-cli#7405]
Hi Team.  Sorry to revisit this.  I recently upgraded from 2.15.0 to 2.16.2, I tried to then generate a component via `ember g component status-manager` and got a template file that still uses the "old" globals imports:

```
import Ember from 'ember';

export default Ember.Component.extend({
});
```
Output from ember version --verbose && npm --version && yarn --version:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
```
`npm version: 3.10.10`
`yarn version: 0.27.5`

**Comment by rwjblue** [comment]
What is your ember-source version? That is what controls the actual component blueprint that is used...

**Comment by alexmasita** [comment]
My ember-source version was 2.15.0.  Have since upgraded to 2.16.0 and the problem is now resolved.  Perhaps this can be mentioned in the docs for future upgraders?  Many thanks.
