### ISSUE TITLE
No longer able to serve

### ISSUE THREAD

**Issue by machty** [ember-cli/ember-cli#7407]
```
$ ember sever
The specified command sever is invalid. For available options, see `ember help`.
```

the ember is broken. why cannot you fix the ember 1?!?!?! switching to raect now

**Comment by kiwiupover** [comment]
@machty what is raect?

**Comment by machty** [comment]
don't @ me

**Comment by machty** [comment]
here is screenshot
![image](https://user-images.githubusercontent.com/81818/32148287-85e756d8-bcc2-11e7-9969-3b20c5cd6013.png)
does it make sense?

**Comment by machty** [comment]
sorry, closing now, ran command in wrong foldre

**Comment by trabus** [comment]
![No LoNGer aBle tO sErVE](https://imgur.com/X5GNi6Y.jpg)
