### ISSUE TITLE
`ember-cli-version-checker` deprecation

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7408]
On the latest `master` if I run `ember -v` I get this deprecation warning. 

![screen shot 2017-10-30 at 1 03 36 pm](https://user-images.githubusercontent.com/1131196/32192936-ef2d04a2-bd72-11e7-8cb5-2d777d2795a1.png)

**Comment by rwjblue** [comment]
Awesome, thank you for reporting!  This was introduced by https://github.com/ember-cli/ember-cli/pull/7401 (and the PR did call out that this would be an issue).  We should create an issue in ember-cli-dependency-checker to migrate away (and cross linking it here).  

This should be considered a blocker for 2.18.0-beta.1.

**Comment by twokul** [comment]
I looked into it a little more. I don't think the warning comes from `dependency-checker` (although we do try to access `nodeModulePath` [here](https://github.com/quaertym/ember-cli-dependency-checker/blob/v2.0.1/lib/utils/read-node-modules-path.js#L5)). This warning [comes](https://github.com/ember-cli/ember-cli-version-checker/blob/v1.3.0/src/npm-dependency-version-checker.js#L11) from "old" version of `ember-cli-version-checker@1.3.0`.

I created a dummy app and ran `npm ls ember-cli-version-checker`:

```
➜  theapp git:(master) ✗ npm ls ember-cli-version-checker
theapp@0.0.0 /Users/anavasar/code/oss/cli/tmp/theapp
├─┬ ember-cli@2.17.0-beta.1 -> /Users/anavasar/code/oss/cli/ember-cli
│ └─┬ ember-cli-legacy-blueprints@0.1.5
│   └── ember-cli-version-checker@1.3.1
├─┬ ember-cli-babel@6.8.2
│ └── ember-cli-version-checker@2.1.0
├─┬ ember-cli-eslint@4.2.1
│ └── ember-cli-version-checker@2.1.0
├─┬ ember-cli-htmlbars-inline-precompile@1.0.2
│ └── ember-cli-version-checker@2.1.0
├─┬ ember-cli-shims@1.1.0
│ └── ember-cli-version-checker@1.3.1
├─┬ ember-resolver@4.5.0
│ └── ember-cli-version-checker@2.1.0
```

I think we need to make sure we're on the same version of `ember-cli-version-checker` across and then try to address this issue if it still exists.

**Comment by rwjblue** [comment]
Confirm, good sleuthing!

We need to update `ember-cli-legacy-blueprints` and `ember-cli-shims` to `ember-cli-version-checker@2`.

**Comment by villander** [comment]
@rwjblue  `ember-cli-shims` was deprecated. We can closed this issue?
