### ISSUE TITLE
Ember CLI warning for latest node LTS release 8.9.0

### ISSUE THREAD

**Issue by suspectdoubloon** [ember-cli/ember-cli#7410]
Ember CLI is throwing a Warning message on the most recent Node LTS version 8.9.0.
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
WARNING: Node v8.9.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
ember-cli: 2.12.1
http_parser: 2.7.0
node: 8.9.0
v8: 6.1.534.46
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.2.1
```

**Comment by rwjblue** [comment]
The latest version of ember-cli (2.16.2) does not issue a warning when using Node 8, please upgrade. 😄 

Also, the node version compat information can be found in https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md (and newer versions of ember-cli link to that document from the warning you are seeing).

I'm going to close this as already fixed. 🎉
