### ISSUE TITLE
Live reload of tests fails when watchman is installed on macOS

### ISSUE THREAD

**Issue by jkersten** [ember-cli/ember-cli#7411]
Tested with watchman version 4.9.0 on macOS Sierra and macOS High Sierra
Removing watchman helped solve the problem for now.

```
ember-cli: 2.13.3
http_parser: 2.7.0
node: 6.11.5
v8: 5.1.281.108
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
3.10.10
1.2.1
```

**Comment by pzuraq** [comment]
Having this issue now as well, did you find a way to resolve it other than by uninstalling watchman?

**Comment by csprocket777** [comment]
Why was this closed? I'm experiencing this same issue right now.

**Comment by jkersten** [comment]
Closed this issue, as I couldn't reproduce it with a clean Ember install. This still remans an issue with our existing code base however.

**Comment by skaterdav85** [comment]
anyone find out why? experiencing this myself.

**Comment by rwjblue** [comment]
Hmm, I believe the issue is likely with fsevents. Generally speaking a system restart will reset things to a known good state, but you can also sometimes recover via `watchman shutdown-server`.

**Comment by rwjblue** [comment]
I'm going to close this now, but please let me know if I've misunderstood something. I'm happy to reopen if I have... 😺

**Comment by snewcomer** [comment]
Just had this issue.  `watchman shutdown-server` seems to fix it!
