### ISSUE TITLE
[feature request] ability to list unused components

### ISSUE THREAD

**Issue by bekzod** [ember-cli/ember-cli#7418]
while building apps you create bunch of components and then some of them end up not used in app at all, would be awesome if ember-cli had command for listing all unreferenced/unused components

something like : 
`ember list component --unused`  and for destroying `ember destroy component --unused`

**Comment by rwjblue** [comment]
Seems like a great addon! I don’t think it belongs in ember-cli itself though...

**Comment by bekzod** [comment]
great will try to make one

**Comment by scottkidder** [comment]
@bek check out https://github.com/MaxCodeDE/ember-clean-project

**Comment by bekzod** [comment]
@scottkidder thanks nice one 👍
