### ISSUE TITLE
unable to use shorthand export with @ember packages

### ISSUE THREAD

**Issue by xcambar** [ember-cli/ember-cli#7420]
Here's a repo that illustrates the behaviour I'm experiencing: https://github.com/xcambar/ember_2_16_resolver_test

I'm creating a component which sole contents is:

```js
export { default } from "@ember/component";
```

The app build correctly but it fails in the browser on the following block:

```js
define('resolver-test/components/fail-me', ['exports'], function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  var default = exports.default = Ember.Component;
});
```

As you have probably already guessed, the `var default = ...` is the part that breaks, with the following message: `Uncaught SyntaxError: Unexpected token default`.
Are shorthands exports no longer welcome? Should we only use the explicit `import` then `export` syntax?

I also realise that may not be the appropriate repo, but please redirect me to the correct place as required.

Best,

**Comment by rwjblue** [comment]
Was fixed by https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/31, and should after a `yarn upgrade`.

**Comment by rwjblue** [comment]
Closing for now, but happy to reopen if that doesn't solve the issue...
