### ISSUE TITLE
Move `ember-try` dependency out of `ember-cli`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7421]
At the moment `ember-cli` has a dependency on `ember-try` which causes even apps to unnecessarily install `ember-try`. Having it as a dependency of `ember-cli` also couples the versions of both projects and a major bump in `ember-try` would technically need to result in a major bump of `ember-cli` too.

The simple solution to this problem is decoupling both projects and having addons have an explicit dependency on `ember-try` if they want to use it. This would allow them to upgrade `ember-try` independent from the `ember-cli` version that they use and remove the dependency for apps.

Since this is a breaking change we should aim for this to happen in 3.0 and add deprecations if you're using `ember-try` but not having it as an explicit dependency.

/cc @rwjblue @kategengler @kellyselden

**Comment by rwjblue** [comment]
Seems reasonable to me.  We should discuss in the next CLI team meeting...

**Comment by kategengler** [comment]
I'm 👍 on this. It makes it a pain to develop & test.

**Comment by kellyselden** [comment]
This is a good idea.

**Comment by Turbo87** [comment]
first step will probably be to get rid of https://github.com/ember-cli/ember-try/blob/master/index.js#L11-L16

after that we can issue a deprecation if the implicit `ember-try` is used, and then in 3.0 we can remove it :)

**Comment by rwjblue** [comment]
I submitted https://github.com/ember-cli/ember-try/pull/166 to remove the warning in ember-try (first step).

**Comment by Turbo87** [comment]
closing, as this has been implemented by now :)
