### ISSUE TITLE
Add `useYarn` flag to `config/ember-try.js` if `yarn.lock` exists

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7422]
`ember-try` lately introduced the [`useYarn` flag](https://github.com/ember-cli/ember-try#yarn) that should be used when testing addons that use [`yarn`](yarnpkg.com) to install their dependencies.

Similar to how we conditionally change the `.travis.yml` based on `yarn.lock` presence we should conditionally add the necessary flag to the `config/ember-try.js` file.

**Comment by rwjblue** [comment]
Fixed by #7430
