### ISSUE TITLE
Destroying a unit test for a component does not work [closed]

### ISSUE THREAD

**Issue by joshsearles** [ember-cli/ember-cli#7423]
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
os: linux x64
3.8.6
```

**Comment by rwjblue** [comment]
I think perhaps the issue description was submitted early or something, there is no command listed?

**Comment by joshsearles** [comment]
Solution: component test folder was not in /unit/components/<component-name>/ but rather without the components director (e.g. /unit/<component-name>/) 

Move along, nothing to see here :p
