### ISSUE TITLE
Backwards compatible change for module transpilation

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7433]
We should keep application/add-on files untranspiled as long as possible and transpile them as the very last step during packaging. This would help with implementing long anticipated features like tree-shaking and code splitting.

cc @rwjblue

**Comment by rwjblue** [comment]
Agreed, however I believe this needs an RFC (not because of public API changes, but to ensure the plan is well understood by addon authors and fully formed)...

**Comment by twokul** [comment]
https://github.com/ember-cli/rfcs/pull/110
