### ISSUE TITLE
Unable to run ember serve in newly created Ember project

### ISSUE THREAD

**Issue by kevgathuku** [ember-cli/ember-cli#7448]
Hello,
I'm just trying out Ember by following the Ember Getting Started guide.
After generating a new project and trying to run `ember s` to start the server, I get a blank terminal output, like it's trying to process something. This never exits and I have to cancel the command.
After I cancel the `ember s` command, I get this output:
```
Looks like you have a different program called watchman.
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:7020
cleaning up...
Cannot stop: not the current node.
Cannot stop: not the current node.
Cannot stop: not the current node.
Build Canceled
```
I have watchman installed via brew

Output of `watchman --version`:
`4.9.0`

Output of `which -a watchman`:
`/usr/local/bin/watchman`

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.16.2
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
5.5.1
1.3.2
```

**Comment by rwjblue** [comment]
Can you run with more logging (likely create a gist) via:

```
DEBUG=* ember s
```

**Comment by kevgathuku** [comment]
Thanks @rwjblue. That led me to find the solution.
The command was failing at this step:
```
ember-cli:watcher no watcher preference set, lets attempt watchman +21ms
ember-cli:watcher execSync("watchman version") +0ms
```
☝️ is where it hangs and leaves the command prompt unresponsive

Indeed, running `watchman version` on a separate terminal does also hang, returning no output and making the prompt unresponsive.

I have solved this by re-installing `watchman` and now `watchman version`  returns the correct output:
```
{
    "version": "4.9.0"
}
```
Thanks a lot for the help 😄

**Comment by rwjblue** [comment]
No problem, glad you got it sorted!
