### ISSUE TITLE
Add YUIDoc

### ISSUE THREAD

**Issue by ferdis** [ember-cli/ember-cli#746]
Myself, I was at a loss when I discovered that `ember-cli` did not provide any documentation generation tools.

EAK had support for YUIDoc by default, which operated as a grunt task.
I asked around on IRC for any suggestions but could not get anything conclusive other than to create my own implementation of consistent documentation generation alongside the broccoli pipeline.

Consequently, that's exactly what I've done: https://www.npmjs.org/package/broccoli-yuidoc

My creation is quite agnostic to what is going on with existing trees within the pipeline. 
It isn't perfect, not by any stretch of the imagination, but it gets the job done.

I really don't dare to touch ember-cli's internal broccoli plugin, as my knowledge of it is almost zlitch. Maybe someone could provide a conditional hook for it?

**Comment by sivakumar-kailasam** [comment]
@stefanpenner @rwjblue I've been using https://github.com/cibernox/ember-cli-yuidoc for a while in my projects and I see from emberaddons.com that it has 1,691 so far. Should ember-cli ship with the addon by default since documentation is a standard requirement in most apps.

//cc @cibernox

**Comment by cibernox** [comment]
In fact my addon is already used in ember.js itself, but if you decide to include it I'd like to polish it a bit more.
Particularly adding live-reload functionality and maybe run in a separate process, because it's a bit slow.
