### ISSUE TITLE
Add environment output when building

### ISSUE THREAD

**Issue by ondrejsevcik** [ember-cli/ember-cli#7480]
Hi, I would love to see what environment I'm building for when I run `ember b` or in general any script that will trigger run for me.

Something like this
```bash
user@bash>ember b
Building
Environment: development
.....
```

**Comment by Benjy1979** [comment]
I already do this doing console.log in the config/config.js

**Comment by ondrejsevcik** [comment]
Yeah, me to, but it would be nice to have it with every ember project I work on or contribute to.

**Comment by abhilashlr** [comment]
Made it in this PR #7874. If someone can have a look and suggest changes if any, would be welcome to do it.
