### ISSUE TITLE
Global error: ReferenceError: Can't find variable

### ISSUE THREAD

**Issue by sarbbottam** [ember-cli/ember-cli#7493]
on upgrading `ember-cli` from `2.12.3` to `2.15.0`, `ember test` errors out.

Similar issue #7022 

```
not ok 2 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/learning-enterprise-web.js, line 8
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/learning-enterprise-web.js, line 8\n' }
    ...
not ok 3 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: define at http://localhost:7357/assets/tests.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: define at http://localhost:7357/assets/tests.js, line 3\n' }
    ...
not ok 4 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: EmberENV at http://localhost:7357/7398/tests/index.html?hidepassed&_split=8&_partition=1, line 77
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: EmberENV at http://localhost:7357/7398/tests/index.html?hidepassed&_split=8&_partition=1, line 77\n' }
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.15.0
http_parser: 2.7.0
node: 8.9.0
v8: 6.1.534.46
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.1.0
```

**Comment by rwjblue** [comment]
What steps have to tried?  How can we reproduce the error?

**Comment by rwjblue** [comment]
The basic issue is that an error was thrown earlier during evaluation of `vendor.js` (possibly the `EmberENV` one, but also possibly earlier than that).

**Comment by sarbbottam** [comment]
```
npm install -g ember-cli@2.15.0
rm -rf node_modules dist tmp
npm install --save-dev ember-cli@2.15.0
npm install
ember init -- cherry picked the changes
```

```
ember test
```

**Comment by Turbo87** [comment]
@sarbbottam it looks like you updated **a lot** of dependencies. try updating them one by one and incrementally to narrow down where the issue might be. This is unlikely to be an actual bug in Ember CLI and most likely some breaking change in an addon breaking your tests.

**Comment by sarbbottam** [comment]
I was able to resolve the issue. The issue was one of the add-on was including `ember-cli-babel` as a `devDependency`, a newer version of the add-on has moved  `ember-cli-babel` to `dependency` .

**Comment by BryanCrotaz** [comment]
so is devDependency correct, or is dependency correct?

**Comment by sarbbottam** [comment]
`ember-cli-babel` needs to be part of `dependencies`

**Comment by Turbo87** [comment]
@BryanCrotaz it depends. if the addon has no JS files to transpile then it does not need `ember-cli-babel`. https://github.com/simplabs/ember-hbs-minifier is an example of such an addon, but in general most addons should have it as a `dependency`

**Comment by SanthoshRaju91** [comment]
I fixed this issue, but making `includePolyfill` to true in the app's ember-cli-build.js

`
'ember-cli-babel': {
   includePolyfill: true
}
`

Hope this helps
