### ISSUE TITLE
`setApplication()` using wrong `rootElement`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7497]
I've updated `ember-cli-qunit` to v4.1.1 and our tests suite runs fine. Once I replace the `setResolver()` code in `tests/test-helper.js` with `setApplication()` some of our tests started failing because `waitUntil()` was timing out. It turned out that we were waiting for a modal dialog to show that is rendered via `liquid-wormhole`, but instead of putting that dialog in `#ember-testing` it was put into the `body` element. Looking at `this.owner` confirmed that the application being given to `setApplication()` has `rootElement: 'body'` on it, instead of `rootElement: '#ember-testing'` as configured in `config/environment.js`.

**Comment by rwjblue** [comment]
How were you running the tests (`ember test` or `/tests`)? Any special build config in `ember-cli-build.js` (e.g. `storeConfigInMeta: false`)?

**Comment by rwjblue** [comment]
Also, what kind of test (acceptance, component integration, etc)?

**Comment by Turbo87** [comment]
> How were you running the tests (ember test or /tests)?

`ember test` using `ember-exam`, but also `ember test --server` without `ember-exam`

> Any special build config in `ember-cli-build.js`

There are quite a few custom things in there, yes

> e.g. `storeConfigInMeta: false`

Nope, just the standard setting for this one

> what kind of test (acceptance, component integration, etc)?

Acceptance seems to work fine, this is a component integration test in particular that is failing.

**Comment by Turbo87** [comment]
from Slack:

```js
import config from '../config/environment';

// ...snip...
let appConfig = Ember.merge({ autoboot: false }, config.APP);
setApplication(App.create(appConfig));
```

seems to resolve the problem

**Comment by Turbo87** [comment]
This was mostly resolved by https://github.com/ember-cli/ember-cli/pull/7507
