### ISSUE TITLE
[ENHANCEMENT] Ability to exclude folders from public folder in production build

### ISSUE THREAD

**Issue by Benjy1979** [ember-cli/ember-cli#7498]
Hi,

This is a feature request.

I have the need to omit certain files/folders (images in my case) from the public folder of the production build. Although you can omit them from fingerprinting etc, it ember-cli-build or environment.js doesn't allow to ignore folders etc to not appear in the production build.

The reason is because i have images that only apply to certain configurations and they are accumulating, it is a manual step to delete them, and if I don't the transfer to the remote server takes long and longer.

**Comment by Turbo87** [comment]
This would add an extra filter step to the build pipeline, which means slower builds for everyone. If you want to filter things out after the app is built you could use the `rm()` helper from https://github.com/stefanpenner/broccoli-stew inside your `ember-cli-builds.js` file to achieve this depending on the environment/configuration you build for.

**Comment by Benjy1979** [comment]
Thanks for your broccoli suggestion, I'll bear it in mind, but:

If everyone had this feature, and is not using it, how would the following code be slow:

if( excludedfolders.length >0) { filter directory; }
