### ISSUE TITLE
Should we add a lockfile do the default blueprint(s)?

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7503]
If https://github.com/ember-cli/ember-cli/pull/7482 lands, it might make sense to be complete to ship a lockfile as well. The added benefit is our release is "guaranteed" to work when it is first installed. The downside is the upkeep.

Thoughts?

**Comment by rwjblue** [comment]
IMHO, we shouldn’t do this. We want folks to get the latest deps at the time they create a new project, not whatever was latest X weeks ago when we last released...

**Comment by kellyselden** [comment]
That is a good point. On the other hand, we can help out the person that tries to generate a new project with an older global ember-cli, and is stuck with a regression somewhere. I think there are benefits on both sides.

**Comment by Turbo87** [comment]
I agree with @rwjblue. I don't think forcing users into a pregenerated set of dependencies will work well. This will likely result in lots of merge conflicts.
