### ISSUE TITLE
Obfuscate Javascript in production build

### ISSUE THREAD

**Issue by Benjy1979** [ember-cli/ember-cli#7504]
A nice option would be to properly obfuscate the javascript that is output in the production build, and optionally choose whether not to or not, as in fingerprinting option.
At the moment it's a manual process for us, if it was included in the "ember build" it smooth over the workflow.

**Comment by pichfl** [comment]
You can create a full or in-repo addon handing this for you. See the Ember-CLI documentation for addons here: https://ember-cli.com/extending/#developing-addons-and-blueprints

Pretty much like fingerprinting or minification you can use the postProcessTree method of the addon to run your mangling. https://ember-cli.com/api/classes/Addon.html#method_postprocessTree - Take a look at the  source of [ember-cli-uglify](https://github.com/ember-cli/ember-cli-uglify) for examples.

Personally, while fingerprinting and minification provide value to a build Ember app (by allowing for more predictable caching strategies and reducing file size), there is no added value in obfuscation. It can hurt performance and if someone wants to read your source, they can simply use the AST to transform it back to a rather quite readable source. 

Please read the [Guidelines](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#requesting-a-feature) for contributing to this project. They state quite clearly that this issue tracker should not be the target for feature requests.

**Comment by Benjy1979** [comment]
Obfuscation isn't supposed to be a catch all attempt to secure javascript. It's a certain level of thwarting against people picking up the plug-in you might have embedded with ease, and reusing it.

Like a lot of anti-hacker measures, it's just another deliberate obstacle in the way. I realised an add-on would do it, but so would an option in Ember-cli. 

Sorry about writing feature requests here.
