### ISSUE TITLE
Update `lib/broccoli/ember-addon.js` to forward `vendor` tree.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#7505]
By default ember-cli updates a number of the "app trees" to be from `tests/dummy` when developing an addon locally. We do this for app, styles, templates, public, and tests trees (handled inside `lib/broccoli/ember-addon.js`).

Unfortunately, we do not forward the apps vendor tree to tests/dummy/. This means that our addon's `treeForVendor` is called, but then subsequently clobbered by the "apps" vendor tree (which is _literally the same tree_, but untranspiled).

See https://github.com/emberjs/ember-test-helpers/pull/274 for an example of how addons can work around this issue for now.

**Comment by tylerturdenpants** [comment]
@rwjblue wouldn’t it be safe to assume that the fix used for `ember-let` in `treeForVendor` could be applied to this bug?
