### ISSUE TITLE
The config caching breaks the configPath option

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-cli#7535]
After https://github.com/ember-cli/ember-cli/pull/7270, the `EmberApp()` `configPath` option no longer works (since 2.16-beta.2).

This is because the cache is not invalidated when the path is changed on project init here: https://github.com/ember-cli/ember-cli/blob/daf7fc93af7eef82ea29b4e950b00c397a7e7c93/lib/broccoli/ember-app.js#L201.

/cc @krisselden who implemented the feature.

**Comment by rwjblue** [comment]
TBH, I doubt many of us knew the feature existed.  Can you share your usage scenario? 

It seems straightforward to fix (e.g. to purge the cache just after setting the update `configPath` function), mind sending in a PR?

**Comment by kanongil** [comment]
I setup my project with it long ago, as a way to support multiple variant configurations. I can probably rework it, if you want to deprecate it.

PR in #7538.

**Comment by locks** [comment]
Closed by #7535!
