### ISSUE TITLE
v3.0.0-beta.1 runs everything twice

### ISSUE THREAD

**Issue by daniel-de-wit** [ember-cli/ember-cli#7540]
I just updated my ember-cli by following the release setup guide:
`npm install -g ember-cli@3.0.0-beta.1`

Then created a new project, like so: `ember new testing`
Started it up immediatly: `cd testing` & `ember s`

The welcome page shows up, with every console output doubled:
<img width="1402" alt="screen shot 2018-01-04 at 11 22 50" src="https://user-images.githubusercontent.com/3015394/34559707-12b2d8c6-f143-11e7-83a9-e97f8d5132bf.png">

I'm using Google Chrome Version 63.0.3239.84 (Official Build) (64-bit) on osx 10.13.2 (17C88) "High Sierra"

*update: Ember-cli v2.18.0 does **not** have this problem.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.0.0-beta.1
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.3.2
```

**Comment by rwjblue** [comment]
This was a bug in Ember itself, it has been fixed, and will be included in the next beta release (likely next Monday).

**Comment by rwjblue** [comment]
Issue is described here: https://github.com/emberjs/ember.js/issues/16041

Fix is here: https://github.com/emberjs/ember.js/pull/16045

**Comment by daniel-de-wit** [comment]
@rwjblue I'm sorry, I didn't see the issue you are referring to. Thanks for you quick reply!
