### ISSUE TITLE
ESLint parses test/dummy/app/**/index.js as a script instead of a module

### ISSUE THREAD

**Issue by xomaczar** [ember-cli/ember-cli#7543]
Producing lint errors similar to 
```Parsing error: 'import' and 'export' may appear only with 'sourceType: module'```

---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.18.0
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: linux x64
5.5.1
1.3.2
```

**Comment by rwjblue** [comment]
This is being addressed in https://github.com/ember-cli/ember-cli/pull/7537.

**Comment by xomaczar** [comment]
Sorry, tried searching for a similar issue wit no luck. Was about to submit a PR - all good.

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-cli/ember-cli/pull/7537

**Comment by Panman8201** [comment]
Just FYI, I also got this error when creating `/addon-test-support/index.js` and adding `'addon-test-support/**'` to the `excludedFiles` array fixed it. Can open another issue, maybe even PR if needed, but figured I'd start here.
