### ISSUE TITLE
ember serve reloading on OSX

### ISSUE THREAD

**Issue by Martodox** [ember-cli/ember-cli#7551]
Hi there,
I would like to share an error that I encountered after upgrading from 2.14 to 2.18 (night not be related).

`ember s` command doesn't work anymore and prevents from working with an app entirely.
On top of that watchman starts consuming most of CPU which makes the whole system unstable.

See the screenshot below.

<img width="440" alt="screen shot 2018-01-12 at 11 37 16" src="https://user-images.githubusercontent.com/2963304/34871207-083ee1b4-f78d-11e7-8849-4e24dd4e889d.png">

Has anyone seen an issue like that before, is it even a bug with ember-cli itself of could it be an issue with the dependencies?

```
ember-cli: 2.18.0
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.6.0
1.3.2
```

**Comment by nightire** [comment]
@Martodox Yes, I encountered same thing recently. But I have two macOS device (iMac & MBP), this only appears in one of them, and I don't know the reason behind. The way I resolve this is to uninstall watchman completely, and it works well for now.

BTW, every time watchman has a update, I will reinstall it to see if things going better, but unfortunately no.

**Comment by Martodox** [comment]
I ended up installing latest node LTS, removing dist, tmp and node modules from my project, rebooted my mac. After that -> npm install and guess what... it started working. Something strange is happening under the hood and it is not being reported in the cli

**Comment by Turbo87** [comment]
@Martodox watchman is known to have some issues on MacOS High Sierra, though unfortunately running without it also creates its own set of issues. there is unfortunately not much we can do here other than waiting for watchman or Apple to fix these issues.
