### ISSUE TITLE
Module Unification - Broccoli Todo List

### ISSUE THREAD

**Issue by mansona** [ember-cli/ember-cli#7568]
This Issue is expected to keep track of tasks that need to be done as part of the module unification effort. If you have any questions please reach out to me in #st-module-unification on the Ember Community Slack (username @real_ate)

# Blockers
- [ ] Get initial implementation merged so we can enable it behind a feature flag (See https://github.com/ember-cli/ember-cli/pull/7490) 
- [ ] Filter `<type name>-test.js` files from the output dist so we don't ship them to production

**Comment by NullVoxPopuli** [comment]
second item can be checked off: https://github.com/ember-cli/ember-cli/pull/8314 -- trying to verify atm, but have babel6/7 issues :(

**Comment by Turbo87** [comment]
closing due to https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html
