### ISSUE TITLE
not opening localhost:4200 error 404

### ISSUE THREAD

**Issue by balu9177** [ember-cli/ember-cli#7581]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
[Replace this line with the output.]
```

**Comment by rwjblue** [comment]
Closing, seems like the issue was opened in error?
