### ISSUE TITLE
generating a route with initial slash causes an error

### ISSUE THREAD

**Issue by shouldergiant** [ember-cli/ember-cli#7603]
Hey!

* `ember new my-app && cd my-app`
* `ember g route /my-route`
* `ember s`

Then I went to localhost://4200 and found this error in the console: 

`"Assertion Failed: fullName must be a proper full name"`

I've done this a couple times now and have to clean up. It would be nice to detect this and help others from having the same issue. 

---

Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 2.18.2
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
-bash: yarn: command not found
```

**Comment by kellyselden** [comment]
Welcome! What a nice and detailed first bug report to ember-cli. It's almost like I was sitting right next to you when you wrote it... haha

**Comment by locks** [comment]
Linked PR has been merged!
