### ISSUE TITLE
`addon` blueprint enables `ember/new-module-imports` ESLint rule for `app` folder

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7609]
Using the `@ember/...` imports in the `app` folder of an `addon` can lead to broken apps if the host app is not using `ember-cli-babel@6.6+`. We should disable the rule for this folder when generating the `.eslintrc.js` file for the `addon` blueprint.

**Comment by rwjblue** [comment]
👍  - seems good (though folks should probably continue to focus on upgrading to babel@6...)

**Comment by locks** [comment]
⛵
