### ISSUE TITLE
A better doc to ember-cli hooks/API

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#7612]
how does each `ember-cli hooks` work, more examples about each, besides the `public API ember-cli` provides us with to work on addons, for example: `(this.project, this.parent, this.import)` we want to know the whole API

Its very important to drive the community to contribute and share solutions and improve people's lives, is part of the philosophy (developer ergonomics) of Ember, maker our ecosystem more ergonomic. It is very difficult to build an addon that requires knowledge of ember-cli

I think this would help both increase open source contribution and instigate people to contribute to ember-cli as well

> I guess part of the problem is that broccoli itself isn't documented very well

**Comment by villander** [comment]
@Turbo87

**Comment by Turbo87** [comment]
@villander I totally agree and you're very welcome to contribute to the existing documentation :)

**Comment by locks** [comment]
For anyone that happens upon this issue, we are always looking for help with writing and improving documentation!
