### ISSUE TITLE
Investigate skipped tests and general test flakiness

### ISSUE THREAD

**Issue by thoov** [ember-cli/ember-cli#7623]
Below are the tests that currently have a `.skip`

- [ ] tests/acceptance/brocfile-smoke-test-slow.js
- [ ] tests/acceptance/pods-destroy-test.js
- [ ] tests/acceptance/pods-generate-test.js
- [ ] tests/acceptance/smoke-test-slow.js
- [ ] tests/unit/cli/cli-test.js
- [ ] tests/unit/commands/show-asset-sizes-test.js

**Comment by locks** [comment]
Tracked in https://github.com/ember-cli/ember-cli/issues/7981.
