### ISSUE TITLE
Ember 3.0 Addon Blueprint does not pass linting

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#7624]
When I updated my addon to Ember 3.0 via `ember init` today, I was met with the following error:

```
tests/dummy/config/targets.js
  1:1  error  'const' declarations in non-strict mode are not supported yet on Node 4.5.0  node/no-unsupported-features
  7:1  error  'const' declarations in non-strict mode are not supported yet on Node 4.5.0  node/no-unsupported-features
  8:1  error  'const' declarations in non-strict mode are not supported yet on Node 4.5.0  node/no-unsupported-features
```

My `targets.js` file is the default generated by the new blueprint, and I have not customized any linting rules either.

**Comment by Turbo87** [comment]
@elwayman02 thanks for reporting. I guess we need to backport https://github.com/ember-cli/ember-cli/pull/7563 to the `release` branch 🤔

**Comment by locks** [comment]
Addressed in relevant PR at the time!
