### ISSUE TITLE
Deprecate ember-cli-babel 5

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7642]
The new work we are doing to support packaging and tree-shaking won't work with babel 5. We are also probably going to remove babel 5 support in a minor version of ember-cli, as we determined we don't have a babel version support matrix as part of our semver policy.

**Comment by Dhaulagiri** [comment]
Clarifying for interested spectators like myself, this would mean any addons using Babel 5 would no longer work in the consuming app once this support is removed?

**Comment by Turbo87** [comment]
Correct, but in reality updating an addon to Babel 6 is actually not that hard since most of the hard work is abstracted away in `ember-cli-babel`.

**Comment by Dhaulagiri** [comment]
definitey. I’ve been able to update most of our addons at this point so now it’s a matter of the less maintained ones where getting any PRs merged and released is hard to do 🌵

**Comment by kellyselden** [comment]
Completed on master.
