### ISSUE TITLE
Unknown blueprint: resource for ember-cli 3.0.0

### ISSUE THREAD

**Issue by belgoros** [ember-cli/ember-cli#7644]
When running
```
ember generate resource books title:string price:number author:belongs-to publisher:belongs-to
```
I got the following error:
```
Unknown blueprint: resource
```
It seems like `resource` does not make part of blueprints anymore.
Nevertheless, it is still present on the DOCs [page](https://ember-cli.com/extending/#generators-and-blueprints) listing available blueprints:

![image](https://user-images.githubusercontent.com/83579/36604867-3e7ca3f8-18bf-11e8-9e7f-bb90996b60a1.png)

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.0.0
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.6.0
1.3.2
```

**Comment by alvinkatojr** [comment]
This issue was closed without further clarification of the next steps to take. The documentation itself on ember-cli is not clear on how to create a resource blueprint i.e in terms of file structure, configuration etc. 
@belgoros how did you resolve this problem? 
@kellyselden many people have run into this same issue. It would be nice if you'd outline some quick steps/ideas on how to get this resolved. Thanks!

**Comment by belgoros** [comment]
@alvinkatojr I think the documentation has been updated, `ember generate resource` generator is no more available.

**Comment by Wicazu** [comment]
Hi... My question is... Why? That generator was useful for me. Now, do we have to use the generators individually like model, route and template ?

**Comment by Dhevendhirancs** [comment]
Hello @belgoros , I have the same question like @Wicazu. I need this clarity urgently. could you please suggest, if you know

**Comment by Wicazu** [comment]
@belgoros Ooohh ok I understand many many thanks friend..!

**Comment by rreckonerr** [comment]
@belgoros Thank you! Seems like I'm currently following the same tutorial as you were.

**Comment by chmich** [comment]
thank you @belgoros
