### ISSUE TITLE
Ember CLI SSD vs RAM Disk Test

### ISSUE THREAD

**Issue by tomaszs** [ember-cli/ember-cli#7645]
My project builds slow on SSD. It takes 27s after i add a space to a file. So i have tested what happens when whole project will be moved to RAM DISK (used ImDisk). 

Here are results:

SSD: Build successful - 27085ms.
SSD: Build successful - 11019ms.

= 59% faster rebuild time

So if you have spare RAM it's some kind of a solution to speed up build time.

Pros:

+ faster build and rebuild time

Cons:

+ lossing power = loosing changes

**Comment by Turbo87** [comment]
thanks for the feedback! we are currently working on integrating Broccoli 2, which will soon use the system temp folder instead of project-local `tmp`. Since the system temp on a lot of platforms is a ramdisk this will hopefully soon be the default :)

**Comment by tomaszs** [comment]
Cool :)

**Comment by stefanpenner** [comment]
https://www.npmjs.com/package/ember-cli-ramdisk may be able to work.

**Comment by tomaszs** [comment]
Nice, i will try to use ramdisk only for tmp, on Windows. It should also give benefits without risk of loosing changes

**Comment by tomaszs** [comment]
I did it with imdrive and mklink. Results are:

First build - 38s
Second build - 32s
Third build -15s

So its nice.

**Comment by tomaszs** [comment]
For comparision, before i did it:

Ember s - 44s
Rebuild after file change - 39s
Second rebuild - 27s
Third - 22s

So its 32% gain

**Comment by kellyselden** [comment]
Wow thanks for that link! We should get that advertised. cc @jessica-jordan @jenweber

**Comment by yaxinr** [comment]
just use wsl 2
it gives me x10 faster speed
https://stackoverflow.com/a/66481419/1359764
