### ISSUE TITLE
Addon compilation order

### ISSUE THREAD

**Issue by mikemunsie** [ember-cli/ember-cli#7653]
Is there a way to tell my addon that I should compileStyles first and then compileAddon last?

I have a scenario where when my sass is compiled, it creates a few JS files that need to be included as part of the addon tree. I can't seem to figure out how to add those files back into the tree because I think at the point my sass is compiled, the JS files have already compiled and you aren't able to make changes.

I should also mention every tree hook is ran before sass is compiled, so I am not able to use any existing hooks to do what I need.

**Comment by Turbo87** [comment]
@mikemunsie no, the order in which the trees are compiled by broccoli is not defined. the new `packager` hook might allow you to achieve what you want though.
