### ISSUE TITLE
Test's dummy app doesn't reexport /src in Module Unification adons

### ISSUE THREAD

**Issue by cibernox** [ember-cli/ember-cli#7666]
The logic in #7490 has a hole.

When you generate an addon using the module unification layout but with the dummy app inside the test folder in "classic" mode, `isModuleUnification` check thinks the app is un MU layout, and doesn't reexport the contents of the addon's `/src` into `/app` automatically.

Reproduction: https://github.com/cibernox/my-mu-addon

**Comment by gossi** [comment]
I think a more applicable approach for testing is what @mansona has done in https://github.com/mansona/testing-mu where you have in-repo apps that will serve as test apps. I think the blueprint for a mu addon should contain two apps by default: one classic, one mu-app to test the addon in both locations.

**Comment by ppcano** [comment]
https://github.com/ember-cli/ember-cli/pull/8431 should fix this issue

**Comment by Turbo87** [comment]
closing due to https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html
