### ISSUE TITLE
In an addon, a template in /app gets converted to export default `Ember.HTMLBars.template`

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-cli/ember-cli#7677]
When exporting a template in /app for public consumption the original file starts out as 

```
<div class="ember-admin">
  <h2>Admin</h2>
  {{#each filteredModels as |name|}}
    {{link-to name 'model-records' name}}
  {{/each}}
  {{outlet}}
</div>
```

However, when using `ember s` the file get converted to 
`export default Ember.HTMLBars.template(....`

This is ok, it still works, but it now fails during linting.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.0.0
http_parser: 2.7.0
node: 9.4.0
v8: 6.2.414.46-node.17
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.6.0
1.5.1
```

**Comment by locks** [comment]
Is this still relevant?

**Comment by rwjblue** [comment]
No
