### ISSUE TITLE
Open editor on clicking build error message in the browser

### ISSUE THREAD

**Issue by astronomersiva** [ember-cli/ember-cli#7687]
When there is a build error in an Ember app, it will be helpful to open the editor on clicking the error message. This will be helpful for new developers and improve their overall experience with Ember.

This is already available in React through create-react-app and the implementation is rather trivial. I can take this up if you feel this could be helpful to the Ember ecosystem.

**Comment by rwjblue** [comment]
Definitely open to the idea. I assume you mean clicking on the error in the browser (because you can already configure your terminal to do this AFAICT)...

**Comment by astronomersiva** [comment]
Yes. I am giving a shot at this :)

**Comment by Turbo87** [comment]
@astronomersiva did you find a solution to this?

**Comment by astronomersiva** [comment]
@Turbo87 Sorry, I haven't gotten around to doing this yet.

**Comment by astronomersiva** [comment]
@rwjblue , @Turbo87 I have managed to get this working...I am facing a few difficulties in determining the file to open though. The `broccoliPayload` object that contains the stack is modifying the file name..For example, for the application.hbs file in an app `open-editor`, the file path provided by this object is `openEditor/templates/application.hbs`. This has to be normalised to `./app/templates/application.hbs`.

This gets complicated when you factor in in-repo engines. For example, when you have an in-repo engine `hyphenated-name` with a template `car`, the file name returned in this object is `hyphenated-name/templates/car.hbs`. Now this has to be normalised to `./lib/hyphenated-name/templates/car.hbs`.

Is there a way to determine whether the file is a part of the application itself or an in-repo engine?

**Comment by Turbo87** [comment]
I don't think that info is available anymore at that point :-/

**Comment by astronomersiva** [comment]
I have created a [PR](https://github.com/ember-cli/broccoli-middleware/pull/47) upstream in broccoli-middleware. Please have a look.
