### ISSUE TITLE
sourcemap not working

### ISSUE THREAD

**Issue by premchandars** [ember-cli/ember-cli#7697]
Team,

sourcemaps: {
        enabled: false,
        extensions: ['js']
}
I have added this option in ENV.OPTIONS still source .map file is generating for development.
Which is the right place to add this option.
Also map for css files is also getting generated.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.12.3
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
3.10.10
1.3.2
```

**Comment by rwjblue** [comment]
Can you push up a demo project that reproduces the error?

**Comment by premchandars** [comment]
Thanks For the reply.
I tried it to reproduce in simple demo app . Its working as expected. 
May be due to some other add-on ,So closing the issue
