### ISSUE TITLE
Prevent generation of .js.js files

### ISSUE THREAD

**Issue by MrChriZ** [ember-cli/ember-cli#7699]
Small feature request.

If I type 
ember g controller post.js

Ember creates a post.js.js and a test post.js.js

Would it perhaps be useful instead to either strip the .js or display an error message or something similar?

**Comment by Turbo87** [comment]
sounds like a reasonable suggestion. do you have time to work on a pull request for this?

**Comment by abhilashlr** [comment]
@Turbo87 I have a solution for this, but I'm not sure if that is the perfect one thoug. Will share a PR, please let me know if that is fine.

**Comment by romgere** [comment]
@Turbo87  is this have to be done in ember-source blueprint ? And it's concern only controller or others  blueprint (route, helper, component, ...) ?

**Comment by Turbo87** [comment]
@romgere yes, I think doing it in the blueprints in the `ember-source` repo is the best way to do it. the issue only talks about controllers, but doing the same for routes, components, etc. is a good idea. probably also for templates and `.hbs` 🤔

**Comment by romgere** [comment]
OK I'am going to try to do it...
Just one more question about pod. For commands  with "--prod" option like `ember g component foo.js --pod` what's the expected behavior :thinking:  ? `app/components/foo/component.js` or `app/components/foo.js/component.js` file ?

**Comment by Turbo87** [comment]
> For commands with "--prod" option like `ember g component foo.js --pod` what's the expected behavior 🤔 ? 

`app/components/foo/component.js` AFAIK

**Comment by Gaurav0** [comment]
Is this fixed?

**Comment by romgere** [comment]
@Gaurav0 
![image](https://user-images.githubusercontent.com/13900970/66254133-867ae600-e772-11e9-828d-7abce9455dc1.png)
I think yes. This issue can be closed now.
