### ISSUE TITLE
Add yarn to upgrade instructions on Release notes

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#7704]
Origin: https://github.com/ember-cli/ember-cli.github.io/issues/140

> The release notes at https://github.com/ember-cli/ember-cli/releases specify how to upgrade using npm. Shouldn't this be changed for yarn now or at least instructions for yarn added?

**Comment by gossi** [comment]
Psst. Merge `ember-cli-update` into `ember-cli` and write the release notes according to `ember update` making it package manager independent.

**Comment by rwjblue** [comment]
FWIW, `ember-cli-update` is definitely the planned path forward. The main blockers are documentation AFAICT...

**Comment by billybonks** [comment]
how do we generate these release notes? if we do.

**Comment by Turbo87** [comment]
@billybonks except for the changelog we just copy-paste from previous releases

**Comment by locks** [comment]
Not as relevant currently.
