### ISSUE TITLE
Deploying to azure won't properly read rootURL !!

### ISSUE THREAD

**Issue by viganella** [ember-cli/ember-cli#7706]
Hello Guys
So I have this ember app that will support versioning.
I have in the  rootURL: '/runtime/v1/' and locationType: 'auto' . When i run locally everything works fine.
Then I do ember build. Grab the build from dist folder and paste it to my Azure using KUDU.
However that is not working. It give me error saying: 
Uncaught SyntaxError: Unexpected token <<DIR NAME>.js:1 Uncaught SyntaxError: Unexpected token < on vendore.js:1 and <DIR NAME>.js:1

IMPORTANT: when rooturl is set to: **rootURL: '/'** works fine.

**Comment by Turbo87** [comment]
That sounds a lot like you're server is serving HTML instead of JavaScript code. I don't think this is an issue with Ember CLI itself. Please report back if you think that this is indeed an Ember CLI issue.
