### ISSUE TITLE
Module-unification component blueprint not working

### ISSUE THREAD

**Issue by xg-wang** [ember-cli/ember-cli#7726]
reproduce:
```
npm i -g github:ember-cli/ember-cli
MODULE_UNIFICATION=true ember new foo
cd foo
ember g component foo-bar
```
error would be:
> Cannot read property 'isModuleUnification' of undefined

This is due to the component blueprint in https://github.com/emberjs/ember.js/pull/16043 depends on `this.project` which doesn't exists [link](https://github.com/emberjs/ember.js/pull/16043/files?diff=split#diff-017cbe40fcdfe1804dd384796ec8f809R28).

The tests are correct, but they passed because the ember-cli was pinned to an [earlier version](https://github.com/emberjs/ember.js/blob/400ec6ee69265ce45538e07ace9523926569f805/package.json#L110) and some code wasn't covered.

cc @GavinJoyce 

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.0-beta.1
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.8.0
1.5.1
```

**Comment by GavinJoyce** [comment]
Here's what I think is happening.

I made this change recently: https://github.com/ember-cli/ember-cli/commit/7b6be06caaf52e08e9d5d46d5ac79cda482fd1c7. I extracted out a variable as the logic was getting complicated, this had the side effect of calling [`blueprint.supportsAddon()`](https://github.com/ember-cli/ember-cli/blob/e23c2ef653cffa4a95db8dad78214cef20222b79/lib/models/blueprint.js#L775) in more cases that before. It turns out the `blueprint.supportsAddon()` calls `this.files()` which must evaluate something in the blueprint without the `this.project` context.

I'll work on a fix now

**Comment by GavinJoyce** [comment]
@xg-wang I believe that this will fix it: https://github.com/ember-cli/ember-cli/pull/7731

**Comment by xg-wang** [comment]
BTW The first time Gavin's commit in [ember.js] introduced component blueprint wouldn't work, it will still generate classic structure, this has something to do with the `[extends](https://github.com/emberjs/ember.js/blob/master/broccoli/transforms/inject-babel-helpers.js#L7)` change introduced later - which will override the base object's method so the component blueprint's `this.files()` will be correctly called.

**Comment by GavinJoyce** [comment]
@xg-wang I don't fully understand your comment above. Both the `ember g component` tests and manually running the command works for me. Perhaps you could expand on which chases it isn't working?

**Comment by xg-wang** [comment]
I tried this:
```
npm i -g ember-cli@3.1.0-beta.1
MODULE_UNIFICATION=true ember new my-app
cd my-app
ember g component foo-bar
```

output:
```
installing component
  create app/components/foo-bar.js
  create app/templates/components/foo-bar.hbs
installing component-test
  create tests/integration/components/foo-bar-test.js
```

in package.json, `"ember-source": "http://builds.emberjs.com/canary.tgz"`

**Comment by GavinJoyce** [comment]
We're currently using a feature flag which is removed in betas: https://github.com/ember-cli/ember-cli/blob/e23c2ef653cffa4a95db8dad78214cef20222b79/lib/models/project.js#L198

You need to run against canary

**Comment by xg-wang** [comment]
Actually it's same, when generating component it's by checking the `src` folder to determine isModuleUnification. You can debug to `this.files()` and will find the wrong function was called.

```
 ❯ MODULE_UNIFICATION=true ember g component foo-bar2                        [08:28:13]
installing component
  create app/components/foo-bar2.js
  create app/templates/components/foo-bar2.hbs
installing component-test
  create tests/integration/components/foo-bar2-test.js
```

**Comment by GavinJoyce** [comment]
The `MODULE_UNIFICATION=true` variable is only for when creating an addon or an app, not for generator blueprints.
