### ISSUE TITLE
ModuleUnification: `src` by default becoming build/shipped is breaking

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#7734]
```js
<addon-foo>/src
```

Now has meaning, unfortunately this as implemented is a breaking change. And may result in unexpected assets being shipped to production. It is not uncommon for `src` to be raw typescript source.

Short Term:

* we make this disabled by default
* add-ons supporting module unification will need to opt-in. Either via `package.json` addon-config entry, or by returning true/false from `isModuleUnification()  { return false;}`

**Comment by kategengler** [comment]
This file is a cleaned up list with more helpful info:
https://gist.github.com/kategengler/5403e1013a9b372cd18a2320d05fc9e8#file-addons-with-toplevel-src-dir-with-urls-csv

There are 33 out of over 3300 (all the addons that have valid repo urls).

**Comment by dfreeman** [comment]
I think there may be some false positives in that list — `ember-botanist` definitely doesn't have a `src` directory (though it depends on a non-addon package that does...)

**Comment by billybonks** [comment]
pretty unique but this doesn't actually use cli https://github.com/kellyselden/ember-cli-update

**Comment by rwjblue** [comment]
This was addressed by https://github.com/ember-cli/ember-cli/pull/7735
