### ISSUE TITLE
eslint override problem

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7743]
https://github.com/kellyselden/eslint-override-bug

https://github.com/kellyselden/eslint-override-bug/blob/master/app/test.js
https://github.com/kellyselden/eslint-override-bug/blob/master/.eslintrc.js#L49-L52

`npm run lint:js` passes but `ember test` fails, meaning the override isn't being handled properly. The problem may lie in ember-cli-eslint, not sure.

**Comment by locks** [comment]
Is this still an issue @kellyselden?

**Comment by kellyselden** [comment]
Not sure. Closing for now.
