### ISSUE TITLE
`ember-exam` no longer works as expected

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7745]
With the update to v3.1.0 `ember-exam` stopped working correctly. We have it configured to split our test suite into three partitions and run them in parallel. After the update only Partition 1 is running, and the rest of the test suite does not run at all, while testem still finishes with exit code 0.

My guess is that https://github.com/ember-cli/ember-cli/pull/7728 is the cause of that issue 🤔 

/cc @stefanpenner @arthirm @rwjblue @trentmwillis

**Comment by Turbo87** [comment]
It appears that this also landed in v3.0.3 without any beta testing period...

**Comment by stefanpenner** [comment]
I have confirmed this to be the issue. It is also affecting our app. (the lack of test failures let this sneak through...)

**Comment by Turbo87** [comment]
I can confirm that v3.1.1 (and v3.0.4) fix the issue for us. Closing this as resolved (by https://github.com/ember-cli/ember-cli/pull/7746) 🎉
