### ISSUE TITLE
Does processor change increase Ember CLI build?

### ISSUE THREAD

**Issue by tomaszs** [ember-cli/ember-cli#7754]
Ember CLI build (ember s) in an old version takes aprox 34 s on a SSD disk with 8GB RAM.
Can anyone share if changing processor to more powerful decrease build time substantially?

**Comment by stefanpenner** [comment]
If you are having performance issues, I would recommend skimming the guide: https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md

Now that may not address your issue, but it should help inform where the time is being spent. Given that, It should be clear if you are CPU or disk bound. At which point a recommendation could be provided. It may also reveal some good areas of improvement.

**Comment by tomaszs** [comment]
I have tried it but run into various trouble. I have a good SSD, just to know if someone seen better speed after processor change.

**Comment by Turbo87** [comment]
if your bottleneck is not disk speed, then it is likely your CPU, so yeah, maybe a faster CPU will improve things, but there are likely other things to try first which might be a bit cheaper.

**Comment by tomaszs** [comment]
I will have a better processor tomorrow, so we will see

**Comment by tomaszs** [comment]
What other things do you mean?

**Comment by Turbo87** [comment]
see https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md

**Comment by tomaszs** [comment]
Thanks. I have tried actually stuff from this list. Half is no gain, half is not working :(

**Comment by tomaszs** [comment]
After upgrading a processor time dropped. Project is bigger, so it is hard to compare, but:

Ember s - 44s
Rebuild after file change - 39s
Second rebuild - 27s
Third - 22s

So it's better :)

**Comment by tomaszs** [comment]
I have concluded my reasearch on Ember CLI ember s speedup here: https://emberjs-developer.quora.com/How-to-make-Ember-js-CLI-ember-s-32-times-faster

**Comment by efx** [comment]
Updated perf guide link for future travelers: https://github.com/ember-cli/ember-cli/blob/master/docs/perf-guide.md
