### ISSUE TITLE
MinifyCSS on 3.1.1 not working

### ISSUE THREAD

**Issue by catz** [ember-cli/ember-cli#7755]
Hello

Tried to build ember new app with ember cli 3.1.1 and minification for css is not working.
3.0.2 is working fine.

No additional packages used.

```
ember-cli: 3.1.1
node: 6.9.5
os: darwin x64
```

**Comment by twokul** [comment]
closed via https://github.com/ember-cli/ember-cli/releases/tag/v3.1.2
