### ISSUE TITLE
Obligatory ember-ajax in add-on generator templates/blueprints?

### ISSUE THREAD

**Issue by PoslinskiNet** [ember-cli/ember-cli#7760]
Not sure what is the background of such a decision, but do we really need `ember-ajax` as a "starter" dependency for a new add-on setup?

Which part of it are we using for instance for UI components? If it's redundant, then I can help with removal of it  👍

**Comment by PoslinskiNet** [comment]
Any thoughts on that @rwjblue @Turbo87 😈 ?

**Comment by initram** [comment]
Should `ember-ajax` only be removed from addons  or also from the normal ember app blueprint. I do not see it mentioned in any guides. It also relies on jQuery, so if we want people to have an easier transition away from jQuery, then it may be better not to include addons that rely on jQuery in the basic blueprint.

What are your thoughts on this? @Turbo87 @rwjblue

**Comment by Turbo87** [comment]
removing it from the `addon` blueprint seems uncontroversial to me, the `app` part might need a bit more discussion and possibly an RFC
