### ISSUE TITLE
Test error "Cannot read property 'hasRegistration' of undefined"

### ISSUE THREAD

**Issue by kaermorchen** [ember-cli/ember-cli#7763]
How to detect:
```
ember new test-app
cd test-app\
ember s
```
We have green tests
![2018-04-16_10-11-49](https://user-images.githubusercontent.com/11972062/38794665-9d3f9324-415e-11e8-81ec-ae01fcf7804f.png)
```
ember g helper foo-bar
```

We have an error - "Uncaught TypeError: Cannot read property 'hasRegistration' of undefined"
![2018-04-16_10-13-08](https://user-images.githubusercontent.com/11972062/38794754-c8ebba52-415e-11e8-9b9c-b519d5149b14.png)

// test-app/tests/integration/helpers/foo-bar-test.js
```
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import hbs from 'htmlbars-inline-precompile';

module('Integration | Helper | foo-bar', function(hooks) {
  setupRenderingTest(hooks);

  // Replace this with your real tests.
  test('it renders', async function(assert) {
    this.set('inputValue', '1234');

    await render(hbs`{{foo-bar inputValue}}`);

    assert.equal(this.element.textContent.trim(), '1234');
  });
});
```

Output from `ember version --verbose && npm --version`:
```
ember-cli: 3.1.2
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: win32 x64
5.6.0
```

**Comment by chilicoder** [comment]
I have the same issue

**Comment by sivakumar-kailasam** [comment]
Reported in https://github.com/emberjs/ember-inspector/issues/818

**Comment by Turbo87** [comment]
closing in favor of https://github.com/emberjs/ember-inspector/issues/818
