### ISSUE TITLE
[Feature request] in-memory file server & build tool

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli#7765]
As we well know, ember-cli has wery low build speed & performance on windows machines.

Yes, this behaviour can be improved by [ssd + no search + admin rights for symlinks], 
but, this case not useful for enterprise.

* You can't get Admin rights
* You can't disable search
* You can't updade HDD to SSD

But, you always have alot of ram [8-16gb]
And ember-cli .tmp path in middle project - takes about 200-300mb

What if ember-cli will work just like an [webpack](https://github.com/webpack/docs/issues/32) with in-memory-file server?

broccoli can create in-memory-fs and manage files inside it, and ember-cli can serve files from it.

All times ember - is best tool for enterprise UI, but, it worst tool for secured Windows(R) enterprise.

**Comment by stefanpenner** [comment]
Unfortunately a pure in-memory solution isn't super viable for many users, but maybe as an opt-in? I would encourage you to experiment with this and report back.

For a general purpose solution, which would help all users, pure in memory is problematic as node has a very low JS heap memory limit. (1.7gb or something)

Given that in general, the IO performance issues are related to testing if files have changed, and creating many symlinks (or similar on windows) to emulate a layered FS. There are two very nice directions we aim to take (and you have time, we would love your time).

### Skip IO if we know we can:

"side affect free" broccoli plugins, which provides a great optimization. Skipping massive amounts of disk IO, during rebuild. https://github.com/broccolijs/broccoli-plugin/pull/23

This works by adding a strong rule, if a broccoli-plugin inputs haven't changed, safely assume the plugin can be skipped. This could also nicely be connected to the watcher, resulting in very fast rebuilds.

### Virtualize the most costly IO:

* leave files on disk
* leave mutations of files on disk
* virtualize only the symlinks/directories

An old spike: https://github.com/stefanpenner/fs-tree-diff/pull/36

**Comment by stefanpenner** [comment]
> All times ember - is best tool for enterprise UI, but, it worst tool for secured Windows(R) enterprise.

Ya I totally agree. I wish I personally had free cycles to work on the above to described solutions, as I do feel they will minimize that windows pain.

but again, I would encourage you or someone to spike using one of the virtual FS solutions, if it is viable. We can likely make it opt-in.

**Comment by lifeart** [comment]
> Unfortunately a pure in-memory solution isn't super viable for many users, but maybe as an opt-in for those who can?

Agree, flag, for example `ember s --in-memory`

> but again, I would encourage you or someone to spike using one of the virtual FS solutions, if it is viable. We can likely make it opt-in.

Yeah, I was thinking about it, In my imagine, first of all, we need to cover all nodejs `fs` calls into some wrapper, and start tracking/handing fs calls inside it.

**Comment by lifeart** [comment]
@stefanpenner do you need any help on `Skip IO if we know we can` way? It's looks like 30% ready

**Comment by lifeart** [comment]
@stefanpenner I see alot of rebuild errors like "EPERM: operation not permitted, symlink: C:\{path}", is any broccoli option to force disable symlinking?

**Comment by lifeart** [comment]
https://github.com/lifeart/broccoli-memento

**Comment by lifeart** [comment]
@stefanpenner my findings https://github.com/ember-cli/broccoli-builder/pull/30

**Comment by locks** [comment]
Closing as we should focus build efforts on embroider.
