### ISSUE TITLE
Test suite broken for `beta` branch

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#7776]
After disabling the experiments for the 3.2 beta release in 786890f the test suite started failing. Enabling the `MODULE_UNIFICATION` experiment seems to "fix" the test suite again.

/cc @mixonic @GavinJoyce @cibernox @rwjblue

**Comment by GavinJoyce** [comment]
Thanks for pointing this out, I'll wrap the existing module unification tests now with an experiments check

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/7804 fixes the module unification related failures, but there are still a couple of failures remaining due to `DELAYED_TRANSPILATION`.

**Comment by rwjblue** [comment]
#7805 fixed the remaining issues
