### ISSUE TITLE
Error with babel-plugin-transform-es2015-modules-amd with Mozilla pdf.js

### ISSUE THREAD

**Issue by csetera** [ember-cli/ember-cli#7778]
### Summary
I wrote up an issue against Babel (see https://github.com/babel/babel/issues/7759#issuecomment-382809333).  I've been trying to days to figure out how to get a build that does not fail.  I *believe* that ignoring the offending files as part of the Babel processing would likely solve the issue.  However, I've been unable to find a way (documented or otherwise) that works to ignore the offending files which then triggers Babel to crash as documented in that issue.

Is this a bug in Ember CLI?  A shortcoming?  Or am I missing something simple?

### Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.18.2
http_parser: 2.7.0
node: 6.9.4
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
3.10.10
zsh: command not found: yarn
```

**Comment by locks** [comment]
I do not fully understand what the problem is. Can you give a status update if this is still relevant? Thank you!

**Comment by csetera** [comment]
I don't believe this is still an issue.
