### ISSUE TITLE
package-info-cache regressions?

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7815]
I have been testing packager related changes against [`percy-web@master`](https://github.com/percy/percy-web) and it seems like we introduced two regressions with [package-info-cache](https://github.com/ember-cli/ember-cli/pull/7729).

Steps to reproduce (assuming latest `master` of `ember-cli` is npm linked, that is `npm link` within `ember-cli` repo):

```bash
cd ~/tmp && git clone git@github.com:percy/percy-web.git && cd percy-web &&
npm i && npm link ember-cli && ember b
```

After running _any_ `ember` command, several `Missing package.json file` warnings are shown:

```bash
WARNING:
WARNING: /path/to/ember-cli/node_modules/fast-sourcemap-concat/node_modules/chalk:
WARNING:    Missing package.json file
WARNING:
WARNING: /path/to/ember-cli/node_modules/fstream:
WARNING:    Missing package.json file
WARNING:
WARNING: /path/to/ember-cli/node_modules/node-pre-gyp:
WARNING:    Missing package.json file
WARNING:
WARNING: /path/to/ember-cli/node_modules/node-pre-gyp/node_modules/http-signature:
WARNING:    Missing package.json file
WARNING:
WARNING: /path/to/ember-cli/node_modules/node-pre-gyp/node_modules/request:
WARNING:    Missing package.json file
WARNING:
WARNING: /path/to/ember-cli/node_modules/tar-pack:
WARNING:    Missing package.json file
```

[`percy-web@master`](https://github.com/percy/percy-web) now fails with the following error:

```bash
Build failed.
Build Error (Funnel)

ENOENT: no such file or directory, lstat '/path/to/tmp/percy-web/tests/dummy/mirage'
```

Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 3.2.0-beta.2-app-and-deps-236d49bcf6
http_parser: 2.8.0
node: 9.11.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 3
openssl: 1.0.2o
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
5.6.0
1.6.0
```

I don't think I'm blocked on packager work, but to test it out, I'm going to have to pluck out `package-info-cache` commit. That being said, I think we should forward-fix to avoid reverting that PR and lose speed gains.

thoughts? @stefanpenner @dcombslinkedin

**Comment by twokul** [comment]
I also run semi-consistently into:

```bash
1) models/package-info-cache.js
     packageInfo contents tests on valid project
       shows projectPackageInfo has 9 node-module entries:

    AssertionError: expected 10 to equal 9
    + expected - actual

    -10
    +9

    at Context.<anonymous> (tests/unit/models/package-info-cache-test.js:118:58)
```

**Comment by dcombslinkedin** [comment]
I managed to get a copy of ember-cli into a state where 4 directories, like node_modules/node-pre-gyp, only contained 'node_modules' subdirectories, and no other content. I'm not sure exactly how, but I had an older copy of ember-cli and did a 'git pull --rebase' to update it. It was only linked to github, it was not a fork. Once I did 'yarn' on that, everything worked. I did a second clone of ember-cli and everything worked immediately, even without the extra 'yarn' to update anything.

**Comment by stefanpenner** [comment]
> nice I did 'yarn' on that, everything worked. 

is it that package-info stuff is catching yarn/npm bugs, specifically missing installed files?

**Comment by dcombslinkedin** [comment]
Presumably two/index.js should resolve to node_modules/one, right? Given that two/node_modules/one is empty, what's the node-resolution algorithm supposed to return in this situation? I was pretty careful in this section, though it's definitely possible there's an error there.

**Comment by twokul** [comment]
@dcombslinkedin I tried the combination of `yarn` and `yarn link`, all of the warnings are gone now and in good state. It's very likely is npm bug.

I am unsure if it's worth spending time reproducing it locally so I'm going to close for now.
