### ISSUE TITLE
Test error: "Missing npm packages:  Package: ember-source"

### ISSUE THREAD

**Issue by kaermorchen** [ember-cli/ember-cli#7820]
Hello.

My some addons have the same test error: 

```
Missing npm packages: 
Package: ember-source
  * Specified: https://s3.amazonaws.com/builds.emberjs.com/release/shas/cc511bb5280d5697f2c07379fafe506644df6855.tgz
  * Installed: (not installed)
Run `npm install` to install missing dependencies.
```

All another builds work well

![2018-05-08_13-15-52](https://user-images.githubusercontent.com/11972062/39751785-f6e24cfe-52c1-11e8-8641-393f0838ab26.png)

Broken builds: [ember-cli-bootstrap-4](https://travis-ci.org/kaermorchen/ember-cli-bootstrap-4/jobs/375842582), [ember-mdi](https://travis-ci.org/kaermorchen/ember-mdi/jobs/373078671), [ember-photoswipe](https://travis-ci.org/kaermorchen/ember-photoswipe/jobs/375452064)

I dont't understand what is wrong.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.2
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: win32 x64
6.0.0
```

**Comment by rwjblue** [comment]
This was reported by @kellyselden in https://github.com/emberjs/ember.js/issues/16580. @kategengler and I did a _ton_ of digging and essentially confirmed that this is an NPM bug. Sadly I’m not sure exactly how to fix it. The only thing we thought of was: use yarn or _always_ trigger a second empty commit after each tagged release. :sob:

**Comment by kaermorchen** [comment]
Thanks for fast comment.

**Comment by rwjblue** [comment]
Just pushed emberjs/ember.js#7a4945943 to help mitigate. Might need to add this to our release process 😢.

**Comment by MrAvantiC** [comment]
Hi there,
unfortunately I'm discovering this at the moment when trying to deploy an Ember application to Netlify.

Version-Info `ember version --verbose && npm --version`
```
ember-cli: 3.8.0-beta.1
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.7.0
```

Dependencies:
```
  "devDependencies": {
    "@ember-decorators/babel-transforms": "^5.1.2",
    "@ember/optional-features": "^0.6.3",
    "babel-eslint": "^10.0.1",
    "broccoli-asset-rev": "^2.7.0",
    "ember-auto-import": "^1.2.19",
    "ember-bind-helper": "^0.3.2",
    "ember-cli": "github:ember-cli/ember-cli",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.1.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-fastboot": "^2.0.4",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-markdown-resolver": "^0.1.3",
    "ember-cli-showdown": "^4.4.4",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-stylus": "^1.0.7",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-decorators": "^5.1.2",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-prism": "^0.4.0",
    "ember-qunit": "^3.4.1",
    "ember-resolver": "^5.0.1",
    "eslint-plugin-ember": "^5.2.0",
    "loader.js": "^4.7.0",
    "prember": "^1.0.2",
    "prettier": "^1.16.4",
    "qunit-dom": "^0.8.0",
    "sparkles-component": "^1.3.0",
    "sparkles-decorators": "^0.0.6"
  },
```

As soon as Netlify installs the dependencies and runs `ember build -e production` I get the error.
I can also reproduce this locally by removing my node_modules, running `npm install` and starting the development server.

I tried adding
`"ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/e7a144b1bf432769383c3360bbcc44a68e2b9522.tgz"`
explicitly as a dependency but that did not work either.

The only way to get the deployment working is by running 
`npm install ember-source && ember build -e production`
instead of just
`ember build -e production`

...but that doesn't feel quite right. :/
