### ISSUE TITLE
"viewBox" Attribute on SVG is Misnamed (Ember CLI v3.1.0)

### ISSUE THREAD

**Issue by kkincade** [ember-cli/ember-cli#7839]
I have a simple addon that contains a loading spinner (an SVG element with a circle inside that rotates).

![Working Code](https://user-images.githubusercontent.com/2199847/40320548-54ea3eac-5ce9-11e8-8430-8652b298034c.png)

In Ember CLI version 3.0.0, everything works as expected. After updating to Ember CLI v3.1.4 (likely any version >3.1.0), there is a naming problem in the "viewBox" parameter. It is improperly named as "viewbox", with a lower case _b_. This causes the viewBox not to be respected and therefore the spinner element does not scale.

![Not Working Code](https://user-images.githubusercontent.com/2199847/40320669-afaf3108-5ce9-11e8-9d80-84727771d4e9.png)

I'm applying the viewBox attribute via an attributeBindings:

```js
const VIEWBOX = '0 0 18 18';

// Inside the Component...
attributeBindings: [ 'viewBox', 'width', 'height', 'xmlns' ],

viewBox: VIEWBOX,
```

It seems as though any attributeBinding is being converted to lowercase, which is not what should happen with _viewBox_ in particular. I'm assuming there are other attributes where you would not want to convert case as well. I have reproduced this in all major browsers.

Is anyone aware of this issue? Thanks!

**Comment by rwjblue** [comment]
Seems to be the same as reported in https://github.com/emberjs/ember.js/issues/16477 which was fixed in https://github.com/glimmerjs/glimmer-vm/pull/801 and https://github.com/emberjs/ember.js/pull/16559.

Can you share a demo application that is using ember-source@3.1.2?

**Comment by kkincade** [comment]
Ahh, thank you for pointing me to that. I've updated to 3.1.2 and the issue is resolved. Thank you!
