### ISSUE TITLE
The 2.18.2 dependency on an old testem 2.0.0 pulls in insecure dependencies

### ISSUE THREAD

**Issue by mileslane** [ember-cli/ember-cli#7845]
The latest LTS version of ember-cli has a dependency on a version of testem that pulls in an insecure version of ws.

https://nodesecurity.io/advisories?search=ws&version=1.1.1  (Denial of Service)

“ember-cli”: “2.18.2” depends on
	"testem": "2.0.0" depends on
		"socket.io": "1.6.0" depends on
			"engine.io": "1.8.0" depends on
				"ws": "1.1.1"

---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.18.2
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.8.0
1.1.0
```

**Comment by kellyselden** [comment]
ember-cli doesn't have an LTS version, only ember proper does. Only the latest stable version of ember-cli is supported. This may change in the near future. Thanks for the issue.
