### ISSUE TITLE
Tracker for updating to ember-try 1.0 before release

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7846]

**Comment by rwjblue** [comment]
We need to make sure the addon blueprint has 1.0.0 in it (it had a beta when this issue was created) before we close.

**Comment by rwwagner90** [comment]
@rwjblue it looks like it is set to 1.0 here https://github.com/ember-cli/ember-cli/blob/0a4ecdb474807dae25c18c442dd7f9a8f3ad92b4/blueprints/addon/index.js#L73
