### ISSUE TITLE
Errors when starting empty MU App with latest ember-cli

### ISSUE THREAD

**Issue by GavinJoyce** [ember-cli/ember-cli#7851]
I'm seeing the following error when creating and starting a new module unification app:

`broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, stat 'mu_app/tmp/config_replace-input_base_path-5vaoHUX0.tmp/0/index.html'`

/cc @twokul you might be able to shed some light on this as it looks like you've been working in the area recently 

<img width="714" alt="screen shot 2018-05-26 at 05 53 58" src="https://user-images.githubusercontent.com/2526/40572652-40a14616-60a9-11e8-8efa-ff95abc3edc9.png">

<img width="1114" alt="screen shot 2018-05-26 at 05 57 23" src="https://user-images.githubusercontent.com/2526/40572667-bb13f876-60a9-11e8-9d9a-dc6d0535944f.png">

### Repo steps

Following the instructions in https://github.com/emberjs/ember.js/issues/16373

```
npm install -g https://github.com/ember-cli/ember-cli.git
```

```
MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true ember new my-mu-app
```

```
cd my-mu-app && ember serve
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.2.0-beta.2
http_parser: 2.8.0
node: 10.2.1
v8: 6.6.346.32-node.8
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
5.6.0
1.6.0
```

**Comment by twokul** [comment]
tried it locally and it worked for me :| let me see what I can find

**Comment by twokul** [comment]
`EMBER_CLI_MODULE_UNIFICATION=true ember s` works

**Comment by twokul** [comment]
`canary` works with the packager (internally) now and I made a clear separation between classic and MU folder layouts which means every time you run `serve` or `build`, you will need to specify `EMBER_CLI_MODULE_UNIFICATION=true` flag

**Comment by GavinJoyce** [comment]
👍 thanks, I've verified that it's working as expected with the `EMBER_CLI_MODULE_UNIFICATION=true` flag. I'll update the docs in the quest issues
