### ISSUE TITLE
package hook is getting compiled addon code

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#7852]
Even with DELAYED_TRANSPILATION on, the package hook is getting AMD addon code. It is because of this line https://github.com/ember-cli/ember-cli/blob/5e124442e7366ecaf93f22973819db12c03056e6/lib/broccoli/ember-app.js#L1164.

This block needs to move to after the package hook is called (for our fallback packager to handle).

cc @twokul

**Comment by locks** [comment]
Should be fixed by referenced PR.
