### ISSUE TITLE
Ember Cli test --host option is ignored

### ISSUE THREAD

**Issue by robert-j-webb** [ember-cli/ember-cli#7854]
Hi, running into a problem where my test server is listening to all incoming connections. I could reproduce it on a completely new ember install, so I figure this is a big problem affecting anyone.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.4
http_parser: 2.7.0
node: 9.3.0
v8: 6.2.414.46-node.15
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.5.1
zsh: command not found: yarn
```

Steps I took:
```
nvm use v9.3.0 
npm install -g ember-cli@latest
mkdir hello
cd hello
ember init
ember test --serve --host 127.0.0.1
lsof -i -n -P | grep 7357
```

Observed output:
```
node      13529 robertwebb   22u  IPv6 0xXXXXXXXXXXXXX     0t0  TCP *:7357 (LISTEN)
node      13529 robertwebb   30u  IPv6 0xXXXXXXXXXXXXX      0t0  TCP 127.0.0.1:7357->127.0.0.1:56246 (ESTABLISHED)
```

Expected output:

```
node      13529 robertwebb   22u  IPv6 0xXXXXXXXXXXXXX      0t0  TCP 127.0.01:7357 (LISTEN)
node      13529 robertwebb   30u  IPv6 0xXXXXXXXXXXXXX     0t0  TCP 127.0.0.1:7357->127.0.0.1:56246 (ESTABLISHED)
```

Basically lsof tells me which ports are open and on which host. This means that test servers are listening on any port, including 0.0.0.0, so basically everyone running a test server is broadcasting it to their network and they can't change it, AFAIK.

Possible fix: modify the express.listen call: https://expressjs.com/en/api.html#app.listen

**Comment by rwjblue** [comment]
Eeck. Seems bad. Can you check `ember s` also?

**Comment by robert-j-webb** [comment]
It looks like `ember s` is working.

```
ember serve --host 127.0.01
Build successful (3016ms) – Serving on http://127.0.0.1:4200/
```
Check
```
lsof -i -n -P | grep 4200
node      25902 robertwebb   18u  IPv4 0xXXXXXXXXXX      0t0  TCP 127.0.0.1:4200 (LISTEN)
```

**Comment by rwjblue** [comment]
Specifically [here](https://github.com/testem/testem/blob/ed17398452743afd0a4952d343c10bf07588ea7a/lib/server/index.js#L64) where it should also be using `this.config.get('host')` (in addition to `this.config.get('port')`).

**Comment by robert-j-webb** [comment]
Ok, I'll open an issue in that repo. Thanks @rwjblue!
