### ISSUE TITLE
Cannot Set "selected" Attribute on Select's Option Element

### ISSUE THREAD

**Issue by kkincade** [ember-cli/ember-cli#7859]
I am implementing a dropdown using Ember, but I cannot set the _selected_ property of an *option* element using a handlebars expression.

Here is an [ember-twiddle example](https://ember-twiddle.com/760cc2026e79ee0a77bce85b43272c8c?openFiles=templates.components.test-select.hbs%2Ctemplates.components.test-select.hbs) that shows the issue. Notice how in the DOM, the selected attribute does not appear for the top example.

```hbs
<select
    aria-disabled="{{disabled}}"
    aria-multiselectable="{{multiselect}}"
    disabled={{cannotOpen}}
    onchange={{action 'itemClicked' value='target.value'}}
>
    <option selected disabled value="">{{placeholder}}</option>

    {{#each items as |item|}}
        <option value={{item.value}} selected={{if (is-item-selected item.state) "selected"}} disabled={{item.disabled}}>
            {{item.name}}
        </option>
    {{/each}}
</select>
```

> "is-item-selected" is a custom helper that returns true if "item.state === 2", which is does when the item is selected in the dropdown.

No matter what I try in the handlebars, the _selected_ attribute will not display (e.g. `selected={{if true "selected"}}` does not work either). However, changing _selected_ to _data-selected_ works exactly as intended.

Is anyone aware of this issue? Or am I misunderstanding how the _selected_ attribute is supposed to work?

**Comment by twokul** [comment]
I suspect you meant to create an issue on [https://github.com/emberjs/ember.js](https://github.com/emberjs/ember.js) because Ember CLI a command line utility for building Ember applications. I'd suggest you start asking either on [stackoverflow](https://stackoverflow.com/search?q=emberjs) or [discourse](http://discuss.emberjs.com/).
