### ISSUE TITLE
App's fingerprint changes even when only a package has been updated

### ISSUE THREAD

**Issue by astronomersiva** [ember-cli/ember-cli#7865]
When I add/update a package in my app, running a production build causes the app.js' fingerprint to change. Ideally, I would expect only the vendor.js' fingerprint to change as I have updated some vendor assets only.

This is happening because of the commit SHA that is getting added to the end of app.js. (`.default.create({name:"appName",version:"0.0.0+b3aa7951"})`). Due to this, even if I just update some strictly development related dependency(like eslint), our users will have to fetch the entire app.js again as the commit for updating eslint would have now caused the app.js' checksum to change.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.18.2
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.6.0
1.3.2
```

**Comment by Turbo87** [comment]
@astronomersiva that commit SHA is added by https://github.com/ember-cli/ember-cli-app-version. if you don't need it then you could remove the dependency and hopefully afterwards the fingerprint should stay constant.

**Comment by astronomersiva** [comment]
@Turbo87 thanks for the response. I guess it's better to make a note about this in ember-cli docs as this seems like a bad behaviour by default for most people. IMO, there should at least be a way to disable this in production.

**Comment by Turbo87** [comment]
> IMO, there should at least be a way to disable this in production.

yes, remove `ember-cli-app-version` from your depencencies.

> I guess it's better to make a note about this in ember-cli docs as this seems like a bad behaviour by default for most people

I don't necessarily agree. It's far more common for app code to change than it is for your dependencies to change, so in most cases `app.js` will change anyway.

It might be good to add a note about this to the README of `ember-cli-app-version` though.

**Comment by rwjblue** [comment]
Also, FWIW, it’s quite possible for dependency updates to _also_ change the app JS file (e.g. an addon adds or changes a file in its `app/` dir).

**Comment by astronomersiva** [comment]
@rwjblue that's a valid point. My concern is about packages like ember-cli-eslint where it is not ideal to change the checksum of app.js due to a version upgrade.

Even a small typo correction in the project's README.md will cause the app.js' checksum to change because of this behaviour.

**Comment by rwjblue** [comment]
Yep, and most of the time _thats ok_ 😸! 

Having the repo version (including SHA) in the build is quite useful generally speaking. Removing it when you have special cache invalidation constraints seems totally reasonable.
