### ISSUE TITLE
[Module Unification] Support for loading/error substates

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-cli#7868]
I was expecting with the new file layout that adding a handlebars file with the correct naming and location would keep the existing functionality of [these substates](https://guides.emberjs.com/release/routing/loading-and-error-substates/).

So I tried the obvious location beside the template.

```
src
├── ui
│   ├── routes
│   │   ├── application
│   │   │   ├── loading.hbs
│   │   │   └── template.hbs
```

As this didn't work I took a look at the [initial PR](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md) and realised that there is no mention of loading / error substates in it.

Is this something which has been considered, or are substates now being phased out to be replaced by some other best practice to handle these use cases?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.2.0-beta.2
http_parser: 2.8.0
node: 9.10.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2o
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
os: darwin x64
5.6.0
1.5.1
```

**Comment by rwjblue** [comment]
From the guide you linked:

> When accessing foo.bar.slow-model route then Ember will alternate trying to find a routeName-loading or loading template in the hierarchy starting with foo.bar.slow-model-loading:
>
> 1. foo.bar.slow-model-loading
> 2. foo.bar.loading or foo.bar-loading
> 3. foo.loading or foo-loading
> 4. loading or application-loading

All of this information is still correct in MU layout, but the exact location on disk for these files is not obvious. At a glance I believe the various loading routes/templates that are looked up should be:

1. `src/ui/routes/foo/bar/slow-model-loading/{template.hbs,route.js}`
2. `src/ui/routes/foo/bar/loading/{template.hbs,route.js}`
3. `src/ui/routes/foo/bar-loading/{template.hbs,route.js}`
4. `src/ui/routes/foo/loading/{template.hbs,route.js}`
5. `src/ui/routes/foo-loading/{template.hbs,route.js}`
6. `src/ui/routes/loading/{template.hbs,route.js}`
7. `src/ui/routes/application-loading/{template.hbs,route.js}`

**Comment by chrism** [comment]
Ah OK, many thanks for explaining—that's interesting as I hadn't initially considered it would be organised that.

I'd imagined that because they it was just a template, not an entire route, that the expected location would be to just locate the loading or error hbs files in the same route location at the `template.hbs` file.

For reference [here is a demo repo](https://github.com/chrism/emberjs-2018/tree/application-loading-route) showing that approach `src/ui/routes/application/loading.hbs` does not work.

https://github.com/chrism/emberjs-2018/blob/application-loading-template/src/ui/routes/application/loading.hbs

Following your advice [here is another demo repo](https://github.com/chrism/emberjs-2018/tree/application-loading-route) where I've created an entirely new route, called `application-loading`, which contains the `route.js` and `template.hbs` files.

https://github.com/chrism/emberjs-2018/tree/application-loading-route/src/ui/routes/application-loading

But this does not seem to work either.

For reference, the way I am delaying the model is to use a simple run.later, which I hope illustrates the use case as simply as possible.

[`/src/ui/routes/application/route.js`](https://github.com/chrism/emberjs-2018/blob/application-loading-template)

```js
import Route from '@ember/routing/route';
import { Promise } from 'rsvp';
import { later } from '@ember/runloop';

export default class ApplicationRoute extends Route {
  model() {
    const delayPromise = new Promise(resolve => later(resolve, 2000));

    return delayPromise.then(() => {
      return { filename: "tomster", filetype: "png" };
    });
  }
}
```

**Comment by ldong** [comment]
![image](https://user-images.githubusercontent.com/5491695/59143400-8ebb4400-897f-11e9-9e32-16f991dbeaf7.png)

```
ember -v
ember-cli: 3.11.0-beta.3
node: 12.2.0
os: darwin x64
```

```
MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true ember s --port=4201
```



`MODULE_UNIFICATION=true EMBER_CLI_MODULE_UNIFICATION=true ./node_modules/ember-cli/bin/ember g route loading`

If you generate a `loading` route, seems to be okay.

Not sure why `application-loading` isn't behaving like it ought to.

**Comment by Turbo87** [comment]
closing due to https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html
