### ISSUE TITLE
ember serve is currently broken — Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by chrism** [ember-cli/ember-cli#7870]
`ember serve` no longer works with the most recent version of Canary.

It can be reproduced as simply as by creating a new application and upgrading ember-cli to the latest version.

```
ember new classic-error --yarn
yarn upgrade ember-cli@https://github.com/ember-cli/ember-cli.git
```

Now it displays this error when running `ember serve`

Here is the full stack from the error log file

```
  - stack: TypeError: Cannot read property 'replace' of undefined
    at Class.serverMiddleware (/Users/username/classic-error/node_modules/ember-cli-inject-live-reload/index.js:44:38)
    at ExpressServerTask.<anonymous> (/Users/username/classic-error/node_modules/ember-cli/lib/tasks/server/express-server.js:101:22)
    at /Users/username/classic-error/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/username/classic-error/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/username/classic-error/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/username/classic-error/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/username/classic-error/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

The line it refers to is [this one](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/master/index.js#L44).

```js
var baseURLWithoutHost = baseURL.replace(/^https?:\/\/[^\/]+/, '');
```

I noticed that the [most recent commit to ember-cli](https://github.com/ember-cli/ember-cli/commit/9a4c95608928c207e6fefc22a9ee0c7af652ecc8) also related to config and baseURL so figured perhaps this was the cause.

By downgrading the `ember-cli` package to the previous commit SHA

```
yarn upgrade ember-cli@https://github.com/ember-cli/ember-cli.git#5f78c5c2e88b5d701798ec7b09bf3e636ef0fbb2
```

`ember serve` now runs the server again correctly.

This makes me pretty confident that the issue has arisen from the most recent commit.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.2.0-beta.2
http_parser: 2.7.0
node: 9.8.0
v8: 6.2.414.46-node.21
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
os: darwin x64
5.6.0
1.6.0
```

**Comment by buschtoens** [comment]
Also experiencing this. But only for a module unification addon. Works fine for a regular addon. 🤔

**Comment by buschtoens** [comment]
Nevermind. I did not upgrade the classic addon as described by @chrism. After upgrading, I experience the same error in a classic addon.

**Comment by buschtoens** [comment]
https://github.com/ember-cli/ember-cli/pull/7861

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-cli/pull/7875
