### ISSUE TITLE
Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin.

### ISSUE THREAD

**Issue by abulsayyad123** [ember-cli/ember-cli#7878]
I am trying to upgrade my Ember application from Ember **2.12.0** to **2.13.0**. I am able to change ember-cli version but when I try to change ember version in bower.json file. I am getting "**Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin**" error.
package.json:
```
{
  "devDependencies": {
    "active-model-adapter": "2.1.1",
    "body-parser": "^1.18.2",
    "broccoli-asset-rev": "^2.6.0",
    "connect-restreamer": "^1.0.3",
    "cors": "^2.7.1",
    "ember-ajax": "^2.5.1",
    "ember-cli": "2.13.0",
    "ember-source": "~2.13.0",
}
```
After doing **npm install** and **bower install** (also doing npm cache and bower cache clean). And on running server I am getting above error.
How to solve this problem?

**Comment by jacobq** [comment]
@abulsayyad123 Could you please post the error details? (e.g. there is usually some output afterwards like "failed with: .....") Googling your reported error message, suggests that you might have a [syntax error](https://stackoverflow.com/questions/41646927/ember-cli-build-error-the-broccoli-plugin-broccoli-persistent-filtertemplat#41647006)

**Comment by twokul** [comment]
It doesn't seem to be a bug with `ember-cli` itself, but if you think it is, please re-open. I would suggest asking on [stackoverflow.com](http://stackoverflow.com/).
