### ISSUE TITLE
Does ember CLI (ember s and rebuilds) use multiple cores?

### ISSUE THREAD

**Issue by tomaszs** [ember-cli/ember-cli#7883]
I am using an old version of ember. And noticed it uses 100% of one core, but does not take use of other 5 cores. It impacts the ember s command and rebuild time.

[http://pl.tinypic.com/r/2ni7haa/9](http://pl.tinypic.com/r/2ni7haa/9)

So my question is if current latest version did have any changes in it? Does it use all cores?

**Comment by rwjblue** [comment]
Yes, but there were issues until recently preventing the parallelization with Babel. Should be good now though...

**Comment by jasonmit** [comment]
Most apps will opt out of parallelization because of:
https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/issues/41

**Comment by Turbo87** [comment]
@jasonmit it should still run Babel in parallel though
