### ISSUE TITLE
Bugs in Packager

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#7890]
The original error:

```
Build failed.
Sass Syntax Error (SassCompiler) in percy-web/styles/app.scss:4:1

Error: File to import not found or unreadable: tailwind.
       Parent style sheet: /Users/alex.navasardyan/code/oss/percy-web/tmp/sass_compiler-input_base_path-JLAFoPAa.tmp/percy-web/styles/app.scss
        on line 4 of tmp/sass_compiler-input_base_path-JLAFoPAa.tmp/percy-web/styles/app.scss
>> @import "tailwind";
   ^
```

Discovered two bugs while running latest `master` against `percy-web`:

+ `tailwind` folder (https://github.com/embermap/ember-cli-tailwind/) should be under `styles` folder as it contains styles necessary for the application 
+ `ember-data-factory-guy` shouldn't be under `tests` folder

![screen shot 2018-06-28 at 3 31 25 pm](https://user-images.githubusercontent.com/1131196/42063830-75a7a39c-7ae8-11e8-9483-0d45ab83c093.png)

cc @kellyselden

**Comment by kellyselden** [comment]
> ember-data-factory-guy shouldn't be under tests folder

According to your image, it isn't. Do you mean it shouldn't have a tests folder? Or it should be in the tests folder?

After the last two fixes, is this still an issue?

**Comment by twokul** [comment]
Turns out that it has nothing to do with packager --  stable releases of `ember-cli` have the same behaviour

![screen shot 2018-07-05 at 9 39 18 am](https://user-images.githubusercontent.com/1131196/42336085-6477cbd4-8037-11e8-84bc-88246c092706.png)

**Comment by twokul** [comment]
compilation bug was fixed; safe to close

**Comment by webark** [comment]
@twokul did you ever figure out when this got introduced?
