### ISSUE TITLE
Define ENV variables in .ember-cli

### ISSUE THREAD

**Issue by gossi** [ember-cli/ember-cli#7896]
It can become tedious to prefix every command with the correct environment variables over and over again. At the moment for example if you have an experiment running, you have to prefix the ember command with that experiment name, e.g. `EMBER_CLI_MODULE_UNIFICATION=true ember serve`.

As those ENV variables depend on their project, it makes most sense to define them once for that project and use ember commands as usual. `.ember-cli` looks like a good place for me to define them and could look like this:

```json
{
  "disableAnalytics": false,
  "EMBER_CLI_MODULE_UNIFICATION": true
};
```

or be more explicit:

```json
{
  "disableAnalytics": false,
  "ENV": {
    "EMBER_CLI_MODULE_UNIFICATION": true
  }
};
```

Alternatively read in a `.env` file(s) where variables can be defined. There is kind of a standard here I guess? Which is used by CI/CD services. I haven't run enough research on this one to make a clear statement other than "more research needed".

**Comment by astronomersiva** [comment]
+1 to this. I have been running a module unification project myself and this often gets in the way.

I feel `.ember-cli` is the right place for this as `.env` files are generally ignored in source control. There can be an `experiments` field in the `.ember-cli` file that we can make use of [here](https://github.com/ember-cli/ember-cli/blob/master/lib/experiments/index.js).

I am willing to work on this if this seems reasonable.

cc: @rwjblue

**Comment by stefanpenner** [comment]
> I feel .ember-cli is the right place for this as .env files are generally ignored in source control. There can be an experiments field in the .ember-cli file that we can make use of here.

Sounds reasonable to me.

**Comment by gossi** [comment]
Solution is in #8157

**Comment by locks** [comment]
Fix has been merged!

**Comment by btecu** [comment]
It looks like it got reverted: https://github.com/ember-cli/ember-cli/pull/8008.

**Comment by locks** [comment]
Hm, it looks like it was. Thanks for the link! I think I'll keep the issue closed for a couple of reasons. One is that module unification has been dropped for a long time, the other is that usage of dotenv is widespread and that seems like a better solution than putting more functionality into `.ember-cli`.
