### ISSUE TITLE
node_modules appears empty, you may need to run `yarn install`

### ISSUE THREAD

**Issue by afuno** [ember-cli/ember-cli#7906]
Dockerfile:

```
FROM alpine:3.8

ENV APP_PATH=/app

ENV OTHER_PACKAGES nodejs npm yarn

ENV RAILS_ENV=production
ENV NODE_ENV=production

RUN apk update \
&&  apk add $OTHER_PACKAGES \
&&  apk upgrade \
&&  rm -rf /var/cache/apk/*

RUN mkdir $APP_PATH

WORKDIR $APP_PATH

COPY package.json .
COPY yarn.lock .

RUN npm install -g ember-cli --no-cache
RUN yarn install

COPY . .

RUN yarn build:prod
```

How to fix this error?

```
$ ember build --environment=production
node_modules appears empty, you may need to run `yarn install`

error Command failed with exit code 1.
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.1.4
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
5.6.0
1.7.0
```

**Comment by twokul** [comment]
This is not the issue with `ember-cli` itself, and likely with `Dockerfile` itself (maybe you're not moving `node_modules` folder along with newly create application.)

I'd suggest asking this question either on [Ember Discourse](https://discuss.emberjs.com/) or [Stackoverflow](https://stackoverflow.com/questions/tagged/ember-cli).

**Comment by imrrahul** [comment]
![screenshot from 2018-02-07 21-14-08](https://user-images.githubusercontent.com/37583853/51789476-2da08a00-21af-11e9-878d-05c2bd46ad96.png)
I am getting this error whenever I run the ember server
Please help me in solving this problem.

**Comment by imrrahul** [comment]
I am getting thsi problem whenever I run "ember server", it says to install npm , after installing same error comes out.
![screenshot from 2019-01-26 21-12-40](https://user-images.githubusercontent.com/37583853/51789548-b7e8ee00-21af-11e9-8ef1-fd148f9542d2.png)

**Comment by enigmatix** [comment]
Potentially related to this: https://github.com/ember-cli/ember-cli/issues/8575
