### ISSUE TITLE
Add FAQ entry to PERF_GUIDE about docker + ember-cli 

### ISSUE THREAD

**Issue by hefox** [ember-cli/ember-cli#7918]
Considering the drastic performance issues with ember-cli in docker (https://docs.docker.com/docker-for-mac/troubleshoot/#/known-issues), it could be good to add an entry in the PERF_GUIDE about it

I'm still working on a solution, can do a PR once I figured out how to fix it if desired.

**Comment by stefanpenner** [comment]
@hefox nice, yes would love to have a PR with your insights/experiences once you have them.

**Comment by Turbo87** [comment]
@hefox did you figure something out?

**Comment by hefox** [comment]
@Turbo87 a few things were tried but in end we ended up taking the ember cli build out of docker :/

**Comment by Turbo87** [comment]
okay, I'll close this for now then. feel free to open a PR if you find improvements.
