### ISSUE TITLE
Removing ember-cli-shim

### ISSUE THREAD

**Issue by step2yeung** [ember-cli/ember-cli#7928]
Using ember-cli: 3.3.0 to create a new ember app, I can still see ember-cli-shim as a devDependencies in package.json. According to https://github.com/ember-cli/ember-cli-shims, the addon is deprecated. 

Talked to @rwjblue and this should be removed.

```
syeung-mn5:test-app-2 syeung$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.3.0
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
5.6.0
1.5.1
```

**Comment by Turbo87** [comment]
this was resolved by https://github.com/ember-cli/ember-cli/pull/7774
