### ISSUE TITLE
[MU] Style from treeForStyles not included in build 

### ISSUE THREAD

**Issue by hakubo** [ember-cli/ember-cli#7930]
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.0-beta.1
http_parser: 2.8.0
node: 10.7.0
v8: 6.7.288.49-node.15
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: linux x64
6.1.0
1.7.0
```

I was trying to add MU support to ember-cli-tailwind but I could not figure out how to include generated CSS file inside treeForStyles hook to final build

here is my work https://github.com/embermap/ember-cli-tailwind/pull/43

I have tried different paths for distPath
src/styles, src/ui/styles, app/styles, addon/styles
nothing worked for me

Is there something I do wrong? or bug in ember-cli?

**Comment by willviles** [comment]
Could this be related to https://github.com/ember-cli/ember-cli/issues/7862?

**Comment by locks** [comment]
Thank you for trying out MU support! As the team is no longer pursuing MU, I will close this issue.
