### ISSUE TITLE
"index.js.map" referenced in ember.prod.js, but it is not included in ember-source

### ISSUE THREAD

**Issue by pieter-v** [ember-cli/ember-cli#7944]
Originally reported in ember.js.  as https://github.com/emberjs/ember.js/issues/16844
Description copied.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.3.0
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
-bash: npm: command not found
```

create a new ember project
```
 ember new abc --yarn --skip-git
```
modify `ember-cli-build.js` to generate sourcemaps:
```js
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true
    },
  });
```
A production build gives the following warning:
```
[WARN] (broccoli-uglify-sourcemap) "index.js.map" referenced in "assets/vendor.js" could not be found
```
The `index.js.map` is referenced in `ember.prod.js`

**Comment by urbany** [comment]
I am also seeing this while building for production with sourcemaps. Any idea how to debug it?

**Comment by Turbo87** [comment]
yep, I agree that this is a problem in `ember-source`, not in `ember-cli`. closing in favor of https://github.com/emberjs/ember.js/issues/16881
