### ISSUE TITLE
'ember' is not recognized as an internal or external command -- WINDOWS 10

### ISSUE THREAD

**Issue by rofoto** [ember-cli/ember-cli#7955]
Hi, 

  I have used ember for a little while now( mostly in WSL ) and now am trying to get away from that and go windows 10 all the way. I can install ember-cli from npm but when I try to ember new xxx I get the following error: 

E:\>ember new test
'ember' is not recognized as an internal or external command,
operable program or batch file.

also running ember directly from the C:\Program Files\nodejs\node_global folder seems to work. Would seem there is a PATH issue not sure if the issue is with node/npm as that path gets installed and works. 

I have uninstalled and reinstalled nodejs and made ember-cli the first thing I try to install. 

Any help would be great

Thanks

**Comment by kellyselden** [comment]
It sounds like you've confirmed that this is an issue with your npm PATH set up incorrectly. Closing as this is not an issue with ember-cli. StackOverflow would be your best bet.

**Comment by DPK101** [comment]
Hi rofoto,

I faced the same issue in my win7 machine, I fixed the issue by adding "C:\Users\username\AppData\Roaming\npm" to the path variable as below

1. open command prompt (cmd) and run
2. setx "%path%;C:\Users\username\AppData\Roaming\npm"
3. Reopen the cmd to confirm the changes
4. run command "ember"

You should be seeing that ember command is detected now and is working :)

Thank you!
