### ISSUE TITLE
Expected undefined `event` to cause eslint to fail but doesn't 

### ISSUE THREAD

**Issue by dandehavilland** [ember-cli/ember-cli#7978]
I would expect eslint to throw up `no-undef` error but it passes.

Tried in a fresh 3.3 app, no additional dependencies.

```
// Inside some object, tested in extensions of `Component` and `Controller` 
// ...
someMethod() {
  this.event = event;
}
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.3.0
http_parser: 2.7.0
node: 8.7.0
v8: 6.1.534.42
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
6.1.0
1.9.4
```

```
$ ./node_modules/eslint/bin/eslint.js -v
-> v4.19.1
```

**Comment by kellyselden** [comment]
I don't think a new project has that rule enabled.

**Comment by dandehavilland** [comment]
Anything other than `event` behaves as expected.

```
someMethod() {
  this.event = somethingElse;
}
```

```
$ yarn lint:js
-> ...
-> 5:18  error   'somethingElse' is not defined  no-undef
```

**Comment by kellyselden** [comment]
Is event an default eslint global?

**Comment by dandehavilland** [comment]
Yes it is. I would suggest disallowing that as covered [here in the eslint docs](https://github.com/eslint/eslint/blob/002e199c7b579a760dc87e61be7430aa9ad0f601/docs/rules/no-restricted-globals.md), but I imagine that might throw up some issues for apps that may already be using it. I guess I'll just do that in my app.
