### ISSUE TITLE
Breaking changes to meaning of `environment`

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#7980]
The [new feature that allows you to put environment variables in .ember-cli](https://github.com/ember-cli/ember-cli/pull/7910) has some very surprising side effects:

1. At runtime, `require('your-app/config/environment').default.environment` changes from a string like `"development"` to a POJO containing the settings from your `.ember-cli`.

2. Custom ember-cli commands that previously accepted their own option named `environment` are now getting stomped with the settings from `.ember-cli`. Here is [an example](https://github.com/cardstack/cardstack/blob/8ec12aa1f2bb2c88496d302336586d2a74dbac7d/packages/hub/commands/start-native.js#L11-L15) of a command that breaks if you try to use the new feature.

**Comment by ef4** [comment]
So this has _got_ to be a bug:

https://github.com/ember-cli/ember-cli/blob/0f9d15d011fd9adb4c2a8db52e44bf5d74679631/lib/models/builder.js#L50

When you're using this feature, the `EmberApp`'s `env` is `"[object Object]"`

That is what causes point number 1 above. Point number 2 is maybe legitimate, if surprising. It seems that your `.ember-cli` is allowed to provide defaults for any command line argument.

**Comment by ef4** [comment]
After more digging, these two issues are one-in-the-same, because the `build` command itself is getting its `environment` stomped here:

https://github.com/ember-cli/ember-cli/blob/0f9d15d011fd9adb4c2a8db52e44bf5d74679631/lib/commands/build.js#L19

It used to receive `{ environment: 'development' }` in the `commandOptions`, now it will get your POJO.

**Comment by knownasilya** [comment]
I'm surprised no tests caught this issue?

**Comment by rwjblue** [comment]
Indeed.

**Comment by rwjblue** [comment]
We should revert ASAP, and bring back the feature with more test coverage.
