### ISSUE TITLE
treeForStyles regression since 3.4.0-beta.2

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli#7987]
When using `ember-cli-sass` and `ember-bootstrap` in an app using at least 3.4.0-beta.2 (or -beta.3), this error shows up:

```
Sass Syntax Error (SassCompiler) in stylestest/styles/app.scss:3:1

Error: File to import not found or unreadable: ember-bootstrap/bootstrap.
        on line 3 of tmp/sass_compiler-input_base_path-RoP5qwYN.tmp/stylestest/styles/app.scss
>> @import "ember-bootstrap/bootstrap";
```

This does *not* happen with 3.4.0-beta.1 (or any other version before that AFAIK)!

The addon funnels Sass files from `node_modules` in `treeForStyles()`, for easy importing in `app.scss` (here: https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L193-L199).

FWIW, `ember-sass-bootstrap` does basically the same, and suffers from exactly the same problem! (cc @ef4)

### Investigation

I tried to investigate this, could not really find anything suspicious in between -beta.1 and -beta.2 (https://github.com/ember-cli/ember-cli/compare/v3.4.0-beta.1...v3.4.0-beta.2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) though. I patched `ember-cli-sass` to wrap the input tree for the Sass plugin in a `debug()` (here: https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L26), and these are the results:

For 3.4.0-beta.1:
![image](https://user-images.githubusercontent.com/1325249/44292862-a0641b80-a287-11e8-8683-ec357f6ec551.png)

For 3.4.0-beta.2:
![image](https://user-images.githubusercontent.com/1325249/44292868-aa861a00-a287-11e8-9171-6aa45e1b3ab4.png)

As you can see the trees are quite different, for beta.2
* has a `stylestest` (name of app) folder instead of `app`
* that tree includes all the *.js files as well! 🤔
* the funneled `treeForStyles` tree (the highlighted `ember-bootstrap` line) is *within* this folder, instead of a sibling of it

### Reproduction

Find the steps to reproduce this here: https://github.com/kaliber5/ember-bootstrap/issues/645

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.0-beta.3
http_parser: 2.8.0
node: 10.5.0
v8: 6.7.288.46-node.8
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
6.1.0
1.9.2
```

**Comment by simonihmig** [comment]
Yes, I saw this PR, and I already tried -beta.3 as mentioned, as well the latest beta and master branches, but to no avail unfortunately!

**Comment by dcyriller** [comment]
Wondering if the first commit of this diff would not fix the issue https://github.com/ember-cli/ember-cli/compare/v3.4.0-beta.3...master 🤔

**Comment by simonihmig** [comment]
> Wondering if the first commit of this diff would not fix the issue v3.4.0-beta.3...master 🤔

No, it does not. Tried with this commit, as well as head of master.

**Comment by stefanpenner** [comment]
Bummer. I’m traveling today, but will try to find time this week to investigate.  

Thanks for the bug report during beta, better to catch this stuff early.

If you happen to have time, a bisect of ember-cli commits would be handy.

**Comment by camthompson** [comment]
I've run into this while testing the beta as well. Bisecting shows dd5d2d2abdb15dccd323faef8f9c4637c7345e8a as the first commit where this occurs.

**Comment by simonihmig** [comment]
Seems definitely related. Not sure though why things are working for me with 3.4.0-beta.1, while github shows the mentioned commit is included there!? 🤔

@twokul pinging you here as you were the author of the PR (#7829) in question...

**Comment by twokul** [comment]
@simonihmig let me investigate; while trees are supposed to look different, functionality should we the same. thanks for reporting!

**Comment by twokul** [comment]
found the root cause; going to post a more detailed update in a few

**Comment by twokul** [comment]
As Ember CLI gathers the trees from add-ons, it needs to properly place them within its "working" directory for processing later (both JS and SASS/LESS).

The root cause of the issue was that files returned from the add-ons weren't properly moved, and will later cause transpilation failures as preprocessing step couldn't find files it needed to resolve `@import` statements within `app.scss`.

I drafted [a fix](https://github.com/ember-cli/ember-cli/compare/v3.4.0-beta.3...twokul:beta-styles-fix)  and tested it locally w/ both `ember-bootstrap` and `ember-basic-dropdown`.

Similar bug exists in `master`, I will make sure the fix lands tomorrow and you are unblocked.

thanks much for testing @simonihmig, I'm sorry if it caused you any grief (debugging this stuff can get frustrating sometimes)

gonna catch some 💤

**Comment by simonihmig** [comment]
> thanks much for testing @simonihmig, I'm sorry if it caused you any grief (debugging this stuff can get frustrating sometimes)

No problem, things happen... thanks for the quick response! 👍

**Comment by simonihmig** [comment]
@twokul just tried this out with the latest beta and master branches, after your PRs have been merged. Works fine now again! 🎉

Closing this, thank you!
