### ISSUE TITLE
can't use `ember new newproject` 

### ISSUE THREAD

**Issue by FrankWang1991** [ember-cli/ember-cli#8009]
this is my development environment ：
```
ember-cli: 3.3.0
node: 8.11.4
os: darwin x64
```
and my npm version is 5.6.0.  
but when I use `ember new newproject` ,it's will take a long time in `npm Installing dependencies`.when it's done,terminal will show some errors,like this:  
```
Error creating new application. Removing generated directory `./just-test`
Command failed: npm install --loglevel error
npm WARN deprecated exists-sync@0.0.4: Please replace with usage of fs.existsSync
npm ERR! Unexpected end of JSON input while parsing near '...,"tarball":"http://re'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frank/.npm/_logs/2018-09-02T06_45_25_740Z-debug.log




Stack Trace and Error Report: /var/folders/r2/b01x9bv93gx88m_p5g9ndxmm0000gn/T/error.dump.3a488f200422150bb64a923e89d04626.log
```
[2018-09-02T06_49_52_178Z-debug.log](https://github.com/ember-cli/ember-cli/files/2343023/2018-09-02T06_49_52_178Z-debug.log)
anybody can help me?

**Comment by rwjblue** [comment]
Looks like you might have a broken cached tarball? Maybe attempt to `npm cache clear` and try again?

**Comment by FrankWang1991** [comment]
@rwjblue thanks.It's worked.

**Comment by Uriel7** [comment]
I run this:

`sudo npm cache clear --force`
