### ISSUE TITLE
release ember-cli@3.4

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#8012]
+ [x] fix for `travis-web` and `ember-cli-tailwind` (breaks b/c `ember-cli-tailwind` returns a tree nested under `app/styles`)
  + [x] I've got a fix, need to submit a PR + test (https://github.com/ember-cli/ember-cli/pull/8013)
+ [ ] fix for https://gist.github.com/pgengler/1c7c8117c8ff0c732d3fb06bdfd6ac02
  + [reproduction](https://github.com/twokul/ember-cli-3-4-bug)
  + tried w/ `3.0`, `3.1`, `3.2`, `3.3` and betas; keeps failing, not sure it ever worked?
  + the fix is to switch to relative path within add-on
  + thanks for reporting @pgengler; probably not a release blocker; happy to fix for you in point release
+ [ ] fix tests and verify the build again
+ [ ] release

**Comment by simonihmig** [comment]
@twokul landing this fix is not slated for the next release? https://github.com/ember-cli/ember-cli/pull/7895

**Comment by rwjblue** [comment]
@simonihmig - no doesn't look like it, lets chat over there but we should probably target a patch release with that fix...
