### ISSUE TITLE
App name 'public' breaks ember-cli

### ISSUE THREAD

**Issue by nickschot** [ember-cli/ember-cli#8023]
Generating and starting a new app `ember new public` totally breaks ember-cli. We might want a feature where known broken names are disallowed by ember-cli.

<img width="762" alt="screen shot 2018-09-06 at 12 07 07" src="https://user-images.githubusercontent.com/334789/45150991-68d4f900-b1cd-11e8-9685-31fadfbe5d7f.png">

**Comment by rwjblue** [comment]
Thanks for reporting! We have a blacklist of certain names that break things that we can/should add `public` too.

We shoild also look into _why_ it causes this breakage (we shouldn’t break things needlessly if we don’t have to)....

**Comment by rwjblue** [comment]
The blacklisting is here:

https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/valid-project-name.js
