### ISSUE TITLE
3.4.x stable

### ISSUE THREAD

**Issue by twokul** [ember-cli/ember-cli#8036]
outstanding list:

+ [ ] https://github.com/ember-cli/ember-cli/issues/8026 (waiting for repro & more details)
+ [x] https://github.com/ember-cli/ember-cli/issues/8029 ([fix](https://github.com/Raynos/body/pull/16))
+ [x] https://github.com/ember-cli/ember-cli/issues/8035 ([fix](https://github.com/ember-cli/ember-cli/pull/8038))
+ [x] https://github.com/ember-cli/ember-cli/issues/8037 ([fix](https://github.com/ember-cli/ember-cli/pull/8038))

last two might be similar (that is if you fix one, the other one will be fixed as well)

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/8038 fixes the last three. The [body PR](https://github.com/Raynos/body/pull/16) does fix one aspect of the problem (for users using JSON:API) but doesn't solve the general problem which is that `tiny-lr` is trying to parse all of our responses and having issues.

The fix in #8038 ensures that tiny-lr only parses responses for live reload related things...

**Comment by rwjblue** [comment]
v3.4.2 has been released as `latest` and is stable...
