### ISSUE TITLE
Local server unable to accept login as of 3.4.1

### ISSUE THREAD

**Issue by backspace** [ember-cli/ember-cli#8037]
Hey, I [updated `travis-web` to Ember CLI 3.4.1](https://github.com/travis-ci/travis-web/pull/1784) yesterday but I didn’t realise a problem until I had merged: local logins no longer work.

How login works, briefly:
* a `GET` to `travis-api`
* which redirects to GitHub
* which redirects back to `travis-api`
* which `POST`s back to `travis-web`, which is localhost:4200 running locally

Something has started going wrong with that `POST` since Ember CLI 3.4.1. On the commit before I merged the Ember CLI update, travis-ci/travis-web@d26afc5, I’m able to log in. On 3.4.1 and 3.4.2-beta.1 I’m not, it hangs on the last step and eventually times out. Some logs from `DEBUG:* ember s`:

```
  tinylr:server Destroy client ws1 (url: http://localhost:4200/) +21s
  express:router dispatching POST / +21s
  express:router query  : / +0ms
  express:router expressInit  : / +0ms
  express:router compression  : / +0ms
  express:router bound handler  : / +0ms
  tinylr:server LiveReload handler / (middleware: on) +55ms
  tinylr:server Request: POST / +1ms
  express:router logger  : / +1ms
  express:router urlencodedParser  : / +0ms
  body-parser:urlencoded content-type "application/x-www-form-urlencoded" +21s
  body-parser:urlencoded content-encoding "identity" +0ms
  body-parser:urlencoded read body +0ms
  morgan log request +2m
POST / - - ms - -
  express:router <anonymous>  : / +2m
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +0ms
  express:router dispatching POST / +0ms
  express:router query  : / +0ms
  express:router expressInit  : / +0ms
  express:router compression  : / +0ms
  express:router bound handler  : / +0ms
  tinylr:server LiveReload handler / (middleware: on) +2m
  tinylr:server Request: POST / +0ms
  express:router logger  : / +0ms
  express:router urlencodedParser  : / +1ms
  body-parser:urlencoded content-type "application/x-www-form-urlencoded" +2m
  body-parser:urlencoded content-encoding "identity" +0ms
  body-parser:urlencoded read body +1ms
  finalhandler default 400 +8m
  compression no compression: size below threshold +2m
BadRequestError: request aborted
    at IncomingMessage.onAborted (/Users/b/Documents/Travis/t3/node_modules/body-parser/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:182:13)
    at abortIncoming (_http_server.js:444:9)
    at socketOnClose (_http_server.js:437:3)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:599:12)
```

## Replication

This is possible to reproduce by running `travis-web` locally, [as described in the documentation](https://github.com/travis-ci/travis-web#running-the-app):

```
npm install
npx ember s
```

Once the server has started, if you visit http://localhost:4200 and click “Sign in with GitHub”, you should see the problem. This presumes that you’ve already set up an account on Travis CI; I’m not sure what would happen if you didn’t have one, it would probably still encounter the bug.

## Workaround

There‘s been sleuthing on Discord and there’s a workaround, thanks to @cibernox and @rwjblue: if I run with `ember s --no-live-reload`, I’m able to log in!

None of this is relevant outside of development, thankfully.

Thanks to everyone for their work on this project. 😀

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.2-beta.1
http_parser: 2.8.0
node: 10.7.0
v8: 6.7.288.49-node.15
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.0
1.6.0
```

**Comment by rwjblue** [comment]
Fixed by #8038 and released in v3.4.2.
