### ISSUE TITLE
jQuery flag not honored

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#8043]
Enabling `jquery-integration` in `@ember/optional-features` should respect the following setting in `ember-cli-build`:
```
    vendorFiles: {
      'jquery.js': null
    }
```
This is useful when `jQuery` is already provided by say a parent application and Ember doesn't have to load its own but still keep the integration.

Reproduction https://github.com/btecu/ember-jquery-flag: notice how `jQuery 3` is loaded on top of existing `jQuery 2` loaded in `index.html`.

**Comment by simonihmig** [comment]
I don't think this is supposed to work. Using `vendorFiles` *happened* to work, but was never really a public API to achieve that goal, AFAIK. That's why the RFC proposed the optional feature as *the*  way to opt out. 

Nowadays the  `@ember/jquery` package is responsible to import jQuery. One could certainly add a flag there to skip the import. But that would not rely on the old weird `vendorFiles` hack I would say, instead introduce an own flag like `jquery: { import: false }` or so...

I would suggest to close this and create a feature request over there: https://github.com/emberjs/ember-jquery

**Comment by btecu** [comment]
Is not a hack and is well documented:

<img width="1010" alt="vendorfiles" src="https://user-images.githubusercontent.com/7517745/45596767-48f0c280-b98f-11e8-8c68-75d9d6e43e8a.png">

@rwjblue also confirmed on Discord that it should work.

**Comment by rwjblue** [comment]
Well, @simonihmig is totally correct. It definitely didn’t _mean_ to be public api or anything, but folks happened to reply on it working and I think it’s somewhat important to cater to the use case over in `@ember/jquery`.

Interestingly, the `app.import` over in `@ember/jquery` **is** guarded by a check to `vendorFiles[‘jquery.js’]` so I’m not 100% sure why this isn’t just working....

**Comment by omairvaiyani** [comment]
Just to clarify as this is still a little confusing, if we want to completely remove ```jquery```, we should set ```@ember/optional-features[jquery]``` to ```false```, and for good measure, remove the ```vendorFiles``` property from our ```ember-cli-build.js``` as its no longer the de-facto way to disable ```jquery```?

**Comment by simonihmig** [comment]
@omairvaiyani have a look at the prepared update to the docs here: https://github.com/ember-learn/guides-source/pull/64/files?utf8=%E2%9C%93&diff=unified#diff-5e5a53f135107b69ab4252f47de34f3c

This should work, as long as you use Ember 3.3+ and Ember CLI 3.4+.

**Comment by btecu** [comment]
&nbsp; | jQuery Builtin Integration | jQuery Integration | No jQuery
------------ | ------------- | ------------- | -------------
`optional-features['jquery']` | true | true | false
`vendorFiles['jquery.js']` | - | null | -

@omairvaiyani it's the middle case where that flag is needed, which is not very common.
In general is used when another application is loading jQuery and you want the benefits of it in the Ember app but without duplicating the code (loading it again).

**Comment by omairvaiyani** [comment]
Are you referring to nested ember apps, or add-ons in your second sentence? @btecu

**Comment by btecu** [comment]
It's about applications, addons have no concern with bringing in jQuery.

**Comment by locks** [comment]
I believe this has been addressed. If you think this is still relevant please let us know!
