### ISSUE TITLE
`@ember/test-helpers` included in `tests.js` (v3.4.x)

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#8053]
After updating from EmberCLI 3.3.0 to 3.4.2 I noticed that the `@ember/test-helpers` modules were now included in the `dist/assets/tests.js` file. The diff did not show them as being removed from `test-support.js`, so I'm assuming they are in that file as well for some reason.

**Comment by locks** [comment]
This has been closed by the referenced PR.
