### ISSUE TITLE
ember serve returns error "uv_os_get_passwd returned ENOENT (no such file or directory)"

### ISSUE THREAD

**Issue by lholmquist** [ember-cli/ember-cli#8054]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.3.0
http_parser: 2.8.0
node: 10.10.0
v8: 6.8.275.30-node.24
uv: 1.23.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.33.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: linux x64

npm 6.4.1
```

I ran into this issue when running `ember serve` on Openshift.

a user ID will be assigned by OpenShift regardless what is specified in the
DockerFile. This leads to the command os.userInfo() to fail with the
following error:
```
Running as user uid=1000120000 gid=0(root) groups=0(root),1000120000
....
....
A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
```

Doing a `whoami` will also fail

This actually use to cause a core dump, but was recently fixed to supply the error i'm currenlty getting. 
 see https://github.com/nodejs/node/pull/22599, https://github.com/nodejs/node/pull/22609 for context

It looks like the underlying module that makes the calls to `os.userInfo` is in the username-sync module, so i suppose that is where the possible fix would need to happen.

I'm usually using minishift so i can run openshift locally, then deploying my "ember new ember-app" application using a node module called "nodeshift"

high level gist: https://gist.github.com/lholmquist/b3382a33e5bccb55031744b056b00aab

**Comment by nathan-osman** [comment]
I am seeing this as well when building an Ember app with the `node:latest` Docker container: https://ci.quickmediasolutions.com/job/msm/6/console

```
> ember build

[...]
A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
```

**Comment by locks** [comment]
Is this still happening with the currently supported versions?

**Comment by lholmquist** [comment]
I will need to test it again

**Comment by lholmquist** [comment]
looks like it is all set now!

**Comment by zardaloop** [comment]
> I am seeing this as well when building an Ember app with the `node:latest` Docker container: https://ci.quickmediasolutions.com/job/msm/6/console
> 
> ```
> > ember build
> 
> [...]
> A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
> ```

I am seeing exact same problem when I try to build ember using docker agent in jenkins. Does anyone know how to fix this ? Thaks

**Comment by csprocket777** [comment]
I'm still experiencing this and would as well like to know if there's a solution.

**Comment by zardaloop** [comment]
This is how I resolved it. Let me know if it works for you . https://stackoverflow.com/questions/61961485/a-system-error-occurred-uv-os-get-passwd-returned-enoent-no-such-file-or-direc?noredirect=1#comment109603079_61961485

**Comment by csprocket777** [comment]
I'm not using Jenkins. I'm using Gitlab and am not sure how to translate this solution to work there.
