### ISSUE TITLE
preprocessTree for tests tree is no longer called

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#8056]
Reported by @Turbo87 and is affecting ember-test-selectors.

Reproduction steps:

```
git clone git@github.com:simplabs/ember-test-selectors.git
cd ember-test-selectors
git checkout dependabot/npm_and_yarn/ember-cli-3.4.2
npm install
STRIP_TEST_SELECTORS=true ember test
```

When `STRIP_TEST_SELECTORS` environment variable is set, the `preprocessTree` hook attempts to remove all unit / integration tests (because `ember-test-selectors` strips the attributes), but `preprocessTree` is not working properly.

[Failing PR Upgrading to 3.4.2](https://github.com/simplabs/ember-test-selectors/pull/234)
[Failing CI run](https://travis-ci.org/simplabs/ember-test-selectors/builds/429585313?utm_source=github_status&utm_medium=notification)

**Comment by Turbo87** [comment]
@twokul did you have time to look into this?

**Comment by twokul** [comment]
@Turbo87 I did; let's discuss during next core meeting

**Comment by Turbo87** [comment]
I did a rudimentary bisect and this issue started appearing somewhere between v3.1.4 and v3.2.0-beta.1.

**Comment by Turbo87** [comment]
e93bdaef39865b7de42008b9ec975779e8491acb is the first bad commit
commit e93bdaef39865b7de42008b9ec975779e8491acb
Author: Alex Navasardyan <alex.navasardyan@gmail.com>
Date:   Tue Feb 27 11:40:36 2018 -0800

    Package Tests

**Comment by locks** [comment]
According to the linked PR this has been fixed.
