### ISSUE TITLE
Further livereload improvements

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#8073]
Recently we introduced livereload sharing the same port as the base pages http.

There is at-least one scenario that is quite important to many users. User wanting to utilize https://repl.it/ or https://glitch.com/ or similar architectures.

Briefly, that architecture is:

* HTTP Proxy -> ember-cli, where the HTTP Proxy servers the base page on a port that is different then what ember-cli serves it on.

The problem with our current approach we configure livereload explicity. Specifically the port is not inferred, but always configured. https://github.com/ember-cli/ember-cli-inject-live-reload/blob/21b5f6568fd1f59fa2ab416e7da01bd456d22f9b/index.js#L28

If we can allow the default live-reload configuration to be implicit rather then explicit, it could infer the port.

---

Improving this, would make ember-cli "just work" for the above architecture

**Comment by stefanpenner** [comment]
I believe, if we change the following code:
https://github.com/ember-cli/ember-cli-inject-live-reload/blob/master/index.js#L28

* To infer port from `location.port` if `options.port === options.liveReloadPort`
* to hard-code port if `options.port !== options.liveReloadPort`

**Comment by stefanpenner** [comment]
a more holistic solution would be:

1. [fork livereload-js](https://github.com/ember-cli/livereload-js) and apply https://github.com/livereload/livereload-js/pull/78
2. release the fork as `ember-cli-livereload-js`
3. update ember-cli [here](https://github.com/ember-cli/ember-cli/blob/284505b8f8caea192ee9134904078116214c15c1/lib/tasks/server/livereload-server.js#L126) to provide ember-cli-livereload-js as an option to tinylr
4. have ember-cli-inject-live-reload detect that it's version of ember-cli includes the above capability, and provide a simply/more resilient `src` for the injected script tag.

**Comment by stefanpenner** [comment]
@sparshithnr mind working on this this week?

**Comment by rwjblue** [comment]
FWIW - I believe (from a conversation with @mike-north in discord) that the same issue exists for codesandbox.com as well.

**Comment by stefanpenner** [comment]
@rwjblue ya it exists in a bunch of places, include our own internal proxy setup. I just spoke with @SparshithNR, he hopes to have this landed in the next few days.

**Comment by stefanpenner** [comment]
I think we are good
