### ISSUE TITLE
Assertion Failed: registerBoundHelper-generated

### ISSUE THREAD

**Issue by chrishough** [ember-cli/ember-cli#808]
Following this thread http://stackoverflow.com/questions/17095813/handlebars-if-and-numeric-zeroes I created the following helper named `var-exists.js` in the `app/helpers` directory:

```
export default Ember.Handlebars.makeBoundHelper(function(value, options) {
    if (typeof value !== 'undefined') {
      return options.fn(this);
    } else {
      return options.inverse(this);
    }
});
```

When I try to use this in an hbs view i.e. 

```
{{#var-exists myvar}}
  YES
{{else}}
  NO
{{/var-exists}}
```

I get error message:  

```
Uncaught Error: Assertion Failed: registerBoundHelper-generated helpers do not support use with Handlebars blocks.
```

**Comment by jackmatt2** [comment]
@chrishough Did you get anywhere on the block bound helper?  I have having the same issue as @chrishough.  Here is my helper

```javascript
export default function ifEqual(input1, input2, options) {
    var boundItem1 = Ember.Handlebars.get(this, input1, options);
    var boundItem2 = Ember.Handlebars.get(this, input2, options);

    if (boundItem1 === boundItem2) {
        return options.fn(this);
    } else {
        return options.inverse(this);
    }
}
```

and I am calling it with bound parameters

```javascript
        {{#if-equal movementPricing.vehicleTypeCode.id vehicleModel.vehicleTypeCode.id }}
            <div class="panel panel-success">
        {{else}}
            <div class="panel panel-primary">
        {{/if-equal}}
```

The issue is that when `movementPricing.vehicleTypeCode.id` or `vehicleModel.vehicleTypeCode.id` is updated, the code is not refreshed.

**Comment by chrishough** [comment]
It has been awhile since I looked at that code + ember upgraded significantly.  I may not be much help in answering that question at this time @jackmatt2.  @matt-morris do you have any thoughts on this by chance?

**Comment by alex88** [comment]
Seems you can't do that anymore, I mean, using custom block helpers with bound properties, isn't it?
