### ISSUE TITLE
Helper `Naming` issue

### ISSUE THREAD

**Issue by ashjackguo** [ember-cli/ember-cli#8082]
Ember version: 2.18
I ran into a weird issue with Naming for helpers causing errors when running unit test.

Steps to reproduce:
1. `ember g helper is-before`
2. using ember cli to generate a unit test for that helper.  `ember g helper-test is-before --unit`
3. Run `ember s` or `ember t` or `ember t -s`
4. Navigate to that unit test page
5. You should this error: 
```
TypeError: (0 , _isBefore.isBefore) is not a function

Source: | TypeError: (0 , _isBefore.isBefore) is not a function     at Object.<anonymous> (http://localhost:4200/assets/tests.js:2014:41)     at runTest (http://localhost:4200/assets/test-support.js:4164:30)     at Test.run (http://localhost:4200/assets/test-support.js:4150:6)     at http://localhost:4200/assets/test-support.js:4371:12     at advanceTaskQueue (http://localhost:4200/assets/test-support.js:3763:6)     at advance (http://localhost:4200/assets/test-support.js:3744:4)     at advanceTestQueue (http://localhost:4200/assets/test-support.js:3789:4)     at Object.advance (http://localhost:4200/assets/test-support.js:3747:5)     at begin (http://localhost:4200/assets/test-support.js:5769:20)     at http://localhost:4200/assets/test-support.js:5729:6
-- | --
```

It works with other names but doesn't with `is-before`.

**Comment by urHuckleberry1** [comment]
Nice

**Comment by locks** [comment]
This is expected because the helper blueprint no longer exports a named function.
The idea is that you should use a rendering (integration) test for testing a helper. If you need to refer to the logic without the helper wrapper, my suggestion is to write a module with said function and unit test that, and import it in the helper!
