### ISSUE TITLE
Missing modules when setting up new project

### ISSUE THREAD

**Issue by lmcardle** [ember-cli/ember-cli#8084]
After creating a new project, in the browser console, I am getting the error: `Error: Could not find module 'ember-compatibility-helpers' imported from '@ember/ordered-set/index'`

Steps to reproduce:
```
npm install -g ember-cli
ember new foo
cd foo
ember-serve
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.3
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
6.4.1
1.7.0
```

**Comment by rwjblue** [comment]
Hmm, thanks for reporting! 

@pzuraq / @snewcomer - Is this perhaps related to the ember-compatibility-helpers release today?

**Comment by locks** [comment]
I believe @rwjblue's assessment is correct.
I have patched `@ember/ordered-set` for now, thanks for reaching out!
