### ISSUE TITLE
Minor update of ember-cli-broccoli-sane-watcher is backwards incompatible

### ISSUE THREAD

**Issue by goldenice** [ember-cli/ember-cli#8090]
We are running version 2.x of `ember-cli` on node 4.8. In the `ember-cli-broccoli-sane-watcher` repository, a new minor release was released updating the `sane` dependency to 4.x up from 2.x. Since `sane` 4.x does not support node 4 anymore, `ember-cli` will not install anymore, even though we have pinned it to an older version.

As the update of `ember-cli-broccoli-sane-watcher` breaks backwards compatibility, in my opinion this should have been a major version bump. However, that is tricky to do now, since the update has been published and probably been installed many times. I propose that a new bugfix release of ember-cli@2 is made that pins the version of `ember-cli-broccoli-sane-watcher` explicitly to versions between 2.0.4 (current package.json specifies `^2.0.4`) and 2.1.1.

I'd be glad to submit a PR to do this. If you feel like such an update is not necessary, would you have any clue on how I could get yarn to install according to the ember-cli lockfile at version 2.18.2?

cc @stefanpenner

**Comment by goldenice** [comment]
By the way, this also seems to be the case for `testem` which went from `2.11.0` to `2.12.0` and it's subdependency `execa` which was updated from `0.11.0` to `1.0.0` and dropped support for node 4. 

Not every dependency update should cause a major version bump in the project that uses it, but if this is dropping support for a node engine, then that IS a backwards incompatible change.

**Comment by rwjblue** [comment]
> We are running version 2.x of ember-cli on node 4.8. In the ember-cli-broccoli-sane-watcher repository, a new minor release was released updating the sane dependency to 4.x up from 2.x. Since sane 4.x does not support node 4 anymore, ember-cli will not install anymore, even though we have pinned it to an older version.

As I’m sure you know, Node 4 is **completely** unsupported. I’d _strongly_ suggest that you update Node versions to a supported version as soon as possible. In addition, you should almost certainly be using a package management system (npm >= 5 or yarn) that properly pins dependencies such that the kind of drift that is affecting you here doesn’t happen. 

> As the update of ember-cli-broccoli-sane-watcher breaks backwards compatibility, in my opinion this should have been a major version bump. 

I definitely agree with this, but it seems like this issue belongs over in ember-cli-broccoli-sane-watcher. 

> I propose that a new bugfix release of ember-cli@2 is made that pins the version of ember-cli-broccoli-sane-watcher explicitly to versions between 2.0.4 (current package.json specifies ^2.0.4) and 2.1.1.

No ember-cli versions older than 3.4 (current release) are actually supported. It’s fairly unlikely that we would do a patch release of 2.18. 

> this also seems to be the case for testem which went from 2.11.0 to 2.12.0 and it's subdependency execa which was updated from 0.11.0 to 1.0.0 and dropped support for node 4.

Yep, I noticed this also (even commented on the PR/commit in testem). 

---

I am sorry that this is breaking your builds. I suggested above using a package manager to aid you, here is an example PR where I had to deal with these sorts of issues in a project that still supports Node 4 (so you can see how I was able to work around it):

https://github.com/emberjs/ember-test-helpers/pull/412

Hopefully this is helpful, good luck!

**Comment by rwjblue** [comment]
Hmm, why do you need to install anything globally?

**Comment by Turbo87** [comment]
@goldenice I ran into the same problem as you on several CI builds. I had opened https://github.com/ember-cli/broccoli-sane-watcher/issues/11 a few days ago and just now saw this issue here. As you can see in https://github.com/ember-cli/broccoli-sane-watcher/issues/11#issuecomment-429552234 we resolved the problem. v2.x should now be compatible with Node 4 again and we released the new changes as v3.0.0.

**Comment by goldenice** [comment]
@Turbo87 That's great news, thanks for that :+1:
