### ISSUE TITLE
Proxying backend requests using --proxy 

### ISSUE THREAD

**Issue by Romain-P** [ember-cli/ember-cli#8104]
Hi,

I'm running the latest ember version with `ember server --proxy=http://localhost:8080`
Nothing happens on the webservice logs (nor on ember console) when I'm trying to hit one endpoint e.g `http://localhost:4200/admin/login`. It should redirect it to `http://localhost:8080/admin/login`

Is there other needed configuration(s) to make it working?

**Comment by rwjblue** [comment]
Nope, shouldn’t be more needed other than the `--proxy` flag. 

Do you have any errors in the terminal? Can you try to create a reproduction?

**Comment by Romain-P** [comment]
I didnt specify that it’s not working when I click on a link. For some technical reasons, i have to call one of my backend endpoint without  Ajax (CAS logis). That’s why I created a simple link with <a href=/mybackendendpoint ...> but it seems thé proxy is not apply on that kind of call

**Comment by Romain-P** [comment]
I see, thank you

**Comment by clemlatz** [comment]
For anyone stumbling upon this thread like I did, I was able to achieve this with the command:

```shell
ember generate http-proxy api http://localhost:3000    
```

Unlike the `ember server --proxy` command, this generates a customizable development proxy server that also routes requests with the `accept: text/html` header (ie request from the browser when the user clicks a link).
