### ISSUE TITLE
Manually activating jQuery excludes it from tests

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-cli#8119]
I'm not quite sure where exactly to place this issue, I hope it is fine here.

Basically, I updated our app to ember-cli 3.4, and started to get the warning that I should explicitly add `@ember/jquery` to my package.json. I did this, and then also added `@ember/optional-features` and activated jquery there, so I had the correct file under `tests/dummy/config/optional-features.json`:

```
{
  "jquery-integration": true
}
```

(I am testing a lazy loaded engine here).

Now, my tests started failing with the error `Promise rejected during "XXX test name": this.$ is not a function`

Basically, all calls to `this.$()` in my tests stopped working. I'm not sure if this is supposed to be that way - if it is, I would say it is highly confusing.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.4.3
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: win32 x64
5.6.0
1.9.4
```

My engine's devDependencies (simplified):

```
 "devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.7.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-cli": "^3.4.0",
    "ember-cli-app-version": "~3.2.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "~1.0.2",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-qunit": "~4.3.1",
    "ember-cli-uglify": "~2.1.0",
    "ember-data": "^3.3.1",
    "ember-engines": "~0.5.1",
    "ember-export-application-global": "~2.0.0",
    "ember-load-initializers": "~1.1.0",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.1.0",
    "loader.js": "^4.7.0"
  }
```

**Comment by rwjblue** [comment]
This happened when testing locally or in CI?

**Comment by rwjblue** [comment]
What type of tests? Did you do anything other than update the ember-cli version when upgrading?

**Comment by mydea** [comment]
Both. All tests failed that used something like this:

```
 assert.equal(this.$().html().trim(), "greeting: <span>hello ember testing</span>");
```

Tests complained that `this.$()` is not defined. It works without adding `@ember/jquery` and activating it via `@ember/optional-features` (e.g. the default inclusion of jQuery), but once I add & activate it manually it stops working.

**Comment by rwjblue** [comment]
Can you double check to see which of these two things is happening:

1. jQuery is actually present but the testing harness doesn't expose `this.$`
2. jQuery is not present

**Comment by mydea** [comment]
So importing jquery works, but `this.$()` does not.

E.g. this works:

```
import $ from 'jquery';
```

Note: This is in a new-style test.

**Comment by crhayes** [comment]
I am having this issue as well. @mydea Were you able to fix this or did you just refactor all of your code to manually import jquery?

**Comment by crhayes** [comment]
@rwjblue I am having the same issue ATM. It appears that jQuery is not present, and so does not get added to the test harness.

Specifically, in `setupRenderingContext`, the following:

```js
if (_global.default.jQuery) {
  Object.defineProperty(context, '$', { value: jQuerySelector, writable: false });
}
```
is not working because `_global.default.jQuery` is `undefined`. Is there anything you can suggest off the top of your head to help fix this?

**Comment by crhayes** [comment]
For those who are interested, this issue manifested in my project because I was using an outdated version of `ember-cli-page-object`.

More details here: https://github.com/emberjs/ember-jquery/issues/8

**Comment by mydea** [comment]
I "solved" the issue by rewriting all our tests to stop using jQuery - which took quite some time but was due  at some time anyhow.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? With jQuery on its way out, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by rwjblue** [comment]
Ya, I think we can probably close this one. After this was opened, we deprecated `this.$` from within the test harness and the current version of `ember-qunit`/`@ember/test-helpers` does support it at all.
