### ISSUE TITLE
Improve build error logging

### ISSUE THREAD

**Issue by oligriffiths** [ember-cli/ember-cli#8121]
# What

Currently, when an error is encountered during a build, we write the error information to a temp file log, e.g.:
```
➜  ember-test git:(master) ember serve
Build Error (MyPlugin)

AHHH


Stack Trace and Error Report: /var/folders/g7/70cblrm11nx2g393qmjkkwkc0000gn/T/error.dump.0c6fb20d2f9c3cf255c57b684ec94929.log
open /var/folders/g7/70cblrm11nx2g393qmjkkwkc0000gn/T/
cleaning up...
```
See https://github.com/oligriffiths/ember-test for the test project

However, the content that is contained within the log is duplicated and kind of hard to digest, here's some examples:

[broccoli.log](https://github.com/ember-cli/ember-cli/files/2478376/broccoli.log)

(deprecated broccoli-builder log) `EMBER_CLI_BROCCOLI_2=false ember build`
[broccoli-builder.log](https://github.com/ember-cli/ember-cli/files/2478375/broccoli-builder.log)

# Improvements

I'm opening this issue to discuss the possible improvements to make debugging errors more easy to debug:

* improve the output in the CLI, as merely outputting the error message and the plugin name isn't wholly helpful imo.
* de-duplicate the log output, make the instantiation stack *not* just a string, but an object that can be enumerated
* copy the build temp directory output to somewhere persistent, and recreate the build pipeline with symlinks
* write a graphical representation similar to heimdall of the build pipeline and exactly where the error occured
* ... suggestions welcome

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.5.0
http_parser: 2.8.0
node: 10.0.0
v8: 6.6.346.24-node.5
uv: 1.20.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
5.6.0
1.10.1
```

**Comment by Gaurav0** [comment]
We can do much of this manually with broccoli-stew, maybe we just need someone to write a tutorial. ;)

**Comment by oligriffiths** [comment]
@Gaurav0 that doesn’t really help your average ember-cli user who gets an error in an addon they installed. Additionally I don’t think broccoli-stew is that user friends for really debugging an issue.

**Comment by stefanpenner** [comment]
I am very down for improvements in this space :)

**Comment by locks** [comment]
Some improvements have been done in the meantime and it is unlikely more development in this area will happen. Thank you everyone that helped out!
