### ISSUE TITLE
[3.5.0] "Directory not found" error due to some change in plugin order

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#8122]
[Here](https://github.com/boris-petrov/ember-cli-ordering-bug) is a repo to showcase the bug.

I'm actually not sure this is a bug or maybe we've been using it wrongly all along but in any case that broke from 3.4.3 to 3.5.0. The last commit downgrades from 3.5.0 to 3.4.3 and you can see `ember serve` running fine. If you checkout the previous commit, run `npm install`, `rm -rf tmp` and run `ember serve` you'll see it fail.

In the latest version, the `ember-cli-sass` plugin seems to be resolving its `includePaths` *before* the `ember-cli-webfont` plugin has run - hence the directory is not generated - and hence the build process fails with `Directory not found: tmp/iconfont-styles`.

Again, I'm not sure if this is a bug in `ember-cli` or something else, please give us any ideas.

**Comment by rwjblue** [comment]
The issue here _almost certainly_ is the migration to use Broccoli v2.0.0. This migration moves the various `tmp` dirs created by the build out of the project's own `tmp/` directory and into your default system temp dir.

You can confirm this by manually disabling the Broccoli 2 experiment and rebuilding:

```
EMBER_CLI_BROCCOLI_2=false ember s
```

**Comment by rwjblue** [comment]
After a quick dig into the repro, it looks like this worked before by instructing `ember-cli-webfont` to write the CSS (via `cssDest` option) _above_ its own temporary directory which just _happened_ to be the project's own `tmp/some-path`. This coupling is what is breaking and is directly related to the Broccoli 2 upgrade. 

The work around I provided above does work, but definitely should not be considered a long term solution (we will eventually remove support to fallback to broccoli@2). The right solution here is to do a bit of broccoli fu and wire up the output tree from ember-cli-webfont directly with the sass compilation. FWIW, this will also remove a race condition situation in your project (today multiple concurrent builds will "fight" for the "well known path" `tmp/iconfont-styles`).

**Comment by rwjblue** [comment]
At least one reason using an absolute path doesn’t work is that ember-cli-webfont does something like:

    webfontOptions.cssDest = path.join(this.outputPath, options.cssDest);

Which will end up with a string like `/tmp/some/absolute/path/some/other/absolute/path` and won’t be valid. You could try to remove that when the incoming path is absolute (seems reasonable), but that doesn’t completely fix the issues anyways (still has the same resource contention / race condition scenario I mentioned above).

**Comment by rwjblue** [comment]
> Can you elaborate on what you mean by The right solution here is to do a bit of broccoli fu and wire up the output tree from ember-cli-webfont directly with the sass compilation?

I’m not too familiar with all of the pieces in the pipeline, but I’d say a rough example (typed on mobile so sorry for typos) is:

```js
const WebfontPlugin = require(‘ember-cli-webfont/lib/utils/webfont’);
const SassPlugin = require(‘broccoli-sass’); // whatever ember-cli-sass uses internally, I can’t recall


let webfont = new WebFontPlugin(‘app/iconstyles’)

let app = new EmberApp(defaults, {
  trees: {
    styles: new MergeTree([‘app/styles’, webfont]),
  }
});
```
 This basically wires the webfont up to your normal styles compilation pipeline...

**Comment by boris-petrov** [comment]
OK, so in the end we patched `ember-cli-webfont` like so:

https://github.com/joankaradimov/ember-cli-webfont/commit/a456fcd56f2b806b1e3e4fc14b60c297b229d26c

And this seems to do the job. We've opened a PR in `ember-cli-webfont` and hopefully that will be the end of it. Thanks for the support! I'll close the issue now.

**Comment by rwjblue** [comment]
Awesome, glad you were able to work through it.
