### ISSUE TITLE
Fix addon styles concatenation

### ISSUE THREAD

**Issue by raghuvaran** [ember-cli/ember-cli#8133]
In 'MODULE_UNIFICATION' project, styles are added under `src/ui/styles`.

However, addons add their styles under `app/styles/`, which are not being copied to `src/ui/styles` and this is resulting in no stylesheet files in the final build.

**Comment by NullVoxPopuli** [comment]
I *think* this should be a concern of ember-cli, as app/styles should be detected, and merged with src/ui/styles just by convention.

Still good to track progress on this issue though.

**Comment by ppcano** [comment]
#8289 has fixed this issue and it can be closed now.

**Comment by rwjblue** [comment]
Thank you @ppcano!
