### ISSUE TITLE
Entry module not found: Error: Cannot resolve module 'b2a'

### ISSUE THREAD

**Issue by ivanhueso** [ember-cli/ember-cli#8140]
Hi,
I have tried to upgrade to the ember 3.5 from 3.1 and got this error when trying to serve or build:

```
Entry module not found: Error: Cannot resolve module 'b2a' in /var/folders/4p/8vv12p693l94nh1hb1p4_prh0000gn/T/broccoli-11191fg9vjgrw6PCA/out-078-funnel
resolve module b2a in /var/folders/4p/8vv12p693l94nh1hb1p4_prh0000gn/T/broccoli-11191fg9vjgrw6PCA/out-078-funnel 0 [ 'Entry module not found: Error: Cannot resolve module \'b2a\' in /var/folders/4p/8vv12p693l94nh1hb1p4_prh0000gn/T/broccoli-11191fg9vjgrw6PCA/out-078-funnel\nresolve module b2a in /var/folders/4p/8vv12p693l94nh1hb1p4_prh0000gn/T/broccoli-11191fg9vjgrw6PCA/out-078-funnel' ]
Build Error (WebpackWriter)

null


Stack Trace and Error Report: /var/folders/4p/8vv12p693l94nh1hb1p4_prh0000gn/T/error.dump.e7d62d636ca767096f4bb9893ea1962a.log

```

**Comment by Turbo87** [comment]
@ivanhueso it looks like you're using some addon in your build pipeline that is using Webpack internally. can you check what addon that might be? are you using `ember-auto-import` for example?

**Comment by nickschot** [comment]
I am also seeing this on a newly generated 3.5 app w/ just ember-cli-fastboot and ember-cached-shoe. Seeing as b2a is a dep of ember-cached-shoe, I think it is caused by this addon.

**Comment by ivanhueso** [comment]
I've removed ember-cached-shoe and it works! Thank you!
