### ISSUE TITLE
expected container not to be destroyed

### ISSUE THREAD

**Issue by brancusi** [ember-cli/ember-cli#8148]
Test error: `expected container not to be destroyed`

I can't reproduce this exactly. It will happen sometimes locally, sometimes on travis, most of the time on travis, but repeat builds will sometimes pass.

Here's running the same test several times, it will randomly fail on 1 usually.

Here's the test: https://github.com/brancusi/juice-core/blob/aramzadikian/ch45/bump-to-ember-5/tests/acceptance/login-test.js

Here's a passing build, and this same build restarted will mostly fail.
https://travis-ci.org/youpressed/juice-core/builds/444900579

Any ideas?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.5.0
http_parser: 2.8.0
node: 6.14.4
v8: 5.1.281.111
uv: 1.16.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
napi: 3
openssl: 1.0.2p
os: darwin x64
3.10.10
1.10.1

```

**Comment by kiwiupover** [comment]
What versions of ember-data and ember-href-to are you using?

**Comment by brancusi** [comment]
@kiwiupover, from yarn.lock
```
ember-source@~3.5.0:
  version "3.5.0"
  resolved "https://registry.yarnpkg.com/ember-source/-/ember-source-3.5.0.tgz#2322e393125684e1e043d0eedad8fd79c6de78a8"
  ```

ember-href-to: I didn't even know about this, doing a search through node_modules, looks like 3 packages use it and they are point to 1.15.1

1. ember-power-select
2. ember-copy
3. ember-basic-dropdown

Just to play, I will try to rip those out and see if anything happens. 

I've also try ember 3.4 and 3.3, but I may do another pass in case I missed something. Do you see anything with the way I setup the test that is a red flag?

With the new testing system, do I need to be tearing down anything in the afterEach hook?

The repo: https://github.com/youpressed/juice-core

Thank you

**Comment by myfashionhub** [comment]
Running into the same issue. For me it seems like there're unrelated console errors when running locally. But on the CI I get that error.

**Comment by locks** [comment]
I haven't found recent mentions of this specific error so I'm closing the issue. Thanks for filing an issue!
