### ISSUE TITLE
3.5.0 - random funnel failure on windows

### ISSUE THREAD

**Issue by Kilowhisky** [ember-cli/ember-cli#8153]
Ever since the 3.5.0 upgrade my team of 3 developers keeps randomly having the following error.

```
file changed pods\portal\operations\routes\edit\route.js
Build Error (Funnel)

ENOENT: no such file or directory, scandir 'C:\Users\CCF88~1.RIC\AppData\Local\Temp\broccoli-9584wNx8qEGDY4tL\out-004-broccoli_merge_trees_empty_merge_tree'


Stack Trace and Error Report: C:\Users\CCF88~1.RIC\AppData\Local\Temp/error.dump.077aff15ce9a9adf50ab6c6031df59eb.log
```

It only happens on windows and happens when a file has been changed. It also seems to happen without any cause. When this occurs there is no way to recover other than killing `ember s`, deleting the `tmp` dir. and restarting `ember s`. 

Attached is the dump file referenced before. Here is the output from ember -v

```
ember-cli: 3.5.0
node: 8.11.4
os: win32 x64
```

Also attached is the list of packages installed from an output of `yarn list -g --depth=0`

[packages.txt](https://github.com/ember-cli/ember-cli/files/2516881/packages.txt)

[error.dump.077aff15ce9a9adf50ab6c6031df59eb.log](https://github.com/ember-cli/ember-cli/files/2516871/error.dump.077aff15ce9a9adf50ab6c6031df59eb.log)

**Comment by locks** [comment]
Is this still an issue with current releases?

**Comment by Kilowhisky** [comment]
Haven't been able to get onto the latest release as `ember-data` won't let me upgrade. I do seem to get the problem on `3.14` which is the farthest i got to. But at this point it only seems to happen when adding / deleting files.

**Comment by bertdeblock** [comment]
Cleaning up some old issues...
Please reopen if this is still an issue for new projects.
