### ISSUE TITLE
instanceof with ember-data models not working as expected

### ISSUE THREAD

**Issue by sheldonbaker** [ember-cli/ember-cli#816]
Apologies if this is more specific to https://github.com/emberjs/ember.js, but here goes:

I replicated this on a fresh ember-cli project (but couldn't replicate on a 'normal' ember project (see http://emberjs.jsbin.com/loviqozo/1/edit)):

```
// app/models/fruit.js
var Fruit = DS.Model.extend();
export default Fruit;

// app/models/banana.js
import Fruit from 'app/models/fruit';
var Banana = Fruit.extend();
export default Banana;

// app/routes/index.js
var banana = this.store.createRecord('banana');
var fruitClass = this.store.modelFor('fruit');

alert(banana instanceof fruitClass); // false
```

Currently this prevents me from using polymorphic relationships in ember-data, for example.

**Comment by gitowiec** [comment]
What to distable? The url is outdated! @stefanpenner please could you write more?
