### ISSUE TITLE
Add Node 11 support

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#8161]
I'm having numerous issues with Node.js 11.0.0. For example, running `ember test` seems to "block" in the console - the browser runs all tests but in the console it logs only some of them and then stops. It doesn't close the browser. And CTRL+C doesn't kill it - I have to do a `kill -9`. I know it says that Node 11 is unsupported but just to give you a heads up and to ask what's the status on this?

**Comment by rwjblue** [comment]
AFAIK, we haven't tested Node 11 yet. First step is probably adding it to CI here and see what breaks...

**Comment by boris-petrov** [comment]
Just some heads up - updating `node-sass` seems to have fixed the issue and `Ember CLI` seems to work fine with Node 11.

**Comment by boris-petrov** [comment]
This issue is a duplicate of https://github.com/ember-cli/ember-cli/issues/8301 so I'll close it.
