### ISSUE TITLE
ember-new-output#master is missing 3.5.0 (stable), 3.4.1, 3.4.2, 3.4.3

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-cli#8168]
The tags exist, but the master branch seems to be behind.

![screen shot 2018-11-05 at 3 11 30 pm](https://user-images.githubusercontent.com/558005/48032589-194b7480-e10d-11e8-9ddd-a27f6c7690b8.png)

**Comment by kellyselden** [comment]
This is correct. 3.5.0 is on the stable branch. There is no 3.6 beta yet, that is why master is out of date.
