### ISSUE TITLE
[Discussion] code coverage for ember-cli's own codebase

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#8169]
I was poking around with [c8](https://github.com/bcoe/c8), my goal was to understand how v8's built-in coverage tooling worked, and one of my experiments was to run it on ember-cli.

### My findings:

* 👍 no more code-mangling 
* 👍 more or less just worked
* 👍 code coverage
* 👎 slows test suite time down (2m `yarn test` took 4m)
   * https://cs.chromium.org/chromium/src/v8/src/debug/debug-coverage.cc?l=605&rcl=8c9f5ca80b39c4ef7b71f3216e49537e0b7bc147 in non best-effort mode will deopt everything + use more memory. best-effort mode (i should experiment with) but may loose information due to GC, and I believe wont collect anything beyond function granularity.

### My Questions:

* Given this does slow down test, do we want to proceed? Does the larger team find this of value?
* If perf is a concern should we provide `test:coverage` and `test:all:coverage` tasks for custodial work, but not part of CI?
* .... ?

### Some related links:

* https://v8.dev/blog/javascript-code-coverage
* https://github.com/bcoe/c8

##### Note:

*I am also thinking of creating a new testem runner that uses https://github.com/tracerBench/chrome-debugging-client + v8-to-istanbul to create form test coverage from our UI test runs, I believe this also requires fixing up source-maps...*

**Comment by locks** [comment]
Closing as stale.
