### ISSUE TITLE
Ensure ember-new-output#master never falls behind #stable

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-cli#8172]
Inspired by #8168 

#### Why does this matter?

The community-maintained web-based editors (i.e., codesandbox.io) should create new "apps" based on some official source of truth so that we don't incur additional maintenance costs as we add ember support to similar tools.

Especially for "reproduce this bug" cases, it's important to be able to reliably create new apps based on the latest "beta channel" code -- currently ember-new-output#master is not in alignment with this need

#### What's the cause of the problematic state?

Very rarely, a new stable release of ember/ember-cli is cut without cutting a beta of the following version. In this situation the source of truth for the output of the [`ember new` command](https://github.com/ember-cli/ember-new-output) gets into a wierd state where the "beta channel" has older code than the "stable channel".

#### What needs to be done?

https://github.com/ember-cli/ember-cli/blob/b52ce2e2614a08cf3c8690d668677900e523e383/dev/add-to-output-repos.sh#L38-L43 

will need to be updated to have different behavior in the event that the beta commit is behind (older than) the stable commit

**Comment by Turbo87** [comment]
> will need to be updated to have different behavior in the event that the beta commit is behind (older than) the stable commit

sounds good. do you have time to work on a PR to fix this?

**Comment by kellyselden** [comment]
Would this be better solved by making sure we release a new beta when we turn old beta into stable? Seems like that's where the problem lies, not with adding a workaround to this script.

**Comment by mike-north** [comment]
> Would this be better solved by making sure we release a new beta when we turn old beta into stable? Seems like that's where the problem lies, not with adding a workaround to this script.

This seems far more intuitive from the standpoint of consuming ember-new-output. I see no advantage whatsoever in allowing master to fall behind.

**Comment by NullVoxPopuli** [comment]
Is there a release script somewhere?
maybe we just add the tags `latest-beta` and `latest`, and then update the output repos based off those tags?

**Comment by NullVoxPopuli** [comment]
This is resolved via: https://github.com/ember-cli/editor-output/branches

which currently only has branches being created for stackblitz.
to support codesandbox-specific configs, we'll want to 
 - add to this array: https://github.com/ember-cli/ember-cli/blob/master/dev/update-output-repos.js#L22
 - add a folder here: https://github.com/ember-cli/ember-cli/tree/master/dev/online-editors for editor-specific config
 - and then update codesandbox's url/pointer thing to point at the new branch, similar to what we do for stackblitz: https://stackblitz.com/github/ember-cli/editor-output/tree/stackblitz-app-output

**Comment by locks** [comment]
Thanks for the update!
