### ISSUE TITLE
Tree returned from `ember-cli-build.js` no longer reaches `dist`

### ISSUE THREAD

**Issue by jacobq** [ember-cli/ember-cli#8176]
I'm not sure exactly what is going on here, but when I try to upgrade from ember-cli 3.4.3 to 3.5.0 my icons (from `@mdi/font`) stop working. The files needed are currently being returning in `ember-cli-build.js`. Reproduction can be seen in [jacobq/e-icon-bug-repro](https://github.com/jacobq/e-icon-bug-repro) 

If the method used below is no longer valid/supported/whatever, what is the new/supported/recommended/alternative approach?

```js
// ...
const Funnel = require('broccoli-funnel');
module.exports = function(defaults) {
  // ...
  const mdiFont = new Funnel('node_modules/@mdi/font/fonts', {destDir: './assets/fonts'});
  return app.toTree([mdiFont]);
};
```

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.5.0
http_parser: 2.8.0
node: 11.1.0
v8: 7.0.276.32-node.7
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 67
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
os: linux x64
6.4.1
1.12.1
```

Note that this also happens with node 10.x though. It works fine if ember-cli v3.4.3 is used instead of 3.5.0.

**Comment by jacobq** [comment]
Could this be related to moving to broccoli 2.0?

**Comment by boris-petrov** [comment]
@jacobq - I think this is a duplicate of https://github.com/ember-cli/ember-cli/issues/8128 which has been fixed but still hasn't been released.

**Comment by jacobq** [comment]
Ah, so it is. Sorry, I didn't see that issue when I created this one.
