### ISSUE TITLE
[3.5.0] broccoli-asset-rev doesn't change the hash of a file even when the contents change

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-cli#8178]
[Reproduction repo](https://github.com/boris-petrov/ember-cli-asset-rev-bug)

Pretty horrible bug. Steps:

1. Checkout the repo.
2. Run an `ember build --environment=production`.
3. Apply any modification to `app.css` - e.g. change `.x` to `.y`.
4. Run an `ember build --environment=production` again.

Notice that in steps 2 and 4 the JS file has the same hash - `dist/assets/ember-cli-asset-rev-bug-4a1c02c83345a2463dd229536adc6f88.js`. However, the contents are different, as they contain a reference to the `dist/assets/ember-cli-asset-rev-bug-*.css` file inside it.

We'll be changing the JS whenever we change some CSS to workaround this for now until this is fixed (hopefully soon).

**Comment by Turbo87** [comment]
this is unfortunately a known bug in broccoli-asset-rev (https://github.com/rickharrison/broccoli-asset-rev/issues/29). do you have time to tackle the issue?

closing in favor of https://github.com/rickharrison/broccoli-asset-rev/issues/29
