### ISSUE TITLE
Why running lint commands before ember test ?

### ISSUE THREAD

**Issue by BnitoBzh** [ember-cli/ember-cli#8199]
https://github.com/ember-cli/ember-cli/blob/e02ec00543195ecddf475319273519f40f3d8bef/blueprints/app/files/.travis.yml#L33-L35

`ember test` command already runs `lint:js` and `lint:hbs` during the tests
I think these two lines (L33 and L34) are not necessary

**Comment by Turbo87** [comment]
> `ember test` command already runs `lint:js` and `lint:hbs` during the tests

why do you think so?

are you aware of https://github.com/ember-cli/rfcs/pull/121?
