### ISSUE TITLE
Consider adding @ember/test-helpers to default app & addon blueprints

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#8201]
As part of our overall movement toward shipping real NPM packages for each of the modules people import into their apps, one small and easy step would be to add `@ember/test-helpers` to the default `devDependencies` of a new app or addon.

This is a case where people have already done the work to make it a real standalone NPM package, but we are still relying on inclusion by side effect (`ember-qunit` depends on` @ember/test-helpers`), rather than a straightforward dependency.

The major difference is that (1) NPM package hoisting isn't ever guaranteed, so `@ember/test-helpers` may sometimes not be resolvable from your app, therefore (2) general code analysis tools (editors, Typescript, general-purpose Javascript packagers) won't necessarily be able to tell you much about the package.

I would suggest making `@ember/test-helpers` a peerDependency of `ember-qunit` so that it never has a version that doesn't match the one the app has. This probably requires a major version bump for `ember-qunit`.

If people like this idea I can make the PRs. I'm opening this issue because I don't believe this rises to the level of an RFC, because we already ship `@ember/test-helpers` in the default blueprint, this is a just a question of the implementation details of how.

**Comment by kellyselden** [comment]
I think this is a good idea.

**Comment by rwjblue** [comment]
seems fine to me

**Comment by Turbo87** [comment]
does the same apply to the `qunit` and `mocha` dependencies?

**Comment by ef4** [comment]
It does, but I would rather not rush those, because they aren’t ember-addons and aren’t truly importable unless we also add auto-import, which is a bigger design job.

**Comment by bertdeblock** [comment]
👋 Think this can be closed?
