### ISSUE TITLE
Linting errors in Travis is not preventing additional tests.

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#8245]
Looks like we have an issue where the linting in Travis is not stopping the script. https://travis-ci.org/ember-cli/ember-new-output/builds/441565040

The Ember tests should not have run with this lint failure.

**Comment by Turbo87** [comment]
@kellyselden not sure I understand. that is expected behavior for TravisCI. it will run all the commands in `script` no matter if the previous ones have failed or not. why do you think that that's a problem?
