### ISSUE TITLE
chrome tests hang if jquery is required but ember-jquery missing

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#8247]
1. Install an addon that requires jquery (e.g. `ember-spectrum-color-picker`)
2. Do not install `ember-jquery`

`ember test` (chrome headless) hangs on completion, after logging the `ReferenceError` to the console. This breaks CI runs.

3. `ember install ember-jquery`

`ember test` no longer hangs on completion.

`ember test` should never hang - instead it should quit with an error so that CI can flag this.

**Comment by locks** [comment]
I believe this is no longer relevant as we're kicking ember-jquery to the curb. Let us know otherwise!
