### ISSUE TITLE
Build Error (UglifyWriter)  'return' outside of function

### ISSUE THREAD

**Issue by mapeveri** [ember-cli/ember-cli#8251]
After run `embe build --environment=production` i have this issue:

```
Build Error (UglifyWriter)

'return' outside of function


Stack Trace and Error Report: /tmp/error.dump.b30ea78b6371081667862a3904960ded.log
```

With ember build, I do not have this problem.

**Comment by rwjblue** [comment]
Something in your codebase is invalid and throws an error when minified. Presumably the stack trace points you to more information about the error.


The reason it doesn't happen with `ember build` is that we don't run minfication there by default.

**Comment by mapeveri** [comment]
Hi @rwjblue, I understand. And how could I detect the error in my code?. Thanks!!

**Comment by locks** [comment]
We have switched from Uglify to Terser. Hopefully nowadays you get a better error message!

**Comment by csprocket777** [comment]
Just got this today after searching for a solution:
```sh
Build Error (TerserWriter)

'return' outside of function

Stack Trace and Error Report: /var/folders/g1/pkdwgwq57135gknzdvy_h0tr0000gn/T/error.dump.accae8da8d25920654632765fface5cd.log
```

```json
    "ember-auto-import": "^2.4.2",
    "ember-cli": "~4.7.0",
    "ember-cli-app-version": "^5.0.0",
    "ember-cli-babel": "^7.26.11",
    "ember-cli-code-coverage": "^1.0.3",
    "ember-cli-dependency-checker": "^3.3.1",
    "ember-cli-htmlbars": "^6.1.0",
    "ember-cli-inject-live-reload": "^2.1.0",
    "ember-cli-sass": "^11.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-string-helpers": "^6.1.0",
    "ember-cli-terser": "^4.0.2",
    "ember-cli-typescript": "^5.1.1",
    "ember-cli-typescript-blueprints": "^3.0.0",
 ```

**Comment by NullVoxPopuli** [comment]
`return` outside of a function isn't valid javascript, so it's likely one of your libraries is causing will need to be updated, patched, or PR'd to.

- [babel](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=E4UwLgrsB2Q&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.8&externalPlugins=&assumptions=%7B%7D) (what we use)
- [TypeScript](https://www.typescriptlang.org/play?#code/E4UwLgrsB2Q)
- [SWC](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAytKLSktyrMGAAeFEfMHAAAA&config=H4sIAAAAAAAAA31VPY%2FbMAzd71cEmjsUGTp0vivQIehQ4FZBsShHV1kyRCqXIPB%2FLy07H5fQ2Sw%2BPlLix%2FPpZbVSH9ion6sTf%2FKhNxkhX85swWMkc2CLomMP2GTfk%2Fp2RglHyJmAUE3DhCgyuQUaWYDr7%2Bv1zFAhJYQzY7Z1Pnp3vM3ZpK7PgHhjYyuHLB1Ewq%2F8GcvpcwQol1v7NqUAJj5BtEHtI0ELWQrcpBBMj6D3JgtRxpua7DFJKUawEFjd59SLeLSefIqc8xG1YKxukgUB8hka8nuQaJyLaRH5ecJ7KmxhW9q29vmODXsTiiEhJxxqS%2Fi2QtRd8kjalSiVcAIXajCBc3Hvmd7pDFRyfOR9JB8XevIPgCsQDGI0HUhxq4fjeVpiu6dMHx2PLB0FnOdbemWElouqvXdCZcfKQCYvdTODLQ2MlW2k68zwQvnQW9DgHM%2BKEBo%2FPTU7Kem46MkJAPfXOGmqJkBftnABHxfiCfyLX0nygM0enaHdMorHbpvCkwQd0C7ZJw7cCkrLcGaVOPTLeIkWeDTAii4FK%2FAoArwAlHSoevkwG7weHFG3IW2vMjE7DBcd7kxs7%2Ff9osWZZc6l3H2VWE67SbaEOgEndU1wUlUf6tfvv%2Fr17V1v%2Fry%2BjWJeo6thGKYEL3MS1dVA19%2FIOEGT%2BP9QV6ezzl%2FuqDxuzsz6rOE%2FQnOQmpIGAAA%3D)
