### ISSUE TITLE
ember new ember-quickstart - cause "Invalid Version" error

### ISSUE THREAD

**Issue by oracle1wr** [ember-cli/ember-cli#8276]
just trying to run "ember new ember-quickstart" to create a new app but getting back an error (with no much error details).

This is console output:
```
Error creating new application. Removing generated directory `./ember-quickstart`
Invalid Version: 
```

This is complete log from a report file:

```
ENV Summary:

  TIME: Mon Dec 10 2018 21:25:22 GMT-0800 (Pacific Standard Time)
  TITLE: ember
  ARGV:
  - /snap/node/1400/bin/node
  - /home/psyscout/.npm-global/bin/ember
  - new
  - ember-quickstart
  EXEC_PATH: /snap/node/1400/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /usr/local/cuda/bin
  - ~/.npm-global/bin
  - /home/psyscout/bin
  - /home/psyscout/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/psyscout/workspace/apps/tomcat/current/bin
  - /home/psyscout/workspace/apps/maven/current/bin
  - /home/psyscout/workspace/apps/ide/idea/current/bin
  - /home/psyscout/workspace/apps/java/1.8/current/bin
  - /home/psyscout/workspace/apps/dlang/dmd/current/dmd2/linux/bin64
  PLATFORM: linux x64
  FREEMEM: 476246016
  TOTALMEM: 67495698432
  UPTIME: 89653
  LOADAVG: 0.41259765625,0.5400390625,0.701171875
  CPUS:
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3375
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3268
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3290
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3478
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3442
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3490
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3485
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 3488
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.14.1
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.36
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Invalid Version:
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Invalid Version:
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Invalid Version:
    at new SemVer (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/semver/semver.js:312:11)
    at outside (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/semver/semver.js:1257:13)
    at Function.ltr (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/semver/semver.js:1246:10)
    at npm.then.result (/home/psyscout/.npm-global/lib/node_modules/ember-cli/lib/tasks/npm-task.js:66:28)
    at tryCatcher (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
WARNING: 
WARNING: /home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/ember-cli-broccoli-sane-watcher/node_modules/sane:
WARNING:    Missing dependency 'fsevents'
WARNING: 
WARNING: /home/psyscout/.npm-global/lib/node_modules/ember-cli/node_modules/sane:
WARNING:    Missing dependency 'fsevents'
ember-cli: 3.4.1
http_parser: 2.8.0
node: 10.14.1
v8: 6.8.275.32-node.36
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: linux x64
6.4.1
1.12.3

```
run "npm cache clean && bower cache clean", reinstalled "SemVer" doesn't help.
 
Any clue what I'm doing wrong or how to make it working?

**Comment by Turbo87** [comment]
@oracle1wr can you check if this is still a problem with the latest Ember CLI release?

**Comment by oracle1wr** [comment]
@Turbo87 installed 3.5.1, same issue.

**Comment by Turbo87** [comment]
I've tried to reproduce this, but it seems to work fine for me. Can you run this command using a debugger, set a breakpoint at `ember-cli/lib/tasks/npm-task.js:66` and check what the value of the `version` variable is?

**Comment by oracle1wr** [comment]
version is empty
![ember_new1](https://user-images.githubusercontent.com/10953868/50068600-67777d00-017b-11e9-83b0-a30e9610d522.png)

but >> "npm  --version" in console returns "6.4.1"

**Comment by Turbo87** [comment]
hmm, interesting. It sounds like EmberCLI does not have access to `npm` for some reason. can you check the value of `result.stderr` in that state? maybe that will give a clue on what's wrong 🤔 

is there a particular reason why you're using that snap package? I use https://github.com/creationix/nvm to manage my node versions and it usually works quite well.

**Comment by oracle1wr** [comment]
yeah, result.stderr is also empty, it looks wired. 
So I decided to reinstall node using "nvm" and after that I got it working. 

Thanks, @Turbo87 for the help.

**Comment by openhouse** [comment]
I had this same issue trying to install ember on my friend's computer which is running MacOS 10.11.6.  In `ember-cli/lib/tasks/npm-task.js` `this.npmVersion` is undefined on [line 165](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js#L165).  **Setting this value manually allowed ember to create a new project**. (yes! But not a real fix.)

I know this OS is out of date, but I'm not able to update it for them.  I tried uninstalling and reinstalling node via homebrew, node's installer from their website, and multiple version from latest to boron with NVM.  In all cases I still had the issue.

I'm not sure where `this.npmVersion` gets set, but I could look into it and see if I can get it to set properly on this machine.  I'll post any updates.

Let me know if you have any pointers.

**Comment by rwjblue** [comment]
@openhouse the issue you were hitting is being tracked in https://github.com/ember-cli/ember-cli/issues/8458, there is a PR open to fix which we will land ASAP.
