### ISSUE TITLE
Use TravisCI for Windows tests

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#8310]
We would like to migrate away from AppVeyor and use TravisCI instead.

There are currently two major blockers:

- secret variables are causing issues (https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264)
- Chrome does not run, which means testem will fail (https://travis-ci.community/t/puppeteer-not-working-on-windows-container/354)

/cc @backspace

**Comment by backspace** [comment]
Hey, I didn’t have any success getting feedback on the internal issue I opened about Chrome. I’ll try to track someone down to ask them directly when I’m back from winter break.

**Comment by backspace** [comment]
I can’t get anyone to make a public comment on this, I’m sorry. It’s shameful to me to have nothing to share but it’s not something I’m close to.

At least regarding Chrome, the thread has been [updated](https://travis-ci.community/t/puppeteer-not-working-on-windows-container/354/3) and it appears that it can work now?

**Comment by Turbo87** [comment]
> At least regarding Chrome, the thread has been [updated](https://travis-ci.community/t/puppeteer-not-working-on-windows-container/354/3) and it appears that it can work now?

that's good news :)

I guess without support for the secret vars we can't use it yet though 😢

**Comment by backspace** [comment]
yeah, to me, shipping without support for environment variables means this amounts to a toy rather than a useable product, but it’s not something I can fix myself 😞

**Comment by Turbo87** [comment]
I see. thanks for asking anyway! ❤️

**Comment by Turbo87** [comment]
given the latest developments at TravisCI I guess we can close this issue and look for other alternatives... 😞
