### ISSUE TITLE
Document (and implement?) usage of `test-support` and `addon-test-support` folders in Module Unification addons

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli#8342]
It is not clear how to use `test-support` and `addon-test-support` folders in addons leveraging Module Unification project structure.

This PR may be related: https://github.com/ember-cli/ember-cli/pull/8314

CC @ppcano

**Comment by locks** [comment]
Module unification has been dropped. Thanks for the discussion!
