### ISSUE TITLE
Link-to broken in 3.7.0

### ISSUE THREAD

**Issue by villander** [ember-cli/ember-cli#8355]
After updated my app to 3.7.0, I have this warning on `ember s`

My `router.js`

```js
Router.map(function() {
  this.route('index', { path: '/'});

  this.route('merchant', function() {
    this.route('dashboard');
    this.route('transactions');
    this.route('virtual-terminal');
    this.route('batches');
    this.route('users');
  ....
```

I have this error, but `merchant.virtual-terminal` don't have dynamic segments. 

```
Assertion Failed: You attempted to define a `{{link-to "merchant.virtual-terminal"}}` but did not pass the parameters required for generating its dynamic segments. Class constructor ComputedProperty cannot be invoked without 'new'
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.7.0
http_parser: 2.8.0
node: 8.11.4
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
```

**Comment by villander** [comment]
cc: @rwjblue @Turbo87

**Comment by Turbo87** [comment]
can you try to create a minimal reproduction repository that we can check out?

**Comment by James1x0** [comment]
@villander For me this ended up being a bug in ember-concurrency. Bumping my patch version to the latest fixed it.

**Comment by rwjblue** [comment]
> Class constructor ComputedProperty cannot be invoked without 'new'

this is the underlying issue as @James1x0 mentioned the most common case of this error is fixed by upgrading to the latest ember-concurrency

Closing for now as I don't believe this is an actual bug here...

**Comment by villander** [comment]
thank you so much @rwjblue @James1x0
