### ISSUE TITLE
CLI option to specify ember version

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#8380]
```bash
ember new my-app --ember-version 2.18
```

This would be a nice API to have. It could be broken down to `--ember-source` and `--ember-data` options as well.

**Comment by stefanpenner** [comment]
Currently, we ensure all dependencies bundled work with each other, if we allowed overriding such as this, I am not sure how we can ensure we create valid/working apps.

**Comment by mehulkar** [comment]
Would it be possible to use a different blueprint based on these flags?

(I’m handwaving on “blueprint” terminology, I don’t actually know in detail how “ember new” works)

**Comment by stefanpenner** [comment]
@mehulkar ya, you can fully customize this via blueprints already, so in theory if someone created the ember-2-18 blueprint, you could do `ember new -t ember-2-18` and it would "just work"

**Comment by stefanpenner** [comment]
In theory someone could grab the blueprints bundled with ember-cli, from those versions and publish them separately to NPM.

Although I would love to provide (And support those) I'm not sure we have the free cycles to do so. But this could easily be a community project.

**Comment by mehulkar** [comment]
Are the blueprints tied to a git tag right now? It seems like with a little refactoring, all blueprints could live in the project simultaneously and the default could be set to the latest. Not sure why it would need to live in a new NPM package, especially if we're only talking about the package.json blueprint.

**Comment by locks** [comment]
My suggestion is to use `npx` to generate a project for a specific Ember version, or `volta` to manage global ember-cli install and use those.
