### ISSUE TITLE
Newest `ember-cli-inject-live-reload` causes deprecation

### ISSUE THREAD

**Issue by btecu** [ember-cli/ember-cli#8391]
Steps to reproduce:
- create new ember application
- update `ember-cli-inject-live-reload` to version `2.0.1`
- run `ember s` and open the browser

![image](https://user-images.githubusercontent.com/7517745/51932413-25be3100-23cd-11e9-8f72-115247953e9a.png)

**Comment by btecu** [comment]
Same warning with version `1.10.2`.

**Comment by locks** [comment]
I think this is no longer relevanat. Let us know if otherwise!
