### ISSUE TITLE
no such file or directory, lstat 'C:\runtime.js'  while using Electron-forge

### ISSUE THREAD

**Issue by Zankhna95** [ember-cli/ember-cli#8413]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
[Replace this line with the output.]
```

**Comment by Turbo87** [comment]
@Zankhna95 can you add more details to this issue? what are you trying to do and how? without such information, this will be impossible to fix.
