### ISSUE TITLE
Can't build project due to the error "Skipping remote @import of ... as resource is not allowed."

### ISSUE THREAD

**Issue by devdemi** [ember-cli/ember-cli#8443]
I use `Ember-CLI 3.7.1` and today during the build I started to get the next errors:

> 11:40:27 Build Error (broccoli-persistent-filter:CleanCSSFilter) in assets/frontend.css
> 11:40:27 
> 11:40:27 2 errors found while optimizing CSS with clean-css:
> 11:40:27   1. Skipping remote @import of "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&subset=latin-ext" as resource is not allowed.
> 11:40:27   2. Skipping remote @import of "https://use.fontawesome.com/releases/v5.2.0/css/all.css" as resource is not allowed.
> 11:40:27 
> 11:40:27 clean-css dangerously ignores these errors but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
> 11:40:27 

I tried to push `@import` to the start of my app.scss but It doesn't help me.
As a workaround I added lines to index.html:
```
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin-ext" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet">
```

But before today project was built well.

**Comment by rwjblue** [comment]
Can you tell me what this outputs:

```
npm list ember-cli-preprocessor-registry
npm list broccoli-clean-css
```

**Comment by antonbavykin1991** [comment]
have same issue

works good with broccoli-clean-css@1.1.0 

maybe issue related to these changes, when push warning as errors
https://github.com/shinnn/clean-css-promise/blob/master/index.js#L102


Antons-MacBook-Pro:user-app antonbavykin$ npm list ember-cli-preprocessor-registry
hc@0.0.0 /Users/antonbavykin/hotecloud/user-app
└── (empty)

Antons-MacBook-Pro:user-app antonbavykin$ npm list broccoli-clean-css
hc@0.0.0 /Users/antonbavykin/hotecloud/user-app
└─┬ ember-cli@3.4.4
  └─┬ ember-cli-preprocess-registry@3.1.2
    └── broccoli-clean-css@1.1.0 

after update 
hc@0.0.0 /Users/antonbavykin/hotecloud/user-app
└─┬ ember-cli@3.4.4
  └─┬ ember-cli-preprocess-registry@3.2.1
    └── broccoli-clean-css@2.0.1

**Comment by boris-petrov** [comment]
I also get the same error after updating `ember-cli-preprocess-registry` from `3.1.2` to `3.2.1` (which updates `broccoli-clean-css` from `^1.1.0` to `^2.0.1`).

**Comment by gibso** [comment]
We got the same error in our application. 
Our `npm list clean-css` gives the following output:
```
+-- ember-cli@3.7.1
| `-- ember-cli-preprocess-registry@3.2.1
|   `-- broccoli-clean-css@2.0.1
|     `-- clean-css-promise@2.1.0
|       `-- clean-css@4.2.1  deduped
`-- semantic-ui@2.3.1
  `-- gulp-clean-css@3.10.0
    `-- clean-css@4.2.1
```

In the Ember-CLI Documentation they say that you can configure clean-css with options in the ember-cli-build.js file. (https://ember-cli.com/asset-compilation#minifying)
So we tried to set
```
...
    minifyCSS: {
      options: {
        processImport: true,
        processImportFrom: ['remote']
      }
    },
...
```

in the ember-cli-build.js file to allow remote import statements in the css. But this doesn't change anything.

Please help, this is really critical for us.

Thank you,
Oliver.

**Comment by lifeart** [comment]
We working on sprint tasks clarification and minor bugfixes.

```
17:48:48 ERROR Summary:
17:48:48 
17:48:48   - broccoliBuilderErrorStack: Error: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48     at minify (/var/****_home/workspace/frontend-build/node_modules/clean-css-promise/index.js:61:13)
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/clean.js:125:9
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:26:64
17:48:48     at loadOriginalSources (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:26:14
17:48:48     at applySourceMaps (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
17:48:48     at Object.callback (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:25:12)
17:48:48     at doInlineImports (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:200:25)
17:48:48     at Object.callback (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:324:14)
17:48:48     at doInlineImports (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:200:25)
17:48:48   - code: [undefined]
17:48:48   - codeFrame: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48   - errorMessage: assets/vendor.css: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48         in /tmp/broccoli-1120sqhrjWjjQLyf/out-499-simple_concat_concat_concat_vendor_styles_assets_vendor_css
17:48:48         at broccoli-persistent-filter:CleanCSSFilter
17:48:48   - errorType: Build Error
17:48:48   - location:
17:48:48     - column: [undefined]
17:48:48     - file: assets/vendor.css
17:48:48     - line: [undefined]
17:48:48     - treeDir: /tmp/broccoli-1120sqhrjWjjQLyf/out-499-simple_concat_concat_concat_vendor_styles_assets_vendor_css
17:48:48   - message: assets/vendor.css: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48         in /tmp/broccoli-1120sqhrjWjjQLyf/out-499-simple_concat_concat_concat_vendor_styles_assets_vendor_css
17:48:48         at broccoli-persistent-filter:CleanCSSFilter
17:48:48   - name: BuildError
17:48:48   - nodeAnnotation: [undefined]
17:48:48   - nodeName: broccoli-persistent-filter:CleanCSSFilter
17:48:48   - originalErrorMessage: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48   - stack: Error: An error found while optimizing CSS with clean-css:
17:48:48   * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Open Sans:300,400,500,600,700,800&subset=latin" as resource is not allowed and after other content.
17:48:48 
17:48:48 clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
17:48:48     at minify (/var/****_home/workspace/frontend-build/node_modules/clean-css-promise/index.js:61:13)
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/clean.js:125:9
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:26:64
17:48:48     at loadOriginalSources (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
17:48:48     at /var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:26:14
17:48:48     at applySourceMaps (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
17:48:48     at Object.callback (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:25:12)
17:48:48     at doInlineImports (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:200:25)
17:48:48     at Object.callback (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:324:14)
17:48:48     at doInlineImports (/var/****_home/workspace/frontend-build/node_modules/clean-css/lib/reader/read-sources.js:200:25)
17:48:48 
```

**Comment by Benjy1979** [comment]
I've got this well.

`Build Error (broccoli-persistent-filter:CleanCSSFilter) in assets/ember-roomviewer-easybathrooms.css

2 errors found while optimizing CSS with clean-css:
  1. Ignoring local @import of "bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css" as resource is missing.
  2. Empty property 'border' at ../../../Users/BENGLA~1/AppData/Local/Temp/broccoli-31712tg4lX2b4cZ7m/out-143-funnel/assets/roomviewer/planner/overlays/user-parameters/user-parameters.css:28:1. Ignoring.

clean-css dangerously ignores these errors but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.


Stack Trace and Error Report: C:\Users\BENGLA~1\AppData\Local\Temp/error.dump.bb441d72affabe81d2f9b28e2a6a0e76.log
`

**Comment by Benjy1979** [comment]
I spoke too soon, after fixing the css issues some of my images are broken because it seems to take out relative file references like where you have "../" at the beginning. It works in DEV mode, but after building the images are broken.

e.g 

in the CSS I have `background: url(../assets/arp/page_images/common/3ds/std_bg.gif);` and the image shows in dev mode, and it looks like this in dev mode when you view the inspector styles.

But after building it looks like:
`background: url(assets/arp/page_images/common/3ds/std_bg.gif);` and the image does not show.

**Comment by Benjy1979** [comment]
> Can you tell me what this outputs:
> 
> ```
> npm list ember-cli-preprocessor-registry
> npm list broccoli-clean-css
> ```

Did you mean:
> npm list ember-cli-preprocess-registry

**Comment by locks** [comment]
Closing work as stale. If this issue still happens for you please open a new issue with a new reproduction!
