### ISSUE TITLE
Security Notices for yuidocjs

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#8449]
Looks like we have security notices are coming from yuidocjs.

As this is devDependency, and our usage of it is limited. I don't believe we are affected by these issues, But this raises a larger issue. Currently YUIDocjs is essentially unmaintained, should we switch to something else? What are our options?

cc @mike-north  I think your working on some doc tool stuff, you may have some recommendations.

**Comment by mike-north** [comment]
@stefanpenner I'd advise sticking with yuidoc in the short term. I have an early version of something better, but would want to wait until I can ensure all of ember-cli's important use cases are addressed first. ETA 3/30

**Comment by locks** [comment]
I think the use of yuidoc will need to eventually be revisited, but we can open a fresh issue when that happens.
