### ISSUE TITLE
"ember new" is throwing "You cannot use the new command inside an ember-cli project" error. 

### ISSUE THREAD

**Issue by puramanuj** [ember-cli/ember-cli#8495]
When I try to create a new ember project using `ember new my-app` from a non ember cli project folder it throws the following error

`You cannot use the new command inside an ember-cli project.` 

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.8.1
http_parser: 2.8.0
node: 10.3.0
v8: 6.6.346.32-node.9
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
os: darwin x64
6.1.0
1.13.0
```

**Comment by rwjblue** [comment]
My guess is that you have a `package.json` somewhere in or above the directory you are running `ember new` from, can you double check?

**Comment by puramanuj** [comment]
I did double check it I do not see any package.json in any of the parent directories

**Comment by puramanuj** [comment]
Sorry, it was my mistake there is actually a `package.json` in one of the parent directories.
