### ISSUE TITLE
"@@" from config/environment.js replaced by "%40%40" in index.html meta tag starting with ember-cli@3.8.0

### ISSUE THREAD

**Issue by nfc036** [ember-cli/ember-cli#8496]
I'm using grunt-replace as a post-build step to replace some text snippets from environment.js (included as meta tag in index.html). Starting from ember-cli@3.8.0 the simple lookup mechanism of grunt-replace is broken (```@@string```), all ```@@``` are replaced by ```%40%40``` in the meta tag of index.html.

I could not find any commit indicating this breaking(?) change. My grunt-replace step was correctly working with ember-cli@3.7.1.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.8.1
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: win32 x64
6.9.0
1.3.2
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by nfc036** [comment]
Yes and no. Ember is still changing "@@" in strings in environment.js into "%40%40" in the meta tag within index.html. However, I have adjusted my post-processing steps so that this no longer bothers me. Since I was obviously the only one with this problem, the issue can be closed.
