### ISSUE TITLE
.ember-cli "port" option not working in Octane preview

### ISSUE THREAD

**Issue by courajs** [ember-cli/ember-cli#8525]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.9.0-beta.2
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
6.7.0
1.15.2
```

Specifically:
```
    "ember-cli": "github:ember-cli/ember-cli#ed51787b3e18efee706f163d57836a30cd5286b7",
```

I ran `ember init -b '@ember/octane-app-blueprint'` in an existing app. After properly merging stuff, I ran `ember serve`, and it ran on the default port 4200 instead of 3000 as configured in my `.ember-cli` file (which was working on my previous version). An explicit `--port 3000` argument works though.

So, just reporting a possible failure to read options from `.ember-cli`.
I haven't tried on master or anything though, sorry

**Comment by rwjblue** [comment]
The octane blueprint uses a `.ember-cli.js` file, can you confirm thats where you added `port` (and that the repo doesn't have both `.ember-cli` and `.ember-cli.js`)?

**Comment by courajs** [comment]
Ah, I do have both files, and port is specified only in `.ember-cli`. I suppose if things are being shifted from one to the other, it would be good to have a deprecation notice, or maybe detect specifically when both files are present.

Thanks for the help!
