### ISSUE TITLE
"Build successful" message missing with latest deps

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli#8541]
When installing all the latest dependencies for an Ember CLI 3.8.1 based app (i.e. ignoring lock files), the "Build successful" message is not shown anymore.

This not only causes a reduced DX, but has more far reaching consequences with `ember-cli-addon-tests` (and related tools like `ember-fastboot-addon-tests`) [relying on that output](https://github.com/tomdale/ember-cli-addon-tests/blob/5d4cea6163fc6264539b98577b36df7ca1a56519/lib/commands/start-server.js#L56) to detect the server being read for requests, causing [tests to timeout](https://travis-ci.org/kaliber5/ember-bootstrap/jobs/512596694#L1118).

### Reproduction

Using Ember CLI 3.8.1:

```bash
ember new buildoutput 
cd buildoutput
ember s
```

### Expected

```
Build successful (7356ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: ember-data (2)                         | 3002ms (1501 ms)
Babel: ember-test-helpers (2)                 | 1518ms (759 ms)
Package /assets/vendor.js (1)                 | 772ms
Rollup (1)                                    | 662ms
Babel: buildoutput (2)                        | 412ms (206 ms)
```

### Actual

```
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel: ember-data (2)                         | 3002ms (1501 ms)
Babel: ember-test-helpers (2)                 | 1518ms (759 ms)
Package /assets/vendor.js (1)                 | 772ms
Rollup (1)                                    | 662ms
Babel: buildoutput (2)                        | 412ms (206 ms)
```

### Analysis

This has been working before, but started to happen just recently, when running in CI with `yarn.lock` being ignored. With an [existing `yarn.lock`](https://github.com/kaliber5/ember-bootstrap/blob/4f95cd1f588061c5c70cc615cb6e797f6c57a265/yarn.lock) (6d old) this does not occur. So this seems to be caused by some updated (transitive) dependency. 

As it is [related to watcher events](https://github.com/ember-cli/ember-cli/blob/eeac6b1d945659d1fde9d5e4d66e70e6f709e79a/lib/models/watcher.js#L46), I skimmed through some of the related dependencies (e.g. `sane`), but could find any suspicious recent changes.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.8.1
6.4.1
1.13.0
```

**Comment by nightire** [comment]
confirmed and I noticed it also affected other outputs, e.g. `ember init`:

![image](https://user-images.githubusercontent.com/1104018/55294653-1bed9400-5437-11e9-9dd7-43d5efa3fe2e.png)

**Comment by rwjblue** [comment]
This was caused by https://github.com/ember-cli/console-ui/issues/67, and has been fixed. 

Thank you for reporting!
