### ISSUE TITLE
Octane addon component pod template exports itself

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli#8553]
Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 3.9.0-beta.2
6.7.0
1.13.0
```

Something wrong with the blueprint.

```
// app/components/my-component/template.js
export { default } from './template';
```

**Comment by locks** [comment]
I tried reproducing in a more recent version and it seems to have been fixed. Let us know if that's not the case!
