### ISSUE TITLE
Automatically run prettier on staged files

### ISSUE THREAD

**Issue by RichardOtvos** [ember-cli/ember-cli#8573]
Now that we have Prettier on the codebase, do you think it would be a good idea, to run it to js files that has been staged, so we avoid committing badly formatted code?

I'm thinking about using lint-staged to format our files like how create-react-app does here: https://github.com/facebook/create-react-app/blob/master/package.json#L46

I'm happy to work on this if it's something we want, but thought we could discuss it before, I put time into this.

**Comment by kellyselden** [comment]
If it touches the git hooks, I'm pretty much opposed.

**Comment by RichardOtvos** [comment]
@kellyselden no worries 😄
Yeah, I see how this can be pretty controversial, that's why I wanted to talk about it, see what you guys think. 

Also that repo destroying story sounds scary 😬
