### ISSUE TITLE
"node_modules appears empty, you may need to run yarn install"

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-cli#8575]
Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 3.9.0
http_parser: 2.8.0
node: 10.12.0
v8: 6.8.275.32-node.35
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.9.0
1.15.2
```

I've generated a brand new Ember project, and it has an in-repo-addon. I want to generate a new component inside of said in-repo-addon:

```
% ember g component some-component
node_modules appears empty, you may need to run `npm install`
```

OK, let's do that:

```
$ yarn install
yarn install v1.15.2
warning package.json: No license field
info No lockfile found.
warning my-addon: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 0.08s.
$ ls
index.js     node_modules package.json yarn.lock
```

Now let's try again:

```
$ ember g component kleenex
node_modules appears empty, you may need to run `yarn install`
```

For completeness, here's a link to the barebones repo in question: https://github.com/jherdman/fart

**Comment by next-adriangonzalez** [comment]
It seems broken. I came up with a "workaround": 

Edit file `node_modules/ember-cli/lib/cli/index.js:127` and change

```
disableDependencyChecker: options.disableDependencyChecker,
```

With:

```
disableDependencyChecker: true,
```

Regards,

**Comment by MelSumner** [comment]
I can only replicate this issue sometimes- but I can't replicate it with the repo you linked here. It builds and runs successfully for me. 

Here's what I've tried: 
- yarn vs npm, does it matter?
- replicating the issue for multiple repositories
- checked `where npm` from my terminal and checked my environmental variables
- checked different versions of Ember (3.9 vs 3.10)

I get it sometimes but not others. I just have no idea what's causing it and I can't consistently produce results. If anyone has some knowledge or prior art for this issue it would be helpful.

**Comment by lougreenwood** [comment]
I was getting this error just this morning when trying to run `ember t` in a locally forked `ember-cli` checkout...

**Comment by MelSumner** [comment]
@lougreenwood that seems to be my issue, haha!

**Comment by rwjblue** [comment]
@lougreenwood FWIW, ember-cli itself is not an addon or app, so running `ember <anything>` in it would always emit this error.

**Comment by lougreenwood** [comment]
@rwjblue yep, exactly - hence my idiocy... :D - However, to be fair to myself, it was 6am when I was messing around with a local `ember-cli` build for the first time ;)

**Comment by rwjblue** [comment]
Hehe. Either way, the error message should be clearer. We _totally_ know that a given package isn’t an addon or app, we should say that instead of “node_modules is empty”.

**Comment by locks** [comment]
Fixed by a linke PR!
