### ISSUE TITLE
addon templates were detected, but no template compilers were registered.

### ISSUE THREAD

**Issue by MelSumner** [ember-cli/ember-cli#8589]
As an addon author, I would like a template compiler to be automatically registered for me when I need it, so I avoid the error message below. Is there a reasonable way to for ember-cli to do this?

Error message: 
"Addon templates were detected but there are no template compilers registered for (addon-name). Please make sure your template precompiler (commonly ember-cli-htmlbars) is listed in dependences (NOT devDependencies) in (addon-name)'s package.json."

**Comment by rwjblue** [comment]
We've talked about this a bit. We have a few choices:

* Automatically add ember-cli-htmlbars to `dependencies` when a generator is ran that creates a template. This is something we have previously discussed and seems broadly agreed on.
* Move ember-cli-htmlbars into the `dependencies` of the addon blueprint by default.

**Comment by MelSumner** [comment]
@rwjblue what's the next step for taking action on this?
