### ISSUE TITLE
Addons require a dummy app to build

### ISSUE THREAD

**Issue by runspired** [ember-cli/ember-cli#8617]
Reproduction with ember-cli 3.9

https://github.com/runspired/ember-cli-build-bug-reproduction

It appears addons cannot run `ember build` without a tests directory and dummy application. This is problematic for addons which do not have a dummy application (or tests) but do need to build.

I encountered this case when attempting to publish `ember-data`. All of our tests are contained in just one of our packages currently, but we require doing a build of each of our packages to produce the `yui` documentation for our modules.

**Comment by locks** [comment]
Is this still true?

**Comment by runspired** [comment]
Probably.
