### ISSUE TITLE
Addon blueprint using yarn fails tests on Travis

### ISSUE THREAD

**Issue by bendemboski** [ember-cli/ember-cli#8643]
Addons generated with the `ember-cli@3.10.0` blueprint and using yarn fail on TravisCI because of a node version incompatibility.

The blueprint's `travis.yml` specifies `6` as the node version, but `ember-cli` [dropped node 6](https://github.com/ember-cli/ember-cli/commit/88a59e4363c6d51918454d40cf67d7c50f09e1f1) support in `3.10`, so when Travis runs `yarn` to install the addon dependencies, it fails with

```
$ yarn install --non-interactive
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error ember-cli@3.10.0: The engine "node" is incompatible with this module. Expected version "8.* || >= 10.*". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "yarn install --non-interactive" failed and exited with 1 during .
Your build has been stopped.
```

`npm` (in node 6) apparently doesn't validate the `engines`, so this only happens when using `yarn`.

**Comment by bendemboski** [comment]
I tried to prod into a solution that would allow testing the LTS versions on node 6, while testing default/release/beta/canary on node 8, but it doesn't seem feasible. If an addon's `ember-cli` version is >= 3.10, it can't even install its initial dependencies on node 6 because `ember-cli` will fail to install, so it can't even get to invoking the `ember-try` scenario that might specify all node 6-compatible dependencies.

It looks like we need to just bump the node version to `8` for the whole matrix and tell maintainers of any addons that do build pipeline/ember-cli/node dependent stuff to either drop support for the LTS versions, keep support but stop Travis testing against them, or do some custom Travis acrobatics to test those scenarios?

**Comment by rwjblue** [comment]
@bendemboski - We _could_ use `--ignore-engines` when using `yarn` (`npm` doesn't care/enforce engines), but I think the right solution here is to update the `.travis.yml` to use Node 8 and make it clear in the 3.10 release blog post that support for Node 6 is completely dropped and addons updating to the 3.10 blueprint should consider making a major version bump.

**Comment by bendemboski** [comment]
@rwjblue that makes sense, but then does it still make sense to keep the two LTS scenarios in `ember-try.js`?

**Comment by kellyselden** [comment]
I'm going to submit a PR soon.

**Comment by kellyselden** [comment]
Should be fixed here https://github.com/ember-cli/ember-cli/pull/8645.

**Comment by locks** [comment]
Referencedd PR has been merged.
