### ISSUE TITLE
ember 3.10 build with option -w hangs

### ISSUE THREAD

**Issue by shofmannka** [ember-cli/ember-cli#8647]
The behavior can be reproduced with the following commands:
ember new test-app
cd test-app
ember build -w

Output from `ember version --verbose && npm --version && yarn --version`:
ember-cli: 3.10.0
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: win32 x64
6.4.1
1.13.0

on windows 10

**Comment by hectorh30** [comment]
I'm also seeing this on ember-cli 3.11.0-beta.1 and linux x64.

Using an `ember build -w` results in the bulind message an animation never going away.

This doesn't happen with an `ember serve`

**Comment by locks** [comment]
Is this still happening for you?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
