### ISSUE TITLE
Link to source in docs is broken

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#8670]
[http://api.emberjs.com/ember/3.10/functions/@ember%2Fobject%2Fobservers/addObserver](http://api.emberjs.com/ember/3.10/functions/@ember%2Fobject%2Fobservers/addObserver)

Links to:
```https://github.com/undefined/tree/vundefined/packages/@ember/-internals/metal/lib/observer.ts#L9```

Pretty sure the `undefined` parts should be populated to be

```https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/metal/lib/observer.ts```

**Comment by bertdeblock** [comment]
Closing as this is no longer an issue, please reopen if otherwise.
