### ISSUE TITLE
PORT env var needs to be number-ized

### ISSUE THREAD

**Issue by ClayShentrup** [ember-cli/ember-cli#8709]
Passing the PORT via an environment variable gives the error, `Port 5100 is already in use.`

But this works in `.ember-cli.js`

```
module.exports = {
  "port": Number(process.env.PORT)
};
```

You can also pass it explicitly on the command line like `-p $PORT` and that works.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.10.1
node: 12.4.0
v8: 7.4.288.27-node.18
uv: 1.29.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.3
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.9.0
1.16.0
```

**Comment by bertdeblock** [comment]
I've been testing this out locally, but I can not reproduce. `PORT=5100 ember s` works fine for me.
