### ISSUE TITLE
Ember new is broken. 3.9.0 version

### ISSUE THREAD

**Issue by KalachevDev** [ember-cli/ember-cli#8733]
Hey, I was trying to create new ember application and got following error:

> Uncaught Error: Assertion Failed: Expected hash or Mixin instance, got [object Undefined]

After some investigation I found a root cause:

ember-data/adapters/rest, line 271

`var RESTAdapter = _adapter.default.extend(_private.BuildURLMixin, {`

But in version 3.9.0 BuildURLMixin is undefined.

```
ember-cli: 3.9.0
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.15.2
```

Did someone else face it?

**Comment by dfreeman** [comment]
@KalachevDev I think this should be fixed now that https://github.com/typed-ember/ember-cli-typescript/pull/751 has been published
