### ISSUE TITLE
Should the default values for options in `--help` take into account of .ember-cli?

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli#8755]
If you override the flags passed to the commands from `.ember-cli`, should the `--help` output reflect that? Is that desirable/feasible?

**Comment by chancancode** [comment]
The use case that comes to mind is [RFC #481](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html#generator) which (originally, at least) proposes to alter the default flags for the generators in new (Octane) apps and leave the existing defaults to preserve compatibility. For this use case, it seems nice to have the `--help` output reflect the "effective defaults".

**Comment by rwjblue** [comment]
Ya, I would like to have the defaults updated in this case.

**Comment by locks** [comment]
Closing as stale.
