### ISSUE TITLE
Ember new app not working - Babel polyfill is deprecated

### ISSUE THREAD

**Issue by f4ww4z** [ember-cli/ember-cli#8756]
I just installed `ember-cli` with npm, and was trying to create a new app. It failed with this error:

```
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
```

#### How to Reproduce

1. Run `ember new client`
2. Error shows up, `client` directory is deleted.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.11.0
http_parser: 2.7.1
node: 8.10.0
v8: 6.2.414.50
uv: 1.18.0
zlib: 1.2.11
ares: 1.14.0
modules: 57
nghttp2: 1.30.0
openssl: 1.0.2n
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
os: linux x64
3.5.2
1.17.3
```

**Comment by mbernwieser** [comment]
I had the same problem, using yarn instead of npm worked for me:

1. ember new name_of_project --skip-npm
2. cd name_of_project
3. yarn

**Comment by HermitSun** [comment]
Me too. And @mbernwieser is right, yarn also works for me.

**Comment by rwjblue** [comment]
FWIW, that output doesn’t indicate an error. Are you reporting that the install emits a warning? Is there also an error? If so can you include more details on that part?
