### ISSUE TITLE
Diff links are broken in 3.11.0 release

### ISSUE THREAD

**Issue by larryh** [ember-cli/ember-cli#8757]
The 2  `diff` links under `Blueprint changes` are broken

```
larry@larry-lap:~/RubyMine/BNC$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.11.0
node: 11.9.0
v8: 7.0.276.38-node.16
uv: 1.25.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
os: linux x64
6.9.0

Command 'yarn' not found, but can be installed with:

sudo apt install cmdtest

```

**Comment by baron1405** [comment]
The incorrect links are:
https://github.com/stefanpenner/ember-new-output/compare/v3.10.0...v3.11.0
https://github.com/stefanpenner/ember-addon-output/compare/v3.10.0...v3.11.0

The correct links are:
https://github.com/ember-cli/ember-new-output/compare/v3.10.0...v3.11.0
https://github.com/ember-cli/ember-addon-output/compare/v3.10.0...v3.11.0

**Comment by rwjblue** [comment]
Sorry about that! Just fixed it in the release notes and CHANGELOG.md.
