### ISSUE TITLE
Docs: list of all official lts versions.

### ISSUE THREAD

**Issue by MichaelDimmitt** [ember-cli/ember-cli#8760]
### Goal
Trying to find a list of all releases that have become LTS.

### Why is this important?
The docs for ember update recommend going one LTS version at a time:
```
 For large, complex apps, it is recommended to jump between LTS versions in order.
```
~ https://cli.emberjs.com/release/basic-use/upgrading/#managing-major-upgrades

### Research attempts:

I have looked for a list of LTS releases on the official docs.
Maybe a website with the cool LTS trophies.
https://emberjs.com/releases shows some trophies and some LTS but not all LTS.

Going to https://github.com/ember-cli/ember-cli/releases there is no distinguishable tag for LTS

My understanding is that LTS (Long Term Support) releases are done at least every four minor versions, plus the last version before a new major release. Therefore, should I look at the releases page and guess where the LTS release is located?

It seems a release is a candidate for LTS and then LTS is finally announced in a blog post when the code has become stable.

Blog posts are the only location I find mention "release is now LTS".

This issue is also documented in ember-cli-update:
https://github.com/ember-cli/ember-cli-update/issues/542

### Ask
1) Am I missing a website/view that shows the LTS versions?
2) Are there plans for keeping track of LTS versions?
3) How does the ember-cli team keep track/remember LTS versions?

**Comment by rwjblue** [comment]
> Am I missing a website/view that shows the LTS versions?

I don't think so...

> Are there plans for keeping track of LTS versions?

I think this would be great, but I'm not sure where to show it and whatnot...

> How does the ember-cli team keep track/remember LTS versions?

The _rough_ rules around what will be an LTS:

* every release where the minor is divisible by 4 will be an LTS (e.g. 3.4, 3.8, 3.12, 3.16)
* the last minor version within a major (e.g. 1.13, 2.18)

**Comment by maxwondercorn** [comment]
@MichaelDimmitt  You should bring this up on the #dev-ember-learning Discord channel

**Comment by locks** [comment]
Thanks for filing the report! https://emberjs.com/releases/lts/ tracks the currently active ember.js LTS versions, so that part should be addressed!

**Comment by MichaelDimmitt** [comment]
@locks , that looks like the link searching to find:
emberjs.com/releases/lts

```
LTS Version | Released | Bugfixes until | Security patches until

       3.16 | Feb 2020 | Sep 2020 | Feb 2021
       3.12 | Aug 2019 | Mar 2020 | Aug 2020
       3.8  | Feb 2019 | Sep 2019 | Feb 2020
       3.4  | Oct 2018 | May 2019 | Oct 2019
       2.18 | Feb 2018 | Sept 2018 | Feb 2019

```
thanks, Michael Dimmitt
