### ISSUE TITLE
Resolver warns on partials that start with '_'

### ISSUE THREAD

**Issue by tomdale** [ember-cli/ember-cli#879]
The Ember CLI resolver issues a deprecation warning if you have a partial that starts with `_`, which IMO is still the recommended syntax.

In this case, I have a folder full of partials:

```
app/
  templates/
    endpoint/
      _header.handlebars
      _list.handlebars
      _debug.handlebars
```

I had to rename this to:

```
app/
  templates/
    endpoint/
      -header.handlebars
      -list.handlebars
      -debug.handlebars
```

Which seems wrong (again, IMO).

**Comment by Floby** [comment]
I know this issue is closed but I finally got around to fixing this deprecation warning throughout our codebase and this was a pain to do automatically since most commands (especially mv) treats any argument starting with a hyphen as a string of flags.
Did I miss something obvious ?
