### ISSUE TITLE
What should we do with the module unification blueprint?

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#8790]
It is currently a maintenence burden, and correct me if I'm wrong, it is not something that will be released?

**Comment by rwjblue** [comment]
IMHO, we should remove module unification support code. Ember has already disabled its support (in https://github.com/emberjs/ember.js/pull/18066) in other words it's already not possible to actually use.

**Comment by locks** [comment]
Does this work necessitate a major version?

**Comment by dcyriller** [comment]
It was an experiment, behind a feature flag...

**Comment by rwjblue** [comment]
> Does this work necessitate a major version?

No.

**Comment by locks** [comment]
I believe most if not all of the work as been done, so I'll close this issue. Thanks everyone x)
