### ISSUE TITLE
Explicit resolution

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#8810]
ember-source: 3.4.8 
npm: 6.1.0
node: v10.6.0

*Question?*

Is is possible to add a flag to enable explicit imports? 

Current import

import foo from 'foo/components/foo'

Proposal

import foo from 'foo/addon/components/foo'

*Why?* 

This will enable the use of many tools out of the box in the javascript ecosystem.

Currently editors and the rest of the ecosystem doesn't know / needs to be able to understand the non-explicit pathing that ember-cli enables.

**Comment by gabrielcsapo** [comment]
Given that v2 addon spec has contentious topics that are still being debated, would it make sense to land things that are pointing towards a true north? Supporting node module resolution as well as the current ember resolver would be forward compatible with any direction we are going. Also the tooling options this allows from the JS side has great advantages without bringing in all of the requirements of embroider.

**Comment by rwjblue** [comment]
IMHO, no? Any changes we make to the build pipeline here increases the work that has to be done in Embroider and also increases the work that we expect addon authors to do in the meantime.

**Comment by locks** [comment]
As mentioned by the last comment we should be focusing our efforts on Embroider. Thanks for filing the issue!
