### ISSUE TITLE
Customizing `modulePrefix` breaks build output

### ISSUE THREAD

**Issue by dcyriller** [ember-cli/ember-cli#8821]
## Description

In an app, I've tried to customize the `modulePrefix` option (in file: `config/environement.js`). This breaks the build output.

A reproduction is available here: https://github.com/dcyriller/__module-prefix-reproduction/commits/master

## Reproduction

First, I setup a working app with a working import: [commit 2](https://github.com/dcyriller/__module-prefix-reproduction/commit/351390853ab7b2bda15b6d5d6355634ff950299d#diff-a9a19ee37ba8619bc68db992b637dd05R2)

In this commit, I apply the `modulePrefix` customization: [commit 3](https://github.com/dcyriller/__module-prefix-reproduction/commit/236d930a8edc468696c09bb50adc5f70794b325b). It breaks the build output...

... that I have commited in a [last commit](https://github.com/dcyriller/__module-prefix-reproduction/commit/d21ee909f307120ddaca7eae2fedaefc38bae517).

## Build output

As you will see, the bugged build output looks like this:
```javascript
 ;define("--module-prefix-reproduction/app", ["exports", "--module-prefix-reproduction/resolver", "ember-load-initializers", "--module-prefix-reproduction/config/environment"], function (_exports, _resolver, _emberLoadInitializers, _environment) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;
  const App = Ember.Application.extend({
    modulePrefix: _environment.default.modulePrefix,
    podModulePrefix: _environment.default.podModulePrefix,
    Resolver: _resolver.default
  });
  (0, _emberLoadInitializers.default)(App, _environment.default.modulePrefix);
  var _default = App;
  _exports.default = _default;
});


if (!runningTests) {
  require("custom-module-prefix/app")["default"].create({"name":"--module-prefix-reproduction","version":"0.0.0+ab98effa"});
}
```

---

Output from `ember version --verbose`:
```
ember-cli: 3.12.0 and ember-cli@3.8.3 + ember-source@3.8.3
```

**Comment by rwjblue** [comment]
Can you describe what you mean by "breaks build output"? Do you get a build error? A runtime error?

**Comment by dcyriller** [comment]
I get a runtime error: `Uncaught Error: Could not find module `custom-module-prefix/app` imported from `(require)`. The runtime error points to these lines (taken from the snippet above):
```javascript
if (!runningTests) {
  require("custom-module-prefix/app")["default"].create({"name":"--module-prefix-reproduction","version":"0.0.0+ab98effa"});
}
```

**Comment by dcyriller** [comment]
I image `"custom-module-prefix/app"` is not defined because `"--module-prefix-reproduction/app"` is defined.

**Comment by locks** [comment]
Hey @dcyriller :) Can you confirm whether this is still an issue?

**Comment by bertdeblock** [comment]
The only way that I got a rename to work properly, was to also edit the `name` field in the `package.json` file.
It seems that field is also taken into account for e.g. the names of your built js and css asset files.
So afaict, only renaming `modulePrefix` isn't sufficient.

**Comment by dcyriller** [comment]
Hey @locks :)
Thanks for the clarification @bertdeblock. I’m closing the issue.
