### ISSUE TITLE
Transitive dependencies re-exported by ember (RSVP)

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#8838]
There are instances of RSVP being used in our application:

```
import { resolve } from 'rsvp';
```

But we do not define this dependency in our package.json. Would it be possible to add this as a optionalDependencies to ember-cli to ensure that we have explicit dependencies in our application?

ember: 3.4.8
npm: 6.1.0
yarn: 1.17.3

**Comment by locks** [comment]
I think further discussion would be more useful in the RFC issue linked above! Thanks for bringing it up :)
