### ISSUE TITLE
Ember cli 3.8.3: ember serve fail without ember-cli-htmlbars-inline-precompile

### ISSUE THREAD

**Issue by Emmanuel-Coutlee** [ember-cli/ember-cli#8876]
I just updated to ember-cli-htmlbars@4.0.5 and got this deprecation warning:
`ember-cli-htmlbars-inline-precompile is no longer needed with ember-cli-htmlbars versions 4.0.0 and higher, please remove it from `package.json`

But when removing  ember-cli-htmlbars-inline-precompile, `ember serve` fail with this message:
`It looks like you're not on ember-cli 1.13, which includes ember-cli-htmlbars-inline-precompile by default. Please run: ember install ember-cli-htmlbars-inline-precompile.`

**Comment by Emmanuel-Coutlee** [comment]
seem related to change made in ember-cli/ember-cli-htmlbars#312

**Comment by rwjblue** [comment]
The last error message is coming from ember-mocha, which landed a fix for that https://github.com/emberjs/ember-mocha/pull/456. I don't think that has been released yet though.

**Comment by Emmanuel-Coutlee** [comment]
Made the update to ember-mocha@0.16.1 fix the problem for me.
