### ISSUE TITLE
`this.project.hasDependencies()` does not honor Yarn Workspaces

### ISSUE THREAD

**Issue by davidwkeith** [ember-cli/ember-cli#8881]
[https://github.com/ember-cli/ember-cli/blob/4d8304aca205a147694426b56d71addd9e0adc5e/lib/models/command.js](this.project.hasDependencies()) only checks the current `package.json` and not any workspaces parent. thus it throws an error if the sub-project does not have the necessary devDependencies. This is not optimal as it is best practice to share devDependencies across projects in a monorepo.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.13.1
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
os: darwin x64
6.9.0
1.17.3
```

**Comment by rwjblue** [comment]
Hmm, I'm not sure that I'm following you. We definitely attempt to resolve a dependency from the project's root directory using the normal node modules resolution algorithm:

https://github.com/ember-cli/ember-cli/blob/dbc469ac4c621adb160adaf4425fc3c3db0dee07/lib/models/project.js#L136-L147

We only check to see that the first dependency is valid, but we do use normal resolution. If the project lists something as a depencency (regular or dev only) it _should_ be resolvable from the project, this is generally true in both yarn workspace projects and single package projects.

Can you give an example/demo project that has an issue here? Maybe I've made a mistake in my brief perusal...

**Comment by stefanpenner** [comment]
this seems to have gone stale, closing. Will gladly reopen if @rwjblue's question is answered.
