### ISSUE TITLE
Deprecation: ember-cli-htmlbars-inline-precompile no longer needed

### ISSUE THREAD

**Issue by monkeywithacupcake** [ember-cli/ember-cli#8895]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

When ember newis called with ember-cli 3.13.1, you get a deprecation warning that suggests a change to package.json

DEPRECATION: ember-cli-htmlbars-inline-precompile is no longer needed with ember-cli-htmlbars versions 4.0.0 and higher, please remove it from /Users/jess/ember-quickstart/package.json``

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.13.1
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
os: darwin x64
6.9.0
zsh: command not found: yarn

```

**Comment by monkeywithacupcake** [comment]
traced:
```
> npm ls ember-cli-htmlbars-inline-precompile                                                                                      [14:46:46]
ember-quickstart@0.0.0 /Users/jess/ember-quickstart
├── ember-cli-htmlbars-inline-precompile@3.0.1 
└─┬ ember-qunit@4.5.1
  └─┬ @ember/test-helpers@1.6.1
    └── ember-cli-htmlbars-inline-precompile@2.1.0 
```

**Comment by rwjblue** [comment]
We have fixed this in the `release` branch so it will avoid the deprecation notice with ember-cli@3.13.x once we publish a new version (and will also work with ember-cli@3.14+).
