### ISSUE TITLE
[FEATURE REQUEST]: Add an interactive step to choose package manager

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/ember-cli#8896]
While running `ember new <project-name>` the default package manager used is npm. But the package manager can be changed to `yarn` by making use of the `--yarn` flag.

Would it be useful to add an interactive question to let the user choose which package manager to use?

This is something I came across recently while setting up gatsbyjs project. Something like the one below:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/5667722/67158997-b0303180-f35c-11e9-9e19-d982d1f87cbc.png">

I can also send a PR. Thoughts?

**Comment by locks** [comment]
Hey @abhilashlr! Something similar to what you mention has been proposed as the [Interactive new Ember app creation](https://emberjs.github.io/rfcs/0638-interactive-app-creation.html) RFC and accepted, so I'll be closing this issue. 
I'm not sure what the status of the implementation is, but that's a separate issue.
