### ISSUE TITLE
`ember test` hangs if baseURL is anything but /

### ISSUE THREAD

**Issue by chnn** [ember-cli/ember-cli#891]
Running `ember test` or `ember test --server` fails if the environment `baseURL` has been set to anything but `/`.

When testem goes to capture the browsers, the `tests/index.html` attempts to load resources according to `{{BASE_TAG}}`, which is set to the new base url. Somehow the assets are served differently when running the test server vs. `ember serve`, and the assets aren't found.

If I change the base url in `tests/index.html` to just '/' then testem works, but navigating to localhost:4200/tests does not. 

If the fix is simple for this I can attempt to submit a PR. I wasn't sure where to start looking. Let me know if you need more info. I checked both master and 0.28.

**Comment by manishranade** [comment]
What was the solution to this problem? I created a brand new ember app with ember cli 1.13.8 and I have modified baseUrl value. Now with this, "ember test" works but http://localhost:4200/<base_url>/tests doesn't work. If I modify paths in tests/index.html with <base_url> prepended to static assets, http://localhost:4200/<base_url>/tests works but "ember test" just hangs after the project is built.

**Comment by stefanpenner** [comment]
the fact that this is trolling people, we need to fix this.

Ultimately baseHref stuff is a mess, and likely will need a rethink/refresh.

**Comment by msranade** [comment]
@stefanpenner Thanks for the response. Is there any workaround for this problem while we figure the right solution? May be some hacky solution?

**Comment by stefanpenner** [comment]
one can hard-code the paths, instead of relying on base HREF

**Comment by Turbo87** [comment]
I've just tried this in a new app with the current release of ember-cli and had no issues running `ember test` after setting `baseURL` to `/foo/bar/`
