### ISSUE TITLE
Use of undocumented `fail_fast` TravisCI option

### ISSUE THREAD

**Issue by jacobq** [ember-cli/ember-cli#8912]
https://github.com/ember-cli/ember-cli/blob/80f2e31260bf35758f87151373758ec73fd01b1c/blueprints/addon/files/.travis.yml#L33

My IDE is reporting a schema validation error on this line. Searching the Travis CI docs, the closest thing I could find is [`fast_finish`](https://docs.travis-ci.com/user/customizing-the-build#fast-finishing), but I see in [#7803](https://github.com/ember-cli/ember-cli/pull/7803/files) that this was done in the old version (presumably changed on purpose). 

I tried to find where this was referenced in the publicly available TravisCI code, but all I found were fixtures of ember configs and [this "potential alias" entry](https://github.com/travis-ci/travis-yml/blob/ee4e590905eeee183082b09657fb2ef8ff96ede3/spec/integrate/configs_spec.rb#L166).

Could someone help me find where this option is documented?

**Comment by tniezurawski** [comment]
I think you are right. I tried to find `fail_fast` as well but failed. IMO the blueprint should use [`fast_finish`](https://docs.travis-ci.com/user/customizing-the-build#fast-finishing).

I see [Travis online config validator](https://config.travis-ci.com/explore) is complaining:

![image](https://user-images.githubusercontent.com/4335166/69527251-377c5080-0f6c-11ea-9136-c78f9dda02fe.png)

**Comment by jacobq** [comment]
> I tried to find `fail_fast` as well but failed.

But did you fail *fast*? :laughing:

**Comment by tniezurawski** [comment]
Haha, yeah. Pretty fast :D

btw `fail_fast` feels to me like a better name than `fast_finish` but 🤷‍♂

**Comment by jacobq** [comment]
I think the rational for the name is that it will also mark a build as
successful before all jobs have finished as long as the only ones left are
allowed to fail. In other words, it's also `succeed_fast`

**Comment by tniezurawski** [comment]
Oh, yeah. That's true. I didn't think about it that way :+1:
So in addon's case, it will mark the build as successful even if:
```yaml
- env: EMBER_TRY_SCENARIO=ember-canary
```
didn't finish yet. That's the one where we `allow_failures`.

Anyway, I'll prepare a PR soon and maybe we will get a bit more attention to it :)

**Comment by rwjblue** [comment]
Sorry about this y'all, when I copied things over to the stages setup I totally messed up this option 😢.

**Comment by jacobq** [comment]
> Sorry about this y'all

It's OK. Finding an ember mistake made by Robert Jackson is sort of like [finding an error by Donald Knuth](https://en.wikipedia.org/wiki/Knuth_reward_check) -- one of those virtual souvenirs one treasures and is tempted to list on a resume :laughing:
