### ISSUE TITLE
.ember-cli needs to become .ember-cli.js to match .npmignore

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#8934]
.npmignore was changed .ember-cli => .ember-cli.js https://github.com/ember-cli/ember-cli/commit/ea1a067e3549aaa49fa7c3d76baea00fa6a46ded#diff-a145567d820c92abaee9865b7127a28aR11

but the actual file was missed in the rename.

**Comment by rwjblue** [comment]
I think this is fixed
