### ISSUE TITLE
3.14 Regression - `let` (not `var`) appears in production assets, breaking Safari 9 despite correct targets.js directive

### ISSUE THREAD

**Issue by samcic** [ember-cli/ember-cli#8938]
In 3.14, the `let` keyword appears in the production assets for a bare-bones Ember app, even when specifying `Safari >=9` and `iOS >= 9` in `targets.js`. This causes the app to crash (i.e. not launch at all) on Safari 9 (which [doesn't support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility) `let`).

The browser error shown in Safari in this case is `SyntaxError: Unexpected identifier 'e'`, which is the [typical error shown](https://stackoverflow.com/questions/39145783/does-safari-have-issues-with-es6-keyword-let) when Safari 9 encounters a `let`.

Repro:
1. `ember new app-3-14`
2. Modify `targets.js` to include `Safari >= 9` and `iOS >= 9`
3. `ember build --environment=production`
4. Inspect `/dist/vendor-<hash>.js` and notice the `let` keyword around line 94 (looks like the start of the `ember-source` code).

This wasn't a problem on 3.13. Is this a bug, or am I missing something new with 3.14 that needs to be configured?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.14.0
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: win32 x64

npm --version
6.12.0

yarn --version
1.19.1
[Replace this line with the output.]
```

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/18582, thank you for reporting!
