### ISSUE TITLE
Issues upgrading ember cli from 3.3.0 to 3.4.4

### ISSUE THREAD

**Issue by tehmaestro** [ember-cli/ember-cli#8948]
**Short description**

Hi, I have a very weird issue while trying to update a rather large app. I started at Ember 2.13 and I'm trying to reach the latest LTS. I managed to reach ember 3.3.0 without any issues.
 However, while updating to 3.4.4, I encountered a couple of issues that throw a fatal error in the console.

**Setup**
```
ember-cli: 3.4.0-beta.2
node: 8.16.2
ember: 3.3.2
```
This issue is produced by ember-cli `3.4.0-beta.2` , `beta.1` works as expected.

**Issue 1**

So, I have a component named `lessons/chip-munks.js`. When I run the app, I get:
```
Uncaught SyntaxError: Cannot use import statement outside a module

// inside app.js I have
;import Ember from 'ember';

export default Ember.Component.extend({
    classNames: ['chip-munks'],
```

So it seems the component is not transpiled? If I rename to `chip-munksss`, it still doesn't work, but if I rename to `chip-munkis`, it works! I would like to mention that I have hundreads of components, and this is the only one that does not work (and the js is incredibly simple, no funny stuff)

**Issue 2**
I created an in-repo addon, which basically excludes the `app\locales\**\translations.js` files from the final build using `broccoli-funnel`. The addon is reached, here's how the code looks like:

```
// lib/translations/index.js

    preprocessTree: function(type, tree) {
        if(type !== 'js') {return tree;}

        return new BroccoliFunnel(tree, {
            exclude: ['**/locales/*/translations.js']
        });
    },
```

However, locale translations do end up in app.js, the files are not excluded. This worked fine before upgrading to beta.2 . Moreover, in the console, I get:
```
Uncaught SyntaxError: Unexpected token 'export'

// app.js
;export default {
    "key1": "value",
    "key2": "value"
```
So, these files are not transpiled as well .. and it seems related to issue number one.
Any help is extremely appreciated. Thank you!

**Edit**
Issue 1 seems  to be because of ember-cli-conditional-compile. This is the issue: https://github.com/minichate/ember-cli-conditional-compile/issues/59

I am trying to find out if Issue 2 is related to this. But I believe the same thing happens. Does this mean we cannot exclude files from within an addon, in-repo or not? Is there another way we can exclude files/folders from the tree, from within an addon?

**Comment by locks** [comment]
Thank you for your detailed issue, and apologies for the long turnaround! From what I understand, this issue is no longer relevant. If I got that wrong please comment and reopen the issue and we can work on figuring out a path forward.
