### ISSUE TITLE
Provide a hash of test failures

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#8953]
When running `ember test` on a large test suite, it would be very useful to get a hash of all the failed tests. This way, it is useful to compare across builds if the *same* test cases are failing or if new failures were introduced.

**Comment by rwjblue** [comment]
You can configure your `testem.js` to emit an .xml file in addition to the normal TAP output.

**Comment by rwjblue** [comment]
Here is an example:

https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/d96e046c79a963bfee14f3789a6fe6c6a131e8e0/testem.js#L23-L25
