### ISSUE TITLE
`ember test` works in Linux, but doesn't on Windows

### ISSUE THREAD

**Issue by bguiz** [ember-cli/ember-cli#896]
With the same project folder on both Windows and Linux

When I run `ember server`, and visit `localhost:4200/tests`, I get the same results: tests run and give me the same results.

When I run `ember test`, I get different results: On Windows, a the tests crash before getting to the first one, but on Linux, they run through all fine. 

The error thrown is a little generic, and does not give any clue as to what went wrong.

---

Details:

On Windows:

```
version: 0.0.28
Built project successfully. Stored in "tmp\class-tests_dist-kJcdoBfe.tmp".

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

On Linux:

```
version: 0.0.28
Built project successfully. Stored in "tmp/class-tests_dist-7KLxb1TH.tmp".
[[Lots of PhantomJS/ QUnit output (1 line per test)]]
1..57
# tests 57
# pass  57
# fail  0

# ok
```

**Comment by samdelagarza** [comment]
same issue here.
