### ISSUE TITLE
Add new type of blueprint "custom project"

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#8960]
There are various custom project blueprints floating around

* https://github.com/tildeio/libkit
* `@glimmer/blueprint`
* `@ember/octane-app-blueprint` and `@ember/octane-addon-blueprint`

They were built by people that have intimate knowledge of how ember-cli detects a package that is also a blueprint. We can make it easier for people to make their own blueprints by baking the best conventions into a "blueprint of a custom project blueprint".

The blueprint would be similar to the addon blueprint with the following changes

* package.json keyword "ember-addon" => "ember-blueprint"
* README changes mentioning "ember install my-addon" => "ember init -b my-blueprint"
* Remove testing matrix and dummy app stuff
* perhaps add a "files/.gitkeep" file

**Comment by rwjblue** [comment]
ya, sounds good to me

**Comment by kellyselden** [comment]
We can probably wait until after octane to do this, as there will probably be a lot of blueprint trashing during the release.

**Comment by locks** [comment]
Closing as stale. It is unllikely that the team will have bandwidth to build this. If an enterprising community member is interested in giving it a proper go I can reopen.
