### ISSUE TITLE
Add Windows CI run to GitHub Actions Configuration

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#8973]
Moving to GH actions would significantly reduce our CI wait time (the AppVeyor queue is often very large), and reduce the number of false failures (the AppVeyor jobs fail after 60 minutes, and the VM's seem somewhat underpowered on the free plan).

**Comment by rwjblue** [comment]
@Turbo87 - When you landed the GH actions setup in #8949 did you _try_ to add Windows and it failed, or just didn't try it yet?

**Comment by Turbo87** [comment]
@rwjblue yeah, I did try and it did fail. about 40 tests were failing iirc, and they looked like similar issues to the ones we've been occasionally seeing on AppVeyor already.

**Comment by rwjblue** [comment]
I'm slowly working through some of these issues over on this branch: 

https://github.com/ember-cli/ember-cli/compare/windows-gh-actions

Hopefully, I can get the basic tests passing soon so we can lock things down...

**Comment by rwjblue** [comment]
Finished in https://github.com/ember-cli/ember-cli/pull/9086
