### ISSUE TITLE
Error after upgrading to ember-cli@3.15.1: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes

### ISSUE THREAD

**Issue by aklkv** [ember-cli/ember-cli#8980]
```bash
==========================================================================

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
    at new WatcherAdapter (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/broccoli/dist/watcher_adapter.js:21:19)
    at new Watcher (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/broccoli/dist/watcher.js:19:44)
    at Watcher.constructBroccoliWatcher (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/lib/models/watcher.js:42:19)
    at new Watcher (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/lib/models/watcher.js:28:41)
    at ServeTask.run (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/lib/tasks/serve.js:58:7)
    at /Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/aklkv/Projects/work/foodee/MasterFox/clients/swift-fox/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)


===========================================================================
```

**Comment by rwjblue** [comment]
What version were you upgrading from? Any hints on how to reproduce this?

**Comment by stevetyler** [comment]
We're seeing this as well for 3.4 and it started happening 2 days ago and it was fine beforehand.

`WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
AutoprefixerFilter: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (Merge Asset Manifest)
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/Users/stevetyler/Projects/bg/oam/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/stevetyler/Projects/bg/oam/node_modules/broccoli-merge-trees/index.js:16:10)
    at BroccoliMergeTrees (/Users/stevetyler/Projects/bg/oam/node_modules/broccoli-merge-trees/index.js:10:53)
    at generateAssetManifest (/Users/stevetyler/Projects/bg/oam/node_modules/ember-asset-loader/lib/generate-asset-manifest.js:59:10)
    at Class.postprocessTree (/Users/stevetyler/Projects/bg/oam/node_modules/ember-asset-loader/lib/manifest-generator.js:48:28)
    at projectOrAddon.addons.reduce (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/broccoli/ember-app.js:866:12)
    at EmberApp.host.addonPostprocessTree (/Users/stevetyler/Projects/bg/oam/node_modules/ember-auto-import/js/auto-import.js:108:20)
-~- (end) -~----------------

WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes`

**Comment by stevetyler** [comment]
```Error Summary

```ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes
    at new WatcherAdapter (/Users/stevetyler/Projects/bg/oam/node_modules/broccoli/dist/watcher_adapter.js:21:19)
    at new Watcher (/Users/stevetyler/Projects/bg/oam/node_modules/broccoli/dist/watcher.js:19:44)
    at Watcher.constructBroccoliWatcher (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/models/watcher.js:42:19)
    at new Watcher (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/models/watcher.js:28:41)
    at ServeTask.run (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/tasks/serve.js:58:7)
    at Promise.resolve.then (/Users/stevetyler/Projects/bg/oam/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/stevetyler/Projects/bg/oam/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/stevetyler/Projects/bg/oam/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/stevetyler/Projects/bg/oam/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/stevetyler/Projects/bg/oam/node_modules/rsvp/dist/rsvp.js:2441:7)

**Comment by JoeHartzell** [comment]
I'm having this same issue. I'm updating a very small application from 2.18 to 3.15, and faced the same build errors (specifically trying to use Octane). If I downgrade to 3.14 and run the steps to enable Octane the app builds without issues.

**Comment by fender-hm** [comment]
I have the same error, any ideas?

Downgrade to 3.14.0 is tmp fix.

**Comment by GCheung55** [comment]
I experienced this issue while upgrading as well. My app has an addon that was using `ember-browserify`. Updating the addon to use `ember-auto-import` addressed the error. I believe the reason is because `ember-browserify` was not extending from Broccoli Plugin. 

I’m guessing I’d you are using `ember-browserify` directly in your app you would experience this error too.

**Comment by cah-briangantzler** [comment]
Also having this problem. Upgrading from ember 3.14 to 3.15

**Comment by stevetyler** [comment]
I've pinned ember-cli to the same as ember-source in our package.json (3.4.3 in our case) and that's resolved the issue for us.

**Comment by cah-danmonroe** [comment]
We are upgrading from 3.14 to 3.15 ourselves and also see this issue.  We found by pinning ember-cli to 3.14 resolves warning for us.  We'll watch this issue before we upgrade ember-cli

**Comment by fender-hm** [comment]
Yesterday update ember-cli one more time (from 3.14 to 3.15.1), works perfect now. Looks like issue was fixed.

**Comment by kennydp** [comment]
I had the same issue. I had to update ember-cli-deprecation-workflow. This fixed the issue for me.

**Comment by cah-briangantzler** [comment]
ember-cli-deprecation-workflow 1.0.0 would not work. Dont remember why. left it at 0.2.x. Left ember-cli at 3.14 due to this issue. Above statements said ember-cli 3.15.1 fixed issue. When I upgraded ember-cli to 3.15.2 tests would not run until I upgrade deprecation workflow to 1.0.0, So now everything works and a more current release. 

Agree with `kennydp` you may have to upgrade deprecation workflow to get things to run

**Comment by rwjblue** [comment]
Hmm, I'm not quite sure what is going on here. Do we have a reproduction that I can look at?

**Comment by cah-briangantzler** [comment]
Now that 3.15.2 is out, its fixed, Im not sure if I could create an example since I think it 3.15.1 worked on a new build. I would have to dump my whole repo to know what addon or thing maybe I did that caused it.


Given that 3.15.2 does not have the issue, I think this could probably be closed

**Comment by cah-briangantzler** [comment]
Its been a while, but I just remembered we may have narrowed it down to one of these

    "broccoli-funnel": "^2.0.2",    // latest 3.0.1
    "broccoli-merge-trees": "^3.0.0",    // latest . 4.1.0

when we did ember-cli-update it updated a lot of things and we thought is was ember-cli 3.15.1 be we found if we backed off the above two it worked.

Let me see if it still fails

**Comment by cah-briangantzler** [comment]
Upgrading broccoli-funnel works, then upgrading broccoli-merge-trees works with 3.15.2. Did not retry various ways with 3.15.1 given that one should just update to 3.15.2

**Comment by spizzirri** [comment]
I have this package and I tried to update ember cli 2.18.2 to 3.15.2 but I suffered the same error.

Any idea? I need to help please. :(

```
  "devDependencies": {
    "@ember/optional-features": "^1.1.0",
    "@glimmer/component": "^1.0.0",
    "babel-eslint": "^10.0.3",
    "body-parser": "^1.19.0",
    "bootstrap-sass": "^3.3.7",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.5.3",
    "ember-bootstrap": "^1.0.0-rc.2",
    "ember-cli": "^3.15.2",
    "ember-cli-analytics": "^1.3.0",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.13.0",
    "ember-cli-chart": "^3.4.0",
    "ember-cli-clipboard": "^0.10.0",
    "ember-cli-cookie": "^0.2.0",
    "ember-cli-daterangepicker": "^0.9.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-eslint": "^5.1.0",
    "ember-cli-file-saver": "^1.2.4",
    "ember-cli-google-recaptcha": "^1.0.0",
    "ember-cli-htmlbars": "^4.2.0",
    "ember-cli-inject-live-reload": "^2.0.1",
    "ember-cli-moment-shim": "^3.7.1",
    "ember-cli-numeral": "^1.0.0",
    "ember-cli-sass": "^7.1.7",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.3",
    "ember-cli-testem-http-mocks": "^0.3.0",
    "ember-cli-uglify": "^3.0.0",
    "ember-component-css": "^0.6.3",
    "ember-data": "~3.15.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^7.0.0",
    "ember-file-upload": "^2.7.1",
    "ember-font-awesome": "^4.0.0-alpha.6",
    "ember-jwt-decode-shim": "^1.2.0",
    "ember-light-table": "^1.12.2",
    "ember-link-action": "0.0.38",
    "ember-load-initializers": "^2.1.1",
    "ember-maskmoney": "^0.4.4",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-modal-dialog": "^3.0.0-beta.0",
    "ember-model-validator": "^3.7.0",
    "ember-moment": "^7.5.0",
    "ember-poller": "^1.0.1",
    "ember-power-select": "^2.0.0-beta.2",
    "ember-qunit": "^4.6.0",
    "ember-resolver": "^7.0.0",
    "ember-responsive": "^2.0.4",
    "ember-responsive-tabs": "0.0.10",
    "ember-simple-auth": "^1.4.0",
    "ember-simple-auth-token": "^3.0.0",
    "ember-source": "~3.15.0",
    "ember-star-rating": "^3.0.0",
    "ember-truth-helpers": "^2.1.0",
    "ember-user-activity": "^0.10.0",
    "ember-welcome-page": "^4.0.0",
    "ember-world-flags": "^1.0.0",
    "eslint-plugin-node": "^10.0.0",
    "express": "^4.16.4",
    "glob": "^4.5.3",
    "jquery-maskmoney": "^3.0.2",
    "loader.js": "^4.7.0",
    "morgan": "^1.9.1",
    "qunit-dom": "^0.9.2"
  },
  "engines": {
    "node": "8.* || >= 10.*"
  },
  "ember": {
    "edition": "octane"
  },
  "dependencies": {
    "@types/bignumber.js": "^5.0.0",
    "bignumber.js": "^8.1.1",
    "ember-inputmask": "^0.8.5",
    "handsontable": "^6.2.0",
    "moment": "^2.19.2"
  }
```

WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Object: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to BroccoliMergeTrees (TreeMerger (vendor))
..............................


WatcherAdapter's first argument must be an array of SourceNodeWrapper nodes

**Comment by patricklx** [comment]
just hit this problem as well.
turns out its because of returning something like `mergeTrees([app.toTree(), bootstrap])` in ember-cli-build.js

**Comment by Lucie-H** [comment]
In case it helps anyone: I got this error message despite having updated ember-cli and it disappeared after replacing the deprecated ember-browserify with ember-auto-import.

**Comment by aklkv** [comment]
Yeah I think the root cause it ember browserify. I am closing this issue, there is nothing else to be solved.

**Comment by TangoYankee** [comment]
I encountered this error when upgrading ember-cli from `3.14.0` to `3.15.0`. Resolving it appears to require auditing your application for any packages that uses the [deprecated Broccoli-related API](https://github.com/ember-cli/ember-cli/issues/8198). This applies to both direct and indirect dependencies. As these graphs are notoriously chaotic, I personally used the GitHub Dependency Graph search to find (possibly) affected packages and versions. Because my application uses `yarn` we are able to use a `resolutions` field in the `package.json` to tell our dependencies to use certain minimum versions of packages. 

From scouring the internet for other folks encountering the same issues, the suspect list of affected packages (inclusive of this thread) includes:
- [broccoli-plugin](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-442018303)
- [broccoli-persistent-filter](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-442008543)
- [ember-cli-htmlbars](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-442008543)
- [ember-yaml-cms](https://github.com/jholt1/ember-yaml-cms/issues/7#issue-431024933)
- [broccoli-babel-transpiler](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-442014901)
- [ember-browserify](https://github.com/ember-cli/ember-cli/issues/8980#issuecomment-570446802)
- [broccoli-templater](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-443513243)
- [ember-cli-emblem](https://github.com/ember-cli/ember-cli/issues/8198#issuecomment-448979133)

**Comment by kboucher** [comment]
I received this error when upgrading from 3.12.0 to 3.16.2. Removing `ember-browserify` got me past that error.
