### ISSUE TITLE
Remove/deprecate ember-cli-template-lint

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#8982]
I've been removing `ember-cli-template-lint` from our apps and updating the `npm test` script to run `npm run lint && ember test` instead. It might be a good idea to make these changes in the blueprint also.

https://github.com/ember-cli/ember-cli/blob/v3.15.1/blueprints/app/files/package.json#L34

**Comment by rwjblue** [comment]
This will be done as part of implementing https://github.com/ember-cli/rfcs/pull/121 (which moved to the emberjs/rfcs repo here https://github.com/emberjs/rfcs/blob/master/text/0121-remove-ember-cli-eslint.md).

**Comment by mehulkar** [comment]
ahh, beaut. feel free to close this issue then. i just noticed it was still there when I started a new app with 3.15 yesterday.

**Comment by happycollision** [comment]
See also what I discovered in #9005 (even though I closed it after further investigation). TLDR: `broccoli-lint-eslint` (a dep of `ember-cli-eslint`) is holding `eslint` back in the 5.x version.

**Comment by rwjblue** [comment]
Done!
