### ISSUE TITLE
After upgrading to ember 3.15 generating glimmer components adds templates to wrong folder

### ISSUE THREAD

**Issue by Nippius** [ember-cli/ember-cli#8987]
Hi! 

After updating my app to ember 3.15.1 and upgrading all my components to glimmer components
I was expecting that, when generating a new component, it would automatically create a new glimmer component with the templates inside the component folder.

Instead, generating a new component creates a regular component (extends from @ember/component and the template is created in the templates folder).
Is there any flags I need to set to activate the new behaviour? When creating a new application using `ember new my-app` this works correctly.

## Reproduction steps:

* `git clone https://github.com/Nippius/digitalillusion-frontend.git`
* `cd digitalillusion-frontend`
* `npm install`
* `ember generate component xpto`

Notice how the template is created on the wrong folder and a component class is created:
![image](https://user-images.githubusercontent.com/1528640/71384238-290b6e00-25d8-11ea-9aa6-4b13f82e005d.png)

## Things I've tried

* Using -gc flag has no effect (`ember generate component xpto -gc`)
* Adding `"componentStructure": "flat"` to .ember-cli puts the templates in the correct folder but the class is always generated and it also extends from `@ember/component` instead of `@glimmer/component`

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.15.1
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: win32 x64
6.12.1
```

**Comment by chancancode** [comment]
What is your `ember-source` version and do you have the edition set in your package.json? (i.e. did you run `npx @ember/octanify`?

**Comment by Nippius** [comment]
Yes I did run that command :) 
`ember-source` is at version 3.15.0 and the edition is set to "octane"

![image](https://user-images.githubusercontent.com/1528640/71386533-71ca2380-25e6-11ea-86e5-009b8d2d466e.png)

**Comment by chancancode** [comment]
Can you run `yarn why @ember/edition-utils`?

**Comment by Nippius** [comment]
Sure, here's the output:

```
yarn why v1.21.1
[1/4] Why do we have the module "@ember/edition-utils"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@ember/edition-utils@1.2.0"
info Reasons this module exists
   - "ember-cli-htmlbars" depends on it
   - Hoisted from "ember-cli-htmlbars#@ember#edition-utils"
   - Hoisted from "ember-data#@ember#edition-utils"
   - Hoisted from "ember-source#@ember#edition-utils"
   - Hoisted from "ember-data#@ember-data#adapter#@ember#edition-utils"
   - Hoisted from "ember-data#@ember-data#debug#@ember#edition-utils"
   - Hoisted from "ember-data#@ember-data#model#@ember#edition-utils"
   - Hoisted from "ember-data#@ember-data#private-build-infra#@ember#edition-utils"
   - Hoisted from "ember-data#@ember-data#record-data#@ember#edition-utils"
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
Done in 1.05s.
```

**Comment by chancancode** [comment]
Hmm that is pretty odd. As you said, it definitely works on new apps. What does `ember g component --help` show?

**Comment by Nippius** [comment]
Odd indeed. At first I thought ember-cli was being smart and detecting my old style components but I've since updated everything and it still does it so I'm completely at a loss here.

This is the output of `ember g component --help`:

```
PS D:\Tiago\Projectos\DigitalIllusion\digitalillusion-frontend> ember g component --help

Requested ember-cli commands:

ember generate <blueprint> <options...>
  Generates new code from blueprints.
  aliases: g
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --pod (Boolean) (Default: false)
    aliases: -p, -pods
  --classic (Boolean) (Default: false)
    aliases: -c
  --dummy (Boolean) (Default: false)
    aliases: -dum, -id
  --in-repo-addon (String) (Default: null)
    aliases: --in-repo <value>, -ir <value>
  --in (String) (Default: null) Runs a blueprint against an in repo addon. A path is expected, relative to the root of the project.

      component <name> <options...>
        Generates a component.
        --path (String) (Default: components)
          aliases: --no-path (--path="")
        --component-class (@ember/component, @glimmer/component, @ember/component/template-only, "") (Default: @ember/component)
          aliases: -cc (--component-class=@ember/component), -gc (--component-class=@glimmer/component), -tc (--component-class=@ember/component/template-only), -nc (--component-class=""), --no-component-class (--component-class=""), --with-component-class (--component-class=@ember/component)
        --component-structure (classic) (Default: classic)
          aliases: -cs (--component-structure=classic)
```

Hmm maybe the defaults weren't updated? Could this be a cache issue? (unlikely since cloning the project on another computer has the same behaviour)
Anyway, using `-gc` isn't working (or it's being ignored).

**Comment by chancancode** [comment]
The default depends on the edition: https://github.com/emberjs/ember.js/blob/master/blueprints/component/index.js#L13

So I was thinking that this is caused by having an old version of editions utils that didn’t understand the package.json declaration, but it doesn’t seem to be the case. Do you think you can find this file in your `node_modules` and see if you can debug it further? (Either using a remote debugger or console.log). Alternatively if you can recreate a reproduction and push it to GitHub I can dig in.

**Comment by Nippius** [comment]
The file looks identical. I've added some console.log statements and it looks like the problem seems to be inside the `has()` function in `@ember/edition-utils` because it always returns `false` for line 54 `let isOctane = has('octane');`

After digging a little deeper into the `has()` function, I think I've found the problem. For some reason, npm installs `@ember/edition-utils: 1.1.1` instead of `@ember/edition-utils: 1.2.0`

This is the file I have in my project:
https://github.com/emberjs/ember-edition-utils/blob/7a7830602599236512c2a261b6b38846d1b6460e/index.js

And this is the file I have when creating a new ember app:
https://github.com/emberjs/ember-edition-utils/blob/master/index.js

Comparing the `package.json` file from my project to a new one, the only difference I can see is that I'm using `ember-cli-sri: ^2.1.0` instead of `ember-cli-sri: ^2.1.1`.

Is there a way to force `@ember/edition-utils` to be updated to the latest version?

As for reproduction, just clone my project and create a new component:

* git clone https://github.com/Nippius/digitalillusion-frontend.git
* cd digitalillusion-frontend
* npm install
* ember generate component xpto

**Comment by chancancode** [comment]
Hm so that actually matches my original suspicion, but for some reason `yarn why` reported the wrong version. I think this is probably a bug we should fix in ember-source (to require 1.2.0+) but in the meantime you can probably workaround the problem with a resolution rule in your package.json. cc @rwjblue

**Comment by chancancode** [comment]
You can probably also just run `yarn upgrade @ember/edition-utils` and inspect/commit the lockfile instead of using a resolution rule.

**Comment by Nippius** [comment]
It sounds like a bug indeed. If you need a way to repoduce, feel free to use my project (checkout commit dc0156b).

Having said that, running `yarn upgrade @ember/edition-utils` worked perfectly. Now `ember generate component` works as expected.

Thank you for the help!

**Comment by beerinho** [comment]
For anyone finding this and having an issue with the `ember generate component test -gc` command. It might be to do with ember-cli-typescript. Took a couple of hours to figure out so might be useful for anyone else finding this thread.

Link to ember-cli-typescript discussion - https://github.com/typed-ember/ember-cli-typescript/issues/1042
