### ISSUE TITLE
new addon (3.15.1) is failing most ember-try scenarios

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#9006]
```
Unable to satisfy placement constraints for Babel plugin @babel/plugin-proposal-decorators
```

It's strange that some of the jobs pass.

https://travis-ci.org/ember-cli/ember-addon-output/builds/627766032

Attached a screenshot in case the jobs get rerun.

<img width="1083" alt="Screenshot 2020-01-03 at 10 08 47" src="https://user-images.githubusercontent.com/602423/71717806-26e3b380-2e11-11ea-87c9-e40a8f221e90.png">

**Comment by rwjblue** [comment]
Working on well now https://travis-ci.org/ember-cli/ember-addon-output/builds
