### ISSUE TITLE
 ember-cli >= 3.15 or EMBER_CLI_BROCCOLI_WATCHER=true prior to 3.15 usage does not correctly print out errors

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#9007]
In 3.14, an app.import of a missing file was an immediate exit with an expected stack trace. In 3.15, it is now a hung build with a UnhandledPromiseRejectionWarning.

3.14 https://travis-ci.org/kellyselden/ember-cli-test-server/jobs/633006370#L624
3.15 https://travis-ci.org/kellyselden/ember-cli-test-server/jobs/633037017#L560

My test suite is intentionally causing this error, that's the only way I discovered this. Here is the line
https://github.com/kellyselden/ember-cli-test-server/blob/764e703573/test/index-test.js#L112
https://github.com/kellyselden/ember-cli-test-server/blob/764e703573/test/index-test.js#L61

**Comment by rwjblue** [comment]
Hmm, this is definitely odd. Not sure what we changed internally here to make this be an unhandled rejection now. :thinking:

**Comment by stefanpenner** [comment]
3.15 first enabled BROCCOLI_WATCHER by default, I believe that experiment fails to correctly print errors.

**Comment by stefanpenner** [comment]
Potentially introduced by https://github.com/ember-cli/ember-cli/pull/8666 and but enabled by default by https://github.com/ember-cli/ember-cli/pull/8906

**Comment by stefanpenner** [comment]
I'll dig into this, most likely in the AM. I'm about to head to the gym...

**Comment by stefanpenner** [comment]
some prep work, so we can fail the test on unhandled rejections: https://github.com/ember-cli/ember-cli/pull/9070

**Comment by kellyselden** [comment]
@stefanpenner Thanks a lot for digging!

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/9070
https://github.com/ember-cli/ember-cli/pull/9072
