### ISSUE TITLE
Usage with SWC

### ISSUE THREAD

**Issue by lstrzebinczyk** [ember-cli/ember-cli#9008]
Hello : )

I came across this project: https://github.com/swc-project/swc. If I understand it correctly, this is a babel drop-in replacement that grants ~18 times speedup. This is huge!

I'd love to know what you guys think of it and if it can be considered to be used with ember cli. 18x speedup would significantly improve my (and I think everybodies) life.

I don't quite think just adding it to package.json does the trick.

**Comment by xg-wang** [comment]
I think it depends on https://github.com/stefanpenner/broccoli-swc/issues/10

**Comment by lstrzebinczyk** [comment]
Interesting! Thank you for pointing it out, I'm closing this issue and will monitor the one you mentioned.
