### ISSUE TITLE
Ember live reload via SIGHUP?

### ISSUE THREAD

**Issue by paddor** [ember-cli/ember-cli#9019]
I'm working in Ubuntu Linux in a Parallels VM on macOS. My project directory is on a Parallels shared folder (`ubuntu-18.04-dev2 on /media/psf/ubuntu-18.04-dev2 type prl_fs (rw,nosuid,nodev,noatime,sync,ttl=250,share)`). Unfortunately this kind of FS does not support inotify, which means I have to restart `ember serve` after every change. This takes a lot of time, power, and even hangs after like 3 times.

Is there a way to tell Ember to reload the source files via a process signal like SIGHUP? That'd be super helpful. Like `killall -HUP ember`.

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.12.0
http_parser: 2.8.0
node: 10.17.0
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 5
openssl: 1.1.1d
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
os: linux x64
6.11.3
```

**Comment by rwjblue** [comment]
Sorry, nothing like this exists built in. I think it would be plausible to add, but it would take a bit of digging around to figure out the right place.

Going to close for now, but let me know if you are interested in picking it up and I can reopen.

**Comment by paddor** [comment]
Never mind. I've moved the project into the Linux VM and am using SSHFS to access it from macOS, which works pretty well.
