### ISSUE TITLE
Omit code for optional features that are turned off

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#9021]
Talked to @pzuraq and he mentioned that it's theoretically possible to strip out ember-source code that won't be used due to optional-features. This tooling would be great incentive for apps to invest in moving in the direction the core team/communities deems as the way forward. 

Not sure where this would happen, but opening here since it seems like a build time concern

**Comment by pzuraq** [comment]
This would actually currently happen in `ember-source`, since it is now an addon that builds itself and can have custom behaviors. I do think that could change with Embroider though, we would have to rely on Embroider's macro system instead, which I haven't dug _too_ deeply into yet.

**Comment by mehulkar** [comment]
Moved to other repo. Closing.
