### ISSUE TITLE
Template only not working

### ISSUE THREAD

**Issue by broerse** [ember-cli/ember-cli#9043]
In ember-cli before Octane I could overwrite an addon template. Like this: https://github.com/broerse/ember-cli-blog/blob/bootstrap4/app/components/page-numbers.hbs

Now I get this error: Note it states `hbs` does not contain a `default export`. 

`Uncaught (in promise) Error: 'myapp/components/page-numbers.hbs' does not contain a 'default export'. Did you forget to export the component class?`

https://github.com/mharris717/ember-cli-pagination/blob/master/app/components/page-numbers.js 
```
export { default } from 'ember-cli-pagination/components/page-numbers';
```

If changed to this the error goes away but it should not be necessary to change all addons like this. 
```
import test from 'ember-cli-pagination/components/page-numbers';
export default test;
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.16.0
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: win32 x64
6.13.7
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rwjblue** [comment]
With the colocated template feature there is no actual module for the `.hbs` file within `addon/components/*.hbs`. The prose in the RFC explains this better than I can so I'll quote it here:

From [this section](https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md#1-component-classtemplate-coupling):

> The JavaScript class and template of a component are not just related but fundamentally coupled. Together, they provide the whole implementation of the component. It is impossible to understand one of them without the other. When one file is changed, the other likely need to be updated as well. Placing these files physically far apart on the file system fails to communicate this tight coupling, in addition to causing a lot of inconveniences when navigating a project.
 
From [here](https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md#4-lack-of-single-import):

> First, within the addon folder, there is the component class and template. Having these files in the addon folder allow them to be imported from JavaScript (e.g. import FooBar from 'my-addon/components/foo-bar';) for subclassing. However, as mentioned above, this does not also bring along the component's template.
> 
> To avoid developers having to also import the template, the addon component blueprint sets the layout property on the component's class. At runtime, when Ember fail to find a template associated with the component, it will then fall back to this property.
> 
> Finally, it re-exports the component in the app folder, which is merged with the app's app folder, allowing the component to be resolved by the resolver and invoked from Handlebars.
> 
> This workaround gets the job done, but has several major drawbacks.
> 
> First, it adds a significant amount of boilerplate to addon components, which could be puzzling even to seasoned addon developers. In fact, the problem it solves is unique to addons – there is nothing wrong with using inheritance in apps – we just didn't think we could justify adding this amount of boilerplate to every app and putting them in Ember's "happy path".
> 
> Second, the layout property in classic component uses a feature in Glimmer VM called "late-bound layout", in which we must assume a different template for each instance of the component (the layout property can be set in init). This is fundamentally more difficult to optimize and excludes the component from key optimizations (and opportunities for future optimizations).
>
> Most importantly, Glimmer components do not have the equivalent of the layout property, meaning that addons (or components designed for inheritance in mind) cannot be written using Glimmer components today.
>
> To solve these problems once and for all, we need to change things such that component templates are automatically associated with their JavaScript class at build time, and importing the JavaScript class should result in a value that has this metadata associated with it, which needs to survive subclassing as well. Solving this problem is also essential for unblocking template imports.

**Comment by rwjblue** [comment]
The way to do this when using colocation is to extend the component, and provide your own colocated template. So in your specific case you'd do:

```js
// app/components/page-numbers.js

import PageNumbersComponet from 'ember-cli-pagination/components/page-numbers';

export default class CustomPageNumbersComponent extends PageNumbers {}
```

And:

```hbs
{{! app/components/page-numbers.hbs}}

Your custom template here...
```

**Comment by broerse** [comment]
@rwjblue Thanks for explaining. It is not enforced for doing this in the addon also works:

```
import test from 'ember-cli-pagination/components/page-numbers';
export default test;
```
Why is this allowed and `export { default } from 'ember-cli-pagination/components/page-numbers';` not?

Maybe the deprecation warning should be more like a deprecation and not an error, for now, it talks about a `.hbs` template not containing a `default export`.

```
Uncaught (in promise) Error: 'myapp/components/page-numbers.hbs' does not contain a 'default export'. Did you forget to export the component class?
```

**Comment by rwjblue** [comment]
> Why is this allowed and export { default } from 'ember-cli-pagination/components/page-numbers'; not?

It is in general, but you have to put it in the right place (`app/templates/components/page-numbers.js`).
