### ISSUE TITLE
[Editor:VSCode] Using decorators in native class syntax throws `experimentalDecorators` error

### ISSUE THREAD

**Issue by abhilashlr** [ember-cli/ember-cli#9050]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.16.0
npm: 6.9.0
yarn: 1.19.1
```

Attaching the error screenshot shared in Discord channel:
https://cdn.discordapp.com/attachments/480501885837770763/678548314391576599/unknown.png

The fix I applied:
https://github.com/microsoft/vscode/issues/28097

Based on `#dev-ember-cli` channel discussion, if this is something that needs to be addressed as mentioned in the above github link, we need to add a default `jsconfig.json` or `tsconfig.json` in the default `ember new <app-name>` command.

Alternatively, the suggestion is to turn on the same feature in VSCode's preferences. This needs to be informed to every developer though.

**Comment by rwjblue** [comment]
Properly configuring the editor is _always_ the responsibility of each developer 😸 

We should not add editor specific files to the new project blueprint. IMHO, vscode should do a better job of detecting when this support is already opted into (for example, we _already_ enable the experimental decorator support in eslint configuration).

**Comment by knownasilya** [comment]
This is an annoying thing, especially when demoing a new app setup to someone it makes things feel sloppy, incomplete and broken. Maybe we need a `--vscode` option
