### ISSUE TITLE
layout import is incorrect when generating a classic component in an addon

### ISSUE THREAD

**Issue by skaterdav85** [ember-cli/ember-cli#9066]
I created a component in a new addon with `ember g component modal -cc`.

This generated the following files using template colocation:

* `addon/components/modal.hbs`
* `addon/components/modal.js`

```js
// addon/components/modal.js
import Component from '@ember/component';
import layout from '../templates/components/modal';

export default Component.extend({
  layout
});
```

This produces the following error because the `layout` import isn't correct. 

<img width="1114" alt="Dummy" src="https://user-images.githubusercontent.com/687449/75493597-1eba7700-596f-11ea-9024-374994492f5a.png">

I don't know what the `layout` import should be though. I tried changing the import to the following but `undefined` is logged to the console.

```js
import Component from '@ember/component';
import layout from './modal';

console.log(layout); // undefined

export default Component.extend({
  layout
});
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.16.0
node: 13.8.0
v8: 7.9.317.25-node.28
uv: 1.34.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
os: darwin x64
6.13.6
1.21.1
```

**Comment by rwjblue** [comment]
The component generator comes from ember-source itself, would you mind filing this over there?

**Comment by skaterdav85** [comment]
Looks like there is already an issue there: https://github.com/emberjs/ember.js/issues/18719
