### ISSUE TITLE
Impossible to run `ember v` when there's a build error

### ISSUE THREAD

**Issue by entendu** [ember-cli/ember-cli#9067]
I had a build error, `Cannot read property 'ui' of undefined`. I attempted to see what version of `ember-cli` I was running, and got this output:

```
$ ember v
Cannot read property 'ui' of undefined


Stack Trace and Error Report: /var/folders/gc/[etc].log
An error occurred in the constructor for [snipped]
```

The version number was not returned. Can you not run `ember v` if there's a build error?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.15.1
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.12.0
1.21.1```

**Comment by stefanpenner** [comment]
`ember-cli@3.15.1 ` has a known issue that appears to be the same one you describe, the fix landed in 3.15.2: https://github.com/ember-cli/ember-cli/commit/9e904a97288c219adca35499479c51927a431737
