### ISSUE TITLE
Yarn 2 (berry) compatibility

### ISSUE THREAD

**Issue by bartocc** [ember-cli/ember-cli#9071]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.15.1
node: 12.13.1
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.12.1
2.0.0-rc.29.git.20200227.795ecc8e
```

Yarn 2 has a new installation strategy for Node, called Plug'n'Play. See https://yarnpkg.com/features/pnp.

I believe that ember-cli is not yet compatible with yarn pnp because of [PackageInfo.prototype. addDependencies](https://github.com/ember-cli/ember-cli/blob/master/lib/models/package-info-cache/package-info.js#L177)

I found this while porting my addon's repo to yarn 2. When running the addon's test, ember-cli complained about my addon having template or js files but not preprocessor for them, instructing me to add `ember-cli-htmlbars` or `ember-cli-babel` to my `dependencies`, which was already the case. See the error message below.

```
DEPRECATION: Addon files were detected in `/Users/julien/Projects/OSS/foobar/packages/my-addon/addon`, but no JavaScript preprocessors were found for `my-addon`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `my-addon`'s `package.json`.
```

I'll host a reproduction repo on github quickly.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/issues/8164 has a bunch of details around PnP support. Maybe we should update the title of that issue, and close this one?

**Comment by bartocc** [comment]
I completely missed #8164 ! I'll close this one and let you update the title of #8164 as you see fit 👍
