### ISSUE TITLE
output repos missing releases

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#9077]
Tracking issue since issues are disabled there.

https://github.com/ember-cli/ember-new-output/tree/v3.12.1
https://github.com/ember-cli/ember-addon-output/tree/v3.12.1
https://github.com/ember-cli/ember-new-output/tree/v3.14.0-beta.1
https://github.com/ember-cli/ember-addon-output/tree/v3.14.0-beta.1

**Comment by void-mAlex** [comment]
I saw there is also a beta.2 release that also missing

https://github.com/ember-cli/ember-new-output/tree/v3.14.0-beta.2
https://github.com/ember-cli/ember-addon-output/tree/v3.14.0-beta.2

**Comment by rwjblue** [comment]
@kellyselden - Feel free to push the tags, but I don't really consider this a bug per-se 🤔

We really should be migrating folks away from these output repos as the source of truth for ember-cli-update.

**Comment by kpfefferle** [comment]
Both https://github.com/ember-cli/ember-new-output and https://github.com/ember-cli/ember-addon-output still have 4.8.0-beta.0 as their latest release. These repos are linked to from the release notes, but the links haven't worked for 4.8 stable and 4.9 series. If these repose aren't intended to be a source of truth, maybe they should be removed from the release notes?

**Comment by bertdeblock** [comment]
Seems this has been fixed for a while for newer releases. Probably not worth the effort to try and fix it for old releases. Closing for now.
