### ISSUE TITLE
output repos missing v3.12.1

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#9078]
Tracking issue since issues are disabled there.

https://github.com/ember-cli/ember-new-output/tree/v3.12.1
https://github.com/ember-cli/ember-addon-output/tree/v3.12.1

**Comment by locks** [comment]
I know the tags are still missing but my question is whether it's still worth it at this point to backfill that?

**Comment by locks** [comment]
Closing as stale.
