### ISSUE TITLE
You attempted to overwrite the built-in helper "array"

### ISSUE THREAD

**Issue by aklkv** [ember-cli/ember-cli#9119]
After upgrading to latest ember-cli I get this error when using `array` helper 

`{{log (array 1 2 3)}}`

```
Error: Assertion Failed: You attempted to overwrite the built-in helper "array" which is not allowed. Please rename the helper.
```
---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.17.0
node: 13.11.0
v8: 7.9.317.25-node.29
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: darwin x64
6.13.7
1.22.4
```

**Comment by rwjblue** [comment]
Can you push up a demo repo? I'm not sure what is going on here, but I haven't seen that issue before (so maybe it is situational)...

**Comment by aklkv** [comment]
@rwjblue I figured this error is coming form one of the addon that uses alder version of `ember-composable-helpers` in particular `ember-cli-addon-docs`. At this point it's safe to close. Hopefully it will be fixed with this PR: https://github.com/ember-learn/ember-cli-addon-docs/pull/452

**Comment by rwjblue** [comment]
Thanks for following up!
