### ISSUE TITLE
Unable to read options of an addon in another addon

### ISSUE THREAD

**Issue by AravinthAro** [ember-cli/ember-cli#9133]
`ember version --verbose && npm --version && yarn --version`

```
ember-cli: 3.13.2
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
os: darwin x64
6.14.3
bash: yarn: command not found
```

Hi, I'm working on an addon to make svg icons, which reads it's dependent addon's option in included method for building icons. I assume index.js is the right file to add options for an addon. But I cannot read the options.

svg-addon/index.js
```
module.exports = {
  name: require('./package').name,
  included: function (app){
  //read app.options.iconList
 }
}
```

dependent-addon/index.js
```
module.exports = {
  name: require('./package').name,
  iconList:{
}
}
```

**Comment by bertdeblock** [comment]
I'm not sure if this is supported. Can't you just `require` the options from `dependent-addon`?

**Comment by bertdeblock** [comment]
I'm going to close this one for now, this seems like an very uncommon thing to do as well.
