### ISSUE TITLE
Ember build output is not deterministic

### ISSUE THREAD

**Issue by stukalin** [ember-cli/ember-cli#9187]
It has begun recently presumably after we've upgraded to 3.17.

The problem is that the output, i.e. bundles which are produced by the `ember build` (specifically `ember build --prod` sometimes have different structure, i.e. the output is not deterministic. 

The reproducing might be tricky since it's like playing dices or something, but here are some basic steps:
- create a new app with `ember init --yarn --no-welcome`
- install `macro-decorators` package `yarn add macro-decorators --dev` (hardly the package matters here, but we need something to "feed" the auto-import/webpack; without it the webpack doesn't produce the `vendors~app` chunk)
- create a new component `ember g component test-compunent -gc`
- edit this component as

```
import Component from '@glimmer/component';
import {tracked} from '@glimmer/tracking';
import {reads} from 'macro-decorators';

export default class TestCompunentComponent extends Component {
    @tracked name;
    @reads('name') anotherName;
}
```
- now run `ember b --prod`

The non-deterministic sections are related to the `ember-auto-import` and its webpack output. I cannot say for sure if that's an issue of the `ember-auto-import` that's probably something you might have a better guess than me.

Anyways, we can clearly see that this block of the code is simply shifted in these 2 outputs
![image](https://user-images.githubusercontent.com/9863365/80068804-e7b8aa00-8548-11ea-9e95-e4ccb494876f.png)

and

![image](https://user-images.githubusercontent.com/9863365/80068819-ee472180-8548-11ea-80cb-d75edbb5feae.png)

_Some funny observation: I absolutely have no idea how this happens but it seems like the `ember-cli` tends to produce the same output depending on the path the source sits in. For instance, if you look at my screenshots the left-hand folder seems to **most likely** produce that output which is depicted and same goes for the right-hand side folder. (Took me almost the whole day yesterday to understand that it's not always the case and the problem is not with my PC; I proved that by writing a small script which runs 10 times in a row and prints the output)._

Questions:
- Is that a bug? It may seem to be 'not a big deal' because it's simply the same codeblock shifted in the file, but it's definitely has different filename because of fingerprinting and the CDN will think it's a new resource when it's not, so I'd answer to that as yes.
- It seems like some parallelism takes place (not sure where). Is there any way to disable that even by sacrificing some build speed?

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.17.0
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
os: win32 x64
6.12.0
1.22.4
```

**Comment by stukalin** [comment]
Ok, it's really the `ember-auto-import` and the webpack config. I've created a separate issue in their repo and referenced it here. A temporary workaround would be to add the following in the project's `ember-cli-build.js`

```
   ...other config,
    autoImport: {
      webpack: {
        output: {
          filename: 'chunk.[id].[chunkhash].js',
          chunkFilename: 'chunk.[id].[chunkhash].js',
        },
      }
    }
```

**Comment by acorncom** [comment]
Looks like this issue can be closed now?

**Comment by stukalin** [comment]
@acorncom yep, you're totally right!
