### ISSUE TITLE
Finding a scoped addon via its unscoped name is deprecated issue

### ISSUE THREAD

**Issue by abishek-srinivasan** [ember-cli/ember-cli#9213]
I am using ember-cli version "3.4.0" ember-auto-import version "1.5.2" and my ember-cli-code-coverage is "1.0.0-beta.8", and trying to import highcharts dynamically. I am able to achieve that. I wrote the test cases for it but in my jenkins build, I am facing this error,

Trace: Finding a scoped addon via its unscoped name is deprecated. You searched for `test-helpers` which we found as `@***/test-helpers` in '***'
    at findAddonByName (***)
    at Project.findAddonByName (***)ember-cli version 3.4.0. 

Checked about the error and found https://github.com/ember-cli/ember-cli/pull/8964/files had the fix. But I can find this fix only above ember-cli 3.15 versions. Updating my ember-cli version to 3.15 is the only solution available to overcome this error or is there something that I could do with my current version??

**Comment by rwjblue** [comment]
ember-cli@3.4 is definitely unsupported, there are a number of bugs/errors in it that have been addressed on newer versions. I'd suggest updating to ember-cli@3.12 or ember-cli@3.16, which should both properly support scoped addons. I'm not really sure there is much we can do here (even if we do discover there was a bug in 3.4, we wouldn't be able to fix it for you) 🤔
