### ISSUE TITLE
helper test blueprint not Octane compliant

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#9224]
`ember g helper my-helper`

generates a test with this line in it:
```await render(hbs`{{escape inputValue}}`);```

This should instead read
```await render(hbs`{{escape this.inputValue}}`);```

**Comment by kennethlarsen** [comment]
The blueprint for the helper tests are in `ember-source` and not in `ember-cli`: https://github.com/emberjs/ember.js/tree/master/blueprints/helper-test

**Comment by rwjblue** [comment]
Ya, would absolutely love a PR for this over in ember-source repo (where @kennethlarsen linked above). 

Closing for now, as there isn't much we can do here and GH doesn't let me transfer issues between orgs yet...
