### ISSUE TITLE
Unknown feature "default-async-observers" found in config/optional-features.json

### ISSUE THREAD

**Issue by Unkrass** [ember-cli/ember-cli#9226]
Since upgrading from ember-cli 3.9 to 3.18 I get the following error when serving ember:

`Unknown feature "default-async-observers" found in config/optional-features.json`

Can you please help me to get rid of this problem? We rather urgently need to upgrade ember-data to resolve another issue with receiving a new id from the backend that has already been used by another record in Ember's store.

I cannot even generate the output from `ember version --verbose && npm --version && yarn --version` because ember won't do anything.

Ember is 3.18, Node is v12.16.1, yarn is 1.22.4

The problem also seems to exist when upgrading to ember-cli 3.17, as described [here](https://github.com/Semantic-Org/Semantic-UI-Ember/issues/261)

**Comment by Unkrass** [comment]
@richard-viney `@ember/optional-features` is at 1.3.0

When serving ember, I still get:
````
Unknown feature "default-async-observers" found in config/optional-features.json

An error occurred in the constructor for @ember/optional-features at /Users/<user>/<project>/node_modules/semantic-ui-ember/node_modules/@ember/optional-features

An error occurred in the constructor for semantic-ui-ember at /Users/<user>/<project>/node_modules/semantic-ui-ember
````

Maybe I have to backpedal and this might really be an issue with Semantic-UI-Ember (see link in my original comment). I am running out of options where to debug.

**Comment by richard-viney** [comment]
Ah, `semantic-ui-ember` specifies `"@ember/optional-features": "^0.7.0"` in its `package.json`. That needs to be updated and the problem should go away.

You can also override the dependency resolution in your `package.json` which should fix the issue while waiting for the Semantic UI package to be updated. See https://classic.yarnpkg.com/en/docs/selective-version-resolutions/ for details, it may be something like:

```json
  "resolutions": {
    "semantic-ui-ember/@ember/optional-features": "^1.3.0"
  }
```

I don't think this is an Ember CLI problem, so if the above sorts it out this issue can probably be closed.

**Comment by Unkrass** [comment]
Stunning. I don't know why I didn't think of checking the dependency in semantic-ui-ember. Thank you. Especially for teaching me about resolutions. This will bring our project a lot further because we have other indirect dependency issues and some of them aren't even maintained anymore (like semantic-ui-ember)
