### ISSUE TITLE
[Feature Request] Allow namespaced generation inside non-root folder

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli#9228]
It will be greate to have same behavour as in `angular-cli`, especially for complex projects (with nested addons/routes)

- calculate namespace automatically

for example, instead of 
```
cd project-root
ember g component foo/bar/baz

-> project/root/components/foo/bar/baz.hbs
```

allow
```
cd project-root/components/foo/bar
ember g component baz

-> project/root/components/foo/bar/baz.hbs
```

**Comment by rwjblue** [comment]
I'm not opposed to doing this. I don't think it's particulary common to have changed into a project subdir, but if you have _and_ that subdir happens to be the right place for the thing you are generating: seems fine to do that.

**Comment by rwjblue** [comment]
Since each blueprint decides what files to emit, this will likely have to be changed in each blueprint.

**Comment by lifeart** [comment]
@rwjblue I know developers, who has up to 5 nested engines, and they don't use blueprints at all, because of crazy paths

**Comment by lifeart** [comment]
current blueprints handy only for first level, if we dealing with in-repo addons/engines, things getting worse and worse

**Comment by lifeart** [comment]
example: https://github.com/catz/eng-test/tree/master/lib/wall/lib/viewer
cc: @catz

**Comment by lifeart** [comment]
@rwjblue how about allowing users run `ember` under in-repo addons itself?

allow: 
```
app-root: ember g component foo-bar
-> app-root/components/foo-bar.hbs

app-root/lib/my-addon: ember g component foo-bar
-> app-root/lib/my-addon/addon/components/foo-bar.hbs

app-root/lib/my-addon/lib/my-engine: ember g component foo-bar
-> app-root/lib/my-addon/lib/my-engine/components/foo-bar.hbs

```

**Comment by rwjblue** [comment]
> @rwjblue I know developers, who has up to 5 nested engines, and they don't use blueprints at all, because of crazy paths 

Sure, I definitely wasn’t saying it never happens. Just that it is generally uncommon in my experience.

**Comment by locks** [comment]
The conversation seems to be heading into RFC territory with the thornines of the topic. Would be interesting to see a solid proposal on how to tackle this in a general way.
