### ISSUE TITLE
Add ember-cli-update.json file to new app / addon blueprint?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#9237]
Now that ember-cli-update will honor this file by default, I think we should add it to the default blueprints. Without it, using ember-cli-update is a bit annoying in a world with dependabot / renovate / green keeper.

Thoughts?

**Comment by Turbo87** [comment]
what does it do?

**Comment by rwjblue** [comment]
@turbo87 - Sorry, I should have mentioned in the initial description, basically it is the result of [emberjs/rfcs#477](https://github.com/emberjs/rfcs/blob/master/text/0477-blueprints-update.md). It instructs `ember-cli-update` to use this config file to determine the last `ember-cli` blueprint version to use for the "from" version when determining the diff for updating. Without this config file ember-cli-update will look into the `package.json` to see the `ember-cli` version to compute its "from" for the diff. Unfortunately, that means that ember-cli-update is kinda broken when you bump the `ember-cli` version without _also_ doing the blueprint update.
