### ISSUE TITLE
Failure when serving / building an ember app

### ISSUE THREAD

**Issue by tobiemh** [ember-cli/ember-cli#9245]
Since the upgrade to [`ember-cli-babel@7.20.1`](https://github.com/babel/ember-cli-babel/commit/5161e5b738ac54ef389aefbd3249cb7564f72d27), I'm receiving the following error:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @glimmer/component]) in @glimmer/component/-private/ember-component-manager.ts

/Users/user/Repositories/test/@glimmer/component/-private/ember-component-manager.ts: Property id of TSDeclareFunction expected node to be of a type ["Identifier"] but instead got "MemberExpression"
```

To reproduce:

```
npm cache clean --force
ember new tester
cd tester
ember serve
```

This is also happening on already existing ember projects:

```
rm -rf node_modules package-lock.json
npm install
ember serve
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.18.0
node: 14.3.0
v8: 8.1.307.31-node.33
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0
os: darwin x64
6.14.4
1.22.4
```

I have also tried this with `node@12.13.0`

**Comment by tobiemh** [comment]
Ah this has already been posted in the ember.js repo:

https://github.com/emberjs/ember.js/issues/18995

**Comment by rwjblue** [comment]
https://github.com/babel/ember-cli-babel/releases/tag/v7.20.2 is out with the fix for the TS issue (thank you @fivetanley!).
