### ISSUE TITLE
[docs] server middleware

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#9258]
This used to exist in https://ember-cli.com/user-guide/#developing-on-a-subpath but currently doesn't exist on the new docs anymore. 

<img width="1094" alt="Screen Shot 2020-06-24 at 12 21 31 PM" src="https://user-images.githubusercontent.com/1854811/85618175-4071f500-b615-11ea-80c9-bf98cad97c76.png">

https://cli.emberjs.com/release/basic-use/folder-layout/ also doesn't mention the server folder as being something that is optional part of creating an app or addon.

**Comment by rwjblue** [comment]
@gabrielcsapo - Can you move this over to https://github.com/ember-learn/cli-guides ?

**Comment by gabrielcsapo** [comment]
@rwjblue I moved it to https://github.com/ember-learn/cli-guides/issues/188. Thank you.
