### ISSUE TITLE
JS source map stopped working in Chrome developer tools

### ISSUE THREAD

**Issue by arkadiyk** [ember-cli/ember-cli#926]
After I upgraded from 0.0.27 to 0.0.29 I see only singe concatenated app-name.js in Chrome inspector.
Do I need to make any config changes to make the source map work again?

**Comment by stefanpenner** [comment]
FYI as of 0.1.5 we have basic but real source map support.

**Comment by indirect** [comment]
I just noticed. :) hooray!

**Comment by mansona** [comment]
@stefanpenner much :heart: :+1:
