### ISSUE TITLE
Production builds takes a lot of time to print compression stats

### ISSUE THREAD

**Issue by rajasegar** [ember-cli/ember-cli#9260]
If the build assets are larger then printing the compression statistics like gzipped sizes is taking time since all the assets are serially processed by compressing using `gzip` and then printing the size. Can we make this faster by making it run concurrently or spawning multiple processes for the same? I see some room for optimization there.

## Why?
- We can make use of the multiple cores present in a machine to do faster builds.
- This will eventually result in quicker prod builds and faster deployments.

@rwjblue What are your thoughts?

**Comment by rwjblue** [comment]
Ya, we can definitely do that. Seems good to me.
