### ISSUE TITLE
[feature] output tmp directory

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#9261]
When running an ember serve or build there is no easy way to see the tmp directory. It would be great when the build is completed it would show which tmp directory is being used.

**Comment by rwjblue** [comment]
This is possible via a few different hooks already. I'd probably use `postBuild`.

**Comment by gabrielcsapo** [comment]
@rwjblue I was hoping this could be a part of the default ember-cli build and serve output.
