### ISSUE TITLE
I am always getting error "You cannot use the new command inside an ember-cli project."

### ISSUE THREAD

**Issue by takshch** [ember-cli/ember-cli#9285]
### Error : `You cannot use the new command inside an ember-cli project.`
----
Screenshot:
![ember-cli-problem2](https://user-images.githubusercontent.com/26649558/88317242-9df18280-cd36-11ea-9369-2faf70dcbace.png)

---
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.19.0
node: 12.18.2
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: linux x64
6.14.5
1.22.4
```

**Comment by rwjblue** [comment]
Most likely there is a `package.json` either in `~/Desktop` or somewhere above there that lists `ember-cli` as a dep/devDep.

**Comment by takshch** [comment]
@rwjblue  I found package.json and package-lock file in home of the my ubuntu. I just removed these 2 files and it worked.
### It is better to open an issue on GitHub instead of wasting lots of hours.  
Thanks `Robert Jackson` for the `help`.

**Comment by rwjblue** [comment]
Glad you got to the bottom of it!
