### ISSUE TITLE
Trying To Install Ember CLI Results In Error

### ISSUE THREAD

**Issue by l33z3r** [ember-cli/ember-cli#9301]
Running a simple `npm install -g ember-cli` seems to throw an error related to a missing package:

Not Found - GET https://registry.npmjs.org/@cnakazawa%2fwatch - Not found

Anyone see this error?

**Comment by sputnik-adam** [comment]
Encountering the same problem at the moment. Curiously, the error for that package suddenly disappeared and has been replaced with

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sindresorhus%2fis - Not found
npm ERR! 404 
npm ERR! 404  '@sindresorhus/is@^0.7.0' is not in the npm registry.
```

**Comment by sputnik-adam** [comment]
Looks like npm are having issues: https://status.npmjs.org/

I'm getting Not Found errors for different packages. Looks like they need some time to fix the problem.

**Comment by l33z3r** [comment]
Ah, yes, that would be it

**Comment by rwjblue** [comment]
Indeed!

Going to close this for now though, not much we can do (other than wait it out) it seems.
