### ISSUE TITLE
[feature] expose functionality and data from ember-cli via /graphql endpoint

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#9326]
Having this as something as supported via ember-cli itself would allow functionality in projects like;

- https://github.com/rajasegar/ember-cli-ui
- https://github.com/gabrielcsapo/broccoli-inspector

The idea was brought up here https://twitter.com/stefanpenner/status/1301288417376890881?s=20.

## Summary

Using the ember-cli middleware, we can expose a set of functions and models that you can query to build experiences against ember-cli as a middleware package. This issue is basically to brainstorm ideas on what that functionality and data would be.

**Comment by rwjblue** [comment]
Seems good, though I think an actual proposal is needed as a path forward (likely as an RFC).

**Comment by bertdeblock** [comment]
Seems like a neat idea, but going to close this one for now, because of the comment above.
