### ISSUE TITLE
Prevent foot-guns when customizing index.js

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9334]
For example, let's say you want to add 
```
options: {
  autoImport {
    // some config
  }
}
```

it seems that if another addon specifies those options, whichever is loaded last wins.

so, it'd be great if ember-cli could either warn/hard-error when there is a conflict in `options` _or_, forbid the setting of options for other addons within your addon (I recognize that a deep merge of all options wouldn't be predictable, because there isn't a good way to guarantee order).

If this is already supported, then there are other foot guns I've yet to track down :(

**Comment by rwjblue** [comment]
I don't understand the issue, let's focus on the actual problem that you faced (not the general case of attempting to prevent all footguns). What did you have specified in your `index.js`? What didn't work?

**Comment by NullVoxPopuli** [comment]
the full index.js was:
```js
module.exports = {
  name: require('./package').name;
  options: {
    // but i'm not sure if specifics matter
    autoImport {
       ['splunk-sdk']: 'splunk-sdk/client/splunk',
    },
    skipBabel: [
      {
        // options for above package
      }
    ]
  }
}
```

_but_ in both the dummy app and all consuming apps the autoImport config acted as if it wasn't there. (error thrown when trying to import a specific module, splunk-sdk)

what did work was the exact same `autoImport` config, but in ember-cli-build.js.

Knowing that, to get things working, I deleted the `options` object, and used the `included` hook to find the root project and install / merge the autoImport config on that.

**Comment by NullVoxPopuli** [comment]
Code used for `included` hook:

```js
  included() {
    let app = this._findRootApp();

    let autoImport = app.options.autoImport || {};

    app.options.autoImport = {
      ...autoImport,
      alias: {
        ...(autoImport.alias || {}),
        ['splunk-sdk']: 'splunk-sdk/client/splunk',
      },
      skipBabel: [
        ...(autoImport.skipBabel || []),
        { package: 'splunk-sdk', semverRange: '*' }
      ]
   };

    this._super.included.apply(this, arguments);
  },

  _findRootApp() {
    let current = this;

    while (current.parent.parent) {
      current = current.parent;
    }

    return current.app;
  },
```

**Comment by rwjblue** [comment]
You basically can't use `options` like that as far as I can tell. 

https://github.com/ember-cli/ember-cli/blob/8ce28a9cbfd431b1da591b3c5d9cc180cfeef448/lib/models/addon.js#L329-L331

I would expect you need to do:

```js
module.exports = {
  name: require('./package').name,

  init() {
    this._super.init.apply(this, arguments);

    this.options.autoImport = {
      alias: {
        'splunk-sdk': 'splunk-sdk/client/splunk',
      },
      skipBabel: [
        ...(autoImport.skipBabel || []),
        { package: 'splunk-sdk', semverRange: '*' }
      ],
    };
  }
}
```

Can you confirm that works properly?

**Comment by chrismllr** [comment]
@rwjblue Ah, so in the above, would the apps options then be deep-merged on top of the `this.options.autoImport` above? This looks nice for instance where the host app's options don't need to be referenced to decide what to add in.

**Comment by NullVoxPopuli** [comment]
@rwjblue why can't I use `options`? I just successfully uses `options` in addons to set `ember-cli-babel` to enable typescript transpiling. Is there a difference between ember-cli-babel and auto-import options? or are not all options treated the same?

**Comment by locks** [comment]
@NullVoxPopuli issue still relevant/warranted?

**Comment by NullVoxPopuli** [comment]
Nope, none of these problems exist with v2 addons
