### ISSUE TITLE
[question] utilizing workers for addon discovery

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#9342]
I just wanted to know if it was something that would be supported for addon-discovery and addon-initialization to use a worker pool to utilize more system resources for a faster experience?

**Comment by rwjblue** [comment]
Off the top of my head, I don't think it would make much difference. Happy to entertain a PR with some measurements, but overall I'd expect workers to help if we were CPU bound but I'd be surprised if that was the case here. Again, happy to review results of investigation...

**Comment by rwjblue** [comment]
going to close for now, I don't think this is a CPU bound operation (its mostly IO, which I don't think will be helped by leveraging workers)...
