### ISSUE TITLE
Renaming .ts or .js requires restart

### ISSUE THREAD

**Issue by rsmith-cs-ux** [ember-cli/ember-cli#9345]
Hi there!

While running `ember s`, whenever I generate a new component everything works just fine and the changes are automatically detected.  But when I rename the file from `.js` to `.ts` (because I'm using typescript) I have to restart the server because the changes break everything.  It would be great if it could detect the change and handle it properly.

Thanks!

**Comment by rwjblue** [comment]
This sounds like an issue with ember-cli-typescript to me. Also, I think that when you run `ember generate component` you can have it emit `.ts` files (if you have the ember-cli-typescript-blueprints addon installed).

Can you file an issue over there, and cross link back here? Feel free to ping me in that issue, I definitely want to make sure we get to the bottom of things...
