### ISSUE TITLE
RFC #645 | Add ember-page-title to the app blueprint

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#9370]
As [RFC #645](https://github.com/emberjs/rfcs/blob/master/text/0645-add-ember-page-title-addon.md) has been accepted, the next step is to implement this.

The changes necessary to this repo as per [the RFC](https://github.com/emberjs/rfcs/blob/master/text/0645-add-ember-page-title-addon.md#detailed-design) are:
https://github.com/emberjs/rfcs/blob/master/text/0645-add-ember-page-title-addon.md#detailed-design

1. Add the dependency to the [app blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L19)
1. Update route blueprint to include `{{page-title RouteName}}` at the top of the route template.hbs (this template.hbs too) where `RouteName` is the name of the route provided to the ember generate route command

**Comment by raido** [comment]
ember-page-title needs patch version bump in blueprints before this can be closed - https://github.com/ember-cli/ember-page-title/issues/195#issuecomment-716816938
