### ISSUE TITLE
Build fails when npm dependencies `require('fs')`

### ISSUE THREAD

**Issue by artsyca** [ember-cli/ember-cli#9385]
This is one of those gnarly edge or corner case issues that only affects a small number of people at the most inopportune moments, I'm very grateful to any assistance.

Attempting to install a node package which internally requires `fs` (e.g. code that serves a server-side purpose) causes the build to fail.

Steps to reproduce, using the package https://github.com/grimmdude/MidiWriterJS as an example

1. `yarn add midi-writer-js` // succeeds
2. `import MidiWriter from 'midi-writer-js';` in any controller/component etc
3. Build fails with

```bash
ERROR in ./node_modules/midi-writer-js/build/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/alex/Code/ember-drumming/node_modules/midi-writer-js/build'
 @ ./node_modules/midi-writer-js/build/index.js 1474:15-28
 @ /private/var/folders/j9/r67c___n7n58t5lfz3q96lzh0000gn/T/broccoli-77203ztEDFL55YBSZ/cache-271-bundler/staging/app.js
 @ multi /private/var/folders/j9/r67c___n7n58t5lfz3q96lzh0000gn/T/broccoli-77203ztEDFL55YBSZ/cache-271-bundler/staging/l.js /private/var/folders/j9/r67c___n7n58t5lfz3q96lzh0000gn/T/broccoli-77203ztEDFL55YBSZ/cache-271-bundler/staging/app.jsBuild Error (Bundler)

webpack returned errors to ember-auto-import


Stack Trace and Error Report: /var/folders/j9/r67c___n7n58t5lfz3q96lzh0000gn/T/error.dump.34ca33ad64ce8952f5b55dfa8b1d0bd9.log
```

The code in question:

```js
...
  }, {
    key: "saveMIDI",
    value: function saveMIDI(filename) {
      var fs = require('fs');

      var buffer = new Buffer.from(this.buildFile());
      fs.writeFile(filename + '.mid', buffer, function (err) {
        if (err) throw err;
      });
    }
  }]);
...
```

Apparently this issue can be remedied by updating the webpack config as suggested here and many other places when searching for issues containing `Can't resolve 'fs'`

https://github.com/webpack/webpack/issues/11064

But I'm wondering what is the Ember-CLI way of handling this idiomatically so to speak? Is there a webpack config somewhere under the hood?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.22.0
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: darwin x64
6.14.8
1.22.10
```

**Comment by loganrosen** [comment]
Please see [this entry](https://github.com/ef4/ember-auto-import#global-is-undefined-or-cant-find-module-path-or-cant-find-module-fs) in `ember-auto-import`'s FAQ.

**Comment by artsyca** [comment]
Very helpful and well appreciated! Works marvellously. The key is to add the entry into the new EmberApp call as instructed by the link

```js
let app = new EmberApp(defaults, {
  autoImport: {
    webpack: {
      node: {
        global: true,
        fs: 'empty'
      }
    }
  }
```
