### ISSUE TITLE
Add support for Node v15

### ISSUE THREAD

**Issue by halfbusy** [ember-cli/ember-cli#9386]
In keeping with ember-cli's [node support policy](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md), add support for current version of Node (v15) which was released on October 20th, 2020.

HEAD only supports up to 14.x at the moment.

`node-version: [10.x, 12.x, 14.x]`
https://github.com/ember-cli/ember-cli/blob/87db7f29c362938ca5fa4fedeee792cfa46627ee/.github/workflows/ci.yml#L57

**Comment by rwjblue** [comment]
We'll need to fix https://github.com/ember-cli/ember-cli/issues/9404 first I think.

**Comment by bertdeblock** [comment]
Is this one still relevant now that v16 is LTS and v17 is current?

**Comment by kellyselden** [comment]
Nope, but we should probably add node 17 support now.
