### ISSUE TITLE
Add eslint-plugin-qunit to blueprint

### ISSUE THREAD

**Issue by bmish** [ember-cli/ember-cli#9390]
Have we ever considered adding/enabling [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) linting to the Ember blueprints? It's a great plugin for enforcing QUnit best practices in tests, and I consider it to be the most useful/relevant linting plugin that we haven't added to the blueprint yet. I use in many of my Ember apps/addons.

RFC: https://github.com/emberjs/rfcs/pull/702 (similar to the recent [prettier RFC](https://github.com/emberjs/rfcs/blob/master/text/0628-prettier.md)).

CC: @platinumazure

**Comment by Turbo87** [comment]
FWIW we are using it at Qonto too and it has been working quite well. We are using the `plugin:qunit/recommended` and `plugin:qunit/two` presets, but we had to manually disable a few rules due to false positives:

```js
    // disabled due to false positives
    'qunit/no-global-assertions': 'off',
    // disabled because the rule doesn't handle explicit imports correctly
    'qunit/no-global-module-test': 'off',
    // disabled due to false positives
    'qunit/no-global-stop-start': 'off',
```

**Comment by bmish** [comment]
@Turbo87 the good news is that I just fixed that bug (platinumazure/eslint-plugin-qunit#75) so those rules will no longer need to be disabled :) See #9392 for my proposed implementation.

**Comment by platinumazure** [comment]
The false positive globals was something I had known about for a while and I knew how it could be fixed, but I just never had time to do it. Big "thank you" to @bmish for getting it done!

**Comment by bmish** [comment]
I have written an RFC for this! https://github.com/emberjs/rfcs/pull/702
