### ISSUE TITLE
[Discussion] To include ember-template-inspector while creating new app.

### ISSUE THREAD

**Issue by siva-sundar** [ember-cli/ember-cli#9409]
Hi,

https://github.com/siva-sundar/ember-template-inspector#ember-template-inspector

This add-on opens the template file in the code editor while inspecting an element. Would it be better if we make it as a dependency of ember-cli ?

People, who are trying ember for the first time might enjoy its benefits.

Kindly share your thoughts.

**Comment by siva-sundar** [comment]
@rwjblue would like to know your thoughts on this.

**Comment by bertdeblock** [comment]
@siva-sundar You could consider opening an issue at https://github.com/emberjs/rfcs/issues to gather some feedback?

**Comment by siva-sundar** [comment]
Sure. Here is the link https://github.com/emberjs/rfcs/issues/703
