### ISSUE TITLE
Consider writing warnings to stderr

### ISSUE THREAD

**Issue by jaswilli** [ember-cli/ember-cli#9416]
Hi,

I'm trying to use `ember asset-sizes --json` and the output is rendered invalid by any warnings that happen to be output. For example:

```
$ ember asset-sizes --json
WARNING: Node v15.5.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
{"files":[{"name":"dist/assets/tests.js","size":941,"gzipSize":527},{"name":"dist/assets/vendor.css","size":2200,"gzipSize":672},{"name":"dist/assets/vendor.js","size":2856916,"gzipSize":625494},{"name":"dist/assets/warn.css","size":0,"gzipSize":20},{"name":"dist/assets/warn.js","size":12882,"gzipSize":2464}]}

$ ember asset-sizes --json | jq .
parse error: Invalid numeric literal at line 1, column 8
```

At least in my experience it's common to write output that's not expected to stderr so that it won't interfere with processing the output. There's also the benefit of surfacing the information to the user in the event that output is being redirected, e.g., `ember asset-sizes --json > log_sizes.json` would correctly capture the data but the warning message would still be echoed to the terminal for the user to see and act upon.

I realize this is actually handled upstream at https://github.com/ember-cli/console-ui, I just thought it might be better to discuss in the context of ember-cli itself. I'm happy to take this down the hall to the console-ui issue tracker if that's better.

**Comment by rwjblue** [comment]
I think this is a good idea. Wanna take a crack at it?

**Comment by jaswilli** [comment]
Yep, happy to do the work on this.

**Comment by locks** [comment]
Related PR has been merged. Thank you for your help :)
