### ISSUE TITLE
Blueprints: Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#9427]
Given the recent severe restrictions that Travis-CI has placed on all projects, is it time now to switch the default app/addon blueprints over from a `travis.yml` config to a GitHub Actions config?

Here's an example of a config that @Turbo87 and @loganrosen wrote for one of my addons, as a starting point for what that could look like:

https://github.com/elwayman02/ember-user-activity/blob/master/.github/workflows/ci.yml

**Comment by Turbo87** [comment]
https://github.com/emberjs/rfcs/pull/696 😉

**Comment by elwayman02** [comment]
Ah, he beat me to it!
