### ISSUE TITLE
It appears the new lint script doesn't work in Windows

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#9428]
```
C:\code\client>yarn lint
yarn run v1.22.10
$ npm-run-all --aggregate-output --continue-on-error --parallel 'lint:!(fix)'
' was unexpected at this time.

C:\code\client>  "C:\code\client\node_modules\.bin\\node.exe"  "C:\code\client\node_modules\.bin\\..\..\..\node_modules\npm-run-all\bin\npm-run-all\index.js" --aggregate-output --continue-on-error --parallel 'lint:!(fix)'    
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rwjblue** [comment]
@kellyselden - What shell? Is it due to quote escaping?

**Comment by kellyselden** [comment]
Standard CMD. Looks like using `\"` instead fixes it.

**Comment by rwjblue** [comment]
Sounds good, we should confirm that also works on *nix and make a targetted PR against `release` branch to fix.

**Comment by rpemberton** [comment]
I believe I ran into this issue on #9469 when writing acceptance tests. To work around it, I switched from using the lint script to directly running `eslint .` and `ember-template-lint .`.

**Comment by rwjblue** [comment]
Ya, we really need to investigate and fix this.

**Comment by lupestro** [comment]
I'll have a PR shortly, just so nobody duplicates work... tested a project I build on three platforms using Kelly's fix, and it works on all of them. Adjusted blueprint and test fixtures, retesting... I'll post the PR number here as soon as it is in place.
