### ISSUE TITLE
Automatically run `lint:fix` after `ember init` and `ember generate`

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#9429]
The [Prettier RFC](https://github.com/emberjs/rfcs/blob/master/text/0628-prettier.md) includes the following:

> In order to ensure blueprint output follows each individual projects custom stylistic linting settings as much as possible. The following will be updated to run lint:fix (when available) after their existing functionality:
> 
> * ember generate
> * ember init
> * ember-cli-update

This is specifically to avoid every addon that provides blueprints from failing linting after generation. 

Related to:

* https://github.com/emberjs/ember.js/issues/19333
* https://github.com/emberjs/data/issues/7418

**Comment by bendemboski** [comment]
It's also worth mentioning that this is a big problem for Windows support because blueprint files will either have `\n` or `\r\n` line endings, meaning they cannot pass prettier on both Windows and MacOS/Linux.

**Comment by rwjblue** [comment]
Ya good point @bendemboski. We definitely need to try to land this...
