### ISSUE TITLE
Removing ember-auto-import does not fully work

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-cli#9432]
With a default blueprint + `npm uninstall -S ember-auto-import`, it will still leave some code in the compiled `vendor.js`.

I expect this has something to do with `@ember/test-helpers` and `ember-qunit` having a dependency on it. They seem to have been introduced recently with https://github.com/emberjs/ember-test-helpers/commit/167100cde9a82632a5b9b2955d00d6fb822be285 & https://github.com/emberjs/ember-qunit/commit/257556d0246bb05f2a174253dd03b382b24ae9e9, but I don't know why these test modules would leak into my normal bundle.

Minimised, it adds another 1371 bytes.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.24.0
node: 15.5.1
v8: 8.6.395.17-node.23
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: darwin arm64
6.14.11
zsh: command not found: yarn
```

**Comment by rwjblue** [comment]
Do you have a reproduction that we could look at?

**Comment by rwjblue** [comment]
I believe this was fixed. 

References:

* https://github.com/ef4/ember-auto-import/pull/329
* https://github.com/ember-cli/ember-cli/pull/9411
* https://github.com/ef4/ember-auto-import/pull/330
