### ISSUE TITLE
Npm/yarn test results in error in a new project

### ISSUE THREAD

**Issue by alucao** [ember-cli/ember-cli#9447]
Running 'npm test' or 'yarn test' in a newly created project results in error. Running 'ember test' works without errors though.

To reproduce:
1) ember new ember-quickstart --lang en
2) npm test

---

$ npm test

> ember-quickstart@0.0.0 test E:\Git\#Tmp\emberapp2\ember-quickstart
> npm-run-all lint test:*

> ember-quickstart@0.0.0 lint E:\Git\#Tmp\emberapp2\ember-quickstart
> npm-run-all --aggregate-output --continue-on-error --parallel 'lint:!(fix)'

ERROR: Task not found: "'lint:!(fix)'"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ember-quickstart@0.0.0 lint: `npm-run-all --aggregate-output --continue-on-error --parallel 'lint:!(fix)'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-quickstart@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.24.0
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: win32 x64
6.14.4
1.22.4
```

**Comment by rwjblue** [comment]
I **think** this is the same as what was reported in https://github.com/ember-cli/ember-cli/issues/9428, so I'm going to close this issue in favor of that one.
