### ISSUE TITLE
Snyk shows high vulnerable issue through dependencies

### ISSUE THREAD

**Issue by yenanandu** [ember-cli/ember-cli#9452]
https://snyk.io/test/github/ember-cli/ember-cli

Regular Expression Denial of Service (ReDoS)
Vulnerable module: underscore.string
Introduced through: quick-temp@0.1.8
Detailed paths
Introduced through: **/broccoli-plugin › quick-temp@0.1.8 › underscore.string@3.3.5

NOTE : Still 3 more high vulnerable

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by locks** [comment]
I am closing this issue as no longer relevant. We _are_ actively auditing our dependencies so any current vulnerability should be addressed soon, but I also want to say that most of these vulnerabilities are not actually relevant to the end users of ember-cli.
