### ISSUE TITLE
eslint scans all dotfiles, even in ignored folders

### ISSUE THREAD

**Issue by Techn1x** [ember-cli/ember-cli#9470]
I think there's a slight misconfiguration in the default `.eslintignore` file

Here's an example of it
https://github.com/ember-cli/ember-new-output/blob/7faae3f8d1c029efb0e47664d5ef232a9ef912ac/.eslintignore#L1-L21

```ignore
# unconventional js
/blueprints/*/files/
/vendor/

# compiled output
/dist/
/tmp/

# dependencies
/bower_components/
/node_modules/

# misc
/coverage/
!.*
.eslintcache

# ember-try
/.node_modules.ember-try/
/bower.json.ember-try
/package.json.ember-try
```

Focusing on the `!.*` introduced by https://github.com/ember-cli/ember-cli/issues/8070

This causes it to scan _all_ dot-files and dot-directories, even in the ignored directories listed above it (dist, tmp, vendor, node_modules, ...). It unignores them, I don't think this was the intent when it was added.

One solution is moving that line to the top of the file, but then it will still unignore dotfiles in default eslint ignored directories (like `**/node_modules/*` or whatever else they might decide to add in the future)

I think a better solution would be better targeting for the `!.*` - assuming the intent was just to target dotfiles in the top directory, maybe something like this is enough ->`./!.*`

**Comment by Techn1x** [comment]
I stumbled on this problem in https://github.com/eslint/eslint/issues/14158
The 7.21.0 eslint release unignores symbolic link files, so I noticed that eslint was scanning my `node_modules/.bin/` directory (full of yarn symbolic links, some to JS files) and ended up with eslint errors for that JS file. Turns out it was because of the `!.*`

**Comment by rwjblue** [comment]
I think @chancancode / @wagenet just recently fixed this. Mind taking a look?

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/9456

**Comment by Techn1x** [comment]
Oh nice! Re-ignoring dot-directories would solve most of the issue (and indeed, the problem I was having)

I don't think it would fix the problem of dotfiles inside ignored folders being scanned. Say if a file like `/tmp/abc/.my-file` existed, eslint would scan it

Happy for this to be closed though if you think that's an edge-case

**Comment by rwjblue** [comment]
Can you confirm that is still an issue (dotfiles with or without extension within an ignored directory still get detected and linted)?

It seems odd that ignored directories would be traversed at all in.

**Comment by Techn1x** [comment]
Looks like you're right. To test this I made my .eslintignore config match the one in the PR, added a file `touch ./tmp/.test.js` and some code that definitely fails linting. It didn't seem to get picked up.

I think the work in the PR above is sufficient :+1: thanks!
