### ISSUE TITLE
Deprecate outputPaths usage under Embroider

### ISSUE THREAD

**Issue by thoov** [ember-cli/ember-cli#9478]
Under Embroider the output paths of `/dist` are no longer predetermined. For example the application's javascript which would normally be `/dist/assets/app_name.js` will become for example: `/dist/assets/chunk.adjasld33lk23jol.js` + `/dist/assets/chunk.zsiojladj20ljk23jl.js`. The amount of "chunks" can vary based on the size / structure of your app especially if you have route based code splits, lazy engines, and/or dynamic imports. Each of these will create their own chunk(s). This issue is a reminder that we need to add the appropriate deprecations before enabling Embroider.

**Comment by thoov** [comment]
@SergeAstapov Thanks for the feedback. 

> to support some specific use cases

Could you elaborate more about the use case you had in mind? In general is this renaming of the asset directory something that can just be done outside of the build once it has finished?

**Comment by SergeAstapov** [comment]
@thoov we had a use case when we had to run two different web-site versions (built with Ember.js) on the same domain so we configured `outputPaths` for one of them to use folder other than `/assets`.

Potentially, it might be enough to run regexp within `dist` folder and replace `assets` with smth else, like `my-assets`.
However, I'm not sure how reliable is this.

**Comment by SergeAstapov** [comment]
I wonder if we did extra mile and had to use [`fingerprint` configuration](https://cli.emberjs.com/release/advanced-use/asset-compilation/#fingerprintingandcdnurls) instead. Not sure if it will be supported by Embroider as it's based on `broccoli-asset-rev`

**Comment by rwjblue** [comment]
Hmmm, I guess I would have assumed that you would take `dist/` from each of the production builds and scope them to `app-1-dist/` and `app-2-dist/` upon deploy. 🤔
