### ISSUE TITLE
Initializing a service does not work in ember glimmer components

### ISSUE THREAD

**Issue by rinoldsimon** [ember-cli/ember-cli#9508]
```
ember-cli: 3.26.0
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
os: darwin x64
6.9.0
1.22.5
```

**app/initializers/pandaui.js**

```
export function initialize( application ) {
  application.inject('route', 'pandaui', 'service:pandaui');
  application.inject('component', 'pandaui', 'service:pandaui');
  application.inject('controller', 'pandaui', 'service:pandaui');
}

export default {
  initialize
};
```

**app/pods/pandaui/service.js**
```
import Service from '@ember/service';

export default class PandauiService extends Service {
  block() {
    ...
  }

  unblock() {
    ...
  }
}
```

**app/components/test-form/component.js**

```
import Component from '@glimmer/component';
import { action } from '@ember/object';

export default class TestFormComponent extends Component {
  @action
  testPandaService() {
    this.pandaui.block() **ERROR: Cannot read property 'block' of undefined**
  }
}

```

The line `this.pandaui.block()` throws `Cannot read property 'block' of undefined`
When I explicitly inject the service like below it works. 

```
import { inject as service } from '@ember/service';
@service pandaui;
```

Am i missing something? OR its a bug?

I think according to the doc that is all I need to do 
https://guides.emberjs.com/release/applications/initializers/#toc_application-initializers

**Comment by bertdeblock** [comment]
@rinoldsimon You probably want to post this issue in the [Ember.js issue tracker](https://github.com/emberjs/ember.js) instead.

Regarding your problem, I'm not sure what's going on, but I can tell you that implicit injections are on their way out ([related RFC](https://emberjs.github.io/rfcs/0680-implicit-injection-deprecation.html)) and that explicit injections where needed is definitely the way to go.

**Comment by bertdeblock** [comment]
Since https://github.com/emberjs/ember.js/issues/19505 is closed, I think we can close this one as well?
