### ISSUE TITLE
Breaking change in addons with customized ember-addon.main

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#9522]
Testing against the current master branch of ember-cli, an addon like `@embroider/macros` that has both:

1. A customized `ember-addon.main` in package.json
2. A vendor directory at the default location.

is broken because the default vendor location has changed. Before, it was relative to the addon main. Now it is relative to the package root.

The problem was introduced in https://github.com/ember-cli/ember-cli/pull/9505

**Comment by rwjblue** [comment]
@brendenpalmer is going to revert then do a follow-up to add a new property (for `packageRoot`), thank you for reporting this (especially before we published our next beta!)
