### ISSUE TITLE
Embroider addon compatibility 

### ISSUE THREAD

**Issue by thoov** [ember-cli/ember-cli#9536]
This issue tracks embroider compatibility across the top section of addons in the community with the goal of getting help from others to improve embroiders compatibility. We have created [test helpers](https://github.com/embroider-build/embroider/tree/master/packages/test-setup) that can be added to addons to validate that they work in embroider in both safe and optimized variants via ember-try scenarios. Below is a list of the top 25 addons (according to emberobserver.com) and their current state. If you are able to work on adding @embroider/test-setup (instructions can be [found here](https://github.com/embroider-build/embroider/tree/master/packages/test-setup#how-to-use-it)) please reference this issue so I can keep this list updated.

- [x] ember-test-helpers https://github.com/emberjs/ember-test-helpers/pull/989 (only tests embroider-safe ATM)
- [x] ember-test-waiters https://github.com/emberjs/ember-test-waiters/issues/303
- [x] ember-cli
- [x] ember-resolver
- [x] ember-qunit
- [x] ember-concurrency
- [x] ember-test-selectors https://github.com/simplabs/ember-test-selectors/pull/670
- [ ] ember-cli-mirage https://github.com/miragejs/ember-cli-mirage/pull/2184
- [x] ember-basic-dropdown https://github.com/cibernox/ember-basic-dropdown/pull/613
- [x] ember-power-select
- [x] ember-cli-string-helpers
- [x] ember-cli-code-coverage https://github.com/kategengler/ember-cli-code-coverage/pull/327
- [x] ember-svg-jar
- [x] ember-in-viewport
- [ ] ~~ember-angle-bracket-invocation-polyfill~~ (angle brackets are fully supported since Ember v3.10)
- [x] ember-cli-postcss (not needed, using `postcss-loader` would make more sense instead of a dedicated Ember addon)
- [x] ember-modal-dialog https://github.com/yapplabs/ember-modal-dialog/pull/370
- [x] ember-changeset
- [ ] ~~ember-power-calendar~~ (seems unmaintained)
- [x] ember-tooltips
- [x] ember-sortable https://github.com/adopted-ember-addons/ember-sortable/pull/469
- [ ] ember-cp-validations
- [x] ember-changeset-validations
- [x] ember-math-helpers
- [x] ember-cli-flash https://github.com/poteto/ember-cli-flash/pull/360
- [x] ember-lifeline
- [ ] ember-infinity https://github.com/ember-infinity/ember-infinity/pull/451
- [ ] ember-engines
- [ ] ~~[ember-cli-eyeglass](https://github.com/linkedin/eyeglass/tree/master/packages/ember-cli-eyeglass)~~ (seems unmaintained)

**Comment by NullVoxPopuli** [comment]
has this list been updated? I think more of these are compat now?

**Comment by bertdeblock** [comment]
@NullVoxPopuli I've updated the list as best as I could, please let me know if anything else should be checked off.

**Comment by NullVoxPopuli** [comment]
Some of these can't be v2 addons, and maybe may never need embroider compatibility?

Like ember-cli-postcss is often used with Tailwind, and the ideal tailwind setup works best with webpack-native plugins (or as a separately running build)

And the polyfills... should be easy tests.

**Comment by bertdeblock** [comment]
Does `ember-angle-bracket-invocation-polyfill` need to be Embroider compat?

**Comment by bertdeblock** [comment]
Is this issue still needed / relevant?

**Comment by bertdeblock** [comment]
I updated the list a bit more, but going to close this for now. I think for the most part, this ticket has served its use.
