### ISSUE TITLE
v3.15 w/ Node 14+ crashes consistently when postBuild hook throws

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9584]
Discovered during some investigative work by @dfreeman over here https://github.com/typed-ember/ember-cli-typescript/issues/1439#issuecomment-878244006

tldr: 
 - postBuild returns a rejected promise, ember-cli crashes
 - rejected promises need to be caught from postBuild

**Comment by NullVoxPopuli** [comment]
Here is a reproduction: https://github.com/NullVoxPopuli/ec-typescript-repro-1439

**Comment by NullVoxPopuli** [comment]
To add, this is not typescript related. Any error result in a crash after browser access

**Comment by Alonski** [comment]
This is happening to me too

**Comment by SanderKnauff** [comment]
Is there anything that stops us from adding a `.catch()` to `return Promise.all(addonPromises).then(() => results);` [(`lib/models/builder.js:161`)](https://github.com/ember-cli/ember-cli/blob/a6a3fe0eb11277efdb4adfe25de3e5c4409b9333/lib/models/builder.js#L161)

**Comment by NullVoxPopuli** [comment]
Someone needs to pr it 🙃

**Comment by SanderKnauff** [comment]
I will look into it soon. It looks so simple that I get the feeling that here is more behind this...

**Comment by dfreeman** [comment]
If a `postBuild` promise rejects, that _should_ fail that particular (re)build—it just shouldn't cause the whole Node process to crash. If I'm reading the code in `builder.js` right, adding a `.catch()` there would cause it to ignore rejected promises and succeed the build anyway.
