### ISSUE TITLE
`ember install` fails on first attempt, succeeds on second (ember-cli 3.28.0)

### ISSUE THREAD

**Issue by lfrost** [ember-cli/ember-cli#9606]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.28.0
node: 14.17.5
v8: 8.4.371.23-node.76
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: linux x64
6.14.14
1.22.11
```
*Description*
`ember install` fails on first attempt, succeeds on second.

*Steps to Reproduce*
```
$ ember new --no-welcome --yarn test-app
$ cd test-app
$ ember install ember-composable-helpers

🚧
Yarn: Installed ember-composable-helpers
Install failed. Could not find addon with name: ember-composable-helper
```
This happens on every Ember add-on tested, including ember-cli-typescript, ember-cli-mirage, ember-cli-string-helpers, ember-composable-helpers, and ember-uuid.

**Comment by bertdeblock** [comment]
I'm seeing the exact same issue. Could it be that this PR is related => https://github.com/ember-cli/ember-cli/pull/9487? Since it seems to touch code related to initializing addons.

**Comment by bertdeblock** [comment]
@davecombs 👋 Would you mind checking if #9487 might be related to this issue?

**Comment by mansona** [comment]
So I'm seeing this as an issue when running `ember install` for any addon that has a default blueprint (a blueprint with the same name as the addon). For example when you run `ember install empress-blog` it throws an error 

```
Install failed. Could not find addon with name: empress-blog
```

I have done a `git bisect` and I have confirmed that it is indeed https://github.com/ember-cli/ember-cli/pull/9487 that caused the issue, specifically this commit: https://github.com/ember-cli/ember-cli/pull/9487/commits/22b799b51410546d8e07685c9b621da8c11998d7

Unfortunately this is a **massive** PR and I'm wondering if we can actually just revert it while we figure out what went wrong? I don't even know how to test this to make sure that it doesn't break 🙈

**Comment by bertdeblock** [comment]
> for any addon that has a default blueprint

It happens for every addon AFAICT. The error happens before ember-cli can determine whether or not the installed addon has a default blueprint.

**Comment by mansona** [comment]
@bertdeblock oh that's even worse 🙈  but I guess for regular addons it's not an issue, but if the addon is relying on the default blueprint to add anything then it's just plain broken for them 😞

**Comment by rwjblue** [comment]
@brendenpalmer - Do you think you might be able to poke at this?

**Comment by rwjblue** [comment]
@mansona / @lfrost  / @bertdeblock - Have y'all debugged what is going on here? Specifically, _why_ it is failing to install?

https://github.com/ember-cli/ember-cli/blob/9c8ca9eafdd35f7cb3b105afd98d5f5c6b54ebdf/lib/tasks/addon-install.js#L38-L49

This is the promise chain that runs during `ember install`, which of those steps fail? What is the error message?

**Comment by rwjblue** [comment]
Based on what @bertdeblock said in https://github.com/ember-cli/ember-cli/issues/9606#issuecomment-909670764, I'd suspect that the `project.reloadAddons()` does not work properly

**Comment by davecombs** [comment]
I can take a look at it, @rwjblue.

Cheers,
Dave

**Comment by brendenpalmer** [comment]
Thanks for reporting this; I've just opened a PR with a fix here: https://github.com/ember-cli/ember-cli/pull/9618

**Comment by nadnoslen** [comment]
Anyone know if this issue has inadvertently been re-introduced?

I've recently created a number of new projects and addons with:

```
ember-cli: 4.6.0
node: 16.17.0
os: darwin x64
```

...and every time I go to install an addon using `ember install ...` I get the failure on the first attempt indicating _Could not find addon with name: ..._ and then if I re-run it, it completes successfully.

(I should note that I'm actually invoking _ember_ from my project/addon root directory via: `./node_modules/.bin/ember install ...`)

**Comment by nadnoslen** [comment]
Terrific @bertdeblock ... thanks for pointing that out. Didn't see it in my google/github searches 🍻
