### ISSUE TITLE
Restore test behavior when qunit behavior is restored

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#9615]
qunit v2.17 has a [regression](qunitjs/qunit#1651) in the behavior when no tests match a filter that caused one of our tests to fail. When the old behavior is restored, our test will need to be altered again.

See #9613

**Comment by Krinkle** [comment]
@kategengler I've released qunit 2.17.1 which makes the error message visible again.

**Comment by Krinkle** [comment]
@kategengler 

I've released qunit 2.17.1 which makes the error message visible again. And qunit 2.17.2 which restores the implementation detail of "No tests" resulting in a failing fake test rather than a run error.
