### ISSUE TITLE
Remove IE11 comments from `config/target.js`

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#9622]
Remove these comments:

https://github.com/ember-cli/ember-cli/blob/39dcf21c5b1a5dc22a8be142ab628caff0f97ee8/blueprints/app/files/config/targets.js#L9-L22

**Comment by bertdeblock** [comment]
@rwjblue Seems this one wasn't closed automatically when merging #9666.

**Comment by kategengler** [comment]
Thanks!
