### ISSUE TITLE
Addon is unable to modify app files using preprocessTree

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli#9639]
I use `preprocessTree` to manipulate app files like this:

```js
const stew = require('broccoli-stew');
const themeName = process.env.EMBER_THEME || 'default';

module.exports = {
  name: require('./package').name,

  preprocessTree(type, tree) {
    if (type === 'css' && themeName !== 'default') {
      tree = stew.rm(tree, `app/styles/config/themes/_current-theme.scss`);

      tree = stew.mv(
        tree,
        `app/styles/config/themes/_${themeName}.scss`,
        `app/styles/config/themes/_current-theme.scss`
      );

      tree = stew.rm(
        tree,
        `${this.app.name}/styles/config/themes/_current-theme.scss`
      );

      tree = stew.mv(
        tree,
        `${this.app.name}/styles/config/themes/_${themeName}.scss`,
        `${this.app.name}/styles/config/themes/_current-theme.scss`
      );

      return stew.debug(tree);
    }

    return tree;
  },
};
```

This is super straightforward: I remove `_current-theme.scss` and replace it with another Sass file.

From the debug tree output I can see that the substitution happens successfully.

Yet, the resulting CSS stylesheet does not reflect the substitution.

@simonihmig has figured out that this may be because the addon's tree gets overwritten with the app tree, so all changes that the addon makes are discarded.

The only exception are new files which don't exist in the app tree. Those don't get overwritten. But we can't rely on a file that does not exist in the app codebase because the IDE is unable to resolve references:

![image](https://user-images.githubusercontent.com/200884/134325045-acd1549b-cce7-4f71-872c-7939e313bab4.png)

I don't expect the core team to recognize this as a bug, but from an addon author's perspective it surely feels as a bug!

How do I make my addon manipulate app files in the build?

PS Why are there two copies of styles in a tree: `app/styles/` and `my-app-name/styles/`?! Which one is the right one?

---

Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 3.28.0
node: 12.14.1
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
os: linux x64
npm: 7.11.2
yarn: 1.22.4
```

**Comment by lolmaus** [comment]
Tried `postprocessTree`, no difference.

**Comment by lolmaus** [comment]
> Tried postprocessTree, no difference.

This is probably because `ember-cli-sass` uses `setupPreprocessorRegistry`, so when my addon reaches `postprocessTree`, then Sass has already finished and manipulating Sass source files is useless.

**Comment by simonihmig** [comment]
I think I have figured it out:

The problem is that in `app/styles/app.scss` we import (colocated) Sass files from `app/components/foo-bar.scss`, but the latter is not within the actual styles tree, that is preprocessed. It still works, as apparently Sass will still find the file even when it is not within the `includePaths` (which is the temporary preprocessed broccoli tree folder), when it is able to find it in the *current* folder (which is the actual project folder). In that `app/components/foo-bar.scss` we import `app/styles/config/themes/current-theme`, but now Sass seems to resolve this (relative from the component style file) from the *current project folder*, where this file *also* exists, but obviously as the *un*processed version.

So I think this issue is quite specific to a) our setup, and b) how Sass resolves those imports, and not a bug here. So I think this issue can be closed!

**Comment by lolmaus** [comment]
@simonihmig Do you think we should reopen this with an updated description and a reproduction?

I understand that it behaves as it is implemented, but it's still a problem that could be solved...

**Comment by lolmaus** [comment]
Here's a reproduction of the issue:
https://github.com/lolmaus/ember-sass-addon-issue

**Comment by lifeart** [comment]
@lolmaus @simonihmig fixes the issue
```patch
diff --git a/node_modules/sass/sass.dart.js b/node_modules/sass/sass.dart.js
index fb18b80..91ebbc4 100644
--- a/node_modules/sass/sass.dart.js
+++ b/node_modules/sass/sass.dart.js
@@ -81367,7 +81367,7 @@ self.fs = require("fs");
     _resolveLoadPath$2(path, forImport) {
       var t2, t3, t4, t5, _i, parts, result, _null = null,
         t1 = $.$get$context(),
-        cwdResult = this._tryPath$2(t1.absolute$7(path, _null, _null, _null, _null, _null, _null), forImport);
+        cwdResult = null;
       if (cwdResult != null)
         return cwdResult;
       for (t2 = this._includePaths, t3 = t2.length, t4 = type$.JSArray_nullable_String, t5 = type$.WhereTypeIterable_String, _i = 0; _i < t3; ++_i) {
```

**Comment by lifeart** [comment]
@lolmaus @simonihmig one more workaround - replace `cwd` for `sass` in `broccoli-sass-source-maps` build step:

```patch
diff --git a/node_modules/broccoli-sass-source-maps/index.js b/node_modules/broccoli-sass-source-maps/index.js
index bb43eaa..69c11b3 100644
--- a/node_modules/broccoli-sass-source-maps/index.js
+++ b/node_modules/broccoli-sass-source-maps/index.js
@@ -82,8 +82,11 @@ module.exports = function(sass) {
     };
 
     assign(sassOptions, this.sassOptions);
+    let cwd = process.cwd();
+    process.chdir(this.inputPaths[0]);
 
     return this.renderSass(sassOptions).then(function(result) {
+      process.chdir(cwd);
       var files = [
         writeFile(destFile, result.css)
       ];
@@ -93,7 +96,9 @@ module.exports = function(sass) {
       }
 
       return Promise.all(files);
-    }.bind(this)).catch(rethrowBuildError);
+    }.bind(this)).catch(rethrowBuildError).finally(() => {
+      process.chdir(cwd);
+    });
   };
 
   return SassCompiler;
```

**Comment by lifeart** [comment]
one more option - implement custom importer on app/addon level 

```js
 let app = new EmberApp(defaults, {
    // Add options here
    sassOptions: {
      importer: function(url, prev, done) {
        console.log(this.includePaths);
        console.log(url, prev);
        return done({file: prev});
      }
    }
  });
```
https://github.com/sass/node-sass#importer--v200---experimental

(can't find way to fallback to default one logic here)

**Comment by lifeart** [comment]
`ember-cli-build.js` customization example:

* this is very simple resolver, and complex cases may fail

```js
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');
const path = require('path');

module.exports = function (defaults) {
  let app = new EmberApp(defaults, {
    sassOptions: {
      importer: function (url, prev, done) {
        let paths = this.options.includePaths;
        let file = path.join(
          paths.split(';').filter((el) => el !== process.cwd())[0],
          url + '.scss'
        );
        return done({
          file,
        });
      },
    },
  });
  return app.toTree();
};

```

**Comment by lolmaus** [comment]
@lifeart Thank you for your research and proposed fixes! :pray: 

So @lifeart discovered that the root cause of the issue is [this line in Sass](https://github.com/sass/dart-sass/blob/ba38c09c6869c1c7da19f05298a270da29d93e73/lib/src/importer/legacy_node/implementation.dart#L156) which makes `cwd` (current working directory) to always be the first include path. This behaviour is comment-documented [here](https://github.com/sass/dart-sass/blob/ba38c09c6869c1c7da19f05298a270da29d93e73/lib/src/importer/legacy_node/implementation.dart#L33-L41).

Unfortunately, changing that would be severely breaking. Sass relies on that behaviour similar to how Ember CLI relies on that app files always have priority over addons' `app/` files. For this reason, we did not attempt creating a PR or even an issue in Sass.

But this `cwd` behaviour makes no sense in `ember-cli-sass`. In `ember-cli-sass`, `cwd` should be pointing at the Broccoli tree, not the project codebase. @lifeart has created an upstream issue: https://github.com/simonexmachina/broccoli-sass-source-maps/issues/30

For this reason, the easiest solution could be changing `cwd` in `broccoli-sass-source-maps`, rather than creating a custom importer (which must support importing from `node_modules/` in addition to the Broccoli tree, which requires extra effort to reimplement).

**Comment by lolmaus** [comment]
Note that Sass relative imports do not require the `./` prefix.

Thus, `@use "foo/bar";` inside `my-ember-app/app/styles/partials/_baz.scss` may mean:

* `my-ember-app/app/styles/partials/foo/_bar.scss`;
* `my-ember-app/foo/_bar.scss` because project root seems to be in `import_paths`;
* `my-ember-app/node_modules/foo/_bar.scss` if you have `node_modules/` in `include_paths` for convenience;
* `my-ember-app/node_modules/ember-foo/stylesheets/foo/_bar.scss` if an `ember-foo` addon adds its own to `include_paths`.
* `my-ember-app/node_modules/foo/stylesheets/foo/_bar.scss` if an `ember-foo` addon is a wrapper addon over the `foo` Sass package and adds it to `include_paths`.

:see_no_evil: 

This is likely historically influenced by Ruby's style of importing everything as globals within local scope. Here it is not clear where `bar` comes from:

```rb
require "foo";
bar();
```

Compare this to how explicit ES imports are:

```js
import { bar } from "foo";
bar();
```

Sass has too recognized the importance of explicit references and introduced its own `@use` syntax:

```scss
@use "foo";
@log foo.bar();
```

It makes the code more verbose but relieves you from having to scroll the file all the way up to consult the imports and lose context.

I wish `import_paths` followed suit and required an explicit namespace for each import path. Unfortunately, it does not seem feasible to change the underlying `import_paths` behaviour without tripping every Sass user up. :pensive:

**Comment by simonihmig** [comment]
Impressive investigation, thanks @lifeart!
