### ISSUE TITLE
ember-classic scenario will stop working soon

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli#9658]
https://github.com/ember-cli/ember-cli/blob/7f38e722ada061c80494ac9b03cbb43880449e2b/blueprints/addon/files/addon-config/ember-try.js#L63-L77

I believe the classic option is deprecated/removed for 4.0, so we will probably have to pin this scenario to 3.28 or something.

**Comment by bertdeblock** [comment]
Can be closed since #9659 is merged?

**Comment by kategengler** [comment]
I think so, thanks!
