### ISSUE TITLE
[feature] migrate express to fastify

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-cli/ember-cli#9676]
There are so many benefits of using https://www.fastify.io/ over expressjs.

Right now expressjs is awaiting a much needed v5 upgrade and is missing async and h2 support.

As https://www.fastify.io/ is being upgraded and maintained, moving to it over express would enable a faster dev experience for anyone using ember.

**Comment by locks** [comment]
Would you be willing to help out with the migration?

**Comment by gabrielcsapo** [comment]
Yes @locks

**Comment by kategengler** [comment]
Is fastify.io API compatible with express? When generating proxies and http-mocks, users directly interact with express, so if it is not compatible, we may need an RFC to make this change.

**Comment by jherdman** [comment]
I know this is slightly off topic, but perhaps this entire feature ought to be extracted into an addon. I can't say that I've ever reached for it in the many years that I've used Ember.

**Comment by gabrielcsapo** [comment]
The dev server should be abstracted to another addon @jherdman?

**Comment by jherdman** [comment]
No, the http-mock servers. Apologies if I misunderstood the original ticket.

**Comment by kategengler** [comment]
I don't often use http-mock, but I do frequently use proxies. 

This also reminds me that another place this is probably exposed to users is in the `serverMiddleware` options for addons https://ember-cli.com/api/classes/addon#method_serverMiddleware

**Comment by gabrielcsapo** [comment]
Yes for sure, there are multiple ways that people will interact with the underlying http implementation. My main motivation for this issue is that we are held up on merging https://github.com/ember-cli/ember-cli/pull/9383. This introduces the ability to serve assets via h2 and make local development a lot faster. I think there are some concerns that this is not supported at the express level hence the start of this discussion.

**Comment by kategengler** [comment]
I think it requires an RFC if it isn't a drop-in replacement for express.

**Comment by locks** [comment]
@gabrielcsapo would you be willing to author such an RFC? We definitely need some research into the impact of a change this big, and possible mitigation paths.

**Comment by pichfl** [comment]
Uncertain if it matters, but fastify does provide a compatibility layer which works quite well: https://github.com/fastify/fastify-express

**Comment by locks** [comment]
Closing as a feature request of this magnitude should go through an RFC first to ensure that we don't accidentally leave people behind with broken apps. @gabrielcsapo reach out in `#dev-rfc` and we'll help you get going 💪

**Comment by runspired** [comment]
fwiw I don't think `serverMiddleware` even works anymore. I recently tried using it and could not get it to handle any routes, ember-cli's built in's were taking precedence always, even when I tried `/` and `*`.

**Comment by kategengler** [comment]
`ember-cli-code-coverage` uses `serverMiddleware` to enable capture of coverage when tests are run without testem, afaik this is working https://github.com/kategengler/ember-cli-code-coverage/blob/master/packages/ember-cli-code-coverage/index.js#L123
