### ISSUE TITLE
`ember new my-app --yarn` on 4.0 beta uses npm and does not generate a yarn.lock

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#9695]
`ember new my-app --yarn`

`--yarn` has been replaced by a `--package-manager` option for the [`install` command but not for the `new` command](https://github.com/ember-cli/ember-cli/commit/eb6f2bdaea4c9b2a65d4ec1b68061f164fc344d8#diff-c0549e8d8103bfd6f899a82077404b21dcb6868d5abb8de81bcd6955e0046b12R38).

The app generates, uses `npm` to install and results in a `package-lock.json`, but the words at the end do suggest using `yarn start`

Caught by @chancancode when working with the tutorial. 

I confirmed on cli@beta and that cli@latest works with `--yarn` as expected.

**Comment by btecu** [comment]
With https://github.com/ember-cli/ember-cli/pull/9696 merged, this can be closed, right?

**Comment by kategengler** [comment]
Yes, thanks! Though, I'm surprised it did not auto-close.
