### ISSUE TITLE
Node 16.13 (LTS) Support

### ISSUE THREAD

**Issue by Thomasevano** [ember-cli/ember-cli#9698]
Hello,

We want to upgrade our app to Node 16.13 but when we start the application, we encounter the following issue: `TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array`

Is Node 16 support in the roadmap ?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.28.4
node: 16.13.0
v8: 9.4.146.19-node.13
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: darwin x64
8.1.0
```

**Comment by pichfl** [comment]
See #9694

**Comment by Thomasevano** [comment]
> See #9694

Yes, i saw it. it remove the warning saying node 16 is not tested, but it don't think it add support

**Comment by jherdman** [comment]
@Thomasevano I happened to dig into this just last night! As far as I can tell there are certain dependencies using a  very ancient version of workerpool. In the case of my app there are two offenders:

1. ember-cli-flash (via ember-runtime-enumerable-includes-polyfill)
2. ember-data (we're stuck on v3.24 at this time)

**Comment by Thomasevano** [comment]
> @Thomasevano I happened to dig into this just last night! As far as I can tell there are certain dependencies using a very ancient version of workerpool. In the case of my app there are two offenders:
> 
> 1. ember-cli-flash (via ember-runtime-enumerable-includes-polyfill)
> 2. ember-data (we're stuck on v3.24 at this time)

Oh ok, maybe you right, i didn't think of this, cause the error happened in `ember-cli-test-loader`

**Comment by mansona** [comment]
so this should be fixed since we backported the fix to the "very ancient version of workerpool" https://github.com/josdejong/workerpool/releases/tag/v2.3.4

You might have a lock file that is preventing you from getting that patch release but if you just update that should be fine (with npm the command is just `npm update workerpool` and that will update the lockfile accordingly if you're on the latest npm)

**Comment by runspired** [comment]
I notice that as of ember-cli 3.28 we get this warning despite node 16 being the active LTS both then (at time of ember-cli release) and now:

```
WARNING: Node v16.13.2 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
```

**Comment by locks** [comment]
The original issue has been fixed. Thanks for the discussion!

**Comment by runspired** [comment]
@locks can you open a new ticket then for adding node16 support to ember-cli?
