### ISSUE TITLE
ember production doesn't expose `Ember.Handlebars.compile`

### ISSUE THREAD

**Issue by AdamFerguson** [ember-cli/ember-cli#972]
I'm inlining my template for a component using `Ember.Handlebars.compile` which works fine in development. Unfortunately, it's breaking in production b/c that function isn't available. I believe this is b/c handlbars.runtime.js (which is used in production) doesn't expose a compile function [and this](https://github.com/emberjs/ember.js/blob/master/packages/ember-handlebars-compiler/lib/main.js#L295). Is there way to inline templates that is preferable to `Ember.Handlbars.compile`. If not, is the use of handlebars.runtime.js strictly necessary for production or can this be overriden to use handlebars.js instead?

**Comment by wbyoung** [comment]
In case anyone else reads this thread and is trying to figure out how to include the full version of Handlebars using Ember CLI, it's now [documented on the Ember CLI website](http://www.ember-cli.com/#customizing-a-built-in-asset).

**Comment by jdhines** [comment]
@wbyoung, that worked for me. And it was handlebars that was messing it up. Or, more specifically, the reference to it used by something Bootstrap. This error caused "module not found" errors on down the line. Another lesson learned...
