### ISSUE TITLE
Fresh ember-cli app is resulting in an error when run.

### ISSUE THREAD

**Issue by iofusion** [ember-cli/ember-cli#9732]
Thanks for your help developing Ember!

Two tests with an empty application are resulting in an error when run.  The standard Welcome Page is not rendered and the following error is shown in the inspector. `page-title.js:13 Uncaught Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.`

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.28.4
node: 14.18.1
v8: 8.4.371.23-node.84
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.4
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: darwin x64
6.14.15
1.22.10
```

I updated ember-cli today with ` volta install ember-cli`

I created a new app with `ember new --yarn hmmm`

`yarn start` results in error free build, but Chrome displays a blank page with a tab titled `Hmmn`.  Chrome's inspector reports the following error, note the mismatch between the `ember --version` and what is reported in the inspector:
```
DEBUG: -------------------------------
index.js:201 DEBUG: Ember      : 3.28.8
index.js:201 DEBUG: Ember Data : 3.28.6
index.js:201 DEBUG: -------------------------------
runtime.js:6162 

Error occurred:

- While rendering:
  -top-level
    application


execute @ runtime.js:6162
(anonymous) @ runtime.js:6248
runInTrackingTransaction @ validator.js:165
sync @ runtime.js:6248
(anonymous) @ index.js:7573
(anonymous) @ index.js:7542
(anonymous) @ index.js:7893
inTransaction @ runtime.js:5074
_renderRoots @ index.js:7873
_renderRootsTransaction @ index.js:7925
_renderRoot @ index.js:7860
_appendDefinition @ index.js:7767
appendOutletView @ index.js:7749
invoke @ backburner.js:353
flush @ backburner.js:241
flush @ backburner.js:447
_end @ backburner.js:999
end @ backburner.js:729
_run @ backburner.js:1054
run @ backburner.js:773
run @ index.js:119
callback @ application.js:438
page-title.js:13 Uncaught Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and runs after the decorators transform.
    at _initializerWarningHelper (page-title.js:13:1)
    at PageTitle.<instance_members_initializer> (page-title.js:22:1)
    at new PageTitle (page-title.js:29:1)
    at Function.create (core_object.js:678:1)
    at FactoryManager.create (index.js:556:1)
    at Proxy.create (index.js:254:1)
    at ClassicHelperManager.createHelper (index.js:5175:1)
    at manager.js:968:1
    at Object.evaluate (runtime.js:2084:1)
    at AppendOpcodes.evaluate (runtime.js:1312:1)
```

Thanks for your attention and let me know if more information would be helpful.

  FYI. James.exe [noted a similar error on Discord](https://discord.com/channels/480462759797063690/480462759797063692/920780206590029885) earlier today.

**Comment by iofusion** [comment]
There is more [discussion about this on Discord](https://discord.com/channels/480462759797063690/483601670685720591/921047063511326741), NullVoxPopuli recommended specifying `ember-cli-babel` to `"7.26.6"`.  This resolved the issue for a Discord user, however I am seeing the same problem described above after that change.  Additionally after deleting `node_modules` and running `yarn install` I received the following warnings:

```
hmmn on  master [!] via  v14.18.1 took 2m1s
❯ rm -fr node_modules

hmmn on  master [!] via  v14.18.1 took 5s
❯ yarn install
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "ember-source > @babel/plugin-transform-block-scoping@7.16.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-maybe-import-regenerator > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "@glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-load-initializers > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-source > @babel/plugin-transform-object-assign@7.16.5" has unmet peer dependency "@babel/core@^7.0.0-0".
[5/5] 🔨  Building fresh packages...
✨  Done in 12.28s.
```

**Comment by jherdman** [comment]
See https://github.com/babel/ember-cli-babel/issues/423

**Comment by iofusion** [comment]
@jherdman.  Thanks for the tip: Adding `resolutions": { "ember-cli-babel": "7.26.6"}`  to package.json let the new app start.  But a new version of `ember-cli-babel`  `7.28.8` has just been released, which should clear the issue.

**Comment by locks** [comment]
Thank you for the follow ups!
