### ISSUE TITLE
Deprecation warning 'template-compiler.registerPlugin' does not provide a lot of information

### ISSUE THREAD

**Issue by LeopoldHock** [ember-cli/ember-cli#9738]
The following deprecation warning does not give me any information about what plugin is causing it.

Deprecation ID: `template-compiler.registerPlugin`
This is the console output:
https://deprecations.emberjs.com/v3.x/#toc_template-compiler-registerPlugin
```
| building... [Babel: ember-popper > applyPatches]
DEPRECATION: Using class based template compilation plugins is deprecated, please update to the functional style: SetTransform [deprecation id: template-compiler.registerPlugin]
        at logDeprecationStackTrace (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:1984:21)
        at HANDLERS.<computed> (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2117:9)
        at raiseOnDeprecation (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2011:9)
        at HANDLERS.<computed> (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2117:9)
        at invoke (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2129:9)
        at deprecate (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2085:28)
        at wrapLegacyPluginIfNeeded (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:20501:49)
        at C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:20482:16
        at Array.map (<anonymous>)
```

Maybe adding information required to find the plugin would be beneficial?

ember-cli: 3.28.4
ember-source: 3.28.8

**Comment by boris-petrov** [comment]
I believe it is coming from [ember-box](https://github.com/pzuraq/ember-box/issues/23).

**Comment by bertdeblock** [comment]
This deprecation warning comes from `ember-source`, so maybe it's better if we move this issue to the Ember.js repo?

**Comment by cah-briangantzler** [comment]
I have the same issue but from discord I believe I have tracked mine down to ember-tooltips/ember-in-element-polyfill. Which is weird because Im on a high enough ember the polyfill is inert, but the check must be happening anyway.

What I was hoping for here was the solution to quick the noise til a fix can be made (assume moving to ember 4 will quiet it as well, just not there yet)

**Comment by gnclmorais** [comment]
Did https://github.com/emberjs/ember.js/pull/19704 perhaps address this deprecation?

**Comment by bertdeblock** [comment]
I think the issue reported here is, that it's not clear which plugin is triggering this deprecation.
Though, the deprecation message _does_ include the name of the plugin, being `SetTransform`.
[A quick code search with `SetTransform` on emberobserver.com](https://emberobserver.com/code-search?codeQuery=SetTransform) only returns a handful of addons, one of them being `ember-box` as mentioned here https://github.com/ember-cli/ember-cli/issues/9738#issuecomment-1000821584, but it could also be that it's coming from one of the other addons that have a transform plugin (just check which ones you are using). I think the `SetTransform` name has just been copied from one addon to the other. Those addons are all from the same author.
I still think this issue should be closed here though, it's not an `ember-cli` issue.

**Comment by bertdeblock** [comment]
I'm going to close this one if that's okay.
The deprecation _does_ contain the name of the offending plugin (in this case: `SetTransform`) and is triggered by `ember-source`, not by `ember-cli`. I've also made https://github.com/ember-learn/deprecation-app/pull/1129 to update the docs for this deprecation, so hopefully, it will be clearer for people running into this.
