### ISSUE TITLE
Contributing.md bug with scoped package

### ISSUE THREAD

**Issue by ctjhoa** [ember-cli/ember-cli#9757]
**Reproduction steps**

- Run `$ ember addon @ctjhoa/test-addon`
- Run `$ cat test-addon/CONTRIBUTING.md`
- The line `cd @ctjhoa/test-addon` should be `cd test-addon` as scope is not part of the generated folder name.

Output from `ember version --verbose && npm --version && yarn --version`:

```
ctjhoa@t490 ~ % ember version --verbose && npm --version && yarn --version
WARNING: Node v17.1.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
ember-cli: 3.28.4
node: 17.1.0
v8: 9.5.172.25-node.13
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 102
nghttp2: 1.46.0
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
os: linux x64
8.1.3
1.22.17
```

**Comment by bertdeblock** [comment]
I just checked my PR again, and I'm not sure if it's the right fix after all. When people clone a repository, the directory name will be based on the repository's name. So I'm thinking, the most sensible default would be to _always_ use the package's name without the scope?
