### ISSUE TITLE
Better error messaging when local ember-cli is missing

### ISSUE THREAD

**Issue by MichalBryxi** [ember-cli/ember-cli#9758]
Assume I have an ember-cli project:

```sh
❯ ember --version
ember-cli: 4.1.0
node: 16.13.2
os: darwin x64

~/ember/
❯ ember new sandbox
❯ cd sandbox
...
```

Now let's say that I will for some reason nuke `node_modules`:

```sh
❯ rm -rf node_modules
```

And I will try to run `ember` command again in that "sandbox" directory. But I will get:

```sh
❯ ember --version
Volta error: Could not locate executable `ember` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

Which is confusing. I don't really care that you did not find local installation of `ember`. Maybe use the global version instead and give me a warning?

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 4.1.0
node: 16.13.2
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
os: darwin x64
8.1.2
1.22.17
```

**Comment by kategengler** [comment]
I don't believe this error is from `ember-cli`, as it says, it didn't find the executable.

`Volta error: Could not locate executable `ember` in your project.` implies the error comes from Volta?

**Comment by bertdeblock** [comment]
> Maybe use the global version instead

AFAICT, that's what Ember CLI already does:
https://github.com/ember-cli/ember-cli/blob/master/bin/ember#L28-L31

**Comment by MichalBryxi** [comment]
Ok, I tried to nuke volta and now the unexpected error "Could not locate executable `ember` in your project" does not appear:

```
~/EmberJS                                                                                                           
❯ ember --version
ember-cli: 4.1.1
node: 14.19.0
os: darwin x64

~/EmberJS                                                                                                             
❯ cd sandbox

~/EmberJS/sandbox                                                                                                 
❯ ember --version
ember-cli: 4.1.1
node: 14.19.0
os: darwin x64

~/EmberJS/sandbox 
❯ ember g component foo
Required packages are missing, run `npm install` from this directory to install them.
```

Sorry for the noise.
