### ISSUE TITLE
Exclude files/folders from asset size printer

### ISSUE THREAD

**Issue by mehulkar** [ember-cli/ember-cli#9763]
The asset size printer currently prints everything in the `dist/` directory. We have some files we're putting in there that we don't need to see in our export. Moreover, for \*reasons\*, a single build job actually builds ~10 ember builds, so the output gets really verbose. I'd like to be able to exclude asset sizes for files in some folders based on some configuration.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.23.0
node: 14.17.1
v8: 8.4.371.23-node.67
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: darwin x64
# npm
6.14.13
#version
1.22.17
```

**Comment by mehulkar** [comment]
Seems we could read and use this config here: https://github.com/ember-cli/ember-cli/blob/fdb393f1331dd12f24a3afbc46c8d81ae76da07d/lib/models/asset-size-printer.js#L20-L27

**Comment by mehulkar** [comment]
Since I'm stuck on ember-cli@3.20 for a while, I'd be open to suggestions of how to override this printer locally as well!

**Comment by bertdeblock** [comment]
@mehulkar It seems you have closed the linked PR. Are you still interested in this issue or should we close this?

**Comment by mehulkar** [comment]
I didn't get any feedback for a few months, and have since left the job where it was relevant. I don't have a need to pursue anymore

**Comment by bertdeblock** [comment]
Okay, sorry your PR went without any feedback! Going to close this one for now if that's okay.
