### ISSUE TITLE
Investigate custom watch mode for js bundling pipeline

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli#9772]
Created after twitter conversation: https://twitter.com/nullvoxpopuli/status/1487035219748208650

tldr: I use broccoli without ember with rollup on relatively huge production project (600 files)

I found very slow rollup rebuild speeds 6-9s - https://github.com/chadhietala/broccoli-rollup
Also, I found that a lot of time spend on change detection, because broccoli could not emit changed files (as public API)

I decided to try webpack in watch mode as broccoli plugin, and it's works just like a charm!

Plugin example:

```js
const webpack = require('webpack');
const Plugin = require('broccoli-plugin');
const path = require('path');


class WebpackBroccoli extends Plugin {
    constructor(inputNodes, options = { }) {
        super([inputNodes], {
            annotation: options.annotation,
            persistentOutput: true
        });
        this.wp = null;
    }
    createWp() {
        if (this.wp) {
            return this.p;
        }

        const compiler = webpack({
            context: this.outputPath,
            entry: './index.js',
            mode: 'development',
            externals: {
                jquery: 'jQuery'
            },
            output: { filename: 'index.js', path: path.join(this.outputPath, 'chunks'), }
        });

        const watching = compiler.watch({
            // Example [watchOptions](/configuration/watch/#watchoptions)
            aggregateTimeout: 300,
            followSymlinks: true,
            poll: undefined
          }, (err, stats) => { // [Stats Object](#stats-object)
            // Print watch/build result here...
            if (err) {
               this.p.reject(err);
            }
            this.p.resolve();
        });
        this.wp = watching;
        return this.p;
    }
    async syncTree() {

        this.output.symlinkOrCopySync(this.input.readFileMeta('entry').path, 'entry');
        await this.createWp();

    }
    async build() {

        let resolve, reject;

        if (this.p) {
            this.p.reject();
        }

        this.p = new Promise((res, rej) => {
            resolve = res;
            reject = rej;
        });

        this.p.resolve = resolve;
        this.p.reject = reject;

        await this.syncTree();
    }
}

module.exports = {
    WebpackBroccoli
}

```

I able to reduce rebuild times from 6-9s to 0.7-1.4s with it

**Comment by NullVoxPopuli** [comment]
Based on the twitter thread -- the main argument is that all the file i/o is what is making brocolli's performance not so great -- do you think it's worth figuring out a way to have all of broccoli do things in RAM? (ramdisk style?) idk if Windows has anything like that, but the best I/O is the I/O that isn't needed :partying_face:

**Comment by ef4** [comment]
Per recent ember-cli core team meeting: the path forward for this is the embroider side. The way to avoid broccoli's I/O cost is to keep moving everything into v2 addons. And Embroider is going to support delegating watching to the general-purpose javascript packager.
