### ISSUE TITLE
Tweak Node LTS warning when using recent active LTS

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#9783]
At the moment, when you are using the most-recent Node active LTS, but that LTS came out after the ember-cli you are using, you get this annoying error:

```
WARNING: Node v16.13.2 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
```

A suggestion given at the meeting was to instead link to the place that lists which versions of Node your ember-cli _was_ tested against.

**Comment by gnclmorais** [comment]
Doesn’t https://git.io/v7S5n already point to that?
![image](https://user-images.githubusercontent.com/385232/159119626-ac8b9a85-2ceb-4297-8fe4-c2b3cf693631.png)

**Comment by locks** [comment]
The list is kind of the reverse, it tells you which CLI versions work for each node.js version.
