### ISSUE TITLE
.ember-cli page does not document all options

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9791]
https://cli.emberjs.com/release/appendix/configuration/

at the time of writing, it only lists:
```
  "liveReload": false,
  "disableAnalytics": false,
  "port": 8080,
  "proxy": "http://localhost:3000"
```  

I _know_ there are at least 4 more options, but I forget what they're called :sweat_smile:

**Comment by bertdeblock** [comment]
I was thinking, it might also be nice if we could provide autocomplete for `.ember-cli` somehow?

**Comment by NullVoxPopuli** [comment]
@lifeart's ELS could do that, perhaps?

**Comment by lifeart** [comment]
@NullVoxPopuli yes, it's possible

**Comment by locks** [comment]
@NullVoxPopuli I'm not sure what the action item here is? Changes to the CLI guides should be filed at the [CLI Guides](https://github.com/ember-learn/cli-guides/) repository.
Given that the content of `.ember-cli` is forwarded to every `ember` call, what should we document?

It's not possible to transfer across organizations, so I have to close this issue 🙏

**Comment by NullVoxPopuli** [comment]
I did not know there was a cli-guides repo 😅
