### ISSUE TITLE
Remove/deprecate old `deprecate` utility?

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9792]
A new one was added here: https://github.com/ember-cli/ember-cli/pull/9731.

Should we remove/deprecate the [old one](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/deprecate.js)?

**Comment by rwjblue** [comment]
Does anyone outside of ember-cli use it? If not, lets just remove the older one; if they do we can update it to emit a deprecation itself (using the new infrastructure) and then have it **call** the new method (e.g. making it a wrapper around the newer utility).

**Comment by bertdeblock** [comment]
The only somewhat active addon that uses this is [ember-cli-memory-leak-detector](https://github.com/steveszc/ember-cli-memory-leak-detector).
I made https://github.com/steveszc/ember-cli-memory-leak-detector/pull/50 to resolve this.
We need https://github.com/ember-cli/ember-cli/pull/9899 and https://github.com/ember-cli/ember-cli/pull/9902 merged first as well.
