### ISSUE TITLE
Dependency `isbinaryfile` dropped node 12 in patch release

### ISSUE THREAD

**Issue by gilest** [ember-cli/ember-cli#9828]
Node support of `isbinaryfile` updated to `>= 14` in [this commit](https://github.com/gjtorikian/isBinaryFile/commit/3c4f558a4cd7a4171471f464f72547bdc4608e7e) has been released in `4.0.9`.

This is a problem because `ember-cli` supports node 12 and depends on `"isbinaryfile": "^4.0.8"`.

**Comment by dmtask** [comment]
Yeah, my Project is broken.... Please merge this and release a update. :)

**Comment by dominicroessner** [comment]
Will this be applied to older versions of the ember-cli? We’re on 3.22.0.

**Comment by Windvis** [comment]
Wait.. Shouldn't this just be fixed on the `isbinaryfile` side? It seems weird to pin that version here instead of rolling that change back and releasing a major instead over there?

You can just uses overrides / resolutions in the meanwhile if this is breaking your builds.

**Comment by gilest** [comment]
> Wait.. Shouldn't this just be fixed on the isbinaryfile side? It seems weird to pin that version here instead of rolling that change back and releasing a major instead over there?

Yes but I wasn't confident we'd be able to get that to happen. Looks like they backed down and released `4.0.10` 😅
