### ISSUE TITLE
Having an option to specify ci mode for ember test

### ISSUE THREAD

**Issue by smk1992** [ember-cli/ember-cli#9840]
It would be convenient to have an option such as `ci` with values `true|false` to specify whether testem should launch in ci or launch in dev. Right now it appears to always be running in CI mode based on code in `lib/tasks/test.js:Ln18`.

<img width="1367" alt="CleanShot 2022-04-05 at 17 16 41@2x" src="https://user-images.githubusercontent.com/4854072/161850702-425d6647-90ca-4f0d-b4e5-982e31788e41.png">

If I'm wrong please do let me know what is the correct way to run launch in dev.

Thanks

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.24.0
http_parser: 2.9.3
node: 10.19.0
v8: 6.8.275.32-node.55
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 5
openssl: 1.1.1d
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019c
os: darwin x64
6.13.4
1.22.4
```

**Comment by bertdeblock** [comment]
@smk1992 Is it `ember test --server` that you are looking for?
That should call `testem.startDev` instead of `testem.startCI` if I'm not mistaken.

**Comment by smk1992** [comment]
> @smk1992 Is it `ember test --server` that you are looking for? That should call `testem.startDev` instead of `testem.startCI` if I'm not mistaken.

Ah gotcha missed that. Mb 😅 , didn't realize there was a separate task (test-server.js) for running with server
