### ISSUE TITLE
Remove automatic integration of jQuery into Ember

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9874]
This happens here:
https://github.com/ember-cli/ember-cli/blob/177f52340dcaa59cf27402ed77fda5e55860fd35/lib/broccoli/ember-app.js#L558-L579
It seems this was supposed to be removed in v4.

**Comment by rwjblue** [comment]
This is talking about ember version, **not** ember-cli version. While I think it could be done, I think it makes things a bit more difficult (e.g. supporting older ember-source versions throughout their corresponding supported ember-cli version range).

I'd rather deprecate *all* of the "vendor files" that we do there for 5.0.0.

**Comment by bertdeblock** [comment]
Closed by #10195.
