### ISSUE TITLE
Remove support for finding an addon by its unscoped name

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9878]
This happens here:

https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/find-addon-by-name.js#L55-L64

Seems to have been deprecated a while ago.

**Comment by rwjblue** [comment]
Can you double check what version that deprecation landed in? Assuming it was < 4.0.0, we can remove support.

**Comment by bertdeblock** [comment]
@rwjblue This landed in v3.4.0, so seems okay to remove I'd say?
