### ISSUE TITLE
Remove `.eslintrc.js` and `.jshintrc` from `server` blueprint

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9881]
- `.eslintrc.js` is not needed, because this is already covered in the main `.eslintrc.js` file: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.eslintrc.js#L36
- `.jshintrc` seems like a remnant from when `ember-cli-jshint` was still a thing?

**Comment by rwjblue** [comment]
Ya, seems good to me, but we should ensure that we add `server/` to the "node files" section in the top level `.eslintrc.js` file.
