### ISSUE TITLE
Remove support for `ember-cli-jshint`?

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9882]
`ember-cli-jshint` was removed a long time ago, but it seems we still have a few parts in the codebase that have checks for this:

https://github.com/ember-cli/ember-cli/blob/b24b73b388934796ca915ca665b48a27c857199b/blueprints/blueprint/index.js#L6-L20

https://github.com/ember-cli/ember-cli/blob/b24b73b388934796ca915ca665b48a27c857199b/blueprints/server/index.js#L30-L38

**Comment by rwjblue** [comment]
We should issue a deprecation if we hit this code path (until: 5.0.0)
