### ISSUE TITLE
Remove `vendor-shim` blueprint?

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9883]
I'm not 100% sure, but this seems a remnant from the pre `ember-auto-import` era?

**Comment by SergeAstapov** [comment]
@bertdeblock yes, it's was somewhat common in many years ago (side-note it was "fun" to do)

I wonder if we need RFC for that or ✂️ right away.

**Comment by rwjblue** [comment]
@bertdeblock - Let's deprecate it, and enqueue for removal at 5.0.0 at least
