### ISSUE TITLE
Drop support for Node v12

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9893]
Node v12 is EOL since 2022-04-30, which means we should be able to drop support according to [our Node support doc](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md).
Is this something we can do right away or do we need to do other things first before we can drop support here?

**Comment by locks** [comment]
I think the team might wait for an LTS sometimes, which would mean that v12 can be dropped as master is 4.6, right?
