### ISSUE TITLE
Links in new app screen broken

### ISSUE THREAD

**Issue by givensuman** [ember-cli/ember-cli#9918]
The `Quick Start` and `Ember Guides` links lead to a broken Netlify page. URLs are also different from working Ember site:

`broken`: https://guides.emberjs.com/v4.4.0/getting-started/quick-start/
`working`: https://guides.emberjs.com/release/getting-started/quick-start/
![ember](https://user-images.githubusercontent.com/16063606/170356835-96380c59-9a6d-44d1-9ce1-dc32d441b55e.PNG)

Opening in case it's not just a case of servers being down.

---

Output from `ember version --verbose && npm --version && yarn --version`:

```
ember-cli: 4.4.0
node: 14.17.6
v8: 8.4.371.23-node.76
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: win32 x64
6.14.15
1.22.10
```

**Comment by bertdeblock** [comment]
I think that's because Ember v4.4.0 hasn't been "officially" released yet. As in, no blog post announcing the new version has been published yet and the guides haven't been updated yet to include v4.4.0. Once that's the case, the link should work.

**Comment by bertdeblock** [comment]
The guides for v4.4.0 have been added and the link now works. Thanks for reporting!
