### ISSUE TITLE
Add --pnpm flag like we have --yarn?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9924]
using ember-cli 4.4, i noticed `ember install` supports pnpm, but `ember new` does not.

`ember new --help` shows a `--yarn` flag, but now `--pnpm`

default install is with `npm`, which.. I don't want :upside_down_face:

**Comment by bertdeblock** [comment]
Created a related ticket here https://github.com/ember-cli/ember-cli/issues/9879.

**Comment by rwjblue** [comment]
Closing in favor of #9879
