### ISSUE TITLE
ember install does not work with generic packages

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9925]
ember-cli 4.4

I tried to run `ember install @glint/core` and got an error:
```
Install failed. Could not find addon with name: @glint/core
```
```
❯ ember install @glint/core @glint/config @glint/environment-ember-loose @glint/environment-ember-template-imports
```

This works, however:
```
❯ pnpm add --save-dev @glint/core @glint/config @glint/environment-ember-loose @glint/environment-ember-template-imports
```

**Comment by bertdeblock** [comment]
I'm guessing initially, `ember install` wasn't designed to work with plain packages?
I guess the question is, do we want it to support plain packages?

**Comment by locks** [comment]
Why would it support plain packages?

**Comment by bertdeblock** [comment]
I can imagine people would find it convenient to do `ember install ember-addon normal-package` in one go, but personally, I would prefer to not overload `ember install` and only have it support installing Ember addons.

**Comment by bertdeblock** [comment]
Going to close this for now if that's okay. `ember install` was designed for installing addons and automatically running their default blueprint afterwards. I think it's best we keep it that way and have users install plain packages using their preferred package manager.
