### ISSUE TITLE
Addon generator should list ember-auto-import under dependencies, not devDependencies

### ISSUE THREAD

**Issue by raycohen** [ember-cli/ember-cli#9940]
Newly generated *addons* are being created with ember-auto-import under devDependencies:

https://github.com/ember-cli/ember-addon-output/blob/master/package.json#L40

From the EAI [readme](https://github.com/ef4/ember-auto-import#installing-ember-auto-import-in-an-addon)

> To add ember-auto-import to your addon:
> add ember-auto-import to your dependencies, not your devDependencies, so it will be present when your addon is used by apps

**Comment by raycohen** [comment]
Does a freshly generated addon need ember-auto-import at all if it isn't importing any non-addon packages?

**Comment by bertdeblock** [comment]
Yes, it's required for using `ember-source` v4 in the dummy app. That requirement was part of the v4 release as `ember-source` will become a v2 addon somewhere in the v4 cycle.

**Comment by bertdeblock** [comment]
> a normal (non-addon) npm package.

This part wasn't super clear / accurate. It's also needed to consume v2 addons. Sorry for the confusion.

**Comment by bertdeblock** [comment]
I'm going to close this if that's okay.
I think having `ember-auto-import` in `devDependencies` for new addons is the right thing at the moment.
