### ISSUE TITLE
ember-cli keeps rebuilding images for no reason

### ISSUE THREAD

**Issue by Benjy1979** [ember-cli/ember-cli#9949]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---
Hi,

When ember serve is running and you're browsing the app you have made, ember-cli keeps rebuilding itself because it thinks an image has changed just because it is being read. Constantly. You spend all your time waiting and waiting for image after image to cause a rebuild. This isn't a hard thing to reproduce because it's been happening on separate machines on Windows 10, in fact the only machines I ever run it on.
How can I fix this, other people must be getting it!

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.28.4
node: 14.19.3
v8: 8.4.371.23-node.87
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.4
openssl: 1.1.1o
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
os: win32 x64

(base) PS D:\dev\articad\websites\ember-roomviewer-smiles> npm --version
6.14.5
(base) PS D:\dev\articad\websites\ember-roomviewer-smiles> yarn --version
1.22.15

```

**Comment by bertdeblock** [comment]
Is this happening for a completely new Ember app as well?

**Comment by Benjy1979** [comment]
I will try it this evening.Thanks

**Comment by bertdeblock** [comment]
@Benjy1979 Any update on a reproduction?

**Comment by Benjy1979** [comment]
> @Benjy1979 Any update on a reproduction?

Hi, 
 I'm not sure how that will help me if there is no issue on a new project. 
The project it is working on is quite big. Have you seen this issue before if so what was the cause.  Maybe I can just cut to the chase with it if you know of possibly causes?

**Comment by bertdeblock** [comment]
If this issue doesn't occur in a newly generated project, then this issue might be with your project itself.
Maybe something else is triggering updates on these images? An addon or an IDE extension or something?

**Comment by Benjy1979** [comment]
It happens on Edge AND chrome. It also happens on all the projects though admittedly they are all similar projects.
Ok let me try a new project right now.

**Comment by Benjy1979** [comment]
Hi, it's not happening with a new project. You might as well close the ticket I can't make head or tail of it. I'll just have to build an empty project up again. If I make light of it I'll submit another ticket. Thanks.

**Comment by bertdeblock** [comment]
Thanks for checking @Benjy1979.
