### ISSUE TITLE
Peer violation from testem -> consolidate -> mustache

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9968]
```
frontend
└─┬ ember-cli
  └─┬ testem
    └─┬ consolidate
      └── ✕ unmet peer mustache@^3.0.0: found 4.2.0
```

occurred on this pr: https://github.com/NullVoxPopuli/limber/pull/521 -- which is likely unrelated (directly) and more an effect of lockfiles being loosey goosey.

I _think_ the solution here is for consolidate to widen their peer range

**Comment by bertdeblock** [comment]
AFAICT, the latest version of `consolidate` has a peer dep on `mustache@^4.0.1`.
`testem` uses the latest version of `consolidate` and also has `mustache@^4.2.0` as a dependency, which should satisfy `consolidate`'s peer dep. Am I missing something?
I'm not really sure what needs to be done on `ember-cli`'s side.

**Comment by NullVoxPopuli** [comment]
it looks like, because I have testem-failure-only-reporter, my testem version is 3.6.0 (latest is 3.8.0).

> I'm not really sure what needs to be done on ember-cli's side.

Looks like nothing?, but due to the reported dep tree -- this is more for SEO purposes.
Buuut, this is owned by the emberjs org; https://github.com/emberjs/testem-failure-only-reporter

**Comment by NullVoxPopuli** [comment]
I opened https://github.com/emberjs/testem-failure-only-reporter/pull/13 to resolve

**Comment by NullVoxPopuli** [comment]
Oh more context:

```
❯ pnpm why testem
limber@0.0.0 /home/nullvoxpopuli/Development/NullVoxPopuli/limber/frontend

devDependencies:
ember-cli 4.4.0
└── testem 3.6.0
ember-cli-dependency-checker 3.3.1
└─┬ ember-cli 4.4.0 peer
  └── testem 3.6.0
testem-failure-only-reporter 1.0.0
└── testem 3.6.0
```

and after looking at the failure-only-reporter (they use caret) and ember-cli (also caret).
The issue was solely within my lockfile this whole time. :upside_down_face:

**Comment by NullVoxPopuli** [comment]
To resolve:

(the bruteforce way)
```
rm pnpm-lock.yaml
# delete all node_modules, recursively
find . -name 'node_modules' -type d -prune -exec rm -rf '{}' + \
# re-install
pnpm install
❯ pnpm why testem
Legend: production dependency, optional only, dev only

limber@0.0.0 /home/nullvoxpopuli/Development/NullVoxPopuli/limber/frontend

devDependencies:
ember-cli 4.4.0
└── testem 3.8.0
ember-cli-dependency-checker 3.3.1
└─┬ ember-cli 4.4.0 peer
  └── testem 3.8.0
testem-failure-only-reporter 1.0.0
└── testem 3.8.0

❯ pnpm why mustache
Legend: production dependency, optional only, dev only

limber@0.0.0 /home/nullvoxpopuli/Development/NullVoxPopuli/limber/frontend

devDependencies:
ember-cli 4.4.0
└─┬ testem 3.8.0
  ├─┬ consolidate 0.16.0
  │ └── mustache 4.2.0 peer
  └── mustache 4.2.0
ember-cli-dependency-checker 3.3.1
└─┬ ember-cli 4.4.0 peer
  └─┬ testem 3.8.0
    ├─┬ consolidate 0.16.0
    │ └── mustache 4.2.0 peer
    └── mustache 4.2.0
testem-failure-only-reporter 1.0.0
└─┬ testem 3.8.0
  ├─┬ consolidate 0.16.0
  │ └── mustache 4.2.0 peer
  └── mustache 4.2.0



🎉🎉🎉
```
