### ISSUE TITLE
[Feature Request] Default workspace settings for Visual Studio Code

### ISSUE THREAD

**Issue by kaermorchen** [ember-cli/ember-cli#9986]
👋 Hi!

I had created a new [RFC](https://github.com/kaermorchen/rfcs/blob/default-workspace-settings/text/0000-default-workspace-settings.md), it is not published right now.

The RFC adds the default workspace settings for Visual Studio Code. Is it make sense?

I also have the PR #9985, which has a simple implementation. But I had broken a lot of another tests 🤦‍♂️. Maybe I will need some help for to fix it.

**Comment by bertdeblock** [comment]
Hi @kaermorchen, thanks for opening this issue. Since you intend on opening an RFC PR, I think we can close this one for now. The RFC PR would definitely be a better way for gathering community feedback instead of an issue here.
