### ISSUE TITLE
Find a path to updating ember-cli-preprocess-registry

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-cli#9993]
Some years ago [ember-cli-preprocess-registry](https://github.com/ember-cli/ember-cli-preprocess-registry) had a v4.0 including various updates and a [few breaking changes including removing the built-in default minifyCSS plugin](https://github.com/ember-cli/ember-cli-preprocess-registry/pull/22). Unfortunately, it was determined that because of the way ember-cli passes through to the addon, this was a breaking change in ember-cli as well, and [4.0 was unpublished](https://github.com/ember-cli/ember-cli-preprocess-registry/issues/50). 

Today the version of `ember-cli-preprocess-registry` that is a dependency of `ember-cli` is v3.3.0. This version uses `broccoli-clean-css` v1.1 which uses `clean-css-promise` v0.1 which uses `clean-css` v3.4 which has a security warning (https://github.com/ember-cli/ember-cli-preprocess-registry/issues/62, #8579).

An existing ember-cli issue https://github.com/ember-cli/ember-cli/issues/8457 addresses removing implicit CSS minification. 

Other related issues: https://github.com/ember-cli/ember-cli-preprocess-registry/issues/71

**Comment by SergeAstapov** [comment]
@kategengler thanks for helping push this through!

Looks like v5 of `ember-cli-preprocess-registry` got published https://github.com/ember-cli/ember-cli-preprocess-registry/releases/tag/v5.0.0 

looks like this is now being worked in https://github.com/ember-cli/ember-cli/pull/10244

**Comment by kategengler** [comment]
#10244 has now merged to beta.
